### ISSUE TITLE
[Date Input] calendar widget hide/show behavior is buggy

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1000]
Reproducible on openmct master and in VISTA (with some custom config to make calendar picker available).  Easiest way to get a time conductor is to use the [demo site](https://openmct-demo.herokuapp.com/) and navigate to the mars weather display layout.

### Does not dismiss when date is selected:
1. Click calendar icon to trigger calendar widget
2. select a date in calendar widget

Expected outcome: calendar widget should disappear, date should update.
Actual outcome: calendar widget does not disappear, date updates.

### does not dismiss when clicking toggle button
1. Click calendar icon to trigger calendar widget
2. click calendar icon again to dismiss widget

expected outcome: calendar widget should disappear when clicking to dismiss.
actual outcome: calendar widget does not disappear when clicking to dismiss.

### toggle button click target is smaller than indicated by styles.
1. hover over grey button-like border around calendar icon.  Note that cursor appears as a pointer.
2. click.

Expected outcome: calendar picker will hide/show.
Actual outcome: calendar picker does not hide/show.

**Comment by larkin** [comment]
Since clicking to select a date doesn't cause the box to dismiss, weird things happen.  Also, it seems that the clickawaycontroller no longer triggers a digest (this is present in master, not in live demo), so selecting a date and then clicking on something that would trigger a digest (e.g. selecting an item from the tree) doesn't actually cause the date selection to take effect.  It's super buggy.

**Comment by larkin** [comment]
Bumping to kress for triage; the calendar inputs are a pain in the butt now-- almost unusable.

**Comment by VWoeltjen** [comment]
Sounds like an issue we should take care of in this sprint, seems very detrimental to TC usability. I've self-assigned, but @akhenry, if you're still feeling light, feel free to take this from me

**Comment by akhenry** [comment]
* [x] Does not dismiss when date is selected
* [ ] Does not dismiss when clicking toggle button
* [ ] Toggle button click target is smaller than indicated by styles

**Comment by akhenry** [comment]
* [x] Does not dismiss when date is selected
* [ ] Does not dismiss when clicking toggle button
* [ ] Toggle button click target is smaller than indicated by styles

**Comment by charlesh88** [comment]
I'll take a look at the "click target is smaller..." aspect of this.

**Comment by charlesh88** [comment]
The version of the TC on demo is now behind what's in master; we should not be evaluating against that version. Better is to use master, and just add the conductor bundle manually to main.js.

**Comment by charlesh88** [comment]
Testathon 2016-06-16
Could not verify, calendar widget not enabled.

**Comment by VWoeltjen** [comment]
Verified testathon 2016/06/16 (for all three cases in bold of original issue)
