### ISSUE TITLE
[time-conductor] bounds slider gets stuck to mouse

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1001]
I don't have a reproduction for this, it just happens to me once or twice every demo.  When dragging the time conductor start or end, sometimes it continues to follow my cursor after i stop dragging it.  It's not following it exactly the same, it's like a slow laggy update rate.  Have to click it and redrag it to stop it from continuously following the mouse.

**Comment by charlesh88** [comment]
This UI has been removed, closing.
