### ISSUE TITLE
[Time Conductor] Time Conductor bounds can overrun screen.

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1003]
While looking into #1000 I managed to get the time conductor into a right old state -

![screen shot 2016-06-08 at 13 55 05](https://cloud.githubusercontent.com/assets/4215777/15894961/a8629a10-2d80-11e6-845d-7a7f95b9e08e.png)

To reproduce this:
1) select an end date that is earlier than the start
2) change the end date to one that is after the start date
3) change end again to be earlier than start
4) finally, change end to be after the start date. Conductor will extend out to the far left of the screen.

Observed in master

**Comment by akhenry** [comment]
It appears that what's happening here is that the inner bounds can exceed the outer bounds. Then when the percentages are calculated for the inner bounds (https://github.com/nasa/openmct/blob/master/platform/commonUI/general/src/controllers/TimeRangeController.js#L132) it ends up with a weird negative number. This is then used for left and right values for the sliders in the template.

**Comment by charlesh88** [comment]
Wow, you broke the hell out of that thing.

**Comment by VWoeltjen** [comment]
Not a high priority, as TC will be changed soon, and user has a workaround (enter valid times). But a quick-fix would be reasonable.

**Comment by akhenry** [comment]
Will be replaced by Time Conductor v2
