### ISSUE TITLE
[Composition] Drag-drop composition was not working during webex demo

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1011]
During a demo, drag and drop composition failed to work with plots and display layouts. Appeared to affect multiple plot or display layout and was not confined to a particular one. Also tried reloading the page, to no effect. Demo was in Chrome 51.

Composition worked as expected after disconnecting from web ex and projector.

Cause is unknown, but only occurred while on webex and projecting. Will try and isolate each of these potential causes to see which is responsible.

**Comment by charlesh88** [comment]
Wonder if this DnD to initiate editing, or all DnD even when Edit mode is enabled.

**Comment by larkin** [comment]
I believe this is resolved.  Unsure what caused it, but we've been done 10-20 webex demos recently without seeing anything like this.
