### ISSUE TITLE
[Tables] Table row border misaligned in some columns in VISTA

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1012]
A table showing sol, with no sol data showed a border that was misaligned with neighboring cells.

Could potentially be due to the object not producing sol data.

**Comment by VWoeltjen** [comment]
Able to reproduce fairly easily in open source with Sine Wave Generator by returning `undefined` from SineWaveTelemetrySeries.getRangeValue

**Comment by akhenry** [comment]
Am closing and marking unverified so that we can determine if this is still an issue.
