### ISSUE TITLE
Action button colors messed up in Snow theme

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1014]
Very probably a regression error from recent changes to for #973. Check all buttons in the Snow theme, and double-check buttons in Espresso.

**Comment by larkin** [comment]
reproduced in 2016-06-16 testathon, also visible in plot action icons:

![screen shot 2016-06-16 at 3 44 09 pm](https://cloud.githubusercontent.com/assets/226503/16135552/3507fede-33d9-11e6-8ed4-7e16aa10c312.png)

![screen shot 2016-06-16 at 3 44 14 pm](https://cloud.githubusercontent.com/assets/226503/16135560/386585e2-33d9-11e6-9831-7e82ea5bd84d.png)

**Comment by charlesh88** [comment]
This will have to be verified in VISTA, as WARP doesn't use the Snow theme.

**Comment by VWoeltjen** [comment]
Verified-_ish_ during testathon 6/20/2016, by changing included CSS from espresso to snow using Elements tab of Chrome Dev tools.

![screen shot 2016-06-20 at 3 29 31 pm](https://cloud.githubusercontent.com/assets/1685764/16212420/4e892e34-36fc-11e6-8dac-97689f950af8.png)

Not the same as verifying in VISTA, but it does appear this is addressed.

**Comment by charlesh88** [comment]
Testathon 2016-06-20: verified sort-of fixed in local build of open, having manually changed to the Snow theme in main.js. That said, the Edit button is not being emphasized per desire. What's confusing is Victor's screenshot, which isn't what I see but *is* what I wanted.

**Comment by charlesh88** [comment]
Mystery solved: the edit button can have `.key-edit` or `.key-properties` depending on current object type. CSS only handling `.key-edit` right now.

**Comment by charlesh88** [comment]
Testathon 2016-06-23
Fix for `.key-properties` isn't working. Looking at rendered theme-espresso.css, I don't see a definition at all for .key-properties. Are we sure the running test rebuilt the CSS?

**Comment by charlesh88** [comment]
Testathon 2016-06-23
Verified fixed on rebuilt testathon. Woot!
