### ISSUE TITLE
[Timeline] Add menu in edit Timeline is being clipped

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1019]
See during Testathon 2016-06-16: the Add menu while editing a Timeline is being clipped because `<mct-toolbar name="mctToolbar" structure="toolbar.structure" ng-model="toolbar.state" class="flex-elem grows ng-pristine ng-untouched ng-valid ng-isolate-scope">` is set to overflow: hidden. 

![screen shot 2016-06-16 at 2 10 03 pm](https://cloud.githubusercontent.com/assets/1056412/16133329/14fae00a-33cc-11e6-9031-bc86eeb31215.png)

**Comment by VWoeltjen** [comment]
Could this be related to style changes for animating into Edit mode (#987)?

Since this interferes with timeline-building, I think this should be classified as a release blocker

**Comment by akhenry** [comment]
There is a workaround - you can create activities via the create button, but it's not great.

**Comment by VWoeltjen** [comment]
Verified in testathon 6/20/2016; menu is no longer clipped

**Comment by charlesh88** [comment]
To verify: 

1. Edit a Timeline.
1. Click the Add button.
1. If you see the Add menu, the bug is fixed.

**Comment by charlesh88** [comment]
Testathon 2016-06-20: verified fixed.
