### ISSUE TITLE
Stacked plots can be squished into nothingness

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1020]
Too many stacked plots on screen can result in them being squished into nothingness.  On an iPhone, they're basically unusable.

Currently their height is a percentage of their parent container.  Adding `min-height: 200px` allows them to resize but guarantees that they stay visible when smaller by forcing the parent container to scroll instead of squishing them to nothing.

observed some time ago, reporting in testathon 2016-06-16.

**Comment by VWoeltjen** [comment]
> Adding `min-height: 200px` allows them to resize but guarantees that they stay visible when smaller by forcing the parent container to scroll instead of squishing them to nothing.

👍

**Comment by larkin** [comment]
@charlesh88 has reported this in #1022 and included more detail, going to close this as duplicate.

**Comment by VWoeltjen** [comment]
Verified testathon 6-23-2016
