### ISSUE TITLE
Triggering edit mode should expand the inspector

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1031]
1. Open the application
2. Collapse the inspector pane
3. Create a new display layout (or any other object w/ edit mode)

Expected behavior: the inspector pane becomes visible
Actual behavior: the inspector pane stays hidden.

When the users starts editing an object, the inspector should become visible if it is not already visible.  Otherwise it is very unclear to the user how to do certain editing actions.

**Comment by larkin** [comment]
@akhenry as the most knowledgable person when it comes to edit mode; is there a trivial fix for this that we could demo early?  I have some end users performing a demo of the application and this is one of the bugs they would like to see fixed; as the frequently browse with the inspector collapsed and this has been confusing for them when they start editing.

We don't need to merge and deliver within Kress; I can build from a branch for demonstration purposes.

**Comment by akhenry** [comment]
@larkin A quick fix is trivial. Doing it properly without polluting browse code with edit stuff might take a little while.

**Comment by larkin** [comment]
@akhenry a quick fix on a branch for demo purposes (not for integration) with a plan for a longer term solution would be fine for the current time frame.

**Comment by charlesh88** [comment]
Is there a path where we could get something that's not heinous into the main branch? This is highly desirable. What if edit mode just showed the Inspector always, and we didn't worry about remembering if the Inspector was hidden or not while browsing?

**Comment by akhenry** [comment]
@charlesh88 Fix is inbound. Open to the option of also just forcing inspector visible in edit mode.

**Comment by larkin** [comment]
Note to testers: see original comment for reproduction steps and expected behavior.

**Comment by charlesh88** [comment]
Testathon 2016-07-18 Verified fixed

**Comment by VWoeltjen** [comment]
Verified in VISTA, testathon 2016-07-18

**Comment by larkin** [comment]
verified testathon 2016-07-18

**Comment by charlesh88** [comment]
Looks like this should have had "unverified" removed after the 7/18 testathon; doing so now.
