### ISSUE TITLE
Some JSHint errors found

### ISSUE THREAD

**Issue by jesusprubio** [nasa/openmct#1035]
Some errors are thrown trying to validate the code style and good practices. To reproduce it:

``` sh
npm run jshint
```

<img width="799" alt="captura de pantalla 2016-06-20 a las 21 13 22" src="https://cloud.githubusercontent.com/assets/2753855/16207338/df34f2f8-372c-11e6-930b-0f4b60087f8a.png">
<img width="755" alt="captura de pantalla 2016-06-20 a las 21 17 12" src="https://cloud.githubusercontent.com/assets/2753855/16207339/df359190-372c-11e6-8cd8-060aadeb299e.png">

We only need to add some [environments](http://jshint.com/docs/options/#environments) to the ".eslintrc" file and remove some unused JSHint existent exceptions to solve it. I'm making a PR to solve it.

**Comment by VWoeltjen** [comment]
Thanks for filing this - I believe this broke when we switched to a gulp-based build. The `jasmine` environment is specified for specs as part of the `gulp lint` task

Think the easy fix is to update the `jshint` task to run `gulp lint` (or just remove the `jshint` task from package.json)

**Comment by akhenry** [comment]
Assigned to @jesusprubio

**Comment by jesusprubio** [comment]
I like it, but the only "problem" I can see with this solution is that most of the IDEs (like Atom) plugins rely in the ".eslintrc" file. What do you think? BTW, of course I could live with the solution you've proposed. :)

**Comment by larkin** [comment]
We use jshint (and `.jshintrc` respectively)-- so if your editor picks up those files it should be good to go.  That said, those don't declare the `jasmine` environment thus you see the errors above.  

I think we should add the `jasmine` environment to our jshintrc file-- I don't see a good reason why we need to restrict it to tests only.  Would simplify things.  @akhenry @VWoeltjen thoughts?

We should also clean up our npm commands and add some documentation to the README to cover what we use npm for vs what we use gulp for.

**Comment by jesusprubio** [comment]
My fault, I meant ".jshintrc" not ".eslintrc" (I've updated my comment). I'll wait for the rest of the team response then. Thanks :)

**Comment by VWoeltjen** [comment]
> I like it, but the only "problem" I can see with this solution is that most of the IDEs (like Atom) plugins rely in the ".eslintrc" file. What do you think? BTW, of course I could live with the solution you've proposed. :)

I think this is a good consideration, having consistent configuration between IDE and build would be useful. 

>  I think we should add the `jasmine` environment to our jshintrc file-- I don't see a good reason why we need to restrict it to tests only.  Would simplify things.  @akhenry @VWoeltjen thoughts?

Good point. Using jasmine API from non-tests would be "wrong," but I don't think we need ongoing automated help to avoid doing that (I would expect it to cause other things to visibly break, in any event, if for some bizarre reason this happens)
