### ISSUE TITLE
New tab link broken?

### ISSUE THREAD

**Issue by RCarvalhoNASA** [nasa/openmct#1038]
Was trying to open some layouts in new tabs.  I opened one, and then after that, other ones came up with the following error:

Service Temporarily Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

**Comment by VWoeltjen** [comment]
Investigated this, found that the process which serves the client had stopped running (the same Service Temporarily Unavailable could be seen trying to load the app directly.) Not sure why; filed https://developer.nasa.gov/ResourceProspector/warp/issues/186 for investigation. 

Closing this issue, as this is now covered by an issue in the closed-source tracker.

**Comment by VWoeltjen** [comment]
Verified that Open in New Tab is working in testathon 6-23-2016, including when used repeatedly and from previously-opened tabs. This is consistent with expectations based on previous comment; still need to verify resolution of that issue (via long-duration test)
