### ISSUE TITLE
Real-Time Table not locking scroll to bottom in order to display latest data

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1040]
Testathon 2016-06-20.
First observed with #1039. The current implementation of the RT table is not automatically locking its scroll to the bottom and displaying the latest incoming data as intended; instead, the scroll handle stays at the top and the latest data is hidden. Manually scrolling the scroll handle will cause it to lock, but that's not a solution to this problem. As data is hidden, this is a blocker.

**Comment by VWoeltjen** [comment]
Related to #1039 (RT Telemetry Default Order), if default order was to insert at top instead of bottom, would this still be a blocker?

**Comment by akhenry** [comment]
Issue is actually by (possibly misunderstood) design. autoscroll behavior is only being applied to text telemetry.

Easiest solution for now is to enable auto-scroll behavior for all real-time tables.

**Comment by VWoeltjen** [comment]
In the older Scrolling List views, numeric telemetry filled in from the top, and text-based telemetry had an additional view that filled in from the bottom.

Use case for the former is general monitoring; use case for the latter is for viewing server event messages, which make more sense when read top-to-bottom.

>  Easiest solution for now is to enable auto-scroll behavior for all real-time tables.

I believe this works for both use cases above, so I'd second this approach.

I think that ultimately we'll want to make this configurable, but would go for the easy solution for now.

**Comment by akhenry** [comment]
@VWoeltjen Ah, that makes sense. A quick straw poll of @RCarvalhoNASA and @costigan indicated that autoscrolling with newest values at the bottom is acceptable for now.

**Comment by akhenry** [comment]
Verified Testathon 2016-06-23

**Comment by VWoeltjen** [comment]
Verified in testathon 2016-06-23
