### ISSUE TITLE
excessive persistence errors and failure to exit edit mode

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1046]
This has been reported in VISTA and can be reproduced there; I do not yet have a openmct reproduction for this but I think it may be a conflict between multi-space persistence and VISTA.  It was first detected with a build of openmct 5 days ago, and is still present.

The basic reproduction steps in vista:

1. search for something basic (that gives you objects)
2. create new display layout
3. add some of your search results to the display layout
4. save the display layout to your user folder.

expected result: the layout should save successfully.
actual result: VISTA displays multiple persistence errors and the application does not leave edit mode.

This appears to be caused by an issue in the bleeding edge of OpenMCT, as targeting older versions of OpenMCT does not cause this to occur.

@akhenry @VWoeltjen can you try and reproduce this in the WARP CI environment?  I can't reproduce with scratchpad or localstorage and think it might require a certain amount of latency for it to occur.

I'll spend more time tomorrow trying to isolate the cause in the VISTA environment.

**Comment by VWoeltjen** [comment]
The fact that search needs to be involved is a little interesting. Maybe something to do with context (although I thought we'd gotten that fairly well-sorted for search...) Will look at reproducing this in either WARP or Open

**Comment by VWoeltjen** [comment]
Able to reproduce in WARP. Note that __Step 2__ is not mentioned in the repro steps above but appears to be necessary in WARP:

1. Search for a known packet name (e.g. RMM_STATE_DAT)
2. Navigate to that packet in search results
3. Click Create, choose Display Layout
4. Drag that packet from Search results into the display layout
5. Save (you will need to choose a folder, e.g. your user folder)

...and you get the failure to save dialog.

No errors appear on the console, but I was able to get the ID for the failed-to-save object:

```
> angular.element(document.querySelector('.t-object-label')).scope().domainObject
e {id: "warp:e559a9e6-cdc0-41ac-b1ee-7650206944be", model: Object, capabilities: Object}
```

...and it has the "warp" persistence space.

Suspect that the created object is getting the persistence space of the object selected at the time that it is created, instead of the persistence space of the object selected at the time that it is saved.

**Comment by akhenry** [comment]
Sounds suspiciously like a regression of #656, possibly introduced by NEM refactoring. Could also be an edge case that we didn't pick up at the time, although the absence of this issue in older builds suggests not.

**Comment by larkin** [comment]
Further reports from VISTA: after you fail to exit edit mode, you can click cancel twice to exit edit mode.  At this point, if you create a new object, and press save, it will never ask you for a location-- it immediately exist edit mode, and you end up with an orphaned object that you won't be able to navigate back to.

Is it possibly related to orphan-navigation-protection in https://github.com/nasa/openmct/issues/765?

**Comment by larkin** [comment]
Also: the number of failure to persist warnings is based on the number of items (perhaps modifications) that you performed before saving.  Adding one object results in 1 error notification.  Adding 4 objects results in 8 persistence errors.

**Comment by larkin** [comment]
doing something similar to git-bisect to find openmct version where this starts occurring.

**Comment by akhenry** [comment]
> Also: the number of failure to persist warnings seems to be based on the number of items (perhaps modifications) that you performed before saving. Adding one object results in 1 error notification. Adding 4 objects results in 8 persistence errors.

This might be a bug in transaction management. Transactions should only queue one persist per-object, with subsequent persist calls being ignored while a transaction is active. That is tracked per object instance though, so operations on different instances of an object could result in multiple persist calls for one object?

In the longer term, stuff like this makes me inclined to change our transaction management to use dirty model tracking instead of our present system of queuing persist function calls.

In any case, it sounds like we have more than one unrelated issue at play here.

**Comment by akhenry** [comment]
I'll see if I can reproduce the potential bug I'm describing above in open, but I suspect it's a symptom rather than the root cause of this issue.

**Comment by VWoeltjen** [comment]
Did put a breakpoint in TransactionService.commit to take a look at this. What's interesting is that its promise (a Promise.all over functions to execute on commit) resolves _before_ the 404 that occurs when trying to save the object. Not sure how to account for that behavior.

**Comment by akhenry** [comment]
Wait, there's a 404 on *save*? Is that caused by a call to `refresh`?

**Comment by akhenry** [comment]
Or is it the search indexer rearing its head again.

**Comment by larkin** [comment]
v0.10.1 does not exhibit this behavior, v0.10.2 does exhibit it.

Looking at that range of commits for possible candidates: https://github.com/nasa/openmct/compare/v0.10.1...v0.10.2?expand=1

**Comment by VWoeltjen** [comment]
> Or is it the search indexer rearing its head again.

Just tried again, and now I saw a 500 on a PUT request - definitely not search indexer in this case (although the 404 could have been)

What is strange is that the persistence space in the identifier being passed to the server looks correct in this case (my user space) but the call still fails

I'll try symlinking to my Open MCT folder to see if I can support a `git bisect` that way

**Comment by larkin** [comment]
@VWoeltjen i'm doing that for a git bisect, but having some trouble with git bisect.

I'm pretty certain it's caused by orphan-navigation-765, but the way that branch was merged is making it hard to isolate.

**Comment by larkin** [comment]
nope, not that branch.  i'm failing at git bisect right now.

**Comment by akhenry** [comment]
I have definitely identified a bug on save. I don't think it's causing the persistence failures, but it will certainly be increasing the number of persistence failures that are reported.

1. In dev tools capture network traffic
2. Create a new Display Layout
3. Drag anything into it (eg. a plot)
4. Save, selecting a location (eg. mine) and name

Expected outcome: Two OPTIONS requests, and two PUT requests. One each for the composition change to 'mine' and one each for the new layout
Observed behavior: Three OPTIONS requests, and three PUT requests. One each for the composition change to mine, one each for the new layout, and one each for an orphaned 'clone' of the layout with a different ID.

Inspecting the 'clone', the payload is identical to the layout, but with a different ID.

This behavior is not exhibited during creation of simple objects, only new objects that have nested objects (have observed with displays and tables).

**Comment by akhenry** [comment]
Could it be related to #666 ? I knew that PR would be trouble 😛

**Comment by VWoeltjen** [comment]
This is observable as far back as ffacf6e1aeb0f200733472763521fd594a2503f3 but not as far back as dcf26d386349e7e9d7bf01ffb7e3b87de7eefbc1

Bisecting is a little difficult because (at least for me?) the issue is not reliably reproducible.

**Comment by akhenry** [comment]
### Note to testers
This fix is temporary, and addresses a blocking issue in VISTA. In the process, there is a good chance that it will introduce an issue in timelines in WARP (described in discussion below from #1050). There is a followup issue #1059 to revisit this problem.

> Clearing the transaction risks clearing other stuff that we don't want to (thinking in particular of deep nesting cases like Timelines). I'm not sure if this is a problem or not, but might be worth testing.
@akhenry

> That's a good point. Clearing the whole transaction discards changes to things that weren't cloned, too. I believe the only practical case we have of this currently is in Timelines (Create Timeline, drag in an existing activity from the tree to add a link, change the Activity's name, save... the change to the Activity's name gets lost.)
@VWoeltjen

**Comment by larkin** [comment]
Can't reproduce in vista testathon  2016-07-18

**Comment by charlesh88** [comment]
Testathon 2016-07-18 
- Cannot reproduce in WARP using Victor's recipe with the RMM_STATE_DAT packet approach.
- Cannot reproduce in VISTA using Pete's original recipe.
