### ISSUE TITLE
[Style Guide] Refactor glyphs to classes

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1047]
Update font symbols and UI prior to capturing screenshots for the Style Guide.

**Comment by larkin** [comment]
Note for integration down the road: frontend-1047 should be squash-merged, many many WIP commits.

**Comment by charlesh88** [comment]
@larkin Yep, this one touches a lot of small things. Up for any suggestions about how to ease the pain of integration.

**Comment by larkin** [comment]
@charlesh88 i think we can work it out, basically no conflicts (there is one teensy easy one).  I'm advocating for a squash merge for a clean history as a note to a future integrator.

**Comment by charlesh88** [comment]
Testing notes (adding to this as I go)

- Browse everywhere and look for obviously wrong icons, or weird characters where an icon might be expected.
- Collapse pane icons have changed, please note.
- Timeline resource column indicators now display a grayed out icon when a line item has not been added to the Resource Graph. Clicking the icon should add that item to the Resource Graph, and enable the icon.

**Comment by charlesh88** [comment]
### Testing Notes
This issue did a fairly significant refactoring to convert how the application defines the way that objects use icons. 
- Browse everywhere and look for obviously wrong icons, or weird characters where an icon might be expected.
- Collapse Tree and Inspector buttons and icons have changed. Make sure they're visible and that they function.
<img width="411" alt="screen shot 2016-08-08 at 4 28 48 pm" src="https://cloud.githubusercontent.com/assets/1056412/17499814/d257f1a6-5d84-11e6-9bad-7fcbaf5e761b.png">
- Timeline resource column indicators now display a grayed out icon when a line item has not been added to the Resource Graph. Clicking the icon should add that item to the Resource Graph, and enable the icon. 
<img width="266" alt="screen shot 2016-08-08 at 4 27 20 pm" src="https://cloud.githubusercontent.com/assets/1056412/17499802/b2a5487c-5d84-11e6-8bd0-88b844930e86.png">

**Comment by akhenry** [comment]
Removing unverified label because issues addressed in specific tickets.
