### ISSUE TITLE
[Plot] squish prevention margin too large

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1048]
From a VISTA user:
> I started vista this morning and noticed there were several plots that had scroll bars at the right in the layout i had (on the main plot not the 'legend').  the only way to get rid of them was to adjust the layout to make those plots much larger than i wanted for just "awareness" plots.  not urgent, but would be nice to have the plot size height be able to be smaller without requiring scroll bars.  we can chat about it sometime later since not urgent.  just passing along.

Sounds like the min-height value is a little too large.  I'm going to sit with the end user and adjust the value to find one that works for them and report back.

**Comment by charlesh88** [comment]
I put the minimum pretty tight, but we might be able shave off a little bit.

**Comment by larkin** [comment]
From user perspective, min-height of 95 is what they desire for certain "awareness" style displays where they are really looking for visible patterns and don't need it to take up screen space.

**Comment by larkin** [comment]
Charles: based on users saying "I want to be capable of making plots this small" I propose we switch to 95px min height.  The ticks may occasionally overlap but that should be fixed at a later date with #977 or by a future request to allow users to remove ticks entirely.

**Comment by VWoeltjen** [comment]
Verified in testathon 06-23-2016. Note that plot area itself is only 31px at its smallest; labels are overlapping but semi-readable, which is consistent with height expected from issue/discussion
