### ISSUE TITLE
[Documentation] Improve readme documentation

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1053]
Assigned to @pacozaa 

The readme documentation should be updated. It should follow the lead of the website, briefly explain what OpenMCT is, and then provide clear installation instructions to get up and running. Currently it opens with a discussion about bundles, then goes into testing, and then has some confusing build instructions (npm prepublish is mentioned before npm install, which is under "Building Documentation").

The comment has been made that it should include a screenshot. I'm not convinced of the value, however our app is awful purdy, so it wouldn't do any harm.

**Comment by pacozaa** [comment]
Which directory I should use for store the picture? Can I use imgur link?

**Comment by akhenry** [comment]
@pacozaa Thanks for taking a look at this. I'll assign the task to you.

**Comment by pacozaa** [comment]
https://github.com/nasa/openmct/pull/1044

Check this out :)

**Comment by akhenry** [comment]
Issue resolved by #1044. Thanks @pacozaa !
