### ISSUE TITLE
[Edit] Revisit approach to transaction-clearing

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1059]
PR #1050 solved #1046, but #1051 looked more like the solution we wanted (based on review.) The latter did not work reliably. We should figure out why, revert changes from #1050, and implement a solution that is more coherent/maintainable for the long-term.

### Notes for Testing

These changes are primarily a refactor, so testing should be done around saving from Edit mode (and cancelling, etc.) There is one WARP bug resolved by these changes; steps to reproduce:

* Create a Timeline containing one Activity ("First Activity")
* Save this Timeline (e.g. to My Items)
* Navigate to "Packets" using the tree
* Choose Create > Timeline again
* Drag and drop "First Activity" (created above) into the Timeline area; it should appear as a link
* Right-click on "First Activity" in the Timeline and choose Edit Properties
* Change the name of "First Activity" to "Renamed Activity"
* Click Save; choose some appropriate location and hit OK

__Expected Behavior__: The Activity formerly known as "First Activity" appears as "Renamed Activity", in both places where it occurs in the tree

__Erroneous Behavior__: The Activity's name reverts to "First Activity", in both places where it occurs in the tree

**Comment by VWoeltjen** [comment]
Particularly, see notes in #1050 about timeline issues

**Comment by akhenry** [comment]
Marking as critical as would like to address prior to Le Guin testathon. If this issue manifests in WARP as expected it's likely to be a blocker.

**Comment by charlesh88** [comment]
Testathon 2016-07-18 Verified fixed
