### ISSUE TITLE
[Time Conductor] Highlight views whose bounds are different from the time conductor in real-time mode

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1076]
When a view is displaying real-time data and is zoomed, scrolled etc. in such a way that real-time data is no longer visible, this should be clearly visually indicated to the user.

**Comment by charlesh88** [comment]
@akhenry @larkin Need roughed in CSS class applied to components, somethings "s-status-timeconductor-unsynced" or something much better.

**Comment by charlesh88** [comment]
@akhenry Checking in on this: have we done any wiring on this yet?

**Comment by akhenry** [comment]
@charlesh88 Not as yet. None of the components explicitly support the time conductor per-se. It should be trivial to put a basic implementation of this into the old plot so that when you zoom in real-time mode it adds the above status.

**Comment by akhenry** [comment]
Initial implementation of this in #1089

**Comment by charlesh88** [comment]
@akhenry This needs to be applied to standalone views - such as when viewing a plot object directly - as well as frames in layouts.

**Comment by charlesh88** [comment]
Have mostly delivered on this, but leaving open for further enhancements as needed.

**Comment by charlesh88** [comment]
Once branches associated with #933 have been merged to master, this issue should be tested as part of that Testathon.

Testing notes:

1. Enable Real-time in the Time Conductor. 
1. Navigate to a telemetry view with a plot. 
1. Perform a zoom or pan (alt-left-drag) in the plot.
1. Observe: the plot area should be displayed with an orange border, and an orange alert icon should appear to the right of the object's title in the view area or in a Layout.

**Comment by larkin** [comment]
Closing to verify in testathon.

**Comment by larkin** [comment]
Will need a VISTA testathon to verify, deferring.

**Comment by charlesh88** [comment]
Testathon 11-09-2016: cannot test this.

**Comment by larkin** [comment]
Deferred to Roddenberry.

**Comment by charlesh88** [comment]
**NOTE:  Won't be testable in WARP for the Testathon 02-07-2017**

**Comment by charlesh88** [comment]
Testathon 2017/04/20 Cannot verify, TC not enabled.

**Comment by charlesh88** [comment]
Testathon 2017/04/20 Although TC not enabled, verified this functionality via marquee zoom and pan gestures in plot area. Verified fixed.

**Comment by larkin** [comment]
Time conductor is actually enabled and does allow you to see this functionality in WARP testathon.

Verified.

Created a new label to track where we should write test cases, as this is something we are likely to forget about in the future.  (there is a VISTA test case for this however).
