### ISSUE TITLE
[Tables] Reconcile real-time and historical tables

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1077]
Currently tables are implemented as two different components. These should be reconciled into a single component that shows both historical and real-time values and observes time-conductor bounds.

**Comment by akhenry** [comment]
Clearing milestone, deferring this until the new telemetry API is merged.

**Comment by larkin** [comment]
Moved to Robinson, discuss in sprint planning if we want to defer to Roddenberry.

**Comment by charlesh88** [comment]
My two cents: we need to stop deferring this, it has a significant impact for certain deployments. WARP, for example, will have both Historic and Real-time Tables. RT tables will work fine; Historic Tables won't work at all. Providing objects and views that will fail for no reason apparent to the user undermines trust in the system at a pretty fundamental level and we should try very hard to avoid this situation.

**Comment by akhenry** [comment]
@charlesh88 agreed, it's high on my priority list for similar reasons. In principle, it's totally doable for Robinson, but there may be some iterations on the telemetry API that might delay things a little beyond that. Hopefully not though.

In the worst case, they could be split into separate bundles, which would allow historical to be disabled in WARP. That would be a five minute job.

**Comment by charlesh88** [comment]
@akhenry @VWoeltjen Definitely need some testing notes here for Testathons. I only see a single Telemetry Table object in the Create menu; hoping that means this is complete.

**Comment by VWoeltjen** [comment]
Verified during testathon 2017-10-05; Telemetry Table includes both real-time and historical data
