### ISSUE TITLE
add object to new table tries to persist / causes error

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1086]
From testathon 2016-07-18, in VISTA

In VISTA:
1) create a realtime or historical telemetry table
2) drag and drop an object from the tree to the table (add it)

expected outcome: the item should be added to the table
actual outcome: the item is added to the table, a persistence failure is logged, and multiple network requests are made resulting in the object getting persisted to the server.  When you cancel editing, you are navigated to an orphaned object.

**Comment by larkin** [comment]
Somehow I've ended up with this which is quite invalid:

![screen shot 2016-07-18 at 3 46 13 pm](https://cloud.githubusercontent.com/assets/226503/16932938/baaa8b68-4cfe-11e6-9db5-74d507a2e08c.png)

**Comment by VWoeltjen** [comment]
I'm unable to reproduce this in testathon instance - think there may be a reproduction step missing? I've tried with and without a Save between steps 1 and 2

**Comment by VWoeltjen** [comment]
Also, that screenshot looks a little different from what I see in the testathon instance:

* I see this labelled as "Location", not "Object's Original" (assuming you're looking at the inspector?)
* I do not see "The root object" in the path for any objects I navigate to

Mentioning in case you're looking at a weird version (e.g. need to clear cache or something)

**Comment by larkin** [comment]
verified build version before testing & have cache explicitly disabled.  Let me experiment a bit further.

**Comment by akhenry** [comment]
If you create a new table you get the 'Object's Original' section in the inspector

**Comment by akhenry** [comment]
Unable to reproduce in WARP, apart from the "Object's Original" section mentioned above. This is an artifact of the creation process. The LocationCapability is [incorrectly identifying](https://github.com/nasa/openmct/blob/master/platform/entanglement/src/capabilities/LocationCapability.js#L118) the newly created object as a link, I think because it doesn't have context? I'll file a separate issue for this.

**Comment by larkin** [comment]
After reloading the browser I can't reproduce this specific bug on demand any more.  When it was occurring, I was able to do it repeatedly.  During that time, cancellation did not result in me receiving a "are you sure you want to discard your changes" message.

On the other hand, now when I cancel out of edit mode in a historical table and choose to discard changes the browser locks up for ~30 seconds.

**Comment by larkin** [comment]
Now I can't even reproduce that... well, perhaps I'm crazy.

**Comment by akhenry** [comment]
@larkin could it have been network? I think cancel waits for a refresh() to complete?

**Comment by larkin** [comment]
I'll try and get a minimal reproduction for something and if I can't I will close this.

**Comment by charlesh88** [comment]
Still an issue?
