### ISSUE TITLE
[Inspector] Newly created objects incorrectly identified as links in the inspector.

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1088]
1. Create a new object with an editable view, such as a table
2. The inspector contains a section normally shown for linked objects that references the object's original location.

This appears to be an artifact of the creation process. The `LocationCapability` is [incorrectly identifying](https://github.com/nasa/openmct/blob/master/platform/entanglement/src/capabilities/LocationCapability.js#L118) the newly created object as a link, I think because it doesn't have context? I'll file a separate issue for this.

**Comment by akhenry** [comment]
Discovered in the context of #1086

**Comment by charlesh88** [comment]
Can't duplicate, closing.
