### ISSUE TITLE
[New API] Synchronize models on mutation

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1094]
In the new API, objects are not synchronizing their models when mutation events occur. This needs to happen.

Moreover, new style mutation events need to trigger mutation events in the old API. This can be achieved by simply triggering topic listeners manually using string literal event name.

**Comment by VWoeltjen** [comment]
Closing this issue as it's been implemented (and defects with that implementation are tracked elsewhere, e.g. #1275 #1306 ...)
