### ISSUE TITLE
[table] remove name column, expect as property of telemetry

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1099]
The rt and historical tables currently create a `name` column which is the name of the telemetry object.  In EVRs and other data sets, this name column duplicates an existing column in the data and could be considered incorrect.

Per discussions with Victor in the VISTA repo, we're considering making `name` a property of the telemetry datum, so that it would be another column on the data instead of being a property of the object.

On the VISTA side, we've already implemented the `name` property on the datum (the server returns it for us, anyways), but to remove this column from the standard table implementation would mean that we'd have to update telemetry definitions in WARP and examples to define a `name` property.  I'm not against this.

@VWoeltjen @akhenry if we have consensus this should be a relatively easy task to do.  Assigning to Niven for discussion after which I think we can defer it to Orwell or later.

**Comment by VWoeltjen** [comment]
This approach sounds very sensible, but I'm not sure how it will interact with other views. How does plot know to ignore the `name` property, for instance?

**Comment by larkin** [comment]
@VWoeltjen How does the plot already know how to ignore this property? :)  With the latest changes to VISTA EVR metadata, the old plot would attempt to plot them.  The new plot hardcodes the list of domains, but this needs to change.

Ultimately telemetry metadata needs to provide generic hints for interpretation by views.  Currently, this is `domains` and `ranges`, which are too specific to plots.  I have a branch where these are combined, and each element has a `hints` property, an array providing hints for how views should visualize that data.  Potential values might be `'x'`, `'y'`, or integers representing general priority of the value over other values-- useful for populating columns in table views.  Can check that out when I get it tidied up.

**Comment by VWoeltjen** [comment]
Sticking it in metadata sounds good to me. I'd like something a little more specific than "hints", but I also like putting things off and that seems like something we could put off a bit.

**Comment by akhenry** [comment]
Implemented as part of #1077
