### ISSUE TITLE
[Gestures] Decouple gestures from actions

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#110]
Fully decouple "gestures" from "actions". That is, a gesture should just describe (or, more accurately, detect) certain DOM interactions, but should not particularly care which action gets fired. This should instead be decided by some intermediary that determines which action corresponds to which gesture; that intermediary should in turn by policy-controllable, such that certain bindings can be enabled/suppressed depending on device features (and whatever else turns out to be useful)

I see two approaches to this:
- Add a new `bindings` extension category that mediates between gestures and actions (and may in fact just be a simple tuple specifying gesture & action by key) and filter these by a new policy category.
- Address this solely with a new policy category; treat the `action` as the candidate and the `gesture` as the context, or similar. This, in turn, could be done by either:
  - Adding a new `gesture` policy category for this purpose
  - Adding `gesture` as an optional property of `ActionContext` which, in turn, can be used to filter out which actions should or should not be triggered by a certain gesture using the existing `action` policy. 

My preference is for the first option because it is the most explicit, but the benefit of the two variants of the second option is that they reuse existing concepts (at the cost of muddying their meanings)

**Comment by larkin** [comment]
I definitely think this decoupling is important, and there's a few levels at which it can be decoupled.  I don't particularly thing there should be a direct connection between gestures and actions.

I see a few different concepts:

**gestures**: things which handle input events and providing a cleaner interface, e.g. mct-drag, mct-pinch, etc.  At the view level, completely unrelated to "actions," a view may want to use these to implement functionality that isn't worth generalizing (pan/zoom immediately coming to mind, repositioning of elements on a layout, etc).  

**interactions**: in specific contexts, specifying available interactions is all you want to do.  For instance, any label (textual representation of a domain object) should support context menu, inspector, and infobubble actions, though the gesture that is used for each interaction depends on whether the user is on mobile or on desktop.  Adding directives such as `mct-context-menu`, `mct-infobubble`, and `mct-inspector` allows view creators to easily add this support anywhere in their view.  (Note: interactions are implemented with gestures, but don't monopolize gestures).

**actions**: these are generally things which appear inside of a context menu or as actions selectable by a user.  There are cases where actions are fired by gestures (drag and drop composition being one), but I think we should think of these as "interactions" and use the `interaction` as a method of decoupling them.

sidenote: drag-drop composition is implemented by specifying `"gestures: ["drop"]"` in a bundle.  Not very clear!

**Comment by VWoeltjen** [comment]
I like the idea of having interactions being slightly more general than the "bindings" I've described (instead of coupling gesture-to-action, couple gesture-to-some-function which may fire an action). We probably want some reusable components which simplify "just fire an action" because I think that will be the common case.

I'd like to keep gestures more semantic (or, at least, have gestures reduced to semantics somewhere); e.g. have an `info` gesture which stands in for "the user is interested in this thing". Then, use policy to decide if this is a hover or a tap (for example.) I'd rather not implement these as directives because this would make using/controlling them outside of templates (e.g. via policy) difficult. Separately, I think `mct-drag` and `mct-pinch` directives are useful to have, but I wouldn't want these to replace semantic gestures (otherwise these are just going to become new locations for if-blocks about device capabilities to build up, or directives being used for interactions will become this place.)

Lastly, the "any label should support XYZ" is probably to broad a statement to be practical. We already have cases (dialogs, for instance) where we specifically don't want these interactions to be available (except maybe for info bubbles.) We don't really have a good solution for this currently, I think this is another place where policy could be useful (whether it's about determining the applicability of the kind of gesture or the result of the gesture is a different question)

**Comment by larkin** [comment]
`mct-drag` and `mct-pinch` definitely wouldn't replace semantic gestures-- just building blocks that we build semantic gestures upon, while also giving views building blocks for implementing their own functionality-- reusable code.  

To me, it feels odd that policy would determine what gesture maps to a given interaction; I always thought policies were more focused on determining "whether or not you can do something," not "how do you do something."

As far as specific elements supporting xyz, not saying that every element MUST support them, but it should be easy for a view developer to attach existing interactions to specific elements, and directives a a really clean way to do this.  I question the need for a new framework construct when directives would work just as well.

**Comment by larkin** [comment]
Important in context of https://github.com/nasa/openmct/issues/1719, merging into that issue.
