### ISSUE TITLE
[Sub-objects] Sub-object selection

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1101]
This is a general user story for UX and UI considerations related to sub-object selection. This issue may relate to #584.

- This capability has utility in both browse and edit modes.
- Multiple selection obviously introduces additional complexity versus single selection; single selection has been identified as a logical first development effort, with us moving on to multiple selection in further dev cycles.
- Interface elements that are affected by sub-object selection are the main view, context menus, the Inspector, and toolbar buttons while in Edit mode. 
- The main view (in both browse and edit) will need to include affordances (hover styles) for objects that are capable of being selected. When a sub-object is selected, it needs to indicate that state. Ancestors of the selected sub-object need to also indicate their "secondarily selected" state to provide adequate orientation for the user.
- The Inspector needs to be modified to use a "selected" context, rather than the current one of "navigated to".

#### Single Selection
- In a single selection modality, context menus and toolbar buttons should be relatively straightforward: available actions can be determined via current mechanisms.
- The Inspector might continue to display similarly as current when an object is navigated to, but additionally, there are user requests to support special display functionality per object type. For example, select a single telemetry object in a plot by clicking its legend item, and in addition to that element's metadata (name, location, etc.) the Inspector might display the current value as an alphanumeric, as well as the min, max and average values calculated over the currently available dataset.

#### Multiple Selection
- When multiple selection is enabled, all affected interface elements as noted must handle a more complex logic in order to display and behave properly. 
- Available context actions might generally be described as the intersection set of the capabilities of the all the selected elements. This works well for actions such as "Delete..." or "Move..." where the action doesn't require choices made per action per object, but it fails with regard to an action like "Edit Properties..." in which the performance of the action for each object requires individualized attention. We may need to class actions in such a way that that kind of action would be suppressed in a multi-select context.
- The Inspector needs to handle sub-object multi-select well. We have user requests for the ability to select multiple telem elements in a plot and see the mean deviation for each selected element. We may find that we'll need to define available Inspector views based on the type of container; e.g. a Plot object allows the mean deviation view component when selecting amongst its children, but a Layout would not. Instead, a Layout might provide a component view useful during editing that displays the coordinate position and total size of the selected elements, with the ability to edit that value and move items numerically.

**Comment by charlesh88** [comment]
@akhenry @VWoeltjen @larkin @akhenry Here's the start of the user story issue for sub-object selection. As was discussed earlier today, the initial proposed plan is to go after single sub-object selection of plot elements via their legend elements in both browse and edit modes, with context menus, toolbar buttons and the Inspector being affected. UI design will focus the details of this effort, and in parallel we can continue further design discussions as possible.

**Comment by charlesh88** [comment]
@akhenry @VWoeltjen @larkin @akhenry 
I've just pushed sketches for SO selection up to our GooDocs repo, here's the link: https://drive.google.com/open?id=0B0v27OM1JkSeR001RFJZMk43QVk. The action mainly takes place on pages 42 and 43. As usual, more nuance has risen up after poking at this for a bit, so please have a look prior to development. I'm showing some enhancements to the Inspector as well that are not necessarily in scope, but I wanted to include for the larger vision.

**Comment by VWoeltjen** [comment]
Reviewed new sketches, looks good!

Boy is it a bummer that CSS doesn't provide a good "hover" solution for nested objects. The solution suggested by the sketches (borders + opacity effects) seems like it would make sense. We could do more specific selection highlights with JS, if for some reason the CSS approach works out to be unacceptable (I could see it getting disorienting if selection depth/granularity is great enough)

A couple of notes on the tree caught my eye:

> * The currently navigated-to object in the tree must still articulate its "selected" state, but that must be displayed differently from how it appears as a primary selection.
> * ...
> * Note that the currently selected sub-object does not hilite as such in the tree. The tree's job is to provide context regarding the currently navigated-to object.

Could this be simplified such that the tree _only_ reflects navigation state, meaning there's no visual change there when a primary selection is made? Then, the only area that mixes navigation and selection state is the inspection area (which articulates this difference already, with "1 item selected")

**Comment by larkin** [comment]
Charles, few notes:
* sub-object selected + object selected: You selected the child object, not the parent.  Why is the parent highlighted?  Does it mean anything to the user?  (I don't think so).  I would prefer only highlighting the selected object.  
* showing selection state in tree-- Selection state in tree should be for drag and drop composition/actions and is not related to inspecting or viewing properties.   I think it would be confusing and not useful to show the selected object in the tree, as the true selection context depends on the view.
* navigation = navigate + select.  That way, you navigate to a plot, you have also selected the plot, and the inspector updates accordingly.  To change your selection, you click elsewhere in the view.

Victor, re CSS limits that's fine we can still implement something trivial, e.g [jsfiddle](https://jsfiddle.net/8nrmv34w/1/):
* `.selectable` -- item can be selected.  put this on elements that can be selected.
* `.hover` -- class that we apply when a user is hovering over a selectable item
* `.selected` -- class that we apply when something is selected.

**Comment by charlesh88** [comment]
Responding to Victor's and Pete's comments from Aug 10:

- Victor re. "couple of notes on the tree": I think it's important to articulate what is currently "selected" with regard to the Inspector. When you click an item in the tree, the tree item does the job of articulating what's selected, and the Inspector updates to display data about the selected object. When you sub-object select an item in a Layout, the Layout itself is doing the job of articulating selection and the Inspector is showing data for the selected sub-object. If you click more than one item in a layout, the Layout shows that, hiliting all items currently selected and the Inspector handles showing info for multiple selections. If the tree continues to show "selection" when a sub-object is also selected, it's now out of sync with what's happening in the Inspector - it's as if the user has selected the parent (the tree item) and one or more of it's children (via sub-object selection) all at the same time. I think it will be important for the user to clearly understand what selection is driving the data displayed in the Inspector.
- Pete re. "sub-object selected + object selected": My concern here was that it'd be important for the user to understand the container hierarchy of their selection. That said, let's defer this and add it later if it turns out to be something we do need.
- Pete re. "showing selection state in tree": See response above for Victor's "couple of notes on the tree". Tree selection is related to the Inspector when first selecting something from the tree. We agree, I emphatically don't want to have the tree sync up and display selected sub-objects.

**Comment by charlesh88** [comment]
Starting work on #1161, some notes about current UX that needs to be brought into parity:

**Comment by charlesh88** [comment]
Digging into this further, I think we'll need `.s-moveable`  and `.s-resizable`. For example, a child frame in a layout might have `.s-status-selectable .s-moveable .s-resizable`, while a plot legend item would only have `.s-status-selectable`. `.s-moveable` is important because I need to change the cursor to the 'move' icon; we may not need a separate `.s-resizable`.

**Comment by VWoeltjen** [comment]
A timeline use case for sub-object selection (which is consistent with existing designs, I believe) reported in #1189

**Comment by larkin** [comment]
Design work is completed, implementation will be handled in #1126 and beyond.
