### ISSUE TITLE
Overlay inputs need proper sizing

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1108]
- Fixed Position "Image" overlay dialog input is using the default field size. Make it use the large class.
- Fixed Position Save As... dialog Layout Grid inputs should use small numeric class.

**Comment by charlesh88** [comment]
**Testing notes**: 

1. Create a Fixed Position object.
1. Add an image object and verify that the URL input field takes up the full width of the dialog area:
![screen shot 2016-09-19 at 2 30 25 pm](https://cloud.githubusercontent.com/assets/1056412/18649702/d0984fc0-7e75-11e6-8a75-9940d7e3c345.png)
1. Save your new FP object, and enter numeric values in the two Layout Grid inputs. Observe that the number align right.
![screen shot 2016-09-19 at 2 30 54 pm](https://cloud.githubusercontent.com/assets/1056412/18649749/02f63e8c-7e76-11e6-9ae9-8ec2e07e0efc.png)

**Comment by VWoeltjen** [comment]
Verified in testathon 2016-09-19

**Comment by charlesh88** [comment]
Testathon 2016-09-19: verified.

**Comment by RCarvalhoNASA** [comment]
Although this particular feature worked fine, the image that I inserted into the fixed position object, which I formatted to look very nice, came out really awful when I saved the FP.  Not sure if this is a known issue already or not, but look at the Robert's FP in the Testathon20160919 folder to see the result.

**Comment by larkin** [comment]
Hrm, it looks good to me in the FP, but I think the sizing is not as expected.  @RCarvalhoNASA is this what you saw (or expected to see) in the FP?

![screen shot 2016-10-21 at 3 48 42 pm](https://cloud.githubusercontent.com/assets/226503/19614044/e7c26a98-97a5-11e6-9f1a-1d781d3a7bfd.png)

**Comment by charlesh88** [comment]
Here's what I think happened:

1. He added the image.
1. He editing the layout grid settings.
1. The image then got messed up.

@RCarvalhoNASA Is that what happened? If so, let's file a separate issue for layout grid. I've also got several ancillary things to tie to that.

**Comment by larkin** [comment]
@charlesh88 will file follow up issue for bug in layout sizing, marking verified.

**Comment by RCarvalhoNASA** [comment]
To be clear, I followed the bug steps above:
1. Create FP
2. Add image
   a. resized to make it look nice (i.e. could see the whole meatball)
3. Save the FP with size numbers
   a.  Image then appeared as above once saved.

**Comment by larkin** [comment]
@RCarvalhoNASA Thank you for clarifying-- I think that is a UX bug, I have tracked it in a new issue (https://github.com/nasa/openmct/issues/1285) which we will schedule for this sprint.
