### ISSUE TITLE
[API] Generate API docs

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1111]
After #1110, review JSDoc and ensure generated documentation is clear, readable, complete, et cetera.

This should be in the scope of public API, and should be clearly separate from API documentation generated for internal components (e.g. by ignoring `platform` and using `@private` for non-public scripts/methods/etc in `src`)

**Comment by VWoeltjen** [comment]
From API tagup 8/12/2016, do want JSDoc-generated API docs to be complete/comprehensive/correct (and should use this to verify that API is structured in a manner that is conducive to in-line documentation), but we also want a more "guided tour" than plain API docs might provide.

There will be a trade-off to balance between providing clear, well-ordered introductory documentation, and co-locating documentation (for ease-of-maintenance and to limit redundancy.) Ideally, API documentation would be so well-structured that it would fill both roles (for instance, documentation for the `mct` namespace could provide the introductory text), but this may not work well in practice for us.

**Comment by VWoeltjen** [comment]
Relevant work is on branch `api-1111` and JSDoc-built [API docs](https://vwoeltjen.github.io/openmct-api/) are available for review.

**Comment by larkin** [comment]
Closed as handled in #1124.
