### ISSUE TITLE
Collapse Inspector button being hidden in open933

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1112]
In the open933 (Time Conductor v2) the collapse Inspector button is being hidden because .primary-pane has overflow: hidden applied to it. This was added to clip the Time Conductor when it's min-width is exceeded.

**Comment by larkin** [comment]
@charlesh88 with this fix the mode selection window is now cut off: 

![screen shot 2016-08-08 at 11 42 03 am](https://cloud.githubusercontent.com/assets/226503/17491626/412923b6-5d5d-11e6-9198-b33250b8b15d.png)

**Comment by charlesh88** [comment]
Ack, you are right... one sec.

**Comment by charlesh88** [comment]
@akhenry @larkin Sorry about that fellers, just pushed a fix for my last not-so-good fix.

**Comment by charlesh88** [comment]
Testathon 2016-08-29: Verified fixed.
