### ISSUE TITLE
Plot consistency

### ISSUE THREAD

**Issue by RCarvalhoNASA** [nasa/openmct#1115]
During the 20160808 testathon, the server went down (Service Unavailable).  I had several tabs open on WARP already, and kept them open.  When the server came back up, some plots showed only one set of data, while others began overplotting, showing both old data and new data in the same time span.  I'm not really sure why this is doing this, but it seems to me undesireable behaviour
![plot consistency](https://cloud.githubusercontent.com/assets/5769437/17498924/22f9fa2e-5d7f-11e6-836b-d33ffb6a7e43.jpg)
The ideal would be for it to maintain the old plotted data through a server outage, and then continue plotting from there (without overplotting), so that the data is consistent

**Comment by akhenry** [comment]
This looks like a known issue with how out of order data is rendered by plots, which is captured in #343. The inconsistency seen here is probably as a result of the playback data restarting. Would like to verify that plots maintain consistency during server outage after #343 has been addressed.

**Comment by larkin** [comment]
Closed, plots no longer render out-of-order data in this fashion.
