### ISSUE TITLE
mshirley folder not appearing in search results

### ISSUE THREAD

**Issue by Costigan** [nasa/openmct#1116]
There's an mshirley folder under My Items.  When I type 'mshirley' into the search field, with all filters unchecked, I don't see any matches.  Shouldn't the folder be returned?  (If I search for 'shirley', I also don't see anything.)

If I search for a layout inside that folder, e.g., Mastcam Images, using, for instance, 'mastcam', I do see the expected matches.

**Comment by Costigan** [comment]
This is my fault (partially).  During my testing process, I checked several filters, including the Folder filter.  I then unchecked them.  I did not recheck 'All'.  Therefore, nothing was matched.  When I select the first 'Folder' entry in the filters list, the folder is matched.  If I check only the second 'Folder' further down the filter list, then no matches are returned.  This is what I did the first time.

Why are there two 'Folder' items in the list?  Why do they behave differently?

When a checkbox is changes such that nothing is checked, shouldn't the All checkbox become checked?  The state where nothing is checked isn't useful.

**Comment by akhenry** [comment]
There appear to be two different object types with the name `Folder`. The first has a key of `folder` and the second has a key of `warp.taxonomy`. `warp.taxonomy` is presumably not creatable, and should probably be named something else.

> When a checkbox is changes such that nothing is checked, shouldn't the All checkbox become checked? The state where nothing is checked isn't useful.

Yep, I agree.

**Comment by akhenry** [comment]
@VWoeltjen @larkin Propose we create a ticket in the WARP repo to change the name attribute on warp.taxonomy to 'Taxonomy' or something. 

I have filed [an issue in open](#1117) for the __All__ checkbox to be automatically selected when all other options are deselected.

**Comment by VWoeltjen** [comment]
Added a note about the extra "Folder" type to https://developer.nasa.gov/ResourceProspector/warp/issues/211 ("Object types appearing twice in Search filter menu"); closing this issue as, with #1117, it has now been split into two sub-issues
