### ISSUE TITLE
[Search] When no filter types are selected, "All" should be automatically selected

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1117]
Currently it is possible to deselect all object types in the search filter, including the __All__ option. This will always return no results, which is not useful.

The desired behavior is for __All__ to be automatically re-selected when there are no types selected

**Comment by charlesh88** [comment]
Agree.

**Comment by larkin** [comment]
I think this is a regression, was previously implemented this way.

Pete

On Aug 8, 2016, at 4:31 PM, Andrew Henry <notifications@github.com<mailto:notifications@github.com>> wrote:


Filter on no types makes no sense as it will always return nothing.

**Comment by akhenry** [comment]
Assigned to @vankessel and @varghesethomase

**Comment by varghesethomase** [comment]
@akhenry  @vankessel 's solution is a better one.

**Comment by RCarvalhoNASA** [comment]
verified, testathon 20160829

**Comment by charlesh88** [comment]
Testathon 2016-08-29: verified fixed.

**Comment by akhenry** [comment]
@vankessel Thanks for your fix. As you can see it's now been tested and verified fixed. Nice work!

Thanks also to @varghesethomase who contributed a PR for this issue as well.
