### ISSUE TITLE
Improve layout in dialogs that use location picker

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1118]
The location picker element that displays the tree (used by Save, Move, etc.) is a small, set size. It should be able to expand to the available space.

**Comment by charlesh88** [comment]
Should also hit #1108 while I'm at it.

**Comment by charlesh88** [comment]
Need to deal with form layout in mobile.

**Comment by charlesh88** [comment]
**Testing notes:** Display the appropriate dialog by creating a new folder, moving an existing item, creating a link, etc. In short, you want to be seeing the "Save In" (or "Link To", "Move To", etc.) tree selection field in the Location part of the dialog:

![screen shot 2016-09-19 at 2 24 03 pm](https://cloud.githubusercontent.com/assets/1056412/18649545/e6dc1970-7e74-11e6-8876-8329291fc1dc.png)

Ensure that the input is large, and actually resizes itself as you scale the size of the browser window larger and smaller. Note that making the window small may create a situation where the input is forced beneath its minimum height. In this case, double scrollbars will be displayed:

![screen shot 2016-09-19 at 2 24 13 pm](https://cloud.githubusercontent.com/assets/1056412/18649595/2ecd3336-7e75-11e6-9095-e6e9704de580.png)

This is right and proper and is nothing to worry about. However, if the input dialog persists for more than 4 hours, consult your doctor.

**Comment by RCarvalhoNASA** [comment]
Testathon 20160916 verified

**Comment by VWoeltjen** [comment]
The sizing isn't occurring quite the way I'd expect; when space is limited, I get a scroll bar on the whole thing but not on the locator:

![screen shot 2016-09-19 at 3 37 14 pm](https://cloud.githubusercontent.com/assets/1685764/18651250/f9b1c856-7e7e-11e6-916b-575f969b3643.png)

I also tried zooming out to see what would happen with more vertical space; dialog grew vertically as expected at first, but eventually started to get shorter, at least in proportion to the window.

For instance, at 50%:

![screen shot 2016-09-19 at 3 40 09 pm](https://cloud.githubusercontent.com/assets/1685764/18651310/64b11af8-7e7f-11e6-9945-b9616ea92360.png)

Then at 33%:

![screen shot 2016-09-19 at 3 40 42 pm](https://cloud.githubusercontent.com/assets/1685764/18651321/7885f4ae-7e7f-11e6-9934-6f40ba6167ea.png)

I'm not sure how fully we intend to support different zoom levels (viewing displays built at a different resolution is a use case that would support). I don't know if this manifests at larger display sizes, or if it only occurs as the consequence of zooming.

**Comment by VWoeltjen** [comment]
@charlesh88 - what's your assessment based on the above? Reopen, new issue, not an issue?

**Comment by charlesh88** [comment]
@VWoeltjen 
Not sure either if zooming is a factor here or not, but will investigate.
- This was in Chrome, yes?
- In those screen shots, did you start with the browser zoom at 100%?
- Is this on your laptop, which is 1366 x 768 if memory serves? If not, what was the screen resolution?

**Comment by VWoeltjen** [comment]
> - This was in Chrome, yes?

Yes 

> - In those screen shots, did you start with the browser zoom at 100%?

Yep 

> - Is this on your laptop, which is 1366 x 768 if memory serves? If not, what was the screen resolution?

Yeah 😃

**Comment by charlesh88** [comment]
@VWoeltjen I cannot duplicate this issue on my system. Let's try this on your computer next week.

**Comment by charlesh88** [comment]
Closing with unverified tag to bring this up in a Testathon. For testing, see Testing Notes above.

**Comment by VWoeltjen** [comment]
Verified in testathon 20161021

**Comment by charlesh88** [comment]
Testathon 2016-10-21: can't duplicate, calling fixed.
