### ISSUE TITLE
[Live Demo] Edit Button Tooltip responsiveness on 13 inch MBP

### ISSUE THREAD

**Issue by dylan-cooper** [nasa/openmct#1137]
Was going through the live demo on 13 inch macbook pro and this came up:

![screen shot 2016-08-23 at 10 19 55 am](https://cloud.githubusercontent.com/assets/9642887/17895559/7dfc7aa8-691b-11e6-81f2-aab3d123d51e.png)

As you can see, you can't hit the "Next" button.

**Comment by jlaneve** [comment]
Can confirm this happens in both Safari and Chrome with a 15" MacBook pro, but it only occurs if the Inspection Pane is closed/minimized.

**Comment by akhenry** [comment]
@dylan-cooper Good catch, thanks!

**Comment by akhenry** [comment]
Assigned to @dylan-cooper

**Comment by larkin** [comment]
Correction, assigned to @jlaneve

**Comment by akhenry** [comment]
@jlaneve Apologies for the incorrect assignment. Thanks for your contribution.

**Comment by VWoeltjen** [comment]
__Note for testing:__ Needs to be verified in the [live demo](https://openmct-demo.herokuapp.com/) as opposed to the testathon build.

**Comment by charlesh88** [comment]
Testathon 2016-08-29: Verified fixed.
