### ISSUE TITLE
[Documentation] wscat code block in tutorial stretches to fit whole content, makes page abnormally wide

### ISSUE THREAD

**Issue by BogdanAlexandru** [nasa/openmct#1143]
Screenshot displaying the issue:
![screen](http://i.imgur.com/ply2uP3.png)

It seems the indented code blocks do not handle overflow via scrollbars, they just stretch all the way. This leads to an exaggeratedly stretched page, and a hard to read block.

Switching it to a fenced block takes care of the issue because it spawns a scroll bar, but the code block becomes inconsistent relative to the other command line blocks.

Another potential solution I see is to snip the output. Something like:

    wscat -c ws://localhost:8081
    connected (press CTRL+C to quit)
    > dictionary
    < {"type":"dictionary","value":{"name":"Example Spacecraft", /* snipped for brevity */

This way the block stays consistent with the others.

Thoughts?

**Comment by VWoeltjen** [comment]
Thanks for reporting this. I think this can be solved with CSS tweaks for the website; moved this issue over to nasa/openmct-website#15
