### ISSUE TITLE
[proxyUrl] proxy endpoint does not pass URL parameters on

### ISSUE THREAD

**Issue by raoulsullivan** [nasa/openmct#1158]
The /proxyUrl endpoint doesn't pass URL parameters to the URL which it is providing a proxy for. For example, /proxyUrl?url=http://localhost:8085/telemachus/datalink&foo=bar results in a call to http://localhost:8085/telemachus/datalink, but without passing foo=bar. 

This prevents the use of this proxyUrl feature to avoid CORS issues when integrating with Telemachus for KSP (#1146) but would also prevent use with similarly designed telemetry providers.

I would call this a 'trivial' issue.

**Comment by raoulsullivan** [comment]
PR for this shortly.

**Comment by akhenry** [comment]
closed by #1159
