### ISSUE TITLE
[Sub-objects] Sub-object selection styling

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1161]
Say that three times fast. Ok, it's not that hard. This is a task issue for CSS styles associated with sub-objects, stemming from #1101.

From Pete's starting point, I propose these styles:
`.s-status-selectable`: put this on elements that can be selected. Will probably not have any individualized styling associated with it.
`.s-status-selectable .s-hover`: applied when a user is hovering over a selectable item. 
`.s-status-selectable .s-selected`: applied when something is selected.

A couple notes:
- `.s-status-selectable` should remain applied for the two 'state' styles.
- Hovering over a selected object should apply both `.s-hover` and `.s-selected` at the same time.

@VWoeltjen Anything to add here?

**Comment by charlesh88** [comment]
`.s-selected` already exists as a class in use in Panels and Fixed Position displays, it's used when interacting with objects in the canvas workspace. For consistency, will be trying to reuse this as much as possible.

**Comment by charlesh88** [comment]
I think we'll need `.s-moveable` as well. A Layout's child frames are selectable, moveable and resizeable; a Plot object's legend item is only selectable. `.s-moveable` is useful because I need to change the cursor when that object is selected and has `.s-hover` applied. We might need a separate resizable style, but I can't think of that use case right now.

**Comment by charlesh88** [comment]
@VWoeltjen I need to understand where in the DOM we'll be applying these styles. For instance, in Layouts and Fixed Position Displays `.s-selected` is actually applied to a separate DOM element. That object displays the "selected" or "hover" states accordingly.

**Comment by VWoeltjen** [comment]
The API I'm looking at is along the lines of `makeSelectable(domElement, itemToSelect)` - that is, we can decorate arbitrary DOM elements with selectability. So,  `s-hover` / `s-selected` / `s-selectable` would be applied to the same DOM node. If the visual effects need to be more complicated than a single DOM node changing, I think that can be accomplished with additional CSS/markup, without JS.

In practice, I think we'd most commonly see this applied to `mct-representation` elements, as that's the easiest way to reuse this ubiquitously. But that's not a hard restriction and we can decorate things differently without much additional effort (an `mct-selectable` directive would be easy to add, too).

Regarding `s-moveable`, I agree that this would be useful. I think that could be done with just markup; we would benefit from consolidating some of the code around moving things, too, but I think that's out of scope for this issue.
