### ISSUE TITLE
[Notifications] Progress dialogs may flash

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1168]
Originally mentioned in [this comment](https://github.com/nasa/openmct/issues/588#issuecomment-244422876), an indeterminate progress dialog may "flash" briefly when saving. This is most observable/noticeable when using Save and Continue Editing, but can also be seen with regular Save (esp. with a remote persistence store.)

This is undesirable; if a Save can be completed very quickly, the dialog is not useful and instead serves only as a distraction or annoyance.

**Comment by VWoeltjen** [comment]
General UX guideline I've seen used is to display progress notifications only after 100ms. If a task completes more quickly than that, no need to notify.

**Comment by hudsonfoo** [comment]
@VWoeltjen this is good to go if you are up for a code review.

**Comment by larkin** [comment]
IIRC the save-in-progress dialog prevents someone from accidentally double-clicking the save button?  If we wait 100ms before showing it we need to ensure that something prevents the user from double-clicking save.

**Comment by VWoeltjen** [comment]
Interesting point, not sure if that would be problematic or not. We could test around it.

I'd be interested in seeing what a CSS-only approach using animated opacity looked/felt like. If the overlay was still in the DOM, clicks would be blocked during that 100ms (if it is even displayed that long) but there wouldn't be any visual disruption. What I don't know is if it would be annoying to have your clicks blocked without a visual reason, or if that 100ms will go by so quickly that nobody would ever notice it.

**Comment by hudsonfoo** [comment]
I tried double clicking quite a bit but was never able to do so, but I only tried in the display editor.

**Comment by hudsonfoo** [comment]
Btw, I've always loved in-button loading indicators like Ladda (http://lab.hakim.se/ladda/) for situations like this.

**Comment by akhenry** [comment]
@hudsonfoo How is your CSS? Addressing this via a CSS animation actually makes a lot of sense to me. There's no code delta, and it has the side benefit of also blocking ticks. What are your thoughts on trying this approach?

@VWoeltjen I think the delay would be so brief that nobody would notice that their clicks are blocked.

**Comment by hudsonfoo** [comment]
CSS is a good solution for this. Wish I had thought of it! :) I replaced my original PR with #1178.
