### ISSUE TITLE
[Search] Consolidate/summarize Search related issues

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1173]
Bring together Search-related issues so the team can decide on possible open source community outreach to solve.

**Comment by charlesh88** [comment]
### Results not performant/weird/confusing/unusable
- #132 Search results ordering is confusing
- #603 Search on partial words is confusing
- #868 Actions missing in search results
- #340 Objects not removed from results
- #91 Input un-responsive
- #121 Clicking objects in search results does not navigate

### New Search features/tasks
- #310 Generic search worker
- #501 Search providers should accept filters; relates to search by type #1092 
- #1092 Allow user to find all objects of a type
- #353 Get Mark Shirley's input on Search reqs

**Comment by charlesh88** [comment]
TODO: review with team to determine good Help Wanted items.

**Comment by larkin** [comment]
Goal for Robinson: create / update related issues to clarify what we want done, and add help wanted tags where we feel they are good candidates for open source contributors.

**Comment by larkin** [comment]
@charlesh88 to schedule a meeting in Robinson to review this.

**Comment by charlesh88** [comment]
Notes from tagup 10/26/16:
- #132: not a good HW candidate.
- #603: not a good HW candidate.
- #868: not a bug
- #340: Woot! HW candidate.
- #91:  Woot! HW candidate.
- #310: Not a HW candidate. Visit in Roddenberry.
- #501: Not a HW candidate. Related to #132.
- #353: Not a HW candidate.
