### ISSUE TITLE
[Time Conductor] Add pan and zoom gestures to time conductor

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1182]
Add the ability to click on the time conductor axis and drag it to pan the window of time being displayed.

Also add a zoom slider to adjust conductor bounds.

**Comment by akhenry** [comment]
@charlesh88 I've pushed a change into this branch that makes the zoom slider label work.

You probably know this already, but to test this branch you'll want to enable the time conductor, the utcTimeSystem, and the compatibility layer for views. Using the MSL test data also helps

I've added the following lines to my local main.js -
``` javascript
    './platform/features/conductor-v2/conductor/bundle',
    './platform/features/conductor-v2/utcTimeSystem/bundle',
    './platform/features/conductor-v2/compatibility/bundle'
```
I don't want to check it in as I want to keep the commit history clean.

**Comment by akhenry** [comment]
Notes from discussion between @charlesh88 @larkin and @akhenry

Zoom is not well supported in real-time mode at the moment. Currently "deltas" are defined as durations limited to 24 hours. This limit exists for technical reasons that should be fixed. For reasons of situational awareness it may be desirable to define a mode specific zoom limit in real-time mode but this should be specified via configuration or policy.

Supporting deltas beyond 24 hours requires some additional design. A number of options were discussed including:

1. Supporting free-text input of durations such as "00:10:00", "ten minutes", "01:00:00", "one hour" etc.
2. A menu that is made available when the text input is focused that gives some default options such as "last five minutes", "last hour" etc.
3. A separate menu similar to the session selector menu in the design that allows specification of start and end deltas simultaneously.

**Comment by larkin** [comment]
@akhenry open issue for durations beyond 24 hours, separate from #1225, schedule for Robinson.

**Comment by akhenry** [comment]
Closed by https://github.com/nasa/openmct/commit/79b4f9a0f4e667bc9662ef3143a0ca4116e2523e
