### ISSUE TITLE
Notes field return

### ISSUE THREAD

**Issue by RCarvalhoNASA** [nasa/openmct#1184]
From lander timeline training 2016/9/13:
User requested notes field available in the Edit Properties view of any item type (note that this was available way back when) to allow for further annotation of details of activities, modes, etc.

**Comment by VWoeltjen** [comment]
@charlesh88 - thoughts on this? It would be simple to add a "notes" textarea that appears for all domain objects (this is also a good "help wanted" candidate as the change would be fairly self-contained)

**Comment by larkin** [comment]
@charlesh88 @VWoeltjen have heard this requested many times and it would be a great simple value add.

**Comment by charlesh88** [comment]
I'm fully onboard, especially with this as a Help Wanted. We may need some very minor styling to control the textarea size, but that will be very easy.

**Comment by hudsonfoo** [comment]
It just hit me that my commit line lengths are incorrect. Updating my IDE to not make that mistake again.

**Comment by BogdanAlexandru** [comment]
Should this not have been closed by https://github.com/nasa/openmct/pull/1194 being merged?

**Comment by VWoeltjen** [comment]
Yes it should have - good catch.

**Comment by larkin** [comment]
Testathon 2016-10-21: Verified implementation.

**Comment by charlesh88** [comment]
Testathon 2016-10-21: Verified implementation too.
