### ISSUE TITLE
Timeline moving parents should move children

### ISSUE THREAD

**Issue by RCarvalhoNASA** [nasa/openmct#1187]
From lander timeline training 2016/9/13:
User experienced frustration that moving a parent activity in a timeline (ahead by 5 days) did not also move the children.  Children should move along with their parents while retaining the same internal structure.  This would be particularly useful now that we can duplicate activities, so a user can easily copy a cluster of activities (TCM) and then move each one to where it should be.

**Comment by akhenry** [comment]
Makes total sense. Interestingly, *dragging* a parent activity left or right does move its children, but setting a new start time manually does not. This seems like a bug to me.
