### ISSUE TITLE
[Dialog] Accept ESC key to close out of a dialog

### ISSUE THREAD

**Issue by hudsonfoo** [nasa/openmct#1197]
During my use of Open MCT, I have hit the escape key so many times, anticipating a dialog window to close. It's apparently a normal part of my workflow that I never noticed before. I'm wondering if folks at NASA might feel the same way, and if it would be a useful function to add to all dialog windows to listen for ESC and close when appropriate?

Also, please let me know if creating issues is how your team would prefer to receive suggestions.

**Comment by VWoeltjen** [comment]
I've tried to do the same as well out of habit.

@charlesh88 - your thoughts? The one risk I see is that, when filling out forms, if you hit Esc expecting something else to happen, you'll lose your form input. But this is fairly common behavior for web overlays and dialogs at this point, so I don't think a typical user would be surprised by this.

> Also, please let me know if creating issues is how your team would prefer to receive suggestions.

Yes it is, and thanks for the suggestion.

**Comment by larkin** [comment]
I think this is good, and also as a number of our dialogues are forms, it would be great to be able to submit them by pressing the return key.  Return says "ok," escape says "cancel".  Or such.

**Comment by charlesh88** [comment]
I'm for this, but would only apply to dialogs for now, which is the scope of this issue. ESC should not navigate you somewhere else, or exit you from Edit mode without saving changes, etc.

**Comment by goelrohan6** [comment]
What we can do is,
- Close dialog if there is no editing being conducted.
- If the user is filling the form then on ESC key we may ask "are you sure, changes won't be saved" and on pressing enter both dialogs will close and on ESC warning dialog will be closed and first one won't.

Basic idea being user can operate through keyboard only, increases convenience

**Comment by akhenry** [comment]
@goelrohan6 Thanks for the suggestion! I think this sounds sensible.

I also wouldn't be averse to implementing it initially without any warning to see how it feels and to get user feedback.

**Comment by charlesh88** [comment]
I definitely think that Cancel via ESC key if the user has entered information should fire a warning; we wouldn't need that on the Return key of course.

**Comment by cseale** [comment]
Hi @akhenry, I was looking to get involved in this project, and this issue seems like something super simple that I could do in order to get into the codebase and start contributing. If you wish I could implement this feature?

**Comment by cseale** [comment]
I have a branch ready to go, but I cannot push to the repo? I guess I need permissions?

I have added the simple change of ESC keypress cancelling a dialog.

I created 2 directives, `mct-esc-keydown` which operates similar to `ng-keydown`. As mentioned above, ESC keydown could be used in multiple different contexts, so reusability is good.

The other is `mct-autofocus`. Focus is required in order for a DOM element to receive keyboard events, and when the dialog and overlay is inserted into the DOM, they do not have focus. This directive will give an element focus when it is inserted into the DOM, as the regular `autofocus` attribute is only valid for `<input>` tags. You also will need to include `tabindex="0"` attribute on any non-input element for it to be able to receive focus. Not sure if I should check for the presence of that attribute on the element this directive is applied to and maybe log a warning if it does not exist. Seems like a pitfall someone could easily fall into.

**Comment by larkin** [comment]
@cseale In addition to completing the CLA, you'll need to submit your changes with a [pull request](https://help.github.com/articles/about-pull-requests/); you should fork the repository, push your changes there, and open a pull request with those changes.  We'll then focus feedback and discussion around that pull request.

**Comment by akhenry** [comment]
@cseale I think this is a great first issue. We have received your CLA, thanks for sending it along.

**Comment by cseale** [comment]
No problem, looking forward to getting more involved

**Comment by scottwarren** [comment]
I found this issue on [Issuehub](http://issuehub.io/?label%5B%5D=help+wanted&label%5B%5D=trivial&language=javascript), but it appears that the related PR has been accepted and merged - is this open because there is outstanding issues? I'd love to lend a hand on Javascript related PR's :)

**Comment by cseale** [comment]
I was wondering about this myself

**Comment by akhenry** [comment]
Ah, good catch. This should have been closed when the PR was merged. Thanks guys!

@scottwarren We'd love for you to lend a hand! #1422 might be a good one to start with?

**Comment by scottwarren** [comment]
Thanks @akhenry, I'll take a look at #1422

**Comment by charlesh88** [comment]
Testathon 2017/04/20 Verified fixed.
