### ISSUE TITLE
[Live Demo] Add link to web site

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1199]
Currently there's not a link from the live demo to the web site, so if someone starts at the live demo they don't have any way to get more information (except search engines)

We should have a link in the last bubble of the guided tour, and in the About dialog as well (for those who exit the tour early)

**Comment by akhenry** [comment]
@VWoeltjen On it. I'll push something today.

**Comment by akhenry** [comment]
Addressed in 7b1ef58224b5f3299284ad2418cc76944a667387

**Comment by VWoeltjen** [comment]
Verified that this is live at https://openmct-demo.herokuapp.com
