### ISSUE TITLE
[Plots] Remove export buttons from objects when in a Layout

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1202]
The current implementation of the export buttons (specifically in plot views, Panels, and table views) when those objects are in a Layout are to hide the buttons initially, and then shrink the plot or table on hover to reveal the buttons. For some reason as well it's behaving differently from SWG plot views to Panel views. After living with this for a while, I'm finding it's driving me completely insane, and I think that will happen to other users as well. 

This issue acts as an "undo": the solution I intend is to not display the export buttons when the object is in a layout; they will still be available when a user navigates to the actual object. At the end of the day, context actions need to be enhanced to allow adding this kind of functionality there - at that time, we can bring this functionality back to objects in layouts.

**Comment by charlesh88** [comment]
@akhenry Thanks!

**Comment by larkin** [comment]
Testathon 2016-10-21: Verified

**Comment by charlesh88** [comment]
Testathon 2016-10-21: Verified fixed.
