### ISSUE TITLE
[Search] Clicking objects in search results does not navigate

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#121]
1. Enter a search query that brings up more than zero results. 
2. Regular click on the search result to view it in the right hand pane.
3. Clear the search text such that the tree disappears

Observe: Nothing appears to be navigated-to. Desired behavior is to see the object that was clicked on in the search results as the currently navigated-to object.

Observed during testathon, 9/17/2015

**Comment by VWoeltjen** [comment]
@charlesh88 can you check my "desired behavior" above for accuracy?

**Comment by VWoeltjen** [comment]
(From tagup 9/21/2015) Charles says desired behavior is accurate

**Comment by VWoeltjen** [comment]
Can't reproduce as of 51968954a98815b87e1af72ff68d0fcaf3aeb905; domain object appears correctly navigated-to. Believe this was resolved by #119.

**Comment by RCarvalhoNASA** [comment]
Testathon 20151123:  While I stay on the selected item, the tree view does not change in any way to show me that I have 'gone to' that item in the tree.  No indication in inspector panel either of where I am.

**Comment by VWoeltjen** [comment]
Think the root cause of this is that same as the one described in [this comment](https://github.com/nasa/openmctweb/issues/147#issuecomment-159687669) on #147. When a complete location chain is present, navigation does occur as expected.

This the most practical solution will be to ensure that complete location information is available. May also want to add some sort of visual indication or notification for cases where location chains are incomplete, but not sure what that should look like. 

Perhaps on a navigate to an ambiguous location, we could pop a dialog asking users to choose the primary location for the relevant object? (That's a little hard because it means finding all occurrences, but search could be amended to support this)

**Comment by VWoeltjen** [comment]
Want to reevaluate if there are any bugs here after #346 has been implemented and used.

**Comment by charlesh88** [comment]
Notes from tagup 10/26/16:
- Think this is not bug, closing.
