### ISSUE TITLE
[Create] Scroll bar appears in Create menu

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1210]
During training 9/28/2016, observed Create menu had a scroll bar and no right hand description pane. This was after Searching, Editing, and various other activities.

Most significant impact is that descriptions of object types are not visible, making it less clear what is available to Create.

Observed on Mac OS X in Chrome, display resolution 1280x1024

**Comment by charlesh88** [comment]
Able to duplicate the scrollbar locally: a sufficient number of items in the Create menu will force a scrollbar to appear on overflow; this is correct behavior. Still not sure why the right-hand pane was not appearing though.

**Comment by charlesh88** [comment]
Adding unverified tag to see if we can dupe this during a Testathon.

**Comment by larkin** [comment]
@akhenry will try to reproduce in the lab on the projector which has the 1280x1024 resolution and see if it can be reproduced. If not, remove "unverified".

**Comment by akhenry** [comment]
Can't recreate on projector in Chrome on Mac OS @ 1280x1024
