### ISSUE TITLE
[Build] Unexplained build failures on master

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1214]
Noticing several build failures on CircleCI for various PRs. Made a test commit, 7cb40fae3088c62e1aed23d6f2a263d10101368d, which had a whitespace-only change in README.md, and [that failed too](https://circleci.com/gh/nasa/openmct/2810).

Investigating.

**Comment by VWoeltjen** [comment]
Notably, CircleCI failures are also [inconsistent](https://circleci.com/gh/nasa/openmct/2809) somewhat

**Comment by VWoeltjen** [comment]
Suspect order of script loading may be relevant here, based on inconsistency in errors. 

I think the Error object above is a [mismatch](http://requirejs.org/docs/errors.html#mismatch) error from RequireJS, which can happen an anonymous define occurs in the global scope.

Going through a `git bisect` to try to narrow this down further.

**Comment by VWoeltjen** [comment]
According to `git bisect`, d1f67fd8b9f8eaa82cc1c1b04504a2c4210e1cd8 is the first bad commit

Which makes no sense to me.

**Comment by larkin** [comment]
I will start investigating this.
