### ISSUE TITLE
[Tables] Scrollable area in tables much longer than content

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1216]
![table-scroll-bug](https://cloud.githubusercontent.com/assets/4215777/19005359/055161f6-870f-11e6-90ec-d4254abd23e6.gif)

In historical tables (but problem is probably in mct-table directive and thus not specific to historical tables) the scroll bar allows scrolling well beyond the visible rows of the table.

It looks as though the table in question (historical table with Sine Wave Generator content) probably has many more rows than the 50 displayed, but these are not being rendered for some reason. 50 is a suspicious number as it is the size of the [maxDisplayRows variable](https://github.com/nasa/openmct/blob/7439d949c472e76d7119dbf748120d636384c671/platform/features/table/src/controllers/MCTTableController.js#L21) that determines when the [scrolling logic kicks in in the setVisibleRows function](https://github.com/nasa/openmct/blob/7439d949c472e76d7119dbf748120d636384c671/platform/features/table/src/controllers/MCTTableController.js#L183). This is where I would look first.

**Comment by akhenry** [comment]
Data loss is occurring, but in historical tables only, so possibly not a sprint blocker because not used in WARP. Would be a blocker for any VISTA release though.

**Comment by akhenry** [comment]
Ah, it's super easy. It's due to [selecting the wrong element](https://github.com/nasa/openmct/blob/5b0fa90e39bb6b375ee245773c614c3b113c06a7/platform/features/table/src/controllers/MCTTableController.js#L23) against which to process scroll events. It selects the first child `div`, which has changed since initial implementation. This needs to be a little more robust.

**Comment by akhenry** [comment]
> Might also be a change to html/css with the control bars that causes the wrong element to scroll.

Yup, this is basically it.

**Comment by larkin** [comment]
Testathon 2016-10-21: Can't validate in historical tables, appears fixed in realtime tables.

**Comment by charlesh88** [comment]
Testathon 2016-10-21: Verified in RT Table objects and views. Can't validate in historical tables via WARP.

**Comment by akhenry** [comment]
Fix was in `MctTable` directive, so applies to historical tables also.
