### ISSUE TITLE
[Export] jsPDF appears to be causing errors

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1217]
Observable on `master` as of c27c0c5b8cb735e2ebf8641c6f27295aa08927af

When starting the application, most of the time (I'd say 80-90% of the time) everything loads fine, but sometimes see:

```
angular.js:12416 TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
    at TypeError (native)
    at new FileSaver (http://localhost:8080/bower_components/jspdf/dist/jspdf.debug.js:9767:30)
```

Also sometimes see require attempts fail to load, such as:

```
require.js:165 Uncaught Error: Script error for "platform/containment/src/ToggleView"
```

Easiest way to reproduce is to run the development server (I was just using `node app.js` when reproducing this) and reloading the application a few times

**Comment by VWoeltjen** [comment]
Think solution here is probably just to remove PDF export (and the jsPDF dependency) for now

**Comment by larkin** [comment]
Ok, gonna kill it with 🔥 .

**Comment by akhenry** [comment]
I say we take off and nuke the entire site from orbit. It's the only way to be sure.

**Comment by VWoeltjen** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;:rocket:
🌎

---

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:rocket:
&nbsp;&nbsp;&nbsp;&nbsp;:bomb:
🌎

---

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; :rocket:

:boom:

**Comment by akhenry** [comment]
:fire: :fire::fire: :fire: :alien: :fire: :fire: :fire: :fire:
