### ISSUE TITLE
[Testing] Add unit tests for openmct module

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1218]
Add unit tests for `openmct` module, as well its components.

Goal is to get code coverage in the `src` hierarchy back to standards after #1212

**Comment by larkin** [comment]
Scope this to only the openmct object and not the sub APIs, open follow-ups for test coverage of each individual API.

**Comment by larkin** [comment]
#1400 raises a question: do we need test coverage for plugins, or should that be specific to the plugin?  Uncertain.

**Comment by VWoeltjen** [comment]
Statement coverage after #1510:

![image](https://cloud.githubusercontent.com/assets/1685764/24673238/64eaa2c6-192c-11e7-9296-30664b10cb21.png)

**Comment by VWoeltjen** [comment]
Filed issues for the various directories under `api`.

The `adapter` is used to interface with legacy APIs and I'm dubious of the value of tests here, so haven't filed anything.

I'm somewhat expecting the other directories to disappear as a result of #1219, so haven't filed issues for those either. Left [a note](https://github.com/nasa/openmct/issues/1219#issuecomment-291598527) to look at testing after that is complete.
