### ISSUE TITLE
[Code Style] Reorganize src hierarchy

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1219]
The `src` hierarchy is looking a little messy after #1212. This should get cleaned up. Suggest, roughly:
- `src`
  - `adapter`: Things which appear in the adapter layer
  - `api`: Things that are exposed as part of the public API
  - ...other directories by feature...

...which is not too dissimilar from the current hierarchy.

**Comment by VWoeltjen** [comment]
Should take a look at linked issues from #1218 and ensure code coverage is either present or accounted for by issues once this reorganization is complete.

**Comment by larkin** [comment]
Happy to defer this a sprint unless we think it's a blocker for anything?

**Comment by larkin** [comment]
closing as this will be resolved via other issues.
