### ISSUE TITLE
Reduce D3 dependency size

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1224]
Currently we are using a small subset of D3 functionality, but including the whole library. At 211KB minified, it's not small. One option is to include the relevant [microlibraries](https://github.com/d3) instead of the [single monolithic build](https://github.com/d3/d3) which we are currently including.

**Comment by slinto** [comment]
https://github.com/d3/d3-axis is not available on Bower. Can I use a node_modules/ dir for a d3-* require in openmct.js file?

**Comment by akhenry** [comment]
@slinto Thanks for looking into this, apologies for the delay in getting back to you.

Currently we're using `npm` for managing build-time dependencies, and bower for runtime dependencies. I don't see a good reason not to use npm managed dependencies at runtime though.

Note that in order to test this you'll need to enable the time conductor component, which uses D3. In order to enable it some dependencies need to be added to the `require` block in `index.html` -

```js
require(['openmct'], function (openmct) {
    [
        'example/imagery',
        'example/eventGenerator',
        'example/generator',
        'platform/features/conductor/core',
        'platform/features/conductor/compatibility',
        'platform/features/conductor/utcTimeSystem'
    ].forEach(
        openmct.legacyRegistry.enable.bind(openmct.legacyRegistry)
    );
    openmct.install(openmct.plugins.myItems);
    openmct.install(openmct.plugins.localStorage);
    openmct.install(openmct.plugins.espresso);
    openmct.start();
});
```

Once enabled, just make sure that the axis ticks and labelling are rendering ok with the per-module dependencies. It should look something like this -

<img width="920" alt="screen shot 2017-02-06 at 11 36 04" src="https://cloud.githubusercontent.com/assets/4215777/22663179/7e43b8be-ec60-11e6-9905-58b9b95d481c.png">

**Comment by slinto** [comment]
I think, this can be closed?
