### ISSUE TITLE
[Time Conductor] Active time system unpredictable

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1228]
It has been observed in VISTA that the time system selected by default on load can change randomly. This may be related to non-deterministic bundle loading order.

It has also been observed that when switching between fixed and real-time mode, the time system can sometimes change unpredictably. 

@larkin do you have any additional details or reproduction steps for the second aspect of the bug? Is it a bug or a case of user expectation not matching implementation? When switching mode the TC will try to retain selected time system if it is supported by the selected mode, but if not it will default to the first time system that is supported by the mode. Which time system is the "first" supported time system will be affected by the non-deterministic loading seen in the first part of this issue.

**Comment by larkin** [comment]
The unpredictability in the default time system is based to requirejs load ordering, but there also may be issues switching between modes.

**Comment by larkin** [comment]
I did not experience unpredictability for reasons other than requirejs ordering, will close this.
