### ISSUE TITLE
Load & Persist Time Conductor state in URL

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1231]
The Time conductor should persist the time conductor state in the URL, and on page load should load the time conductor state from the URL.  Such that a user can share what they are currently viewing by sharing the browser URL.

Tentatively scheduling for Robinson and assigning to @akhenry as he has done a lot of work on the time conductor.

**Comment by charlesh88** [comment]
**NOTE:  Time Conductor won't be available in WARP for the Testathon 02-07-2017**

Testing notes:

1. Change the Time Conductor to use different time bounds than its defaults.
1. Copy the URL currently in the browser.
1. Create a new tab and paste the URL in that tab's Address input.
1. Observe, the object and Time Conductor should use the previously entered time bounds.

**Comment by charlesh88** [comment]
Testathon 2017/04/20 Cannot verify, TC not enabled.

**Comment by VWoeltjen** [comment]
Verified in testathon 2017-10-05
