### ISSUE TITLE
Create Style Guide as an example bundle

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1233]
Implementation task related to #988.

**Comment by charlesh88** [comment]
Per Jay week of Nov 7 this was pushed out to make way for GV design sprint and prototype building.

**Comment by charlesh88** [comment]
Todo: remove inclusion of example/msl and create PR for @akhenry.

**Comment by VWoeltjen** [comment]
Verified locally during testathon 2017-10-05
