### ISSUE TITLE
[Notifications] You cannot click on the notifications icon

### ISSUE THREAD

**Issue by BogdanAlexandru** [nasa/openmct#1239]
![Imgur](http://i.imgur.com/UM2AqTU.gif)

You have to click on the label in order to view the notifications, but this is very confusing because by default the label is hidden. I find myself hovering on the notifications icon and then trying to click on it to bring the notifications up, while the label expands. Nothing other than the icon not responding suggests that I should click on the label instead.

**Comment by akhenry** [comment]
👍 I agree, good catch

**Comment by Brantron** [comment]
Is there a dev database or some easy way to populate notifications?

**Comment by larkin** [comment]
@brantron There is an example bundle which allows you to toggle notifications.

**Comment by kjsan** [comment]
@brantron That's right, you can include It in the index file.

![screenshot](https://cloud.githubusercontent.com/assets/22921864/19498869/dffc8e1e-9558-11e6-8270-7c4819eb20d7.png)
