### ISSUE TITLE
[Live Demo] Refactor live demo to bring it in line with Master

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1240]
As well as showing the capabilities of the platform, the Live Demo serves as a didactic tool for developers of applications based on Open MCT. The Live Demo needs to be updated for parity with master, and refactored to remove conflicting code that is application specific.

One option is to make the Live Demo an application built on Open MCT ala WARP and VISTA, rather than a branch. That way regular merges from master would not be necessary to keep it up to date. It could instead be built on the latest stable build of Open MCT.

**Comment by larkin** [comment]
@akhenry to start working on, may spread over two sprints.

**Comment by larkin** [comment]
Break it down into a few issues for scheduling purposes.

**Comment by akhenry** [comment]
1. Externalize inline code changes into separate plugin. __Roddenberry__
2. Rebase over master __Roddenberry__
3. The deployed Live Demo should be built from the minified library ala VISTA and WARP. __Roddenberry__
3. The code can then be ported to the new API next sprint, allowing some time for the API to be bedded in. __Sagan__ #1327

**Comment by akhenry** [comment]
This is now being worked on. The Live Demo is being built as an Open MCT based application in a separate repository. At the same time, demo specific code is being rewritten using the new API, addressing #1327.

There are some issues arising out of this that will need addressed in master prior to relaunching the live-demo:

* [ ] #1483 - Prevent editing of objects that cannot be saved
* [ ] #1482 - Triggering a persist on each tick

**Comment by larkin** [comment]
Fixed in https://github.com/nasa/openmct-demo.  Deploys are not automated, see https://github.com/nasa/openmct/issues/1549 for follow-up.
