### ISSUE TITLE
[Time Conductor] Time of Interest enhancements

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1242]
After discussion between @charlesh88 and @akhenry the TOI indicator should be modified to support clicking on the label and the clock icon to "resynchronize" the time of interest. This will be useful to reset all views to show the current time of interest without having to set a different time of interest. The TOI will be dismissable by clicking on a new cancel button that will need to be added to the design and markup.

**Comment by charlesh88** [comment]
Work completed.
