### ISSUE TITLE
[Documentation] Update tutorials to reflect new API

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1248]
Update tutorials to reflect changes to API from #1212. In particular, tutorials can and should now be written as standalone files which use `openmct` as a dependency.

Should also consider #1206 and #1163 in the context of this issue (they may be solved or made obsolete)

**Comment by VWoeltjen** [comment]
Some notes:

* Related issue with CSS classes, #1163 
* Tutorials depend on `legacyRegistry` which may not be available, depending on whether/when the `openmct` module has been loaded. (Which is also easy to miss depending on load ordering.) We won't use `legacyRegistry` in updated tutorials but should watch out for any analogous issues

**Comment by VWoeltjen** [comment]
Note from tagup 12/20: Want tutorial to be a complete document, but also want standalone files to see the finished product.

**Comment by VWoeltjen** [comment]
In terms of content, original three tutorials are good starting point, but there were also some useful additional tutorials/examples in #999 that are worth  looking back at (e.g. composition examples)

**Comment by akhenry** [comment]
Consider #265 and #1381 in the context of this - ideally we want both syntax and diff highlighting in the code examples. Also worth providing source code for the tutorials, and unit tests to pick up breaking changes.

**Comment by larkin** [comment]
@akhenry I wonder about the diff notation; I haven't seen many tutorials that follow this example.  Seems too technical / distracting.  If we write clear tutorials it shouldn't be a big problem.

**Comment by akhenry** [comment]
@larkin I certainly found it useful the first time I followed the tutorials. It depends on the approach we take with the new tutorials though. If we adopt a similarly stepwise approach with incremental changes to files it may be useful to highlight the differences.

**Comment by larkin** [comment]
Completed, will open new issues as we add new APIs
