### ISSUE TITLE
[Composition] provide ids, not objects

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1253]
Currently composition providers are expected to return objects.  However, if composition providers return objects it is also necessary to implement an object provider to resolve those objects. Otherwise, many functions of the framework do not work properly.  

As it currently stands I have a composition provider which provides objects and it "seems to work," until I try and compose those objects in other places. To resolve this I had to implement an object provider that replicates a lot of the functionality of the composition provider. 

To clarify the API story, I think composition providers should only deal with identifiers and should leave the loading of objects to the object service. Had I tackled the problem in that order it would have saved me a lot of time in implementation. 

@akhenry @vwoeltjen lmk your thoughts. I can chat through some of the backstory if you want to know more. 

Assigning to me for implementation if we concur.

**Comment by larkin** [comment]
Also note that the composition collection can handle loading objects so that API consumers don't have to deal with that.

**Comment by VWoeltjen** [comment]
That makes sense to me. Shouldn't require the same behavior to be implemented/exposed twice. 

For purposes of comparing to alternatives, the other alternative I see would be to only allow domain objects to be loaded via composition, and add something like a "find" to composition collection (so you can do an `openmct.composition(root).find(id).then(useDomainObject)`)

I think that alternative would work, and isn't so bad to use, but could get very gnarly to implement. Wouldn't be able to choose the correct provider efficiently. So, I like what you've proposed.
