### ISSUE TITLE
[API] Asynchronous root registration

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1264]
Follow up for #1252; want to allow asynchronous root registration, but want My Items to be present in the out-of-the-box configuration of Open MCT for developers.

Suggestion: Treat "My Items" as a plugin that can be enabled, and enable it from `index.html` in this repository. Then WARP (and other My Items users) can also easily enable it through the legacy registry

**Comment by larkin** [comment]
@VWoeltjen Hrm... see https://github.com/nasa/openmct/pull/1252/commits/891412bdb91297afff15a924c9c8f6081be1c42e

This should have been merged with #1252. I had smoke tested and noted that this was visible, were you looking at warp which has a custom index file? 
.

**Comment by VWoeltjen** [comment]
Interesting. I was running Open MCT on `master` when I observed this; loaded with an empty tree and the root object in view.

Let me double-check; there may have been some user error on my part here

**Comment by VWoeltjen** [comment]
Error is reproducible in 56a662841e2c0a58fd8f76d2bec4377b9e6a777b (prior to the revert)

**Comment by VWoeltjen** [comment]
I can take this issue in the context of https://developer.nasa.gov/ResourceProspector/warp/issues/236, working on a PR
