### ISSUE TITLE
[API] Provide methods for registering time systems and formats for TCv2

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1265]
Add an adapter to support the TCv2 in the new public API.

**Comment by akhenry** [comment]
Should also address need to set Mode, and tick sources (from #1091)

**Comment by akhenry** [comment]
Should also address setting the initial state of time conductor (based on registered time systems etc.). Ideally this should occur before any client code queries the time conductor.

**Comment by larkin** [comment]
Closed with https://github.com/nasa/openmct/pull/1553
