### ISSUE TITLE
[Inspector] Table options controls in Inspector need better layout

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1266]
Somehow we got a lot of extra vertical space in the layout of the table options elements in the Inspector. Seen in WARP, but suspect this is in Open.

<img width="1554" alt="warp edit rt table 3" src="https://cloud.githubusercontent.com/assets/1056412/19504274/d3150932-956d-11e6-9673-9fa23a851b68.png">

**Comment by charlesh88** [comment]
@akhenry Inspecting this reveals that ng-form is being repeated - is that right?

**Comment by charlesh88** [comment]
Add this to line 92 of _inspector.scss:

**Comment by akhenry** [comment]
@charlesh88 At first glance, repeating form doesn't seem right. I'll investigate.

**Comment by akhenry** [comment]
@charlesh88 I think the nested ng-form elements are ok. ng-form !== html form tag. It's used for grouping form controls. I think we're using it for validation purposes. For some reason `MctForm` `ng-repeat`s the `ng-form` on each form row, but I expect there's a reason for that.

**Comment by charlesh88** [comment]
Testathon 2017/04/20 Verified fixed.
