### ISSUE TITLE
gulp develop takes way too long

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1268]
A recent update seems to have added some new commands to `gulp develop` (including optimizing openmct.js) that add a great deal of time to starting up the app. If there's anything we can do here to make this sportier, that would be better.

**Comment by akhenry** [comment]
Ah, it seems as though `gulp develop` now invokes `gulp install`, which builds the optimized/minified scripts. Do we really want to develop against the minified scripts? Will make debugging tricky...

**Comment by larkin** [comment]
Think we don't want to develop against minified and we were not doing this anyhow, should revise.
