### ISSUE TITLE
[Examples] Update examples to use 1.0 API, or decommission if no longer relevant

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1272]
The API [is documented on the website](https://nasa.github.io/openmct/docs/api/).
- Should consider changes proposed in #841 
- Where possible, attempt to address #1163

**Comment by VWoeltjen** [comment]
Per API tagup 1/12/2017, leaving this as help wanted for now. May want to use this to exercise new APIs, but better to do that with production code. Tutorials are a higher priority for developers in any event (#1248)

**Comment by larkin** [comment]
merging to #846
