### ISSUE TITLE
Allow Clocks to set Time Zone

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1273]
Add an ability for Clock objects to have configurable time zones.

<img width="1138" alt="warp overlay create clock" src="https://cloud.githubusercontent.com/assets/1056412/19606250/eeb9eb9e-9775-11e6-89a5-3e973c369d51.png">

**Comment by larkin** [comment]
@charlesh88 any design here? time zone is a loaded term: you have the simple UTC offsets as per ISO-8601, or you have the [IANA time zones](https://en.wikipedia.org/wiki/Lists_of_time_zones) which are updated frequently and contains some 500 plus entries.

**Comment by larkin** [comment]
Per tag-up, IANA time zones per [moment.js timezone](http://momentjs.com/timezone/) library is a good way to go here.

**Comment by charlesh88** [comment]
The key here is to keep this simple. Suggest 

1. A scrolling tabular list, sortable and filterable by abbreviation, name, UTC offset, etc. 
1. Alternately, a single text input with auto-suggest that ties into the IANA values array and matches against abbreviation, name, UTC offset, etc. 

The first is more browsable but takes up more space, the second is vice versa. @larkin Thoughts?

**Comment by larkin** [comment]
@charlesh88 drop down select with typing autocomplete?  Browsable and small footprint.

![screen shot 2017-01-27 at 1 00 07 pm](https://cloud.githubusercontent.com/assets/226503/22387484/ac87f820-e490-11e6-9ad5-f66ee604ccfc.png)

**Comment by dhrubomoy** [comment]
I used the Moment Timezone library to add options to set the timezone via dropdown. I simply used the select control. [Here](https://github.com/dhrubomoy/openmct/commit/3984e30ab238f938b0cbbf2ae6321d02b8e21b8c) is my code change if you want to take a look.

![screen shot 2017-02-18 at 1 21 06 pm](https://cloud.githubusercontent.com/assets/12648587/23537618/49a12454-ff9b-11e6-978d-00e49185e6b9.jpeg)

I was wondering if you had any advice on how should I proceed in order to add autocomplete with dropdown option. Should I use a third party library? I have tried using the HTML datalist tag, but it is very slow and doesn't look good UI wise.

**Comment by akhenry** [comment]
@dhrubomoy Looks like a good start, based on your screenshot.

@charlesh88 Do you have any suggestions on how we might achieve an auto-complete dropdown ala @larkin's suggestion? Is this feasible, or should we go for lower-hanging fruit?

**Comment by dhrubomoy** [comment]
I can try to help with this feature if its ok. Just one question, should I write the `autocomplete-dropdown` control from scratch or I should use a third-party library?

**Comment by charlesh88** [comment]
That's awesome @dhrubomoy thanks! Also, wish I'd mentioned this earlier, but we'd prefer that the zone default to UTC if it doesn't already - that's the most common setting for NASA users by far.

**Comment by VWoeltjen** [comment]
Third-party dependencies add some overhead for us, although that is still often preferable to maintaining custom code. If the amount of code can be kept low (<50 LOC, ballpark) then it would be simplest to do something custom. In either case, if it's an `autocomplete-dropdown` that can be reused elsewhere for different form items, that would be useful to us going forward as well.

**Comment by dhrubomoy** [comment]
Thanks for the advice. Just made a pull request. I decided not to use any third-party library for autocomplete and implemented one from scratch. Then used it to allow users to set timezone in clock. The default timezone is UTC. Here is a screen capture:

![timezone_](https://cloud.githubusercontent.com/assets/12648587/26533317/516843a0-43e5-11e7-98bf-d709ebaaf601.gif)

Let me know if I can improve the code further. Thanks :-)

**Comment by larkin** [comment]
Implemented in https://github.com/nasa/openmct/pull/1595.
