### ISSUE TITLE
Cannot discard changes by clicking "X" in edit mode.

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1277]
Discovered Testathon 2016-10-21.
1. Navigate to an object that cannot contain objects, such as a telemetry point or packet in WARP.
2. Create a plot, table, or other object that takes you into edit mode.
3. Press "X" button next to "Save As" button.

Expected result: something happens
Actual result: nothing happens

**Comment by larkin** [comment]
@akhenry this appears to be resolved by https://github.com/nasa/openmct/pull/1301.  I will take this issue and close it when #1301 is merged.

**Comment by larkin** [comment]
Should be closed with either #1301 or #1316, closing to verify.

**Comment by charlesh88** [comment]
Testathon 11-09-2016: verified NOT fixed.
- Navved to this [telem elem](https://hulk.arc.nasa.gov:8080/#/browse/mine/843c1e8c-e0ea-45ab-9545-dc0c5837186d/95074094-682d-45e9-890b-9857d91ab955/0f455f29-e1b2-44d5-be0b-522add9d1046/warp:epsio_thm_dat.sequencecount?view=plot)
- Clicking "X" still does nothing.

**Comment by VWoeltjen** [comment]
Looks like a different root cause though (there's an error being thrown that looks new); filed https://developer.nasa.gov/ResourceProspector/warp/issues/248 with more info

**Comment by larkin** [comment]
Considered verified, going to track follow-up in the warp issue for the new issue.
