### ISSUE TITLE
Inconsistent search indexing

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1279]
Suspect this may be a bug with new API, different behaviors reported by Charles, Victor, Andrew.  Search results do not include the things we expect them to.  Appears that indexing is not occuring, probably due to a change in how roots are configured.

Also reported in https://developer.nasa.gov/ResourceProspector/warp/issues/240.

**Comment by larkin** [comment]
@larkin to work on, @VWoeltjen to keep an eye out for potential causes as he looks at related code

**Comment by larkin** [comment]
Can no longer reproduce as of https://github.com/nasa/openmct/pull/1292 in the default configuration.  The reason for this is that the GenericSearchProvider depends on the model service, which does not have a compatibility adapter with the new API.  If an object provider is registered with the new API, but has no matching model provider, then the object will not get indexed.

As a compatibility layer I think it is reasonable to add a model service decorator similar to the missing model decorator that detects missing responses and attempts to load the model from the New API.  This will resolve WARP #240.

**Comment by charlesh88** [comment]
Testathon 11-09-2016: I don't believe this is fixed, see 3rd bullet below.

Tested using recipe from original WARP issue:
- Search for a known Packet like EPSIO via "EPS". Packet successfully found.
- Search for a known Packet with "bit". EPSIO_BIT successfully found.
- **Search for type "Packets" or "Real-time Telemetry Table" with single character (like "a", "e", etc.): no results found**. 

Given that single letter searches do return other object types (like Layouts) and are not for Packets, Tables, etc. I think this is not yet fixed.

**Comment by larkin** [comment]
@charlesh88 did you see a "more results" or did you see no results at all?

**Comment by larkin** [comment]
Reopening for further investigation, will determine if this is the same problem or something different.  Expect to carry this bug to roddenberry.

**Comment by charlesh88** [comment]
@larkin I didn't get any results or the "More Results" button.

**Comment by charlesh88** [comment]
@larkin to look at this - is a dupe of #132?

**Comment by larkin** [comment]
Noted in testathon 4/20/2017: now that we're not using elasticsearch persistence and thus don't have the elasticsearch search provider, the results are very useful.  Going to close and remove unverified label.

There is a separate issue for separating (or just removing) the elasticsearch search provider.

**Comment by larkin** [comment]
closing, resolved.
