### ISSUE TITLE
Duplicate failure due to network error looks like success.

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1281]
1. right click on an object, select duplicate
2. select a location to duplicate the object to (but don't click ok).
3. simulate network issues (e.g. in chrome dev tools, select checkbox for "offline", or disconnect network cable).
4. press "ok" on duplicate window.

Expected result: error is displayed and duplicate object is not visible in tree.
Actual result: error is displayed and duplicated object appears in tree.  Furthermore, duplicated object can be edited but changes will be lost upon refreshing page.

May be a side effect of #825, unsure.

**Comment by larkin** [comment]
I imagine this also applies to all entanglement actions.

**Comment by larkin** [comment]
To be discussed in Robinson sprint planning.

**Comment by charlesh88** [comment]
Can't believe I'm the first in with this: two wrongs *do* make a right.
