### ISSUE TITLE
Fixed Position should have default values for grid size

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1285]
The Fixed Position object should have default values for grid size that match those hardcoded into the editor.  Otherwise the user may feel the need to specify the values when saving the object, which can completely screw up their display.

User flow that can be confusing:
1. user creates fixed position display (they are now in edit mode)
2. user adds a number of elements and positions them how they like.
3. user presses "save as," and notices that they can specify a layout grid and that it is currently blank, so they type in some random numbers and save it.
4. the grid resizes due to the new numbers and the entire display looks broken.

It's not clear that specifying grid size in step 3 is optional, and it's also confusing because there is a default value but the user has no idea what that value is.  We should properly set the default on the model.

Reported in https://github.com/nasa/openmct/issues/1108#issuecomment-255796675

**Comment by larkin** [comment]
Verification Steps:

1. create fixed position display (they are now in edit mode)
2. press save as.
3. layout grid should be defined as 64px by 16px by default.  Previously these fields were blank.

**Comment by charlesh88** [comment]
Testathon 11-09-2016: Verified fixed

**Comment by VWoeltjen** [comment]
Verified fixed testathon 20161109
