### ISSUE TITLE
[Windowing] Evaluate and prototype technical solutions for multi-window designs

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1290]
Support #1289 by researching, evaluating, and prototyping technical solutions for providing suitable support for using Open MCT in dense multi-windowed environments.

Specific actions here will largely depend on design inputs from #1289, but as a starting point, there's interest in an [Electron](http://electron.atom.io/)-based native app as a basis for a solution, so it will be useful to understand any technical challenges or benefits inherent to that approach.

**Comment by larkin** [comment]
Work on evaluating Electron and the alternative (not using it) to solve for use cases presented in #1289.

**Comment by akhenry** [comment]
Closing this for now. A summary google doc has been produced and distributed to team members. Also an Electron based prototype has been built and also shared with the team.
