### ISSUE TITLE
[Build] start using package.lock

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1291]
Since the start of this project, we've been using `node-sass` which was built using C++ compiled binaries. This caused us to have issues when using npm to build in different environments on different system architectures.

We've since moved to the latest dartsass package based on https://sass-lang.com/blog/libsass-is-deprecated/

Now that we've made the migration, it's time to add package-lock back into our process and update our CI tooling.

- [x] Add package-lock back into our repo
- [x] Update .npmrc file
- [x] Update CircleCI to use `npm ci` instead of `npm install`
- [x] Update GHA to use `npm ci` instead of `npm install`
- [x] Update any documentation

**Comment by larkin** [comment]
Updated text to better describe issue, think it is still relevant.

**Comment by akhenry** [comment]
This cropped up again recently as https://github.com/nasa/openmct/pull/1898

**Comment by austinjalexander** [comment]
Committing `package-lock.json` is a standard ([and official](https://docs.npmjs.com/files/package-lock.json)) practice in the Node/NPM world.

If OpenMCT isn't going to include it for some set of reasons, it would be beneficial to users if that decision and the reasons were documented.

**Comment by factoidforrest** [comment]
Hey, I work for a security company that analyses open source frameworks' supply chains. 

You NEED a package-lock.json, this is sketchy. Install, commit, done.

**Comment by akhenry** [comment]
Thanks all for your feedback. As well as the reasoning already provided in the original issue, some of our legacy build tooling had platform-specific requirements that package-lock was interfering with, which was causing build failures across different environments.

Our build tooling has changed and we should be able to build reliably across all of our environments now, so we will re-enable package-lock in this project for folks building from source. 

We continue to encourage you to use our [pre-packaged npm releases](https://www.npmjs.com/package/openmct) unless you're contributing code to the project.
