### ISSUE TITLE
[API] type registration not functional

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1294]
It seems that whatever adapter code was previously responsible for type registration in the new API is no longer present-- I can't find any code that would actually define types as expected.  Nor does any of the code in the Type API work; so all of the tutorials from #999 are broken.

**Comment by larkin** [comment]
Looks like Type.prototype.toLegacyDefinition (from [Type.js](https://github.com/nasa/openmct/blob/b4dc50295c33cb1cf25d31ff580fabcde74111ec/src/api/Type.js)) and the [MCT type method](https://github.com/nasa/openmct/pull/999/files?diff=unified#diff-99bf719c45547a2a6e959e529854b8a0R106 ) changed significantly between #999 and #1212.

Functional code is just missing, not sure how it happened.

**Comment by akhenry** [comment]
Might be related to https://github.com/nasa/openmct/pull/1212#pullrequestreview-2630121

**Comment by larkin** [comment]
For my own review I've generated a diff comparing the API as proposed in #999 to the one implemented in #1212, to see if there are any other changes to review.  Others can see it here: https://github.com/nasa/openmct/commit/3b86e02ed378377de821557af5a87a2c5f335ae7

**Comment by VWoeltjen** [comment]
__Note for testing:__ This bug is not observable from the UI, but the solution effects type-handling, so want to test around that for regressions (e.g. by creating various different types.)

**Comment by charlesh88** [comment]
Testathon 11-09-2016: Created one of all object types, didn't encounter any problems.
