### ISSUE TITLE
Limit violations in Fixed Position should encompass both title and value

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1299]
In plot legends and tabular view, limit violation visualizations encompass the entire element including the title/label and value elements, but in Fixed Position the violation only displays attached to the value. This should be standardized for consistency.

**Comment by larkin** [comment]
I believe in fixed position this is intentional as the display could be dn or eu and limits can be evaluated individually for dn and eu.

Combine this with the request for the ability to display multiple configurable telemetry values per point (#1300) and this might not be a change we want to make.

**Comment by larkin** [comment]
@charlesh88 point for discussion, different states on different values in a table:
![demo- limit states](https://cloud.githubusercontent.com/assets/226503/20278986/a06d73fe-aa5b-11e6-98ae-c2e6fc4eeeac.png)

**Comment by charlesh88** [comment]
@larkin As usual, raising excellent points. Could be we want the opposite of this issue: violations perhaps should only encompass the value and not the title, when the title can have more than one value associated with it. 

Parking this for now pending coming enhancements to Fixed Position (re. #1300) and plots.

**Comment by charlesh88** [comment]
After more discourse elsewhere, it's becoming clearer that the limit violation should NOT encompass the title, in that in many instances a telem element my be displaying more than one value, with only a single value in violation. Closing as won't fix.
