### ISSUE TITLE
Object title does not always update.

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1303]
1. open Open MCT
2. navigate to an object.
3. REFRESH the application (using the deeplink, such that when it reloads you are viewing the same  object).
4. right click the object in the tree and edit properties.
5. Change the name of the object and save it.

expected result: the main title of the object (in the view area) will update to reflect the new name.
actual result: the name does not update.

Note that if you navigate to the object by clicking in the tree, and then rename the object, it will be properly renamed in the main view.

If you navigate within the application by url instead of clicking a navigate button, this same behavior occurs.  There seems to be some juju to the navigate command.

**Comment by larkin** [comment]
This same interaction happens with views, for instance the "items" view of a folder exhibits the same behavior: navigate via URL and change detection doesn't work  (e.g. remove child from tree, items view will not update.)  If you navigate by clicking in the tree change detection works properly.

**Comment by VWoeltjen** [comment]
Observe on console `angular.js:12416 Error when notifying listener: Cannot read property 'identifier' of undefined` when this happens, imagine this is related

**Comment by VWoeltjen** [comment]
Found and addressed root cause of error, still seeing bug as described in original issue.

**Comment by VWoeltjen** [comment]
At least in the case of this issue, removing the `$watch` on the `modified` timestamp and replacing it with a proper mutation listener resolves symptoms. Doesn't help with inspector. Think this is probably a reasonable solution in this context; new API expects views to listen to mutation, legacy-style views expect to be kept up-to-date, and `mct-representation` is only present at this point to support those legacy views.

**Comment by larkin** [comment]
Seems reasonable and in tracing the code I think it ends up having the same impact as the previous solution, as that was watching modified which is set every time mutation occurs.  Only difference is that refreshCapabilities is triggered per mutation instead of per digest.

This could be premature optimization, but...

By listening for mutation you guarantee that the model stays in sync (per SynchronizingMutationCapability).  This is only true if you always access it with `getModel()` (instead of storing a reference).  So we could get by with only updating `$scope.model` on mutation and not running the full `refreshCapabilities`.  Unless there is a case where mutation causes the capabilities associated with a model to actually change?

**Comment by VWoeltjen** [comment]
Good concern to raise!

> Unless there is a case where mutation causes the capabilities associated with a model to actually change?

In principle they can. Given that the prior code did a `refreshCapabilities` on every change to `modified`, it should be running just about as often now, so I wouldn't expect (and don't really see) a performance difference, whereas failing to invoke `refreshCapabilities` might introduce further regressions.

It's definitely heavier than it needs to be, but that's not necessarily a problem in every case. Would prefer to optimize by migrating UI components to newer subscribe-to-what-you-need paradigm on an as-needed basis (similar to what we did for the tree) or at least [opportunistically](https://github.com/nasa/openmct/issues/1276#issuecomment-258521971)

**Comment by larkin** [comment]
Sounds good-- for correctness keep it simple.  That's the main risk I foresaw that made me preface it as "premature optimization".

**Comment by charlesh88** [comment]
Testathon 11-09-2016: Verified fixed per original bug report replication recipe, using a Timeline.
