### ISSUE TITLE
removed objects come back from the grave

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1306]
1. create a few folders in your root (say, "a", "b", "c").
2. right click and remove each of these folders.
3. create a new folder in your root (say, "d").

Expected outcome: your root will not contain "a", "b", or "c", and will include "d".
Actual outcome: your root will contain all of the folders you deleted in addition to "d".

Note that refreshing after step 2 is equivalent to a silver bullet and ensures "a", "b", and "c" will stay in their graves instead of returning to haunt us all.

Discovered this while hunting another bug, I'm guessing that there is some odd cache behavior going on.
![url](https://cloud.githubusercontent.com/assets/226503/19787620/80c02170-9c58-11e6-8afa-611a0c9aa2f4.jpg)

**Comment by VWoeltjen** [comment]
Appears that root cause is different from #1303, still not sure what that root cause is though

**Comment by larkin** [comment]
#1275 may be related.

**Comment by larkin** [comment]
Going to look into with #1275.

**Comment by VWoeltjen** [comment]
Does look like it is caching related. If I convert the caching model decorator into a caching model provider and adding a basic eviction strategy (see branch `walkers-1306`), I no longer see this issue. However, I do see big performance impacts which can probably be managed by using the cache and/or evicting more smartly. #1275, however, is still reproducible on that branch.

**Comment by larkin** [comment]
@VWoeltjen Aah, there appears to be a race where the object is not actually persisted by the time you navigate back-- you're still seeing the cached version, which seems to be missing the attributes required to properly show actions.

**Comment by larkin** [comment]
Should be resolved with #1316, closing for verification.

**Comment by charlesh88** [comment]
Testathon 11-09-2016: Verified fixed using original zombie-spawning incantation.
