### ISSUE TITLE
[Docs] Add documentation indicating that model providers and taxonomy services should provide location

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#131]
Currently, model providers that provide models with composition and do not provide locations will have all the objects they provide appear as links.

The documentation regarding taxonomy services should include a note indicating that their models should include an accurate location attribute.

Alternatively, perhaps the location capability can add a default location to objects that do not have a location?

**Comment by VWoeltjen** [comment]
I think it makes sense to log a warning if an object _doesn't_ have a defined location, with some advice about how to rectify it. (Probably with some additional logic to make sure this doesn't happen for the root object.) 

Having a note in the documentation (and adding this to tutorials) makes sense too, but could be easy to miss. Putting it into JSDoc for model providers feels a little funny to me (since this is still a non-core facet of the domain object model) but I think that's splitting hairs.

**Comment by larkin** [comment]
Maybe we could take a note from angular and include links to documentation from warnings?

I would like to propose that location and move/copy/link are core functionality at this point, they may still have some rough edges to sand off but they are functionality that is key to having a useful platform.  Not to mention search's dependence on location (and other objects may eventually have the same dependence).

Documentation of key user stories and interactions (a user guide?) would be helpful: how the platform is intended to be used is not well specified.

**Comment by VWoeltjen** [comment]
We may have different meanings in mind for the word "core". I'm thinking somewhat literally of `platform/core`, or less literally of a minimum subset of concepts on which you can build a useful object model. If anything, I'd like to see core (in that sense of the word) shrink.

I think Search is actually a good example of _why_ I want to do better about keeping facets isolated & dependencies clear. Search doesn't really have a dependency on location - some other features depend upon _context_ and weren't fault-tolerant in its absence, and attaching context via location was an expedient way to mask that problem.

Anyway, that's more of a clarification; I don't think adding a note about the `location` property will cause anything bad to happen.

**Comment by larkin** [comment]
Closed as fixed in new API.
