### ISSUE TITLE
[API] Telemetry API not implemented

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1310]
This wasn't functional in #999 but there was a pull request (https://github.com/nasa/openmct/pull/1069) which featured a telemetry provider that worked for fetching telemetry (but not providing telemetry-- still had to use old API for that).  The actual API merged in with API v1 seems to have the same interface but is not functional (e.g. requests which should result in responses do not actually result in responses).

I think Victor or I can work on wrapping this one in the next week or so; not something we have to dive on today.

**Comment by VWoeltjen** [comment]
Per API tagup 1/12/2017 there are some outstanding issues around `TelemetrySeries.getDatum` that @larkin is working through. Also, not sure new API's limit evaluation is actually implemented (@akhenry says it is not)

**Comment by akhenry** [comment]
@larkin Based on above comment, and #1369 being merged, can we close this issue?

**Comment by larkin** [comment]
Sure, closing, have placeholders for rest of work.
