### ISSUE TITLE
Dialog boxes points to empty places at first run

### ISSUE THREAD

**Issue by jkiddo** [nasa/openmct#1311]
When starting the demo and eg. "Navcam Right" is chosen to open it in a new tab, the info boxes are displayed again - this time the do however point to empty places.

**Comment by larkin** [comment]
It sounds like we should not launch the live demo tutorial after opening a display in a new tab.  We can tell if it's being "opened in a new tab" by checking `window.opener`, e.g.

```javascript
if (!window.opener) {
    startTutorial();
}
```

@akhenry is this correct for the live demo?

**Comment by akhenry** [comment]
Addressed by #1321
