### ISSUE TITLE
[Edit] Can't cancel editing without network connection

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1319]
Steps to reproduce (needs a non-local persistence store, e.g. ElasticSearch):

1. Edit a domain object (e.g. a layout)
2. Modify that object (e.g. move some panels around)
3. Disconnect from network (or otherwise make persistence unreachable.
4. Click X to cancel editing.

__Observe:__ Nothing happens.

Expected behavior here needs to be specified, but there needs to be either some meaningful behavior and/or helpful messaging in this case.

**Comment by VWoeltjen** [comment]
Very probably related to the fact that transactions are cancelled by invoking `refresh` to pull domain object models back from the remote persistence store, which cannot complete while disconnected.

**Comment by larkin** [comment]
Happy to defer to Roddenberry.

**Comment by charlesh88** [comment]
I think it'd be fine in this case to quietly revert the object without a message - the user in this case really doesn't need to communicate with the server.
