### ISSUE TITLE
search results ordering is inconsistent and not often usable

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#132]
During the 9/17/2015 testathon, Sarah reported that search results ordering did not make sense.  Searches for hazcam returned Gimbal Layout as the highest match instead of multiple direct matches below.  Searching for things like "el" return many results that do not appear to contain "el". (e.g. every telemetry pan**el**)

At the same time, it was noted that repeating the same search multiple times could return different search results.  I imagine most of this is caused by trying to merge results of two different search ranking algorithms, and race conditions causing them to be merged in different orders.

I would propose a search bake-off in our next testathon, where we get multiple ops users to test two side by side search configurations (generic, and generic + elasticsearch) and get their feedback on which works best.

**Comment by VWoeltjen** [comment]
It occurs to me that there is another possible explanation here, which is that generic search is indexing in the background starting at page load. How long this takes will vary (depending on network, number of objects to index, hardware, etc) but I'm observing times of around ~1min to complete indexing in VISTA. Searches may may definitely give different results depending on how long after page load they occur. (This does not exclude the possibility of race conditions in the merging of search results from multiple providers)

I don't think this can be avoided for generic search, but we could show a little "indexing" notification somewhere while this is happening, and dismiss it when indexing is complete. (Or, more generally, provide some user feedback that search results may be incomplete at that time)

**Comment by charlesh88** [comment]
Testathon 03032016
Mark reporting that typed in criteria and then results are not as expected. For example, entering "NIRVSS degrees" shows items that aren't expected. Entering "degrees" alone has even more unexpected results. 

Bottomline: search needs some love, such that results are expected and predictable.

**Comment by charlesh88** [comment]
![testathon 03032016 search results](https://cloud.githubusercontent.com/assets/1056412/13513999/bc34d63e-e159-11e5-9b7f-dfb9d1ba7d4e.png)

**Comment by charlesh88** [comment]
Notes from tagup 10/26/16
- Show "indexing" in progress related to search when that is happening. @charlesh88: this may needs design.
- Allow advanced search by title, notes, etc.

@larkin Need to break this up into separate issues, then possibly close this one.

**Comment by larkin** [comment]
Note to self, pay attention to https://github.com/nasa/openmct/issues/501 as a potential spin out from this.

**Comment by charlesh88** [comment]
We need to create a new issue for the system to indicate the current status of Search, e.g. it's still indexing when the app starts up.

@larkin to create new issue.

**Comment by charlesh88** [comment]
@larkin to look at this - is a dupe of #1279?

**Comment by charlesh88** [comment]
@larkin Did we create the new issue as mentioned Jan 11, and is this a dupe of #1279?

**Comment by larkin** [comment]
@charlesh88 created issue and closing this.
