### ISSUE TITLE
[API] Composition API issues

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1322]
* ~~The default composition provider [is expecting non existent attribute 'key'](https://github.com/nasa/openmct/blob/dfa459183482c959d7a837c9ee3e9ea099853014/src/api/composition/DefaultCompositionProvider.js#L44) on new style objects. Structure of identifiers may have changed, or it may have just been a mistake.~~ Addressed in open1322, for which a PR is ~~inbound~~ [available](#1328).
* DefaultCompositionProvider makes a [static reference to an instance method](https://github.com/nasa/openmct/blob/dfa459183482c959d7a837c9ee3e9ea099853014/src/api/composition/DefaultCompositionProvider.js#L79) on ObjectAPI. Needs the singleton instance of ObjectAPI from the global MCT instance.

**Comment by larkin** [comment]
@akhenry to log notes and pass issue to @larkin

**Comment by akhenry** [comment]
Dunzo.
