### ISSUE TITLE
[Documentation] Specify object model

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#133]
Draft a specification of the domain object model, as it is intended to behave. This should be written at an intermediate level of abstraction - e.g. concepts like "composition" should be explained, but composition properties/capabilities should not be referenced, as these are implementation details. Should also include an explanation of various actions and their intended effects. Should _not_ include significant references to the user interface; one of the goals here should be to fill the gaps between UI docs (which are focused on appearance, with descriptions of behavior interspersed) and the developer guide. 

UI docs, however, should be primary source material for this. Want to get UX participation in this reviewing and ultimately approving this. 

Finally, while implementation details should be avoided, organizing the document in a manner which will align well with the implementation (e.g. separating out rules/constraints that are likely to be expressed as policies)

**Comment by VWoeltjen** [comment]
Note that it is also desirable to include this in the repository, preferably as Markdown or similar. Should expect to encounter UX issues that can be traced to omissions/shortcomings of the object model, and want to be able to solve for these by amending/revising this specification before making related changes to code (or, concurrently.)

**Comment by VWoeltjen** [comment]
Also, while this shouldn't be tied to closely to UI, having some linkage between this and user stories (or more general usage patterns) that we wish to support is strongly desirable.

**Comment by larkin** [comment]
wontfix due to api changes.
