### ISSUE TITLE
[Plugin] Integrate Open MCT with YAMCS

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1331]
[Yamcs](http://www.yamcs.org/) is an open source mission control system with a web API. Yamcs can ingest CCSDS packets, decom them, and expose the telemetry using a web API. Yamcs also supports commanding and historical telemetry.

Integration between Open MCT and Yamcs would be beneficial to users who are looking to build a low cost ground system with open source software.

@temecom is currently working on a Yamcs telemetry adapter for Open MCT to enable Open MCT to expose parameters and display telemetry from Yamcs.

**Comment by ev1stensberg** [comment]
Working on this. Do you want to modify data as well? @akhenry

**Comment by akhenry** [comment]
@ev1stensberg Thanks again for taking a look at this! This plugin is going to be a HUGE plus for the Open MCT user community. 

At this stage it's sufficient just to get data flowing to the client. Eventually we may want to be able to change settings in YAMCS, send commands to the spacecraft etc. but I'd suggest we focus initially on creating a polished plugin that displays historical and realtime telemetry from YAMCS and go from there.

**Comment by ev1stensberg** [comment]
Gotcha. I've got a lot of URL's to run against, there's a lot of data fetching to be done, so we should discuss how you want to approach this in the future. I've got the `missionDatabase` (MDB) object that contains some telemetry. Can get a quick demo up and running within next week I think, depending on how my week looks @akhenry :) Sent you a email, sorry for spamming :(

**Comment by larkin** [comment]
related to #1701

**Comment by akhenry** [comment]
https://github.com/akhenry/openmct-yamcs
