### ISSUE TITLE
[API] TimeConductor API not mapped to internal time conductor

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1333]
Attempted to use time conductor api via `openmct.conductor`.  It doesn't seem to be linked to the active instance of the time conductor-- everything returns undefined or errors unceremoniously.  

In the environment I'm testing in I have activated `platform/features/conductor-v2/compatibility` and `platform/features/conductor-v2/conductor`

May be "not-a-bug", need to investigate further.

**Comment by akhenry** [comment]
Yeah I found this when I tried to use it from the new API as well. There is a duplicate TimeConductor object that appeared as part of the new API. I actually fixed this in #1287 (but failed to mention it in the description), so it will be resolved when that's merged.

**Comment by larkin** [comment]
Great! Closed with #1287.
