### ISSUE TITLE
examples of high volume, real time data?

### ISSUE THREAD

**Issue by mg1075** [nasa/openmct#1334]
...just found out about this project and while looking through the demo site, it seems all the real time data is coming in at a rate of about 1 point per second in the canvas charts. Is there a part of the demo, or another example elsewhere, that shows real time data coming in at a rate of a hundred or more points per second (the kind of challenge [smoothiecharts](http://smoothiecharts.org/) was designed to handle)?

**Comment by larkin** [comment]
@mg1075 Welcome!  Our plots use webgl and are optimized for high data volumes, though as you mention, our demos are running at low data rates.  It wouldn't be hard to write a telemetry provider that generates data at a higher rate and add it to the live demo.

**Comment by akhenry** [comment]
Good idea. I've created [an issue](#1337) (with the satisfying number of #1337 ) for this and tagged it as help wanted.

**Comment by larkin** [comment]
Closing in favor of #1337.
