### ISSUE TITLE
Telemetry Adapter tutorial not working 

### ISSUE THREAD

**Issue by manuel-vh** [nasa/openmct#1336]
Hi, I'm unable to run  tutorial example of telemetry adapter. It seems doc is not updated to match last openmct release.  Can any body provide me with  simple working example?
Regards

**Comment by akhenry** [comment]
Hi @manuel-vh. Thanks for raising this, and apologies for the issues you've experienced with the tutorials. I have pushed a branch today (currently awaiting review and merge) that fixes the issues with the telemetry adapter tutorial (along with some other tutorial issues). You can either wait until it gets merged into master and appears on the website at https://nasa.github.io/openmct/docs/tutorials/ or feel free to use the fixed tutorials [directly from the branch](https://github.com/nasa/openmct/blob/f85595665f4b1434b894f97f8338473c8b902643/docs/src/tutorials/index.md).
