### ISSUE TITLE
[Live Demo] Create a high volume mock data source

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1337]
The [current mock data source](https://github.com/nasa/openmct/blob/2ef9820b4893ce85727a5ac066c0aa2510bb51e7/demo/src/telemetry/DemoTelemetryProvider.js) in the live demo has very low update frequency (1Hz). It would be useful to have a data source that produces data at a higher rate, on the order of 100's of Hz. 

Optionally, the frequency value could be user definable as an attribute at creation time ala the [period attribute of the Sine Wave Generator](https://github.com/nasa/openmct/blob/master/example/generator/bundle.js#L95) (with some sensible default).

**Comment by larkin** [comment]
I like the idea of configuration at creation time similar to how the SWG works.

Also, putting the generator into a webworker would help us ensure high data rates that are not bound to the current angular digest cycle as they are with $timeout and such.

**Comment by mg1075** [comment]
@larkin - you wouldn't want to use a library for websockets like socket.io?

**Comment by larkin** [comment]
@mg1075 nice thing about webworkers is we don't need a server-- can run the demo in a browser without a backend. 

When it comes to websockets (which we use for real data sources), we tend to run those raw as the websockets API in modern browsers is fine for our uses-- no real benefit in using socket.io. And we do often run websockets in a webworker as a performance optimization when there is heavy processing of incoming data formats.
