### ISSUE TITLE
[Tables] Autoscroll on real-time tables does not work with high data rate source

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1355]
The real-time table auto-scrolls to the bottom of the table when new telemetry is received. With high data rate sources this appears not to be working.

The reason may be that [auto-scroll](https://github.com/nasa/openmct/blob/a920220122f8b0d84f318601fba04504b85c7fbb/platform/features/table/src/controllers/MCTTableController.js#L157) is battling with the [onScroll](https://github.com/nasa/openmct/blob/a920220122f8b0d84f318601fba04504b85c7fbb/platform/features/table/src/controllers/MCTTableController.js#L208) behavior that disables auto-scroll when the user scrolls away from the bottom. This could be finessed to differentiate between when a user initiated onScroll and when it was initiated by code

**Comment by larkin** [comment]
believe this is fixed.
