### ISSUE TITLE
[Navigation] Navigation confirmation not working with any objects

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1360]
Currently openmct will allow navigation away from a dirty object without a warning. 

eg. 
1. Edit a display layout
2. Drag in a telemetry point
3. Click on another object to navigate away
4. Application merrily navigates to the other object without a warning

**Comment by akhenry** [comment]
I believe it's due to https://github.com/nasa/openmct/pull/1342/files#diff-d813a2ca49c8390e9da3c02c1a2c632dL97

Previously the NavigateAction was being used from the BrowseController which checks for dirtiness and displays the warning. Without the NavigateAction, dirtiness checking is not occurring.

**Comment by larkin** [comment]
@akhenry Ah, so this is interesting.  It still can occur but it depends on how you got to the page.  I think there is stills some instances where "incomplete navigation events" occur which get the application into a weird state.  I'll dig into it further with some instrumentation I was previously using to detect incomplete nav events.

**Comment by akhenry** [comment]
@larkin great, thanks for taking a look!

**Comment by charlesh88** [comment]
Testing notes for Testathon 02-07-2017:

1. Edit a display layout
1. Drag in a telemetry point
1. Click on another object in the tree to navigate away
4. Observe: the application display the unsaved changes warning dialog, and should NOT merrily navigate away.

**Comment by charlesh88** [comment]
Testathon 2017/04/20 Verified fixed.
