### ISSUE TITLE
[Failing Test] Save As action test fails on CI

### ISSUE THREAD

**Issue by BogdanAlexandru** [nasa/openmct#1361]
And locally.

> _The Save As action in order to keep the user in the loop notifies if saving succeeded_
> Expected spy notificationService.info to have been called.,Expected spy notificationService.error not to have been called.

The test was brought in by https://github.com/nasa/openmct/pull/1258

The pre-merge CIs worked but were old. Looking into what happened.

**Comment by akhenry** [comment]
@BogdanAlexandru Thanks for picking this up quickly! Appreciate it.

**Comment by BogdanAlexandru** [comment]
This changed paired with mine introduced the failure:
https://github.com/nasa/openmct/commit/2708562872aa2f8e78450fb408ebaabb449bc0b0

```
.then(function () {
     return fetchObject(clonedObject.getId());
);
```

Likely having to do with the absence of `getId()` on the cloned object (just an assumption based on a couple of test runs w/ changes, didn't hook up a debugger yet), so a dig thru the mocks to see why is in order. It's midnight here so I'll leave this for tomorrow.

**Comment by akhenry** [comment]
@BogdanAlexandru I jumped in and fixed this in #1365, sorry about that, I know you were working on a fix. I'm about to go on vacation and didn't want to leave the trunk in a non-building state.

Your diagnosis was right, it was missing a getId on the mock object. There was also a method on the `CopyService` that needed to be mocked.

**Comment by BogdanAlexandru** [comment]
@akhenry No worries; though the fix on my side was submitted in a PR several hours ago here: https://github.com/nasa/openmct/pull/1363

Yours looks better so I can close my PR if it goes in.

**Comment by akhenry** [comment]
Gah! I totally missed this! I didn't get an email notification for some reason. Shows I've become too dependent on GH's email notifications...

I'm going to merge yours since it was first, and they're basically the same.

Thanks again.
