### ISSUE TITLE
[API] Adapter to make new Telemetry API providers available to legacy telemetry consumers

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1364]
To allow old-style plugins to continue to work, e.g. lad, autoflow, fixed position.

**Comment by VWoeltjen** [comment]
May defer until needed, we don't have any new-style telemetry adapters _yet_. It could prevent someone from using the API, however.

Should also consider cost of implementation; this is a nice short-term support solution but will be temporary, so may be more effective in the long-run to just refactor views to use the API and make this issue obsolete.
