### ISSUE TITLE
Display Layout is not saving child positions

### ISSUE THREAD

**Issue by psybox** [nasa/openmct#1367]
I have created a Display Layout with Telemetry Panel, Timer and and Timeline, but they are all stacked.
I tried to edit the layout and change the positions of the children components and save it but it stills show the components stacked.

**Comment by BogdanAlexandru** [comment]
Are you running off the latest master? Tried to repro it myself by creating a Display Layout and then the children you indicated, and repositioning them after they're stacked + saving works.

**Comment by psybox** [comment]
Yes, I'm running 0.12.1-snapshot, I gonna try create another Display Layout and do the desbribed test.

**Comment by psybox** [comment]
I tried again and got the same results. There is something that I can do to get more info?

**Comment by larkin** [comment]
Does this occur every time or only infrequently?  (try loading the application from the base url).  I thought I experienced similar behavior yesterday but couldn't reproduce it.

**Comment by psybox** [comment]
I installed today morning, so for me its occurs every time, I wanna try other possibilities to see what happens.

**Comment by psybox** [comment]
I tried many combinations of components but it still occurs.

**Comment by psybox** [comment]
I am using Opera, I gonna try on Chrome.

**Comment by psybox** [comment]
Don't works too.

**Comment by larkin** [comment]
I can verify it's not working locally, expect it to be a regression from https://github.com/nasa/openmct/pull/1366.  Going to investigate further.

**Comment by charlesh88** [comment]
Testathon 2017/04/20 Verified fixed.
