### ISSUE TITLE
Add Session Timestamps || Hide Tooltip Option

### ISSUE THREAD

**Issue by ev1stensberg** [nasa/openmct#1380]
## Current Behaviour:

When entering the OpenMCT app, you need to click your way through the tooltip section.

## Target Issue/Solution:

Add "hide tooltip" or check the session of the user to see if he/she has previously visited the page

**Comment by ev1stensberg** [comment]
Also, https://nasa.github.io/openmct/docs/guide/#overview under "Declarative Services component model. " has to be changed. It's broken

**Comment by charlesh88** [comment]
@ev1stensberg Just to be clear: believe by "tooltip" you're referring to what we call The Tour, that stems off the website, at https://openmct-demo.herokuapp.com/#/browse/mine/88a26104-8bd5-445d-8b57-10b567d2823d?view=layout.

There is a pre-existing close "x" button in each tour step bubble that cancels the tour; but perhaps that's not apparent enough. A button, in the first bubble only, that reads something like "Not Now" and that performs the same action as the close "x" might be good.

**Comment by akhenry** [comment]
Might be worth having two options - "Not now" and "Never" which remembers their answer so there's a way of permanently dismissing it.

**Comment by larkin** [comment]
moved to https://github.com/nasa/openmct-demo/issues/4.
