### ISSUE TITLE
[example] Examples that modify taxonomy aren't working but should be

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1384]
In trying to get my styleguide bundle project (see #1233) back up to speed, I merged the latest master into my [last working commit](https://github.com/nasa/openmct/commit/a01b3a39b47fbbd09eb468213365d78fb9acc33b) and on doing so my styleguide stopped manifesting properly in the tree. Digging further, it seems as though all examples that create a model don't seem to be working. Here's what's displayed when the scratchpad and taxonomy examples are enabled in a vanilla version of latest master:

<img width="519" alt="screen shot 2017-01-09 at 1 46 18 pm" src="https://cloud.githubusercontent.com/assets/1056412/21784754/bfe88dee-d671-11e6-8714-1723d9ec6072.png">

Note that there are no console errors, and items were included in both defaultRegistry.js and index.html.

**Comment by VWoeltjen** [comment]
`git bisect` says this was introduced in 73b3ae72649a56366583a119e8f1bb3a57b82b2a

Looking into that diff to understand the direct cause.

**Comment by VWoeltjen** [comment]
That commit removes the RootModelProvider, which in turn makes the `roots` extension category unsupported. Examples are still using this, as is the style guide.

Will look at adding a `roots` adapter if it is very lightweight; otherwise, think we should update these `roots` users to use the new API.

@larkin - thoughts?

**Comment by larkin** [comment]
@VWoeltjen that commits changes the functionality of the roots extension category but doesn't completely remove it.  Instead, it separates declaring a root from providing a model, which leads to the new API, where in you register roots (ids or promises for ids) and an object provider (if necessary).

For old-style plugins the correct thing would be to register both a root and a model ([see my-items bundle changes](https://github.com/nasa/openmct/pull/1338/files)).

I could see us porting the "models" extension category to a new "static model" registry, but generally prefer less API surface.

**Comment by VWoeltjen** [comment]
Ah, makes sense. Agree with not adding a new registry for this. I think there could be utility in providing some base classes for ObjectProviders for simple cases like scratchpad, but that's more of a design note.

For this issue, I'm thinking I'll update `examples/taxonomy` and remove `examples/scratchpad`. The latter is not really representative of anything useful at this point.
