### ISSUE TITLE
[Build] Remove phantomjs-prebuilt dependency

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1387]
After various build issues related to PhantomJS (see [this comment](https://github.com/nasa/openmct/pull/1385#issuecomment-271436153), or #1177), would like to switch to running tests in Chrome.

**Comment by cseale** [comment]
I can look at this

**Comment by BogdanAlexandru** [comment]
This issue should've been closed once the PR got merged, right? Nothing else to do for it.

**Comment by VWoeltjen** [comment]
> This issue should've been closed once the PR got merged, right? Nothing else to do for it.

Indeed! Thanks!
