### ISSUE TITLE
Plots are sometimes pixelated

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1393]
Migrated from WARP repo https://developer.nasa.gov/ResourceProspector/warp/issues/103

<p>See <a href="https://trunk.arc.nasa.gov/jira/browse/WTD-852" title="[Plot] Plot is occasionally misaligned and pixelated" class="issue-link" data-issue-key="WTD-852"><del>WTD-852</del></a> for background. Going back and forth to edit mode from a telemetry panel can result in plot becoming pixelated. This appears to be due to Chrome's WebGL implementation choosing to downscale the buffer size for the canvas, likely because available video memory is running low.</p>

<p>This behavior is useful and (now that alignment is fixed) generally desirable in this situation. However, this situation does occur more frequently than one would expect - there is probably something that can be done to release these contexts or to encourage Chrome to release these earlier in order to reduce usage of video memory (assuming that is why this is occurring.)</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-856
Originally created: Mon, 9 Feb 2015 16:58:53 -0800
Updated: Thu, 21 Jan 2016 15:12:15 -0800

Migrated comment, from @plricha1:
<blockquote>
<p>The "browser not returning the expected size" behavior occurs when the computer is out of memory and occurs when too many contexts exist (perhaps due to not being garbage collected).  In this situation, any canvas that exists will be incapable of getting the requested size until the garbage collector runs.</p>

<p>Some potential work-arounds:</p>

<p>1. fake "release"  the context.  Setting the canvas size to 1x1 on scope destroy could theoretically release video memory and make more memory available for future contexts.</p>

<p>2. use an object pool for webgl contexts so that we're not using the garbage collector to clean them up-- instead we manage the lifecycle of a webgl context ourselves.</p>
</blockquote>

**Comment by charlesh88** [comment]
Still an issue?

**Comment by larkin** [comment]
Believe this is fixed in 1557.  Closing.
