### ISSUE TITLE
Allow copying of tick values

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1394]
Per Mark Shirley: tick values should allow copying to the clipboard - in plots (for example) CSS currently disables user-select; this may be an oversight with this style being applied to the entire plot element. Time Conductor and other relevant displays should be examined to ensure that ticks can be copied.

Note that this doesn't intend to solve for the problem of truncated tick labels (like ...00:00:05Z).

**Comment by charlesh88** [comment]
Digging into this further. `user-select: none` is not being applied to tick elements in plots or elsewhere, but the ticks can't be selected for copying. Appears as though this may be due to their dynamically updating nature. The same is true of the clock status element in the Status bar.

Moving this into the backlog for now pending higher priority being assigned to this.

**Comment by larkin** [comment]
Fixed in #1557.  Ticks can now be selected as they are not getting thrashed by angular.
