### ISSUE TITLE
Review new telemetry registration API

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1397]
Based on discussions in API tag up, we'd like to review the new telemetry API and make a few changes:

* [ ] Ensure new telemetry provider registration can override legacy provider
* [ ] use separate providers for "subscriptions" and "requests" as they generally have very different semantics.
* [ ] remove strategy and lean on "canProvideTelemetry" (by passing request objects) for differentiating providers by strategy.

**Comment by ev1stensberg** [comment]
@larkin One thing I've noticed with the new API is that it's impossible for me to do something like `openmct.objects.addProvider('example.taxonomy', YamcsProvider);` with `$http` injected. Is it a workaround for that? Besides using `legacyRegistry`, which doesn't seem to play very well without a bundle in `src/plugins/yamcs` (from my PR on #1331 )

**Comment by larkin** [comment]
@ev1stensberg Correct-- we're moving away from angular (and any specific framework) for the new API.  So plugins should include their own http library.

The tutorial has a [simple http library](https://github.com/nasa/openmct-tutorial/blob/master/lib/http.js) you can use, or you can utilize a [fetch API polyfill](https://github.com/github/fetch), or something else.

**Comment by ev1stensberg** [comment]
@larkin Got it. What about other thing people have been using injection for, such as `$q` ? I'm also curious to know why you've discarded injections like in the old API, as we're thinking about the same approach at [webpack](https://github.com/webpack/webpack-cli) for code that isn't accessible on our end ( which is too hard to narrow down with scaffolding )

**Comment by larkin** [comment]
@ev1stensberg instead of `$q`, use `Promise`.  For all such services... use the standards based option.

We discarded angular DI because it isn't necessary and distracts from the core purpose of Open MCT.  It also had the unintended side effect of exposing all of the internals of the application as APIs-- which was impossible to maintain.

**Comment by ev1stensberg** [comment]
@larkin Right, got it. Do you have `http` implemented in `openmct` yet, or should I install & import  it from `bower_components`? ( relative to the yamcs PR )

**Comment by larkin** [comment]
Done, as implemented in Tutorial.
