### ISSUE TITLE
Possible memory leak in idle app

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1401]
Steps to reproduce
1. Navigate to the app's default route (eg. http://localhost:8080/#). You should be taken to My Items, a folder view.
2. In dev tools go the timeline tab, and hit record
3. Trigger garbage collection (the trash can in the Timeline tab)
4. Wait a while and do nothing (~100s should do it). It's important to keep the tab in focus though, otherwise setTimeouts won't happen.
5. Trigger garbage collection again
6. Heap does not return to original usage. Instead, looks something like this -

![screen shot 2017-01-12 at 16 31 04](https://cloud.githubusercontent.com/assets/4215777/21914000/28771338-d8e5-11e6-89bd-20574dd49524.png)

Sawtooth shape is due to regular minor garbage collections. Additionally there is one full GC at the start triggered manually, and two full GCs (triggered twice manually for good measure) at the end. Despite the two full GCs heap allocation does not return to its original size.

**Comment by ev1stensberg** [comment]
- https://github.com/andywer/leakage

**Comment by larkin** [comment]
Pretty sure this is the sinewave generator, which accidentally keeps references to unsubscribe functions.

**Comment by unlikelyzero** [comment]
This is still an issue

**Comment by scottbell** [comment]
I left "My Items" running for ~30 minutes, and 805 kbytes of new memory allocated (big blue line before is garbage collection):
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/9853862/175537936-69f273b5-4c4e-4b12-b638-660b97748bea.png">

Here's the heap snapshot:
[Heap-20220624T143929.heaptimeline.zip](https://github.com/nasa/openmct/files/8976198/Heap-20220624T143929.heaptimeline.zip)

**Comment by scottbell** [comment]
Ran it again and saw ~350 kbytes of growth over ~30 minutes:
<img width="1312" alt="Screen Shot 2022-06-24 at 3 47 06 PM" src="https://user-images.githubusercontent.com/9853862/175549076-39a63ed5-dbeb-47d4-b29b-23e20d433826.png">
[Heap-20220624T154733.heaptimeline.zip](https://github.com/nasa/openmct/files/8976665/Heap-20220624T154733.heaptimeline.zip)

@akhenry looks pretty minimal to me?

**Comment by unlikelyzero** [comment]
@scottbell we have an automated test for this. Let's sync out of band

**Comment by akhenry** [comment]
Yeah just having dev tools open is enough to cause some degree of leakage. Is there anything suspicious in those arrays?

**Comment by unlikelyzero** [comment]
@akhenry production environment on hulk during the STM Devsims on root folder menu

**Comment by akhenry** [comment]
@scottbell within tolerances, yup. Let's close this for now.
