### ISSUE TITLE
What is MCT in OpenMCT?

### ISSUE THREAD

**Issue by joshbaldwin** [nasa/openmct#1403]
This is the lowest of defects, however looking https://nasa.github.io/openmct/ and the github readme, no where does it say what "MCT" stands for.  I assume it is Mission Control Terminal but I don't know.  This is such beautiful software, it needs this polish.

If the owners agree, I can add the name to the website (please supply the link) and to the readme file for OpenMCT.

**Comment by BogdanAlexandru** [comment]
I think it's Mission Control Technologies (https://www.nasa.gov/centers/ames/orgs/exploration-tech/tech-updates/tech-update-mission-control-technologies-msl.html) but it did require a bit of googling to get there.

I agree some disambiguation somewhere would help.

**Comment by akhenry** [comment]
Good question, it's Mission Control Technologies. Abbreviating things to acronyms is an important part of our remit here at NASA.

I agree though some disambiguation would be helpful here.

**Comment by joshbaldwin** [comment]
I cannot find the code to the main website https://nasa.github.io/openmct/ to add the text there.  If this code is open sourced, please provide the link.  Otherwise, if the pull request is approved we can close out this ticket.

**Comment by ssuds** [comment]
The website code is in the github pages branch, https://github.com/nasa/openmct/tree/gh-pages

**Comment by akhenry** [comment]
Hi all! The website source is actually maintained in a private repository, from which gh-pages is automatically generated by a circle-ci script.

![The More You Know -==x](https://media.giphy.com/media/83QtfwKWdmSEo/giphy.gif)

**Comment by akhenry** [comment]
Closing because the associated PR has been merged. I've also added a disambiguation to the [about page](https://nasa.github.io/openmct/about-open-mct/) on our website.
