### ISSUE TITLE
[Fixed Position] Add alternative method for setting element size and position

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1405]
User request from WARP side on 1/17/2017:

> Is there a way to size things other than dragging a mouse point?  It would be good to be able to determine the size (in pixels) of an object.  Laying out collections of data points require things be sized uniformally.  Hard to do right now.

Might be specified as a default (e.g. "all telem elements are 2 units wide").  One trick to this is that the layout grid units do not map directly to pixels (e.g. default layout grid, 1 width unit = 64px, 1 height unit = 16px).

**Comment by charlesh88** [comment]
This isn't about defining a default size, although that might be useful. This is about being able to type into X, Y, H and W text fields and specify the position and dimensions of elements numerically. Here's an example from Illustrator:

![screen shot 2017-01-17 at 10 22 01 am](https://cloud.githubusercontent.com/assets/1056412/22033816/e46044a4-dc9e-11e6-903c-0428d164ca9c.png)

We may need to examine our grid units vs. pixels approach and see if this still makes sense. Illustrator lets you select which units you'd like to use, perhaps we might want the same.

**Comment by larkin** [comment]
I was on the verge of calling this "type in width/height of element" but didn't want to suggest the gesture.  Does this make sense as something visible in the inspector when selecting an element?

**Comment by charlesh88** [comment]
Was thinking Inspector myself. 

Also, from Kevin Smith via email 1/17/17:
> An interim solution might be just show the object’s size whenever it is being changed. I set one object to a size I like and note it is 80 x 8 pixels.  I can the make all subsequent like telemetry points the same size.

**Comment by charlesh88** [comment]
Done!
