### ISSUE TITLE
[Code Style] Build is failing in master due to lint and checkstyle errors

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1408]
It appears that some style errors have crept into the codebase with #1374. For some reason the build process was succeeding despite code style violations so these weren't picked up during development or review.

[jslint-out.txt](https://github.com/nasa/openmct/files/715797/jslint-out.txt)
[checkstyle.txt](https://github.com/nasa/openmct/files/715800/checkstyle.txt)

@larkin I think you were looking at this late Tuesday so I've assigned to you initially. Un-assign if you're not working on it.

**Comment by larkin** [comment]
@akhenry there's a pull request open for this, https://github.com/nasa/openmct/pull/1407.  Resolves these issues.

**Comment by akhenry** [comment]
Closed by #1407
