### ISSUE TITLE
[Tables] Auto-scale number of table rows based on screen height

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1409]
Using Open MCT on 2560 x 1440 screen and table renders with large gaps above and below the content rows.

Problem is because window height exceeds the 50 rows rendered by the table. As a performance optimization only 50 table rows are rendered and on scroll the row contents are switched out for the correct values.

**Comment by larkin** [comment]
@akhenry knew this would happen eventually; 50 rows was a shortcut.  Ideally this autoscales but that itself is tricky to do.  Unfortunately, bumping it to 100 or something would not scale well as it would add significant digest cost.  Perhaps delay this until we've de-angularized the table view?

**Comment by akhenry** [comment]
@larkin Interestingly, increasing the size to 100 does not noticeably affect performance. In fact, scrolling is a little more performant at 100, I think because there's effectively a larger buffer.

**Comment by akhenry** [comment]
Recasting this issue slightly, as the immediate issue is resolved with the use of a larger table.

**Comment by charlesh88** [comment]
Still an issue?
