### ISSUE TITLE
Allow Notes to be viewed in Inspector

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1411]
Notes can only be viewed in an object's Properties dialog box, limiting their usefulness. Notes should be visible in the Inspector. This is related to #1280 and a popular JPL user request https://github.jpl.nasa.gov/MissionControl/vista/issues/221

**Comment by BogdanAlexandru** [comment]
Quick question as I'm not sure I understand what the issue describes. Notes are already visible in the inspector's Properties panel. In the mockup from #1280 the Notes show up in their own panel. Is this issue about pulling Notes out of the Properties panel and into their own?

Like this, but without the notes underneath Properties:
![](http://i.imgur.com/mD7gz1a.png)

**Comment by evanohara** [comment]
I've been looking at this program for the past day,  I think mostly what is needed is that it can be edited in place during edit mode.  I'm working on something for this, although I am not sure how the nature of notes will change when you can select multiple objects.

**Comment by akhenry** [comment]
Looks like this is already in place, as noted by @BogdanAlexandru . I'm going to go ahead and close this issue.

@evanohara Thanks for taking a look at this! There is actually already a help-wanted issue for editing notes in edit mode - #1280.
