### ISSUE TITLE
[Time Conductor] Grab to pan gesture in TC should be more affordable

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1415]
From @larkin, onsite at JPL:
> jason3 user noting that the time conductor grab to pan is not easy to discover.  cursor changes to a grabby thing but otherwise is hard to discover.  (maybe a slightly different background, highlights, etc)

**Comment by charlesh88** [comment]
Time Conductor design changes for WARP historic imagery cover this issue.

**Comment by charlesh88** [comment]
Testathon 2017/04/20 cannot verify, TC not enabled.

**Comment by VWoeltjen** [comment]
Verified fixed in testathon 20180221. A highlight appears on mouseover drawing additional attention to the grabbiness.

**Comment by Costigan** [comment]
Testathon 2/21/18 fixed (hand cursor, tick area highlights)
