### ISSUE TITLE
[Tutorial] Adding a task to a Todo List created in the 2nd step fails

### ISSUE THREAD

**Issue by BogdanAlexandru** [nasa/openmct#1419]
Minor issue I encountered while going through the tutorial.

1. Create a Todo List at step 2 in the tutorial.
2. At step 3 create a new one.
3. Continue with the tutorial working with the new list until you implement editing.
4. Try to edit the old Todo List and add a task. Notice that nothing happens.

Console says: `uncaught exception: undefined` at `unknown`. Should there be a warning about this behavior in the tutorial (if it's expected)?

**Comment by akhenry** [comment]
Thanks for creating an issue for this! Behavior is not expected, and should be investigated. Worth bearing in mind that tutorials will be rewritten in the near future for the new API, so this should be considered in the context of any remedial work here.

**Comment by larkin** [comment]
Will have new tutorial soon-ish.
