### ISSUE TITLE
[Code Style] Configure jscs, add examples

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#142]
The style guide in CONTRIBUTING.md is a useful shorthand for code style, but doesn't have sufficient detail to ensure real consistency throughout the code base. Would like to add some supplemental documentation (under docs) for code style as a place to record style decisions as they are agreed-upon.

Initially, this should include some detail on the decisions for code style in CONTRIBUTING.md, as well as the additional points:

* Methods/functions should assume that inputs are valid (of valid types, etc.) to the degree specified in their documentation.
  * Rationale here is to fail fast on invalid types, and to discourage excessive type-checking which can hinder readability by distracting from the real purpose/behavior of given blocks of code.
* Where possible and appropriate, interfaces to distinct architectural components (typically services) should include or be wrapped with try-catch blocks which detect and log errors, and return reasonable default values.
  * Rationale here is to ensure fault tolerance - in the absence of defensive type-checking above, it is more likely to see exceptions occur due to bugs. We want these to be noisy (so log) but we want to minimize the extent to which the error disrupts run-time behavior (because it is unrealistic to expect errors to never find their way into production)
  * "Possible", "appropriate", and "reasonable" are important qualifiers there. Errors won't be completely recoverable so correct behavior cannot be assumed, but if better behavior than "whatever happens" can be provided, we should do that.

Proposed amendments to code style can thereafter be handled as pull requests (providing a venue for discussion as well as additional documentation for the rationale behind code style changes.)

**Comment by VWoeltjen** [comment]
Per discussion in #459, this may be handled as a build step instead of a document.

**Comment by VWoeltjen** [comment]
As noted in [pull request for build changes](https://github.com/nasa/openmctweb/pull/642#issuecomment-180516276), this should instead be handled as `jscs` configuration. That configuration should be the definitive description of code style guidelines; only additional documentation to provide should be examples which satisfy it.

**Comment by VWoeltjen** [comment]
Note that changes to sources will likely be necessary in conjunction with this issue, to satisfy whatever rules are described. (IIRC `jscs` can automate this.)

**Comment by VWoeltjen** [comment]
Tagup 4/19 - using crockford presets as a starting points is sensible here (least deviation from current code style). @larkin would like to amend that with some more flexible rules on `var` declarations

**Comment by larkin** [comment]
@VWoeltjen @akhenry 

I want to stop enforcing the combined var statement rule.  It's a pointless restriction and it hampers readability.  Instead of declaring variables at the very beginning of a block, we should be declaring them when they are used.  We don't have to rewrite everything; we can make this switch as we go forward.  

It also prevents some really insidious practices such as declaring a variable that isn't used due to a branch in a function body.  In this case, the developer is forced to choose between two unappealing options: adding an extra line of code (declare and initialize separately), or initializing unnecessarily.  In the worst case this is downright sloppy, e.g. in MCTRepresentation we initialize `uses = ((representation || {}).uses || [])` despite the fact that `uses` will never be referenced if `representation` is falsy.

**Comment by VWoeltjen** [comment]
Agree that multiple var statements are more readable.

The three cases I'd be concerned about if we allow this (all valid JS but unlikely to reflect author's intent and/or likely to be misread):

```
// Use before declaration
console.log(foo);
var foo = 3;

// Use outside of declaring block
for (var i = 0; i < foo; i += 1) {
  var bar = i * 2;
}
console.log(bar);

// Duplicate definition (esp. in a block)
var baz = 6;
if (foo !== baz) {
  var baz = 12;
  console.log(baz);
}
```

These cases aren't covered by jscs, but there are [jshint options](http://jshint.com/docs/options) which cover these (which is appropriate, as these are all possible/probable errors):

```
{
  "shadow": "inner",
  "latedef": true,
  "funcscope": false
}
```

Somewhat annoyingly, JSHint will only flag the second two cases as errors if they occur within a function, but in the context of our code base that should not be a problem.

@larkin - Do you see any issue with enforcing these rules to complement permitting multiple var declarations?

**Comment by larkin** [comment]
No issues, I like those options!

**Comment by akhenry** [comment]
I am totally onboard with this. :+1:
