### ISSUE TITLE
[export] image export with espresso theme should be "printer friendly" 

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1422]
Currently, PNG/JPG exports (only activated for plots at this time) export an image that varies with the theme.  A export done with the espresso theme active will have a dark grey background, and an export done with the snow theme will have a white background.  

A JPL mission which utilizes both themes has requested that the PNG/JPG export always have a white background as that is a printer friendly option.

**Comment by akhenry** [comment]
Help wanted candidate?

**Comment by larkin** [comment]
@akhenry yes.

**Comment by akhenry** [comment]
For anyone looking at this issue, the plot export is available as two buttons at the top of plots when you click on a telemetry point, or a plot. It's visible in the screenshot below. 
<img width="464" alt="screen shot 2017-02-20 at 17 44 27" src="https://cloud.githubusercontent.com/assets/4215777/23147702/c9129a0a-f795-11e6-9563-a8071bcca789.png">

The main source files involved are

- `platform/features/plot/res/templates/plot.html`
- `platform/features/plot/src/PlotController.js`
- `platform/features/plot/src/services/ExportImageService.js`

The `ExportImageService` relies on a library called Html2Canvas. It appears to be possible to pass a background color as an option to the library, so this might be a good place to start experimenting - https://html2canvas.hertzen.com/documentation.html

**Comment by scottwarren** [comment]
I can take a look at this if you guys like? Thanks for the investigation @akhenry it helps a lot 👌

**Comment by akhenry** [comment]
@scottwarren It's all yours, feel free to ask if you have any questions.

It's worth taking a look at the guide to [contributing](https://nasa.github.io/openmct/contributing/) on our website. Among other useful information, it contains a link to our Contributor License Agreement, which you will need to sign before we can merge your code.

Thanks again for your help!

**Comment by scottwarren** [comment]
I am still looking at this albeit slowly due to life :) - happy to keep going with this unless it's super time sensitive

**Comment by charlesh88** [comment]
Related to #681

**Comment by VWoeltjen** [comment]
Related feature request, noting here to reduce issue clutter:

> pngs export with the grey background that’s seen in the webpage, but for powerpoints it might be nice to export the background as clear.
