### ISSUE TITLE
[Tutorials] Fix broken telemetry tutorial

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1425]
The telemetry tutorial is failing due to an an attempt to mutate immutable objects such as telemetry points. This occurs because of [the tutorial's approach to asynchronously populating telemetry points in the object tree](https://github.com/nasa/openmct/blob/3ae0fd7bc96bc6017f7ae8c0fd30e421494b7a2e/docs/src/tutorials/index.md#step-2-expose-the-telemetry-dictionary). 

Asynchronous composition is now explicitly supported via `CompositionProvider`s, so the telemetry tutorial should be updated to reflect this.

**Comment by ev1stensberg** [comment]
@akhenry Need a hand on this?

**Comment by akhenry** [comment]
@ev1stensberg Thanks for the offer. We actually have a replacement for this tutorial which uses the new API, and is just about ready to go. As such I'm going to close this issue.
