### ISSUE TITLE
Remove infobubble.html

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1427]
It's not used anywhere, and appears to be [promoting a bluetooth mouse](https://github.com/nasa/openmct/blob/3ae0fd7bc96bc6017f7ae8c0fd30e421494b7a2e/platform/commonUI/inspect/res/infobubble.html#L46) (?!?).

To clarify, this refers to `infobubble.html` and __not__ `info-bubble.html` which should not be deleted.

**Comment by depperm** [comment]
so this is done?
