### ISSUE TITLE
[Build] Address Bourbon API deprecation

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1432]
Bourbon just deprecated like 60% of their API in preparation for v5 (https://github.com/thoughtbot/bourbon/issues/702). npm build is now dumping a ton of deprecation warnings to the console.

Suggest we [suppress these for now](http://bourbon.io/docs/#output-bourbon-deprecation-warnings) as they're __extremely__ noisy, and then decide on a strategy going forward.

**Comment by akhenry** [comment]
PR to suppress warnings is inbound...

**Comment by charlesh88** [comment]
Arrgh, they're removing prefixing... We're definitely going to have to do a migration to something else like Autoprefixer.

**Comment by charlesh88** [comment]
Talking with Pete and Andrew today: for now, we'll hold < Bourbon 5.0 until it becomes clearer why we should migrate up.
