### ISSUE TITLE
[Tables] Improve table performance

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1436]
The Angular digest cycle is a significant performance bottleneck in this view, and tables would benefit from a reduction in use of angular digests for rendering data in tables.

**Comment by larkin** [comment]
May serve as the centerpoint for a future "table refactor".  marking question so that I can find potential dupes later.

**Comment by VWoeltjen** [comment]
Observed during testathon 2017-10-05 that historical data arriving in Telemetry Table caused browser to freeze for several seconds, before displaying and becoming scrollable as expected.

**Comment by VWoeltjen** [comment]
Believe this was addressed by #1531; marking unverified to evaluate during next testathon

**Comment by VWoeltjen** [comment]
Verified during testathon 3/22/2018. Browser remained responsive as streaming data came in, and became unresponsive for roughly a second when 8 hours of historical data arrived, before subsequently becoming responsive again.
