### ISSUE TITLE
Any way to avoid the constant visualization mode reset?

### ISSUE THREAD

**Issue by BogdanAlexandru** [nasa/openmct#1440]
This reset to Plot happens with a telemetry panel inside a display layout:
![gif](http://i.imgur.com/S06C1y3.gif)
It also happens when simply visualizing other telemetry providing DOs.

I can see why it does, since I'm just toggling between display modes which are not persisted, but I was wondering if this was brought up before and if there's a way to avoid the constant reset. I guess what I really want is for the display layout to keep track of the display modes of its children and persist then re-apply them on refresh.

The use case that I'm going for is a customizable indicator (e.g. one that allows you to change the color of  some part of it on the fly, or one that allows you to choose between a few icons to display next to the indicator), which implies that preferences need to be persisted.

Is creating a new domain object whose role is to host single such customizable indicators (like the telemetry panel, somewhat), and a new display layout-like object (does the job of aggregating and persisting preferences) the best approach here, or am I missing something simpler and more obvious?

**Comment by larkin** [comment]
> Is creating a new domain object whose role is to host single such customizable indicators (like the telemetry panel, somewhat), and a new display layout-like object (does the job of aggregating and persisting preferences) the best approach here, or am I missing something simpler and more obvious?

@BogdanAlexandru Our preferred option is to have a single object that handles the indicators and persists changes to them.  We're moving away from the layout persisting properties of the child objects, and indeed are moving away from view switching as it is currently implemented.  The goal for us over the next few weeks is to remove the telemetry panel and replace it with the subtypes (fixed position, stacked plot, overlay plot, table).
