### ISSUE TITLE
Is there a known use case of Open MCT where there's focus on control?

### ISSUE THREAD

**Issue by BogdanAlexandru** [nasa/openmct#1441]
Open MCT's focus on telemetry is easy to spot, but I was wondering if the opposite was and is being covered in some of its use cases. Sample is something like [this](https://codepen.io/samarkandiy/pen/Gevcm), that allows you to remotely control your equipment via controls.

My idea right now would be to treat each controllable entity (i.e. parameter that is changed via a control) as a separate domain object, with the controls being views that `need` controllable entities to display. Technically I don't see much getting in the way of doing it, since in the end it boils down to instructing the server to relay commands somewhere else on each interaction with the UI, but I'd love to hear if you guys went through some use cases where this was done, and if you encountered any issues & developed a standard approach.

**Comment by larkin** [comment]
@BogdanAlexandru I think your strategy of having a specific domain object for each parameter is good, although in some cases you might want to group multiple parameters in a single object if the parameters are related or have dependencies.  There is no hard and fast rule for how you should do it.

The pattern of a view applying to an object with certain properties makes sense-- in this case "parameter objects".  This specialized view then has two options of sending updates-- either it can make calls directly to a backend service, or they could mutate the "parameter object", and you could implement a custom object provider that relays those changes back to a server.

The custom object provider I'm talking about is part of the new API and should be available soon.
