### ISSUE TITLE
[Copy] Cancelling a duplicate operation results in an error in the console

### ISSUE THREAD

**Issue by BogdanAlexandru** [nasa/openmct#1456]
```
TypeError: Cannot read property 'message' of undefined
    at error (CopyAction.js:124)
    at angular.js:14634
    at n.$eval (angular.js:15916)
    at n.$digest (angular.js:15727)
    at b.$apply (angular.js:16024)
    at HTMLAnchorElement.<anonymous> (angular.js:23416)
    at HTMLAnchorElement.c (angular.js:3293)
```

which is:

```js
function error(errorDetails) {
   var errorDialog,
         errorMessage = {
         title: "Error copying objects.",
         severity: "error",
         hint: errorDetails.message, // here
```
This is because the dialog service rejects the promise for the results when the user clicks Cancel, and this bubbles up to CopyAction which treats it as an error. `errorDetails` is undefined, hence the error.

**Comment by BogdanAlexandru** [comment]
Quick PR submitted for this.

**Comment by akhenry** [comment]
Ah! Great, thanks for picking this up and fixing it so quickly!

**Comment by akhenry** [comment]
@VWoeltjen @larkin Has this ever been verified in a testathon?

**Comment by VWoeltjen** [comment]
Don't think so. If it was, we failed to record it, so we ought to take a look (and record it) during today's testathon
