### ISSUE TITLE
Contact with the developer community

### ISSUE THREAD

**Issue by josephwinston** [nasa/openmct#1462]
What is the preferred method of interacting with the committers?  In other words is there a slack channel, gittet community, or an email list to ask about the direction of openmct as well as what kinds of contributions that the community would welcome?

Thanks

**Comment by akhenry** [comment]
@josephwinston Thanks for raising this. GitHub is our primary point of contact for suggestions, bugs, etc. We have a [help wanted list](https://github.com/nasa/openmct/labels/help%20wanted) of issues that are ideal for open source contributors.

More broadly speaking, if you don't see anything on that list that interests you, developing plugins that integrate with telemetry sources are great. For example, we have developers working on integration with an open source telemetry backend called YAMCS (https://github.com/nasa/openmct/issues/1331). There is also an open and currently unassigned issue to [develop a generic CSV telemetry adapter](https://github.com/nasa/openmct/issues/857) which would be quite useful, as it potentially makes Open MCT integration easier in some cases. 

Importantly, plugins need not be space related. For example, we had a suggestion to develop a plugin to integrate with an [Internet of Things](https://github.com/nasa/openmct/issues/1058) API in the past. Basically any plugin that increases the number of people for whom Open MCT is useful is a great contribution 😄 

In terms of the direction of Open MCT we have some notes on this [on our website](https://nasa.github.io/openmct/about-open-mct/). See the section on Open MCT's future. 

Also, feel free to contact the developers directly at [arc-dl-openmct@nasa.gov](arc-dl-openmct@nasa.gov).

**Comment by josephwinston** [comment]
Thank you for showing me where I can go for help.  I'm sure that you will be hearing from me in the future.

I've written a simple OpenMCT example that consumes telemetry data from [Snap](https://github.com/intelsdi-x/snap).  More specifically, the data is generated by [OpenSensorHub's Weather Example](https://github.com/opensensorhub/).  Snap reads the data using a plugin that consumes OSH's WebSocket and then another plugin publishes it on topic in [Kafka](https://kafka.apache.org/).  Working from the [tutorial](https://github.com/nasa/openmct-tutorial) and using [no-kafka](https://github.com/oleksiyk/kafka) to preform the read from Kafka, the data is plotted on strip charts.  Remaining work includes switching from an implicit JSON schema to an explicit [Avro](https://avro.apache.org/) so that the OpenMCT code becomes more generic.  If there is interest, I'll see about releasing what I have.

I'm also working on a large set of OpenMCT widgets and would be willing to collaborate with others than need to perform 3D visualizations like [Cesium](https://cesiumjs.org/), raster displays, GIS, etc.

Finally, my use case requires alerts.  I can help here as needed.

**Comment by akhenry** [comment]
@josephwinston Oh, nice! Are your plugins available in a plugin somewhere? We want to try and build an ecosystem of plugins for Open MCT, so it's great to be able to track what people are building.

We are very interested in seeing your widgets. Do you have anything you can share right now?

**Comment by josephwinston** [comment]
I'm in the process of getting everything approved.  Once I do, we can talk about what I should put where.
