### ISSUE TITLE
Don't automatically requery on Time Conductor input blur

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1463]
When the user tabs in or out of a Time Conductor input, the object in view will automatically requery even if the value wasn't changed. The use case here is the user just tabbing through fields, or selecting an input date to copy it. The issue is that a requery that takes a long time is an expensive price to pay for tabbing through a field.

Instead, on blur the system should compare the input value with the last query performed. If there's no difference, don't requery.

**Comment by akhenry** [comment]
Yeah this has been bugging me for a while, and should be a trivial fix. I'll take a look at it
