### ISSUE TITLE
[Move/Copy/Link] Add "Go to Original"

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#147]
Add "Go to Original" as shown on p 12 of UI Docs.

This action should trigger a navigation change to the original (non-linked) version of the object.

"Go to Original" should only be available for links, and should appear in the context menu.

**Comment by VWoeltjen** [comment]
This has been in UI docs for a while, filing issue for this in this issue tracker because this would have some utility during development (and equivalent utility during use, I'd expect.) In particular, when trying to find other telemetry objects within the same dictionary (when starting from a layout, for instance) this would be very helpful

Note that this action may be inappropriate in certain places where the context menu appears, but want to defer those details until #138

**Comment by VWoeltjen** [comment]
Not high-priority but should be simple and should have some immediate value. May reconsider working on this in Asimov if there are gotchas lurking that make this non-simple to implement

**Comment by RCarvalhoNASA** [comment]
Testathon 20151123:  While this appears that it might perform the function expected, it does less than half of what I expect as a user.  It un-highlights the link item, but does not open the tree to the original location or highlight the original item in the tree.  Additionally, the information in the inspector panel doesn't show the location either.

**Comment by VWoeltjen** [comment]
Reopening based on notes from testathon. Needs investigation; _may_ be confusing behavior due to #214, but think it's most likely a case where objects have incomplete location information (this was not included in migration scripts.) Finally, could just be a regression in this particular action.

**Comment by Costigan** [comment]
Tried Go To Original when various packets were selected (expecting a no op).  It reloaded the view area.  The object was the same.  That's ok, although not optimal.  It also changed the selection status of the packet node in the tree so that it was no longer highlighted.  That doesn't seem right.  (Costigan==mshirley)

**Comment by larkin** [comment]
Also has odd behavior when doing the following:
1. create a new object (an original), verify that it does not have a green link arrow.
2. create a link to that object in a different location, then select "go to original" on that object.
3. Observe that the original is not navigate to, and the currently selected link is no longer indicated.

**Comment by VWoeltjen** [comment]
Debugging this a bit, it appears that this occurs when there are missing `location` properties on either the link being clicked, _or_ any of its locating parents.

Consider this example:

* A
  * B (missing `location` property)
    * C
* D
  * C' (a link to C)
* B' (a link to B)
  * C

"Go to Original" on C' fails because the original C cannot be located. From the model, C is known to be in B, but it isn't known where B can be found. (Go to Original needs to know the full path to the original - otherwise you cannot disambiguate C in B from C in B'.)

Some options to solve this:

* Migrate existing databases such that location chains are always complete.
  * Not great; a migration script cannot be especially smart here
* Disable the "Go to Original" action when the location chain is incomplete.
  * Also not great. Requires a large refactor, since policy and appliesTo are both synchronous and the location-following must proceed asynchronously (in some cases, you might need to go to a server to find the locating object.) But these are synchronous for a reason; making these asynchronous would have eventual UX ramifications (e.g. wait spinners in context menus)

Both these options seem not-so-great. Want to consider other options.

**Comment by VWoeltjen** [comment]
Another option: The LocatingObjectDecorator does follow the location chain when objects are loaded, so this information will have been examined before an object has been exposed from the ObjectService. This decorator could detect an incomplete chain and report this to some intermediary; later, this intermediary could be synchronously examined to suppress the "Go to Original" action (as in the second option from the previous comment.)

This leaves open the problem of repairing the location chain when it is missing. IIRC, @larkin has suggested in the past that we add a "Set Primary Location" action that is available for objects without a `location` property. This would allow users (or developers acting as users) to manually repair existing object databases. Will file a separate issue for this (since these items are not strictly related and can be handled separately.)

**Comment by VWoeltjen** [comment]
If we get #346 done, can defer remaining work on this issue. Once we've migrated databases using #346, expect this will no longer be an issue.

**Comment by larkin** [comment]
Closing this right now as "works when there aren't errors in database".
