### ISSUE TITLE
[Conductor] Markup fixes for hidden Time Conductor

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1470]
As part of [recent changes](https://github.com/nasa/openmct/pull/1455), the Conductor has been enabled by default but hidden in the UI. This has resulted in a border being visible at the bottom of the main view, shown in the image below (it's pretty subtle and kinda hard to see in the screenshot at first. I've put a bright red border around it using the power of MS Paint.

![conductor border](https://cloud.githubusercontent.com/assets/4215777/23672504/d9d3f0d2-0366-11e7-9517-0317ce7eae57.png)

**Comment by larkin** [comment]
I am relatively certain this is no longer a problem due to changes in how the conductor is wired up.
