### ISSUE TITLE
[Docs] Cleanup and publish new tutorial docs

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1473]
* [x] Proof read and cleanup docs
* [x] Merge / publish on website / remove old references to API
* [x] Link in tutorials (github.com/nasa/openmct-tutorial)

**Comment by akhenry** [comment]
Also consider #1475 in the context of this task. I think we need to maintain the existing tutorials for things like creating a view, which is still only possible using the legacy API, but make it clear that they are essentially deprecated. Maintaining them incurs some cost, as we know, but the alternative is to adopt the position that Open MCT can only be used for telemetry integration until the rest of the new API is done. Since we don't have a firm time-frame on that yet, this is probably not a tenable position.

**Comment by larkin** [comment]
@akhenrt w.r.t. Tutorials for views,  I think it's a waste of time to try and maintain existing ones. We should prioritize updating them to new API (we are close) and not expose old API.  Yes, we limit scope of adaptations, but it's not reasonable to expect people to use old API which will break in many ways very soon.

We just have to prioritize fixing and improving over maintaining old outdated code. For a short time, then all is well.

**Comment by akhenry** [comment]
This is addressed by PR #1493 . Will update links on website once API docs merged into Master.
