### ISSUE TITLE
ToDo Tutorial Outdated?

### ISSUE THREAD

**Issue by kb1lqc** [nasa/openmct#1475]
I tried following the [ToDo Tutorial](https://github.com/nasa/openmct/blob/master/docs/src/tutorials/index.md#to-do-list) but it does not make sense. I saw that #1309 was closed in December but the code appears to have been updated even since then. [This comment](https://github.com/nasa/openmct/issues/1309#issuecomment-258485028) tried to get the new API described but it too appears to not be valid anymore.

## Tutorial index.html Code of Interest
![image](https://cloud.githubusercontent.com/assets/331540/23891478/c711b334-0853-11e7-806b-e07ce8a7b3f8.png)

## Latest Master index.html Code of Interest
![image](https://cloud.githubusercontent.com/assets/331540/23891552/38901f64-0854-11e7-881f-df80568efb10.png)

The "Function" JavaScript has been replaced with a "forEach" and it's not clear how to proceed. This is the initial experience someone has when trying to understand how to develop for openMCT and it would be beneficial to have a smooth start. I'm sure once I get the hang of it I could use intuition to figure this out but this stops me in my tracks really before I get started. Any suggestions?

**Comment by kb1lqc** [comment]
OK I made progress on this. I was tripped up by the formatting and missed the `function` code.

![image](https://cloud.githubusercontent.com/assets/331540/23891968/f4bca738-0855-11e7-850a-feb2f0fb8481.png)

This results in the plugin apparently loading:
![image](https://cloud.githubusercontent.com/assets/331540/23891960/e8ac1cee-0855-11e7-8c69-2f0a342373c9.png)

However this is contrary to [the suggestion](https://github.com/nasa/openmct/issues/1309#issuecomment-258485028) where `openmct.install(todoPlugin);` actually causes an error for me.

**Comment by akhenry** [comment]
@kb1lqc Sorry about the problems you've had with the tutorials. We are in the process of rewriting our public API, and this has resulted in some refactoring of the platform, which has from time to time rendered our tutorials out of date. They should currently be functional, and we will be gradually replacing them with tutorials that reflect the new API. 

The advice in the comment you referenced is the correct way of registering new plugins. The bundle registration mechanism in the tutorials however, reflects a slightly archaic style that is still supported for legacy reasons. The tutorials should be updated to reflect the new plugin registration mechanism, including using the new builtin plugins for MyItems, LocalStorage, etc.

**Comment by akhenry** [comment]
@kb1lqc Hi! I don't know whether you got the point of trying to integrate Open MCT with a telemetry data source, but we have recently published a new telemetry tutorial that should make the task easier - https://github.com/nasa/openmct-tutorial

It actually replaces the previous Telemetry tutorial and uses the new public API. If you do get Open MCT integrated with Faraday, we'd love to hear about it.

**Comment by kb1lqc** [comment]
@akhenry Thanks for the update! I'll have to check it out. I have not had a chance to look into this as we needed to deliver something for the Rose-Hulman Institute of Technology which is flying our hardware on a high altitude balloon very soon. So we implemented a [SimpleUI](https://github.com/FaradayRF/Faraday-Software/issues/145). No frills and half-decent at being an example of how to pass data between python and javascript over localhost.

Not sure if my next task will be to keep doing UI. I will add this tutorial to [our OpenMCT ticket](https://github.com/FaradayRF/Faraday-Software/issues/131) to make sure and have it available when we do!

**Comment by calvinhuang** [comment]
@akhenry So is a "plugin" basically the new "bundle" in the new API?

I had previously started building multiple plugins and installing them inside a bundle like this:

```js
// massive/bundle.js
define([
    './macesTelemetry/plugin',
    './supro/plugin',
    // ...
], function (
    MacesTelemetryPlugin,
    SuproPlugin,
    // ...
) {
    var massive = (openmct) => {
        for (let plugin of this.plugins) {
            plugin(openmct);
        }
    };
    massive.plugins = {
        MacesTelemetry: MacesTelemetryPlugin,
        Supro: SuproPlugin,
        // ...
    };
    return massive;
});
```

```js
// index.html
require(['openmct', 'massive/bundle'], function (openmct, massive) {
    // ...
    openmct.install(massive.plugins.MacesTelemetry);
    openmct.start();
});
```

I'm guessing this is incorrect and should just be a single plugin instead?

**Comment by VWoeltjen** [comment]
@calvinhuang - Your plugin registration code looks up-to-date. Whether you split up the functionality into one or many plugin functions is up to you. 

For clarification, the "bundle" abstraction was a [declarative plugin syntax](https://nasa.github.io/openmct/docs/guide/#bundles) inspired by OSGi and is non-standard to JS; we've dropped that concept from our public API due to the extra learning curve it imposed.

**Comment by larkin** [comment]
Closing as wontfix, this tutorial will be rewritten at a later date.
