### ISSUE TITLE
[Examples] Update example imagery

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1484]
The current example imagery can be disconcerting as it doesn't show a coherent sequence of images. The example imagery could be updated to use the same image sources as the [live demo](https://github.com/nasa/openmct/blob/2ef9820b4893ce85727a5ac066c0aa2510bb51e7/example/imagery/src/ImageTelemetry.js#L38).

**Comment by larkin** [comment]
✔️ just do it.

**Comment by akhenry** [comment]
@larkin Will do. Just Ticketing stuff so I have a [todo list](https://github.com/nasa/openmct/issues/1240#issuecomment-288799539) :)
