### ISSUE TITLE
[Live Demo] Fix markup / styling in live demo tour

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1485]
Due to changes in markup in Open MCT since the original live demo was created, the styles previously defined for the tour popups in the live demo no longer appear to work properly. Most noticeably, the close window button turns dark gray on hover in espresso. 

eg.

![screen shot 2017-03-23 at 14 07 29](https://cloud.githubusercontent.com/assets/4215777/24270372/2025a0a4-0fd2-11e7-8853-ad2bac2afcee.png)

**Comment by larkin** [comment]
is this a conflict between the classname provided by the tour library and the classnames used in our modal dialogs?

**Comment by akhenry** [comment]
@larkin Sounds totally plausible. Haven't done any investigation yet, just recording everything that needs to be fixed.

**Comment by larkin** [comment]
@charlesh88 to do, @akhenry for help if needed.

**Comment by charlesh88** [comment]
@akhenry Where do I get the latest live_demo, and how do I edit if mods are needed to something in open master?
