### ISSUE TITLE
A flat badge for NASA

### ISSUE THREAD

**Issue by aleen42** [nasa/openmct#1486]
Here is [a repository](https://github.com/aleen42/badges) for making badges more acceptable in documenting, and I hope that the flat badge can be used in documenting in NASA. 

[![nasa](https://rawgit.com/aleen42/badges/master/src/nasa.svg)](https://rawgit.com/aleen42/badges/master/src/nasa.svg)

**Comment by akhenry** [comment]
@aleen42 Neat, thanks! We'll take it into consideration. It looks like you provide a tool for generating badges with different text, right? So we could potentially generate a badge with the text "Open MCT"? 

This might be useful for our plugin community to use in their repositories to identify it as an Open MCT plugin.

@jasonduley Are there any legal issues here with the use of the NASA logo in this way? Eg. if the text were changed to Open MCT and plugin developers used it in their repositories? Would the use of the NASA logo by other projects with either the NASA or Open MCT text be seen as tacit endorsement of said project?

**Comment by aleen42** [comment]
Is there any icon designed for **Open MCT**?

**Comment by jasonduley** [comment]
Based on what I can tell, the meatball embedded into this graphic has not been changed so it is my understanding that this is ok.  please see this page for further guidance on this topic.  https://www.nasa.gov/multimedia/guidelines/index.html
