### ISSUE TITLE
Descriptions don't always show in create menu.

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#149]
The hover target for the create menu is larger than the text label, however, the description is only visible when hovering over the text label.  Whenever the hover effect is shown, the description should also be visible.

Example of hovering in two different locations:

Not over text:
![screen shot 2015-09-28 at 10 00 55 am](https://cloud.githubusercontent.com/assets/226503/10142495/de6c7bde-65c7-11e5-95f3-9a3009a6531c.png)

Over text:
![screen shot 2015-09-28 at 10 01 02 am](https://cloud.githubusercontent.com/assets/226503/10142499/e1fa080c-65c7-11e5-9038-a5515371efd8.png)

**Comment by charlesh88** [comment]
Fixed.
