### ISSUE TITLE
Discussion: Switch from gulp to webpack

### ISSUE THREAD

**Issue by ev1stensberg** [nasa/openmct#1491]
Webpack has huge tradeoffs on performance and is really flexible in terms of how you want to bundle your application. If you want to use webpack, which supports tons of options like chunk splitting ( instead of one distributed `openmct.js` file), I'm happy to implement it for you. I refer to the 2017 goal for `openmct`.

This is up for discussion, I can generally answer questions you have about webpack if you want to as well. 

Relative on perf: https://developers.google.com/web/fundamentals/performance/prpl-pattern/

I know AMD "speeds things up a bit", in terms of async loading, but I think there's opportunities here.

**Comment by ev1stensberg** [comment]
Another fair point, is that it's super-fast to implement ES6 support across the entire project or for a targeted directory, as well as other options such as PWA's, etc..

**Comment by larkin** [comment]
We don't use requirejs for async loading.  It's a stable module loader that ties in nicely with our build system.  Yes, we could switch to Webpack, but there's no immediate gain and it's a large retooling effort.  All we currently need is a single distributable openmct.js file (which we have).

There's a point down the road where webpack might be nice, but it brings us nothing of value right now-- and it does so at significant cost.  We'll re-evalute this at a later date.

**Comment by ev1stensberg** [comment]
@larkin I can put up something and let's compare it. It's no hazzle at all. In production ( like [nasa.github.io](https://nasa.github.io/openmct/) ), we could benefit from chunking, and we can distribute a single prod file for user usage?

**Comment by larkin** [comment]
@ev1stensberg we wouldn't merge a change of that magnitude.  Can reconsider in a year.

**Comment by evenstensberg** [comment]
Any change of perspective? Happy to help with migraion
