### ISSUE TITLE
[API] Accept multiple plugins from openmct.install

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1492]
One of the (very small) pain points in using the recent plugin registration API is that an openmct-derived application will typically want to register several plugins, so you end up with some boilerplate:

```
var plugins = [ somePlugin(options), someOtherPlugin(), etc ];
plugins.forEach(function (plugin) {
  openmct.install(plugin);
});
```

Install could detect arrays and do this for you to reduce that to `openmct.install(plugins)` which is cleaner/clearer/simpler. Could use a different method name to avoid confusion (this is something of a matter of taste)

**Comment by larkin** [comment]
@vwoeltjen seems reasonable to me, can't see what this might prevent in the future. And it simplifies some code.

**Comment by larkin** [comment]
Seems unnecessary at this time, can reconsider later.
