### ISSUE TITLE
Web Page URL regex fails valid addresses

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1507]
The current Web Page URL regex 
`"pattern": "^(ftp|https?)\\:\\/\\/\\w+(\\.\\w+)*(\\:\\d+)?(\\/\\S*)*$",`

fails this valid URL:
http://s3-us-west-1.amazonaws.com/landlords-prod/resource_prospector/index.html

and yet it should allow it. 

Do we need a regex here beyond user convenience? Are there security concerns? If not, I suggest removing the pattern statement entirely.

**Comment by VWoeltjen** [comment]
Dashes should be allowed for domains/subdomains. Will submit a PR shortly.
