### ISSUE TITLE
[Tables] Error on view destruction

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1509]
The telemetry tables throw an error when the view is destroyed (eg. on navigation away from a table)
```
angular.min.js:110 TypeError: Cannot read property 'displayRows' of undefined
```

This error is due to some over-zealous scope cleanup code [in the TelemetryTableController] (https://github.com/nasa/openmct/blob/251438eefd16c7cb70664a583003d65d34c71788/platform/features/table/src/controllers/TelemetryTableController.js#L230) and in the [MctTableController](https://github.com/nasa/openmct/blob/251438eefd16c7cb70664a583003d65d34c71788/platform/features/table/src/controllers/MCTTableController.js#L179) which was added because of a memory leak that would occasionally cause some views to hang around longer than they should. Delayed garbage collection is a problem for tables because of their large memory usage.

I believe that the condition that lead to this memory leak has been resolved, and this code should be removed. In doing so, it's worth checking that the `TelemetryTableController` and `MctTableController` are being garbage collected as expected.

**Comment by larkin** [comment]
Problem is actually from MCTResize not handling scope destruction properly.  Resolved.
