### ISSUE TITLE
[Time Conductor] Time conductor should display only when relevant

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#152]
The time conductor/controller should appear at the bottom of the screen only when a view containing telemetry data is visible (either directly, as in a Plot, or indirectly, as in a Layout containing a Plot)

**Comment by VWoeltjen** [comment]
Note - this refers to time conductor as implemented in #104

**Comment by larkin** [comment]
Closing this as a wontfix.  There are ways that a customer could customize the application to hide/show the time conductor and controller based on navigation or other events, and this would conflict with those customizations.  Additionally, styling may be a better solution for this.
