### ISSUE TITLE
[Tables] Tables need updating for telemetry metadata changes

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1521]
`source` metadata field, where supplied, should be used for extracting domain values from data instead of exclusively using `key`. 

Typically, metadata should be searched for a domain value where `key` matches the selected time systems's `key`. The source field of the resulting match can then be used for extracting domain values from telemetry data.

**Comment by larkin** [comment]
This is fixed in one of the table refactors-- they use telemetry formatters, which abstract away this behavior.
