### ISSUE TITLE
How to have multiple imagery telemetries?

### ISSUE THREAD

**Issue by Yiluo-pHoton** [nasa/openmct#1524]
Hi,

I'm quite new to JavaScript, so trying to adapt to it was a bit challenging for me. I am using openmct to try to display imageries from four different cameras, streaming through the same server but different ports. So this is what happened:
I tried to duplicate the bundle for imagery and modify the URL for the image, but after I put these different bundles up in the browser, they all display the imageries of the same camera at each time and are switching between different cameras randomly.
I wonder if someone could give me some advice on this, or maybe is there a better way to display two different telemetries?

Thank you.

**Comment by larkin** [comment]
@Yiluo-pHoton Hi there!

I would look into the [telemetry tutorial](https://github.com/nasa/openmct-tutorial) for how to expose multiple telemetry objects-- one object for each camera-- and then look at the realtime provider for an idea of how to provide a different image url for each camera whenever it updates.  If that doesn't help, can you provide a code snippet or git repo showing your code to help us understand what you are doing?
