### ISSUE TITLE
Plots not showing data

### ISSUE THREAD

**Issue by RCarvalhoNASA** [nasa/openmct#1525]
Testathon 2017/4/20.  Plots are not showing data, whether individual, panel, or in a layout.  The x and y axis get updated, but nothing actually shows in the plot

**Comment by charlesh88** [comment]
@RCarvalhoNASA @larkin Ticks shouldn't be updating. They should be static, with new data being drawn in the plot display area. I'm looking at Packets > WHEELIO_DATA > various telemetry points that are definitely getting updated values. What I see are the ticks being updated, but nothing gets plotted. Are the ticks "moving" to the left such that new data never gets rendered into the plot display area? 
Same behavior with plot view of a Panel.

**Comment by larkin** [comment]
This is an issue with Clock and time conductor settings in WARP, closing and tracking there:

This is based on the WARP deploy using an invalid clock and timeconductor setting, closing this and tracking as: https://developer.nasa.gov/ResourceProspector/warp/issues/286
