### ISSUE TITLE
Plot X axis updating and at an insane rate

### ISSUE THREAD

**Issue by RCarvalhoNASA** [nasa/openmct#1526]
Testathon 2017/4/20  The X axis values in the plots are continually updating in realtime, showing every millisecond.  Wouldn't it make more sense for them to update just as new data comes in, or at least at a lower frequency?

**Comment by charlesh88** [comment]
@RCarvalhoNASA @larkin Do you see any data being plotted? I'm looking at Packets > WHEELIO_DATA > various telemetry points that are definitely getting updated values. What I see are the ticks being updated, but nothing gets plotted. Are the ticks "moving" to the left such that new data never gets rendered into the plot display area?

**Comment by charlesh88** [comment]
Same behavior when adding telem points to a newly created Panel.

**Comment by RCarvalhoNASA** [comment]
Charles, that's a separate ticket #1525

**Comment by larkin** [comment]
The update rate is based on the new hidden time conductor which ticks at 60hz.  

The clock that has been configured is actually based on last ~30 minutes local time, which doesn't match the timestamps of the telemetry we are playing back, so the plot shows nothing.

Configuration issues with new APIs and WARP that we'll have to address.

**Comment by akhenry** [comment]
> The clock that has been configured is actually based on last ~30 minutes local time, which doesn't match the timestamps of the telemetry we are playing back, so the plot shows nothing.

Oh, LOL. That actually makes total sense. Also explains why nothing in tables. Gosssssssh.

We need a LAD or some other server-side clock source.

**Comment by larkin** [comment]
This is based on the WARP deploy using an invalid clock and timeconductor setting, closing this and tracking as: https://developer.nasa.gov/ResourceProspector/warp/issues/286
