### ISSUE TITLE
Expected the selected packet view to come to front when selected in Display Layout

### ISSUE THREAD

**Issue by shobart** [nasa/openmct#1528]
Created a new display layout and dragged a few packets into  it.  I arranged the packets so they overlapped each other. 

When I selected a packet that was behind another packet, it did not pop to front.  I expected it to do so, since that's standard for most windowing systems.

**Comment by shobart** [comment]
I was testing on Firefox.

**Comment by charlesh88** [comment]
@shobart This is a known limitation of edit mode. This should be examined when we look at edit mode in the future - the solution is as you suggest, or give more direct control over layer order as in Fixed View/Panel mode objects.

**Comment by larkin** [comment]
original issue is #123, merging there.
