### ISSUE TITLE
[Build] Include version information in openmct.js

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1541]
It would be useful to be able to identify the version (up to and including commit hash) of Open MCT simply from a built openmct.js artifact. 

This information actually shows up in the [UMD template](https://github.com/nasa/openmct/blob/185567cf2947baa9e7e1153771c7b20fc3510e0d/src/start.frag#L23-L29) and should be injected as part of the gulp build, but appears to be getting trimmed out by the minification step.

Desired behavior would be to include that version information along with a single license header in dist/openmct.js

**Comment by slinto** [comment]
I try to fix this and here is my results and questions.

- Sourcemaps in production build? I think it can be remove. What do you think?
- Requirejs: sourcemaps + preserveLicenseComments not work ([more about this problem](http://requirejs.org/docs/optimization.html#sourcemaps))
- If we remove sourcemaps, we can use preserveLicenseComments, but this preserve license comments from all packages.

So, this is my solution for this problem:

1. remove sourcemaps from build
2. remove _gulp-replace-task_ dependency
3. add _gulp-header_ dependency
4. add _preserveLicenseComments: false_ to require.js config
5. add _comment_ variable to gulp file: 
```
   var comment = [
      '/**',
      ' * Open MCT https://nasa.github.io/openmct/',
      ' * Version: ${pkg.version}',
      ' * Built: ${pkg.timestamp}',
      ' * Revision: ${pkg.revision}',
      ' * Branch: ${pkg.branch}',
      '*/\n'
    ].join('\n');
```

After this I have a openmct.js file which looks like this:
```
/**
 * Open MCT https://nasa.github.io/openmct/
 * Version: 0.12.1-SNAPSHOT
 * Built: 2017-05-29T20:40:48Z
 * Revision: 1bdc0497c73167d38d3a74bbe9506adacd808036
 * Branch: master
*/
.... minified code here ....
```

What do you think about this solution. I have ready this code changes for make PR.
Thanks.

**Comment by VWoeltjen** [comment]
> Sourcemaps in production build? I think it can be remove. What do you think?

I think they're useful. Open MCT isn't deployed directly in practice, and dependent projects can pick and choose what to include.

> This is my solution for this problem:

> 1. remove sourcemaps from build
> 2. remove _gulp-replace-task_ dependency
> 3. add _gulp-header_ dependency
> 4. add _preserveLicenseComments: false_ to require.js config
> 5. add _comment_ variable to gulp file: 

Ah, good thought on using `gulp-header`!

We don't want to lose sourcemaps, and `gulp-replace-task` is still needed for version info to be available at run-time. Think this solution can be simplified to:

1. Add `gulp-header` dependency
2. Compute `comment` in gulp script
3. Use `gulp-header` at the end of the `scripts` task

**Comment by slinto** [comment]
@VWoeltjen ok, you are right with sourcemaps. I create PR with this fix, but I have a one question.

When I running openmct in localhost, in 'about' I don't see a version info but only: 
```
/**
 * Open MCT https://nasa.github.io/openmct/
 * Version @@version
 * Built @@timestamp
 * Revision @@revision
 * Branch @@branch
 */
```

I tested this behavior on my fixed branch and on master too, and I still don't see a version info in app.

**Comment by VWoeltjen** [comment]
> When I running openmct in localhost, in 'about' I don't see a version info

Version info gets injected as part of the build, so you won't see it populated in a dev environment. I see the About dialog correctly populated when running with the built `openmct.js` from the `dist` folder.

**Comment by VWoeltjen** [comment]
Verified that the following appears in the header of openmct.js of our testathon build, 20180221:

```
 * Open MCT https://nasa.github.io/openmct/
 * Version: 0.12.1-SNAPSHOT
 * Built: 2018-02-21T19:04:35Z
 * Revision: Unknown
 * Branch: Unknown
```

Notably, revision and branch are unknown. This is presumably a consequence of the way `npm install` runs `prepare`, in which case there's not much to be done (but arg)

**Comment by akhenry** [comment]
@VWoeltjen Trying to understand the issue here. Is it because when WARP is built Open MCT is pulled in as an npm dependency, and as such lacks the git metadata necessary to populate those fields?

**Comment by akhenry** [comment]
Also, is there any remedial work to be done here? Do we need to reopen the issue?

**Comment by VWoeltjen** [comment]
After giving it some thought, I'll file a new issue. Whenever we're depending on the repository directly we're likely to run into this, and that's where having the specific commit (as opposed to a version identifier) is particularly useful. This is potentially simple; I believe the info ends up in package.json during a checkout, so we can read it from there if it is unavailable from git directly.
