### ISSUE TITLE
Remove action is available for non-editable objects

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1542]
Attempting to use the action fails as expected, but it probably shouldn't be available in the first place. This is evident in the live demo. Navigate to a non-editable layout (eg. anything under "demo objects"). The context menu on any of the objects in the layout includes the remove action.

**Comment by larkin** [comment]
Similarly, "move" is also available but should not be available.  reported by jay.

**Comment by larkin** [comment]
This is also visible with the style guide.  Likely need to add policies to that bundle.

**Comment by marcobeltempo** [comment]
I would like to tackle this issue.

**Comment by akhenry** [comment]
@marcobeltempo Thanks very much for your offer. My apologies that we didn't respond to your offer to fix this sooner. One of our developers has fixed this issue. If there's anything else in our help-wanted list that takes your interest though, let me know.
