### ISSUE TITLE
[telemetry] standardize on domain, range

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1546]
We should switch all hinting in the telemetry API to use "domain" and "range" instead of "x" and "y", as x,y are specific to plotting and domain and range are more elementary concepts.

**Comment by VWoeltjen** [comment]
:+1:; I'll add that we should take extra care to be explicit about what these mean to Open MCT in our documentation. Domain/range have resulted in occasional confusion; it's non-obvious how their mathematical meaning translates to our platform. Our usage implies that measurements are a function of time, which is not necessarily how other developers will view their telemetry.
