### ISSUE TITLE
[Live Demo] Automate the deployment process for the live demo

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1549]
The live demo should be automated so that when changes are made the demo is pushed to our heroku app.

Also, the live demo is currently dependent on openmct master, via its [`package.json`](https://github.com/nasa/openmct-demo/blob/c57fc4a3ad2e777c9f392fb68080eebda7c5dd19/package.json#L17). At some point it would make sense to change this dependency so that it's based on a stable tag.

**Comment by larkin** [comment]
moved to https://github.com/nasa/openmct-demo/issues/5
