### ISSUE TITLE
[Style Guide] Publish style guide

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1565]
Publish a version of Open MCT with the style guide plugin from #1479 enabled/displayed.

**Comment by VWoeltjen** [comment]
Per discussion in email, this would be as a standalone instance of Open MCT reachable from the Documentation section of the website, with only the Style Guide visible in the tree.

**Comment by larkin** [comment]
We'd also discussed just copy/pasting the html output into a few pages and including the built CSS in the page, so it was static content.  Could be done manually or scripted.

If that's a bit hard for a V1.0 candidate then we can delay just a bit; we're likely to have a better solution in a few months when we get through the bulk of our refactors, so current options are also fine.  And I'd expect anyone who needs the style guide to be able to checkout open mct and run a dev server without issues.

**Comment by VWoeltjen** [comment]
https://github.com/nasa/openmct-website/pull/31

**Comment by charlesh88** [comment]
Testing notes:
- Look in the tree view and find the Style Guide folder.
- Expand the folder and click on several items, verify they display properly.

**Comment by VWoeltjen** [comment]
https://nasa.github.io/openmct/style-guide
