### ISSUE TITLE
tabbing through "dialog" allows input in background elements

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1569]
Repro steps

1. Open the create dialog (e.g. by creating a folder)
2. Select the "name" field.
3. press tab a few times.  the input cursor will eventually highlight the `search` box and allow you to type inputs / search.

This will happen with any dialog, and the behavior is unexpected.  Tabbing should be restricted to the current dialog window (as the backdrop gives the impression that nothing else is active).

**Comment by charlesh88** [comment]
There does not appear to be any pure CSS way to limit tab indexing to a given container or context; most solutions I saw involve using JavaScript to "redirect" the tab target when leaving a given field. Here's an interesting article: https://bitsofco.de/accessible-modal-dialog/

**Comment by charlesh88** [comment]
Testing notes:
- Create a new object like a clock or timer.
- In the Create dialog, click in the Name field to insert the cursor. 
- Now, tab into the other fields of the overlay. 
- Observe: the cursor should go sequentially to each field of the overlay until the last one, as which point it *will* tab into background inputs, but this is expected.

**Comment by larkin** [comment]
This is definitely something that can't be contained by css alone, that article hits on all the key points.

**Comment by VWoeltjen** [comment]
Regarding background inputs, we could add a `disabled` attribute to all of them before showing the overlay, then remove them when the overlay is dismissed. 

There's a risk that this could interact badly with other code (e.g. if something in the background tries to disable something while a dialog is showing, and we incorrectly reenable it when the overlay is removed) but I'm doubtful that we'd run into this in practice.

**Comment by larkin** [comment]
@VWoeltjen there are simple options that are self contained within the dialog service and IMO would be a better option.  The article Charles linked is pretty good, I'm a little concerned about the keyboard jail for tab and shift+tab; yet any other solution I think of is much more complicated.
