### ISSUE TITLE
[Plot] Vertical pixel alignment seems to be incorrect

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1578]
In the attached screenshot, all data values are exactly 0. The horizontal line for data, however, looks like it's ~~one pixel or so~~ two pixels below the guideline for 0, implying that data is less than zero.

Guessing this is something like a simple alignment issue between the `canvas` and the dotted lines that get drawn over it.

![image](https://cloud.githubusercontent.com/assets/1685764/26081534/16e4f864-3980-11e7-8ac4-a78b5f53e602.png)

**Comment by ivikash** [comment]
How can I reproduce this bug at my end?

**Comment by larkin** [comment]
outdated with #1557 .
