### ISSUE TITLE
[Search] Generic search not indexing across namespaces?

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1579]
Noticed in WARP that search indexing was not being applied to the telemetry dictionary, which has a separate namespace from My Items. GENERIC_SEARCH_ROOTS is not being overridden by this deployment, so speculate that exclusion is due to change in namespace.

**Comment by larkin** [comment]
@VWoeltjen search only works with standard composition right now (it reads ids from model.composition), needs to hook into composition providers for efficient transversal.
