### ISSUE TITLE
[Plots] Style plot features

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1590]
Implementation task stemming from #584 and other related issues.

**Comment by charlesh88** [comment]
Todos:
- [ ] Basic layout for legend on sides or top/bottom.
- [ ] Better solution to make values fixed width so they don't jiggle when hovering.
- [ ] Integrate @larkin changes to include limit violations.
- [ ] Show "more" indicator when collapsed legend is in overflow state.
- [ ] Style values when cursor is hovering.
- [ ] Style config interface in sidebar.

**Comment by charlesh88** [comment]
Questions for @larkin 
- I need the legend to know when the user is hovering to and we're going to display a current value in the legend so I can handle the layout it that circumstance. Ideally, we do this once in the legend

**Comment by charlesh88** [comment]
@larkin There are two items outstanding from the to-do list in this issue:

1. Integrate @larkin changes to include limit violations.
1. Show "more" indicator when collapsed legend is in overflow state.

On the first, did you get the limit violations stuff in? On the second, I'll need some pointers on where/how to include a listener (?) to watch the overflow state of the collapsed legend and set a class appropriately.

**Comment by larkin** [comment]
Tracking one remaining task as #1937 and closing.
