### ISSUE TITLE
[telem] handle multiple subscriptions for the same point invisibly?

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1594]
It strikes me that the telemetry API could abstract away the need for subscription providers to handle multiple requests for a single telemetry object.  It could track subscriptions per identifier and not send multiple requests to the individual providers. This would remove a common piece of boilerplate from subscription telemetry providers.

Note that this can only be done if we don't expect the subscription requests options to change the actual request.  At this point, those options are not used for anything at all, so I think it's okay, but discussion should be had.

@VWoeltjen ?

**Comment by larkin** [comment]
A simple example is in the tutorial: https://github.com/nasa/openmct-tutorial/blob/master/realtime-telemetry-plugin.js#L23-L39

This would change the tutorial code from this:

```javascript
subscribe: function (domainObject, callback, options) {
    if (!listeners[domainObject.identifier.key]) {
        listeners[domainObject.identifier.key] = [];
    }
    if (!listeners[domainObject.identifier.key].length) {
        socket.send('subscribe ' + domainObject.identifier.key);
    }
    listeners[domainObject.identifier.key].push(callback);
    return function () {
        listeners[domainObject.identifier.key] =
            listeners[domainObject.identifier.key].filter(function (c) {
                return c !== callback;
            });

        if (!listeners[domainObject.identifier.key].length) {
            socket.send('unsubscribe ' + domainObject.identifier.key);
        }
    };
}
```

to

```javascript
subscribe: function (domainObject, callback, options) {
    socket.send('subscribe ' + domainObject.identifier.key);
    listeners[domainObject.identifier.key] = callback;
    return function unsubscribe() {
            socket.send('unsubscribe ' + domainObject.identifier.key);
            delete listeners[domainObject.identifier.key];
        };
}
```

**Comment by VWoeltjen** [comment]
I like it! Moving this responsibility into Open MCT also gives us more options for how we handle dispatching telemetry to views.

> Note that this can only be done if we don't expect the subscription requests options to change the actual request. At this point, those options are not used for anything at all, so I think it's okay, but discussion should be had.

Should we just get rid of the `options` argument?

**Comment by larkin** [comment]
That's my thought.  It could come back if we need it.

**Comment by floradar8** [comment]
Поадуцста не зайобуй меня не пиши мне ты отстал от жизни

25.05.2017 3:35 пользователь "Pete Richards" <notifications@github.com>
написал:

**Comment by larkin** [comment]
@floradar8 I don't understand, can you say that in English?
