### ISSUE TITLE
[Inspector] Inspector properties do not get updated properly

### ISSUE THREAD

**Issue by dhrubomoy** [nasa/openmct#1596]
Edit a clock for example, and the inspector properties don't get updated then and there.
Click another item, then click on the clock again. Now we will see the new updated time. But it should be updated immediately.

![inspector_](https://cloud.githubusercontent.com/assets/12648587/26535243/9090bcc4-43f9-11e7-9da9-1b95d757122b.gif)

**Comment by larkin** [comment]
@dhrubomoy Thanks for reporting this!  It's been reported before as #1276, so I'm going to close this and move your comments to that issue.
