### ISSUE TITLE
[Timeline] "No representation found" warning when creating a new Timeline

### ISSUE THREAD

**Issue by dhrubomoy** [nasa/openmct#1597]
After creating a new timeline I am getting a warning in my console, "No representation found for time-conductor".

![untitled](https://cloud.githubusercontent.com/assets/12648587/26565180/0e303e94-44b7-11e7-93a0-44d8cd0e9748.png)

**Comment by akhenry** [comment]
This is an artifact of how the Time Conductor gets conditionally added to the dom. `browse.html` will always ask for a representation called `time-conductor`. If the time conductor plugin has been installed it will exist and the conductor will be added, if it hasn't, it won't be shown. The side-effect is this warning in the console. It stemmed from not having a generic extension point for adding new screen elements, and not wanting to hard wire conductor-specific logic into core code. 

We could just remove this warning from mct-representation, or downgrade it to a debug message...

**Comment by akhenry** [comment]
This is harmless, and will be resolved when views are de-angularized.
