### ISSUE TITLE
[Save] Prototype centralized persistence queue

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#160]
Prototype a centralized means of persistence which maintains a queue of objects which has changes-to-be-saved, in the order in which the changes are meant to be saved. This should issue persistence calls to the server in the order they occur (presuming this ordering is important) and provide some notification of progress globally.

This should also expose object status in a manner that can be used to determine the specific state of an object (e.g. "has changes which are scheduled to be saved but have not yet been saved")

Corollary to this is #159 which is to provide UI details for this

**Comment by larkin** [comment]
In discussions yesterday we removed the display of in-progress actions (such as duplicate) from the tree, as showing in-progress objects while preventing users interacting with them is complicated and can be avoided by #128 (not showing object until it's completely duplicated).

As for general changes to objects (editing properties or saving changes made in edit mode), it seems that those operations should block user input and navigation until all changes are persisted.  If this persistence is asynchronous, and the user leaves edit mode, when a save error occurs they have to go back to edit mode to resolve the issue-- a bit of a context switch, and it makes it very hard to resolve the error.

I believe this ticket can be removed from the current sprint.

**Comment by VWoeltjen** [comment]
This is intended to be exploratory - don't think it necessarily needs to be in this sprint, and certainly should be lower priority than other items.

The rationale for this isn't recorded so let me take a moment to write it out a little:

We have a general category of issues related to communicating failures to persistence; solutions like #128 suggest handling these failures on a per-action basis, which also means they need to be verified, maintained, debugged on a per-action basis. To answer the basic question - "how does the user know if their changes have been saved?" - you then need to look in N places. What I'm looking for here is a way to answer the question in one place, decoupling actual persistence from the actions which initiate them; this has UX ramifications, insofar as you now have to convey state differently (instead of "this action could not be completed, retry?" you see "changes to these objects could not be written to the server, retry?") This is a different way of communicating with the user, but I think that the state of the system can still be articulated well enough that this doesn't become a significant UX cost (and I'd like to prototype this to demonstrate that.)

This does have some implications on the way actions which involve multiple changes need to be structured. For instance, you need to persist things in an order that can be interrupted reasonably at any point without violating consistency; you can't rely on the action to know how to clean up after itself if things go wrong partway through. This is already the world we live in, however; our backends are non-transactional (and if we want to work well with RESTful architectures generally, which seems like a highly reasonable platform goal, then we cannot presume transactionality is available), and the computer the client is running on could _literally blow up_ at any time, so even if our N actions know how to roll back intelligently we cannot use that as a guarantee of consistency.

I'm not convinced this solution is the right way to go, but I think it's worth prototyping because (a) solving a problem once is better than solving it N times (unless N &le; 1) and (b) because if we do find problems with it, we'll at least have an empirical reason for investing time in those N solutions.

**Comment by larkin** [comment]
"Solving a problem once is better than solving it N times" is true ***only if the singular solution is cheaper than the solution for N times***.  Seeing as N is currently `2`, it's hard to say that we should spend time prototyping this.  We also have to consider that we don't currently catch persistence failures in any fashion right now.

I cannot understate how bad it is in it's current incarnation: users have already lost more than a day of work because the system doesn't throw any error at all when it completely fails to do what they ask (persist something they have created).

I think it's worth spending the time to solve the problem individually a few times.  Once we've seen a few different implementations of it, we're better prepared to see the commonalities between them and provide a singular solution.

**Comment by VWoeltjen** [comment]
I count at least 7 distinct actions which involve persistence calls (Create, Edit Properties, Remove, Save from Edit mode, Move, Duplicate, Link) so I'm not sure where that number comes from.

I agree that this is severe, which is why I'm inclined to look at comprehensive solutions that don't leave us realizing that "oh, we didn't catch this problem in X" later. I also think the problem is significant enough that it is worth doing an analysis of alternatives. 

I absolutely think solving this in specific cases is still warranted and am not suggesting that we deprioritize any other issues related to handling persistence failures at this time.

**Comment by larkin** [comment]
* Create, edit properties, and save from edit mode may become a singular action in the future.
* Remove has a consistent interface (action returns a promise, promise resolution is success, promise rejection **should be** an error object that can be easily displayed).
* Move/Copy/Link, not fully shipped and has further design changes coming, hard to hit a moving target.

In general, they are all async actions and already have a consistent interface supporting success and error: the ubiquitous Promise.

**Comment by larkin** [comment]
Closing as we don't currently have plans to implement this with current persistence architecture.  not a strong wont-fix though.
