### ISSUE TITLE
do not default to plot for non-plottable telemetry

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1601]
With the new telemetry API, the plot is being shown instead of the telemetry table for telemetry points that cannot be plotted.

The [PlotViewPolicy](https://github.com/nasa/openmct/blob/master/platform/features/plot/src/policies/PlotViewPolicy.js) needs to be updated to use the new telemetry API to access metadata, and we need to decide how to make a reasonable decision here.

I posit a few possible scenarios:

1. A telemetry point does not have numeric values and should be shown in a table.
2. A telemetry point has numeric values and should be plotted.
3. A telemetry point has both numeric and non-numeric values and should default to a table view, e.g. event messages may have a numeric severity but should still default to a table.
4. A telemetry point has both numeric and non-numeric values and should default to a plot view, e.g. enumerated telemetry may have string values but should not default to a plot view.

To force us to track these sorts of issues in one place, I'm trying to shoehorn this into our existing system of hint priority.  I also happen to have insider information the new View API will allow views to interrogate an object and return their priority for a given object dynamically, and I will make some some statements about how things "currently work" that are actually false but will be correct very soon.

At present, the Plot requires both "domain" and "range" hints.  The Table does not require any hints to be present.  If we remove "range" hints from string telemetry points, then plots would not apply to those telemetry points, while tables would continue to apply, and we would support the simple cases of "default to table/plot".

What becomes harder is "prefer plot" or "prefer table".

The Plot could fetch the bestValueForHint('range') and return the priority of that hint as it's priority score.

The Table could iterate through all available values and return the index of the first string-formatted value metadata.

If a value metadata of string format was defined before a value metadata with a range hint, it would default to table.  

(I kick myself for using format when I think it should be a hint).

@VWoeltjen somewhat related to imagery, your inputs would be appreciated.

**Comment by VWoeltjen** [comment]
> ... what do tables use to prioritize themselves over plots? Ideally there is a relevant hint they can return the priority of?

`Table.getPriority = function (domainObject) { return SOME_CONSTANT_VALUE; }`

Unlike plot, I don't think Table can reasonably infer which telemetry points they'd be best suited for. If there's a `range` with a hint value higher than SOME_CONSTANT_VALUE, plot is higher priority than table; otherwise, table is higher priority than plot. Along with a boolean applicability check, this covers all four cases, correct?

If we need something beyond that, I'd be inclined to let types/objects define priorities for specific views (overriding whatever the view thinks.) The underlying rationale for prioritizing view for enums differently from events, for example, is something I'd have trouble articulating fully in people language, let alone source code. In that situation I'd prefer to just be overtly ad hoc.

**Comment by larkin** [comment]
@VWoeltjen yeah I realize that case 3 is rare; I agree that we're better off documenting the specific edge case and workaround instead of doing some really weird inexplicable 💩 .

So how about the following solution:

1. Don't supply a `range` hint for things that should only display as a table.
2. If it's plottable but should default to table, then all of your range hints should be larger than `100` (e.g. some arbitrary but documented MAGIC_NUMBER).

If we need something beyond that in the future, I'm hoping we'll have a matching user story we can use to help define a plan.

**Comment by VWoeltjen** [comment]
I don't understand the need for a magic number. 

Assuming, for instance, that we define the following scale for priorities:

Value | Usage
---|---
0.00 | Valid, but only minimally so
0.50 | Valid, but not especially so
1.00 | Best fit possible!

Assuming plot uses highest range values, and table uses a constant priority of 0.5, it is straightforward to achieve:

Use case | Table priority | Plot priority | Highest priority
:---:|:---:|:---:|:---:
1 | 0.5 | N/A | Table
2 | 0.5 | 1.0 | Plot
3 | 0.5 | 0.25 | Table
4 | 0.5 | 1.0 | Plot

I believe this is compatible with the existing semantics for hint weights.

**Comment by larkin** [comment]
@VWoeltjen magic number is an overloaded term, what I mean is arbitrary.   You're supposing a range of `[0, 1]`, but this is javascript, so why not `[Number.MIN_SAFE_INTEGER, Number.MAX_SAFE_INTEGER]`?

It doesn't really matter, so long as we document it.

**Comment by larkin** [comment]
This is resolved with #1557, depends on correct telemetry hinting to operate.
