### ISSUE TITLE
[Performance] Strangely high CPU usage in Chrome when editing a display layout

### ISSUE THREAD

**Issue by BogdanAlexandru** [nasa/openmct#1603]
See this gif here: http://imgur.com/QAMfBoc
As soon as I start editing an empty display layout, the CPU usage in Chrome 58.0.3029.110 (64-bit) (latest at the time of writing) goes nuts and my laptop turns into a wind turbine.

Normally I wouldn't mind this that much, but the UI itself also ends up being very sluggish. For example, scrolling in the save as dialog shown in the gif feels unpleasant to say the least.

Quitting the edit process results in smooth performance once again.

It's been a while since I tried out a build of OpenMCT, a few months ago (around January) I'm almost 100% sure I used the same laptop for it and the bad Chrome behavior did not exist. I'm not sure if it also happens in Firefox, I've yet to try it out.

I'm going to investigate this as I continue work on my PRs, and come back with any other info I can spot. Let me know if you can't repro it, it could be local to my machine settings. No other machine available to test on my side atm.

Running it on Win 10 Home (updated to latest version), i5 6200U, integrated GPU.

**Comment by VWoeltjen** [comment]
Thanks for reporting this. I'm able to reproduce locally; `top` shows Chrome at 10-25% in Browse, 85-115% in Edit mode for the same layout.

Did some initial investigation. Profiling didn't show any hotspots, and `example/profiling` showed very modest changes in watch/digest counts. Next I tried using the [animation tab](https://developers.google.com/web/tools/chrome-devtools/inspect-styles/animations) in Chrome's dev tools - aha! When animations are paused, the issue goes away.

Based on fiddling with CSS, it seems like it's the pulsing animation `pulseNew` in particular that is causing this; guessing that is causing more redrawing than we might expect.

Assigning to @charlesh88 to look at performance here. There's an approach for [performant animated box shadows](http://tobiasahlin.com/blog/how-to-animate-box-shadow/) that doesn't translate exactly, but might be a decent starting point; basic idea is to use an ::after pseudo-element for the animated part, and animate the opacity on that to reduce the amount of actual redrawing that the browser (thinks it) needs to do.

**Comment by VWoeltjen** [comment]
Also, @larkin / @charlesh88, does the "critical" designation seem right to you? This doesn't observably impact performance in my dev environment, but the performance impact is steep enough that I could see this creating problems for users.

**Comment by larkin** [comment]
@BogdanAlexandru great job reporting this.  

Critical, maybe not.  We have to be very careful with keyframe animation-- they're not implemented well and generally cause browser repaints at 60hz which causes significant performance overhead.  Especially when you consider there are many levels of transparencies and other calculations it's forcing for each frame for every item inside of the edit pane.

I had mentioned this performance problem to @charlesh88  before and he was happy to drop the animation or replace with something different.  It's good to get this issue opened and it should be a quick fix.

**Comment by larkin** [comment]
Here's a good breakdown of the keyframe animation problems from when this was a problem in VSCode:  https://github.com/Microsoft/vscode/issues/22900

**Comment by VWoeltjen** [comment]
Removed critical flag per above.

Candidate fix: Render the border by [animating the opacity of an `::after` pseudo-element](http://tobiasahlin.com/blog/how-to-animate-box-shadow/) with [`will-change: opacity`](https://github.com/Microsoft/vscode/issues/22900#issuecomment-288804045). Tried locally by editing CSS directly, seems to work.

**Comment by BogdanAlexandru** [comment]
Thanks a lot for the quick response to this! 👍 It's very appreciated, the issue does hurt when you work in edit mode often, the UI is simply crawling.

**Comment by charlesh88** [comment]
@BogdanAlexandru Was unaware of this issue about keyframing anims in CSS, thanks for bringing this up. @VWoeltjen, great pointer to a solution. There's other spots where I'm using keyframing, I'm going to look across the app and convert or remove.

**Comment by charlesh88** [comment]
Testing notes:
- Start Open MCT, make a new Display Layout but don't populate it with anything. Save and exit to Browse mode.
- In terminal, run top or an equivalent tool that will report on CPU usage of the Chrome browser. Observe the CPU usage for the instance of Chrome that is running Open MCT, which should be somewhere around 15 - 18%. Close other Chrome browser windows if it's unclear which is which.
- Click to edit the layout. Once in Edit mode, observe the CPU usage of Chrome in top again: it may have gone up while going into Edit mode, but should settle back down again and stay about the same as during Browse mode.
