### ISSUE TITLE
[Build] NPM packages update

### ISSUE THREAD

**Issue by slinto** [nasa/openmct#1604]
Node 8 is out. I updated to new node and gulp-sass not working with this version, I trying update to 3.1.0 and everything looks good. But I see there more out dated dev packages.

- requirejs: _2.1.22 -> 2.3.3_
- gulp-sass: _2.2.0 -> 3.1.0_
- gulp-jscs: _3.0.2 -> 4.0.0_
- gulp-requirejs-optimize: _0.3.2 -> 1.2.0_
- gulp-sourcemaps: _1.12.0 -> 2.6.0_

and karma dependencies
- karma: _0.13.22 -> 1.7.0_
- karma-chrome-launcher: _0.1.12 -> 2.1.1_
- karma-cli: _0.0.4 -> 1.0.1_
- karma-coverage: _0.5.5 -> 1.1.1_

I think there is a lot of improvements in this packages. 
What do you think about update (and test) all of this deps?

Thanks.

**Comment by larkin** [comment]
@slinto Our most likely update will be from node 4 (LTS) to node 6 (LTS) in a Month (after our next release).  We might then bump again to node 8 when it enters LTS in October 2017.  

Can we come back to this in a month?

**Comment by slinto** [comment]
Ok, if you need help with an update from node 4 to 6, I'm ready for this.

**Comment by larkin** [comment]
merging to #102
