### ISSUE TITLE
[Build] Can't run from dist

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1605]
For dev/testing purposes, it's sometimes useful to run directly from `dist` (e.g. to verify built files...)

Currently, when serving flat files from `dist` the application fails to load due to a missing requirejs dependency. Also appears that some assets are missing (e.g. background image for splash graphic)

**Comment by larkin** [comment]
I thinking dist should have a different `index.html` that doesn't use requirejs and calls `openmct.setAssetPath` with the correct arguments.

**Comment by ev1stensberg** [comment]
Is this something I could work on? Resuming the work on YAMCS plugin but need some feedback from @akhenry first.

**Comment by larkin** [comment]
maybe a wontfix, expected usage would be for us to point users to something like openmct-demo instead.

**Comment by VWoeltjen** [comment]
Agree with a wontfix on this; I got used to working around this pretty quickly on #1707, and do like how reasonably clean `dist` is getting.
