### ISSUE TITLE
[Persistence] 404s on Style Guide objects with CouchDB

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1607]
When running Open MCT with CouchDB, the following errors can be observed on console:

```
GET http://localhost:5984/openmct/ROOT 404 (Object Not Found)
GET http://localhost:5984/openmct/intro 404 (Object Not Found)
GET http://localhost:5984/openmct/standards 404 (Object Not Found)
GET http://localhost:5984/openmct/colors 404 (Object Not Found)
GET http://localhost:5984/openmct/glyphs 404 (Object Not Found)
GET http://localhost:5984/openmct/controls 404 (Object Not Found)
GET http://localhost:5984/openmct/input 404 (Object Not Found)
GET http://localhost:5984/openmct/menus 404 (Object Not Found)
```

Looks like Open MCT is trying to fetch these objects from CouchDB. These objects are in-memory, and given that we have namespace support Open MCT should be able to determine that and not issue these requests.

**Comment by VWoeltjen** [comment]
Marking trivial, as these 404s are benign (just console noise)

**Comment by larkin** [comment]
I think, when we move fully to new object API, these won't happen anymore?

**Comment by larkin** [comment]
We could probably prevent the ROOT call too-- there's no reason that should hit the database.
