### ISSUE TITLE
Stacked plots should allow sub object selection

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1609]
Follow on to #1590 and the "new plots" work from @larkin in May 2017: we need to give the configuration options that were brought to overlay plots to stacked plots as well. [Design is here](https://drive.google.com/open?id=0B0v27OM1JkSeR001RFJZMk43QVk), starting on page 92.

**Comment by larkin** [comment]
Retitling this to track intent:  Stacked plots should 

a) support sub object selection.
b) auto-create overlay plots when drag-dropping telemetry points.

**Comment by mudinthewater** [comment]
Stacked plots should also include the frame/title (if it exists) around an overlay plot if one is dragged on. Right now it just pulls the tlm points. Either that or a handy way of entering text would work - I just want to stack a bunch of overlays and label them all nicely.

**Comment by shefalijoshi** [comment]
@charlesh88 What should the behavior be for Overlay Plots that are added to stacked plots? Should it not be listed in the series?

**Comment by charlesh88** [comment]
Per our discussion today:
- We're going to leverage a sub-object editing approach in Stacked Plots (SP). The user will click on each child element in the stack in the main view to select it; once selected, that element takes over the context in the Inspector.
- To edit the properties for the SP, the user will have to de-select any selected child plot to "climb up" to the context of the containing SP. We should allow a click on the main view header to accomplish this, and we should consider a clickable breadcrumb element that displays as a global element while editing in the Inspector. @charlesh88 to add this as a separate enhancement request.
- Overlay Plots (OP) selected while editing an SP will display their Inspectors as if in the main view, with the exception of the Legend section, which will be hidden. Any pre-existing legend settings in the OP need to be overridden by the SP's settings.
- Telemetry end points in an SP will be styleable, but the applied styles will only pertain to that element when viewed in that SP, consistent with our approach elsewhere.
- Overlay Plot styling from within an SP will behave the same as if in a layout, with styles set while editing an OP in an SP being persisted with the main OP object.
-

**Comment by shefalijoshi** [comment]
Testing Notes:

- Create an Overlay Plot, add telemetry to it
- Create a Stacked Plot
- Add the Overlay Plot to the Stacked Plot
- Drag another telemetry endpoint (not overlay) to the Stacked Plot and save it.

Ensure that all the rules specified in this comment work: https://github.com/nasa/openmct/issues/1609#issuecomment-1079513693

**Comment by shefalijoshi** [comment]
Testing Instructions: See https://github.com/nasa/openmct/issues/1609#issuecomment-1079513693

**Comment by charlesh88** [comment]
Verified fixed Testathon 6-9-22.

**Comment by michaelrogers** [comment]
Verified fixed in testathon 06/09/22.
