### ISSUE TITLE
[Telemetry] Errors on console

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1618]
Third-party plugin author reports seeing the following errors on console:

 
> angular.min.js:110 TypeError: Cannot read property 'source' of undefined
>    at t.requestData (http://localhost:8080/dist/openmct.js:34:16561)
>    at n (http://localhost:8080/dist/openmct.js:34:21604)
>    at o (http://localhost:8080/dist/openmct.js:34:21819)
>    at Array.map (native)
>    at s (http://localhost:8080/dist/openmct.js:34:21857)
>    at http://localhost:8080/dist/openmct.js:3:16972
>    at p.$eval (http://localhost:8080/dist/openmct.js:3:24445)
>    at p.$digest (http://localhost:8080/dist/openmct.js:3:22940)
>    at p.$apply (http://localhost:8080/dist/openmct.js:3:24736)
>    at http://localhost:8080/dist/openmct.js:3:31231
> 
> and
>
> angular.min.js:110 TypeError: Cannot read property 'source' of undefined
>     at t.subscribe (http://localhost:8080/dist/openmct.js:34:17194)
>     at f (http://localhost:8080/dist/openmct.js:34:19402)
>     at Array.map (native)
>     at h (http://localhost:8080/dist/openmct.js:34:19456)
>     at http://localhost:8080/dist/openmct.js:3:16972
>     at p.$eval (http://localhost:8080/dist/openmct.js:3:24445)
>     at p.$digest (http://localhost:8080/dist/openmct.js:3:22940)
>     at p.$apply (http://localhost:8080/dist/openmct.js:3:24736)
>     at http://localhost:8080/dist/openmct.js:3:31231
>     at i (http://localhost:8080/dist/openmct.js:2:10739)
 
Suspect this is due to absence of a `telemetry` property on the domain object being viewed. Notably, subscribe/requestData are legacy calls. See email thread "Open MCT metadata question" for background/context

**Comment by larkin** [comment]
because there's no historical imagery provider, the tableview and plot view hit telemetrycapbility.requestData which is where this error occurs. 

It's triggering because the image telemetry metadata doesn't specify a `domain`.
