### ISSUE TITLE
[Navigation] Extra back required to undo navigation (sometimes)

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1621]
Steps to reproduce:

1. Create a Folder with an Example Imagery object in it.
2. View the Folder in Items mode
3. Navigate to the Example Imagery
4. Hit back. __Observe__: Still looking at the Example Imagery
5. Hit back. Now you're looking at the Folder again!

Expected behavior would be to return to the Folder on Step 4. Note that on this step, the URL does change; "view=items" becomes "view=imagery". 

May become obsolete by view-as-object

**Comment by VWoeltjen** [comment]
Observed during self-testing for #1620

**Comment by larkin** [comment]
Not resolved by https://github.com/nasa/openmct/pull/1638, but the commit message for https://github.com/nasa/openmct/pull/1638/commits/fa042cbd287b6240ca533327f0158ab35f7f5041 points to the underlying cause.

**Comment by larkin** [comment]
closing this as wontfix as it will likely be outdated when we eventually rework navigation.
