### ISSUE TITLE
Add Number input as mct-control

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1628]
@adoubekk Aaron's work on Fixed Position editing via text inputs would really benefit from HTML5 "number" inputs, as would quite a few other places in the UI that require numbers-only input.

**Comment by adoubekk** [comment]
I added some internal type control for the fixed position inputs, but a numeric input control type would be a more natural solution

**Comment by charlesh88** [comment]
@adoubekk Your wish is my command. I just pushed up a topic branch that adds a "numberfield" input to mct-control, similar to "textfield". Supports min, max and step properties.

Talking with @larkin I'm going to see if I can fast-track this getting integrated into master, and you can pull it down from there.
