### ISSUE TITLE
[BUILD] Running NPM doesn't auto install a few dependencies

### ISSUE THREAD

**Issue by stevesdawg** [nasa/openmct#1631]
I am a newbie at node.js and npm. I'm on Ubuntu bash for windows 10.

When I clone the repo, and run `npm install`, it fails because it can't find some modules right out of the box.
With every run of `npm install` I installed a new package that it was missing. Is this an issue with my setup or system? Can the dependency list be updated so that it installs *everything* for a node noob like me, right out of the box?

These are the packages I had to install manually myself:
- mout
- bower-logger
- bower-config

After installing the above three packages, npm throws another error:
```
Error: Cannot find module './util/abbreviations'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/mnt/c/Users/Shrivathsav/Documents/GaTech/YJSP/repositories/openmct/node_modules/bower/lib/index.js:3:21)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

**Comment by larkin** [comment]
@stevesdawg it's probably due to your NPM or node version. We are currently compatible with node4 (lts) and npm<5. Can you tell me what you are running?

**Comment by stevesdawg** [comment]
@larkin 
npm 3.3.6
node 5.0.0

Sidenote. I cloned version 0.11.0 of the openmct, and npm install installed everything properly, and npm start successfully launched the server. Unfortunately, the most current code on master doesn't behave the same way for me :/

**Comment by larkin** [comment]
@stevesdawg Node v5.0.0 is older (2 years) than the latest Node v4.x (LTS).  You should install the latest Node v4 LTS version and try again.  If you're still having a problem, do a fresh clone and install and attach the contents of npm_debug.log.

For more on Node LTS releases, check out the working group here: https://github.com/nodejs/LTS

**Comment by larkin** [comment]
@stevesdawg Let me know if you're still experiencing this problem when using a newer version of node.

**Comment by stevesdawg** [comment]
@larkin sorry about the delay. I still haven't checked. I'm continuing development on node 5.0.0. I will try to test out the most up to date mct code with Node 4LTS as soon as I can and let you know.

**Comment by larkin** [comment]
considering resolved.
