### ISSUE TITLE
remove "no services to aggregate for telemetry" warning

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1641]
With the new Telemetry API, warnings are thrown in the console because there are no services to aggregate for telemetry.  We should disable this warning so that it isn't a false flag for developers.

reported here: https://github.com/nasa/openmct-tutorial/issues/15

Also reported in other places.

**Comment by larkin** [comment]
Also remove the "Telemetry service unavailable" warning.

**Comment by larkin** [comment]
To reproduce: run the [openmct tutorial](https://github.com/nasa/openmct-tutorial) and view a telemetry point.  You'll see these warnings in console.

**Comment by luisschubert** [comment]
@larkin were you thinking to just comment out/ delete the warnings entirely? 

Telemetry Service Unavailable:
platform/telemetry/src/TelemetryCapability.js Line 120

No services to aggregate for telemetry:
platform/framework/src/register/ServiceCompositor.js Line 169 - 175

**Comment by larkin** [comment]
@luisschubert remove, or change their severity to info, which should be below our default log level.

**Comment by larkin** [comment]
Closed in #1643.
