### ISSUE TITLE
Summary widgets

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1644]
This is the overall user story to cover Summary widgets. 

### Overview
- A new domain object that can be added to a Layout.
- Displays as a button-type of object with color and text.
- Allows the user to evaluate *n* telemetry elements against multiple "rules", with each rule controlling the look of the widget itself.
- The widget can link to another domain object or any arbitrary URL, optionally in a new tab.

### Details
- User can add multiple telemetry elements to the widget to a TBD maximum.
  - Can Packets be added? Ideally, yes.
  - Can Folders be added? Idea is that the widget would evaluate all evaluate-able elements in that folder as if they were directly in the object. Not sure this is useful or clear.
- User can define multiple rules to be eval'd against the telem elements in the widget.
  - Each rule will have a single output effect on the widget, such as turning it a color or changing text.
  - Each rule may be a single evaluation like "When `any` telemetry is `over limit`" or potentially a chain of AND statements, like "When `any` telemetry is `over limit` AND `specific telemetry` `telemetry ID` is `greater than` `100>`
- The widget can have a URL associated with it that allows it to link to another domain object or any arbitrary URL.
  - Optionally opens in a new tab.
  - Allow different URL per rule?

**Comment by charlesh88** [comment]
@adoubekk Aaron, here's where I'm beginning to stub in what we're thinking for Summary widgets. This needs to be socialized with the team, I'll be making that happen next week.

**Comment by charlesh88** [comment]
Updated UI has been added to Google Docs: https://drive.google.com/open?id=0B0v27OM1JkSeb2ZIejZsR21xbVU

@adoubekk Aaron, please review in detail and ping me with any questions. There's some new markup and CSS involved with this that I'll be doing - any markup and styling you do should be as minimal as possible so you can see what you're doing, but no more. Let's work together to make it as easy as possible for you to integrate what I deliver.

**Comment by adoubekk** [comment]
@charlesh88 Latest commit has much of the core functionality implemented; if you've got a minute to look at this, I'd like to get your thoughts. Also have a couple questions about some UI implementation

**Comment by charlesh88** [comment]
WIP in branch summary-widgets-styling (old remote version of this branch deleted; have started anew from latest summary-widgets branch)

**Comment by larkin** [comment]
related to #1669 #1654 , merging them into this.

**Comment by charlesh88** [comment]
More detail on this related PR #1668.

### Testing Notes

1. Create one or more Sine Wave Generator (SWG) objects. Set them to use different amplitudes, like 5 or 10. Set the period to a number like 5 which will change the value at a good pace.
1. Create a new Summary Widget. Drag in the first SWG you created.
1. Interact with the Rules interface area by expanding the single initial "Default" rule. Try changing the Rule name, entering a new label, changing the label's icon, adding a message and changing the style associated with this rule. Note that all changes will be reflected instantly in the thumbnail version of the widget in the rule you're operating on. When you only have the default condition, you'll see all the changes reflect in the larger view of the widget at the top of the display area.
1. Add a new Rule by clicking "Add Rule".
1. Change the label text and style of this Rule; again, changes should be reflected instantly.
1. Define conditions for this rule by interacting with the "Trigger when" and "when" rows of the condition. Use "Sine" or "Cosine" to evaluate numeric values from the SWG. For example, use `Trigger when <any condition is met>`
`when <any telemetry> <Sine> <is greater than> [0]`
Note that the large widget preview will start to update when the SWG telemetry matches your condition.
1. Duplicate the current rule by mousing over it and clicking the Duplicate icon button on the right. Observe that all properties and settings from the original were correctly copied.
1. Change the style of this rule so that it is visually distinguishable from the rule you just copied. Change `<is greater than>` to `<is less than>`. You now have two mutually exclusive and collectively exhaustive rules in the widget. 
1. Save and exit editing the widget.
1. Create a new Layout, and drag in your widget and the SWG you included in the widget. Save Save and exit editing the Layout.
1. Observe your new layout: as the SWG plot rises and falls, your Widget should change its appearance as it rules match the SWG's values.

**Comment by VWoeltjen** [comment]
Verified in testathon 12/05/2017. Note that I _did_ see a save error for summary widgets, similar to what we saw during demo, but this was on first page load and was irreproducible after reloading, so I'm guessing I still had the old version cached

**Comment by dtailor90** [comment]
Created 13 Summary Widgets, added them to layout. Could not recreate save errors.

**Comment by VWoeltjen** [comment]
Found some steps to reproduce save errors (at least, they're working reliably for me at the moment), filed #1827

**Comment by larkin** [comment]
I believe this is considered closed, there are issues for follow-up tasks.

**Comment by larkin** [comment]
Testing notes for Eagle Testathon:

* Try creating summary widgets and specifying different combinations of criteria and see if results match what you expect to see.  It may help to create a fixed position display with a number of telemetry points and view that side by side with your summary widgets in a layout.
* Add multiple summary widgets to display layouts and make sure they operate correctly.
* With another tester (or two browser windows), try both viewing a layout containing summary widgets.  Try both navigating around and verify that there are no persistence errors logged.
* Try using one summary widget inside of another summary widget as criteria.  Do condition editors make sense for the available data types?   Can you successfully configure a summary widget that rolls up the status of other summary widgets?  Any thoughts for improvement?
* Try adding summary widgets to plots or tables or fixed positions-- do the results match what you'd expect?
* Try building a complex summary widget with a large number of rules and saving it.  Now duplicate that summary widget a few times and add them all to a display layout.  Is the performance okay?

**Comment by dtailor90** [comment]
Uncaught (in promise) TypeError: Cannot read property 'style' of undefined
    at t.updateState (SummaryWidgetView.js:14)
    at t.<anonymous> (SummaryWidgetView.js:53)
    at <anonymous>
When trying to save a summary widget with 2 rules. 
Also got a persist error at the same time.

**Comment by dtailor90** [comment]
Verified, telemetry being produced by Summary Widget, added it to a telemetry table, seeing values for background color, rule name etc.

**Comment by larkin** [comment]
testathon 3/15/2018: telemetry applicability is problematic-- should not be tied to telemetry property on model.  This causes problems when upgrading to a new version of openmct-- have to create new summary widgets to use as telemetry source.

**Comment by charlesh88** [comment]
Testathon 03-22-2018 - found issue:
- Navigate to a plot view (I used Dictionary > POSE_DELAYED > qx) and invoke the Create menu to create a new Summary Widget. Observe: the resulting edit interface is as if we're creating a new plot object, rather than the Summary Widget UI as expected.

**Comment by larkin** [comment]
testathon 3/22/2018: persist error when saving a brand new summary widget, with the error message Deep mentioned above.  https://github.com/nasa/openmct/issues/1644#issuecomment-373543444 may not be reproducible with localstorage but definitely possible with couch.

**Comment by akhenry** [comment]
Note that the two issues described by @charlesh88 and @larkin immediately above have not been resolved yet and are carried into the Testathon for Enterprise

**Comment by charlesh88** [comment]
Testathon 03-30-2018: NOT fixed. I am still seeing the same incorrect edit interface and persistence errors that I described in the 03-22-2018 testathon comment above.

**Comment by dtailor90** [comment]
@larkin - have the above issues been resolved?

**Comment by charlesh88** [comment]
### Testing Notes July 2, 2018

Specifically, testing should focus on verifying that issues found during Testathon 03-22-2018 have been addressed:
> - Navigate to a plot (or table) view (I used Dictionary > POSE_DELAYED > qx) and invoke the Create menu to create a new Summary Widget. Observe: the resulting edit interface is as if we're creating a new plot object, rather than the Summary Widget UI as expected.
> - Saw same persist error reported elsewhere for brand new widgets

And 
> Uncaught (in promise) TypeError: Cannot read property 'style' of undefined
at t.updateState (SummaryWidgetView.js:14)
at t. (SummaryWidgetView.js:53)
at 
When trying to save a summary widget with 2 rules.
Also got a persist error at the same time.
