### ISSUE TITLE
[UX] Side tree does not stay resized on refresh

### ISSUE THREAD

**Issue by Shotokeki** [nasa/openmct#1646]
Resizing the tree is necessary (can barely fit the root level) at least on my machine, likely due to hidpi scaling being done automatically. The resize status is not saved anywhere it appears, so I have to resize it manually every time I refresh the page. This gets quite tedious over time.

It would be awesome if this was saved and auto-applied on each refresh. This gif shows the issue live:

![Imgur](http://i.imgur.com/aNkdtdh.gif)

**Comment by larkin** [comment]
@BogdanAlexandru thanks for the report.  This behavior is desired for both the tree and the inspector.

When a user resizes the tree by dragging, the resulting size should be stored in localstorage.  When a user opens openmct, the size should be read from localstorage.  If localstorage doesn't contain a value, then the size should be set the same way it is currently set.

This same behavior should apply to the inspector.

**Comment by dtailor90** [comment]
fixed in pr #1663

**Comment by ozyx** [comment]
Reopening as pane positions are no longer persistent since the Vue rewrite

**Comment by ozyx** [comment]
# Testing Instructions

1. Start Open MCT with a fresh localStorage
2. Reposition the left pane by dragging it
3. Reposition the right pane by dragging it
4. Reposition "Recent Objects" pane by dragging it
5. Refresh
6. Verify that the position of the panes persist correctly

**Comment by michaelrogers** [comment]
Fix verified locally during testathon on 2022-02-02. Pane positioning persists through a page refresh.

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 02/02/23
