### ISSUE TITLE
Style Summary Widgets

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1654]
Styling and markup for @adoubekk work on Summary Widgets.

**Comment by charlesh88** [comment]
@adoubekk *Significant* progress on markup and styling in the widgets. Don't try to merge this yet - there are a bunch of conflicts with your summary-widgets branch. I'll merge and fix mine early tomorrow and then push that back up.

**Comment by charlesh88** [comment]
@adoubekk Just pushed up my branch that merges your latest from yesterday and resolves conflicts. Suggest you merge that into what you're doing asap - that will make it easier for both of us moving forward.

**Comment by adoubekk** [comment]
@charlesh88 Merged this branch into mine, minimal conflict. New style looks awesome. Wired up some of the new markup to my implementation and pushed it up

**Comment by charlesh88** [comment]
@adoubekk Awesome! Just grabbed yours and merged in, no conflicts. Going to move ahead as far as I can before Jay gets here this morning. I've added dupe and delete buttons to the condition and am adding the new grippy icon. Time permitting, I'll create the icon palette for the Label form row based on your implementation of the color palette.

**Comment by adoubekk** [comment]
@charlesh88 New push to my branch is merged with your latest commit, adds more implementation for the new markup, and duplication

**Comment by charlesh88** [comment]
@adoubekk Just pushed latest version, includes some CSS refactoring to generalize palettes. Added the icon palette for the label, but didn't wire it up to anything. 

Note: when I merged in your stuff late today, the label text stopped appearing in the main widget - hope that wasn't the result of something I did.

**Comment by adoubekk** [comment]
@charlesh88 Apparently during the last merge I accidentally deleted the input event handlers for labels and messages, pushed up a fix

**Comment by larkin** [comment]
Merging to #1669.
