### ISSUE TITLE
[Layout] Allow enable/disable object frames in layout

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1658]
It should be possible for users to specify whether or not an object in a layout has a frame or not.  

The gesture for this, while editing a layout:
1) select object in layout (click).
2) toolbar should appear with control TBD to toggle visibility of that object's frame.
3) The selected setting is persisted in the layout for that frame.

Selection isn't implemented in the layout yet, so that will need to be done.  It should mirror the selection behavior of the fixed position display's edit mode.

mentioning @charlesh88 for design tasks.

**Comment by charlesh88** [comment]
Provide a UI sketch of this.

**Comment by charlesh88** [comment]
@psarram New glyphs have been created for the show/hide frames button, and are pending a merge to master with #1667. Once merged, I can go in and update the JSON for the button and effect any other HTML/CSS mods that are needed.

**Comment by charlesh88** [comment]
@psarram Pushed my stuff to branch layout-issue-1658-styling. Repaired what I broke in Fixed Position objects so that's looking pretty good as this point.

Still to-do:
- Clean up CSS
- "no-frame" styling
- Checkout and fix Telem Panels

**Comment by charlesh88** [comment]
@psarram @larkin More pushes to layout-issue-1658-styling including snapping grids displaying in Layouts, and View Large and view Switcher controls being displayed when a Layout frame is in `no-frame` state. I also now suppress the View Large buttons for elements it doesn't make sense for, such as Clocks, Timers and Hyperlinks.

**Comment by charlesh88** [comment]
@psarram Just pushed to layout-issue-1658-styling the CSS mods that prevent sub-selection in Layout editing, as well as some polishing on the hover borders classes for Layouts. Please merge in when you can.
