### ISSUE TITLE
[Performance] Replace Angular listeners with CSS

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#166]
@larkin points out there are several places where Angular is being used to effect the visual appearance of things when CSS styles could achieve the same. This is highly undesirable from a performance perspective, both because JS will typically be less efficient than CSS, and especially because doing so via Angular results in extra digest cycles.

**Comment by charlesh88** [comment]
@larkin @VWoeltjen Is this still a problem, and if so, can you point me to areas in particular where it is?

**Comment by larkin** [comment]
Not worth spending development cycles to tackle this directly when current system works well-enough.
