### ISSUE TITLE
Update glyphs

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1661]
In order to avoid multiple versions of the glyphs styles floating around in different topic branches, I will now always be adding new glyphs to the branch `glyphs-update`, then merging that branch into whatever topic branches need them, while continuing to merge `glyphs-update` into master.

**Comment by larkin** [comment]
@charlesh88 A long lived `glyphs-update` branch will cause problems as it will get out of sync with master and will cause merge issues-- especially if people are also merging it into their topic branches, which then get rebased or merge in master.  (This has already happened and causes big trouble).

You should make a new branch off of master per glyph or set of glyphs and open a PR for master.  I'd be willing to add a no-review exception to our process for glyph-only changes too, though generally if you're working on an issue with someone they should be able to R&I that branch immediately.  You should then delete the local branch.

Topic branches then just rebase or merge master and have the glyphs.

**Comment by charlesh88** [comment]
@larkin The issue I'm having is that I've been working with issues on folks that include new glyphs that are *not* getting merged - for example, there were two new glyphs that have been in the plot update work you and I have been working on that are not yet merged.

Happy to do a separate branch per update rather than one long standing one, that makes sense. Would you be Ok if I went ahead and did the merges myself to master? This would make life around this much easier, and reduce conflicts when folks merge their topic branches back.

**Comment by larkin** [comment]
So long as you open a pull request to track the merges to master it's okay with me.  Post both author and review checklists and make a note that it's a glyph only change.
