### ISSUE TITLE
More Summary Widget styling

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1669]
From comments for @charlesh88 in #1668.

**Comment by charlesh88** [comment]
- Implementing a new CSS class `no-selection`. This renders a diagonal red line in the background of whatever element it is applied to, like this: ![screen shot 2017-08-08 at 3 05 07 pm](https://user-images.githubusercontent.com/1056412/29096717-05bf7e34-7c4b-11e7-9745-99959ea87522.png). 
  - color.html (used for color palettes in Angular-legacy interface elements) updated accordingly. 
  - Added `no-selection` to "None" selection choice in /src/plugins/summaryWidget/res/input/paletteTemplate.html
  - @adoubekk When the user has selected "None" in the palette, you'll need to modify the palette code to add the class `no-selection` to the `t-swatch` span in /src/plugins/summaryWidget/res/input/paletteTemplate.html
- Added new CSS class `selected` and implemented in color.html.
  - @adoubekk When the user makes a palette selection, you'll need to modify the palette code to add the class `selected` to that `.s-palette-item` element.

**Comment by charlesh88** [comment]
@adoubekk Just pushed up final palette colors. Go ahead and merge this into yours when you like.

**Comment by adoubekk** [comment]
@charlesh88 Should the selected class apply to icon palettes as well? Currently, applying it to an icon palette item overrides its own icon with a check:
![screen shot 2017-08-10 at 10 15 21 am](https://user-images.githubusercontent.com/16962045/29182773-f3871680-7db4-11e7-984b-8f4bd51cd0ac.png)
![screen shot 2017-08-10 at 10 15 32 am](https://user-images.githubusercontent.com/16962045/29182767-f21d50c0-7db4-11e7-83d1-5b901b410b30.png)

**Comment by charlesh88** [comment]
@adoubekk Good catch on the palette issues from last week; I pushed up changes that fix that, and also just pushed up some mods that fix some text alignment issues with the custom selects. Go ahead and merge in when it's convenient.

**Comment by adoubekk** [comment]
@charlesh88 Merged, everything is looking good

**Comment by charlesh88** [comment]
@adoubekk Just pushed some mods to branch summary-widget-styling-2 that makes the thumbs show their associated icon and label text. This gives more feedback to the user as they configure the style and label of each rule. Please pull in when you get a chance.

**Comment by adoubekk** [comment]
@charlesh88 Merged, resolved some conflicts with changed rule implementation. Might want pull this down again and make sure it still works like you expect.

**Comment by charlesh88** [comment]
@adoubekk @larkin I've simplified the markup for the label so it's more inline with the markup and layout styles of the Hyperlink object; those changes are pushed to branch summary-widget-styling-2 but haven't been integrated yet into Aaron's work.

**Comment by charlesh88** [comment]
Need to take a look at latest here, @larkin says that Edit stuff was moved into Edit mode, and there are remaining style issues.

**Comment by larkin** [comment]
merging to original issue, https://github.com/nasa/openmct/issues/1644
