### ISSUE TITLE
[Plot] Disallow pan outside of time conductor bounds

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#167]
When time conductor boundaries are in force, disallow panning in a single plot outside of those time bounds.

**Comment by VWoeltjen** [comment]
Placing in Asimov, but this is a decent candidate to move to following sprint, since it was a late add.

**Comment by VWoeltjen** [comment]
This is no longer desired behavior, likely will want to close this as a wont-fix

**Comment by larkin** [comment]
Not desired behavior, wontfix closing.
