### ISSUE TITLE
[Imagery] combine history and realtime views

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1676]
There are currently separate image history and realtime views--
history:  strip of thumbnails.
realtime: shows latest image.

These should be combined into a single view:

* New images arriving in realtime should be added to the thumbnail strip and set as the large image.
* selecting an image in the thumbnail strip should pause the large view and display the thumbnail in the large view.

not a new request, @charlesh88 likely has more detailed designs.  reported by jay during live demo review.

**Comment by larkin** [comment]
@dtailor90 want to tackle this?

**Comment by charlesh88** [comment]
@dtailor90 Pushed some mods to branch imagery-issue-1676-styling, please pull down and have a look, then let's chat.

**Comment by larkin** [comment]
Merged and completed with #1699.

**Comment by charlesh88** [comment]
### Testing Notes

1. Create an example imagery object, or if available, navigate to a real-time Imagery object that is streaming data.
1. Observe: a pool of image thumbnails will build up as image data arrives. The main view area image will automatically update as new image telemetry arrives.
1. Clicking a thumbnail should "pause" the main view area and highlight that thumbnail in the pool. New thumbnails will continue to be added to the pool.
1. Unpausing in the main view area by clicking the "Play" button <img width="141" alt="screen shot 2017-10-02 at 2 39 33 pm" src="https://user-images.githubusercontent.com/1056412/31101508-da88375c-a782-11e7-897a-c8d4c7b04299.png"> will unselect the currently selected thumbnail and return the main view area to automatic update mode.

**Comment by VWoeltjen** [comment]
Verified testathon 2017-10-05; looks good, feels nice to use
