### ISSUE TITLE
inline edit object name during edit mode

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1679]
When a user is editing an object (e.g. a layout in edit mode), it should be possible for them to click on the name in the title bar and edit the object name directly.

@charlesh88 Do you think such an interaction should also be possible outside of edit mode, e.g. by doubleclicking on the name of the object?

Requested by Jay and others.

**Comment by charlesh88** [comment]
My thoughts: 
- That element is in object-header.html, which is used by many components. The span `.title-label` needs to be an input; we can use CSS to control when it visually manifests edit affordances and when it doesn't. Alternately, we make a new version of the object-header component specifically for this.
- I think the field should be editable in Browse mode, we can do it like this (ripping off Google Docs):
  - Title looks like normal, but when user hovers over it it gets a subtle rounded rectangle "input" look, done with CSS.
  - If the user clicks, the field border strengthens and it gets an inset shadow, now looking fully like an input. We put a text insertion point into the input.
- The field is editable until the user clicks elsewhere (including navigating elsewhere) or hits the Return/Enter key.
- Blank names are an error and should keep the field in input mode until the user enters something. I need to design a style for errors in a control like this; for now, let's apply the CSS style `.error`  to the input when in that condition.

**Comment by larkin** [comment]
@charlesh88 the only problem (where css isn't a good enough solution) is that `object-header.html` is used in `frame.html`.  I'm thinking you make a new component for `frame-header` so that you can make changes in `object-header` without impacting frames.  My .2c

**Comment by charlesh88** [comment]
@larkin Yes, and once we have sub-object editing we'll want this to work there too, so we should go for it. CSS would be good enough solution; if desired, pure CSS could be used to prevent editing in a frames context.

**Comment by larkin** [comment]
How would you prevent editing via pure CSS-- disable pointer events?  Would that not prevent issues with context menus, selection, and dragging?  Probably getting ahead of myself.

**Comment by charlesh88** [comment]
@larkin Yes, disable pointer-events only on the input. If the click is higher up the hierarchy, that would be a problem as you say - but the click to edit the name shouldn't be overlapping other elements that also handle clicks.

**Comment by psarram** [comment]
@charles my changes are in inline-edit-issue-1679 branch. In addition to the CSS style .error in the case of blank names, .inline-edit is also applied when the field is clicked and editable.

If the name is blank and enter is pressed, the focus remains on the field and the cursor is in the field, whereas clicking elsewhere removes the focus. Which behavior do we want in case of an error in either situations? I'd think to keep the focus.

**Comment by charlesh88** [comment]
### Testing notes:

1. Select an object in the tree, then hover over its title in the main view area. A rectangle will appear around the title:
![screen shot 2017-09-29 at 10 35 26 am](https://user-images.githubusercontent.com/1056412/31028180-f0141e20-a501-11e7-905a-750bf478386f.png)
1. Click on the title. The field will now get an inset shadow and the text can be edited:
![screen shot 2017-09-29 at 10 36 45 am](https://user-images.githubusercontent.com/1056412/31028247-1be773a8-a502-11e7-89a9-419a732d8862.png)
1. Alter the text, then click anywhere else, press the "Return" key or tab out of the field. The object should now have the new name in the main view area and in the tree.
1. Test this while in browse mode and while editing an object.

**Comment by larkin** [comment]
@charlesh88 @psarram Note from pre-testing: objects which can't be edited should not be inline-editable.  Can be demonstrated by editing objects in the style guide (see screenshot) or editing telemetry points in tutorial/WARP/VISTA.

![screen shot 2017-10-02 at 11 07 12 am](https://user-images.githubusercontent.com/226503/31092048-ffc2221a-a761-11e7-85e4-5384ccaf9241.png)

**Comment by VWoeltjen** [comment]
Verified during testathon 2017-10-05, excepting bugs reported as #1757 and #1746

**Comment by jtrimble2100** [comment]
I created a layout, clicked and named it - very nice feature.
