### ISSUE TITLE
disable spellcheck on date fields

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1682]
different browsers attempt to spell check date fields which may cause weird feedback to end users, and it is not consistent with the validation logic applied by openmct.  We should disable spell check and autocorrect on date input fields.  we should also consider disabling it for other controls where it could be confusing.

**Comment by ev1stensberg** [comment]
This could be closed if implemented?

**Comment by larkin** [comment]
2018-07-02: Uncertain which browser was triggering this issue.  Can't reproduced with firefox, chrome, or safari.
