### ISSUE TITLE
Fix Timeline vertical splitter sync

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1686]
![screen shot 2017-08-28 at 11 06 52 am](https://user-images.githubusercontent.com/1056412/29786686-08cc1f06-8be1-11e7-88b3-6be3a67034e0.png)

**Comment by VWoeltjen** [comment]
Looks like this was introduced by #1663; I think the user's position is competing with positions from local storage for these.

**Comment by dtailor90** [comment]
Fixed in pr #1692
