### ISSUE TITLE
Timeline Gantt area not resizing on zoom

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1687]
Zooming out in the Timeline causes it to not proportionally extend to the right; consequently it is getting out of sync with the Resource Graph area.

![screen shot 2017-08-28 at 11 35 31 am](https://user-images.githubusercontent.com/1056412/29787806-24cca1b8-8be5-11e7-8497-392c93d0875f.png)

**Comment by VWoeltjen** [comment]
Believe this is fixed by changes to zoom logic to avoid invalid bounds, from 14592d1c3e70a4074f3c503f4f3ae33a193fef61 in #1694. Marking unverified to check this during future testathon.

**Comment by jtrimble2100** [comment]
Appears to be fixed, see screenshot. 

![screen shot 2017-10-05 at 4 55 34 pm](https://user-images.githubusercontent.com/2153309/31257558-0e43ad2a-a9ee-11e7-816d-eb7ededeb0fe.png)
