### ISSUE TITLE
[Timelines] Timeline Auto-follow Mode

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1688]
Allow the Timeline view to follow the "current" time in whatever time system makes sense. Desired for WARP EOFY 2017 Capability Demo, stems from needs identified during RP15 DOT. 

@VWoeltjen @costigan Updated UI now available at https://drive.google.com/open?id=0B0v27OM1JkSeR001RFJZMk43QVk starting on page 57.

### Notes
- Allow two key things: 1) Let the Timeline sync to the Time Conductor as other objects do; 2) Allow the Time Conductor to use a specific Timer as its timebase, operating as if in real-time. Number 1 has implications in that the Timeline view will need to be able to display time extents beyond the duration of a given Timeline.
- What to do if Timer is countdown? Does Time Conductor progress backwards?
- Pausing or resetting a bound Timer would pause or restart time in the Time Conductor immediately and in all synced displays.
- All Timelines are in SET currently. Timers are in UTC. This would need to reconciled.
- Allow Timeline to be unsynced and then resynced with the Time Conductor.
- Timeline should display a "Follow" line 1 that is to the left of the right-most edge of the Gantt area. The user should be able to drag the line itself to set and persist a desired visual offset.
- Pan should behave as in other objects, freezing the Timeline with a visual indication of that state as in other unsynced objects. Ideally, if the view is frozen and the Follow line is visible, it would continue to move relative to the Gantt area.
- Zoom could operate independently of tracking without freezing the view.

**Comment by charlesh88** [comment]
@costigan @larkin Please have a look and add any comments.

**Comment by VWoeltjen** [comment]
> - What to do if Timer is countdown? Does Time Conductor progress backwards?

"Countdown" timers are really counting up through negative durations. Don't think any difference is necessary here. Given the way SET is defined, a "countdown" timer would always be somewhere off the left edge of a timeline (once it's greater than SET 00:00:00, it becomes a "countup" timer)

> - Pausing or resetting a bound Timer would pause or restart time in the Time Conductor immediately and in all synced displays.

Ah, good case to consider. I think this will be one of the last things to implement; I'm curious to see what happens when this is not given any special attention.

> - All Timelines are in SET currently. Timers are in UTC. This would need to reconciled.

Timers are nice because they define a single reference time. If we presume this UTC time to be SET=0, that's all the reconciliation we need.

> - Allow Timeline to be unsynced and then resynced with the Time Conductor.
> - Timeline should display a "Follow" line 1 that is to the left of the right-most edge of the Gantt area. The user should be able to drag the line itself to set and persist a desired visual offset.
> - Pan should behave as in other objects, freezing the Timeline with a visual indication of that state as in other unsynced objects. Ideally, if the view is frozen and the Follow line is visible, it would continue to move relative to the Gantt area.

Agree on all of these; which are needed for demo? Would like to break down this implementation task a bit.

**Comment by VWoeltjen** [comment]
> 2) Allow the Time Conductor to use a specific Timer as its timebase, operating as if in real-time. 

As I get into the details of implementing this, I realize it's a bit of a non sequitur. One of two things will be true:

* The Timer is interpreted as UTC, in which case every timer is just equivalent to the Local Clock (so just use the local clock) and not useful for Timelines
* The Timer is interpreted as a positive or negative time; this would make it correct for SET-based timelines, but totally useless for telemetry viewing (unless we convert telemetry to SET or something, but that seems silly)

The Timer is useful for the conversion from UTC to SET, which is only relevant to Timelines. I'm going to avoid sticking this in the time conductor for now; I'll use an indicator or something else simple, and we can review the UI later.

**Comment by charlesh88** [comment]
Need to discuss:
- Best way to allow the Follow Line to extend down into the Resource Graph area. Moving the Follow Line out of the div that wraps the timeline-ticks (now `l-timeline-gantt-header-w`) causes position sync to fail when zooming.
- Horizontally scrolling while the Timeline is in follow time bounds mode doesn't work - the JS keeps fighting the user. We should break the Timeline out of that mode on that gesture.

Stashing WIP in my own topic branch for now, timeline-follow-1688-styling.

**Comment by charlesh88** [comment]
@charlesh88 WIP in branch timeline-follow-1688-styling; image captures below based on that branch.

@VWoeltjen I'm seeing some weird behavior re. the Follow Line when zooming in the Timeline: when zooming out, I'll hit a threshold where suddenly the Follow Line is positioned incorrectly: in the sequence below, I zoom out from the initial condition of following the TC extents. All is well in images 1 -3, but you can see the Follow Line is clearly off in image 4. This always seems to occur when the text labels of each Gantt extent initially come back into view as I zoom out.

![screen shot 2017-09-18 at 3 19 03 pm](https://user-images.githubusercontent.com/1056412/30567392-fb33927a-9c84-11e7-9475-abdc1f0edf06.png)
![screen shot 2017-09-18 at 3 19 08 pm](https://user-images.githubusercontent.com/1056412/30567395-002363be-9c85-11e7-903f-0df7e4dd8aaa.png)
![screen shot 2017-09-18 at 3 19 15 pm](https://user-images.githubusercontent.com/1056412/30567398-037efa3c-9c85-11e7-8081-070965212e86.png)
![screen shot 2017-09-18 at 3 20 01 pm](https://user-images.githubusercontent.com/1056412/30567401-0751f8e4-9c85-11e7-801d-9ea77f171289.png)

**Comment by charlesh88** [comment]
### Testing Notes

**IMPORTANT: BUG #1741 SHOULD BE FIXED BEFORE WE TEST THIS**

1. Create a Timeline if you don't have one already. Make sure the Timeline is populated such that it starts at 00:00:00 and it's got some decent duration, more than 5 minutes or so.
1. Create a Timer if you don't have one already.
1. Create a new Display Layout and add both the Timer and the Timeline to it. Save the Layout and exit Edit mode.
1. Set the Time Conductor to "Local Clock" mode, and change the Conductor's Start offset from -00:30:00 to -00:01:00:
![screen shot 2017-09-29 at 11 34 47 am](https://user-images.githubusercontent.com/1056412/31030434-38b10320-a50a-11e7-92b0-6ace1ac9d694.png)
1. In the Layout, restart the Timer so it begins again at 00:00:00. Click the Timer's context menu arrow, and select "Follow Timer" from the dropdown menu:
![screen shot 2017-09-29 at 11 30 50 am](https://user-images.githubusercontent.com/1056412/31030296-aebb8b04-a509-11e7-9aef-18805d6b1a04.png)
1. Observe: the Timeline should display a vertical blue "Follow Line" with a Timer icon at the top. The line will track across the Timeline, corresponding with the Timer's current time:
![screen shot 2017-09-29 at 11 31 59 am](https://user-images.githubusercontent.com/1056412/31030343-d46d5724-a509-11e7-8c41-21e32b3e57c9.png)
1. When the Follow Line tracks far enough to the right side of the Timeline, the line will become static, and the Timeline will begin to scroll to the left.
![screen shot 2017-09-29 at 11 53 35 am](https://user-images.githubusercontent.com/1056412/31031192-da4ec4ae-a50c-11e7-8309-14378d93868b.png)
1. Change the zoom in the Timeline and observe: the blue Follow Line should continue to track the Timer. Additionally, the "Sync to Time Conductor Bounds" button will appear - click this button to resync the Timeline's bounds to the bounds of the Conductor.
1. Pause the Timer, observe: tracking in the Time Conductor will also pause, and the Follow Line will remain visible.

**Comment by jtrimble2100** [comment]
Works
![screen shot 2017-10-05 at 4 25 35 pm](https://user-images.githubusercontent.com/2153309/31256935-55dcd02a-a9ea-11e7-961f-c06dc9f998ec.png)

 fine, however... going from minus zoom then zooming back in can cause you to lose the line. It's still there, it's just not visible so some kind of UI element that recenters the line would be helpful. I found it by scrolling, but it was a bit dis-orienting to zoom in and lose it.

**Comment by akhenry** [comment]
Late to the party! Forgive me if I've misunderstood this and the following is total nonsense. A couple of thoughts -

1. Why are we following timers? The time API should be the sole timing reference source. Two consequences of this are that -
2. Timelines should support UTC and SET, and
3. Time Conductor should support UTC and SET

In short, SET should be a time system. Both time conductor and timelines should follow it. For now it can be controlled by a local timer that can be started and stopped arbitrarily for testing purposes, but ultimately we're going to need an external reference for SET so everyone's seeing the same thing.

Having timelines following a local timer, while the conductor is following UTC in real-time mode is confusing to me.

Timelines don't currently support UTC, which is fine, we can just support following in timelines if the SET time system is active.

**Comment by larkin** [comment]
@akhenry timers are synchronized across clients and staked to the local clock such that everyone sees the same values so long as local clocks are synchronized, and everyone will see the timeline start/stop advancing with only a single person start/stopping the timer.

It doesn't follow the time conductor is because the procedure might not have started but there is still real-time data flowing and you don't want to stop seeing realtime.  It's mainly just to coordinate execution.

And, moreso it's an experiment to support some simulations, and we'll learn more about how we think it should work from those simulations.

**Comment by akhenry** [comment]
@charlesh88 @vicfx Can we close this? Looks like Jay verified back in October, and we've run several demos using this functionality.

**Comment by akhenry** [comment]
Testers - please test general auto-follow functionality so we can remove the unverified label here :)

To setup a timeline to follow a timer -
1. Choose a timer, and from the context menu select 'follow'.
2. Navigate to a timeline (eg. WARP Demo 2017.ARC > Components > Timeline > Science Station 7)
3. Start the timer (or restart at 0 if it's already running).
4. Observe the time of interest line moving across the timeline.

**Comment by charlesh88** [comment]
Testathon 03-30-2018: verified fixed.

**Comment by psarram** [comment]
Verified fixed in Testathon 3/30/18.
