### ISSUE TITLE
[CSS] Upload glyph needed for Import action

### ISSUE THREAD

**Issue by prestonjcrowe** [nasa/openmct#1695]
There should be a dedicated upload glyph to be used by the import action, possibly a dedicated export glyph as well. This is not a pressing issue but something that @charlesh88 and I previously discussed. CSS icons for Import and Export actions are set in platform/import-export/bundle.js.

**Comment by charlesh88** [comment]
#1702 added glyphs to font; once merged will file a new PR for this update.
