### ISSUE TITLE
[Plot] Location flashes while plotting

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1696]
Steps to reproduce:

1. Create a Sine Wave Generator
2. View that Sine Wave Generator as a plot
3. Expand the Inspection area (if not already expanded)
4. __Observe:__ Location metadata flashes during every plot update.

Desired behavior is for that metadata to display continuously (instead of, you know, just flashing for no reason)

**Comment by larkin** [comment]
Believe this is a) not linked to plots and b) might have been fixed.  Closing.
