### ISSUE TITLE
[Plot] Units not shown in plots

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1697]
View a telemetry object with a defined `name` and `units` for a range.

__Observe:__ The name is shown on the left axis &ast;, but units are shown nowhere.

Users would expect units to be visible in this circumstance. This has been implemented previously, but looking over plot code, this appears to have regressed under some refactor.

This may be addressed in #1557

**Comment by VWoeltjen** [comment]
From #1684

**Comment by klepsydra-robotics** [comment]
Hi,
doing further testing, I realised I cant save the telemetry panels with the new version after the merge. I can see the following errors in the console:

openmct.js:10 No representation found for time-conductor
(anonymous) @ openmct.js:10
d @ openmct.js:41
a @ openmct.js:41
(anonymous) @ openmct.js:9
te @ openmct.js:9
g @ openmct.js:9
a @ openmct.js:9
g @ openmct.js:9
a @ openmct.js:9
(anonymous) @ openmct.js:9
s @ openmct.js:41
a @ openmct.js:41
u @ openmct.js:41
d @ openmct.js:41
$digest @ openmct.js:10
$apply @ openmct.js:10
(anonymous) @ openmct.js:12
n @ openmct.js:9
:8080/#/browse/mine/40aed213-0703-4be4-b014-bcaf949d8def/0a2ab15e-39e6-4cbe-9483-da9facec6de1?tc.mode=local&tc.timeSystem=utc&tc.startDelta=900000&tc.endDelta=0&view=plot:1 [.Offscreen-For-WebGL-0x3498cb36e800]RENDER WARNING: Render count or primcount is 0.

**Comment by larkin** [comment]
Fixed in #1557
