### ISSUE TITLE
[Imagery] Play/Pause button hidden in layout

### ISSUE THREAD

**Issue by dtailor90** [nasa/openmct#1704]
The pause play button is hidden in layout mode. User has to expand imagery in order to continue stream. 

![image](https://user-images.githubusercontent.com/13260688/30340367-24ff020c-97a7-11e7-8e5d-254c078f71aa.png)

**Comment by charlesh88** [comment]
This is an unintended consequence of hiding the local controls and then displaying on hover in frame.scss. Hover is showing the right thing, but is hiding too much.
