### ISSUE TITLE
broken sourcemaps in build

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1707]
Appears that js sourcemaps are broken when openmct is built.

Doing some debugging, it appears that this is due to the build info replace task and the header insertion.  Commenting both of these lines out results in working sourcemaps.

https://github.com/nasa/openmct/blame/master/gulpfile.js#L87-L88

```
        // .pipe(replace(options.replace))
        // .pipe(header(comment, options.replace.variables))
```

**Comment by VWoeltjen** [comment]
After a brief side trek down [a](http://requirejs.org/docs/optimization.html#sourcemaps) [modest](http://requirejs.org/docs/errors.html#sourcemapcomments) [documentation](https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler) [rabbit](https://github.com/requirejs/r.js/issues/584) [hole](https://github.com/requirejs/r.js/issues/584#issuecomment-231860537), a fix is forthcoming.

**Comment by larkin** [comment]
@VWoeltjen we use gulp-sourcemaps instead of sourcemaps built into rjs optimizer.  Does that change your solution?

**Comment by VWoeltjen** [comment]
Branch `sourcemaps-1707` has a _partial_ fix. Handling the license/version headers in a more r.js-idiomatic way gave me sourcemaps that the browser could parse, but I think the text substitution is resulting in misalignment. Think this can be fixed by moving string-replacement earlier in the pipeline; investigating.

**Comment by VWoeltjen** [comment]
Notes for testing:

- [ ]  Open About dialog. Is version info present?
  * Note that version info will _not_ be present in dev environments when running from unbuilt sources; this should be verified in a testathon or similar.
- [ ] Open Chrome console. Any errors about sourcem
- [ ] Check that [breakpoints](https://developers.google.com/web/tools/chrome-devtools/javascript/breakpoints) can be set and pause execution where expected (the `perform` method of an action like Export JSON it helpful here)
- [ ] Inspect `openmct.js`, verify that Copyright, license info, and version information are present in a comment at the top of the file.

**Comment by VWoeltjen** [comment]
Verified during testathon 20180221
