### ISSUE TITLE
Support Angular filters

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#171]
Currently there's no way of defining an [Angular filter](https://docs.angularjs.org/guide/filter) provider in our bundles, meaning that custom filters cannot easily be defined and used in mctweb. It would be nice if we could declare filters in our bundles in the same way that we declare controllers, services, and directives

**Comment by VWoeltjen** [comment]
Resolved by a50410f8ed2eb77fdca9750866113d9f85590a70 from #485
