### ISSUE TITLE
Allow user-controllable tree sorting

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1717]
Currently, the tree only displays in oldest-last sort order, but this becomes pretty unusable when the number of items grows large. The user should have access to persistent sort options:

- Created Datetime asc and desc
- Modified Datetime asc and desc
- Alphabetical (asc)

**Comment by akhenry** [comment]
What about favorites? You could mark an object as a favorite, and then it appears under a 'favorites' root at the top of navigation pane?

**Comment by larkin** [comment]
@akhenry there's a VISTA user-request for that.  Could be broken out into a separate issue, likely will get backlogged immediately.

**Comment by akhenry** [comment]
@larkin understood. I'll create an issue for it. Sounds like a potential help-wanted candidate.

**Comment by akhenry** [comment]
Created #1798
