### ISSUE TITLE
[Models] Handle migration

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#172]
Implement supporting infrastructure for migrating domain object models. Should make it straightforward to automatically upgrade domain object models of a given type from one version to the next.

Some points to consider:
- How to handle migrations that are not specific to a given type?
- Should this be accompanied by validation generally?
- Can this be handled outside of core?
- How decoupled can this be from object type?

**Comment by larkin** [comment]
Closing as wontfix so that we can track that we're not implementing it a this time.  May be something for future consideration.
