### ISSUE TITLE
[Telemetry] Legacy provider series not handling source mapping.

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1724]
The legacy telemetry provider is not correctly implementing source extraction in telemetry series.  As a result, views that utilize the legacy telemetry API fail to display data that uses source remaps.  For example, the plot view does not work with the tutorial objects due to remapping of the timestamp field.

**Comment by VWoeltjen** [comment]
__Note for testing:__ Solution from #1725 creates some temporary objects during requests, want to profile around this during testathon to see if this gets hot.

**Comment by larkin** [comment]
@VWoeltjen my hypotheses: one per request/subscription for the lifetime of the request data; probably not notable.
