### ISSUE TITLE
Telemetry Table not working

### ISSUE THREAD

**Issue by jpw-erigo** [nasa/openmct#1726]
Telemetry Table view does not appear to be working.

This was working earlier today - I installed updates earlier today after which this was still working; installed updates again after the merge of pull request #1725, after which Telemetry Table was not working.  Thus it appears that it was one of today's commits that changed this functionality.  Tested on Windows 10 and Mac platforms.

Best regards,

John

**Comment by larkin** [comment]
@jpw-erigo If you are seeing telemetry tables that show realtime data but don't show historical data then I suspect you're hitting #1722, which occurs when the timeSystem is unset.  

The master branch of the tutorial hasn't been updated, but there's an [update branch in progress](https://github.com/nasa/openmct-tutorial/pull/17) which resolves the issue.  Try making this change to your index.html file and let me know if it helps: https://github.com/nasa/openmct-tutorial/pull/17/commits/1d590d4860b6d733b70c8fb1d88de7045d0a59fd

If that doesn't resolve the issue, can you check the developer console for errors and post any that you see?

Best,

Pete

**Comment by jpw-erigo** [comment]
Thanks, Pete.  My apologies, this was operator error - working today.  BTW, I am using the main openmct repo (I migrated files over from the tutorial to the main repo probably a couple months ago).
