### ISSUE TITLE
create telemetry panel fails

### ISSUE THREAD

**Issue by klepsydra-robotics** [nasa/openmct#1728]
Hi,

we the latest code as of today, I get the following error when creating a telemetry panel:

angular.min.js:110 TypeError: Cannot read property 'forEach' of undefined
    at t (TelemetryMetadataManager.js:38)
    at new i (TelemetryMetadataManager.js:124)
    at o.getMetadata (TelemetryAPI.js:308)
    at e.hasNumericTelemetry (PlotViewPolicy.js:39)
    at e.allow (PlotViewPolicy.js:51)
    at e.allow (PolicyProvider.js:125)
    at t (PolicyViewDecorator.js:46)
    at Array.filter (<anonymous>)
    at e.getViews (PolicyViewDecorator.js:50)
    at e.invoke (ViewCapability.js:53)
(anonymous) @ angular.min.js:110
(anonymous) @ angular.min.js:83
$apply @ angular.min.js:136
(anonymous) @ angular.min.js:255
n @ angular.min.js:38

Thanks,

Pablo.

**Comment by VWoeltjen** [comment]
Thanks for the report; I'm hitting the same issue when I view existing Telemetry Panels, too. Using `git bisect` points back to b3cf7a5d932ffc3467ef1b2949c1e4491944ca72. In particular, want to investigate changes to TelemetryCapability there.

**Comment by VWoeltjen** [comment]
The particular exception is hit when `plot`'s policy tries to get telemetry metadata for a telemetry panel. This has no telemetry metadata.

It's poorly-defined what should happen when `openmct.telemetry.getMetadata(domainObject)` is called with a non-telemetry object. We should define this, and handle that circumstance from plot's policy.

**Comment by VWoeltjen** [comment]
PR #1732 fixes this. Didn't touch `openmct.telemetry` API; instead, handled this entirely in plot policy. Telemetry delegation will likely be obsoleted by future solutions for plots with multiple telemetry elements, so avoiding API changes is nice, even if it does leave unresolved questions about how the Telemetry API should handle cases like this.

**Comment by jtrimble2100** [comment]
Created a folder, then created a telemetry panel in it, works fine, no problems.

**Comment by akhenry** [comment]
Removing unverified label. Comment suggests that has been verified in the past, and panels are deprecated anyway.
