### ISSUE TITLE
Create Menu upgrade

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1729]
The Create Menu doesn't respond well to a large number of items in it and on lower resolution monitors.

**Comment by VWoeltjen** [comment]
Verified during testathon 2017-10-05, displays well on 1366x768, gets scroll bars appropriately

**Comment by jtrimble2100** [comment]
Create menu has no problems on Macbook Pro 13" but that's 2560x1600. What do you mean by low res?
