### ISSUE TITLE
[Timeline] Navigating while following Timer causes following to fail

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1741]
To reproduce:

1. Create a Timeline if you don't have one already. Make sure the Timeline is populated such that it starts at 00:00:00 and it's got some decent duration, more than 5 minutes or so.
1. Create a Timer if you don't have one already.
1. Create a new Display Layout and add both the Timer and the Timeline to it. Save the Layout and exit Edit mode.
1. In the Layout, restart the Timer so it begins again at 00:00:00. Click the Timer's context menu arrow, and select "Follow Timer" from the dropdown menu. Following should now be properly working; Pausing and restarting the Timer all effect following as expected.
1. Click in tree to navigate to any other object, including the Timer or Timeline itself. Navigate back to the Layout, then pause or restart the Timer: observe that following in the Timeline doesn't pause or reset, but keeps marching on. Similarly, changing the Timer's target by editing its properties, and note that following continues to not update. The indicator in the Status bar continues to indicate that the designated Timer is being followed.
1. Selecting Follow from the Timer will cause following to work properly again.

**Comment by larkin** [comment]
3/15/2018: Verified working, navigation and start stop worked properly.

Observed odd behavior with a brand new timer:
1. create layout
2. create timeline (as described above), add to layout.
3. create time, add to layout.
4. save layout.
5. press "follow timer".
6. Note that timeline zooms to very weird extents, and zoom in / out buttons don't work.  Pressing play on timer fixes this.  Once a timer has been started, this no longer occurs.

Also, noticed that there is no way to turn off timer following once enabled.  You can pause the timer, but cannot stop following it. Is this intended?

**Comment by akhenry** [comment]
@larkin Zoom issue sounds like a separate issue. It sounds like the original bug has been verified though?

**Comment by larkin** [comment]
Yes, original bug verified, needs new issue for broken zoom.
