### ISSUE TITLE
[Site] Broken links in the documentation page

### ISSUE THREAD

**Issue by BogdanAlexandru** [nasa/openmct#1751]
At: https://nasa.github.io/openmct/documentation/

![Imgur](https://i.imgur.com/a2NxreB.png)

Is the markdown file from which that page gets generated somewhere in the repo? I tried to search for strings found on that page but couldn't find anything.

**Comment by VWoeltjen** [comment]
Thanks for the report; this has been [fixed](https://nasa.github.io/openmct/documentation/) by https://github.com/nasa/openmct-website/commit/9cde6f9412d0f89a4cac48248a7b3cf3a0da036b
