### ISSUE TITLE
Show/Hide arrows for the object tree and the inspector are too small

### ISSUE THREAD

**Issue by jtrimble2100** [nasa/openmct#1758]
<img width="17" alt="create menu show hide" src="https://user-images.githubusercontent.com/2153309/31255337-404400e8-a9e1-11e7-80ad-8d11f1b92a8c.png">

The arrows to show/hide the create menu and the object tree, and the inspector are very small. The problem is both visibility and selection.

**Comment by akhenry** [comment]
Was raised again by @jtrimble2100 as an issue during demo 02/2018/2018
