### ISSUE TITLE
[Summary Widget] Confusing default name and rule label

### ISSUE THREAD

**Issue by psarram** [nasa/openmct#1760]
When creating a new summary widget, the default name and rule is set to "Unnamed Summary Widget". After renaming the object, the rule still says "Unnamed Summary Widget". Perhaps a better naming for the default rule would be less confusing.

**Comment by psarram** [comment]
<img width="1110" alt="screen shot 2017-10-05 at 3 57 17 pm" src="https://user-images.githubusercontent.com/26494733/31256220-fdff17c2-a9e5-11e7-82c2-a586bc218de6.png">

<img width="1099" alt="screen shot 2017-10-05 at 3 59 01 pm" src="https://user-images.githubusercontent.com/26494733/31256245-23e7536e-a9e6-11e7-981b-5812a72c86a6.png">

**Comment by charlesh88** [comment]
Definitely agree, good catch. "Unnamed Summary Widget" would be the default object name, while "Unnamed Rule" should be the default name for a rule.

**Comment by dtailor90** [comment]
Fixed in latest commit to summary-widgets

**Comment by dtailor90** [comment]
Fixed in commit e6beaf2. Closing issue
