### ISSUE TITLE
[Summary] Can enter HTML, scripts in label

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1761]
1. Create a Summary Widget
2. Drag one or two telemetry elements
3. Enter `Hello! <script>console.log("ruh roh");</script>` as the Label for the default rule.
4. Open the JavaScript console
5. __Observe:__ "ruh roh" is being written to the console about once every digest cycle

This also allows things like `Robot arm <b>ON</b>` which might have some utility, but script execution is definitely a bug. Other users who view the widget would have those injected scripts execute, so this is a vulnerability. Marking `blocker` accordingly.

**Comment by dtailor90** [comment]
Fixed in most current branch of summary-widgets
