### ISSUE TITLE
[Summary Widget] Duplicate and trash icons are too close to each other

### ISSUE THREAD

**Issue by psarram** [nasa/openmct#1762]
A bit more spacing between the two icons would make it easier to use.

<img width="1227" alt="screen shot 2017-10-05 at 4 26 24 pm" src="https://user-images.githubusercontent.com/26494733/31256971-92893662-a9ea-11e7-94f9-340fecafda7a.png">

**Comment by dtailor90** [comment]
Added margin and fixed in PR #1768
