### ISSUE TITLE
Hidden controls

### ISSUE THREAD

**Issue by jtrimble2100** [nasa/openmct#1763]
There are too many hidden controls. It's a mission, not a treasure hunt. I understand the need to reduce interface clutter but we need to discuss how to make the controls visible.

**Comment by jtrimble2100** [comment]
![screen shot 2017-10-05 at 4 56 33 pm](https://user-images.githubusercontent.com/2153309/31257580-288a8c08-a9ee-11e7-911b-aeb520920c54.png)

See the attached example from the timeline.

**Comment by larkin** [comment]
This was raised by JPL users and developers as well. The hidden-until-mouseover control scheme makes it hard to discover functionality. 

@charlesh88: our users disagree with our current approach and it’s hurting adoption. Let’s always show controls, and look for other strategies to deal with control clutter.
