### ISSUE TITLE
[Notebook] Notebook todos

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1772]
#### Address Jay comments of 10-10-17:
- [x] The delete icon is too prominent. I look at the notebook and it’s trash can icons all the way down… too much visually.  @charlesh88: the intent here is to only display that icon on hover over an entry. It's implied in the design, but I didn't explicitly state that as a requirement. It's an extremely easy change to make once we have the source code.
- [x] Don't show seconds in entry timestamps in the Notebook list.
- [x] Notebook name change not being reflected in the Inspector. @charlesh88: believe that #1276 will address this.
- [x] Test Notebook in a sim-like scenario.

**Comment by dtailor90** [comment]
All above issues seem to be fixed. The only one left is to test in sim like scenario. Closing as unverified.

**Comment by dtailor90** [comment]
Testing Notes:
1. Create Notebook
2. Add Entries
3. Take snapshots, annotate and add to entry. 
4. General usability of Notebook.
