### ISSUE TITLE
Support for numberfield min/max/step in composite controls

### ISSUE THREAD

**Issue by calvinhuang** [nasa/openmct#1785]
Numberfield controls don't appear to support min/max/step when they're part of a composite control.

I.e. for the following form structure, the "Path Tolerance" numeric input will have min/max/step set correctly, but the "Tolerance" input will not have min/max/step specified:
```bash
form: [
    {
        key: 'pathTolerance',
        name: 'Path Tolerance',
        control: 'numberfield',
        min: 0,
        max: 1,
        step: 0.0001
    },
    {
        key: 'simplify'
        name: 'Simplify',
        control: 'composite',
        items: [
            {
                name: 'Enable',
                control: 'checkbox'
            },
            {
                name: 'Tolerance',
                control: 'numberfield',
                min: 0,
                max: 1,
                step: 0.0001
            }
        ]
    }
]
```

**Comment by larkin** [comment]
@calvinhuang thanks for the report and code to reproduce, have a fix inbound.

Note, if you add `cssClass: 'l-inline'` to each item in the composite it will turn it into an inline input, e.g.

![screen shot 2017-10-20 at 5 21 49 pm](https://user-images.githubusercontent.com/226503/31846031-2ee95b78-b5bb-11e7-8046-30f2ffe343c5.png)
