### ISSUE TITLE
[NSS Heatmap / Demo] Heatmap showing erroneous position plots

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1789]
Using @Costigan's latest playback data, when the heatmap starts up, it always seems to draw a straight line immediately from a default (?) position to a place where it starts getting data:
<img width="497" alt="screen shot 2017-10-25 at 2 10 47 pm" src="https://user-images.githubusercontent.com/1056412/32023626-ad2a6ca8-b98e-11e7-9883-0561b463223e.png">

After a while of running, it will then jump position as well:
<img width="701" alt="screen shot 2017-10-25 at 2 09 45 pm" src="https://user-images.githubusercontent.com/1056412/32023645-bc8b18b4-b98e-11e7-98d3-247cca6b5331.png">

Here's my config parameters:
<img width="523" alt="screen shot 2017-10-25 at 2 10 03 pm" src="https://user-images.githubusercontent.com/1056412/32023658-c94801d4-b98e-11e7-9925-888ec5653290.png">

@VWoeltjen Could you have a look? If this is an easy fix it'd be great to hit it, but not a big deal if not.

**Comment by VWoeltjen** [comment]
Fixed! Since this is still a demo component, closing without verification
