### ISSUE TITLE
[Imagery] - Imagery does not forward to latest picture on un-pause

### ISSUE THREAD

**Issue by dtailor90** [nasa/openmct#1799]
When viewing historical imagery, once user un-pause's from an older image, it does not forward to the latest image. It does however forward once a new image comes in.

**Comment by dtailor90** [comment]
Fixed in commit 71c54cd. Closing Issue

**Comment by dtailor90** [comment]
Testing Notes:

1. Expand Imagery to view historical data. 
2. Click on older image to pause the imagery.
3. Unpause the imagery - Check wether it forwards to the latest image.

**Comment by VWoeltjen** [comment]
Verified during testathon 12/05/2017
