### ISSUE TITLE
Display layout rendered upside down in Safari

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1805]
User reported that when they edited a display layout it would fairly consistently be rendered upside down. Issue occurred on 2016 Macbook Pro using Safari Version 11.0.1 (12604.3.5.1.1), and they were unable to reproduce it in other browsers. Some details below from the user:

* Note, I could only get it to occur when I was dragging 'unnamed telemetry panel' that I had added, dragging other objects, i.e. camera data from rover didn't reproduce. I didn't take the time to test thoroughly, but also seemed like it occurs more when the telemetry panel being dragged was beneath other layers of items. Screenshots attached!
* I only saw it in the layout editor.
* I had been messing with the layout, dragging objects around, and then I opened a safari extension (overlay window from the toolbar), I noticed the issue after I closed the safari extension. (note that in the reproduced bugs, I didn't open the extension window)
* I haven't seen this behavior specifically, but I have experienced other graphics card issues, mainly an issue where windows will appear as all red until I click on them and focus.
* It was a new empty panel. I played with a few WebGL experiments on the google site and couldn't reproduce but I didn't do a very exhaustive search.

At this time we believe it to be a driver or hardware issue. 

<img width="1679" alt="upside down" src="https://user-images.githubusercontent.com/4215777/32636026-cdc56d2a-c567-11e7-8868-8b7bb93597d4.png">

**Comment by VWoeltjen** [comment]
It looks like the whole window is getting rendered upside down as the background of the editable area of the layout.

It could also be a browser bug. We've sometimes seen compositor bugs or performance issues get tickled by certain styling (animation and opacity, for instance), and those can be worked around. Unless we reproduce this elsewhere, though, I agree that driver/hardware issues are more likely.

**Comment by akhenry** [comment]
@VWoeltjen Agreed. I was thinking along similar lines. It might possibly be WebGL doing the tickling since it only seemed to happen with the panel in the layout? If someone actually manages to reproduce it, or another user reports it, we can do some further investigation at that point.
