### ISSUE TITLE
[Demo] Update online demo with latest features

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1806]
Features have been added recently, or will be added in the near future that will be picked up simply by kicking off a new build of the demo repository.
eg.
* Historical imagery
* New plots
* Summary Widgets

We should update the layouts to incorporate things like Summary Widgets, and just to make them a little more interesting generally.

**Comment by larkin** [comment]
@akhenry does this need to be an issue?  This could be tracked elsewhere.  The demo is currently hardcoded to a openmct version identifier, all you have to do is update & push.

**Comment by akhenry** [comment]
> "We should update the layouts to incorporate things like Summary Widgets, and just to make them a little more interesting generally."
