### ISSUE TITLE
[Tables] Error in tables - "could not read property 'length' of null"

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1817]
This has been reported in VISTA, and in the [YAMCS-Open MCT](https://github.com/nasa/openmct/issues/1701#issuecomment-329891778) plugin.

This requires investigation and reproduction. The fact that it's a `null` value is odd, and probably a fairly good clue as to what's going on. There are a very limited number of ways that a null value could get into a table row. The telemetry data is either null to begin with, or [a telemetry formatter is returning null values](https://github.com/nasa/openmct/blob/5a49ac16b1346cbf17e88b462e538caf4f4f1947/platform/features/table/src/TableConfiguration.js#L68). 

Stack trace below is taken from the YAMCS-Open MCT plugin. See [original issue](https://github.com/nasa/openmct/issues/1701#issuecomment-329891778) for more info.

![image](https://user-images.githubusercontent.com/4215777/33226295-2744ec3a-d13f-11e7-8311-fded51cc9736.png)

**Comment by ev1stensberg** [comment]
@akhenry Good way to fix the bug might be to list all scenarios where the table format might fail, and see if there's some inconsistency somewhere?

**Comment by VWoeltjen** [comment]
For reference, [this block](https://github.com/nasa/openmct/blob/01d93306f3c44e65f245072941ae1c0c1b6c7a28/platform/features/table/src/controllers/MCTTableController.js#L614-L629) is where the error gets hit. Adding/fixing guard code around `currentColumn` and `largestColumn` would address this, but it would be nice to understand where this null value is coming from in the first place.

**Comment by ev1stensberg** [comment]
Can I investigate?

**Comment by akhenry** [comment]
@ev1stensberg Please do! As @VWoeltjen mentions, it would be better to address the root cause first, and then consider workarounds. Your best bet is to investigate it in the context of the YAMCS plugin where it's been observed. It's not been observed with test data sources such as the Sinewave Generator.

The problem here is that the .text property is null under some circumstances. This means that either the telemetry data itself is null, and is passing through telemetry formatter untouched, or the telemetry data is not null, but [the formatter is producing null values]((https://github.com/nasa/openmct/blob/5a49ac16b1346cbf17e88b462e538caf4f4f1947/platform/features/table/src/TableConfiguration.js#L68)) in some circumstances. I would 
start by reproducing the error in the YAMCS plugin (ala https://github.com/nasa/openmct/issues/1701#issuecomment-329891778). With the error reproduced, do some debugging and check whether it's the telemetry value that's null (more likely) or whether the formatter is producing nulls for non-null inputs (less likely, but possible -
 [moment.js has a history of returning nulls for things it doesn't like](https://github.com/moment/moment/issues/716)).

**Comment by ev1stensberg** [comment]
Aight, got some assignments to do next week, starting next weekend or week after that

**Comment by akhenry** [comment]
In the case of YAMCS it looks like this is being caused by null input values from the telemetry source. 

The right fix in that case is to add guard code, [as originally suggested]() (This assumes that it is contractually correct for a formatter's `.format()` function to produce null values - which on balance I think it is). 

@larkin @VWoeltjen This error is occurring in VISTA as well. It is caused by either a telemetry source providing null values (correctly or incorrectly), or a telemetry formatter erroneously returning nulls from a call to `.format()`. Without having access to VISTA's telemetry formatters I can't verify whether the latter is possible under any circumstances. We will need to reproduce this in VISTA and take a look at the incoming telemetry values to see whether nulls are being provided.
