### ISSUE TITLE
Sub-object selection in Display Layouts

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1820]
Extending this to an issue so @psarram can add testing notes for the upcoming Testathon.

**Comment by psarram** [comment]
Testing Notes:

1. Create some new objects like Timer, Button, Link and Fixed Position.
2. Create a new Layout and rename it to Layout.Inner.Inner. Drag in two or more objects (like Timer and Link). As you drop a new object observe that it gets selected and that the inspector and toolbar update. Try clicking on the show/hide frame button in the toolbar and notice the changes to the frame. Deselect all objects and observe that the Elements pool in the inspector lists all the objects. Save and Finish Editing. 
3. Create a new Layout and rename it to Layout.Inner. Drag in the Layout.Inner.Inner, Fixed Position and another object like a Timer. As you drop a new object observe that it gets selected and that the inspector and toolbar update. Save and Finish Editing.
4. Create a Sine Wave Generator (SWG) object. 
5. Create a Telemetry Table object and drag in the SWG you created.
6. Create a new Layout and rename it to Layout.Table. Drag in the Telemetry Table you created. As you drop the object observe that it gets selected and that the inspector and toolbar update. In the inspector, the Elements pool should list the SWG and the Table Options should list the columns which you can edit. Save and Finish Editing.
7. Create a new Layout and rename it to Layout.Outer. Drag in the Layout.Inner and Layout.Table. As you drop an object observe that it gets selected and that the inspector and toolbar update. To select sub-objects inside Layout.Inner and Layout.Table, double click on them. This puts you in the drill-in mode which allows you to select sub-objects. Double click the Layout.Inner.Inner to select its sub-objects. Try moving and resizing objects. Try clicking the hide/show frame button in the toolbar to see the changes to the frame for different objects. Deleting a sub-object should select the parent object and update the toolbar with the right button.

**Comment by VWoeltjen** [comment]
Verified during testathon 12/05/2017.
