### ISSUE TITLE
[API] Implement InspectorViewRegistry 

### ISSUE THREAD

**Issue by psarram** [nasa/openmct#1825]
Implement a registry for views which should appear in the Inspector area based on the selection state.

**Comment by psarram** [comment]
Testing Notes:

1- Add the following code to index.html to define a view.
2- Create a Layout and observe the 'Congratulation...' message to appear in the inspector right below the Location area.

```
openmct.inspectorViews.addProvider({
    key: "my-key",
    name: 'my view',
    canView: function (selection) {
        return selection[0].context.item.type === 'layout';
    },
    view: function (selection) {
        return {
            show: function (container) {
                container.innerHTML = '<div> Congratulations, this is an inspector view of: ' + selection[0].context.item.name + '</div>';
            },
            destroy: function (container) {

            }
        }
    }
});
```

**Comment by VWoeltjen** [comment]
Verified during testathon, 12/05/2017. (Ran the code snippet above from Chrome console after a `var openmct = require('openmct');`, saw the message appear in Inspector after selecting a Layout)
