### ISSUE TITLE
[New Plots] CH Testathon 12-05-17 Results: New Plots

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1828]
Per Pete direction, using Fixed Timespan. Also using telem from playback.
@charles88 Intend to file separate issues from this or add to those others create.

#### Problems
- Create new plot, add telem via drag into plot area. Nothing in elem pool but elems showing in Inspector "Series Options" and data is plotted. Added 3 things. Nothing. Expanded legend, items appear in pool. 
- Marquee zoom not working in edit mode; instead get pan gesture. Browse mode Ok. Tried to replicate and could not.
- Wait spinner is going away too quickly: plot appears to be ready, trying to marquee zoom shows no marquee area, but then zooms anyway.
- Adding CH Overlay Plot 2 to a new Layout gave me a browser Kill warning, that went away (?!).
- Selecting Expand Legend by default on a selected plot while editing a layout didn't expand the legend, but should of.
- Line color palette is not displaying.
#### Ok
- Legend position manipulations looking good.
- Line interpolation changes are working as expected.

**Comment by larkin** [comment]
All resolved in #1557, closing.
