### ISSUE TITLE
Info Bubbles appear then disappear immediately

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1830]
eg.
![tooltip](https://user-images.githubusercontent.com/4215777/33639045-50f03092-d9de-11e7-940b-9553850570c4.gif)

Steps to reproduce:
1. Hover over any object in the tree on testathon build.
2. Observe info bubble appearing briefly before disappearing.

**Comment by dtailor90** [comment]
Fixed in PR #1868

**Comment by VWoeltjen** [comment]
@larkin - This is reproducible in VISTA R3.4 RC1, which is a few commits behind this particular change. Don't believe this blocks any requirements; treat as a known issue?

**Comment by VWoeltjen** [comment]
Verified fixed in testathon 20180221

**Comment by psarram** [comment]
Verified fixed in testathon 02/21/2018

**Comment by charlesh88** [comment]
Testathon 2/21/2018: Verified fixed
