### ISSUE TITLE
How to change repo location for js file in npm/bower install?

### ISSUE THREAD

**Issue by hcaulfield** [nasa/openmct#1835]
Im building the openmct project on Windows 10. Its failing at one of the later steps. 

It fails at the publish prescript step. 

The npm install is looking for a Filesaver.js at https://github.com/carlos-algms.

But its no longer in that repo. 

I think it derives from  https://github.com/eligrey/FileSaver.js. 

How do I change the npm/bower build to point to the correct repo.

i.e where is npm/bower picking up the carlos-algms repo definition.

Thanks for your help.

**Comment by VWoeltjen** [comment]
Hello! I believe this issue was addressed by #1808 and #1822. If you pull the latest from the `master` branch this should be resolved. I'll close this issue, but please reopen if you are still having problems with the build. Thanks!
