### ISSUE TITLE
[Clocks] The follow status indicator incorrectly shows follow status.

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1836]
(You had one job to do, follow indicator...)

It also prints a bunch of error messages to the console. It looks like the 'timer' object has changed since it was first implemented.

Steps to reproduce
1. Follow a clock
2. Observe that the follow indicator goes green, correctly. But if you hover over it, the text says "NO TIMER BEING FOLLOWED".

Opening the console reveals that the console is full of errors like -
```
angular.js:12416 TypeError: timer.getModel is not a function
    at FollowIndicator.getText (FollowIndicator.js:48)
    at fn0 (eval at compile (angular.js:13231), <anonymous>:4:559)
    at Object.get (angular.js:14191)
    at n.$digest (angular.js:15745)
    at n.$apply (angular.js:16024)
    at angular.js:17791
    at e (angular.js:5490)
    at angular.js:5762
```

**Comment by dtailor90** [comment]
Seems like getModel does not exist on timer. Calling timer.name works

**Comment by akhenry** [comment]
Note to testers: Verify that the label on the follow indicator correctly shows status, and that there are no errors in the console relating to timers.

**Comment by charlesh88** [comment]
Testathon 2/21/2018: Verified fixed.
Label is correct in both states; no console errors.
