### ISSUE TITLE
Clicking tree item silently navs away from newly created object

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1838]
Observed during hands-on training 12/12/17. Users new to the application would create a new Layout or FP object, mistakenly single-click a thing in the tree, and then wonder what happened to the thing they just created. This was very confusing and people were not figuring it out on their own.

1. Create a new Layout, Fixed Position or other object that has an Edit mode. Don't add anything to it.
1. Click an item in the tree, rather than drag it.
1. Observe: you are navigated to the tree object silently.

Even if the user hasn't added anything to their newly created object, we should display the blocking confirmation dialog.

**Comment by larkin** [comment]
Short term, we should display the blocking dialog.  This is a trivial change to the edit object controller to remove the dirty check here: https://github.com/nasa/openmct/blob/1ad5094b7229e4246d8a0666dff63e7141fdf395/platform/commonUI/edit/src/controllers/EditObjectController.js#L62

**Comment by dtailor90** [comment]
Fixed in PR #1864

**Comment by dtailor90** [comment]
Testathon 2/21/18: Verified fixed (although this may be a short term solution)

**Comment by charlesh88** [comment]
Testathon 2/21/2018: Verified fixed.
