### ISSUE TITLE
Add requirejs/text plugin for more build flexibility.

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#184]
Adding the [requirejs/text](https://github.com/requirejs/text) plugin will allow developers to require text files (html, css, json, etc) files in their bundles and use them however they would like.  

Some use cases:
* Can require html template files for directives (and respect relative urls) instead of inlining templates or using absolute paths for directives.
* an implementation file can require the bundle file and read constants (such as domain object types) instead of hardcoding them in the implementation.

**Comment by VWoeltjen** [comment]
Addressed by #642
