### ISSUE TITLE
[Selection] Activity toolbar in Timeline appears only for a brief second

### ISSUE THREAD

**Issue by dtailor90** [nasa/openmct#1842]
When editing a timeline, clicking on the activity should bring up the settings toolbar for the acitivity. It appears for a brief second and then disappears. Seems to me that there is a secondary click event occurring after the first click that causes the toolbar to disappear.

**Comment by akhenry** [comment]
@psarram I have closed this in light of [the associated PR](https://github.com/nasa/openmct/pull/1849) being merged. Please let me know if this is incorrect.

**Comment by charlesh88** [comment]
Testathon 2/21/2018: Verified fixed.
