### ISSUE TITLE
Clock still ticks when in fixed timespan mode

### ISSUE THREAD

**Issue by losnake** [nasa/openmct#1844]
Hi, 
I have just started using OPENMCT to visualize some time series data.
Thank you for share such an interesting project to the world!

I am now having a small problem on Time API. (I am on the master branch)
I found that when we switch from local clock to fixed timespan mode, the time line(x-axis) still ticks. 
It unsubscribes the data source and then subscribe it again, which means the real time data is still feeding into the trend line.

Is there a possible way to prevent it from doing this?

It can be reproduced on the heroku demo app.
![de5b00119b1147d3887d23297e4d4166](https://user-images.githubusercontent.com/3121302/34199553-1c8dded6-e5a9-11e7-9373-1193b925084b.gif)

Thank you.

**Comment by larkin** [comment]
The new plots which recently got merged into master fix this issue. Let us know if you continue to experience it.
