### ISSUE TITLE
[Fixed Position] Use the Selection API 

### ISSUE THREAD

**Issue by psarram** [nasa/openmct#1848]
Modify the fixed position to use the Selection API to select elements and update the toolbar.

**Comment by charlesh88** [comment]
@psarram Need some testing notes here please.

**Comment by psarram** [comment]
@charles88 Fixed position has been modified to use the new Selection API. Please verify all the functionality work as expected (i.e, you can add elements, select elements, update their properties via toolbar and drag and drop).

**Comment by dtailor90** [comment]
Verified - 03/15/2018
