### ISSUE TITLE
[Search] Can't create while Search item is selected

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1853]
Steps to reproduce:

1. Enter text in the search area that provides results
2. Navigate to one of those results, leave search area as-is
3. Click Create, choose a type
4. **Observe**: No Create dialog or editable object appears; searched object remains navigated.

Need to check with @charlesh88 what the desired behavior would be here; IIRC the Create button should disappear while searching, in which case the bug is that the Create menu is available after step 1.

**Comment by VWoeltjen** [comment]
Can't reproduce on master (Create menu is available but behaves sensibly); may only occur when the selected object is in another namespace

**Comment by VWoeltjen** [comment]
Also can't reproduce with MSL or style guide plugins, so probably not a namespace issue

**Comment by larkin** [comment]
I believe Open MCT is attempting to add the object to the composition of the selected item and failing; there might be a missing policy.

**Comment by charlesh88** [comment]
Cannot duplicate or has fixed itself as a result of other changes. Closing.

**Comment by larkin** [comment]
2018-07-02: Verified fixed.
