### ISSUE TITLE
[Plot] Color picker not showing

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1854]
Steps to reproduce:

1. Create an Overlay Plot
2. Add a telemetry object to it
3. In Edit mode, under Series Options, expand the telemetry object
4. Click on the picker next to Color
5. __Observe:__ No color picker appears, although a small change in padding indicates the click has been registered

**Comment by VWoeltjen** [comment]
Previously referenced [here](https://github.com/nasa/openmct/pull/1557#issuecomment-349476677); this is an issue with new plots, which are still not on master here.

**Comment by VWoeltjen** [comment]
This is also not currently reproducible on #1557, so appears to have been addressed there. VISTA may just need that update?

**Comment by larkin** [comment]
VISTA just needs a rebuild with this change.  Will do.

**Comment by larkin** [comment]
Verified resolved in VISTA build.
