### ISSUE TITLE
[Plot] Chart area disappears when Legend Position is Hidden

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1856]
Steps to reproduce:

1. Create an Overlay Plot
2. Add some telemetry
3. Edit the overlay plot
4. In the Inspector, under Legend, set Position to hidden

Observe that the legend is hidden, but that the plot itself collapses vertically:

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/1685764/34365926-681bec44-ea4a-11e7-833a-1648430c4658.png">

**Comment by VWoeltjen** [comment]
Note: Reproducible on branch from #1557, but not master

**Comment by charlesh88** [comment]
@larkin @VWoeltjen Just pushed up a one line fix for this to branch pete-plot-import.

**Comment by larkin** [comment]
Verified fixed.

**Comment by psarram** [comment]
Verified fixed in Testathon 02/21/2018/

**Comment by charlesh88** [comment]
Testathon 2/21/2018: Verified fixed
