### ISSUE TITLE
[Summary Widgets] Add "is not undefined" comparison to Summary Widgets

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1860]
We have "is undefined" and should also have "is not undefined". Should be applicable to all field types.

**Comment by dtailor90** [comment]
Fixed in PR #1863

**Comment by charlesh88** [comment]
Testathon 2/21/2018: Verified fixed.

**Comment by psarram** [comment]
Testathon 2/21/2018: Verified fixed.
