### ISSUE TITLE
Form spacing is off again

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1862]
Seen here: 

![form spacing off](https://user-images.githubusercontent.com/226503/34574049-4ce96036-f144-11e7-8d00-ac1bd8ea979a.png)

Need to double-check Open and see if it's there as well.

**Comment by ev1stensberg** [comment]
How could I reproduce this @charlesh88 ?

**Comment by charlesh88** [comment]
Fixed with changes effected in #2000. 

### Testing Notes

1. Use the Create menu to create a type of object that first starts with the Properties dialog, like a Sine Wave Generator or Timer. 
1. Observe the form in the dialog: the amount of space under the input fields should be the same above and below each field, like this:
![screen shot 2018-07-02 at 12 59 49 pm](https://user-images.githubusercontent.com/1056412/42183796-fe71ba3e-7df7-11e8-819d-701085c7c1c6.png)

**Comment by larkin** [comment]
2018-07-02: Verified, though we should test this in the next VISTA build and verify that the dataset displays properly.
