### ISSUE TITLE
[Sub-object Selection] Must click twice to select outer context in Display Layout

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1866]
When editing a Layout, you must click twice to deselect selected objects and select the outermost parent object. This is only an issue when all placed objects don't have children. To reproduce:

1. Create a new Layout.
1. Add one or more objects that don't have any children, like telemetry elements. The last one will be selected by default.
1. Click once on an empty area of the Layout to deselect the element. The object will deselect, but the Inspector won't display info for the Layout you're working within and its object(s) in the Elements pool.
1. Click again on an empty area of the Layout. Now, the Inspector will display info for the Layout you're working within and its object(s) in the Elements pool.
1. If you add any object that has its own children (stacked/overlay Plot, another Layout) a single click will work as desired, deselecting the selected element and "selecting" the Layout you're working in.

**Comment by psarram** [comment]
@charlesh88 I can't reproduce this issue following the steps. A single click works as expected for objects that don't have any children.
