### ISSUE TITLE
[Inspector] Elements pool doesn't get updated after removing an object

### ISSUE THREAD

**Issue by psarram** [nasa/openmct#1869]
In Layout, try removing an object via the context menu by right clicking the object in the elements pool. Notice the object remains listed in the elements pool.

**Comment by VWoeltjen** [comment]
Verified fixed in testathon 20180221. The Elements pool does become empty when the context menu is opened, but that is a consequence of the selection changing; I believe this is correct behavior. After the Remove operation the removed object is gone as expected.

**Comment by charlesh88** [comment]
Testathon 02/21/2018: Verified fixed.

**Comment by charlesh88** [comment]
@VWoeltjen What do you mean "The Elements pool does become empty when the context menu is opened..."?

**Comment by VWoeltjen** [comment]
* I click on Button A in Layout B's little drop-down arrow
* Visually, three things change simultaneously:
  * Button A takes on a selection highlight
  * A context menu appears
  * The Inspection area updates to reflect Button A (which has no composition, so the Elements pool is empty)
* I click remove, Button A disappears, nothing is selected, Inspection area reflects Layout B and Elements pool reflects current content of Layout B (so Button A is no longer there)
