### ISSUE TITLE
[Create] Type descriptions should better explain purpose

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#187]
This is the open version of github.jpl#85 https://github.jpl.nasa.gov/MissionControl/vista/issues/85. 

Type definitions (as visible in the Create menu) should better explain what they allow the user to do.

**Comment by larkin** [comment]
@charlesh88 is this branch (or #188) ready to merge to open-master?

**Comment by charlesh88** [comment]
Should update https://github.com/nasa/openmctweb/compare/open187 with latest open master, and then issue a pull request for this.

**Comment by VWoeltjen** [comment]
Testathon 20160509: Type descriptions look good to me. Telemetry Panel has a brief summary but we are planning to remove this in favor of Display Layout.

@charlesh88 - do current descriptions look good to you? Would like to remove "unverified" label from this issue.

**Comment by charlesh88** [comment]
Testathon 20160512
Verified fixed.
