### ISSUE TITLE
[Date picker, Windows] Time Conductor Date Picker menu is missing background

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1872]
Or is z-indexed under other stuff. Seen while meeting with Peter Pasquale about Asteria. May be due to missing CSS files?

**Comment by akhenry** [comment]
For open source contributors, the Time Conductor is a plugin that adds a UI element to the bottom of the screen that allows manipulation of time parameters. It's not installed by default, but can be installed by adding the following to `index.html`:

```js
openmct.install(openmct.plugins.Conductor({
    menuOptions: [
        {
            name: "Fixed",
            timeSystem: 'utc',
            bounds: {
                start: Date.now() - 30 * 60 * 1000,
                end: Date.now()
            }
        },
        {
            name: "Realtime",
            timeSystem: 'utc',
            clock: 'local',
            clockOffsets: {
                start: -30 * 60 * 1000,
                end: 5 * 60 * 1000
            }
        }
    ]
}));
```
Add it after the lines -
```js
openmct.time.clock('local', {start: -15 * 60 * 1000, end: 0});
openmct.time.timeSystem('utc');
```
The issue described by @charlesh88 is demonstrated (along with the location of the time conductor) in this screen cap -

**Comment by lopezdp** [comment]
Im guessing this one is still open? im getting my environment set up and was thinking about starting here to help. Let me know. Either way, I work slow so Ill pick another if this one is already taken.

**Comment by charlesh88** [comment]
I've got this one, but thanks!

**Comment by charlesh88** [comment]
Need refactor SCSS to use .s-menu class, instead of baking everything into .menu. Remove .s-datetime-picker class, although maybe keep it and extend .s-menu.

**Comment by dtailor90** [comment]
Verified date picker has back background. 03/15/2018

**Comment by VWoeltjen** [comment]
Verified during testathon 03/15/2018

**Comment by larkin** [comment]
Verified. 3/15/2018
