### ISSUE TITLE
[Plot] No scroll bar in stacked plot

### ISSUE THREAD

**Issue by vicfx** [nasa/openmct#1878]
Steps to reproduce (requires new plots from #1557):

1. Create Stacked Plot
2. Drag and drop in 15 (or so) telemetry elements. The number needed may vary depending on available vertical resolution.
3. __Observe__: Plots continue down past the bottom of the viewing area, but no scroll bar is available with which to see them.

Expected behavior would be to get a scroll bar leading down to the remaining plots

**Comment by larkin** [comment]
@charlesh88 can you take a look at this? getting user reports that this is a problem.

**Comment by charlesh88** [comment]
Will do.

**Comment by larkin** [comment]
2018-07-02: Verified fixed.

**Comment by dmilewicz** [comment]
Verified fixed
