### ISSUE TITLE
[Table] Various error messages in tables

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1884]
The table component can sometimes produce various errors when the view changes (eg. on save, on navigation away etc.). Some examples include -

```
TypeError: Cannot read property 'getRowValues' of null
    at d (TelemetryTableController.js:313)
    at f (TelemetryTableController.js:329)
    at <anonymous>

TelemetryTableController.js:442 TypeError: Cannot set property 'headers' of null
    at o.loadColumns (TelemetryTableController.js:244)
    at n (lodash.js:3095)
    at <anonymous>
```

I believe that these are due to asynchronous processes that are not cancelled on page unload. They are sometimes being triggered after page unload, so the the scope, controller, instance variables etc have been cleaned up. Because it's racy the exact error messages sometimes differ.

I believe that these error messages are benign, but they shouldn't be stinking up the console. Any asynchronous processes should be cancelled on page destruction (ideal), or guard code added to prevent these error message (not so ideal).

**Comment by psarram** [comment]
I also noticed this error after creating a table

```
Uncaught (in promise) TypeError: Cannot read property 'autoScroll' of undefined
    at MCTTableController.<anonymous> (MCTTableController.js:219)
    at <anonymous>
```
 and this error after adding a Sine Wave Generator to the table and saving it.

```
MCTTableController.js:408 Uncaught (in promise) TypeError: Cannot read property 'displayRows' of undefined
    at MCTTableController.setElementSizes (MCTTableController.js:408)
    at wrapper (lodash.js:3095)
    at <anonymous>
```

**Comment by dtailor90** [comment]
Verified Fixed - 07/02/18
