### ISSUE TITLE
[Style Guide] Add documentation for classes for Status Indicators

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1894]

**Comment by charlesh88** [comment]
Ended up doing somewhat significant cleanups and refactoring of indicator-centric styles, markup and config. Still todo: actually do the examples in the Style Guide.

@akhenry: I ended up changing the markup for indicators, it's much simpler now. Is there documentation anywhere that should also be updated?

**Comment by akhenry** [comment]
@charlesh88 There is a PR for the indicators API which contains documentation - https://github.com/nasa/openmct/blob/b35be0c559534f464c8d12c3753982c67dc81eab/API.md#indicators . The PR is https://github.com/nasa/openmct/pull/1837

**Comment by charlesh88** [comment]
@akhenry Pushed my latest to style-guide-1894-2. All yours!

**Comment by charlesh88** [comment]
With the merging of work done in #1837 and #2076 this issue is closed.
