### ISSUE TITLE
[Timers] Timers aren't visually indicating countdown or countup

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1895]
Timers should display + or - depending on whether they are counting up or down. This is a regression error, they used to do this.

**Comment by akhenry** [comment]
@charlesh88 ok if @PunkChameleon takes a look at this?

**Comment by PunkChameleon** [comment]
@charlesh88 @akhenry 

Just to be clear on the ask, is it to add a plus or minus to the timer on screen here:
<img width="820" alt="screen shot 2018-05-08 at 6 35 17 pm" src="https://user-images.githubusercontent.com/1300125/39786440-9d729bb0-52ee-11e8-9b4b-286b3f6e77bc.png">

Or here, on the bottom toolbar?
<img width="846" alt="screen shot 2018-05-08 at 6 35 27 pm" src="https://user-images.githubusercontent.com/1300125/39786439-9d66f24c-52ee-11e8-974d-d256d178d37d.png">

**Comment by akhenry** [comment]
@PunkChameleon The first one - ie. timer objects. A timer is associated with a target date, and if that date is in the future the timer should show a '-' in front of it. If it's in the past, it should show a '+'.

It used to do this, so this is a bug rather than a new feature request.

**Comment by charlesh88** [comment]
@PunkChameleon Ok, a bit more info: the HTML that surrounds the value is supposed to have an additional class in it: either `icon-plus` or `icon-minus` for countup and countdown timers respectively. Here's the rendered HTML as of now:

<img width="889" alt="screen shot 2018-05-09 at 12 13 12 pm" src="https://user-images.githubusercontent.com/1056412/39834657-8baad4b2-5382-11e8-990f-8a74361f0d3c.png">

And here's how it should be:

<img width="791" alt="screen shot 2018-05-09 at 12 11 18 pm" src="https://user-images.githubusercontent.com/1056412/39834562-3d988cc4-5382-11e8-8e8e-82b0502cc818.png">

And the resulting display:

<img width="127" alt="screen shot 2018-05-09 at 12 11 13 pm" src="https://user-images.githubusercontent.com/1056412/39834697-9d89e2a4-5382-11e8-814b-81b85f5eba5e.png">

So, something in the code is failing to add those `icon-*` classes. Like I said: bug hunt.

**Comment by PunkChameleon** [comment]
@charlesh88 @akhenry -- thank you for the lead on here -- was really helpful in spotting the issue. PR submitted!

**Comment by PunkChameleon** [comment]
@dawsbot -- good point; will make sure to do next time. This can be closed though as it's been merged.

**Comment by charlesh88** [comment]
### Testing Notes

1. Create a new Timer, enter a Target Time that is in the future. Save, and observe: the saved Timer should be counting down, and should display a "-" sign.
1. Mouse over the timer, and click its Stop button. Then click its Start ( > ) button. Now observe: the Timer should display a "+" sign as it counts up.

**Comment by larkin** [comment]
2018-07-02: Verified fixed.

**Comment by dmilewicz** [comment]
Verified fixed
