### ISSUE TITLE
[Notebook] Snapshot backgrounds are being set to white

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1902]
Relates to #1896, #1897 
Backgrounds of elements being captured as a snapshot for a Notebook entry are having their backgrounds turned to white. Per @dtailor90, this is due to new functionality introduced to make PNG and JPG exports of plots more print-friendly. Notebook implements our export capability, but allows captures of *all* object types, so all Snapshots are manifesting this issue. 

**For a Notebook Snapshot, all backgrounds should not be altered**, including Plots. 

Examples:
#### Plot object
![screen shot 2018-02-02 at 3 23 44 pm](https://user-images.githubusercontent.com/1056412/35759262-6d90d616-082d-11e8-9caf-baeae86aa287.png)

#### Fixed Position object
![screen shot 2018-02-02 at 3 14 07 pm](https://user-images.githubusercontent.com/1056412/35759275-83424c24-082d-11e8-8e78-2a8aa3603af7.png)

**Comment by dtailor90** [comment]
Fixed in PR #1905

**Comment by akhenry** [comment]
Note to testers: The fix for this is in the plot export functionality, so please verify that plot export still works as expected. 

1. In any plot, select "export to png" or "export to jpg". 
2. Verify that the background of the exported plot is set to white for printing.

**Comment by VWoeltjen** [comment]
Verified that notebook snapshots do not have a white background and that plot exports due have a white background during tesathon 03/15/2018

**Comment by larkin** [comment]
Verified in testathon 3/15/2018
