### ISSUE TITLE
[Notebook] Notebook Snapshot not capturing some DOM elements

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1903]
Relates to #1896, #1897 and #1902
Adding a snapshot to a Notebook entry doesn't capture some elements, which seem be canvas and background images. Note that the white background problem is captured as #1902.

#### Fixed Position object
Original:
![screen shot 2018-02-02 at 3 14 15 pm](https://user-images.githubusercontent.com/1056412/35759053-1f7ca12c-082c-11e8-9aa8-0ba7e4eb897e.png)
Snapshot: 
Images and lines are missing; boxes, text and telemetry are Ok
![screen shot 2018-02-02 at 3 14 07 pm](https://user-images.githubusercontent.com/1056412/35759057-257b087a-082c-11e8-9469-2fb6856ee288.png)
#### Image object
Original:
![screen shot 2018-02-02 at 3 17 54 pm](https://user-images.githubusercontent.com/1056412/35759360-fe4a6c58-082d-11e8-8165-2d369735aa02.png)
Snapshot:
Main image and thumbs are all missing.
![screen shot 2018-02-02 at 3 18 36 pm](https://user-images.githubusercontent.com/1056412/35759366-073b9a76-082e-11e8-959f-c00bf9309216.png)

**Comment by dtailor90** [comment]
Partially fixed, canvas elements are captured, but images are not because of CORS. Closing

**Comment by charlesh88** [comment]
Testathon 2018-05-01 - NOT fixed: scrolling tables are not being captured.

Original:
![screen shot 2018-05-01 at 3 15 09 pm](https://user-images.githubusercontent.com/1056412/39496243-77de2b18-4d52-11e8-898f-882e542499a3.png)

From snapshot:
![screen shot 2018-05-01 at 3 14 51 pm](https://user-images.githubusercontent.com/1056412/39496257-80cdef92-4d52-11e8-8715-8afa4c94fa8c.png)
