### ISSUE TITLE
[Notebook] Duplicated code to add New Notebook Entry functionality

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1906]
The Notebook author at TopCoder has completely duplicated the code of the Large View overlay (/platform/features/layout/src/MCTTriggerModal.js) just in order to add a "New Notebook Entry" button. The new code is found in /platform/features/notebook/src/directives/MCTModalNotebook.js. The code is about 95% the same. 

Given that everything that is capable of displaying in a Large View should also be allowed as a Snapshot in a Notebook entry, is there a better, more DRY way to do this?

@dtailor90 @VWoeltjen Can you please weigh in?

**Comment by VWoeltjen** [comment]
Agree that these should be deduplicated

**Comment by alamora** [comment]
This is Andy from TopCoder.  Curious what happened here - I wonder if we missed just taking this out?

**Comment by larkin** [comment]
@alamora my guess is it was an expedient way to keep all changes isolated to the plugin code without impacting the core platform, and it worked well enough.

@VWoeltjen @charlesh88 @dtailor90 the functionality from MCTModalNotebook can get rolled into MCTTriggerModal-- if the notebook plugin isn't activated then the action won't return anything, etc.

**Comment by dtailor90** [comment]
fixed in latest notebook branch, closing.
