### ISSUE TITLE
Broken documentation link

### ISSUE THREAD

**Issue by BusbyActual** [nasa/openmct#1907]
In [The site](https://nasa.github.io/openmct/documentation/) the hyperlink Development Process is referencing a directory instead of  '/docs/process/cycle.md'

**Comment by marcobeltempo** [comment]
I'm interested in fixing this issue

**Comment by BusbyActual** [comment]
likewise

**Comment by PunkChameleon** [comment]
@BusbyActual -- had found that there was an actual HTML page in the package that would be better to point to then the markdown. Included in PR. Thanks for spotting and hope this helps!

**Comment by BusbyActual** [comment]
I thought it was private as I couldn't find what was hydrating the page in the current repo. Cheers

**Comment by akhenry** [comment]
@BusbyActual Thanks for your help
