### ISSUE TITLE
[Tree] incorrect object icons after removing objects

### ISSUE THREAD

**Issue by psarram** [nasa/openmct#1911]
I deleted bunch of random objects from the tree via the context menu and noticed the icon for some objects appeared incorrect. For example, the icon for 'Layout Inner' which is of type display layout changed to the timer icon. See the screenshot. 

![screen shot 2018-02-13 at 11 38 36 am](https://user-images.githubusercontent.com/26494733/36170154-6ca16804-10b3-11e8-9202-cf8051167bdb.png)

**Comment by larkin** [comment]
Closed in https://github.com/nasa/openmct/pull/1992.
