### ISSUE TITLE
[Autoflow-Tabular] No telemetry points or data shown in WARP

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1914]
Currently the autoflow-tabular view is not showing any points within a packet. The console shows a javascript error associated with the CompositionCollection. It appears to be expecting all providers to expose a `.on` function, which the `WARPDictionaryCompositionProvider` does not.

```
TypeError: this.provider.on is not a function
    at t.on (CompositionCollection.js:80)
    at t.activate (AutoflowTabularController.js:103)
    at De.mounted (AutoflowTabularView.js:105)
    at he (vue.min.js:6)
    at vue.min.js:6
```

**Comment by akhenry** [comment]
On second though, closing to move to WARP repo.

**Comment by akhenry** [comment]
On analysis by @larkin it is actually an issue in openmct. `CompositionCollection` is incorrectly making an assumption that all composition providers will support `on`, which is an optional function.

**Comment by akhenry** [comment]
Testing notes:

This issue can be verified as fixed if the autoflow tabular view shows telemetry points within a packet, with telemetry updating alongside each telemetry point name.

**Comment by charlesh88** [comment]
Testathon 02/21/2018: Verified fixed.

**Comment by dtailor90** [comment]
Testathon 2/21/2018: Verified fixed

**Comment by Costigan** [comment]
Testathon 2/21/2018: Verified fixed
