### ISSUE TITLE
Telemetry

### ISSUE THREAD

**Issue by michele241993** [nasa/openmct#1916]
Hi, I would to know how I can chance  a telemetry data. I would introduce an alert icon if a data is greater than a  determined maximum value.
Thanks.

**Comment by larkin** [comment]
@michele241993 limit evaluators are currently in draft state, take a look at https://github.com/nasa/openmct/blob/master/example/generator/SinewaveLimitProvider.js for an example of how to implement one. 

Follow https://github.com/nasa/openmct/issues/1996 for updates on the limit evaluator API.
