### ISSUE TITLE
[Inspector] Clicking Inspector breadcrumb elements doesn't navigate

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1927]
![screen shot 2018-02-24 at 10 39 08 am](https://user-images.githubusercontent.com/1056412/36633718-1bb02256-194f-11e8-9050-2e11d4235de7.png)

Clicking any element in a path breadcrumb should navigate to that element, but does not.

**Comment by larkin** [comment]
Fix up for review in https://github.com/nasa/openmct/pull/1930.

**Comment by dtailor90** [comment]
Verified working 03/15/2018

**Comment by jtrimble2100** [comment]
Verified.

**Comment by larkin** [comment]
Verified. 3/15/2018

**Comment by VWoeltjen** [comment]
Verified in testathon 03/15/2018
