### ISSUE TITLE
CircleCI v.1 will be removed August 2018

### ISSUE THREAD

**Issue by ev1stensberg** [nasa/openmct#1933]
[CircleCI will be removed in August](https://circleci.com/blog/sunsetting-1-0/?mkt_tok=eyJpIjoiTVdNNE9ERTRNR1l3T1RGaCIsInQiOiJNRzc4Zm5JWlYyOFM4WjhcLytiS3ZnZ24xMjU4RVQ4alhWVENzM2ZtVVU0SDJ3Zmg3V3piV09GWXRiY21lY0lTRXozTStaSTBhenVwWWkyaCtFa3pyOWk5WkRWSHV3ZERld3lRbUJIeElhRTV1cEhsK21qbVJEUkFsXC95UWJpK0RPIn0%3D), which means the test will fail/deny to run. It would be nice to upgrade to CircleCI v.2 as fast as possible to be done with the migration from v1 -> v2. 

V2 has a lot of breaking changes, so it might be a good time to do this now.

**Comment by ev1stensberg** [comment]
I've fiddled around in CircleCI  v2 with OpenMCT before, so maybe I could take a stab at it?

**Comment by akhenry** [comment]
@ev1stensberg Thanks for the heads up. If you have the time and inclination find out what's involved in migrating our build to CircleCI v2 that would be much appreciated!

**Comment by akhenry** [comment]
@ev1stensberg Feel free to work on whichever you prefer :) @VWoeltjen is not working on an orbital visualization, I linked to his heatmap repo as an example of an Open MCT plugin built with Webpack. It was simply to make the point that you don't need to use AMD/UMD/require/whatever to build a plugin for Open MCT. You can use whatever tools you prefer to work with.
