### ISSUE TITLE
Datepicker Calendar doesn't appear if there are non-zero milliseconds

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1934]
1. Load Open MCT 
2. Switch to fixed timespan mode if you're not currently using it.
3. Ensure the start time in the time conductor has milliseconds, e.g. 2018-03-01 23:52:22.700Z
4. Click on calendar icon to open datepicker.
5. Notice that datepicker does not open, and start time changes (milliseconds are removed).

Reported by a user at JPL.
![datepicker-not-showing](https://user-images.githubusercontent.com/226503/36877299-62e44224-1d6e-11e8-8d0e-b7ce0630e751.gif)

**Comment by mudinthewater** [comment]
> Ensure the start time...

It appears my initial bug report was incorrect - this affects both the start time calendar and the end time calendar. I just never noticed the end time calendar. This can be worked around in existing applications by setting the fixed time on load for both start time and end time (if the application is designed for a fixed time) to XXX-XX-XX XX:XX:XX.000Z. 

Note that dragging the time-slider will always set the milliseconds to .000Z, regardless of what they were before so the time slider can't be used for translating a graph set in a very small time range. (I assume this was a design decision to keep the time slider from being too precise to be useful)

**Comment by rukmini-bose** [comment]
Verified Testathon 3/20/2024

**Comment by charlesh88** [comment]
Testathon 2024-03-20 cannot repro, fixed.
