### ISSUE TITLE
[Plot] Alarm markers persist after removing telemetry series

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1935]
If you remove a telemetry series from a plot that is displaying alarm markers, the alarm markers will continue to display.

Simple repro:
1. create new sine wave generator with defaults.
2. create overlay plot
3. drag and drop in sine wave generator
4. right click in elements pool, remove sine wave generator
5. note that alarm markers still display.

**Comment by psarram** [comment]
Verified in Testathon 2018-05-01.

**Comment by charlesh88** [comment]
Testathon 2018-05-01 - verified fixed.

**Comment by psarram** [comment]
@larkin although this issue is fixed, but I noticed label will continue to display after removing a sine wave generator. I'd expect label to be removed also.

**Comment by larkin** [comment]
@psarram opened https://github.com/nasa/openmct/issues/2014 to track that.
