### ISSUE TITLE
bundles.json missing: How to register a new bundle?

### ISSUE THREAD

**Issue by Xnaff** [nasa/openmct#1944]
Hi in all your documentations a new Bundle should be registered in the bundles.json file located in the root directory. This file is missing and even if I create one it doesn't work. I could register my bundle in src/defaultRegistry.js but i don't think you intent to move the registration to this file. So if you changed the registration could you update your documentation?

**Comment by larkin** [comment]
@Xnaff the old developer guides and documentation is now considered legacy and will be deprecated soon.  We now use plugins, a simple function that gets invoked with an openmct instance and attaches functionality to that.  For some examples, look at [the tutorial](https://github.com/nasa/openmct-tutorial) and see the new docs in [API.md](https://github.com/nasa/openmct/blob/master/API.md).
