### ISSUE TITLE
[Notebook] Initial Integration

### ISSUE THREAD

**Issue by dtailor90** [nasa/openmct#1946]
A bunch of Issues that need to be fixed before we integrate into master:

1. Entry line breaks are not being preserved (Mac; Chrome and Firefox Quantum). Entering multiple lines with line breaks does displays multiple lines, even after tabbing out. But refreshing the window (or navigating away and back) displays the entry without line breaks.
2. New entry isn't setting focus to the input, but should.
3. Entry text should be sanitized.
4. New entries pick up the text of a previous entry. To reproduce, create a new entry, add text. Tab out, then click the dashed box area to create a new entry. Instead of blank (desired) the text of the new entry will be the same as the previous.
5. Editing an entry is updating the entry's createdOn datetime value, reordering the entries. Instead, do not update createdOn, but track the datetime of the edit in a new property, something like modifiedOn.
6. Deleting a newly created entry (before refreshing browser), removes entry below the intended delete. Note: When refreshed the correct entry is deleted, but before refresh the wrong li is removed

**Comment by dtailor90** [comment]
## Testing Notes

Below are the testing instructions that correspond to the Issue number above:

1. Create a new entry with line breaks, click outside the entry to save the current entry, refresh the page and verify line breaks present still. 
2. Click on new entry, verify the top most entry (newest) is focused and ready for user entry.
3. Try and inject a script, verify that it does not work.
4. Create a new entry, add text. Tab out, then click the dashed box area to create a new entry. Instead of blank (desired) the text of the new entry will be the same as the previous. Verify old entry text is not copied into new entry.
5. Create a few entries, edit an older entry and tab out. Verify that the order of entries does not change. 
6. Create a new entry with some text, tab out and create another new entry with different text. Try and delete the latest entry. Verify the correct entry is deleted.

**Comment by akhenry** [comment]
Closing to mark ready for testing

**Comment by larkin** [comment]
Testathon 3/15/2018:
* closing browser or refreshing browser in the middle of writing a notebook entry discards all changes.
* snapshot behavior is 100% broken and does not do the right thing.  Let's discuss the proper way to integrate this.

**Comment by jtrimble2100** [comment]
There are enough usability issues to make the notebook very frustrating to use. Example - I add a snapshot but every time I do this I have to go through the whole tree from the start to save something, and find the notebook I was just in. Why doesn't it default to my current notebook, or at least have a list of favorites or even have a list of notebooks. I'm trying to save something to a notebook yet I have to navigate the tree with every object type.

**Comment by jtrimble2100** [comment]
The mental model for taking snapshots doesn't make any sense to me.

**Comment by dtailor90** [comment]
clicking on new entry with an empty last entry does not focus for user entry

**Comment by dtailor90** [comment]
Conversation with @larkin:

1. For snapshot - right click on object to be captured, in the menu, there should be a add to notebook option, this will open up a modal with selected object view, which then allows user to take a snapshot of. 
2. User should only be able to snapshot what he see's currently. 
3. Dragging objects into new entry should only create a link entry to object, no snapshot.

**Comment by dtailor90** [comment]
After conversation with Jay - 

1. disable "new notebook entry" action on notebooks.
2. remembering last notebook entry. -> V2.
3. should not be able to delete entires, only archive. -> V2
4. allow multiple embeds / links in a single entry. -> V2
5. Fix snapshotting process so it works.

**Comment by charlesh88** [comment]
Notebook merged with master; closing so this can be part of the 07-02-2018 Testathon.

**Comment by dtailor90** [comment]
Testing Notes:

Create Notebook
Add Entries
Take snapshots, annotate and add to entry.
General usability of Notebook.
