### ISSUE TITLE
[Notebook] Removing text from an entry doesn't persist

### ISSUE THREAD

**Issue by psarram** [nasa/openmct#1951]
Steps to reproduce:

1- In a notebook, click "To start a new entry, click here to start..." and enter "Test 1" in the entry.
2- Click "To start a new entry, click here to start..." again to create another entry and enter "Test 2".
3- Remove "Test 1" from the first entry.
4- Click "To start a new entry, click here to start..." to add a new entry. 
5. Notice "Test 1" appears in the entry from which it was removed.

**Comment by dtailor90** [comment]
@charlesh88 - Do we want to persist empty entries, or rather entries that are modified to empty?

**Comment by dtailor90** [comment]
After discussion with @charlesh88 and @costigan - we came to an understanding that we should persist modified entries even if the user modified it to an empty entry.

**Comment by dtailor90** [comment]
Fixed in most PR #1947. Closing

**Comment by charlesh88** [comment]
Testathon 2018-05-01 - verified fixed.
