### ISSUE TITLE
Some dates appearing as "Invalid dateZ"

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1952]
Some displays are showing the above text in place of dates. 

### Steps to reproduce
1. In WARP, navigate to the POSE_DELAYED packet.
2. I the autoflow-tabular view, the 'Timestamp' field will show "Invalid dateZ" instead of the date.

![screen shot 2018-03-15 at 16 52 00](https://user-images.githubusercontent.com/4215777/37496801-dc7bb488-2871-11e8-9ac9-d85116b6f5b1.png)

**Comment by akhenry** [comment]
This has been fixed by a change in WARP server.

**Comment by charlesh88** [comment]
Testathon 03-30-2018: verified fixed.

**Comment by psarram** [comment]
Verified fixed in Testathon 3/30/18.
