### ISSUE TITLE
Update Style Guide from v1.0.0

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#196]
https://drive.google.com/a/nasa.gov/file/d/0B0v27OM1JkSeRTg0bzE1Q0hDOEE/view?usp=sharing

HTML/CSS changes, usage of .loading class, DialogService, etc.

**Comment by larkin** [comment]
@charlesh88 for html and css documentation, have you seen css living style guides such as http://kaleistyleguide.com and http://jacobrask.github.io/styledocco/?

They allow you to document CSS styles with real examples and we could easily add it to our build process so it is published along side our auto-generated docs at http://nasa.github.io/openmctweb/

**Comment by charlesh88** [comment]
Styledocco looks great, I'll dig into this further.

**Comment by charlesh88** [comment]
Closing as a duplicate of #1233
