### ISSUE TITLE
[Imagery] History shows oldest image first

### ISSUE THREAD

**Issue by vicfx** [nasa/openmct#1962]
Steps to reproduce:

1. Set Time Conductor to Fixed Timespan mode
2. Locate a telemetry point which provides images (and has history) and navigate to that
3. __Observe:__ Image shown is the oldest image from history

Desired behavior would be to show the latest image.

**Comment by akhenry** [comment]
This also affects real-time mode if images are not received regularly (eg. in WARP sims).

**Comment by larkin** [comment]
Fixed in #1983

**Comment by larkin** [comment]
In verification, seeing that upon navigation to an imagery source, the last image displays, but the history pane shows the last image twice.  Twiddling the time conductor to reload data and the last item will only display once.

![screen shot 2018-05-01 at 2 33 23 pm](https://user-images.githubusercontent.com/226503/39494828-c0992368-4d4c-11e8-85af-230d626c6c31.png)

**Comment by larkin** [comment]
Testathon 2018-05-01: Verified fix, but also seeing separate bug in comment above.

**Comment by charlesh88** [comment]
Testathon 2018-05-01 - verified fixed.

**Comment by akhenry** [comment]
Testathon 2018-05-01: Verified fixed.
