### ISSUE TITLE
[Frontend/CSS] Better initial startup strategy

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#1966]
I think there's a better way to handle the display when the application is loading, to solve for this issue:
![screen shot 2018-03-27 at 4 44 09 pm](https://user-images.githubusercontent.com/1056412/38000783-1af8f5b6-31de-11e8-9e5b-cd44018ee489.png)

1. Add styles to the splash screen CSS that hide the outermost container of the DOM that's about to be injected (`.holder-all`) when the app loads. 
1. Move the transition of the splash screen to styles in the main app;
1. Add a style that renders at the end of the main CSS that makes `.holder-all` visible.

**Comment by charlesh88** [comment]
### Testing notes:
Load and refresh the app multiple times. Navigate to a complex object, or one with a lot of plots. Observe: while you might see elements moving into position, or initially not visible and then appearing as they load, one should never see the application render as shown in the screenshot at the top of this issue where elements are loading ahead of the CSS.

**Comment by larkin** [comment]
I believe this only happens because the warp splash css isn’t properly loAded in the first place.
