### ISSUE TITLE
[Time Conductor] Enter not working to set start or end time

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1969]
Enter no longer works when manually setting start and end times in the time conductor. Currently it is necessary to tab out of the field for changes to take effect.

**Comment by larkin** [comment]
Closed with #2020.

**Comment by dtailor90** [comment]
Testathon 07/02/18 - Can still recreate bug. Enter is not working to set time conductor time.

**Comment by larkin** [comment]
2018-07-02: Verified Enter is working to set start time in both fixed and real-time modes.

**Comment by akhenry** [comment]
Reopening to address focus issue.

**Comment by charlesh88** [comment]
Will be fixed for Local UTC (real-time) mode with #3311.

**Comment by charlesh88** [comment]
Fixed.

**Comment by rukmini-bose** [comment]
Testathon Verified Still Fixed 3/20/2024

**Comment by ozyx** [comment]
not an issue anymore :) -- retested 3/20/24
