### ISSUE TITLE
[Snapshot] 'undefined' tooltip

### ISSUE THREAD

**Issue by psarram** [nasa/openmct#1970]
In the Annotate Snapshot overlay, the tooltip for the button that does undo is 'undefined'.

![undefined-tooltip](https://user-images.githubusercontent.com/26494733/38156274-905e47de-3431-11e8-972a-c78144cb7b99.png)

**Comment by psarram** [comment]
Observed in Testathon 03/30/18.

**Comment by aayusharora** [comment]
Hi @psarram 
I want to work on this, can you please provide the steps to reproduce this issue.

**Comment by psarram** [comment]
1- Create an object like a Sine Wave Generator.
2- Click the "Add a new Notebook entry" button next to the edit button.
3- Click "Annotate" in the Embed section.

**Comment by larkin** [comment]
@aayusharora this is in work by @dtailor90 already as part of notebook integration, thank you for your interest!

**Comment by larkin** [comment]
@dtailor90 please close this if fixed in your pull request.

**Comment by jvigliotta** [comment]
@depperm Hey sorry for the late reply, this is no longer valid.
