### ISSUE TITLE
Non-non-binary-friendly work environment

### ISSUE THREAD

**Issue by vicfx** [nasa/openmct#1972]
# Steps to reproduce

1. Approach colleagues about a joke that insults a protected characteristic.
2. Receive simultaneous apology and reprimand, with request to stay quiet.
3. Email entire division reporting the incident.

# Observed outcome

A few NASA-side people complain about this email to contractor employing sender. Sender receives pressure from HR to quiet down, resigns to avoid future retaliation.

# Desired outcome

Rapidly educate colleagues about protected characteristic (gender diversity, in my case) and remove disincentives for openness. (My colleague was correct that I'd experience problems if I spoke up; this should not be the case.)

# Remedy

In the specific instance, unisex restrooms would alleviate the most ubiquitously visible assumption that all colleagues are men or women.

More generally, the adversarial relationship between employer and employee ensures conflicts of interest permeate the handling of complaints. Normalize horizontal escalation as an alternative.

# Candidate workaround

1. Dramatically quit.
2. [Embark on a new career as an obnoxious performance artist](https://liberapay.com/vicfx).
3. Resume work as an obnoxious open source contributor.

Working on Step 2. Step 3 is blocked until I get around to actually filling out a CLA correctly like a grown-up.

# Method of verification

Comments to this issue containing the following:

* Photos of NASA Ames Research Center employees openly experimenting with gender presentation in the workplace.
* Confirmation that Code TI bathrooms signs have temporarily (and harmlessly) been replaced with signage indicating "Androgyne" or "Neutral"
* Colleagues sharing stories about the challenges they, their friends, and families have faced due to ignorance of gender diversity.

These performance art exercises are designed to provide experiential learning at an incidental cost of resources.

**Comment by akhenry** [comment]
Appreciate the importance of this subject, but this is out of scope for Open MCT.

**Comment by vicfx** [comment]
Okay! I'll make a fork that non-binary people are allowed to work on.
