### ISSUE TITLE
[Plots] Minmax 'size' parameter is zero on reload / new tab

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1974]
Suspect we are calculating plot size before it has finished rendering.

### Steps to reproduce
1. In WARP, navigate to Dictionary > POSE_DELAYED > px
2. The plot should load data correctly, and show plot line
3. Refresh the browser
4. Plot will load with spinner that will never go away. Opening the javascript console will reveal a server 500 error due to a divide by zero.

**Comment by larkin** [comment]
Testathon 2018-05-01: Verified.  Can see correct size parameter in first load.

**Comment by akhenry** [comment]
Testathon 2018-05-01: Verified.
