### ISSUE TITLE
[Plot] Plot lines disappear when plot loses WebGL context

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1976]
Chrome imposes a hard limit of 16 on the number of active WebGL contexts. There is also a total pixel limit of 16 x 1024 x 1024. When either of these limits are exceeded, the browser will invalidate WebGLPlots contexts, starting with the oldest until it's back under the limit. The plots have some logic  to fall back to canvas 2d rendering if a WebGL context is not available at initialization time, but do not currently handle the case where a WebGL context is subsequently lost due to new WebGL contexts being created that cause the limit to be exceeded.

There are three potential approaches here -

1. Detect "webglcontextrestored" and re-render the plot in a WebGL canvas. 
2. Detect "webglcontextlost" and re-render the plot using the canvas 2D API. 
3. Do both

**Comment by akhenry** [comment]
In WARP the hard limit on WebGL contexts is being hit at 14 plots fairly consistently across different machines. It seems as though something is using two contexts before any plots have even loaded. For now will lower pool size [in our code](https://github.com/nasa/openmct/blob/fa7298a752b90531485941fb4d6b94e726021e54/src/plugins/plot/src/draw/DrawLoader.js#L33) to 14 so that Canvas 2D rendering kicks in sooner, which should prevent plots from losing GL contexts.

**Comment by larkin** [comment]
webglcontextrestored doesn't appear to trigger if browser context limit is exceeded; opting to solve with option 2.

**Comment by larkin** [comment]
Testathon 2018-05-01: Verified.

**Comment by akhenry** [comment]
Testathon 2018-05-01: Verified

**Comment by charlesh88** [comment]
Testathon 2018-05-01 - verified fixed.
