### ISSUE TITLE
[Drag and Drop] Transient issues with drag and drop

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1981]
When testing in WARP, drag and drop did not work on one occasion when trying to build a layout. The issue was resolved when the page was reloaded. No error messages were shown in the logs. Some initial investigation by @dtailor90 suggests that the issue may occur when annotations are created in notebook plugin.

**Comment by akhenry** [comment]
After some investigation, this appears to be due to the Painterro library overriding Open MCT's document and window event listeners. There does not appear to be a way to remove all listeners in Painterro right now - https://github.com/ivictbor/painterro/issues/19

**Comment by dtailor90** [comment]
closing as unverified - @akhenry fix was merged to notebook branch

**Comment by dtailor90** [comment]
verified fixed during testathon 05/01/2018

**Comment by akhenry** [comment]
Verified Fixed testathon 05/01/2018

**Comment by charlesh88** [comment]
Testathon 2018-05-01 - verified fixed.

**Comment by larkin** [comment]
I just repro'd this, let me double check again.

**Comment by larkin** [comment]
1. create notebook entry from object.
2. click "annotate" button.
3. click "x" button in upper right hand corner to close annotate window. (alternatively, press "ESC" key)
4. drag and drop will be broken.

**Comment by dtailor90** [comment]
@larkin - Fixed in latest push to notebook branch
