### ISSUE TITLE
[Fixed Position] Delays in Fixed Position Edit mode

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1987]
Opened by @charlesh88 
> Seen during testing 04102018. 
>
> 1. Creating a new Fixed Position object, there was a delay of around 10 seconds until the `Add` button appeared.
> 1. Clicking an element (telemetry channel, box, line) in a Fixed Position object results in a delay of 5 to 20 seconds until the selection rectangle updates to indicate selection, and the toolbar updates to reflect options for the selected item. Occasionally the delay is longer. Deselection showed similar delays. This was the case with telemetry included in the object and without.
>
> This makes Fixed Position unusable and should be fixed ASAP.

I believe this is due to a lack of digests regarding selection and the toolbar.

**Comment by psarram** [comment]
See issue #1991 for the problem related to Add button.

**Comment by larkin** [comment]
Closed with #1994

**Comment by psarram** [comment]
**Testing Notes:**

1. Create a Fixed Position object. 
2. Add new elements (e.g. line, box, text)
3. Select and de-select each element and verify toolbar updates immediately when selection changes.

**Comment by charlesh88** [comment]
Testathon 2018-05-01: verified fixed.

**Comment by larkin** [comment]
Testathon 2018-05-01: Verified.
