### ISSUE TITLE
[Fixed Position] Add button is missing when new object is created

### ISSUE THREAD

**Issue by psarram** [nasa/openmct#1991]
When a new fixed position display is created the Add button is missing in the toolbar. Clicking anywhere on the canvas makes it appear in the toolbar.

**Comment by psarram** [comment]
**Testing Notes:** 
1.  Create a Fixed Position Display.
2. Verify the 'Add' button appears in the toolbar.

**Comment by charlesh88** [comment]
Testathon 2018-05-01: verified fixed.

**Comment by larkin** [comment]
Testathon 2018-05-01: Verified.
