### ISSUE TITLE
[plot] support scatter plot (x/y plotting of 2 measurements)

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1995]
support scatter plotting, I.e. x/y plotting of two telemetry points. Or support plotting a different range value as x axis (with a single telemetry point).

Has been requested and in back log for some time, but I can’t find an existing issue, so creating this to track.

**Comment by mudinthewater** [comment]
Here are two examples that this support could be used for: 
1. XY historical movement for rover/robot movements on a map background. An updatable diagram like this would be most useful: [MSL](https://mars.nasa.gov/system/downloadable_items/40133_pia21720_MSL_Landing_to_MtSharp_traverse_Sol1750.jpg)

2. Something that would allow graphs like this one (From ASTERIA slides at AIAA smallsat conference): 
![image](https://user-images.githubusercontent.com/35539679/43742469-e73bd44e-9986-11e8-8557-373d1969de37.png)

**Comment by shefalijoshi** [comment]
Testing instructions:
1. Create a scatter plot
2. Drag in a telemetry endpoint (like a sinewave generator or a Correlation telemetry endpoint (VIPER)) into the scatter plot.
3. Ensure that the data is plotted
4. If you choose to render an underlay - with or without min/max range values - it should be rendered correctly as well
5. Only 1 telemetry endpoint is allowed at a given time - dragging a second one should replace the first with a dialog
6. Real time as well as fixed time span and independent time conductor should work as well.

**Comment by shefalijoshi** [comment]
[Underlay.json.zip](https://github.com/nasa/openmct/files/8766565/Underlay.json.zip)

**Comment by charlesh88** [comment]
Verified fixed Testathon 6-9-22.
