### ISSUE TITLE
[UI] UI enhancements

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2000]
Various UI tweaks to improve the interface.
- Better approach to discoverability for local controls
- Remove unused data visualization element in Time Conductor
- Improve visual styles associated with sub-object selection, especially in browse mode
- Fix broken Inspector properties layout
- Enhance Inspector for more clarity related to sub-object selection
- Enlarge pane expand/collapse arrows
- Hide View Large button on hidden frames

Related issues:
- #1758 
- #1763 
- #1396 
- #2011

**Comment by aayusharora** [comment]
Hi @charlesh88 
Can I work on it?

**Comment by charlesh88** [comment]
### Testing Notes
#### Inspector

1. Create an Overlay Plot, and drag in a few telemetry points. Observe the layout of elements in the Inspector - is everything organized and lined up nicely?
1. Save the Overlay Plot, and

**Comment by charlesh88** [comment]
### Testing Notes

- Review all changes as noted above and ensure they are visible/available and work as described. 
- Create 3 layouts with some objects in them, and nest them all within each other. The 2nd nested layout should have its frame hidden. Like this:
```
<Layout 1>
    <Object>
    <Object>
    <Layout 2 (hidden frame)>
          <Object>
          <Object>
          <Layout 3>
              <Object>
              <Object>
```
The second nested Layout should not display a View Large button on hover.
- Browse to various types of object types, particularly Overlay Plots, and ensure the Inspector appears as described. 
- Edit an Overlay Plot, choose different options, save, and view the object's Inspector pane: ensure that properties are displayed as expected.
- Change settings in the Time Conductor; drag the ticks in Fixed Timespan Mode, etc. and ensure that it works as expected.
