### ISSUE TITLE
overlapping local controls with layout in layout + hide border

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#2009]
When using nested layouts and hiding the border, the local controls overlap:

![screen shot 2018-05-01 at 2 30 18 pm](https://user-images.githubusercontent.com/226503/39494727-5e70880c-4d4c-11e8-9e6a-1cde78be0204.png)

**Comment by charlesh88** [comment]
This was fixed as part of changes executed in #2000, closing. To verify, see comments in that issue.

**Comment by dtailor90** [comment]
Verified Fixed - 07/02/18

**Comment by charlesh88** [comment]
Testathon 07-02-2018: verified fixed.
