### ISSUE TITLE
[Time Conductor] Markup/styling for text entry of dates

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#201]
Review/revise markup/styling for text entry of dates. In particular:

* Apply appropriate classes to inputs (if necessary) when dates are invalid (currently, using the "error" class)
* Ensure appropriately-sized clickable region for the date picker (currently
* Any adjustments to positioning/appearance of text area (currently it looks off by a few pixels, but more generally, not sure we want this to "look" like a text input until it's clicked on, etc)

Believe that all changes can be made within `platform/commonUI/general/res/templates/time-controller.html`

This is contingent on completion of merge related to #181

**Comment by charlesh88** [comment]
Am aware of the this issue and will be getting to asap with assumption that this is important for JPL demos upcoming.

**Comment by charlesh88** [comment]
Date formatting (visually) isn't perfect, but looks fine for now. #259 may introduce some new design aspects to this, so factor that in if needed.

**Comment by charlesh88** [comment]
Also need to fix the layout of the controller - the domain select placement isn't good, and the element should use flex layout.

**Comment by charlesh88** [comment]
In particular, datetime inputs in the Time Controller need to be addressed, particularly with error state colors in the Snow theme.

**Comment by VWoeltjen** [comment]
Unable to verify during testathon 5/31/2016; time conductor is not included in WARP at test time

**Comment by charlesh88** [comment]
Testathon 2016-06-16 
Verified fixed on ciedevweb1.jpl.nasa.gov:8443/mcws/clients/vista/.

**Comment by VWoeltjen** [comment]
Verified testathon 2016/06/16
