### ISSUE TITLE
[Plots] Plot options layout is whack

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2011]
Observed during Testathon 2018-05-01 and also seen in VISTA: when editing an overlay plot, the alignment of row items in the Inspector is messed up, and rows need more vertical space.
![screen shot 2018-05-01 at 3 03 01 pm](https://user-images.githubusercontent.com/1056412/39495853-fbe62606-4d50-11e8-8362-4317803fe9ed.png)

**Comment by larkin** [comment]
Refer to #2000 for testing notes.  Generally speaking, edit a plot and it should look un-whack.

**Comment by charlesh88** [comment]
Technically, the plot options layout in the Inspector should look un-whack :)

**Comment by dtailor90** [comment]
Verified Un-Whack! - 07/02/18
