### ISSUE TITLE
[Imagery] Duplicate image showing in history

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#2012]
seeing that upon navigation to an imagery source, the last image displays, but the history pane shows the last image twice. Twiddling the time conductor to reload data and the last item will only display once.

**Comment by dtailor90** [comment]
![image](https://user-images.githubusercontent.com/13260688/39496669-4f32410c-4d54-11e8-9ecf-2c151df4e07c.png)
Discovered by @larkin while verifying #1962

**Comment by ev1stensberg** [comment]
Could I take this one on?

**Comment by akhenry** [comment]
@ev1stensberg Thanks for the offer! We're actually going to take this one ourselves, so I've removed the help-wanted label.
