### ISSUE TITLE
[Notebook] Scrolling tables not captured in Notebook snapshot

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2013]
Seen during Testathon 2018-05-01, relates to #1903. Scrolling table in a Snapshot of a Layout.
Original:
![screen shot 2018-05-01 at 3 15 09 pm](https://user-images.githubusercontent.com/1056412/39496243-77de2b18-4d52-11e8-898f-882e542499a3.png)

From snapshot. Note that the table is empty, and the table column headers are visible.
![screen shot 2018-05-01 at 3 14 51 pm](https://user-images.githubusercontent.com/1056412/39496257-80cdef92-4d52-11e8-8715-8afa4c94fa8c.png)

To replicate: the view's scroll must NOT be pinned to the top. When pinned to the top, either via scrollbar manipulation, sorting, etc. the Snapshot will work Ok. Put the scroll anywhere other than at the very top, and Snapshot will not work.

**Comment by dtailor90** [comment]
Fixed with notebook and merged into master. Closing as unverified.
