### ISSUE TITLE
[Plot] automatic axis label should change when all elements removed

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#2014]
1. create new sine wave generator with defaults.
2. create overlay plot
3. drag and drop in sine wave generator
4. right click in elements pool, remove sine wave generator
5. notice that y-axis will be labeled "sine", even though there is no sine wave generator in the plot.

Found by @psarram while verifying fix for https://github.com/nasa/openmct/issues/1935

**Comment by psarram** [comment]
Also, If there are multiple sine wage generators on the plot and the Y axis label is set to something other than the default, e.g. "Test", removing one of the sine wave generators resets the label to "Sine".
