### ISSUE TITLE
[Summary Widgets] Better behavior when data not available for Summary Widgets

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2015]
Currently, when data is not available for a Summary Widget, it never loads and displays "Loading..." perpetually,  not even loading the default state. We need a better solution for this scenario that makes the "no data" situation more clear to the user. @charlesh88 to mind meld with @larkin to understand the scenario better, and why it's different from a telemetry point's field being undefined.

**Comment by larkin** [comment]
@charlesh88 The summary widget assumes (correctly or not) that the user will want data for every telemetry point before it displays a result, thus, it does not evaluate the current rule set until it has received data for all telemetry points.  

If we change that assumption, then either we force users to define rules that handle the case when data is missing, or we have to handle the case where a rule depends on data from a telemetry point and none has been received.  The latter seems like a reasonable option, especially if combined with a way to define rules that match when a telemetry point has no data, e.g.
![screen shot 2018-05-01 at 5 16 39 pm](https://user-images.githubusercontent.com/226503/39499752-dc7b08a4-4d64-11e8-8c75-58743763297c.png)
