### ISSUE TITLE
[Telemetry Table] shows intersection of columns, not union

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#2027]
When adding multiple telemetry points to a table that have different values available, (e.g. sine wave generator and state generator), the table should show all available columns.  Rows should contain blank values for unsupported columns.

Currently, the table only shows the intersection of columns, so combining a sine wave generator and a state generator results in a table that only has "name" and "timestamp" columns.

**Comment by akhenry** [comment]
An earlier version definitely showed the union of columns, but it's probably been this way for a long time.

**Comment by dtailor90** [comment]
Testathon (07/02/18)

When adding a state generator and sine wave generator to a telemetry table, it shows all available columns (as required), but some values (sine, cosine) should be blank for rows with state generator values but they show up as NaN. 

![image](https://user-images.githubusercontent.com/13260688/42188868-92995b56-7e0a-11e8-8d63-8e3a930fbb3e.png)

**Comment by larkin** [comment]
2018-07-02: Verified... but buggy with various combinations.

The nan bug seems to be very specific to the sine and cosine columns, and can't be reproduced with other combinations of telemetry (e.g. event generator + state generator).

Try combining a state generator with a warp telemetry point and... my browser crashed.  But the warp telemetry point was showing values for the state column before that, which it should not do.

**Comment by charlesh88** [comment]
Testathon 07-02-2018: verified fixed, per this issue: I now see the superset of columns.

**Comment by akhenry** [comment]
Reopening to investigate performance issues and NaN values.
