### ISSUE TITLE
[Time Conductor] Ticks not displaying in Time Conductor in Chrome

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2031]
In latest master running locally, not seeing the TC ticks in either Fixed or RT modes:
<img width="1599" alt="screen shot 2018-05-04 at 1 28 08 pm" src="https://user-images.githubusercontent.com/1056412/39651055-567ddf50-4f9f-11e8-809e-0d8f2a7caab5.png">

Weirdly, they do display in Safari:
![screen shot 2018-05-04 at 1 29 22 pm](https://user-images.githubusercontent.com/1056412/39651074-61fbfb82-4f9f-11e8-965b-8726361209ef.png)

Note the inconsistency between the two browsers in the gradient tick blockers beneath the Start and End inputs as well.

**Comment by charlesh88** [comment]
Fix for gradient blockers done in branch mobile-2008 44c218f.

**Comment by charlesh88** [comment]
Tick marks have been removed from the Time Conductor in work done for #2000, but the time strings are retained.

**Comment by charlesh88** [comment]
Fixed in branch topic-core-refactor.

**Comment by rukmini-bose** [comment]
Testathon Verified Still Fixed 3/20/2024

**Comment by ozyx** [comment]
Testathon Verified Still Fixed 3/20/2024
