### ISSUE TITLE
[Notebook] Add property to set default sorting order when creating notebook

### ISSUE THREAD

**Issue by dtailor90** [nasa/openmct#2037]
After conversation with Jay and Charles (05/14) - A conclusion was made to add this feature as it would be useful for users. Users should still be able to change sort order later, and through the edit menu.

**Comment by dtailor90** [comment]
Fixed in PR #1947 commit on (05/16). Closing as unverified

**Comment by dtailor90** [comment]
## Testing Notes:
1. Create notebook
2. when saving, verify there is a default sorting order option. 
3. Verify you can change the order while viewing notebook, and when you refresh/navigate away from the notebook and back, it reverts to default order.

**Comment by larkin** [comment]
2018-07-02: Verified, however:

This should show the default sort order instead of being blank.

**Comment by charlesh88** [comment]
Testathon 07-02-2018: verified fixed.

Definitely agree with @larkin, will file an issue for such.

**Comment by juliecwang** [comment]
Testathon 07-02-2018: verified fixed.
