### ISSUE TITLE
[Noteboook] Can't move text insertion point with mouse when Notebook is in a Layout

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2041]
When a Notebook is in a Layout, the user is unable to move the text insertion point with the mouse, or select text. Interactions with the Notebook on its own work as expected.
### Replication

1. Add a Notebook to a Layout.
1. Add an entry, type some text, tab out to save the entry.
1. Click the text field of the Notebook entry to edit it, then observe: the text insertion cursor is at the end of the entry, and attempts to change it's location by clicking in the text don't work, appearing to toggle out of the field. Arrow keys can be used to move the cursor.

Expected: user should be able to move the text insertion point and select text normally with mouse gestures.

**Comment by dtailor90** [comment]
@charlesh88 - this is because of s-input-inline getting pointer events disabled inside .t-frame-outer. Fixed in PR #2049, with some code cleanup as well

**Comment by dtailor90** [comment]
fix merged to notebook branch, closing as unverified.

**Comment by charlesh88** [comment]
Testathon 07-02-2018: verified fixed.

**Comment by juliecwang** [comment]
Testathon 07-02-2018: verified fixed.
