### ISSUE TITLE
[export] JSON export is exporting links

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#2042]
The JSON export functionality is exporting linked objects as links rather than original objects in some cases. This limits the utility of this functionality as the original objects will need to exist in the import environment.

It looks like the linked objects are actually being copied, as they appear in the exported tree, but the composition of the new parent is not being updated with the new IDs.

Steps to reproduce
1. Create three folders - "Folder A", "Folder B", and "Folder C"
2. Drag Folder B and Folder C into Folder A. Folder A should now have two child links, eg. -
<img width="218" alt="screen shot 2018-05-18 at 16 25 19" src="https://user-images.githubusercontent.com/4215777/40261875-1ba7a7de-5ab8-11e8-96d6-d2440e930d29.png">

4. Export Folder A as JSON
5. Import the exported file
6. Navigate to the newly imported Folder A. Note that Folder B is still a link.
<img width="220" alt="screen shot 2018-05-18 at 16 27 26" src="https://user-images.githubusercontent.com/4215777/40261907-63ebddd0-5ab8-11e8-9fcd-d2898c23ac30.png">

**Comment by dtailor90** [comment]
Verfied: 07/02/18

**Comment by charlesh88** [comment]
Testathon 07-02-2018: verified fixed.

**Comment by juliecwang** [comment]
Testathon 07-02-2018: verified fixed.
