### ISSUE TITLE
Building and running OpenMCT locally does not work

### ISSUE THREAD

**Issue by 9a3eedi** [nasa/openmct#2050]
I'm a new user to OpenMCT and I've been trying to follow the tutorials on openmct-tutorials, without any luck (I get a blank page in localhost:8080). So I thought I'd try building and running openmct from this project, however I'm getting similar issues..

I have followed the instructions as written in the README, but I end up with a blank page in localhost:8080. I get the following errors in chrome's javascript console.

```
require.js Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:33 Uncaught ReferenceError: require is not defined
    at localhost/:33
localhost/:1 Refused to apply style from 'http://localhost:8080/platform/commonUI/general/res/css/startup-base.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
localhost/:1 Refused to apply style from 'http://localhost:8080/platform/commonUI/general/res/css/openmct.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
localhost/:1 Refused to apply style from 'http://localhost:8080/platform/commonUI/general/res/css/startup-base.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
localhost/:1 Refused to apply style from 'http://localhost:8080/platform/commonUI/general/res/css/openmct.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

```
I'm not sure what went wrong, but I simply can't get it to work. I figured that there's a missing dependency with require.js, but I'm not sure how to resolve it. I also tried installing require.js from my package manager (Ubuntu 16.04) but that didn't help either. I'm guessing something needs to be fixed in the npm install step, but I'm not an expert on javascript or npm.

**Comment by akhenry** [comment]
Thanks for reporting this, we're looking into it.

**Comment by akhenry** [comment]
@9a3eedi Looks like this happens in certain versions of Node. I don't get this issue in Node 8.7.0, but I do get it in Node 6.10.0.

In the short term, I'd recommend using Node 8.7.0+ and I'll see what we can do about improving support for older Node versions. If you're newish to the Node world, [nvm](https://github.com/creationix/nvm/blob/master/README.md) is a great tool for switching node versions.

Thanks for your patience.

**Comment by akhenry** [comment]
Another workaround is to run `npm run prepare` manually. I've detailed both of these workarounds in in a new issue tracking npm compatibility generally in #2052. Let me know if the workarounds listed there do not work.

**Comment by pr331570** [comment]
@9a3eedi can you try with below code in index.html

<script src="bower_components/requirejs/require.js" type="application/json"> </script>

I think this should fix the first error. Let me know if this works.

**Comment by 9a3eedi** [comment]
@akhenry I can confirm that using `npm run prepare` manually before running `npm start` has fixed the problem. I can now open OpenMCT in my browser. Thank you!

For the record I am using npm 3.5.2. I guess this is what's bundled with Ubuntu 16.04 LTS. I just try to avoid installing things outside what's available in the package manager.
