### ISSUE TITLE
Error while running the project

### ISSUE THREAD

**Issue by pr331570** [nasa/openmct#2051]
Getting error -  Uncaught ReferenceError: require is not defined.

![image](https://user-images.githubusercontent.com/39397597/40724753-70bcd614-643f-11e8-90c3-6ce4c5a736b8.png)

**Comment by akhenry** [comment]
Thanks for reporting. Looks like a recently introduced bug in the build process. We're looking into it, in the meantime thanks for your patience.

**Comment by akhenry** [comment]
@pr331570 It looks like this is a [Node version issue](https://github.com/nasa/openmct/issues/2050#issuecomment-393251827). If you're able to upgrade to 8+ then that should fix it in the short term.

**Comment by akhenry** [comment]
Looks like the same issue as https://github.com/nasa/openmct/issues/2050, and https://github.com/nasa/openmct-tutorial/issues/29

**Comment by pr331570** [comment]
Thanks akhenry for coming back to me.

I tried with - npm run prepare but no go. Encountered with the same error again.

**Comment by akhenry** [comment]
@pr331570 can you tell me which npm version you're using? ie.
```
npm --version
```
Thanks!

**Comment by pr331570** [comment]
Hi,

I am using npm 5.6.0 and OS Win 10 64-bit.
