### ISSUE TITLE
[Elements Pool] Ability to rearrange elements in composition

### ISSUE THREAD

**Issue by dtailor90** [nasa/openmct#2066]
Drag and Drop capability to rearrange the elements in composition. This would give users the ability to rearrange stacked plots as well as rearrange objects in Fluid-Layouts.

**Comment by dtailor90** [comment]
Testing Notes: 
1. Create 3 Sinewave Generators with different properties. 
2. Create a Stacked plot and drag in the sinewave generators created in step one. 
3. Hover over element in elements pull, and use drag and drop to reposition their order. 
4. Confirm Plots in stacked plots were also rearranged.

**Comment by larkin** [comment]
This generally works, but there are bugs with plot.  If you rearrange the composition of the plot, and then edit series options, initially, everything looks good.  But when you save and quit, things get borked.

Will open plot issue.

**Comment by larkin** [comment]
2018-07-02: Verified working in other views.

**Comment by charlesh88** [comment]
Testathon 07-02-2018: verified fixed.

**Comment by juliecwang** [comment]
Testathon 07-02-2018: verified fixed.
