### ISSUE TITLE
[Folder] List view takes a long time to load

### ISSUE THREAD

**Issue by psarram** [nasa/openmct#2067]
1. Navigate to a folder with some objects in it.
2. Open the Grid drop down and select List.
3. Note the time it takes for the data to display

I've seen cases as long as 4 seconds and up to 14 seconds. Clicking on the screen makes the data display immediately. At a minimum a wait spinner should be displayed until the data loads.

**Comment by dtailor90** [comment]
Fix was merged with PR #2069. Closing as unverified.

**Comment by juliecwang** [comment]
###Testing Notes 
Navigate to a folder with some objects in it, open the Grid drop down and select List, note that the data appears immediately.

**Comment by dtailor90** [comment]
Verified Fixed during testathon (06/02/2018)

**Comment by larkin** [comment]
2018-07-02: Verified Fixed

**Comment by charlesh88** [comment]
Testathon 07-02-2018: verified fixed.

**Comment by juliecwang** [comment]
Testathon 07-02-2018: verified fixed.
