### ISSUE TITLE
odd rendering in the telemetry plot

### ISSUE THREAD

**Issue by pablogh-2000** [nasa/openmct#2077]
Dear all,

since I last updated open mct via NPM, I am seeing the telemetry plots like the attached screenshots.
They have like a specular image of the same plot attached to it in a dotted line....

Do you know how to get them right?

Thanks,

Pablo.

Update1: this happens in Ubutu 16.04 with both Chrome and Firefox. I have npm 6 and node 8. I have not tested other setups.
Update2: the same issue happens with the tutorial.

<img width="1319" alt="open_mct_screenshot2" src="https://user-images.githubusercontent.com/39036462/41510927-85604f06-726d-11e8-8fad-356ca41db8d3.png">
<img width="1329" alt="open_mct_screenshot1" src="https://user-images.githubusercontent.com/39036462/41510928-857d6adc-726d-11e8-80f4-e3bdd950c0c6.png">

**Comment by akhenry** [comment]
@pablogh-2000 Thanks for raising this as an issue. We have not observed this behavior on other platforms, so it's possible that it's platform-specific. That said, we have done some testing in Ubuntu 16.04 previously. May possibly be driver-related. It [would not be the first time](https://github.com/nasa/openmct/issues/1805).

@larkin you're more knowledgeable about the plots, any theories about what might be going on here?

**Comment by pablogh-2000** [comment]
Hi again,

after doing some more testing, I can see that the problem happens only in browsers opened in Ubuntu.
I am running Ubuntu in VMWare in my Mac Book pro. So I have tried with a browser in the host Mac OS and it works fine there.
Same versions of Firefox and Chrome works well in Mac and don't work in the Ubuntu 16.04 VMWare virtual machine.

I have now, therefore a workaround, but if you have any fixes or ideas how to fix this issue, would be great.

Thanks,

Pablo.

**Comment by akhenry** [comment]
@pablogh-2000 Thanks for following up with us.
