### ISSUE TITLE
Red and Yellow limits not displaying icon

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2083]
A red or yellow limit violation applied to a block element (without upper or lower violation designation) should still display a warning triangle icon.

**Comment by charlesh88** [comment]
Violations also messed up in Fixed Position: 
<img width="93" alt="screen shot 2018-06-21 at 12 59 47 pm" src="https://user-images.githubusercontent.com/1056412/41742526-22723a4c-7553-11e8-9a2b-584973fbbd8c.png">

**Comment by charlesh88** [comment]
Actually, the correct classnames must be in use: `s-limit-icon-yellow` and `s-limit-icon-red`.

**Comment by aayusharora** [comment]
Hi @charlesh88 
Can you please provide the steps to reproduce?
It would be great if I can take this issue.
