### ISSUE TITLE
Limit violations not displaying in plot legend

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2084]
Limit violations are not displaying in plot legend, but should. Related to #2083.

**Comment by larkin** [comment]
Steps to verify:

1. Create a sine wave generator
2. view sine wave generator as plot: you should see plot points in alarm on plot.
3. hover over plot point in alarm on plot
4. legend should highlight to display limit state.

![screen shot 2018-07-20 at 2 17 17 pm](https://user-images.githubusercontent.com/226503/43025712-b0d92972-8c27-11e8-80be-80e46f701a50.png)
