### ISSUE TITLE
Summary Widget string eval works in Edit mode but not in Browse

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2086]
Widget evaluation with strings works as expected in Edit mode, but not Browse. Relates to https://github.jpl.nasa.gov/MissionControl/vista/issues/561. Here's how to replicate, using two Summary Widgets to get string output that mimics enum'd telemetry.

1. Make a State Generator with a state duration of 1 to 3 seconds. Then make a Summary Widget that uses it as an input, like this:
![screen shot 2018-06-25 at 12 28 06 pm](https://user-images.githubusercontent.com/1056412/41871293-577062be-7873-11e8-8334-35485587d670.png) Make sure to enter values for each Rule's Label field.

2. Make another Summary Widget that uses the first one as an input, like this:
![screen shot 2018-06-25 at 12 30 56 pm](https://user-images.githubusercontent.com/1056412/41871396-a3573d88-7873-11e8-9ea3-a499d8931be3.png)

3. Note that while editing, your Summary Widget will regularly change styling, as expected.
4. Save your work and exit to browse mode. Observe: the widget will no longer change style as the rule evaluation is working differently in browse mode.

**Comment by dtailor90** [comment]
After some investigation - Need to add string support for formatProvider

**Comment by charlesh88** [comment]
### Testing Notes
Execute steps as detailed in the bug replication notes above, except observing the widget in Browse mode in step 4 should show it working as expected.

**Comment by charlesh88** [comment]
Testathon 07-02-2018: verified fixed.

**Comment by juliecwang** [comment]
Testathon 07-02-2018: verified fixed.
