### ISSUE TITLE
[Notebook] "New Notebook Entry" action is available from the context menu when creating new notebook entry

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#2098]
Steps to reproduce
1. Create a new notebook entry using the snapshot action from any object view
2. In the locator, right click on any object and observe that the "New Notebook Entry" action is available from the context menu.

Click on this action embeds the object currently being viewed, rather than the object that was right-clicked on. The snapshot is also lost.

For now this option should be disabled from the New Entry dialog.

**Comment by dtailor90** [comment]
@akhenry - Currently we don't have a method to check in what location these actions show up. We can only disable them for certain objects, using a policy. Correct me if I am wrong though.

**Comment by larkin** [comment]
Fixed by #2113.
