### ISSUE TITLE
[Summary Widget] Cannot return to default label option after selecting a label

### ISSUE THREAD

**Issue by juliecwang** [nasa/openmct#2100]
To replicate:
Create a new summary widget. While defining a new rule, select a label from the drop-down menu other than "None", observe that the default label option "None" is no longer available for selection.

**Comment by charlesh88** [comment]
@juliecwang I can't duplicate this locally - I see the menu option for "None" whether I've selected a label icon or not.
 
![screen shot 2018-07-03 at 2 43 28 pm](https://user-images.githubusercontent.com/1056412/42245968-b047a962-7ecf-11e8-949d-db0eeb39e76c.png)

Any chance you could add a screenshot of what you saw?

**Comment by juliecwang** [comment]
@charlesh88 For me the "None" option is still visible, but I can no longer select it. So I can't return to a no label option after selecting a label icon.
