### ISSUE TITLE
Snapshot from View Large overlay has a number of problems

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2110]
Snapshotting from the View Large overlay for a variety of object types has problems. Note that this is not an issue when adding a new Notebook entry from the main view, and _partially_ when invoking the Preview action.

### Reproduce
- Create a Layout and add various object types to it. Save it.
- In Browse mode in the Layout, click View Large on the object's frames. From the dialog, click "New Notebook Entry".

### Problems
1. The snapshot is grabbing the entire overlay instead of the view object inside. 
<img width="1428" alt="screen shot 2018-07-03 at 5 08 00 pm" src="https://user-images.githubusercontent.com/1056412/42250559-97e970be-7ee6-11e8-805a-d3da54d0c302.png">
<img width="1300" alt="screen shot 2018-07-03 at 5 57 23 pm" src="https://user-images.githubusercontent.com/1056412/42251179-9267ffc6-7eea-11e8-8811-86fc09f13a4f.png">

2. Tables and plots (plot view, Overlay and Stacked plots) are coming up blank. See above image. Could be related to #1. 
3. Fixed Position and Imagery don't show images, very probably an issue with our background-image approach. This also occurs with the Preview action as well.
4. Imagery thumbs overrun the thumbs holder. The overrun problem almost assuredly the same as seen in #2105 and I think the same fix applied here will fix this issue. 
<img width="1521" alt="screen shot 2018-07-03 at 5 22 12 pm" src="https://user-images.githubusercontent.com/1056412/42251011-a764e4a8-7ee9-11e8-89f4-b84426b75781.png">
5. Timeline: Timeline appears, but translucent. I have no idea what's going on here. 
<img width="1302" alt="screen shot 2018-07-03 at 5 15 35 pm" src="https://user-images.githubusercontent.com/1056412/42251027-bffc6fae-7ee9-11e8-956b-e23cf26cdd95.png">

**Comment by larkin** [comment]
Fixed by #2113.
