### ISSUE TITLE
Line Styles and other metadata do not persist for overlay plots in master

### ISSUE THREAD

**Issue by mudinthewater** [nasa/openmct#2136]
Line styles are not being saved to either CouchDB or LocalStorage in master. They always default to linear interpolate after leaving and returning to a diagram. To reproduce: 

clone master
npm install 
npm start
create sine wave generator
create overlay plot with the sine wave generator, select None under line style and save to my items. 
At this point your saved overlay plot might just lose its telemetry points!
Leave the plot and come back to it and line styles will be reset back to linear interpolate.

**Comment by mudinthewater** [comment]
This bug first appears with commit 8d21d420ae6a3a706a5bf70a1d823c00888fc0b0 referencing issue #2120

**Comment by larkin** [comment]
Two bugs here:
* adding a telemetry point and then immediately editing plot series options causes the series to get removed from the plot.  
* interpolation style was always set to default (ignored persisted configuration).

2137 fixes both.

Verification steps for various iterations of this:

1. create overlay plot
2. drag and drop telemetry point into overlay plot.
3. edit plot series option (e.g. change interpolation/value/markers). 
4. save plot
5. refresh page, plot should appear correctly.

1. create overlay plot.
2. drag and drop telemetry point into overlay plot.
3. change plot series interpolation to something other than default.
4. save plot.
5. refresh page, plot series should use the interpolation selected in step 3.

1. edit existing overlay plot.
2. change interpolation style.
3. save.
4. refresh page, plot series should use the interpolation selected in step 4.

**Comment by mudinthewater** [comment]
I've deployed the commit with a local database and a couchDB. Line styles persist as selected now.
