### ISSUE TITLE
[notebook] links to annotated entries should include time conductor state

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#2138]
When an annotation is linked to a notebook, the current time conductor time range should be included, such that a user can click the entry and see data at that point in time. 

Requested by various user groups.

**Comment by charlesh88** [comment]
@larkin What is the purpose behind the user request here? The idea was that the annotation serves as the "historic" snapshot, while the link let's the user see what's happening _now_ with the object in the Notebook. I can see utility in allowing exploration in a historic context, of the annotated object plus others beside, but I'd be hesitant to throw out the ability to link to the object "now". Maybe allow both?

My other concern is that there is some nuance to the UI here: if an operator is in RT operations mode, it needs to be very clear that when they are exiting RT mode in the Time Conductor. While this is also a general problem with our bookmarked URLs, adding these clicks into the Notebook potentially exacerbates this problem.

**Comment by larkin** [comment]
The first question I have had from users who see the notebook linking functionality in the existing user is "why isn't that displaying the same data as the screenshot?", because after clicking the link they are showing "now" and not "the context of the entry".  Users from two different missions have said that they expect the links in a notebook entry to operate in the context of the notebook entry -- and not the current time frame.

It's trivial to return to "now" via the time conductor, so I think notebook specific UI to support linking to either "now" or "the time of the entry" would not be DRY.

**Comment by larkin** [comment]
As a side note, if a navigation event causes changes to the time conductor regardless of "realtime" mode, it is probably worth showing a small notification to alert the user to the change.  It could be confusing in any context.

**Comment by mudinthewater** [comment]
@charlesh88 Psyche would really like this.

**Comment by jakeaston** [comment]
Would be great to see this

**Comment by akhenry** [comment]
@nikhilmandlik Let's try and get this done in notebook v2.0 as well. Get everything else for MVP done first though.

**Comment by nikhilmandlik** [comment]
fixed in https://github.com/nasa/openmct/issues/2666
