### ISSUE TITLE
Moving an object should not warn users that it will be permanently removed

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#2141]
Moving an object via context menu gives the user the warning that the object will be permanently removed.  This is scary and incorrect messaging that occurs because Move is implemented as "link" followed by "remove", so the dialog occurs.

![move-gives-remove-error](https://user-images.githubusercontent.com/226503/43872068-8641b97e-9b34-11e8-9de6-ad71c7ee1e0c.gif)

**Comment by dtailor90** [comment]
@larkin - I’ll work on this
