### ISSUE TITLE
Styleguide images unavailable for setup in subdirectory

### ISSUE THREAD

**Issue by Moyaccercchi** [nasa/openmct#2149]
This is my first issue, and my first time contributing to Open MCT - or any open source project at all, so sorry if I got something wrong. =)

I tried to install Open MCT into a subdirectory on my webserver, such that I would call it like this in the browser:

`http://www.awesome-url.com/openmct/index.html`

instead of just

`http://www.awesome-url.com/`

When accessing the style guide, several images are missing - which are present when Open MCT is not started in a subdirectory:

![images_missing](https://user-images.githubusercontent.com/4249570/44114438-7b474d46-a00b-11e8-96bd-f0689a241747.png)

**Comment by Moyaccercchi** [comment]
Hm... I tried creating a local branch with my fix, but don't seem to be allowed to push it to github:
```
git push origin missing-images-2149
Password for 'https://Moyaccercchi@github.com':
remote: Permission to nasa/openmct.git denied to Moyaccercchi.
fatal: unable to access 'https://Moyaccercchi@github.com/nasa/openmct.git/': The requested URL returned error: 403
```

Here is the diff anyway; after all, it seems to be enough to remove the leading slash such that the images are accessed relatively:
```
diff --git a/example/styleguide/res/templates/intro.html b/example/styleguide/res/templates/intro.html
index beba9b9..2cbe267 100644
--- a/example/styleguide/res/templates/intro.html
+++ b/example/styleguide/res/templates/intro.html
@@ -34,7 +34,7 @@
             <p>As you develop plugins for Open MCT, consider how a generalized component might be combined with others when designing to create a
             </div>
             <div class="col">
-                <img src="/example/styleguide/res/images/diagram-objects.svg" />
+                <img src="example/styleguide/res/images/diagram-objects.svg" />
             </div>
         </div>
     </div>
@@ -48,7 +48,7 @@
             <p>The types of objects that a container can hold should be based on the purpose of the container and the views that it affords. For
             </div>
             <div class="col">
-                <img src="/example/styleguide/res/images/diagram-containment.svg" />
+                <img src="example/styleguide/res/images/diagram-containment.svg" />
             </div>
         </div>
     </div>
@@ -60,7 +60,7 @@
                 <p>Views are simply different ways to view the content of a given object. For example, telemetry data could be viewed as a plot o
             </div>
             <div class="col">
-                <img src="/example/styleguide/res/images/diagram-views.svg" />
+                <img src="example/styleguide/res/images/diagram-views.svg" />
             </div>
         </div>
     </div>
```

**Comment by dtailor90** [comment]
Hi,

You don’t access to push directly to the NASA repository. Please fork the repository and push to a branch on your github profile, and create a Pull Request and we can review that way.

Thanks for the contribution! 

Sincerely,

Deep Tailor

**Comment by larkin** [comment]
@Moyaccercchi Thanks for noticing this.  We have resolved this issue in work for #2140 which will change the relative paths for the style guide (among other things).  Will track this against that issue.

**Comment by Moyaccercchi** [comment]
Ah, great - thank you both for your help. =)

**Comment by unlikelyzero** [comment]
Marking as closed
