### ISSUE TITLE
Vue Layout UX Todos

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2172]
For me @charlesh88; related to work by @psarram.
### Actionable
- [x] Add is-selectable, is-moveable, etc. to appropriate elements;
- [x] Style is-selectable, including hover in edit and browse mode;
- [x] `pointer-events: none` on hyperlink/button/summary widget button elements;
- [x] button and Summary Widget need to fill frame when in a Layout frame (browse or edit);
- [x] Fix `no-frame` so it doesn't affect nested frames;

### Blocked
By inconsistent application of `s-selected`; see comment below.
- [ ] Show grid when a nested layout is `s-selected` or is `s-selected-parent`;

**Comment by charlesh88** [comment]
Observed issues/questions:
- When a Layout is nested with another and is selected, `s-selected` is properly applied to `c-frame`. But when it's `no-frame`, selecting it applies that class instead to this element: `<div droppable="true" class="l-layout">`.

**Comment by psarram** [comment]
@charlesh88 I believe the issue with s-selected not being applied to c-frame is fixed. Show grid seems to be working properly in topic-core-refactor as well, so the issue can be closed.
