### ISSUE TITLE
Problem with sending telemetry data to a state generator

### ISSUE THREAD

**Issue by zv-acsat** [nasa/openmct#2176]
I'm a non-English beginner in Open MCT, I can send telemetry data from outside and show it in an example.measurement domain object in open MCT, just like what is said in [tutorials/#telemetry-adapter](https://nasa.github.io/openmct/docs/tutorials/#telemetry-adapter).

![image](https://user-images.githubusercontent.com/43611890/46134820-a66af600-c250-11e8-803a-44090a7c1793.png)

Now I want to change the type to example.state-generator, but is doesn't get value!

![image](https://user-images.githubusercontent.com/43611890/46135209-8982f280-c251-11e8-8e7e-ab1b2a663e6d.png)
 

So, what is the problem with my state-generator? Is there any other information I have to say to clarify my problem?

**Comment by zv-acsat** [comment]
These are the warnings that I get from the page.

![image](https://user-images.githubusercontent.com/43611890/46136830-4dea2780-c255-11e8-97a3-25272ab9b8ed.png)


and this is the red Error at the bottom of the page.

![image](https://user-images.githubusercontent.com/43611890/46137193-fef0c200-c255-11e8-9658-93dac971ea92.png)

**Comment by akhenry** [comment]
@zv-acsat Did you change the corresponding [`supportsRequest`](https://github.com/nasa/openmct-tutorial/blob/1a59c787b468d8aad1bb16ca0a3c0716b79aec07/historical-telemetry-plugin.js#L9) and [`supportsSubscribe`](https://github.com/nasa/openmct-tutorial/blob/1a59c787b468d8aad1bb16ca0a3c0716b79aec07/realtime-telemetry-plugin.js#L18) functions in the telemetry providers?

**Comment by larkin** [comment]
Going to close this due to inactivity.
