### ISSUE TITLE
Vue Time Conductor todos

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2179]
- [x] Remove Zoom control.
- [x] Tick density isn't working as desired. In particular, there are circumstances where the ticks can end up way overcrowded: 
![screen shot 2018-10-02 at 11 10 46 am](https://user-images.githubusercontent.com/1056412/46368045-105e1380-c634-11e8-8692-8628f3377363.png)
![screen shot 2018-10-02 at 11 13 00 am](https://user-images.githubusercontent.com/1056412/46368084-29ff5b00-c634-11e8-844a-efad07c9ec29.png)
- [ ] Date picker needs mobile styling. @charlesh88

**Comment by akhenry** [comment]
@charlesh88 Have pushed a fix for tick density to vue-conductor-style-fixes
