### ISSUE TITLE
Plot Y-axis Scale persistence not loading with plot

### ISSUE THREAD

**Issue by mudinthewater** [nasa/openmct#2182]
Using ca16892237b55856df0691f317b0ba34029b97e4 and CouchDB, plot Y-axis persistence values are being saved to the store, and are being returned from the store on page load (verified by comparing the put payload and the get payload for that object). However, the loaded plot does not appear to act on those values. It will just have y bounds from 0 to 0.

**Comment by larkin** [comment]
@mudinthewater is autoscale active when the plot reloads?

**Comment by mudinthewater** [comment]
@Larkin No it detects the autoscale:false property, just not the bounds of it.

**Comment by akhenry** [comment]
@larkin Any theories on this?

**Comment by larkin** [comment]
Mistake in mutation path: any plots created before the latest changes to the editor were merged would have correct axis, but anything created after that commit was persisting the yAxis range as the wrong property.  the fix (#2208) ensures custom yAxis range is persisted in the correct property.  Will close with #2208.
