### ISSUE TITLE
[Vue] Allow ordering of items in the Create menu

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2207]
With our migration to Vue, we've lost the capability to order items that was a feature previously with #787. This is most important to allow logical grouping of similar object types, such as Display Layout and Flexible Layout, or Clocks and Timers.

We should allow plugins to assign a priority for itself, which will allow us to organize the list logically. Eventually, we should consider categorizing plugins as well, which could allow grouping and a much more clearly organized menu.

Related to #787 and #355.

**Comment by larkin** [comment]
Moving to TCR tracking branch as TODO.
