### ISSUE TITLE
Allow alpha displays in Layouts to include a label element for their field

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2214]
When a user adds a telemetry element as a alphanumeric to a Layout, they can choose from the fields of the element (value, DN, EU, etc.) but the chosen field "type" isn't visibly displayed in the interface. During a review of 11/09/18, Jay would like the ability to display a label that identifies the chosen field type.

**Comment by larkin** [comment]
moving to refactor todo tracker.
