### ISSUE TITLE
CSS overflow-x visible with an element at far right in the demo

### ISSUE THREAD

**Issue by emilfihlman** [nasa/openmct#2217]
In the demo here: https://openmct-demo.herokuapp.com/ linked from https://nasa.github.io/openmct/
It's an older technique and baaad style.

It seems it's only visible when a getting started message is shown in the middle, so not just at the beginning.

Chrome version: 70.0.3538.102
OS: Windows 10

![image](https://user-images.githubusercontent.com/9070088/48348491-30004700-e68a-11e8-9535-62ae093f1660.png)
![image](https://user-images.githubusercontent.com/9070088/48348313-b405ff00-e689-11e8-8402-e581f110336b.png)
![image](https://user-images.githubusercontent.com/9070088/48348251-7a34f880-e689-11e8-8192-c1ff869ae0ad.png)

**Comment by larkin** [comment]
Thanks for the report, have moved this to the proper repository: https://github.com/nasa/openmct-demo/issues/9
