### ISSUE TITLE
Vastly different load times in chrome vs firefox

### ISSUE THREAD

**Issue by mudinthewater** [nasa/openmct#2263]
I'm noticing increased query times in the latest build of chrome that aren't displayed in firefox. 
Chrome version: 71.0.3578.98
Firefox Version: 64.0.2
OS: W10, 1803, 17134.472
OpenMCT hashes I've seen it on: 
ca16892, 9582fb2
Example: 
Plot with 3 channels, roughly 300k points each channel, loaded in firefox and chrome. 
Firefox load time: 10s (mostly transmission - openmct processing time was negligible)
Chrome load time: ~7 minutes

**Comment by larkin** [comment]
Have isolated issue to be specific to Chrome 71, is not present in Chrome 70.  Filed issue and reproduction steps in chromium issue tracker: https://bugs.chromium.org/p/chromium/issues/detail?id=922316

**Comment by mudinthewater** [comment]
Latest version of chrome 73 is much better about this - I'm fine with closing this unless it resurfaces.
