### ISSUE TITLE
Summary Widget editing/saving broken

### ISSUE THREAD

**Issue by plaa** [nasa/openmct#2277]
The Summary Widget editing/saving seems to be completely broken.  Whenever I try to edit a Summary Widget and save it, nothing is saved and the configuration is reverted.

Steps to reproduce:

1. Checkout openmct and `npm install` and `npm start`
2. Create a new Sine Wave Generator telemetry source in My Items
3. Create and save a new Summary Widget in My Items (don’t configure it yet)
4. Open the Summary Widget into editing mode
5. Drag the Sine Wave Generator on the Summary Widget (so you can edit the rules)
6. Open the default rule, and change the label to “Foo”
7. Save and finish editing

Expected: Component configuration is saved

Actual:  Everything is reverted to before save state

When doing the same steps in [the demo environment](https://openmct-demo.herokuapp.com/), it works as expected.

I bisected the issue, and the commit that broke the functionality is e5fe8fd975e "Save As clears transaction while undirtying"

**Comment by akhenry** [comment]
@plaa Thank you very much for reporting this, especially the git bisect to identify the commit! Very helpful. We will try and address this as quickly as possible.
