### ISSUE TITLE
[Plot] Logarithmic axis, log plots

### ISSUE THREAD

**Issue by tadmorgan** [nasa/openmct#2297]
Is it possible to set a plot axis to logarithmic scale?

**Comment by trusktr** [comment]
In progress in https://github.com/nasa/openmct/pull/4710

**Comment by trusktr** [comment]
We have an initial version in the log-plots branch. But some more work needs to be done. A few things we are thinking about:

- intermediary axis ticks are missing, and seeing only 1, 100, 1000, etc, is not useful without unevenly-spaced ticks in between those main ticks.
- what if data has values smaller than 1 (f.e. what if most of the data is below 1 with outliers above 1)? We need a way to multiply the log formula by a fraction (f.e. 0.1) to make it apply to values greater than 0.1 instead of greater than 1, for example.
- what about negative values? we would need to mirror the log formula around its Y axis and/or X axis.
  - Four cases:
    - positive Y values at on X (normal case)
    - positive Y values at on -X
    - positive -Y values at on X
    - positive -Y values at on -X
  - we would want to apply the multiplier in all cases, so that we can change the no-go range (the area where plotting points doesn't make sense) from the default of (-1, 1) to something like (-0.1, 0.1), for example.

**Comment by trusktr** [comment]
Updated playground. All plots toggled off except symmetrical log functions: https://www.desmos.com/calculator/htkxrlto3a

**Comment by trusktr** [comment]
A better one showing symlog, scaled symlog, and scaled antisymlog, with a slider to adjust the scale value: https://www.desmos.com/calculator/2pcxvmsd6y

**Comment by charlesh88** [comment]
Good chat with @trusktr today:

- UI should add a "Use log scale" checkbox to the Inspector "Y Axis" UI section when editing.
- Joe will look into also including a range slider that allows the user to control the log scaling directly, which only appears when the "use" checkbox is checked. This is a stretch goal.
- @charlesh88 will do any front-end sanding and shimming if needed.

**Comment by trusktr** [comment]
#4931 is in. When editing an Overlay Plot, there is now a "Log mode" checkbox that can be enabled in the right sidebar.

Testing:

- make overlay plot
- add sinewave generator (or any other data)
- edit overlay and turn on log mode
- toggle log mode on/off a few times and the plot drawing should visibly toggle between both modes
- save overlay plot in log mode
- refresh the browser and the overlay should still be in log mode and render correctly
- edit overlay, try turning autoscale on/off and ensure that log mode still works
- try zooming in out and panning with permutations of any of the above actions and make sure things work

**Comment by khalidadil** [comment]
I'm seeing an issue in an overlay plot when using a sine wave generator with log mode turned on. If I turn on log mode, save, and refresh, the plot isn't displaying correctly. 
<img width="1316" alt="Screen Shot 2022-04-25 at 4 47 57 PM" src="https://user-images.githubusercontent.com/2343076/165180679-7f3410ca-659b-40d9-aa1a-514814bb4534.png">

I'm seeing this error:
<img width="481" alt="Screen Shot 2022-04-25 at 4 47 42 PM" src="https://user-images.githubusercontent.com/2343076/165180828-69688104-ed7f-4f27-a1df-08d5870fa0b6.png">
<img width="722" alt="Screen Shot 2022-04-25 at 4 49 13 PM" src="https://user-images.githubusercontent.com/2343076/165180859-83869384-b442-4f81-910d-12201e0578a9.png">

**Comment by akhenry** [comment]
We could be doing a better job of formatting y-axis values in log mode. Instead of showing something like this:
![Screen Shot 2022-04-25 at 3 02 23 PM](https://user-images.githubusercontent.com/4215777/165182362-3d5faa8e-dd95-4e7d-a591-ba37848748e5.png)

We should be rounding the y-axis values to the nearest whole number in this case.

**Comment by akhenry** [comment]
@khalidadil Sounds like this issue - https://github.com/nasa/openmct/issues/5039. Which _should_ be fixed, but evidently isn't.

**Comment by khalidadil** [comment]
@akhenry I just checked, and autoscale was turned on for me.

**Comment by charlesh88** [comment]
Verified not fixed Testathon 04-25-22: log scale should not change tick values from fairly compact integers to long floats:
**Log scale off**
![image](https://user-images.githubusercontent.com/1056412/165186912-05615085-fcdd-4548-a358-ef457151a88f.png)

**Log scale on**
![image](https://user-images.githubusercontent.com/1056412/165186947-e0ceb8e2-7671-41a3-9472-46aeca4ad492.png)

**Comment by akhenry** [comment]
@shefalijoshi to investigate https://github.com/nasa/openmct/issues/2297#issuecomment-1109075202

**Comment by shefalijoshi** [comment]
> 

I think maybe we could use toFixed(2) instead of whole numbers? Otherwise if the range of values is small (0-1 for instance) then all the ticks would be either all 0 or all 1 which would be odd.

**Comment by akhenry** [comment]
Verified fixed

**Comment by charlesh88** [comment]
Verified NOT fixed Testathon 4-28-22. Ticks end up being duplicated when the plotted value is < 1.

<img width="218" alt="image" src="https://user-images.githubusercontent.com/1056412/165860258-b3933771-a2d1-4bf0-b5ba-913aa7e57037.png">

**Comment by akhenry** [comment]
Testing Instructions
1. Create an overlay plot
2. Enable log scale
3. Verify that the scale is not causing a loss of precision resulting in repeating scale values as seen in https://github.com/nasa/openmct/issues/2297#issuecomment-1112724445

**important note** This cannot be verified with sine wave generators. SWGs have a custom formatter which will round all values to 2 decimal places. In this case the precision is already lost before the log plots format the values.

**Comment by michaelrogers** [comment]
This change appears to be fixed in testathon 05/02. On inspecting an overlay plot with log scale enabled, the scale values do not repeat and instead show values without clipping the # of decimal places.

**Comment by akhenry** [comment]
Verified fixed.

**Comment by rukmini-bose** [comment]
Confirmed Fixed 05/02. Seeing the same behavior as Michael.
