### ISSUE TITLE
How is NaN/Infinity dealt with?

### ISSUE THREAD

**Issue by tadmorgan** [nasa/openmct#2298]
Is it possible to include IEEE 754 values such as NaN and Infinity in the telemetry? I have a sensor that sometimes outputs NaN and it would be best if I could represent it as such instead of some fake value. My understanding is that the standard JSON parser does not but one such as [JSON5](https://json5.org/) does.

**Comment by dtailor90** [comment]
@tadmorgan  - You can easily write a telemetry adapter and a telemetry formatter to parse JSON5 and represent the data in any way you would like. We have a simple tutorial at [https://github.com/nasa/openmct-tutorial](url). Let me know if you need help with defining the adapter or the formatter.

**Comment by tadmorgan** [comment]
Thanks, will look into it.
