### ISSUE TITLE
Summary Widgets Should work for Recorded Telemetry

### ISSUE THREAD

**Issue by mudinthewater** [nasa/openmct#2347]
Summary widgets seem to only work with realtime telemetry, they generate the correct request for latest data in the timerange provided, but don't appear to updated on that latest data in the recorded context.

**Comment by charlesh88** [comment]
@akhenry We should take a look at this asap.

**Comment by mudinthewater** [comment]
@akhenry I guess it's a matter of interpretation if the request is correct for a recorded context of the widget. 

The options request for a summary widget in recorded context is: 
        options.strategy=undefined
        options.size=1
        options.start=<start_time>
        options.end=<end_time>
        options.domain=<time_type>
    
My interpretation of that on the serverside is to send it the latest telemetry point it could find in that timerange. Of course in realtime, it just gets the latest telemetry point. 

Comparing that to a fixed position display, which does show data in the recorded context: 
        options.strategy=undefined
        options.size=1
        options.start=<start_time>
        options.end=<end_time>
        options.domain=<time_type>

The problem is that in a fixed position display, it's obvious to the user that the fixed position table should display the latest point available in the query range, but for a widget I'm not so sure. 

For recorded data with a summary widget I think what I really want is a way to cycle through all the data in that timerange - almost like an embedded replay functionality for the widget. 

That way if I select my timerange as yesterday->today, I can easily see when the widget was what value. 

That's completely different behavior than current behavior though, so more feature request than bug report.

**Comment by mudinthewater** [comment]
Worth noting that the table associated with the summary widget does work correctly for recorded telemetry.
