### ISSUE TITLE
Easy integration with COSMOS

### ISSUE THREAD

**Issue by davidskeck** [nasa/openmct#2395]
[COSMOS](https://github.com/BallAerospace/COSMOS) is a well-used tool and it would be great to have out-of-the-box integration with OpenMCT. Is there something OpenMCT community could do to support this?

**Comment by akhenry** [comment]
We would love for someone to do an open source plugin for integrating with COSMOS. This would be of huge value to a lot of potential users. If someone wanted to attempt it we would be happy to provide technical support and guidance.

**Comment by davidskeck** [comment]
That's great to hear. Can you tell me if the latest API for OpenMCT has tutorials as of yet? It looks like the OpenMCT tutorial repository hasn't been updated for 2 years.

**Comment by imrishabh18** [comment]
Hey! @akhenry I would like to contribute to this repo and will really appreciate your guidance. Is this a beginner friendly issue to start with?

**Comment by jvigliotta** [comment]
Hello! I'm going to actually move this over to discussions as I think it's a good topic for the Community Q&A
