### ISSUE TITLE
Code that ignores duplicate points for plotting is removing non-duplicate points

### ISSUE THREAD

**Issue by mudinthewater** [nasa/openmct#2404]
Looks like the code that's removing duplicate points before plotting is only checking for duplicate timestamps before removing it and only plotting one. I'm seeing two points that have identical timestamps but different values with one point getting removed and the other plotted. 

Is this the intended behavior?

**Comment by akhenry** [comment]
Closed by https://github.com/nasa/openmct/pull/2515. Did not make it into VISTA-R4.3, but will be in VISTA-R4.3.0. Will also be in Open MCT v1.0.0 in December.
