### ISSUE TITLE
Creating vectors with data coming in?

### ISSUE THREAD

**Issue by mauricerivers** [nasa/openmct#2415]
Hello, 

Is there a way that we can take 3 different telemetry objects (ex: Mag X, Mag Y, Mag Z), and create a vector out of their data using any of the tools available in OpenMCT?

Is this possible through a plug-in, built-in function, or any of the options in the Create menu?

Thanks.

**Comment by deeptailor** [comment]
Hi @mauricerivers, we currently do not have a plugin to create vectors. 

Building a simple plugin to accomplish what you need should not be too hard with out plugin API. Let me know if you need help with regards to that.

**Comment by mauricerivers** [comment]
@deeptailor I could use the help for the upcoming LightSail Mission on June 24th
