### ISSUE TITLE
Inconsistent file naming convention

### ISSUE THREAD

**Issue by psarram** [nasa/openmct#2433]
The naming convention for files in Open MCT is PascalCase. At least majority of the files follow that convention in the master branch. However, after rewriting the components using the vue framework in topic-core-refactor, the file names follow different styles, including camelCase, PascalCase and kebab-case.

**Comment by akhenry** [comment]
Totally agree, we need to stick to a standard. We should probably review the coding standard with the current team and see if there are any changes we'd like to make. Let's schedule for early next release.

**Comment by depperm** [comment]
linting from #5216 should resolve

**Comment by unlikelyzero** [comment]
@depperm thanks
