### ISSUE TITLE
Build fails with Node 12

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#2446]
The Open MCT build is currently failing with Node 12 [due to an incompatibility with Gulp 3](https://github.com/gulpjs/gulp/issues/2324) with the error below:

```
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
```

For right now the workaround is to use an earlier version of Node JS. Since we will soon be replacing Gulp with Webpack there is no intention to upgrade to Gulp 3.

**Comment by MarkCodering** [comment]
Copy that, so which version of Node.js is suitable for the installation the most?

**Comment by akhenry** [comment]
@MarkCodering As of today if you pull from master and run the build it should work with Node 12

**Comment by akhenry** [comment]
@MarkCodering I would suggest doing a completely fresh install (eg. clear your node_modules directory). The dependencies have changed a lot, and the build system is now completely different (Webpack instead of Gulp)
