### ISSUE TITLE
Build fails with 'esprima' error due to change in dependency

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#2447]
During the optimization step, the build will fail with the following error message:
```
{ Error: Parse error using esprima for file: /Users/akhenry/Code/openmct-master/node_modules/painterro/build/painterro.min.js
Error: Line 258: Unexpected token *
```

This is due to a change in the `isMobile` dependency which itself is a dependency of `painterro`. It appears to contain characters that cause the version of the RequireJS optimizer we are using to fail.

**Comment by ivictbor** [comment]
@akhenry Hello, just FYI in painterro v1.0.23 I updated `isMobile` to 1.0.x major, https://github.com/devforth/painterro/commit/af96b0caf2cbed8b2ff7cba282044e2c45e386d9
probably it could fix it.

If not, we might ask @kaimallea (isMobile author) directly.
Also Painterro v1.0.x includes sevaral major Text/Zoom features, API improvements, arrow tool, so would be nice to try
