### ISSUE TITLE
[Tables] Clicking a selected table row causes the entire table to refresh, losing selection

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2456]
When single-clicking, shift-clicking or cmd-clicking to select rows in a table, clicking any selected row (without or with any key modifier pressed) causes the entire table to reload, and all selection to be lost. The current behavior for clicking to select with the Shift and Cmd keys is excellent and doesn't need changing.

Given a starting state of one or more selected rows, expected behavior is as follows:
1. Clicking any already selected row without any key modifiers or while holding the shift key should do nothing. 
1. Clicking any already selected row while holding the Cmd key will deselect the currently selected single row. This applies to any combination of shift-selected or previously discontinuously (Cmd-clicked) selected rows. 

Examples:
1. Select a single row, then Cmd-click it. Result: no rows are selected. *Table may be auto-unpaused, but if that adds a lot of effort to this fix, let's leave the table paused.*
1. Select a continuous set of rows by holding the Shift key. Cmd-click any selected row in the selected set. Result: the clicked row is de-selected, but all other rows remain selected and the table remains paused.
1. Select a discontinuous set of rows by holding the Cmd key. Cmd-click any selected row in the selected set. Result: the clicked row is de-selected, but all other rows remain selected and the table remains paused.

**Comment by charlesh88** [comment]
@charlesh88 to rewrite relevant VISTA test case for this feature.

**Comment by deeptailor** [comment]
Closing as FIXED
