### ISSUE TITLE
Inline editing a view object's name allows an empty string

### ISSUE THREAD

**Issue by psarram** [nasa/openmct#2457]
1. Create an object and save it with the default name. 
2. Bring the mouse to the name and click the text box. Delete the name and hit enter. 
3. The object now has no name both in the main view and in the tree. 
4. Click on the arrow icon next to the object icon in the main view and click on `Edit Properties`. Enter a name and hit OK.
6. The new object name is displayed in the tree but not in the main view.
7. Clicking on any object in the tree will show that object with no name in the main view.

**Comment by charlesh88** [comment]
Desired behavior: while inline editing the object's name, attempting to blank out the field should result in the change being ignored and the original name being reapplied.

**Comment by charlesh88** [comment]
@deeptailor has a fix in for PR.

**Comment by akhenry** [comment]
Fixed by https://github.com/nasa/openmct/pull/2461
