### ISSUE TITLE
Plot Y Axis value select is causing visual problems

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2464]
The plot Y axis value select, when present, is causing visual and overflow scroll problems a plot view is very vertically constrained such as in a layout or when many telemetry items are added to a Stacked Plot. The user must be afforded a control to select the value to be used as the axis label without that control causing such issues.

**Comment by akhenry** [comment]
Fixed by https://github.com/nasa/openmct/pull/2465
