### ISSUE TITLE
[Build] No index.html in dist folder after npm run prepare

### ISSUE THREAD

**Issue by JohanWinther** [nasa/openmct#2476]
### There is no `index.html` in the `dist` folder after building.

I have done the following steps:

1. Cloned the repo from GitHub
2. `npm install`
3. `npm run prepare`

However checking the `dist` folder there is no `index.html` file. Only these are present:
```
dist
│   openmct.js
│   openmct.js.map
│
├───example
│   ├───mobile
│   │   └───res
│   │       └───css
│   │               mobile-example.css
│   │               mobile-example.css.map
│   │
│   └───styleguide
│       └───res
│           ├───css
│           │       style-guide-espresso.css
│           │       style-guide-espresso.css.map
│           │       style-guide-snow.css
│           │       style-guide-snow.css.map
│           │
│           └───images
│                   diagram-containment.svg
│                   diagram-objects.svg
│                   diagram-views.svg
│
└───platform
    ├───commonUI
    │   ├───general
    │   │   └───res
    │   │       ├───css
    │   │       │       normalize.min.css
    │   │       │       openmct.css
    │   │       │       openmct.css.map
    │   │       │       reset.css
    │   │       │       startup-base.css
    │   │       │       startup-base.css.map
    │   │       │
    │   │       ├───fonts
    │   │       │   └───symbols
    │   │       │           openmct-symbols-12px.eot
    │   │       │           openmct-symbols-12px.svg
    │   │       │           openmct-symbols-12px.ttf
    │   │       │           openmct-symbols-12px.woff
    │   │       │           openmct-symbols-16px.eot
    │   │       │           openmct-symbols-16px.svg
    │   │       │           openmct-symbols-16px.ttf
    │   │       │           openmct-symbols-16px.woff
    │   │       │
    │   │       └───images
    │   │           │   logo-app-shdw.svg
    │   │           │   logo-app.svg
    │   │           │   logo-nasa.svg
    │   │           │
    │   │           └───favicons
    │   │                   favicon-16x16.png
    │   │                   favicon-32x32.png
    │   │                   favicon-96x96.png
    │   │                   favicon.ico
    │   │
    │   └───themes
    │       ├───espresso
    │       │   └───res
    │       │       └───css
    │       │               theme-espresso.css
    │       │               theme-espresso.css.map
    │       │
    │       └───snow
    │           └───res
    │               └───css
    │                       theme-snow.css
    │                       theme-snow.css.map
    │
    └───features
        ├───conductor
        │   └───core
        │       └───res
        │           └───css
        │                   time-conductor-espresso.css
        │                   time-conductor-espresso.css.map
        │                   time-conductor-snow.css
        │                   time-conductor-snow.css.map
        │
        ├───notebook
        │   └───res
        │       └───css
        │               notebook-espresso.css
        │               notebook-espresso.css.map
        │               notebook-snow.css
        │               notebook-snow.css.map
        │               notebook.css
        │               notebook.css.map
        │
        └───table
            └───res
                └───css
                        table.css
                        table.css.map
```

I plan on using Open MCT for my project and deploy it by uploading the `dist` folder to a remote server (GitHub Pages). This issue seems to keep me from doing that.

Running a local development server with `npm start` works perfectly well.

OS: Windows 10 64 bit
node v11.10.0
npm v6.7.0

**Comment by akhenry** [comment]
Hi Johan,

Thanks for your email. Great to hear you're using Open MCT! We'd love you hear a bit more about your project if you're able to share any information with us?

We don't build a default index.html because to do anything useful with Open MCT you're going to create a custom index.html anyway. You'll need to install custom plugins (such as telemetry adapters, object providers, etc.) to integrate it with your own telemetry sources and a lot of users will want to disable local storage, and use a distributed document store like Couch DB.

I'd recommend building a custom index.html (based on the one provided in the source directory) and integrating that into your build process so that you can push it to gh-pages.

Andrew

________________________________

**Comment by JohanWinther** [comment]
> Thanks for your email. Great to hear you're using Open MCT! We'd love you hear a bit more about your project if you're able to share any information with us?

My plan is to use Open MCT as a home automation/IoT dashboard (project can be found [here](JohanWinther/home-automation)).

>I'd recommend building a custom index.html (based on the one provided in the source directory) and integrating that into your build process so that you can push it to gh-pages.

I assume that I should write my own index.html, but I don't know how to include it in the build process.

**Comment by mudinthewater** [comment]
@JohanWinther I personally just copy it into dist and leave it there once I've generated it. It almost never needs to be changed.

**Comment by JohanWinther** [comment]
@mudinthewater Thanks for the tip!
