### ISSUE TITLE
Search resets tree browse context

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2484]
Interacting with Search collapses all currently open nodes in the tree.

<img width="297" alt="Screen Shot 2019-09-13 at 3 10 27 PM" src="https://user-images.githubusercontent.com/1056412/64897557-ba159500-d638-11e9-8d8f-74468d5bad02.png">
<img width="299" alt="Screen Shot 2019-09-13 at 3 10 45 PM" src="https://user-images.githubusercontent.com/1056412/64897558-ba159500-d638-11e9-83ae-e2619dc122a8.png">
<img width="299" alt="Screen Shot 2019-09-13 at 3 10 55 PM" src="https://user-images.githubusercontent.com/1056412/64897559-ba159500-d638-11e9-8d89-d0554db15e23.png">

If the user has spent time drilling down through the tree to find something of interest, this is quite a punishment for interacting with Search. Instead, the tree context should be preserved. 

Suggest hiding the Browse tree DOM element when searching, and displaying Search results in a new DOM element. When Search is done, simply reshow the Browse DOM element.

**Comment by deeptailor** [comment]
@charlesh88 - Agreed, should not be too hard to implement

**Comment by deeptailor** [comment]
fix in PR #2512

**Comment by akhenry** [comment]
Fixed by https://github.com/nasa/openmct/pull/2512

**Comment by charlesh88** [comment]
Verified fixed 12-06-19.
