### ISSUE TITLE
[Plot] Y axis label is not displayed when editing

### ISSUE THREAD

**Issue by psarram** [nasa/openmct#2487]
Edit a plot and set a Y axis label in the inspector. The label doesn't show next to the Y axis. Save and refresh. The label shows up.

**Comment by psarram** [comment]
Also, when dragging a channel, the label text field is populated with a value but it doesn't show next to the Y axis until after the plot is saved and switched to browse mode.

**Comment by charlesh88** [comment]
@nikhilmandlik to have a look at this with @psarram and @charlesh88.

**Comment by charlesh88** [comment]
And also: 
1. Edit a plot and enter a label for Y axis in the inspector.
2. Either hit enter or save and continue.
3. Remove the label.
4. Save and exit.
5. The label reads 'Not defined'

**Comment by charlesh88** [comment]
Desired solution: the user shouldn’t be allowed to blank the label out. It should be like inline editing the title of an object: blanking the field restores whatever the last value for the axis label was (either the default, or a user-entered value) in the editing UI, which means the object can never be saved with a blank value.

**Comment by nikhilmandlik** [comment]
Fixed in https://github.com/nasa/openmct/pull/2492, closing
