### ISSUE TITLE
Summary Widget Rule conditions not persisting values

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2491]
When defining a rule condition that evaluates a value (greater than, less than, etc.) the numeric or string values entered do not persist.

Enter values:
<img width="863" alt="Screen Shot 2019-09-17 at 10 54 03 AM" src="https://user-images.githubusercontent.com/1056412/65066666-a8363980-d939-11e9-9f72-b5f3f6abf9d5.png">

Save the widget and exit to browse mode, then edit it again. Observe: values are not persisted. 
<img width="892" alt="Screen Shot 2019-09-17 at 10 54 21 AM" src="https://user-images.githubusercontent.com/1056412/65066670-abc9c080-d939-11e9-8d27-e4ec36b35edd.png">

This is happening for both numeric and string comparison values. No console errors are being thrown.

Could be related to #2411.

**Comment by charlesh88** [comment]
@nikhilmandlik Just looked at this locally via branch `summary-widget-new-condition-reset` and that branch appears to fix the problem for numerics, but string comparisons aren't persisted, and are actually replaced with the value 0.

Initial state:
<img width="706" alt="Screen Shot 2019-09-17 at 11 10 45 AM" src="https://user-images.githubusercontent.com/1056412/65067660-dae13180-d93b-11e9-9b5d-20ce5f0aad13.png">

Save, then go back in and edit:
<img width="702" alt="Screen Shot 2019-09-17 at 11 11 00 AM" src="https://user-images.githubusercontent.com/1056412/65067671-e5033000-d93b-11e9-8d26-3b9bad130fab.png">

**Comment by nikhilmandlik** [comment]
@charlesh88 please check following commit for fix https://github.com/nasa/openmct/commit/c7a940149eb83138a908b1cd4c9fdb05f41ab564
