### ISSUE TITLE
Summary Widget move grippys not displaying move cursor

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2494]
And also getting shrunk. 

<img width="196" alt="Screen Shot 2019-09-17 at 2 20 22 PM" src="https://user-images.githubusercontent.com/1056412/65080646-a6c73a00-d956-11e9-97a3-63c2203905b0.png">

Fix:
<img width="232" alt="Screen Shot 2019-09-17 at 2 22 28 PM" src="https://user-images.githubusercontent.com/1056412/65080645-a6c73a00-d956-11e9-93dd-2c574f9c6a15.png">

**Comment by charlesh88** [comment]
Fixed in `vista-fixes-4`

**Comment by deeptailor** [comment]
fixed in pr #2499
