### ISSUE TITLE
Overflow scroll broken in Summary Widgets

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2495]
The Rules holder should be handling overflow, but isn't. User can still access all controls, nothing is hidden. 

<img width="1271" alt="Screen Shot 2019-09-17 at 2 37 34 PM" src="https://user-images.githubusercontent.com/1056412/65081544-b5165580-d958-11e9-92ea-656f18ee98ec.png">

**Comment by charlesh88** [comment]
Solution: 
<img width="273" alt="Screen Shot 2019-09-17 at 2 40 57 PM" src="https://user-images.githubusercontent.com/1056412/65081751-37067e80-d959-11e9-9e95-2eab4239d84e.png">

**Comment by charlesh88** [comment]
Fixed in `vista-fixes-4`.

**Comment by deeptailor** [comment]
fixed in pr #2499
