### ISSUE TITLE
[Theme] Restore theme plugins

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#2507]
During the refactoring of our build process the ability to select themes was effectively lost. Applying a different theme right now involves modifying [sass-base.scss](https://github.com/nasa/openmct/blob/c054914a9ce22988f5904d6e5610091238b24c0b/src/styles/sass-base.scss) and recompiling openmct.

Previously themes could be [installed as plugins]() and I think that this is the right approach to carry forward. In future it should be possible for developers to define and install their own plugins. I think that what this looks like is some scaffolding styles that define the scaffolding of the application (layout fundamentals etc.) with the ability to customize the look and feel using a theme.

Right now I'm not sure what the best approach is for achieving this with our current build process and I think that the initial task here is to spend a little time doing some research and prototyping to propose a path forward. 

One option would be to reconfigure webpack to produce a base css file + a css file for each theme. Themes could then be "installed" via a plugin that simply adds a given stylesheet to the DOM. In the future, third party developers would be provided with a styleguide that covers theming and details how to define a new theme and use the same plugin mechanism to install and apply their custom theme.

**Comment by mudinthewater** [comment]
Just want to pipe in here and mention that I've had multiple missions change their themes post-delivery and maintaining theme changes as a plugin is the only way that's possible.

**Comment by akhenry** [comment]
@mudinthewater Yup, it's definitely a priority to restore this behavior.

**Comment by akhenry** [comment]
Based on conversations with @charlesh88 base css file + theme specific css file is not an option. The only solution that seems possible right now is to have webpack produce a single CSS file for each theme. 

How to achieve this with Webpack is not clear right now though, especially given that our Vue single file components are [importing theme constants](https://github.com/nasa/openmct/blob/72e382c46af4968cbc488cdf5e429540009b19bf/src/plugins/telemetryTable/components/table.vue#L155) that are determined at build time. For anyone interested in taking a look at this, the entry point for our SASS styles is core.scss, [which is included from MCT.js](https://github.com/nasa/openmct/blob/72e382c46af4968cbc488cdf5e429540009b19bf/src/MCT.js#L41). core.scss [includes sass-base.scss](https://github.com/nasa/openmct/blob/72e382c46af4968cbc488cdf5e429540009b19bf/src/styles/core.scss#L24), in which the current theme is configured. Right now this is done manually by [including the appropriate theme constants file](https://github.com/nasa/openmct/blob/72e382c46af4968cbc488cdf5e429540009b19bf/src/styles/sass-base.scss#L29) prior to the build.

A brute force approach here would be to parameterize the theme constants file name, and define a new npm 'script' that invokes the Webpack build multiple times, changing the parameterized theme name each time. If that works, it's not ideal, but it unblocks us for right now. The intention is to start distributing Open MCT as prebuilt binaries via NPM, so it no longer require users to build it from scratch, so the build time is not that important.

**Comment by mudinthewater** [comment]
@akhenry I'm not worried about delays unless they _really_ start adding up.

**Comment by akhenry** [comment]
@mudinthewater Delays as in slower build times?

**Comment by mudinthewater** [comment]
Yep - while some of my sites could probably transition to a pre-built, I still expect to be building my own as I have in the past pretty frequently.

**Comment by akhenry** [comment]
@mudinthewater Got it. Thanks for the the feedback!

**Comment by akhenry** [comment]
@nikhilmandlik Can we get some quick testing notes on this issue please?

**Comment by charlesh88** [comment]
Testathon 12/11/19: changed installed theme from Espresso to Snow in index.html and reloaded. Snow theme loaded as expected. Verified fixed.

**Comment by akhenry** [comment]
Verified fixed 12/11/19
