### ISSUE TITLE
[Examples] Define default compositions for the open source project

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#252]
Some default compositions should be defined that demonstrate all of the components of OpenMCTWeb (including those ported across in #207 ). One of these compositions should be selected by default as a 'home' screen so that a user deploying the software for the first time will see a telemetry layout immediately on browsing to the application, rather than a blank screen and a blank display.
#### Notes
- Suggest that an optional example bundle is created that populates the object tree with some default objects and compositions, and routes the user to a 'home' screen by default.
- This will require some example data. A [separate issue](https://github.com/nasa/openmctweb/issues/253) has been created for this.

**Comment by larkin** [comment]
Closed, implemented in https://github.com/nasa/openmct-demo
