### ISSUE TITLE
[Examples] Integrate with public data sources for demonstrating OpenMCTWeb functionality

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#253]
The open source project needs some data that can be used to demonstrate the functionality of OpenMCTWeb. The easiest option here might be to integrate with existing public data sources. There are several options here, including live ISS data, historical MSL science data, space weather, or even data from non-space domains.

Once available, the integration with public data sources should be used in some default compositions created in task #252
#### Notes
- There is a branch that integrates MSL REMS data from a public source, which could be used as a starting point - [https://github.com/nasa/openmctweb/tree/rems_data]() . Ideally this could be extended to include image telemetry from MSL's navcam and/or hazcam - [http://mars.nasa.gov/msl/multimedia/raw/]() . There are also activity plans and other data publicly available that could potentially be scraped, eg. [https://an.rsl.wustl.edu/msl/mslbrowser/planActivity.aspx?s=438]()
- Any integration with public data sources should be implemented in optional bundles
- Links to MSL public data: 
  - [https://an.rsl.wustl.edu/msl/mslbrowser/]()
  - [http://curiosityrover.com/]()

**Comment by akhenry** [comment]
Suggest we limit scope for now to cleaning up and merging https://github.com/nasa/openmctweb/tree/rems_data. This will require minimal effort, and could be targeted for Baxter (though there's no immediate need to do it within this release). Have created #359 to track this.

I'd like to do further work in the future to integrate additional open data sources, so I'd like to keep this ticket open, but de-scope it for Baxter. In particular, real-time or 'real-time' sources. The REMS data is purely historical, which is not really the primary use case for OpenMCTWeb.

**Comment by larkin** [comment]
closed, fixed
