### ISSUE TITLE
Table view search would be more useful if there was a regular expression implementation

### ISSUE THREAD

**Issue by mudinthewater** [nasa/openmct#2534]
User feedback would appreciate the ability to specify value >50 or !string or some other form of search within table views. Exports of the view would then be limited by the search, allowing simple analysis.

**Comment by deeptailor** [comment]
@mudinthewater - This is a great suggestion. I will add it on our list of feature requests

**Comment by nikhilmandlik** [comment]
Verified Fixed.
Tested using,
1./[a-zA-Z]/
2. ^0.81
etc...
