### ISSUE TITLE
Error running 'npm install' on Windows

### ISSUE THREAD

**Issue by ageofabenius** [nasa/openmct#2536]
When running 'npm install', for the topic-core-refactor branch (with the following in package.json: "openmct": "git://github.com/nasa/openmct.git#topic-core-refactor") the following error is received:

"'NODE_ENV' is not recognized..."

Running 'npm install' in a Linux subsystem shell on the same Windows machine worked fine.  The line "NODE_ENV=production webpack" is causing it, according to this [stackoverflow thread](https://stackoverflow.com/questions/11928013/node-env-is-not-recognized-as-an-internal-or-external-command-operable-comman) the issue is due to Windows needing a "SET NODE_ENV..." command.

**Comment by akhenry** [comment]
Good catch, we should avoid using OS-specific commands. We will have to find a cross-platform way of achieving this. Ideally without relying on an additional `npm` package.

**Comment by unlikelyzero** [comment]
This was implemented at some point
