### ISSUE TITLE
'isEditing' should be removed from ViewProvider.view(...) arguments

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#2537]
In the [View API](https://github.com/nasa/openmct/blob/topic-core-refactor/src/ui/registries/ViewRegistry.js), ["View Providers"](https://github.com/nasa/openmct/blob/527c5ec7dde82f5313fcad729a73e7304074394b/src/ui/registries/ViewRegistry.js#L209) are factory classes that instantiate "View" objects by invoking the `view` function.

Currently `ViewProvider.view()` accepts three arguments - `domainObject`, `isEditing`, and `objectPath`. The `isEditing` argument is superfluous and should be removed. The argument is intended to inform views whether or not the application is in edit mode. However, view providers can optionally implement an `edit` function if the ViewProvider needs different logic for browse and edit modes. Moreover, when `View.show()` is invoked on the view returned by `ViewProvider.view()`, the `isEditing` argument is also provided at this point. As such, the `isEditing` argument provided to `ViewProvider.view()` is completely superfluous.

After removing the argument from the API it will be necessary to also search for any usage of it in Open MCT, and remove/refactor as necessary. It is invoked from `ObjectView.vue`, as well as all of the view providers defined in Open MCT. Search for `objectViews.addProvider` to find everywhere that a View Provider is being registered. 

I don't believe that this argument is actually being used anywhere. If you do find instances where it's being used, please highlight these and let's discuss.

In addition to Open MCT, there are various plugins in VISTA, and NIRVSS that are defining view providers that may also need to have this argument removed.

**Comment by akhenry** [comment]
assigned to @shefalijoshi

**Comment by deeptailor** [comment]
@shefalijoshi - was this fix merged? If it was, can you label it as unverified and close the issue.
