### ISSUE TITLE
[UI] Refactor DialogService to allow dismissal of specific dialog instances

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#254]
The dismiss() method on the DialogService is not connected to the specific dialog previously displayed and creates the opportunity for unusual behavior. I'm picturing some other blocking dialog being implemented in the same way (show the dialog on one event, dismiss it on another); if this were triggered at the same time as this dialog, then it would be very easy to dismiss the wrong dialog.

My thinking is that showBlockingMessage should return something that allows the specific dialog that was just shown to be dismissed. Either an object with a dismiss method, or perhaps just a promise that we could pass into a dialogService.cancel(promise) function (this would allow the other dialogService methods to also be cancelled consistently)

**Comment by akhenry** [comment]
## Note to testers
This change affects many modal dialogs in the system. In particular the way that they are dismissed both by the user and by automatic processes. Be on the lookout in particular for any popup dialogs that cannot be dismissed.

Examples of modal dialogs in the system include
1. Notifications list. This popup is available from an indicator at the bottom of the application. The indicator is represented by a bell icon, and is available, for example, after a successful copy operation. Clicking on the icon will launch the popup. If working correctly, then once launched clicking the X at the top should dismiss it.
1. The save progress indicator. This is a new indicator that appears briefly when an object is saved after editing. If working correctly the dialog should appear briefly while saving and disappear quickly when the object is successfully saved.

**Comment by VWoeltjen** [comment]
Tested in VISTA, testathon 2016-07-18, no observed issues with dialogs when duplicating or saving

**Comment by charlesh88** [comment]
Testathon 2016-07-18 Verified fixed, via duping an object, displaying the "Messages" overlay, and dismissing it via the close "X" button in upper right.

**Comment by charlesh88** [comment]
Testathon 08-08-2016: @akhenry Looks like we verified this 7/18 - should we remove the "unverified" label? I just tried verifying via the method above and didn't see any issues.
