### ISSUE TITLE
[Elements Pool] Element not removed when in edit mode

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#2547]
When Element is removed from the elements pool while in edit mode, the element is still available until we click on save and finish.

User's should not be able to see the removed element (once they removed it) until unless they click on cancel edit and revert the changes.

**Comment by toveroox** [comment]
@deeptailor, just sent you a note asking for help with Open MCT setup.  I followed all the steps listed, installed all the dependencies and still can't get MCT to run.  Appreciate any help you can offer.  olga

**Comment by davetsay** [comment]
Resolved by #3799.

**Comment by davetsay** [comment]
> @deeptailor, just sent you a note asking for help with Open MCT setup. I followed all the steps listed, installed all the dependencies and still can't get MCT to run. Appreciate any help you can offer. olga

@toveroox , sorry that you didn't get a response to this. If you are still having issues with installing and running Open MCT can you create a new issue listing specifics?
