### ISSUE TITLE
Inspector layout adversely affected by pre-wrap

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2557]
Seen in latest TCR branch today. Linting may have surfaced a bad CSS layout choice to use `whitespace: pre-wrap`:

![Screen Shot 2019-12-05 at 10 31 35 AM](https://user-images.githubusercontent.com/1056412/70263211-aadf4880-174a-11ea-913d-eef6b28c9170.png)
![Screen Shot 2019-12-05 at 10 33 47 AM](https://user-images.githubusercontent.com/1056412/70263256-c0547280-174a-11ea-9fd9-65ab726131ab.png)
A simple solution here may just be to remove the whitespace style declaration.

**Comment by charlesh88** [comment]
Testing notes: 
1. Nav to any object in the tree.
1. Observe: values displayed in the Inspector should be easily readable and laid out in a space-saving compact fashion, and not exhibit unexpected line breaks as in the image at the top of this issue.

**Comment by charlesh88** [comment]
Testathon 12/11/19: verified fixed.

**Comment by akhenry** [comment]
Verified fixed 12/11/19
