### ISSUE TITLE
[Notebook] Entry styling is broken

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#2577]
Notebook entries look whacky. See screenshot below:

![image](https://user-images.githubusercontent.com/13260688/70667470-d0c28c80-1c25-11ea-9c07-be5316d2e3a4.png)

**Comment by charlesh88** [comment]
Notebook CSS was missing.

**Comment by charlesh88** [comment]
Testathon 12/11/19: verified fixed.
