### ISSUE TITLE
Link Arduino Device(s) with NASA OpenMCT

### ISSUE THREAD

**Issue by MarkCodering** [nasa/openmct#2581]
Hello there,

I am currently building a school project. The project uses OpenMCT as mission control software to monitor the data sent from the Arduino board via WiFi. Therefore, I would like to ask the following questions.
- It is possible to link the Arduino board or sent the data to OpenMCT?
->No, why?
->Yes, how to do this? (It there has any steps or instruction to do this?)

My system environment:
Hardware (Computing)
-> Arduino Uno Board
-> HP Z Mobile Station (Windows 10 Pro) (System information is attached to the file named '' BI 0 '')

Hardware (Communication)
-> Wifi Module (Arduino)

Software (Installed)
-> Git (Able to execute ''git clone'')
-> Node.js (Vesion: 11)
![BI 0](https://user-images.githubusercontent.com/58692435/70677811-3157d500-1ccb-11ea-98c2-3dfe2dcd4a1d.PNG)

Thanks a lot for your guidance!!

Mark

**Comment by MarkCodering** [comment]
I have now completed the development procedure planning. And, the architecture goes like the following:

Data Flow (From the Top to the Bottom) [Linker]; - (location)
*TOP
- Sensors
-[SDA,SLA]- ECM
---------------------------------------------[WiFi Linker]
-[WiFi]- Mission Control Data Receiver (ECDR)
-[Serial Communication]- Mission Control Computer (ECC)
---------------------------------------------[Internal Communication]
-[Serial port (Web-Socket Protocol)]- Node.js Local Server (Important!!)
-[get Serial port Data]- JavaScript (Important!!)
-[Read Serial port data from JavaScript to Open MCT]- an HTML page (Complex layout, difficult!!)
/Bottom

Development Procedure
- Rocker to ECDR Communication
- ECDR TO ECC Communication
- ECC TO Node.js Local Server (via Web-Socket Protocol)
- Depth Communication (get Serial Data from Node.js Local Server on JavaScript)
- Depth Communication (get Serial Data from JavaScript to HTML page)
- HTML Page Configuration
- Function Test

And, now I will send serial data to the local server 8080. But, how to write the code to receive the serial data from the local server to Open MCT's javascript. And, display the data on the HTML page. 
- What specific code do I need to find and modify in the OpenMCT folder because the tutorial document doesn't match the current Open MCT framework?

**Comment by refaat100** [comment]
you could implement the server-side with node and it through the data after processing to openmct,

**Comment by MarkCodering** [comment]
I understand the concept. But, is there has any specific way to configure the node.js local server to receive serial data? The serial port function may be possible to achieve. But, where I can configure the node.js. I can not find a specific file to do so. 

Thanks for your response.

Mark.
