### ISSUE TITLE
openmct build problem

### ISSUE THREAD

**Issue by rchimiak** [nasa/openmct#2604]
I am trying to install openmct-tutorial on my Windows 10 platform with Node.js 12.13.0 and get the following error following  npm install:

ERROR in ./src/plugins/themes/espresso-theme.scss
npm ERR! prepareGitDep Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
npm ERR! prepareGitDep ModuleBuildError: Module build failed (from ./node_modules/fast-sass-loader/lib/index.js):
npm ERR! prepareGitDep Error: import file cannot be resolved: "@import "~styles/vendor/normalize-min";"
and a few more similar errors

The tilde included in the src/plugins/themes/*.scss files seems to be the problem.  Please advise

**Comment by MarkCodering** [comment]
The openmct build fails with node.js version 12. You should try version 11 or earlier.

**Comment by rchimiak** [comment]
The openmct build fails with node.js version 11 and node.js version10 with the same error as was with version 12:
Entrypoint maelstromTheme = maelstromTheme.js maelstromTheme.js.map

ERROR in ./src/plugins/themes/espresso-theme.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/fast-sass-loader/lib/index.js):
Error: import file cannot be resolved: "@import "~styles/vendor/normalize-min";
---
ERROR in ./src/plugins/themes/maelstrom-theme.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/fast-sass-loader/lib/index.js):
Error: import file cannot be resolved: "@import "~styles/vendor/normalize-min";

and a few more

**Comment by LDercher** [comment]
I have the same problem. I tried building with node.js version 8, 10, and 11. If I find a solution, I'll post it here.

**Comment by LDercher** [comment]
My work around for this was to replace these imports in the scss files "@import "~styles/vendor/normalize-min" with "@import "../../styles/vendor/normalize-min".

**Comment by Srokap** [comment]
This problem seems to be Windows-specific. Looks like Windows doesn't like `~styles` notation for paths. Changing import to relative seems to help.

**Comment by Myprecious-Ring** [comment]
> 
> 
> This problem seems to be Windows-specific. Looks like Windows doesn't like `~styles` notation for paths. Changing import to relative seems to help.

Hey Man,666!

**Comment by akhenry** [comment]
Thanks for reporting this everyone, we're looking into this issue. 

@KhaledSharif Thanks for the PR! I think relative paths should be fine, let me just do some experimentation in our various deployment configurations.

**Comment by Srokap** [comment]
Once ready to close this issue, we could close #2721 and #2563 too.

**Comment by egmed** [comment]
> Thanks for reporting this everyone, we're looking into this issue.
> 
> @KhaledSharif Thanks for the PR! I think relative paths should be fine, let me just do some experimentation in our various deployment configurations.

FYI: one is not able to install [openMct tutorial ](https://github.com/nasa/openmct-tutorial) for the same reason.

**Comment by akhenry** [comment]
@shefalijoshi Would you mind picking this up and seeing what we can do to get this merged? I believe that the underlying problem is actually in the sass loader we're using, so there may also be an alternative that actually works with windows.

If there isn't an alternative loader that works, then [there is a PR](https://github.com/nasa/openmct/pull/2670) that uses relative paths. I'm ok with this approach, but we should get @charlesh88 's feedback as well.

**Comment by MarkCodering** [comment]
> I have the same problem. I tried building with node.js version 8, 10, and 11. If I find a solution, I'll post it here.

It doesn't work. I have tried it for serval times

**Comment by MarkCodering** [comment]
Is there have any solution for it? I can not build-up the openmct with node.js version (12,11,10,8,6). Thanks a lot for the resolutions
