### ISSUE TITLE
Notebook drag-and-drop has problems

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2619]
Seen running latest master branch locally today. 

1. Dragging and dropping a domain object onto a Notebook's new entry area (the pale blue area at the top of every Notebook, with the plus symbol)

<img width="608" alt="Screen Shot 2020-01-10 at 4 16 27 PM" src="https://user-images.githubusercontent.com/1056412/72194908-9b47c500-33c4-11ea-9839-eec8f62de332.png">

doesn't create a new entry, but should - the functionality is supposed to be identical to clicking the Notebook icon in the top bar of a domain object. This appears to be a regression, and given that the new entry area explicitly invites this gesture and it's not working, I'm marking this critical.

2. Dragging and dropping a domain object onto an existing entry does create an embed as intended, but the drop target is currently limited to the text entry field, and should instead be the entire visual area of the entry. Not sure if this is a new problem, but should be fixed if possible.

**Comment by deeptailor** [comment]
@charlesh88 - I have a branch for notebook fixes, just need to wrap it up when I get a chance

**Comment by shefalijoshi** [comment]
Fixed in Notebook V2
