### ISSUE TITLE
[Create Menu] create items should not display tooltips on hover 

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#2627]
While hovering over create-able items in the create menu, the tooltip can obscure the description pane.

![create menu item hover](https://user-images.githubusercontent.com/3614296/72937136-640ad980-3d1d-11ea-8423-1e661e1103eb.gif)

**Comment by davetsay** [comment]
## Expected Behavior
Tooltip should not display and obscure object description.

## Testing instructions
1. click on create menu
1. hover over a creatable object
1. Observe that tooltip appears and can even block display of the object description

**Comment by rukmini-bose** [comment]
Verified Testathon 3/202/24, tooltips do not appear on the create menu anymore, as well as supermenus in general.
