### ISSUE TITLE
Object names should not be editable for non user-editable objects

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#2634]
The name field of telemetry objects and other non-editable object types are currently editable. This causes an error on saving. This should be disabled.

The best way of checking this right now is by using `openmct.objects.isPersistable()`.

**Comment by shefalijoshi** [comment]
@akhenry @jvigliotta objects.isPersistable checks for a provider but it does not tell us if the object itself is user-editable. I would think checking if the object is creatable would be a better option here?

**Comment by jvigliotta** [comment]
## Testing
- try to edit a non-editable objects name in the browse bar
- boom

**Comment by deeptailor** [comment]
Verified fixed.... But

Right now when we hover above the name of non-editable items, the text box changes and makes it look like it is editable.
We should definitely prevent the text box from changing on hover when the item is un-editable

**Comment by nikhilmandlik** [comment]
Verified Fixed. Same thoughts as @deeptailor

**Comment by davetsay** [comment]
verified. +1 @deeptailor

**Comment by charlesh88** [comment]
_Partially_ verified Testathon 02/01/2021: cannot edit Open MCT in the tree, but other non-editable items like folders within "VIPER_SIMULATOR" apparently allow edit, although the change is not persisted. 

![Screen Shot 2021-02-01 at 11 37 55 AM](https://user-images.githubusercontent.com/1056412/106509291-49b42180-6482-11eb-95ad-eb2973e9c52a.png)


The correct behavior here is to not display the "Edit Properties..." menu item.

**Comment by jvigliotta** [comment]
@charlesh88 yeah, the issue there is our dictionary folders were coming in as type "folder", the fix there is updating them to the new type "noneditable.folder" and that fixes the problem.

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 2/25/2021

If a folder is a noneditable.folder type it is no longer editable via right click "edit properties" and the option to edit does not show up on hovering the name in the object view

**Comment by charlesh88** [comment]
Testathon 2/25/21 verified fixed.
