### ISSUE TITLE
[Documentation] Improve visual representation of diffs in tutorials

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#265]
The tutorials include a significant amount of source code, and when changes are made the diffs are highlighted. In the pdf version of the docs this highlighting was done via coloring the text, but this is not supported in markdown. Instead, in the markdown version file diffs are highlighted with a + or - next to each line changed. 

Some processing should be added to the documentation process in order to strip + and - characters for the HTML version of the docs, and instead use colors to highlight file diffs, ala the original pdf documentation.

Should do this change post #225 so that it's compatible with whatever documentation generation system is employed.

**Comment by larkin** [comment]
Wrapping diffs with a fenced code block and specifying `diff` allows them to automatically colorize,  ex:

```diff
[
    "platform/forms",
    "platform/persistence/queue",
--  "platform/persistence/elastic",
    "platform/policy",

    "example/generator"
]
```

Depends a bit on the markdown processor we use, but most of them should support similar usage.

**Comment by akhenry** [comment]
@larkin awesome, thanks for pointing this out. This works really well for the markdown, and I've included it in pull request https://github.com/nasa/openmctweb/pull/269

Currently the `diff` tag does not effect the HTML output though, so leaving this issue open for an HTML solution.

**Comment by larkin** [comment]
Interpretation of the diff tag depends on the markdown flavor, of which there are many.  I think redcarpet works as expected, that is, it applies CSS classes to the preformatted block and adds span tags around the lines.  However, there's some CSS needed to apply the styles, which we may need to specify.

**Comment by larkin** [comment]
Closed, tutorial feedback now part of github.com/nasa/openmct-tutorial.
