### ISSUE TITLE
Display Layouts should show imagery telemetry as images by default

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#2653]
Right now, dragging and dropping an imagery telemetry point into a display layout results in the image URL being displayed as an alpha-numeric layout element. Instead, Open MCT should use the Imagery plugin to display them.

**Comment by JoelMcKinnon** [comment]
Is this related to #2652?

**Comment by charlesh88** [comment]
Testathon 2024-03-20 cannot repro, fixed.
