### ISSUE TITLE
[Notebook] V2.0 development

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#2666]
Mockup: https://drive.google.com/file/d/1uqt-wJkMJYfJj0OAUN5BcPv_sC3ac2Yi/view

After discussion between @akhenry @nikhilmandlik and @charlesh88 these are the priorities for the development of the Notebook V2:

### V2.0 (MVP)
* [x] default section and default page icon (Charles)
* [x] Time conductor state - https://github.com/nasa/openmct/issues/2138
* [x] Add default on Notebook object in tree. (include Andrew)
* [x] Add and remove sections and pages
       * inc. custom section and page names
* [x] "Save to Notebook snapshots"
* [x] Notebook entries from "Notebook Snapshots"
* [x] Save snapshot to last used section and page
* [x] Collapsible or Responsive notebook navigation
* [x] Add section and pages in URL

### V2.1 (or V2.0 stretch goals)
7. Drag entries between notebooks
8. Drag and drop layout interactions 

### Bugs:
* [x]  focus on newly added entry
* [ ]  Entries filter
* [ ]  Remove 'new notebook entry' button inside Preview.
* [ ]  Remove default section/page from localstorage on notebook delete

* [x]  Section/Page rename does not reflect in notebook snapshot menu.
* [x]  Default notebook icon inside layouts is not visible.
* [x]  Removal of default Notebook from tree
           * clear location property on domain object if its original object and use when populating snapshot menu.
* [x]  localstorage max quota error 
           * Add warning before storage fills
           * Reduce to max size of 5.
* [x]  fix context menu
* [x] Search results: clicking in a page or section from a search result doesn’t completely clear the search bar, but it should. It also and breaks add section, add page buttons.
* [x]  edit entry updates entry in all sections and pages.

**Comment by mudinthewater** [comment]
Would also love to see saved time conductor state as opposed to just object so we can go back to the saved time conductor location of a notebook. 

(now in wishlist territory): Would be really neat if the annotations were a scalable overlay instead of an image, so you could go to a location and the overlay followed. This is an order of magnitude more painful for you guys though so I understand why that hasn't been done)

**Comment by akhenry** [comment]
@mudinthewater Agreed, __proper__ annotations are on our wishlist too. They're not on the roadmap right now for this FY, but I'll let you know if and when they get scheduled.

**Comment by akhenry** [comment]
@mudinthewater We have an issue for time conductor state - https://github.com/nasa/openmct/issues/2138 will try and get it to it in the same release as this.
