### ISSUE TITLE
[Design / Plot] Allow multiple plot lines per stack plot element

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#267]
**Charles**: Feature request from Sim #6
Would like to be able to create a stacked plot, but have multiple telemetry elements in each plot within the stack. This is also mentioned as a comment in WTD-86 but marking here

**Pete:** A regurgitation of a JPL user story, from my leaky memory:

When an ops user is designing a to persist, they know in advance how they want to see data.  in designing a page, a user may say, for any given page, "I want an overlay plot of channels a, b, and c," and then an overlay plot of "d, e, and f", and another of "g, h, and i".  Then they decide they want those three overlay plots to be stacked, but stacked isn't what they think:  instead, they think "I want them to share a common x axis and allow me to highlight times of interest across all three plots.

It was also noted that an ops user may not actually care to persist the display they are making-- it may contain channels that are very specific to troubleshooting a very specific problem which may not occur again, so being able to do all of this in edit mode in a very exploratory context would be ideal.

The current VISTA implementation allows them to create three overlay plots with the channels they want, and then they can use those separately or they can combine them to form a stacked plot (which causes them to gain time-sync like abilities).

**Comment by larkin** [comment]
closing as fixed in #1557.
