### ISSUE TITLE
object type keys should be moved to a constants file

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#2674]
Currently all types added to openmct.types.addType use hardcoded typeKeys. In order to track these effectively and to prevent conflicts, these should be moved to a constants file.

TypeKeyConstants.js:
{
WEBPAGE: 'webPage',
ANOTHERTYPE: 'anotherType',
...
}
Ex: https://github.com/nasa/openmct/blob/master/src/plugins/webPage/plugin.js#L29
could be changed to:
`openmct.types.addType(TypeKeyConstants.WEBPAGE, ...)`

**Comment by rajcrk** [comment]
This would result in adding multiple constant files for each plugin.
example: DisplayLayoutConstants.js in src/plugins/displayLayout and LADTableConstants.js in src/plugins/LADTable.
Is this the best way or do we have a single constants file possibly PluginConstants.js and have all constants in them?

**Comment by shefalijoshi** [comment]
Yes, a single constants file was the initial recommendation. Not one constants file for each plugin.

**Comment by rajcrk** [comment]
I would like to work on this!

**Comment by jvigliotta** [comment]
Closing as we do not want to couple our standalone plugins to the main code.
