### ISSUE TITLE
Criteria with more than one comparison input

### ISSUE THREAD

**Issue by JoelMcKinnon** [nasa/openmct#2678]
If condition criterion comparison operation is either 'between' or 'notBetween' it has to have two inputs. Value of criterion.input is derived from the values entered into both fields.

**Comment by shefalijoshi** [comment]
@JoelMcKinnon 
If you use the `inputCount` property of each operation, you should be able to generate the number if input fields dynamically.
See: https://github.com/nasa/openmct/blob/topic-conditionals/src/plugins/condition/utils/operations.js#L81
