### ISSUE TITLE
[Conditions] Persistence lost on navigation

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#2690]
Steps to reproduce

Create a minimum working condition set (with a condition and output)
Change the output of the Condition
Save
Observe that Condition Set output does not change although Condition output shows it has
Navigate to another object in tree
Navigate to Condition Set
Edit
Observe that output has not retained the change

NOTE: If you save, then immediate edit again (without navigating away), and save again the change is persisted

Persistence lost on Navigation after Save
![conditions - lose persistence on nav](https://user-images.githubusercontent.com/3614296/75389497-7091cd00-589b-11ea-9ebd-a0daba980667.gif)

Persistence retained if saved twice
![conditions - persistence on save again before nav](https://user-images.githubusercontent.com/3614296/75389501-72f42700-589b-11ea-86d8-9af9af1b9b1b.gif)

**Comment by shefalijoshi** [comment]
Closing this as it is fixed - tested in the conditions-do-refactor branch.
