### ISSUE TITLE
Flexible Layouts: dragging within Flex Layout in browse mode has problems

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2692]
1. Make a Flexible Layout and add an Imagery object to it. Save the Layout.
1. Mouse over the Imagery frame and try to drag the Brightness / Contrast controls. 
1. Observe that the layout behaves as if it's in Edit mode, and the Imagery element displays a drag ghost (not shown in screenshot). The B/C controls can be moved a tiny bit at best.
<img width="2021" alt="Screen Shot 2020-02-26 at 6 30 22 PM" src="https://user-images.githubusercontent.com/1056412/75407260-67b6f080-58c7-11ea-9bee-c4d0b9906f2f.png">

**Comment by charlesh88** [comment]
Re-upping this issue and now setting to blocker, as this behavior presents a significant impact to a crucial use case, making it effectively impossible to adjust brightness and contrast inside a Flexible Layout.
![Screen Shot 2022-03-23 at 10 04 31 AM](https://user-images.githubusercontent.com/1056412/159756097-b738e8b3-97c0-495f-8804-b3f7b7b4f496.png)

**Comment by unlikelyzero** [comment]
@charlesh88 are you saying that brightness/contrast controls do not work _at all_?

**Comment by khalidadil** [comment]
Verified in Testathon on 04/21/22
