### ISSUE TITLE
Fix styling for criteria icons and controls

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#2699]
Styling for criteria isn't aligned correctly. See:
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/5247066/75573451-ba042880-5a11-11ea-92ca-78db4cf87640.png">

**Comment by JoelMcKinnon** [comment]
Re-assigning this one to Charles. He instructed me to make no effort on styling these as that's his domain. I will be studying his implementation carefully however so some day I might be Charles Jr. :)

**Comment by shefalijoshi** [comment]
Closing as this is fixed and merged.
