### ISSUE TITLE
[Fixed Position] Bad image URLs come up empty

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#270]
If an image fails to load for an element in a fixed position view, there is no user feedback; instead, you simply see an empty frame.

Desired behavior is that some placeholder or other visual indicator (text?) is displayed in this circumstance, presumably within the frame where the image would otherwise appear.

**Comment by VWoeltjen** [comment]
Assigning to @charlesh88 as this needs a bit of design (what should be displayed in the empty frame when the image is not available, e.g. due to a 404). Reassign once this has been specified.

**Comment by charlesh88** [comment]
Moving this to backlog as fixed position view has reduced support currently.
