### ISSUE TITLE
Telemetry Table view for Condition Sets in Fixed timespan mode does not show any data.

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#2709]
In order to show data for fixed timespans, historic telemetry for conditionSets should be implemented.

Acceptance Criteria:
Data to be displayed in Telemetry Table view for a fixed time span provided the data is available.

**Comment by davetsay** [comment]
@shefalijoshi , I'll pick this up. The solution is providing the latest historical data available.

**Comment by davetsay** [comment]
resolved in #2759
