### ISSUE TITLE
[Images] Image view should react to time conductor changes

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#2712]
Right now the images view [correctly requests historical telemetry using the currently defined time bounds on load](https://github.com/nasa/openmct/blob/master/src/plugins/imagery/components/ImageryViewLayout.vue#L155) , but it also needs to react to changes in the time conductor and re-request historical telemetry using the new bounds.

The Time API will emit an event when the time conductor bounds change. A listener can be created for this event using [the `on` function on the time API](https://github.com/nasa/openmct/blob/master/src/api/time/TimeAPI.js#L220).  [Here is an example of its use in the wild](https://github.com/nasa/openmct/blob/master/src/plugins/displayLayout/components/TelemetryView.vue#L194).

eg.
``` JavaScript
openmct.time.on('bounds', someListenerFunction);
```

While you're in there, another couple of quirks about the imagery view that we should address:

* The `subscribe` function is [unnecessarily re-requesting the object](https://github.com/nasa/openmct/blob/master/src/plugins/imagery/components/ImageryViewLayout.vue#L200)
* The image view needs to check timestamps of incoming subscription data, and throw away images that fall after the current conductor end bounds. Let's talk about how to do this when you get to it.

**Comment by akhenry** [comment]
Per discussion 04/09: The incoming data will have timestamps defined on it that correspond to the active time system (this is not true for the "local time system" with the imagery data, so if this is an issue in testing let's talk). This means that you can retrieve a timestamp from the telemetry datum using the key of the active time system. Our API docs [provide guidance on using time systems](https://github.com/nasa/openmct/blob/master/API.md#time-systems-and-bounds).

The timestamp on the datum may or may not need parsing by a [telemetry formatter](https://github.com/nasa/openmct/blob/master/API.md#telemetry-formats-draft), so in all cases we parse telemetry values just in case. You can use the `.parse()` function on the telemetry formatter for the active time system for this purpose. In the imagery view, the formatter for the active time system is [already made available in the code](https://github.com/nasa/openmct/blob/11574b7c40142e17861d3f1d68ee3fc56c69cc62/src/plugins/imagery/components/ImageryViewLayout.vue#L204), so you can use that without having to retrieved it again.

Finally, we need to react to time system changes. You can observe time system changes using the `openmct.time.on('timeSystem')` event listener.

In this case it's safe to just throw all of the telemetry data away and re-request it (it was requested for time bounds that may no longer be valid in the new time system). The formatter should also be updated when this event occurs, since it is dependent upon the active time system. In the case of the `ImageryViewLayout.vue`, the simplest way of doing this is by just calling the `.subscribe()` function again, being careful to clean up any subscriptions as necessary.

**Comment by jvigliotta** [comment]
## Testing
- Add a new Example Imagery object
- Change the time bounds End date to a time in the future
  - New imagery should be coming in
- Change the time bounds End date to a time in the past (change the start as well if needed)
  - Latest imagery should be within those new bounds
- Changing to "Local Clock", new imagery should come in around every 5 seconds

**Comment by nikhilmandlik** [comment]
Testathon 6-22-2020
Fix Verified.

**Comment by davetsay** [comment]
Verified 06/22/2020
