### ISSUE TITLE
Inline edit "blur" can mutate other objects

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2713]
### Reproduction
1. Click on an object's title in the main view to put it into inline edit mode:
![Screen Shot 2020-03-02 at 3 45 59 PM](https://user-images.githubusercontent.com/1056412/75728535-f26b6700-5c9c-11ea-8c7d-d3d37bb7a792.png)
1. Without changing the name, click an object in the tree. Note that the main view hilites the correctly navigated object in the tree, but displays the title of the previous view:
![Screen Shot 2020-03-02 at 3 47 27 PM](https://user-images.githubusercontent.com/1056412/75728618-40806a80-5c9d-11ea-8856-08c1b68a216d.png)
1. Click the object's title in the main view again to put it into inline edit mode, then click elsewhere in the tree. Note the clicked tree item will immediately be mutated and renamed.
![Screen Shot 2020-03-02 at 3 49 51 PM](https://user-images.githubusercontent.com/1056412/75728680-7c1b3480-5c9d-11ea-91e1-fc7b0f493481.png)

**Comment by jvigliotta** [comment]
Verified 5/12/2020

**Comment by charlesh88** [comment]
WOOOTTT! Verified fixed testathon 05-12-20.
