### ISSUE TITLE
[Toolbar] Error occurs under some circumstances after editing display layouts and flexible layouts

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#2716]
This issue will sometimes happen when trying to create a new object after editing a layout. The UI will appear to transition into edit mode, but it will not navigate to the newly created object. Instead the user will be stuck in edit mode in the currently navigated object, which may even be a non-editable object such as a folder.

The following error is recorded in the JavaScript console:

```
DisplayLayoutToolbar.js:523 Uncaught TypeError: Cannot read property 'type' of undefined
    at DisplayLayoutToolbar.js:523
    at Array.forEach (<anonymous>)
    at Object.toolbar (DisplayLayoutToolbar.js:519)
    at ToolbarRegistry.js:51
    at Array.map (<anonymous>)
    at e.get (ToolbarRegistry.js:50)
    at s.toggleHasToolbar (Layout.vue:200)
    at n (vue.js:194)
    at n.s.emit (index.js:137)
    at n.select (Selection.js:78)
```

The following steps should reproduce the error:

1. Create display layout
2. Drag plot into it
3. Drag to reposition the plot (this seems to be essential. Just selecting it won't work)
4. Save and finish editing
5. Click on any folder
6. Create a table

**Comment by akhenry** [comment]
Have simplified reproduction steps.

**Comment by akhenry** [comment]
Let's verify if this is still an issue

**Comment by jvigliotta** [comment]
Verified Fixed Testathon 9/30/22

**Comment by khalidadil** [comment]
Following the steps provided exactly, I'm not seeing this issue. Verified Fixed in Testathon on 09/30/22
