### ISSUE TITLE
[Conditions] Changing view not updating mutations

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#2722]
Steps to recreate
1. Create a condition set
1. Add a condition
1. Save
1. Navigate to Telemetry Table View
1. Navigate to Condition Set View
1. Observe that edits do not appear to have been saved
1. Refresh browser
1. Observe that indeed edits have been saved

![conditions - change view not updating](https://user-images.githubusercontent.com/3614296/75927185-bfea7700-5e20-11ea-8645-23f61f90e805.gif)

**Comment by shefalijoshi** [comment]
Closing this as it is fixed. Tested in the conditions-do-refactor branch.

**Comment by davetsay** [comment]
I can reproduce the issue by following these steps
1. create a condition set
1. drop in a telemetry node
1. create a condition
1. configure and save the condition
1. navigate to telemetry table view
1. navigate back to conditions view
1. observe that condition is now gone from condition set
