### ISSUE TITLE
Condition dynamic summary description based on criteria

### ISSUE THREAD

**Issue by JoelMcKinnon** [nasa/openmct#2728]
Each condition within a condition set must include a summary description. This should be a dynamic property summarizing the combination of criteria and trigger used in evaluating the condition.  

Acceptance Criteria:

- User should be able to see a summary description describing each condition.
- Changes to the condition trigger or criteria should reflect in the summary description immediately.

**Comment by shefalijoshi** [comment]
Closing since it's merged.
