### ISSUE TITLE
[Conditions] Telemetry endpoints should not have multiple simultaneous subscriptions

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#2736]
Manage telemetry subscriptions so that each telemetry endpoint only gets subscribed to once.

Currently each condition set contains a set of conditions. Those conditions each contain criteria. Those criteria listen to telemetry endpoints. This results in potential duplication of subscriptions to  the same endpoints. This is turn will result in duplicate timestamped telemetry being provided by condition sets if those condition sets listen to an endpoint in multiple criteria.

**Comment by shefalijoshi** [comment]
Closing since it's merged.
