### ISSUE TITLE
Condition Set error on create

### ISSUE THREAD

**Issue by JoelMcKinnon** [nasa/openmct#2737]
Creating a new Condition Set results in an error in console and no default condition created in initial condition collection.

![Screen Shot 2020-03-10 at 9 07 58 AM](https://user-images.githubusercontent.com/6541399/76333346-ba70af00-62ae-11ea-9409-6d8bbf6101bd.png)

Workaround: Create a new Condition Set, which puts you into edit mode with no default condition. Click the X to leave edit mode. This puts you back into non-edit mode but there is now a default condition. Clicking the edit icon takes you back to edit mode and the default condition remains.

**Comment by shefalijoshi** [comment]
Fixed in topic-conditionals. Closing.
