### ISSUE TITLE
Handle equals for numbers correctly when comparing telemetry values

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#2741]
The issues comparing raw values are:
1. Rounding
2. Numbers behind the scenes are not visible to the user and might be confusing (for example `<value> is equal to 1`)

**Comment by akhenry** [comment]
Per discussion 03/10 - The approach decided upon is to use the raw (parsed) values for comparison. User input can be passed through the `.parse()` function of the appropriate telemetry formatter as defined by telemetry metadata.

**Comment by shefalijoshi** [comment]
Closing as this has been merged. Needs to be tested.
