### ISSUE TITLE
Conditional styling for multiple items in a layout

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#2744]
Select multiple items in a layout. Only the styles that are applicable to all the items maybe be changed and displayed in the styles inspector.
- Static styles should work for multiple selection
- Conditional styles may not be allowed
- Handle a mixture of objects some that have conditional styles and others that don't

**Comment by charlesh88** [comment]
Preferably, we allow Conditional Styles to be applied to multiple objects at once. This can be done in a simple fashion: 
1. If a given set of selected items doesn't include any items with Conditional Styling. Show the static styling controls that are applicable, and allow the user to click "Use Conditional Styling..." and configure styles. **As of 4/8/20, this is supported**.
1. If a given set of selected items includes one or more items with Conditional Styling, display a message stating that either static styles OR conditional styles may be applied, but either choice will replace any existing styling. Show the static styling controls that are applicable, and allow the user to click "Use Conditional Styling..." and configure styles.
1. If all the selected items use Conditional Styling, even if all the styles are identical for all selected items, take the approach described in 2 above.

**Comment by charlesh88** [comment]
### multiple-item-styles branch review 4/8/2020:
- [ ] Mixed styles need to be reflected in the thumbnail style element. @charlesh88 to address. Not a blocker for merge.
- [ ] Unable to set font-size style on telemetry elements, including dropped Condition Set elements. **This is a regression, therefore is a merge blocker unless addressed elsewhere.**

**Comment by shefalijoshi** [comment]
> Preferably, we allow Conditional Styles to be applied to multiple objects at once. This can be done in a simple fashion:
> 
>     1. If a given set of selected items doesn't include any items with Conditional Styling. Show the static styling controls that are applicable, and allow the user to click "Use Conditional Styling..." and configure styles. **As of 4/8/20, this is supported**.
> 
>     2. If a given set of selected items includes one or more items with Conditional Styling, display a message stating that either static styles OR conditional styles may be applied, but either choice will replace any existing styling. Show the static styling controls that are applicable, and allow the user to click "Use Conditional Styling..." and configure styles.
> 
>     3. If all the selected items use Conditional Styling, even if all the styles are identical for all selected items, take the approach described in 2 above.

Sure, let's do this as a separate Issue though.
