### ISSUE TITLE
[Conditions] refactor observables on condition sets

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#2750]
Limit updates to condition set in ConditionManager while ensuring changes to condition set are still observed correctly.
- Ensure on condition set changes...
  - existing listeners continue to listen correctly
  - new listeners listen correctly
  - deleted listeners are cleaned up properly

**Comment by shefalijoshi** [comment]
I think a lot of our issue could be mitigated if we stopped subscribing to the condition set's own telemetry in conditionSet.vue and instead update the output in the view by handling an event emitted by conditionCollection.vue.
Other updates to the condition set domain object then are limited to adding telemetry and changing the conditionSet name which are not likely to happen often and these can be handled by doing something like this when we persist conditions in ConditionManager:
`persistConditions() {
        this.openmct.objects.get(this.conditionSetDomainObject.identifier).then((conditionSetDomainObject) => {
            let conditionCollection = this.conditionSetDomainObject.configuration.conditionCollection;
            //we want to keep our copy of the conditionSet domain object in sync
            this.conditionSetDomainObject = conditionSetDomainObject;
            //but we want to ensure that the conditionCollection we have is the latest
            this.conditionSetDomainObject.configuration.conditionCollection = conditionCollection;
            this.openmct.objects.mutate(this.conditionSetDomainObject, 'configuration.conditionCollection', this.conditionSetDomainObject.configuration.conditionCollection);
        });
    }`

**Comment by shefalijoshi** [comment]
Merged. Closing.
