### ISSUE TITLE
Consolidate style definitions for drawing objects

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#2756]
Currently we support styling from the Display Layout Toolbar OR styling from the style tab of the conditional inspector? 
We should only be defining styles in one place.

More details to come @akhenry @charlesh88

**Comment by charlesh88** [comment]
The current UI design moves conditionally-controllable properties (border-color, background-color, color, image, etc.) out of the toolbar and into the Inspector. An object's layer position and canvas coordinates remain in the toolbar. From a design standpoint, what further detail is needed?

**Comment by shefalijoshi** [comment]
Closing as this is merged.
