### ISSUE TITLE
Fixed Position editing: multiple select and manipulate in the canvas area

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#276]
Originally JIRA issue https://trunk.arc.nasa.gov/jira/browse/WTD-1516
- Mark Shirley was building a Telemetry Panel in Fixed Position view for John Scheiner that involved a large number of telemetry points in an adhoc grid. Not only was the selection process from the Library tedious, but even worse was having to manipulate ~50 telem point and static text elements one by one to lay the screen out the way he wanted it. The solution here is to allow the user to select and manipulate multiple items on the canvas area. 
- Starting in an empty area of the canvas, drag a marquee. All items that are intersected (are alternately if easier, encompassed) become selected.
- Multiple items should be able to be moved as a group.
- Multiple items should be able to be resized as a group. This could be complex given grid snapping - we'd need to discuss how this might work.
- Toolbar buttons would need to be smart about the set of selected items: only buttons that are common to all selected objects would be available, and the selected button action would apply to all selected items. For example, being able to set a fill or border on multiple items.

**Comment by larkin** [comment]
Separate from multi-select and manipulate (which I definitely see the value in), I'm wondering if some more constrained objects could be used here to make it easier to build what they wanted to see-- in this a case a table.

Perhaps a new a "table" object which has user defined columns and N rows; users can add as many rows as they like.  Perhaps rows could be composite; where cell1 is user defined text and cell2 is the value of a telemetry point, or rows could be simple-- a telemetry point as a row would work and would populate cells based on the table headers.  Could re-arrange rows via drag and drop.

**Comment by larkin** [comment]
merging dupe into #135.
