### ISSUE TITLE
ConditionSet Output should be treated as a string format for conditions (currently incorrectly assumed number)

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#2765]
According to the logic in Criterion.vue, if metadata has a hints.range property, it is considered a number format.
See: https://github.com/nasa/openmct/blob/topic-conditionals/src/plugins/condition/components/Criterion.vue#L150

Since the ConditionSet's metadata has this property, it is incorrectly interpreted as a number:
See: https://github.com/nasa/openmct/blob/topic-conditionals/src/plugins/condition/ConditionSetMetadataProvider.js#L30

Repro steps:

- create a condition set with at least 2 conditions - ensure it's output is correctly changing based on it's conditions. Save
- create another condition set. Drag the first condition set as telemetry into the 2nd condition set
- Select the condition set as telemetry for a criterion.
- Select Output from the metadata dropdown for the criterion
- Observe the available operations are for number formats. (They should be string format operations instead).

**Comment by davetsay** [comment]
This is set up this way, as an enum, so that condition sets can be provided as telemetry to plot views.

**Comment by JoelMcKinnon** [comment]
Confirmed that removing hints from the getMetadata method in ConditionSetMetadataProvider resolves the issue in the use case @shefalijoshi describes.

**Comment by shefalijoshi** [comment]
Closing this as the enum operations now show up correctly.
