### ISSUE TITLE
Control visibility for domain objects and drawing objects in a layout

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#2766]
When an item is part of a layout, conditional styling should allow showing/hiding that item.

Acceptance Criteria:
Allow show/hide controls when an item is a child of a layout item.
If an item is not a child, don't show the control

**Comment by shefalijoshi** [comment]
Closing as this is merged.

**Comment by charlesh88** [comment]
**VERIFIED FIXED TESTATHON 03/26/2020**
