### ISSUE TITLE
Conditionals Testathon 1 Issues

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#2772]
### High
- [ ] Test data is still not complete
- [ ] Resizing and/or repositioning drawing objects and them immediately changing a style attribute in the Inspector causes the drawing object to reset to its previous pose. Main toolbar interactions for same don't exhibit this behavior. 
![Screen Shot 2020-03-24 at 3 25 10 PM](https://user-images.githubusercontent.com/1056412/77482652-b0d56400-6de3-11ea-9e55-43bfa0e01d08.png)
- [X] **WON'T FIX** Summary Widgets do not accept styling as expected: styling does not have the desired effect when styling directly, and has no effect when being styled in a Layout;
![Screen Shot 2020-03-24 at 11 20 31 PM](https://user-images.githubusercontent.com/1056412/77507811-63c6b180-6e26-11ea-8ad6-a15bb3514ed5.png)
- [ ] Hyperlinks have similar problems to Summary Widgets as noted above; plus they only have Edit Properties and don't allow direct styling.
- [ ] 'when any | all telemetry' context not yet implemented
- [x] When editing a Condition Set and removing a Condition, all objects that use that CS must be updated accordingly.
- [x] @charlesh88 Remove re-located toolbar icons (fill, border, etc.)

### Medium
- [ ] While editing, Conditions should be clickable to apply their style settings.
- [ ] Currently matched Condition is not visually highlighting
- [x] @charlesh88 tree items should be clickable on the whole line, not just the label.
- [ ] Dynamic condition evaluation and style application should be suspended while editing an object.
 - [x] @charlesh88 Text color does not have any effect on all Plot views.
   - @charlesh88 fixed in `conditionals-ch-fixes-032420`.
- [x] Condition description value for enum should show the name of the enum not the value.
example:  When State Generator Value is 1 or Condition Set1 Output is 0
- [ ] Drag reorder in Condition Set needs to be improved.

### Low
- [x] @charlesh88 `is-style-invisible` as applied to imagery should also be used for __all__ `c-style-thumbs`.
  - @charlesh88 fixed in `conditionals-ch-fixes-032420`.
- [ ] Add a Confirmation dialog when removing a Condition Set from an object.
- [x] @charlesh88 In Condition, need a space between controls: 
![Screen Shot 2020-03-24 at 2 37 58 PM](https://user-images.githubusercontent.com/1056412/77479469-16722200-6ddd-11ea-959a-63566df1279a.png)
  - @charlesh88 fixed in `conditionals-ch-fixes-032420`.
- [x] @charlesh88 Text inputs for 'string' type operations are incorrectly setting the HTML input type to 'string'; should be 'text'. 
  - @charlesh88 fixed in `conditionals-ch-fixes-032420`.

**Comment by charlesh88** [comment]
Closing this for verification of issues during Testathon 2 03/26/2020.
