### ISSUE TITLE
[Conditionals] Output text is unclear

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#2774]
The output of a newly created Condition Set is "No Output Selected". This should be clarified. It sounds as though the user needs to "select output", but what does that mean? I haven't even defined any conditions yet.

**Comment by charlesh88** [comment]
This is a bug. When creating a new Condition Set (CS), the default Condition is present, and is currently defaulting to the first option in the "Output" select, which is "False":
![Screen Shot 2020-03-24 at 6 21 48 PM](https://user-images.githubusercontent.com/1056412/77491937-5bf21780-6dfc-11ea-881b-7f3301bbffc5.png) 
but the component is reacting as if the Output select is set to it's null default "- Select Output -".

It's looking like the CS is requiring telemetry to be added before __anything__ gets processed, but I don't think that should be the case - the set should evaluate even without any telemetry being added and no other conditions being defined. So, the output should be "False" with the current defaults. Also, it might be more intuitive if the default selection here is String with "Default" entered in the input field:
![Screen Shot 2020-03-24 at 7 03 04 PM](https://user-images.githubusercontent.com/1056412/77494103-1f291f00-6e02-11ea-836f-bfb59f612d5e.png)

**Comment by davetsay** [comment]
@JoelMcKinnon , I can take this one. I know what is going on here.
@charlesh88 , I can also handle the preventing of `- no selection -`.
