### ISSUE TITLE
[conditionals]: Condition set does not reset on 'cancel Editing' on overlay plot.

### ISSUE THREAD

**Issue by nikhilmandlik** [nasa/openmct#2777]
Steps to reproduce:

1. overlay plot add sine wave
2. add Condition Set in styles
3. save
4. edit overlay plot
5. remove Conditional styles
6. cancel Editing
7. observe styles in overlay plot, it should go back to original/old styles

<img width="1079" alt="Screen Shot 2020-03-24 at 3 10 44 PM" src="https://user-images.githubusercontent.com/1292612/77481812-b336be80-6de1-11ea-9616-c3147533e220.png">

**Comment by davetsay** [comment]
Not reproducible anymore
