### ISSUE TITLE
[Conditionals] Setting text color of tables only affects headers

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#2778]
Steps to reproduce:
1. Drag table into display layout
2. Set default text color to blue
3. Observe below - 

![Screen Shot 2020-03-24 at 3 10 55 PM](https://user-images.githubusercontent.com/4215777/77481811-b336be80-6de1-11ea-86a1-11f615305698.png)

**Comment by charlesh88** [comment]
3/24/20: fixed in `conditionals-ch-fixes-032420`.
