### ISSUE TITLE
[Conditionals] criterion state selection is not persisted

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#2787]
Steps to Reproduce
1. Set `state is ON`.
1. Save.
1. Refresh
1. Observe that state reverts back to `OFF`

![state is operator not persisting](https://user-images.githubusercontent.com/3614296/77611165-d779c480-6ee1-11ea-8bb0-1ba9c50903e2.gif)

**Comment by shefalijoshi** [comment]
Closing as it is merged.
