### ISSUE TITLE
[Edit Mode] Create menu filtered to only allow creation of items that can be contained by the currently selected object

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#280]
Taken from item 4. https://github.com/nasa/openmctweb/issues/161#issuecomment-155162928
Create menu filtered to only allow creation of items that can be contained by the currently selected

**Comment by akhenry** [comment]
From #161
> I'd defer this, partly because I'm not sure it's the right thing to do. There are cases where we want to be able to create things while editing and place them more deeply in the hierarchy, particularly as we move toward a "edit panels inside of a layout" approach. I think the right thing to do in that case is filter down based on what's contained in the whole subgraph being edited (which may require loading a lot of objects just to figure out; we could end up with a wait spinner in the Create menu) which is different enough that I'm inclined to defer.
@VWoeltjen

**Comment by charlesh88** [comment]
Covered by #581, closing.
