### ISSUE TITLE
Conditionals: Add support for NOT and XOR in Match

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2811]
![Screen Shot 2020-03-27 at 10 49 39 AM](https://user-images.githubusercontent.com/1056412/77784989-b1a30b80-7018-11ea-941e-9fd135e6c110.png)

Add "when no criteria are met" and "when only one criteria is met" respectively.

**Comment by shefalijoshi** [comment]
Closing as this is merged.
