### ISSUE TITLE
[Notebook]: Remove default section/page from localstorage on notebook delete

### ISSUE THREAD

**Issue by nikhilmandlik** [nasa/openmct#2822]
Once notebook is remove from tree

<img width="863" alt="Screen Shot 2020-03-30 at 10 49 28 AM" src="https://user-images.githubusercontent.com/1292612/77944645-28881080-7274-11ea-8f85-73d12c4cb108.png">

**Comment by jvigliotta** [comment]
Verifed 5/15/202

Following the instructions, no issues, works as expected.
