### ISSUE TITLE
[Tables] Test coverage

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#2826]
Some unit tests exist for telemetry tables, but these should be expanded upon in order to bring statement coverage as close to 100% as is practical.

### Additional Tests Required
* [ ] Order results by a column (return some test telemetry, simulate click on header, and inspect resulting rows)
* [ ] Ensure that sort order is correctly maintained when new data becomes available
* [ ] Filter by a column (programmatically enter some text in the filter input and inspect resulting rows)
* [ ] Test that export to CSV works
* [ ] Pause / Play buttons
* [ ] Expand Columns
* [ ] Show / hide columns (from the inspector. Let's talk about how to test this, since it involves interactions between the inspector and the main table view.)
* [ ] New row for each datum received that is within bounds

**Comment by unlikelyzero** [comment]
Need to reassess
