### ISSUE TITLE
[Conditionals] Deleting criterion incorrectly adds input element to next criterion

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#2828]
Steps to Reproduce
1. Create a condition set with 1 condition and 1 filled out criterion
1. Add a second criterion
1. Select telemetry
1. Select field
1. Delete first criterion
1. Observe that a non-sensical and non-styled input remains

![straggler input on delete criterion](https://user-images.githubusercontent.com/3614296/78062621-cd255380-7343-11ea-980b-a75e695909f1.gif)

**Comment by akhenry** [comment]
This might be a good candidate for @jvigliotta to take a look at

**Comment by charlesh88** [comment]
Have we checked to make sure this doesn't affect criterion evaluation? If it does, it's not Low priority.

**Comment by JoelMcKinnon** [comment]
I did some testing of evaluations, but will do more. From my perspective, the flaw that caused the bug was significant and adds risk. It definitely shouldn't be left as is.

**Comment by shefalijoshi** [comment]
Closing this as it has been merged.
