### ISSUE TITLE
[Conditionals] Unable to style telemetry values in display layout

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#2838]
Selecting the styling options has no effect

![Screen Shot 2020-03-31 at 4 13 42 PM](https://user-images.githubusercontent.com/4215777/78083546-a1699400-736a-11ea-8023-0ac18a2aaafc.png)

If I navigate away and back again the styles are applied...

![Screen Shot 2020-03-31 at 4 16 56 PM](https://user-images.githubusercontent.com/4215777/78083707-189f2800-736b-11ea-87bc-405569174de0.png)

**Comment by shefalijoshi** [comment]
@akhenry I think this fix can be combined with #2779 Since that changes how we apply styles to non composable objects

**Comment by shefalijoshi** [comment]
Closing as this is fixed.
