### ISSUE TITLE
[Edit Mode] Move fixed position editing from Panels into Layouts

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#284]
From https://github.com/nasa/openmctweb/issues/161#issuecomment-155162928 no. 8

**Comment by larkin** [comment]
Note in discussions, it may be way more beneficial to move layouts into fixed position panels instead of trying to port fixed position functionality to layouts.

**Comment by larkin** [comment]
wontfix: they are two different displays with different purposes and will not be merged.
