### ISSUE TITLE
Unable to complete npm install on windows and linux

### ISSUE THREAD

**Issue by infinitymakerspace** [nasa/openmct#2840]
Hi I have cloned the latest files via git to 3 machines of which 1 is my laptop and two are Linux machines.  Is there any extra manual work needed which version of node js and npm works.

**Comment by akhenry** [comment]
@infinitymakerspace Should definitely work in Linux with Node 10+. Windows support is [an ongoing issue](https://github.com/nasa/openmct/issues/2604) due to a problem with a dependency.

**Comment by infinitymakerspace** [comment]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! openmct@1.0.0-snapshot build:prod: `cross-env NODE_ENV=production webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the openmct@1.0.0-snapshot build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-03-31T23_41_39_716Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! openmct@1.0.0-snapshot prepare: `npm run build:prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the openmct@1.0.0-snapshot prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-03-31T23_41_39_794Z-debug.log

**Comment by infinitymakerspace** [comment]
[2020-03-31T23_43_50_429Z-debug.log](https://github.com/nasa/openmct/files/4412022/2020-03-31T23_43_50_429Z-debug.log)

**Comment by infinitymakerspace** [comment]
> @infinitymakerspace Should definitely work in Linux with Node 10+. Windows support is [an ongoing issue](https://github.com/nasa/openmct/issues/2604) due to a problem with a dependency.
> 
> If it doesn't work with Node 10 in linux could you post any error messages you're seeing?

I hope this gives you some idea of what is going on.  I really need to get this to work

**Comment by MarkCodering** [comment]
I have this problem as well. The OpenMCT was built failed on the Node.js version 12, 11, and 10. Is there have any resolution for this issue?

Thanks, 
Mark

**Comment by deeptailor** [comment]
Exit code 137 points to out of memory error in multiple different node applications - maybe increasing memory would fix this issue?

https://support.circleci.com/hc/en-us/articles/115014359648-Exit-code-137-Out-of-memory
