### ISSUE TITLE
[Notebook]: Unnecessary notification "Time bounds changed to fixed timespan mode" 

### ISSUE THREAD

**Issue by nikhilmandlik** [nasa/openmct#2843]
Found during: Testathon on 3 Mar 31, 2020

Every time user clicks embed link there is notification "Time bounds changed to fixed timespan mode".

This notification should be visible only incase of time bound change.

**Comment by akhenry** [comment]
Verified that original issue is fixed, but have found a new bug. Will file followup issue.

**Comment by akhenry** [comment]
Have filed issue for related bug - https://github.com/nasa/openmct/issues/3034

**Comment by JoelMcKinnon** [comment]
## Testing Instructions:

### 1. No timebound change - Fixed Timespan Mode

1. be in a fixed timespan mode.
2. take a snapshot to add new entry into a Notebook
3. click on embed name
4. this should take you to original embed object
5. and observe there is no notification regarding timespan change.

### 2. Timebound change - Fixed Timespan Mode

1. be in a fixed timespan mode.
2. change start and end time to month old time
3. take a snapshot to add new entry into a Notebook
4. goto notebook
5. change back start and end time to current month
6. click on embed name
7. this should take you to original embed object
8. and observe there is a notification regarding timespan change. `Time bound values changed`

### 3. Timebound change - Real Time Mode

1. be in a fixed timespan mode.
2. change start and end time to month old time
3. take a snapshot to add new entry into a Notebook
4. goto notebook
5. change time to real time mode
6. click on embed name
7. this should take you to original embed object
8. and observe there is a notification regarding timespan change. `Time bound values changed to fixed timespan mode`
