### ISSUE TITLE
[Notebook] Delete Snapshot, Section and Page context action sporadically doesn't work

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#2844]
1. Navigate to a view
2. "Save to Notebook Snapshots"
3. Repeat so that you have two or three snapshots
4. Expand the snapshots area of the screen
5. Expand the context menu associated with a snapshot, and click on "Delete Snapshot"

**Comment by charlesh88** [comment]
Saw similar issues when using the context menu to delete Notebook Section and Pages. No recipe to reproduce at this time.
