### ISSUE TITLE
[Conditions] Metadata format check incorrectly identifying string/number formats

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#2847]
updateOperationFormat in Criterion.vue should be changed to match what telemetry formatter is doing.
- format should be checked first
- fallback should be number, not string

![image](https://user-images.githubusercontent.com/3614296/78085241-45edd500-736f-11ea-9197-63d98ea7e68c.png)

**Comment by shefalijoshi** [comment]
Closing as this is merged.
