### ISSUE TITLE
[Notebook] Remove 'Saved to Notebook Snapshots' notification

### ISSUE THREAD

**Issue by nikhilmandlik** [nasa/openmct#2859]
- [x] remove Saved to Notebook Snapshots notification, it is no longer needed. (approved by @charlesh88)

<img width="1298" alt="Screen Shot 2020-04-01 at 3 15 27 PM" src="https://user-images.githubusercontent.com/1292612/78191960-ffaa7b80-742b-11ea-9729-f8b305f40fde.png">

- [x] Update 'Saved to Notebook ......' message delimiters from '>' to '-'
<img width="445" alt="Screen Shot 2020-04-01 at 3 24 29 PM" src="https://user-images.githubusercontent.com/1292612/78192635-63817400-742d-11ea-8e08-bbbbc7d86968.png">

**Comment by akhenry** [comment]
Assigned to @jvigliotta

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 2/25/2021

Saved a snapshot and did not see the notification.

**Comment by charlesh88** [comment]
Sigh, no testing notes. 

Testathon 2/25/21 verified fixed.

**Comment by tiffanyatruong** [comment]
Saved a snapshot and got a notification 2/25/2021
<img width="590" alt="Screen Shot 2021-02-25 at 10 27 37 AM" src="https://user-images.githubusercontent.com/78380145/109199375-38de8f00-7754-11eb-9481-40c4fec740b7.png">
