### ISSUE TITLE
[Conditionals] Request results and subscription results should be atomic

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#2862]
A condition stores the latest result from each of its criteria. If request results do not all come in before subscription results come in (this is not guaranteed), then the LAD request output might be incorrect.

Originally one instance of conditionManager was being used for requests and one separate instance of conditionManager was being used for subscriptions so this wasn't an issue. Now one instance is being shared to provide both request and subscription telemetry.

**Comment by akhenry** [comment]
Verified fixed 04/10/20202
