### ISSUE TITLE
"Move" context action leaves Linked object in original location

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2863]
This appears to be a relatively recent regression.

### Reproduction
1. Create a new folder if you don't have one already. This will be the move target, shown as "2" in screencaps.
1. Create a new object outside the new folder, if you don't have one already.
1. Context-click the object and choose "Move" from the menu.
![Screen Shot 2020-04-01 at 6 59 36 PM](https://user-images.githubusercontent.com/1056412/78203483-f0d3c100-744b-11ea-87b4-3796fcec70d2.png)
1. Select the move target folder in the locator dialog as the move destination.
1. Observe: the "original" object will be shown as located in the move target folder, but a link to the moved object will remain in the original location, shown as "1" in screencaps.
![Screen Shot 2020-04-01 at 7 00 02 PM](https://user-images.githubusercontent.com/1056412/78203463-e31e3b80-744b-11ea-9bc6-5fb931b0f75d.png)
The Inspector will also incorrectly report the Original Location, although this is corrected after a refresh.
![Screen Shot 2020-04-01 at 7 00 37 PM](https://user-images.githubusercontent.com/1056412/78203453-def21e00-744b-11ea-979b-7615606703ed.png)

### Expected
Moving an object should not leave a link in the original location, and the Inspector should correctly report the object's original location without the app needing to be refreshed.

**Comment by deeptailor** [comment]
Looks like the legacy remove action was deleted, which is why the link still remains in the original location. I think the best solution would be to translate this legacy action into a new MoveAction plugin, and utilize the re-written remove action.

**Comment by akhenry** [comment]
When re-implementing as a new style action, also add the ability to rename the object during copy
https://github.com/nasa/openmct/issues/604

**Comment by jvigliotta** [comment]
## Testing
- Create two folders or use existing folders or objects
- Create a new object to move, or use an existing object
- Right click on the object to move and select "Move"
- (optional) Change the name to something new
- Select a new folder (try selected it's current folder, should not work)
- Click OK
- Verify the object was completely removed from the existing folder or object (no link or alias)
- Verify the object was moved to the new folder or object
- If you changed the name, verify the name has been updated to reflect that
- Try different variations of above (different types of objects, etc)

**Comment by shefalijoshi** [comment]
Tested, but I still see this.

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by charlesh88** [comment]
Verified fixed Testathon 11-30-20
