### ISSUE TITLE
"Preview" overlay should display object styles

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#2874]
![Screen Shot 2020-03-31 at 5 43 58 PM](https://user-images.githubusercontent.com/1056412/78087848-3a061100-7377-11ea-8495-0fea79f0c958.png)
![Screen Shot 2020-03-31 at 5 39 03 PM](https://user-images.githubusercontent.com/1056412/78087860-44c0a600-7377-11ea-8fd3-60464357f9d0.png)

**Comment by akhenry** [comment]
Verified fixed, 05/12/2020

**Comment by charlesh88** [comment]
Verified fixed testathon 05-12-20.
