### ISSUE TITLE
[Conditionals] State generator state cannot be evaluated

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#2881]
Configuration is being saved as string but data is number. Also, it appears telemetry name is trying to be cast as a Number.

<img width="1008" alt="state_generator_output" src="https://user-images.githubusercontent.com/3614296/78701923-a70c3000-78bc-11ea-8199-a1d7607b1368.png">

<img width="1029" alt="state_generator_name" src="https://user-images.githubusercontent.com/3614296/78702402-61039c00-78bd-11ea-9130-ae12c04f2885.png">

**Comment by shefalijoshi** [comment]
Should take a look at the enum comparison operators to fix this:
https://github.com/nasa/openmct/blob/master/src/plugins/condition/utils/operations.js#L217

**Comment by charlesh88** [comment]
@davetsay @shefalijoshi Can we get some notes about how to verify if this has been fixed? Is it simply this:
1. Create an Event Message Generator.
1. Create a Condition Set that evaluates the EMG.
1. Verify that conditions are matched.
