### ISSUE TITLE
[Conditionals] Default should never be output

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#2882]
A state generator with conditions for `ON` and `OFF` should never output the default condition, but it still does.

Steps to reproduce
1. Create a condition set and add a state generator
1. Create a condition - `value = 1` (ON)
1. Create another condition - `value = 0` (OFF). `value != 1` works as well to test.
1. Save Condition Set
1. Switch to Telemetry Table view and observe that default condition is still output

<img width="1021" alt="state_condition_default" src="https://user-images.githubusercontent.com/3614296/78708604-40404400-78c7-11ea-904b-13585ec1ed63.png">

**Comment by shefalijoshi** [comment]
Is it possible that the Default condition isn't the last one to be evaluated?

**Comment by shefalijoshi** [comment]
Please also test: #2873 when this is resolved.

**Comment by shefalijoshi** [comment]
This is also related to:  #2872

**Comment by shefalijoshi** [comment]
There are multiple issues here, but the major 2 are:
1. Conditions are being evaluated for telemetry datapoints that were not relevant to them.
2. Condition result evaluations are referencing criteria results that are outdated for a specific telemetry datapoint.
3. ConditionManager result is referencing condition results for mixed telemetry datapoints.
