### ISSUE TITLE
LAD Table Set allowed to be created in/moved into LAD Table

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2892]
Should be disallowed.
<img width="415" alt="Screen Shot 2020-04-08 at 4 27 02 PM" src="https://user-images.githubusercontent.com/1056412/78842883-1ca7f700-79b6-11ea-934f-cc1c9808be3f.png">

**Comment by jvigliotta** [comment]
Added new composition policy for LADTable. Checks if LAD Table, child is telemetry, if LAD Table Set, child is LAD Table.

**Comment by jvigliotta** [comment]
Testing Notes:

- Create a LAD Table
- Add any telemetry producing object (example imagery, sine wave generator, etc) it should accept it
- Add any NON telemetry producing object (display layout, folder, etc) it should not be added
- Create a LAD Table Set
- Add any LAD table, it should accept it
- Add anything OTHER than a LAD table and it should not be added

**Comment by jvigliotta** [comment]
Removing unverified label, this is merged in.

**Comment by jvigliotta** [comment]
closed this issue, does not need to be tested in 06/04/2021 2 testathon

**Comment by shefalijoshi** [comment]
Verified Fixed.

**Comment by charlesh88** [comment]
Verified fixed Testathon 6/4/2021
