### ISSUE TITLE
[Conditional Styling] Can't set font size on Telemetry alphanumerics in Layout

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2894]
`multiple-item-styles branch` review 4/8/2020.

Unable to set font-size style on alphanumeric telemetry elements, including dropped Condition Set elements. This is a regression from current functionality.
<img width="535" alt="Screen Shot 2020-04-08 at 5 20 22 PM" src="https://user-images.githubusercontent.com/1056412/78845438-5fb99880-79bd-11ea-9126-da353e562bf7.png">

**Comment by charlesh88** [comment]
Reviewed in `multiple-item-styles` branch: fixed, but has issues. See comments in #2895.

**Comment by akhenry** [comment]
Verified fixed.
