### ISSUE TITLE
ESLint script not linting some files it should

### ISSUE THREAD

**Issue by JoelMcKinnon** [nasa/openmct#2903]
Observed a discrepancy between result of running npm run lint at command line and what should be the same check run by CircleCI. For example; after making changes to lodash linter to remove the import-restrictions exclusion npm run lint found about 8 violations where the full lodash library was imported in the form of `import _ from 'lodash'`. Correct format should be `import methodname from 'lodash/methodname`. I corrected all of these errors, ran npm run lint which passed, and then pushed changes and opened a pull request. CircleCI failed the check due to two more violations of the exact same form.

**Comment by JoelMcKinnon** [comment]
Resolved by changing the lint and lint:fix scripts in package.json from the format
`"eslint platform example src/**/*.{js,vue} openmct.js"`
to
`"eslint platform example src --ext .js,.vue openmct.js"`

**Comment by JoelMcKinnon** [comment]
Testing notes: some files were not being linted. Make an indent change in HelloWorld.vue, for example. Before it would not have been caught,. Now it should.

**Comment by jvigliotta** [comment]
Verified 5/12/2020
