### ISSUE TITLE
[Actions] Disambiguate keys for Create

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#291]
Currently, all create actions have a key of "create". This limits usage of these actions; you can't have any shorthands like `domainObject.getCapability('action').perform('create.folder')`, for instance. Would be useful to provide unique keys per creatable type.

Corollary to this, want to look up create actions by category instead of by key.

Observed during CLI prototyping (branch cli), filed per #176; this is a place where behavior that belongs in the information model has been handled in the display layer.

**Comment by larkin** [comment]
Interesting note that action contexts are getting quite muddy.  using category for "create" seems to conflict with other uses of category.

Anyhow, closing as wontfix.
