### ISSUE TITLE
Removing telemetry from inspector not updating view

### ISSUE THREAD

**Issue by JoelMcKinnon** [nasa/openmct#2910]
Steps to reproduce:
1. Create Telemetry Table
2. Drag in telemetry, such as a Sine Wave Generator.
3. Context click on the telemetry object in the Elements view and Remove.
4. Click OK. Note that the table data remains in the object view.
5. Click Save and Continue Editing - data remains.
6. Click Save and Finish Editing - data remains.
7. Reload page. Data is gone.

**Comment by unlikelyzero** [comment]
This is no longer happening, however would make a great regression test
