### ISSUE TITLE
[Conditionals] Condition description renders incorrectly

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2917]
1. Create a Condition Set with a condition that uses a 'between' criterion. Save it.
1. Note that the description will look correct:
<img width="259" alt="Screen Shot 2020-04-10 at 4 35 43 PM" src="https://user-images.githubusercontent.com/1056412/79029492-77be2300-7b49-11ea-99e3-35a131151248.png">
1. Edit the CS, then change the between condition to any other condition that uses a single input, like 'greater than'. Save it, then observe it uses the comma-based approach from between:
<img width="193" alt="Screen Shot 2020-04-10 at 4 33 46 PM" src="https://user-images.githubusercontent.com/1056412/79029488-74c33280-7b49-11ea-9fd2-26904383ab24.png">

**Comment by JoelMcKinnon** [comment]
Verified per testing notes

**Comment by charlesh88** [comment]
Verified fixed testathon 05-12-20.
