### ISSUE TITLE
[Notebook] Creating  Notebook entries randomly throws errors with a Couch backend

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#2918]
Steps to reproduce:
1. Create a new notebook
2. Drag an object into the notebook to create a new entry
3. Observe that an error notification appears.

In the console:
```
PUT https://<>/couchdb/vipersim/1654b1c6-1dde-4dcc-99d4-0dc697f64508 409 (Conflict)
```

The problem appears to be that we are attempting to persist an object with an out of date Couch DB version number. Some investigation is necessary to understand exactly what is going on here.

**Comment by shefalijoshi** [comment]
There were couchDB related fixes. Let's retest this.

**Comment by unlikelyzero** [comment]
### Testing Notes
Create a list of sanity tests to verify (simply) that couchdb is configured corrrectly. No duplicate requests. No 500s. No 404s in console.

**Comment by michaelrogers** [comment]
Attempted to test during Testathon for 1.8.3. on 2022-01-06 and was unable to add entries to a new Notebook.

**Comment by shefalijoshi** [comment]
Verified fixed on a notebook that is NOT the default notebook

**Comment by michaelrogers** [comment]
Fix verified for default and non default notebooks in mini testathon 2022-01-07 on release 1.8.3.

**Comment by shefalijoshi** [comment]
Verified fixed on default notebook.
