### ISSUE TITLE
[Notebook] Save snapshot dropdown should be available from "view large" overlay

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#2922]
If an object is included in a display layout, then there is currently no way to snapshot it from the layout. If the user wants to capture just the object itself (eg a plot with an interesting features), they have to either snapshot the whole layout, or navigate to the object and then capture a snapshot.

The desired fix here is to add the snapshot dropdown to the "view large" overlay, so that the user can capture individual views within a display layout.

**Comment by charlesh88** [comment]
Preview (via a tree item) is also not displaying the Notebook Snapshot menu, but should.

**Comment by nikhilmandlik** [comment]
> Preview (via a tree item) is also not displaying the Notebook Snapshot menu, but should.

There is issue related to this, May be it needs to reopen and disabled only for notebook previews

[Notebook] [V2.0]: Remove 'new notebook entry' button inside Preview. #2821

**Comment by JoelMcKinnon** [comment]
## Testing Instructions (from PR):

1. Create a 'Display layout'
2. Add any existing plot (eg: Overlay Plot) into Display layout
3. Click on 'view large' icon on top-right corner of Overlay Plot.
4. View large should have 'notebook' dropdown.
5. Click the 'Notebook' dropdown and verify the menu is available.
6. Take a Snapshot using the 'Save to Notebook Snapshots' option.
7. Close the View Large overlay and verify a Snapshot was added to the Snapshots area:
8. 

![Screen Shot 2020-05-12 at 2 26 12 PM](https://user-images.githubusercontent.com/1056412/81747236-9707e300-945c-11ea-8320-4ef71634efc0.png)
![Screen Shot 2020-05-12 at 2 26 21 PM](https://user-images.githubusercontent.com/1056412/81747238-98d1a680-945c-11ea-85b2-9474ea117ab8.png)

**Comment by JoelMcKinnon** [comment]
Verified per test notes.

**Comment by charlesh88** [comment]
Verified fixed testathon 05-12-20.
