### ISSUE TITLE
Elasticsearch types deprecation - need to support typeless APIs

### ISSUE THREAD

**Issue by JoelMcKinnon** [nasa/openmct#2944]
Elasticsearch v7.0 deprecated APIs that accept types and introduced new typeless APIs, and removed support for the _default_ mapping. See migration notes at https://www.elastic.co/blog/moving-from-types-to-typeless-apis-in-elasticsearch-7-0

OpenMCT current implementation results in bad request on removing objects from tree:

![image](https://user-images.githubusercontent.com/6541399/79487246-cf86df00-7fcc-11ea-9275-11a14dc9224d.png)

User attempting to install Elasticsearch plugin encountered problems related to Elasticsearch not in bundleMap, addressed in #2941. Also see original issue for notes on CORS config in original issue #2886.

**Comment by akhenry** [comment]
Verified Fixed 05/12/2020
