### ISSUE TITLE
Telemetry elements in a Layout don't allow styling

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2960]
Seen on hulk 4/22/20 with branch `notebook-view-large-save-drop-down-menu`.

Telemetry elements don't display the Styles tab, and can't be styled - however, selecting a drawing object, like a text object, and then selecting a telem object displays the Styles tab and allows them to be styled. Styles set this way do persist.

This can't be duplicated via running the master branch or `notebook-view-large-save-drop-down-menu` locally with Sine Wave generators. I suspect it's a problem with real telemetry vs. SWG's and is a problem in master.

**Comment by shefalijoshi** [comment]
@deeptailor You said you saw this on VISTA. Can you please add repro steps?

**Comment by charlesh88** [comment]
Testing notes:
1. Create or edit a Layout.
1. Add a telemetry element to the Layout. 
1. While selected, verify that the telemetry element can be statically styled with fill, color and border color via static styling, and the same when using conditional styling.

**Comment by charlesh88** [comment]
Verified fixed, testathon 05-12-20.
<img width="1693" alt="Screen Shot 2020-05-12 at 4 41 37 PM" src="https://user-images.githubusercontent.com/1056412/81756057-82811600-946f-11ea-801d-5d46735971e5.png">
