### ISSUE TITLE
Condition Set telemetry output being evaluated incorrectly

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2961]
Example on hulk: https://hulk.ndc.nasa.gov/viper/#/browse/0ff3a037-af01-497e-93b5-5ac3839da282/mine/0b834eca-5833-4f5d-a641-d58ac4f273a7?tc.mode=local&tc.timeSystem=utc&tc.startDelta=3610000&tc.endDelta=0&view=layout.view

Here's some recorded VIPER telemetry that varies between ~-1 and 567 over about an hour:
<img width="329" alt="Screen Shot 2020-04-22 at 9 45 36 PM" src="https://user-images.githubusercontent.com/1056412/80060135-a9889f80-84e2-11ea-8262-a6d3d06421f9.png">

Here's a Condition Set that evals that telemetry:
<img width="226" alt="Screen Shot 2020-04-22 at 9 34 22 PM" src="https://user-images.githubusercontent.com/1056412/80059749-96290480-84e1-11ea-8d2a-531b626304e9.png">

When the Condition Set is viewed on its own in the main view, the conditions are matching real-time data as expected. But when the CS is dropped into a Layout as telemetry, or is used to control conditional styling, the evaluator isn't working properly. 

What appears to be happening is that historic values within the current Time Conductor range are being included in the evaluation, but shouldn't be. For example, consider this: the TC is set to 1 minute, constraining available historic values to a narrow band:
<img width="339" alt="Screen Shot 2020-04-22 at 9 52 40 PM" src="https://user-images.githubusercontent.com/1056412/80060651-edc86f80-84e3-11ea-9065-dcdfc9b06b56.png">

In this case, the CS is evaluating as expected, showing an output of 65% based on the value being greater than 100.

But, setting the TC to 2 hours brings the max value of 566 into view:
<img width="347" alt="Screen Shot 2020-04-22 at 9 53 32 PM" src="https://user-images.githubusercontent.com/1056412/80060762-32eca180-84e4-11ea-8f16-1f9810814e04.png">

Note that even though the current value is 197 and the CS should be matching and displaying 65%, it shows 92%, which is a match against values greater than 500. So the historic 566 value is being used as part of the matching, but should not be, as there are much more current values closer to "now" that should be the ones being evaluated.

IMO, this is a major bug and could cause erroneous displays - we should fix ASAP. 

fix in master and in vista-r4.4-rc6

**Comment by nikhilmandlik** [comment]
Verifiled not fixed in testathon 05/12/20

<img width="1145" alt="Screen Shot 2020-05-12 at 3 55 52 PM" src="https://user-images.githubusercontent.com/1292612/81753704-3b902200-9469-11ea-9243-7b566e689f00.png">

**Comment by charlesh88** [comment]
@nikhilmandlik I think you're seeing the stalled telemetry evaluator problem.

**Comment by nikhilmandlik** [comment]
> @nikhilmandlik I think you're seeing the stalled telemetry evaluator problem.

This issue happened after testing https://github.com/nasa/openmct/issues/3032, wondering if it is related.

**Comment by charlesh88** [comment]
Verified fixed, testathon 05-12-20.
<img width="1693" alt="Screen Shot 2020-05-12 at 4 37 32 PM" src="https://user-images.githubusercontent.com/1056412/81755880-e7883c00-946e-11ea-8b11-7368a9f5f7dc.png">
