### ISSUE TITLE
[Display Layout] A better workflow for adding plots into display layout

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#2973]
At the moment, users have to create an overlay or stacked plot to add endpoints to display layouts. 
A suggested workflow is - users are able to drag endpoints directly into Display Layout and then choose wether they want an alphanumeric, plot or table

**Comment by charlesh88** [comment]
- I think when you add a telem to a layout, you get a choice of how it's added: alpha, (overlay) plot, or telem table. Choosing plot or table creates child objects in the composition of the layout that are visible and exactly the same as if they'd been pre-created. There may be a some strategies around automatic naming that could streamline the UX here, something like '<Telem name> Plot'.
- This approach is very consistent with the model that the user already understands, and allows us to use all the existing editing  / properties / Inspector UI elements to manage child objects.
- Right now, sub-object editing allows you add to a plot or a table when you're editing it in the Layout. So the user could customize the composition of these new auto-created objects as they see fit.
- The user should be able to switch the 'view type', but this isn't the same as a View Switcher. It's more like converting from one object type to another. Going from plot to table doesn't effect composition, but going from both of those to alpha does if the user has more than one child element in that composition, so we'd have to figure that out. Maybe you can't go that direction, or we create an alpha view for each child element. 
- If we end up doing this object conversion, this could also be made available at the main view level to allow plots (both types) to be converted to tables and back.
- No doubt, there is nuance here that needs to be thought through. If you auto-create a plot, then use that plot elsewhere, then convert it to a table, what happens? Switching from a plot to a table means that defined properties unique to each view might be lost, make sure the user understands.

**Comment by deeptailor** [comment]
## Testing Notes

1. Create a new Display Layout.
2. Add a telemetry element (sine wave/event generator/etc.). It will be selected.
3. Verify that the first icon in the toolbar is the "View switch" icon button menu:
4. Click the button and change the view to a plot or table;
5. Click the button again and verify that "Alphanumeric" is available as an option in the menu, and that the menu entry uses the proper glyph

**Comment by charlesh88** [comment]
Verified fixed Testathon 06-22-20.

**Comment by akhenry** [comment]
Partially fixed. 

I've found one edge case that I think is problematic. I can convert from alphas, overlay plots, and tables, to stacked plots. I can't convert from a stacked plot to any other type. These means I can be flipping through the different display options available and hit a dead end that I can't recover from. I'd suggest we either need conversions from stacked plots to the other types, or just to suppress stacked plots as an option for now.

**Comment by jvigliotta** [comment]
6/22/20 - Noticed the same as Andrew above. Once you go Stacked Plot, you don't go back.

**Comment by deeptailor** [comment]
Suggestion to convert from stacked plots to alpha's

**Comment by charlesh88** [comment]
6/22/20: And also, you can't create a Stacked Plot from a single initial telem source, like a SWG - but you should be able to.
Let's discuss Stacked Plots: the one complication I see here is that a Stacked Plot can contain Overlay Plots, meaning there is more granular grouping structure available to them that other views don't replicate. I'd suggest that such a Stacked Plot would "flatten out" if converted, and should be convertible to all the other view types.

**Comment by nikhilmandlik** [comment]
Verified. Testathon 6/22/2020

**Comment by davetsay** [comment]
Found issue when switch object view inside display layout

Steps to Reproduce.

1. create a display layout
1. drag in an object with plot and table views (in this case a condition set)
1. switch object view to telemetry table view
1. save display layout
1. refresh browser
1. observe object is now missing

![missing object after switch view](https://user-images.githubusercontent.com/3614296/85343536-f583a080-b4a1-11ea-8435-08754ecfa958.gif)

**Comment by nikhilmandlik** [comment]
Verified fix. Testathon 7/01/2020

**Comment by jvigliotta** [comment]
Verified Fixed (w/SWGs): Testathon 07/01/2020

**Comment by akhenry** [comment]
Created new issue #3142 to address https://github.com/nasa/openmct/issues/2973#issuecomment-647811721
