### ISSUE TITLE
[Time Views] Basic prototype Time View that supports composition with imagery

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#2977]
Define a basic view that shows a time axis, and supports composition of image objects. This should be consistent with early design sketches, which will be supplied separately. Images should be shown as thumbnails at appropriate points along the axis that reflect their timestamp.

Time axis should use D3, refer to Time Conductor for an example of this.

Success criteria:
1. A new "Time View" that shows just an axis by default, where the start and end correspond to the current conductor start and end
2. Dragging and dropping imagery into this view should result in image thumbnails being added along the timeline, with the position corresponding to image timestamps.

**Comment by charlesh88** [comment]
@charlesh88 to work with @jvigliotta for design guidance.

**Comment by jvigliotta** [comment]
@charlesh88 nice! Do we want to set up a meeting to go over this?

**Comment by charlesh88** [comment]
This functionality to be included in the new Timestrip View that @shefalijoshi is working on.

**Comment by charlesh88** [comment]
### Testing Notes
1. Create or edit a Time Strip view. 
2. Add image telemetry to the composition.
3. Verify that images are shown in the strip. Note that if imagery is close enough together in time, the actual imagery may not be displayed until rolled over with the mouse:

Images too close to be displayed in the strip:
![image](https://user-images.githubusercontent.com/1056412/134083256-adf83e20-0543-4f62-9fc3-ee3266e61310.png)


Images far enough apart in time to be displayed:
![image](https://user-images.githubusercontent.com/1056412/134083058-b43129e0-3afb-4ca4-9061-1b814de804ba.png)

4. Hovering over an image should bring it to the fore:
![image](https://user-images.githubusercontent.com/1056412/134083375-7b440758-c0d2-46b6-bab4-6ebcee1692d8.png)


5. Clicking a thumb in the strip should display the image in large view:

**Comment by charlesh88** [comment]
Verified Testathon 9-20-21.

**Comment by shefalijoshi** [comment]
Reopening as this doesn't work for non example imagery due to assumption of 'time' property

**Comment by charlesh88** [comment]
Testathon 9-28-21, NOT fixed: clicking an image in the thumbstrip view should display the same image paused in large view, but instead always displays the latest image.

![image](https://user-images.githubusercontent.com/1056412/135173046-495b7948-44f8-4556-bd27-0e4b0e11b701.png)


![image](https://user-images.githubusercontent.com/1056412/135172967-fd8739ce-ef47-4e7f-8e86-4a9ee39cd372.png)

**Comment by shefalijoshi** [comment]
Issue found:
Hovering over an image in the time strip view continually requests an image from the server:
![image](https://user-images.githubusercontent.com/5247066/135173622-fbc513c2-4f02-46ec-95e0-e7bad6119f1d.png)

**Comment by jvigliotta** [comment]
Issue:
Some lines seem to be behind the strip. Also, images aren't showing in small mode (if they're supposed to).

<img width="1172" alt="Screen Shot 2021-09-28 at 3 35 50 PM" src="https://user-images.githubusercontent.com/12013460/135175076-08df8abd-f7cb-48c7-b22c-1a0687750cbd.png">

**Comment by charlesh88** [comment]
Testathon 9-30-21: verified fixed.
