### ISSUE TITLE
[Time Conductor] Date-time picker improperly z-indexed

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#298]
As seen in [this comment](https://github.com/nasa/openmctweb/issues/297#issuecomment-156261548), recent CSS changes cause date pickers from the time conductor to be rendered "underneath" other DOM elements

Temporary workaround is to add `div.css('z-index', 75);` from the `MCTPopup` directive (in platform/commonUI/general) to explicitly force a higher z-index. Would be better to assign a class to popups (or similar) which handles this behavior (or whatever other behavior is appropriate here)

**Comment by charlesh88** [comment]
Fixed.
