### ISSUE TITLE
Sporadic duplication of telemetry points

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2982]
Seen on hulk as of 04/29/20 and for about the last week or two. Telemetry points in the tree are being duplicated sporadically. This doesn't occur for items not in the "VIPER" directory.

Note that selecting a node selects all of its "clones":

**Comment by deeptailor** [comment]
@charlesh88 seems like a dictionary or object provider issue

**Comment by merose** [comment]
@charlesh88, were you doing any zoom activity on the plot? We've previously discussed a known issue with Yamcs/OpenMCT and zooming.
