### ISSUE TITLE
[Conditionals] Condition Sets' default condition has bad text

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2987]
While editing a Condition Set, "Define criteria" should not be present in the default criterion - there is no criteria to define. Make blank instead.
![Screen Shot 2020-04-29 at 10 16 55 PM](https://user-images.githubusercontent.com/1056412/80674625-50cb8080-8a67-11ea-98ad-f130b9633a98.png)

When browsing, "When all else fails" is too cheeky (this is the fault of @charlesh88 who left this in the UI spec). Change to "When no other condition is matched"
![Screen Shot 2020-04-29 at 10 17 05 PM](https://user-images.githubusercontent.com/1056412/80674764-a3a53800-8a67-11ea-83ff-c10b6a75ecfb.png)

**Comment by unlikelyzero** [comment]
Verified in 6/25
