### ISSUE TITLE
[Conditionals] Condition Set using "any | all telemetry" summarizes State badly

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2988]
When a telemetry element that has state as an output (like another Condition Set) is included in a Condition Set's condition criteria, and that criteria uses "any | all telemetry", the summary appears to use an array index of the selected value (in this case, "High"). See red arrows in image.
![Screen Shot 2020-04-30 at 12 52 17 AM](https://user-images.githubusercontent.com/1056412/80686107-140a8400-8a7d-11ea-8d02-cf4ffdb86598.png)

When the criteria uses the telemetry element explicitly (green arrows) the summary is correct. "any | all telemetry" should use the same approach.

**Comment by shefalijoshi** [comment]
**Testing instructions:**
Create a new condition set
Add a condition using a state generator and configure it's Output to a String (example call it "High" or "Low")

Create a second condition set
Drag the first condition set into this one as telemetry
Add a condition using the condition set using the metadata "State" is "High" or "Low" or whatever the output string was set to.
Ensure that the description of the Condition shows the output string and not the index.

**Comment by davetsay** [comment]
Verified

**Comment by jvigliotta** [comment]
Testathon: 08/24 - Fixed
