### ISSUE TITLE
[Notebook] Notebook persistence error notifications on hulk when deleting entries

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2993]
Seen on hulk quite consistently as of 4/30/2020:
![Screen Shot 2020-05-01 at 12 28 41 AM](https://user-images.githubusercontent.com/1056412/80790075-bc365080-8b42-11ea-9408-3c2893872c0a.png)

Not sure of cause, but seems to coincide with navigating within Notebook pages or deleting entries. No errors are thrown to the console.

**Comment by nikhilmandlik** [comment]
Was able to get console error, looks like related to following error, 

<img width="1680" alt="Screen Shot 2020-05-01 at 9 26 05 AM" src="https://user-images.githubusercontent.com/1292612/80821564-da756e00-8b8d-11ea-97b4-2b7874fa4a44.png">

**Comment by akhenry** [comment]
This is almost certainly the same thing as https://github.com/nasa/openmct/issues/2918

It's to do with Couch DB object version numbers but I'm not sure why the objects we're sending to Couch are out of date. Some investigation needed.
