### ISSUE TITLE
Moment 2.25.0 breaks build

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#2999]
It seems that for whatever reason Webpack exposes the moment dependency differently with 2.25.0 than prior versions of moment.js. eg. 2.24.0 works fine. Others have reported issues building with 2.25.0 and Webpack (eg. https://github.com/moment/moment/issues/5486, https://github.com/moment/moment/issues/5489, https://github.com/moment/moment/issues/5491) so it does appear that something about the packaging has changed. The moment team, to their credit, released a hotfix today, but upgrading to the 2.25.1 hotfix did not resolve our issue.

In brief, it seems that moment is suddenly being exposed as an ES6 dependency with a "default" export to our older code that uses `require` and `define` dependencies. The obvious fix is to just use moment.default in the places in our source where we are using `require` or `define` to import it. This introduces another problem however, because moment-timezone does not support es6 modules and Webpack. [There has been an outstanding issue since 2017 about this](https://github.com/moment/moment-timezone/issues/449).

**Comment by jvigliotta** [comment]
Verified 5/12/2020

**Comment by akhenry** [comment]
Verified fixed, 05/12/2020
