### ISSUE TITLE
[Plots] Drag-zoom behavior inconsistent when dragged off plot area

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#3004]
When dragging and zooming in Vista, if the zoomed area mouse click is released off of the plot, the zoom doesn't actually release. Instead, when the user mouses back over the plot, the area is still there. To clear the area, the user clicks, and rather than zoom, the plot's sticky plot feature activates. On mouse release, zoom area should release if the mouse is not in the plot context.

**Comment by JoelMcKinnon** [comment]
Testing Instructions:

1. Zoom plots using the marquee zoom, and move the cursor outside the plot element while still zooming.
2. Release the mouse while outside the plot element.
3. The zoom marquee gesture should end even when released outside the plot element.

**Comment by charlesh88** [comment]
Verified fixed testathon 05-12-20.

**Comment by nikhilmandlik** [comment]
Verifiled fixed in testathon 05/12/20

**Comment by JoelMcKinnon** [comment]
Verified as described, but another oddity. If you select a part of a plot and drag just off the bottom of the plot area it behaves as expected. Marquee area about like the following:
![image](https://user-images.githubusercontent.com/6541399/81753355-75145d80-9468-11ea-87c1-a7b76958b033.png)

Zooming and dragging to bottom of plot area:
![image](https://user-images.githubusercontent.com/6541399/81753141-fcad9c80-9467-11ea-86f8-291a4ff5007a.png)

but if you drag way off the bottom of the page you get something like this:
![image](https://user-images.githubusercontent.com/6541399/81753252-3ed6de00-9468-11ea-8505-38679f8f23bb.png)

**Comment by davetsay** [comment]
Verifiled fixed in testathon 05/12/2020
