### ISSUE TITLE
[Notifications] Need a clear all notifications option

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#3006]
When there are hundreds of error notifications, users have to clear each one separately, this can become very daunting. 

Need a clear all notifications option. 

@charlesh88 @akhenry - Thoughts?

#### Testing instructions:

1. Install 'example.notifications' plugin on line 41 of index.html
2. Using the example notifications indicator, generate a bunch of alerts, error etc messages
3. Click on the new notifications indicator to see the notifications
4. Click on the clear all notifications and verify the notifications are cleared

**Comment by akhenry** [comment]
I don't see a problem with this. We could just add a button to the notification popup.

**Comment by nikhilmandlik** [comment]
Fixed in #3068 need to verify

**Comment by jvigliotta** [comment]
Verified Fixed.

**Comment by charlesh88** [comment]
Verified Fixed in Testathon 6/1/2020

**Comment by JoelMcKinnon** [comment]
Verified fixed in Testathon 6/1/2020

**Comment by nikhilmandlik** [comment]
Verified fixed in Testathon 6/1/2020
