### ISSUE TITLE
[Tabs View] We should store current tab information in the url

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#3014]
Requested by JPL missions - When users share links of tabs view, the users loose context of which tab was being shared. 

Thoughts @charlesh88 and @akhenry

**Comment by deeptailor** [comment]
There are 2 ways to deal with this:

1. Store current tab metadata in the url
2. Store current tab metadata in the tabs domainObject.

My vote is for the second solution, it will solve current tab information when used in display layouts or flexible layouts without polluting the url

**Comment by charlesh88** [comment]
Verified not fixed during testathon 05-12-20:
1. Created tabs view with multiple views.
1. Clicked to tab 2, then copied URL.
1. Clicked to tab 4.
1. Navved to another object entirely in tree.
1. Pasted copied URL into browser address bar, hit enter.
1. View refreshes to tab 4.

**Comment by nikhilmandlik** [comment]
Verified partial fixed , in Testathon 05/12/20
It always remembers last tab accessed. (as @Deep mentioned, current tab metadata is in domainObject instead of url)

**Comment by jvigliotta** [comment]
Testathon 07/13 - Verified Fixed
Looks like Issue Charles mentioned is good.
No other issues noticed.

**Comment by JoelMcKinnon** [comment]
Testathon 07/13 - Verified Fixed

**Comment by akhenry** [comment]
Verified fixed 07/13/2020

**Comment by charlesh88** [comment]
Verified Testathon 07/13/2020.

**Comment by davetsay** [comment]
Verified in VISTA

**Comment by nikhilmandlik** [comment]
Verified. Testathon 7/13/2020
