### ISSUE TITLE
[Conditionals] Empty Requests should be handled properly

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#3027]
Realtime only telemetry endpoints making requests or requests returning no results are returning malformed data, breaking plots.

Steps to replicate
1. Create a condition set
1. Add a telemetry endpoint that is realtime only (vista)
1. Complete the condition set
1. Drop this condition set into a plot and observe no data is plotted

**Comment by akhenry** [comment]
Based on discussion 05/12/2020 cannot be easily verified in Open MCT. Corresponding issue will be created in VISTA repo and verified there.
