### ISSUE TITLE
[Plots] "$digest in progress" error in plots

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3028]
Occasionally a `$digest in progress` error has been observed in the console when viewing plots, or layouts containing plots. 

I have been unable to reproduce consistently.

**Comment by nikhilmandlik** [comment]
Verified fix in Testathon 05/12/20

**Comment by davetsay** [comment]
Verified fix in Testathon 05/12/20
various changes done including conditional styles. no console errors over 5+ mins
