### ISSUE TITLE
[Conditionals] Condition Sets cannot be used as telemetry for other Condition Sets

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#3029]
Condition Sets should be able to be used as telemetry for other Condition Sets

Steps to replicate issue
1. Create a condition set
1. Create another condition set and drop original condition set in
1. Complete configuration of condition set (with nested condition set) and observe that no configuration will result in a match / output other than default

**Comment by charlesh88** [comment]
Verified fixed in testathon 05-12-20.

**Comment by nikhilmandlik** [comment]
Verified, fixed in Testathon 05/12/20
