### ISSUE TITLE
[Sine Wave Generator] Add randomness to the generated values

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3030]
For various demos, simulations, etc. we would benefit from having more realistic looking data. A simple way to do this is to add some randomness to sine wave generators. A long-period sine wave generator can show a long-term trend, with noise in the data, mimicking data seen in real-world scenarios.

eg.

![Screen Shot 2020-05-12 at 1 39 59 PM](https://user-images.githubusercontent.com/4215777/81743175-2067e700-9456-11ea-9702-a633ed04a456.png)

**Comment by deeptailor** [comment]
Verified works as intended.

**Comment by charlesh88** [comment]
Verified fixed in testathon 05-12-20.
