### ISSUE TITLE
Removing telemetry resets any/all telemetry criteria

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#3032]
Steps to reproduce:

- Create a condition set with at least 2 telemetry and one condition with 2 criteria
- The first criterion should use Any Telemetry or All Telemetry. The second can be a specific telemetry object
- Save the condition set
- Edit the condition set and remove all the telemetry in use.
- Observe: The Any/All telemetry criterion gets reset

**Comment by charlesh88** [comment]
Verified fixed in testathon 05-12-20.

**Comment by nikhilmandlik** [comment]
Testathon: 05/12/2020

<img width="699" alt="Screen Shot 2020-05-12 at 3 12 55 PM" src="https://user-images.githubusercontent.com/1292612/81750905-42b43180-9463-11ea-9514-645c85a7ae70.png">
