### ISSUE TITLE
[Plots] Should not make requests every time a user clicks on the plot

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#3033]
Plots should not be requesting new data every time a user clicks on the plot. It should only re-request when the user uses marquee zoom or pan.

## Steps to Reproduce
1. Use console to set a breakpoint inside of `request()` in `TelemetryAPI.js`
1. Open a plot view
1. Observe that breakpoint is hit
1. Resume app
1. Zoom or pan and observe that breakpoint is hit again
1. Resume app
1. click and observe that breakpoint is hit again

## Behavior
**Expected** - Request not called on click (Breakpoint is not hit on click)
**Actual** - Request is called on click

**Comment by davetsay** [comment]
Verified 05/15/2020

**Comment by nikhilmandlik** [comment]
Able to reproduce using, 

1. Use console to set a breakpoint inside of request() in TelemetryAPI.js
1. Open a plot view
1. Observe that breakpoint is hit
1. Resume app
1. Zoom and observe that breakpoint is hit again
1. Pan and observe that breakpoint is hit again
1. Now every click on plot hits breakpoint

**Comment by ozyx** [comment]
Verified Testathon 09/30/22
