### ISSUE TITLE
[Notebook] Clicking on an embed in a notebook entry does not result in bounds change

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3034]
![Screen Shot 2020-05-12 at 3 30 18 PM](https://user-images.githubusercontent.com/4215777/81752040-89a32680-9465-11ea-947a-c114fcd9f0f3.png)

### Steps to reproduce
1. Switch to realtime mode
2. Create a new notebook
3. Drag a SWG into the first entry
4. Click on the SWG embed link

### Expected behavior
User is navigated to embedded SWG, conductor bounds are changed to the bounds when the object was embedded, and conductor mode is changed from realtime to fixed

### Actual behavior
User is navigated to embedded SWG, but conductor bounds do not change. Conductor mode remains in realtime mode.

**Comment by charlesh88** [comment]
Verified fixed testathon 05-15-20. Filing followup issue for "Time bound values changed" message when bounds have not actually been changed.
