### ISSUE TITLE
LADTables plugin needs tests

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#3044]
LadTables plugin currently does not have testing.

Testing:
1. run npm run test (you can add fdescribe to any lad table root describes for speedier tests)
2. verify output has no failing tests

**Comment by akhenry** [comment]
Verified fixed 06/22/2020

**Comment by deeptailor** [comment]
Verified fixed 06/22/2020

**Comment by JoelMcKinnon** [comment]
Verified fixed 06/22/2020

**Comment by nikhilmandlik** [comment]
Verified. Testathon 6/22/2020
