### ISSUE TITLE
[Notebook] Dynamic Notebook content syncing

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3046]
Currently, if two users are looking at the same Notebook at the same time, they will not see updates to the Notebook's structure and entry content without refreshing their browser. This will almost certainly not be sufficient for operations, where users will need to see updates live as they happen.

**Comment by jakeaston** [comment]
I've been looking in to this over the past few days. I've been hoping to use the notebook as a dynamically generated log for system events, but likewise will not update if the user has the notebook already loaded.

**Comment by akhenry** [comment]
Closed by https://github.com/nasa/openmct/issues/3784 Note that this will only work if the object provider being used implements the `observe` function, which right now is only our Couch provider. If this is needed for LocalStorage as well, this issue should be reopened.
