### ISSUE TITLE
Notebook embed link notifies that time bound values have changed, even when they haven't

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3051]
Related to fixes in #3034. If a Notebook entry embed link is clicked to nav to a view in a Fixed Timespan Time Conductor context, the user still sees a "Time bound values changed" message when the bounds have not actually been changed.

### Steps to reproduce:
1. Switch to realtime mode in the Time Conductor.
1. Create a new Notebook.
1. Create a new Sine Wave Generator if you don't have one already.
1. Drag the SWG into the Notebook to create a new entry.
1. Click on the link to the SWG in the Notebook embed.
1. Observe: the TC will change to Fixed Time mode and the Start and End datetimes will be set based on the set span of the TC at the time of the embedding. You will be navved to the SWG. You will see a notification that says "Time bound values changed to fixed timespan mode". Do not touch the Time Conductor.
1. Nav back to the Notebook, click the SWG link again.
1. **Expected**: nav to the clicked object without a notification.
1. **Actual**: you will see a notification that says "Time bound values changed" even though the bounds have not changed.

#### Extra Verifications:
1. Play around with Time Conductor values (eg: start, end, time mode etc) and nav back to the Notebook, click the SWG link again.
1. Also add snapshots to Notebook at different time values (mix-match real time/fixed time values)
1. Observe that it shows correct notifications.

**Comment by jvigliotta** [comment]
Verified Fixed.

**Comment by charlesh88** [comment]
Verified Fixed in Testathon 6/1/2020
