### ISSUE TITLE
[Plots] Alt+click pan error causes pan to not be released

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#3052]
In a plot, alt+click pan can result in an error that causes the pan to not be released.

To reproduce:
1. Create Overlay Plot
2. Add Sine Wave Generator
3. Alt+click on the plot and pan
4. Release Alt key FIRST (error in console)
![Screen Shot 2020-05-15 at 4 28 47 PM](https://user-images.githubusercontent.com/12013460/82103795-4648f200-96c9-11ea-8b15-4a4ddb888b3f.png)
Now the mouse will continue to be locked in pan
5. Alt+click again
6. Release moust button FIRST, then Alt
7. Back to normal

Currently, I believe, Alt+click pan is more of a less-used feature, but definitely something we need to look at.

**Comment by nikhilmandlik** [comment]
Testathon 07/13/2020:
Verified, Fixed.

**Comment by jvigliotta** [comment]
Testathon: 07/13 - Verified Fixed.

**Comment by JoelMcKinnon** [comment]
Testathon: 07/13 - Verified Fixed.

**Comment by charlesh88** [comment]
Verified Testathon 07/13/2020.
