### ISSUE TITLE
[Documentation] Update code standard

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3056]
Our code standard is a few years old now, and includes items that are no longer relevant in the ES6 era. It should be updated to reflect current best practices.

It should:
1. Automate as much as possible. That way there is less to remember.
2. Where it can't be automated, guidance should be brief and focused on highest value items. Complex and detailed rules that can’t be automated will be forgotten by developers and reviewers.

**Comment by shefalijoshi** [comment]
Verified! :)
