### ISSUE TITLE
[Standards] Enable additional ESLint rules that require manual code changes

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3059]
An additional issue intended to further address and close https://github.com/nasa/openmct/issues/3056

### Proposal
1. Enabling the following ESLint rules which require code changes. Some can be addressed automatically using `npm run lint:fix`

    #### Trivial code changes necessary
    https://eslint.org/docs/rules/no-unused-expressions
    `"no-unused-expressions": "error",`
    https://eslint.org/docs/rules/no-useless-concat
    `"no-useless-concat": "error",`
    https://eslint.org/docs/rules/radix
    `"radix": "error",`
    https://eslint.org/docs/rules/require-await
    `"require-await": "error",`
    https://eslint.org/docs/rules/no-alert
    `"no-alert": "error",`
    https://eslint.org/docs/rules/no-useless-constructor
    `"no-useless-constructor": "error",`
    https://eslint.org/docs/rules/no-duplicate-imports
    `"no-duplicate-imports": "error",`

    #### More involved changes necessary
    https://eslint.org/docs/rules/array-callback-return
    `"array-callback-return": "error",`
    https://eslint.org/docs/rules/no-invalid-this
    `"no-invalid-this": "error", // Believe this one actually surfaces some bugs`
    https://eslint.org/docs/rules/func-style
    `"func-style": ["error", "declaration"],`
    https://eslint.org/docs/rules/no-var
    `"no-var": "error",`

2. Upgrading ESLint to v7, accepting all new recommend rules, and additionally enabling the following rules:
     https://eslint.org/docs/rules/default-case-last
    `"default-case-last": "error",`
    https://eslint.org/docs/rules/default-param-last
    `"default-param-last": "error",`
    https://eslint.org/docs/rules/grouped-accessor-pairs
    `"grouped-accessor-pairs": "error",`
    https://eslint.org/docs/rules/no-constructor-return
    `"no-constructor-return": "error",`
    https://eslint.org/docs/rules/one-var
    `"one-var": ["error", "never"],`

This issue could be broken up into multiple PRs using the groupings above, in order to minimize the code diffs involved.

**Comment by JoelMcKinnon** [comment]
Created branch eslint-trivial-changes to work on first group. Only ten violations are seen and they do look pretty trivial. Will do a PR just for those, then move on.

**Comment by akhenry** [comment]
### Testing notes
This issues involves a very large number of minor code changes touching on every aspect of the application. Individual code changes are all low risk, but due to the volume of changes bugs are possible.

General testing should be performed on basic functionality (creating objects, editing object attributes, editing layouts, etc.), and the JavaScript console observed for error messages.

**Comment by davetsay** [comment]
Went through two testathons with no major bugs found. Verified.
