### ISSUE TITLE
[Layout] Tree refactor

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#3060]
Update tree to show one node (plus children w/lazy loading if applicable) at a time and its ancestors.

Currently you can have multiple nodes/children open. If there are MANY children in a node the vue component for tree items can be loaded many times causing performance issues.

**Testing:**
When using the tree note the following:
- Only 1 set of children are open at a time.
- Any parent elements are shown above the currently viewed item and it's children.
- If the amount of children being viewed exceeds the screen size, the child container should be able to be scrolled.
- Clicking the rightward facing arrow will drill down if children exist.
- Clicking the leftward facing arrow will reset to that items children.
- Any time you reload, the directory you were last viewing should be showing.
- If you reload and the item currently being viewed is in that directory, it should be scrolled into view in the tree.
- If you click the "sync" button and the actively viewed item is in another directory of the tree, that directory should open and if applicable, the item should be scrolled to.
- Clicking the "sync" button while in the directory of the object being viewed, should scroll to the object in the tree if applicable.
- If you resize the screen the tree (with scroll active) should accommodate the new size.

**Comment by shefalijoshi** [comment]
**Tested on 8/24/2020:**
Did an npm install on master
npm start
Reloaded my local (localhost:8080)

I see Missing: browse in the tree before My Items.
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/5247066/91103191-c7484b80-e61f-11ea-919b-0397a8250253.png">

**Comment by deeptailor** [comment]
Found an issue: #3321

**Comment by davetsay** [comment]
Found issue #3320

**Comment by charlesh88** [comment]
New associated problem found during Testathon Aug 28, 2020, reopened #3320.

**Comment by shefalijoshi** [comment]
Verified on 08/28/2020 - Missing: browse issue found before has been fixed.
