### ISSUE TITLE
Accessibility alerts for public facing website

### ISSUE THREAD

**Issue by JoelMcKinnon** [nasa/openmct#3070]
Using three different tools, audited the public facing website at https://nasa.github.io/openmct/.
- ANDI (https://www.ssa.gov/accessibility/andi/help/install.html): tool that provides on-page guidance of issues in five categories. Provided by SSA.gov in accordance with ADA.
- Lighthouse: Built-in chrome devtools tab providing audits for accessibility and other metrics.
- AXE: Chrome extension from Deque provides a tab for analysis of whatever page you are on.

Issues found:

**ANDI**:

Focusable Elements:
    - Elements with No Accessible Name (4)
    - Misuses of Alt attribute (3)
Graphics/images:
    - Elements with No Accessible Name (3)
    - Misuses of Alt attribute (1)
    - Graphics Alerts (1)
Links/buttons:
    - Elements with No Accessible Name (1)
    - Misuses of Alt attribute (3)
Structures:
    - Heading structure found. Determine if headings appropriately applied
Color contrast
    - Contrast Alerts (6)
    - Manual Tests Needed (32)

**Lighthouse:**
	Desktop: 24/100
	Mobile: 24/100

**AXE:**
	46 issues found

**Comment by unlikelyzero** [comment]
closing since these a11y alerts are out of date
