### ISSUE TITLE
Accessibility alerts for openmct app

### ISSUE THREAD

**Issue by JoelMcKinnon** [nasa/openmct#3071]
Using three different tools, audited two views of openmct; one with an empty tree and another with an overlay plot with three sign wave generators added.
- ANDI (https://www.ssa.gov/accessibility/andi/help/install.html): tool that provides on-page guidance of issues in five categories. Provided by SSA.gov in accordance with ADA.
- Lighthouse: Built-in chrome devtools tab providing audits for accessibility and other metrics.
- AXE: Chrome extension from Deque provides a tab for analysis of whatever page you are on.

**Issues found for empty tree view:**

**ANDI**:
Focusable Elements:
    - Elements with No Accessible Name (7)
Graphics/images:
    - Graphics Alerts (1)
Links/buttons:
    - Reference Alerts (1)
    - Link Alerts (2)
Structures:
    - No headings
Color contrast
    - Contrast Alerts (8)
    - Manual Tests Needed (10)

**Lighthouse:**
	Desktop: 32/100
	Mobile: 37/100

**AXE:**
	39 issues found

**Issues found for overlay plot view:**

**ANDI**:
Focusable Elements:
    - Elements with No Accessible Name (10)
    - Tab Order Alerts (2)
Graphics/images:
    - Elements with No Accessible Name (2)
    - Graphics Alerts (1)
Links/buttons:
    - Reference Alerts (13)
    - Link Alerts (10)
Structures:
    - Heading structure found. Determine if headings appropriately applied
Color contrast
    - Contrast Alerts (22)
    - Manual Tests Needed (5)

**Lighthouse:**
	Desktop: 32/100
	Mobile: 37/100

**AXE:**
	39 issues found

**Comment by unlikelyzero** [comment]
Closing since these a11y alerts are out of date
