### ISSUE TITLE
Conditional Styles for multiple items

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#3076]
Select multiple items in a layout. Only the styles that are applicable to all the items maybe be changed and displayed in the styles inspector.
- Static styles should work for multiple selection
- Conditional styles should work for multiple selection
- Mixture of styles should be overridden if conditional styles are applied.

**Comment by shefalijoshi** [comment]
Testing notes:

    Create or edit a Display Layout.
    Add some drawing objects, and a telemetry element.
    Select at least two objects and click the Styles tab.
    Click "Use Conditional Styling...".
    Set styles for different conditions.
    Click elsewhere to de-select the selected items.
    Single-click one of the previously selected items, and verify that conditional styling remains applied as previously set.
    Single click another of the previously selected items, repeat previous step verification.

Note: Using Conditional Styling on multiple objects is a one-time application; multiple-selecting items that use exactly the same conditional styling will still NOT present the edit interface, but will instead display the "Use Conditional Styling..." button. This was done for now to keep things simpler and may be addressed with future enhancements.

**Comment by charlesh88** [comment]
Verified in testathon 6/1/20

**Comment by nikhilmandlik** [comment]
Testathon 6/1/20:
1. Passed above test
1. Found error while applying style to individual box in display layout.
```
  [Vue warn]: Error in event handler for "persist": "TypeError: Cannot convert undefined or null to object"

found in

---> <StyleEditor> at src/plugins/condition/components/inspector/StyleEditor.vue
       <StylesView> at src/plugins/condition/components/inspector/StylesView.vue
         <Root>
```
```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at eval (StylesView.vue?10ee:470)
    at Array.forEach (<anonymous>)
    at VueComponent.removeConditionSet (StylesView.vue?10ee:467)
    at VueComponent.boundFn [as removeConditionSet] (vue.js?ba4c:195)
    at VueComponent.updateStaticStyle (StylesView.vue?10ee:506)
    at boundFn (vue.js?ba4c:193)
    at VueComponent.invoker (vue.js?ba4c:1989)
    at VueComponent.Vue.$emit (vue.js?ba4c:2497)
    at VueComponent.updateStyleValue (StyleEditor.vue?346a:211)
```

**Comment by charlesh88** [comment]
Based on Testathon results of 6/1, reopening this.

**Comment by shefalijoshi** [comment]
Testing notes:
In a display layout, test changing styles for different item types - boxes, lines (border), text as well as objects and alphanumerics.
In a display layout, test adding static styles initially and then using conditional styles to the same items
In a display layout, test adding conditional styling initially and then using static styles to the same items

**Comment by nikhilmandlik** [comment]
verified, fixed, Testathon 6/5/20:

**Comment by deeptailor** [comment]
Verified fixed - 6/22/2020

**Comment by charlesh88** [comment]
Verified fixed Testathon 06-22-20.
