### ISSUE TITLE
[Snapshots] Are holding on to outdated domainObjects when clicking on preview

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#3078]
To Reproduce:

1. Build a display layout, add a few items. 
2. Take a snapshot and save it in the snapshots container.
3. Make changes and save to display layout that you created in Step 1.
4. Navigate away from the display layout.
5. Click on the preview action from the snapshot in the snapshot container.
6. Notice the preview is of the time the snapshot was taken, not the current domainObject state

**Comment by akhenry** [comment]
Snapshots and notebooks should not be persisting domain objects at all. They should only persist object identifiers and fetch the associated object as needed.

**Comment by deeptailor** [comment]
@akhenry - I think this may constitute as a critical bug, I can see issues with domain objects being returned to an older state; and the user loosing the current state of the domain object

**Comment by charlesh88** [comment]
Verified fixed Testathon 08-03-2020.
