### ISSUE TITLE
[Telemetry Table] Allow users to optionally hide table headers

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#3086]
When screen real estate is minimal, users would like to be able to hide headers to make the most of the space available.

**Comment by deeptailor** [comment]
## Testing Notes:

1. Create a Telemetry Table
2. Add some telemetry (eg sine wave)
3. Notice the new option in the inspector for hide headers
4. Toggle the option and verify the table headers are toggled with the checkbox.

**Comment by jvigliotta** [comment]
Verified in Testathon: 6/23/20

**Comment by akhenry** [comment]
Verified Fixed 06/23/2020

**Comment by nikhilmandlik** [comment]
Verified. Testathon 6/22/2020
