### ISSUE TITLE
[Search] Move generic search to shared worker

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#310]
Move generic search behavior to a shared worker. Desired behavior is that domain objects which have already been indexed do not get re-indexed when a second window is launched. It's probably reasonable to make this distinction in bulk to simplify implementation (e.g. if Window 1 hasn't finished indexing, then Window 2 starts from the beginning; if Window 1 has finished, Window 2 doesn't start at all.)

Work-in-progress for this on branch open308search

**Comment by charlesh88** [comment]
Notes from tagup 10/26/16:
Pete: worth figuring out what the alternative is to shared web workers, which don't work in Safari, meaning this wouldn't work in iOS. Checkout IndexedDB.
Charles: this should tie into our multi-window investigation coming up soon, #1289.

**Comment by charlesh88** [comment]
Won't fix.
