### ISSUE TITLE
[Conditionals] Short circuit condition evaluation for performance

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3102]
Currently [we exhaustively evaluate every condition each time new data is received](https://github.com/nasa/openmct/blob/771fb9c04464480e3bacc6ed482b622b3f6fafeb/src/plugins/condition/ConditionManager.js#L314). We could short circuit this by stopping on the first condition that evaluates to `true`. Perhaps it would make sense to use [Array.some()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some) for this purpose?

**Comment by shefalijoshi** [comment]
**Testing Instructions:**

Create a condition set and drag telemetry into it
Create two conditions that would evaluate to true
Check that the first condition is highlighted as expected

Now change the 1st condition to evaluate to false
Check that the 2nd condition is highlighted.

**Comment by charlesh88** [comment]
Verified fixed Testathon Aug 28, 2020.

**Comment by jvigliotta** [comment]
Testathon 08/28: Verified Fixed
