### ISSUE TITLE
[Example Imagery] Console error on pause when start and end date is in future

### ISSUE THREAD

**Issue by nikhilmandlik** [nasa/openmct#3103]
#### Steps to reproduce:
1. Add a new Example Imagery object
1. change start time and end time to future date.
1. click on 'pause' and observe error in console.
```
Uncaught TypeError: Cannot read property 'selected' of undefined
    at VueComponent.setSelectedImage (ImageryViewLayout.vue?e401:188)
    at VueComponent.boundFn [as setSelectedImage] (vue.js?ba4c:194)
    at VueComponent.paused (ImageryViewLayout.vue?e401:158)
    at Proxy.boundFn (vue.js?ba4c:194)
    at click (ImageryViewLayout.vue?3994:106)
    at invoker (vue.js?ba4c:1989)
    at HTMLAnchorElement.fn._withTask.fn._withTask (vue.js?ba4c:1787)
setSelectedImage @ ImageryViewLayout.vue?e401:188
boundFn @ vue.js?ba4c:194
paused @ ImageryViewLayout.vue?e401:158
boundFn @ vue.js?ba4c:194
click @ ImageryViewLayout.vue?3994:106
invoker @ vue.js?ba4c:1989
fn._withTask.fn._withTask @ vue.js?ba4c:1787
```

<img width="1916" alt="Screen Shot 2020-06-22 at 3 21 51 PM" src="https://user-images.githubusercontent.com/1292612/85341083-2fea3f00-b49c-11ea-8414-e44c938c3484.png">

**Comment by jvigliotta** [comment]
## Testing
- Add new example imagery
- Set time bounds to future date (both end and start)
- Check the console for errors (used to be an undefined image url)
- Click Pause
- Check the console for errors

**Comment by davetsay** [comment]
Verified fixed 07/01/2020

**Comment by nikhilmandlik** [comment]
Verified fix. Testathon 7/01/2020

**Comment by JoelMcKinnon** [comment]
Verified fixed testathon 07/01/2020

**Comment by shefalijoshi** [comment]
Verified fixed
