### ISSUE TITLE
Stacked Plot Y axis jumps, hides axis values

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3105]
Seen during Testathon 06-22-20: the "tickwidth" in Stacked Plots appears to not being calculated properly, causing the Y axis of that view to hide tick values and sporadically jump around. This was not observed in standard plot views and Overlay Plots.

To replicate:
1. Set Time Conductor to Local UTC with a very small past time interval (00:01:00, or even 00:00:10) and 00:00:00 for the future.
1. Create a Stacked Plot and add one or more SWGs to it.
1. Observe: the Y axis will often compress to where it is overlapping into the units designation, and will sometimes completely hide the tick values as in the uppermost plot here:
![Screen Shot 2020-06-22 at 4 50 48 PM](https://user-images.githubusercontent.com/1056412/85346098-477bf480-b4a9-11ea-86bf-4c62d4a3b6f9.png)
1. Also observe that the axis will periodically expand and contract, causing a jumpy effect:
![Stacked Plot jumpy Y axis in Layout frame](https://user-images.githubusercontent.com/1056412/85346173-80b46480-b4a9-11ea-87bb-52471abe60df.gif)

Inspecting the code reveals the following:
![Stacked Plot jumpy Y axis browser Inspect](https://user-images.githubusercontent.com/1056412/85346336-f7516200-b4a9-11ea-9e78-bda7f3d883f4.gif)

tickWidth appears to be evaluated to 0, causing the width of `gl-plot-axis-area` to be set to 30px - this is responsible for the narrowing effect that is hiding tick values. This alternates with no style being set, which results in the axis area _not_ having a width setting, and reverting to the default CSS width of 60px, which allows shorter values to be displayed "properly".

**Comment by charlesh88** [comment]
Verified fixed Testathon July 1, 2020

**Comment by shefalijoshi** [comment]
Verified Fixed
