### ISSUE TITLE
[Performance] Add mct-refresh directive

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#311]
Add an `mct-refresh` directive (as prototyped in #303) which causes its contents to be re-rendered upon the mutation of some observed domain object.

Example of usage would look like:

``` html
<mct-refresh mct-object="domainObject">
    <span class="type-{{::domainObject.getCapability('type').getKey()}}">
        {{::model.name}}
    </span>
</mct-refresh>
```

...where `::`-prefixed Angular expressions are one-time-bound. The re-rendering of this content on mutation allows it to stay up-to-date, without using Angular watches (which become expensive in places like the tree, where there are many)

**Comment by VWoeltjen** [comment]
Should consider consolidating this with #312 as something like:

```html
<span mct-refresh="domainObject.getCapability('mutation').listen(observer)">
  {{::domainObject.getModel().name}}
</span>
```

...where the directive, instead of expecting an object with some `Observable` interface, simply evaluates an expression at link-time while passing in a function that, when triggered, will cause the contents to refresh.

**Comment by larkin** [comment]
Closing as we are moving away from angular directives for this sort of thing.
