### ISSUE TITLE
LAD Table Bug Fixes

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#3113]
Fixed some bugs on LAD Tables:

1. Was breaking on local time system (no formatter from telemetry for local), added error handling and warning.
2. Edge cases in race conditions and future time bounds, updated logic.

Found when working on #2929 

## Testing
- Create a LAD Table
- Add Sine Wave Generator
- Enable local time system (index.html)
`openmct.install(openmct.plugins.LocalTimeSystem());`
- Add local time system to time conductor menu options (index.html)
`{
    name: "Local",
    timeSystem: 'local',
    bounds: {
        start: Date.now() - THIRTY_MINUTES,
        end: Date.now()
    }
}`
- Change to local time system
  - Should work correctly now (no errors in console)
- Play around with time bounds (set future dates, past dates) make sure timestamps show or don't show based on bounds

**Comment by deeptailor** [comment]
Verified Fixed 07/01/2020

**Comment by akhenry** [comment]
07/01/2020 Not fixed. Investigating, but may not be an issue in the view.

**Comment by akhenry** [comment]
Issue was caused by bounds handling in openmct for VIPER. A separate issue has been raised there.
