### ISSUE TITLE
[Layout] Object removal from display layout, followed by task cancelation, doesn't consistently revert to pre-delete-attempt state

### ISSUE THREAD

**Issue by johnriedel** [nasa/openmct#3118]
Steps to reproduce error:
1. Add a display layout to "My Items" folder
2. In Display Layout main window, click "Save and Finish Editing"
3. Add a "State Generator" object to the Display Layout in the object tree
4. Select the Dispay Layout in the object tree so it's active in the main window
5. Note that you can see the State Generator in the display layout in the upper left corner of the main window
6. Click the Edit icon in the main window to edit the Display Layout
7. Select the State Generator object in the Display Layout in the main window
8. Click the trashcan icon to delete the State Generator object
9. Click OK when prompted with "Do you wish to continue?"
10. Note that the State Generator object is removed from both the Display Layout main window and the object tree, as expected
11. Click the "X" icon in the main window to cancel editing
12. Click OK when prompted with "Any unsaved changes will be lost. Continue?"
13. Note that the State Generator object reappears in the object tree, as expected
14. Note that the Display Layout in the main window now contains double the number of State Generators, which is incorrect and unexpected (double objects may be overlapping, so you may have to go into Display Layout edit mode and move one of the objects to see both).

Expected behavior: When an object is removed from the display layout in the main window, followed by a task cancelation, the display layout in the main window, and the object links that appear in the associated object tree, should be returned to their pre-delete-attempt state.

Actual behavior: When an object is removed from the display layout in the main window, followed by a task cancelation, the display layout in the main window duplicates/doubles the object that you attempted to remove.

(Ubuntu 16.04 - Firefox 77.0.1 64-bit, Chrome Version 70.0.3538.102 64-bit)

**Comment by johnriedel** [comment]
This issue is fixed by @deeptailor 's PR #3130. Closing this issue.

**Comment by JoelMcKinnon** [comment]
Confirmed fixed testathon 7/13/20

**Comment by nikhilmandlik** [comment]
Verified (Mac OS). Testathon 07/13/2020.

**Comment by charlesh88** [comment]
Verified Testathon 07/13/2020.
