### ISSUE TITLE
[Flexible Layout] Object link removal from object tree doesn't consistently remove object from Flexible Layout in main window

### ISSUE THREAD

**Issue by johnriedel** [nasa/openmct#3119]
Overview to reproduce error:
    1. Add an item to flexible layout, then "Save and Finish Editing"
    2. Select the child item in the object tree so that it's active in the main window
    3. Right-click and remove object. Notice it was removed from object tree but not flexible layout.

Detailed steps to reproduce error:
1. Add a State Generator to "My Items" folder
2. Add a Flexible Layout to "My Items" folder
3. In Flexible Layout main window, click "Save and Finish Editing"
4. Drag State Generator from object tree onto Flexible Layout in main window
5. Note that State Generator appears in Flexible Layout in main window, as expected
6. Note that a State Generator link appears under Flexible Layout in the object tree, as expected
7. In Flexible Layout main window, click "Save and Finish Editing"
8. In object tree, select the State Generator Link object that appears under the Flexible Layout object, so that it's active in the main window
9. Right-click State Generator Link object and select "Remove" to delete it.
10. Click OK when prompted with "Are you sure you want to continue?"
11. Select the Flexible Layout in the object tree so that it's active in the main window
12. Note that the State Generator is still visible in the Flexible Layout main window, which is incorrect and unexpected

Expected behavior: When an object link is removed from the flexible layout in the object tree, it should be removed from the flexible layout in the main window.

Actual behavior: When an object link is removed from the flexible layout in the object tree, it's not always removed from the flexible layout in the main window.

(Ubuntu 16.04 - Firefox 77.0.1 64-bit, Chrome Version 70.0.3538.102 64-bit)

**Comment by charlesh88** [comment]
Verified fixed Bug Bash 04-21-22

**Comment by unlikelyzero** [comment]
Verified fixed Bug Bash 04-21-22

**Comment by khalidadil** [comment]
Verified in Testathon on 04/21/22
