### ISSUE TITLE
[Performance] Add mct-observe directive

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#312]
Add an `mct-observe` directive (as prototyped in #303) which causes its contents to be re-rendered upon the firing of some callback.

Example of usage would look like:

``` html
<span mct-observe="someObservable">
    {{::someObservable.get()}}
</span>
```

...where `::`-prefixed Angular expressions are one-time-bound. The re-rendering of this content on callback firing allows it to stay up-to-date, without using Angular watches (which become expensive in places like the tree, where there are many)

**Comment by larkin** [comment]
closing as we're not using angular directives for this sort of thing.
