### ISSUE TITLE
[Flexible Layout] Object removal from flexible layout, followed by task cancelation, doesn't consistently revert to pre-delete-attempt state

### ISSUE THREAD

**Issue by johnriedel** [nasa/openmct#3120]
Steps to reproduce error:
1. Add a State Generator to "My Items" folder
2. Add a Flexible Layout to "My Items" folder
3. In Flexible Layout main window, click "Save and Finish Editing"
4. Drag State Generator from object tree onto Flexible Layout in main window
5. Note that State Generator appears in Flexible Layout in main window, as expected
6. Note that a State Generator link appears under Flexible Layout in the object tree, as expected
7. In Flexible Layout main window, click "Save and Finish Editing"
8. In Flexible Layout main window, click the "Edit" icon to edit the layout
9. Select the State Generator "frame" and click the trashcan icon to remove it from the layout
10. Click OK when prompted with "Do you want to continue?"
11. Note that the frame is removed from the Flexible Layout, as expected
12. Note that the State Generator link is removed from the object tree under the Flexible Layout, as expected
11. Click the "X" icon in the Flexible Layout main window to cancel editing
12. Click OK when prompted with "Do you want to continue?"
13. Note that the State Generator link reappears in the object tree under the Flexible Layout as expected
14. Note that the Flexible Layout in the main window now contains double the number of State Generators, which is incorrect and unexpected

Expected behavior: When an object is removed from the flexible layout in the main window, followed by a task cancelation, the flexible layout in the main window, and the object links that appear in the associated object tree, should be returned to their pre-delete-attempt state.

Actual behavior: When an object is removed from the flexible layout in the main window, followed by a task cancelation, the flexible layout in the main window, and the object links that appear in the associated object tree, don't consistently return to their pre-delete-attempt state.

(Ubuntu 16.04 - Firefox 77.0.1 64-bit, Chrome Version 70.0.3538.102 64-bit)

**Comment by charlesh88** [comment]
Verified fixed Bug Bash 04-21-22

**Comment by charlesh88** [comment]
Testathon 2024-03-20 cannot repro, fixed.
