### ISSUE TITLE
Open MCT Fails on multiple platforms

### ISSUE THREAD

**Issue by infinitymakerspace** [nasa/openmct#3127]
Good Day

I have now re-tried after waiting a couple of weeks.  Open MCT does not install and run on any of the Linux distributions I have tried (Ubuntu/Raspbian/MX19/PopOS/Fedora/Arch/Manjaro) nor on Windows with the latest stable release of NodeJS.  When will this project become usable again.

**Comment by akhenry** [comment]
@infinitymakerspace Hi, sorry about the problems you're having building Open MCT. I have just built the latest master on Ubuntu 16.04 with node v13.14.0, and on RHEL 6.10 with node v10.18.1 with no problems. Building on Windows is still an ongoing issue, but it's at least one that we understand. The linux build issue you're experiencing is more of a mystery...

The logs you've provided previously tell us there was a problem, but unfortunately don't shed much light on what the problem is. [Exit code 137 has been associated with memory issues](https://github.com/npm/npm/issues/4008), so it might be running out of memory during the build. Running the build on my laptop I am seeing memory usage get close to 2GB. If you're running on a system with limited resources (eg. a Raspberry Pi) this might be problematic.

**Comment by infinitymakerspace** [comment]
Weird as it did the same on a full bare metal dual xeon server with 32GB or RAM so it does not make any sense

**Comment by haisamido** [comment]
Clone this https://github.com/haisamido/openmct and then run:

make start

I have pull request for this.

**Comment by infinitymakerspace** [comment]
> Clone this https://github.com/haisamido/openmct and then run:
> 
> make
> make start
> 
> I have a pull request for this. This assumes you have make, docker and docker-compose.

Sorry not working

**Comment by haisamido** [comment]
> > Clone this https://github.com/haisamido/openmct and then run:
> > make
> > make start
> > I have a pull request for this. This assumes you have make, docker and docker-compose.
> 
> Sorry not working

What is it that is not working? What are the exact errors that you are seeing?

**Comment by infinitymakerspace** [comment]
I am not using docker.  I want to be able to npm install , npm start and
work from there, but packages keeps complaining about funding or that
packages used are insecure and out of date on both git repos.

**Comment by akhenry** [comment]
@infinitymakerspace Which repository are you seeing messages about insecure packages? This should not be happening. Also, could you try doing a fresh install (delete node_modules and package-lock.json) on a bare metal machine with > 4GB of RAM and let me know what happens? I'd like to get to the bottom of this.

**Comment by infinitymakerspace** [comment]
Hi there

Fresh install on both a 4gb machine and 16gb machine running Ubuntu 20.04
and 18.04 respectively and this is using the repo from the official nasa
open mct website

**Comment by akhenry** [comment]
I'm assuming you're using the master branch?

On the 16GB machine, in a new directory, could you please follow these steps exactly:
```
git clone https://github.com/nasa/openmct.git
cd openmct
npm install
npm start
```
Is it failing in `npm install` or `npm start`? If you're able to send us the output of your terminal, that would also help. You can email it to arc-dl-openmct@mail.nasa.gov

Could you also tell me which version of node you're using on this machine? I have an 18.04 machine that I can test this on, I'd like to recreate the exact same conditions.

**Comment by infinitymakerspace** [comment]
npm install.

**Comment by akhenry** [comment]
@infinitymakerspace Have just done a clean install from https://github.com/nasa/openmct.git on a Xeon machine running Ubuntu 18.04 with node v13.14.0, and everything built ok. 

This was a totally fresh environment that didn't even have node installed on it. I used [nvm](https://github.com/nvm-sh/nvm#installing-and-updating) to install node, then followed the steps that I posted previously. I didn't get any warnings about vulnerabilities, and I did not get any errors.

Let me know how you get on, I want to get you up and running with Open MCT.

**Comment by infinitymakerspace** [comment]
Many thanks I will redo the steps and use nvm and report back

**Comment by infinitymakerspace** [comment]
> @infinitymakerspace Have just done a clean install from https://github.com/nasa/openmct.git on a Xeon machine running Ubuntu 18.04 with node v13.14.0, and everything built ok.
> 
> This was a totally fresh environment that didn't even have node installed on it. I used [nvm](https://github.com/nvm-sh/nvm#installing-and-updating) to install node, then followed the steps that I posted previously. I didn't get any warnings about vulnerabilities, and I did not get any errors.
> 
> Let me know how you get on, I want to get you up and running with Open MCT.

Andrew Henry , you are the man, got it working.  Will make a personal note in my personal KB files for future reference.  Many thanks.  Warm regards from Port Elizabeth, South Africa.

**Comment by akhenry** [comment]
@infinitymakerspace That's awesome that you got it working, I'm relieved. 

I would love to understand what the issue was though. Did you use a different node version this time?

**Comment by infinitymakerspace** [comment]
I did not use nvm so ubuntu was installing the known "stable" version.  I
followed your procedure after first purging all previous nodejs installs.
And that worked.

Many thanks again. I am following you now on GitHub.

Regards
Gert
