### ISSUE TITLE
[Display Layout] When switching types and canceling edit, the switched item duplicates

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#3128]
Steps to reproduce:

1. Create a new display layout
2. Add a telemetry point and save.
3. Edit the Display Layout and switch the type of the telemetry point to a plot. 
4. Cancel edit (discard changes)
5. Observe that there are 2 alphanumerics now, instead of the original 1.

**Comment by johnriedel** [comment]
This is also similar to issue #3118.

**Comment by JoelMcKinnon** [comment]
Confirmed fixed 7/13/20.

**Comment by nikhilmandlik** [comment]
Verified. Testathon 07/13/2020.

**Comment by charlesh88** [comment]
Verified Testathon 07/13/2020.
