### ISSUE TITLE
[Performance] Change ng-model to mct-model

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#313]
Change the name of the `ng-model` attribute on the various directives where it is used to `mct-model`.

Using `ng-model` invokes the directive of the same name, attaching unwanted listeners. This also helps distinguish the differing behavior of the two.

For backwards compatibility, would be useful to fall back to `ng-model` when `mct-model` is not present. This usage should be clearly marked as deprecated and removed before a 1.0.0 release

**Comment by larkin** [comment]
closing as wontfix.
