### ISSUE TITLE
[Editable Views] Should be lock-able to prevent editing

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#3133]
Editable views should provide users with a locking mechanism that prevents users from accidentally editing them.

**Comment by deeptailor** [comment]
Testing Notes:

1. Create 2 Display Layouts.
2. In the first one add a bunch of boxes, lines, telemetry etc and save it. 
3. Click on the new lock button - This will lock the view from editing.
4. Try dragging and dropping items into this layout
5. Verify that you cant edit it.
6. Add the locked display layout to another layout
7. Verify the locked layout cannot be edited.

**Comment by nikhilmandlik** [comment]
Verified fix. Testathon 7/01/2020

**Comment by shefalijoshi** [comment]
Verified fix.
