### ISSUE TITLE
[Plots] Should be able to change marker style

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#3134]
All plots have square markers. Users should be able to configure plots to use different shape markers.

Instructions
1. Create a plot
1. Edit the plot
1. In inspector view, expand plot options, ensure Markers checkbox is checked, select Marker style from available styles
1. See that marker style changes for that plot

![plots - change marker](https://user-images.githubusercontent.com/3614296/86051774-cd002700-ba0a-11ea-8711-51b93b8a5c6f.gif)

**Comment by jvigliotta** [comment]
Testathon: 07/13 - Verified Fixed.

**Comment by JoelMcKinnon** [comment]
Testathon: 07/13 - Verified Fixed.

**Comment by deeptailor** [comment]
Verified Fixed - 07/13

**Comment by JoelMcKinnon** [comment]
Confirmed works with and without hardware acceleration enabled.

**Comment by nikhilmandlik** [comment]
Verified. Testathon 7/13/2020

**Comment by deeptailor** [comment]
Verified. Testathon 7/13/2020

**Comment by charlesh88** [comment]
Verified Testathon 07/13/2020.
