### ISSUE TITLE
[Performance] Don't two-way bind mct-model, parameters

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#314]
Don't two-way bind `mct-model` (formerly `ng-model`, #313) or `parameters` when used from an `mct-representation` or an `mct-include`; instead, watch these objects and pass them by value into the isolate scope.

This permits users of these directives to one-time-bind these values, without having an extra watch lingering to publish these back into the parent scope. (This directionality is not used in practice, in any event; `mct-model` usages most commonly, if not exclusively, write to some known property in the object to work around scope inheritance quirks.)

**Comment by larkin** [comment]
Closing as wontfix.
