### ISSUE TITLE
[Display Layout] - Switching types does not work for dictionary-based telemetry points

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#3142]
When adding or having added telemetry to a Layout, switching the type (to plot, table, etc.) does not work for telemetry points added from the dictionary. Need to investigate.

**Comment by deeptailor** [comment]
Testing Notes:

1. Create a Display Layout
2. Drag in some dictionary based telemetry points
3. Switch types to plots and tables.
4. Verify it works as expected.

**Comment by JoelMcKinnon** [comment]
Confirmed fixed testathon 7/13/20

**Comment by nikhilmandlik** [comment]
Verified on Hulk. Testathon 7/13/20

**Comment by charlesh88** [comment]
Verified on hulk 7/8 - 7/10/2020.
