### ISSUE TITLE
Removing telemetry for a matching condition causes output to stick

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#3143]
Seen during Testathon on hulk July 1, 2020 by both @charlesh88  and @JoelMcKinnon. Related to a problem documented in #2817.
1. Create a new Condition Set and add _only_ a single telemetry element to it.
1. Setup a condition that will match for values in the telemetry. For example, for a telemetry point that consistently has values over 145, setup a condition with a "greater than 140".
1. _While the condition is being matched_, remove the telemetry point from the Elements pool. The set will become stuck on that condition, when it should just be matching the Default.
1. Save the set and exit to browse mode. Note that the set is still stuck on an incorrect match.
1. Nav away and back to the set; note that now it evals to the Default condition properly.

**Comment by davetsay** [comment]
verified

**Comment by charlesh88** [comment]
Testathon 01-07-2021 verified fixed
