### ISSUE TITLE
[New Folder Action] Should have default name of 'Unnamed Folder' and should be required

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#3145]
Testing Notes:

1. Create a New Folder using context menu actions
2. Verify that the default name in the overlay is 'Unnamed Folder'
3. Delete the default name
4. Verify that the OK button is not clickable when there is no entry in the text box.

**Comment by akhenry** [comment]
Verified Fixed 07/13/2020

**Comment by shefalijoshi** [comment]
Verified fixed 13th July.

**Comment by nikhilmandlik** [comment]
Verified. Testathon 7/13/2020

**Comment by charlesh88** [comment]
Verified Testathon 07/13/2020.
