### ISSUE TITLE
[Tabs View] Unable to remove tab from tabs view interface

### ISSUE THREAD

**Issue by johnriedel** [nasa/openmct#3147]
There's no clear way to remove a tab from the tabs view object.

Steps to reproduce:
1. Add one or more tabs to tabs view object and save.
2. Go into edit mode and try and remove a tab from the tabs view.

**Comment by deeptailor** [comment]
Test:

add one or more tabs to tabe view object and save
ensure there are no "X" icons on the tabs when not in edit mode
go into edit mode and ensure each tab has an "X"
Click the "X" to remove a tab and ensure a confirmation dialog appears.
Ensure the dialog Cancel button dismisses the dialog.
Ensure the dialog OK button removes the tab from the tabs view UI and from the object tree
Cancel tab removal by clicking the "X" in the tabs view toolbar and ensure the tab reappears in the tabs view UI and in the tabs view object tree
Remove a tab and save the tabs view this time. Ensure the tab is removed from the tabs view UI and the object is removed from the tabs view object tree.

**Comment by charlesh88** [comment]
Verified fixed in Testathon 08-03-20, but with a regression error that needs to be addressed. See #3265.

**Comment by jvigliotta** [comment]
Testathon 08/04: Verified
