### ISSUE TITLE
Failed to create an object under a folder (Domain object). 

### ISSUE THREAD

**Issue by MarkCodering** [nasa/openmct#3152]
Dear NASA Development Team and Opensource Communities,

We are a group of undergraduate and high school student building thrust vector control rocket. We need NASA OpenMCT to monitor the telemetry data and many more.

I have successfully installed NASA OpenMCT with npm and Node.js. And, I am going to add a domain object called TVC Experiment 1 Data. In advance, I would like to create an object, for example, a telemetry table or telemetry plot under the TVC Experiment 1 Data folder. But, I have failed serval times when I clicked the bottom "Create" to add an object to OpenMCT.

What problem I have encountered?

Why the problem persists?

How to resolve the problem?

The code is shown below:
(I directly install the new plugin on the HTML page.)

openmct.install(function install(openmctAPI) 
        {
            console.log("This is an experiment data plugin for TVC research");
            
            openmct.types.addType('example.type', {
                name: "My Type",
                description: "This is a type that I added!",
                creatable: false
            });

            openmct.objects.addRoot({
             namespace: "example.namespace",
             key: "my-key"
             });

            openmct.objects.addProvider('example.namespace', 
            {
              get: function (identifier) {
                return Promise.resolve({
                    identifier: identifier,
                    name: 'TVC Experiment 1 Data',
                    type: 'folder',
                    location: 'ROOT',
                    composition: []
                    });
                }
            });
          
            openmct.composition.addProvider({
              appliesTo: function (domainObject) {
               return domainObject.type === 'example.namespace';
               },
              load: function (domainObject) {
               return Promise.resolve(myDomainObjects);
               }
            });

            var domainObject = {
            name: "My Object",
            type: 'folder',
            location: 'ROOT',
            composition: 
            [{
            id: '412229c3-922c-444b-8624-736d85516247',
            namespace: 'example.namespace'
            }]
            };
            
        });

Much appreciate for the answer,
Mark

**Comment by JoelMcKinnon** [comment]
We would love to see you use Open MCT to accomplish your goals in monitoring telemetry from your thrust control rocket. It looks like you’ve made a good start getting it to work.

I would suggest following the steps of the tutorial fairly closely and build your own dictionary json file and plugin. You could call these tvc.json and tvc-plugin.js for example. You have a start on some of the code for tvc-plugin.js in your html document.

The objects you wish to monitor should be included in the tvc.json file in the same manner as the tutorial shows with the example spacecraft.

As for the question regarding the Create button, you can’t create your domain objects in this way. For something to be creatable through the Create menu it needs to be a type which includes a view provider, such as Telemetry Table, Overlay Plot, etc. You should instead define any objects you wish to include in the TVC Experiment 1 Data folder within the measurements array of the parent object in your tvc.json folder. The tutorial files provide an example of how to set this up.

**Comment by MarkCodering** [comment]
> We would love to see you use Open MCT to accomplish your goals in monitoring telemetry from your thrust control rocket. It looks like you’ve made a good start getting it to work.
> 
> I would suggest following the steps of the tutorial fairly closely and build your own dictionary json file and plugin. You could call these tvc.json and tvc-plugin.js for example. You have a start on some of the code for tvc-plugin.js in your html document.
> 
> The objects you wish to monitor should be included in the tvc.json file in the same manner as the tutorial shows with the example spacecraft.
> 
> As for the question regarding the Create button, you can’t create your domain objects in this way. For something to be creatable through the Create menu it needs to be a type which includes a view provider, such as Telemetry Table, Overlay Plot, etc. You should instead define any objects you wish to include in the TVC Experiment 1 Data folder within the measurements array of the parent object in your tvc.json folder. The tutorial files provide an example of how to set this up.

**Comment by MarkCodering** [comment]
JoelMcKinnon and NASA Open MCT Team,

I have tried to install the plugin as the tutorial showed. The plugin installed via ''openmct.install()'' function. The script and files are shown below. But, the error codes keep shown as always.

Error Code:
GET http://localhost:8080/dictionary-plugin.js net::ERR_ABORTED 404 (Not Found)

Error Code:
Uncaught ReferenceError: DictionaryPlugin is not defined at (Index: 81)

**HTML Script**
`<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no">
        <meta name="apple-mobile-web-app-capable" content="yes">
        <title></title>
        <script src="dictionary-plugin.js"></script>
        <script src="dist/openmct.js"></script>
        <link rel="icon" type="image/png" href="dist/favicons/favicon-96x96.png" sizes="96x96" type="image/x-icon">
        <link rel="icon" type="image/png" href="dist/favicons/favicon-32x32.png" sizes="32x32" type="image/x-icon">
        <link rel="icon" type="image/png" href="dist/favicons/favicon-16x16.png" sizes="16x16" type="image/x-icon">
    </head>
    <body>
    </body>
    <script>
        const FIVE_MINUTES = 5 * 60 * 1000;
        const THIRTY_MINUTES = 30 * 60 * 1000;

        [
            'example/eventGenerator'
        ].forEach(
            openmct.legacyRegistry.enable.bind(openmct.legacyRegistry)
        );

        openmct.install(openmct.plugins.LocalStorage());
        openmct.install(openmct.plugins.Espresso());
        openmct.install(openmct.plugins.MyItems());
        openmct.install(openmct.plugins.Generator());
        openmct.install(openmct.plugins.ExampleImagery());
        openmct.install(openmct.plugins.UTCTimeSystem());
        openmct.install(openmct.plugins.AutoflowView({
            type: "telemetry.panel"
        }));
        openmct.install(openmct.plugins.DisplayLayout({
            showAsView: ['summary-widget', 'example.imagery']
        }));
        openmct.install(openmct.plugins.Conductor({
            menuOptions: [
                {
                    name: "Fixed",
                    timeSystem: 'utc',
                    bounds: {
                        start: Date.now() - THIRTY_MINUTES,
                        end: Date.now()
                    }
                },
                {
                    name: "Realtime",
                    timeSystem: 'utc',
                    clock: 'local',
                    clockOffsets: {
                        start: - THIRTY_MINUTES,
                        end: FIVE_MINUTES
                    }
                }
            ]
        }));  

        openmct.install(DictionaryPlugin());
        openmct.install(openmct.plugins.Elasticsearch());
        openmct.install(openmct.plugins.SummaryWidget());
        openmct.install(openmct.plugins.Notebook());
        openmct.install(openmct.plugins.LADTable());
        openmct.install(openmct.plugins.Filters(['table', 'telemetry.plot.overlay']));
        openmct.install(openmct.plugins.ObjectMigration());
        openmct.install(openmct.plugins.ClearData(['table', 'telemetry.plot.overlay', 'telemetry.plot.stacked']));
        openmct.start();
    </script>
</html>
`

Plugin
`function DictionaryPlugin() {
    return function install(){
        console.log("Hi");
    }
};`

Much appreciated for the reply.
Mark

**Comment by MarkCodering** [comment]
I have resolved the issue with OpenMCT. Thanks for your help.
