### ISSUE TITLE
Value formatting not working on Display Layout alphanumerics

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3161]
Seen on hulk/viper 7/7/20. This may be a regression error with new "object-type" switcher. Problem exists for old, existing Layouts as well as brand new ones. Inability to use this feature really effects the nature of displays that can be built with alphas.

<img width="725" alt="Screen Shot 2020-07-07 at 3 24 08 PM" src="https://user-images.githubusercontent.com/1056412/86850300-ee45c080-c065-11ea-8a2d-7ce1b55bfdba.png">

1. Add a telemetry as an alphanumeric to a Display Layout.
1. Try to set the alphanumeric format for the field in the Inspector Properties, e.g. "%.3f".
1. The format doesn't apply, won't persist, and results in these console errors:
```
[Vue warn]: Error in event handler for "formatChanged": "TypeError: e is not a function"

found in

---> <TelemetryView>
       <Layout>
         <Root> openmct.js:16:4292
TypeError: e is not a function
    updateTelemetryFormat https://hulk.ndc.nasa.gov/viper/node_modules/openmct/dist/openmct.js:584
    n https://hulk.ndc.nasa.gov/viper/node_modules/openmct/dist/openmct.js:16
    t https://hulk.ndc.nasa.gov/viper/node_modules/openmct/dist/openmct.js:16
    $emit https://hulk.ndc.nasa.gov/viper/node_modules/openmct/dist/openmct.js:16
    updateTelemetryFormat https://hulk.ndc.nasa.gov/viper/node_modules/openmct/dist/openmct.js:584
    n https://hulk.ndc.nasa.gov/viper/node_modules/openmct/dist/openmct.js:16
    formatTelemetry https://hulk.ndc.nasa.gov/viper/node_modules/openmct/dist/openmct.js:584
    formatTelemetry https://hulk.ndc.nasa.gov/viper/node_modules/openmct/dist/openmct.js:584
    n https://hulk.ndc.nasa.gov/viper/node_modules/openmct/dist/openmct.js:16
    t https://hulk.ndc.nasa.gov/viper/node_modules/openmct/dist/openmct.js:16
    _withTask https://hulk.ndc.nasa.gov/viper/node_modules/openmct/dist/openmct.js:16
openmct.js:16:13930
    Ge https://hulk.ndc.nasa.gov/viper/node_modules/openmct/dist/openmct.js:16
    Xe https://hulk.ndc.nasa.gov/viper/node_modules/openmct/dist/openmct.js:16
    Ve https://hulk.ndc.nasa.gov/viper/node_modules/openmct/dist/openmct.js:16
    $emit https://hulk.ndc.nasa.gov/viper/node_modules/openmct/dist/openmct.js:16
    updateTelemetryFormat https://hulk.ndc.nasa.gov/viper/node_modules/openmct/dist/openmct.js:584
    n https://hulk.ndc.nasa.gov/viper/node_modules/openmct/dist/openmct.js:16
    formatTelemetry https://hulk.ndc.nasa.gov/viper/node_modules/openmct/dist/openmct.js:584
    formatTelemetry https://hulk.ndc.nasa.gov/viper/node_modules/openmct/dist/openmct.js:584
    n https://hulk.ndc.nasa.gov/viper/node_modules/openmct/dist/openmct.js:16
    t https://hulk.ndc.nasa.gov/viper/node_modules/openmct/dist/openmct.js:16
    _withTask https://hulk.ndc.nasa.gov/viper/node_modules/openmct/dist/openmct.js:16
```

**Comment by deeptailor** [comment]
##Testing Notes:

1. Add a telemetry as an alphanumeric to a Display Layout.
2. Try to set the alphanumeric format for the field in the Inspector Properties, e.g. "%.3f".
3. Verify no errors in console related to Display Layout, and that the format changed to what you entered.
4. Celebrate with a cold one!

**Comment by shefalijoshi** [comment]
**Tested on 13th July:**

- For an existing Sine wave generator, add the following formatting in properties - %0.1fff (accidentally press f many times here)
- Observe that the data in the Alpha numeric changes to show the extra 'f's.

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/5247066/87359160-2775a900-c51c-11ea-8b96-fda79ae21102.png">

**Comment by JoelMcKinnon** [comment]
Confirmed fix and @shefalijoshi issue - testathon 7/13/20

**Comment by charlesh88** [comment]
Verified Testathon 07/13/2020.

**Comment by nikhilmandlik** [comment]
Verified. Testathon 7/13/2020
