### ISSUE TITLE
[Plots] Alt-Tab switches plot select behavior in Windows

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#3163]
In MCT, Alt is used to switch plot select behavior from drag-zoom to translate. In Windows, an Alt-Tab from the browser triggers this, so users will alt-tab from MCT to a presentation, then back to MCT, expect to zoom in a plot, and instead will translate the plot making unnecessary queries and looking unpolished for presentations.

Reproduction Steps
1. Find current windows machine to test on
1. View a plot
1. press alt-tab to switch between browser and another windows application
1. press alt-tab as needed to return to browser
1. see that pan feature is enabled even if alt is not currently pressed (when marquee is expected)
1. additional alt-tabs from plot in browser will continue to toggle pan and marquee

original user issue - https://github.com/nasa/openmct/issues/2320

**Comment by jvigliotta** [comment]
Testathon: 07/13 - Peter from JPL Verified
