### ISSUE TITLE
[Plots] Context menu (ctrl-click) breaks marquee functionality

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#3164]
Steps to Reproduce
1. View a plot
1. Hold `ctrl` key
1. Click and drag mouse (the browser context menu should appear)
1. Release mouse and see that marquee is active
1. If you don't see marquee active wait a few seconds then move mouse

Expected Behavior
Marquee should not be active after opening browser context menu in plot view.

![plots context click](https://user-images.githubusercontent.com/3614296/86972229-76d86580-c127-11ea-8142-bedd915be423.gif)

**Comment by deeptailor** [comment]
Verified Fixed 07/13/2020

**Comment by charlesh88** [comment]
Verified _partially_ fixed: ctrl-click has been handled, but right-mouse click also needs to be handled.

**Comment by nikhilmandlik** [comment]
Partially (same as @charlesh88 ) Verified. Testathon 7/13/2020

**Comment by jvigliotta** [comment]
Handle **ALL** context clicks, not just control clicks.

**Comment by unlikelyzero** [comment]
Will verify in next testathon

**Comment by charlesh88** [comment]
Verified fixed Testathon 06-25-21.
