### ISSUE TITLE
[Plots] Should allow changing x-axis metadata

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#3167]
Original User Issue #2380
## Expected Behavior
In Plot View
- User should be able to change x-axis metadata for one series
- x-axis scale should reflect this change
- Time conductor should not be affected by this change

In Overlay Plot View
- Same functionality for single series in plot view
- User should not be able to change x-axis metadata for multiple series

In Stacked Plot
- Same functionality for single series in plot view (only currently edited plot should change)

## Steps to Reproduce
1. Hover over x-axis metadata label to see dropdown of available/selectable metadata
1. Select a metadata to change x-axis
1. Observe that plot changes as expected but time conductor does not change

**Comment by shefalijoshi** [comment]
Verified 09/14/2020
On hulk, verified this with Sine Wave generator, switched successfully between Time and Yesterday and back to Time.
There is some odd behavior with the data being displayed, but that is likely an issue with the sample Sine Wave Generator.

**Comment by deeptailor** [comment]
Verified on VISTA 09/14/2020
