### ISSUE TITLE
[Annotation] Painterro throws error when cropping

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#3170]
![image](https://user-images.githubusercontent.com/13260688/87074104-3df5ca80-c1d3-11ea-964b-a7acab2988f2.png)

To reproduce:

1. Take a snapshot.
2. Open snapshot and annotate.
3. Select a portion of image and crop.
4. You will see errors in the console relating to Painterro

**Comment by davetsay** [comment]
Verified

**Comment by charlesh88** [comment]
Verified Testathon 07/13/2020.

**Comment by nikhilmandlik** [comment]
Verified. Testathon 7/13/2020
