### ISSUE TITLE
[Snapshots] [Notebook] Users should be able to use clipboard images in their notebook entries

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#3173]
It will be useful if we allowed users to use their system dependent screenshot capabilities, eg PrintScrn in Windows and Screenshot in Mac, copy and paste images etc to take snapshots and store in their notebook entries. Painterro already allows pasting clipboard images, we could simply use this functionality. 

Thoughts?

**Comment by scottbell** [comment]
We allow drag/drop of user images in #7048
