### ISSUE TITLE
[Imagery] Should listen to Clear Data like plots and telemetry tables

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#3175]
Plots and Tables clear out data when the global data clear event is emitted. Imagery should do the same

**Comment by michaelrogers** [comment]
## How To Test
1. open an example image with telemetry
2. select the clear data global function
3. observe that image telemetry was cleared

**Comment by shefalijoshi** [comment]
Verified fixed.

**Comment by akhenry** [comment]
@shefalijoshi Observing the same thing. Not fixed.

**Comment by nikhilmandlik** [comment]
clears but refills all images again

**Comment by charlesh88** [comment]
Verified fixed Testathon 6-9-22.

**Comment by khalidadil** [comment]
Verified fixed - testathon on 06/09/2022

**Comment by rukmini-bose** [comment]
Verified Fixed Testathon 3/20/2024
