### ISSUE TITLE
UI enhancements July 2020

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3176]
Various user requests:
- [x] Large overlay should be fullscreen.
- [x] Develop "small" detection that looks at the display size of an object and allows better formatting in that circumstance.
  - [x] When a table or plot is "small", hide header buttons when not in use or not relevant.
  - [x] Recast plot "Hide legend" configuration as "Hide legend when small"; change plot legend behavior to only hide legend when the plot itself is "small", and always show plot legend in main view or overlay large view.
  - [x] Hide table filter inputs when table is "small".
- [x] Better approach to selected and paused, don't use borders that alter layout.
- [x] Increase size of borders and line size for Display Layout drawing objects. Problematic with the line object when it's perfectly horizontal or vertical.

Work being done in `ui-enhance-3176`.

**Comment by charlesh88** [comment]
### Test Notes

Refer to screen examples below for verifications.
1. Make or edit a Display Layout, add telemetry or a Sine Wave Generator to it as plots and tables. Use the default grid sizing of 10 x 10 px.
1. Click the middle area of a table, verify that the frame selects, but table rows do not.
1. Size the table smaller than 60 x 60 grid units. Verify that buttons and column search inputs are hidden.
1. Size the table larger than or equal to 60 x 60, verify that buttons and column search inputs are displayed.
1. Click the middle area of a plot, verify that the frame selects, but the plot area doesn't react (lock cursor, zoom, etc.).
1. Size the plot smaller than 60 x 60 grid units. 
1. In the Inspector, check the option under Legend for next to "Hide when plot small". Verify that the legend and PNG/JPG buttons are hidden.
1. Click the plot's View Large button. Verify the plot appears as expected in the full-screen overlay and that the legend and PNG/JPG buttons are displayed.
1. Size the plot larger than or equal to 60 x 60, verify that the legend and buttons are displayed.
1. Verify that both X and Y axes have adequate spacing for their labels and ticks.
1. 






**_Full-screen overlay_**

<img width="1712" alt="Screen Shot 2020-07-20 at 4 51 19 PM" src="https://user-images.githubusercontent.com/1056412/87997329-a41eff00-caa9-11ea-9dc8-22b66e36cb25.png">

**_New layout of plot local controls_**

<img width="327" alt="Screen Shot 2020-07-20 at 5 01 28 PM" src="https://user-images.githubusercontent.com/1056412/87997704-b0578c00-caaa-11ea-9a75-1fe177d3f97e.png">

**_Thicker borders, better horizontal and vertical lines_**
<img width="1712" alt="Screen Shot 2020-07-20 at 4 44 30 PM" src="https://user-images.githubusercontent.com/1056412/87998099-ca459e80-caab-11ea-9c27-1b0da304c744.png">

**_Table buttons when in small container_**
<img width="1712" alt="Screen Shot 2020-07-20 at 4 58 05 PM" src="https://user-images.githubusercontent.com/1056412/87997591-61115b80-caaa-11ea-9129-954d665a47f2.png">

**_Legend changes_**
<img width="1712" alt="Screen Shot 2020-07-20 at 4 47 38 PM" src="https://user-images.githubusercontent.com/1056412/87998001-7dfa5e80-caab-11ea-80d7-c82caa7e9135.png">

**Comment by charlesh88** [comment]
Problem with table scrolling seen during Testathon 08-03-20 due to this CSS:

`.is-editing .c-telemetry-table__body-w`

Two things should be different for this: 
- Disable pointer events on tr elements which are the actual click handlers in order to allow scrolling.
- Frame this to only apply to tables within a Layout.

**Comment by charlesh88** [comment]
Verified fixed Testathon 08-03-20.

**Comment by shefalijoshi** [comment]
Verified on 08/03/2019
