### ISSUE TITLE
[Dependencies] Lock dependency version numbers

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3178]
Right now we are using the caret (^) version specifier in package.json for most packages. This will cause npm to use the latest minor version of a package at build time (absent`package-lock.json`). This means that packages are silently and unpredictably upgraded, leading to problems when a newer package version introduces breaking changes or bugs. Experience has taught us that both happen with unfortunate regularity.

**Comment by khalidadil** [comment]
I'm still seeing the caret on several packages @johnhill2 - was this intentional?

**Comment by unlikelyzero** [comment]
@khalidadil this was an older ticket that i added to https://github.com/nasa/openmct/pull/4795
Let me update `master` to retest this in 2.0.1
