### ISSUE TITLE
Visually differentiate objects that are "missing"

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3179]
A change to a dictionary may remove a previously instantiated object, possibly causing that object to no longer function or appear correctly. Users that may depend on it should have a way of easily discerning the current state of such an object.

**Comment by charlesh88** [comment]
Work done in branch `missing-items-v2`, committed and merged into master 7/10/20.

**Comment by charlesh88** [comment]
Unit testing finds that Folder grid and list view, and plot legends, are all not looking at the correct property to discern if the item is missing. Will fix.

**Comment by charlesh88** [comment]
### Testing Notes
1. Modify the file `src/adapter/services/LegacyObjectAPIInterceptor.js` and change the return statement in line 90 from 
```
return utils.toNewFormat(model, key);
```
to 
```
newFormat.status = 'missing';
return newFormat;
```
2. Run Open MCT and compare the following views with the screenshots attached. MORE TK FROM @charlesh88

**Comment by charlesh88** [comment]
Verified Testathon 07/13/2020 using line 90 code change method.

**Comment by nikhilmandlik** [comment]
Verified. Testathon 7/13/2020
