### ISSUE TITLE
Style time conductor for mobile

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#318]
Currently, the time conductor does not display correctly on a mobile screen, e.g. an iPhone.  It gets smushed off screen.  It looks rather unpolished.

Should we disable it for mobile devices, and bring it back when it has been restyled for mobile?

**Comment by charlesh88** [comment]
And, somewhat importantly, none of the gestures work either, yes? Until we get this working, I'd use the same approach I used for the Create button and suppress this in mobile via CSS.

Sent from my iPhone

On Nov 17, 2015, at 8:20 PM, Pete Richards <notifications@github.com<mailto:notifications@github.com>> wrote:


Currently, the time conductor does not display correctly on a mobile screen, e.g. an iPhone. It gets smushed off screen. It looks rather unpolished.

Should we disable it for mobile devices, and bring it back when it has been restyled for mobile?

**Comment by larkin** [comment]
Have to keep in mind the separate use cases for mobile and desktop; realizing we may not wish to match the functionality here.

I think a happy median would be to hide the slider, show start/end dates, but prevent changing them.  It simply serves to allow users to know the default time range.  Normal mobile use cases are for weekend warriors checking to see if their systems are currently okay-- they'd whip out a laptop for futher investigation.

The domain switcher should be active as it's required to make some components work properly.

If users want to explore outside the time range, maybe we use other gestures such as pan/zoom in plots.  Can figure that out as we get more mobile users.

**Comment by VWoeltjen** [comment]
Unable to verify during testathon 5/31/2016; time conductor is not included in WARP at this time

**Comment by VWoeltjen** [comment]
Verified in testathon 6/16/2016; when emulating a mobile device, time conductor appears as start/end/time system fields only, and triggers requery as expected when these are changed

**Comment by charlesh88** [comment]
Testathon 2016-06-16
Still has issues, see #493.
