### ISSUE TITLE
[Annotation] Should not output to console on cancel

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#3185]
## Expected Behavior
On cancel annotation, console message should not be output

## Steps to Reproduce
1. Make sure browser console is open
1. Take a snapshot and open by clicking thumbnail
1. Annotate then click cancel
1. See that on cancel a message is logged to console (You cancelled the annotation!!!)

**Comment by imrishabh18** [comment]
@davetsay Is this issue resolved? Otherwise, I will like to contribute to resolve some beginner issues 😄

**Comment by nikhilmandlik** [comment]
Is addressed in https://github.com/nasa/openmct/pull/2943

**Comment by jvigliotta** [comment]
Testathon - 8/24/2021 : Unable to test due to notebook errors

**Comment by unlikelyzero** [comment]
Will retest after https://github.com/nasa/openmct/issues/4144 is solved
