### ISSUE TITLE
[Time Conductor] History should not need priming before working

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#3189]
## Overview
During testathon in server environment, some abnormalities were observed, which went away after refreshing the browser a few times.
- no history being recorded
- history not being recorded but not displayed until refreshing browser

## Expected Behavior
- on load, any previous history should be displayed in conductor history
- on any bounds change, new history item should be recorded and displayed in conductor history

## Steps to Reproduce
1. open OpenMCT
2. open conductor history, below conductor axis and inputs
3. observe if any existing history items exist
4. change bounds by panning, zooming, calendar select, direct input, or notebook, and observe new bounds should be recorded and displayed in conductor history
5. repeat as desired
6. Clear entry in local storage to start fresh and repeat as desired

**Comment by jvigliotta** [comment]
Verified fixed Testathon 6/4/2021
