### ISSUE TITLE
Some views broken in Safari

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3192]
Per #3191, a number of views in Safari (and hence iOS mobile) are broken. 

<img width="1712" alt="Screen Shot 2020-07-14 at 6 01 18 PM" src="https://user-images.githubusercontent.com/1056412/87491163-42b7e580-c5fc-11ea-8d9b-cc462fa4eef0.png">
<img width="1712" alt="Screen Shot 2020-07-14 at 6 01 24 PM" src="https://user-images.githubusercontent.com/1056412/87491165-43e91280-c5fc-11ea-9853-69517d52c077.png">

Collapsed indicators not so good:
<img width="710" alt="Screen Shot 2020-07-14 at 6 45 10 PM" src="https://user-images.githubusercontent.com/1056412/87493677-3171d780-c602-11ea-9d83-e9e9704aacfc.png">

**Comment by mudinthewater** [comment]
I don't have an ios device but last time I checked this minmax views came out odd

**Comment by mudinthewater** [comment]
Might be worth checking against the desktop chrome/ff with heavy data loads in ios

**Comment by charlesh88** [comment]
### Testing Notes
- [ ] Verify that the following appears as in attached screens in Safari 12.0.
1. Create a few Sine Wave Generators. Verify they appear correctly.
1. Create an Overlay Plot and add the SWG's just created. Verify they appear correctly. Save and exit.
1. Click on a Folder, then context-click the SWG and select Preview. Verify the view is displayed correctly.
1. Expand and collapse the Status area at the top of the screen, verify visual appearance. In the collapsed view, hover over the indicators and verify that bubbles appear and that bubbles that have buttons are clickable.

- [ ] Repeat above having enabled Safari > Develop > Enter Responsive Design Mode.
- [ ] Repeat above in Chrome.
- [ ] Repeat above in Firefox (extra credit).

### References
#### Desktop
<img width="1712" alt="Screen Shot 2020-07-14 at 7 24 16 PM" src="https://user-images.githubusercontent.com/1056412/87497182-f07dc100-c609-11ea-863c-aeee20326d63.png">
<img width="1712" alt="Screen Shot 2020-07-14 at 7 23 59 PM" src="https://user-images.githubusercontent.com/1056412/87497189-f378b180-c609-11ea-9f07-6aae739d0047.png">
<img width="1712" alt="Screen Shot 2020-07-14 at 7 23 45 PM" src="https://user-images.githubusercontent.com/1056412/87497201-f70c3880-c609-11ea-9a19-c7282fd88166.png">

#### Mobile
<img width="795" alt="Screen Shot 2020-07-14 at 7 26 23 PM" src="https://user-images.githubusercontent.com/1056412/87497218-fecbdd00-c609-11ea-8346-afce4c562403.png">
<img width="658" alt="Screen Shot 2020-07-14 at 7 25 24 PM" src="https://user-images.githubusercontent.com/1056412/87497225-02f7fa80-c60a-11ea-8467-8e9e770de15a.png">

**Comment by charlesh88** [comment]
> I don't have an ios device but last time I checked this minmax views came out odd

@deeptailor Wondering if you can check this out locally for VISTA?

**Comment by mudinthewater** [comment]
@charlesh88 I set up a sample site using the latest commit today - its at https://petersmcttest.net. It only does minmax to base index on two test channels, but you can see that on ios and android switching between the tree and the view causes issues (although not as bad as last time I was doing this, where they didn't even match each other). I'd suggest loading it on your phone/ipad and seeing how it works - browser-based emulation doesn't capture how frustrating mobile can be. 

For example, I can zoom in my browser, and zooming seems to produce odder aliases than it should. (on mobile set it to jan1-10, then zoom in - there's no pan option or 2 finger zoom option)

**Comment by mudinthewater** [comment]
Another difference between emulation and actual ipad: on my ipad I click a view and it takes up ~1/8th the available vertical space - on my browser emulation of it, it works fine. 

Also looks like image capture isn't working on android, but is on IOS. 

Okay I should really go to sleep now.

**Comment by charlesh88** [comment]
Fixed by #3193, closing pending verification.

**Comment by mudinthewater** [comment]
I'll pull and update my test then check.

**Comment by charlesh88** [comment]
> @charlesh88 I set up a sample site using the latest commit today - its at https://petersmcttest.net. It only does minmax to base index on two test channels, but you can see that on ios and android switching between the tree and the view causes issues (although not as bad as last time I was doing this, where they didn't even match each other). I'd suggest loading it on your phone/ipad and seeing how it works - browser-based emulation doesn't capture how frustrating mobile can be.
> 
> For example, I can zoom in my browser, and zooming seems to produce odder aliases than it should. (on mobile set it to jan1-10, then zoom in - there's no pan option or 2 finger zoom option)

I've moved this and the iPad 1/8 vertical space comments into a more mobile-specific issue: #3259.

**Comment by unlikelyzero** [comment]
No Rendering issues detected on Safari in and out of Responsive Design Mode
