### ISSUE TITLE
[User Request] Show units when available

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#3197]
Users have requested the ability to show units when possible.

This applies to: Alphanumerics, Telemetry Tables, LAD Tables (and Sets), and Plots

## Testing

**Add Units**
In /example/generator/GeneratorMetadataProvider.js add a unit property to some metadata (example is sine here):

`{
    key: "sin",
    name: "Sine",
    formatString: '%0.2f',
    unit: 'something',
    hints: {
        range: 1
    }
}`

**Alphanumerics**
- create display layout
- add sine wave generator (new units field has been added) to a display layout
- verify units are showing by default
- edit the display layout and select the alphanumeric element
- toggle units on and off
- select multiple alphanumerics and toggle units off and on, verify works as expected
- navigate away and come back to verify unit visibility is persisting

**Telemetry Tables**
- create a telemetry table
- add a state generator (no units field added) no unit column should show
- add a swg (new units field has been added)
- unit column should now show
- in edit mode under "table column visibility" you should be able to hide the unit columns
- if you export table data with columns showing they should be in the exported file

**LAD Tables (Table sets)**
- create a simple lad table with a state generator (no units have been added)
- verify no units column
- add a swg (units have been added)
- verify unit column is showing up after value field
- remove swg and verify that the units column has disappeared
- create another lad table with a swg (units have been added)
- create a lad table set with the sg lad table
- verify no units column
- add the swg lad table
- verify unit column is showing

**Plots**
- create an overlay plot with a SG (no units have been added)
- verify no unit shows up in the legend after the sg object name
- add a swg (unit field has been added)
- verify the swg has the units appearing after the swg object name
- expand the legend
- verify that there is a units column and it's showing units for the swg
- enter edit mode
- in the "Legend" under "When expanded show" toggle "Units"
- verify the units column (when expanded) corresponds to the configured setting
- create another plot (sg, swg, etc)
- create a stacked plot with the two plots created
- verify each plot is working as expected
- navigate away, refresh, verify persistence

**Gauges**
Note that the Gauge only displays the units if they're available from the telemetry source, and both 'Display current value' and 'Display units' are enabled in the view's properties. Here's a Display Layout with multiple Gauges in all the available styles: [Gauge Display Layout 3.json.zip](https://github.com/nasa/openmct/files/8682990/Gauge.Display.Layout.3.json.zip)

1. Create a new Gauge of type Filled Dial. Disable "Display units" in the initial creation properties dialog.
1. Add a sine wave generator or telemetry source known to include units into the Gauge. Save, exit then nav away and back.
1. Verify that no units are displayed.
1. Edit properties for the Gauge and enable "Display units". Save and exit, then nav away and back.
1. Verify that units are displayed in the view, similar to below:

![Screen Shot 2022-05-12 at 3 41 44 PM](https://user-images.githubusercontent.com/1056412/168180330-feac4870-e4d0-4644-852c-b8a38c319924.png)

6. Manipulate the view in the browser or within a layout to shrink and expand the Gauge view, and verify that the units size proportionally with the current value.
1. Edit properties for the Gauge and set the Gauge type to the next available option. 
1. Repeat steps 5-7 immediately above to ensure that all Gauge types are displaying units properly.

**Comment by shefalijoshi** [comment]
Create a telemetry table and add a sine wave generator to it.
Turn off Cosine and Cosine Units columns in properties inspector
Save and navigate to a different domain object in the main view
Return to the initial telemetry table and turn on the Cosine and Cosine Units columns in the properties inspector
Expected: the columns show up with data and units.
Observed: The columns show up but are empty.

**Comment by charlesh88** [comment]
Testathon 03-03-20: did not get all the way through the test, but I want to change the icon and toolbar placement for the toggle units button:

**Comment by jvigliotta** [comment]
@shefalijoshi Moved the telemetry column/data issue to another issue, looks like it's not specific to this branch (showing before these changes were implemented). It's now #3271 

Can you elaborate on the second issue regarding alphanumerics in display layouts?

**Comment by davetsay** [comment]
@jvigliotta should this still be open?

**Comment by jvigliotta** [comment]
@davetsay nope!

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by charlesh88** [comment]
Did an assay today, running latest master locally (except for Gauge) and using a Sine Wave Generator as the data source. See findings below, reopening this issue as either not fixed or regressed.

### Findings:

Object type | Displays units | Note
-- | -- | --
Bar Graph | N | Should display units but doesn't.
Built-in plot view | Partial | Does display unit, but switching the value in the Y axis should update the unit, but doesn't.
Built-in telemetry table view | Y |  
Condition Set | N/A | Includes telemetry, but doesn't directly display value data. Units aren't germane to configuration interface.
Display Layout alphanumeric | N | Should display units but doesn't.
Gauge | N | Should display units but doesn't.
LAD Table | Y |  
Overlay Plot | Partial | Does display unit, but editing the plot to select a value other than the default should update the unit, but doesn't.
Stacked Plot | Partial | Same problem as described for other plot views.
Telemetry Table | Y |

**Comment by charlesh88** [comment]
Here's a design mockup for units in Gauges: 
https://www.figma.com/proto/0ViN9SQDkPYxCOZVXXUia4/Units-in-Gauges-v1?page-id=0%3A1&node-id=2%3A11&viewport=501%2C48%2C0.91&scaling=min-zoom&starting-point-node-id=2%3A11

**Comment by charlesh88** [comment]
Verified fixed Testathon 6-9-22, with Overlay and Stacked Plots, LAD Table, Gauges, DL alphanumerics.

![image](https://user-images.githubusercontent.com/1056412/172951520-a469fb68-53df-44a4-b77f-fe81e0cb3fc8.png)
