### ISSUE TITLE
[API] Implement the "save" method on the Object API

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3199]
Currently the "save" method is not implemented on the Object API. This prevents object providers written using the new API from persisting any objects.

### Testing Instructions
This change subtly how persistence occurs. General testing of persistence events should be carried out, with particular attention paid to:
1. Creating new objects
2. Batch creation events (eg. duplication)
3. Editing objects and discarding changes
4. Editing objects and saving changes

**Comment by jvigliotta** [comment]
Testathon 08/04: Partially Verified...

Found a possibly related bug: #3264
