### ISSUE TITLE
[Persistence] Re-implement the Couch DB persistence provider as an Object Provider

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3201]
In the interests of refactoring legacy Angular code, the Couch DB persistence provider should be re-implemented as an object provider. 

Previously it was not possible to do persistence from object providers, instead it required them to be implemented using legacy API. [There is a PR](https://github.com/nasa/openmct/pull/3200) that adds the ability to define `save` and `update` methods on object providers, which means that object providers defined in the current API can now support persistence.

Until the PR is merged, create a new branch based on that PR.

**Comment by shefalijoshi** [comment]
Testing Instructions:

1. Install CouchDB on local machine
2. Comment out the following in index.html
`openmct.install(openmct.plugins.LocalStorage());`
3. Add the following in index.html: (*note*: You might have to delete the admin account in couchDB and enable CORS for this to work
`openmct.install(openmct.plugins.CouchDB('http://localhost:5984/openmct'));`
4. npm start
5. Navigate to localhost:8080
6. Test that creation, deletion, retrieving and duplication of objects works in general.

**Comment by shefalijoshi** [comment]
Verified on 08/28/2020 
Found this bug while testing: #3340
