### ISSUE TITLE
[Telemetry] Subscriptions are not being cleaned up properly

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3203]
While investigating telemetry dropouts in the VIPER test environment it was discovered that in some cases cached subscriptions are being cleaned up properly.

There appear to be two issues here:
* The Subscription API [muxes multiple subscriptions for the same telemetry into a single subscription](https://github.com/nasa/openmct/blob/87d63806b9a2d6035b8a6786175f6c068c688b9b/src/api/telemetry/TelemetryAPI.js#L314), but it should be cleared [when there are no more subscriptions for a given telemetry object](https://github.com/nasa/openmct/blob/87d63806b9a2d6035b8a6786175f6c068c688b9b/src/api/telemetry/TelemetryAPI.js#L336).
* Some telemetry consumers are [not deleting references to unsubscribe callbacks after unsubscribing](https://github.com/nasa/openmct/blob/87d63806b9a2d6035b8a6786175f6c068c688b9b/src/plugins/condition/StyleRuleManager.js#L48), resulting in unsubscribe being called again later, causing new subscriptions to be dropped.

### Testing Notes
The VIPER specific issue VIPEROMCT-15 includes reproduction steps for the original bug.

Additionally, this change affects telemetry subscriptions globally, and particularly in Condition Sets. General testing should be performed with realtime data to look for regressions. 
eg.
1. Create a number of objects with multiple telemetry points in them (tables, plots, LAD Tables, alpha-numerics in display layouts). Ensure that realtime data is flowing ok, and that navigating away and back to the view does not cause unexpected data dropouts
2. Create a condition set, and define some rules using the same telemetry points used in the previous step
3. Use the condition set to apply some conditional styling to some of the telemetry views defined in step 1. Ensure that you use the same telemetry points in the condition set as are used in the view you're styling
4. Navigate away from the views and back a few times, and ensure that realtime data is flowing as expected for all telemetry points in the views.

**Comment by nikhilmandlik** [comment]
Verified. Testathon 8/3/2020
