### ISSUE TITLE
Dragging into locked View puts the editor in 'edit' mode

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#3204]
Scenario 1:
Create a Condition Set and a Sine wave generator in My Items
Lock both the Condition Set and the Sine wave generator
Create a Tabs view and add the Condition Set and Sine Wave generator to it
Save and lock the Tabs view
Create a State Generator in My Items
Navigate to the Tabs View and drag the State generator onto the Condition Set tab
**Expected:** The drag should be ignored
**Observed:** The Tabs View goes into Edit mode

Scenario 2:
Create a Condition Set and a Sine wave generator in My Items
Lock both the Condition Set and the Sine wave generator
Create a Tabs view and add the Condition Set and Sine Wave generator to it
Save and lock the Tabs view
Create a new Display Layout and drag the Tabs View into it
Create a State Generator in My Items
Navigate to the Display Layout and drag the State generator onto the Condition Set tab of the Tabs View in the layout
**Expected:** The drag should be ignored
**Observed:** The Display Layout goes into Edit mode

**Comment by jvigliotta** [comment]
Testathon 08/04: Verified

**Comment by nikhilmandlik** [comment]
Verified. Testathon 8/3/2020

**Comment by charlesh88** [comment]
Verified fixed Testathon 08-03-20.
