### ISSUE TITLE
Imagery should include Next and Previous image controls

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3209]
### Overview
The main image in Image Telemetry should include "Prev" and "Next" arrow buttons. User request from VIPER dsims.

<img width="365" alt="Screen Shot 2020-07-16 at 4 54 29 PM" src="https://user-images.githubusercontent.com/1056412/87733570-0cf23880-c785-11ea-926c-e71701972bc2.png">

### Details
- Clicking the Prev or Next arrows should display the image immediately preceding or following the the current image, respectively. This should have _exactly_ the same effect as clicking the the thumb immediately preceding the image that the user is currently on. 
  - Clicking Prev should add the "paused" state to the image interface - again, same as clicking a previous thumb does now.
  - If the image is currently in the "paused" state and clicks the Next button such that they would display the most current image available, the interface should be released from the "paused" state; yet again, same as clicking the most current thumb.
- If there are no images in the current data query preceding or following the current image, the relevant arrow should have the `disabled` attribute applied to it.
- Arrows buttons should be available everywhere that the main image appears: in the main view, in Layouts, in large view.
- Arrow buttons will be hidden until the user hovers over the main image.

Related: #3302

**Comment by charlesh88** [comment]
7/16/2020: Work being done on this in `imagery-prev-next-3209`.

**Comment by jvigliotta** [comment]
## Testing
Basically make sure you can do everything @charlesh88 mentioned in his first comment in the "Details" section

 - Clicking the Prev or Next arrows should display the image immediately preceding or following the the current image, respectively. This should have exactly the same effect as clicking the the thumb immediately preceding the image that the user is currently on.
 -  - Clicking Prev should add the "paused" state to the image interface - again, same as clicking a previous thumb does now.
 -  - If the image is currently in the "paused" state and clicks the Next button such that they would display the most current image available, the interface should be released from the "paused" state; yet again, same as clicking the most current thumb.
 - If there are no images in the current data query preceding or following the current image, the relevant arrow should **be** disabled.
 - Arrows buttons should be available everywhere that the main image appears: in the main view, in Layouts, in large view.
 - Arrow buttons will be hidden until the user hovers over the main image.

**Comment by jvigliotta** [comment]
#3302 created!

**Comment by nikhilmandlik** [comment]
![Screen Shot 2020-09-14 at 3 09 34 PM](https://user-images.githubusercontent.com/1292612/93143209-533c1900-f69c-11ea-9fda-bd3f0e90181a.png)

**Comment by shefalijoshi** [comment]
Verified on 09/14/2020.
