### ISSUE TITLE
Time Conductor should include useful built-in time spans and history tracking

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3213]
<img width="528" alt="Screen Shot 2020-07-20 at 10 47 33 AM" src="https://user-images.githubusercontent.com/1056412/87969249-9ef48c80-ca76-11ea-92b6-97c869b82ae1.png">

In a similar fashion to a feature recently added for Fixed Timespan mode the Time Conductor's real-time mode should have useful pre-determined timespans available to the user via a menu. Additionally, we should watch, remember and make those available in the same way as well. Ideally, these are configurable per deployment.

### Timespans:
00:60:00 - 00:00:00
00:30:00 - 00:00:00
00:15:00 - 00:00:00
00:05:00 - 00:00:00
00:01:00 - 00:00:00

**Comment by mudinthewater** [comment]
While you're doing this please make sure that it works for spans greater than 24 hours. Your timespan example doesn't include that case.

**Comment by charlesh88** [comment]
@jvigliotta Can you weigh in on @mudinthewater's request? We don't do more than 24 hours now, and wondering if that's easy (if so, let's keep in scope) or difficult (in that case, let's create a separate issue).

**Comment by charlesh88** [comment]
@mudinthewater After discussion with @akhenry extending the time frame beyond 24 hours is non-trivial, so I've broken that into its own issue: #3220.

**Comment by jvigliotta** [comment]
## Testing

 - clear out any current history tracking from local storage
   - `delete localStorage['tcHistoryRealtime']; delete localStorage['tcHistory'];`
 - Open up a plot or SWG (anything you can verify timespans and offsets changing)
 - Switch between realtime (local clock) and fixed time modes
 - Choose preset times and enter in your own times in both modes
 - **verify that** 
   - the selections are modifying the view offsets and time bounds accordingly
   - it's tracking your selections correctly
   - it's not allowing duplicates
   - if you close your browser and open again, that the same history presets are restored

**Comment by nikhilmandlik** [comment]
Testathon 11/2/2020: Not able to verify, can not see predefined options such as Last day, Last hour etc.

**Comment by charlesh88** [comment]
Verified partially fixed Testathon 11-02-20: saves and applies user-changed historical values, but isn't displaying any pre-configured ranges, but should.

**Comment by charlesh88** [comment]
Reopening to get useful timespans in the deployment.

**Comment by unlikelyzero** [comment]
Let's retest with the viper-openmct changes in the next testathon

**Comment by charlesh88** [comment]
Fixed.

**Comment by unlikelyzero** [comment]
### e2e testing notes

timeConductor.e2e.spec.js

History has default values
1. Open history values in timeConductor and validate default selections

History appears for recently entered
1. Modify start, end and offset times of time conductor to create a "history"
2. Switch to Local Clock
3. Open 'History' and look for time conductor history from step 1.

Duplicates do not appear
Repeat 'History appears for recently entered' three times
Verify that it does not appear as 3 separate entries

Verify that values appear in localStorage and can be loaded from SessionStorage file
Reach out to an Open MCT dev for more!

**Comment by loftwah** [comment]
I can definitely take a look at this.

**Comment by charlesh88** [comment]
Fixed
