### ISSUE TITLE
Fix circle CI failing builds due to ChromeHeadless crashing

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#3214]
CircleCI build intermittently fails due to the following error:

`20 07 2020 22:03:35.880:ERROR [launcher]: ChromeHeadless crashed.
	Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
 `
...
...
`20 07 2020 22:03:35.948:INFO [launcher]: Trying to start ChromeHeadless again (1/2).
20 07 2020 22:03:46.290:WARN [HeadlessChrome 0.0.0 (Linux 0.0.0)]: Disconnected (1 times), because no message in 10000 ms.
HeadlessChrome 0.0.0 (Linux 0.0.0) ERROR
  Disconnected, because no message in 10000 ms. 
HeadlessChrome 0.0.0 (Linux 0.0.0) ERROR
  Disconnected, because no message in 10000 ms.
 `

**Comment by shefalijoshi** [comment]
Testing Instructions:
Local:
npm install
npm run test:coverage

On CircleCI:
Ensure that the build passes and no headless browser crashes are observed.

**Comment by shefalijoshi** [comment]
Verified Fixed 08/24/2020

**Comment by davetsay** [comment]
Verified
