### ISSUE TITLE
[Persistence] Implement search in Couch DB provider

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3218]
Currently search works by creating an in-memory index of all known objects on application load [via a full tree traversal](https://github.com/nasa/openmct/blob/7221dc1ac6c4fdb77cd55a4245103956a90bf5cc/platform/search/src/services/GenericSearchProvider.js#L182).

This works particularly well when using the LocalStorage provider, but with remote persistence (eg. the Couch DB provider) this causes unnecessary server load, and can result in excessive memory usage.

Couch DB [provides a search capability](https://docs.couchdb.org/en/stable/api/database/find.html) from its API, which should be leveraged instead of creating an in-memory index.

Here is a proposed plan for implementing search in Couch DB:
1. The current search indexer should still run on startup, but it should first fetch the provider for a given object, and check whether it implements its own `search` function. If it does, then do not index the object or attempt to resolve its composition. If the object provider does not implement `search`, then carry on as usual. This will provide default behavior for object providers that do not implement search.
1. Add a new `search(text)` method to the object API. This method will check all known object providers. For each one, if it implements a search method, then it invoke it with the provided search terms. If it does not, it will go to the generic in-memory index and search that. The results of all providers should be aggregated and returned asynchronously.
1. Implement `.search(text)` for the [new Couch DB object provider](https://github.com/nasa/openmct/issues/3201).

This will involve working with [legacy API](https://github.com/nasa/openmct/blob/master/docs/src/guide/index.md). Ask when you get stuck.

**Comment by akhenry** [comment]
### Testing instructions

These testing instructions only apply to an Open MCT instance that is using Couch DB
1. Open the network tab
2. Clear the contents of the network tab (click on the trash icon).
3. In Open MCT, type in a search string (eg. `test`).
4. In the network tab, verify that a call is made to the `_find` endpoint.
5. In Open MCT verify that the returned objects contain the string searched for

**Comment by davetsay** [comment]
verified
