### ISSUE TITLE
[Display Layout] Lines impossible to move when vertical or horizontal

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#3221]
We recently improved lines to better handle perfectly vertical and horizontal lines, this introduces a small bug where users are unable to move the line when it is vertical or horizontal.

A workaround is to make the line slightly diagonal before moving it, and then returning it back to its vertical or horizontal stature.

**Comment by akhenry** [comment]
Verified fixed 08/03/2020

**Comment by nikhilmandlik** [comment]
Verified. Testathon 8/3/2020
