### ISSUE TITLE
[Tables] Should allow more control over object path (for context menu) for individual rows

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#3231]
## Overview
Currently, contextual object path passed to context menu api is the same for each telemetry table row. Would be nice to allow more granular control to rows, so that you can change context to be particular for a characteristic of each individual row.

## Expected Behavior
Can extend a telemetry table row and overwrite `getContextualDomainObject` method.

**Comment by deeptailor** [comment]
@davetsay - Need some testing instructions.

**Comment by nikhilmandlik** [comment]
can not test on hulk 👊

**Comment by davetsay** [comment]
Verified in VISTA
