### ISSUE TITLE
Need ISOTimeFormat formatter and plugin

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#3242]
The openmct-yamcs adapter needed to switch to ISO standard time from UTC to better handle performance issues as well as leap seconds.

## Testing 
To test this you'll need to have the openmct-yamcs adapter installed and setup with the quickstart server
Alternatively this can be tested on another server that already has this setup
Basically, just make sure there are no errors and timestamps from data returned looks correct

**Comment by davetsay** [comment]
Verified (checked 5 or so endpoints with data coming in)

**Comment by nikhilmandlik** [comment]
Verified Fixed. Testathon 9/14/2020
