### ISSUE TITLE
[Preview] Preview window should not have any context menu actions

### ISSUE THREAD

**Issue by nikhilmandlik** [nasa/openmct#3250]
#### Related to : 
https://github.com/nasa/openmct/pull/3240#pullrequestreview-456868342

### Testing instructions:
1. Create a SWG
2. Create a Display Layout
3. Edit Display Layout
4. Click on SWG (this ll open it in Preview Window)
5. There should be no context menu on Preview.
6. But SWG should show view changer (plot view/ table view)

**Comment by akhenry** [comment]
Verified Fixed 08/03/2020
