### ISSUE TITLE
Rename methods and variables in LadTableSet.vue for more clarity

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#3254]
Names like primary and secondary were a bit confusing, changing to ladTables and telemetryObjects should make things a bit more clear.

## Testing
Create a LAD Table set
Add/Remove LAD Tables, reorder, make sure everything works as expected

**Comment by shefalijoshi** [comment]
Verified on 09/14/2020

**Comment by nikhilmandlik** [comment]
Verified Fixed. Testathon 9/14/2020

**Comment by davetsay** [comment]
Verified
