### ISSUE TITLE
Update TelemetryTable config to allow disable multiselect

### ISSUE THREAD

**Issue by nikhilmandlik** [nasa/openmct#3256]
### Related to NIRVSS issue: 
https://babelfish.arc.nasa.gov/jira/browse/NIRVSSOMCT-178

### Testing instructions:
1. Create a TelemetryTable
2. Add telemetry data point into TelemetryTable (eg: SWG)
3. Check all features such multiselect rows, sorting, filter, play/pause, export, marking etc are working as expected.

#### Testing `multiselect disable`
1. open file `openmct/src/plugins/telemetryTable/TelemetryTableViewProvider.js`
2. on line [#59 click here to view line](https://github.com/nasa/openmct/blob/b76d4b76cb746e5d0bfdaf1bfa59b96efa42fe37/src/plugins/telemetryTable/TelemetryTableViewProvider.js#L59 
) add `disableMultiSelect: true,` under `markingProp` so that it looks like following,
```
let markingProp = {
                    disableMultiSelect: true,
                    enable: true,
```
3. Now goto TelemetryTable and try multiselect using `shift/cmd + click`
4. it should not select multiple rows.

**Comment by nikhilmandlik** [comment]
PR: https://github.com/nasa/openmct/pull/3228

**Comment by davetsay** [comment]
Verified
