### ISSUE TITLE
Console error when clicking on a line in a display layout

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3262]
If I edit a display layout and click on a line the following error appears in the console in chrome:
```
TypeError: Cannot read property 'status' of undefined
    at s.<anonymous> (ObjectName.vue?0303:1)
```
The error is reported slightly differently in Firefox
```
TypeError: e.domainObject is undefined
    B https://hulk.ndc.nasa.gov/viper/node_modules/openmct/dist/openmct.js:355
    _render https://hulk.ndc.nasa.gov/viper/node_modules/openmct/dist/openmct.js:17
```

Steps to reproduce:
1. Edit a display layout and draw a line
2. Select the line by clicking on the background of the layout
3. Click on the line again to select it.

The error appears to be benign, I am not seeing any secondary effects.

**Comment by nikhilmandlik** [comment]
![Screen Shot 2020-08-03 at 3 31 14 PM](https://user-images.githubusercontent.com/1292612/89233465-7b653200-d59e-11ea-8866-1eedbdaf9008.png)

**Comment by jvigliotta** [comment]
Verified Fixed: Testathon 09/14/20

**Comment by nikhilmandlik** [comment]
Verified Fixed. Testathon 9/14/2020
