### ISSUE TITLE
[Tabs View] Tabs no longer displaying object type icons

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3265]
Seen in Testathon 08-03-20 on hulk: tabs in Tab View are no longer displaying object type icons, but should be:
![Screen Shot 2020-08-03 at 3 29 55 PM](https://user-images.githubusercontent.com/1056412/89233489-84560380-d59e-11ea-9fa7-4065ebffd3cb.png)

Also, when removing a tab the resulting dialog refers to "Tabs Layout" but instead should use the term "Tabs View". 

May have been introduced with #3147.

**Comment by akhenry** [comment]
Verified Fixed 10/05/2020

**Comment by davetsay** [comment]
Verified

**Comment by jvigliotta** [comment]
Verified Fixed - 10/05/2020
