### ISSUE TITLE
[User Request] Clearer indication of image age in Imagery View

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#3283]
Show a "count up" clock for images in the imagery view, so people can see the age of the image.

## Testing
- load up the Imagery Plugin
- if in fixed time mode switch to realtime
- when in realtime mode (local clock) you should see the age of the image updating live
- selecting older images should show older image ages
- switching back and forth between fixed/realtime should hide/show image age

**Comment by charlesh88** [comment]
Design notes:
- Only apply to the main image. Please stub in to right of the existing datetime.
- Show as hh:mm:ss
- When the image is brand new (like < 5 mins), I want to visually flag the age indicator to highlight the newness.
- When the image gets beyond a certain age threshold (8 hours, 24 hours, etc.), display the age as "> <age>", e.g. "> 24 hrs".

**Comment by akhenry** [comment]
Verified that it appears to work as designed 10/09/2020. I have filed a followup issue for an unrelated imagery issue that I found - https://github.com/akhenry/openmct-yamcs/issues/27

**Comment by davetsay** [comment]
Verified
