### ISSUE TITLE
Timeline views - Plan/Activities view using d3

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#3290]
Create new object type and view for Plans (not creatable) that consists of activities
Each plan object should have:
- name
- number of swimlanes
- bounds - currently use time conductor bounds
- list of activities

An activity has
- type
- start time
- duration or end time

Leverage the d3 APIs to do this if possible.

**Comment by shefalijoshi** [comment]
**Testing Notes:**
Create a new Plan object using the menu
Upload [this file](https://github.com/nasa/openmct/blob/master/src/plugins/timeline/activities.json)
Change your fixed mode timestamps to: 
starting 2020-04-02 and ending 2020-04-03

**Comment by charlesh88** [comment]
Verified fixed Testathon 10-05-20.

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon 10/05/20

**Comment by akhenry** [comment]
Verified fixed 10/05/2020
