### ISSUE TITLE
[Notebook] Do not persist domain objects on notebooks or snapshots

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3291]
### Description:
Currently Notebook storage is storing domain object which can cause data loss.
### Testing instructions:
1. Open console on browser and run following
2. `JSON.parse(localStorage.getItem('notebook-storage'));`
3. Check and make sure object does not have any domainObject (should only contain identifier to retrieve domain object)
### Expected Result:
No domain objects stored in notebook storage.
### Actual Result:
domain objects stored in notebook storage.
### Screenshots:
<img width="536" alt="Screen Shot 2020-08-12 at 12 36 48 PM" src="https://user-images.githubusercontent.com/1292612/90059785-928bda00-dc98-11ea-998c-65f184c4b5f8.png">

**Comment by shefalijoshi** [comment]
Verified fixed.
