### ISSUE TITLE
Display Layout grid toggle and dimensions

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3293]
New features for Layout dimensions and toggling the display of the snapping grid.

1. **Show Layout dimensions**: show the current extents in pixels of the Layout being edited. This would be calculated by looking at the largest X2 and Y2 grid values of all objects in a given Layout context and multiplying against the current grid size settings.
1. **Toggle grid display**: a new toolbar button that toggles display of the Layout's snapping grid. Note that this does not turn snapping off, it just sets the visibility of the grid. This setting is not persisted.

<img width="1712" alt="Screen Shot 2020-08-11 at 3 27 54 PM" src="https://user-images.githubusercontent.com/1056412/89955583-34072300-dbe8-11ea-90db-931095885541.png">

@charlesh88 to create new icon glyphs for this. I also have some very initial work in progress in `layouts-3293`. Let's discuss how this will be implemented in terms of the toolbar.

**Comment by charlesh88** [comment]
@charlesh88 Add details from convo today with Deep and Dave: 
- Add setting dimensions to this issue. Is guide, not explicit cropping.
- Toggle grid button will not right align

**Comment by davetsay** [comment]
@charlesh88 , I've created a draft pull request, #3297. This will be a reference for me to see the changes. I'll be working from branches cut from your branch for the individual issues.

**Comment by davetsay** [comment]
For reference only. See #3315 and #3332 for specific issues and related pull requests.
