### ISSUE TITLE
[Plots] Allow Plot views to toggle axis grid lines visibility

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3294]
## Overview
Allow the user to toggle the axis grid line visibility of a given plot view. 

## Expected Behavior
- When displaying gridlines, clicking toggle button should hide gridlines and change toggle button icon accordingly.
- When not displaying gridlines, clicking toggle button should show gridlines and change toggle button icon accordingly.

## Steps to Reproduce
1. Navigate to a telemetry endpoint
1. [Verification] Verify toggle gridlines button is available in both view only and edit mode
1. [Verification] Verify you can toggle gridlines by clicking the button
1. Repeat verification steps using an overlay plot
1. Repeat verification steps using a stacked plot
1. Repeat verification steps within a display layout (layout object must be large enough to enable buttons)
1. Repeat verification steps when previewing plot (edit an object and click on a plot to preview)

### Design Notes
- I think this should be a persistable property of the view, rather than a real-time usage gesture. Showing or hiding axis gridlines has to do with information density, noise reduction and informational clarity - all of which relate to the work involved when composing a view. 
- In stacked plots, the setting would be global and would apply to all child plot views, including other composed plot views that may have their own independent setting.
- For extra credit, we could make horizontal and vertical axis lines separately settable.

**Comment by shefalijoshi** [comment]
@davetsay  @charlesh88 Has this issue been satisfied by the accompanying PR? If so, should it be marked closed/unverified?
