### ISSUE TITLE
Default styles while editing a Display Layout

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3296]
Define a default style (background/foreground/font family and size) for View Objects and elements added to a Display Layout as properties of the layout.

### Overview
From discussion Aug 26, 2020 with @davetsay @deeptailor:
1. Allow user to save style settings for the currently selected object in a Layout. Allowed for all object types, including domain, alphanumeric and drawing objects, even images (which would only set the border color).
1. Settings always include values for the following, even when set to "None" or default. Note that image URL is purposefully not included in this list:
- Background/fill color
- Foreground color
- Text color
- Border color
- Font size
- Font family

UI doc is here: https://drive.google.com/file/d/1D2TfXIDdB6skZLhZDbXdqcI6fHRDENJ1/view?usp=sharing

## Expected Behavior (see [UI doc](https://drive.google.com/file/d/1D2TfXIDdB6skZLhZDbXdqcI6fHRDENJ1/view?usp=sharing) for all expected behavior)
- Styles can be saved from any context. Only available styling options will be saved.
- Mixed styles cannot be saved.
- Styles can be applied to any context. Only styles available to current object to be styled will be styled.
- Saved styles can be accessed from inspector
- Saved styles can be deleted

## Steps to Reproduce
1. Create an object
1. Style the object
1. Observe save icon appears when styles have been applied
1. Save style
1. Create another object
1. Apply the saved style and observe that the new object is styled accordingly.
1. Repeat all steps as needed with different scenarios
    - different contexts (objects/objects in display layouts, etc.)
    - static styles / conditional styles
    - multi select (style should be savable if all styles match, but not if styles are mixed)
    - apply to objects with less styles and see that only applicable styles are applied (font family, font size)

**Comment by charlesh88** [comment]
From discussion Aug 26, 2020 with @davetsay @deeptailor:
New approach:
1. Allow user to save style settings for the currently selected object in a Layout. Allowed for all object types.
1. Settings always include values for the following, even when set to "None" or default. Note that image URL is purposefully not included in this list:
- Background/fill color
- Foreground color
- Text color
- Border color
- Font size
- Font family

@charlesh88 to sketch UI.

**Comment by davetsay** [comment]
Remaining tasks per spec
- [ ] pane styling (Overview. spacing / header / layout)
    - [ ] 
- [ ] show save on hover only (Overview.1)
- [ ] show delete on hover only (Overview.4)
- [ ] show saved style details (Overview.5)
- [ ] show font size and family (Overview.6)
- [ ] correct and safe behavior for applying styles when target(s) styles are mixed (currently it overwrites all. works well for static but terrible for conditional)
- [ ] name styles
- [ ] prevent (warn against) duplicate styles

**Comment by davetsay** [comment]
Additional testing notes (or the TLDR; [UI doc](https://drive.google.com/file/d/1D2TfXIDdB6skZLhZDbXdqcI6fHRDENJ1/view?usp=sharing))

- Saved styles can be deleted (by index)
- There is a max # of saved styles (20)
- can apply saved styles to multiple selections
- Should not be applicable for locked objects (objects within locked layouts)

**Comment by nikhilmandlik** [comment]
Verified Fixed. Testathon 11/2/2020

**Comment by deeptailor** [comment]
Verified 11/2/2020 - But needs some polishing around font menu's

**Comment by charlesh88** [comment]
Verified fixed Testathon 11-02-20. Filed two followup bugs: #3487 and #3489.
