### ISSUE TITLE
Enhance view controls and actions with a "3 Dot" button and menu

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3298]
As we continue to add new capabilities and gestures to existing views (some of which are becoming overloaded with controls; Telemetry Table, I'm looking at you) we need a better overall strategy to organize and utilize space for controls and gestures within a given view and context.

Solution: the **3 Dot button and menu**. 

Goals of the approach:
- Consolidate all options for a given object and context into a “3 dots” button and resulting menu.
- Make it easier to add and manage gestures, capabilities and functions for views and contexts.

UI for this task is here: https://drive.google.com/file/d/1QIuOKze72K_SyM1QrH7lMrm_D-1gbNO1/view?usp=sharing
Spreadsheet of views, contexts and actions is here: https://docs.google.com/spreadsheets/d/1vwsQLwCtA31ueTOX6EXdCqm9bksgi6O6eTwkGYJAgqY/edit#gid=1216360461

**Comment by akhenry** [comment]
See [this comment](https://github.com/nasa/openmct/issues/3299#issuecomment-673848534) for notes on how to share view context with actions.

**Comment by deeptailor** [comment]
## Testing Notes:
1. Verify context menu actions work as expected.
2. Create a telemetry table, add some telemetry to it.
3. Verify the pause, expand columns buttons etc work as expected.
4. Click on the three dot button, and verify the state of the buttons mentioned above are in sync. 
5. Verify overall usability of three dot menu button, and context menu actions.
6. Create a display layout, add an alpha numeric telemetry to it.
7. Context click and use new add to notebook and copy to clipboard context menu actions. 
8. Verify the above works as expected.

**Comment by deeptailor** [comment]
@charlesh88 - Any other testing notes to add?

**Comment by charlesh88** [comment]
Verified fixed Testathon 11/20/20

**Comment by shefalijoshi** [comment]
Tried the Move action on a new Notebook domain object to a different folder.

It appears to duplicate the notebook rather than move it as I can see it in the original location as well as the new one.
<img width="301" alt="image" src="https://user-images.githubusercontent.com/5247066/99857441-1a0ea200-2b40-11eb-97d8-fca234c82d72.png">

<img width="299" alt="image" src="https://user-images.githubusercontent.com/5247066/99857454-2135b000-2b40-11eb-80b2-29a24f7c497e.png">

**Comment by davetsay** [comment]
verified most common 3 dot actions

**Comment by charlesh88** [comment]
Looked at items in #3532 and did additional poking. Verified fixed Testathon 11-30-20.

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 11/30/2020
