### ISSUE TITLE
[Notebook] Copy label and value from alphanumeric in Layout directly to a Notebook entry

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3299]
A new gesture to copy the label and value from any alphanumeric in a Layout directly to a Notebook entry or to the clipboard. 

### Design
Alphanumerics already have a "context" action: 'View Historical Data' and I suggest we add a new entry to that menu that utilizes the default Notebook functionality used by Snapshots:

<img width="1047" alt="Screen Shot 2020-08-18 at 11 07 10 AM" src="https://user-images.githubusercontent.com/1056412/90549211-01f34500-e143-11ea-8324-1bfdc26d87cd.png">

A string should be compiled with the current datetime in UTC, the label, selected value and units for the alphanumeric, like this:

> `At <datetime> <label> had a value of <selected value> <selected value units>.`

So,

> `At 2020-08-13 20:27:25.461Z SWG_NLV had a value of 0.01 Amps.`

All the above content is copied, even if the alphanumeric hides its labels and units. For the Notebook, although entries are timestamped, the current datetime in the copied content facilitates adding the content to an existing entry. See notes below.

### Notes
1. If a default Notebook section and page are not defined, don't show that option in the menu.
1. Optionally, we expand the capabilities of the Snapshot container to be more of a general Notebook "clippings" container and allow the copied label and value to be saved to the container as a free-standing Notebook entry. Dragging an entry from the Snapshot container into a Notebook would behave the same as a doing so with a Snapshot: it either adds a new entry or adds content to an existing entry depending on the drop target. The latter case is a bit more nuanced: what to do with existing content in an entry? Suggest we could append the copied content to any existing entry text.

**Comment by akhenry** [comment]
> I suggest we add a new entry to that menu that utilizes the default Notebook functionality used by Snapshots:

@nikhilmandlik This presents an interesting code design problem. A context menu item knows about the domain object and nothing else. It has no idea what's currently displayed in the view. There is currently a little-known function available from views called `getSelectionContext()` (take a look at display layouts for [an example](https://github.com/nasa/openmct/blob/891fe0a36bd2878e34623e13dbea25a3cc015951/src/plugins/displayLayout/plugin.js#L65)) which is used by the selection API to get state information from Views. One option would be to repurpose this as a general function for retrieving view state. we could rename it `getViewContext()`. [The Context Menu API](https://github.com/nasa/openmct/blob/891fe0a36bd2878e34623e13dbea25a3cc015951/src/api/contextMenu/ContextMenuAPI.js#L78) could then be modified to accept a `viewContext` object, which would be [provided by the `ObjectFrame`](https://github.com/nasa/openmct/blob/891fe0a36bd2878e34623e13dbea25a3cc015951/src/ui/components/ObjectFrame.vue#L49) whenever the context menu is invoked.

The new `getViewContext()` method could then be used to provide the current value from alphanumerics to a new "Copy To Notebook" context menu item, which would format it into a message ala the example provided by @charlesh88 .

> Suggest we could append the copied content to any existing entry text.

Appending the text makes the most sense to me.

**Comment by deeptailor** [comment]
Can we copy to clipboard instead? That will give users the flexibility to use that value anywhere they wish

**Comment by charlesh88** [comment]
I have revised the issue to expand it slightly and cover copying to the clipboard.

**Comment by akhenry** [comment]
After some discussion, and given how quickly the [new menu work is advancing](https://github.com/nasa/openmct/issues/3298), suggest we defer this issue until the new API is available to support this action.

**Comment by deeptailor** [comment]
Verified Fixed

**Comment by deeptailor** [comment]
Found a related bug when data has no units, undefined is concatenated into the notebook entry

**Comment by charlesh88** [comment]
Verified fixed Testathon 11/20/20

**Comment by davetsay** [comment]
needs small fix as deep described above.

**Comment by charlesh88** [comment]
Verified fixed Testathon 06-25-21 - nice work!
