### ISSUE TITLE
[Notebook] Create Snapshot directly from any frame in a layout

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3300]
Create snapshot directly from any element's frame in a Display or Flexible Layout.

### Design
A new button added to a Layout element's frame that exposes the Snapshot menu. 
<img width="608" alt="Screen Shot 2020-08-13 at 2 49 19 PM" src="https://user-images.githubusercontent.com/1056412/90190787-8c6b2b80-dd74-11ea-872d-8c4a117c5144.png">

In the short-term, add the Snapshot button before the current View Large button. In the longer-term, this functionality ties in with the 3 Dots menu design #3298. Right now though, this issue and its UI provides a little more detail on how this button element should work in the short-term. See the UI here: https://drive.google.com/file/d/1QIuOKze72K_SyM1QrH7lMrm_D-1gbNO1/view?usp=sharing

**Comment by unlikelyzero** [comment]
will retest after https://github.com/nasa/openmct/issues/4144
