### ISSUE TITLE
[Imagery Plugin] Arrow keys for Imagery prev/next feature

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#3302]
Need to add key listeners for left and right arrows to add additional functionality to imagery plugin prev/next feature.

Related to #3209 

## Testing
- using imagery plugin, go forward and backward using the on screen arrows
- N/A - this will happen later ---- now do it using the arrow keys and ensure functionality is the same
- make sure to go to the end of the images and to the beginning of the images as well

**Comment by shefalijoshi** [comment]
Tested on 09/14/2020. The actual functionality seems fine.
It looks like the brightness and contrast changes are also being applied to the previous and next arrow icons

**Comment by akhenry** [comment]
Verified fixed 10/09/2020

**Comment by nikhilmandlik** [comment]
Verified Fixed. Testathon 10/09/2020

**Comment by davetsay** [comment]
Verified
