### ISSUE TITLE
[Imagery Plugin] Imagery not updating when thumbnails clicked

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3303]
Seen during Matt Deans rover driving dSim 8/14/20 on hulk by both Matt and Robert Carvalho: clicking between the most recent thumb and the one immediately previous was not updating the main image in the View Large overlay. Confirmed that images _were_ different. This is important functionality for users to A/B two different images easily.

**Comment by jvigliotta** [comment]
Should be handled in this PR https://github.com/nasa/openmct/pull/3308

**Comment by nikhilmandlik** [comment]
Verified Fixed. Testathon 10/09/2020

**Comment by davetsay** [comment]
Verified
