### ISSUE TITLE
Creating plugins with custom views

### ISSUE THREAD

**Issue by Deathbat2190** [nasa/openmct#3305]
Hi.
I want to create a plugin with a custom view. I copied the SimpleVuePlugin from the examples folder but got an error that I can't use import statements outside a module. So based on how the default plugins are written I changed the code to this:

```
define(["vue", "./HelloWorld.vue"], function (Vue, HelloWorld) {
function SimpleVuePlugin() {
    return function install(openmct) {
        //here's the same code as in the example file
    }
}
});
```
Now I get an error that define is not defined. The only dependencies I have are express and express-ws (I'm trying to expand the openmct-tutorial project). Can someone please explain how do I create a plugin with a custom view properly?

**Comment by jvigliotta** [comment]
Hi @Deathbat2190 just wanted to check and see if you were able to figure this out?

**Comment by Deathbat2190** [comment]
Yes I did figure it out. I'm not sure if I did it correctly but it's working now.

**Comment by jvigliotta** [comment]
Great, let us know if you run into any other issues, sorry for the delayed response.

**Comment by Kokodora** [comment]
Hey  @jvigliotta, I have the exact same error, how did you manage to get it working?

**Comment by Deathbat2190** [comment]
Hi @Kokodora. 
Take a look at this plugin https://github.com/nasa/openmct-heatmap. You need to add webpack as a dependency to your package.json and then create webpack.config.js file. In the config you have to add loaders for the files you are using and also install them with npm.
Here's how I configured webpack:
```
let path = require("path");
const VueLoaderPlugin = require("vue-loader/lib/plugin");

module.exports = {
  entry: "src/path/to/javascript/file/you/want/to/pack(without file extension)",
  output: {
    path: path.resolve(__dirname, "path/to/where/you/want/the/output"),
    filename: "output_name.js",
    library: "library_name",
    libraryTarget: "umd",
  },
  resolve: {
    alias: {
      vue: "vue/dist/vue.min.js",
    },
  },
  module: {
    rules: [
      {
        test: /\.vue$/,
        loader: "vue-loader",
      },
      {
        test: /\.scss$/,
        use: ["style-loader", "css-loader", "sass-loader"],
      },
    ],
  },

  plugins: [
    new VueLoaderPlugin(),
  ],
  devtool: "source-map",
};
```
Then in your index.html you import the script that webpack created and install your plugin as usual. If you want to create multiple plugins you can make one "master" plugin that installs all of your plugins so that webpack will create one file with all of them. You can do this like this:
```
define(
    [
        "./Plugin1",
        "./Plugin2",
        "./Plugin3" 
    ],
    function(
        Plugin1,
        Plugin2,
        Plugin3
    ){
        return function MasterPlugin(){
            return function install(openmct){
                openmct.install(Plugin1())
                openmct.install(Plugin2())
                openmct.install(Plugin3())

            }
        }
    }
)
```
I'm not sure if this is the correct way of doing this but it worked for me. Hope it helps you :)
