### ISSUE TITLE
[Notifications] Improve the info message for copy success

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#331]
After successfully copying an object, a success message is displayed and auto-times out. The message is still visible in the message list, however the current message is "Copying complete.". This is fine for the realtime notification, but when it appears in the list it does not tell the user which copy event it relates to. The success message should be updated to show the name of the object that was copied.

**Comment by Costigan** [comment]
I agree with the previous comment.

I'm fine with success notifications appearing in the list, but all notifications need to provide enough information to understand later what they pertained to.  I'd also like timestamps.

**Comment by dtailor90** [comment]
Closing as unverified.
@juliecwang - Add testing notes, so we can verify the fix during the next testathon.

**Comment by juliecwang** [comment]
#Testing Notes 
1. Create new object in any folder.
2. Duplicate object into Style Guide Home Folder.
3. Verify that object name is displayed in copy success notification.
4. Verify that timestamp is present for error notifications.

**Comment by dtailor90** [comment]
Verified Fixed - 07/02/18
