### ISSUE TITLE
[Tables] Object names should appear in tables

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3312]
When adding multiple telemetry points into a table a name column is needed in order to differentiate between values from different sources.

This can be done without modifying the telemetry data itself, by adding a `TelemetryTableNameColumn` that extends `TelemetryTableColumn`, and which overrides the `getFormattedValue()` method.

The table should automatically add a name column and populate it with the name of the object. Currently some telemetry providers are automatically adding the object name to telemetry (namely the VISTA telemetry providers and the Sine Wave Generator in Open MCT). These should be updated to remove the insertion of a name column into the telemetry itself.

When changing the table, you should make sure that the Export as CSV function is also exporting the name column.

**Comment by charlesh88** [comment]
Verify fixed Testathon 11-06-20.

**Comment by shefalijoshi** [comment]
Verified fixed.
