### ISSUE TITLE
[Display Layout] User should be able to toggle grid lines

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#3315]
## Overview
Allow the user to toggle the grid line visibility of a given display layout view. See #3293.

## Expected Behavior
- When displaying gridlines, clicking toggle button should hide gridlines and change toggle button icon accordingly.
- When not displaying gridlines, clicking toggle button should show gridlines and change toggle button icon accordingly.

## Steps to Reproduce
1. Navigate to and edit a display layout
1. [Verification] Verify you can toggle gridlines
1. With gridlines hidden, save the display layout and immediately edit the display layout.
1. [Verification] Verify gridlines are visible
1. Repeat steps as necessary with different selections within the display layout (single and multi-selection)
1. [Verification] Verify toggling gridlines is selection agnostic

**Comment by deeptailor** [comment]
Verified 11/2/2020

**Comment by shefalijoshi** [comment]
Verified fixed.

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by charlesh88** [comment]
Verified Testathon today.
