### ISSUE TITLE
[Navigation] Tree drill down animation should be smoother

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#3320]
## Overview
When drilling down, the animation is slightly jarring, since new nodes to be expanded are displayed first, and then nodes to be collapsed are then hidden.

## Expected Behavior
Animation should be smoother

## Steps to Reproduce
1. Ensure you have multiple items in tree in current view
1. Drill down on a node with children (click right arrow)
1. Verify that for less than a second the tree displays too many nodes (may need to go back and forth a few times to see)

![tree blip](https://user-images.githubusercontent.com/3614296/91102670-7ab04080-e61e-11ea-9837-cbade9fd7220.gif)

**Comment by charlesh88** [comment]
Verified _partially_ fixed Testathon 8/28/20. While the "too many nodes" issue has been fixed, the tree now displays "No items" below the Loading indicator, but should not:

![Screen Shot 2020-08-28 at 2 29 07 PM](https://user-images.githubusercontent.com/1056412/91616689-10a7dc00-e93b-11ea-9625-445b5dc5f28d.png)

"No items" should not be displayed until we've really determined there are no items.

**Comment by jvigliotta** [comment]
## Testing
- throttle your internet with chrome dev tools (Network -> Online) change online to 3g (fast or slow)
- navigate down the tree and verify there are not "Loading" and "No Item" texts at the same time

**Comment by nikhilmandlik** [comment]
Testathon 9/14/2020

Still able to reproduce bug where "Loading" and "No Item" texts shows at the same time.

**Comment by shefalijoshi** [comment]
Reopening as this was reproduced.

**Comment by charlesh88** [comment]
Verified fixed Testathon 9/18/2020

**Comment by nikhilmandlik** [comment]
Verified Fixed. Testathon 9/18/2020

**Comment by davetsay** [comment]
Verified
