### ISSUE TITLE
[Conditionals] Description displays incorrect condition on condition re-order

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#3322]
## Overview
Descriptions are not following their conditions on re-order.

## Expected Behavior
Descriptions should match the condition being edited after being re-ordered.

## Steps to Reproduce
1. Create a condition set with two conditions
1. Swap the order of the conditions
1. Edit the second condition
1. Verify the description of the first condition changes on edit of second condition set

![condition reorder](https://user-images.githubusercontent.com/3614296/91104288-52c2dc00-e622-11ea-85fd-6d651d947057.gif)

**Comment by davetsay** [comment]
Verified

**Comment by charlesh88** [comment]
Verified fixed Testathon 8/28/20
