### ISSUE TITLE
[Conditionals] When composition is still loading the condition message shows undefined

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#3326]
Steps to reproduce:

1. Create a condition set, add a telemetry point and create a couple of conditions.
2. Save and reload. 
3. You will notice the message shows undefined in place of the telemetry point in the  message.

Note: You may need to slow down composition, so it takes a few seconds to resolve. 

![image](https://user-images.githubusercontent.com/13260688/91333714-ca0f8180-e782-11ea-889e-7a53e2b52387.png)

**Comment by davetsay** [comment]
verified
