### ISSUE TITLE
Popup overpersistence

### ISSUE THREAD

**Issue by RCarvalhoNASA** [nasa/openmct#333]
![screenshot](https://cloud.githubusercontent.com/assets/5769437/11353445/00b2766a-91f8-11e5-9c09-4f720ae41d4d.jpg)
Testathon 20151123:  When opening an object in a new tab using the right-click menu, when I go back to the original tab, the right-click menu is still there for a little while, and then the mouse-hover details popup is there on the object that was under the menu even though my mouse is up at the tab bar.  Attached screenshot was when my mouse was up on the My Items tab.

**Comment by charlesh88** [comment]
We keep seeing this, related to other bugs as well. May also manifest when we have persistence errors.

**Comment by larkin** [comment]
#1211 is a good tracker for this. closing as dupe.
