### ISSUE TITLE
[Display Layout] User should be able to set outer dimensions

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#3332]
## Overview
Setting and displaying outer dimensions of layouts would aid in building layouts. This is not a hard cutoff, but rather a guide. See #3293.

## Expected Behavior
- User should be able to set horizontal and vertical dimensions (in pixels) for layouts.
- If content extends beyond the dimension limits, the limit is displayed in the layout as an aid.
- If dimensions extend beyond the size of the layout in the current window, the window should be scrollable to the extent of the dimensions
- If selection is the current layout or an object(s) within the layout, the dimension guide should be visible.
- If the selection is a nested inner layout, the dimension guide should be visible for the selected inner layout as well as the parent layout.
- If the selection is an object(s) within the inner layout, the dimension guide should be visible for the inner layout

## Steps to Reproduce
1. Create a layout and observe that horizontal and vertical dimensions can be set in the object creation window
1. Navigate to layout and observe that the dimensions are displayed in the inspector
1. Observe that you can change dimensions by editing the layout properties (context menu)
1. Observe that dimension guide is shown/hidden based on the expected behaviors.

**Comment by charlesh88** [comment]
### Styling Changes
- Added display of configured values;
- Refined look for dimensions box;
- Added `v-if` that only displays dimensions box if both height and width have bee specified;
- Dimensions box now only displays when editing;
- Fixed erroneous CSS selector that was preventing sub-layouts from displaying grid and dimensions properly;

Following screenshots show proper display behavior:
<img width="1552" alt="Screen Shot 2020-09-14 at 11 31 53 AM" src="https://user-images.githubusercontent.com/1056412/93124641-c040b600-f67e-11ea-885b-cc65c4626e9b.png">

<img width="1552" alt="Screen Shot 2020-09-14 at 11 32 03 AM" src="https://user-images.githubusercontent.com/1056412/93124639-c040b600-f67e-11ea-9362-18ded787053e.png">

<img width="1552" alt="Screen Shot 2020-09-14 at 11 32 09 AM" src="https://user-images.githubusercontent.com/1056412/93124635-bf0f8900-f67e-11ea-9917-2c109c9c39e0.png">

**Comment by shefalijoshi** [comment]
Verified fixed.

**Comment by charlesh88** [comment]
Verified Testathon today.
