### ISSUE TITLE
[Navigation Tree] Tree in modal context does not scroll

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#3337]
## Overview
Some styles in new nav seem to be corrupting old nav functionality.

## Expected Behavior
Old tree navigation should work as expected. Scroll should work.

## Steps to Reproduce
1. Go to an object
1. Use conditional styles
1. In modal, observe that there is no scroll so you cannot reach objects in tree

![image](https://user-images.githubusercontent.com/3614296/91521971-e52ae000-e8ad-11ea-8104-7797af7aecca.png)

**Comment by charlesh88** [comment]
Verified fixed Testathon 8/28/20

**Comment by davetsay** [comment]
Verified

**Comment by shefalijoshi** [comment]
Verified!
