### ISSUE TITLE
[v1.2-Release-Candidates] Zoom not changing bounds

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#3346]
## Overview
The bounds display is being changed on zoom operation but the actual bounds are not changing.
`branch: v1.2-Release-Candidates`

## Expected Behavior
Completing a valid zoom operation should change the time conductor bounds.

## Steps to Reproduce
1. Navigate to a plot
1. Perform zoom function (Hover over time conductor axis, click, drag, and release)
1. Observe that bounds in inputs change to zoom bounds.
1. Observe that plot changes with respect to new bounds.

**Comment by deeptailor** [comment]
Closing as merged into V1.2-Release-Candidates
