### ISSUE TITLE
[v1.2-Release-Candidates] bugs in changing x-axis metadata in plots

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#3348]
## Overview
Various issues for switching x-axis metadata in plots

## Expected Behavior

- [x] Should not allow switching x-axis when no data exists for that metadata
- [x] gear icon should not display when switching x-axis is not allowed
- [x] bounds change should reset x-axis selection to current time system
- [x] switching x-axis then pan/zoom then reset should go back to good state (or disable pan/zoom after switch)

## Steps to Reproduce
1. Navigate to an endpoint in plot view
2. Hover over x-axis label (if multiple metadata exists)
3. Select new x-axis metadata from dropdown

**Comment by deeptailor** [comment]
Closing as merged into V1.2-Release-Candidates
