### ISSUE TITLE
[Open MCT] Change default "The Root Object" Root name to "Open MCT"

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#3349]
When more than one root child is present in the navigation tree, the root object itself shows up with it's default name of "The Root Object". Need to rename this to "Open MCT". Users can use the DefaultRootName plugin to modify further.

## Testing
- on any Open MCT instance with multiple root children and no DefaultRootName plugin being used, verify root name is "Open MCT"

**Comment by nikhilmandlik** [comment]
Verified Fixed. Testathon 9/14/2020

**Comment by deeptailor** [comment]
Verified Fixed. Testathon 9/14/2020
