### ISSUE TITLE
[Actions] Rewrite Duplicate Action in new Action Style

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#3357]
Need to rewrite the legacy duplicate action in the new action style. Also, need to add the ability to rename while duplicating.

related: #604
related: #2863 

## Testing
- Create two folders or use existing folders or objects
- Create a new object to duplicate, or use an existing object
- Right click on the object to move and select "Duplicate"
- (optional) Change the name to something new
- Select a new folder (try same folder as well)
- Click OK
- Verify the object was duplicated into the selected folder (no alias)
- Verify the object remains in the current folder as well
- If you changed the name, verify the name has been updated to reflect that
- Try different variations of above (different types of objects, etc)

**Comment by charlesh88** [comment]
Verified _partially_ fixed Testathon 11-30-20. Problem occurs when duplicating objects with composition.

1. Make a new item that has composition (plot, Tabs View, etc.) and put child objects in it. Save it.
1. Dupe the new item and rename it (although renaming is not essential to manifesting the problem).
1. Observe: a persistence error will occur, and after a refresh the duped item will have become an alias. If renamed, the new name if thrown away and reverted to the original name.

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by shefalijoshi** [comment]
Verified Fixed.

**Comment by davetsay** [comment]
reopen for further testing regarding 409

**Comment by jvigliotta** [comment]
## Testing
(basically run through @charlesh88 's steps from above)
1. Make a new item that has composition (plot, Tabs View, etc.) and put child objects in it. Save it.
1. Dupe the new item and rename it (although renaming is not essential to manifesting the problem).
1. Observe: a persistence error will occur, and after a refresh the duped item will have become an alias. If renamed, the new name if thrown away and reverted to the original name.

Verify no persistence issues and items remain on refresh

**Comment by akhenry** [comment]
Verified fixed

**Comment by deeptailor** [comment]
Verified Fixed
