### ISSUE TITLE
Error persisting new objects if object from non-persistable namespace selected in tree

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3363]
### Reproduction steps
1. Enable the styleguide plugin. This will give you a non-persistable namespace
ie. in index.html, add `example/styleguide` to [the array of legacy plugins](https://github.com/nasa/openmct/blob/18b2a270c914ff8ec1178e1a099ae364fb116f6a/index.html#L40) that are loaded on startup.
``` JavaScript
[
    'example/eventGenerator',
    'example/styleguide'
].forEach(
    openmct.legacyRegistry.enable.bind(openmct.legacyRegistry)
);
```
2. Select any object in the styleguide
3. Click on the Create button, and create any object.
4. Select any location under "My Items" to save the new object.
5. A persistence error will occur. This is because the styleguide namespace is being used to persist the object.

This is an ancient bug that was fixed years ago by doing a copy from the original namespace, to the namespace of the object selected in the tree when the Save As dialog is shown. This copy step caused problems with the new Object persistence API, and [so it was removed](https://github.com/nasa/openmct/commit/9f7799b44f1cb16d40b60a734742aa2e04e7c6f3#diff-55181241cfa7aebea9080d84a4490c0bL153).

### Proposed Solution
The namespace of the object should be updated after the user has selected the save location. This could be done [where the `location` of the new object is set](https://github.com/nasa/openmct/blob/master/platform/commonUI/edit/src/creation/CreateWizard.js#L114).

**Comment by akhenry** [comment]
Testing instructions:

* If testing locally, follow reproduction steps in description.
* If testing in another environment, instead of enabling the styleguide, select an object in a non-persistable namespace (eg. a telemetry point in a telemetry dictionary).

**Comment by shefalijoshi** [comment]
Verified on 09/14/2020
