### ISSUE TITLE
[Style] new glyphs

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#3366]
## Overview
- icon-3-dots
- icon-grid-on
- icon-grid-off
- icon-camera

## Expected Behavior
- glyphs are available for use and visible when used

## Steps to Reproduce
1. manipulate dom directly in inspector
1. replace any existing icon in Open MCT with the above icons
1. Observe that the icons exist and display properly

**Comment by jvigliotta** [comment]
Testathon 09/14/20
Not seeing this on Hulk...

Was able to replace other existing icons like folder in new places, but not the new ones.

**Comment by davetsay** [comment]
Verified

**Comment by jvigliotta** [comment]
Verified: Testathon 09/14/20

I'm seeing this working now.
