### ISSUE TITLE
[Navigation Tree] Padding for loading indicator should be the same as current children

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#3370]
The padding for the loading spinner and text doesn't seem to change the further down the tree you go. Need to add padding equal to the current children padding.

**Comment by akhenry** [comment]
09/18 Verified Fixed

**Comment by nikhilmandlik** [comment]
Verified Fixed. Testathon 9/18/2020

**Comment by charlesh88** [comment]
Verified fixed Testathon 9/18/2020

**Comment by shefalijoshi** [comment]
Verified on 9/18/2020

**Comment by davetsay** [comment]
Verified
