### ISSUE TITLE
Angular 9?

### ISSUE THREAD

**Issue by glapointe** [nasa/openmct#3381]
I've got an existing Angular 9 application to which we're trying to add real-time telemetry charts and I was directed to this project by some folks at JPL but from what I can tell it would appear that OpenMCT only works with AngularJS? If I'm mistaken in that can you direct me to any documentation or provide any guidance regarding how to make this work with an Angular 9 application? Also, I noticed that the themes provide styles for common tags (body, div, a, etc.) which suggests to me that the intent of this framework is to be for the entire SPA and not just controls within an existing SPA which makes me think that even if I were doing AngularJS that this just wouldn't be appropriate? Guess I'm looking for general guidance around usage of this before I invest tons of time digging through all of the docs.

I very much appreciate any insights or help that folks can provide!

Thanks!

**Comment by sometimesvlad** [comment]
> Also, I noticed that the themes provide styles for common tags (body, div, a, etc.)
What kind of themes you are talking about?

Btw, checked that latest openMCT does not depend on AngularJs and is distributed as a normal npm package, when using this api in ANGULAR 9 just a layer of components / modules / services will be added, so you have to develop in context of classes

References: 
[Official website](https://nasa.github.io/openmct/getting-started/)
[OpenMCT API](https://github.com/nasa/openmct/blob/master/API.md)
[Tutorial](https://github.com/nasa/openmct-tutorial)

**Comment by akhenry** [comment]
@glapointe Open MCT exposes no external dependency on Angular, however some of our legacy code uses Angular 1 internally. How this will behave when loaded alongside an Angular app of a different version is unclear, we haven't tested it. We'd love to know if you try it out though. Our current timeline for removing all legacy Angular code is by mid 2021.

To your point about it being an SPA, this is correct. Right now you cannot load Open MCT visualizations in isolation. We are currently considering making this a possibility though.

If you want to get a sense of how Open MCT works and some of its capabilities, you can check out [our online demo](https://openmct-demo.herokuapp.com/). If you decide to dig a little deeper and want to get a better understanding of what telemetry integration looks like in Open MCT, take a look at the tutorial (as @sometimesvlad suggested - thanks!).

**Comment by glapointe** [comment]
Thanks for the feedback guys! Because I have an existing app I was hoping to integrate with it's not going to be a good fit for me given Andrew's response but I would definitely look at it again in the future if the visualizations are usable in isolation. (Right now we're using Telerik's chart controls but I haven't been overly happy with it when dealing with high frequency data coming from a SignalR feed so I was looking for something that could handle lots of data a little better).

Vladislav, to clarify about the themes - per the tutorials, when adding the Espresso plugin or any other theme, it adds the appropriate styles which contain global selectors such as anchor and body and div tags, etc. (https://github.com/nasa/openmct/blob/master/src/styles/_global.scss). This makes sense given Andrew's point about it driving a complete SPA versus working in isolation.

Thanks again for the info!

**Comment by akhenry** [comment]
@glapointe Interesting that your use case is real-time data. What we found when we looked for off the shelf plotting libraries was that most of them are great at plotting static data, or at best low-frequency real-time data, but none of them were particularly performant with high data rates. The closest we came to finding something performant was Plotly in webgl mode, but we were still not quite seeing the performance we wanted. So, we implemented our own.

There were some commercial plotting libraries we looked at which looked very promising, but we don't want Open MCT depending upon commercial software.

So, yeah, there seems to be a gap in the "open source realtime plotting software" market 😄

**Comment by glapointe** [comment]
@akhenry Yeah, we're trying to do something pretty simple right now (or should be simple) - we have a model representing components and sensors and we're trying to chart the health status of each over time (eventually we want to chart other data such as suspension rate, etc.). The model could have dozens of components and sensors sending data at anywhere from 5hz to 100hz. I'd be curious to know what commercial products you evaluated though to see if one can perform better than the Telerik chart we're using.
