### ISSUE TITLE
[Tree] Tree scrolling area should not display horizontal scroll

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3383]
![Screen Shot 2020-09-18 at 2 34 32 PM](https://user-images.githubusercontent.com/1056412/93646981-349b9200-f9bc-11ea-8108-4a429db97155.png)

### Reproduce
1. Open the tree and size the window such that a vertical scroll will be forced.
1. Observe: a track for horizontal scroll is displayed (purple arrow) but only the track and thumb for the vertical scroll should be visible.

### Additional Testing Notes
I think this also fixes the undocumented "scrollbars not appearing when they should" bug. To verify do the following: nav somewhere in the app that has enough items in it that you can resize the browser window such that the bottom-most tree item can be covered. 
![Screen Shot 2020-09-18 at 3 07 28 PM](https://user-images.githubusercontent.com/1056412/93655250-2eff7580-f9d7-11ea-8b09-31a102bd4d05.png)

If the problem has NOT been fixed then you should be able to hide the bottom-most item without scrollbars appearing. If scrollbars DO appear even as you start covering the bottom-most item, then the problem has been fixed.

**Comment by nikhilmandlik** [comment]
Verified Fixed. Testathon 10/09/2020

**Comment by davetsay** [comment]
Verified
