### ISSUE TITLE
Object tree cannot be navigated while it's loading

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3384]
Steps to reproduce:
1. Throttle your bandwidth to a 3G connection.
2. Expand a tree node that requires a connection to a server (eg. "My Items" or "Shared Items" using the Couch DB adapter. LocalStorage will not manifest this problem)
3. Observe the "loading" indicator while the browser requests the tree composition from the server
4. Before the tree items are loaded, attempt to expand a parent node using the `<` arrow next to that node.
5. Observe that the node does not expand.

**Comment by deeptailor** [comment]
Verified

**Comment by davetsay** [comment]
verified

**Comment by nikhilmandlik** [comment]
Verified Fixed.
