### ISSUE TITLE
how to archive telemetry in open mct and retrieve it later

### ISSUE THREAD

**Issue by Vaibhav2121** [nasa/openmct#3386]
Dear All,

I am new to openmct. I want to know how to archive telemetry and how to retrieve data later using plots. How to give start time and end time to open mct software and plot telemetry data in between these times in this software.

**Comment by Vaibhav2121** [comment]
My main concern is that whether it is possible in open mct to archive and retrive data. If yes then whats the procedure to archive and retrieve data later.

**Comment by deeptailor** [comment]
Hi Vaibhav,

In order to archive data, you'll have to create a backend that would allow you to record data as it comes in, then re-publishes it via a websocket or an REST API, that Open MCT will be able to use.

**Comment by Vaibhav2121** [comment]
Thanks

**Comment by Vaibhav2121** [comment]
Hi Deep,
We have created a Backend and data is available but now the question in
which port open mct listens for data. In which format open mct accepts data
that is date time, data element key, data. Should we provide data in text
file from where open mct can read it. Suppose we want to plot more than one
day archived data is it possible in this software.
