### ISSUE TITLE
Saving a display layout after changing it's subobject view throws 409 error

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#3389]
Create a display layout
Add alpha numeric telemetry
Save the display layout
Edit the layout and switch the type of the alpha numeric to either stack or overlay plot
Edit the properties of the plot and change it's name
Save the display layout

Expected: Display layout and changed telemetry are saved
Observed: Error persisting the telemetry

**Comment by deeptailor** [comment]
Verified Fixed - 10/05/2020

**Comment by jvigliotta** [comment]
Verified Fixed - 10/05/2020

**Comment by davetsay** [comment]
Verified
