### ISSUE TITLE
[LegacyPersistenceAdapter] readObject only taking one argument, when it should accept two

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#3393]
The readObject method in the LegacyPersistenceAdapter only accepts one argument, it needs to accept two arguments (space, key) and use those to form the identifier passed to the objectAPI get method.

## Testing
Verify any legacy objects are being indexed in search

**Comment by shefalijoshi** [comment]
Closing since this is fixed by the PR above.

**Comment by deeptailor** [comment]
Verified Fixed 10/05/20

**Comment by shefalijoshi** [comment]
Verified Fixed 10/05/2020
