### ISSUE TITLE
[Images] Add helper class and metadata attributes for VERVE integration

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3394]
VERVE requires some imagery metadata to be provided from Open MCT when an image is clicked on.

1. Add an additional `js-verve-image` class to [the div element that contains the image in the imagery view](https://github.com/nasa/openmct/blob/master/src/plugins/imagery/components/ImageryViewLayout.vue#L25) to allow VERVE to easily select the image element and attach a click event listener. 
2. Add new data attributes `data-openmct-image-timestamp` and `data-openmct-object-keystring`. These will allow VERVE to retrieve the timestamp of the image, and the ID of the image object (which contains the camera name).

This will allow VERVE code to add a click event listener to image elements, and retrieve metadata like so:

```
document.querySelectorAll('.j-verve-image').forEach((imageElement) => {
    imageElement.addEventListener('click' () => {
        const timestamp = imageElement.dataset.openmctImageTimestamp;
        const camera = imageElement.dataset.openmctObjectKeystring.split('~')[2].match(/(.*)_image_url/)[1];
    });
});
```

**Comment by jvigliotta** [comment]
## Testing

- load up example imagery plugin and right click and "inspect"
- verify that "j-imagery-image" class is on the div
- verify data attributes: data-openmct-object-keystring and data-openmct-image-timestamp exist and are populated

**Comment by akhenry** [comment]
Verified fixed with simulator imagery 10/05/2020.
