### ISSUE TITLE
Root object has no view, but needs one

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3398]
When the root object is exposed in the tree, navigating to it displays nothing in the main view:

<img width="1563" alt="Screen Shot 2020-09-24 at 9 59 33 AM" src="https://user-images.githubusercontent.com/1056412/94176472-ff27f600-fe4c-11ea-99bf-7dd42f9f25c3.png">

Instead, the root object should use the folder view.

**Comment by charlesh88** [comment]
Seen again during Testathon 3-3-21, we need to fix this.

**Comment by unlikelyzero** [comment]
Cannot repro
