### ISSUE TITLE
[Image Telemetry] Support pan-zoom

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#34]
Support pan-zoom of image telemetry. This should function similarly to pan/zoom in plots. Specifically:
- Click-drag should marquee zoom into an area of an image
- Shift-click-drag should pan around the image
- Once panned or zoomed, buttons should become available in the top right:
  - Step back pan-zoom
  - Reset pan-zoom

Example image telemetry is available with bundle `example/imagery` (add `"example/imagery"` to `bundles.json`)

Note that, once panned or zoomed, the image should pause an stop updating with the latest image telemetry (I believe; double check with @charlesh88  on this point)

**Comment by akhenry** [comment]
@charlesh88 to provide some technical guidance here.

**Comment by nikhilmandlik** [comment]
1. when on imagery Layout resize window causes, main image overflow
2. hide lock when not zoomed (cant click to lock when not zoomed) also disable
3.

**Comment by jvigliotta** [comment]
I think we shouldn't show the magnify icon when outside of the image, as it doesn't do anything.

**Comment by akhenry** [comment]
Seeing an issue where I just see a blank image sometimes when I navigate to an image. 

To reproduce:
1. Navigate to an imagery telemetry point
2. Refresh the browser
3. Note that although thumbnails appear, the main image view is blank.

OR
1. Navigate to an imagery telemetry point
2. Navigate away, and back again.
3. Repeat **2.** until eventually you will see a case where the main image area is blank.

**Comment by charlesh88** [comment]
Testathon 2/1/22
- Blocker: zoom click in an image that has been placed in a Layout sends that image to the Large View overlay when the user intended to zoom the image. We should replace with a Cmd/Windows keydown and click to allow the zoom in click, or remove the single-zoom-click gesture. The magnify cursor should only be shown on when the correct key is down for zoom if we're going with that solution.
- The thumb strip displays a yellow selection style _and_ a white selection indicator, but should only display one:
![Screen Shot 2022-02-01 at 12 00 08 PM](https://user-images.githubusercontent.com/1056412/152042334-dc39d1a5-71db-4f8c-a02b-7bbbc9242788.png)
The white selection should be shown when the TC is in Fixed Mode, and yellow when in RT. Unclear if this a regression occurring in this branch, or pre-dates it.
- When the image is zoomed, the grab cursor is displayed at all times, but should only be displayed if the user is keydown on `alt`.

**Comment by charlesh88** [comment]
Testathon 2/2/22:
- Initially, imagery in main view required Cmd-click to zoom, but then something changed and it's now in single-click mode again. Cmd-click should always be required. This is sporadic and I can't replicate.
- BLOCKER: still going to overlay on Cmd-click on image in Display Layout.

**Comment by michaelrogers** [comment]
### How To Test
_Navigate to example imagery_

* Zoom in using mousewheel
* Zoom out using mousewheel

* Meta + Click to zoom in
* Meta + Shift + Click to zoom out

* Click zoom in button
* Click zoom out button
* Click reset button

**Comment by charlesh88** [comment]
Verified in main view and Flexible Layout: fixed Testathon 04-04-22.
