### ISSUE TITLE
[Navigation Tree] Revert locked navigation and handle multiple requests

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#3402]
Recently made a change where if a request for navigation (down/up tree or tree sync) was made and the tree was still "loading" a previous request for navigation, then it would be denied. This creates a situation where if the tree hangs on loading, then you can't navigate away. Need to revert this change and handle these types of situations correctly (just the latest request is navigated).

## Testing
- on any system that is pulling data from a database (ie. couch persistence) make multiple navigation requests (up/down tree, sync tree, etc)
- verify that only the last of those requests is what ends up in the tree

**Comment by shefalijoshi** [comment]
Verified fixed 10/05/2020

**Comment by akhenry** [comment]
Verified fixed 10/05/2020
