### ISSUE TITLE
Image thumbnail display is broken

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3412]
From hulk/viper:

![Screen Shot 2020-09-30 at 6 13 59 PM](https://user-images.githubusercontent.com/1056412/94848493-ef725980-03d8-11eb-966d-05732df2aeff.png)

Fix and deploy asap ahead of next week's sims.

**Comment by charlesh88** [comment]
My local master can't reproduce this in Chrome or Firefox. Arrrggghhhh...

![image](https://user-images.githubusercontent.com/1056412/94869786-e4302580-03fa-11eb-8ae6-44754193ed0a.png)

**Comment by shefalijoshi** [comment]
The root cause is that the viper telemetry is using `iso` format for timestamps while example imagery uses `utc`
Resulting in the following timestamps:
Viper telemetry: 2020-10-01T22:50:49.897Z
Example telemetry (has a space that allows wrapping of text): 2020-10-01 22:51:45.000Z

**Comment by charlesh88** [comment]
The problem here is data formatting. We expected and used to get
> 2020-10-01 22:51:45.000Z

but are now getting this ISO format instead
> 2020-10-01**T**22:50:49.897Z

The UI needs a clear distinction between date and timestamp to wrap properly.

**Comment by charlesh88** [comment]
### Testing Notes
1. Get to an Imagery view that uses ISO-formatted datetimes; Example Imagery doesn't suffice, but the code running on a mission deployment like VIPER will.
1. Observe the thumbnails: the datetime should look like this

![image](https://user-images.githubusercontent.com/1056412/94869786-e4302580-03fa-11eb-8ae6-44754193ed0a.png)

and not like this

![Screen Shot 2020-09-30 at 6 13 59 PM](https://user-images.githubusercontent.com/1056412/94848493-ef725980-03d8-11eb-966d-05732df2aeff.png)

**Comment by charlesh88** [comment]
Verified Testathon 10-05-20

**Comment by deeptailor** [comment]
Verified fixed 10-05-20
