### ISSUE TITLE
[Persistence] Couch DB provider is not working

### ISSUE THREAD

**Issue by jmlgo** [nasa/openmct#3417]
After enabling the Couch DB persistence provided as commented [in this issue](https://github.com/nasa/openmct/issues/3201) using the default index.html, several errors appear in the console and the tree never loads.
The database exists and is public, and CORS is enabled for all domains.

![Screenshot_20201005_095103](https://user-images.githubusercontent.com/16480649/95053605-f4911a80-06f0-11eb-8183-32860e9244bd.png)

**Comment by shefalijoshi** [comment]
**Testing instructions.**
Run CouchDB locally and ensure that there are no documents in the database.
Run OpenMCT and ensure that MyItems shows up in the UI
Add an object to the MyItems folder and save it
REfresh the browser and ensure that MyItems and the new object are present.

**Comment by akhenry** [comment]
Verified fixed.
