### ISSUE TITLE
Add lookahead time to the plan view

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#3418]
The Plan view should show 30 minutes ahead of the time end bounds

**Comment by shefalijoshi** [comment]
**Testing Instructions:**
For Fixed timespan, add a known start and end bounds to the plan view
Import a plan (JSON)
Observe the time axis on the top of the Plan view
Expect to see 30 minutes added to any end time you see in the time conductor

**Comment by charlesh88** [comment]
Verified fixed Testathon 3/29/21. Note this doesn't work for Timestrip view.

**Comment by shefalijoshi** [comment]
See #3772 for related work
