### ISSUE TITLE
[Search] Objects in search tree do not have same functionality as objects in navigation tree

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#3420]
## Overview
When searching, some objects do not have full functionality. Clicking does not navigate to object. Context-clicking does not provide context-click menu. Seems to be an issue only with object dictionaries, non-creatable objects. Created items seem to have full functionality.

## Expected Behavior
Searched items should have same functionality as navigation tree items

## Steps to Reproduce
1. Perform a search in the navigation tree
1. Click on a dictionary object search result
1. Context-click on a dictionary object search result

![image](https://user-images.githubusercontent.com/3614296/95133836-c3c3dc00-0716-11eb-955b-0986b43f8b35.png)

on context click of searched dictionary item
```
PreviewAction.js:84 Uncaught TypeError: Cannot read property 'identifier' of undefined
    at u._isNavigatedObject (PreviewAction.js:84)
    at u.appliesTo (PreviewAction.js:77)
    at ContextMenuAPI.js:93
    at Array.filter (<anonymous>)
    at t.default._showContextMenuForObjectPath (ContextMenuAPI.js:80)
    at showContextMenu (context-menu-gesture.js:33)
    at HTMLAnchorElement.n (vue.min.js:6)
```

**Comment by davetsay** [comment]
Debugging notes:

In mct-tree.vue, getSearchResults(), objectPath and navigateToParent only get set if object has context capability, which it does not. If i click on the object in navigation tree, not search tree, I can see that it is not doing a similar check for a context capability. getSearchResults() code below.

If I search for a created object (like a folder), before getting to the getCapability call in DomainObjectImpl.js a context capability is exposed.
 
```
        async getSearchResults() {
            let results = await this.searchService.query(this.searchValue);
            this.searchResultItems = results.hits.map(result => {

                let context = result.object.getCapability('context');
                let object = result.object.useCapability('adapter');
                let objectPath = [];
                let navigateToParent;

                if (context) {
                    objectPath = context.getPath().slice(1)
                        .map(oldObject => oldObject.useCapability('adapter'))
                        .reverse();
                    navigateToParent = objectPath.slice(1)
                        .map((parent) => this.openmct.objects.makeKeyString(parent.identifier));
                    navigateToParent = ROOT_PATH + navigateToParent.reverse().join('/');
                }

                return {
                    id: this.openmct.objects.makeKeyString(object.identifier),
                    object,
                    objectPath,
                    navigateToParent
                };
            });
        }
```

**Comment by davetsay** [comment]
Self Verified

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 10/09/2020
