### ISSUE TITLE
Add Timeline plugin to hulk deployment

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#3422]
Add the following plugin to the hulk deployment
        openmct.install(openmct.plugins.Timeline());

**Comment by jvigliotta** [comment]
Tracking this in Jira: VIPEROMCT-22

**Comment by akhenry** [comment]
Fix has been merged and VIPEROMCT-22 closed.

**Comment by nikhilmandlik** [comment]
Verified Fixed. Testathon 10/09/2020

**Comment by akhenry** [comment]
Verified fixed 10/09/2020

**Comment by davetsay** [comment]
Verified
