### ISSUE TITLE
[Notebook] Clicking new entry does not work as expected

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#3423]
1. Create a new notebook
2. Try to add a new entry
3. Observe that the entry appears for a brief moment, then disappears.

Edit: you may have to use the couch db provider to see this issue. 

This may be an issue with the domainObject not being in sync with the persisted domainObject

**Comment by davetsay** [comment]
@nikhilmandlik , this is most likely due to a mutation bug we're seeing (not on local). Please see #3425

**Comment by shefalijoshi** [comment]
Fixed by https://github.com/nasa/openmct/pull/3431

**Comment by akhenry** [comment]
Reopening, not fixed by #3431

**Comment by nikhilmandlik** [comment]
Verified Fixed. Testathon 10/9/2020

**Comment by jvigliotta** [comment]
Verified Mostly Fixed - Testathon: 10/09/2020

Benign (possibly) error in console when creating a new entry.
![Screen Shot 2020-10-09 at 10 54 15 AM](https://user-images.githubusercontent.com/12013460/95615920-d7748880-0a1d-11eb-8fa2-8140f382a368.png)

**Comment by davetsay** [comment]
Filed new issue for console error
