### ISSUE TITLE
[Display Layout] Regression with cancelling edits

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#3425]
There is regression where if an item in a display layout is edited (change properties) and then you cancel the changes (ie not save), the changes are not thrown away.

**Comment by deeptailor** [comment]
This issue is not reproducible using local storage.

**Comment by shefalijoshi** [comment]
**Testing Instructions:**
In addition to testing cancelling edits for display layouts and individual objects, also test the following:

Do each of these with CouchDB and for LocalStorage persistence:
1. Creating new objects works
2. Creating new folders and nested folders works
3. Right-click actions on objects in the tree works
4. Searching the tree works.

**Comment by nikhilmandlik** [comment]
Verified Fixed. Testathon 10/09/2020

**Comment by davetsay** [comment]
Verified

**Comment by akhenry** [comment]
Verified fixed 10/09/2020
