### ISSUE TITLE
[Testing] Error while running npm test

### ISSUE THREAD

**Issue by nikhilmandlik** [nasa/openmct#3426]
### Description:
exportImageServiceProvider error while testing
### Testing instructions:
1. Run `npm run test`
2. observe errors 
 - `ERROR: Error: [$injector:unpr] Unknown provider: exportImageServiceProvider <- exportImageService`
 - `[Vue warn]: Injection "stylesManager" not found`
 - `[Vue warn]: Error in mounted hook: "TypeError: identifier is undefined"`

### Expected Result:
Pass all tests without error
### Actual Result:
Pass all tests with error
### Screenshots:
<img width="1763" alt="Screen Shot 2020-10-07 at 8 40 27 AM" src="https://user-images.githubusercontent.com/1292612/95356774-e28fb300-087b-11eb-81bb-8aa68c7a4187.png">

**Comment by akhenry** [comment]
Verified fixed.

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 12/14/2020
