### ISSUE TITLE
[Navigation Tree] Deleting selected item does not highlight parent when it's selected after

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#3438]
## Observed
- Delete a child folder folder that's currently selected in tree
- Parent folder is now being viewed
- Parent folder is NOT showing as selected

## Expected
- Deleting a child folder that is selected in the tree should update viewed object to parent (does so correctly) AND highlight parent in the tree

**Comment by deeptailor** [comment]
Verified

**Comment by akhenry** [comment]
Verified fixed.

Found a related issue though - https://github.com/nasa/openmct/issues/3490

**Comment by charlesh88** [comment]
Verified fixed Testathon 11-06-20.

**Comment by nikhilmandlik** [comment]
Verified Fixed.
