### ISSUE TITLE
[Tree] Ancestor composition not being watched for changes

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#3439]
## Overview
Ancestors are not being watched for changes to its composition so changes on the current object, if it children are expanded

## Expected Behavior
The tree structure should react to all changes current visible tree.
* deleting the current node if it has children expanded should be removed from tree

## Steps to Reproduce
1. Create a display layout
1. Create any subobject with a child
1. Expand tree so that the display layout, the subobject, and the subobject's child(ren) are visible
1. In edit mode, delete the subobject
1. Observe that the node in the tree has not changed.

![tree delete](https://user-images.githubusercontent.com/3614296/95614284-18b76900-0a1b-11eb-8d50-86dd0a0ed066.gif)

**Comment by akhenry** [comment]
Verified Fixed 11/02/2020
