### ISSUE TITLE
My Items plugin can not load correctly.

### ISSUE THREAD

**Issue by ja-why-son** [nasa/openmct#3444]
I installed the plugins `MyItems` but in the app it seems like MyItems can't find the object provider properly.

For reference, here's the code I used to set up openMCT
```
<script>
        openmct.setAssetPath('node_modules/openmct/dist');
        openmct.install(openmct.plugins.LocalStorage());
        openmct.install(openmct.plugins.MyItems());
        openmct.install(openmct.plugins.UTCTimeSystem());
        openmct.install(openmct.plugins.Espresso());
        openmct.install(openmct.plugins.SummaryWidget());

        openmct.start();
    </script>
```

Reproduce process: 
1. Clone a new openMCT repo
2. Add MyItems plugin
3. `npm install`, `npm start`
4. Will be able to see that `MyItems` folder is not being populated correctly.

I've tried removing the plugins, but the whole object tree still won't be populated correctly, so it may be another issue that caused this bug. 

![Screen Shot 2020-10-09 at 1 04 59 PM](https://user-images.githubusercontent.com/39038039/95627006-4529b000-0a30-11eb-8988-bb204f8adac2.png)

**Comment by akhenry** [comment]
@ja-why-son Thanks for reporting this. We are looking into it and we will have a fix very soon.

**Comment by deeptailor** [comment]
See #3462 for a workaround.

Closing as duplicate

**Comment by shefalijoshi** [comment]
See https://github.com/nasa/openmct/issues/3417 for testing instructions for the fix.

**Comment by akhenry** [comment]
Verifying...

**Comment by akhenry** [comment]
@ja-why-son This has been fixed and verified in our testing. Thanks for reporting it, and please let us know if you are still having issues.
