### ISSUE TITLE
[Notebook] Link to snapshot should not be a fully qualified url

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#3445]
## Overview
Links to snapshots are saved as fully qualified urls so stale links can lead to bad places. They should be stored as object paths.

## Expected Behavior
Links should not redirect to a different deployment

## Steps to Reproduce
Seen on server hosting multiple deployments. Snapshot was taken on deployment 1. From deployment 2, clicked on the snapshot and was redirected to deployment 1.

**Comment by nikhilmandlik** [comment]
Actually it was done to capture properties such as time, view , timeSystem etc.
So that it represents correct link to the exact view captured inside screenshots.

eg: view=table&tc.mode=fixed&tc.startBound=1602288014694&tc.endBound=1602289814694&tc.timeSystem=utc

**Comment by akhenry** [comment]
Not fixed 11/02/2020.

When I click on a notebook link created in another system I do not observe any navigation occurring at all.

Steps to reproduce:
1. Create a new notebook on one test system
2. Drag an object or telemetry point available on both systems into the notebook to create a new entry.
3. Export to JSON
4. In other system, import JSON file exported in previous step
5. Observe that clicking on the link to the object has no effect.

I also observed what appears to be a bug in the markup. Don't know if it's related:
![Screen Shot 2020-11-02 at 2 22 02 PM](https://user-images.githubusercontent.com/4215777/97925797-daaa1e00-1d16-11eb-8d4d-b8fe252f080a.png)

Note that the outer element has an attribute named `entry` with a value of `[object Object]`. Two things about this:
1. `[object Object]` is clearly a bug, and should be investigated
2. We should not be adding non-standard attributes like `entry`. If we need to add attributes to elements we should use `data` attributes.

**Comment by davetsay** [comment]
Tested by comparing notebook entries in another deployment. Could see urls changing based on older code. With fix in, url stays consistent to current deployment.

**Comment by akhenry** [comment]
Needs investigation, if unrelated, create new issue and close and verify this one.

**Comment by nikhilmandlik** [comment]
> Needs investigation, if unrelated, create new issue and close and verify this one.

fixed,
1. import notebook issue, older version had full url link saved, instead of hash
2. [object Object]  was due to unregistered prop passed to vue component.

**Comment by davetsay** [comment]
verified

**Comment by shefalijoshi** [comment]
Verified.
