### ISSUE TITLE
[Navigation Tree] Duplicate ancestors showing in the tree

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#3450]
When tree objects take a long time to load, there were certain situations (mainly with tree syncing) that would cause duplicate ancestors to be added to the tree. Need to block navigation while syncing the tree (will not affect other navigation).

## Testing
- you can test on a server that's pulling objects from couchDB
- you can also throttle the network speed to test as well
- when syncing the tree, try to click it multiple times
- when syncing the tree try to reset to any other point in the tree that's loaded
- make sure normal navigation is not affected

**Comment by shefalijoshi** [comment]
Pulled master locally to test this with couchDB.
Not sure if this is an edge case, but here are the steps to reproduce.
1. In index.html run OpenMCT with LocalStorage persistence, refresh OpenMCT in a browser and navigate to an object under My Items.
2. Switch to CouchDB in index.html, refresh OpenMCT and here's what you get:

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/5247066/95895274-46fcb780-0d3f-11eb-900c-1c52c8b509aa.png">

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by akhenry** [comment]
Verified Fixed 11/06/2020. Haven't seen this for a long time now.

**Comment by shefalijoshi** [comment]
Unable to reproduce - Verified fixed.
