### ISSUE TITLE
Procedure to import plugins from old open mct version to new open mct version

### ISSUE THREAD

**Issue by Vaibhav2121** [nasa/openmct#3452]
Some of the plugins that were available in old openmct versions like timeline and activities is not available in new open mct version. I want to use these plugins in my application so how can I do this.

**Comment by deeptailor** [comment]
Hi, we deprecated the old timeline plugin, if you want to use it, you can checkout one of the older branches, but we will not be providing any support for the deprecated plugins

**Comment by deeptailor** [comment]
https://github.com/nasa/openmct/tree/activity-import-2

**Comment by Vaibhav2121** [comment]
I want to use timeline and activity plugins in new open MCT version, how to convert plugins/bundles written in old open mct to new open mct. For old openMCT version that is Apr 2016 there is developer guide available which explains about that version of open MCT where plugins were defined as bundles. Is that type of developer Guide available for present version. There is one tutorial that shows implementation of bar graph and To do list in old open mct version. How can we implement these two plugins in new version. Please tell
