### ISSUE TITLE
Cannot add any additional notebook entries after initial entry

### ISSUE THREAD

**Issue by trgarvey** [nasa/openmct#3453]
Notebook only allows a single note entry, then any more attempts to add an entry result in the UI just briefly flashing a new entry box, then it is gone.  No errors, but a second entry is not permitted.

Browser is Google Chrome.

This is on V. 1.3.0 with hash Revision: 6f2d8e6ce39df86c76df082e5e1aa05f5b34c1f8

![image](https://user-images.githubusercontent.com/57674056/95776907-34c53f80-0c93-11eb-8e99-39bcf649fad9.png)

**Comment by akhenry** [comment]
@trgarvey Thanks for filing this issue. We're aware of this issue (we're tracking this as https://github.com/nasa/openmct/issues/3423), and it *should* be fixed (as of Friday) if you pull the latest from GitHub. Try pulling from master, and let us know if you're still seeing the issue.

**Comment by jvigliotta** [comment]
Hi @trgarvey just wanted to check in to see if this was resolved for you?

**Comment by trgarvey** [comment]
We are still running v.1.3.0 but a quick look at one of your later versions indicates that this seems to work now.  When we get a chance to upgrade to the latest release I can confirm this.

Tom Garvey | Mission Operations Lead
Astrobotic Technology, Inc.
1016 N.Lincoln Avenue

Pittsburgh, PA 15233
www.astrobotic.com<http://www.astrobotic.com/>

**Comment by trgarvey** [comment]
In testing on the latest master (Revision: 59946e89ef57ce32f3c2298f20a5cd6def3c2ec1) the original problem seems to be solved, but a new, more minor bug has been introduced:


  1.  Create a new notebook.
  2.  Try to create an initial entry

The entry will not be created until the user manually clicks away from the notebook object to another screen and returns.  Once returning to the note book, the initial entry will reappear and the notebook will work as expected from that point onward.

This was noticed in the Chrome browser.  The workaround is easy but unless one knows about the bug, it appears initially as though the notebook does not work.



Tom Garvey | Mission Operations Lead
Astrobotic Technology, Inc.
1016 N.Lincoln Avenue

Pittsburgh, PA 15233
www.astrobotic.com<http://www.astrobotic.com/>

**Comment by jvigliotta** [comment]
Hey @trgarvey looks like this one was fixed a couple hours agowith https://github.com/nasa/openmct/pull/3496 

Whenever you get a chance to pull the latest version of master let us know if it resolved the issue for you.

Thanks!

**Comment by akhenry** [comment]
Closing this for now. @trgarvey  let us know if this is still an issue.
