### ISSUE TITLE
Newly created object does not show after navigating away from it in the tree

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#3457]
To Reproduce:
1. Create a new folder under another folder
2. Confirm that it's visible in the tree
3. Navigate away from the parent folder by clicking the < arrow on one of it's ancestor items in the tree
4. Navigate back to the parent folder
Expected: The newly created object is visible in the tree
Observed: The newly created object is not visible in the tree

**Note** that refreshing the browser window will make the new object show up.

Also, removing children of nested folders doesn't always work.

**Comment by akhenry** [comment]
Verified fixed 11/06/2020

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by charlesh88** [comment]
Verified fixed Testathon 11-06-20.
