### ISSUE TITLE
[Conductor] Remove 24 hour default limit in time conductor

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3459]
The time conductor seems to be limited to spans of 24 hours by default ([in index.html](https://github.com/nasa/openmct/blob/1ae8199e89b4fda8fc788b7d8cb63ab80965aa73/index.html#L99)). This limit should be removed in the default configuration, and [the conductor documentation](https://github.com/nasa/openmct/blob/master/API.md#the-time-conductor) should be updated to reference this new option.

**Comment by davetsay** [comment]
verified

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 12/14/2020

**Comment by shefalijoshi** [comment]
Verified
