### ISSUE TITLE
After updating OpenMCT, the default page is "Missing: mct:mine"

### ISSUE THREAD

**Issue by KhaledSharif** [nasa/openmct#3462]
I recently updated my version of OpenMCT. When I clear the browser cache and cookies, and open OpenMCT, I get directed to the default page which now says "Missing: mct:mine". The browser console log shows no errors or warnings. [Screenshot](https://i.imgur.com/nEVGKmG.png).

I'm using the latest version of OpenMCT, commit hash 1ae819.

**Comment by aniston** [comment]
Same issue of "Missing: mct:mine" on a fresh install on Linux :
Debian 10 Buster (4.19.0-11-amd64 #1 SMP Debian 4.19.146-1) 
Node v12.19.0
Git v2.20.1
Open MCT v1.3.1 08b2940

running as root and following the basic installation guidelines of:
```
git clone https://github.com/nasa/openmct.git openmct
cd openmct
npm install
npm start
```
calling up the application at http://localhost:8080 produces the error in the middle pane.
![Missing_mct_mine](https://user-images.githubusercontent.com/3067891/96464538-40cb7700-1228-11eb-874e-f68dd84460b0.png)

reading some past issues , tried:
- the whole install and running procedure as another user that is not the root user with the same results.
- same error even on Windows 10
- cannot Create anything from the left panel as the Location to Save In is showing Missing: mct:mine and hence not able to save. 
![CannotCreate_LOCATION_SaveIn_NotPossible](https://user-images.githubusercontent.com/3067891/96465293-14fcc100-1229-11eb-9faa-4a6b6371f875.png)

I'm wondering if we need to create a directory before starting the App ? though the getting started does not speak of this.

**Comment by deeptailor** [comment]
Hi,

This is a known bug, please use the steps below to get it working for the time being:

Open the browser console and do the following, then refresh the page:

```
let mine = {name: "My Items", type: 'folder', composition: [], location: 'ROOT', modified: 1588717201558, persisted: 1588717201558};
let jsonString = JSON.stringify({"mine": mine});
localStorage.setItem('mct', jsonString);
```

**Comment by shefalijoshi** [comment]
This issue is fixed by https://github.com/nasa/openmct/pull/3461

**Comment by aniston** [comment]
Thanks @deeptailor that worked, I didn't know it was a known bug and as my first experience with OpenMCT searching for issues related to "Missing: mct:mine" only brings up this #3462

however the workaround got me going further.
