### ISSUE TITLE
[Notebook] Cannot add entries to a notebook

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#3464]
Getting the following error when clicking on the new entry section:

Notebook.vue?800c:434 Uncaught (in promise) TypeError: Cannot read property 'identifier' of null
    at s.updateDefaultNotebook (Notebook.vue?800c:434)

**Comment by nikhilmandlik** [comment]
Duplicate: https://github.com/nasa/openmct/issues/3440
PR: https://github.com/nasa/openmct/pull/3443
