### ISSUE TITLE
Imagery brightness and contrast are affecting the wrong DOM element

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3467]
<img width="353" alt="Screen Shot 2020-10-20 at 11 13 03 AM" src="https://user-images.githubusercontent.com/1056412/96627195-5cd12600-12c5-11eb-8a2c-f0f54efda3f0.png">

Controls should only affect the image, not controls. Controls can be made non-visible.
<img width="345" alt="Screen Shot 2020-10-20 at 11 13 40 AM" src="https://user-images.githubusercontent.com/1056412/96627192-5b9ff900-12c5-11eb-8e05-db0d7b8e1fa5.png">

**Comment by charlesh88** [comment]
### Testing Notes
1. Navigate to an image telemetry view or Example Imagery object.
1. Hover over the image area. Change the image and contrast both quite low to almost completely darken the image.
1. Verify that the prev and next arrows do not change their appearance as the image is changed.
<img width="950" alt="Screen Shot 2020-10-26 at 4 09 31 PM" src="https://user-images.githubusercontent.com/1056412/97238212-189ec380-17a6-11eb-846f-cd5a09707f72.png">

1. Do the above in Firefox, and verify that slider knobs are vertically centered with respect to the slider tracks (green arrows in following screenshot):
![Screen Shot 2020-10-26 at 4 09 45 PM](https://user-images.githubusercontent.com/1056412/97238290-44ba4480-17a6-11eb-893e-8ae0da073dfc.png)

**Comment by shefalijoshi** [comment]
@jvigliotta @charlesh88 Is this issue fixed?

**Comment by jvigliotta** [comment]
> @jvigliotta @charlesh88 Is this issue fixed?

Great question. I assume so, but apparently @charlesh88 would probably have a more definitive answer. I thihnk I just added the label.

**Comment by charlesh88** [comment]
Verified fixed Testathon 6/4/2021

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by jvigliotta** [comment]
Verified fixed Testathon 6/4/2021

**Comment by kobe1104** [comment]
Verified fixed.
