### ISSUE TITLE
[VISTA]  custom format tokens

### ISSUE THREAD

**Issue by nikhilmandlik** [nasa/openmct#3468]
### Description:
[VISTA] VCP-0170 VISTA shall allow custom format tokens to be specified via Javascript and included in deployments such that they are usable in format strings.
### Testing instructions:
1. Create 'Display Layout' 
1. add SWG to it (alphanumeric)
1. While in edit mode, click on SWG(alphanumeric)
1. check 'ALPHANUMERIC FORMAT' under inspector 
1. Add format to one of following and compare against desired output. 
1. formats : `%.2f`, `%.4f`, `&sclk`, `&lts`

**Comment by deeptailor** [comment]
Verified Fixed in VISTA
