### ISSUE TITLE
[Display Layout]Telemetry Graphs on display layout are not visible

### ISSUE THREAD

**Issue by FillyHolly** [nasa/openmct#3470]
When adding a chart to the display layout workspace, a chart rectangle appears, but the chart itself is not displayed. What am I doing wrong?

<img width="1440" alt="Снимок экрана 2020-10-24 в 17 11 17" src="https://user-images.githubusercontent.com/61470698/97084978-1e1fd080-1623-11eb-9b90-4c07feec1775.png">
<img width="1440" alt="Снимок экрана 2020-10-24 в 17 11 10" src="https://user-images.githubusercontent.com/61470698/97084979-211ac100-1623-11eb-94e9-2898532c29e6.png">

**Comment by deeptailor** [comment]
@FillyHolly - Any errors in the console?

**Comment by FillyHolly** [comment]
@deeptailor 
The problem was with the safari browser. When switched to chrome the error disappeared
