### ISSUE TITLE
Enter full screen mode button not working.

### ISSUE THREAD

**Issue by AliMuhammadOfficial** [nasa/openmct#3476]
![full screen bug](https://user-images.githubusercontent.com/49407055/97424468-94c61200-1932-11eb-9889-f08a2c1b44a8.png)

whenever I click on enter full screen button it does not work.

**Comment by deeptailor** [comment]
@AliMuhammadOfficial What operating system / what browser are you using? It seems to work fine on MAC OS with Chrome

**Comment by AliMuhammadOfficial** [comment]
Ok Thanks but I want to contribute to this project butt I'm confused how to contribute. kindly if you can share details and guide with me it would be really helpful for me.
Thanks

**Comment by jvigliotta** [comment]
Hi @AliMuhammadOfficial please take a look at https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md regarding contributing. Any other questions let us know. Thanks!
