### ISSUE TITLE
[Testing] Add functional testing to build

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#348]
Add a regression testing step to the build which verifies the behavior of the full application.

There is such a suite in the `protractor` directory of the repository, but this currently requires multiple separate steps to be executed. Instead prefer to have this executable in a single build step.

**Comment by VWoeltjen** [comment]
Build process is expected to change substantially with the outcome of #69, want to address this during or after those changes are implemented.

**Comment by VWoeltjen** [comment]
Want to see if #643 can be addressed/improved in the context of this issue

**Comment by unlikelyzero** [comment]
done!
