### ISSUE TITLE
[Display Layouts] Should use composition API for adding and removing children, not mutation

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3482]
Composition changes (adding and removing children) should always use the composition API. Right now [display layouts are directly mutating object composition](https://github.com/nasa/openmct/blob/5646a252f7b044ec29474c570df57a6ff2cb2a90/src/plugins/displayLayout/components/DisplayLayout.vue#L480). Our API allows composition providers to define and store composition any way they want (eg. on a server via web services), but unfortunately right now some of our views assume that composition is always held on an object.

Instead of directly mutating the composition property, developers should use the composition API like so:
```
openmct.composition.get(domainObject).remove(childObject);
```

**Comment by AliMuhammadOfficial** [comment]
I want to work on this patch. it would be honor for me to send PR.

**Comment by rukmini-bose** [comment]
Unverified 11/14: When following reproduction steps, I am receiving this error in the console.
<img width="410" alt="Screen Shot 2022-11-14 at 3 26 01 PM" src="https://user-images.githubusercontent.com/48999852/201788934-6c49d1b5-b984-412a-ad60-2d57d56fa84c.png">

**Comment by unlikelyzero** [comment]
Verified
