### ISSUE TITLE
[Notebook] new entries on brand new notebook not rendered

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#3488]
## Overview
On a brand new notebook, new entries are being created but not rendered to the screen.

## Expected Behavior
New notebook entries are always rendered.

## Steps to Reproduce
1. Create a new notebook
1. Click on + to create a new notebook entry
1. Click a few more times because nothing happened
1. Navigate away from notebook
1. Navigate back to notebook and observe all entries were created, and new entries are now rendered correctly when added

**Comment by deeptailor** [comment]
Verified Fixed

**Comment by davetsay** [comment]
Verified.

Worked with new notebook and after clearing local storage and creating new notebook.

**Comment by charlesh88** [comment]
Verified fixed Testathon 11/20/20

**Comment by shefalijoshi** [comment]
Verified fixed for only this issue.
