### ISSUE TITLE
Notebook entry cursor is on right side of input for blank entries

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3491]
Seen during Testathon 11-02-20 on https://hulk.ndc.nasa.gov/dev. This only occurs in the following circumstance:

1. Create a new blank entry:
<img width="814" alt="Screen Shot 2020-11-02 at 2 40 06 PM" src="https://user-images.githubusercontent.com/1056412/97927688-522d7c80-1d1a-11eb-8077-9b1019c64ed9.png">

2. Click into the entry field. Observe: the cursor is on the right side of the input, but should be on the left:
<img width="805" alt="Screen Shot 2020-11-02 at 2 40 22 PM" src="https://user-images.githubusercontent.com/1056412/97927695-56599a00-1d1a-11eb-8b53-eedf7b31eafe.png">

**Comment by akhenry** [comment]
Appears to be fixed, closing.

**Comment by deeptailor** [comment]
Verified Fixed

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by charlesh88** [comment]
Verified fixed Testathon 02/01/2021

**Comment by shefalijoshi** [comment]
Verified fixed

**Comment by tiffanyatruong** [comment]
verified fixed 2/1/2021
