### ISSUE TITLE
Tree is not rendering after first load

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3492]
Upon loading of Open MCT certain DOM elements need to be queried for height calculations. There are certain instances where the DOM element is NOT loaded fully yet before being checked for height. Need to have a more robust method for checking heights on these elements, ResizeObserve seems to be a good choice as it will fire once the elements size has changed.

## Testing
- load the site on a server where it was previously NOT working correctly
- verify the tree and all it's elements/children are showing

**Comment by davetsay** [comment]
verified

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by shefalijoshi** [comment]
Verified fixed
