### ISSUE TITLE
Change Notebook entry to use "click to edit" approach

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3498]
From [Notebook user testing in summer 2020](https://github.com/nasa/openmct/issues/3224), issue NT1-10: Hover over Notebook entry input can create "flicker"; hovers over Notebook entries are distracting. 

Solution: turn off behavior on hover; change so user must click input first to make an existing entry editable.

**Comment by charlesh88** [comment]
### Testing Notes
1. Create new or edit an existing Notebook.
1. Add some entries to the Notebook, either with text or blank.
1. Observe: when viewing the Notebook, hover the cursor over the main portion of the entry (green arrow) to highlight the entry area. Verify that it appears as shown, with a subtle highlight and no changes to padding or other neighboring elements:
<img width="814" alt="Screen Shot 2020-11-02 at 2 40 06 PM" src="https://user-images.githubusercontent.com/1056412/97934431-90cb3300-1d2a-11eb-92ed-9c12b9fb1497.png">
4. Verify that clicking into the entry area places the edit cursor and causes the entry field to appear editable:
<img width="805" alt="Screen Shot 2020-11-02 at 2 40 22 PM" src="https://user-images.githubusercontent.com/1056412/97934482-b5bfa600-1d2a-11eb-9c2b-4d082b522d76.png">

**Comment by shefalijoshi** [comment]
Unable to verify as I cannot create a notebook.

**Comment by akhenry** [comment]
Verified Fixed 11/06/2020

**Comment by charlesh88** [comment]
Verified fixed Testathon 11-06-20.

**Comment by davetsay** [comment]
verified and cursor issue verified as well
