### ISSUE TITLE
[Plots] Switching from Enum to Non Enum, does not refresh the Y Axis 

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#3501]
1. Create an overlay plot with an enum endpoint.
2. It will default to Enum on the Y Axis, which is fine.
3. In the inspector change the Y Axis value to a non enum value.
4. Once the data is loaded, notice that the Y Axis labels still show enum strings.
5. Save the overlay plot, then navigate away and back to the plot.
6. Notice that the Y Axis now shows the correct non string format on the Y Axis.

**Comment by charlesh88** [comment]
Testathon 11/20/20: can't test on hulk, skipping.

**Comment by nikhilmandlik** [comment]
Verified Fixed using state generator.
