### ISSUE TITLE
Web Page objects cannot be created

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3503]
Trying to create a Web Page object results in this state in the creation dialog:
![Screen Shot 2020-11-06 at 10 47 06 AM](https://user-images.githubusercontent.com/1056412/98403382-bb183b80-201d-11eb-9e4c-d768224fd7ee.png)

The user can never select a target that enables the Ok button. Seen in later master branch on local, and on hulk/viper as of Nov 6, 2020.

**Comment by davetsay** [comment]
Try again @charlesh88
