### ISSUE TITLE
Views are broken in Safari 12

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3505]
Related to https://trunk.arc.nasa.gov/jira/browse/VIPERVERVE-266 - many Open MCT views are broken in Safari, including principally Imagery and Plots. The issue is related to mid-level containers (`c-so-view` and near) and flex CSS.

This is urgently needed for VERVE's integration of Open MCT Imagery views.

**Comment by charlesh88** [comment]
Fix here touched multiple elements, so we need to do some regression testing as well. Suggest that in a Testathon, some should use **Safari 12** or better, and some should use **Chrome** to look for regressions.

### Testing Notes
Repeat each step below for the following objects: 
- [ ] Imagery
- [ ] Overlay Plot
- [ ] Stacked Plot
- [ ] Telemetry Table
- [ ] LAD Table
- [ ] Display Layout
- [ ] Flexible Layout
- [ ] Condition Set.

1. Navigate to or create a new view.
1. Verify that the view displays as expected, and that all functionality and gestures behave as expected. For example, in Imagery, make sure the main image and thumbs are displayed and work as expected.

**Comment by charlesh88** [comment]
Appears to have been fixed for all views in the VERVE Open MCT integration, with exception of the modal "view large". @charlesh88 to have a look locally.

**Comment by akhenry** [comment]
Verified fixed 11/20/2020 in Safari 14

**Comment by davetsay** [comment]
Verified
