### ISSUE TITLE
Example Imagery styles not applied as expected

### ISSUE THREAD

**Issue by nikhilmandlik** [nasa/openmct#3506]
### Testing instructions:
1. Create Example Imagery
1. Create a display layout
1. Drag Example Imagery into display layout
1. Apply BG color to Example Imagery
1. Color only applies to Timestamp value.

### Actual Result:
Color only applies to Timestamp value.

### Screenshots:
![Screen Shot 2020-11-06 at 2 41 35 PM](https://user-images.githubusercontent.com/1292612/98421643-a5673e00-203e-11eb-9352-740d1747319a.png)

**Comment by davetsay** [comment]
Not needed if fixing #3472
