### ISSUE TITLE
[Import as JSON] Should not apply to non-composable domainObjects

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#3509]
Items without composition should not show the Import as JSON context menu action.

**Comment by shefalijoshi** [comment]
@deeptailor  It appears that this has already been implemented here:
https://github.com/nasa/openmct/blob/master/platform/import-export/src/actions/ImportAsJSONAction.js#L230

**Comment by shefalijoshi** [comment]
Closing as this works as designed.
