### ISSUE TITLE
Timeline plan view should display new activities immediately

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#3510]
When a new JSON file is uploaded into an existing Plan view, the view should re-render and display the new plan without needing a browser refresh.
Currently a browser refresh is required.

**Comment by shefalijoshi** [comment]
**Testing instructions:**
Create a new plan by uploading an activities json file.
Ensure the plan renders correctly
Change the plan's json file and save it
Edit properties of the Plan and upload the new file
Ensure the plan shows the changed activities

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by davetsay** [comment]
Verified
