### ISSUE TITLE
Timeline Plan view does not group activities correctly

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#3511]
Activities from groups seem to bleed into each other. Each group's activities should be rendered within that group.

**Comment by shefalijoshi** [comment]
**Testing instructions:**
Create a new plan by uploading an activities json file that has multiple groups and activities within those groups
Ensure the plan renders correctly and the activities from one group do not bleed into the other group.

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by davetsay** [comment]
Verified
