### ISSUE TITLE
plot is not plotting historical data.

### ISSUE THREAD

**Issue by Vaibhav2121** [nasa/openmct#3514]
In order to integrate old historical data in open mct application. I have modified historical-server.js . Whenever fixed time span is chosen in open-mct overlay plot and time is changed, application has to read archived data from file. Each archived data file has following format.
[
{ "timestamp":"-------", "value":"-----", "id":"----"},
{ "timestamp":"-------", "value":"-----", "id":"----"}
]
this data is read by historical-server.js and send to historical-plugin.js. 

This data is not being plotted by overlay plot although when i select Telemetry table data is showing alright.

**Comment by unlikelyzero** [comment]
@Vaibhav2121 I'm closing this for now. Please let us know if this is still an issue for us and file a new bug. Thansk!
