### ISSUE TITLE
Disallow duplicate and move actions for non creatable objects

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#3519]
Testing instructions:

Right-click on any tree item that is not creatable (like from a dictionary) and ensure that the Move and Duplicate actions are not visible.

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 11/30/2020

**Comment by davetsay** [comment]
verified
(found related issue #3560)
