### ISSUE TITLE
gendocs.js Uses an outdated version of Canvas Constructor

### ISSUE THREAD

**Issue by lorenzo-gomez-windhover** [nasa/openmct#3521]
Hi there,

I was trying to generate an html version of the docs by running `node gendocs.js --in src --out output` and I got the following error:
```
gendocs.js:57
            new Canvas(CONSTANTS.DIAGRAM_WIDTH, CONSTANTS.DIAGRAM_HEIGHT);
TypeError: Canvas is not a constructor


```

This is because of this https://github.com/Automattic/node-canvas/issues/997. As pointed out in the canvas repo, this is a very easy fix:

Change this line 
` var canvas =
            new Canvas(CONSTANTS.DIAGRAM_WIDTH, CONSTANTS.DIAGRAM_HEIGHT); `
to

`var canvas = new Canvas.Canvas(CONSTANTS.DIAGRAM_WIDTH, CONSTANTS.DIAGRAM_HEIGHT);`

This is a one line change so I might submit a PR if no one else fixes it.

Hope this helps either way!
Cheers!

**Comment by lorenzo-gomez-windhover** [comment]
Quick question: how reliable are these docs? Some of it is as old as 4 years old.

**Comment by jvigliotta** [comment]
Hi @lorenzo-gomez-windhover we're taking a look into this and will update when we can, until then, regarding contributing to the project, take a look at our contributor guidelines for more information, we do require agreements for contributors.

https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md

**Comment by akhenry** [comment]
@lorenzo-gomez-windhover Thanks for reporting this issue. This documentation actually covers the internals of our legacy codebase, which we keep around for posterity. We should definitely get it building again, but if you're looking for guidance on extending Open MCT, you should use our [up to date API documentation](https://github.com/nasa/openmct/blob/master/API.md) as reference.

**Comment by lorenzo-gomez-windhover** [comment]
I was looking at that documentation, which has been extremely helpful :+1:. Thanks a lot for the info @akhenry.
