### ISSUE TITLE
[Style Rule Manager] Should not update domainObject style on destroy

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#3523]
At moment, we are updating the object style after destroy is called. ie:

![image](https://user-images.githubusercontent.com/13260688/99583037-c6f9eb00-2997-11eb-8fb6-c817c84ff65d.png)

This causes bad side effects, because the callback is called after the component is destroyed. This forces components to call StyleRuleManager.destroy before components are destroyed and leads to an anti-pattern.

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 01/07/2021

By verify... I see it was removed from destroy() and seems to be applied in other places in the code.
