### ISSUE TITLE
Looking for an openmct map

### ISSUE THREAD

**Issue by egmed** [nasa/openmct#3524]
Hi, 

I would like to consult with you guys about the best choice for displaying a map in OpenMCT.

The map should show a spacecraft orbit around the world.

I am getting real time data that includes:
  1. Longitude
  2. Latitude
  3. Altitude (Displaying altitude is not a must. i can settle on Lon and Lat)

I am getting an update of the spacecraft data every 10 seconds and would like to show the orbit that the spacecraft have made since launch.

Are there any recommendation on which JS map I should use to accomplish this behavior? And what is the best way to tackle this issue in OpenMCT?

Many thanks

**Comment by mudinthewater** [comment]
Hey @egmed - have you tried https://github.com/nasa/openmct-map? It does 2d on an arbitrary plane so you could put a plot of the world on it then update your points. I've done something similar with it. If that's not sufficient for your purpose,, you can use that as a base and integrate a commercial map application with an API such as HERE, Google, Garmin, etc on top of it.

**Comment by egmed** [comment]
Thank you @mudinthewater for your response. I managed to get things going on my own. Showing the spacecraft trajectory in a 3d map (Cesium). I am showing the map in a custom view I made.

**Comment by jvigliotta** [comment]
Thanks @mudinthewater going to close this one out now as it seems to be resolved. @egmed any other questions let us know!
