### ISSUE TITLE
Three dot menu needs unit tests

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3525]
This is a major new piece of functionality, and it needs unit tests. In the interests of expediency the PR has been merged without tests, but these need to be done ASAP - https://github.com/nasa/openmct/pull/3325

**Comment by deeptailor** [comment]
## Testing Notes:

1. npm run test
2. Celebrate when all tests pass

**Comment by davetsay** [comment]
celebrated

**Comment by akhenry** [comment]
Celebration verified
