### ISSUE TITLE
Notebook Snapshotting has a number of problems

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3529]
In latest master as of today, Snapshotting has a number of problems. The VIPER team would like to use the Snapshot capability to annotate images while in driving sims, so marking this a blocker.

- [x] Saving a Snapshot to the default Notebook doesn't work, but instead saves to the Snapshots holder:
             - created issue and PR for it, https://github.com/nasa/openmct/issues/3530               -nikhil

<img width="420" alt="Screen Shot 2020-11-20 at 11 42 04 AM" src="https://user-images.githubusercontent.com/1056412/99842925-8d56ea80-2b25-11eb-86dd-0d3a4a602221.png">

- [x] The Snapshot capability that we use to have in the View Large overlay is gone:

https://github.com/nasa/openmct/pull/3240#issuecomment-665189739
<img width="849" alt="Screen Shot 2020-11-20 at 1 56 59 PM" src="https://user-images.githubusercontent.com/1292612/99854304-6c989000-2b39-11eb-926c-c954c3839d64.png">

<img width="1041" alt="Screen Shot 2020-11-20 at 11 44 56 AM" src="https://user-images.githubusercontent.com/1056412/99843119-e0c93880-2b25-11eb-986b-6f20a2bc142f.png">

- [x] https://github.com/nasa/openmct/pull/4753 
<img width="1712" alt="Screen Shot 2020-11-20 at 1 57 32 PM" src="https://user-images.githubusercontent.com/1056412/99853802-7d94d180-2b38-11eb-94b7-7849839eabed.png">

**Comment by unlikelyzero** [comment]
@charlesh88 could you ensure that this severity is accurate and that the issues are not already resolved?
