### ISSUE TITLE
[Notebook] can not add snapshots to default notebook

### ISSUE THREAD

**Issue by nikhilmandlik** [nasa/openmct#3530]
### Description:
can not add snapshots to default notebook, snapshots always gets stored in snapshot container.

### Notes:
regression caused by merging error.

### Testing instructions:
1. add snapshot to notebook.

### Expected Result:
snapshots should add into default notebook.

**Comment by akhenry** [comment]
Verified fixed 11/20/2020

**Comment by davetsay** [comment]
Verified
