### ISSUE TITLE
[Drawing Objects] Are not selectable

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#3535]
There is a regression where drawing objects become un-selectable. ObjectLabel is throwing an error cannot read identifier of undefined.

**Comment by deeptailor** [comment]
## Testing Instructions:
1. Create a Display Layout
2. Add a drawing object eg Box, line 
3. Select it, move it, re-size it
4. Verify it works as expected.

**Comment by akhenry** [comment]
Verified Fixed

**Comment by nikhilmandlik** [comment]
Verified Fixed.
