### ISSUE TITLE
Navigating to a Notebook snapshot not working 

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#3538]
On Hulk /dev, View any domain object and click on Snapshot menu in the main view to save a Notebook snapshot
Navigate to a different domain object to view it
In the snapshot shelf click on the Notebook snapshot that was saved earlier
Expected: Open MCT should navigate to the domain object for that snapshot
Actual: Console error
```
Uncaught TypeError: URL constructor: #/browse/mine/b6072898-975e-456c-9882-30a38e92a2b8/85829244-f865-4afe-9f4b-c57fda746f45?view=table&tc.mode=fixed&tc.startBound=1605910186394&tc.endBound=1605912046394&tc.timeSystem=utc is not a valid URL.
    changeLocation https://hulk.ndc.nasa.gov/dev/node_modules/openmct/dist/openmct.js:355
    n https://hulk.ndc.nasa.gov/dev/node_modules/openmct/dist/openmct.js:17
    t https://hulk.ndc.nasa.gov/dev/node_modules/openmct/dist/openmct.js:17
    _withTask https://hulk.ndc.nasa.gov/dev/node_modules/openmct/dist/openmct.js:17
```

**Comment by shefalijoshi** [comment]
Tested but I still see this issue:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/5247066/100673066-af1b5300-3317-11eb-80c5-c71c2e84cfb5.png">

**Comment by jvigliotta** [comment]
Found Issue - Testathon: 11/30/2020

Found an issue for this in Chrome.

Created a domainObject (imagery or swg in this case) and viewed it.
Saved to snapshots. 
Viewed another domainObject.
Opened snapshots and selected it, error below in console.

![Screen Shot 2020-11-30 at 2 17 31 PM](https://user-images.githubusercontent.com/12013460/100673021-99a62900-3317-11eb-9d92-bdf1f05b3039.png)

**Comment by davetsay** [comment]
ditto what @jvigliotta found

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 12/14/2020

**Comment by davetsay** [comment]
verified
