### ISSUE TITLE
Default Notebook grid item not displaying properly

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3540]
Styles for `is-status--*` are incorrectly affecting the look of the default Notebook grid item: 

![image](https://user-images.githubusercontent.com/1056412/99861910-b50d7900-2b4c-11eb-94f2-39f60e75f0e9.png)

**Comment by charlesh88** [comment]
### Testing Notes
1. Create a new Notebook directly within a Folder (or use an existing one) and add an entry to make it the default Notebook.
1. Navigate to the Folder's grid view and verify that the grid item's icon and label are not knocked back, and that the default indicator (purple icon) appears, and the layout of icons appears as shown:

![image](https://user-images.githubusercontent.com/1056412/99862060-3bc25600-2b4d-11eb-950d-dd6a3cba294f.png)

**Comment by shefalijoshi** [comment]
Verified fixed.

**Comment by davetsay** [comment]
verified

**Comment by nikhilmandlik** [comment]
Verified Fixed.
