### ISSUE TITLE
Labels for Telemetry Views in Display Layouts

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3547]
Description
After creating a label element in a display layout the label cannot be moved.

Steps to Reproduce
1. Create a new Display Layout or edit an existing one
2. Create a new "label" element
3. Try to drag the new label element around in the display and notice that the label cannot be moved.

**Comment by deeptailor** [comment]
@akhenry - This issue was fixed by #3539

**Comment by charlesh88** [comment]
This actually a dupe of #3535, closing.
