### ISSUE TITLE
Cannot set font style or size on alphanumerics in Display Layout

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3549]
### Reproduce 
1. Make a new Display Layout.
1. Add a telemetry point or Sine Wave Generator object to the layout as an alphanumeric. 
1. While the object is selected, change its font size and style.
1. Observe: the font size and style should change, but don't.

The problem is that the class 'u-style-receiver' is not applied to the markup for 'c-telemetry-view'.

**Comment by charlesh88** [comment]
### Testing Notes
1. Make a new Display Layout.
1. Add a telemetry point or Sine Wave Generator object to the layout as an alphanumeric. 
1. While the object is selected, change its font size and style.
1. Observe: the font size and style should change.

**Comment by shefalijoshi** [comment]
Verified fixed.

**Comment by davetsay** [comment]
verified

**Comment by nikhilmandlik** [comment]
Verified Fixed.
