### ISSUE TITLE
[Plots] Renaming the child of a plot does not update the name in the legend.

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3554]
## Description
In a plot with children, renaming a child should result in the plot's label being immediately updated with the new name of the child.

## Reproduction steps
![Plot rename child](https://user-images.githubusercontent.com/4215777/100276747-e3a59e00-2f16-11eb-8cec-89a06f5ba773.gif)

**Comment by michaelrogers** [comment]
Fix verified locally during testathon 2022-02-02.

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 02/02/23
