### ISSUE TITLE
[Telemetry Table] [Three Dot Menu] Export marked rows does not work

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#3556]
An error is being thrown when trying to export marked rows, in telemetry tables

**Comment by deeptailor** [comment]
## Testing Instructions
1. Create a telemetry table
2. Add some telemetry to the table
3. Mark a few rows
4. Click on export marked rows
5. Verify it works as expected, and produces a csv file

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 12/14/2020

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by davetsay** [comment]
verified
