### ISSUE TITLE
[Object Tree] non creatable objects should not have remove context action

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#3560]
## Overview
non creatable objects should not have remove action available in context menu dropdown

## Expected Behavior
should not be able to see remove action for non creatable objects

## Steps to Reproduce
1. navigate to a non creatable object
1. context click and view actions available

**Comment by shefalijoshi** [comment]
@davetsay I don't see this anymore for non creatable objects. Let's retest.

**Comment by charlesh88** [comment]
Verified fixed Testathon 3-3-21.

**Comment by akhenry** [comment]
Verified Fixed

**Comment by deeptailor** [comment]
Verified Fixed, but found a related bug. We should not show the import as JSON action either, if the folder does not allow composition customization
