### ISSUE TITLE
Performance profiling of Plan view using SVG rendering

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#3561]
Using 500 activities, analyze the performance of using SVG for Plan views.

**Comment by shefalijoshi** [comment]
**Memory leaks:** No memory leaks were found during performance analysis. Memory usage did not spike at any point.
**Load time:** Load time was less than 2 seconds when plan was viewed. On resize there is some visible drawing activity but it is minimal and stabilizes is less than 2 seconds.
**Site Performance (Chrome dev tools)**
Without Fixes:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/5247066/100677976-05d95a80-3321-11eb-915b-1c32e2ecbe5a.png">

With Fixes:
<img width="353" alt="image" src="https://user-images.githubusercontent.com/5247066/100677727-7a5fc980-3320-11eb-830d-6962a665163e.png">

**Comment by shefalijoshi** [comment]
Closing this issue as it's been completed.

**Comment by akhenry** [comment]
I think we can close this? We're going with SVG.

**Comment by shefalijoshi** [comment]
Closing - this research is done.
