### ISSUE TITLE
[Export Snapshots] With periods in the file name will cause system to think the file type is anything after the period

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#3564]
When exporting snapshots of objects with periods in the filename, the system will automatically think the filetype is anything that follows the period. 

## Testing Notes
1. Rename a folder to SOME_FILE_NAME.NEW_FILE
2. Take a snapshot of the folder view
3. Open the snapshot and click the download as png or jpeg file.
4. Notice in the save as dialog the file type will be NEW_FILE

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by davetsay** [comment]
verified

**Comment by akhenry** [comment]
Fixed, but I will file a separate issue - we're not appending an appropriate file extension at all.
