### ISSUE TITLE
[Notebook] snapshots on plots are empty

### ISSUE THREAD

**Issue by nikhilmandlik** [nasa/openmct#3566]
### Description:
Snapshots taken on plots shows empty/blank.

### Testing instructions:
1. Create/select SWG from notebook snapshot menu click on 'Save to Notebook Snapshots'
2. Check 'Notebook Snapshots', Click on image to confirm that its empty/blank

### Notes:
looks like issue with element having classname `l-angular-ov-wrapper`. If added property `display: block;` on it I was able to see plot data in snapshot.

### Expected Result:
image to reflect plot data in it.

### Actual Result:
Snapshots taken on plots shows empty/blank.

### Screenshots:
![Screen Shot 2020-12-01 at 12 39 26 PM](https://user-images.githubusercontent.com/1292612/100794644-b489a380-33d2-11eb-8197-53b21937ae03.png)

**Comment by deeptailor** [comment]
## Testing instructions:

1. Create/select SWG from notebook snapshot menu click on 'Save to Notebook Snapshots'
2. Check 'Notebook Snapshots', Click on image to confirm that its empty/blank

**Comment by akhenry** [comment]
Verified fixed.

**Comment by davetsay** [comment]
verified
