### ISSUE TITLE
[Object Label] Object names with descenders seem cutoff

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#3568]
![image](https://user-images.githubusercontent.com/13260688/100805659-eb1bea00-33e3-11eb-8fd2-32ad12974ec5.png)

See first object label in image above, notice that the 'g' are cutoff

**Comment by ozyx** [comment]
# Testing Instructions
1. Create an object with a name that includes characters with descenders (as seen in above screenshot)
2. Verify that the descenders are not cut off or clipped at the bottom.

**Comment by charlesh88** [comment]
Dupe of #6036. Verified fixed Testathon 2023-01-31.
