### ISSUE TITLE
[Layouts] Layouts only saving in browser cache

### ISSUE THREAD

**Issue by Duncan-McD** [nasa/openmct#3571]
label: help wanted

My layouts appear to be only saving in the browser cache - I can't seem to be find out how to go about saving it locally so it can be the preset for any computer or browser running my project - is this able to be done?

**Comment by deeptailor** [comment]
Hi Duncan, 

You can use the couch DB plugin running on a shared server to achieve your goal

**Comment by jvigliotta** [comment]
Going to close this one out. @Duncan-McD if you have any other issues, let us know.
