### ISSUE TITLE
[Selection] emits an update event even if selected item has not changed

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#3572]
When clicking on already selected items, the selection API should not emit an update event.

What happens right now is that every click will cause a selection update, which in turn causes the entire inspector to re-render, causing unnecessary destroying and re-rendering of views, when the selection has not really changed. 

Happens most when marking rows in tables, clicking around an overlay plot etc

**Comment by deeptailor** [comment]
Testing Instructions:

1. Create an overlay plot
2. Add a few telemetry points
3. Save the overlay plot.
4. Click around the plot and verify that the inspector views do not reload (flash)

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 12/14/2020

**Comment by davetsay** [comment]
verified
added break on emit events in selection api to test
