### ISSUE TITLE
Problem copying unitless telemetry values to notebook 

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3574]
The entry is created ok, with the correct telemetry value, however the entry has `undefined` appended to it. This appears to be an issue with unit-less values.

eg.
![Screen Shot 2020-12-03 at 9 12 54 AM](https://user-images.githubusercontent.com/4215777/101064837-461b2180-3549-11eb-908c-2f645e5993b9.png)

Steps to reproduce:
1. Drag an event message generator object (you may need to create one) into a display layout. This should add an "alpha-numeric" telemetry view to the layout
2. Drag a notebook into the layout
3. Save the layout and exit edit mode
4. Add an entry to the notebook to ensure it's the default
5. Right click on event generator telemetry view and select the "Copy to notebook..." option
6. Note that a new entry appears in the notebook, and that it ends in `undefined`.

**Comment by davetsay** [comment]
verified
used condition set as alpha numeric telemetry provider

**Comment by akhenry** [comment]
Verified fixed.

**Comment by charlesh88** [comment]
Testathon 01-07-2021 verified fixed.

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 01/07/2021
