### ISSUE TITLE
[User testing feedback] Tree navigation "up" arrow could be clearer

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3575]
From Time Conductor and tree user testing sessions in October 2020, there was a bit of confusion on how the left "up" arrow works in the tree. Let's change the behavior a bit, in this way:

- [x] Move "up" arrow down one level, so My Items would not have a nav up arrow. @jvigliotta 
- [x] Change "up" arrow glyph to use "nav-to-parent" icon. @charlesh88

**Comment by jvigliotta** [comment]
Hey @charlesh88 I added the icon, but you'll need to tweak the css, I just kinda shoved it in there...

**Comment by jvigliotta** [comment]
## Testing
- navigate the tree and note that the "nav-to-parent" icon will navigate you back up to the item ABOVE that arrow
- make sure objectPath is correct by performing actions
- make sure to test with and without root showing

**Comment by charlesh88** [comment]
Testathon 2/25/21 verified fixed.

**Comment by tiffanyatruong** [comment]
verified fixed 2/25/21

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 2/25/2021

@deeptailor created this related issue #3697 regarding highlighting confusion
