### ISSUE TITLE
Fix the browser back button in Open MCT

### ISSUE THREAD

**Issue by nikhilmandlik** [nasa/openmct#3588]
### Description:
Browser back button is not behaving as expected.

### Testing instructions:
1. navigate to different objects
2. use 'back' and/or 'forward' buttons of browser history to navigate pages.

**Comment by Chaphasilor** [comment]
Just noticed this as well. You can never fully leave the page using the back button :P

**Comment by davetsay** [comment]
Using the back and forward button navigates between views, but does not care about state. I think this needs to be addressed as you can be in edit mode, use the back button to get to a non-editable object, and still be in edit mode. Also, back should maybe be blocked while in edit mode so as to prevent loss of edits. Also noticed modals remain open. I start the remove notebook entry action, navigated to another object, then finished the the action to remove the notebook entry.

**Comment by jvigliotta** [comment]
Separate issue to be created for issue @davetsay saw.

Verified Fixed - Testathon: 06/02/2021
