### ISSUE TITLE
Open MCT is not picking up all panorama images

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3592]
Observed during driving sim on hulk/viper 12/10/20: panorama images expected by users were being dropped from Open MCT history. This is having a real impact on driving in the sim. Touch base with Robert C. and Mark A. for more info.

**Comment by RCarvalhoNASA** [comment]
This issue has been going on for a while.  Used to be we would lose 1/6 pan images in openMCT.  Last couple of weeks, we've only been seeing half (3/6) of panorama images every time.  Not clear yet if there's a pattern as to which are being dropped.

**Comment by RCarvalhoNASA** [comment]
To be clear, this is an issue in the openMCT on hulk that we're using for dSims

**Comment by akhenry** [comment]
Will need a little more info here, panoramas are new to me. Are they published on the navcam topic? Do they all have the same timestamp?

**Comment by akhenry** [comment]
Investigation is focused on simulator and ROS-YAMCS bridge. Closing because not an Open MCT issue.
