### ISSUE TITLE
Configuration hiddenColumns is not respected in a Display Layout

### ISSUE THREAD

**Issue by KhaledSharif** [nasa/openmct#3597]
## Error outline

The TelemetryTable plugin in OpenMCT supports a configuration property called hiddenColumns which can hide certain columns when viewing that object in a tabular view in OpenMCT. This works for me when I hide a particular column and view the table. However, if I use that same table in a Display Layout, the hidden column(s) are still shown. If I use the table in a Flexible Layout, the hidden column(s) are hidden, as expected. Therefore this bug is specific to the Display Layout. 

## How to reproduce

Create an OpenMCT object and hide one of the columns. For example:

```
"configuration": {"hiddenColumns": {"name": true}}
```

Use this table in a Display Layout. The column will not be hidden (incorrect). Use the same table in a Flexible Layout. The column will be hidden (correct).

## Environment

```
OpenMCT commit 41783d on Dec 11 2020
```

**Comment by deeptailor** [comment]
@jvigliotta - Can we take a look at this

**Comment by jvigliotta** [comment]
@KhaledSharif hello!

I've tried to reproduce this by doing the following:
- created a Telemetry Table and added a Sine Wave Generator
- edited table and hid a column, saved
- created a Display Layout and added the Table

I'm unable to reproduce what you're seeing as the column I hid is still hidden for me in the Display Layout. I went back and unhid the column in the Telemetry Table and saved it. Then went back to the Display Layout the changes were reflected there as well as the column was showing again.

Is there another way to reproduce what your seeing? Are you still seeing this issue?

Thanks!

**Comment by KhaledSharif** [comment]
@jvigliotta thanks for your response. I think my issue might be more specific than I had previously thought. My guess is that my issue only occurs when I hide the "name" column. I can only hide this column through code, not through the interface, because when I use the interface to hide/show particular columns, I'm not given the choice of hiding the "name" column.

**Comment by akhenry** [comment]
@KhaledSharif Ah, that sounds eminently plausible. Good sleuthing!

@jvigliotta This is probably related to the [recent work to automatically add a name column if it's absent in telemetry metadata](https://github.com/nasa/openmct/pull/3466). Users should be able to hide this if they wish.

**Comment by jvigliotta** [comment]
@KhaledSharif would you mind posting an example of the where you're making this change programmatically so I can better reproduce?

**Comment by KhaledSharif** [comment]
@jvigliotta @akhenry 

Sorry for taking so long to get back to you on this. I've forked the OpenMCT tutorial and modified it to show an example of changing the configuration using code. Specifically, [please check the last commit in my fork](https://github.com/KhaledSharif/openmct-tutorial/commit/3afc5a5df0a5c1c2b5c47b948cca5d434be4b741).

```
git clone https://github.com/KhaledSharif/openmct-tutorial.git
npm i
npm start
```

To reproduce, view the "Fuel" parameter as a table, notice that the name column is hidden. Then view any other parameter as table and the table should retain the name column. Hope this helps!

**Comment by charlesh88** [comment]
Verified fixed Bug Bash 04-21-22
