### ISSUE TITLE
Snapshot images should include an appropriate file extension

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3600]
Saving files as a PNG or JPG will download a file with no extension (at least in firefox, where I tested this).

Steps to reproduce:
1. Open Firefox
2. Navigate to any object
3. Save a snapshot
4. In the snapshot preview section, click on the snapshot itself to bring up the snapshot preview
5. Click on the PNG or JPG button.
6. Note that the file produced has no file extension.

**Comment by nikhilmandlik** [comment]
hmm, working as expected on both chrome and Firefox (86.0 (64-bit))

**Comment by davetsay** [comment]
<img width="501" alt="Opening_Unnamed_Notebook_and_My_Items" src="https://user-images.githubusercontent.com/3614296/116156025-caf50c00-a69f-11eb-961b-24feefb665c9.png">

Still seeing in FF78 and FF88.

**Comment by davetsay** [comment]
troubleshooting session with @nikhilmandlik 

In FF preferences, png and jpg types seem to be corrupted or not recognized properly.

![image](https://user-images.githubusercontent.com/3614296/116163648-01855380-a6ad-11eb-83af-2ef395cdc3d1.png)

Going to try to reset FF mimeType association per this article https://support.mozilla.org/en-US/questions/1074515.

**Comment by nikhilmandlik** [comment]
More info here,
https://support.mozilla.org/en-US/kb/change-firefox-behavior-when-open-file#w_resetting-download-actions-for-all-content-types

**Comment by davetsay** [comment]
progress with https://support.mozilla.org/en-US/questions/1277280.

Preview.app Document types are cleared from FF applications list, but still not downloading properly.
