### ISSUE TITLE
[Menu API] All our drop down menu's should use the new menu api

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#3607]
We should migrate all the drop down menu's to use the new menu API, for consistency. 

This will have the added benefit of smart positioning of menu's. 

@nikhilmandlik 
Identified following menus:
1. Tree right click context menu
1. Notebook Snapshot menu (already done)
1. View Change menu (already done)
1. Display layout alphanumeric context click menu (already done)
1. Display layout Object frame three-dot-menu (already done)
1. Flex layout Object frame three-dot-menu (already done)
1. LAD table row (already done)
1. Telemetry table row (already done)
1. BrowseBar three-dot-menu (already done)
1. Preview header three-dot-menu (already done)

**Comment by charlesh88** [comment]
Verified fixed Testathon 3/29/21.

**Comment by shefalijoshi** [comment]
Verified fixed.

**Comment by davetsay** [comment]
verified
