### ISSUE TITLE
Timers not updating for multiple users as expected

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3608]
Problem has been recurring on hulk/viper during driving sims.

### Steps to reproduce
1. Two users, or Open MCT running in two different browser windows.
2. Create a Timer.
3. Get Timer in view for both users or in both browser windows.
4. User 1 starts the Timer. User 2 should confirm they see the Timer start.
5. User 1 resets Timer. User 2 expects their view of the Timer to reset, but it doesn't.

The Timer has become an important part of driving sims, used to limit and communicate off-optimal sun angle driving intervals between Flight and drivers, therefore this is a blocker.

**Comment by shefalijoshi** [comment]
This apears to be a problem mostly when using CouchDB

**Comment by shefalijoshi** [comment]
Verified fixed.

**Comment by davetsay** [comment]
verified
