### ISSUE TITLE
[openmct-YAMCS] TelemetryTableRow refactor createNormalizedDatum to include extra datum 

### ISSUE THREAD

**Issue by nikhilmandlik** [nasa/openmct#3613]
### Description:
TelemetryTable is filtering `datum` based on `columns`. Need to retain all datum values as it can be used in other helper functions eg: in case of YAMCS `limitEvaluator.evaluate` function uses those extra properties.

### Notes:

comments from Andrew 

> It does some basic processing of incoming data to make it more performant for sorting. Rather than modifying the provided datum (which might be shared with other views), it makes a new datum and just copies across the data it needs, modifying some of it for performance reasons. I think the right thing to do is do a native copy of the provided datum (ensuring it's a deep copy), and then apply the existing data mapping only to the column values. ie. instead of .reduce, use .forEach and modify a copy of the provided datum.

### Testing instructions:
1. run 'openmct-yamcs'
2. create any 'TelemetryTable'
3. drop any dictionary telemetry object. (do not add SWG)

### Expected Result:
Should show 'red/yellow' styles on values crossing defined limits (red: 21-39, yellow: 23-37)

### Actual Result:
not showing any limit styles

**Comment by deeptailor** [comment]
Needs to be tested locally with YAMCS

**Comment by akhenry** [comment]
Needs limits defined in test environment to verify.

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 3/3/2021
