### ISSUE TITLE
Problem with CouchDB. An error occurs while creating an object.

### ISSUE THREAD

**Issue by FillyHolly** [nasa/openmct#3615]
I did the following:
1) Intsall CouchDB on my local machine and create database 'openmct';
2) Comment out the following in index.html `openmct.install(openmct.plugins.LocalStorage());`;
3) Add the following in index.html: (note: You might have to delete the admin account in couchDB and enable CORS for this to work `openmct.install(openmct.plugins.CouchDB('http://127.0.0.1:5984/openmct'))`;
4) `npm start`;
5) Navigate to localhost:8080
6) When checking folder creation and saving, the following error occurs:
<img width="1440" alt="Снимок экрана 2020-12-22 в 13 59 20" src="https://user-images.githubusercontent.com/61470698/102883961-dde1a080-4461-11eb-9c96-8c9fe832ba9c.png">
<img width="604" alt="Снимок экрана 2020-12-22 в 14 00 32" src="https://user-images.githubusercontent.com/61470698/102883974-e1752780-4461-11eb-873d-4821215f5fc5.png">

What am I doing wrong?

**Comment by shefalijoshi** [comment]
@FillyHolly 
Do you have a database called `openmct`in CouchDB?

**Comment by FillyHolly** [comment]
@shefalijoshi 
Yes.
<img width="1309" alt="Снимок экрана 2020-12-23 в 21 51 22" src="https://user-images.githubusercontent.com/61470698/103028579-1ae48a80-4569-11eb-9e0a-3c39224492cf.png">

**Comment by FillyHolly** [comment]
@jvigliotta 
what do you think is the problem?

**Comment by akhenry** [comment]
@FillyHolly Thanks for reporting this, and for providing the error messages from the console. 

Based on the messages you provided it appears that the browser cannot reach Couch DB on the configured port. Is it possible couch is running on something other than 5984? Also, is it possible that a firewall might be preventing access to that port?

**Comment by FillyHolly** [comment]
@akhenry 
Already tried it with the firewall turned off, but it still did not work unfortunately. Can there be more suggestions?

**Comment by shefalijoshi** [comment]
hi @FillyHolly 
I noticed that your database is partitioned. Would you mind trying creating a non-partitioned database and trying again?

**Comment by FillyHolly** [comment]
Hi @shefalijoshi 
did as you said, but still does not work
I still get a 401 (Unauthorized) error

**Comment by FillyHolly** [comment]
@shefalijoshi 
also when replacing LocalStorage with CouchDB, then I can't see the "My Items" directory

**Comment by FillyHolly** [comment]
@shefalijoshi 
Failed to load resource: the server responded with a status of 401 (Unauthorized) - this error

**Comment by shefalijoshi** [comment]
@FillyHolly If you use `curl` or Postman can you make basic requests to CouchDB? If that's not working either then it's an authentication problem with CouchDB itself. Perhaps a username/password that you need to provide before you can access couchDB.

**Comment by jvigliotta** [comment]
@FillyHolly Hi, just wanted to check in and see if you had a chance to try what @shefalijoshi had suggested?

**Comment by jvigliotta** [comment]
Going to close this due to inactivity, feel free to reopen if the problem is not resolved.
