### ISSUE TITLE
[Tree Item] Should visually show user what item they have context clicked

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#3618]
We should visually show the user that a tree item has been context clicked.

Sometimes the context menu is rendered just below the clicked on tree item, and can confuse users as to which item they clicked on.

## Testing Instructions:

1. Context click a tree item
2. Confirm there is some styling to show user which tree item they clicked on

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by akhenry** [comment]
Verified fixed

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 01/07/2021

**Comment by shefalijoshi** [comment]
Verified.

**Comment by charlesh88** [comment]
Testathon 01-07-2021 verified fixed

**Comment by davetsay** [comment]
verified but still see the issue where parts of tree objects displayed as the element are not clickable

![image](https://user-images.githubusercontent.com/3614296/103929105-9e59bc00-50d1-11eb-9388-27ee56762eb8.png)
