### ISSUE TITLE
Add an indication of max. updates per second

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3623]
For performance testing it will be useful to have an indicator that shows how many telemetry updates the browser is able to perform per second based on current load.

**Comment by akhenry** [comment]
#### Testing instructions
1. Install the Performance Indicator plugin following the instructions in the readme.
2. Run Open MCT, and locate the performance indicator in the bar at the top of the screen. You may want to expand the indicators bar so that indicator values are always visible for testing.
3. Observe how the FPS value changes under different load conditions. Try opening a complex display, or a telemetry source with a high data rate (eg. a sine wave generator @ 100Hz).

**Comment by deeptailor** [comment]
Verified Fixed! great job @akhenry

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 01/07/2021
