### ISSUE TITLE
[Maintenance] objectEventEmitter.js is not used

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#3625]
## Overview
objectEventEmitter.js is not used anywhere.

## Expected Behavior
No adverse effects or regressions as a result of removing dead code.

## Steps to Reproduce
1. grep for `objecteventemitter` in codebase
2. Verify nothing in object api breaks as a result of removed code. Notably, any events not being communicated between instances of the same object.

**Comment by davetsay** [comment]
@akhenry , @deeptailor , I don't think `objectEventEmitter.js` is ever used. I can remove it if you agree. I believe it should have been removed in a5a17b9.

**Comment by deeptailor** [comment]
@davetsay - Agree, it must have been left over after the refactor

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 2/25/2021

Couldn't find any hits in the codebase.
