### ISSUE TITLE
[Object Label] Should fill the full width of Tree Item

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#3627]
The object label div should span the entire width when there is no arrow on the right side. 

The issue the current width causes is, when users click on the right side of the tree item, they would expect an open mct context menu, but instead they get a browser context menu.

**Comment by deeptailor** [comment]
<img width="730" alt="Screen Shot 2021-01-07 at 9 52 44 AM" src="https://user-images.githubusercontent.com/13260688/103926742-305fc580-50ce-11eb-8eb7-5b2a2ee8fec4.png">

**Comment by jvigliotta** [comment]
## Testing
- make sure context click ANYWHERE on the tree item (minus the view controls, eg arrows) will show the Open MCT context menu
- make sure a regular click ANYWHERE on the tree item (minus the view controls) will act the same as if you were to click the obect label (name/icon of item in tree)

**Comment by deeptailor** [comment]
Verified Fixed

**Comment by charlesh88** [comment]
Verified fixed Testathon 02/01/2021

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by shefalijoshi** [comment]
Verified fixed
