### ISSUE TITLE
Object Icon missing from 'view-large' and 'Preview'

### ISSUE THREAD

**Issue by nikhilmandlik** [nasa/openmct#3628]
### Description:
on 'view-large' and 'Preview' window Object icon is missing

### Reproduce:
1. create or use old editable object (eg: display Layout)
2. click on edit to enter edit mode
3. now click on any other object from tree
4. this should open preview window
5. Observe Object icon is missing (top left corner)

### Screenshots:
![Screen Shot 2021-01-07 at 9 51 55 AM](https://user-images.githubusercontent.com/1292612/103926602-fee6fa00-50cd-11eb-9655-6a7ac5dc1f44.png)

**Comment by charlesh88** [comment]
For some reason, type.cssClass is not being rendered. Reassigning.

**Comment by charlesh88** [comment]
@nikhilmandlik Problem was type.**definition**.cssClass.

**Comment by charlesh88** [comment]
### Testing Notes
1. Context click any object in the tree and select the "View" command from the menu.
2. In the resulting preview window, observe the object icon is visible in top left corner next to the object's name.
3. Repeat steps above using the "View Large" action from an item in a Display Layout.
