### ISSUE TITLE
[Tree] Navigating while load in progress breaks tree

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#3629]
## Overview
If any portion of the tree is still loading (initial page load), navigating using the tree menu will break all tree functionality.

## Expected Behavior
Navigating while loading should still navigate to object

## Steps to Reproduce
1. Expand a folder in tree that takes time to load on initial page load
2. Refresh page
3. While still loading, Loading indicator visible, click arrow to navigate to a location in tree. navigate not select

![image](https://user-images.githubusercontent.com/3614296/103927499-4cb03200-50cf-11eb-8ed9-ea5c1224495b.png)

**Comment by jvigliotta** [comment]
## Testing
- on a slow loading system (throttle network) load up Open MCT
- before the children of the currently navigated folder in the tree have loaded (initial page load), try to navigate back up the tree (left arrow icon)
- verify you are able to actually navigate away from the loading item and that there are no errors in the console

**Comment by davetsay** [comment]
verified

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by charlesh88** [comment]
Verified fixed Testathon 01/08/2021
