### ISSUE TITLE
Ensure zoom in/out works with mouse/trackpad for plots

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#3631]
For plot zoom via mousewheel, we should use pinch zoom in / out as well, user's have complained that zooming via a trackpad does not work as expected. For some reason, mousewheel zoom in equals pinch zoom out (browser inconsistency).

_Originally posted by @deeptailor in https://github.com/nasa/openmct/issues/3586#issuecomment-740888358_

**Comment by shefalijoshi** [comment]
The `ctrlKey` is set to true when a pinch to zoom gesture is performed on Chrome. This will be used to identify that gesture so that the zoom direction can be reversed.

**Comment by jvigliotta** [comment]
Mousewheel + ctrl key was looking good for me.

Verified Fixed - Testathon: 03/29/2021

**Comment by tiffanyatruong** [comment]
Verified Fixed - Testathon 3/29/2021

**Comment by nikhilmandlik** [comment]
Verified Fixed.
