### ISSUE TITLE
[Condition Widgets] Should show text output of condition set

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#3634]
Summary widgets used to show the text of the matching condition, which is really helpful (on top of the styling changes).

1. One way to do this would be to include the Text Output in the style object.
2. The other is to subscribe to the condition set separately from the style. 

I would prefer the first implementation, because having to drop in the condition set on top of choosing conditional styling seems like bad UX.

@charlesh88  - Any thoughts?

**Comment by charlesh88** [comment]
Agree on your assessment, and had the same thought as well. When Conditional Styling is enabled, let's allow the use of the Output string from each condition. 

<img width="1712" alt="Screen Shot 2021-01-08 at 12 13 19 PM" src="https://user-images.githubusercontent.com/1056412/104060055-31b2f000-51ab-11eb-8769-a24172e9b477.png">

There's some nuance here:
- Condition Widgets should have a setting that determines if they use a Condition Set's Output string, or their own label - see image above. If enabled, when a condition output string is available, it can override the widget's configured label. 
  - If the user enables this setting, then changes to use another CS, we should remember the setting without them having to re-check the box.
  - If the user removes the CS, then adds one back, we don't need to remember the setting.
- Condition outputs can be True, False or String. If string, the user currently isn't required to enter a value when editing a Condition Set. We should either require an entry in the CS editor if String output is chosen, or handle a null value gracefully, like just show nothing, in the widget. If True or False, I think we just convert those booleans to strings and show those as such.

**Comment by shefalijoshi** [comment]
**Testing Notes:**
Create a condition set
Create a condition widget that uses this condition set (using Styles in the inspector)
Enable the Use condition set output as label toggle. Save.
Ensure that the condition set output is displayed on the condition widget.
Disable the toggle and ensure that the condition set output is NOT showed in the condition widget.

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by nikhilmandlik** [comment]
Verified Fixed.
