### ISSUE TITLE
[Notebook] Search should search through section and page names

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#3637]
Notebook search should also search through section and page names. 

At the moment, it only searches through entries.

**Comment by jvigliotta** [comment]
## Testing
- all entries with a hit should be in the results
- pages with no entry hits or section name hits should be in the results
- any sections with no page hits or entry hits should be in the results
- any page or section hits without entry hits should have boiler plate text for the entry text
- any section or section and entry hits with no page hits should default to first page in section
- any hits (section name, page name or entry text) should be highlighted and intuitive

**Comment by nikhilmandlik** [comment]
Verified Fixed.

Wondering about searching (inside entry) for timestamp or embed object text?

**Comment by tiffanyatruong** [comment]
Verified Fixed - Testathon 3/29/2021

**Comment by davetsay** [comment]
section name not being searched correctly

**Comment by shefalijoshi** [comment]
Verified fixed. I didn't see the issues nikhil and dave did. :)

**Comment by nikhilmandlik** [comment]
search not working :(, getting error 
<img width="718" alt="Screen Shot 2021-04-02 at 3 07 19 PM" src="https://user-images.githubusercontent.com/1292612/113457643-2a276f80-93c5-11eb-94fc-4a439d4bf876.png">

**Comment by davetsay** [comment]
@jvigliotta issue with search. See comments by @nikhilmandlik and @shefalijoshi

**Comment by jvigliotta** [comment]
Ok, cool, thanks guys, I'll take a look at this!

**Comment by nikhilmandlik** [comment]
Verified Fixed.
