### ISSUE TITLE
[Telemetry Collections] Add new Telemetry API endpoint for aggregated time-bound telemetry

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#3639]
* Add new function to Telemetry API that returns a telemetryCollection
    * Telemetry Collection works similarly to BoundedTableRowCollection, but is generalized
    * Manages telemetry data and ensures all data is within bounds
    * Keeps telemetry sorted by timestamp
    * Exposes event for when telemetry is added (happens on page, historical request, subscription)
    * Exposes event for when telemetry is removed (happens when telemetry falls out of time bounds)
* TelemetryCollection will essentially remove the distinction between historical and realtime data from views
* TelemetryCollection will expose method for requesting next page, and allowing view to determine if more pages available.
* Telemetry providers will hide details of how paging works in their particular case (different backends will implement paging differently)
* Telemetry API and telemetry providers ARE SINGLETONS AND SHOULD NOT STORE STATE.

**Comment by akhenry** [comment]
Created followup issue for deferred paging work - https://github.com/nasa/openmct/issues/4104

**Comment by akhenry** [comment]
Created followup issue for additional tests - https://github.com/nasa/openmct/issues/4105

**Comment by jvigliotta** [comment]
Currently enabled for Telemetry Tables

## Testing
- View a Telemetry Table
- Verify the following are working as expected:
- Add/Remove Telemetry
- Switch between realtime/historical
- Pause telemetry
- Filter telemetry columns
- Hide/Show columns
- Do various mixes of all of the above
