### ISSUE TITLE
Click on tree item while in edit mode does not show object in large view/preview

### ISSUE THREAD

**Issue by nikhilmandlik** [nasa/openmct#3644]
### Description:
While in an edit mode, Clicking on any tree item does not show object in large view/preview but it opens up view for it.

### Notes:
probably caused by this change:
https://github.com/nasa/openmct/pull/3638/files#diff-01279d83bee4388c41e0e573d1cd9879f7304ad5dbd6306a6e29b54b065feaa9R150

commenting out `event.stopPropagation();` solves this issue but not sure at what cost 😅 

### Testing instructions:
1. open display layout
2. be in edit mode
3. click on any other object inside tree

### Expected Result:
Clicking on any tree item while in an edit mode to show object in large view/preview.

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 02/01/2021

**Comment by deeptailor** [comment]
Verified Fixed

**Comment by charlesh88** [comment]
Verified fixed Testathon 02/01/2021

**Comment by tiffanyatruong** [comment]
verified fixed 2/1/2021

**Comment by nikhilmandlik** [comment]
Verified Fixed.
