### ISSUE TITLE
Clicking "View Large" on Imagery leaves it paused

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3647]
Seen on hulk/viper 01/14/21. When operating in real-time mode, clicking "View Large" on an Image in a layout pauses it in the overlay, which is desirable. But the image should then be unpaused when dismissing the overlay, unless the user actively unpaused and paused the image via the Pause button, or clicked a past image in the thumb strip.

### Reproduce
1. Put Time Conductor in real-time mode.
2. Click "View Large" on an Image view in a layout.
3. Observe: the image in the overlay is paused. This is Ok.
4. Dismiss the overlay.
5. Observe: the image in the layout continues to be paused, but instead should be returned to the initial auto-updating mode.

**Comment by akhenry** [comment]
Agreed. I'm not sure we need to put the imagery view into a paused state at all, the image shown in the overlay should just be the one that the user embiggened. The imagery view can carry on doing its thing in the background because the user can't see it. It would be great if we could avoid pausing and unpausing the imagery view in the process (just sounds like code complexity that we don't need).

**Comment by charlesh88** [comment]
> Agreed. I'm not sure we need to put the imagery view into a paused state at all, the image shown in the overlay should just be the one that the user embiggened. The imagery view can carry on doing its thing in the background because the user can't see it. It would be great if we could avoid pausing and unpausing the imagery view in the process (just sounds like code complexity that we don't need).

Initially, I thought we shouldn't be pausing the image either. But, typically the user is embiggening because they're studying a _particular_ image in order to make a decision, and the thinking is that if that gets replaced by a new, incoming image that would be quite disruptive. I will discuss this with stakeholders and feed back into this issue.

We should also consider a notification of new imagery, that when paused, lets the user know a new image has come in and gives an affordance to see it and/or switch back to RT mode.

**Comment by akhenry** [comment]
I should have checked how view large works with imagery before commenting. It enlarges the whole imagery view, and not just the image itself. In that case, yes, it should go into pause mode while it's embiggened.

I thought that it just showed the image, in which case I was hoping we could avoid the code spaghettification involved in adding logic to pause it while it's in view large, and then unpause it when it's not.

**Comment by shefalijoshi** [comment]
The code for imagery view for time strips now emits a 'destroy' event when viewLarge closes. We could key off this to unpause the imagery when view large exits.

**Comment by michaelrogers** [comment]
# How to test

Route 1
1. Create a display layout with at least one imagery object
2. Ensure clock is realtime and not paused
3. Click on the imagery to activate the view large action
4. Observe the imagery is paused (orange outline around image)
5. Exit overlay
6. Observe that the imagery pause/unpause status is restored

Route 2
1. Create a display layout with at least one imagery object
2. Ensure clock is realtime and not paused
3. Expand the context menu of an image
4. Click on the View Large or View action from the context menu
5. Observe the imagery is paused (orange outline around image)
6. Exit overlay
7. Observe that the imagery pause/unpause status is restored

**Comment by jvigliotta** [comment]
Verified Fixed: Testathon - 1/24/23

**Comment by rukmini-bose** [comment]
Verified Fixed 3/20/2024

**Comment by charlesh88** [comment]
Testathon 2024-03-20 cannot repro, fixed.
