### ISSUE TITLE
CouchDB "Failed to load resource: the server responded with a status of 401 (Unauthorized)"

### ISSUE THREAD

**Issue by FillyHolly** [nasa/openmct#3653]
1. I commented out LocalStorage ()
2. Added CouchDB plugin ('http://127.0.0.1:5984/openmct')
3. Created an empty database in CouchDB and named openmct
But when I run openmct, I get an authorization error .... With CORs enabled.
<img width="1440" alt="Снимок экрана 2021-01-26 в 20 07 52" src="https://user-images.githubusercontent.com/61470698/105879625-7647e380-6013-11eb-97a4-b4a2eec48f1d.png">
<img width="1440" alt="Снимок экрана 2021-01-26 в 20 08 53" src="https://user-images.githubusercontent.com/61470698/105879643-7b0c9780-6013-11eb-8db9-a870f1eb534c.png">

**Comment by akhenry** [comment]
Which version of Couch DB are you using? By default Couch used to be in "admin party" mode which meant that no authentication was necessary, but that appears to have changed from version 3 onward.

Did you see a login prompt by any chance? I would expect a 401 response to trigger browser native authentication. Is it possible that your instance of Couch is configured to use something other than basic authentication?

**Comment by FillyHolly** [comment]
@akhenry 
I am using version 3.1.1
Maybe I should try to install a different version?

**Comment by FillyHolly** [comment]
@akhenry 
Yes it worked, thanks!
