### ISSUE TITLE
Demo (https://openmct-demo.herokuapp.com/) is erroring out

### ISSUE THREAD

**Issue by ElijahLynn** [nasa/openmct#3656]
https://openmct-demo.herokuapp.com/

```
Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail
```

![image](https://user-images.githubusercontent.com/1504756/106210028-ec1a8f00-617a-11eb-928d-a33f1125a4b5.png)

**Comment by jvigliotta** [comment]
@ElijahLynn Thank you for the heads up, we're aware of and  looking into the issue and hope to have it resolved soon. Currently, it does seem to be up if you wanted to checkout the demo.

**Comment by benridley** [comment]
Seems to be fixed now.

**Comment by ElijahLynn** [comment]
Confirmed it is working now for me!

**Comment by akhenry** [comment]
Thanks for reporting this outage. Still not sure what was causing the issue, but after working great for years the app suddenly started crashing on Heroku without much feedback. I have restarted the dyno, which seems to have fixed it for now. We'll keep an eye on it.
