### ISSUE TITLE
Defer loading of domainObjects

### ISSUE THREAD

**Issue by johanfforsberg** [nasa/openmct#3662]
Hi OpenMCT people,

I've been playing around with OpenMCT for a possible use case at work, and I started building a plugin to allow access to our control system database. It looks great so far, I've been following the tutorial, but now I'm running into performance issues. 

Seems like OpenMCT always reads in the entire world immediately even if the tree is not yet open. This is a problem because the database can contain many thousands of things, and a lot of them - mainly the telemetry objects like "voltage" or "pressure" - can only be listed by directly querying their parent "device" servers individually. This will obviously not scale very well.

Is there a way to tell OpenMCT to not create domainObjects until they are actually needed somewhere, e.g. being visible in the tree? I guess this would not work so well with the search functionality, but I saw that there is ongoing work to offload that to a provider anyway.

Thanks for an awesome project!

**Comment by jvigliotta** [comment]
Hi @johanfforsberg, you're correct, we are working on offloading search to to the providers. Until then you can comment out the lines below:

https://github.com/nasa/openmct/blob/c0742d521cba2369b7070fc91573a56a30960c4f/platform/search/src/services/GenericSearchProvider.js#L200-L205

That will prevent indexing, so search won't return anything, but you should see significant performance improvement on load.

**Comment by akhenry** [comment]
Thanks for raising this @johanfforsberg! [We have an issue already that is tracking this](https://github.com/nasa/openmct/issues/3406), so I'm going to close this and link to it.
