### ISSUE TITLE
Remove Follow Time Action and Indicator

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3664]
These are legacy components that should be removed as they are no longer used.

The ["Follow Timer Action"](https://github.com/nasa/openmct/blob/master/platform/features/clock/src/actions/FollowTimerAction.js) previously allowed a user to indicate a timer's progress with a moving vertical line on our timeline view. With the retirement of our legacy timelines, this action now does nothing. The action had a [corresponding indicator](platform/features/clock/src/indicators/FollowIndicator.js) that showed which timer was currently being followed.

The source code for each of these should be deleted.

The Action and Indicator are shown in the screenshots below -

![Screen Shot 2021-02-03 at 7 54 26 AM](https://user-images.githubusercontent.com/4215777/106772771-307fb200-65f5-11eb-8bee-e2de44b157b5.png)

![Screen Shot 2021-02-03 at 7 50 23 AM](https://user-images.githubusercontent.com/4215777/106772195-9ddf1300-65f4-11eb-85e7-07cb5881acf8.png)

**Comment by unlikelyzero** [comment]
Adding to retest to verify if this was removed at some point

**Comment by akhenry** [comment]
Closed to retest

**Comment by akhenry** [comment]
Verified fixed.

**Comment by rukmini-bose** [comment]
Verified Testathon 12/5. Do not see the action or indicator anymore.

**Comment by rukmini-bose** [comment]
Verified Testathon, 3/20/2024. Still not seeing it!

**Comment by charlesh88** [comment]
Testathon 2024-03-20, fixed.
