### ISSUE TITLE
[Tree Item] Clicking on tree item when in edit mode is broken

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#3667]
Clicking on the tree item when in edit mode triggers preview and navigate, when it should only trigger preview.

Steps to reproduce:

1. Navigate to an editable domainObject.
2. Click on the edit button
3. When in edit mode, click on another domainObject in the tree
4. This should invoke a preview of the domainObject, just as expected.
5. Close the overlay.
6. Oh no, you were also navigated to the item you were previewing 👎

**Comment by tiffanyatruong** [comment]
verified fixed 2/25/21

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 2/25/2021

**Comment by charlesh88** [comment]
Verified fixed Testathon 02/25/21.
