### ISSUE TITLE
[Plots] Angular Plot parity

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3687]
Issues to be addressed in Vue plots to achieve parity with Angular plots
* [x] Plot grids do not show in the new Vue plots
* [ ] The cursor should change from a cross to a hand when the pan modifier key is held down (same as conductor axis)
* [x] Remove `mct` prefix from all files, class, and component names
* [x] Inspector needs to be re-implemented sans Angular

**Comment by shefalijoshi** [comment]
Test Instructions:
- Create a time strip view
- Add an overlay plot to it
- Select the plot and do the following:
1. In view mode, ensure that Plot Series, Y Axis and Legend information is displayed in the inspector
2. In view mode, expand each Plot Series listed in the inspector view and ensure that information for each is displayed correctly.
3. . In edit mode, change options for one or more Plot Series. Save the changes and refresh (refreshing is a known bug). The changes made should be applied to the Series
4. . In edit mode, change options for the YAxis and Legend. Save the changes and refresh (refreshing is a known bug). The changes made should be applied to the YAxis and Legend.

**Comment by nikhilmandlik** [comment]
Verified Fixed.
