### ISSUE TITLE
Refactor plots to use Vue

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#3691]
Plots for telemetry objects, overlay plots and stacked plots should be implemented using Vue and no longer use Angular

**Comment by charlesh88** [comment]
How is this to be tested?

**Comment by akhenry** [comment]
@shefalijoshi Testing instructions

**Comment by shefalijoshi** [comment]
Testing instructions:
1. Create a time strip from the Create menu.
2. Drag in a telemetry endpoint, a stacked plot and an overlay plot into the time strip
Check for the following:
- The 3 plots are rendered in the time strip view
- None of the plots show the X Axis
- The toolbar to export images as PNG, JPG are hidden
- Zoom, pan, reset still works
- Change the time bounds and ensure the data in the plots refreshes correctly
-

**Comment by charlesh88** [comment]
Verified fixed Testathon 3-3-21-EB.

**Comment by akhenry** [comment]
Verified fixed
