### ISSUE TITLE
Basic time strip view for plots and plans

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#3692]
A basic time strip view that includes:
1. Time system with given fixed time bounds / local clock
2. Displays plots for given time bounds - Individual x axis controls not shown.
3. Displays plans for given time bounds

**Comment by shefalijoshi** [comment]
Testing instructions:
Create a time strip object
Create an overlay plot with 2 or more telemetry objects
Create a stacked plot with 2 or more telemetry objects
Create a plan with activities - ensure the plan renders when the plan object is selected in the tree
Drag and drop single telemetry, overlay plot and stacked plot into a time strip view
Drag and drop the plan into the time strip view

1. The plots should be displayed with export buttons and x-axis hidden. Zoom, cursor guides, gridlines, changing bounds should work.
2. Plan with activities should be rendered and should update based on time bounds.
3. Time systems installed should be displayed at the top of the time strip and should sync with the time conductor.

Change from fixed timestamp to local clock and ensure the above work.

**Comment by tiffanyatruong** [comment]
verified fixed 2/25/2021

**Comment by charlesh88** [comment]
Verified fixed Testathon 02/25/21.
