### ISSUE TITLE
[Elements Pool] Needs context-clicked class like tree-item and better rearranging drag and drop interface

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#3695]
1. The elements pool needs to behave similarly to tree-item when context clicked i.e When context clicked, needs to show the user which item you context clicked on.

1. The drag and drop interface for rearranging composition items needs to be improved. We need to show where the user is dropping the element item. 

### Item 1:

1. Create a display layout and add a few telemetry  and non telemetry items
2. While still in edit mode, right click on an element in the elements pool
3. Verify that there is a border around the clicked item

### Item 2:
1. Drag the last element item to the first element item
2. Verify the drop targets are highlighted as you drag over the other element items

**Comment by charlesh88** [comment]
Verified NOT fixed Testathon 3-3-21, don't see any behavior as described in testing notes.

**Comment by davetsay** [comment]
verified
