### ISSUE TITLE
[Tree Item] The navigate up button should be highlighted on hover

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#3697]
At the moment, the navigate up arrow is highlighted when the user is hovering over the entire tree-item. We should use the same styling as the navigate down arrow, and highlight only when the user is hovering over the arrow.

This has at times caused me to navigate to the object vs navigate up the tree level, because I was not sure if I was over the arrow or not

**Comment by jvigliotta** [comment]
This is out of date, we no longer have an up arrow in the tree.
