### ISSUE TITLE
Scalability of open MCT

### ISSUE THREAD

**Issue by Vaibhav2121** [nasa/openmct#3698]
Dear community members,

What is the scalability of open MCT, how much parameters it can show smoothly in realtime.  Suppose I have 100,000 parameters that update every 1 seconds, Is it possible in open MCT to receive so much data and plot any of the parameters in real time.

What is the limit (with respect to number of parameters that can be passed to openmct in real time.

**Comment by DusterTheFirst** [comment]
This may be better suited as a discussion topic: https://github.com/nasa/openmct/discussions/categories/community-q-a

**Comment by unlikelyzero** [comment]
@Vaibhav2121 as @DusterTheFirst suggested, please follow up with a community discussion post!
