### ISSUE TITLE
Plans are not listed in results if the plans are large

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#3700]
Prerequisite: CouchDB and CouchDBSearch plugins are installed.

Create a plan with a lot of activities (100 or more).
Duplicate and save this plan a few times to CouchDB
Load openmct and navigate to the CouchDB Documents folder

Expected: All plans are listed under this folder
Actual: The folder says 'No items'

![image](https://user-images.githubusercontent.com/5247066/109081734-94a70a80-76b7-11eb-927a-384a94f4e880.png)

**Comment by akhenry** [comment]
Verified Fixed
