### ISSUE TITLE
[Tree] object added to composition does not appear in tree

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#3708]
## Overview
Object in composition not appearing in tree

## Expected Behavior
Object added to composition should appear in tree

## Steps to Reproduce
1. Create and save a flexible layout (or any creatable object that allows composition)
2. Drag an object into the flexible layout
3. Navigate to flexible layout in the tree
4. Expand the flexible layout in the tree

![bug - flexible layout composition](https://user-images.githubusercontent.com/3614296/109198237-d5a02d00-7752-11eb-8c65-86260e4b79c7.gif)

![image](https://user-images.githubusercontent.com/3614296/109197908-717d6900-7752-11eb-853d-9e8c64c282bc.png)

**Comment by yacotaco** [comment]
Hi @davetsay, I would like to fix this bug but I cannot reproduce it in Chrome, FireFox and Opera. Does this issue occur only in Safari?

**Comment by jvigliotta** [comment]
hey @yacotaco thanks for your interest in helping out, we're actually in the process of redoing the tree, so this may actually be a moot point after that. I'm going to close for now, @davetsay we can reevaluate after the new tree is up and see if we need to reopen this. Also, @yacotaco if you have not already done so, we'll need you to follow the steps here: https://github.com/nasa/openmct/discussions/3821 to contribute to the codebase. Thanks!

**Comment by yacotaco** [comment]
Hi @jvigliotta ok, so I'll take a look at other bugs and send CLA.
