### ISSUE TITLE
Searching in the tree renders openmct unusable

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#3709]
Search for 'hecd' in the nav tree.
Wait for results to be listed
Try to cancel out of the search results by clicking on the (x) button
OR try to perform some action in the main view
Observed: It looks like there are a lot of documents being retrieved from the persistence store and you can't really do anything in the openmct application.

**Comment by jvigliotta** [comment]
## Testing
- open network tab to view requests
- make sure the object provider you're using for OpenMCT makes fetch calls (ex. CouchDB)
- perform a search that will return many results
- then cancel the search (hitting the target button above search box or x button in search input box)
- verify in network tab that requests are stopped
- make sure there are no errors

**Comment by akhenry** [comment]
Verified Fixed

**Comment by charlesh88** [comment]
Verified fixed Testathon 3-3-21-EB.

**Comment by deeptailor** [comment]
Verified Fixed

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 3/3/2021
