### ISSUE TITLE
Modifying the index.html file to include any of the tutorial provided scripts results in a blank page

### ISSUE THREAD

**Issue by jstoezel** [nasa/openmct#3720]
Edited out

**Comment by jvigliotta** [comment]
@jstoezel Hello, thanks for creating this issue, can you provide some more details specifically of the steps you went through to encounter this issue? Also, any errors in the console or other useful information. Thanks!

**Comment by unlikelyzero** [comment]
@jstoezel i'm closing this out. Please re-open if you find some reproduction steps!
