### ISSUE TITLE
[Plan View] Plan View Icon's Don't Show in Folder Grid View

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#3721]
In file grid view, plans do not show any icons. They DO show in list view and in the tree.
![Screen Shot 2021-03-01 at 6 43 42 PM](https://user-images.githubusercontent.com/12013460/109589077-a248ff80-7abe-11eb-8761-6d8bdcb6862e.png)

**Comment by charlesh88** [comment]
This has been fixed.
