### ISSUE TITLE
Vue-based plots should not be available in view-switcher

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#3722]
Till we're ready to switch over completely to Vue-based plots, the view-switcher in the main view should not list it as a view option.

**Comment by akhenry** [comment]
Have been meaning to file this issue as well. We should fix it for build 4

**Comment by akhenry** [comment]
Plots are not showing any view switcher at all now.

**Comment by charlesh88** [comment]
Verified NOT fixed Testathon 3-3-21, View Switcher is gone.

**Comment by akhenry** [comment]
Verified fixed
