### ISSUE TITLE
Plans should accept either file input OR JSON object

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#3730]
Plans created from the Create menu use a file upload, which stores the activities as a JSON string.
Plans created from the planner tool and saved to CouchDB stores the activities as JSON objects (not strings).

For now, we will support both (ease of testing). Later we will need to remove one or the other.

**Comment by shefalijoshi** [comment]
Testing instructions:
On hulk, upload a plan using the planning tool - ensure the plan is rendered correctly
OR
Use a plan json file and upload the plan using OpenMCT. Ensure the plan is rendered correctly.

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 3/4/2021

Uploaded a plan JSON and everything seemed good.

**Comment by akhenry** [comment]
Verified Fixed
