### ISSUE TITLE
[Imagery Freshness] Imagery freshness indicators flicker sometimes

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#3731]
The checks for freshness are making (OR) checks when they should be making (AND) checks. Need to check if freshness for any of the required telemetry is false before checking others. All must be fresh.

**Comment by jvigliotta** [comment]
## Testing
- make sure indicators don't show and disappear and come back repeatedly

**Comment by akhenry** [comment]
Verified fixed.

**Comment by deeptailor** [comment]
Verified Fixed
