### ISSUE TITLE
Unable to switch views or edit objects

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#3732]
The ability to switch between views (tables vs plots etc.) and the ability to edit domain objects in the main view has been compromised.

**Comment by shefalijoshi** [comment]
Testing instructions:
**Editing objects**
1. Create any editable domain object
2. Click on the Edit icon in the actions bar in the main view
=> Expect editing and saving to work.

**Switching views**
1. Click on a telemetry endpoint
2. Look for the view switcher dropdown in the top right of the main view
=> Expect to be able to Switch between plot and telemetry table and back.

**Comment by akhenry** [comment]
Verified fixed

**Comment by deeptailor** [comment]
Verified Fixed
