### ISSUE TITLE
Unable to create objects

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#3735]
Click on the create menu
Choose Display layout or any other objects

Expected: The properties dialog is displayed and pressing ok creates an object.
Actual: No dialog is displayed - unable to proceed after this.

**Comment by shefalijoshi** [comment]
Testing instructions:
Try to create an object using and save it. Should succeed.
Try to duplicate an object and save it. Should succeed.

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 3/4/2021

There IS a weird UI thing where the folder you're viewing during creation goes into edit mode (blue line around it) in the object view... not sure if it was always like that or not, or if it's a big deal or even an issue.

**Comment by tiffanyatruong** [comment]
verified fixed - testathon 3/4/2021

**Comment by akhenry** [comment]
Verified fixed

**Comment by davetsay** [comment]
verified
