### ISSUE TITLE
[Self updating plans] When plan name is updated, the title of the plan on the browser tab will stay as the original name

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#3739]
When plan (domainObject) name is updated via CouchDB, the browser tab name does not change. 

Notes:
- [ ] need to change title from function `update Name` https://github.com/nasa/openmct/blob/4c9c084eec3ffa7ec42ca2c810d1b8bf85e54633/src/ui/layout/BrowseBar.vue#L267
- [ ]  change title from function `updateModel` https://github.com/nasa/openmct/blob/4c9c084eec3ffa7ec42ca2c810d1b8bf85e54633/platform/commonUI/edit/src/actions/PropertiesDialog.js#L83

**Comment by akhenry** [comment]
Browser title gets set on navigation, and we are not listening for subsequent changes.

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by nikhilmandlik** [comment]
Verified Fixed.
