### ISSUE TITLE
[Imagery] Cant scroll historical images when not paused

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#3740]
When imagery is not paused, users cant scroll the historical images strip. We should be able to scroll back even when not paused. We do something similar in telemetry tables.

**Comment by akhenry** [comment]
Workaround is to pause imagery to go back in time.

**Comment by davetsay** [comment]
I also noticed if you are on local clock, switch to fixed time mode, then switch back to local clock mode, the thumbnail strip focuses on the oldest thumbnails, ie. scrolls all the way left. Have also noticed on occasion a broken image link toggling back to local clock

**Comment by davetsay** [comment]
My last comment may not be correct. Tested again on different deployment using the latest master and no bad scroll behavior (except for that seen in the originally filed issue).

**Comment by davetsay** [comment]
verified

**Comment by shefalijoshi** [comment]
Verified fixed

**Comment by nikhilmandlik** [comment]
Verified Fixed.
