### ISSUE TITLE
[Imagery] Compass rose does not resize with images

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#3742]
When resizing the window, the compass rose stays the same size, sometimes covering the imagery entirely.

**Comment by charlesh88** [comment]
Who is this @deeptailor guy and why is he so insightful? Was coming in here to file this issue myself and luckily checked first...

![image](https://user-images.githubusercontent.com/1056412/112069648-6f2be600-8b29-11eb-97b0-697d086b701f.png)

Yes, we should resize the compass rose when imagery elements are small, as in any kind of layout or on mobile in the main view. Both layouts currently apply a CSS class `is-in-small-container` when the element is small, and this can be used to solve this problem there. This doesn't work for main views though; IMO we should move this functionality into the view provider, which would make it work in all contexts. @akhenry is that true, and what do you think? Many of our views beyond Imagery would benefit from this as well: plots, Clocks, Timers and Notebook could all use this.

**Comment by akhenry** [comment]
@charlesh88 I would be amenable to introducing something into our view API to tell view providers that they are being asked for an "embedded" view, rather than a main view, if that's useful. With regards to size though, my tendency is to just let views figure out how best to display themselves with the pixels that they have. Views can get size information from the element that they are provided with in their `show` function.

**Comment by charlesh88** [comment]
WIP for a pure CSS width-based solution for this at https://codepen.io/charlesh88/pen/OJWawoW

**Comment by charlesh88** [comment]
### Testing Notes
The compass rose should dynamically size itself as the size of the image container changes. This goes for the main view, and for imagery placed within either type of Layout.

Ensure that the imagery view works as detailed below in the main view, a Display Layout and a Flexible Layout.

1. Between image widths of 1000px and 500px, the compass rose sizes and places itself proportionally:
![Screen Shot 2021-04-23 at 2 21 37 PM](https://user-images.githubusercontent.com/1056412/115933414-adc40180-a443-11eb-8cc4-993821693af0.png)

2. When the image is 1000px wide or more, the compass rose doesn't increase in size:
![Screen Shot 2021-04-23 at 2 21 50 PM](https://user-images.githubusercontent.com/1056412/115933437-b87e9680-a443-11eb-99b6-ad3f53e610d8.png)

3. When the image is below 500px wide, all ticks and the SWE indicator labels are removed:
![Screen Shot 2021-04-23 at 2 01 54 PM](https://user-images.githubusercontent.com/1056412/115933453-bf0d0e00-a443-11eb-8153-56edc70b15cc.png)

4. When the image is below 300px wide, the rose doesn't get any smaller:
![Screen Shot 2021-04-23 at 2 55 34 PM](https://user-images.githubusercontent.com/1056412/115933754-6722d700-a444-11eb-8ce3-2f6366fe604b.png)

**Comment by charlesh88** [comment]
Cannot verify Testathon 6/2/2021: imagery not configured properly on banner in order to show the compass rose.

**Comment by charlesh88** [comment]
Verified fixed Testathon 6/4/2021

**Comment by jvigliotta** [comment]
Verified fixed Testathon 6/4/2021

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by akhenry** [comment]
Verified Fixed
