### ISSUE TITLE
[Imagery] Remove roll and pitch as required keys for orientation

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#3745]
Roll and pitch will not be used in the final product. Need to remove them as any keys specified are required.

## Testing
- verify roll and pitch keys are removed from imagery config
- make sure no calls to roll and pitch telemetry are being called in the network tab when viewing imagery

**Comment by mariuszr** [comment]
@jvigliotta Seems like it has been resolved in the merged PR #3744 during solving issue #3748

**Comment by mariuszr** [comment]
@jvigliotta missed removing them from the Compass's [unit test](https://github.com/nasa/openmct/blob/master/src/plugins/imagery/components/Compass/pluginSpec.js#L35-L36)

**Comment by mariuszr** [comment]
@davetsay @akhenry Please check and analyze my comments and PR related to the issue.

**Comment by jvigliotta** [comment]
This was fixed in PR #3744

**Comment by mariuszr** [comment]
Hi @jvigliotta, please note that the PR [#3817](https://github.com/nasa/openmct/pull/3817) completes the PR [#3744](https://github.com/nasa/openmct/pull/3744) by removing the elements that were missed.

**Comment by unlikelyzero** [comment]
@jvigliotta to verify
