### ISSUE TITLE
file contain

### ISSUE THREAD

**Issue by alexandereric995** [nasa/openmct#3746]
File is not as equal to to Demo

**Comment by jvigliotta** [comment]
@alexandereric995 Hello, are you able to provide more information for this issue? Thanks!

**Comment by alexandereric995** [comment]
It is nasa openmct, correct? But, the js and code for gui file does not compile

**Comment by jvigliotta** [comment]
Hi @alexandereric995 have you tried the steps here: https://github.com/nasa/openmct#building-and-running-open-mct-locally

Is this where you're running into issues?

**Comment by alexandereric995** [comment]
Dyd sir... But this webbase generate empty

**Comment by akhenry** [comment]
@alexandereric995  Which version of node are you using? I would recommend building it with version 10 or later.

**Comment by alexandereric995** [comment]
Ops, my bad... Do you have the webbase css?
