### ISSUE TITLE
[Imagery] should be compatible with VIPER data

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#3748]
## Overview
New imagery features should be compatible with VIPER data

## Expected Behavior
- The following features should work with VIPER data
- Imagery temporal freshness
- Imagery positional freshness
- Imagery camera freshness
- Compass rose
- Compass HUD

## Steps to Reproduce
1. using VIPER deployment navigate to telemetry endpoint providing nav cam imagery
2. Observe freshness
3. Observe Compass rose and HUD

**Comment by davetsay** [comment]
No clue why this was not auto closed

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 04/22/2021
