### ISSUE TITLE
[Notebook] First page of section entries deleted if any other page is deleted

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#3753]
When using the section and page panel in notebook, if you delete a page (using dropdown arrow on page). The first pages entrie(s) will be deleted as well.

## Testing
- have a section with multiple pages and one or more entries
- delete any of the pages other than the first
- make sure the first page still has it's original entries

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by davetsay** [comment]
verified
