### ISSUE TITLE
[Notebooks] Don't save images on the object

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3755]
When "snapshots" are saved against a Notebook entry the image is stored as a base-64 encoded string in the notebook itself. This can cause notebook sizes to become very large, very quickly.

Here is a proposed remedy:
1. Store only small thumbnails on the notebook entry itself.
2. Store the full-scale image as a separate DomainObject (though it should not appear in the tree. It could be as simple as:
```
const imageObject = {
    {
        namespace: notebook.identifier.namespace,
        key: uuid()
    },
    type: 'notebook-image',
    imageData: 'TWFuIGlzIGRpc3Rpbmd1aXN...'
}
...
```
3. Save a referencec to the imageObject in the notebook entry
4. Define a migration script that any images in our current notebooks into separate image objects, and links to them.

**Comment by akhenry** [comment]
@nikhilmandlik Needs some testing instructions. Thanks!

**Comment by kobe1104** [comment]
Verified testathon 6/22/21.

**Comment by unlikelyzero** [comment]
More testing needed

**Comment by shefalijoshi** [comment]
Looks good so far.

**Comment by unlikelyzero** [comment]
To retest in next testathon

**Comment by charlesh88** [comment]
Verified fixed Testathon 07-13-21
![image](https://user-images.githubusercontent.com/1056412/125503337-0bbc20d2-4c4d-4b82-b0b9-4696bf3d3f31.png)
