### ISSUE TITLE
[Imagery] Images cannot be saved

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3756]
Users need a way to be able to save images from the imagery view. 

Right-click and "Save Image" would be perfectly sufficient except that it doesn't work right now because it's blocked by [a div that overlays the image](https://github.com/nasa/openmct/blob/master/src/plugins/imagery/components/Compass/Compass.vue#L24) which is part of the compass implementation.

If the compass can't be achieved without blocking the browser's build in "Save Image" functionality, then we should implement an action for doing this.

**Comment by xshifty** [comment]
Hello @akhenry. I added a new action to imagery plugin in order to make it possible to download the image.
Hope it solves this problem.

If you have any suggestion, let me know.

**Comment by charlesh88** [comment]
### Testing Notes
Ideally we test this in a variety of browsers and OS's, especially Ubuntu if possible.
1. Navigate to an imagery endpoint, ideally real imagery (vs. Example Imagery) so that you can see the compass rose.
2. Context-click anywhere in the main image (other than the compass rose) and verify that the browser-based context menu includes an action to save the image.
3. Save the image, then view the resulting file and confirm the image was saved correctly.
4. Put the image in a Display Layout and repeat steps 1 - 3.
5.  Put the image in a Flexible Layout and repeat steps 1 - 3.

**Comment by charlesh88** [comment]
Verified fixed Testathon 6/2/2021

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by jvigliotta** [comment]
Still seeing an issue when right clicking in certain areas.

**Comment by unlikelyzero** [comment]
@charlesh88 can you verify that this was not already fixed?

**Comment by charlesh88** [comment]
Verified NOT fixed Bug Bash 04-21-22. Context-click on image does not give user a Save Image... option. This is due to a code change to display imagery as a div with background.

![image](https://user-images.githubusercontent.com/1056412/164532441-0e49d242-fa8e-478c-8a7d-6ee96e790d6e.png)

**Comment by akhenry** [comment]
We need to revisit this. If the image does indeed need to be displayed as the background of a div then we need to provide the user with some additional affordance for downloading the image. @[xshifty](https://github.com/xshifty) proposed an approach using a new local control, which seems like a reasonable alternative if we can't use an image element.

Unless there's some trick we can use to trigger the correct browser native behavior? Like an aria attribute or something?

**Comment by charlesh88** [comment]
Solution here: https://codepen.io/charlesh88/pen/bGLNyzv?editors=1100

Basically, layer an actual <img> tag (with opacity: 0) over the zoomable/pan-able background-image div.

**Comment by charlesh88** [comment]
### Testing Notes
1. View Example Imagery or an image data product.
2. Context (right) click on the image itself and verify that the OS-provided context menu includes "Save Image As...". Note that the image itself must be clicked; clicking outside the image, the Prev or Next Image buttons or the compass rose will not (and is not expected to) provide an image context. 
3. Choose that menu option, then verify that the downloaded image is the same one that was displayed. 
<img width="239" alt="image" src="https://user-images.githubusercontent.com/1056412/168127842-a401f092-0235-43c4-bb56-33257eca4829.png">

**Comment by michaelrogers** [comment]
Fix verified locally on `release/2.0.5` branch. User is able to successfully save images.

**Comment by khalidadil** [comment]
Verified fixed - testathon on 06/09/2022
