### ISSUE TITLE
[Couch DB] Open MCT should using Couch's "bulk" query support

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3757]
Open MCT issues a lot of requests for objects to the backend persistence store. Right now these are issued as individual GET requests, however Couch DB [supports bulk requesting of objects](https://docs.couchdb.org/en/stable/api/database/bulk-api.html).

This could be used to greatly reduce the number of HTTP requests issued to the backend and thus increase performance.

**Comment by mudinthewater** [comment]
@akhenry Would love this for old tree but for new tree does it matter that much?

**Comment by akhenry** [comment]
@mudinthewater We are finding that with large folders it provides a discernible speed boost, especially with home VPN connections. Sending multiple get requests adds some latency obviously, but the main issue is the way that browsers limit the number of simultaneous requests. Loading even modest folders (with, eg. 20 items) that exceed the limit (I think it's 6 for a given host on Chrome) will block until some of the initial requests return.

The other big improvement that's coming for Couch users is [offloading search to Couch DB](https://github.com/nasa/openmct/issues/3218) rather than using the in-memory indexer. This avoids the need for an exhaustive tree traversal to build an index on load, which DOSs the server and fills the browser's request queue before you've even done anything.

Would love to be able to do either or both of the above optimizations for our MCWS users, but we don't have backend support for them. One thing that *might* help MCWS users is enabling http/2 on the server (if possible), since you avoid the setup and teardown of each GET request. Haven't had a chance to experiment with http/2 to see if it makes much difference though, and http/2 can introduce its own problems by increasing server load (since more requests can be serviced at once).

**Comment by mudinthewater** [comment]
mcws persistance has way worse problems that just http/2. They could start by maybe not storing it in plain text on disk so that it's not 100x slower than couch but that's just me.

**Comment by akhenry** [comment]
Right, http/2 isn't going to magically solve all of their problems, but it might give a low cost speed boost if it's an option.

**Comment by mudinthewater** [comment]
Yeah lots of low hanging fruit. Also setting the byte length on the return would enable tomcat to control compression and speed things up a lot. 
Re: search, this sounds like a huge deal. I know search has always been an issue in MCT, and I think at some points has basically completely hosted the UI while it makes requests in Vista.

**Comment by akhenry** [comment]
@mudinthewater  Ah, I didn't realize they're not compressing the responses. Eeesh.

Search is a pretty big deal. Fixing it has actually introduced its own problems. Nothing's ever simple 😄 It's a long story, but we have some legacy code paths that actually use an in-memory domain object cache. With search no longer indexing Couch objects those objects don't get cached on load, which has highlighted a few places where we were benefiting from the fact that every domain object was being eagerly loaded on start. I have some thoughts on how we can address this though.

**Comment by mudinthewater** [comment]
Oh they're compressing them just not with tomcat's built in compression but with java gzip library. If you switch to tomcat compresssion it compresses all the objects, even though some are small enough that compression makes it slower. Needs the size parameter so we can better use tomcat compression since mcws' built-in compression is slower than it.

**Comment by akhenry** [comment]
### Testing instructions

Note: Instructions require an install of Open MCT that is using couch DB for persistence.

1. Open the network tab
2. Navigate to a folder with many child objects
3. Reload Open MCT
4. In the network tab observe that instead of many requests to individual object endpoints (Eg. `/b540f7d7-175d-4f65-bf93-cd6ee5c11d9e`) there are one or more requests to the `_all_docs` endpoint.
5. Inspecting the request(s) to the `_all_docs` endpoint should reveal that it contains keys for multiple domain objects.

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 04/22/2021

**Comment by davetsay** [comment]
verified
