### ISSUE TITLE
"Import as JSON" dialog is not intuitive

### ISSUE THREAD

**Issue by merose** [nasa/openmct#3761]
When using the "Import from JSON" option, you are shown this dialog:

<img width="1342" alt="image" src="https://user-images.githubusercontent.com/1649381/111924895-ded79d80-8a63-11eb-96fe-865848f6a591.png">

You are supposed to click on "* Select a File" to bring up a file selection dialog. However, that neither looks like a button nor a hyperlink, nor does it look like a form field. It would be obvious what you're supposed to do if there were an obvious field for the file name and an obvious button next to it like "Select file" or something.

Other things:

- "All fields marked * are required". The "*" does not match the styling in the form fields. If it has a color in the form fields, should have the same color in the help message.
- A lot of whitespace between field labels and the fields they label.
- Poor use of whitespace. Huge dialog using only a small fraction of the space (with a very tiny font).
- "OK" button is tiny. (This may be true throughout OpenMCT, not sure.) Maybe pad it a little so it's not so small a target?
- Once a file is selected, its name is shown truncated, even for a fairly short file name:

<img width="1342" alt="image" src="https://user-images.githubusercontent.com/1649381/111924987-31b15500-8a64-11eb-89a3-26aef2402037.png">

(I can see having a bunch of JSON files with some sort of common prefix and not being able to tell which one you just selected.)

**Comment by akhenry** [comment]
@merose Thanks for reporting this. All of these points are valid. Our forms are auto-generated and the "one size fits all" approach sometimes doesn't produce great results. They're also Angular 1.x based and long overdue for a replacement.

@charlesh88 Is there anything we can do in the short term to make this form a little easier to use? We shouldn't spend a ton of time on it because ultimately we need to re-implement our forms, but the import/export as JSON functionality is pretty commonly used.

**Comment by charlesh88** [comment]
Thanks for this @merose. I've been wanting to fix this for a while, but as @akhenry says the one-size-fits-all approach is the core problem. The big thing here is that the link needs to be a button - that's definitely the worst problem here. Is this something we could add to current form gen in the short-term?

The asterisk in the header hint text _used_ to be colored the same, but that was lost a while ago and needs to be fixed. 
Longer term, we should introduce a new, smaller dialog size that would make really spare dialogs like this feel better spatially.

**Comment by akhenry** [comment]
@nikhilmandlik  Can you help @charlesh88 with his form generation question here? We need to change the "select file" link to a button.

**Comment by nikhilmandlik** [comment]
> @nikhilmandlik Can you help @charlesh88 with his form generation question here? We need to change the "select file" link to a button.

created PR: https://github.com/nasa/openmct/pull/3763

**Comment by charlesh88** [comment]
### Testing Notes
1. Context-click any folder and choose "Import from JSON...".
2. Ensure the Import dialog for looks like this (changed elements called out with arrows):
![Screen Shot 2021-03-29 at 2 12 19 PM](https://user-images.githubusercontent.com/1056412/112901301-6c853f80-9099-11eb-8b31-ab206ea59c57.png)
3. Create a new Plan object from the Create menu.
4. Ensure the dialog for looks like this (changed elements called out with arrows):
![Screen Shot 2021-03-29 at 2 18 14 PM](https://user-images.githubusercontent.com/1056412/112901495-b2da9e80-9099-11eb-8d5c-c6008eeb4141.png)

**Comment by charlesh88** [comment]
Verified fixed Testathon 3/29/21.

**Comment by shefalijoshi** [comment]
Verified fixed.

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 03/29/2021

**Comment by tiffanyatruong** [comment]
verified fixed - testathon 3/29/2021
