### ISSUE TITLE
Unable to access openmct on server

### ISSUE THREAD

**Issue by RailgunBreaker** [nasa/openmct#3764]
I installed openmct and would like to use it on my server, but it started on my server's localhost, how can I change it from localhost to my server?

**Comment by KenethSandoval** [comment]
Hello, you could simply change the host variable found in the "app.js" file and put your server address.

**Comment by akhenry** [comment]
@KenethSandoval Thanks!

Just a note that the provided `app.js` is just intended for development purposes, which is why it's bound to `localhost`. It's not intended as a production server at all. If you're opening Open MCT up to a network I'd strongly recommend using an industry standard http server like Apache, NGINX, etc.

**Comment by jvigliotta** [comment]
FYI

For building, you can check out these docs: https://github.com/nasa/openmct/blob/master/API.md#building-applications-with-open-mct
A little further in that document, you can see the built file being used: https://github.com/nasa/openmct/blob/master/API.md#starting-an-open-mct-application

Also, here's an example that uses Open MCT as a dependency: https://github.com/deeptailor/openmct-as-a-dependency/blob/master/src/index.js

**Comment by RailgunBreaker** [comment]
> @KenethSandoval Thanks! This will work.
> 
> Just a note though that the provided `app.js` is just intended for development purposes, which is why it's bound to `localhost`. If you're opening Open MCT up to a network I'd strongly recommend using an industry standard http server like Apache, NGINX, etc.

Actually now I'm using the LAMP environment, but I'm a beginner of apache and the README.md only gives the way to install&start locally, so I'm a little bit confused how to start-up with Apache. (I failed starting openmct after I change localhost to my server's ip address)

**Comment by unlikelyzero** [comment]
Filing this as enhancement to provide an example apache config

**Comment by unlikelyzero** [comment]
Closing to track here https://github.com/nasa/openmct/issues/5812
