### ISSUE TITLE
Plan objects need icons and description

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3771]
Plan objects are missing icons and a description in the Create menu, and icons in folder views.
![Screen Shot 2021-03-29 at 2 26 46 PM](https://user-images.githubusercontent.com/1056412/112902499-11544c80-909b-11eb-8b57-aac54e286102.png)
![Screen Shot 2021-03-29 at 2 26 32 PM](https://user-images.githubusercontent.com/1056412/112902509-144f3d00-909b-11eb-863b-57c18fd55d49.png)

**Comment by jvigliotta** [comment]
@charlesh88 or @shefalijoshi do we have a description for plans? There's a WIP PR for this, just waiting on the description.

**Comment by akhenry** [comment]
This is fixed. Somewhere.
