### ISSUE TITLE
Look ahead in the time strip view by 50% of the time end bounds

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#3772]
The timestrip view should show 50% of time range ahead of the time end bounds
Also, only show this in real-time mode only in both time strip and plan views.

**Comment by akhenry** [comment]
Let's apply this only in real-time mode, not fixed mode in both the plan and timestrip views.

**Comment by shefalijoshi** [comment]
This feature is no longer required as the independent time control for plans is now available. Closing
