### ISSUE TITLE
Imagery click on left/right arrow not working

### ISSUE THREAD

**Issue by nikhilmandlik** [nasa/openmct#3779]
### Testing instructions:
1. create or use existing Example Imagery
2. adjust browser window width such as both arrows are on main image (see image below)
3. now try to click on arrows to change image.

### Expected Result:
left/right arrow click does should change main image
### Actual Result:
left/right arrow click does not change main image

### Screenshots:

<img width="693" alt="Screen Shot 2021-03-31 at 3 13 24 PM" src="https://user-images.githubusercontent.com/1292612/113218169-ec471180-9233-11eb-9df4-971d6a8130bd.png">

**Comment by jvigliotta** [comment]
@nikhilmandlik is this still an issue or was this fixed?

**Comment by nikhilmandlik** [comment]
@jvigliotta working as expected, lets test this in testathon

**Comment by charlesh88** [comment]
Verified fixed Testathon 12-13-21.

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by kobe1104** [comment]
Verified fixed - testathon 12/13/2021
