### ISSUE TITLE
Vue plots legend does not update when inspector options are changed

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#3780]
Open a timestrip view and add an overlay plot to it
Click on the overlay plot and edit the timestrip
In the inspector view, show/hide some legend columns when expanded
Expected: the toggled columns should show/hide in the legend immediately
Observed: A refresh is required for the columns to show/hide

There might be similar issues with other parts of the legend not immediately updating when options for it are changed

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 06/02/2021
