### ISSUE TITLE
[Plots] Support pause / play

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3782]
We should have a simple gesture to pause and resume plots while in realtime mode. Initially a status bar gesture implemented as an action should work just fine.

The new gestures (for pause, and play) should integrate cleanly with the existing gestures for zooming and panning in plots, which also cause the plot to enter a paused state.

**Comment by shefalijoshi** [comment]
Testing instructions:

> Create an overlay or stacked plot
> Add telemetry endpoints to the plot
> In Local Clock mode, a pause button should be visible in the plot action buttons bar
> Press the pause button
A warning should be shown (via orange border and icon) and the pause button should be hidden and the play button should now be visible.
> Press the play button
The plot should resume in sync with the time conductor.

**Comment by jvigliotta** [comment]
Looks like there is a bug, when pausing a SWG or a State Generator and pausing in a stacked plot, I still see data coming in and being shown in the UI.

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by charlesh88** [comment]
Verified NOT fixed: works properly in TC Local UTC mode but is also manifesting in FIxed Mode, which is not correct.

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 06/02/2021
