### ISSUE TITLE
[Conductor] Add duration to time conductor history.

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3783]
The current time conductor history entries are difficult to parse. Adding duration might give the user something that can be comprehend quicker than just the start and end bounds.

**Comment by jvigliotta** [comment]
## Testing
- change timespans in fixed time mode
- open history in time conductor
- make sure that the timespans make sense and include a duration if utc based time system

**Comment by nikhilmandlik** [comment]
Verified Fixed.
