### ISSUE TITLE
Initial support for multi-user notebooks

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3784]
Currently notebooks do not reflect changes made by other users while the notebook is open. Notebook operations (eg. adding and removing entries) are quite atomic and a good next candidate to support real-time synchronization of objects (where the backend supports it).

Although most of the operations are atomic, we are persisting the entire Notebook object each time, so there is at least one edge case here that will result in a persistence conflict. I think we could ignore initially just to get something working for users:
* If two users submit a change at exactly same time it will cause a persistence conflict. Whichever request is serviced first will cause the notebook model in the second outstanding request to go stale. We need to address this problem generally across all of our objects, but I think it's ok initially if we defer solving this until later.

**Comment by akhenry** [comment]
Should build on the changes made in https://github.com/nasa/openmct/pull/3674 to support automatic Couch DB object synchronization.

**Comment by akhenry** [comment]
Testing notes:

This change involves some refactoring of the Notebook codebase, so general regression testing should be performed in addition to the steps below.

The instructions below assume that the user is using Couch DB as the persistence store. LocalStorage won't work.

1. Open the same notebook in Chrome and Firefox
2. Do each of the following steps in one browser, and confirm that the change is reflected in the other browser within a few seconds:
    1. Add a new section to the notebook
    2. Rename the previously added section
    2. Add a new page to the new section
    3. Renamed the previously added page
    4. Add a new entry to the new page in one browser and enter some text
    5. Modify the text of the previously created entry
3. Navigate between different sections and pages of the notebook and confirm that the notebook in the other browser does not change. During development it was observed that navigating to another notebook page or section in one browser would also navigate in the other browser.
4. Confirm that editing an entry in one browser causes that notebook, section, and page to become the default in that browser. The default notebook, section, and page in the other browser should remain unchanged.

**Comment by jvigliotta** [comment]
Verified - Testathon: 6/22/21

**Comment by charlesh88** [comment]
Verified Testathon 06-22-21 - AMAZING WORK!!!

**Comment by nikhilmandlik** [comment]
Verified Fixed. Good Job @akhenry  👍

**Comment by unlikelyzero** [comment]
Retest cross-links
