### ISSUE TITLE
Re-implement Create and EditProperties actions and dialogs in new API

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3787]
We are still using the old actions, dialogs, and forms APIs for the [Create](https://github.com/nasa/openmct/blob/master/platform/commonUI/edit/src/creation/CreateAction.js) and [Properties](https://github.com/nasa/openmct/blob/master/platform/commonUI/edit/src/actions/PropertiesAction.js) actions. We need to re-implement these two actions using the new Actions and Overlays APIs respectively, as well as adding some new API for registering form controls.

This requires re-implementing [our legacy form-generation code](https://github.com/nasa/openmct/blob/master/platform/forms/res/templates/form.html#L28), which is currently implemented in Angular. This took the properties of an object and auto-generated a form based on them, which was rendered into the popup dialog that shows when the user initiates the Create or Properties actions. 

Additionally, developers can provide optional metadata about **how** each property should be rendered in a form by referencing a `control`, and providing some control-specific options when an object type is registered. This metadata, if provided, is used to render the appropriate form controls for each object property

Here are [some](https://github.com/nasa/openmct/blob/cf3566742bbb64ae930f6a68f6590a4b8bde2a14/src/plugins/tabs/plugin.js) [examples](https://github.com/nasa/openmct/blob/cf3566742bbb64ae930f6a68f6590a4b8bde2a14/example/generator/plugin.js#L69) of types that provide additional form rendering metadata about their properties.

Although our new Types API supports this form control metadata when types are registered, the controls themselves [are defined in Angular JS](https://github.com/nasa/openmct/blob/master/platform/forms/bundle.js#L100). We will need to re-implement all of the form controls as Vue components. 

We will also need some new API to allow developers (including us) to register form controls. This could be something like:
```JavaScript
openmct.forms.addControl('colorPicker', {
    show(element) {
        // A render function
    },
    destroy() {
        // A destroy function
    }
});
```

It will probably also need events for when values change, etc.

**Comment by unlikelyzero** [comment]
Assigning to @unlikelyzero to expand the testing notes

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon 1/24/22
