### ISSUE TITLE
Items not being removed from Telemetry Tables (Element Pool and Tree)

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#3789]
Removing an item from a Telemetry Table either from the Element Pool in edit mode OR from the tree when the telemetry table is expanded, will NOT remove the item. You can navigate away or refresh and the item has been removed.

Tracked down to an error (caught with only try/catch) in RemoveAction.js:
https://github.com/nasa/openmct/blob/cf2b8b3c8ab439db08ec8968146214f9defdf3db/src/plugins/remove/RemoveAction.js#L89

that led to FilterView.vue: https://github.com/nasa/openmct/blob/cf2b8b3c8ab439db08ec8968146214f9defdf3db/src/plugins/filters/components/FiltersView.vue#L162

![Screen Shot 2021-04-05 at 6 14 04 PM](https://user-images.githubusercontent.com/12013460/113644954-c908d180-963a-11eb-9ea0-ad7af03fd08b.png)

This DOES NOT seem to affect any similar functionality in Plots or LadTable, etc...

**Comment by davetsay** [comment]
@shefalijoshi , here is the issue for your Element pool removal fix

**Comment by shefalijoshi** [comment]
This is the order of events:
1. composition item is removed
2. domainObject's composition is updated
3. 'remove' event is emitted on the composition
4. The 'remove' event for the composition is handled by different inspector views which in turn update the domain object
5. The domain object is updated with the **OLD composition**
6. * event is emitted on the domainObject for the composition removal
4. * event is handled on the domainObject for the original composition item removal

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 04/22/2021

Removed from both tree and elements pool and both were removed and updated.

**Comment by nikhilmandlik** [comment]
Error: Attempted to destroy non-mutable domain object

try on this object:
https://hulk.ndc.nasa.gov/testathon/#/browse/mine/8254e102-6d77-4d33-b3b1-98cc05cde9e8/cff24160-ac04-4b53-ac85-614a0ffb26c6?tc.mode=local&tc.startDelta=1800000&tc.endDelta=60000&tc.timeSystem=utc&view=layout.view

Steps:
1. open and edit Locked Display Layout
2. try to delete `hazcam_rear_image_url` element from element pool.

<img width="1895" alt="Screen Shot 2021-04-22 at 2 17 49 PM" src="https://user-images.githubusercontent.com/1292612/115786409-a0d8dc80-a375-11eb-8ee7-d4e83d0dba93.png">

**Comment by jvigliotta** [comment]
Testathon - 4/23/2021 Found another error when replicating @nikhilmandlik 's steps above.

![Screen Shot 2021-04-23 at 2 28 20 PM](https://user-images.githubusercontent.com/12013460/115931665-60926080-a440-11eb-8130-cdfbc6fc4760.png)

**Comment by davetsay** [comment]
verified

**Comment by nikhilmandlik** [comment]
Verified Fixed.
