### ISSUE TITLE
how to update dictionary.json and restart spacecraft.js in realtime for changing parameters in realtime

### ISSUE THREAD

**Issue by Vaibhav2121** [nasa/openmct#3790]
Dear Software desginers

I have an issue with this software, presently as shown in telemetry integration example parameters definition is defined in dictionary.json file. Suppose there are 1000 parameters and 10 users of software. Each user wants to monitor different parameters which he can change in realtime. How to modify dictionary.json and restart spacecraft.js in realtime to acquire new parameters in real time.

**Comment by DusterTheFirst** [comment]
The example application has the telemetry vvalues hard-coded as an example. If you want to setup dynamic telemetry parameters, you can modify the node.js server code to accomidate that. This project is not a drop in application, but provides many APIs for a programmer to integrate it however they please. The code that you write will be specific to your application, but you can build off of the tutorial code, replacing the JSON file with something else that can be dynamically updated.

**Comment by DusterTheFirst** [comment]
This may be better suited as a discussion topic: https://github.com/nasa/openmct/discussions/categories/community-q-a

**Comment by jvigliotta** [comment]
@Vaibhav2121 @DusterTheFirst I'll move this over to discussions for any further... discussion.
