### ISSUE TITLE
[Notebook] Search 'no results' text not updating with new search term

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#3795]
when you type part of a search term and a notebook page/section has a hit but not an entry, the entry shows boilerplate "no result" text with the search term. If you update the search term, the boilerplate doesn't update. It should.

**Comment by jvigliotta** [comment]
## Testing
- type part of a search term that will have hits in page or section name, but not entry
- type a bit more and make sure the "no results" boilerplate entry text updates accordingly

**Comment by nikhilmandlik** [comment]
Verified Fixed.
