### ISSUE TITLE
[Mobile] Hover menu

### ISSUE THREAD

**Issue by shivamndave** [nasa/openmct#38]
Hover info menu is only reached after an item is pressed on,
then after a delay the menu pops up. And it is only closed if
another tree menu is pressed.

**Comment by VWoeltjen** [comment]
To clarify, is this the info bubble (with "Title" and "ID" fields) or the context menu ("Open in new tab", "Remove") that appears?

**Comment by VWoeltjen** [comment]
Disregard previous comment, after another look at #37 (which refers to context menu) I realize that this does indeed refer to the info bubble

**Comment by larkin** [comment]
tagging as mobile issue and closing as we don't currently plan on spending cycles on this. 

I also think this might have been fixed.
