### ISSUE TITLE
[Test] failed using the latest source code (commit 1b579990595b6db9cf84a270437043bc3c0caede)

### ISSUE THREAD

**Issue by mariuszr** [nasa/openmct#3804]
After pulling down the latest source code and running the test - the test failed.  

<img width="1636" alt="Screen Shot 2021-04-12 at 4 10 35 PM" src="https://user-images.githubusercontent.com/4381303/114408604-e04f3e00-9ba9-11eb-8309-0866f637c74c.png">

**Comment by jvigliotta** [comment]
Thank you @mariuszr we're aware and tracking this currently here: #3657 

I'm going to close this issue so we don't have duplicates.
