### ISSUE TITLE
[Testathon 12-07-15] Improved required field handling.

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#382]
Observed: The Start datetime fields of the Create Timeline overlay pre-populate with 0's (a valid value), but the form row displays a yellow asterisk as though the current values are incorrect. Even though the form appears to be in error, the user is still able to click the Ok button and proceed. A similar problem was observed when creating an Activity within a Timeline.

Expected: the fields should be pre-popped with 0's and should have a green check mark next to the inputs. Alternately, fields should not be pre-popped, and have the yellow asterisk. **Victor**, do we currently have options for either path?

**Comment by charlesh88** [comment]
![screenshot-chacskaylo - google chrome](https://cloud.githubusercontent.com/assets/1056412/11643921/2194b5dc-9cfc-11e5-892a-89d28ac3826b.png)
![screenshot-t1 - google chrome](https://cloud.githubusercontent.com/assets/1056412/11643922/2194f1dc-9cfc-11e5-80e2-33bd8f510a41.png)

**Comment by VWoeltjen** [comment]
There's two issues here, either one of which would resolve the behavior:

1. The date-time input is (incorrectly) providing its own default value of 0 when none is provided. Instead, it should just leave those fields empty.
2. Forms marked as required should be marked as valid if they contain valid values (regardless of whether there is user input)

Both of these should be reasonably simple fixes.

Option 2 leaves me with some UX questions, as changing form behavior generally could have broader consequences: 

* Is the yellow asterisk meant to communicate an error state, or that the field is required?
  * Currently it's the latter - it appears whenever a field is required, regardless of whether or not it has a default value.
  * Practical example: If a user clears input from a required text field, should an asterisk or a red X appear?
* Do the green check & red x represent user feedback, or do they reflect the state of the data in the form?
  * Currently, they're user feedback - they only appear after the user has touched a form.
  * Practical example: Should a green check appear for default values that are valid but not required?

Regardless of the above, one nice thing to do for Option 2 would be to provide just CSS classes to reflect the current state, and control display with CSS.

Currently, classes get applied with the following logic in an `ng-class`:

```
req: row.required
valid: mctFormInner.$dirty && mctFormInner.$valid
invalid: mctFormInner.$dirty && !mctFormInner.$valid
```

This is a little funny insofar as there are multiple overlapping states; in some cases, CSS decides how to reconcile this, while in other cases it's the code in the template. (e.g. CSS decides that a required form with invalid input should get a red X, but the template code decides to only show a red X after there's been user input.) 

Would be simpler to flatten the classes provided and let CSS decide how to present:

```
req: row.required
dirty: mctFormInner.$dirty
valid: mctFormInner.$valid
```

Then, CSS could decide if `.req:not(.dirty)` displays differently from `.req.dirty`, and so on

**Comment by charlesh88** [comment]
Seen during Testathon 20160209. Reassigning to myself to review, add comments and determine where to go from here.

**Comment by charlesh88** [comment]
We have to strike a balance between messaging current state and live feedback to the user as they interact. I put together [this matrix](https://docs.google.com/spreadsheets/d/1vwsQLwCtA31ueTOX6EXdCqm9bksgi6O6eTwkGYJAgqY/edit#gid=1032451486) to exercise the permutations:

<img width="841" alt="screen shot 2016-06-02 at 1 41 37 pm" src="https://cloud.githubusercontent.com/assets/1056412/15760814/dab9f262-28c9-11e6-9771-95221379605d.png">

I wanted to drive through the user interaction cycle of a field and look for patterns: before user is able to interact, while they're interacting, and when they're "done". Some conclusions from this exercise:

#### General
* Asterisk is meant to denote a required field that is incomplete.
* The green check is meant to denote a field (required or optional) that is complete and has a valid value, whether the field was pre-popped by default or with a previous user entry. See comments on this below.
* The red X is meant to denote a field (required or optional) that is complete and has an invalid value.
* Ok/Submit button is not enabled until all fields have a valid value.

#### Required Fields
* "Blank" values in required fields should be evaluated differently depending on where we are in the interaction cycle:
 * Before the user interacts: incomplete, but the user hasn't touched it yet, use asterisk.
 * While the user interacts: the user blanks out a previously valid value. In this case, they're getting ready to enter a valid value, so treat as incomplete: use asterisk.
 * The user is "done" interacting: see that user touched the field, but left it blank. In this case, use the red X. The field is be clearly flagged as an error in need of correction.
 * Required fields that are pre-populated with defaults should behave the same as if the user had pre-populated them: they get a green check mark. This shifts the question from "should we show an asterisk or a check mark for pre-popped required fields?" to "should we pre-pop this required field?" which is really the right question to be asking.
 * Low-stakes required fields can be pre-populated. We treat newly created object names like this now.
 * High-stakes required fields should never be pre-populated - the user must always enter a value. I don't think we actually have any of these yet.

#### Optional Fields
 * For optional fields, when the system has genned a default value that is meaningful to the user, it should be pre-populated into the field. For example, there is a default snapping grid applied to layouts, but when the dialog for that object is presented to the user, those fields are blank currently.


So, hopefully this simplifies things. Required fields left blank or null will not allow the Ok/Submit button to be enabled. Required fields pre-popped with a default are identical to those where a user had previously entered a value. Invalid entries always display with a red X. Don't pre-populate high-stakes required fields. Always pre-pop optional field values where the system creates a meaningful default for them. 

@VWoeltjen @larkin @akhenry Please have a look, poke holes, etc.

**Comment by VWoeltjen** [comment]
Want to look at this in Orwell primarily from an API perspective; may restrict work to the `api-tutorials` branch (#999) to try out different approaches there first.

**Comment by larkin** [comment]
For prior design, check out https://github.com/thedersen/backbone.validation

Lots of notes around validation lifecycle and how to hook it for clean view rendering.

**Comment by VWoeltjen** [comment]
Per tagup 12/20/2016, deferring this for now; form handling is a larger question, and needs to align with style guide. Moving out of Sagan.

**Comment by larkin** [comment]
Happy to close as part of #1623.
