### ISSUE TITLE
Icon button labels are being clipped

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3822]
Icon buttons that have a text label are being clipped, sometimes hiding the characters descenders. Look at the bottom of the "g" (text changed to illustrate the effect):

![Screen Shot 2021-04-20 at 2 39 26 PM](https://user-images.githubusercontent.com/1056412/115467698-c7b4d880-a1e6-11eb-9065-5b07d3bd4cd2.png)

Adding `padding: 1px 0` to the label fixes the problem:

![Screen Shot 2021-04-20 at 2 39 59 PM](https://user-images.githubusercontent.com/1056412/115467749-d8fde500-a1e6-11eb-866e-0378d91d4435.png)

**Comment by imrishabh18** [comment]
@charlesh88 Is this issue been fixed? Or I can do it if not done yet 😃

**Comment by jvigliotta** [comment]
@charlesh88 thoughts?

**Comment by ozyx** [comment]
# Testing Instructions
1. In chrome devtools, edit the label text of an icon button to include characters with descenders (such as what's been done above, Snapshot -> Snagshot)
2. Verify that the descenders are not cutoff

**Comment by michaelrogers** [comment]
Fix verified locally during testathon 2022-01-24.

**Comment by rukmini-bose** [comment]
Testathon Verified 1/24/2023

**Comment by jvigliotta** [comment]
![Screen Shot 2023-01-24 at 3 09 57 PM](https://user-images.githubusercontent.com/12013460/214441612-0c290b34-77de-482a-b1c6-bdd64ea5f4c6.png)
Verified Fixed: Testathon - 1/23/23

**Comment by charlesh88** [comment]
Verified fixed Testathon 2023-01-24.
