### ISSUE TITLE
Handle deletion of objects (or avoid returning orphans in searches)

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#3823]
That's a great point. We have the same issue with our ElasticSearch plugin (which also supports server-side search).

I can't think of a reliable and performant way of handling this without an exhaustive tree traversal. I think the answer is to stop producing orphans at all by redesigning deletion, but even that is fraught with challenges. 

The way our object links work right now there is no easy way that I can think of to know whether an object is an orphan without an exhaustive tree traversal to see whether any other objects reference it.

Can we defer solving this problem to a followup issue?

_Originally posted by @akhenry in https://github.com/nasa/openmct/pull/3798#discussion_r617054882_

**Comment by shefalijoshi** [comment]
This should remain open, it has not been solved.

**Comment by akhenry** [comment]
So, one approach to this that has occurred to me recently is to treat the case where an _original_ object is deleted as a special case. If the user deletes an original object we mark it deleted via an object attribute. Deleting a link to an object would do nothing but remove that particular link.

Objects that are marked `deleted` could be filtered out of search results, the tree, etc. Or they could be styled differently. Or both, based on context or application setting. This would give users the opportunity to retrieve previously deleted objects, if so desired.

**Comment by akhenry** [comment]
The absence of a `location` property might be a sufficient proxy for "deletion" as well, with the advantage of being backwards-compatible.

**Comment by scottbell** [comment]
@akhenry I have [a PR](https://github.com/nasa/openmct/pull/5599/files#diff-7b3a993b89a077474a9a4cf7fca79c18131e8e222951d164d2848ab147afbd24R634) that uses the `originalPath` to determine if the object is orphaned. When the object is deleted, the `root` object is also removed from its path. This appears to work for both LocalStorage & CouchDB. It's a pretty cheap operation, but it's not clear if it works in all situations (e.g., VISTA? @davetsay question)

**Comment by scottbell** [comment]
@akhenry I should note the `originalPath` and `location` approaches are pretty close. In fact, that's all the [getOriginalPath function is doing](https://github.com/nasa/openmct/blob/master/src/api/objects/ObjectAPI.js#L626) when constructing the path. We do have to recursively check our parents' locations in the case that a folder containing a domain object is deleted. The domain object is orphaned from the `root`, but its `location` will still be listed as the folder we just deleted.

**Comment by ozyx** [comment]
Verified Fixed 8/4/22 Testathon

Orphaned objects no longer show up in search results.

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon 8/4/22
