### ISSUE TITLE
Remove "follow timer" action and indicator

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3824]
The ["Follow Timer" action](https://github.com/nasa/openmct/blob/master/platform/features/clock/src/actions/FollowTimerAction.js) and [indicator](https://github.com/nasa/openmct/blob/master/platform/features/clock/src/indicators/FollowIndicator.js) are leftovers from our legacy timeline view which has been deprecated for some time. These should be completely removed from our codebase, as they imply functionality that no longer exists.

This action and indicator are implemented in our legacy codebase, so you'll need to be sure to [remove](https://github.com/nasa/openmct/blob/master/platform/features/clock/bundle.js#L147) [them](https://github.com/nasa/openmct/blob/master/platform/features/clock/bundle.js#L302) from their relevant bundle as well.

**Comment by jvigliotta** [comment]
Hi @aimanafzal, if you haven't already, please follow the steps here https://github.com/nasa/openmct/discussions/3821. We'll need this completed before you can contribute to the codebase. Thanks!

**Comment by aimanafzal** [comment]
Thanks @jvigliotta 
Just signed a copy of the agreement and sent it to the email address mentioned in the document.

**Comment by akhenry** [comment]
Testing Instructions
1. Verify that the "Follow Timer" action is no longer available from the context menu for timer objects <img src="https://user-images.githubusercontent.com/4215777/120049702-a9a17b80-bfcf-11eb-8931-442fe464f991.png" width="200">
2. Verify that the follow timer indicator is no longer visible in the status bar.
![Screen Shot 2021-05-28 at 4 11 04 PM](https://user-images.githubusercontent.com/4215777/120049716-b02ff300-bfcf-11eb-8cbf-3d460d687800.png)

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 06/02/2021

**Comment by davetsay** [comment]
verified

**Comment by charlesh88** [comment]
Verified fixed Testathon 6/2/2021
