### ISSUE TITLE
Reimplement New Tab action in vanilla JS

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3834]
The [New Tab action](https://github.com/nasa/openmct/blob/master/platform/commonUI/browse/src/windowing/NewTabAction.js) is currently implemented in AngularJS, and in our legacy API and should be reimplemented in vanilla JavaScript using [the actions API](https://github.com/nasa/openmct/blob/master/src/api/actions/ActionsAPI.js).

**Comment by mariuszr** [comment]
Hi @akhenry, Do we also want to reimplement the [UrlService](https://github.com/nasa/openmct/blob/master/platform/commonUI/general/src/services/UrlService.js) to generate the URL, or do we want to manage the URL for `Open in a new browser tab` as it is implemented on [the Layout view](https://github.com/nasa/openmct/blob/master/src/ui/layout/Layout.vue#L213)?

**Comment by mariuszr** [comment]
Hi @kobe1104, Thank you for the information that gives me a new insight into the action ("NewTabAction"), using the UrlService which is related to opening a new tab based on the domainObject, and the action implemented on the Layout view that opens a new tab based on the current URL.

**Comment by akhenry** [comment]
@kobe1104  Needs some testing instructions. Thanks!

**Comment by kobe1104** [comment]
### Testing
1. Right click on a domain object and select `Open In New Tab`.
2. Verify that the domain object is open in a new window with the correct URL params.

**Comment by nikhilmandlik** [comment]
Verified Fixed.
