### ISSUE TITLE
Reimplement Link Action in vanilla JS

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3835]
The [Link Action](https://github.com/nasa/openmct/blob/master/platform/entanglement/src/actions/LinkAction.js) is currently implemented in AngularJS, and should be re-implemented in vanilla JavaScript. It should not make use of any legacy API, and should instead use our [Composition](https://github.com/nasa/openmct/blob/master/src/api/composition/CompositionAPI.js) and [Mutation ](https://github.com/nasa/openmct/blob/master/src/api/objects/ObjectAPI.js#L365) APIs.

**Comment by jvigliotta** [comment]
## Testing

- right click and object in the tree and select "Create Link"
- try to add it to it's original parent or itself or another folder it's already linked it, verify you cannot
- select an appropriate object to link it into
- verify you can link it there and that it's showing as an alias
