### ISSUE TITLE
[Navigation Tree] Revert/Refactor

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#3841]
We need to combine the new tree refactor with the old tree design.

Key elements to include from both:
- virtual scroll: only load the amount of tree items (plus a buffer) that will fit on screen (reducing DOM nodes, increasing performance)
- target: locate/scroll to the currently viewed (object view) item in the navigation tree
- ability to expand multiple sibling tree items at one time

## Testing
- can open multiple sibling items in the navigation tree at one time (children as well)
- can target (jump to item in nav tree) for any item (however far nested)
- tree only has a minimal amount of nodes open at a time (roughly enough to fill the tree container (plus a buffer), use DOM inspector to verify
- can collapse all tree items using new collapse button (next to sync)
- can search
- clicking an item, navigates you to the item
- reflects items removed from composition using tree context menu and using elements pool in edit mode (display layouts, plots, etc)
- remembers open folders on refresh

**Comment by davetsay** [comment]
thanks for marking `unverified` @unlikelyzero

**Comment by nikhilmandlik** [comment]
Verified Fixed. Looking good, Good Job @jvigliotta  👍

**Comment by charlesh88** [comment]
Verified NOT fixed, seeing some erroneous behavior:
- [ ] This is occurring when an object without a valid parent has been used as a sync target in the tree:
- Clicking the sync tree button wasn't working;
- After scrolling the tree and then mouse up, the tree would scroll itself back up;

![Tree refactor rubber band scrolling](https://user-images.githubusercontent.com/1056412/120530537-788bc700-c392-11eb-9232-1d77f4c97467.gif)
