### ISSUE TITLE
Disallow panning and zooming plots in time strip view

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#3847]
In time strip view plots should not pan and zoom since they're supposed to align to the time systems at all times.

**Comment by shefalijoshi** [comment]
Testing instructions:
Create an overlay plot
Ensure that pan/zoom/pause/play controls work fine.
Create a time strip object
Add the overlay plot to a time strip view
Pan/Zoom/Pause/Play controls should be hidden.

**Comment by davetsay** [comment]
verified

**Comment by nikhilmandlik** [comment]
on hover, I can see pause button and once paused can see sync button.

**Comment by unlikelyzero** [comment]
@shefalijoshi to take on the pause issues

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 6/25/2021

**Comment by kobe1104** [comment]
Verified fixed testathon 6/25/2021.

**Comment by charlesh88** [comment]
Verified fixed Testathon 06-25-21

**Comment by unlikelyzero** [comment]
Closing with a secondary issue filed
