### ISSUE TITLE
"Ok" is not OK

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3849]
"OK" should be normalized as all caps in dialogs across the app.

### Testing Notes
Invoke a variety of modal dialogs across the app, such as removing an object, and verify that the "OK" button displays that text in all caps.

**Comment by charlesh88** [comment]
Verified NOT fixed Testathon 6/2/2021: "Ok" is still displaying in the Snapshot remove dialog as mixed case.

![image](https://user-images.githubusercontent.com/1056412/120527374-1ed5cd80-c38f-11eb-9c07-789e096d5ea8.png)

**Comment by davetsay** [comment]
Instance of **Ok** not OK also in remove entry in Notebook.
![image](https://user-images.githubusercontent.com/3614296/120529869-bc320100-c391-11eb-8c01-77624e6648ce.png)

Using code search I see instances in `removeDialog.js`, `Notebook.vue` and `ImportAsJSONAction.js`
