### ISSUE TITLE
Stacked plot legends are getting clipped when the plot is small

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3858]
Legends in stacked plots are getting clipped when the stacked plot is compressed vertically: 

![Screen Shot 2021-05-04 at 10 44 45 AM](https://user-images.githubusercontent.com/1056412/117046929-1e7de000-acc6-11eb-8c59-1a73df91a98e.png)

This is the case regardless of the legend being collapsed or expanded. The `c-plot-legend` elements should use `flex: 0 0 auto` to fix this.

**Comment by charlesh88** [comment]
Verified fixed Testathon 2023-02-02.

**Comment by ozyx** [comment]
Verified fixed Testathon 2023-02-02

**Comment by rukmini-bose** [comment]
Verified TEstathon 3/20/2024. The legends scroll and lay on top of the plot when expanded. yay

**Comment by charlesh88** [comment]
Testathon 2024-03-20 cannot repro, fixed.
