### ISSUE TITLE
For a new setup, My Items folder doesn't exist 

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#3861]
Create a new CouchDB database for Open MCT
Spin up Open MCT and point it to the CouchDB instance
When Open MCT starts you see an error in the console and the My Items folder doesn't show.

**Comment by charlesh88** [comment]
Verified fixed (?) on banner: My Items folder was present.

**Comment by nikhilmandlik** [comment]
> Verified fixed (?) Testathon 05-10-21 on banner: My Items folder was present.

Yes, it only happens first time when 'My items' is empty.
Adding steps for reproduction to clarify this issue.

**Comment by nikhilmandlik** [comment]
Observed another issue,

Steps:
1. make sure 'My Items' folder is empty and couchdb (is empty) does not have 'mine' document
2. create any new object eg: create -> clock -> ok
3. creates new object
4. on creation of this object out of 2 PUT requests 1 fails and 1 success.
5. Create another object. (do not refresh browser)
6. now it is stuck on 'Saving'.
7. refresh browser (object is not created).
8. Once we refresh browser, everything works as expected.

**Comment by akhenry** [comment]
Verified fixed, but did observe same behavior as @nikhilmandlik https://github.com/nasa/openmct/issues/3861#issuecomment-837267962

**Comment by akhenry** [comment]
Also verified 100% fixed for local storage
