### ISSUE TITLE
[Persistence API] Progress modal should be dismissed on persistence error

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#3867]
## Overview
On create object, if there is a persistence error, the Saving modal never gets dismissed and user is forced to refresh app to regain control.

## Expected Behavior
Persistence errors should be handled gracefully. Notification given to user. User stays calm and carries on.

## Steps to Reproduce
1. Create an object and get a persistence error (ie. simultaneous create in shared environment)
2. That's it you're stuck

<img width="1361" alt="Test" src="https://user-images.githubusercontent.com/3614296/117727793-580a8b80-b19d-11eb-9402-82595897876c.png">

**Comment by shefalijoshi** [comment]
The issue here is that the pending flag does not get set to false when a couchDB update results in a conflict error.
This PR should fix the issue: https://github.com/nasa/openmct/pull/3751
