### ISSUE TITLE
LAD Table Sets not working

### ISSUE THREAD

**Issue by AdamElliott-AB** [nasa/openmct#3869]
We see the following error in 1.6.2 and v1.7.1 when attempting to view any LAD Table Set. Individual LAD Tables included in the set work fine when viewed separately.
TypeError: Cannot read property 'slice' of undefined
    at s.data (LADRow.vue:69)
    at vue.min.js:6
    at vue.min.js:6
    at ve (vue.min.js:6)
    at s.e._init (vue.min.js:6)
    at new s (vue.min.js:6)
    at Qe (vue.min.js:6)
    at init (vue.min.js:6)
    at a (vue.min.js:6)
    at s (vue.min.js:6)

**Comment by akhenry** [comment]
@AdamElliott-AB  Thanks for reporting. We'll look into this and try and get a fix into 1.7.2.

**Comment by akhenry** [comment]
@AdamElliott-AB This is fixed in Master. It will also be in the 1.7.2 release, which we will cut at the end of the week.

Thanks for reporting it.

**Comment by AdamElliott-AB** [comment]
Fantastic! Thank you for the quick turnaround

**Comment by davetsay** [comment]
verified

**Comment by tiffanyatruong** [comment]
verified fixed - testathon 5/14/21
