### ISSUE TITLE
The Couch DB adapter should use a Shared Worker for the _changes feed

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3880]
The number of simultaneous HTTP connections is [limited to six connections per **browser and domain**](https://developer.mozilla.org/en-US/docs/Web/API/EventSource), ie. not per-tab. The Couch DB adapter is currently holding open an HTTP connection, using up one connection, and reducing the number of available connections for everything else to five. 

To make matters worse, opening a second tab will hold open a second connection, and so on. Six tabs will use up all available connections to the domain, and hold them open, blocking any other requests.

HTTP/2 would help in this situation, but it is not a good general solution.

A reasonable general solution is to use a dedicated Shared Worker for the _changes feed, which all of the tabs can connect to and receive change events from. This will still reduce our connection pool to five simultaneous connections, but unless Couch DB decide to use WebSockets for the _changes feed I don't see that we have much choice here.

The use of shared workers will mean that the changes feed will not be supported in Safari [until they reinstate support for Shared Workers](https://bugs.webkit.org/show_bug.cgi?id=149850).

**Comment by akhenry** [comment]
Should consider implementing Server Side Events at the same time - https://github.com/nasa/openmct/issues/3881

**Comment by shefalijoshi** [comment]
I've  noticed that when running on a local machine, Open MCT cannot be opened in more than 5 tabs even when LocalStorage is being used (instead of CouchDB) because of how webpack works.
We need a different solution for this.

The SharedWorker solution for the changes feed is a good performance improvement regardless of the tabs issue.

**Comment by shefalijoshi** [comment]
Testing instructions:
_On Firefox, Chrome_ - Start Open MCT in multiple tabs In each tab you should not see any network requests with this in the URL: "_changes?feed=continuous&style=main_only&heartbeat=50000&filter=_selector"
View the same plan or notebook in each tab.
Change the plan or notebook and ensure that all the views are updated.

_On Safari_ - Start Open MCT in multiple tabs In each tab you **should** see network requests with this in the URL: "_changes?feed=continuous&style=main_only&heartbeat=50000&filter=_selector" for each tab

**Comment by jvigliotta** [comment]
Verified - Testathon - 8/5/2021

**Comment by akhenry** [comment]
Verified fixed
