### ISSUE TITLE
Use Server-Sent Events in the Couch DB adapter

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3881]
Server Sent Events [provide a cleaner interface](https://docs.couchdb.org/en/stable/api/database/changes.html#changes-eventsource) for receiving change events from the Couch Server than handling chunked HTTP responses.

**Comment by scottbell** [comment]
Though I've resolved the issue of saving objects to CouchDB through @shefalijoshi's fix, it looks like the synchronization is still broken. For example, creating an object of `SYNCHRONIZED_OBJECT_TYPES` (like a notebook) causes the shared worker to engage, but then immediately fails:
`Editor.js?3ce0:82 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'cancel')
    at eval (Editor.js?3ce0:82)
    at new Promise (<anonymous>)
    at Editor.cancel (Editor.js?3ce0:80)
    at onCancel (CreateAction.js?95e8:71)
    at processQueue (angular.js?21b1:18075)
    at eval (angular.js?21b1:18123)
    at Scope.$digest (angular.js?21b1:19242)
    at eval (angular.js?21b1:19562)
    at TaskTracker.completeTask (angular.js?21b1:21403)
    at eval (angular.js?21b1:6879)`
This is because the active transaction is null:
`const transaction = this.openmct.objects.getActiveTransaction();
            transaction.cancel()`
which causes the `cancel` invocation to crash. I'll investigate

**Comment by scottbell** [comment]
This appears to be a timing issue. This:
https://github.com/nasa/openmct/blob/master/src/api/Editor.js#L69
Is being called before this:
https://github.com/nasa/openmct/blob/master/src/api/Editor.js#L81
It's not clear to me why we're invoking cancel in the first place though.

**Comment by scottbell** [comment]
I think the cancel is happening because the `SaveAsAction` is failing due to:
```
TypeError: Cannot read properties of undefined (reading 'filter')
    at eval (CouchObjectProvider.js?a10c:373)
    at EventEmitter.eval (ObjectAPI.js?4467:495)
    at EventEmitter.emit (index.js?ba10:115)
    at MutableDomainObject.$destroy (MutableDomainObject.js?3566:123)
    at ObjectAPI.destroyMutable (ObjectAPI.js?4467:286)
    at ObjectAPI.__webpack_exports__.default.openmct.objects.save (monkeyPatchObjectAPIForNotebooks.js?87fc:23)
    at async Promise.all (:8080/index 0)
```

**Comment by scottbell** [comment]
Still looks like an interplay between transactions and what the persistence plugin is expecting. In `SaveAsAction`, we call `persist`:
https://github.com/nasa/openmct/blob/master/platform/commonUI/edit/src/actions/SaveAsAction.js#L136
which invokes a patch that destroys the mutable object:
https://github.com/nasa/openmct/blob/master/src/plugins/notebook/monkeyPatchObjectAPIForNotebooks.js#L23
which in turn calls `unobserve` for the first time:
https://github.com/nasa/openmct/blob/master/src/plugins/persistence/couch/CouchObjectProvider.js#L373
`this.observers[keyString] = this.observers[keyString].filter(observer => observer !== callback);`
which replaces the `this.observers[keyString]` with null if `observer === callback`

Later, the transaction is committed, and this call save, which invokes the patch a second time that destroys the mutable object:
https://github.com/nasa/openmct/blob/master/src/plugins/notebook/monkeyPatchObjectAPIForNotebooks.js#L23
which signals again to the `CouchObjectProvider` to `unobserve`, but the observers are already null, and thus the raised exception.

**Comment by scottbell** [comment]
Adding a null check seems to fix it:
```
return () => {
            if (this.observers[keyString]) {
                this.observers[keyString] = this.observers[keyString].filter(observer => observer !== callback);
                if (this.observers[keyString].length === 0) {
                    delete this.observers[keyString];
                    if (Object.keys(this.observers).length === 0 && this.isObservingObjectChanges()) {
                        this.stopObservingObjectChanges();
                    }
                }
            }
        };
```
@akhenry @shefalijoshi I'm a bit lost on the observer interaction, but would the above be ok?

**Comment by scottbell** [comment]
Split the Notebook Object issue to:
https://github.com/nasa/openmct/issues/4422

**Comment by scottbell** [comment]
A PR for this issue has been opened here:
https://github.com/nasa/openmct/pull/4427

**Comment by charlesh88** [comment]
Testathon 12-13-21 - no testing notes.

**Comment by khalidadil** [comment]
@scottbell Is there a good way to test this?

**Comment by unlikelyzero** [comment]
@scottbell to update with testing instructions

**Comment by scottbell** [comment]
To test, ensure persisting objects with CouchDB still works as it did previously. Open multiple tabs and ensure persistence still works as well (to engage shared worker). Also try out Safari on iOS to test functionality without shared workers.

**Comment by unlikelyzero** [comment]
### Testing Notes
Each of the following must be performed with Safari and also with Chrome (not at the same time).
1. Open multiple tabs and verify that notebook entries are modified between users. Without Refresh.
2. Modify the name of a clock object and verify that change will take effect on other tabs. With Refresh.

**Comment by khalidadil** [comment]
I'm seeing an issue where opening notebook another tab results in the user not being able to create an entry on the second tab.

Steps to reproduce:
1. Open a notebook in tab 1. Create an entry. The entry should be created successfully.
2. Open the same notebook in tab 2 in the same browser. Create an entry. The entry input appears, but then the entry disappears.

**Comment by shefalijoshi** [comment]
Tried to modify a notebook entry in different *tabs* and the entries did *not* update.
Note that modifying the notebook entry in different browser *windows* works fine.

**Comment by scottbell** [comment]
Post https://github.com/nasa/openmct/issues/4469 being merged, it looks like it's working in 1.8.3 (at least on my local install):

https://user-images.githubusercontent.com/9853862/148540793-7f53c176-3e4e-4e90-9526-9ee8c3d02fe5.mov

**Comment by unlikelyzero** [comment]
Re-opening. There are some scenarios which are not working and need additional debugging.

**Comment by akhenry** [comment]
Closed in favor of https://github.com/nasa/openmct/issues/4737. After investigation it has been determined that notebook issues are unrelated to Server Sent Events.
