### ISSUE TITLE
Show plot limit lines for telemetry

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#3884]
Show plot limit lines for any limit levels provided for telemetry - there may be low, high limits for each limit level.
Allow showing/hiding limit lines for telemetry using configuration in the inspector
Limit line labels should be shown when hovering on that telemetry endpoint in the plot legend.

**Comment by shefalijoshi** [comment]
Reopening as this is not ready on openmct-yamcs

**Comment by shefalijoshi** [comment]
Closing as this is merged. See #3914 as well.

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by charlesh88** [comment]
Verified fixed Testathon 06-22-2021
