### ISSUE TITLE
[Edit Mode] should not allow navigation while in edit mode

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#3891]
## Overview
In edit mode, it is possible to navigate away from the currently selected object, losing any edits, and switching view to new object in edit mode.

## Expected Behavior
Should not navigate away from selected object. Should not exit edit mode.

## Steps to Reproduce
1. Select an object and go into edit mode
2. Select a folder object with children
3. Select a child object of the folder from the large grid view
4. Close large view
5. Observe still in edit mode but displaying selected child object

![edit mode navigation](https://user-images.githubusercontent.com/3614296/119706823-4bc63580-be0f-11eb-88fc-4d97c5372ce1.gif)

**Comment by charlesh88** [comment]
### Testing Notes
1. Navigate to a Folder that has one or more children.
1. Verify that child folders are clickable and navigate as expected. 
1. Use the view switcher to flip to List View. 
1. Verify that child list items are clickable. 
1. Create a new Overlay Plot or Display Layout.
1. From the edit screen, click on any folder item in the tree that has one or more children.
1. The grid view of that folder should appear in a large overlay. 
1. Verify that child folders are _not_ clickable. 
1. Verify that the view switcher and More Options (3 dot) menu function as expected. Note that "Add new folder" will be an option in that menu - this isn't optimal, but it doesn't break anything.

![Screen Shot 2021-05-27 at 3 19 44 PM](https://user-images.githubusercontent.com/1056412/119905596-709ad580-bf01-11eb-81c2-abe71adc1dae.png)

10. Use the view switcher to flip to List View. 
1. Verify that child list items are _not_ clickable. 
1. Verify that that the view switcher and More Options menus function as expected, as well as the table view's headers that perform sorting. 

![Screen Shot 2021-05-27 at 3 19 56 PM](https://user-images.githubusercontent.com/1056412/119905622-7abcd400-bf01-11eb-9259-9bde5b6054b5.png)

**Comment by shefalijoshi** [comment]
Verified fixed.

**Comment by davetsay** [comment]
verified

**Comment by tiffanyatruong** [comment]
verified fixed
