### ISSUE TITLE
"Pausing" Imagery telemetry in Fixed Time mode shows alert styling, but shouldn't

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3898]
When the Time Conductor is in real-time mode, when the user pauses the view by clicking the Pause button or clicking a thumbnail view we show an alert orange border and coloring to indicate that the view will no longer be automatically updated to show new incoming imagery:

![Screen Shot 2021-05-27 at 10 34 03 AM](https://user-images.githubusercontent.com/1056412/119872194-0d487d80-bed8-11eb-818b-40e8f91c18b8.png)

This is correct and expected. 
However, the same styling is being applied when the Time Conductor is in Fixed Time mode:

![Screen Shot 2021-05-27 at 10 22 49 AM](https://user-images.githubusercontent.com/1056412/119872181-09b4f680-bed8-11eb-9833-90996d801689.png)

This doesn't make sense: the intent of the model is that Fixed Time utilizes bounded start and end datetimes and there is _no_ expectation that the latest data will be displayed. Showing the alert styling when pausing in this mode promotes a false expectation that the user _will_ see the latest data if they unpause the view.

The Imagery view in Fixed Time mode should be changed as follows:
- Do not display the Pause button.
- Clicking a thumbnail shouldn't "pause" the view, and therefore no alert styling should ever be displayed.
- If the Time Conductor is in real-time mode, and the user pauses the view and _then_ switches to Fixed Time mode, the currently selected thumbnail should still be selected but the Pause button should be hidden and the alert styling should not be displayed.

**Comment by nikhilmandlik** [comment]
Verified Fixed.
