### ISSUE TITLE
[Build] Upgrade Webpack version to 5

### ISSUE THREAD

**Issue by nikhilmandlik** [nasa/openmct#3899]
### Description:
To support  modern ES6 features need to upgrade webpack from ver4 to ver5

### Testing instructions:
1.  Deploy on banner and verify successful deployment.
2. Try following commands on local openmct and all should work without fail
    `npm start`                         (open localhost:8080 and verify)
    `npm run lint`
    `npm run lint:fix`
    `npm run build:prod`
    `npm run build:dev`
    `npm run build:watch`
    `npm test`
    `npm run test:debug`
    `npm run test:coverage`
    `npm run test:watch`
3. Test all dependent projects.
       - [ ] VISTA
       - [ ] VIPER
       - [ ] NIRVSS

**Comment by unlikelyzero** [comment]
@nikhilmandlik I've added a backlog task to investigate the use of peerDependencies. I think we should use this issue to determine if they would have prevented the webpack config issues we faced in sprint 1.7.3.

**Comment by evenstensberg** [comment]
I'm here to help if you need help

**Comment by unlikelyzero** [comment]
### Testing Instructions

Try following commands on local openmct and all should work without fail

- [ ] npm start (open localhost:8080 and verify)
- [ ] npm run lint
- [ ] npm run lint:fix
- [ ] npm run build:prod
- [ ] npm run build:dev
- [ ] npm run build:watch
- [ ] npm test
- [ ] npm run test:debug
- [ ] npm run test:coverage
- [ ] npm run test:watch

Test all dependent projects.
- [ ] VISTA
- [ ] VIPER
- [ ] NIRVSS

**Comment by michaelrogers** [comment]
Try following commands on local openmct and all should work without fail

- [x] npm start (open localhost:8080 and verify)
- [x] npm run lint
- [x] npm run lint:fix
- [x] npm run build:prod
- [x] npm run build:dev
- [x] npm run build:watch
- [x] npm test
- [] npm run test:debug
- [ ] npm run test:coverage
- [ ] npm run test:watch



`npm run test`
Fails on: 
1) can render an element to a blob
     The Image Exporter basic instatation
     Error: Timeout - Async function did not complete within 5000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)
    at <Jasmine>


`npm run test:debug`
Fails on: 
1) when installed, adds "My Items" to the root
     the plugin with no arguments passed in
     Error: Expected 'Fancy Items' to be 'My Items'.
    at <Jasmine>
    at UserContext.eval (webpack-internal:///./src/plugins/myItems/pluginSpec.js:64:34)

**Comment by unlikelyzero** [comment]
Note: John to investigate the failing test statements on Michael's machine
