### ISSUE TITLE
Fix UI "typos"

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3909]
Fix various "typos" in the UI:
- [x] Snapshots erroneous character:
![Screen Shot 2021-06-02 at 10 51 03 AM](https://user-images.githubusercontent.com/1056412/120528747-a708a280-c390-11eb-9eb0-45a849c44625.png)
- [x] Snapshot annotation interface layout is whacked, and...
- [x] Snapshot dialog template has bad spacing between icon and name, and...
- [x] Snapshot annotation interface Cancel and Save buttons are the reverse of what they should be:
![image](https://user-images.githubusercontent.com/1056412/123338943-826e9900-d4fe-11eb-937c-4ce8c51aa8c2.png)
- [x] Double icon in Display Layouts Inspector:
![Screen Shot 2021-06-02 at 10 51 08 AM](https://user-images.githubusercontent.com/1056412/120528768-aa9c2980-c390-11eb-8c31-d4706d91a728.png)
- [x] Stop menu item doesn't indent properly:
![Screen Shot 2021-06-02 at 11 08 04 AM](https://user-images.githubusercontent.com/1056412/120530983-f4860f00-c392-11eb-940d-6b0f3114e945.png)
- [x] Tree items need margin right:
<img width="284" alt="Screen Shot 2021-06-02 at 11 26 14 AM" src="https://user-images.githubusercontent.com/1056412/120533347-7e36dc00-c395-11eb-84bb-582ad33a29ad.png">

- [x] Time Conductor RT input looks visually blown out in Snow theme; probably a filter setting.
![Screen Shot 2021-06-07 at 11 41 27 AM](https://user-images.githubusercontent.com/1056412/121071904-655b6b80-c785-11eb-90dc-69c7a8229935.png)

**Comment by charlesh88** [comment]
### Testing Notes
1. Expand the Notebook Snapshots container, and take a new snapshot and save to 'Notebook Snapshots' if you don't have any Snapshots currently. Verify that the header element look similar to this: 
![image](https://user-images.githubusercontent.com/1056412/121097309-a44ee880-c7a8-11eb-9d6e-17d6adfb2ac2.png)
1. Edit or create a Display Layout. Add a drawing object (box, line, or text field) and click it to select. Verify that the Inspector title looks like the element indicated by the orange arrow: 
![Screen Shot 2021-06-07 at 3 59 06 PM](https://user-images.githubusercontent.com/1056412/121097821-78803280-c7a9-11eb-8c4d-0f461fef6866.png)

**Comment by charlesh88** [comment]
Verified fixed Testathon 07-12-21. Issue seen with Painterro custom checkboxes, new issue to be filed.

**Comment by davetsay** [comment]
verified...

but ran into unreplicatable snapshot bug #4012

**Comment by nikhilmandlik** [comment]
Verified Fixed. other than font issue @charlesh88  mentioned above.
