### ISSUE TITLE
Unable to view plots - getLimits error

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#3911]
TypeError: t.getLimits is not a function
    getLimits openmct.js:85175
    limitDefinition openmct.js:85164
    initialize openmct.js:99712
    A openmct.js:99565
    d openmct.js:99678
    addTelemetryObject openmct.js:100191
    initialize openmct.js:100169
    A openmct.js:99565
    h openmct.js:93096

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 06/02/2021
