### ISSUE TITLE
[1.7.3] Closed folders still listening to composition

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#3918]
## Testing
- open a folder, close a folder
- then add something TO that folder (anything)
- make sure it doesn't show underneath the closed folder
- find a headless item (somehow)
- have it in the object view
- try to sync to the item, (with many items open so scrolling would have to take place, even though it's not in the tree)
- make sure it doesn't try to keep scrolling

**Comment by shefalijoshi** [comment]
Verified fixed
