### ISSUE TITLE
Refreshing always results Local Clock mode

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#3921]
1. Load Open MCT and change the time conductor to Fix Timespan.
2. Refresh the browser
Expected: The time conductor should still be in Fixed Timespan mode.
Actual: The time conductor is in Local Clock mode again.

**Comment by unlikelyzero** [comment]
@shefalijoshi is this a regression? Did this used to work?

**Comment by unlikelyzero** [comment]
@nikhilmandlik this is likely related to the back button fix

**Comment by akhenry** [comment]
Verified fixed

**Comment by shefalijoshi** [comment]
Verified fixed

**Comment by charlesh88** [comment]
Verified fixed Testathon 07-12-21

**Comment by nikhilmandlik** [comment]
Verified Fixed.
