### ISSUE TITLE
Tree Classic height calculation needs to handle Snapshot container expansion and collapse

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3929]
The tree scroll area is not handling the Snapshot area being expanded and collapsed in its vertical space calculation, but should.

### Steps to replicate
1. Close the Snapshots container via its Status Area icon, if expanded. 
2. Expand the tree and/or resize the browser window such that the tree has a vertical scroll, like this: 
![Screen Shot 2021-06-07 at 3 57 56 PM](https://user-images.githubusercontent.com/1056412/121098051-e9bfe580-c7a9-11eb-828c-08315531e88c.png)
3. Expand the Snapshots container, then observe that the tree clips items at the bottom of the scrolling area, and the scroll height hasn't been recalculated. It's now not possible to scroll any farther to get to the clipped items: 
![Screen Shot 2021-06-07 at 3 58 10 PM](https://user-images.githubusercontent.com/1056412/121098194-33103500-c7aa-11eb-901a-0531088615f6.png)
1. With the Snapshots container visible, resize the browser window a bit, which forces the tree scrolling area height to be recalculated. The clipped items will now be scrollable to. 
2. Now, close the Snapshots container and observe: the tree height doesn't recalculate and is now too short: 
![Screen Shot 2021-06-07 at 3 57 10 PM](https://user-images.githubusercontent.com/1056412/121098473-c6e20100-c7aa-11eb-87d4-4d63b1f92ee0.png)

**Comment by unlikelyzero** [comment]
@nikhilmandlik to retest
