### ISSUE TITLE
Clocks and Timers don't apply and persist Style settings properly

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3930]
Set styles in Display Layout. In this example the text color is set to a red; should be applied to all text but is only affecting the non-dynamic text:
![Screen Shot 2021-06-08 at 11 09 37 AM](https://user-images.githubusercontent.com/1056412/121235904-34913a00-c84a-11eb-8d04-e1424697577b.png)

Save, nav away and back.
![Screen Shot 2021-06-08 at 11 09 59 AM](https://user-images.githubusercontent.com/1056412/121235913-36f39400-c84a-11eb-80ae-26cc4b061dfe.png)

Clock settings are persisted, but Timers don't retain anything.

**Comment by skylinew** [comment]
Do you have steps to reproduce?

**Comment by charlesh88** [comment]
Verified fixed Testathon 06-15-22.

**Comment by rukmini-bose** [comment]
Verified Testathon 06-15-22

**Comment by unlikelyzero** [comment]
@unlikelyzero to finish the test.

A lot of scaffolding was required to get to this point in a testsuite
