### ISSUE TITLE
Add initial automated Lighthouse testing to CI

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#3939]
https://github.com/GoogleChrome/lighthouse-ci automates the configuration, collection and assertions for Google Chrome's lighthouse tool. 

This means our team can:
1. Keep track of performance audit change over time to track regressions
2. Ensure that the parent projects which source Open MCT are also performant or following best practices

Initial Implementation:
The lighthouse CI project provides guidance on how to get started with automated lighthouse ci checks [here](https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/getting-started.md#overview)

- In our first implementation, this is designed to be run ad-hoc as the tool is hardened as a Github Workflows
- 'warn' instead of 'error' on most assertions
- Set examples of how to warn or error on given thresholds
- Only collect best-practices and performance measurements and assert against them

Further iteration:
- Determine how to load test data to execute against different contexts like plot performance
- Run more than ad-hoc. This can be configured to be nightly, per merge, or even block commits
- Custom Performance Marks
- Generalize config so that this can run on all parent projects like https://github.com/akhenry/openmct-yamcs
- Set up internal lighthouse CI sever to run and compare previous releases to project how the performance has improved over time

**Comment by unlikelyzero** [comment]
Testing Notes: 

Run Github Action Workflow on 'master'
Run Github Action Workflow on random branch

**Comment by unlikelyzero** [comment]
Re-opening to fix in https://github.com/nasa/openmct/pull/3957

**Comment by shefalijoshi** [comment]
Verified - Action runs
