### ISSUE TITLE
Move action dialog is correct for one object type

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3940]
Moving an object (in this case an Overlay Plot, but happens for any object type) displays the following dialog:
![Screen Shot 2021-06-14 at 2 55 07 PM](https://user-images.githubusercontent.com/1056412/121964787-e9cb6280-cd20-11eb-8f71-89a3deebd868.png)

The name field is always labeled "Folder Name", and while this works great when moving a Folder, it's not so good for everything else. Also, "location" should be capitalized. 

Finally, cancelling the move always throws this console error:

![image](https://user-images.githubusercontent.com/1056412/121965130-6f4f1280-cd21-11eb-9585-67cf9b89dc9c.png)

**Comment by charlesh88** [comment]
- [x] Fix labels
- [ ] Fix 'cancel' console error

**Comment by charlesh88** [comment]
### Testing Notes
1. Context-click any object in the tree and select "Move" from its menu.
2. Verify in the following dialog that the name is NOT labeled "Folder Name" and that "Location" is capitalized.
3. Cancel the Move action by clicking the Cancel button in the dialog, and verify in the browser console that an error was not thrown.

**Comment by akhenry** [comment]
Looks like the cancel error is because the Move Action [only has happy path handling](https://github.com/nasa/openmct/blame/6483fe24029375dd6c7c7180b11ad75264128394/src/plugins/move/MoveAction.js#L40). It does not appear to handle the case where the user cancels.

**Comment by kobe1104** [comment]
Verified fix on testathon 6/22.

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by charlesh88** [comment]
Verified fixed Testathon 06-22-2021
