### ISSUE TITLE
Plan View/Timestrip not responding to Time Conductor bounds changes

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3943]
### Reproduce
1. Go to a Plan View (like [this one](https://banner.ndc.nasa.gov/stable/#/browse/mine/cd333b91-e464-4bf8-9847-8b419e1425d2/12c0e46c-0295-4bfa-9e8e-1afb1dbb0313/cfc5dad1-3916-4451-9739-7d7e405df135/7eee64a5-14e7-4e52-bfb5-9ba0878496b0?tc.mode=local&tc.timeSystem=utc&view=plan.view&tc.startDelta=1800000&tc.endDelta=60000)) with the Time Conductor in RT mode. If the plan doesn't have dates within the current time bounds, you should see something that looks like this:
![Screen Shot 2021-06-14 at 4 28 03 PM](https://user-images.githubusercontent.com/1056412/121971703-38cbc480-cd2e-11eb-938b-e73cc83e7f77.png)
1. Change the TC to Fixed Time Mode and enter a start and end that encompass the plan's extents. If using the plan linked in this issue, set the End to 2024-03-22 07:00:00.000Z and then the Start to 2023-12-21 12:00:00.000Z. Tabbing out of either TC input should have refreshed the plan view, but it doesn't.
2. Now, resize the browser window or resize a pane in Open MCT. Observe: the plan will now refresh and be displayed properly:
![image](https://user-images.githubusercontent.com/1056412/121972008-f0f96d00-cd2e-11eb-96b3-f4975611f451.png)

### Notes
- When the Plan view is in a Display Layout, pane and browser window resize events don't force an update, presumably because the size of the plan container hasn't been affected.
- This problem also occurs when interacting with the TC's History menu. 
- When making changes to the time bounds in the TC, this console error is being thrown:

![image](https://user-images.githubusercontent.com/1056412/121972233-6a915b00-cd2f-11eb-9f7c-307da45870eb.png)

**Comment by shefalijoshi** [comment]
Testing instructions:
Create a conditionset with at least one condition other than default
Use the conditionset to create a condition widget and add it into a display layout
Change the time conductor bounds and make sure there are no console errors

Go to a plan and change the time conductor bounds again. Ensure there are no console errors.

**Comment by jvigliotta** [comment]
Verified with Plans
Verified with condition set widget layouts ; )
