### ISSUE TITLE
Tree doesn't update after renaming during Duplicate action

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3944]
### Reproduce
1. Select an object and invoke Duplicate from its context menu. 
2. In the following dialog, rename the object. Click Save.
3. Observe: the title in the object's main view is named properly, but in the tree it displays its old name.

![image](https://user-images.githubusercontent.com/1056412/121973068-5c443e80-cd31-11eb-8be6-9cd51ba91fc7.png)

Refreshing will fix the problem.

**Comment by jvigliotta** [comment]
## Testing
- do what Charles said in the issue
- just kidding (kinda)
- duplicate an object on a server using couch for persistence
- make sure the folder you're duping into is open
- change the name of the duplicated object (as you duplicate)
- verify the object shows up in the new folder (or same folder)
- verify the object's name is changed to what you entered in the dialog

**Comment by kobe1104** [comment]
Confirm fix on testathon 6/22.

**Comment by davetsay** [comment]
verified

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by unlikelyzero** [comment]
Re-opening to cover the scenario outlined inhttps://github.com/nasa/openmct/issues/3944#issuecomment-866380314

**Comment by jvigliotta** [comment]
## Updated Testing notes
- cancel instead of choosing a location for duplication, verify no errors in console

**Comment by charlesh88** [comment]
Verified fixed Testathon 06-25-21
