### ISSUE TITLE
[Styles] no js-style-receiver class in object view results in console error

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#3949]
## Overview
If `.js-style-receiver` is not present in an object view, a console error emitted. This is probably common with external plugins.

## Expected Behavior
Views should not be required to have an element with a `.js-style-receiver` class.

## Steps to Reproduce
1. In production environment ensure views are displayed and no console errors appear.
2. In development environment can remove `.js-style=receiver` in plugin template and ensure view is displayed and no console errors appear.

**Comment by kobe1104** [comment]
Verified testathon 6/22/21.

**Comment by unlikelyzero** [comment]
Note: Re-open if this error appears again in the future
