### ISSUE TITLE
Make node support explicit

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#3952]
There have been a few instances in the past year where node support was not explicit and required some intervention. It's also possible that openmct is not currently capable on running on node16 and we should figure out how we want to explicitly test these versions.
We'd want to update the package.json with 
`"engines": {    "node": "&gt;=10.0.0"  },`
at least

NASA deployments are installing Open MCT system dependencies for us. We should make our node support explicit and tested in CI -- especially as we start to integrate with other NASA Systems

Related Issues

- https://github.com/nasa/openmct/issues/3758#issuecomment-803225237
- https://github.com/nasa/openmct/issues/3746#issuecomment-809480340
- https://github.com/nasa/openmct/issues/3681
- https://github.com/nasa/openmct/issues/3966

Testing Notes
- Install nvm and set node version to 16+
- Attempt to install openmct and see it fail
- Install node version 8
- Attempt to install openmct and see it fail
- Install node version 10-15
- Openmct installs correctly

**Comment by akhenry** [comment]
Not fixed. At least it doesn't look like it. I installed node 8 and it built just fine with it, no warning at all. Even more surprisingly it then ran just fine as well...

```
$ rm -rf node_modules/
$ node --version
v8.17.0
$ npm install

> fsevents@1.2.13 install /Users/akhenry/Code/openmct/node_modules/watchpack-chokidar2/node_modules/fsevents
> node install.js

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
...etc.
```

Interestingly I **did** get a warning when I tried the same thing with node 16.

**Comment by unlikelyzero** [comment]
Need to retest this now that we've moved off of node10

**Comment by unlikelyzero** [comment]
### Testing Notes
Attempt to install on node 8,10,12,14,16 and verify expected ressults

**Comment by shefalijoshi** [comment]
Verified
