### ISSUE TITLE
Persistence errors when using Conditional Styling

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3954]
We had seen this often on hulk, and now get lots of persistence errors when applying Conditional Styling on banner. This doesn't happen for me running locally:

![image](https://user-images.githubusercontent.com/1056412/122456456-70bb4d80-cf62-11eb-98d2-aa72fb48ed41.png)

### Reproduce
1. Create a Condition Set.
2. Create a Condition Widget.
3. Use the Condition Set to conditionally style the Condition Widget, then save changes.
4. Sporadically, but often, a persistence error will be displayed.

This also seems to occur when navving around in the tree, or viewing a Layout that includes a conditionally styled element.

**Comment by akhenry** [comment]
Verified Fixed.

**Comment by charlesh88** [comment]
Not fixed, Testathon 07-12-21 - still seeing persistence errors: https://banner.ndc.nasa.gov/testathon/#/browse/mine/a5e28f1a-4a53-4f0e-bfe4-6205e3d0de4f/d825d32c-abf9-4d9a-b172-2b357e1ffb16/5a1e5f93-81ae-4ff8-80ea-ad97f2f686cf/ca7b071b-c0e1-42be-8d06-67b4dc6bf98b?tc.mode=local&tc.startDelta=1200000&tc.endDelta=15000&tc.timeSystem=utc&view=flexible-layout&pageId=0bb32a05-5190-4e46-b9c6-2789c84ad491&sectionId=b68712d3-1e97-4bd8-85be-94409e612f22

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by unlikelyzero** [comment]
We have retested this on 1.7.5, if these areas appear again, please reopen
