### ISSUE TITLE
[Object Tree] context menu won't go away

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#3956]
## Overview
Context menu for an object in the tree does not go away when clicking outside of context menu.

## Expected Behavior
Clicking anywhere outside of menu should close/hide menu

## Steps to Reproduce
1. Context click on an object in tree
2. Navigate to other objects in tree and observe context menu is still visible
3. Select other objects in tree and observe context menu is still visible

**Comment by akhenry** [comment]
@davetsay Unable to repro. This still an issue in latest master?

**Comment by davetsay** [comment]
@akhenry , turns out clicking on missing items in the tree was not de-selecting the context menu. That's probably okay so I'll close.
