### ISSUE TITLE
Navigating sporadically throws Couch errors

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3964]
Sporadically seen on banner/testathon Open MCT 1.7.4. 

1. Navigate to a plan view 
2. You will see CouchObjectProvider errors in the console if the problem is happening.
3. Navigate to any element inside Shared Items.
4. Observe: more errors are thrown, and the main view remains as the plan, the view's title and available actions change:
![Screen Shot 2021-06-22 at 4 11 20 PM](https://user-images.githubusercontent.com/1056412/123011100-a7cf9b80-d374-11eb-84d6-084c36a797de.png)

Once the error occurs, clicking other objects within Shared Items will continue to throw the error. Clicking anything above Shared Items will not manifest the problem.

**Comment by akhenry** [comment]
Testing notes:
1. Navigate to a plan or a notebook within a folder.
2. In the tree, close the parent folder of the navigated object
3. Navigate to another object outside of the closed folder
4. Navigation should be successful, and you should not be "stuck" in the previously navigated object.

note:
In the JavaScript console you _may_ observe a message along the lines of `DOMException: The user aborted a request`. If this does still occur it should be benign and can be addressed in a followup.

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 6/25/2021

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by davetsay** [comment]
verified

**Comment by nikhilmandlik** [comment]
Verified Fixed. No couch related errors.
