### ISSUE TITLE
[Build] Add support for node:16

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#3966]
### Update 01/03/22:

openmct is now failing to install on node16. It hangs after the webpack compilation step.

```
#!/bin/bash -eo pipefail
npm install
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported Th
npm WARN deprecated gulp-header@1.8.12: Removed event-stream from gulp-header
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
m##################] / reify:rxjs: http fetch GET 200 https://registry.npmjs.ors@<
> openmct@1.8.3-SNAPSHOT prepare
> npm run build:prod


> openmct@1.8.3-SNAPSHOT build:prod
> cross-env webpack --config webpack.prod.js

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  openmct.js (3.55 MiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  openmct (3.55 MiB)
      openmct.js


WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

webpack compiled with 3 warnings

Too long with no output (exceeded 10m0s): context deadline exceeded
```
https://app.circleci.com/pipelines/github/nasa/openmct/7852/workflows/b216d5a6-c68d-4df8-bead-f83b0c0f65e4/jobs/23000/parallel-runs/0/steps/0-105

### Investigation
1. It does not appear to be an issue with any other version of node.
2. Updating or removing the npm proxy has no affect.
3. It occurs locally and in CircleCI. Does not resolve after 24 hours.
4. Using the latest npm cli doesn't help

**Comment by akhenry** [comment]
I believe that the underlying issue is that node-sass is deprecated. This will be fixed by https://github.com/nasa/openmct/issues/3997

It does look as though [node-sass have recently added support for Node 16](https://github.com/sass/node-sass/issues/3077), so it may be possible to bump the version number and fix this in the interim.

**Comment by trusktr** [comment]
It's been hanging on me with Node 14 in my Ubuntu VM. I just ctrl+c after I think it is done.

**Comment by trusktr** [comment]
Hmm, I might've been wrong about Node 14, but I'd rather not look back. :D

> node-sass

glad that's out of the way, but unfortunately showing us it's some other issue.

**Comment by akhenry** [comment]
### Testing Instructions
Ensure that Open MCT builds locally without hanging in Node 16 and 17. Previously webpack would hang indefinitely after successfully compiling.

eg.
```
nvm use 16
npm install
```
Verify that that process exits correctly after successfully compiling.

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 03/14/2022. I'm able to install node modules without errors on node v16.9.1
