### ISSUE TITLE
[New Edit Mode] "Move" context menu item from object pool in NEM creates a link, rather than moving the object.

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#397]
1. In an object being edited, select one of the children from the elements pool.
2. Right click, and select move. Select an appropriate location (you may need to create a child that can accept this object first)
3. Save
4. A link to the object is created under the child, and the object being moved stays in its original location.

**Comment by larkin** [comment]
Move no longer an action in new edit mode, fixed.
