### ISSUE TITLE
Use escape key to dismiss dialog real time conductor dialog options

### ISSUE THREAD

**Issue by nikhilmandlik** [nasa/openmct#3977]
### Description:
User should be able to dismiss time conductor options dialog using esc key.

### Testing instructions:
1. change clock to local (realtime)
2. click start time to open options dialog
3. press 'esc'

### Expected Result: 
dialog should dismiss after 'esc' key press

### Actual Result:
dialog does not dismiss after 'esc' key press

### Screenshots:
![Screen Shot 2021-06-25 at 12 35 15 PM](https://user-images.githubusercontent.com/1292612/123476776-ffa71600-d5b1-11eb-8edf-6547c742875a.png)

**Comment by unlikelyzero** [comment]
Verified that the escape key allows the user to dismiss time conductor with and without modification

**Comment by shefalijoshi** [comment]
This works in local clock mode but not in fixed timespan mode for datetime picker. If thats ok then this is verified.

**Comment by davetsay** [comment]
verified

**Comment by unlikelyzero** [comment]
Closing and @davetsay  to file a follow up bug
