### ISSUE TITLE
[Edit Mode] Changing the time format on a clock while in edit mode does not reflect change immediately

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#398]
Affects both New and Old edit modes.

Editing the date format of a clock situated within a layout does not reflect the change immediately. The enclosing layout must be saved in order to show the new clock format.
1. Edit a layout with a clock in it
2. Select the clock from the elements pool, right click, and select "Edit Properties"
3. Change the date format and click OK
4. The date format has not changed.
5. Save the layout
6. The clock now shows the new date format.

**Comment by larkin** [comment]
Fixed, closing.
