### ISSUE TITLE
Implement new "Remote Clock"

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3983]
Right now Open MCT supports a ["local clock"](https://github.com/nasa/openmct/blob/master/src/plugins/utcTimeSystem/LocalClock.js) out of the box for realtime telemetry operations. This clock ticks on a local time source (ie. [a recurring `setTimeout` which just pulls the current time  from `Date.now()`](https://github.com/nasa/openmct/blob/master/src/plugins/utcTimeSystem/LocalClock.js#L69)).

This approach only supports so called "wall clock" time, and does not support simulations or telemetry playback of historical or future time periods.

To support these use cases we need a new clock that ticks in real-time, just like the local clock, but which gets a timing signal from a remote source instead of using `Date.now()`.

The new remote clock plugin should be configurable with a telemetry point from which to receive the time data.

eg.
``` JavaScript
openmct.install(new openmct.plugins.RemoteClock({namespace: 'something', key:'telemetry-key'});
```
On activation the remote clock will
1. Use telemetry metadata to select the appropriate timestamp on the configured telemetry point to fetch time data from (it will be the `domain` field that has the same `key` as the active time system.
2. Request the latest time using a historical query (ie. `openmct.telemetry.request`)
3. Subscribe to the configured telemetry point in order to receive timing signals on an ongoing basis.

When a new telemetry datum is received the Remote Clock will ["tick" with the latest time (as provided by the server) as ms since 01/01/1970](https://github.com/nasa/openmct/blob/master/src/plugins/utcTimeSystem/LocalClock.js#L70) (ie JavaScript time).

Most of the logic in the RemoteClock will be the same as logic in the [LocalClock](https://github.com/nasa/openmct/blob/master/src/plugins/utcTimeSystem/LocalClock.js#L70). The only difference is that instead of a `setTimeout` the tick will be triggered by the telemetry subscription callback. You might consider creating a shared parent class that they both extend.

**Comment by jvigliotta** [comment]
## Testing
- install RemoteClock plugin with an identifier (OR view an already installed one)
- Look in the developer network tab to verify that there is a WS stream emitting time-based telemetry

**Comment by davetsay** [comment]
@akhenry , will this also cover the current clock functionality so that the clock bundle can be replaced by this? Or, is this a new type?

**Comment by akhenry** [comment]
This is a new type of clock, it doesn't replace anything. It's an alternative to the LocalClock.

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by kobe1104** [comment]
Verified fixed. Testathon 8/3/2021
