### ISSUE TITLE
[Edit Mode] Clicking on "Open in New Tab" from context menu in elements pool navigates to the root object

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#399]
Affects New and Old edit mode
1. In edit mode, select an object from the elements pool and right click to show the context menu.
2. Select "Open in New Tab"
3. New tab opens, but navigation goes to the Root Object.

**Comment by akhenry** [comment]
Believe that this is due to suppression of root object in `EditableContextCapability` resulting in an incomplete path being generated by `ContextCapability.getPath()`. In absence of full path, object is not found, and view is routed to default route.

Low priority, refactoring of edit mode will make these sort of wrapped capabilities redundant.

**Comment by VWoeltjen** [comment]
Currently irreproducible, but only because Open in New Tab has been disabled in Edit mode

**Comment by larkin** [comment]
fixed.
