### ISSUE TITLE
Overlay plots do not fetch historical data on zoom or pan

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#3992]
When zooming or panning on an overlay plot, the historical data will flicker briefly before disappearing.

### Replicate
Create an Overlay Plot with enough historical data to exceed the time conductor range
Zoom or Pan out to query for historical data

Expected behavior:
Historical data to appear

Actual behavior:
When zooming or panning on an overlay plot, the historical data will flicker briefly before disappearing.

![Screen Recording 2021-07-02 at 01 24 08 PM](https://user-images.githubusercontent.com/12446869/124325398-5f189f00-db39-11eb-8bb6-e9dec4ca6358.gif)

**Comment by akhenry** [comment]
Verified Fixed

**Comment by nikhilmandlik** [comment]
Verified Fixed.
