### ISSUE TITLE
Replace node-sass with a different library

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#3997]
Node-sass is [deprecated](https://www.npmjs.com/package/node-sass) - replace it with a different library. Maybe try [sass](https://www.npmjs.com/package/sass)
You may have to replace or update the following libraries as well:

- [node-bourbon](https://www.npmjs.com/package/node-bourbon) with [bourbon](https://www.npmjs.com/package/bourbon) during this process.
- [fast-sass-loader](https://www.npmjs.com/package/fast-sass-loader) update to 2.0.0 or greater

**Comment by skrobchik** [comment]
Is there anyone working on this? I'm interested in using the latest LTS version of Node with OpenMCT. Would like to help with this if it's the only issue holding upgrade back.

**Comment by unlikelyzero** [comment]
This has been completed. Spinning out the second task https://github.com/nasa/openmct/issues/5070
