### ISSUE TITLE
[Copy] CopyTask should be refactored to remove low-level manipulation of the model

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#400]
Currently the copy service performs mutation and composition via low level direct manipulation of the object model. This should be refactored to use the mutation and composition capabilities of domain objects.
#377 Has implications for this issue. If this issue is implemented before #377 it will result in additional errors to the console.

**Comment by larkin** [comment]
I believe this is currently safe as implemented, tagging as wontfix.
