### ISSUE TITLE
[Snapshots] Deleting Notebook Snapshots doesn't clear out mct Local Storage

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#4000]
After doing a number of Snapshots, I eventually fill Local Storage and can not take any more Snapshots:

![Screen Shot 2021-07-08 at 4 49 15 PM](https://user-images.githubusercontent.com/1056412/125006320-b4115500-e012-11eb-91ef-2db74e42dde4.png)

When a user deletes Snapshots or adds them into a Notebook they should be removed from Local Storage.

I have no other option than deleting the 'mct' element of Local Storage; this is bad for a number of reasons. If this is an issue that would occur in environments other than localhost, this may be a blocker.

**Comment by akhenry** [comment]
Lucky 4000!

**Comment by nikhilmandlik** [comment]
yup same issue with object deletion API.

**Comment by nikhilmandlik** [comment]
Snapshot container should not store object in couch/mct, but should hold on into local storage till moved into notebook or deleted from Snapshot container.
if moved into notebook persist that object
if deleted from Snapshot container clear it from local storage.

**Comment by akhenry** [comment]
@nikhilmandlik I have created a closely related issue for the namespace problem - https://github.com/nasa/openmct/issues/4007

**Comment by unlikelyzero** [comment]
Please verify that this hasn't already been fixed as a part of #4007

**Comment by nikhilmandlik** [comment]
resolved by PR: https://github.com/nasa/openmct/pull/4020

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon 9/28
