### ISSUE TITLE
Tables should use telemetry formatter for determining bounded telemetry sort order

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4008]
Telemetry Tables always maintain telemetry sorted by timestamp so that date comparisons can be done performantly when telemetry needs to be added to, or removed from the table on bounds changes. Tables will [use the `parse` function of telemetry formatters to convert the wire format of a telemetry value to a number for comparison](https://github.com/nasa/openmct/blob/master/src/plugins/telemetryTable/collections/BoundedTableRowCollection.js#L77). However, currently tables are [using the Time System to determine the formatter to use, instead of telemetry metadata](https://github.com/nasa/openmct/blob/master/src/plugins/telemetryTable/collections/BoundedTableRowCollection.js#L72).

For example, this will result in the `UTCTimeFormat` always being used whenever the UTC time system is active. This will typically work just fine, but it means that we are not benefiting from the significant performance benefits of more optimized  formatters such as the [`ISOTimeFormat`](https://github.com/nasa/openmct/blob/master/src/plugins/ISOTimeFormat/plugin.js) that may be specified in the telemetry metadata.

Instead, telemetry tables should use the correct telemetry-specific formatter for a given row, rather than using the default formatter for the active time system.

**Comment by jvigliotta** [comment]
## Testing
- same as #3639

**Comment by unlikelyzero** [comment]
Fixed and tested as part of https://github.com/nasa/openmct/issues/3639. Table sorting works
