### ISSUE TITLE
Display Layout snapshot issue

### ISSUE THREAD

**Issue by nikhilmandlik** [nasa/openmct#4013]
### Description:
Snapshot images not showing line from 'Display Layout'

### Testing instructions:

1. Create 'Display Layout'
2. Add line to 'Display Layout'
3. Take a snapshot and open it

### Expected Result:
Show line inside a snapshot

### Actual Result:
line missing inside a snapshot

### Screenshots:
![Screen Shot 2021-07-12 at 1 27 14 PM](https://user-images.githubusercontent.com/1292612/125351769-5718e600-e315-11eb-9b30-8ef26c93ebaa.png)

![Screen Shot 2021-07-12 at 1 27 47 PM](https://user-images.githubusercontent.com/1292612/125351771-57b17c80-e315-11eb-81c2-48ea69ad07a9.png)

**Comment by khalidadil** [comment]
@nikhilmandlik Can you please confirm if this is still an issue?

**Comment by khalidadil** [comment]
This is what I see on banner latest

![Screen Shot 2021-09-23 at 12 11 09 PM](https://user-images.githubusercontent.com/2343076/134553109-8efdd21f-d170-4e40-b64b-7eb9e60e94dd.png)

**Comment by khalidadil** [comment]
@nikhilmandlik and I couldn't reproduce this. I added the unverified tag and we should check this in testathon.

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon 9/28
