### ISSUE TITLE
[Painterro] Painterro text input not being removed after annotating Snapshot

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#4019]
Seen on /stable 1.7.5 and current master running locally.

### Reproduce
1. Create a new Snapshot, click it and get to the annotation interface.
2. Add a text element:

![Annotation Open MCT](https://user-images.githubusercontent.com/1056412/125536136-bffc8849-f245-46b7-8369-655cf8c03ef7.png)

3.  Save the annotation and exit the Snapshot overlay dialog. Note at the very bottom of the tree on the left you'll see a pink dotted line:

![image](https://user-images.githubusercontent.com/1056412/125535157-084fae28-8b40-42eb-893c-2404c35da60c.png)

4. Dragging on the browser's bottom edge to Increase the height of the window will reveal the annotation's text element:

![image](https://user-images.githubusercontent.com/1056412/125535232-9eea9aec-3f18-4a2a-834d-775f129b05bc.png)

5. Looking in Dev Tools > Elements, you'll see that contenteditable divs are being left in the DOM:

![Painterro text leftovers](https://user-images.githubusercontent.com/1056412/125535995-bea83504-0f2c-4cee-93b5-c5ab34097148.png)

Multiple rounds of annotation leave multiple contenteditables remaining; refreshing clears them. Although the above screenshot shows a count of two console errors, they aren't being created by this problem.

**Comment by nikhilmandlik** [comment]
created issue for painterro, https://github.com/devforth/painterro/issues/150

**Comment by nikhilmandlik** [comment]
They have fixed this issue in new version v1.2.58

**Comment by unlikelyzero** [comment]
@nikhilmandlik to verify before thursday

**Comment by nikhilmandlik** [comment]
Verified Fixed.
