### ISSUE TITLE
Configurable example imagery

### ISSUE THREAD

**Issue by nikhilmandlik** [nasa/openmct#4026]
### Description:
Add following configurable options for example imagery,

- [x] Images url list (comma separated)
- [x] Image load delay (milliSeconds)

### Testing instructions:
1. create example imagery with name 'default imagery' and leave `Images url list (comma separated)` and `Image load delay (milliSeconds)` field empty
1. create example imagery with name 'custom 1 imagery' and  add  5000 for `Image load delay (milliSeconds)` and some image links from sample list below in `Images url list (comma separated)` 
1. create example imagery with name 'custom 2 imagery' and  add  10000 for `Image load delay (milliSeconds)` and some image links from sample list below in `Images url list (comma separated)`
1. Verify each example imagery object working as expected.
1. now add all three example imagery objects into display layout and each example imagery should work as expected (each has its own correct images from Images url list)

sample image urls:
🟢/images/hazcam_front_left_image_raw_compressed_delayed/hazcam_front_left_image_raw_compressed_delayed_1631774064_56950.jpg,
🟢/images/hazcam_front_left_image_raw_compressed_delayed/hazcam_front_left_image_raw_compressed_delayed_1631774910_3538.jpg,
🟢/images/hazcam_front_left_image_raw_compressed_delayed/hazcam_front_left_image_raw_compressed_delayed_1631775070_47579.jpg,
🟢/images/hazcam_front_left_image_raw_compressed_delayed/hazcam_front_left_image_raw_compressed_delayed_1631812708_44695.jpg,
🟢/images/hazcam_front_left_image_raw_compressed_delayed/hazcam_front_left_image_raw_compressed_delayed_1631812832_29949.jpg,
🟢/images/hazcam_front_left_image_raw_compressed_delayed/hazcam_front_left_image_raw_compressed_delayed_1631813604_23986.jpg,
🟢/images/hazcam_front_left_image_raw_compressed_delayed/hazcam_front_left_image_raw_compressed_delayed_1631813919_63963.jpg,
🟢/images/hazcam_front_left_image_raw_compressed_delayed/hazcam_front_left_image_raw_compressed_delayed_1631814118_50921.jpg,
🟢/images/hazcam_front_left_image_raw_compressed_delayed/hazcam_front_left_image_raw_compressed_delayed_1631815779_48693.jpg,
🟢/images/hazcam_front_left_image_raw_compressed_delayed/hazcam_front_left_image_raw_compressed_delayed_1631876615_14942.jpg,
🟢/images/hazcam_front_left_image_raw_compressed_delayed/hazcam_front_left_image_raw_compressed_delayed_1631878181_40894.jpg,
🟢/images/hazcam_front_left_image_raw_compressed_delayed/hazcam_front_left_image_raw_compressed_delayed_1631878961_7864.jpg,
🟢/images/hazcam_front_left_image_raw_compressed_delayed/hazcam_front_left_image_raw_compressed_delayed_1631987277_589.jpg,
🟢/images/hazcam_front_left_image_raw_compressed_delayed/hazcam_front_left_image_raw_compressed_delayed_1631987432_16711.jpg

**Comment by unlikelyzero** [comment]
Re-opening to address in Target:1.7.6 Release

**Comment by kobe1104** [comment]
Verified fixed testathon 11/15/2021. @nikhilmandlik the 'Image load delay (milliSeconds)' field is required so put 0 instead of leaving it empty, but it works.
