### ISSUE TITLE
[Legacy] Timeline bundle should be removed

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#4028]
## Overview
Legacy Timeline has been deprecated for 3+ years and should be removed.

* [Old issues](https://github.com/nasa/openmct/issues?q=is%3Aissue+is%3Aopen+timeline) should be cleaned up
* Do users filing issues for legacy timeline need to be alerted?
* Do users need additional notification?
* Do legacy objects need to be exportable and importable as new timeline object?

## Expected Behavior
Should use new timeline object instead of deprecated object

## Steps to Reproduce
1. grep for any remnants of legacy timeline bundle in codebase

**Comment by shefalijoshi** [comment]
Verified fixed.
