### ISSUE TITLE
[Edit Mode] Duplication of objects in elements pool results in immediate persistence

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#403]
Edit an object, and select one of its children in the elements pool. Duplicate that child. The duplicate will be created and persisted immediately. Ideally, the duplicate should not be persisted immediately.

This does not have implications for the user at the moment. The composition on the parent is NOT persisted, so the objects just become orphans if the user cancels. When #194 is implemented, these orphans would be taken care of.

The issue may be caused by the fact that the EditableDomainObject does not wrap the CreationCapability, so when it is requested from CopyTask a live CreationCapability is returned, which will create regular DomainObjects (rather than EditableDomainObjects).

**Comment by larkin** [comment]
Duplicate is no longer an option in edit mode, closing.
