### ISSUE TITLE
[Plots] Plot view in VISTA broken because limits() changed to thenable

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#4036]
## Overview
Channel plot view in VISTA does not load at all and has a console error. Telemetry Table view works fine.

## Expected Behavior
Channels load plot view as normal

## Steps to Reproduce
1. Navigate to a channel in VISTA, or a legacy style domain object with a "limit" capability.

```
vue.min.js?a961:6 TypeError: this.limitDefinition.limits(...).then is not a function
    at d.initialize (PlotSeries.js?0d35:121)
    at new A (Model.js?132a:48)
    at new d (PlotSeries.js?0d35:64)
    at v.addTelemetryObject (SeriesCollection.js?b151:86)
    at v.initialize (SeriesCollection.js?b151:43)
    at new A (Model.js?132a:48)
    at new h (Collection.js?d5f7:24)
    at new v (SeriesCollection.js?b151:29)
    at C.initialize (PlotConfigurationModel.js?8b7a:58)
    at new A (Model.js?132a:48)
```

**Comment by davetsay** [comment]
This can be fixed in VISTA by changing the `limits()` call to return a `promise`.

Maybe something that should be put into release notes, although I think that would have to be retroactively added to 1.7.4.

**Comment by akhenry** [comment]
Perhaps if we fix this in the Telemetry API we can avoid making a breaking change to our API. The Telemetry API could check the return type of the limits object and if it's not a Promise, it could be wrapped in `Promise.resolve()`.

**Comment by davetsay** [comment]
Ok. Will do.

**Comment by shefalijoshi** [comment]
@davetsay Is the new limit lines feature implemented in VISTA? That is the only new limits API that requires a promise.

**Comment by davetsay** [comment]
verified in VISTA local builds
