### ISSUE TITLE
[Code cleanup] Remove legacy about dialog

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4038]
Any code associated with the [legacy Open MCT "about" dialog bundle](https://github.com/nasa/openmct/blob/master/platform/commonUI/about/bundle.js) should be removed as it's no longer in use.

**Comment by akhenry** [comment]
Assigned to @khalidadil

**Comment by jvigliotta** [comment]
## Testing
- click the Open MCT logo in the top right
- verify about dialog is working as expected
- no errors in regular Open MCT use

**Comment by charlesh88** [comment]
Verified fixed Testathon 12-13-21.

**Comment by nikhilmandlik** [comment]
Verified Fixed.
