### ISSUE TITLE
Re-implement image export as ES6 class

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4039]
Image export from plots etc. currently depends upon [an Angular managed service](https://github.com/nasa/openmct/blob/master/src/adapter/bundle.js#L89). This service should be reimplemented as an ES6 class  and imported wherever it is needed in our new codebase (ie. search for usage under `/src/..`).

The old behavior was that of a singleton service managed by Angular, but since this service needs no state, the simplest solution is just to make it a class that is instantiated whenever it's used. The existing code can be largely kept and just refactored into an ES6 class. The new code could live under [`/src/exporters`](https://github.com/nasa/openmct/tree/master/src).

**Comment by scottbell** [comment]
It looks like there's a bit of state in the variable `exportCount`. I'll look at changing this to a UUID so we can remove this.

**Comment by scottbell** [comment]
`dialogService` also needs to be changed to `openmct.overlays.dialog`

**Comment by scottbell** [comment]
Need to remove `ExportImageService.js` from `bundle.js` too. Then refactor references to `exportImageService` to use the simpler usage.

**Comment by scottbell** [comment]
For testing, define an `exportImageService` spec, that instantiates the class and tests it that way.

**Comment by scottbell** [comment]
To test, ensure normal image exporting works in the application.

**Comment by scottbell** [comment]
Also check that StackedPlots image exports are functioning. I think (?) they were broken in master.

**Comment by jvigliotta** [comment]
Found an issue, both PNG and JPG (exporting image from snapshot) the downloaded image is blank. Attached.
![plot_jpg](https://user-images.githubusercontent.com/12013460/128064782-45149267-ff30-4629-bbb7-d12765e8b396.jpeg)

**Comment by nikhilmandlik** [comment]
same as @jvigliotta

**Comment by unlikelyzero** [comment]
Leaving open to fix the issues identified by @jvigliotta

**Comment by akhenry** [comment]
Snow theme background is by design, it's for printing. Snapshot issue should be investigated though.

**Comment by akhenry** [comment]
Looks like the issue is in Preview/View large rather than snapshots themselves?

**Comment by scottbell** [comment]
Investigating blank image export, though not the snow theme per @akhenry

**Comment by scottbell** [comment]
The dialog service appears to be interfering with the html2canvas export

**Comment by scottbell** [comment]
Wondering if we need the dialog service when nominally exporting the image. It's near instantaneous! Though perhaps on larger exports it is not?

**Comment by scottbell** [comment]
Added an option to the ImageExport to disable the dialog. Can investigate other options if we need too
