### ISSUE TITLE
Reimplement in-memory search indexer

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4041]
Open MCT object providers may define an optional `search` function if the associated persistence store supports search. eg. [our Couch DB object provider will use Couch DB's `find` API to return objects matching the provided search term](https://github.com/nasa/openmct/blob/master/src/plugins/persistence/couch/CouchObjectProvider.js#L240).

Open MCT also implements a fallback search provider for any objects whose associated object provider does not implement search. This fallback search provider is implemented as an "in-memory" search index, which tracks [a subset of model attributes](https://github.com/nasa/openmct/blob/master/platform/search/src/services/BareBonesSearchWorker.js#L33) for all domain objects whose object provider does not implement search, so that those attributes can be subsequently searched.

This in-memory search indexer is currently implemented as [an Angular-managed service](https://github.com/nasa/openmct/blob/master/platform/search/bundle.js#L101), ~~and should be re-implemented as [a plugin](https://github.com/nasa/openmct/blob/master/API.md#plugins) (under `/src/plugins`) that is [installed by default](https://github.com/nasa/openmct/blob/master/src/MCT.js#L264)~~. There are actually two versions of the legacy indexer (the `GenericSearchWorker`, and the [`BareBonesSearchWorker`](https://github.com/nasa/openmct/blob/master/platform/search/src/services/BareBonesSearchWorker.js)), but only the `BareBonesSearchWorker` is actually in use, so the `GenericSearchWorker` should not be re-implemented.

The legacy Angular managed service is invoked from [the ObjectAPI's `search` function](https://github.com/nasa/openmct/blob/master/src/api/objects/ObjectAPI.js#L210). This logic can be retained, but it should call the new search indexer directly rather than invoking a function on the [`LegacyPersistenceAdapter`](https://github.com/nasa/openmct/blob/master/src/adapter/services/LegacyPersistenceAdapter.js) (which is part of the adapter layer into the legacy API that will soon be removed).

Note that only the search provider needs to be re-implemented, its worker can be brought across as-is, and the rest of [the legacy search bundle](https://github.com/nasa/openmct/tree/master/platform/search) (which includes a `SearchAggregator`, some legacy UI, and associated tests) should be removed from the repository.

**Comment by scottbell** [comment]
Should the `GenericSearchWorker` be deleted too?

**Comment by scottbell** [comment]
We'll get rid of GenericSearchWorker.

**Comment by scottbell** [comment]
Register objects for mutation observers when they're indexed. On mutation, reindex.

**Comment by scottbell** [comment]
Fro GenericSearchProvider.index, go to RootRegistry to get root objects, from the IDs of the root objects, get the namespace, get the Object provider, check if search implemented, then index if not implemented. To index, see MutableDomainObject line 205

**Comment by scottbell** [comment]
Need to get with Vista folks to test on large object corpus.

**Comment by scottbell** [comment]
Try to consolidate GenericSearchWorker and BareBonesSearchWorker. Also try to remove some of the indirection in GenericSearchProvider too.

**Comment by scottbell** [comment]
Make sure class doesn't start indexing until openmct.on('start) has fired. Don't start indexing in constructor.

**Comment by scottbell** [comment]
Note I've been working on ticket in this branch:
https://github.com/nasa/openmct/compare/master...scottbell:mct4041?expand=1

**Comment by scottbell** [comment]
An update where I am on this:

- I've got a new shared worker going. I had to remove a lot of angular services it was depending on. I used the CouchDB worker as an exemplar.
- It's indexing properly, and searching, but the Promise structure needs to be reworked not to use angular's $q & deferred services. I'm implementing this now.

**Comment by akhenry** [comment]
Sounds like great progress, thanks for sharing @scottbell.

**Comment by scottbell** [comment]
Searching is now working, but I had some trouble with the way the shared worker was using its data structures. Namely, in the current way search works, its worker just has an array of items. On mutation, "indexing" works by just pushing the new version of the model to the array. Consequently, if I rename a clock from "Foo Clock" to "Bar Clock", "Foo Clock" hangs around. Searching for "Foo" will return "Bar Clock". Is this what we want @akhenry ? I was instead going to use a dictionary data structure instead, and have the mutation replace the existing item, thus searching "Foo" would return nothing as no item has that name anymore.

One other question, previous versions of the indexed data structure in the workers didn't keep the whole model of the domain objects, only the name/type/id. Due to this, there's a lot of looking up of models when returning results. Do we want to continue this? It's a size/speed trade off of course, but if the size is too big, maybe we only want to keep the surface level stuff (i.e., name/type/id) as we previously did.

**Comment by scottbell** [comment]
Talking to memory, shallow memory is desired.
@akhenry will address after looking at the 👆 whether we should use a dictionary/map, or keep the array.

**Comment by akhenry** [comment]
@scottbell Ah, I see. No, pushing mutated models to an array doesn't make any sense to me. Storing the models in a map keyed on object namespace and id (ie. `` `${object.identifier.namespace}:${object.identifier.key}` ``) makes a lot more sense to me.

For search itself we need an array like structure because we have no choice but to do an exhaustive scan, but we could just use `Object.values(indexMap)`

**Comment by scottbell** [comment]
Great! That’s roughly what I’m doing in my branch (sans the namespace, but will add that). Thank you for the feedback!

**Comment by scottbell** [comment]
@akhenry draft PR opened here:
https://github.com/nasa/openmct/pull/4527

**Comment by scottbell** [comment]
@akhenry @unlikelyzero Ah! I see the issue. Previously we had just used [Workers](https://developer.mozilla.org/en-US/docs/Web/API/Worker) for search. These can be loaded [using Blobs/createObjectURL](https://github.com/nasa/openmct/blob/master/platform/search/test/services/BareBonesSearchWorkerSpec.js#L41)
You can't do that with [SharedWorkers](https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker), which is what this PR is using, all contexts need to load from the same origin, hence the URL.

I guess this is a performance question though - should we be using Shared Workers here, or switch back to Workers? The advantage would be that several tabs could (theoretically) share indexing, which seems useful.

**Comment by scottbell** [comment]
Discussed a bit with @akhenry and we'll keep SharedWorkers, but need to make sure it works without SharedWorkers so Safari on iOS will still function.

**Comment by unlikelyzero** [comment]
@scottbell  would you mind adding testing notes to this one?

**Comment by scottbell** [comment]
To test ticket:

- Add some objects, ensure sure can find them via their name
- Open multiple tabs of OpenMCT, ensure searching for objects works
- If possible, try testing with a lot of objects and ensure search performs well
- Delete an object, ensure search results don't include deleted object

**Comment by akhenry** [comment]
Verified Fixed! Works great, thanks!
