### ISSUE TITLE
Re-implement Hyperlink plugin with Vue

### ISSUE THREAD

**Issue by kobe1104** [nasa/openmct#4056]
The existing [HyperLink](https://github.com/nasa/openmct/blob/master/platform/features/hyperlink/bundle.js) plugin and [controller](https://github.com/nasa/openmct/blob/master/platform/features/hyperlink/src/HyperlinkController.js) are currently implemented as a legacy bundle and written in Angular.js . They should be re-implemented as a plugin under /src/plugins using our current API, with the UI migrated to Vue.

Any legacy code associated with the legacy HyperLink plugin should be removed and replaced by the new one.

**Comment by charlesh88** [comment]
### Testing Notes
These notes are focused on regression testing for changes that occurred to main view, sub-object and preview containers:
1. Create one of every type of view that we have. 
2. Navigate to each view object and ensure it looks as expected.
3. Add each newly created object into a Display or Flexible Layout.; ideally, some testers do one and some do the other. Save the layout and verify each framed element looks as expected. 
![Screen Shot 2021-07-28 at 2 58 02 PM](https://user-images.githubusercontent.com/1056412/127402571-0a43b464-175c-4fc5-9d50-c43e96f1397a.png)
4. From the layout, use each frame's View Large function to see that object in the overlay "Preview" view. Verify again that all views look as expected.

**Comment by kobe1104** [comment]
### Testing instruction

1. On openmct, create a hyperlink by clicking on the '+Create' dropdown menu on top left.
3. On the create hyperlink window, add URL and text to display. Pick either link or button for display format and open in new tab or this tab.
4. Verify that the hyperlink has the expected style (either link or button) and it opens the tab in the expected way.

**Comment by nikhilmandlik** [comment]
unable to create new Hyperlink object

**Comment by davetsay** [comment]
when you edit properties the object view does not change

1. create hyperlink and link to an object in the tree
2. select hyperlink
3. click on hyperlink in object view and see that navigates to specified link
4. select hyperlink
5. edit properties from context menu
6. change url to a different object in tree
7. click on hyperlink in object view and see that navigates to original link

**Comment by davetsay** [comment]
things to fix
1. icon changed
1. form changed
    1. display format missing
    2. tab to open hyperlink missing
1. mutation bug in previous comment

@kobe1104

**Comment by davetsay** [comment]
@kobe1104 , I think hyperlink should not be an editable object. Basically, remove the `canEdit` block in the object view provider.

**Comment by shefalijoshi** [comment]
Marking this as closed as this was merged into 1.7.6.

**Comment by davetsay** [comment]
verified

**Comment by kobe1104** [comment]
Verified fixed. Testathon 8/5/2021

**Comment by shefalijoshi** [comment]
Verified fixed

**Comment by nikhilmandlik** [comment]
found adding `www.nasa.gov/` does not redirect to `https://www.nasa.gov/` 
<img width="558" alt="Screen Shot 2021-08-05 at 4 21 41 PM" src="https://user-images.githubusercontent.com/1292612/128433655-e29bf73d-ff13-4d09-ad83-2e60281a7555.png">

**Comment by unlikelyzero** [comment]
@nikhilmandlik to file a bug on the existing behavior
