### ISSUE TITLE
Memory leak in Import/Export Plugin

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4060]
#### Summary
Import/Export plugin holds reference to Open MCT object instance after application has been unloaded, preventing garbage collection.

#### Expected vs Current Behavior
Import/Export plugin should not prevent garbage collection of Open MCT instance object.

#### Impact Check List
No user impact. Test only.

#### Environment
* Open MCT Version: c3ebf52dd25424002dce7970744b9794bf5f2636
* Deployment Type: Local dev
* OS: Mac OS X 10.15.7
* Browser: Chrome headless (automated tests)

**Comment by akhenry** [comment]
Testing instructions:
Run the automated tests, ensure that they do not fail on the Import/export plugin tests.

**Comment by shefalijoshi** [comment]
Tests did not fail... so fixed?
