### ISSUE TITLE
Clear data for objects clears data for all objects

### ISSUE THREAD

**Issue by nikhilmandlik** [nasa/openmct#4065]
#### Summary
`Clear data for objects` clears data for all objects

#### Expected vs Current Behavior
Should clear a data only for given object

#### Impact Check List
- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce
1. create / use this SWG on banner/dev -> [SWG](https://banner.ndc.nasa.gov/dev/#/browse/mine/cb56f6bf-c900-43b7-b923-2e3b64b412db/6fbeb716-440a-45c5-94fe-25e124e2dd82?tc.mode=local&tc.startDelta=900000&tc.endDelta=15000&tc.timeSystem=utc&view=plot-simple)
2. create empty overlay plot or use this -> [overlay plot](https://banner.ndc.nasa.gov/dev/#/browse/mine/cb56f6bf-c900-43b7-b923-2e3b64b412db/126c9be6-02ce-448e-ac66-f7ff6a67f080?tc.mode=local&tc.startDelta=900000&tc.endDelta=15000&tc.timeSystem=utc&view=plot-overlay) 
3. select SWG to show some data [SWG](https://banner.ndc.nasa.gov/dev/#/browse/mine/cb56f6bf-c900-43b7-b923-2e3b64b412db/6fbeb716-440a-45c5-94fe-25e124e2dd82?tc.mode=local&tc.startDelta=900000&tc.endDelta=15000&tc.timeSystem=utc&view=plot-simple)
3. context click on empty overlay plot and select  `Clear data for objects`
              <img width="221" alt="Screen Shot 2021-07-28 at 12 48 04 PM" src="https://user-images.githubusercontent.com/1292612/127386568-c3a4b9ed-ea6f-4faa-b714-3b836df6a2a6.png">
4. observe data shown for SWG is now cleared.

#### Environment
* Open MCT Version: 
                Version: 1.7.4
                Build Date: Thu Jul 22 2021 11:35:01 GMT-0700 (Pacific Daylight Time)
                Revision: 42af3ad2fccff666cc1749c89f49a0a9849cbb90
                Branch: flexible-inspector-properties
* Deployment Type: dev, viper
* OS: MAC OS 
* Browser: Brave

#### Additional Information
NA

**Comment by akhenry** [comment]
This is implemented as the [ClearDataAction](https://github.com/nasa/openmct/blob/master/src/plugins/clearData/clearDataAction.js)

**Comment by scottbell** [comment]
Was able to reproduce, looking into it now.

**Comment by scottbell** [comment]
The object emit is emitting the correct path in clearDataAction, but the wrong vue component is responding to it (SWG instead of the stacked plot). One solution I've got implemented in a branch is to navigate to the object that's doing the clearDataAction first, before emitting the clearData event. This is borrowing heavily from RemoveAction

**Comment by scottbell** [comment]
Though this causes a regression now with RemoveAction in that the parent & child of the path are now reversed, so attempting to delete the StackedPlot now tries to remove the parent!

**Comment by scottbell** [comment]
@shefalijoshi recommended removing "Clear Action" from non-selected items in the tree. I.e., don't allow contextual "Clear Action" if you haven't selected the item in the tree.

**Comment by scottbell** [comment]
I've added a first draft on removing "Clear Action" from non-selected items in the tree:
https://github.com/nasa/openmct/compare/mct4065

**Comment by charlesh88** [comment]
Verified Testathon 9-20-21.

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by khalidadil** [comment]
Verified Fixed

**Comment by shefalijoshi** [comment]
Verified fixed
