### ISSUE TITLE
Uncaught TypeError: this.stopObservingObjectChanges is not a function, Uncaught TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by nikhilmandlik** [nasa/openmct#4074]
#### Summary
navigate to /testathon, Shared Items and start clicking on random folders inside it.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available? refresh page
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce
1. navigate to /testathon
2. click on Shared Items
3. start clicking on random folders inside it.
4. check console for errors

#### Environment
* Open MCT Version: 
* Deployment Type: 
* OS: MAC Catalina
* Browser: Chrome

#### Additional Information

Screenshot:
<img width="1032" alt="Screen Shot 2021-08-03 at 11 34 08 AM" src="https://user-images.githubusercontent.com/1292612/128067996-fa3693a1-2759-4c54-8fdd-3a55440b27ae.png">

Console Error:
```
Uncaught TypeError: this.stopObservingObjectChanges is not a function
    at CouchObjectProvider.js:382
    at s.<anonymous> (ObjectAPI.js:418)
    at s.emit (index.js:115)
    at l.$destroy (MutableDomainObject.js:123)
    at f.destroyMutable (ObjectAPI.js:256)
    at CompositionCollection.js:69
    at Array.forEach (<anonymous>)
    at s.<anonymous> (CompositionCollection.js:68)
    at s.emit (index.js:136)
    at l.$destroy (MutableDomainObject.js:123)
      (anonymous) | @ | CouchObjectProvider.js:382
      -- | -- | --
        | (anonymous) | @ | ObjectAPI.js:418
        | s.emit | @ | index.js:115
        | $destroy | @ | MutableDomainObject.js:123
        | f.destroyMutable | @ | ObjectAPI.js:256
        | (anonymous) | @ | CompositionCollection.js:69
        | (anonymous) | @ | CompositionCollection.js:68
        | s.emit | @ | index.js:136
        | $destroy | @ | MutableDomainObject.js:123
        | f.destroyMutable | @ | ObjectAPI.js:256
        | (anonymous) | @ | Browse.js:141
        | (anonymous) | @ | Browse.js:139
        | doPathChange | @ | ApplicationRouter.js:300
        | handleLocationChange | @ | ApplicationRouter.js:352
        | navigate | @ | ApplicationRouter.js:136
        | navigateOrPreview | @ | ObjectLabel.vue:78
        | n | @ | vue.min.js:6
        | handleClick | @ | tree-item.vue:149
        | n | @ | vue.min.js:6
        | !click | @ | tree-item.vue?01f7:5
        | t | @ | vue.min.js:6
        | e._withTask.e._withTask | @ | vue.min.js:6
```

**Comment by akhenry** [comment]
Agreed, it's a blocker. It prevents you from navigating to telemetry, so that's loss of data and situational awareness.

**Comment by shefalijoshi** [comment]
Marking closed as the fix is merged into 1.7.6

**Comment by kobe1104** [comment]
Verified fixed. Testathon 8/5/2021.

**Comment by jvigliotta** [comment]
Verified - Testathon - 8/5/2021
