### ISSUE TITLE
[Plots] legend does not update y-axis values when y-axis is changed

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#4079]
#### Summary
For plots with multiple ranges, changing the range type (y-axis) changes the plotting correctly, but the legend continues to display values for the original range.

#### Expected vs Current Behavior
Legend values should match plotted values

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

1. select a plot that has multiple plottable range values
2. expand legend to show range values
3. hover over a plotted point and verify value shown in legend matches value shown in plot
4. switch range from y-axis label dropdown
5. hover of same value from step 3 if possible
6. observe that legend displays original range value and plot shows updated range value

#### Environment
* Open MCT Version: #vista-r4.8-release 
* Deployment Type: VISTA
* OS:
* Browser:

#### Additional Information
I can provide screenshots on request

**Comment by shefalijoshi** [comment]
Marking it as closed as the fix is merged into 1.7.6.

**Comment by davetsay** [comment]
verified in vista
