### ISSUE TITLE
[Persistence] Persistence promises should be rejected on failure

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#408]
Currently, the PersistenceService API returns a boolean indicating success or failure for most operations. Instead, we should be returning promises which are either resolved or rejected based on the success or failure of the underlying call.

This ensures that errors "bubble up" until explicitly handled (making it conspicuous when they are unhandled) and brings us more in line with the way promises would be more commonly used in this context.

**Comment by VWoeltjen** [comment]
Look at #328 in the context of this issue

**Comment by larkin** [comment]
believe this should be the root issue for next cut at handling persistence errors, marking as question.
