### ISSUE TITLE
[Plots] plot performance degradation in vue from angular

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#4084]
#### Summary
Plotting data (after receiving the data) takes longer in new Vue plots as it did in AngularJS plots for large data sets. UI becomes locked during plotting.

#### Expected vs Current Behavior
Vue plots should perform at least as well as legacy AngularJS plots

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

1. ensure time conductor is in fixed time mode
2. select any plot object with decently sized data
2. select a larger timeframe if more data needed
3. observe time to plot
4. expand plot to max size (maximize window size, collapse tree and inspector panes)
5. observe time to plot

* This was observed with identical build environments and data, but different software builds, where the vue plots lagged significantly with the high res plot.

#### Environment
* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Additional Information

Good idea to check vue reactivity. if data is somehow being reactified.

**Comment by unlikelyzero** [comment]
@davetsay to confirm that this was tested as a part of the VISTA release verification

**Comment by davetsay** [comment]
This was tested and released in VISTA
