### ISSUE TITLE
New "My Items" plugin needed

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4088]
**Is your feature request related to a problem? Please describe.**
The "my items" object currently depends on a mixture of code that is split between the legacy and current APIs. The legacy code should be replaced, and the code consolidated into a new "My Items" plugin.

**Describe the solution you'd like**
The legacy "My Items" bundle should be removed, and replaced with a "My Items" plugin (Under `src/plugins/MyItems`). The legacy My Items bundle did two things, one of which has already been replaced with new code:
1. [It creates a "My Items" root object](https://github.com/nasa/openmct/blob/master/platform/features/my-items/bundle.js#L30). This can be replaced with a call to `openmct.objects.addRoot('mine')`
2. [It creates a "My Items" model](https://github.com/nasa/openmct/blob/master/platform/features/my-items/bundle.js#L35). This has already been replaced by [an "Object Interceptor" that does the same thing](https://github.com/nasa/openmct/blob/master/src/plugins/interceptors/myItemsInterceptor.js) using the current API, however the interceptor code should be moved into the new "My Items" plugin.

The **new** My Items plugin will need to be exposed on the [`openmct` API object](https://github.com/nasa/openmct/blob/master/src/plugins/plugins.js#L124) so that it can be easily installed.

**Comment by jvigliotta** [comment]
## Testing
- verify "My Items" folder is showing up correctly
- if possible, delete "My Items" from the DB or start a new instance of Open MCT where "My Items" is not in the DB and verify it does show up

**Comment by nikhilmandlik** [comment]
Tested locally with coucdb, after deleting `mine` from couchdb on UI `my items` shows up but there is no corresponding document in couchdb.
