### ISSUE TITLE
Implement transactions in Object API and retire legacy transactions

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4089]
**Is your feature request related to a problem? Please describe.**
Our legacy API includes a transaction system [that queues requests to persist objects](https://github.com/nasa/openmct/blob/master/platform/commonUI/edit/src/capabilities/TransactionalPersistenceCapability.js#L61) if Open MCT is in Edit mode. Our current API has an Edit API [that starts and ends transactions, but the transactions themselves are still implemented in the legacy API](https://github.com/nasa/openmct/blob/master/src/api/Editor.js#L63).

**Describe the solution you'd like**
Transactions should be re-implemented in the current API.

The legacy API implemented transactions by intercepting calls to persist, and if a transaction was active, the subsequent call to persist the object was queued instead of being immediately executed.

I think that in re-implementing this we should track dirty objects, rather than queuing persistence calls. The Object API should maintain a list of dirty domain objects (probably not in the Object API itself, perhaps in a separate class referenced from the ObjectAPI), and when the transaction is saved (by invoking [`Editor.save()`](https://github.com/nasa/openmct/blob/master/src/api/Editor.js#L62)) the list of dirty object models should be iterated and each object persisted. Objects will be marked dirty on mutation (this could happen when [`ObjectAPI.mutate()`](https://github.com/nasa/openmct/blob/master/src/api/objects/ObjectAPI.js#L285) is invoked).

### Testing instructions:
1. create editable and  non editable objects.
2. make changes to those objects
3. save / cancel changes and observe if changes are persisted (even after page refresh changes should show)

**Comment by nikhilmandlik** [comment]
After discussion with @akhenry, 
1. Start/Create Transaction on edit:
    create a Transaction Set to track mutated objects
2. update transaction on object mutation:
    if (editMode) 
         //update transaction
         object.mutate -> add mutated object to Transaction Set
    else
         persist object -> object.save
3. End transaction:
    on commit -> object.save -> call object.save on items in Transaction set
    on cancel -> object.refresh (pr from Khalid)

**Comment by unlikelyzero** [comment]
Given the size of this change, we'll keep this around for re-opening if a bug is found. Closing and marking as verified for now
