### ISSUE TITLE
Remove Angular from Identity indicator

### ISSUE THREAD

**Issue by kobe1104** [nasa/openmct#4103]
The current [identity bundle](https://github.com/nasa/openmct/blob/master/platform/identity/bundle.js) is written in Angular and it needs to be created as a plugin using Vue.
This includes converting [IdentityIndicator.js](https://github.com/nasa/openmct/blob/master/platform/identity/src/IdentityIndicator.js) and all other components under [identity folder](https://github.com/nasa/openmct/tree/master/platform/identity/src).

**Comment by akhenry** [comment]
Let's park this work for now. This will be addressed under the "user awareness" theme for VIPER build 6.

**Comment by akhenry** [comment]
Closed by https://github.com/nasa/openmct/issues/4407
