### ISSUE TITLE
snapshot clicked while in edit mode should open in preview mode

### ISSUE THREAD

**Issue by nikhilmandlik** [nasa/openmct#4115]
#### Summary
When clicked on snapshot url/text it navigates to that object url.
But if ui is in edit mode then navigation happens but current view gets replaced by new url. This causes 2 major issues,
1. current edited view gets dismissed could cause in loss of changes.
2. new vie may not have edit mode and now is in edit mode. eg: SWG, Clock etc

#### Expected vs Current Behavior
When in edit mode snapshots should open in preview.

#### Impact Check List
- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [x] Is this just a visual bug?

#### Steps to Reproduce
1. create or use clock or SWG (non editable object)
2. take snapshot of object (save in snapshot container)
3. create or open display layout and click edit (be in edit mode)
4. now open snapshot container and click on text inside snapshot item (object name and not image) 
5. this should replace display layout with SWG or clock object with edit mode ON

#### Environment
* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser: brave

#### Additional Information
<img width="1070" alt="Screen Shot 2021-08-13 at 12 00 13 PM" src="https://user-images.githubusercontent.com/1292612/129406549-0eca33e0-51a3-49b1-b33a-cc74eaad9341.png">

**Comment by shefalijoshi** [comment]
Verified Fixed
