### ISSUE TITLE
[Telemetry Collections] Abort signal key name incorrect

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#4118]
#### Summary

The abort signal key for the options being sent to the historical telemetry provider was incorrectly named. This was preventing telemetry requests from aborting.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

1. View a high density telemetry endpoint with network tab opened to view fetch requests
2. Navigate away from the object
3. Requests should be canceled, currently they are not

**Comment by jvigliotta** [comment]
## Testing
- same as #3639

**Comment by shefalijoshi** [comment]
Verified fixed
