### ISSUE TITLE
resize handler causes plot to make duplicate request

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#4121]
#### Summary

Plots are making two identical requests on load.

#### Expected vs Current Behavior

Plots should request data once on load. Plots should then requests data as needed upon explicit element resize.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

1. open browser debugger to network tab and filter to show xhr only
2. navigate to a plot
3. observe network requests
4. observe stack trace for network requests to see calling code

#### Environment
* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

**Comment by charlesh88** [comment]
Testathon 8-24-21: no testing notes, can't test.

**Comment by unlikelyzero** [comment]
@davetsay to add testing notes
