### ISSUE TITLE
only zoom and pan should pause plot, not click

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#4138]
#### Expected vs Current Behavior

Clicking on a plot should not pause the plot. Plot should only pause on zoom or pan, or explicit pause.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

1. Navigate to a plot
2. Click on the plot

#### Environment
* Open MCT Version: 1.7.6
* Deployment Type: 
* OS:
* Browser:

**Comment by michaelrogers** [comment]
I'd like to claim this issue to work on. I am claiming it verbally since I cannot assign the issue at preset.

**Comment by scottbell** [comment]
@michaelrogers just saw your comment! sorry about that. I created a branch already FWIW called `mct4138`. The issue appears to be the `startMarquee` function in `MctPlot.vue`:
https://github.com/nasa/openmct/blob/1.7.8/src/plugins/plot/MctPlot.vue#L738

The marquee is used for zoom in on the plot, so we'll need to distinguish between a real zoom, and the user merely clicking on the plot. Most methods that I found involve some combination of keeping state of the `mouseMove` event, and having `mouseUp` and `mouseDown` read that state.

**Comment by michaelrogers** [comment]
No problem Scott. Locally, I naively removed the `startMarquee` function from the `onMouseDown` handler logic fork, but I had not fully investigated the potential downsides of that approach yet. I do like your suggestion of using the mouse state to deduce the intent of the user.

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by shefalijoshi** [comment]
Verified fixed except an orange border shows up on mousedown till you mouse up - probably can't be prevented.

**Comment by jvigliotta** [comment]
Verified fixed - Testathon 9/30 - ditto to what @shefalijoshi said
