### ISSUE TITLE
Add Security issue submission to our github issue tracker

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#4142]
we should add a issue type to help community members add issues https://github.com/nasa/openmct/issues/4096

**Comment by LeoDog896** [comment]
(this is already done)
![image](https://github.com/nasa/openmct/assets/26509014/bb78703e-383f-4f79-8f25-e6dbbe97fa18)

**Comment by unlikelyzero** [comment]
@LeoDog896 thanks!
