### ISSUE TITLE
Telemetry Tables - Switching from Local clock to Fixed timespan does not retrieve data

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#4145]
#### Summary

While testing #3639 , I created a telemetry table by adding the deltaXr telemetry endpoint to it while in Local Clock mode.
Then I switched to Fixed timespan mode after the initial historical requests had completed (checked Network tab).

Telemetry data was not retrieved immediately upon switching to Fixed timespan mode. 

#### Expected vs Current Behavior

Expected: Switching to Fixed timespan re-requests telemetry data
Observed: No new requests were sent to the backend.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

1. Ensure Open MCT is in Local Clock mode and open the Network tab in the developer console
2. Create a Telemetry Table
3. Drag in a telemetry endpoint
4. Wait for all historical requests to return (no more network requests)
5. Switch time conductor to Fixed timespan mode

#### Environment
* Open MCT Version: 1.7.7
* Deployment Type: VIPER testathon
* OS: Mac
* Browser: Firefox

**Comment by akhenry** [comment]
Not necessarily an issue. Switching from local clock to fixed time mode stops the clock, meaning that the bounds stop changing automatically. It's possible that the Time API issues a bounds change event when switching from local to fixed mode that the table is just ignoring though, I'm not sure? In any case, the bounds shouldn't actually change, so there is no reason for a view to re-fetch data that it already has I don't think?

**Comment by unlikelyzero** [comment]
Working as designed
