### ISSUE TITLE
Tree view not in sync with main view

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#4147]
#### Summary
The tree view is sporadically not in sync with its main view. 

<img width="1446" alt="130681094-05dde580-00e2-4f27-959b-e8a30a82255f" src="https://user-images.githubusercontent.com/12013460/131747744-2f7316a3-599e-4157-a536-366b7731037a.png">

Purple arrow shows expanded folder in tree which doesn't show any children, while the main view shows the folder's children. Navving away and back does not fix the problem, but refreshing does update the tree view properly.

#### Expected vs Current Behavior
Tree view should always sync with the corresponding main view.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available? Browser refresh.
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

Unsure how to reproduce, but folder was created by one user (@charlesh88) and populated by another user during a demo session.

#### Environment
* Open MCT Version: 1.7.7
* Deployment Type: /stable
* OS:
* Browser:

**Comment by jvigliotta** [comment]
@charlesh88 I'm unable to replicate this at all. I even tried in the original folder. Maybe we could do some testing together on the server?

**Comment by nikhilmandlik** [comment]
Unable to reproduce, let test again in next testathon.

**Comment by akhenry** [comment]
I have also observed this FWIW, but I don't have any repro steps right now.

Good idea to retest the next testathon and see if anyone can reliably reproduce.

**Comment by davetsay** [comment]
@akhenry can you do a think on this one?

This is easily reproducible if you have two people. The tree is not seeing the other users updates. I think we could solve this by observing composition on visible nodes that allow composition. @nikhilmandlik mentioned you might have worked on an object refresh capability.

**Comment by akhenry** [comment]
Notes:
Conflicting changes to composition can be resolved via the same merging strategy used in notebook entries. Concurrent changes to folder names could just use a "last change wins" strategy (ie. always just overwrite it with the most recent name).

**Comment by akhenry** [comment]
Note: There _will_ be conflicts in composition changes. The same merge strategy used for [resolving conflicts in concurrent notebook entries](https://github.com/nasa/openmct/blob/master/src/plugins/notebook/monkeyPatchObjectAPIForNotebooks.js) could be used here. Note that the linked code monkey patches `ObjectAPI.save`. We might consider improving our API to support this properly, instead of continually monkey-patching it.

**Comment by RadotJar** [comment]
I've seen this issue with dynamically generated compositions. I'd like to be able to trigger a composition.refresh() if it is changed and cause the tree to repopulate. So far, only way I can cause the re-population is to collapse the folder. Next time a user expands, the composition will be repopulated.
