### ISSUE TITLE
Spectral Aggregate composition policy

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#4178]
**Is your feature request related to a problem? Please describe.**
Spectral Aggregate plots should only work for telemetry that provides/supports spectral data

**Describe the solution you'd like**
Create a Spectral aggregate composition policy that expects telemetry to have metadata attributes for spectral X and Y attributes.
For example:
`{
                    key: "sin",
                    name: "Sine",
                    unit: "Hz",
                    formatString: '%0.2f',
                    hints: {
                        range: 1,
                        spectralAttribute: true
                    }
}`

`{
                    key: "wavelength",
                    name: "Wavelength",
                    format: "string",
                    hints: {
                        domain: 1,
                        spectralAttribute: true
                    }
}`

**Additional context**
Telemetry metadata samples can be found here:
https://github.com/nasa/openmct/blob/master/example/generator/GeneratorMetadataProvider.js#L46

When we look for possible spectral attributes for x and y axes, use the `valuesForHints` utility method here:
https://github.com/nasa/openmct/blob/master/src/api/telemetry/TelemetryMetadataManager.js#L112

**Comment by scottbell** [comment]
Am I correct in thinking we just need to look for `spectralAttribute` here?
