### ISSUE TITLE
Visualize spectral aggregate plot data using plotly

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#4192]
Spectral plots are special plots that use Wavelength or Frequency for the X-axis and any data telemetry for the Y-axis.
Currently, plots use only time for the x-axis. In order to support new views for spectral plots, we need to
Spectral Aggregate plots work similarly, but the x-axis may be non-wavelength/frequency domains.

Plot historic and realtime data received from telemetry endpoint providers using plotly.
The visualization should be a histogram (bar chart) with the following details:
1. Bar values (formatted text and units) should be shown within the bar either horizontally or vertically(if it doesn't fit)
![image](https://user-images.githubusercontent.com/5247066/133128919-d9bd30dc-5299-419f-89a1-bbc2b63cc7b8.png)

![image](https://user-images.githubusercontent.com/5247066/133128961-e5af40cb-8150-486c-a21a-ba85db42bf70.png)

2. Bar width should vary based on the number of x-axis ticks. Handle edge cases where the width of each bar is less than 1px (a large number of x-axis ticks) and where there is only 1 x-axis tick (should be one large bar spanning across the chart)
For example, what happens if you try to plot 4000 x-axis ticks(channels)?
3. Ensure that the bars don't  have any borders
4. Ensure resizing horizontally and vertically resizes the chart to fit vertical space
5. Ensure that the plot is placed at the bottom of the available viewable area and does not appear to be floating:
![image](https://user-images.githubusercontent.com/5247066/133142437-333c6305-973f-4824-82f4-9bd3ec6870a7.png)

5. When 2 spectral aggregate plots are dragged into a Display Layout, ensure that they visualize correctly

**Comment by scottbell** [comment]
1. look at plotly lib on putting values in the bar chart
2. need to do, modify spectral generator to test
3. ✅
4. ✅
5. need to do, put at bottom and take up full real estate.
6. need to make sure in display layout, vertical squishes data like other plots

**Comment by shefalijoshi** [comment]
@charlesh88 Please assist as you see fit or if @scottbell  needs you

**Comment by shefalijoshi** [comment]
X axis labeling to fit - let Plotly handle this, 
- What happens if the labels are mixed lengths?

Bar width - let Plotly handle it for now. If something comes up, we can specify behavior later.

Hover - OK for now since we have only 1 telemetry endpoint at a time we have no issues about what to show on hover.

Colors for traces should be supported (Inspector - see Plot Series Form)

**Comment by scottbell** [comment]
left padding is still having some issue as there's a clearly defined box around the plot which makes the graph look a little funny
