### ISSUE TITLE
Conditional Styling not being applied when editing a Condition Widget

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#4196]
#### Summary
Conditional Styling not being applied when editing a Condition Widget

#### Expected vs Current Behavior
When editing a Condition Widget, clicking a Condition rule in the Inspector should ignore the actual Condition Set's current evaluation state and apply the style as defined in that rule immediately. Instead, the selected rule is having no affect on the applied style, using the Condition Set evaluation to drive which style is being applied as if the system was in browse mode. This makes it practically impossible in some cases to preview how an applied style will look.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

1. Make a Condition Set, and create a rule that will never match. 
2. Edit or create a Condition Widget, and use the CS created in step 1 to conditionally style the widget.
2. Define colors for the default rule, and observe that they are applied.
3. Select the "never match" rule and define colors. Observe that the style is not applied, but should be.

![image](https://user-images.githubusercontent.com/1056412/132599893-e694f398-578c-4a74-9416-e6161c54e3f8.png)

#### Environment
* Open MCT Version: 1.7.7, 1.7.8
* Deployment Type: /stable, /latest
* OS:
* Browser:

**Comment by scottbell** [comment]
I'm not seeing able to replicate this bug in the latest checkout from 1.7.8, though I may not following the steps properly. Here's what I did:

- Created a SNG that varies between -10 and 10
<img width="603" alt="image" src="https://user-images.githubusercontent.com/9853862/134482847-56d2cf41-45e9-498b-aca0-3e5a70d88547.png">

- Created a Condition Set with a condition that will never be true (is checking for the SNG's value to be greater than 100):
<img width="513" alt="image" src="https://user-images.githubusercontent.com/9853862/134483118-2d3751d9-8bf9-43a7-a0ba-54cbb046f88b.png">

- Created a condition widget based on that condition set and edited its style for the default condition and the un-matchable condition. The style appears to change when selecting the different conditions:
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/9853862/134483503-11087f48-835c-43c4-a68a-b2077f698f37.png">
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/9853862/134483852-427012de-691c-4aa1-ba3d-bbf0f5f2a1dd.png">

I did notice a separate bug though. After editing the condition widget, the last style selected remains and is not updated until the user moves away. For example, I've just finished editing the widget and had the un-matchable condition selected. It remains in the display after editing, even though the condition isn't met:
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/9853862/134483975-b9ac3336-8eb9-4848-9456-cdb46aa9e824.png">
Navigating away, and then back corrects the issue:
![Uploading image.png…]()

I'll look into this for the interim. I suspect the edit state isn't being propagated properly from the inspector.

**Comment by scottbell** [comment]
I've got a branch fixing I think the above bug 👆:
https://github.com/nasa/openmct/compare/1.7.8...mct4196?expand=1
We weren't waiting for the telemetry to return before running handleConditionSetResultUpdated after finishing an edit. I changed the function to be async to make the code more clear for future developers.

**Comment by scottbell** [comment]
I'm now able to reproduce the original bug now too. Not sure what changed, but will investigate.

**Comment by scottbell** [comment]
Ok, figured out a way to reliably reproduce:

1. Select condition widget. Select "Styles" tab on inspector
2. Navigate away to another object
3. Select condition widget again. Enable editing mode. Color on Condition Widget does not change

From running this through the debugger, the issue appears to be in the StylesRuleManager's editing state is not being set properly, and it think it in the above step 3, the user is not editing.

**Comment by scottbell** [comment]
After some investigation, it looks like the issue was the `toggleEdit` (and the `refreshData`) in the `StylesRuleManager` were losing this context. I changed both to be declared as arrow functions in the constructor to preserve `this` context, as the bind didn't appear to be working inside the class.

**Comment by scottbell** [comment]
I've opened a PR which includes the fix, and a unit test:
https://github.com/nasa/openmct/pull/4255

**Comment by shefalijoshi** [comment]
Verified fixed
