### ISSUE TITLE
Could we somehow use TelemetryCollections to "yield" historical data progressively as pages return? Rather than blocking until everything comes back?

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#4200]
Name kinda says it all doesn't it?

**Comment by unlikelyzero** [comment]
@jvigliotta  to add testing notes

**Comment by charlesh88** [comment]
Needs testing notes!

**Comment by akhenry** [comment]
Verified fixed

**Comment by akhenry** [comment]
This fix has introduced a bug into some related functionality - https://github.com/nasa/openmct/issues/4234

**Comment by kobe1104** [comment]
Verified fixed testathon 9/20/2021.

**Comment by shefalijoshi** [comment]
Verified fixed
