### ISSUE TITLE
[Tabs View] Making requests when switching tabs while eager load is true

### ISSUE THREAD

**Issue by kobe1104** [nasa/openmct#4206]
The tabs view is making new requests when switching tabs while eager load is true. 
It should not make new request unless clock mode is changed while eager load is true since they are already loaded.

#### Expected vs Current Behavior

Expected: No new requests should be made while switching tabs.
Current: Making new requests when switching tabs.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

1. Create a Tabs view 'eager load' is true and populate it with at least 2 telemetry sources.
2. Open network tab in browser dev tools and clear all the requests.
3. Switch to a different tab and observe new requests for all sources have been made.

#### Environment
* Open MCT Version: Version: 1.7.8-SNAPSHOT
Build Date: Thu Sep 09 2021 12:20:09 GMT-0700 (Pacific Daylight Time)
* Deployment Type: 
* OS: IOS 10.15.7
* Browser: Chrome 92.0.4515.159

**Comment by jvigliotta** [comment]
Verified Fixed Testathon 9/30/22

**Comment by ozyx** [comment]
Verified Fixed Testathon 09/30/22

Did not observe any network requests while switching between tabs
