### ISSUE TITLE
[Display Layout] Grid disappearing when scrolling down (in Edit Mode)

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#4207]
#### Summary

When editing a display layout, if you move an object down lower and the layout has to scroll, the grid background just stops. Possibly new area being added doesn't have css applied?

#### Expected vs Current Behavior

Grid should show.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [x] Is this just a visual bug?

#### Steps to Reproduce

1. Created a dislpay layout
2. Drag an object below the current view, so you have to scroll
3. Grid doesn't continue to that area
4.

#### Additional Information

<img width="501" alt="Screen Shot 2021-09-10 at 2 24 48 PM" src="https://user-images.githubusercontent.com/12013460/132922586-9e0d849e-50ef-4a22-bada-1ae6f8a72c27.png">

**Comment by imrishabh18** [comment]
@jvigliotta Can I take up this issue? I am new to this will be needing your help with this 😁

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 11/15/2021

**Comment by shefalijoshi** [comment]
Verified fixed.

**Comment by charlesh88** [comment]
Verified fixed Testathon 11-15-2021

**Comment by kobe1104** [comment]
Verified fixed testathon 11/15/2021.

**Comment by davetsay** [comment]
when i expand the window horizontally, to the right, the same non-grid behavior exists.

**Comment by nikhilmandlik** [comment]
created related new issue: https://github.com/nasa/openmct/issues/4467
