### ISSUE TITLE
[Layout] Add loading indicators

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#422]
When first viewing a Layout, there can be a delay before composition is loaded, during which time the Layout appears empty. This delay depends on connection and in some cases is fairly long.

Should either:
- Show a wait spinner for the whole Layout while composition is being loaded (simplest)
- Show frames for various objects in the Layout, with wait spinners in those (more visually appealing, probably a larger change set.)

May want to do this in the context of (or after) merging functionality of Layout with Fixed Position view

**Comment by charlesh88** [comment]
Migrated comment here to #567, closing.
