### ISSUE TITLE
When the main Time Conductor is in Fixed Mode, the independent Time Conductor only has one option: Fixed Mode. We should not show the independent mode selector in this case, but should just hide it.

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#4228]
When the main Time Conductor is in Fixed Mode, the independent Time Conductor only has one option: Fixed Mode. We should not show the independent mode selector in this case, but should just hide it.
![Screen Shot 2021-09-17 at 3 59 16 PM](https://user-images.githubusercontent.com/1056412/133862146-ddd3424d-a82d-4ffa-9c2c-e9d26898d1ce.png)

_Originally posted by @charlesh88 in https://github.com/nasa/openmct/pull/3988#pullrequestreview-757907666_

**Comment by jvigliotta** [comment]
@shefalijoshi seems straightforward, but can you provide testing notes?

**Comment by shefalijoshi** [comment]
Testing notes:
Enable the independent time conductor for a time strip while the Global time conductor settting is in 'Local Clock' mode.
Now change the Global time conductor setting to Fixed timespan.
Expected: The independent time conductor should also show fixed time span start and end bounds inputs but not the mode.

**Comment by khalidadil** [comment]
Verified fixed
