### ISSUE TITLE
Address review comments for Bar Graphs

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4229]
Review comments in https://github.com/nasa/openmct/pull/4221 need to be addressed and tested before 1.7.8 is closed out.

- [x] Remove Spectral Generator metadata and provider from example generators.
- [x] Remove Spectral Aggregate metadata and provider from example generators.
- [x] Remove Spectral plot related code - maybe keep it in a separate branch if needed.

- [x] Add an alias for plotly-basic in webpack.config
- [x] Create a new folder under plugins to hold non-time domain plots
- [x] In the BarGraphCompositionPolicy, rename hasAggregateDomainAndRange to hasRange
- [x] Use v-on for event handling: See https://github.com/nasa/openmct/pull/4221/files/a1a7e73e3383152727afbdacc0ffbb7cf4dd84ab#r711627257
- [x] Remove the use of `this.currentDomainObject` and it's observer from the BarGraphView
- [x] Remove the listener for `openmct.time.clock` from BarGraphView
- [x] Resolve objects.mutate usage. See here: https://github.com/nasa/openmct/pull/4221/files/a1a7e73e3383152727afbdacc0ffbb7cf4dd84ab#r711631275
- [x] Remove telemetryAPI request options. https://github.com/nasa/openmct/pull/4221/files/a1a7e73e3383152727afbdacc0ffbb7cf4dd84ab#r711633345
- [x] Check that data returned by the telemetry request and subscribe calls are within the time bounds provided: https://github.com/nasa/openmct/pull/4221/files/a1a7e73e3383152727afbdacc0ffbb7cf4dd84ab#r711632679
- [x] Format data before adding it to the traces for display

**Comment by scottbell** [comment]
I've made a branch and have addressed all except:

-  Check that data returned by the telemetry request and subscribe calls are within the time bounds provided (was going to look and see how plot does this. hopefully something else does this!)
- Move BarGraphCompositionPolicy tests to the plugin level (was this unchecked intentionally?)
- Format data before adding it to the traces for display (was having trouble getting a formatter for the spectral data generator, perhaps i need to add one?)

The branch is located here:
https://github.com/nasa/openmct/compare/spectral-plots...mct4229?expand=1

I'll work on the outstanding three issues, but would love any pointers!  😀

**Comment by shefalijoshi** [comment]
Thanks @scottbell We're good now. Let's write some tests! :)

**Comment by unlikelyzero** [comment]
Going to keep this closed and track issues in https://github.com/nasa/openmct/issues/4177
