### ISSUE TITLE
Table data export does not export all available rows

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4234]
#### Summary
The Export Table Data action will only export the data available in the client, even if there is more data available on the server. This is due to the recent addition of paging support which will asynchronously populate the table with new pages as they are fetched.

#### Expected vs Current Behavior
Export Table Data should export all available data. The current behavior is that it will export only the data that has been downloaded so far.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [X] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [X] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce
1. Open a telemetry point with telemetry flowing
2. In the chrome dev tools, go to the network tab.
3. Throttle the connection to Slow 3G
4. Set the time conductor to show an hour of data
5. While the table is slowly refreshing with new data, click on the Export Table Data action from the three-dot menu
6. Observe that the CSV file exported only contains the rows in the table, and does not contain any of the rows available from the server.

#### Environment
* Open MCT Version: 1.7.8

#### Additional Information

**Comment by akhenry** [comment]
@charlesh88 @jvigliotta We should discuss potential approaches here. It _might_ be ok to disable the action until all of the data has returned? The user is going to have to wait either way, and waiting for the table to finish loading will be quicker than starting again. Also we have an activity indicator in tables, we don't for the export action.

**Comment by unlikelyzero** [comment]
Bumping severity for now

**Comment by akhenry** [comment]
Closed by https://github.com/nasa/openmct/pull/4245

**Comment by shefalijoshi** [comment]
Unable to test since YAMCS was not functioning at the time.
