### ISSUE TITLE
console error on navigation away from timeline object

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#4236]
#### Summary
Console error received when navigating away from a timeline object.

#### Expected vs Current Behavior
No console errors on navigation away from timeline object.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

1. navigate to a timeline object that exists, or create a new one
2. navigate to another object in tree
3.
4.

#### Environment
* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Additional Information

```
vue.min.js:6 Error: Attempted to destroy non-mutable domain object
    at g.destroyMutable (ObjectAPI.js:265)
    at a.beforeDestroy (TimelineObjectView.vue:92)
    at me (vue.min.js:6)
    at a.e.$destroy (vue.min.js:6)
    at destroy (vue.min.js:6)
    at m (vue.min.js:6)
    at m (vue.min.js:6)
    at m (vue.min.js:6)
    at m (vue.min.js:6)
    at m (vue.min.js:6)
```

**Comment by unlikelyzero** [comment]
Note: this needs further investigation

**Comment by shefalijoshi** [comment]
Verified Fixed.
