### ISSUE TITLE
Values in Bar Graph display with weird characters in Y axis labels

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#4237]
yVelocity telemetry point:

<img width="999" alt="Screen Shot 2021-09-20 at 4 02 24 PM" src="https://user-images.githubusercontent.com/1056412/134087992-7a8ce2d1-d7ba-40fb-ab8b-2e60924b4b26.png">

Sine wave generator:

<img width="1066" alt="Screen Shot 2021-09-20 at 3 50 24 PM" src="https://user-images.githubusercontent.com/1056412/134087997-1eb4ec42-561d-431a-8df9-1b2e4b7f559e.png">

DOM inspection of SWG label:

<img width="592" alt="Screen Shot 2021-09-20 at 3 57 35 PM" src="https://user-images.githubusercontent.com/1056412/134087996-de287cc6-6ab6-4ac8-bad6-e6d40466163f.png">

#### Expected vs Current Behavior
Values in the Y axis should display with "-", e,g. "-0.5", "100", etc.

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

1. Make Bar Graph.
2. Add a Sine Wave generator and/or telemetry points that have negative values.
3. Observe: labels in Y axis for negative values have weird unexpected characters.

#### Environment
* Open MCT Version: Version: 1.7.4-rc1 Branch 1.7.8
* Deployment Type: /testathon
* OS:
* Browser:

**Comment by shefalijoshi** [comment]
Fixed this in the viper-openmct repository by adding a meta tag with utf-8

**Comment by unlikelyzero** [comment]
Testing notes for latest fix:
verify that nothing strange shows up on the y-axis of a bar graph

**Comment by khalidadil** [comment]
Verified Fixed in testathon on 09/30/2021

**Comment by jvigliotta** [comment]
Verified fixed - Testathon 9/30

**Comment by kobe1104** [comment]
Verified fixed - testathon 9/30/2021
