### ISSUE TITLE
[Telemetry Tables] Progress bar is not showing correctly during loading

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#4239]
#### Summary

The progress bar is supposed to show whenever the table is making historical requests. This allows the user to know when all the data has been loaded and is available. Currently the bar does not show correctly.

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Testing

1. View a large dataset
2. While all the data is loading, you should see the progress bar
3. When all data has loaded (can be verified in network tab) progress bar should disappear
4. Create a new empty telemetry table, verify there is NO loading bar

**Comment by shefalijoshi** [comment]
Verified fixed.
