### ISSUE TITLE
JSON import causing 409 errors

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#4240]
Importing a domain object JSON file is causing 409 errors in the 1.7.8 build. Despite this, the imported objects appear whole and to function as expected.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

1. Export anything. 
2. Open the browser console and clear it.
3. Import the file exported in step 1.
3. Observe: Open MCT will report persistence errors, and 409 errors will be present in the console.

#### Environment
* Open MCT Version: 1.7.8-SNAPSHOT
* Deployment Type: /testathon
* OS:
* Browser:

#### Additional Information
![Screen Shot 20![Screen Shot 2021-09-21 at 10 32 30 AM](https://user-images.githubusercontent.com/1056412/134229051-695140b1-f6dd-4138-b665-2fa42e401995.png)-09-21 at 10 32 16 AM](https://user-images.githubusercontent.com/1056412/134228830-72b8e4cb-a73c-4ff5-aa53-4668c72396c2.png)

![Screen Shot 2021-09-21 at 10 32 30 AM](https://user-images.githubusercontent.com/1056412/134251405-8bc8a503-0eba-473c-85e7-afdd6fefca70.png)

**Comment by khalidadil** [comment]
This looks good to me
