### ISSUE TITLE
Import as JSON dialog select file button not working properly

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#4241]
#### Summary
Seen during issues described in #4240.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

**Setup**
Use an Open MCT deployment in which the Clock notifier is not present. Make sure a Timer object is not the main view; Folder view is a good place to do this. Why? We're keeping anything out that would trigger an Angular digest cycle.
1. Export anything.
2. Import the exported file. In the dialog, click "Select File..." and select a file using the resulting OS picker. Press Enter.
3. Observe: the Select button will hang on "Select File..." rather than switching to the selected file name. 

![Screen Shot 2021-09-21 at 2 41 30 PM](https://user-images.githubusercontent.com/1056412/134252795-a3338b5e-711a-4d95-99ec-86181f5e4e9e.png)

4. Click the Select button again: it will immediately update to the name of the selected file, but also cause the OS picker to be displayed. 
5. Continuing the process at this point will allow you to import the file.

**Expected behavior** 
Step 3 should not occur; the button should switch to the selected file name as soon as it can and the Ok button should become enabled.

#### Environment
* Open MCT Version: 1.7.8
* Deployment Type: /testathon
* OS:
* Browser:

**Comment by akhenry** [comment]
This is almost certainly an Angular digest issue, and related to the removal of the Angular clock component. The Angular clock had the side effect of trigger regular Angular digests. The long term fix is to rewrite the Angular forms dialog in Vue, which is underway. 

A potential short term fix is simply to manually trigger a digest once the user is done selecting a file (maybe onchange could be used on the input?).

**Comment by jvigliotta** [comment]
Verified fixed - Testathon 9/30

**Comment by kobe1104** [comment]
Verified fixed - testathon 9/30/2021
