### ISSUE TITLE
Bar graph color change not taking effect for dictionary items

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#4252]
#### Summary
Unable to change the color of a telemetry endpoint added from the VIPER dictionary

#### Expected vs Current Behavior
When a color from the color swatch is chosen, expectation is that the color of that series bar should reflect that color.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce
1. Create a bar graph
2. Add a telemetry endpoint from the VIPER dictionary
3. Edit the bar graph and expand the color properties. Choose a color different from the assigned one.
4. Expect the bar color to change, but it does not.

#### Environment
* Open MCT Version: 1.7.8
* Deployment Type: /testathon
* OS: Mac
* Browser: Firefox/Chrome

#### Additional Information

![image](https://user-images.githubusercontent.com/5247066/134580005-7e0f8015-3d0f-4505-828f-d29dc4ade21e.png)

**Comment by scottbell** [comment]
I think was fixed in:
https://github.com/nasa/openmct/pull/4232
we just haven't merged it in yet

**Comment by charlesh88** [comment]
Testathon 9-28-21: verified fixed.
