### ISSUE TITLE
Better handling of Overlay Plots added to Bar Graphs

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#4269]
#### Summary
Users can create an Overlay Plot directly into a Bar Graph

![Screen Shot 2021-09-28 at 4 42 30 PM](https://user-images.githubusercontent.com/1056412/135180189-712403cc-f41a-4a1a-8dc1-73fd990ea7fc.png)

or can drag an Overlay Plot onto a Bar Graph, adding it. Either action results in the Bar Graph failing to display anything.

#### Expected vs Current Behavior
Either treat the Overlay Plot as an aggregate data source and display its constituents as such (preferred) or disallow Overlay Plots as part of a Bar Graph's composition.

#### Impact Check List

- [x] Data loss or misrepresented data? _@charlesh88 says: if a user does this, data is not being displayed when there's an expectation that it would be._
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

1. Create a Bar Graph and an Overlay Plot.
2. Drag the plot onto the Bar Graph.
3. Observe: the plot is added, but nothing is displayed.

#### Environment
* Open MCT Version: 1.7.8
* Deployment Type: localhost
* OS:
* Browser:

**Comment by scottbell** [comment]
For 1.7.8, I was thinking we should do the easy thing and just disallow overlay plots in the composition policy. For the other option (treating the Overlay Plot as an aggregate data source and display its constituents as such), should we have a separate ticket?

**Comment by shefalijoshi** [comment]
We will disallow Overlay Plots as part of a Bar Graph's composition.
