### ISSUE TITLE
[Telemetry Collections] Duplicate requests on load

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#4273]
#### Summary
When loading a telemetry collection, a deliberate call to request historical is made, this isn't necessary, since the timeSystem is also triggered on load and it will request telemetry. Need to remove the initial request.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

1. On load of a telemetry table, make sure no duplicate requests are made

**Comment by davetsay** [comment]
verified

**Comment by unlikelyzero** [comment]
Not to be confused with: https://github.com/nasa/openmct/issues/4282
