### ISSUE TITLE
Toggling Time Conductor changes setting in Independent Time Conductor

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#4283]
#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

1. Put Time Conductor (TC) into Local UTC.
2. Enable Independent Time Conductor (ITC)  on a Time Strip view.

![image](https://user-images.githubusercontent.com/1056412/135540347-14518d0b-2b65-47a6-893a-5ff604871557.png)

3. Change the TC to Fixed mode.

![image](https://user-images.githubusercontent.com/1056412/135540405-72359335-c556-4c88-b966-90655c385234.png)

4. Change the TC back to Local UTC. The ITC should revert back to Local UTC, but instead is set to Fixed Mode.

![image](https://user-images.githubusercontent.com/1056412/135540679-71915a71-00ba-428b-9b70-157dcad87847.png)

#### Environment
* Open MCT Version: 1.7.8
* Deployment Type: /testathon
* OS:
* Browser:

**Comment by akhenry** [comment]
From the outset I always thought that independent time conductors should be overridden by the global time conductor when it changes, but now I'm not so sure. The user has deliberately decided to focus on a particular time period, so maybe we should _never_ override that unless they explicitly tell us to? ie. they switch independent time controls back off again, or we provide some method of force syncing all independent time conductors to the global time conductor?

Maybe the thing to do is to just test what we have right now with users and see what they want?

**Comment by shefalijoshi** [comment]
Closing this. We can look at this again if it comes up.
