### ISSUE TITLE
Improve condtionWidget & clearData tests

### ISSUE THREAD

**Issue by scottbell** [nasa/openmct#4307]
Per the npm test:coverage, these two parts of the code have very little test coverage. I plan to add some useful tests. Furthermore, the clearData tests were written by me very early in the project and should be redone to use the openmct API.

**Comment by unlikelyzero** [comment]
@scottbell we've informally been tracking this type of work on the 'Improve Test Coverage' project with a `label:type:maintenance`

**Comment by unlikelyzero** [comment]
@scottbell  would you consider this ticket closed?

**Comment by scottbell** [comment]
I moved the PR to here:
https://github.com/nasa/openmct/pull/4597

I added a comment to the PR, I forgot to mention this here!
