### ISSUE TITLE
Three dot action menu in the main pane doesn't refresh on object state change

### ISSUE THREAD

**Issue by khalidadil** [nasa/openmct#4313]
#### Summary
The three dot menu doesn't refresh on updating object state. For the timer, specific actions show should when it's in a certain state (started/stopped/paused), and I notice that it works on the tree but not on the main pane.

#### Impact Check List
- [ ] Data loss or misrepresented data?
- [X] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce
1. Try creating a timer and then pausing it, either from the pause button or the three dot menu.
2. The three dot menu should show the actions "Start", "Restart at 0", and "Stop", but instead you will see "Pause", "Restart at 0", and "Stop" for the actions in the three dot menu for the main pane.
3. Right clicking on the object in the tree should show the correct actions ("Start", "Restart at 0", and "Stop").

#### Environment
* Open MCT Version: 1.8
* Deployment Type: Banner Stable
* OS: Mac OS
* Browser: Chrome

**Comment by ozyx** [comment]
## Testing

### Main view

1. Create a Timer
2. Click the different timer actions in the 3dot menu in the object view, making sure that available actions are updated appropriately.
3. Click the different timer actions in the tree context menu (right-click domain object), check to make sure that the available actions in the 3dot menu are updated appropriately.

### Display layout

1. Create a Display Layout
2. Create a Timer, drag it into the display layout and save it
3. Click the different timer actions in the 3dot menu for the timer, making sure that available actions are updated appropriately.
4. Select 'View' or 'Large View'
5. Click the different timer actions in the 3dot menu in the View/Large View. Make sure that the actions are updated appropriately.

#### Available Actions per Timer State

- `Started`
  - 'Pause'
  - 'Restart at 0'
  - 'Stop'
- `Paused`
  - 'Start'
  - 'Restart at 0'
  - 'Stop'
- `Stopped`
  - 'Start'

**Comment by alizenguyen** [comment]
Verified testathon 7/1/2022

**Comment by charlesh88** [comment]
Verified fixed Testathon 07-01-22.
