### ISSUE TITLE
Notebook time frame and sorting method aren't persistent, but should be

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#4319]
#### Summary

The timeframe (all, last 8 hours, etc. ) and sort method for entries within a given Notebook are supposed to be persistent, but navigating away or refreshing will reset them to their defaults. Instead, both settings should be retained _per Notebook_. 

![image](https://user-images.githubusercontent.com/1056412/137390545-a89557dd-409c-4418-806d-7188f866d728.png)

This behavior could have a large negative impact during a mission if a user misreads a shift log.

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

1. See Summary

#### Environment
* Open MCT Version: 1.7.8
* Deployment Type: /stable
* OS:
* Browser:

**Comment by jvigliotta** [comment]
## Testing
- change Timeframe and sort for a notebooks entries
- navigate away
- come back and make sure it's the same
- refresh
- make sure it's the same
- rejoice

**Comment by charlesh88** [comment]
Verified fixed Testathon 1/17/22.
