### ISSUE TITLE
Imagery in timestrip view shows the wrong image in large view

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#4327]
#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

1.
2.
3.
4.

#### Environment
* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

**Comment by shefalijoshi** [comment]
Testing instructions:
Ensure the right image shows up in large view when you click on one in the time strip view.

**Comment by unlikelyzero** [comment]
I think this was missed as a part of the last testathon

**Comment by akhenry** [comment]
Imagery is current broken in test environment, so unable to verify.

**Comment by charlesh88** [comment]
Verified fixed Testathon 01-06-22.
