### ISSUE TITLE
Changing the Time Conductor bounds while the Imagery View is paused displays a broken image

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#4328]
#### Summary
Changing the Time Conductor (TC) Start or End bounds while the Imagery View is paused displays a broken image, but shouldn't. 

#### Expected vs Current Behavior
What should happen when the TC real-time bounds are changed while an image view is paused: 
- If the selected past image is within the new TC bounds, there are two proposed solutions, A and B:
  - Option A (preferred): thumbs in the thumb strip should be updated accordingly, the selected image should _remain selected_ and should display properly, and the view should remain paused. 
  - Option B (if A is too difficult): just treat as if the selected image is NOT within the new TC bounds; see next bullet below.
- If the selected past image is NOT within the new TC bounds, the selected image should be unselected and the view should unpause and continue on as expected. 

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

1. TC set to real-time, something like 15:00 > 00:15
1. Go to an Imagery view, click on a past image to select it. The view will pause and that image will be displayed.
1. Change either TC start or end value.
1. The current image will display as broken and the display remains paused.
1. Clicking the Play button resets the view and resumes, the problem is fixed.

#### Environment
* Open MCT Version: 1.7.8
* Deployment Type: /testathon
* OS: 
* Browser:

#### Additional Information
**Initial State**
![Screen Shot 2021-10-15 at 2 08 36 PM](https://user-images.githubusercontent.com/1056412/137557820-255eddbb-ec39-42d5-b097-9751a49d1b92.png)

**Selecting a past image**
![Screen Shot 2021-10-15 at 2 09 49 PM](https://user-images.githubusercontent.com/1056412/137557881-e7a23a08-f990-4608-8c6b-6042bf898dd6.png)

**Having changed the TC bounds**
![Screen Shot 2021-10-15 at 2 10 30 PM](https://user-images.githubusercontent.com/1056412/137557902-43e555f9-4f01-4304-bd4b-49807a0d4a16.png)

**Comment by shefalijoshi** [comment]
Closing.

**Comment by jvigliotta** [comment]
Verified: Testathon 12/8/2021
Images are no longer broken, though, in local mode, the image is wrong sometimes, this is being investigated and it's issue is #4555
