### ISSUE TITLE
[LAD] [Alphanumeric] Update views to use Request Animation Frame (RAF)

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#4339]
**Is your feature request related to a problem? Please describe.**
Currently not many views use RAF, which can increase performance by letting the browser determine when to update the page.

**Describe the solution you'd like**
Any time new data is going to be updated in the template, we should have that use RAF to determine the best time to do so. LAD Tables/LAD Table Sets/Alphanumerics are prime candidates for these as they update often and are not currently utilizing this built-in feature.

**Additional context**
This came up during testing display layouts with MANY views (Plot, LAD, Alphanumeric, etc.) and we've determined that this could provide performance enhancements.

## Testing
- this is a bit harder to test without having a reference, if able, test with and without this enhancement
- for alphanumerics, create a display layout with MANY high frequency alphanumeric telemetry objects
- for LAD tables create a lad table with MULTIPLE high frequency telemetry objects
- throttle the CPU
- watch FPS between the two versions using the same display layout
- FPS should be noticeably better on the enhanced version

**Comment by shefalijoshi** [comment]
Verified fixed.
