### ISSUE TITLE
Tables are showing data outside of conductor bounds

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4349]
#### Summary
Telemetry tables are showing data with timestamps that are after the end bound of the time conductor. This is demonstrated in this example screenshot provided by the open source community:

![Screen Shot 2021-10-22 at 9 16 49 AM](https://user-images.githubusercontent.com/4215777/138491900-c834013d-5a74-4e0d-a7ca-a93cb4f6091e.png)

#### Expected vs Current Behavior
Telemetry tables should respect the bounds defined by the time API.

#### Impact Check List

- [x] Data loss or misrepresented data? (potentially, needs investigation)
- [X] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [X] Does this impact a critical component?
- [ ] Is this just a visual bug?

**Comment by akhenry** [comment]
Reclassifying as critical. It's an important issue, but it shouldn't block release.

**Comment by akhenry** [comment]
This needs investigation to see if we can reproduce in any of our environments.

**Comment by scottbell** [comment]
I'm having trouble replicating this:
<img width="961" alt="image" src="https://user-images.githubusercontent.com/9853862/156178446-d5e4ccf2-a3a9-46b3-bc61-c6bf60376502.png">

Walking through the code in the debugger, this is rejecting telemetry produced after the bounds have been set:
https://github.com/nasa/openmct/blob/master/src/api/telemetry/TelemetryCollection.js#L190
Perhaps somehow those bounds weren't set properly? Is this easy to see on a test server?

**Comment by scottbell** [comment]
Astutely @davetsay pointed out that the time conductor in the screenshot is within bounds. I’ll close this ticket.
