### ISSUE TITLE
Scrubbing and zooming the time conductor should update the start and end inputs in real time

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4352]
#### Summary
When scrubbing or zooming the time conductor, the values in the start and end inputs should update in realtime. Note that the bounds in the time API should **not** update until the user has released the mouse.

This is a very recent regression and might be related to the [independent time conductor changes](https://github.com/nasa/openmct/pull/3988).

![Screen Recording 2021-10-22 at 1 50 01 PM](https://user-images.githubusercontent.com/4215777/138531906-ec1f9113-f214-4f18-8424-bdaf07391637.gif)

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [X] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [X] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce
1. Switch to fixed time mode
2. Hold the option key (mac) and drag the time conductor axis left and right
3. Observe that the input values for the start and end time do not change until the mouse is released

#### Environment
* Open MCT Version: 1.7.8
* OS: All
* Browser: All

**Comment by shefalijoshi** [comment]
This appears to be working in banner/testathon. Closing.

**Comment by akhenry** [comment]
It's not working on testathon. The start and end dates should change _in real time_ as the conductor is scrubbed. Right now they only change when you release the mouse button.

**Comment by akhenry** [comment]
Here's a comparison of the "panning" (or "scrubbing") behavior from two different versions:
#### 1.7.8
![1 7 8](https://user-images.githubusercontent.com/4215777/145840824-afcf79ba-c53f-4c63-a980-72cbb4898d0f.gif)

#### 1.8.1 (Testathon)
![testathon](https://user-images.githubusercontent.com/4215777/145841195-7a1744d3-5342-4e28-a635-28d1d7821585.gif)

**Comment by akhenry** [comment]
It's important to note that the value of the _inputs_ changes as you drag, but the Time API bounds do not update until the mouse is released. It was all being done via events that were internal to the Time Conductor component, the Time API does not get involved until the user releases the mouse button.

I believe that the intended behavior was lost during refactoring for independent time conductors.

**Comment by unlikelyzero** [comment]
Verified fixed
