### ISSUE TITLE
pinch zoom while hovering over plot action buttons should act like pinch zoom while hovering over plot

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#4353]
#### Summary

When a user hovers over the overlay buttons in plots (eg. zoom in, zoom out, sync time conductor) they leave the plot context. If they then use pinch zoom, not zoom, pinch zoom, the whole browser will zoom since that is the default browser behavior. We should make the buttons part of the plot context.

#### Expected vs Current Behavior

A user would expect when the cursor is within the boundaries of the plot that the zoom gesture zooms the plot, not the browser. The buttons overlayed on the plot should be considered within the boundaries of the plot.

#### Impact Check List

- [] Data loss or misrepresented data?
- [] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [] Is this just a visual bug?

#### Steps to Reproduce

1. navigate to a plot
2. hover over the plot action buttons (eg. zoom in, zoom out, sync time conductor)
3. pinch zoom

#### Environment
* Open MCT Version: master
* Deployment Type: core
* OS:
* Browser:

#### Additional Information

![pinch zoom](https://user-images.githubusercontent.com/3614296/138535877-d6ed602a-4097-4f39-bffb-9de2571c4c46.gif)

**Comment by shefalijoshi** [comment]
We should think about how zoom/pan fixes will work with Stacked Plots when this is being fixed.
