### ISSUE TITLE
move image export and cursor/grid toggle actions to action menu

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#4359]
**Is your feature request related to a problem? Please describe.**
These actions available for plot views takes up an entire row of vertical space.

**Describe the solution you'd like**
The actions should move to the action menu and exposed in the browse bar (next to snapshot and 3 dot menu)

**Comment by trusktr** [comment]
https://github.com/nasa/openmct/pull/5125

**Comment by trusktr** [comment]
To test:

- make an overlay plot
- notice buttons and toggle switch that were visible between the action bar and the plot are gone
- notice that the buttons and switch are now in the action bar or the view menu
- behavior of the buttons should be the same as before

**Comment by shefalijoshi** [comment]
A small change to the design:
1. Move the cursor guide and grid toggle to the 'local controls' for a plot (shown on hover), with on/off states
2. Remove the export image buttons and move them to the 3-dot menu.

**Comment by khalidadil** [comment]
This looks good to me. I noticed that export to png/jpg is available while editing the object, but they still seem to work as expected. Testathon on 05/24/22.

**Comment by rukmini-bose** [comment]
Verified Testathon 05/24/2022

**Comment by davetsay** [comment]
I'm seeing a weird rendering artifact when hovering on the actions in the 3 dot menu. There is flickering and then at points there are grey bars.

<img width="545" alt="Screen Shot 2022-05-24 at 2 55 52 PM" src="https://user-images.githubusercontent.com/3614296/170139145-c7b07a39-914e-4c60-8b9b-ca79b3f98187.png">

**Comment by rukmini-bose** [comment]
Verified Testathon 6/9/2022
