### ISSUE TITLE
fix plot color scheme (especially in espresso)

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#4360]
**Is your feature request related to a problem? Please describe.**
Plots are harder to see with the new color palette.

**Describe the solution you'd like**
plot colors should be more clear. especially first default color. especially in espresso.

**Additional context**
old teal color is much more contrasting to background than the new blue color
![image](https://user-images.githubusercontent.com/3614296/138616861-ab2cb6ec-22b8-4e8c-95b9-75df1da053e4.png)
![Uploading image.png…]()

highest priority is to fix plot colors, but also see #4203 for taking this to the next level

**Comment by charlesh88** [comment]
Old plot colors in need of correction, on both Espresso and Snow plot background colors:

![Screen Shot 2021-12-20 at 1 02 27 PM](https://user-images.githubusercontent.com/1056412/146833641-28695bed-fc36-4c95-9f61-6b17c452c361.png)

New plot colors:

![Screen Shot 2021-12-20 at 1 04 43 PM](https://user-images.githubusercontent.com/1056412/146833632-9ebd7a7e-5836-4072-84f8-1500d2a4fa95.png)

**Comment by nikhilmandlik** [comment]
Verified Fixed.
