### ISSUE TITLE
[Clocks/Timers] Allow a Timer to be paused

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#438]
Originally https://trunk.arc.nasa.gov/jira/browse/WTD-1527. 

From Jay during DOT 8/26/15.
Allow a timer to easily be paused and restarted via controls in the timer itself. When paused, the timer should clearly indicate its state.

**Comment by charlesh88** [comment]
Possible Help Wanted candidate?

**Comment by charlesh88** [comment]
Charles to add design notes and unassign.

**Comment by charlesh88** [comment]
The Timer component already has a Reset button that displays on hover; a Pause/Play button should be added next to this element to toggle the timer pause state. It should follow the same hide/show on hover behavior as the Reset button. When paused, the text of the Timer itself should pulse when paused. See the pulse mixin in _mixins.scss.

**Comment by charlesh88** [comment]
This is related to #623

**Comment by gh0st** [comment]
Was this resolved in #1402?

**Comment by charlesh88** [comment]
@gh0st Appears it was, thanks.
