### ISSUE TITLE
[UTCTimeFormat] Convert to ES6 Plugin

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#4390]
**Is your feature request related to a problem? Please describe.**
We're migrating away from code in `/platform` and converting to ES6 and plugins whenever possible. Currently the [UTCTimeFormat.js](https://github.com/nasa/openmct/blob/master/platform/commonUI/formats/src/UTCTimeFormat.js) is in our old platform directory and is currently in the AMD format.

**Describe the solution you'd like**
We would like to make this a native JavaScript module and convert it to a plugin. A similar example can be found with our [ISOTimeFormat Plugin](https://github.com/nasa/openmct/tree/master/src/plugins/ISOTimeFormat) 

**Note**
This will need to be add to the [plugins.js](https://github.com/nasa/openmct/blob/master/src/plugins/plugins.js) file as well.

**Comment by charlesh88** [comment]
Testathon 12-13-21: no testing instructions.

**Comment by akhenry** [comment]
Verified fixed. Looks good to me.
