### ISSUE TITLE
[CI] Run CodeQL Security scans against every PR

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#4394]
Now that CodeQL Security scans have been implemented for some time, we can enable security scans against individual PRs.

More information on how to Triage is located here:
https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/triaging-code-scanning-alerts-in-pull-requests

# Testing Notes
Implement a security vulnerability and verify that the PR is blocked

**Comment by jvigliotta** [comment]
I don't think this was to be tested, but failed: Testathon: 4/28/2022
