### ISSUE TITLE
[Layout] Persist changes to view selection

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#44]
Persist choices made for view selection in frames within a layout, when those changes have been made in Edit mode. Do not persist choices when the view is in Browse mode.

Summary of desired behavior:
- User creates a Layout
- User Edits a Layout
- User drags some objects (e.g. a Telemetry Panel) into the Layout
- User uses view switcher in frame in a Layout to change the views in these frames (e.g. switching to Scrolling view of a Telemetry Panel)
- User hits Save and returns to Browse mode
- User views the created Layout in Browse mode and sees the view choices from above (e.g. that telemetry panel still shows Scrolling view)
- User can still change these view choices, but if they navigate away from the Layout and come back, the view choice that they Saved from Edit mode should be in effect again.

**Comment by VWoeltjen** [comment]
Will want to store some information in the `configuration` in scope to store these view choices; invoke `$scope.commit` to persist those changes in Edit mode.

There are some examples of this being done to persist frame positions in `handleDrop` and `endDrag` in LayoutController (in platform/features/layout)

**Comment by larkin** [comment]
View-as-object changes our solution to this problem and as such this is a wontfix.
