### ISSUE TITLE
[Bar Graph Plugin] Accepts types that it should not

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#4400]
#### Summary
I had accidentally created a condition set inside of a bar graph. Tried creating some other types, but looks like only condition set is the issue.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce
1. Have a bar graph selected
2. Create Menu -> Condition Set
3. Oh noes!

**Comment by akhenry** [comment]
Bar charts are probably accepting objects that produce telemetry, which condition sets do, but without considering whether the telemetry is actually plottable in a bar chart (ie. does it produce numbers?).

**Comment by scottbell** [comment]
I can take this one

**Comment by scottbell** [comment]
We are checking range values:
https://github.com/nasa/openmct/blob/master/src/plugins/charts/BarGraphCompositionPolicy.js#L27
```
const rangeValues = metadata.valuesForHints(['range']);
return rangeValues.length > 0;
```
but this isn't enough clearly. Should I be checking for a `formatString` too within the rangeValues?

**Comment by akhenry** [comment]
Good question. I think we want to use similar logic to regular plots? Of course I'm assuming they are working correctly in this scenario :)

**Comment by scottbell** [comment]
Regular plots behave the same in that you can drop condition sets upon them. E.g.:
<img width="1407" alt="Screen Shot 2021-11-02 at 5 04 17 PM" src="https://user-images.githubusercontent.com/9853862/139894178-398591bc-1ab5-4e0d-ac2f-b9dd45923509.png">
In fact, the composition policy is mostly just a copy/paste from OverlayPlots, except we loosened it a bit to only check the range for values so we can accept state generators (string/numbers).

**Comment by scottbell** [comment]
Though after talking about this at the tagup, should we trying to plot ConditionSets in BarGraphs, or forbidding them? One can plot them in Overlay plots:
<img width="971" alt="Screen Shot 2021-11-02 at 10 33 06 PM" src="https://user-images.githubusercontent.com/9853862/139954844-ab191790-4d38-4a78-80ef-6c5f0fa0c8dd.png">
Though in BarGraphs, they look rather screwy with the current value being assigned to the y-axis:
<img width="971" alt="Screen Shot 2021-11-02 at 10 34 06 PM" src="https://user-images.githubusercontent.com/9853862/139954941-b8c38f77-318d-4eb3-ad26-87e8a82fdd31.png">
What do you think @shefalijoshi @akhenry @charlesh88?

**Comment by scottbell** [comment]
As I'm not sure there's a good way to look for numbers per se, and if we don't want to modify BarCharts to support enums, we could just block telemetry of the `format` that is equal to `enum` in the composition policy.

**Comment by scottbell** [comment]
Per discussion in tagup, I'm going to check if the metadata is an enum, and block objects in the composition policy that have it.

**Comment by scottbell** [comment]
Fixed in:
https://github.com/nasa/openmct/pull/4434

**Comment by jvigliotta** [comment]
Testathon 12/7/2021 - Verified Fixed
