### ISSUE TITLE
[Performance] Check views for memory leak on navigation

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4406]
There is a class of memory leak that occurs where references to view objects are retained even after the view has been destroyed. View destruction occurs on navigation. 

The usual reason for this is a failure to clean up event handlers.

This can cause performance degradation of the application over time as memory builds up. This is a particular issue with views that hold onto historical telemetry.

[A draft PR](https://github.com/nasa/openmct/pull/6718) exists that provides a framework for implementing this kind of test. **It should be configured to run on every PR**  to catch memory leaks as soon as they are introduced. The draft PR defines tests for the following object views:

* [x] Overlay Plots
* [x] Stacked Plots
* [ ] Tables
* [x] LAD Tables
* [x] LAD Table Sets
* [x] Imagery View (Except for CompassRose)
* [x] Simple Display Layouts
* [x] Simple Flexible Layouts
* [ ] Notebooks
* [ ] Tabs View

Filed followup for remaining screens - https://github.com/nasa/openmct/issues/6734
Also see: https://github.com/nasa/openmct/issues/4209

**Comment by shefalijoshi** [comment]
Testing Instructions:
1. Retest Display Layout actions
2. Retest Drawing tools for display layouts
3. Retest resizing display layouts
4. Retest Flexible Layout actions
