### ISSUE TITLE
Implement User API

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4407]
Introduce user "awareness" into Open MCT to enable user and role specific functionality such as role-specific home pages.

The specific details of how users are identified and authenticated will be platform specific, so we need an API that delegates those details to a "User Provider".

Here are some thoughts on how we can break this problem down:
1. Introduce a new "User API" eg. `openmct.user.getCurrentUser()`
2. Add a new plugin that adds an indicator that shows the name of the currently logged in user. This plugin would be installed by default, but should only show an indicator if a user provider is defined in the API.
3. Add an example User Provider Plugin that exercises the new User API. This plugin could add a dialog that allows the user to identify themselves, and then displays the provided name in the indicator defined in step 2. This plugin will not be installed by default, and will just be provided as an example to developers

A separate issue will be created to integrate the new Open MCT User API with Yamcs' user API.

I have some initial thoughts on what the user API might look like, which we can iterate on. One key thing to note is that I *think* we only want to support a single user provider at a time? Unlike view, object, and telemetry providers where we need to support many.

``` JavaScript
// This is how the current user is checked (eg. from an indicator that displays the logged in user)
let user = openmct.user.getCurrentUser(); // Returns a promise that resolves with a user or undefined

// This is how the `getCurrentUser()` function might be implemented:
openmct.user.getCurrentUser = function() {
    if (!this.provider || this.provider.isLoggedIn) {
        return Promise.resolve(undefined);
    } else {
        return this.provider.getCurrentUser();
    }
}

// This is how a new user provider is registered
openmct.user.setUserProvider({
    isLoggedIn() {

    }
    async getCurrentUser() {
        return {
            id: 'some-user-id',
            fullName: '',
            homeUrl: '' // MAY be built dynamically, based on role.
        }
    }
    async hasRole(roleId) {
    }
});
```

**Comment by akhenry** [comment]
@scottbell

**Comment by jvigliotta** [comment]
## Testing
- with no user provider installed, you should NOT see the user indicator
- with ExampleUserProvider plugin installed, you should see the user indicator
- if logged out, you should be able to login from the user indicator
- the example user provider should give you a login form (username, password)
  - the user name should show in the indicator, when you login
- if logged in, you should be able to logout from the user indicator
  - the user indicator should only show the login button

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by akhenry** [comment]
Verified fixed
