### ISSUE TITLE
[Indicators] Indicators need better layout and interaction

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#442]
* When an indicator has a numeric count of notices, the number is spaced too far away from the icon. 
* The user should be able to click the icon as well as the expanded text to display the Messages overlay
* The expanded notice and icon should have rollover effects (like a subtle background) to indicate clickability.

**Comment by charlesh88** [comment]
@akhenry @VWoeltjen Is there a good way that I can force an error or notice to add an notification indicator in the status area?

**Comment by VWoeltjen** [comment]
@akhenry wrote a nice example plugin to help with this. Add `example/notifications` to bundles.json (or, equivalently, run as `node app.js -i example/notifications`). You will get some extra utilities in the status bar that allow to trigger notifications of various kinds.

**Comment by charlesh88** [comment]
Started work on this in open442. Relates to https://github.jpl.nasa.gov/MissionControl/vista/issues/293

**Comment by charlesh88** [comment]
Need to file PR.

**Comment by charlesh88** [comment]
PR filed, closing this for now.

**Comment by charlesh88** [comment]
I added a regression problem that doesn't manifest in VISTA, but does in WARP: the float-right class applied to the clock element doesn't work with display: inline-block applied to mct-include. Reopening to fix.

**Comment by charlesh88** [comment]
Starting fixes in open442a

**Comment by charlesh88** [comment]
Testathon 03032016
Confirmed functioning as desired for WARP in Linux / Chrome.

**Comment by charlesh88** [comment]
Filing the transition effects problem as another issue.
