### ISSUE TITLE
Ability code injections in [sub.nasa.gov] remote a webshell_executed

### ISSUE THREAD

**Issue by oxctdev** [nasa/openmct#4420]
#### Summary
Introduce my name [ANDRI](https://twitter.com/andridev_) I am currently a bughunter for a company, [Hackerone LTD.](https://hackerone.com/andridev_)

I did Penetration Testing on the nasa.gov domain and for days I tried to find security holes in the entire nasa.gov domain, and finally I got to that stage, I found a vulnerability that had a fatal impact on the network and web applications, this vulnerability can be used by attacker to take over the server as well as the database.
![IMG-20211101-WA0000_1](https://user-images.githubusercontent.com/91846073/139717648-f2ed1a30-5b04-4d6f-81c9-c2593b25425e.jpg)

**Comment by akhenry** [comment]
This repository is for the Open MCT application.

Please report issues with the nasa.gov domain to the NASA security operations center at soc@nasa.gov. Be prepared to report the specific details of any purported security vulnerabilities.

**Comment by oxctdev** [comment]
Nice for closed!
