### ISSUE TITLE
Add Issue template for Security Issues and type:maintenance

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#4424]
Add a security template for Security Issues like https://github.com/microsoft/playwright/issues/new/choose

Add a new issue type for `type:maintenance`

**Comment by unlikelyzero** [comment]
https://github.com/nasa/openmct/pull/4165

**Comment by unlikelyzero** [comment]
# Testing Notes
- Find our security Policy and review it
- Create a new issue with the issue template for 'Maintenance' and verify that the format makes sense and the issue is created with `type:maintenance`

**Comment by charlesh88** [comment]
Verified fixed Testathon 11-15-21.

**Comment by davetsay** [comment]
verified
