### ISSUE TITLE
Domain object properties Notes don't appear in Inspector, but should

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#4430]
#### Summary
This is raised in importance to solve a functional ask to allow users to add authorship and a version number to composed displays in Open MCT.

#### Expected vs Current Behavior
This used to function, filing this as a regression bug.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

1. Edit properties on any composed view and add any content in the Notes field. Save and exit that dialog.
2. Observe: the Notes content is not shown in the Inspector, but should be.

#### Environment
* Open MCT Version: 1.7.8
* Deployment Type: any
* OS: any
* Browser: any

#### Additional Information
![image](https://user-images.githubusercontent.com/1056412/139961077-ca811187-aa93-4487-a5de-5be3091f1d28.png)

![image](https://user-images.githubusercontent.com/1056412/139961101-2a6ce69d-1e3b-4ab7-a31f-3714efd86694.png)

**Comment by khalidadil** [comment]
@charlesh88 I talked to @davetsay and he didn't see notes in the inspector in a really old branch (before conditionals were implemented). Where should they be showing up in the inspector? Under their own heading? Below title and type? We can add them in based on the order you think they need to be in the inspector.

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 12/13/2021

**Comment by charlesh88** [comment]
Testathon 12-13-21: verified fixed.

**Comment by nikhilmandlik** [comment]
Verified Fixed.
