### ISSUE TITLE
[Tabs] Clicking on a tab will reload the view unnecessarily 

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#4435]
#### Summary
Tabs in eager load mode should keep tab views loaded in the background (which it does), but when you click on the tab to bring it into view, the data is re-requested when it shouldn't be.

#### Expected vs Current Behavior
With "Eager Load Tabs" true, any tab that is clicked, should not need to have data re-requested.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

1. Create a tabs view with multiple telemetry view tabs
2. Click on any tab other than the current tab
3. You can see the view reloading data

**Comment by shefalijoshi** [comment]
Verified fixed
