### ISSUE TITLE
New Forms API needs tests

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4438]
#### Summary
The [new Forms API](https://github.com/nasa/openmct/pull/3816) is not compliant with our coding standards as it does not have tests.

#### Expected vs Current Behavior
All new code must be accompanied by test specs.

**Comment by akhenry** [comment]
Closed in favor of https://github.com/nasa/openmct/issues/4539 which has more detail

**Comment by jvigliotta** [comment]
This is a dupe, as per @akhenry above comment.
