### ISSUE TITLE
Fix typo in security policy and duplicate security issue entries in template

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4448]
#### Summary
Fix a [tiny typo in our security policy](https://github.com/nasa/openmct/blob/566469e691ee43c70180fae2d06bd96330cb2ecd/SECURITY.md?plain=1#L17) and remove duplicate security entries in issue template.

**Comment by unlikelyzero** [comment]
# Testing Notes

Create a new issue and verify that 'Security Type' only appears once

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 11/15/2021. I'm not seeing the typo, and I only see a single instance of the "Report a security vulnerability" issue type.

**Comment by charlesh88** [comment]
I just see "Report a security vulnerability" appearing once. Per discussion, verified fixed Testathon 11-15-21.

**Comment by davetsay** [comment]
verified
