### ISSUE TITLE
Notebook Types

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#4449]
Introduce Notebook "types", e.g. General, Shift Log, etc. with different capabilities and/or restrictions like edit/delete entries.

Allow Notebooks to be typed to support the ability to create different types of Notebooks for different use cases, e.g. General Notebook and Shift Log. The General type would allow edit/delete, etc. while the Shift Log might layer in things like entry or page edit locking, etc.

From "Open MCT Notebook Enhancements Fall 2021".

**Comment by jvigliotta** [comment]
## Testing Instructings (pretty sure this is just a dupe)
- #5035

**Comment by charlesh88** [comment]
Testathon 6-9-22: not deployed, cannot test.

**Comment by charlesh88** [comment]
Verified fixed Testathon 06-15-22.
