### ISSUE TITLE
Wait spinner unhappy in WARP

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#445]
Wait spinners don't spin and are not positioned properly on Linux Chrome. Here is a shot from codriver running Chrome 34.0.1847.116:

![warp-master spinner not spinning](https://cloud.githubusercontent.com/assets/1056412/11884679/4c74bb9a-a4d0-11e5-81d5-a1f78e6cff53.png)
![unhappy wait spinners in tree](https://cloud.githubusercontent.com/assets/1056412/11884807/568f88de-a4d1-11e5-9cf7-dfaef1352deb.png)

This shot is from my Mac, running Chrome 46.0.2490.86 (64-bit)

<img width="1096" alt="screen shot 2015-12-17 at 3 08 01 pm" src="https://cloud.githubusercontent.com/assets/1056412/11884770/00a7a3e8-a4d1-11e5-8320-0bf860fc8560.png">

**Comment by charlesh88** [comment]
This works on the Linux workstation that was exhibiting the problem: https://jsfiddle.net/charlesh88/wbtLrd50/

**Comment by charlesh88** [comment]
Work completed and pushed to open445. Pull request filed with #478.

**Comment by charlesh88** [comment]
I'm not dead yet! Reopening, screenshot to come.

**Comment by VWoeltjen** [comment]
Well that's fun!

Think this may be addressed (at least partially) by https://developer.nasa.gov/mct/warp/pull/2

**Comment by charlesh88** [comment]
Seeing this today on Hulk (10.10.81.15:9080) on Mac and Windows Chrome. This may be only manifesting with Packets; Pete says they have their own approach to .loading. Look for double application to nested elements of the CSS class.

**Comment by charlesh88** [comment]
Looking at WARP Packets in Chrome/Mac: s-status-pending *is* getting applied twice per tree node:

* <mct-rep key="tree-node" />
 * <mct-rep key="label" />

CSS was modified to only target the first child of .t-object-label to (hopefully) prevent this class from nesting; however, I'm not sanguine this will fix the problem as I can't locally duplicate it.

**Comment by charlesh88** [comment]
Looking today in the lab on the RTScience machine at a non-refreshed page from hulk: WARP is loading a CSS file /warp/general/res/css/warp-pending-tmp.css. Checking repo and current WARP master, that file is not there. Confirmed that disabling the style definition in that file fixes the problem on Linux. Will verify during the testathon today and close this issue if so.

**Comment by charlesh88** [comment]
Testathon 031516
Sigh, pretty sure saw messed up spinner in tree on Linux. Maybe due to Victor's refactored tree?

**Comment by charlesh88** [comment]
@VWoeltjen So, I can't figure out now how to force a tree node to display as if it's loading. Can you point me in the right direction here?

**Comment by charlesh88** [comment]
During Testathon 031716, determined that wait-node.html is being loaded via line 99 of Treeview.js. This should be changed to take advantage of .loading. Line 75 is where this would be reset.

**Comment by charlesh88** [comment]
Observed different wait spinner implementation in Search results; changes applied to tree should apply here as well. 
![unhappy wait spinners in tree](https://cloud.githubusercontent.com/assets/1056412/13864153/8f8f8dfa-ec5c-11e5-8af5-8f0c29e97c45.png)

**Comment by charlesh88** [comment]
Shortly starting work on this in branch 445b.

**Comment by charlesh88** [comment]
Closing in the hope that this is fixed; let's eval in next Testathon.

**Comment by charlesh88** [comment]
Checking this out on Linux station RTScience. In Chrome:
* Manually added loading class to a div element in the view area: wait spinner working perfectly.
* Manually added s-status-pending class to a tree node in the .rep-object-label element: wait spinner working perfectly.
* Observed spinner working correctly in the results container while using search.

**Comment by charlesh88** [comment]
Testathon 2016-06-02
Can't see packets on Linux workstations. In fact, Mark is baffled as to why that workstation can see hulk at all.

Removing unverified label. If we see this problem again, we can re-open.
