### ISSUE TITLE
Telemetry table is not refreshed after properties are edited

### ISSUE THREAD

**Issue by thehoanguyen** [nasa/openmct#4459]
#### Summary

The Telemetry table object allows editting properties, e.g Hide Header, hide/show some columns.
However, when we save the edited properties, the table is not refreshed to take into account the new properties' values.
Refresh the complete Web page, does allow to take the new properties value into effect.

#### Expected vs Current Behavior

After clicking on button "Save and Finish Editing", the object Telemetry Table should refresh automatically to take into effect the edited properties.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [ ] Does this impact a critical component?
- [x] Is this just a visual bug? yes

#### Steps to Reproduce

1.
2.
3.
4.

#### Environment
* Open MCT Version: 
* Version 1.7.4
* Deployment Type: 
* OS: Windows
* Browser: Chrome, Edge, etc

**Comment by unlikelyzero** [comment]
@unlikelyzero  to follow up

**Comment by jvigliotta** [comment]
@thehoanguyen I noticed you were using version 1.7.4, this issue has been fixed in our latest stable release, 1.7.8. Please upgrade at your convenience. If you notice anything else let us know!
