### ISSUE TITLE
New objects sporadically overlap in treeview

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#4464]
#### Summary
Creating a new object in the tree sporadically causes it to overlap an existing item:

![Screen Shot 2021-11-15 at 2 48 39 PM](https://user-images.githubusercontent.com/1056412/141865337-5587aaa1-c750-4a31-acde-23a487213f69.png)

In the screenshot, note the two tree nodes (orange arrows) getting the same `top` property. Refreshing the page will fix the problem.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

Create a new item in My/Shared items, or a descendant of My/Shared items.
See that none of the following occurs.
* General borkage of tree (you cannot expand nor collpase nodes)
* General borkage of object view (uneditable, unsavable, etc.)
* The created object is overlayed on top of an existing object
* The created object is created twice
* A gap exists between tree items (you may have to scroll down)
For true tree enthusiasts
* Add the first descendant to a parent
* Add a descendant to a parent that is alphabetically before all other siblings
* Add a descendant to a parent that is alphabetically between other siblings
* Add a descendant to a parent that is alphabetically after all other siblings
* Add a descendant to appear after a niece or nephew
\* Having many expanded sibling nodes above the node to be added seemed to helped reproduce borkage

#### Environment
* Open MCT Version: 1.8.1-SNAPSHOT
* Deployment Type: /testathon
* OS: Mac
* Browser: Chrome

**Comment by unlikelyzero** [comment]
Fixed in testathon 11/18

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by charlesh88** [comment]
Verified fixed Testathon 11-18-21
