### ISSUE TITLE
Notebook Snapshotting to the default Notebook isn't working

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#4469]
#### Summary
Snapshotting to the default Notebook doesn't do anything, and fails without a console error. I was able to successfully save a Snapshot to the Snapshots holder.

#### Expected vs Current Behavior
Should work as expected.

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

1. Create a new Notebook. Add an entry, and verify that that Notebook is designated as the default.

![image](https://user-images.githubusercontent.com/1056412/142062013-1d24a9d4-2d6f-4ae5-b926-4ec71ae3d0e2.png)

2. Navigate to a data view such as a plot. Use the Snapshot menu button, and verify that the expected default Notebook appears as a menu option. Select that option.

![image](https://user-images.githubusercontent.com/1056412/142062097-cd1dac97-9a80-4393-bfcb-8c7073d82bfa.png)

3. Note that a Notification message indicates that the Snapshot was saved:

![image](https://user-images.githubusercontent.com/1056412/142062289-bb25fdde-5907-4dad-b0a5-c713803f24ea.png)

4. Nav back to the default Notebook. Observe: no entry with a Snapshot has been added.

#### Environment
* Open MCT Version: 1.8.1
* Deployment Type: /stable and /latest
* OS: Mac
* Browser: Chrome

**Comment by shefalijoshi** [comment]
Please verify: #2918 and #4526 after this is fixed.

**Comment by unlikelyzero** [comment]
Verified Fixed
