### ISSUE TITLE
[Infrastructure] method name sortDescending should be renamed to sortAscending

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#4481]
#### Summary

Method naming is confusing

#### Expected vs Current Behavior

A to Z is sort in ascending order so thats how it should be named.

#### Impact Check List

- [] Data loss or misrepresented data?
- [] Regression? Did this used to work or has it always been broken?
- [] Is there a workaround available?
- [] Does this impact a critical component?
- [] Is this just a visual bug?

#### Steps to Reproduce

Internal change only. Can verify this ticket by verifying #4464 

#### Environment
* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

**Comment by shefalijoshi** [comment]
Verified fixed.
