### ISSUE TITLE
WorkerService is no longer needed

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#4482]
## Overview
Refactor to remove AngularJS. No current benefit in tracking workers in api so removing altogether.

## Expected Behavior
Anything using WorkerService (using Web Workers) should still work.
* Bare Bones Search (fallback search not provided by objectProvider) should still work.

## Steps to Reproduce
1. Do a search for an object that isn't provided by an ObjectProvider and see that it returns a result

**Comment by charlesh88** [comment]
Testathon 12-13-21: needs testing notes, not sure how to find an object that isn't provided by an ObjectProvider.

**Comment by khalidadil** [comment]
I was able to search for "Plan 5" under VIPER Plans on Banner Testathon, and it returned "Plan 5" as a search result. Does that confirm this is working @davetsay?

**Comment by unlikelyzero** [comment]
### Testing Notes
On banner just search for plans and see that viper plans comes up

**Comment by charlesh88** [comment]
Verified fixed Testathon 01-06-22.

**Comment by shefalijoshi** [comment]
Verified fixed
