### ISSUE TITLE
Alphabetical sorting should ignore case

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#4483]
#### Summary
Current tree sorting is sorting lower case letters after their uppercase brethren:

![image](https://user-images.githubusercontent.com/1056412/142512038-e915138b-eee1-48aa-9471-be19bc869b41.png)

#### Expected vs Current Behavior
Tree sorting should ignore case.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

1. Add items to a folder, use uppercase and lowercase naming starting with the same letters, like "foobar" and "Foobar". Use a variety of different letters.
2. Observe: all names beginning with lowercase letters will be sorted after _all_ those beginning with uppercase letters.

#### Environment
* Open MCT Version: 1.8.1 340246ab2620f295ab334d4e7c9ef84b9434a066
* Deployment Type: /testathon
* OS: Mac
* Browser: Chrome

#### Additional Information
Related: #1717, #4463, #4464

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 12/13/2021

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by charlesh88** [comment]
Testathon 12-13-21: verified fixed.  Found related bug https://github.com/nasa/openmct/issues/4571
