### ISSUE TITLE
Add independent time conductor to plots

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4503]
**Is your feature request related to a problem? Please describe.**
Independent time conductors were recently added to [time views](https://github.com/nasa/openmct/blob/25b34311310dd2970788e6a5ab20298012510b2f/src/ui/components/ObjectView.vue#L3). To support some science use cases, these should also be added to our overlay, stacked plots and bar graphs

**Note that in order to avoid adding unnecessary boilerplate code to additional views issue https://github.com/nasa/openmct/issues/4226 must be addressed first.**

**Comment by charlesh88** [comment]
Testathon 1-24-22: verified fixed.
