### ISSUE TITLE
[Release] Remove tests from npm scripts

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#4511]
#### Summary
We are including e2e and jasmine tests in the npm packaging. Let's not do that.

**Comment by unlikelyzero** [comment]
@nikhilmandlik is an ideal ~victim~ tester

**Comment by khalidadil** [comment]
The e2e folder/tests have been removed, but I'm still seeing spec.js files for all plugins under src > plugins.

**Comment by trusktr** [comment]
The `*.Spec.js` line in `.npmignore` is not catching files like `FooSpec.js`. Making a new issue with a better way to write npmignore files

**Comment by unlikelyzero** [comment]
Original design failed. @trusktr to file a new issue with a better npm ignore process
