### ISSUE TITLE
[Snapshots] Blank PNG/JPG image generated for snapshots

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#4526]
#### Summary
We are no longer able to download a PNG/JPG of a snapshot

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

1. Create a Snapshot of an object
2. Open Preview of Object
3. Click on PNG/JPG Button
4. Open PNG/JPG

#### Environment
* Open MCT Version: 1.8.1
* Deployment Type: npm
* OS: N/A
* Browser: Chrome 97

**Comment by unlikelyzero** [comment]
Bumping severity to blocker since this is part of GDS Testing.

**Comment by unlikelyzero** [comment]
### Testing Notes

1. Create a Snapshot of an object
2. Open Preview of Object
3. Click on PNG/JPG Button
4. Open PNG/JPG

**Comment by shefalijoshi** [comment]
Verified saving a snapshot to the notebook snapshots bin, clicking the snapshot preview image and then downloading via the PNG and JPG buttons works.
Unable to verify this for the default notebook.

**Comment by unlikelyzero** [comment]
Verified Fixed

**Comment by shefalijoshi** [comment]
Verified fixed on default notebook as well.
