### ISSUE TITLE
Replace legacy format service

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4530]
#### Summary
The formatting API currently relies on Angular managed services behind the scenes. As part of our effort to remove Angular 1.x the legacy format service needs to be retired and replaced with a vanilla JavaScript solution.

#### Deprecation Notice

This will complete remove support for legacy format registration. The interface of our formatter classes has not changed, only the method of registration. Any code still using legacy format registration should switch to using [our current format registration API](https://github.com/nasa/openmct/blob/master/API.md#telemetry-formats-draft).

**Comment by akhenry** [comment]
#### Testing Notes
This issue affects existing functionality only, so there is no new functionality to test. Instead testers should verify that formatting is still working as expected.

1. Open a plot and verify that X-axis timestamps are rendering correctly
2. Open a table and verify that both telemetry values and timestamps are rendering correctly.
3. Open a LAD Table and verify that both telemetry values and time stamps are rendering correctly.

**Comment by shefalijoshi** [comment]
Verified Fixed
