### ISSUE TITLE
Update copyright to 2022 - automate this?

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#4532]
Copyright for openmct files needs to be updated to 2022 (when 2022 comes around).
If possible, this should be automated.

**Comment by depperm** [comment]
Related Issue #3979 

Will look into automating this. Any suggestions are welcome

**Comment by depperm** [comment]
US copyright law: https://copyright.gov/title17/title17.pdf

A [related question](https://softwareengineering.stackexchange.com/questions/34189/how-do-you-update-copyright-notices) seems to indicate maybe this doesn't necessarily have to be updated

**Comment by scottbell** [comment]
Will write a little tool to automate this.

**Comment by scottbell** [comment]
I've got an npm script to do this here:
https://github.com/nasa/openmct/pull/4715/files

**Comment by unlikelyzero** [comment]
@scottbell can you write test instructions here?

**Comment by scottbell** [comment]
To test, run the script and ensure neither the string 2020 nor 2021 exist in the codebase. Also check through git diff that only copyrights we’re affected.

**Comment by michaelrogers** [comment]
_Testathon 2022-01-24_

The script is working as expected, though the release/1.8.4 branch still has instances of non 2022 years in the copyright text.

**Comment by unlikelyzero** [comment]
@scottbell can you take a look?

**Comment by unlikelyzero** [comment]
@scottbell can you make another PR against release/1.8.4 with those changes?

**Comment by scottbell** [comment]
https://github.com/nasa/openmct/pull/4775/files

Yeah, this was caused by people creating new files before my PR went in. It should happen less and less.

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 01/26/22 - All files referenced were updated
