### ISSUE TITLE
Remove mct-template component

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4536]
#### Summary
The mct-template Vue component was created to support legacy Angular templates that are no longer in use. As such it should be removed.

#### Testing Instructions
1. Make sure component is not used in codebase. `mct-template`, `MctTemplate`

**Comment by khalidadil** [comment]
Checking locally on a release/1.8.2 branch, I don't see `mct-template` or `MctTemplate` being used anywhere, so looks good to me! (Testathon on 12/13/2021)
