### ISSUE TITLE
Unable to create new Condition set

### ISSUE THREAD

**Issue by nikhilmandlik** [nasa/openmct#4542]
#### Summary
unable to create new condition set on /latest 

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce
1.  open openmct 
2. try to create new condition set
3. ok button is always disabled

#### Environment
* Open MCT Version: 
```
Version: 1.8.1-SNAPSHOT
Build Date: Tue Dec 07 2021 12:35:02 GMT-0800 (Pacific Standard Time)
Revision: 8acbcadd5d17e201f32f03deb753b8b12b591063
Branch: master
```
* Deployment Type: `VIPER`
* OS: `MAC OS`
* Browser: `Brave`

**Comment by unlikelyzero** [comment]
Assigning myself to create an e2e test when this PR is opened

**Comment by nikhilmandlik** [comment]
partially fixed, can create new condition but once created it should be in edit mode

**Comment by unlikelyzero** [comment]
Verified fixed but with https://github.com/nasa/openmct/issues/4600
