### ISSUE TITLE
[Display Layout] grid disable toggle does not hide grid in display layout

### ISSUE THREAD

**Issue by nikhilmandlik** [nasa/openmct#4543]
#### Summary
grid disable toggle does not hide grid in display layout

#### Expected vs Current Behavior
grid disable toggle should hide grid in display layout and only show grid if its enabled.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [x] Is this just a visual bug?

#### Steps to Reproduce

1. create or use existing display layout 
2. edit mode
3. if grid is enabled try disabling it. <img width="36" alt="Screen Shot 2021-12-07 at 12 55 29 PM" src="https://user-images.githubusercontent.com/1292612/145104818-67f97efb-aee3-4b56-99a8-1f71f3ce94c5.png">
4. in display layout grid is still visible

#### Environment
* Open MCT Version:
```
Version: 1.8.1-SNAPSHOT
Build Date: Tue Dec 07 2021 12:35:02 GMT-0800 (Pacific Standard Time)
Revision: 8acbcadd5d17e201f32f03deb753b8b12b591063
Branch: master
```
* Deployment Type: `VIPER`
* OS: `MACOS`
* Browser: `Brave`

**Comment by unlikelyzero** [comment]
### To test:

Add a Display Layout
Click the toggle grid button (top right)

**Comment by nikhilmandlik** [comment]
not fixed,
Version Information
Version: 1.8.3-SNAPSHOT
Build Date: Thu Jan 06 2022 14:36:05 GMT-0800 (Pacific Standard Time)
Revision: 2f63718385d0fbfe4fc77230d453f392d7a34218
Branch: release/1.8.3

**Comment by charlesh88** [comment]
Testathon 1-24-22: verified fixed.
