### ISSUE TITLE
[Docs] Update documentation on how to troubleshoot CI issues

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#4544]
#### Summary
There are regularly issues with CI which may or may not match what is running locally. We should update our documentation with a FAQ or Troubleshooting steps on how to approach these problems.

##### e2e
- What to do if local server stuck ```lsof -i :8080 | grep LISTEN```

**Comment by shefalijoshi** [comment]
Closing as a duplicate of #4576
