### ISSUE TITLE
[CI] Ignore tests in codecov reporting

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#4549]
#### Summary
Right now, codecov is picking up parts of Spec files which is missing coverage. This _is interesting_ but not applicable for our team.

We should ignore the test filetype so that the github inline codecov notes don't appear.

#### Testing Notes
Open or find a PR which modifies a Spec file
Verify that the Spec file does not contain any comments from codecov patch

**Comment by unlikelyzero** [comment]
Testing Notes
Open or find a PR which modifies a Spec file
Verify that the Spec file does not contain any comments from codecov patch

**Comment by khalidadil** [comment]
Looking at [this PR](https://github.com/nasa/openmct/pull/4569/files), this looks good. (Testathon on 12/13/2021)
