### ISSUE TITLE
Re-implement the event generator as a new-style plugin

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4552]
#### Summary
The [Event Generator plugin](https://github.com/nasa/openmct/blob/master/example/eventGenerator/bundle.js) provides an example of a telemetry source that produces strings. It was implemented using the legacy API (including the old type API, telemetry API, etc.).

The legacy API has not been used for new development for years and support will soon be removed completely. We want to maintain this useful example code, so we should migrate it to a plugin that defines the event type using the [modern type api](https://github.com/nasa/openmct/blob/master/API.md#domain-object-types), as well as using [the modern telemetry API](https://github.com/nasa/openmct/blob/master/API.md#telemetry-api).

#### A note on migrating Types
Types registered using the legacy bundle registration like so:

```JSON
"types": [
  {
      "key": "folder",
      "name": "Folder",
      "cssClass": "icon-folder",
      "features": "creation",
      "description": "Create folders to organize other objects or links to objects.",
      "priority": 1000,
      "model": {
          "composition": []
      }
  }
]
```

Should be migrated to the types API:
```JavaScript
  openmct.types.addType('folder', {
      name: "Folder",
      key: "folder",
      description: "Create folders to organize other objects or links to objects without the ability to edit it's properties.",
      cssClass: "icon-folder",
      creatable: true,
      initialize: function (domainObject) {
          domainObject.composition = [];
      }
  });
```

Code that was retrieving type definitions using the legacy TypeService like so:
``` JavaScript
typeService.getType(domainObject.type)
```
Should now use the Open MCT type API:
``` JavaScript
this.openmct.type.get(domainObject.type)
```

**Comment by akhenry** [comment]
@scottbell Would you mind taking a look at this?

**Comment by scottbell** [comment]
> @scottbell Would you mind taking a look at this?

Wilco!

**Comment by scottbell** [comment]
@akhenry this looks pretty straightforward. One question though, do you want me to integrate this in with the [other generators](https://github.com/nasa/openmct/tree/master/example/generator), or keep is standalone?

**Comment by scottbell** [comment]
Talked with @akhenry about above 👆, will keep it separate.

**Comment by scottbell** [comment]
FYI, I've got a working branch here:
https://github.com/nasa/openmct/compare/master...scottbell:mct4552?expand=1

**Comment by scottbell** [comment]
Testing:
- Ensure you can still create an Event Message Generator
- Ensure you receive event data with Local Clock & Fixed time spans
- Ensure you can drop the Event Message Generator onto a Telemetry Table

**Comment by scottbell** [comment]
I've opened a PR for review here:
https://github.com/nasa/openmct/pull/4620

**Comment by akhenry** [comment]
Verified that the implementation works as specced. 

Have filed a followup issue to address a low priority bug - https://github.com/nasa/openmct/issues/4879
