### ISSUE TITLE
[Imagery] Adjusting the bounds will sometimes cause the focusedImage to shift which image is selected

### ISSUE THREAD

**Issue by michaelrogers** [nasa/openmct#4555]
#### Summary

Seems to be limited in scope to local clock; the fixed timespan flow seems to be working as expected.

#### Expected vs Current Behavior

If the index is properly matched in the updated imageHistory array, the index should be maintained and the image should not be replaced.

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

1. Navigate to example imagery
2. Adjust the time bounds of local clock
3. Observe sometimes the image will change

#### Environment
* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

**Comment by michaelrogers** [comment]
### How to Test

#### For Fixed Time
* Navigate to an existing Image Telemetry item
* Set to `Fixed Time` if not already selected
* Select an image thumbnail to focus on in the time strip
* Adjust the upper or lower bounds of the date picker; e.g. select a date further in the future
* Observe that if the image still exists in the range, that it does not change
* Or observe that if the image is no longer in range, the last image is selected

### For Local Time
* Navigate to an existing Image Telemetry item
* Set to `Local Time` if not already selected
* Select an image thumbnail to focus on in the time strip
* Adjust the upper or lower bounds of the relative time picker; e.g. increase the upper bounds by 5 minutes
* Observe that if the image still exists in the range, that it does not change
* Or observe that if the image is no longer in range, the last image is selected

**Comment by jvigliotta** [comment]
Nice work!
Testathon - 1.7.22 - Verified Fixed
