### ISSUE TITLE
Many ExportAsJSONAction spec tests are X'd out.

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4558]
#### Summary

Most of the tests in [the ExportAsJSONAction spec](https://github.com/nasa/openmct/blob/master/src/plugins/exportAsJSONAction/ExportAsJSONAction.spec.js#L105) are X'd out. These should be fixed.

Note that recent changes to API mean that the legacy TypeService is no longer needed, so [any spec code mocking it out](https://github.com/nasa/openmct/blob/master/src/plugins/exportAsJSONAction/ExportAsJSONAction.spec.js#L55) should be modified accordingly.

**Comment by nikhilmandlik** [comment]
I think this is covered in https://github.com/nasa/openmct/pull/4225 by @kobe1104

**Comment by davetsay** [comment]
@nikhilmandlik , can you write testing instructions for this if applicable?

**Comment by nikhilmandlik** [comment]
> @nikhilmandlik , can you write testing instructions for this if applicable?

If `npm test` passes it all good 😅

**Comment by unlikelyzero** [comment]
### Testing Notes
Verify that there are no more x'd out tests in ExporrtAsJSONAction

**Comment by akhenry** [comment]
Verified fixed.
