### ISSUE TITLE
[Import from Json] Imported options need to have the File Selector clicked twice to Import

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#4561]
#### Summary
This fixed the import JSON action https://github.com/nasa/openmct/issues/4470 , but in the current implementation, the File Selector must be clicked a second time to import the object

#### Expected vs Current Behavior
Objects should import on first use of File Selection. Instead, domain objects are imported on second use of File Selection button.

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce
1. Export a Domain Object as JSON as "ObjectA"
2. Import a Domain Object as JSON either with the kebob or tree options
3. On 'Import as JSON modal, click the 'Select File...' button and select "ObjectA"
4. Note that the 'Ok' button in not actionable
5. Click on the 'Select File...' button again, but do not make a selection
Note: Can now import as JSON

#### Environment
* Open MCT Version: 1.8.1
* Deployment Type: npm

#### Additional Information
![Screen Recording 2021-12-10 at 02 44 41 PM](https://user-images.githubusercontent.com/12446869/145650680-aace99ea-5c50-492d-8b2f-2cdeec6524de.gif)

**Comment by unlikelyzero** [comment]
Marking as fixed in https://github.com/nasa/openmct/pull/4478 to verify in testathon

**Comment by unlikelyzero** [comment]
### Testing Notes

1. Export a Domain Object as JSON as "ObjectA"
2. Import a Domain Object as JSON either with the kebob or tree options
3. On 'Import as JSON modal, click the 'Select File...' button and select "ObjectA"
4. ObjectA Is imported and available on the Tree

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 12/13/2021

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 12/13/2021

**Comment by nikhilmandlik** [comment]
Verified Fixed.
