### ISSUE TITLE
Adding an item with the same name doesn't update tree view

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#4571]
#### Summary
Adding items (either via Create, or by drag and drop) that have the same name into an object, when that objects tree node is expanded, will result in the tree not updating properly. Collapsing and expanding the tree node will cause it to update properly.

**Having added a bunch of folders and objects into a folder. Note disparity between tree and grid view.**

<img width="1051" alt="Screen Shot 2021-12-13 at 3 15 26 PM" src="https://user-images.githubusercontent.com/1056412/145904250-fbc40650-e2b7-4d5b-b838-e0892ce1a8e4.png">

**Two different Condition widgets with the same name dragged into a Display Layout. Note disparity with tree.**

<img width="1614" alt="Screen Shot 2021-12-13 at 3 18 52 PM" src="https://user-images.githubusercontent.com/1056412/145904505-0a571774-7512-45ca-b3ad-4f0f959be1cc.png">

#### Expected vs Current Behavior
Tree should update without having to manipulate the tree node.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce
1. Expand a folder or other container (like a Layout) in the tree. Create or drag ites
2. Create or drag a number of items that have the same name (independent of upper/lowercase letters) into the container created in 1.
3. Observe: the newly added items will not show up in the tree.

#### Environment
* Open MCT Version: 1.8.2 1a4a9b2fb76a3480935227e3b9701d961507b115
* Deployment Type: /testathon
* OS:
* Browser:

**Comment by khalidadil** [comment]
#### Testing Instructions

1. Expand a folder or other container (like a Layout) in the tree.
2. Create or drag a number of items that have the same name (independent of upper/lowercase letters) into the container created in 1.
3. Observe: the newly added items should show up in the tree.

**Comment by shefalijoshi** [comment]
Verified fixed.
