### ISSUE TITLE
various notebook snapshot bugs (found in VISTA)

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#4572]
#### Summary
1. Thumbnail view is in black/white
2. Cannot save snapshot to notebook (no errors logged)
3. Export to png/jpeg exports a blank white image

#### Expected vs Current Behavior

1. Thumbnail is exact color scheme as Open MCT view at time of snapshot
2. Snapshots are saved to default notebook (or notebook selected)
3. Snapshots are exported as images and appear as they do in Open MCT

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

1. Click on thumbnail view of snapshot
2. 1) Click snapshot dropdown, 2) select save to notebook (a notebook has to exist), 3) view snapshot in notebook
3. 1) Click on thumbnail view of snapshot, 2) click either export as png button or export as jpeg button, 3) open image from computer file system

#### Environment
* Open MCT Version: 8eba3a81f3b0f406faead4725011b5688467ea9a
* Deployment Type: VISTA
* OS:
* Browser:

#### Additional Information
1. B/W snapshot thumb
![image](https://user-images.githubusercontent.com/3614296/145906083-3ff0c69e-9ba6-49ca-a29a-9651815cf770.png)

**Comment by davetsay** [comment]
@charlesh88 , @nikhilmandlik , can you look at this? Is this just in VISTA? (Snow for issue 1 in list?)

**Comment by charlesh88** [comment]
Is the B/W problem just the folder view, or is this happening elsewhere? What OS and browser?

**Comment by davetsay** [comment]
Mac OS Chrome

**Comment by davetsay** [comment]
@charlesh88 , i took snapshots of a table and of a notebook. Those were fine. So currently yes, only the folder grid view is the only snapshot i've seen as B/W

**Comment by nikhilmandlik** [comment]
> 3. @nikhilmandlik to verify that image export works in snow theme. If it does, we can close this issue.
works as expected
![Unnamed Overlay Plot](https://user-images.githubusercontent.com/1292612/155203247-f50f07db-a33b-4ff3-96b3-204e161d6149.png)

**Comment by davetsay** [comment]
Looks like everything has been resolved that needs to. If this is observed in future VISTA testing will open new issue.
