### ISSUE TITLE
[CI] Document how to troubleshoot CI issues

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#4576]
#### Summary
We need to improve the documentation for the community to better explain how to troubleshoot issues in CI.

* [x] How to tell if a test is flaky
* [x] How to bust cache
* [x] How to interpret a build failure
* [x] How to attempt to reproduce locally

##### e2e issues
* [x] when running locally ```lsof -i :8080 | grep LISTEN```

Prior Art https://github.com/karma-runner/karma-chrome-launcher/commit/5400b23199c682bc6bc00739fd6a8d9f6c520bed

**Comment by unlikelyzero** [comment]
### Testing notes
Find the Troubleshooting section and make sure it makes sense

**Comment by shefalijoshi** [comment]
Question about the Busting Cache section here: https://github.com/nasa/openmct/blob/8967b6a72c2177319ba1813639b154fab13e4a81/TESTING.md#busting-cache
How does one know that Circle CI cache is stale and they need to bust cache?
