### ISSUE TITLE
"Export as JSON" yielding corrupted data

### ISSUE THREAD

**Issue by AdamElliott-AB** [nasa/openmct#4577]
When performing "Export as JSON", the downloaded file now includes contents from previous objects that were exported intermixed with expected object contents

**Comment by nikhilmandlik** [comment]
### Testing instructions:
1.  create or use 2 different objects from Tree
2. eg: 1-SWG and 2-Clock
3. export SWG object (save as SWG.json)
4. export Clock object (save as clock.json)
5. open clock.json and observe under 'openmct' SWG object details are included along with clock object details.

**Comment by akhenry** [comment]
The fix for this will be in 1.8.3. For now you should be able to workaround it by refreshing your browser between exports.

**Comment by shefalijoshi** [comment]
Marking as closed as the fix was merged.

**Comment by kobe1104** [comment]
Verified fixed - testathon 12/16/2021

**Comment by khalidadil** [comment]
I exported a clock and see this:
```
{"openmct":{"8f47c188-bf72-40e7-b3a6-d49079af10f3":{"configuration":{"baseFormat":"YYYY/MM/DD hh:mm:ss","use24":"clock24","timezone":"UTC"},"name":"A Clock","type":"clock","location":"c8e4ecff-f10d-4e1c-ad03-20f9e8ae1f78","modified":1639433773640,"identifier":{"namespace":"","key":"8f47c188-bf72-40e7-b3a6-d49079af10f3"},"persisted":1639433773642}},"rootId":"8f47c188-bf72-40e7-b3a6-d49079af10f3"}
```
which seems correct. Verified 12/16/2021
