### ISSUE TITLE
Unable to add LAD tables to LAD table sets

### ISSUE THREAD

**Issue by AdamElliott-AB** [nasa/openmct#4579]
Drag-and-drop of LAD table onto LAD table set no longer works
Also unable to "Move" a LAD table under a LAD table set.

It seems that LAD table sets are no longer valid containers for LAD tables.

**Comment by AdamElliott-AB** [comment]
Droppable area on LAD table set is just smaller than before. Now needs to be dropped at the very top of view, where used to be able to be dropped anywhere in the LAD table set area.

**Comment by unlikelyzero** [comment]
### Testing Notes

Investigate that this new droppable area is smaller but acceptable

**Comment by jvigliotta** [comment]
Success: Testathon - 1.6.22

- drop LAD anywhere in LAD set
- move LAD into LAD set

All above successful with the following.

thing | other thing
-- | --
Version: | 1.8.3-SNAPSHOT
Build Date: | Thu Jan 06 2022 14:36:05 GMT-0800 (Pacific Standard Time)
Revision: | 2f63718385d0fbfe4fc77230d453f392d7a34218
Branch: | release/1.8.3
