### ISSUE TITLE
Re-implement LocalStorage in ES6 and without Angular

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4589]
#### Summary

The LocalStorage adapter is currently implemented using prototypical object inheritence and should be re-implemented using ES6 Classes using our modern API.

**Comment by akhenry** [comment]
#### _Tasting_ Notes 🍷 

This is a re-implementation of the Local Storage adapter, so it will need to be tested locally.
* Verify that objects already defined in your local storage appear in the tree
* Verify that new objects can be created successfully
* Verify that existing objects can be modified successfully.

**Comment by charlesh88** [comment]
Testathon 01-04-22: cannot verify - existing objects can be removed and modified, but new objects cannot be created due to another issue.

**Comment by charlesh88** [comment]
Verified fixed Testathon 01-06-22.
