### ISSUE TITLE
Remove usage of the IdentifierService from any non-legacy code

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4590]
#### Summary
The IdenfitierService [is doing translation](https://github.com/nasa/openmct/blob/master/platform/core/src/identifiers/Identifier.js#L40) between persistence spaces and namespaces. This distinction has never been supported by our modern API and was deprecated years ago.

This change may cause compatibility issues for any legacy custom persistence providers that were implicitly relying on the identifierService to perform translations between the '' and 'mct' namespaces. If this is the case, it is recommended that plugins are updated to use the current Open MCT API, which requires a single unambiguous namespace to be specified.

Any database-specific compatibility issues with existing data that may use a mixture of namespaces (as Couch did) should be handled in the plugin itself. The [Open MCT Couch DB plugin can be used as an example](https://github.com/nasa/openmct/pull/4583/files#diff-e7f7d1740e6ab189b1a7ced0946ce7e262bf99253294f75086cb193eea912b65R31).

**Comment by akhenry** [comment]
#### Testing Notes
This involves no new features but does affect the fundamental functioning of the Object API and the Couch DB adapter.
* Verify that the tree is being populated with objects from Couch DB,
* Verify that new Couch DB objects can be created,
* Verify that existing Couch DB objects can be modified,
* Verify that existing Couch DB objects can be deleted.

**Comment by shefalijoshi** [comment]
Unable to create new objects, but that might be a side-effect of #4615

**Comment by shefalijoshi** [comment]
Apart from the `LegacyObjectAPIInterceptor.js`,  it appears that `identifierService` is not being used in any non-legacy code.
Closing.

**Comment by michaelrogers** [comment]
Verified change during Testathon 2022-01-06 on release/1.8.3.
 
Observed populated tree, creating a new domain object, modifying, and deleting existing ones.
