### ISSUE TITLE
[CI] Update Circle CI branch protection rules for 1.8.3 to match the overall circleci check

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#4596]
#### Summary
need to update the circle ci branch protection rules for 1.8.3 to match this name https://github.com/nasa/openmct/blob/1f588a2a6e6d17ada40ea520ba25531749c53af2/.circleci/config.yml#L142

**Comment by unlikelyzero** [comment]
### Testing Notes
Create a PR against the release/1.8.3 branch with broken tests and verify that you cannot merge

**Comment by akhenry** [comment]
Verified fixed by https://github.com/nasa/openmct/pull/4685

![Screen Shot 2022-01-06 at 3 16 54 PM](https://user-images.githubusercontent.com/4215777/148465858-7040611f-248e-4f54-8fef-3d8e0fa69e62.png)

**Comment by akhenry** [comment]
That screenshot is not going to cause confusion...
