### ISSUE TITLE
Add user name attribution to Notebook entries

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4599]
**Is your feature request related to a problem? Please describe.**
Notebook entries should display the name of the user who created them.

**Describe the solution you'd like**
The new User API allows for components to retrieve basic information about the logged in user. This API should be used to fetch the logged in user's name, and persist it along with notebook entries. The name should how shown in the notebook entry somewhere.

**Comment by unlikelyzero** [comment]
Note: I'd like to be involved in writing some e2e tests on the first pass

**Comment by jvigliotta** [comment]
## Testing
- if you are using openmct WITHOUT a user provider, make sure normal notebook snapshots and entries work as expected
With a user provider
- take a snapshot (make sure it works)
- save to default notebook (navigate to default notebook, verify username is on entry)
- in a notebook, add an entry, make sure your username is on the entry

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 03/14/2022

**Comment by nikhilmandlik** [comment]
Verified Fixed.
