### ISSUE TITLE
[Condition Set] When creating a new condition set, the resulting domain object does not result in 'Edit mode'

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#4600]
#### Summary
When creating a new condition set, the resulting domain object does not result in 'Edit mode'. Otherwise, everything is working correctly.

#### Expected vs Current Behavior
After a new Condition Set is created, the Condition Set should immediately open in 'Edit mode'. It opens in 'View mode'.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce
1. Create New Condition Set from Create Menu
2. After it's saved, note the mode the user ends in.

#### Environment
* Open MCT Version: 1.8.2
* Deployment Type: viper-openmct release/1.8.2

**Comment by shefalijoshi** [comment]
Related to #4615

**Comment by shefalijoshi** [comment]
Resolved by #4675

**Comment by charlesh88** [comment]
Verified fixed Testathon 01-06-22.
