### ISSUE TITLE
fix .spec.js file not being executed.

### ISSUE THREAD

**Issue by trusktr** [nasa/openmct#4606]
There's a single `.spec.js` file within the `src/` folder not being executed. It needs to be renamed to `FooSpec.js` format to be picked up and executed. It will need import paths fixed, and imports will be undefined due to trying to import defaults from ES modules.

[`src/plugins/exportAsJSONAction/ExportAsJSONAction.spec.js`](https://github.com/nasa/openmct/blob/master/src/plugins/exportAsJSONAction/ExportAsJSONAction.spec.js)

cc @shefalijoshi

**Comment by mariuszr** [comment]
Hi @trusktr, I believe it has been considered in the merged [PR #4225](https://github.com/nasa/openmct/pull/4225) that considered changes in the [ExportAsJSONAction.js](https://github.com/nasa/openmct/blob/master/src/plugins/exportAsJSONAction/ExportAsJSONAction.js) plugin and provided the reimplemented [ExportAsJSONActionSpec.js](https://github.com/nasa/openmct/blob/master/src/plugins/exportAsJSONAction/ExportAsJSONActionSpec.js) unit test. Please check it.

Hi @davetsay, could you please confirm my above supposition?

**Comment by unlikelyzero** [comment]
Closed by PR #4225

**Comment by unlikelyzero** [comment]
Assigning to @trusktr to add testing notes

**Comment by trusktr** [comment]
In the pull request we can [see code coverage increased for `ExportAsJSONAction.js`](https://github.com/nasa/openmct/pull/4225#issuecomment-988276766) due to now-actually-executed test file.

Additionally we can verify in the test output all 9 `it` tests in the test file executed and passed:

```
  Export as JSON plugin
    ✓ Export as JSON action exist (4ms)
    ✓ ExportAsJSONAction applies to folder (4ms)
    ✓ ExportAsJSONAction applies to telemetry.plot.overlay (4ms)
    ✓ ExportAsJSONAction applies to telemetry.plot.stacked (5ms)
    ✓ ExportAsJSONAction applies does not applies to non-creatable objects (7ms)
    ✓ ExportAsJSONAction exports object from tree (7ms)
    ✓ ExportAsJSONAction skips non-creatable objects from tree (4ms)
    ✓ can export self-containing objects (5ms)
    ✓ exports links to external objects as new objects (5ms)
```

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon 1/26/2022
