### ISSUE TITLE
Make legacy support optional

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4615]
**Is your feature request related to a problem? Please describe.**
Support for the legacy API depends upon AngularJS and should be rendered optional. The legacy API has been deprecated for several years now, and has been replaced by [our modern API](). Support for the legacy API will be completely removed in a future release because it depends upon Angular 1.x which is now at EOL.

**Describe the solution you'd like**
Legacy support could be enabled by a plugin. This would also serve to clean up legacy support code and entirely remove it from our modern API.

Support for the legacy API should be opt-in. [A separate issue](https://github.com/nasa/openmct/issues/4613) has been filed to ensure that legacy support is not enabled by default in the `index.html` used for development purposes in our source repository.

**Comment by akhenry** [comment]
### Testing Instructions

This change potentially affects all aspects of the application. A best effort has been made to remove all vestiges of the legacy API from our modern codebase, but its possible that some subtle (and not-so subtle) bugs have been introduced that reflect differences between our modern and legacy APIs.

1. Verify that the application initializes ok
2. Verify that the various object views appear to load correctly
3. Verify that composition appears to work as intended via creation and drag and drop. Be on the lookout for cases where composition is allowed that shouldn't be, or where composition is being disallowed unexpectedly. 
4. Try out some of the object actions and verify that they appear to be working correctly.

**Comment by shefalijoshi** [comment]
Found this bug as a likely sideeffect of this issue: https://github.com/nasa/openmct/issues/4666

**Comment by shefalijoshi** [comment]
Closing this as the associated issue #4666 is closed. Please retest.

**Comment by akhenry** [comment]
I believe this is closed by https://github.com/nasa/openmct/issues/4600 ? @shefalijoshi ?

**Comment by shefalijoshi** [comment]
Verified fixed
