### ISSUE TITLE
[Doc] Update Readme to include badge from npm registry

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#4618]
#### Summary
It's possible to add a badge for the npm registry directly on the readme.

**Comment by depperm** [comment]
What badges for npm do you want exactly? Just npm (![t](https://badgen.net/npm/v/npm))?

**Comment by unlikelyzero** [comment]
@depperm just npm as a link to npm. There's a PR for it here https://github.com/nasa/openmct/pull/4619

**Comment by unlikelyzero** [comment]
### Testing Notes
Verify that the npm link appears on the root of the github page.
Verify that when clicking on the link, the browser navigates to the npm package on npmjs.org
Verify that the release version is correct

**Comment by akhenry** [comment]
Verified fixed!

**Comment by charlesh88** [comment]
Testathon 1-24-22: verified fixed.

**Comment by nikhilmandlik** [comment]
Verified Fixed.
