### ISSUE TITLE
[API] Design registration API

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#462]
See [refactoring plan](https://github.com/nasa/openmctweb/blob/api-redesign/docs/src/design/planning/APIRefactor.md#step-4-design-registration-api)

Depends on role of Angular (is Angular API part of how we register extensions to Open MCT Web?) #461

**Comment by VWoeltjen** [comment]
Note that review is the completion criteria here:

> Success criteria here should be based on peer review. Scope of peer review should be based on perceived risk/uncertainty surrounding proposed changes, to avoid waste; may wish to limit this review to the internal team. (The extent to which external feedback is available is limited, but there is an inherent timeliness to external review; need to balance this.)

**Comment by VWoeltjen** [comment]
Constraints from #263:

* Should not involve partial construction
* Should facilitate / be compatible with provision of reusable classes which can be extended
* In general, registration should be instances instead of constructors

**Comment by larkin** [comment]
> In general, registration should be instances instead of constructors

Agree, think the general case is you are registering singletons (e.g. services).  Common exceptional case is when you are registering views/controllers/components which are constructors-- they get reinitialized every time they are viewed.

**Comment by VWoeltjen** [comment]
Patterns for registration are documented in https://docs.google.com/document/d/1uD1SyH5jEKkfmFjzDb-9o72O_FlV0xLXSrmpdxEiiyg. Deferring implementation of these until they are validated (or need for changes is identified) based on prototyping in #999. Closing this issue, as further design work here will be prototype-driven
