### ISSUE TITLE
Condition Widgets not displaying properly

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#4623]
#### Summary
Condition Widgets are not displaying properly in the main view:
![Screen Shot 2021-12-21 at 11 34 11 AM](https://user-images.githubusercontent.com/1056412/147008334-adba7185-12b8-46e6-b18e-9bd04a8cdd8d.png)

#### Expected vs Current Behavior
Condition Widgets should display properly in the main view:
![Screen Shot 2021-12-21 at 2 57 25 PM](https://user-images.githubusercontent.com/1056412/147008348-b739e0f1-0615-48d5-a2d2-4f0b7eb72c01.png)

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [x] Is this just a visual bug?

**Comment by charlesh88** [comment]
The core problem here was the introduction of new markup in ObjectView.vue that, when employed in the main view, introduced a <div> layer that broke a brittle CSS selector definition in `condition-widget.scss`. The right solution involved removing the special casing in ObjectView.vue and making a new, more robust CSS definition: `c-object-view`. This class now surrounds all object views in the main view 

![image](https://user-images.githubusercontent.com/1056412/147008721-fd2a7f0f-4cce-4f93-afc9-4a4fe908ecd6.png)

and gets used in the Time Strip view for child views. Because of this, we need to test more fully for regressions with this one.

### Testing Notes

**Comment by shefalijoshi** [comment]
Verified Fixed

**Comment by jvigliotta** [comment]
Some issues found Testathon 1-4-2022
- Condition Widget looks good
- *Condition Widget in Layout is Top Left (not centered) same for preview*
- Condition Set Scroll looks good

Not able to test all of these due to other issues (ex: imagery)

**Comment by jvigliotta** [comment]
Testathon - 1.6.22
Still seeing the top left positioning from last time.
