### ISSUE TITLE
[My Items] Customizable folder name on install

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#4626]
**Is your feature request related to a problem? Please describe.**
Eh. Certain instances of Open MCT would like to have the ability to have the my items folder name be customizable.

**Describe the solution you'd like**
When installing "My Items Plugin" pass in a name.

**Describe alternatives you've considered**
Currently you can change after an instance is brought up.

**Additional context**
NADA

**Comment by jvigliotta** [comment]
## Testing
- on a fresh instance of Open MCT (clear local storage or use an empty couch db)
- install the My Items plugin while passing in a name as the first argument
- when Open MCT loads, verify the name is what you passed to the plugin

**Comment by khalidadil** [comment]
Verified working in testathon on 01/04/2022 using a release/1.8.3 branch

**Comment by charlesh88** [comment]
Verified fixed Testathon 01-04-22.
