### ISSUE TITLE
[API] Prototype fine-grained API improvements

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#463]
Plan/prioritize fine-grained API improvements (e.g. to specific extension categories), per the process outlined in the [refactoring plan](http://nasa.github.io/openmctweb/design/planning/APIRefactor.html#plan)

Specific topics to investigate here (from #263):

* Views/Representations/Templates to Components
  * Solution needs to ease integration of non-Angular components
  * Solution should not call these "views"
  * Will want to restructure source hierarchy in the context of this issue (such that scripts/templates/etc live happily side by side)
  * Want context menus to become reusable components in this process, per #138
  * Want to improve ability to communicate with components from rest of code. (e.g. view `configuration` should be accessible in a more obvious way than ["in scope, put there by a representer"](https://github.com/nasa/openmctweb/pull/645#issuecomment-178869071))
* Redesign/refactor Capabilities
  * General consensus is that dependencies should be clarified here by making acquisition of these interfaces external to domain objects
  * Candidate solution: ["Roles"](https://github.com/nasa/openmctweb/blob/api-redesign/docs/src/design/proposals/Roles.md)
  * "Delegation" capability should be removed
  * "Editor" capability should be clarified (or, more generally, checking whether a certain object is or is not being edited should be made more clear than the [two competing checks](https://github.com/nasa/openmct/pull/775/files#r57222052) we have currently.
* Telemetry API #811 
  * Want to reduce redundancy among interfaces here
  * Want to replace `TelemetrySeries` interface with an array-of-objects, where metadata describes fields in those objects
* Composite services
  * Should not be "the default" (should be able to use Open MCT Web without understanding Composite Services concept)
* Gestures
  * Want to decouple gestures from the actions they trigger
  * Want to support some degree of substitutions for gestures (e.g. implement a gesture one way on mobile, another way on desktop)
  * Also want a better place to wire in additional logic (like [virtual panels](https://github.com/nasa/openmctweb/pull/712/files#r54446535)) such that specific behavior of a gesture can vary by logic introduced via extension
* Navigation
  * Navigation changes should be URL-driven.
  * Need to explore strategies for preserving application state (e.g. tree node expanded/collapsed state) across these changes
  * Also want to consider [navigation lifecycle](https://github.com/nasa/openmctweb/pull/712#issuecomment-190839103)
* Persistence
  * Reject promises instead of promising false
* "De-batch" requests from providers
* Policy
  * Reduce reliance on string-matching; instead of `policyService.allow('foo', object, context)` we could have `fooPolicy.allow(object, context)`. If approach in #705 is taken, a `PolicyProvider<T,C>` base class could be implemented, and then policy instances could just be registered on that (individual policy categories are then a specialization composite services)
  * Consider switching to an asynchronous policy (`allow` returns a `Promise` which rejects on failure) to (a) improve amount of information passed on failure _and_ (b) supports asynchronous operations as part of policy decision. (Risk here is that we could introduce latency into policy decisions as a consequence.)

**Comment by larkin** [comment]
Our previous Telemetry API discussion focused on replacing TelemetrySeries with a basic array of objects and occurred before a lot of new functionality (time conductor, multi-domain support) was added, and I have more experience now from implementing 4 new telemetry providers and numerous telemetry views.  

Unless anyone sees a problem with it, I'm going to draft a proposal for the Telemetry API based on what I've learned here and present that for feedback.

**Comment by VWoeltjen** [comment]
Sounds good to me!

@larkin / @akhenry - it didn't surface among API proposals but some recent discussions have suggested reconsidering our policy model/API as well. Should I add it to the list above?

**Comment by VWoeltjen** [comment]
Also want to look at Actions here (or, more specifically, the infrastructure around them - how do we model context and how do we use it to determine which actions are available?) See [notes](https://github.com/nasa/openmctweb/issues/138#issuecomment-172057926) on approaches we may take for this.

**Comment by VWoeltjen** [comment]
Based on observations from #481, may want to consider how we model "workflows" in the context of this issue. 

Currently, we don't, or rather, we do so with some code (typically inside an Action, sometimes in a service, other times in various places.) A clear workflow model could be useful - something like New Edit Mode could redefine or augment the object creation workflow with additional workflow steps. (On the other hand, this could just be one more extraneous concept - need to see more cases of this before we can really assess the potential value of this abstraction)

**Comment by VWoeltjen** [comment]
Work is ongoing in the form of API prototypes with usage by tutorial code, tracked by #999

**Comment by VWoeltjen** [comment]
Closing; are no longer engaged in prototyping here, have moved on to documentation and refinement (#1110 and #1111)

**Comment by VWoeltjen** [comment]
Closing; are no longer engaged in prototyping here, have moved on to documentation and refinement (#1110 and #1111)
