### ISSUE TITLE
[Root Objects] Need a way to specify order (use priorities API)

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#4638]
**Is your feature request related to a problem? Please describe.**
Yes. Moving MyItems to a plugin from a legacy angular bundle, changed the order that it was added to the roots array in RootRegistry.js.

**Describe the solution you'd like**
A way to set a specific/general order (priorities).

**Describe alternatives you've considered**
Installing roots in the order they'd like to be shown. This may not always be possible.

**Comment by charlesh88** [comment]
Testathon 1-24-22: verified fixed.
