### ISSUE TITLE
[build] Invert npmignore file to reduce complexity

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#4641]
#### Summary
There is a new pattern for npmignore files which inverts the file to an allowlist instead of a blocklist.

**Comment by unlikelyzero** [comment]
### Testing Notes
run `npm pack`
verify that only the specified files are included

**Comment by trusktr** [comment]
To test #4605, use `npm pack` to create a tar file, then verify the contents.

**Comment by khalidadil** [comment]
I believe this is good now. I'm seeing only the folders src/dist/example in the zip file, and all test files have been removed as far as I can tell. Testathon on 04/04/2022
