### ISSUE TITLE
[New Edit Mode] Implement Drag-drop to initiate edit mode

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#465]
From #453 
_Depends on #464_

__Overview__
Dragging an object onto another object that can compose it should initiate edit mode automatically, and add the dropped object to the composition of the target.

__Implementation notes__
* Hacked into the prototype via DropGesture
* See some of the discussions in https://github.com/nasa/openmctweb/pull/301 around the DropGesture.js on implementation details. Will need to expand comments on outdated diffs.

**Comment by RCarvalhoNASA** [comment]
While this works in Testathon 20160209, might be worth having a discussion of how to lock/prevent this.

**Comment by akhenry** [comment]
This has been implemented
