### ISSUE TITLE
Error building Open MCT on some systems

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4652]
#### Summary
Since the upgrade to Webpack 5 build errors are occurring on some systems.

#### Expected vs Current Behavior
The build is expected to complete without errors. Instead the following error is observed:

```
[webpack-cli] Failed to load '/Users/akhenry/Code/openmct/webpack.prod.js' config
[webpack-cli] Error: Cannot find module 'webpack/lib/rules/DescriptionDataMatcherRulePlugin'
...
```

The issue appears to be due to the version of `vue-loader` that is resolved at build time, which right now is using a version range. 
#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce
1. Configure environment as below
2. run `nvm use 14; nvm clean; npm install`

#### Environment
* Deployment Type: Dev
* OS: MacOS 10.15.7
* Node: v14.17.4
* npm: 6.14.14

**Comment by unlikelyzero** [comment]
### Testing Instructions
Verify that a user can perform an install of openmct and that the installed version of vue-loader is exactly what's specified in the package.json

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon 1/24/22
