### ISSUE TITLE
[CI] Actually build on a specified nvm version instead of lts/fermium

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#4654]
#### Summary
At the moment, there is a bug with our circleci config which will only installs lts/fermium instead of allowing a specified node version in the build_and_install step.

**Comment by unlikelyzero** [comment]
### Testing Instructions
Check the archived npm and node artifacts in any circleci PR

**Comment by shefalijoshi** [comment]
Verified Fixed
