### ISSUE TITLE
Move action issue fix

### ISSUE THREAD

**Issue by nikhilmandlik** [nasa/openmct#4663]
#### Summary
Move action parent/destination object selection throws error `TypeError: Cannot read properties of undefined (reading 'value')`

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

1.
2.
3.
4.

#### Environment
* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

**Comment by unlikelyzero** [comment]
@nikhilmandlik can you add some testing notes here

**Comment by akhenry** [comment]
Original issue verified fixed.

I did observe https://github.com/nasa/openmct/issues/3741, but that's a broader issue.

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 01/24/2022 - successfully able to move objects now
