### ISSUE TITLE
Unable to create domain objects

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#4666]
#### Summary
Unable to create a new object from Open MCT via the Create Menu or via Right-click.

#### Expected vs Current Behavior
New objects should be created.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Steps to Reproduce
1. Click on Create
2. Choose any object (for example, Folder)
3. Choose options in the properties form

#### Environment
* Open MCT Version: Open MCT release/1.8.3
* Deployment Type: banner/testathon
* OS: Mac
* Browser: Firefox

#### Additional Information
<img width="1672" alt="image" src="https://user-images.githubusercontent.com/5247066/148108671-9448aadc-d5ee-441b-9b65-cec24acaebd4.png">

TypeError: e.getCapability is not a function
    allow https://banner.ndc.nasa.gov/testathon/node_modules/openmct/dist/openmct.js:2
    checkPolicy https://banner.ndc.nasa.gov/testathon/node_modules/openmct/dist/openmct.js:2
    checkPolicy https://banner.ndc.nasa.gov/testathon/node_modules/openmct/dist/openmct.js:2
    e https://banner.ndc.nasa.gov/testathon/node_modules/openmct/dist/openmct.js:2
    validateRow https://banner.ndc.nasa.gov/testathon/node_modules/openmct/dist/openmct.js:2
    n https://banner.ndc.nasa.gov/testathon/node_modules/openmct/dist/openmct.js:2
    onChange https://banner.ndc.nasa.gov/testathon/node_modules/openmct/dist/openmct.js:2
    n https://banner.ndc.nasa.gov/testathon/node_modules/openmct/dist/openmct.js:2
    t https://banner.ndc.nasa.gov/testathon/node_modules/openmct/dist/openmct.js:2
    $emit https://banner.ndc.nasa.gov/testathon/node_modules/openmct/dist/openmct.js:2
    handleItemSelection https://banner.ndc.nasa.gov/testathon/node_modules/openmct/dist/openmct.js:2
    n https://banner.ndc.nasa.gov/testathon/node_modules/openmct/dist/openmct.js:2
    t https://banner.ndc.nasa.gov/testathon/node_modules/openmct/dist/openmct.js:2
    $emit https://banner.ndc.nasa.gov/testathon/node_modules/openmct/dist/openmct.js:2
    handleItemSelection https://banner.ndc.nasa.gov/testathon/node_modules/openmct/dist/openmct.js:2

**Comment by scottbell** [comment]
I've added a fix for this here:
https://github.com/nasa/openmct/pull/4672

**Comment by nikhilmandlik** [comment]
Verified Fixed.
