### ISSUE TITLE
[Notebook] Snapshot embed should include link to timeframe of zoomed/panned views

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#4669]
Specifically in plots and imagery, which have the ability to zoom and pan in time, the Notebook Snapshot embed should include a link to that timeframe, not just the timeframe in which the Snapshot was taken which is the current functionality. 

Two examples:
1. while viewing an imagery endpoint in real-time, if the user clicks to select an image thumb from an hour ago and does a Snapshot of such, the embedded start and end times are not for the selected historic image, but instead they are of the time a minute ago when the Snapshot was taken.
2. Similarly, if a plot is zoomed and panned, the Snapshot embed link should include the zoomed and panned timeframe. Note that this has ramifications with Stacked plots, which provide independent zoom and pan (but maybe should not) but only a single Snapshot capability for the view.

Filed as VIPER User Request 194

**Comment by akhenry** [comment]
This is also captured as https://github.com/nasa/openmct/issues/4442 and there is some discussion on the proposed solution in https://github.com/nasa/openmct/pull/3115#issuecomment-988332754.

**Comment by charlesh88** [comment]
Dupe of #4442, closing.
