### ISSUE TITLE
[New Edit Mode] Auto-create panel on composition of telemetry object

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#467]
From #453
_Depends on #465_

__Overview__
When an object is dropped onto another object that can both be composed into a panel, a new 'virtual' panel should be created and edit mode initiated on that object. It should not be persisted until the save action is initiated at the end of editing.

**Comment by RCarvalhoNASA** [comment]
This works in testathon 20160209

**Comment by akhenry** [comment]
This work was completed, but has been disabled. The new plot type will negate the need for this.
