### ISSUE TITLE
[CI] Enable more e2e tests as a part of our CI Checks

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#4674]
#### Summary
We had a regression in basic functionality in recent changes. https://github.com/nasa/openmct/issues/4666 We had an e2e written but not run. This PR enables more e2e tests in the npm 'test:e2e:ci' script which is run on each commit.

We will make sure that we only select new tests to keep the runtime to 5 minutes or less (or the pizza's free!)

Part of this PR will ensure that we only run 2 workers per Agent.

<img width="1105" alt="Screen Shot 2022-01-05 at 8 49 24 AM" src="https://user-images.githubusercontent.com/12446869/148256247-2d6b8234-8b92-4b45-8073-5ff161b12c8a.png">

**Comment by unlikelyzero** [comment]
### Testing Notes
Verify that at least 2 suites of tests are running as a part of each PR check.
Verify that CPU utilization doesn't peg at 100% during the course of execution on the circleci/resources tab

**Comment by shefalijoshi** [comment]
Verified fixed

![image](https://user-images.githubusercontent.com/5247066/151259096-6e2f0333-b40c-4bb8-a6cc-34fd41493d95.png)
