### ISSUE TITLE
Should use relative paths for npm build purposes

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#4682]
#### Summary
Vue components pulled into external repository cannot resolve paths.

*This is an exception in how Open MCT should be used in external repositories. This does not affect normal usage of Open MCT. Internal implementation should not normally affect external usage.

#### Expected vs Current Behavior
Paths should resolve correctly when using component externally.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Steps to Reproduce

1. See that Folder Grid Views work as expected
2. See that Folder List Views work as expected
3. See that Object Labels work as expected
4. See that notebooks work as expected

#### Environment
* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

**Comment by unlikelyzero** [comment]
### Testing Notes
See that Folder Grid Views work as expected
See that Folder List Views work as expected
See that Object Labels work as expected
See that notebooks work as expected

**Comment by charlesh88** [comment]
Verified fixed Testathon 01-06-22.
