### ISSUE TITLE
Static root plugin not loading after namespace/key changes in OpenMCT

### ISSUE THREAD

**Issue by khalidadil** [nasa/openmct#4684]
#### Summary
What it says on the tin! The static root plugin used to use a `namespace:key` format in the key field, which used to work in OpenMCT, but recent changes have made this format incompatible.

#### Impact Check List
- [X] Data loss or misrepresented data?
- [X] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Steps to Reproduce/Testing Steps
1. Install the static root plugin in OpenMCT using a JSON file with an object in it.
2. The plugin currently shows "Missing: root:1" in the tree for the first object. This should properly load and show the object defined in the file.

**Comment by khalidadil** [comment]
Testing notes can be found here: https://github.com/nasa/openmct/pull/4891#issuecomment-1051348231

**Comment by nikhilmandlik** [comment]
Verified Fixed.
