### ISSUE TITLE
[CI] Add Github Action for CouchDB Testing

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#4691]
#### Summary
We've have had several couchdb-specific bugs which have only been discovered as a part of the testathon process. We're going to be adding several key couchdb Search features in the next 4 months.

We should add some automated test coverage for couchdb.

1. Get docker-compose and docker-start.sh file from VIPER
1. Modify docker compose to accept .env file
1. Store in src/persistence/couchdb 
1. Modify https://github.com/nasa/openmct/blob/master/.github/workflows/e2e-pr.yml to start couchdb
1. Write new couchdb-specific e2e tests

**Comment by unlikelyzero** [comment]
### Testing notes
Install couchdb with docker and initialize with open mct
Trigger e2e tests against an open PR
Run couchdb tests locally

**Comment by khalidadil** [comment]
@ozyx got me all setup (thank you!) and this looks good to go! Verified on 08/22/22
