### ISSUE TITLE
Plans must allow hiding swimlanes

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#4692]
In order to simplify views for different teams, plans should allow hiding swimlanes.
There should be an ability to toggle the hidden swimlanes.

**Comment by shefalijoshi** [comment]
@charlesh88 Please provide a UI mechanism to allow showing hidden swim lanes.

**Comment by jerome-leanspace** [comment]
From what I, you can set `options.compact` to `true` which will hide the swim lane

**Comment by ozyx** [comment]
# Testing Instructions

1. Create a Gantt Chart
2. Drag a Plan into it
3. Save
4. Click the "Config" tab
5. Verify all swimlanes are represented in the config and all are "Visible"
6. Activate Edit mode
7. Verify that swimlanes are displayed correctly in the config and all are checked
8. Uncheck a few
9. Save
10. Verify that the correct swimlanes are no longer visible and now display "Hidden" in config while not in edit mode
11. Refresh / Navigate away and back again
12. Verify config persists

**Comment by michaelrogers** [comment]
Fix verified during testathon 03/17/2023. Swimlane config persists through navigation and refreshes.
