### ISSUE TITLE
[e2e] Add MMOC Monitor Resolution to functional, visual, and performance testing

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#4694]
#### Summary
The VIPER MMOC Workstations will be using Dell P2720D at QHD 2560 X 1440

- Update Percy Tests
- Update Functional tests

**Comment by shefalijoshi** [comment]
@unlikelyzero Please add Testing Instructions. Thanks!

**Comment by unlikelyzero** [comment]
### Testing Instructions
- Run e2e tests with `--project=MMOC` flag and verify that the window and viewport resolution match 2560 x 1440
