### ISSUE TITLE
Unable to create links for objects

### ISSUE THREAD

**Issue by khalidadil** [nasa/openmct#4695]
#### Summary
When trying to create a link for an object, I'm getting an error in the console and the selection form "ok" button always remains disabled.

#### Impact Check List
- [ ] Data loss or misrepresented data?
- [X] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [X] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Steps to Reproduce
1. Right click on an object and try to create a link to it. Clicking on any folder in the selection form will cause an error in devtools, and the "ok" button will remain disabled.

#### Environment
* Open MCT Version: latest, testathon (1.8.3)

#### Additional Information
<img width="897" alt="Screen Shot 2022-01-07 at 3 38 42 PM" src="https://user-images.githubusercontent.com/2343076/148610798-14b17f47-1875-43e5-b612-710d1f6d79d0.png">

**Comment by jvigliotta** [comment]
Testathon - 1.7.22 - Verified Fixed

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 01/07/2022
