### ISSUE TITLE
Add e2e tests to verify that basic CRUD operations are working

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4700]
**Is your feature request related to a problem? Please describe.**
We need some e2e tests to perform automated "smoke" tests to verify that the basic operations of the application are working. This issue focuses on testing that basic CRUD operations on objects are working ok. [A separate issue exists to test telemetry display](https://github.com/nasa/openmct/issues/4699).

**Describe the solution you'd like**
This task is to verify that:

- New objects can be created (a test already exists for this)
- Existing objects can be navigated to
- Existing objects can be mutated
- Objects can be deleted from their parent's composition.

This probably necessitates the use of LocalStorage in order to verify mutation. This will require LocalStorage to be initialized into some known state at the start of the tests before RUD operations can be carried out.

**Describe alternatives you've considered**

**Additional context**

**Comment by unlikelyzero** [comment]
Demonstrated in Testathon 05/02
