### ISSUE TITLE
Define object structure for annotations

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4711]
* The annotations need to link to the thing they annotate, and not the other way around. Most of the things we are annotating are immutable.
* My initial assumption is that they are just a new kind of domain object, allowing us to reuse existing API. We probably don't want to show them in the tree though.
* Design needs to meet the use cases identified in the confluence document
    eg. needs to support annotation of
    * Time ranges (plots, tables?), 
    * Pixel space (images),
    * Geospatial features (maps)

    Also needs to support search design, eg.
    * Search for annotations, and from an annotation list all of the objects that it applies to.
* Here is a sketch of what an annotation object MIGHT look like, if constituted as an Open MCT object:

    ```
    {
        identifier: {
            namespace: '',
            id: 'some-uuid'
        },
        type: 'annotation',
        annotationType: 'map-annotation',
        targets: [
            'namespace:unique-identifier-for-the-thing-being-annotated',
        ],
        targetTimes: [{
            start: 123123123,
            end: 12312312
        }],
        originalContextPath: '',
        targetDimensions: {
            x1: 123,
            x2: 323
            y1: 321,
            y2: 345
        },
        tags: ['moon-gopher', ''],
        contentText: 'This is my awesome annotation.'
    }
    ```

**Comment by akhenry** [comment]
@scottbell to work on this

**Comment by scottbell** [comment]
As we're now working https://github.com/nasa/openmct/issues/4820
I think this ticket can be closed. Please reopen if I'm mistaken.
