### ISSUE TITLE
Prototype Annotation Object design

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4712]
The intention here is to prototype the object structure defined in https://github.com/nasa/openmct/issues/4711 and see how performant it is for retrieval. This is not a UI prototype.

Identify some stressing data retrieval cases based on the "Features" identified in the "Annotations, Tagging and Expanded Search in Open MCT" document.
    eg. 
  * "Retrieve all of the annotations for a plot with 10 telemetry points between these timestamps"
  * "Retrieve all of the annotations for a map feature (like an area of interest)."

Prototype the new design by scripting some of the stressing cases identified above with Couch DB. Should pre-fill couch with a large number of objects (maybe ~10,000?) to test how performant it is under those conditions.

Finally, let's discuss performance and decide on next steps.
  * Can Couch support our search and annotation needs, or do we need a new backend component?
  * Are there tweaks we could make to the design to improve search performance?
  * What sort of API will we need to support this? eg. `openmct.annotations.*`

**Comment by akhenry** [comment]
@scottbell to work on this after https://github.com/nasa/openmct/issues/4711

**Comment by scottbell** [comment]
As we're now working https://github.com/nasa/openmct/issues/4820
I think this ticket can be closed. Please reopen if I'm mistaken.
