### ISSUE TITLE
Use relative paths rather than @ alias

### ISSUE THREAD

**Issue by jdekarske** [nasa/openmct#4720]
#### Summary
I'd like to extend the tabs-view plugin to add some hooks (console logs for now) when a user changes tabs.

#### Current Behavior
```
import Vue from 'vue';
import TabsComponent from 'node_modules/openmct/src/plugins/tabs/components/tabs.vue';

// define a component that uses this mixin
var TrackedTabsComponent = Vue.extend({
    mixins: [TabsComponent],
    created: function () {
        console.log("subscribe here")
    },
    methods: {
        logthis: function () {
            console.log("sending")
        }
    }
})
```
Building with webpack gives this error:
```
Module not found: Error: Can't resolve '@/plugins/condition/StyleRuleManager' ...
Module not found: Error: Can't resolve '@/plugins/condition/utils/constants' ...
Module not found: Error: Can't resolve '@/plugins/timeConductor/independent/IndependentTimeConductor.vue' ...
```

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Steps to Reproduce
minimal example above, repo [here](https://github.com/jdekarske/openmct-webpack)

#### Environment
* Open MCT Version: 1.8.2
* Deployment Type: webpack (related to ISAAC UI)
* OS: Ubuntu 20.04
* Browser: NA

#### Additional Information
This may not even be the correct way to accomplish this. Could I import the component from some pre-built openmct module?
Maybe relevant: #3226, #4682
thanks for any help :)

**Comment by depperm** [comment]
is this still an issue? what exactly did you run to get those errors?

**Comment by jdekarske** [comment]
> is this still an issue?

I don't know if this is still an issue, I've moved on to a different project. I ended up changing to an interaction approach that used a backend.

> what exactly did you run to get those errors?

plain ol `webpack`

I'm likely not to come back to this, but the example still exists for reference.

**Comment by unlikelyzero** [comment]
@jdekarske @depperm we have moved this to a linting rule action.

https://github.com/nasa/openmct/issues/6610

ChatGPT was able to crank one out for me, I just didn't get a chance to implement
