### ISSUE TITLE
Independent time setting persists across domain objects

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#4722]
#### Summary
The independent time conductor setting (enable/disable) persists when you switch between domain objects (plots)
This incorrectly displays data in independent time when it should be showing data for the global application time.

#### Expected vs Current Behavior
Independent time conductor should correctly enable/disable based on the domain object being displayed.

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Steps to Reproduce
1. Create 2 plots
2. View one of the plots and enable independent time conductor.
3. From the navigation tree, select the other plot
4. Observe that the independent time conductor shows enabled for the 2nd plot as well, but it should be disabled.

Workaround: Refreshing the page will set the independent time conductor correctly.

#### Environment
* Open MCT Version: 1.8.4-snapshot
* Deployment Type: local, banner
* OS: Mac
* Browser: All

**Comment by charlesh88** [comment]
Testathon 1-24-22: verified fixed. However, there is some undesired behavior: enabling independent Time Conductor (ITC) and changing the time setting, then clicking to the the second plot  and then back to the first results in the first plot's ITC still being enabled, but with its settings reset to the current main Time Conductor setting.

The ITC should persist its settings (preferred) or act in a fully transient manner and disable itself when navved back to. @charlesh88 to file a new issue for this.

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 01/24/22. I can confirm that navigating away from a plot with the independent time conductor enabled and modified time bounds results in a reset of the time bounds when navigating back to the plot.

**Comment by shefalijoshi** [comment]
Testing instructions:
1. Create 3 plots
2. Enable independent time conductor with different bounds for 2 of the 3 plots
3. Switch between independent time conductor enabled plots and ensure that the bounds correctly load/persist
4. Switch between the plot with independent time conductor DISABLED and one of the independent time conductor enabled plots. Ensure that the settings show up and save correctly.
5. Try other combinations of enabled/disabled plots.

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon 1/26/2022

**Comment by nikhilmandlik** [comment]
Verified Fixed.
