### ISSUE TITLE
Unsaved changes to notebook entries can sometimes be lost

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4744]
#### Summary
Under some circumstances unsaved entries to Notebooks can sometimes be lost. This can occur if a user saves a modification to a notebook (eg. creates a new entry, modifies an existing one, deletes an existing one, etc.) while another user is actively editing their own entry. This will cause the entry that is being actively edited to be lost completely. 

Suspect this is not a regression and has always been the case with multi-user notebooks.

This issue is due to the fact that the notebook model does not get persisted until the user blurs the notebook entry. If a remote change is detected during this time it will just fetch the remote version of the notebook and replace the local notebook model.

#### Impact Check List

- [X] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [X] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

**Comment by akhenry** [comment]
A potential solution is to start a transaction whenever a user starts editing a notebook entry, and commit it when they are done. Transactions prevent remote changes to an object affecting an in-progress edit. This will result in conflict at persistence time, once the edit is complete, but notebooks have provision for resolving persistence conflicts.

**Comment by jvigliotta** [comment]
## Testing
- may need a partner for this (yay teamwork!)
- first person (same instance of Open MCT) start a notebook entry
- second person make a change to the notebook (adding an entry, for example) and have it persist
- first person, while still editing entry, make sure notebook isn't reloaded, wiping out your stuff
- first person, finish your entry, check notebook entries to make sure changes are there

**Comment by unlikelyzero** [comment]
verified
