### ISSUE TITLE
Unable to save snapshots to default notebook

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4745]
#### Summary
Snapshots currently cannot be saved to the default notebook. A success notification is shown, and there is no error in the JavaScript console. The snapshot just does not appear in the notebook.

#### Expected vs Current Behavior
When saved to the default notebook snapshots should appear as a new entry.

#### Impact Check List

- [X] Data loss or misrepresented data?
- [X] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [X] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Steps to Reproduce
1. Add an entry to a notebook to make it the default notebook
2. Navigate away to another view (eg. a plot)
3. In the snapshot dropdown, select the option to save a snapshot to your default notebook
4. Navigate back to the notebook. Observe that the entry is not there.

#### Environment
* Open MCT Version: 384af89d4cb370c51d21cdad8ad117b3e185f29a
* Deployment Type: dev local with couch backend.
* OS: Mac OS
* Browser: 97.0.4692.71

**Comment by shefalijoshi** [comment]
Closing this as it was already fixed before.
