### ISSUE TITLE
Snapshot tray is sometimes obscured by long notebooks

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4746]
#### Summary
The notebook snapshot tray sometimes does not extend to its full height, meaning that it is impossible to access the snapshots that have been stored there temporarily. This appears to occur when viewing a notebook that extends beyond the bottom of the page (and includes a scrollbar).

#### Expected vs Current Behavior
The snapshots tray should extend to its full height to allow the user to drag snapshots into notebooks.

#### Impact Check List

- [X] Data loss or misrepresented data?
- [X] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [X] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Steps to Reproduce
1. Create or modify a notebook and add sufficient entries so that the notebook extends beyond the bottom of the screen and a scrollbar appears
2. Take a snapshot using the "Save to Snapshots" option.
3. Click on the snapshot indicator to show the snapshot tray. Observe that it does not extend to its full height, blocking access to the saved snapshots.
![Screen Shot 2022-01-20 at 8 49 02 AM](https://user-images.githubusercontent.com/4215777/150386840-c6372673-b778-47ae-8890-532bf9b6be30.png)

#### Environment
* Open MCT Version: 384af89d4cb370c51d21cdad8ad117b3e185f29a
* Deployment Type: dev with Couch DB enabled
* OS: MacOS
* Browser: Chrome 97.0.4692.71

**Comment by charlesh88** [comment]
Verified fixed Testathon 1-24-22.
