### ISSUE TITLE
Fix code scanning alert - Client-side URL redirect

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#4757]
Tracking issue for:
- [ ] https://github.com/nasa/openmct/security/code-scanning/5

**Comment by akhenry** [comment]
Blocker for 1.8.4 _release_ but not for feature freeze.

**Comment by unlikelyzero** [comment]
### Testing Notes
Verify that the dependabot security warning is gone

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 02/17/22
