### ISSUE TITLE
[New Edit Mode Prototype] Timeline activity icons partially obscure text

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#479]
1. Open a timeline
2. In browse or edit mode, view a timeline. The icons for activities partially obscure text (see below)

![screen shot 2016-01-13 at 2 50 48 pm](https://cloud.githubusercontent.com/assets/4215777/12312578/708b2b9a-ba15-11e5-8af1-570f5730868c.png)

**Comment by akhenry** [comment]
Removed milestone. This is a pre-existing problem in master and wouldn't represent a regression. Don't want to unilaterally add to Bradbury workload.

**Comment by charlesh88** [comment]
Cannot duplicate in current master. Closing as "won't fix", will add unverified label - let's see if we are still seeing this as a problem.

**Comment by VWoeltjen** [comment]
Verified fixed in testathon, 2016/05/31

**Comment by charlesh88** [comment]
Testathon 20160531
Verified fixed.
