### ISSUE TITLE
add type annotations

### ISSUE THREAD

**Issue by trusktr** [nasa/openmct#4793]
#### Summary

Add some type annotations (https://github.com/nasa/openmct/pull/4789)

The behavior of the app shouldn't change (unless I goofed something), so there's nothing to test specifically, just that the app works.

**Comment by shefalijoshi** [comment]
@trusktr Please add some test instructions.

**Comment by unlikelyzero** [comment]
### Testing notes:

if you use TypeScript and you open the source in your IDE, and your IDE is configured for TypeScript, this helps you see things such as informational tooltips when hovering on identifiers, autocompletion of possible values, parameter hints, etc.
As far as OpenMCT itself, there is no change to behavior, nothing to test as far as functionality. If you haven't been using TypeScript intellisense, you'll notice no difference in your editing experience (apart from seeing additional comments in the source code, which you should strive to keep up-to-date if you modify any APIs).

**Comment by unlikelyzero** [comment]
Will cover in demo day
