### ISSUE TITLE
[TimeAPI] Add getMode method

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#4804]
**Is your feature request related to a problem? Please describe.**
It can be a little unclear/tedious to check if `openmct.time.clock() === undefined` to determine if 

**Describe the solution you'd like**
A more simple intuitive way to determine programmatically what mode the time conductor is in.

**Describe alternatives you've considered**
Mentioned above.

**Additional context**
Nada

**Comment by ozyx** [comment]
This was implemented in #6768
