### ISSUE TITLE
Image sizing has visual bugs 

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#4806]
#### Summary

Image sizing in the screen has unacceptable display problems on initial load, when resizing the window, and when changing the size of the main view area by changing the width of the tree or Inspector.
<img width="2140" alt="Screen Shot 2022-01-25 at 11 30 07 PM" src="https://user-images.githubusercontent.com/1056412/151465011-a0d5d0b2-6c5e-4e2f-bb95-b9e5582da138.png">

<img width="1900" alt="Screen Shot 2022-01-27 at 4 43 40 PM" src="https://user-images.githubusercontent.com/1056412/151467148-bb17c54a-f8e1-447a-af5b-063aa91d2592.png">

The image is distorted, and overlaps into the thumbnail area. The compass rose will he hidden beneath the thumbnail strip in the main view. This state will often occur when first going to an Imagery view, and then persist until a new second image comes in, or until the user clicks another image thumbnail.

The other issue that manifests is while adding imagery to a Display Layout, the image will exhibit the same problem, or sometimes remain small and not expand to fill the view.
![image](https://user-images.githubusercontent.com/1056412/151470795-88fd5667-65c6-4349-94b6-be86bebb6850.png)

#### Expected vs Current Behavior

Imagery should size quickly and responsively to fill the space available to its view.

#### Impact Check List

- [x] Data loss or misrepresented data? (Compass is hidden)
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Steps to Reproduce

View Imagery and add an image view to a Display Layout.

#### Environment
* Open MCT Version: 1.8.3 / 1.8.4
* Deployment Type: /stable, /testathon
* OS: Mac
* Browser: Chrome

**Comment by michaelrogers** [comment]
I believe all of these issues have been resolved with the Pan/Zoom implementation.

**Comment by akhenry** [comment]
Marking closed and unverified to retest in 2.0.4

**Comment by rukmini-bose** [comment]
Verified 05/24/2022

**Comment by ozyx** [comment]
Verified -- Testathon 6.9.2022

Tested resize of window in imagery view, and resize of imagery view within display / flexible layouts

**Comment by rukmini-bose** [comment]
Re-verified Testathon 06/09/2022
