### ISSUE TITLE
[Build] Remove API Doc Generation

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#4808]
#### Summary

- [ ] Remove API Doc Generation scripts
- [ ] Remove API Doc Generation readme
- [ ] Remove remaining API Doc Generation dependencies

**Comment by unlikelyzero** [comment]
### Testing Instructions
Verify that there are no dependencies which are specific to doc generation only

**Comment by khalidadil** [comment]
Looks good in Testathon on 03/17/2022
