### ISSUE TITLE
Timestrip View doesn't display Plans properly

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#4810]
#### Summary
Title says it all. Have a look: 

<img width="2160" alt="Screen Shot 2022-01-24 at 10 53 40 AM" src="https://user-images.githubusercontent.com/1056412/151633430-e92e9e57-001e-43b6-bfb7-92830bf97329.png">

This is probably due to a broken CSS selector stemming from updated markup. @shefalijoshi I'll take a look first and ping you if it's something I can't figure out.

#### Expected vs Current Behavior
Title says it all.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Steps to Reproduce

1. Add a plan from the tree to a Timestrip view.
2. Observe that the result is the same as the screenshot at the top of this issue.

#### Environment
* Open MCT Version: 1.8.3 / 1.8.4
* Deployment Type: /stable /testathon
* OS: Mac
* Browser: Chrome

**Comment by charlesh88** [comment]
Problem found, but solution not yet clear. Sometime after 1.8.2, we changed the strategy behind how Plans are added to Timestrips in a way that kills the grid layout:

![Screen Shot 2022-01-31 at 4 17 45 PM](https://user-images.githubusercontent.com/1056412/151895757-5bf45467-529f-4ba7-88e7-7a998ed96b36.png)

What we need to do is 
1. Know when a Plan is inside `c-object-view` and 
1. Write CSS that selects appropriately for that.

**Comment by charlesh88** [comment]
### Testing Instructions
1. Create or edit a Timestrip view.
2. Add a Plan view to the Timestrip view. Add another object view like a telemetry point or Sine Wave Generator.
3. Verify the Plan does NOT appear as the first screenshot in this issue, but instead looks something like this:
<img width="1866" alt="Screen Shot 2022-02-01 at 10 48 50 AM" src="https://user-images.githubusercontent.com/1056412/152032637-97004597-3d9c-4d40-8b3e-25ee7dcbbdc8.png">

or this
<img width="1866" alt="Screen Shot 2022-02-01 at 10 54 17 AM" src="https://user-images.githubusercontent.com/1056412/152032493-ff54baa0-9a1f-4597-ac1a-21bbe62a76e1.png">

4. Check for regressions: click the Plan view itself in the tree, and verify it looks something like this: 
<img width="1866" alt="Screen Shot 2022-02-01 at 10 48 54 AM" src="https://user-images.githubusercontent.com/1056412/152032343-4aa5cacf-d161-498c-bbaf-3df95a71b428.png">

**Comment by shefalijoshi** [comment]
Verified fixed
