### ISSUE TITLE
[Build] Enforce node version at build-time

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#4845]
#### Summary
We have an impossible number of warnings thrown at build time due to dependencies out of our control. This means that it's easy to overlook our engine enforcement -- in some cases it's not even visible due to standard out windowsizes!

NPM provides a configuration to make engine enforcement more concrete with the `.npmrc` file

**Comment by unlikelyzero** [comment]
### Testing Notes
Use a node version of 10 or 16. Attempt to install with `npm install`
Reference openmct in a another project which builds from source: viper-openmct, VISTA?

**Comment by khalidadil** [comment]
@unlikelyzero Can you please provide more detailed testing notes here? I'm not clear on what I should be seeing to verify this is working.

**Comment by khalidadil** [comment]
I tested this with node 16 and got this error, so looks good to me! Testathon on 01/14/2022

```npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: openmct@1.8.5
npm ERR! notsup Not compatible with your version of node/npm: openmct@1.8.5
npm ERR! notsup Required: {"node":">=12.20.1 <15.0.0"}```
