### ISSUE TITLE
Image alt-drag to pan not working in Ubuntu, but should

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#4848]
#### Summary
See title. Alt-dragging moves the entire browser window instead of panning the image as expected. Ctrl-alt drag does work to pan the image though.

#### Expected vs Current Behavior
See title. Solution may be to provide a different hint message utilizing OS detection via JavaScript.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Environment
* Open MCT Version: 1.8.4
* Deployment Type: VIPER/YAMCS
* OS: Linux Ubuntu
* Browser: Firefox

**Comment by unlikelyzero** [comment]
@charlesh88 was this on the 1.8.5-drag branch?

**Comment by unlikelyzero** [comment]
@michaelrogers let's add an e2e test for this. I'm curious to see if this is specific to ubuntu

**Comment by unlikelyzero** [comment]
Verified in the lab
