### ISSUE TITLE
Optimize "View Large" action for imagery

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#4850]
#### Summary
Observed multiple times during egress test today: clicking Imagery in a Flex Layout would often be greatly delayed (20 - 40 seconds) before displaying, and sometimes would not display. Thumbnails which should have been present also would fail to display, or only a sub-set of thumbs would be displayed. 

Important note: there was a lot of latency on the network during the test due to nature of how machines had to be connected, page and new image loads were also pretty slow. 

#### Expected vs Current Behavior
Given my understanding of how Large View works, we should be able to display the cached DOM version (already in the web page) instantly. At the very least, display must be rapid and reliable.

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Steps to Reproduce

See summary

#### Environment
* Open MCT Version: 1.8.4 
* Deployment Type: VIPER
* OS: Linux Ubuntu
* Browser: Firefox

#### Additional Information
Unable to file in VIPER repo due to slowness of that server.

**Comment by akhenry** [comment]
The very slow connection used for this particular test has highlighted some optimizations that we could make for displaying imagery in the "View Large" display. We should not need to re-fetch images in this case, we should be able to either re-use the existing DOM node (as we do with Plots to avoid the same issue) or make use of the browser's cache.

**Comment by akhenry** [comment]
Needs investigation. Use throttling in Chrome dev tools to test.

**Comment by unlikelyzero** [comment]
Verified

**Comment by akhenry** [comment]
Reverify for STM testing

**Comment by jafta009** [comment]
Im very sure someone made up that storie....it wasnt me said Shaggy. So who
do u think would make up a heartbreaking storie like that. And please let
someone that understand u because im scared,,,

**Comment by khalidadil** [comment]
@jvigliotta I'm seeing that when I switch to the telemetry table and switch back, the image has to load again. Is this the expected behavior?

**Comment by charlesh88** [comment]
Testathon 04-25-22: no testing notes, cannot verify.

**Comment by akhenry** [comment]
Verified fixed

**Comment by akhenry** [comment]
@charlesh88 https://github.com/nasa/openmct/issues/4850#issuecomment-1085112668

**Comment by charlesh88** [comment]
Verified PARTIALLY fixed Testathon 04-25-22: While performance seems to be _very_ snappy, going from the layout frame to large view, the scrollbar of thumbnails
![Screen Shot 2022-04-25 at 3 33 01 PM](https://user-images.githubusercontent.com/1056412/165185642-33676f17-e0c2-40dc-8d62-bc3aadd95aee.png)
gets reset to the left to the first image
![image](https://user-images.githubusercontent.com/1056412/165185748-8a8ccf70-6548-4d26-a433-de4e23b03f9b.png)
but should not. Closing the overlay and going back to the main view retains the left-scrolled state, which is also undesirable. The user-set scroll position should be retained from layout frame to large view and back.

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by akhenry** [comment]
Reopening to address @charlesh88

**Comment by shefalijoshi** [comment]
> 

@charlesh88 Would it be OK to scroll to the focused image if there is one when switching from/to large view? If there is no focused image and someone just scrolled the thumb nails, do we still need to retain the scroll position?

**Comment by charlesh88** [comment]
Not sure about the "no focused image" case: there’s only ever a non-selected image state when we don’t have data, and we wouldn’t have any thumbs in that case.

If the question is how to handle the scroll position of the thumbs wrapper, my druthers would be to preserve whatever the user has done as they go back and forth. The idea here is that you're magnifying/demagnifying a thing, and therefore it shouldn't ideally change state between small and large view. Given that we're just moving the thing from one place in the DOM to another, this would be the easiest thing to do as well, yes?

**Comment by michaelrogers** [comment]
Confirmed in testathon on 04/28. The thumbnails now scroll to focused image when transitioning to large view.

**Comment by charlesh88** [comment]
Verified fixed Testathon 4-28-22.

**Comment by nikhilmandlik** [comment]
Verified Fixed.
