### ISSUE TITLE
Deal with legacy styling in Open MCT

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#4851]
We have [some](https://github.com/nasa/openmct/blob/master/src/styles/_legacy.scss) [SASS](https://github.com/nasa/openmct/blob/master/src/styles/_legacy-plots.scss) [files](https://github.com/nasa/openmct/blob/master/src/styles/_legacy-messages.scss) prefixed with `_legacy` in https://github.com/nasa/openmct/tree/master/src/styles.

The purpose of this issue is to establish whether [the recent removal of all legacy code](https://github.com/nasa/openmct/pull/4844) has any impact on these styles.

My (@akhenry) suspicion is that these `_legacy` sass files were created to isolate legacy styles during our migration to [BEM](https://csswizardry.com/2015/08/bemit-taking-the-bem-naming-convention-a-step-further/). These legacy styles were moved into the `src` directory, but named to highlight that they use the old styling conventions. In this case the `_legacy` prefix may actually be appropriate and reflect the fact that there is still outstanding work here. If so, we should treat refactoring our legacy styles as a separate issue. There is no visual impact here, we just name and organize classes differently now. Need @charlesh88 input here.

Spun out as a separate issue from https://github.com/nasa/openmct/issues/4844#issuecomment-1036469584_

**Comment by akhenry** [comment]
No impact on styling observed from removal of legacy codebase.
