### ISSUE TITLE
[Docs] Update Github Bug Report Template to include instructions for envinfo

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#4857]
#### Summary
It's really annoying to find all the important diagnostic information when filing issues. We want to reduce as many barriers as possible AND get more information than is readily available in bash commands. 

Enter https://github.com/tabrindle/envinfo

We should put this in our Bug Report template!

**Comment by unlikelyzero** [comment]
### Testing Instructions
1. File a bug and execute the provided envinfo command

**Comment by jvigliotta** [comment]
Confirmed Fixed - Testathon 3/14/2022
