### ISSUE TITLE
Moving a parent folder into a child folder makes the folder orphaned from the tree

### ISSUE THREAD

**Issue by michaelrogers** [nasa/openmct#4862]
#### Summary
Moving a parent folder into a child folder makes the folder orphaned from the tree, this includes all other domain objects that exist inside of the folder. Domain objects would then be completely orphaned and inaccessible by tree / search. 

#### Expected vs Current Behavior

Expect for this action to either be prohibited or any orphaned folder to be reinserted into the tree.

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Steps to Reproduce

Initial folder structure:
MyItems -> Folder A -> Folder B

1. Move Folder A into Folder B
2. Observe Folder A nor Folder B are accessible in the tree

Note, if Folder A is moved back into the My Items folder it will be accessible again.

#### Environment
Version: 1.8.5
Build Date: Mon Feb 14 2022 12:34:05 GMT-0800 (Pacific Standard Time)
Revision: 5a1791473ea16c51ded53b276fbe927b6b21ff47
Branch: release/1.8.5

**Comment by akhenry** [comment]
Huh! Good catch. 

We need some sort of cyclical composition check generally, which I think would also catch this case.

**Comment by scottbell** [comment]
This is not longer possible (I think) due to [this PR](https://github.com/nasa/openmct/pull/5635). E.g.:
<img width="891" alt="Screen Shot 2022-09-26 at 12 06 43 PM" src="https://user-images.githubusercontent.com/9853862/192250307-aac33d96-4fdf-44a3-a8b9-abf722961ffe.png">

**Comment by michaelrogers** [comment]
Confirmed, this bug no longer exists since release/2.0.8.
