### ISSUE TITLE
Object.hasOwn unsupported

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#4863]
#### Summary
Using javascript's experimental Object.hasOwn method is causing issues:
Error about Object not having 'hasOwn' property.

#### Expected vs Current Behavior
Probably use something other than the hasOwn method.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Steps to Reproduce

1.
2.
3.
4.

#### Environment
* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

**Comment by mariuszr** [comment]
Hi @shefalijoshi, I have found only one place of the Object.hasOwn() method usage - [Telemetry API.js](https://github.com/nasa/openmct/blob/4a9744e916d24122a81092f6b7950054048ba860/src/api/telemetry/TelemetryAPI.js#L515). I assume that the issue refers to the Safari browser that the method is in development and should be supported in a pre-release version.

We can solve it by reimplementing 
```js 
Object.hasOwn(requestProvider, 'request')
``` 
to 
```js
Object.prototype.hasOwnProperty.call(requestProvider, 'request')
```

In this case I would also recommend to add 
```js
typeof requestProvider.request === 'function'
```
as a `&&` condition to be sure that the `request` property is also the function - see [Telemetry Providers](https://github.com/nasa/openmct/blob/master/API.md#telemetry-providers).

@akhenry @jvigliotta @davetsay

**Comment by jvigliotta** [comment]
## Testing
- confirm you can use the historical request functionality of telemetry api. So just view historical telemetry and confirm no errors in console
- try multiple browser types

**Comment by ozyx** [comment]
Verified -- Testathon 6.9.2022
