### ISSUE TITLE
Unsupported API in notebook - screen.orientation

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4875]
#### Summary
The [standard screen orientation API](https://developer.mozilla.org/en-US/docs/Web/API/Screen/orientation) is, unsurprisingly, not supported in Safari. Instead [our code](https://github.com/nasa/openmct/blob/b27f24cc304c69319f27d3c372d39349394311a1/src/plugins/notebook/components/Notebook.vue#L441) should feature-detect for `screen.orientation`, but fall back on the (now deprecated) [`window.orientation`](https://developer.mozilla.org/en-US/docs/Web/API/Window/orientation) if it's undefined.

**Comment by unlikelyzero** [comment]
Adding `bug:platform` to track as platform specific

**Comment by ozyx** [comment]
## Test Procedures

### Notebook no longer throws error if `screen.orientation` is not available

- Run a local instance of OpenMCT.
- Add a Notebook. Add an entry into the notebook.
- Access the app instance from a mobile device with the Safari browser (e.g.: Plug in iPhone and access it over a shared network)
- Select the Notebook. Change device orientation a few times from portrait to landscape, and back.
- View the Safari console on the host machine. Notice that there are no TypeErrors thrown.

### Notebook sidebar correctly covers/pushes notebook entries based on device and orientation

- Run a local instance of OpenMCT.
- Add a Notebook. Add an entry into the notebook.
- Open the instance in a browser, such as Google Chrome.
- Open the "Section/Page" Notebook sidebar. Notice that it does not cover the notebook entries
- Switch to "Responsive Design Mode". Switch device to a mobile device such as "IPhone 12" and refresh the page
- Open the "Section/Page" Notebook sidebar. Notice that it now covers the notebook entries.
- Switch orientation to landscape. Open the sidebar. Notice that it still covers the notebook entries.
- Switch the device to a tablet, such as an IPad, and refresh the page.
- In portrait orientation, open the sidebar. Notice that it covers the notebook entries.
- Switch to landscape orientation, open the sidebar. Notice that it no longer covers the notebook entries

**Comment by khalidadil** [comment]
@ozyx I'm noticing that in iPad portrait orientation, the sidebar doesn't cover the notebook entries (see the image below). Is this right? This is with an iPad Pro 11 inch (3rd generation) running iOS 15.2.

<img width="610" alt="Screen Shot 2022-06-15 at 5 51 41 PM" src="https://user-images.githubusercontent.com/2343076/173955354-6765e777-407e-494e-b7c4-68fc28fff0c1.png">

**Comment by khalidadil** [comment]
After talking with @ozyx, it sounds like the main bug was addressed for this ticket - so verified fixed on 06/15/22

There was a separate visual bug logged here: https://github.com/nasa/openmct/issues/5384
