### ISSUE TITLE
[clock] timezone dropdown once expanded does not collapse

### ISSUE THREAD

**Issue by nikhilmandlik** [nasa/openmct#4878]
#### Summary
clock object: When creating/editing, timezone dropdown once open should be able to dismiss when click outside or on dropdown icon again

#### Expected vs Current Behavior
timezone dropdown once expanded does not collapse

#### Steps to Reproduce
1. create menu, try to create clock object
2. click on dropdown near to `timezone` value
3. should expand timezone list 
4. now try to click dropdown icon again to collapse list
5. it does not collapse

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?

**Comment by unlikelyzero** [comment]
Adding e2e label. This needs a test.

**Comment by jvigliotta** [comment]
Hello @SyedAhmedCU ! Do you have submitted a CLA? I didn't see one on file with us, if you'd like to contribute (which would be awesome!) we'll need you to follow the steps outlined here: https://github.com/nasa/openmct/discussions/3821 once that's done, we can merge in your contributions. Any questions let me know! Thanks!

**Comment by SyedAhmedCU** [comment]
Hi @jvigliotta , I have sent the signed CLA to the emails mentioned in the pdf. I also created a PR that fixes the issue. Let me know if you have any suggestions. Thanks!

**Comment by unlikelyzero** [comment]
### Testing Instructions

Steps to Reproduce
create menu, try to create clock object
click on dropdown near to timezone value
should expand timezone list
now try to click dropdown icon again to collapse list
it does not collapse
