### ISSUE TITLE
Revisit plan views to accomodate changes to VIPER plan JSON

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#4882]
The VIPER plan JSON has changed. The Plan view must be updated to accomodate changes to this JSON.

**Describe the solution you'd like**
Make the plan view more generic so that changes to the JSON schema don't affect the plan view as much.
This might mean a change to the viper-openmct repo as well.

**Comment by shefalijoshi** [comment]
Testing instructions:
Open a VIPER plan posted by the planning tool team. (The VIPER plans folder)
Backwards compatibility - older plans should also be displayed.

**Comment by nikhilmandlik** [comment]
able to verify using new plan 'day1_v9_post_edit'

**Comment by unlikelyzero** [comment]
@shefalijoshi we need some clarity on backwards compatiblity

**Comment by unlikelyzero** [comment]
Verified fixed

**Comment by nikhilmandlik** [comment]
Verified Fixed.
