### ISSUE TITLE
Make image thumbnails available from display layouts

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4884]
**Is your feature request related to a problem? Please describe.**
When placed in a layout the imagery view hides the thumbstrip and only makes it available from the view large action. Past imagery is used a lot in certain workflows, which requires more frequent access to thumbnails from display layouts.

**Describe the solution you'd like**
Much better approach would be a way to access the thumbstrip control from an image's layout frame, either via a popover bubble, or evaluation of the size of the layout frame (i.e. show thumbs if the frame is bigger than a size) and/or a user-set preference when adding the imagery to the layout. Note that this pertains to both kinds of layout.

**Comment by charlesh88** [comment]
### Testing Notes
Before beginning, review the reference images below these notes.
1. Create an example Imagery view, or use existing imagery data products if available.
1. Verify that the thumbs and image view allow selection, scrolling, etc. as expected normally.
1. Put the Imagery view in a Display Layout, and resize the image's container to exercise the size breakpoints as noted in the references. Verify that the view displays in a similar fashion to the reference.
1. Verify that thumbnails display without being clipped in the scrolling thumbnail container.
1. Hover over the thumbnails and verify that a tooltip is displayed as shown in the reference.
1. Repeat steps 3 - 5 in a Flexible Layout.

### Reference Images
**Height <= 200px high, no thumbs displayed**

![Screen Shot 2022-04-22 at 11 33 39 AM](https://user-images.githubusercontent.com/1056412/164775565-5956de06-235a-4d67-9093-00c499f26ce6.png)

**Height > 200px && height <= 600px, show small thumbs**

![Screen Shot 2022-04-22 at 11 33 48 AM](https://user-images.githubusercontent.com/1056412/164775600-9ff7ed13-f079-4106-8f85-a105485d1245.png)

**Height > 600px, show fullsize thumbs**

![Screen Shot 2022-04-22 at 11 48 34 AM](https://user-images.githubusercontent.com/1056412/164776074-7eb0d067-9f00-4456-95cc-fc6f1e821ed0.png)

**In Display Layout, showing tooltip on hover**

![Screen Shot 2022-04-22 at 11 35 52 AM](https://user-images.githubusercontent.com/1056412/164776541-ca6bed17-e38b-4e99-807e-ff3dea1c526e.png)

**Comment by charlesh88** [comment]
Verified fixed Testathon 04-25-22:

**Comment by khalidadil** [comment]
It looks like the thumbnails are visible over ~340px, and large thumbnails are visible over ~730px, but otherwise this looks good.

**Comment by jvigliotta** [comment]
Verified Fixed Testathon: 4/25/22

**Comment by jvigliotta** [comment]
Verified... AGAIN. 4/28/2022

**Comment by charlesh88** [comment]
Verified fixed Testathon 4/28/22
