### ISSUE TITLE
Align image freshness indicators with VERVE

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4885]
**Is your feature request related to a problem? Please describe.**
Image freshness indicators in Open MCT last too long, and blinking is too obnoxious.

**Describe the solution you'd like**
* Default timing of freshness indicators and should be aligned with VERVE.  
* Fade out approach used in VERVE should be considered instead of blinking.

**Comment by shefalijoshi** [comment]
Verified fixed

**Comment by charlesh88** [comment]
Verified NOT fixed Testathon 04-25-22:

![Screen Shot 2022-04-25 at 3 10 39 PM](https://user-images.githubusercontent.com/1056412/165183370-647f1bc9-03b2-4bbf-8e82-056f3461a21f.png)

1. Clicking a past image, then clicking the Play button to resume real-time causes the freshness indicator to reapply, but shouldn't.
2. Camera and Position freshness buttons have lost their color styling.

**Comment by michaelrogers** [comment]
@charlesh88 - Excellent finds. 

2. Do camera & position freshness need separate animation values or can they reuse the image freshness indicators values?

**Comment by akhenry** [comment]
Per discussion 04/28 positional and camera freshness indicators should never time out.

**Comment by charlesh88** [comment]
Verified fixed Testathon 4/28/22

**Comment by akhenry** [comment]
Verified fixed.
