### ISSUE TITLE
OpenMCT should tell you it cannot connect to its persistence store

### ISSUE THREAD

**Issue by scottbell** [nasa/openmct#4888]
**Is your feature request related to a problem? Please describe.**
If OpenMCT cannot connect to its persistence store (e.g., CouchDB), there's no notification to the user aside from some exciting errors in the console. The stored objects in CouchDB don't appear, and the first error a user will get is if they try to save something and the dialog hangs.

**Describe the solution you'd like**
We should alert the user that the configured persistence store is unreachable.

**Describe alternatives you've considered**
If they have more than one persistence store, perhaps one being down is acceptable? In that case, I think an operator would still like to know that one of them is unavailable.

**Additional context**
The error message if CouchDB is down:
```
CouchObjectProvider.js?9318:132          GET http://localhost:5984/openmct/mine net::ERR_CONNECTION_REFUSED
```
The frozen save dialog:
<img width="779" alt="Screen Shot 2022-02-23 at 12 36 07 PM" src="https://user-images.githubusercontent.com/9853862/155312035-b550d739-5a89-45ec-992e-fbb1adf4e8fb.png">

**Comment by scottbell** [comment]
An easy implementation would be to just notice on page load if the persistence store is down and pop up a notification. A nicer implementation would be to heartbeat the persistence store, and notify when connection is lost or restored.

**Comment by akhenry** [comment]
Let's definitely implement this for Couch. We can use the SimpleIndicator. For Couch, since we hold a persistent connection open for updates, so could we just use the status of that connection as a proxy for Couch availability?

**Comment by ozyx** [comment]
## Testing

### Case 1
- Launch OpenMCT with CouchDB plugin installed and CouchDB running
- Notice that CouchDB indicator is present and green
- End CouchDB process by ctrl-C
- Notice that CouchDB indicator is yellow
- Start CouchDB process again
- Notice that CouchDB indicator is green

### Case 2
- Launch OpenMCT with CouchDB plugin installed and without CouchDB running
- Notice that CouchDB indicator is present and red
- Start CouchDB
- Trigger some request to the object API (clicking 'CREATE')
- Notice that CouchDB indicator is green again

### Case 3
- Launch OpenMCT with CouchDB plugin installed and running (but configured for a database that doesn't exist)
- Notice that CouchDB indicator is present and green
- Notice that console errors are present and descriptive ("Database doesn't exist")

**Comment by shefalijoshi** [comment]
Case 1 above fails - after ending the couchdb process indicator does not turn yellow.

**Comment by ozyx** [comment]
> Case 1 above fails - after ending the couchdb process indicator does not turn yellow.

I was not able to reproduce this issue locally on `release/2.0.5` on Chrome.

**Comment by ozyx** [comment]
Found some scenarios where the indicator will show 'connected' erroneously: #5406

**Comment by shefalijoshi** [comment]
Verified this as a feature - there is a bug outstanding which will be addressed separately.
