### ISSUE TITLE
Add Gauge plugin

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#4896]
Add radial Gauge plugin component.

Details from discussion 2/24/22 Andrew, Nikhil, Jamie, Charles:
### @charlesh88 todos:
- [x] Push WIP to branch https://github.com/nasa/openmct/tree/add-gauge-4896
- [x] Design UI for Properties dialog: https:/<>/VIPERMS/Gauge
- [x] Convert colors to theme styles.
- [x] Sand/shim CSS/markup, fix numeric display overrun, etc.

![image](https://user-images.githubusercontent.com/1056412/155597511-681fdb2c-b0ed-4833-b986-48d91eaf9aad.png)

### Other todos
- [x] Add support for lower and upper red limits as user-available options. If selected, use as min/max thresholds with something like 10% padding. If user doesn't select this option, the user should set manual min/max and min/max red limits. Use checkbox per min/max setting.
- [x] Keep settings in Properties dialog form (rather than Inspector) for now.
- [x] Bring inline with current code style and practices.
- [ ] Add testing (?)

### Future
- [x] Vertical and horizontal meter options. Needs design.
- [x] Needle option as an alternative to current "filled bar" visualization. Needs design.

### Testing instructions:
1. Verify new Gauge object with horizontal, Vertical, Needle and Filled bar visualization styles.

**Comment by unlikelyzero** [comment]
@nikhilmandlik let's write out some testing instructions together and merge in some e2e stubs

**Comment by charlesh88** [comment]
### Testing Notes
I've created a folder with Gauges, Sine Wave Generators and a Display Layout that can be imported: [Gauge Test Display Layout.json.zip](https://github.com/nasa/openmct/files/8330156/Gauge.Test.Display.Layout.json.zip)

#### Reference GIF
![Gauge Test Layout](https://user-images.githubusercontent.com/1056412/159634170-d838ab49-eb86-481a-8b11-acb93420cef7.gif)

1. Create a series of Gauges, one for each type, or import the attached file. We're looking to make sure that all 5 types of Gauge are displayed properly and perform as expected.
2. Verify that each Gauge type - Dial Filled, Dial Needle, Meter Vertical, Meter Vertical Inverted and Meter Horizontal all appear the same as shown in the reference GIF above.
3. Edit properties of each gauge type, hiding and showing value and ranges, and verify the gauge displays as expected.
4. Change the properties of the Sine Wave Generators and verify that the gauge updates itself accordingly.

**Comment by charlesh88** [comment]
Verified NOT fixed Testathon 04-25-22: this view needs Edit mode to manage composition.

**Comment by akhenry** [comment]
@nikhilmandlik How much work is involved in enabling edit mode for this?

**Comment by akhenry** [comment]
@nikhilmandlik to enable edit mode

**Comment by jvigliotta** [comment]
Think NOT fixed.

I added a Telemetry Item, then removed from the Elements Pool. The telemetry data was still showing. Even after saving. A refresh seems to fix it. 

I WAS seeing other composition issues as well, could be related.

**Comment by akhenry** [comment]
Verified fixed

**Comment by akhenry** [comment]
> OK... Not Fixed. There is an issue with telemetry that does not have limits, we're showing NaN...

Let's file a followup issue to address this in 2.0.4

**Comment by unlikelyzero** [comment]
https://github.com/nasa/openmct/issues/5155
