### ISSUE TITLE
Changing display layout grid size throws console error

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#4901]
Changing the horizontal or vertical grid size in Display Layout edit properties throws a console error.

#### Expected vs Current Behavior
No console error should be thrown.

#### Steps to Reproduce
1. Create a display layout
2. Save it
3. Edit properties for this layout and change the horizontal or vertical grid size px.
4. Press OK to save the properties.
5. Observe console error displayed.

#### Environment

* Open MCT Version: 2.0.1-SNAPSHOT
* Deployment Type: local
* OS: Mac
* Browser: Firefox

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Additional Information

[Vue warn]: Invalid prop: custom validator check failed for prop "gridSize".

found in

---> <SubobjectView> at src/plugins/displayLayout/components/SubobjectView.vue
       <DisplayLayout> at src/plugins/displayLayout/components/DisplayLayout.vue
         <Root> 3 [vue.js:581:15](webpack-internal:///./node_modules/vue/dist/vue.js)
    VueJS 22
    _onSave webpack-internal:///./src/plugins/formActions/EditPropertiesAction.js:77
    _showEditForm webpack-internal:///./src/plugins/formActions/EditPropertiesAction.js:108
    invoke webpack-internal:///./src/plugins/formActions/EditPropertiesAction.js:54
    onItemClicked webpack-internal:///./src/api/menu/MenuAPI.js:87
    VueJS 30
    show webpack-internal:///./src/api/menu/menu.js:72

**Comment by shefalijoshi** [comment]
Testing Notes:
Try to change the horizontal and vertical grid size of a display layout.
Ensure no console error is displayed.

**Comment by charlesh88** [comment]
Testathon 3-17-22: verified fixed.

**Comment by unlikelyzero** [comment]
Verified Fixed

**Comment by nikhilmandlik** [comment]
Verified Fixed.
