### ISSUE TITLE
Plot x-axis getting cut off in display layout

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#4902]
#### Summary
Plot x-axis getting cut off in display layout - this makes it impossible to see x-axis ticks.

#### Expected vs Current Behavior
X axis should be completely visible

#### Steps to Reproduce
1. Create a plot
2.Create a display layout
3.Add the plot to the display layout
4.Observe that the x-axis is cut off

#### Environment
* Open MCT Version: 2.0.1-SNAPSHOT
* Deployment Type: local
* OS: Mac
* Browser: Firefox

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?

#### Additional Information
![image](https://user-images.githubusercontent.com/5247066/156223910-93833879-1cc8-4628-b0db-4e34db98ee07.png)

**Comment by charlesh88** [comment]
Testathon 3-17-22: NOT fixed.

![image](https://user-images.githubusercontent.com/1056412/158900268-3578cd0d-2631-448d-a73d-81f41ee7e241.png)

@shefalijoshi Let me fix this, this is a complicated and somewhat brittle CSS layout.

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by unlikelyzero** [comment]
Note for e2e test additions: this will require a visual test.

Default.visual.e2e.spec.js
```js
//Psuedo-code as comments
//Create a Display Layout
//Create a SineWave Generator
//Move SineWave Generator into Display Layout
//Reload Display Layout in Read-only Mode
percy.snapshot('Sinewave Generator in Display Layout - Read-only');
//Open Display Layout in Edit mode
percy.snapshot('Sinewave Generator in Display Layout - Edit-only'):
```
