### ISSUE TITLE
[CI] Inline linting warnings are extremely noisy on pr:platform workflow

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#4909]
#### Summary
When a linting warning is found on pr:platform workflows, it results in a ton of inline warnings (1 per component in the matrix). We should remove those linting warnings altogether as the purpose of the linting is only to fail without inline help.

**Comment by unlikelyzero** [comment]
### Test instructions
1. Open a PR
2. Add a pr:platform label to a PR
3. Wait for matrix to complete
4. Verify that no in-line help is generated on the 'Files' Part of the PR

**Comment by jvigliotta** [comment]
Confirmed Fixed - Testathon 3/14/2022
