### ISSUE TITLE
[Plots] "Grab" cursor should be shown when panning

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4911]
#### Summary
Plots should show a grab cursor when the user is panning in a plot. 

#### Steps to Reproduce
1. Navigate to a plot
2. Hold down the option key (in Mac OS) while hovering the cursor over the plot
3. Notice that the cursor does not turn into the grab cursor as it used to.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [X] Regression? Did this used to work or has it always been broken?
- [X] Is there a workaround available?
- [X] Does this impact a critical component?
- [X] Is this just a visual bug with no functional impact?

#### Additional Information
Refer to the panning gesture in the time conductor for an example of what the cursor should look like while panning plots.

**Comment by akhenry** [comment]
Categorizing as medium severity because it affects the discoverability of the pan gesture in plots, which is an important part of user workflows.

**Comment by unlikelyzero** [comment]
### Testing Notes
#### Mac OS
Navigate to a plot
Hold down the option key (in Mac OS) while hovering the cursor over the plot
Notice that the cursor turns into grab cursor

#### Windows
Repeat

**Comment by unlikelyzero** [comment]
akhenry to verify with a windows machine

**Comment by akhenry** [comment]
Verified fixed in Windows

**Comment by unlikelyzero** [comment]
### e2e Testing Notes

Note: much of this functionality can be found in the https://github.com/nasa/openmct/blob/c089a4760d913fc3827d13d374c68058e4796321/e2e/tests/plugins/imagery/exampleImagery.e2e.spec.js#L84 suite

e2e/test/plugins/plot/plotInteractivity.e2e.spec.js
```js
test.describe('Plot and Cursor Tests')
test('Can Pan on plot with Alt+mouse')\
1. Create Overlay Plot
2. Create example Imagery under Overlay Plot
3. Page.goto() Overlay plot
4. hover over plot and detect mouse input type
5. hold down alt key. Detect mouse input type


```
