### ISSUE TITLE
Sometimes cannot remove folders

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4915]
#### Summary
I have noticed an issue where folders sometimes cannot be removed, and are instead turned into links by the "Remove" action.

#### Expected vs Current Behavior
Removing a folder via the remove action should remove the folder from the parent's composition, and not just turn it into a link.

#### Steps to Reproduce
1. Import the attached JSON (if you haven't previously)
2. Navigate to My Items > Components
3. Right click on the "Imagery" folder and click on the "Remove" action.
4. Observe that the "Imagery" folder turns into a link and is not removed from the parent composition.

#### Environment
* Open MCT Version: 74b83903c907680ea183d4ec331fb649d9a9fcc4
* Deployment Type: Local
* Browser: Chrome 98.0.4758.109 (also observed in Firefox)

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [X] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Attachments
[My Items - condition bug.json.zip](https://github.com/nasa/openmct/files/8181778/My.Items.-.condition.bug.json.zip)

**Comment by akhenry** [comment]
_May_ be related to https://github.com/nasa/openmct/issues/5033 and fixed by https://github.com/nasa/openmct/pull/5134

**Comment by alizenguyen** [comment]
Folders that are not being removed is because for some reason in the composition array, these particular folders only have an id string compared to the other folders that have an object with a key and nameSpace property.

<img width="436" alt="Screen Shot 2022-06-30 at 12 16 39 PM" src="https://user-images.githubusercontent.com/29556173/176933794-d478bc10-8310-4ea8-9874-de10db6af6a2.png">

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon 8/4/22

BUT WAIT, THERE'S MORE!

The imported folder is showing as a link, which I believe is not correct.

![Screen Shot 2022-08-04 at 3 21 26 PM](https://user-images.githubusercontent.com/12013460/182962730-cd792a6b-36bd-40b0-9371-ce63bad8a350.png)
