### ISSUE TITLE
Independent Time Conductor forces scroll in Overlay Plots

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#4929]
#### Summary
![Screen Shot 2022-03-08 at 10 20 09 PM](https://user-images.githubusercontent.com/1056412/157388013-53642613-bfd6-4663-8581-9a0588cdca8d.png)

#### Expected vs Current Behavior
![image](https://user-images.githubusercontent.com/1056412/157388259-2ea70dce-a427-4422-993c-9cf54395280b.png)

#### Steps to Reproduce

View an Overlay Plot.

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Additional Information
Put flex with column direction on `.c-so-view__object-view` and set TC to `0 0 auto` and `c-object-view` to `1 1 auto`.

**Comment by charlesh88** [comment]
### Testing Notes
1. Create or edit an Overplay Plot.
2. Verify that it looks like the screen shot in "Expected vs. Current..." above.

**Comment by unlikelyzero** [comment]
This needs a visual test

**Comment by shefalijoshi** [comment]
@charlesh88 Where was this issue observed? It might already be fixed in testathon as part of #4902
