### ISSUE TITLE
[Mobile] Time Conductor in mobile portrait tablet is not fitting

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#493]
Seen with VISTA running on iPad Mini. Screenshots attached.

![vista ipad 2](https://cloud.githubusercontent.com/assets/1056412/12456571/469e5a24-bf55-11e5-9bf0-30a030eb87a8.png)
![vista ipad](https://cloud.githubusercontent.com/assets/1056412/12456570/469bf428-bf55-11e5-8381-ccf4d214405e.jpeg)

**Comment by VWoeltjen** [comment]
Should coordinate with work on #318 (wherein slider may be hidden, for instance)

**Comment by VWoeltjen** [comment]
Unable to verify during testathon 5/31/2016; time conductor is not included in WARP at this time

**Comment by VWoeltjen** [comment]
Now seeing the right text field getting cut off by the time system box (using Chrome Tools, device emulation, iPad):

![screen shot 2016-06-16 at 2 49 33 pm](https://cloud.githubusercontent.com/assets/1685764/16134366/a01d85f2-33d1-11e6-85a9-3218769164e5.png)

(Apologies for the low-res screenshot. Either you can't scroll in Chrome's device emulation mode, or I'm not smart enough to figure out how. Only way I could see the bottom was at 50% scale. Software!)

**Comment by charlesh88** [comment]
Testathon 2016-06-16 ciedevweb1.jpl.nasa.gov:8443/mcws/clients/vista/
* Verified fixed in real iPhone 6 - portrait and landscape both working as expected.
* Seeing same as Victor in iPad emulator.

@VWoeltjen On the scrolling while emulating, if you have the device scale set to 100%, you have to open the window large enough to see the bottom, which also means you need to do that on a big enough monitor. So setting to 50% scale was the thing to do if you're on your laptop.
