### ISSUE TITLE
In Memory Search performance and namespacing issues

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#4946]
#### Summary
* in memory search re-indexes on every tree expansion (even same node)
* in memory search does not work for namespaces

#### Expected vs Current Behavior
Each object should be indexed once on load. Objects should be re-indexed only on name change or composition change.

#### Steps to Reproduce
Over-indexing
1. Load Open MCT
2. Open console browser and open source file `inMemorySearchProvider.js`
3. Set a break point in the index function definition
4. expand a node in the object tree
5. Expect code does not stop at set breakpoint

No Namespacing
1. Gain access to deployment with namespaces
2. Test search

#### Environment

* Open MCT Version: 2.0.1
* Deployment Type: VISTA to test namespacing
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [] Is there a workaround available?
- [] Does this impact a critical component?
- [] Is this just a visual bug with no functional impact?

**Comment by davetsay** [comment]
For what its worth, I verified this in Open MCT for MCWS

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 04/25/2022
