### ISSUE TITLE
[Link Action] Unable to link root level objects

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#4951]
#### Summary

When you try to create a link for a root level item (ex. My Items), when you select a location, a console error blocks you from completing the action. This is due to a "parent" item being checked, but for root level objects, no parent is provided.

#### Expected vs Current Behavior

Uh, you should be able to link root level objects.

#### Steps to Reproduce

1. Right click a root level item (ex. My Items)
2. Select Create link
3. Notice errors in console

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

**Comment by jvigliotta** [comment]
## Testing
- right click root level object in the tree (ex. My Items)
- select "Create Link"
- choose a valid location in the form
- make sure there are no errors and the item is linked correctly
- ALSO
- one other thing
- if you don't mind
- do the same as above, BUT (there's always a but), select a non-persistable item (like a root level dictionary folder or similar)
- once you create a link for that item, make sure it works correctly (same as above) and also make sure you can REMOVE the linked non-persistable object as well
- that is all
- thank you for coming to my TED talk

**Comment by unlikelyzero** [comment]
Verified fixed

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 03/17/2022. 

Pro tip: don't clear your cache so that you're testing with the _wrong version_ of OpenMCT. Then when you realize that you need to clear the cache, you'll have seen the error and how it looks when it's fixed! 😅

**Comment by nikhilmandlik** [comment]
Verified Fixed.
