### ISSUE TITLE
Fix Notebook entry layout

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#4954]
With the addition of [user attribution](#4452 ), Notebook entry layouts are more in need of fixing than ever.

**Comment by charlesh88** [comment]
### Change Refs
![image](https://user-images.githubusercontent.com/1056412/161875392-3be01ec0-8395-4c2f-a877-5ce78160066f.png)

![image](https://user-images.githubusercontent.com/1056412/161875412-d8221962-737f-4854-8378-7a478ebc5fb2.png)

### Testing Notes
Ideally test with user attribution enabled.
1. In the Notebook view, verify that the created datetime and creator are always displayed above the entry as shown in the Change Refs screenshots as above, and that the entry does not align to the right of the created datetime and creator, even when the view area is very wide.
2. Verify that hovering over an entry and editing looks and feels as expected.

**Comment by rukmini-bose** [comment]
Verified Testathon 06/09/2022

**Comment by unlikelyzero** [comment]
Needs Visual Test
