### ISSUE TITLE
Bump git-rev-sync and add coverage

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#4962]
#### Summary
git-rev-sync is out of date. Let's bump and add coverage!

**Comment by jvigliotta** [comment]
@unlikelyzero testing notes?

**Comment by unlikelyzero** [comment]
@jvigliotta none needed. It's all automated.
![woah-amazed](https://user-images.githubusercontent.com/12446869/159620126-3236fdf1-7107-46aa-8c3a-0981c2785c9f.gif)
