### ISSUE TITLE
[Build] Add support for node18

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#4964]
#### Summary
Node 18 should be released on April 18. We should enable it in:

- [x] CircleCI
- [x] 'overall-commit-status'
- [x] 'the-nightly'
- [ ] GHA
- [x] 'pr:platform'
- [ ] 'pr:e2e'
- [ ] 'pr:visual'

**Comment by unlikelyzero** [comment]
### Testing Notes
`nvm install 18;npm install;npm test`

**Comment by michaelrogers** [comment]
Verified in testathon 04/25/2022.

**Comment by jvigliotta** [comment]
Verified @michaelrogers verification: 04/25/2022
