### ISSUE TITLE
[Notebook] Dropped item embeds not displaying properly

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#4967]
#### Summary

Dropping an item into a notebook results in an improperly formatted embed. Snapshot embeds are fine.

#### Expected vs Current Behavior

Should show up like in the image below, with an icon and a link.

#### Steps to Reproduce

1. Drop an item into a notebook

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Additional Information
<img width="375" alt="Screen Shot 2022-03-22 at 11 07 36 AM" src="https://user-images.githubusercontent.com/12013460/159548324-ebf4f53c-0cfa-4790-a40f-7b75f85d5676.png">

**Comment by unlikelyzero** [comment]
Needs a Visual Test
1. Create Notebook
2. Create Overlay Plot
3. Drop Overlay Plot into Notebook
4. percysnapshot()

**Comment by jvigliotta** [comment]
## Testing
- Drop an object into the "drop area" of a notebook (see image below)
- Verify that the name and icon show up correctly (previously, no icon and no name were showing)

**Comment by rukmini-bose** [comment]
Verified Testathon 9/30

**Comment by ozyx** [comment]
Verified fixed -- Testathon 09/30/22
