### ISSUE TITLE
[Build] webpack coverage configuration is throwing lots of errors

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#4984]
#### Summary
When running the following:
```
nvm use 14;
npm install;
npm run build:coverage;
```

The command completes, but a lot of errors are thrown along the way.
```
ERROR in ./src/plugins/themes/espresso-theme.scss (./src/plugins/themes/espresso-theme.scss.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js!./node_modules/resolve-url-loader/index.js!./node_modules/sass-loader/dist/cjs.js!./src/plugins/themes/espresso-theme.scss)
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Can't resolve './fonts/Open-MCT-Symbols-16px.woff' in '/<dir>/openmct/src/plugins/themes'
```

**Comment by unlikelyzero** [comment]
@trusktr can you take another look at this?

**Comment by trusktr** [comment]
These errors seem to be harmlessand not terminating the processes with non zero: the app works, and coverage works.

**Comment by trusktr** [comment]
I haven't checked, but it might be coverage tool not finding those files when it encounters them because they're not JavaScript? Just a random guess.

**Comment by unlikelyzero** [comment]
### Testing Notes

```
nvm use 14;
npm install;
npm run build:coverage;
```

Verify that no errors are thrown during build stage

**Comment by ozyx** [comment]
Verified -- Testathon 7/6/22

**Comment by jvigliotta** [comment]
Verified Fixed Locally - Testathon: 7/8/22
