### ISSUE TITLE
Correlation logic of data for endpoints included in an X-Y plot should be removed from Open MCT and included as a plugin if necessary.

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#4994]
Correlation logic of data for endpoints included in an X-Y plot should be removed from Open MCT and included as a plugin if necessary.

_Originally posted by @shefalijoshi in https://github.com/nasa/openmct/pull/4881#issuecomment-1076910166

**Comment by akhenry** [comment]
@shefalijoshi There a corresponding PR for this? I feel like there is.

**Comment by shefalijoshi** [comment]
No way to test this really. Ensure that the Correlation Telemetry domain object is available to create on the VIPER deployment.

**Comment by jvigliotta** [comment]
Wasn't able to get this to work. Used pose_position_x and pose_postion_y for the options. Error on load, then error on nav (pics in that order).
![Screen Shot 2022-06-09 at 3 34 50 PM](https://user-images.githubusercontent.com/12013460/172956735-6ed37176-2630-4b51-b41e-3bf5a6516407.png)
![Screen Shot 2022-06-09 at 3 35 10 PM](https://user-images.githubusercontent.com/12013460/172956744-3e5b38b6-3b5f-41d5-955f-e8ddbf3ca722.png)
