### ISSUE TITLE
[e2e] Add code coverage support for our e2e tests

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#4995]
#### Summary
It's possible to add code coverage support to our e2e tests by following some examples:

https://github.com/istanbuljs/nyc/blob/master/docs/setup-codecov.md
https://github.com/mxschmitt/playwright-test-coverage

#### Implementation

- [x] [Remove Karma Instanbul Loader as the primary way to instrument code](https://github.com/nasa/openmct/pull/4649)
- [x] Investigate nyc
- [x] Update our e2e tests to run against the coverage webpack build
- [x] Update our circleci config to run the coverage with a `unit tests` codecov.io flag
- [x] Update our circleci config to run the coverage against all e2e tests with a `e2e` codecov.io flag
- [x] Create a combination report from codecov.io
- [x] Modify our PR logic to generate at least one e2e report on create

**Comment by shefalijoshi** [comment]
@shefalijoshi and @unlikelyzero to test this together.

**Comment by unlikelyzero** [comment]
Will verify the final numbers 7/12
