### ISSUE TITLE
Raw-loader needs to be replaced with asset modules in webpack 5

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#4997]
This seems to have broken master and needs to be reverted/fixed by using asset modules with webpack 5.

_Originally posted by @shefalijoshi in https://github.com/nasa/openmct/issues/4978#issuecomment-1078441116_

More here
https://webpack.js.org/guides/asset-modules/

**Comment by shefalijoshi** [comment]
@davetsay https://github.com/nasa/openmct/pull/4998/files#r835370706

**Comment by unlikelyzero** [comment]
Verified by Shefali

**Comment by michaelrogers** [comment]
Fix verified in testathon on 2022-04-04.
