### ISSUE TITLE
[Edit] Remove is available for invalid objects

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#50]
When in Edit mode, the Remove action is available for the object being edited, as well as other objects in the domain object hierarchy above it (in the Library)

Desired behavior is that Remove should be unavailable here (and, more generally, that modification should only be permitted for the domain object being edited and its direct descendants)

Proposed solution:
- Add a `mutation` policy category to determine which objects are mutable
  - Currently, this is handled as a `hasFeature('creation')` check; this check should instead be moved into an instance of the `mutation` policy
- Add a policy disallowing `mutation` in Edit mode for objects which are not the object being edited or one of its direct descendants 
- Add an `action` policy restricting the `remove` action to objects whose contextual parent allows `mutation`

**Comment by VWoeltjen** [comment]
Rephrasing the above:

1. Remove should be valid (in principle) only for objects with a parent.
2. Remove should be available (by policy) only when an object's parent can be user-modified (by policy)
3. User modification of objects that are outside of the current editing scope should be disallowed by policy.

Why not consolidate 1 and 2 and have Remove consult policy about mutation? Because it keeps Remove's dependencies narrow - it only needs to know about the things that are necessary to do its job (it needs to get the parent.)

Why not consolidate 2 and 3 and just have a policy that suppresses Remove specifically in Edit mode? Because then, for every other circumstance where an object should not be modified, it needs to come with its own policy rejecting Remove.

Why not consolidate all of 1 through 3 and have a Remove that is aware of Edit mode? For both of the reasons stated above.

**Comment by larkin** [comment]
I think we've spent enough time on this that we should leave it be.  It works well enough right now, any time we have touched it it has broken and been time consuming to fix.  It's fragile, policy is fragile, we are assuming too much.

We should focus our efforts elsewhere and come back to this later.

**Comment by larkin** [comment]
At this time we don't have a "correct" solution for this.

Consider this a set of problems that we would take into consideration only while doing a complete review of the editing interface.  

Closing as wontfix.
