### ISSUE TITLE
[e2e] Add console error detection to all of our e2e tests

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#5000]
#### Summary
It's possible to intercept console errors in playwright. Let's update our test suite to detect console errors during runtime and fail if found.

Implementation here: https://github.com/microsoft/playwright/discussions/11690#discussioncomment-2060397

**Comment by unlikelyzero** [comment]
### Testing Notes

`npm run test:e2e:full` runs without error

Add the following to a test

```js
wait page.evaluate(() => console.log('error'));
```
and verify that the test fails

**Comment by unlikelyzero** [comment]
### Testing Notes

`npm run test:e2e:full` runs without error

Add the following to a test

```js
wait page.evaluate(() => console.log('error'));
```
and verify that the test fails

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 06/27/22 by adding `await page.evaluate(() => console.error('error'));` to the `smoke.e2e.spec.js` test.
