### ISSUE TITLE
Replace app.js with webpack-dev-server

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#5031]
#### Summary
Currently we provide [app.js](https://github.com/nasa/openmct/blob/master/app.js) as a very basic web-server for development purposes. [webpack-dev-server](https://webpack.js.org/configuration/dev-server/) could do the same thing which would have multiple advantages:
- Remove any ambiguity about the purpose of `app.js`( app.js is **not** an Open MCT server, and should only be used for dev purposes.)
- Remove redundant code
- Remove a dependency on webpack-dev-middleware
- The security and familiarity of using an industry standard tool.

**Comment by unlikelyzero** [comment]
@akhenry we had that filed here: https://github.com/nasa/openmct/issues/4922 to close another issue.

I'd like to demo what we'd gain by using app.js, before moving off of it

**Comment by unlikelyzero** [comment]
@akhenry we've done quite a bit of work in the last 6 weeks on app.js. I think we should take a hard look at this.

Things to consider:
- [ ] How are we generating sourcemaps for unit and e2e tests
- [ ] How are we using NODE_ENV variables at build time and runtime? What associated functionality do we want between them?
- [ ] Why do we not demonstrate how we want folks to run this?

**Comment by scottbell** [comment]
Testing Instructions:

- Ensure `npm start` works for local storage
- Ensure `npm start` works for CouchDB

**Comment by jvigliotta** [comment]
Verified Fixed Locally - Tested with Local Storage and with CouchDB and there were no issues.

**Comment by akhenry** [comment]
Verified fixed.
