### ISSUE TITLE
Notebook types for shift logging

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#5035]
Introduce new Notebook "typing" to allow support for desired shift logging functionality. Details from discussion 4/5/22:

- New types:
  - Notebook (unrestricted type)
  - Shift Log (restricted type)
- Pages are locked or unlocked (exact terminology is TBD).
- Unlocked pages allow same functionality as current purpose Notebook.
- Locked pages do not allow new entries or editing/deletion of existing entries.
- A section with at least one locked page cannot be deleted.
- A Notebook with at least one section with at least one locked page cannot be deleted.
- Implementation notes:
  - Two different Notebook types in the Create menu, avoids issues with "create-only" properties to prevent Notebook type switching after creation.
  - Per deployment: Notebook types (restricted/unrestricted) can be named (Notebook/Shift Log/etc.).

**Comment by unlikelyzero** [comment]
@jvigliotta please run through https://github.com/nasa/openmct/pull/5073

**Comment by jvigliotta** [comment]
## Testing 
- make sure regular notebooks work exactly how they used to
- make sure you can pass in a name to the Notebook and RestrictedNotebook plugins and that they show in Open MCT
- create a restricted notebook
- make sure you can do anything that you can do to a normal notebook (observe "Lock Page" shows when an entry is started)
- open section/page sidebar
- Lock a page (verify confirmation)
- make sure locks show for page and the section that page is in
- make sure you cannot remove the restricted notebook (right click remove from tree)
- make sure you can't edit section titles or section names if locked
- try to delete/edit an entry from a locked notebook (you should not be able)
- try to remove an embed from a locked page entry (make sure you can preview though)
- make sure if the notebook section/page was default, that it was NOT default once locked
- try to drop an item into a locked page (you should not be able), do the same with a snapshot
- make sure search works as expected
- in search, make sure there are locked and unlocked page entries with embeds, make sure you can remove unlocked ones and not remove locked ones

**Comment by rukmini-bose** [comment]
Verified Testathon 06/15/2022 (I'm pretty sure)

**Comment by unlikelyzero** [comment]
Closing as feature complete. Will file new issues as they come across.
