### ISSUE TITLE
`autoscale` turned off doesn't work

### ISSUE THREAD

**Issue by trusktr** [nasa/openmct#5039]
#### Summary

Turning off autoscale causes ticks to disappear, and zoom/pan doesn't work, with an error in console:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'min')
    at VueComponent.updatePan (MctPlot.vue?5bbd:986:1)
    at VueComponent.trackMousePosition (MctPlot.vue?5bbd:678:1)
```

#### Expected vs Current Behavior

I'm not sure how autoscale turned off should work, I've only experienced it in broken state.

#### Steps to Reproduce

1. create an overlay plot
2. save the overlay plot without modifications
3. create a sinwave generator under the overlayplot
4. click the overlay plot in the sidebar so it is active instead of the sin wave generator
5. turn on edit mode for the overlay plot
6. turn off autoscale
7. note that the ticks in the Y axis are gone
8. save the overlay plot
9. try to pan (f.e. alt + mouse drag in Windows)
10. note the error in the console

#### Environment

* Open MCT Version: `master` branch (3a11291a3b6d4562e0685d1b78dbe227318fc46a as of time of writing)
* Deployment Type: npm start
* OS: Windows, but I doubt it is Windows-specific
* Browser: Chrome, but probably same issue in any browser

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Additional Information

Here is an overlay plot before turning off autoscale, showing no error in console yet:

![Screenshot 2022-04-06 134826](https://user-images.githubusercontent.com/297678/162068219-5f9e14d6-6387-459a-a5ba-6b045fdbe707.png)

Here is what it looks like immediately after unchecking the autoscale check box, showing ticks are missing, but no error in the console yet:

![Screenshot 2022-04-06 135003](https://user-images.githubusercontent.com/297678/162068456-0ad0eda5-ef4b-418f-a58c-7783e7322eea.png)

After saving the overlay plot and trying to pan by holding alt while click-dragging with the mouse, the console shows an error, and the pan attempt did not move the plot:

![Screenshot 2022-04-06 135256](https://user-images.githubusercontent.com/297678/162068867-0dcbd0a8-bb91-4d6f-bdef-e5f4e66669d0.png)

**Comment by trusktr** [comment]
I noticed a workaround:

- after saving the overlay plot with autoscale turned off
- click+drag to zoom by making a box selection
- after performing zoom in this fashion, the ticks come back.
- at this point, the plot is fully zoomable and pannable like normal.

**Comment by unlikelyzero** [comment]
Filing as a critical because of workaround

**Comment by trusktr** [comment]
Fix in https://github.com/nasa/openmct/pull/5040

**Comment by shefalijoshi** [comment]
Verified fixed

**Comment by charlesh88** [comment]
Verified fixed Testathon 04-25-22.

**Comment by charlesh88** [comment]
Saw the same problem on banner during Testathon 04-25-22.

**Comment by unlikelyzero** [comment]
Note: this e2e test needs to be re-enabled

**Comment by akhenry** [comment]
Is this fixed or not?

**Comment by shefalijoshi** [comment]
See #6230 #6229

**Comment by unlikelyzero** [comment]
Testing Notes:

Test this in multi-y-axis overlay plots

**Comment by ozyx** [comment]
Verified fixed Testathon 02-09-2023

Autoscale turned off works but we need to set min and max now.

Alt panning works well but seeing a bunch of warnings in the console (may be expected):
![image](https://user-images.githubusercontent.com/9259993/217956819-ae3ac6fd-5cad-4093-83f9-17edcf5d2559.png)

**Comment by unlikelyzero** [comment]
@unlikelyzero to file RFE for alerting when save was successful BUT configuration was reverted back to autoscale
