### ISSUE TITLE
Allow image telemetry to display camera orientation information

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#505]
<p>Jay and Charles, 8/21/15<br/> Graphically indicate camera orientation (rotation, pitch, etc.) over imagery when the data is available. Optionally allow the user to hide and show this element. </p> 

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1521
Originally created: Fri, 21 Aug 2015 11:21:24 -0700
Updated: Thu, 7 Jan 2016 13:27:05 -0800

**Comment by larkin** [comment]
IMO, this would be handled by display composition-- e.g. putting the image object in a fixed position and overlaying other values overhead.
