### ISSUE TITLE
Add static limit values to LAD tables

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#5051]
**Is your feature request related to a problem? Please describe.**
In the case where static limit values are defined by a limit provider for a given telemetry point, our LAD tables should display those limit values. Currently static limit values are rendered as a limit line in plots, this would bring the same concept to LAD tables.

**Describe the solution you'd like**
Telemetry limit values should be displayed as additional columns in the LAD table

**Additional context**
There is a broader desire to bring all of the customizability of telemetry tables to LAD tables. If considered as part of that change, the new limit columns could be optionally shown or hidden by the user.

**Comment by akhenry** [comment]
Let's make the limit column show by default IF LIMITS ARE DEFINED for any of the telemetry points. We need to make sure it works with the column show/hide controls in the inspector.

**Comment by scottbell** [comment]
I've a got first draft here, but could use some design help from @charlesh88 and/or @akhenry:
<img width="1689" alt="Screenshot 2023-10-16 at 4 06 47 PM" src="https://github.com/nasa/openmct/assets/9853862/047c58f1-6cd6-464c-85aa-598ca28370c6">

We've got two values (high and low) for each limit that needs to be displayed and creating a string that combines the together. Do we instead want separate columns for high and low?

Also I could use some advice about limits in general. As telemetry items could have different classes (e.g., one could have "CRITICAL", and another "HIGH"), I'm currently taking the union of them all for column names. Is this correct?

Thanks for the help!

**Comment by scottbell** [comment]
This happened awhile back, but @charlesh88 & @akhenry were good with both the union of limits in the table, and the string combining the high/low values into a string (as LAD tables aren't sortable).

**Comment by scottbell** [comment]
To test:

1. Create a LAD table and a mixture of objects to it with limits and without limits, namely a Sine Wave Generator and an Event Message Generator.
2. Ensure you can see various limits in the table.
3. Edit the LAD table
4. In the inspector, hide the various columns and ensure they work.
5. Refresh the page, ensure the columns you selected remain hidden.
6. Remove the Sine Wave Generator from the LAD table
7. Ensure the LAD table no longer has Units or limit columns
8. Edit the LAD table
9. Ensure the Units & Limits columns aren't there.

**Comment by unlikelyzero** [comment]
@scottbell let's sync on testing this as a feature on quickstart
