### ISSUE TITLE
[Imagery View] View large has a delay for image sizing

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#5053]
#### Summary

If you choose to "view large" on an imagery item in a display or flexible layout, there's a 400ms delay for the image to resize to fit the new large container.

#### Expected vs Current Behavior

Should not have a delay.

#### Steps to Reproduce

1. Select the "View large" option for imagery in a display or flexible layout
2. Notice there is a delay before the image is enlarged to fit the larger container

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?

**Comment by jvigliotta** [comment]
### Testing
- view large an imagery view in a display or flexible layout
- note that there is no delay for the image to be enlargenated (yes... that's _not_ a word, but it should be no?).

**Comment by shefalijoshi** [comment]
Verified fixed

**Comment by akhenry** [comment]
Verified fixed.
