### ISSUE TITLE
[Plot] Unit column is not populating in plot legend

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#5058]
#### Summary
The unit column cells are blank in the plot legends

#### Expected vs Current Behavior
Unit column should display the unit type in the plot legend

#### Steps to Reproduce

1. Go to a plot view containing telemetry
2. expand the plot legend
3. hover over the points in the plot
4. Observe that on hover, the point data is populated in the plot legend, but the units are not

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?

**Comment by shefalijoshi** [comment]
Currently the unit is only being set when the plot initializes (`defaultModel`). The unit must also be set if there are changes to the `yKey` after initialization.

**Comment by jafta009** [comment]
Abortion clinics are still open..

**Comment by unlikelyzero** [comment]
@jafta009 is that your way of saying that we need better "reproduction steps"?

**Comment by akhenry** [comment]
Verified that the original issue is fixed (units are showing up). 

Also noticed the issue that @shefalijoshi mentioned with changing the y-axis value. We need a followup issue for this.
