### ISSUE TITLE
[Plot] utc formatting could be making data unplottable

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#5059]
#### Summary
Could be a VISTA configuration issue. When changing vista configuration `utcFormat` from `utc.day.of.year` to `utc`, data does not plot.

#### Expected vs Current Behavior
Expect data to plot
Plot y-axis shows min/max values correctly but no points are plotted in display range

#### Regression
Working in VISTA R4.5 and VISTA R4.5.1

#### Steps to Reproduce

1.
2.
3.
4.

#### Environment

* Open MCT Version: `#vista-r4.9.0-rc19`
* Deployment Type: OMM R4.9
* OS:
* Browser: Chrome

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

**Comment by shefalijoshi** [comment]
@davetsay Is there any update on this bug?

**Comment by davetsay** [comment]
This was fixed in an `Open MCT for MCWS` formatter
