### ISSUE TITLE
[Timers] Avoid use of polling

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#506]
<p>Keep timers in sync without using HTTP polling. This causes a lot of extra requests to be made, and doesn't keep things very well synchronized. Would be nice to have a shared WebSocket message bus that allows these changes (and object mutations, generally!) to be synchronized.</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1491
Originally created: Wed, 29 Jul 2015 13:58:44 -0700
Updated: Thu, 14 Jan 2016 17:07:15 -0800

**Comment by larkin** [comment]
a larger issue here around a standalone persistence store for Open MCT that handles item sync.  Might be a candidate for the roadmap...

**Comment by larkin** [comment]
For now, closing as a wontfix.
