### ISSUE TITLE
Image pan and zoom lock persistence

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#5068]
**Is your feature request related to a problem? Please describe.**
When pan and zoom are enabled in imagery component the setting should always persist until the user deliberately resets it.

**Comment by charlesh88** [comment]
Related to feedback from VIPER egress testing sessions Feb 2022 and recent stakeholder discussions. Behavior should be:
- Change current behavior that pauses image on pan/zoom action - _don't_ pause the image on that action. Paused states should only occur when: 
  - The user directly pauses the image via the Pause button. 
  - User clicks on a past image thumbnail.
- The orange "paused" border and icon should only be displayed when the view is in real-time mode AND the view is in a paused state. 
  - Zoom/pan lock should have no effect pausing the image.
  - The warning border and icon are not shown when the view/TC is in fixed time mode.
- Zoom and pan lock should be in place until a user actively disables it, including zooming out to 100%, resuming RT playback, etc.

**Comment by charlesh88** [comment]
See #5149, this is very related.

**Comment by michaelrogers** [comment]
### How to test
1. Navigate to Example Imagery Object
2. Select `Local Time` 
3. Activate zoom features either by buttons, wheel scroll, or hot keys
4. Observe that the telemetry is not paused and new imagery streams in as expected

**Comment by ozyx** [comment]
Verified -- 5.24.22 Testathon

**Comment by rukmini-bose** [comment]
Testathon Verified 05/24

**Comment by jvigliotta** [comment]
Testathon - Verified Fixed: 6/15
