### ISSUE TITLE
Images are slow to load initially

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#507]
<p>(From @slhale, testathon 6/25/2015)</p> <p>Images are slow to load initially. Perhaps make a loading icon?</p>

Migrated from: WTD-1380
Originally created: Thu, 25 Jun 2015 17:24:10 -0700
Updated: Thu, 14 Jan 2016 16:34:58 -0800

**Comment by charlesh88** [comment]
Still an issue?

**Comment by larkin** [comment]
still an issue, we need design / input as to how we should handle image loading.
