### ISSUE TITLE
[Image Telemetry] Timestamp updates early

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#509]
<p>Timestamp in Imagery view updates as soon as new image URL arrives, but actual image does not display until it has loaded. This can result in confusion esp. if it takes more than a small fraction of a second for images to load</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1528
Originally created: Wed, 26 Aug 2015 10:33:14 -0700
Updated: Thu, 14 Jan 2016 16:33:12 -0800

**Comment by larkin** [comment]
fixed.

**Comment by larkin** [comment]
#507 tracks a more pertinent issue, slow image loading
