### ISSUE TITLE
[Telemetry Collection]  Telemetry table excluding start and end bound values

### ISSUE THREAD

**Issue by nikhilmandlik** [nasa/openmct#5095]
#### Summary
Telemetry table excluding start and end bound data values.

#### Expected vs Current Behavior
Telemetry table should include values at start and/or end bound timestamp

#### Steps to Reproduce
1. Create Telemetry Table
2. Add telemetry point to it
3. For reference for latest value create Lad table and add same telemetry point to it
4. in Display layout add Telemetry Table (sort desc) and Lad table  compare values in realtime (should match)
5. now change to fixed time and observe/compare latest value in Lad Table vs Telemetry Table (refer to attached snapshot)

#### Environment
VIPER Version Information
Version: 2.0.2
Build Date: Thu Apr 07 2022 14:51:04 GMT-0700 (Pacific Daylight Time)
Revision: 06c9ce01e361e45d1814775eff9709a63f5d0977
Branch: release/2.0.2

Openmct Version Information
Version: 2.0.2
Build Date: Tue Apr 05 2022 16:53:46 GMT-0700 (Pacific Daylight Time)
Revision: 05b4a8149ae299784378b375364092600df37940
Branch: release/2.0.2

## System:
 - OS: macOS 11.6.4
 - CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
 - Memory: 57.27 MB / 16.00 GB
 - Shell: 5.8 - /bin/zsh
## Binaries:
 - Node: 18.0.0 - ~/.nvm/versions/node/v18.0.0/bin/node
 - npm: 8.6.0 - ~/.nvm/versions/node/v18.0.0/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash
 - Perl: 5.30.2 - /usr/bin/perl
 - PHP: 7.3.29 - /usr/bin/php
 - Python: 2.7.16 - /usr/bin/python
 - Python3: 3.9.8 - /Users/nmandlik/Desktop/NASA/brew/bin/python3
 - Ruby: 2.6.3 - /usr/bin/ruby
## Browsers:
 - Brave Browser: 100.1.37.113
 - Chrome: 100.0.4896.127
 - Safari: 15.4

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Additional Information
issue at lines: `187/188` `openmct/src/api/telemetry/TelemetryCollection.js`
https://github.com/nasa/openmct/blob/402cd15726fce61a78c518342ff8e2d013f51ba2/src/api/telemetry/TelemetryCollection.js#L187

<img width="1080" alt="Screen Shot 2022-04-21 at 9 51 57 AM" src="https://user-images.githubusercontent.com/1292612/164511662-ab240688-a38b-47e8-a98a-82a759a17274.png">

**Comment by davetsay** [comment]
verified but filed new issue #5111

**Comment by akhenry** [comment]
NOT verified per @davetsay

**Comment by charlesh88** [comment]
Verified fixed Testathon 4/28/22

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 4/28/2022

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by davetsay** [comment]
Not verified
Reproduction steps
1. create a telemetry table
2. drag and drop a telemetry endpoint into the table
3. set time conductor to fixed time
4. go to the latest timestamped row
5. change the time conductor to match the timestamp of the last row exactly
6. observe that the row is removed from the table

* same behavior is observed with matching the start input of the time conductor with the timestamp of the first row

**Comment by jvigliotta** [comment]
## Testing
- SAME as before... but, there is a YAMCS bug
- if the end time === datum timestamp, it will not show up. this is a YAMCS bug, and will not prevent this fix from passing

**Comment by davetsay** [comment]
verified (locally since yamcs has a bug)

**Comment by nikhilmandlik** [comment]
Verified Fixed. (expect YAMCS issue)
