### ISSUE TITLE
After a Domain Object is modified, composition changes are not being saved

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#5097]
#### Summary
When creating new or editing an existing domain object, composition changes are sporadically not being persisted. For example, only 2 out of 3 objects added to an object will be persisted. This _seems_ to occur more frequently with newly created objects, but has been observed occurring with previously created objects as well.

#### Expected vs Current Behavior

All edit actions should be persisted on the Save action.

#### Steps to Reproduce

1. Create a domain object that has composition (layout, plot, table, etc.) 
2. Add one or more domain objects to the composition via drag and drop.
3. Modify the domain object (add styling, change layout if nested within a display layout, name change from browse bar, etc.)
4. Add one or more domain objects to the composition via drag and drop.
5. Save and Finish editing.
6. Observe: Original composition changes prior to object modification are saved.
7. Observe: Composition changes after object modification are not saved. 

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS: MacOS
* Browser: Chrome

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

**Comment by davetsay** [comment]
Troubleshooting notes added to #5033 

I haven't been able to replicate losing composition, but this is easily reproducible so hoping its related.

**Comment by davetsay** [comment]
If an object is modified, the composition changes (only composition add was tested) are dropped on save.

Examples
- Add telemetry to flexible layout, modify number of panes, toggle horizontal/vertical panes, add more telemetry. Only the original telemetry will be saved.
- Add telemetry to a table to a display layout, modify the table (change dimensions, apply style), add more telemetry. Only the original telemetry will be saved.

**Comment by shefalijoshi** [comment]
I THINK it's fixed? Unless I didn't follow the steps correctly. :)

**Comment by rukmini-bose** [comment]
Verified 05/02– Made 2 different flexible layouts and added different tables and such and everything seems to save correctly.

**Comment by unlikelyzero** [comment]
### e2e testing notes
1. Create Telemetry object
2. Create Flexible Layout
3. Navigate to Flexible Layout
4. Modify Number of Panes
5. Add Telemetry
6. Save
7. Verify Number of Panes and Telemetry changes are both saved
