### ISSUE TITLE
Multiple telemetries destroy table performance

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#5102]
#### Summary
For tables with multiple telemetries added, combining data into the table is not performant. The datasets are combined individually, and each additional dataset takes exponentially longer than the last.

#### Expected vs Current Behavior
Tables should load and render rows in a reasonable amount of time

#### Steps to Reproduce

1. Create a telemetry table and add several telemetry endpoints (5 to 10)
2. Query a time period (start small) using the time conductor (fixed time is easier to observe and control amount of datapoints)
3. Observe time it takes for each dataset to render, shown by the rows count in the lower right of the table updating
4. Change time window to increase amount of datapoints if time to render each set of data is negligible
5. Can also compare to an overlay plot with same data for kicks

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 04/25/2022
