### ISSUE TITLE
Add a regression test for image thumbnails

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#5106]
#### Summary
Add a test to catch regressions of the functionality enabled by https://github.com/nasa/openmct/issues/4884

Preferably an e2e test.

**Comment by unlikelyzero** [comment]
### e2e testing notes

This should be relatively straightforward.

Create a Display Layout
Create example Imagery Object
Add Example Imagery Object to Display layout without modification. Do thumbnails appear?
Modify Example Imagery object within Display layout to be smaller. thumbnails disappear
Modify Example Imagery object within Display Layout to be larger. Thumbnails appear
