### ISSUE TITLE
LAD table not quite as LAD as telemetry table

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#5111]
#### Summary

When a telemetry endpoint is added to both a LAD table and telemetry table, the LAD table does not display the most recent data whereas the telemetry table does.

#### Expected vs Current Behavior
LAD table and telemetry table with the same endpoint added should display the same latest data. LAD table does not display the latest data.

#### Steps to Reproduce

1. Create a LAD table and add a telemetry endpoint
2. Create a telemetry table and add the same telemetry endpoint as was added in step 1
3. Add both tables to a display layout
4. Set time conductor to realtime mode, and set end offset to 0
5. Set time conductor to fixed time mode
6. Compare the timestamps for the LAD table and the latest timestamp in the telemetry table

Note that manually setting the endtime for fixed time mode will give consistent values for the latest available data in that range.

#### Environment

* Open MCT Version: 378a4ca28242d9bc13633f639c2227a3cc236cb8
* Deployment Type: VIPER ce8ba4f02230848be58ec592f55ba40bc4d62c7d
* OS:
* Browser: chrome

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

**Comment by jvigliotta** [comment]
## Testing
- what dave said in "Steps to Reproduce", minus where he messed up the formatting and linked to our very first merged PR
- also, play around with LAD tables and time systems and modes (local vs fixed)

**Comment by charlesh88** [comment]
Verified fixed Testathon 4/28/22

**Comment by akhenry** [comment]
Verified fixed

**Comment by jvigliotta** [comment]
## Testing
- SAME as before... but, there is a yamcs bug
- if the start time === datum timestamp, it will not show up. this is a YAMCS bug, and will not prevent this fix from passing

**Comment by akhenry** [comment]
Verified fixed (aside from Yamcs issue)

**Comment by nikhilmandlik** [comment]
Verified Fixed.  Yamcs Issue not fixed

**Comment by davetsay** [comment]
verified (locally since yamcs has a bug)
