### ISSUE TITLE
[Plots] e2e tests are failing for log plots

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#5112]
#### Summary
Our e2e tests fail on log plot tests when I run them locally with the following error:

```
  2 failed
    [chrome] › plugins/plot/log-plot.e2e.spec.js:30:10 › Log plot tests › Can create a log plot. ===
    [MMOC] › plugins/plot/log-plot.e2e.spec.js:30:10 › Log plot tests › Can create a log plot. =====
  2 passed (1m)
::error file=e2e/tests/plugins/plot/log-plot.e2e.spec.js,title=[chrome] › plugins/plot/log-plot.e2e.spec.js:30:10 › Log plot tests › Can create a log plot.,line=152,col=34::  1) [chrome] › plugins/plot/log-plot.e2e.spec.js:30:10 › Log plot tests › Can create a log plot. ==%0A    Error: expect(received).toBe(expected) // Object.is equality%0A%0A    Expected: 28%0A    Received: 0%0A%0A      150 | async function testLogTicks(page) {%0A      151 |     const yTicks = page.locator('.gl-plot-y-tick-label');%0A    > 152 |     expect(await yTicks.count()).toBe(28);%0A          |                                  ^%0A      153 |     await expect(yTicks.nth(0)).toHaveText('-2.98');%0A      154 |     await expect(yTicks.nth(1)).toHaveText('-2.50');
```

#### Expected vs Current Behavior
e2e tests should pass

#### Steps to Reproduce
1. npm run test:e2e:full

#### Environment
* Open MCT Version: release/2.0.3 378a4ca28242d9bc13633f639c2227a3cc236cb8
* Deployment Type: dev local

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

**Comment by unlikelyzero** [comment]
I didn't realize an issue was filed for this. I've fixed it in this PR https://github.com/nasa/openmct/pull/5168
