### ISSUE TITLE
Better sizing strategy for dial Gauges

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#5117]
Make dial Gauges proportionally size themselves to fit their available space. Currently, that type of Gauge only fits by width, but should also take available height into account.

**Comment by charlesh88** [comment]
WIP in branch `gauge-5117`.

**Comment by charlesh88** [comment]
### Testing Notes IN PROGRESS
![image](https://user-images.githubusercontent.com/1056412/165587183-7432714e-4a7d-44e9-be80-af9d75262cc1.png)

**Comment by rukmini-bose** [comment]
Verified 4/28- do not see any cropping behavior within the gauges.

**Comment by charlesh88** [comment]
Verified fixed Testathon 4-28-22.
