### ISSUE TITLE
[e2e] Enable lint enforcement on e2e suite

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#5124]
#### Summary
We had a breakage where `.only` was on a WIP PR and was merged in. We should add it to our linting rules.

Edit: @ozyx discovered that we weren't linting the tests at all! This Issue now captures that effort

**Comment by unlikelyzero** [comment]
### Testing Notes
Add a .only to an e2e test on a PR
Verify that `npm run lint` fails locally and on circleci check

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 06/27/22 - linting works for end to end tests
