### ISSUE TITLE
[Alphanumerics] Alphanumeric Telemetry Views in Display Layouts Bounds Issue

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#5130]
#### Steps to Reproduce

1. Add an Alphanumeric view of telemetry to a display layout
2. Add the same view as a telemetry table (for comparison)
3. In local clock mode, add a 5 second end offset
4. Switch to fixed time, notice the telemetry table will finish out the 5 second offset (end bounds), but the alphanumeric just stops immediately

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available? (other views, but not really)
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Additional Information

https://user-images.githubusercontent.com/12013460/165642338-29ec71d5-ede8-47d2-807b-24b486739365.mov

**Comment by jvigliotta** [comment]
## Testing
- just perform the reproduction steps and make sure the telemetry still comes in after switching to fixed time

**Comment by akhenry** [comment]
Good catch!

**Comment by charlesh88** [comment]
Verified fixed Testathon 4/28/22

**Comment by akhenry** [comment]
Verified fixed
