### ISSUE TITLE
Local clock mode should remember previously used offsets instead of always using default offsets

### ISSUE THREAD

**Issue by nikhilmandlik** [nasa/openmct#5135]
#### Summary
When switching from Fixed time to local clock start/end time offsets should not reset.

#### Expected vs Current Behavior
👀  into Summary ☝️ 

#### Steps to Reproduce
1. make sure you are on local clock and end time is all zeros (00:00:00)
2. switch to fixed time mode. (bounds should not change)
3. Switch back to local clock mode. Observe that end offset has changed to default value, instead of 00:00:00

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [X] Regression? Did this used to work or has it always been broken?
- [X] Is there a workaround available?
- [X] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

**Comment by akhenry** [comment]
@ozyx Check in with @davetsay who may have context for this. I _think_ it's a regression, but now I'm not so sure :)

**Comment by ozyx** [comment]
Not a regression as per discussion w/ @davetsay

**Comment by jvigliotta** [comment]
Testathon - 6/9/22: Verified Fixed
(Also works for remote clock)
