### ISSUE TITLE
Condition Widgets trigger hundreds of persistence calls.

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#5137]
#### Summary
Navigating to a condition widget triggers hundreds of persistence calls, despite nothing having changed.

#### Expected vs Current Behavior
Condition widgets (and indeed all object views) should **not** be mutating domain objects unless the user has actually changed something. Mutating a domain object will trigger persistence, which is expensive. Do not use mutation to establish an object's default state.

#### Steps to Reproduce
1. Create a condition widget
2. Create a condition set, drag in a telemetry point, and define a basic rule.
3. Edit the condition widget and apply some conditional styling
4. Save the condition widget. Open the network tab and observe that it is now making persistence calls in an endless loop.

#### Environment
* Open MCT Version: e75befafbdf0eaf5c81380282971211e7c40957a
* Deployment Type: testathon

#### Impact Check List
- [X] Data loss or misrepresented data? - Eventually causes browser to crash
- [X] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [X] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

**Comment by akhenry** [comment]
It looks like [this is the offending line of code](https://github.com/nasa/openmct/blob/master/src/ui/components/ObjectView.vue#L218).

There are two issues here -
1. This line of code mutates the domain object in view mode, even if nothing about the object has changed.
2. The logic here encodes knowledge of condition widgets into ObjectView. ObjectView should be agnostic of Condition Widgets.

**Comment by shefalijoshi** [comment]
I'm still seeing requests from condition widgets
