### ISSUE TITLE
Unset Gauge limits are being handled as 0

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#5139]
#### Summary
If a low and/or high limit is not set for a Gauge, it is treated by the Gauge as if it _was_ actually set to 0. Instead, that limit should not be displayed at all. The fix here is to use a `v-if="lowLimit !== empty` instead of the current `null` check.

#### Steps to Reproduce

1. Edit props:
<img width="350" alt="image" src="https://user-images.githubusercontent.com/1056412/165859216-fd63ed32-a365-4e70-9bc9-bf034c2f0e3a.png">

2. Observe: limits are displayed properly.
<img width="170" alt="image" src="https://user-images.githubusercontent.com/1056412/165859437-68b16940-423c-442f-a76f-f866454738a6.png">

3. Edit properties to remove limit definitions
<img width="350" alt="image" src="https://user-images.githubusercontent.com/1056412/165859477-28a74930-e3d8-4783-b7f0-4b28d31d0ec6.png">

4. Observe: limits should not be displayed, but are.
<img width="167" alt="image" src="https://user-images.githubusercontent.com/1056412/165858629-9276befb-8585-4535-91c6-9e9e4b05242c.png">

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

### Testing Notes
1. Create a Gauge view or edit existing.
2. Repeat steps 1 - 4 in 'Steps to Reproduce' above.
3. Verify that limits are not displayed, and the Gauge looks similar to this:
![image](https://user-images.githubusercontent.com/1056412/165864944-2ca293b1-63d2-4bed-8af1-55f1b4c51ab3.png)

**Comment by charlesh88** [comment]
WIP in branch `limits-5139`.

**Comment by charlesh88** [comment]
A fix for this caused a regression that made the limits not display at all. Work being done in the `gauge-fixes` branch by @charlesh88 will fix this.

**Comment by michaelrogers** [comment]
During testathon 06/15/2022, a regression on gauge low/high limits was observed. If a user sets a range low and a range high value, it is not displayed in any of the gauge types
![Screen Shot 2022-06-15 at 5 34 14 PM](https://user-images.githubusercontent.com/7417521/173944959-f2846769-c0fe-4bb0-8ec2-16e72f3359b6.png)
![Screen Shot 2022-06-15 at 5 34 23 PM](https://user-images.githubusercontent.com/7417521/173945113-ecf67b8c-6a5a-41d1-bd70-83332a637df1.png)
.

**Comment by ozyx** [comment]
Testathon 6/23/22:

Verified that after removing limits, the min and max values are displayed instead.

Caveat:
- Ran into issues with properties persisting after changing them. Had to focus a different object and come back to the Gauge in order for the property changes to persist. Seems likely a separate issue?

**Comment by alizenguyen** [comment]
Testathon 6/27/22:

Still see what Jesse is seeing about the property change is not implemented until you move to a different object and come back.

**Comment by unlikelyzero** [comment]
General issue filed here https://github.com/nasa/openmct/issues/5398

**Comment by charlesh88** [comment]
### Testing Notes
See https://github.com/nasa/openmct/issues/5323

**Comment by davetsay** [comment]
verified (although i had to create two gauges to compare as there is a forms mutation bug preventing exact replication steps from working)
