### ISSUE TITLE
Improved image pause handling

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#5149]
Some confusion was encountered by users that zooming in on the most current image caused the orange "paused" warning to appear immediately. The expectation was to pause the view, but not show the warning until a new image had come in.

(Jamie edit) Think this is related: #5113

**Comment by charlesh88** [comment]
Imagery should no longer pause on zoom/pan when view or TC is in fixed time mode. See important related notes in #5068.

**Comment by michaelrogers** [comment]
### How to test
1. Navigate to Example Imagery Object
2. Select `Local Time` 
3. Activate zoom features either by buttons, wheel scroll, or hot keys
4. Observe that the telemetry is not paused and new imagery streams in as expected

**Comment by ozyx** [comment]
Verified -- 5.24.22 Testathon

**Comment by rukmini-bose** [comment]
Verified Testathon 05/24/2022

**Comment by ozyx** [comment]
*Really* Verified - -Testathon 6.9.22

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 06/15/22
