### ISSUE TITLE
Review/revise markup/CSS associated with stacked plot mode

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#515]
<p>For <a href="https://trunk.arc.nasa.gov/jira/browse/WTD-625" title="Stacked plot view development" class="issue-link" data-issue-key="WTD-625"><del>WTD-625</del></a>, stacked plot mode has been implemented by repeating the markup and CSS for a single plot multiple times. The domain axis (time axis) is hidden for all but the bottom axis, but the space it would normally occupy is still in use. This is undesirable from a space-consumption perspective; desired appearance would be to have only minimal vertical space between subplots in a stacked plot.</p> <p>This should be fixable with CSS, e.g. by adding or changing the classes used by the plot elements (e.g. by adding a "ng-class="</p> { 'some-new-class-name': !$last } <p>" to conditionally apply the new class only when it is not the last subplot in a loop.</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-630
Originally created: Fri, 12 Dec 2014 11:02:52 -0800
Updated: Thu, 14 Jan 2016 17:09:51 -0800

**Comment by charlesh88** [comment]
Fixed and also obviated by new plot functionality coming from #1557
