### ISSUE TITLE
[Gauge Plugin] Limits and Composition Issues

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#5155]
(https://github.com/nasa/openmct/issues/4896#issuecomment-1115430493)

Think this is related to #5139 as well

#### Summary

When you add a telemetry item, that does not have set limits and you do not have manually set limits on the gauge property, "NaN" will show where the min and max limits should or should not.

Also, if you remove an item from the gauge (via the tree or the elements pool), then the gauge itself will still show the value from the telemetry item. This can be fixed by navigating away and returning or refreshing.

#### Testing instructions

1. Add a telemetry item without limits provided to a gauge (note, NaN is displayed for min/max values)
2. Remove a telemetry item from a gauge (via tree or elements pool (note, the value of the telemetry is still displayed

#### Environment

Version: 2.0.3
Build Date: Mon May 02 2022 15:46:20 GMT-0700 (Pacific Daylight Time)
Revision: 663f42ad2ed1a746a548533c6811ffc25ba08cc4
Branch: release/2.0.3

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

**Comment by shefalijoshi** [comment]
Verified Fixed
