### ISSUE TITLE
Time strip views should only allow time-based plots, imagery and plans

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#5160]
Non time based plots, other object types and layouts are currently allowed in time strip views. These should not be allowed.

#### Steps to Reproduce
1. Try to add a display layout, condition set, bar graph etc to a time strip view
2. Notice that this is allowed

#### Environment
* Open MCT Version: 2.0.3
* Deployment Type: VIPER/testathon
* OS: Mac
* Browser: All

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

**Comment by shefalijoshi** [comment]
Testing instructions:
Adding plots, overlay plots, stacked plots, plans, imagery should work for timestrips.
All other objects should be disallowed.

**Comment by ozyx** [comment]
Verified -- Testathon 6/27/22

Was able to add Overlay Plot, Stacked Plot, Plan, and Example Imagery to a Timestrip.

**Comment by charlesh88** [comment]
Verified fixed Testathon 07-01-22.

**Comment by rukmini-bose** [comment]
Verified Testathon 7/1/22
