### ISSUE TITLE
[Plot] Add zoom sliders

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#517]
<p>Add zoom sliders to control zoom level of a plot, as shown on p 71 of UI docs attached to <a href="https://trunk.arc.nasa.gov/jira/browse/WTD-868" title="UI for setting plot bounds in a plot view" class="issue-link" data-issue-key="WTD-868"><del>WTD-868</del></a>, bullets 9 &amp; 10.</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1141
Originally created: Sun, 26 Apr 2015 11:09:37 -0700
Updated: Thu, 14 Jan 2016 16:32:02 -0800

**Comment by larkin** [comment]
@charlesh88 do we still desire this functionality?  I don't believe the plot needs every single bell and whistle, and we already support zoom in one way.
