### ISSUE TITLE
Operator Status Indicators

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#5193]
Implement a system to allow operators to report their operational status (eg. 'go', 'no go', etc.), and a specialist user (eg. a flight director) to set a poll question. This is for scenarios such as critical mission phases and activities where the flight director will query each operator (typically via a voice loop) for a go/no go status.

#### Operator Status Widget
![Screen Shot 2022-05-18 at 7 24 55 AM](https://user-images.githubusercontent.com/4215777/169065596-fa12ee22-c713-4600-a69c-e5625353828d.png)

#### Poll Question Widget
![Screen Shot 2022-05-18 at 7 25 12 AM](https://user-images.githubusercontent.com/4215777/169065718-9565419c-a04f-4e65-9b51-e66c74fe1c3b.png)

### Select design notes

* The design utilizes a new Notification widget in the Status bar area; this widget must be aware of the current user's position and role and only allow the correct users to see and interact with it.
* If the current user doesn't have sufficient permissions, they should not see the Notifier widget at all.
* Response options will be configurable per deployment in a configuration file.
* The number of responses should be controllable.
* Response colors should be settable as hex color values.
* Response names (Green, Amber, etc.) should be controllable.
* Response icons should be settable, and optional. These could simply be strings that map to our available glyph classes, like 'icon-check', 'icon-alert-triangle', etc.

Design details are available in Confluence

**Comment by akhenry** [comment]
## Testing Notes
Testing operator status requires at least three people testing at the same time - Two operators, and one Flight Director. These roles will need to be assigned in Yamcs first (@akhenry to do this).

### Setup needed
1. Assign one participant to the Flight Director role in Yamcs
2. Assign all other participants to an operator role in Yamcs

### If you're an operator
1. Verify that the the operator status indicator is available to you. This is what it looks like in our test environment -

2. Verify that the current poll question is shown in your operator status indicator. It should look like this -

3. Verify that your status is shown in the operator status indicator, and that the status field is not blank.
4. Verify that you can successfully change your status via the operator status indicator
5. Verify that the color and icon change appropriately when you change your status. Here are the icons and colors configured in our test environment -

6. Verify that the current poll question is shown in the operator status indicator
7. Verify that the poll question is updated in your indicator when the Flight Director changes it (you will need to coordinate with FD)


### If you're FD
1. Verify that the poll question indicator is available to you. In our test environment it looks like this -

3. Verify that you can change the poll question
4. Verify that the poll question is automatically updated in Operators' displays when you set a new poll question (you will need to coordinate with operators)
5. Verify that changing the poll question resets the status of all operators to "NO_STATUS". You will need to coordinate with operators.
6. Verify that the status counts are correct (you will need to coordinate with operators)

**Comment by davetsay** [comment]
seeing this console error. also not seeing the status indicator changing when I change it, although a notification says it was saved successfully.
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'subscribe')
    at k.getPollQuestion (openmct-yamcs.js?e792:1:22409)
    at async a.fetchCurrentPoll (OperatorStatus.vue?a4fd:114:1)
```
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'subscribe')
    at k.getStatusForRole (openmct-yamcs.js?e792:1:21807)
    at async StatusAPI.getStatusForRole (StatusAPI.js?901b:126:1)
    at async a.fetchMyStatus (OperatorStatus.vue?a4fd:130:1)
```

**Comment by charlesh88** [comment]
Testathon 07-08-22: CANNOT verify, functionality not available - roles not enabled or plugin not installed.
