### ISSUE TITLE
Enable filtering in Edit mode

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#521]
<p>When in edit mode:</p> <p>Allow users to browse the tree to find existing objects (current functionality)</p> <p>allow users to enter a string to be used to filter down the names of existing objects (dynamically if won't kill performance). Need to discuss if we will want to allow common search functions (like quotes around multiple words, boolean operators). Also need to discuss if the filtering returns a container whether or not the contents of that container which don't match the search string get shown for selection (I argue they optionally should).</p> <p>Need to discuss whether or not the search would go through other fields on the objects (like description). For example, some telemetry points are named rather obscurely, and the description if it is available, might more readily include the term the user is looking for. Perhaps this capability might be enabled by a user selection.</p> <p>Allow users to create new objects to be added. For example, when a user is editing a timeline, realises they haven't yet created the activity they want, so they can create a new one.</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-835
Originally created: Thu, 5 Feb 2015 14:43:28 -0800
Updated: Thu, 7 Jan 2016 13:18:31 -0800

**Comment by charlesh88** [comment]
Closing this user story as current search combined with New Edit Mode fulfills most of the ideas here.
