### ISSUE TITLE
[Linting] Fix casesensitive filename imports once and for all

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#5216]
#### Summary
We've lost a lot of manhours due to casesensitivity import bugs. In this ticket, let's rip off the bandaid and fix it once and for all with a new PR which

- [ ] Defines best practices for filename imports with Vue and JS imports
- [ ] Renames our existing files to match the best practice
- [ ] Adds a linter to our filenames to enforce all files match the case sensitive format of choice
- [ ] Add a linter for import statements

Light reading:
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/filename-case.md
https://v2.vuejs.org/v2/guide/single-file-components.html

**Comment by ozyx** [comment]
# Testing Instructions

- Change a *.vue file to not be in PascalCase.
- Run `npm lint`
- verify that the linter throws an error about it

**Comment by khalidadil** [comment]
Verified in Testathon on 10/05/2023
