### ISSUE TITLE
Remote clock shows empty plots

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#5221]
#### Summary
There is a race condition with the remote clock whereby on initial load of the application plots will show no historical data due to the historical request being issued with start and end times of `0`. This is because the historical requests are issued before the remote clock has got a time back from the server.

There are two potential solutions here:
1. The remote clock should issue a proper bounds update (not a "tick") when it eventually gets a time from the server. 
2. The telemetry API blocks all historical requests if the remote clock has not yet received a valid time from the server.

2 Feels more correct to me because we can't really issue historical requests until we know the time. Issuing requests with bad start and end times is at best wasteful, and at worst may result in errors from backend systems.

#### Steps to Reproduce
1. Configure the remote clock
2. Select the remote clock in the time conductor
3. Navigate to a display with plots
4. Refresh the browser
5. Observe that the plots show no historical data. 
6. Switching to local clock and then back to the remote clock will fix the issue as the remote clock now has a valid time to use.

#### Environment
* Open MCT Version: 2.0.3
* Deployment Type: STM test environment (talk to @akhenry for details)

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?

**Comment by akhenry** [comment]
## Testing Instructions
Follow the reproduction steps above and verify that plots are initially populated with data when you refresh using the remote clock.

**Comment by akhenry** [comment]
Not fixed. Refreshing on a plot with the remote clock does not show any historical data. Moreover the following error is observed in the console:
```
requestInterceptor.js?1480:38 Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'start')
    at Object.invoke (requestInterceptor.js?1480:38:1)
    at async TelemetryAPI.applyRequestInterceptors (TelemetryAPI.js?7b82:213:1)
    at async TelemetryAPI.request (TelemetryAPI.js?7b82:279:1)
```

**Comment by charlesh88** [comment]
Testathon 07-08-22: NOT FIXED, still seeing console error referenced by @akhenry above.

**Comment by akhenry** [comment]
Verified fixed after redeploying the latest code.
