### ISSUE TITLE
Fix lint warnings and configure build to fail on lint warning

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#5231]
#### Summary
Some code has slipped in that triggers lint warnings. Our build currently only fails on lint errors, not warnings. Let's fix the lint warnings and modify the build config to fail on warning.

The linter can be run from the command line using `npm run lint`.

To make eslint fail on warning use [the `--max-warnings` flag documented here](https://eslint.org/docs/user-guide/command-line-interface).

These are the warnings it's showing right now:
```
src/api/objects/MutableDomainObject.js
  96:89  warning  Consider using the native optional chaining to get nested values and nullish coalescing operator for fallback values  you-dont-need-lodash-underscore/get

src/plugins/imagery/components/ImageControls.vue
  110:9  warning  Prop 'imageUrl' requires default value to be set  vue/require-default-prop

src/plugins/imagery/components/ImageryView.vue
  58:14  warning  Expected 1 space after '{{', but not found   vue/mustache-interpolation-spacing
  58:34  warning  Expected 1 space before '}}', but not found  vue/mustache-interpolation-spacing

src/ui/toolbar/Toolbar.vue
  184:20  warning  Consider using the native optional chaining to get nested values and nullish coalescing operator for fallback values  you-dont-need-lodash-underscore/get

✖ 5 problems (0 errors, 5 warnings)
  0 errors and 2 warnings potentially fixable with the `--fix` option.
```

**Comment by unlikelyzero** [comment]
@akhenry @ozyx this may cause complications with our e2e tests

**Comment by ozyx** [comment]
> @akhenry @ozyx this may cause complications with our e2e tests

Are you referring to the `playwright/no-wait-for-timeout` rule? I notice that the percy, imagery, and log plot tests rely on explicit waits in order to run correctly. We could [disable this rule for specific files or folders](https://eslint.org/docs/user-guide/configuring/configuration-files#configuration-based-on-glob-patterns) if we want.

**Comment by unlikelyzero** [comment]
### Testing Notes
Verify that no warnings are thrown when running `npm run lint`
Implement make a local codechange that would violate a rule in the e2e suite and vue files. Run `npm run lint` and verify that they're thrown

**Comment by alizenguyen** [comment]
Verified Testathon 06/15/2022
