### ISSUE TITLE
[Performance] Inspector Repaints in Local Clock and Remote Clock Time

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#5247]
#### Summary
When analyzing the performance of a Display Layout, we noticed that the Inspector was being re-painted unnecessarily. We should avoid modifying or updating the Inspector unnecessarily to avoid any performance penalties associated with that repaint.

#### Expected vs Current Behavior
Expected: In Local Clock, Inspector not update or repaint unless the user interacted with an element in the object's Main view.
Current: In Local Clock, Inspector updates and repaints even on a folder with no changes.

#### Steps to Reproduce
1. Open DevTools, Enable Secondary DevTools. Enable Rendering Tab. Enable Paint Flashing.
2. Set Clock to Local Clock
3. Navigate to any object including the Root folder
Note: Inspector repaints

#### Environment
* Open MCT Version: 2.0.3
* Deployment Type: local
* OS: macOS
* Browser: Chrome 101

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?

#### Additional Information

https://user-images.githubusercontent.com/12446869/170097309-772dee09-5b64-4a52-a5d3-5a71ee642721.mov

**Comment by akhenry** [comment]
Is there some way to define a regression test that will prevent this regressing again once fixed?

**Comment by unlikelyzero** [comment]
@akhenry yes, it _should_ be possible with ```RecalcStyleCount Total number of page style recalculations.```

**Comment by shefalijoshi** [comment]
The repaints are being caused by CSS, specifically this `overflow-x` property
https://github.com/nasa/openmct/blob/release/2.0.5/src/ui/layout/layout.scss#L73

@charlesh88 Is there something we can do about this?

**Comment by charlesh88** [comment]
Looking at this now.

**Comment by charlesh88** [comment]
WIP in branch `fix-repaint-5247`. Deferring this behind other issues that are more pressing for the Build 6 "fix" sprint.

**Comment by charlesh88** [comment]
@michaelrogers and I talked today about this. 
- After changes in @charlesh88 fix branch the fact that only the Inspector contents are being repainted makes us both suspicious that this problem may be due to some JS process that's reacting to other onscreen elements and re-rendering content as a result. @michaelrogers to look into this possibility.
- @charlesh88 to look further into online forums re. Flex / overflow and relationships to repainting.

**Comment by akhenry** [comment]
Verified Fixed.
