### ISSUE TITLE
Plan objects are large - look into making loading efficient

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#5249]
#### Summary
Plan objects are now large (6Megs each). We should look into optimizing requests to get only the data we need at a given time
For example:
Only request name/'state' metadata until the object is actually viewed.
Only request the parts of the object that Open MCT needs when the object is viewed.

#### Expected vs Current Behavior
Plan objects are large and are causing Open MCT loading to be slow.

#### Steps to Reproduce
1. Load open MCT with multiple plans in the couch db database.

#### Environment

* Open MCT Version: 2.0.3
* Deployment Type: banner - all
* OS: Mac
* Browser: All

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [ ] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?

**Comment by shefalijoshi** [comment]
While the Plan objects in CouchDB are large, the part of the plans that are pulled into Open MCT are only 165KB ish.

**Comment by akhenry** [comment]
Fair enough, close for now. I have confirmed in our test environment that the plan objects are small, our biggest downloads right now are Open MCT itself, and the telemetry dictionary.
