### ISSUE TITLE
[Layout] Would like to be able to create panel from Layout

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#525]
<p>Mark observed during testathon Feb 26, 2015 - would like to be able to create new plots while editing a Layout (without going back to Browse, creating a Panel, etc)</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-948
Originally created: Thu, 26 Feb 2015 13:52:05 -0800
Updated: Thu, 7 Jan 2016 17:24:06 -0800

**Comment by charlesh88** [comment]
This will be covered by sub-object editing tasks, and starting with #1101

**Comment by charlesh88** [comment]
Covered by #581, closing.
