### ISSUE TITLE
[Example Imagery]: Historical images don't populate for certain image load delay values

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#5265]
#### Summary

Historical images only populate for certain image load delay values (either == 20000, or any value < 5000, even negative!).

#### Expected vs Current Behavior

* Expected:
  * The historical images should populate for any load delay value.
* Current: 
  * Historical images only populate for image load delay values == 20000, or < 5000.

#### Steps to Reproduce

1. Create an Example Imagery object and set the load delay value to any number > 5000 and < 20000, or > 20000
2. See that the historical images never populate

#### Environment

* Open MCT Version: `2.0.4-SNAPSHOT`
* Deployment Type:  npm dev
##### System:
 - OS: macOS 11.6.6
 - CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
 - Memory: 1.71 GB / 16.00 GB
 - Shell: 5.8 - /bin/zsh
##### Binaries:
 - Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
 - npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
##### Browsers:
 - Chrome: 101.0.4951.64
 - Edge: 101.0.1210.32
 - Firefox: 78.11.0
 - Safari: 15.5
##### npmPackages:
 - @babel/eslint-parser: 7.16.3 => 7.16.3 
 - @braintree/sanitize-url: 6.0.0 => 6.0.0 
 - @percy/cli: 1.2.1 => 1.2.1 
 - @percy/playwright: 1.0.4 => 1.0.4 
 - @playwright/test: 1.21.1 => 1.21.1 
 - @types/eventemitter3: ^1.0.0 => 1.2.0 
 - @types/jasmine: ^4.0.1 => 4.0.3 
 - @types/karma: ^6.3.2 => 6.3.3 
 - @types/lodash: ^4.14.178 => 4.14.182 
 - @types/mocha: ^9.1.0 => 9.1.1 
 - babel-loader: 8.2.3 => 8.2.3 
 - babel-plugin-istanbul: 6.1.1 => 6.1.1 
 - comma-separated-values: 3.6.4 => 3.6.4 
 - copy-webpack-plugin: 11.0.0 => 11.0.0 
 - cross-env: 7.0.3 => 7.0.3 
 - css-loader: 4.0.0 => 4.0.0 
 - d3-axis: 3.0.0 => 3.0.0 
 - d3-scale: 3.3.0 => 3.3.0 
 - d3-selection: 3.0.0 => 3.0.0 
 - eslint: 8.13.0 => 8.13.0 
 - eslint-plugin-compat: 4.0.2 => 4.0.2 
 - eslint-plugin-playwright: 0.9.0 => 0.9.0 
 - eslint-plugin-vue: 8.5.0 => 8.5.0 
 - eslint-plugin-you-dont-need-lodash-underscore: 6.12.0 => 6.12.0 
 - eventemitter3: 1.2.0 => 1.2.0 
 - exports-loader: 0.7.0 => 0.7.0 
 - express: 4.13.1 => 4.13.1 
 - file-saver: 2.0.5 => 2.0.5 
 - git-rev-sync: 3.0.2 => 3.0.2 
 - html2canvas: 1.4.1 => 1.4.1 
 - imports-loader: 0.8.0 => 0.8.0 
 - jasmine-core: 4.1.1 => 4.1.1 
 - jsdoc: 3.5.5 => 3.5.5 
 - karma: 6.3.20 => 6.3.20 
 - karma-chrome-launcher: 3.1.1 => 3.1.1 
 - karma-cli: 2.0.0 => 2.0.0 
 - karma-coverage: 2.2.0 => 2.2.0 
 - karma-coverage-istanbul-reporter: 3.0.3 => 3.0.3 
 - karma-firefox-launcher: 2.1.2 => 2.1.2 
 - karma-jasmine: 4.0.1 => 4.0.1 
 - karma-junit-reporter: 2.0.1 => 2.0.1 
 - karma-sourcemap-loader: 0.3.8 => 0.3.8 
 - karma-spec-reporter: 0.0.34 => 0.0.34 
 - karma-webpack: 5.0.0 => 5.0.0 
 - lighthouse: 9.6.1 => 9.6.1 
 - location-bar: 3.0.1 => 3.0.1 
 - lodash: 4.17.21 => 4.17.21 
 - mini-css-extract-plugin: 2.6.0 => 2.6.0 
 - moment: 2.29.3 => 2.29.3 
 - moment-duration-format: 2.3.2 => 2.3.2 
 - moment-timezone: 0.5.34 => 0.5.34 
 - node-bourbon: 4.2.3 => 4.2.3 
 - painterro: 1.2.56 => 1.2.56 
 - plotly.js-basic-dist: 2.12.0 => 2.12.0 
 - plotly.js-gl2d-dist: 2.12.0 => 2.12.0 
 - printj: 1.3.1 => 1.3.1 
 - request: 2.88.2 => 2.88.2 
 - resolve-url-loader: 5.0.0 => 5.0.0 
 - sass: 1.49.9 => 1.49.9 
 - sass-loader: 12.6.0 => 12.6.0 
 - sinon: 14.0.0 => 14.0.0 
 - style-loader: ^1.0.1 => 1.3.0 
 - uuid: 8.3.2 => 8.3.2 
 - vue: 2.6.14 => 2.6.14 
 - vue-eslint-parser: 8.3.0 => 8.3.0 
 - vue-loader: 15.9.8 => 15.9.8 
 - vue-template-compiler: 2.6.14 => 2.6.14 
 - webpack: 5.68.0 => 5.68.0 
 - webpack-cli: 4.9.2 => 4.9.2 
 - webpack-dev-middleware: 5.3.3 => 5.3.3 
 - webpack-hot-middleware: 2.25.1 => 2.25.1 
 - webpack-merge: 5.8.0 => 5.8.0 
 - zepto: 1.2.0 => 1.2.0 

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by unlikelyzero** [comment]
@shefalijoshi this was merged onto master and not 2.0.5, should we be tracking this against 2.1.0 without the need to backmerge onto master?

**Comment by unlikelyzero** [comment]
Closing without the intent to backmerge onto release/2.0.5. This should only be tested on release/2.1.0

**Comment by charlesh88** [comment]
Testathon 07-11-22 verified fixed.
