### ISSUE TITLE
[Fixed Position] Font cut off at bottom

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#528]
<p>Under default grid size, bottom few pixels of text for a telemetry element is cut off in the Fixed Position view.</p> <p>This could be addressed either by changing font size or default grid size.</p> <p>Observed during testathon, Feb 26 2015</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-946
Originally created: Thu, 26 Feb 2015 13:25:19 -0800
Updated: Thu, 7 Jan 2016 17:24:45 -0800

**Comment by charlesh88** [comment]
We should definitely change the default size, not the font size. The real problem isn't the setting IMO, it's the behavior: we define default sizes in terms of grid units, but instead should be using pixels. This becomes a problem when the layout grid is more fine-grained - newly added objects appear very small, and fonts get cut off.

I've filed #1383 to cover a fix for this.

**Comment by charlesh88** [comment]
Fixed with #1703
