### ISSUE TITLE
Demo : Missing curiosity position image

### ISSUE THREAD

**Issue by Ninjeneer** [nasa/openmct#5283]
#### Summary

In the **Mars Weather Display Layout** the position Curiosity is not shown, because image is unreachable

#### Expected vs Current Behavior

The image should appear

#### Steps to Reproduce

1. https://openmct-demo.herokuapp.com/#/browse/demo:root/demo:1?view=layout&tc.mode=fixed&tc.timeSystem=utc&tc.startBound=1344211200000&tc.endBound=1654249297751

#### Environment

Deployed demo

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information

<img width="1090" alt="image" src="https://user-images.githubusercontent.com/30394488/171832756-5c5893de-024c-4da5-b685-8c1312091b91.png">

**Comment by unlikelyzero** [comment]
@Ninjeneer we will be removing this demo soon. Please follow https://github.com/nasa/openmct/issues/5594 for info
