### ISSUE TITLE
UI Components should be exposed

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#5288]
## Description
Exposing UI components would allow developers to re-use components in their plugins.

## Testing Instructions (VIPER testathon environment)
1. Navigate to Static Objects -> Map Tool
2. In the Map Tool, click the layers tool, and make the Instrument data -> H20 Band Depth layer visible
3. Click on the colored portion of the layer (may have to repeat to find data)
4. In Inspector, after data ranges load, select a data range to display plot data for that timeframe (the first data range is selected by default but may need to select a new range to see data)
5. If the plot view loads, that is using the exposed ObjectView

**Comment by shefalijoshi** [comment]
Browser crashed when I finally selected a point in the band depth with data in it. :(

**Comment by unlikelyzero** [comment]
Given the nature of the failure. We should re-open and re-investigate based on @khalidadil 's finding

**Comment by khalidadil** [comment]
@shefalijoshi I'm able to reproduce this on banner tesathon in Chrome but not on dev (even when dev is running the latest code). I'm not sure exactly what the issue is yet.
