### ISSUE TITLE
Markup/styling for Overwrite/Discard dialog

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#530]
<p>Modify markup &amp; styling for the Overwrite/Discard dialog which is shown when external changes have been detected when a user tries to save changes to an object or objects. </p> <p>Dialog's template is platform/persistence/queue/res/templates/persistence-failure-dialog.html and currently contains all information intended to occupy that dialog, so I believe we will just need changes to markup/styling</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1063
Originally created: Tue, 31 Mar 2015 12:49:58 -0700
Updated: Thu, 7 Jan 2016 17:21:25 -0800

**Comment by larkin** [comment]
related to #373
