### ISSUE TITLE
[Fault Management] Create example Fault Telemetry Provider for Ease of Use and Testing

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#5302]
**Is your feature request related to a problem? Please describe.**
It can be difficult to test using local storage and you can't really test all features.

**Describe the solution you'd like**
Create a fault telemetry provider (historical/realtime) that doesn't rely on localStorage.

**Describe alternatives you've considered**
Currently local storage is used.

**Additional context**
Nada.

**Comment by jvigliotta** [comment]
## Testing ##
- install `openmct.install(openmct.plugins.example.ExampleFaultSource());`
- verify you have test fault data and can acknowledge and shelve faults, search, sort, etc

**Comment by michaelrogers** [comment]
Enhancement verified locally in `release/2.0.8` branch. Fault management features and test data are accessible after installing the example plugin.
