### ISSUE TITLE
Grid icons are wrong

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#5303]
#### Summary
Grid icon artwork is wrong for many object types.
<img width="1001" alt="Screen Shot 2022-06-08 at 10 48 37 AM" src="https://user-images.githubusercontent.com/1056412/172686952-f88a9b57-7f39-4d47-9d6e-fd5c7f3ef8ec.png">

#### Steps to Reproduce

1. Create a number of different object types, particularly Display Layout, Notebook, Example Imagery, Web Page, Gauge.
2. Note that the objects will have the correct icons in the tree view.
3. View the folder enclosing the objects in the main view in Grid view, and note that the icon artwork is wrong.

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by charlesh88** [comment]
### Testing Notes
Follow Steps to Reproduce above and verify that step 3 is no longer true.

![image](https://user-images.githubusercontent.com/1056412/172729740-44aa51bf-0e39-488f-ad04-d071922e2ada.png)

**Comment by khalidadil** [comment]
I'm noticing that overlay plots have question marks for the icons - seems like a bug.

**Comment by akhenry** [comment]
Reopening this for merge into release/2.0.5 branch

**Comment by unlikelyzero** [comment]
Please verify this issue "while you're in there" https://github.com/nasa/openmct/issues/3489

**Comment by khalidadil** [comment]
Testathon 06-23-22. Telemetry tables now seem to be missing the icon in grid view.

**Comment by shefalijoshi** [comment]
Not fixed - there are still missing icons for telemetry tables in grid view

**Comment by charlesh88** [comment]
### Updated Testing Notes
The Telemetry Tables icon regression has been fixed for #5640 - see testing notes there.

**Comment by charlesh88** [comment]
Testathon 10-04-22 verified fixed.

**Comment by rukmini-bose** [comment]
Testathon Verified 10/4. All grid icons seem to be correct.

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon 10/4
