### ISSUE TITLE
[Unit Tests] Get test:watch working again

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#5306]
#### Summary
At some point, the test:watch npm script was broken. Let's get it working again!

**Comment by ozyx** [comment]
I was looking into this a little bit earlier today, and I noticed that running `test:watch` causes karma to run the tests over and over again in a loop (it keeps detecting file changes). Is this the broken state of which you speak?

Running it in verbose mode, karma says it keeps detecting file changes after each test run has completed. So I wonder if some files are being watched that shouldn't be?

**Comment by unlikelyzero** [comment]
@ozyx this doesn't have any priority right now, but that's the behavior that I just saw. I haven't used it before so it's possible that it hasn't worked for years

**Comment by unlikelyzero** [comment]
### Testing Notes
Run test:watch and verify that the tests are retriggered ONLY when modify the testcode or the application code
```npm run test:watch```

**Comment by unlikelyzero** [comment]
Not fixed: i did a npm run test:watch without making any changes

**Comment by jvigliotta** [comment]
Not Fixed Locally: Testathon: 7/8/22

This looks to be running in a loop...
