### ISSUE TITLE
[Display Layout] Fix non functioning render test

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#5310]
#### Summary

Render test for display was checking for errors, not that the display rendered, which it didin't.

#### Expected vs Current Behavior

To check that the display rendered.

#### Steps to Reproduce

1. Run test coverage

**Comment by jvigliotta** [comment]
## Testing
- run `npm run test` verify no display layout test errors

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 06/15/2022
