### ISSUE TITLE
Confused about when it's possible to drag and drop

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#532]
<p>Created a new timeline.<br/> Attempted to drag and drop an activity into the new timeline. Didn't work, but also didn't give a warning or error message (or a forbidding icon or other indication).<br/> Entered edit mode for the timeline.<br/> Again attempted to drag and drop an activity into the timeline. Dragged the activity to the middle of the left upper box. No warning or forbidding icon, but again didn't work.<br/> Through experimentation, discovered that if I drag and drop the activity into the top bar (under the title), it works. </p> <p>Would be nice if the icon changed to something to show me where/when it's ok to drop and where it's not. Also, why is it not possible to drag into the box?</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1096
Originally created: Thu, 9 Apr 2015 15:27:23 -0700
Updated: Thu, 7 Jan 2016 17:19:54 -0800

**Comment by larkin** [comment]
merging with https://github.com/nasa/openmct/issues/1718.
