### ISSUE TITLE
VIPER build info missing

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#5322]
#### Summary
Title says it all

#### Expected vs Current Behavior
Title says it all

#### Steps to Reproduce
1. Click on the about page (Open MCT icon)
2. look for build info
3.
4.

#### Environment

* Open MCT Version: VIPER
* Deployment Type: 59880955a2395c195a4a47cd46da2334232989ac
* OS:
* Browser:

#### Impact Check List

- [] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [] Is there a workaround available?
- [] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [x] Does this block the execution of e2e tests?
- [] Does this have an impact on Performance?

**Comment by ozyx** [comment]
Fix is on the VIPER side, PR has been opened there

**Comment by michaelrogers** [comment]
![Screen Shot 2022-06-23 at 5 29 07 PM](https://user-images.githubusercontent.com/7417521/175425602-4456ba85-5233-4f93-8e32-4964741ae59f.png)
Fix verified in testathon 06-23-22.
