### ISSUE TITLE
Gauge is not displayed correctly on Firefox

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#5323]
#### Summary
Creating a Gauge object in Firefox does not display the radial view correctly.

#### Expected vs Current Behavior
The Gauge should appear as it does in Chrome.

#### Steps to Reproduce
1. Create a Gauge object
2. View it in Firefox
3. Expect the Gauge radial to display 

#### Environment
* Open MCT Version: 2.0.5
* Deployment Type: Viper testathon
* OS: All
* Browser: Firefox

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/5247066/172955614-05adfb45-e2b0-4b4d-ae4e-e0622d3e11e1.png">

**Comment by charlesh88** [comment]
The core issue is that Firefox does not allow <clipPath> to be applied to container elements in SVGs. The solution is to use <mask> instead. WIP in https://codepen.io/charlesh88/pen/bGLQbpP?editors=1100

**Comment by charlesh88** [comment]
### Testing Notes
![Screen Shot 2022-06-24 at 11 00 26 AM](https://user-images.githubusercontent.com/1056412/175646939-b4683d29-8e78-49b4-9851-6e9efc4d75b7.png)

[Gauges Flexible Layout for 5323 and 5325.json.zip](https://github.com/nasa/openmct/files/8979994/Gauges.Flexible.Layout.for.5323.and.5325.json.zip)

1. Use "Import from JSON" to pull in the attached Flexible Layout, gauges and generators.
1. View the layout in Chrome: verify that all gauges look similar to the screenshot provided above.
1. View the layout in Firefox: verify that all gauges look similar to the screenshot provided above.
1. Resize the browser window and/or the Open MCT panes to change the size of the Flexible Layout area - verify that the gauges dynamically resize and display in an acceptable fashion.
1. Edit properties on the various gauges, disabling and enabling the three different "Display *" settings. Verify that the gauge hides or shows elements as expected.
1. Verify that when a data source value is below or above the set range min and max values that the "out of range" indicator (yellow arrows in screen cap above) is displayed and hovering over the gauge displays a tooltip: "Value is currently out of range and cannot be graphically displayed".

**Comment by unlikelyzero** [comment]
Ready for retest

**Comment by davetsay** [comment]
verified
