### ISSUE TITLE
[Imagery Layers] NIRVSSOMCT-271 Placeholder

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#5324]
Placeholder for NIRVSSOMCT-271

Using Example Imagery or an imagery endpoint, verify the following:

A layers menu button with dropdown appears. 

Checking and unchecking layers hides layers as expected.

**Comment by charlesh88** [comment]
Verified NOT fixed Testathon 06-15-22: example imagery is not displaying layer art properly (source URLs were 404ing from /testathon). 

The dropdown palette layout is also broken:
<img width="236" alt="image" src="https://user-images.githubusercontent.com/1056412/173942470-799dac87-c575-49e7-b6ef-f174c06ee3b0.png">

<img width="234" alt="image" src="https://user-images.githubusercontent.com/1056412/173942424-98398dd0-502c-4d7f-b757-88de6b2ddef3.png">

**Comment by unlikelyzero** [comment]
We will need to address this feature as a new, untested feature in 2.1.0

**Comment by akhenry** [comment]
This is because the example images are not being copied into the deployment directory. The issue is, they _shouldn't_ be deployed into production environments, and we certainly should not have any configuration in a production environment that copies them into the deployment directory.

One option here might be to host the example overlays from our public webserver (github pages) so they're accessible from anywhere with no deployment-specific configuration.

**Comment by wbnns** [comment]
> One option here might be to host the example overlays from our public webserver (github pages) so they're accessible from anywhere with no deployment-specific configuration.

If helpful, you could also/alternatively set up an `openmct-assets` repository and direct link to the resources there, and utilize similarly to as if it were like an S3 bucket.

**Comment by akhenry** [comment]
@wbnns That's a great, suggestion, thank you!

**Comment by akhenry** [comment]
## Testing Instructions
**This can only be verified locally.**
1. Navigate to an example imagery telemetry point
2. Verify that a layers menu button with dropdown appears.
3. Verify that checking and unchecking layers hides layers as expected.

**Comment by akhenry** [comment]
VIPERRQSTS-203 describes a new "grid overlay" specifically for the viper-openmct project.

**Comment by shefalijoshi** [comment]
Verified fixed locally.
