### ISSUE TITLE
Gauges don't pay attention to the "Display units" property setting

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#5325]
#### Summary
Gauge properties "Display units" setting is not having any affect, but should.

![image](https://user-images.githubusercontent.com/1056412/172955499-5cef6124-7b95-4e1a-bdfd-80c8bd44227a.png)

#### Expected vs Current Behavior
Setting "Display units" to disabled should suppress the display of units.

#### Steps to Reproduce

1. Edit Properties for a Gauge with a telemetry source that has units, set "Display units" to disabled.
2. Save, nav away and back, then observe: units should be hidden, but are not.

#### Environment

* Open MCT Version:  release/2.0.5
* Deployment Type:  /testathon
* OS: Macos
* Browser: Chrome

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by charlesh88** [comment]
### Testing Notes
See same in https://github.com/nasa/openmct/issues/5323

**Comment by charlesh88** [comment]
Verified NOT fixed Testathon 07-01-22: dial gauge specifically is still ignoring the "show units" setting.

**Comment by unlikelyzero** [comment]
@shefalijoshi @akhenry @charlesh88 we should move this to build 7 and ask for a regression test

**Comment by charlesh88** [comment]
### Testing Notes for Dial Gauge "Show units" verification
1. Edit Gauge properties to disable "Show units" and verify that units are not displayed in the Dial Gauge:
<img width="232" alt="Screen Shot 2022-07-08 at 12 00 21 PM" src="https://user-images.githubusercontent.com/1056412/178065016-89d4d66b-8876-48a6-8412-b59f5a21c400.png">

**Comment by rukmini-bose** [comment]
Verified Testathon 7/11/2022

**Comment by charlesh88** [comment]
Testathon 07-10-22 verified fixed.
