### ISSUE TITLE
Image View selected bugs

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#5327]
#### Summary
Imagery view has some regressions.
* No image has a visual selected context in the thumbnail view
When expanding the timerange by modifying the start date the thumbnail strip seems to be at some arbitrary time, and definitely not at the latest image
* Resizing the pane does make the auto scroll kick in

#### Expected vs Current Behavior
@charlesh88 

#### Steps to Reproduce
1. go to an image producing telemetry endpoint
2. see that nothing is indicated as the selected image
3. expand your start time input (in either local or fixed mode)
4. observe the slider is somewhere in the middle of the timerange

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by unlikelyzero** [comment]
In progress. Not ready for testathon 06/23

**Comment by michaelrogers** [comment]
###How To Test


Active state for thumbnail
* Navigate to image object
* Observe that an active blue highlight now exists in local clock and fixed clock modes
* Observe that a hover event still exists 
* Observe that selecting another thumbnail makes the highlight disappear

* Scrolling improvements
* Navigate to image object
* Select `Fixed Time` 
* Expand the TimeConductor start range
* Observe that the range expands and the focused image is scrolled to

**Comment by unlikelyzero** [comment]
Note: This may not be deployed in time for testathon

**Comment by unlikelyzero** [comment]
Ready for testathon

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon 8/4/22
