### ISSUE TITLE
[Plot] Change range axis string format

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#533]
<p>Range axis (y axis) label currently reads "</p> {TYPE} <p>-</p> {UNITS} <p>", e.g. DN-DEGC.</p> <p>Now that orientation of label is different and spaces render correctly, something like "DN (DEGC)" would be more readable.</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-356
Originally created: Mon, 8 Sep 2014 11:56:53 -0700
Updated: Thu, 14 Jan 2016 16:34:24 -0800

**Comment by charlesh88** [comment]
Think this has been fixed.
