### ISSUE TITLE
Review/revise communication of toolbar state in Edit mode

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#534]
<p>Toolbar in edit mode is currently conveyed by way of EditToolbarRepresenter, which looks for a "toolbar" attribute on mct-representation instance and, when present, publishes toolbar structure/state to the parent scope under the variable name used for the toolbar attribute.</p> <p>This is error-prone - introducing a controller at the wrong place in the scope hierarchy can cause the toolbar state to be published to the wrong scope, which has resulted in <a href="https://trunk.arc.nasa.gov/jira/browse/WTD-1020" title="Toolbar not visible in Timelines and Fixed Position view" class="issue-link" data-issue-key="WTD-1020"><del>WTD-1020</del></a>. Toolbar state should be communicated in a manner which does not exhibit this behavior.</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1026
Originally created: Fri, 13 Mar 2015 11:44:49 -0700
Updated: Thu, 14 Jan 2016 16:29:51 -0800

**Comment by charlesh88** [comment]
Is this still a problem?

**Comment by larkin** [comment]
Still a confusion point closing as wontfix as this is a refactor of code that already works.

Future work is related to https://github.com/nasa/openmct/issues/1126.
