### ISSUE TITLE
[Won't Fix] Firefox versions less than 90 will not load Open MCT

### ISSUE THREAD

**Issue by khalidadil** [nasa/openmct#5345]
#### Summary
Note: This issue will not be fixed. Our published browser support includes Firefox ESR which has been >91 since 10/28/21.

When I try to go to the testathon server using the installed version of Firefox, I'm getting the following errors:

```
Uncaught SyntaxError: private fields are not currently supported
    5244 openmct.js:1
    __webpack_require__ openmct.js:1
    <anonymous> api.js:32
    2641 openmct.js:1
    __webpack_require__ openmct.js:1
    <anonymous> MCT.js:25
    6250 openmct.js:1
    __webpack_require__ openmct.js:1
    <anonymous> openmct.js:33
    3043 openmct.js:1
    __webpack_require__ openmct.js:1
    <anonymous> openmct.js:1
    <anonymous> openmct.js:1
    <anonymous> openmct.js:1
    <anonymous> openmct.js:1
[openmct.js:543:17](/testathon/node_modules/openmct/dist/openmct.js)
    5244 openmct.js:1
    __webpack_require__ openmct.js:1
    <anonymous> api.js:32
    2641 openmct.js:1
    __webpack_require__ openmct.js:1
    <anonymous> MCT.js:25
    6250 openmct.js:1
    __webpack_require__ openmct.js:1
    <anonymous> openmct.js:33
    3043 openmct.js:1
    __webpack_require__ openmct.js:1
    <anonymous> openmct.js:1
    <anonymous> openmct.js:1
    <anonymous> openmct.js:1
    <anonymous> openmct.js:1
```

#### Environment
* Deployment Type: Viper Testathon
* OS: Mac OS 11.6.6
* Browser: Firefox 78.12.0esr

#### Impact Check List
- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [X] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by unlikelyzero** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields#browser_compatibility

**Comment by akhenry** [comment]
@unlikelyzero shall we close this? Since we won't fix it?
