### ISSUE TITLE
[Condition Widget] Creating a Condition Widget causes console errors

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#5349]
#### Summary
When creating a Condition Widget, a console error is thrown.

#### Steps to Reproduce
1. Clean install
2. Create Condition Widget
3. Click OK
Note: Console errors thrown 

#### Environment
* Open MCT Version: 2.0.5
* Deployment Type: npm
* OS: MacOS

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [x] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information
[trace (2).zip](https://github.com/nasa/openmct/files/8903697/trace.2.zip)

**Comment by michaelrogers** [comment]
Fix verified in testathon 06/23/2022. No console errors were thrown after creating a condition widget.

**Comment by ozyx** [comment]
Verified Testathon 6/27/22
