### ISSUE TITLE
[Views] Add view configuration button

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#535]
<p>Add view configuration button as shown on p. 49 of UI documents for fixed position view (see <a href="https://trunk.arc.nasa.gov/jira/browse/WTD-615" title="Implement fixed position view" class="issue-link" data-issue-key="WTD-615"><del>WTD-615</del></a>)</p> <p>This should be populated by and interact with the view's configuration in a similar manner to the way an object's properties can be edited in the Edit Properties menu (the structure of this form should be defined in the view's definition, similar to the way the structure for Edit Properties is defined in the type's definition.)</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-875
Originally created: Fri, 13 Feb 2015 16:12:26 -0800
Updated: Thu, 14 Jan 2016 16:43:37 -0800

**Comment by VWoeltjen** [comment]
@charlesh88 - is this issue obsolete now that we're handling configuration in the Inspector?

**Comment by charlesh88** [comment]
Closing.
