### ISSUE TITLE
[Gauge] On create, changing `Value ranges and limits` will override any form changes above

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#5356]
#### Summary
When creating a gauge, if the `Value ranges and limits` configuration is modified, all other edits will be lost on finalizing creation.

#### Expected vs Current Behavior
All changes to a new gauge form should be saved.

#### Steps to Reproduce
1. Select Gauge from the create menu
2. Change the Gauge type property (or any other property other than `Value ranges and limits` property)
3. toggle the `Value ranges and limits` property and make change to that
4. Click OK to save the Gauge
5. Click the 3 dot menu and select edit properties
6. Everything is not OK. Only the `Value ranges and limits` property is saved and all other properties are not

#### Environment
* Open MCT Version: release/2.0.5
* Deployment Type: testathon
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by khalidadil** [comment]
I'm seeing errors on gauges if any properties are toggled

**Comment by rukmini-bose** [comment]
Unverified Testathon 10/27/2022 
(1) Editing any properties breaks gauges 
(2) I've noticed this case happen sporadically and I'm not sure why: editing the property of the gauge after saving will sometimes give you the properties of the previous object you had visited in the tree. (For example, I had navigated to an LAD Table after creating a gauge, then navigated back to it. When I clicked "Edit Properties" under the 3-dot menu, I was prompted to change the properties of the LAD Table.

**Comment by ozyx** [comment]
Gauges seem completely broken. -- Testathon 10/27/22

Following the testing instructions, a blank gauge is generated.

Navigating away and back, these console errors are generated:

![image](https://user-images.githubusercontent.com/9259993/198406236-774e95fb-cc97-4293-aa84-3bfdb13bdfdb.png)

**Comment by unlikelyzero** [comment]
Re-evaluating as `blocker`

**Comment by ozyx** [comment]
OK, so this has kind of evolved past this original issue since we updated `EditPropertiesAction` in 2.1.2.

Gauge is unique from other domain objects as its configuration, which is usually a flat map of keys and values, is encompassed in a parent object `gaugeController`:

```js
gaugeController: {
    gaugeType: 'dial-filled',
    isDisplayMinMax: true,
    isDisplayCurVal: true,
    isDisplayUnits: true,
    isUseTelemetryLimits: false,
    limitLow: -0.9,
    limitHigh: 0.9,
    max: maxValue,
    min: minValue,
    precision: 2
}
```

Due to this, a change to a single property causes all other properties to become undefined, because we shallow merge properties in `EditPropertiesAction`:

```js
if (!(Array.isArray(existingValue)) && (typeof existingValue === 'object')) {
    value = {
        ...existingValue,
        ...value
    };
}

this.openmct.objects.mutate(this.domainObject, key, value);
```

Quick fix is to do a deep merge on both CreateAction and EditPropertiesAction. But we should consider refactoring Gauge in the future to have a configuration consistent with all other domain objects (flat map)

**Comment by khalidadil** [comment]
I'm seeing an issue where I created a gauge (worked correctly), but on editing the gauge properties I'm having issues saving and seeing the changes.

**Comment by ozyx** [comment]
> I'm seeing an issue where I created a gauge (worked correctly), but on editing the gauge properties I'm having issues saving and seeing the changes. Verified Fixed in Testathon on 11/17/22

Separate issue filed here:
https://github.com/nasa/openmct/issues/5138
