### ISSUE TITLE
[Composite Services] Rename aggregators

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#536]
<p>Problem: When developers are trying to understand telemetryService (or any other composite service) they're going to go looking for a TelemetryService.js or similar. However, this doesn't exist: Composite services are not defined by any given class.</p> <p>The most central place where services are defined are aggregators, so it would make to define these interfaces in the same script as the aggregators. Difficulty here is that aggregators are not easily discoverable unless the reader is (a) familiar with composite services, and (b) knows that the dependency they're using is a composite service. This cannot always be guaranteed.</p> <p>Most general goal here: If an injectable dependency is named "blahBlah" I should expect to find a "BlahBlah" somewhere defining it. (So, maybe the solution here is actually to change the naming convention used for composite services, e.g. don't call it a telemetry service.)</p> <p>A specific solution which Pete proposed was to rename TelemetryAggregator (et al) to TelemetryService. </p> <p>Corollary to this, think we should rename "utility" services such that they do not have the same suffix as composite services, for clarity. </p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1418
Originally created: Tue, 30 Jun 2015 11:43:39 -0700
Updated: Thu, 14 Jan 2016 16:43:28 -0800

**Comment by larkin** [comment]
closing as wontfix, not part of public API, new docs will be better tailored to what devs need.
