### ISSUE TITLE
Tags not persisting locally

### ISSUE THREAD

**Issue by scottbell** [nasa/openmct#5361]
#### Summary
Tagging a notebook entry, and then returning to a notebook entry, doesn't display the tags.

#### Expected vs Current Behavior
Tags should display

#### Steps to Reproduce
For original issue:
1. Tag a notebook entry
2. Navigate away
3. Observe entry is lacking tags

For @ozyx's issue:
1. Create several notebook entries in the same notebook
2. Quickly add one tag to them all
3. Quickly navigate away, then back to the notebook
4. Observe some entries may be missing added tags

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [X] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by unlikelyzero** [comment]
@rukmini-bose and @scottbell to sync on this issue given her discoveries in https://github.com/nasa/openmct/issues/4820#issuecomment-1164993710

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 07/01/22. I'm able to create a notebook, add tags, and navigate away and back with the tags persisting after navigation.

**Comment by ozyx** [comment]
Testathon 07/01/22:

Tested locally:
```
Version: 2.0.5
Build Date: Fri Jul 01 2022 11:52:09 GMT-0700 (Pacific Daylight Time)
Revision: a040bb30c22939cc8c7690662accda15749c2064
Branch: release/2.0.5
```

Not verified. Found an issue where creating multiple entries and tagging them, navigating away and back causes some of the tags to disappear.

https://user-images.githubusercontent.com/9259993/176954457-37a7b774-bce5-4e0d-bca0-dae91346701d.mov

**Comment by charlesh88** [comment]
Unable to verify Testathon 07-01-22: no tags are defined on the server, so can't test.

**Comment by scottbell** [comment]
It looks like the issue was here:
https://github.com/nasa/openmct/compare/release/2.0.5...5361-tags-not-persisting-locally-fast-switch?expand=1#diff-e4ed02719deee7500d3d218eed98aff4b89f542ea5693d56fad79b1840198f63L179
where the annotation creation would sometimes finish after the mutation for the new tag had fired. I think I've got a fix where I add the tag to the annotation creation instead.

**Comment by unlikelyzero** [comment]
@scottbell @ozyx can you update this issue to include steps for reproducing the race condition?

**Comment by scottbell** [comment]
> @scottbell @ozyx can you update this issue to include steps for reproducing the race condition?

There's a section called "Steps to Reproduce" that includes how to do it - let me know if you need more.

**Comment by alizenguyen** [comment]
Verified Testathon 7/6/2022: 

All tags remain after navigating away and returning
