### ISSUE TITLE
Stacked Plots having configuration saved on load

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#5363]
#### Summary
In general configurations should not be persisted unless the user explicitly makes a change.

#### Expected vs Current Behavior
Stacked plots should have a reasonable default configuration if it doesn't have one

#### Steps to Reproduce
1. create a stacked plot object
2. drag and drop telemetry into the stacked plot object and save
3. open console browser and navigate to network tab
5. navigate away from and then back to the stacked plot
6. go into edit mode
7. save the stacked plot
9. you should not see a network PUT call to the persistence provider Couch
10. go into edit mode again
11. click on a plot in the stacked plot object
12. modify properties in the plot series in the inspector (aka color of plot lines)
13. save the plot
14. now you should see a network PUT call to couch

#### Environment

* Open MCT Version: release/2.0.5
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by alizenguyen** [comment]
Verified Testathon 6/23/22

**Comment by davetsay** [comment]
verified
