### ISSUE TITLE
Fault Management visual issues

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#5365]
![Screen Shot 2022-06-16 at 11 33 58 AM](https://user-images.githubusercontent.com/1056412/174141627-1ea8bf1d-0125-4c6a-8916-bc2f183bb97f.png)

#### Summary
There are some visual issues that should be fixed in the current implementation of Fault Management:
- [x] The header gets really messed up (pink arrow) when the FM view is compressed horizontally, but needs to handle that case gracefully.
- [x] We need more visual differentiation between unacked and acked faults.
- [x] The elements within a Fault item need vertical margin for a better layout when horizontally compressed (blue arrow).
- [x] The action buttons (green arrow) should be the same size as the standard buttons, like Snapshot.
- [x] Change bell "Acknowledge" icon from bell to checkmark.
- [x] Change Fault Management icon to bell.
- [x] Add `title` attributes onto Trip and Live

#### Environment

* Open MCT Version:  v2.0.5
* Deployment Type:  /testathon
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by unlikelyzero** [comment]
@charlesh88 @rukmini-bose are we targetting 2.0.6 or 2.1.0?

**Comment by rukmini-bose** [comment]
@unlikelyzero These should be fixes for 2.0.6. @charlesh88 Can you please confirm?

**Comment by charlesh88** [comment]
Todos July 1, 2022
- [ ] Values should be in their own container so that background colors don't span the whole cell.
- [ ] Fix markup so grid definition only applies to header and body rows, not entire view.

**Comment by charlesh88** [comment]
We're looking quite good at this point. I may push on this a bit later tonight or over the weekend.

**Comment by charlesh88** [comment]
#### Main view with selected fault
<img width="1391" alt="Screen Shot 2022-07-05 at 3 50 31 PM" src="https://user-images.githubusercontent.com/1056412/177432431-a1cb7c10-ffbd-4cd7-bc84-3d3d383bd825.png">

#### Disposition dialog
<img width="1391" alt="Screen Shot 2022-07-05 at 3 50 38 PM" src="https://user-images.githubusercontent.com/1056412/177432415-f013c7eb-32b5-4135-8037-891a394934a0.png">

#### Acknowledged fault
<img width="815" alt="Screen Shot 2022-07-05 at 4 20 11 PM" src="https://user-images.githubusercontent.com/1056412/177432496-8a9ff899-8f90-416d-9a38-04cee58fe259.png">

#### Width < 600px in a layout
<img width="316" alt="Screen Shot 2022-07-05 at 4 19 26 PM" src="https://user-images.githubusercontent.com/1056412/177432428-2c6e31a9-fa90-4509-b70b-6a08ada5bdf2.png">

**Comment by charlesh88** [comment]
Testathon 07-11-22 verified fixed.
