### ISSUE TITLE
[e2e] Add firefox and chrome canary to the full suite

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#5366]
#### Summary
There have been a few firefox specific bugs and at least one chrome-version-specific bug in the recent past. Playwright supports running in many different browsers and in most cases, firefox support should be "free".

#### Execution
- [x] Add firefox project to playwright configs
- [x] Run through the current suite to see what all needs to be modified for firefox support
- [x] Report firefox bugs

**Comment by unlikelyzero** [comment]
### Testing Notes
Run the CI tests in firefox headed mode
Scan the test suite for a test which is skipping firefox execution. Run that suite with Chrome. Run that suite with firefox and verify that firefox is skipped

**Comment by shefalijoshi** [comment]
Reopening - not verified.
