### ISSUE TITLE
Populate default layout grid size values when Creating

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#537]
<p>From Jay and Alan 8/13/15.</p> <p>When creating a layout or telem panel, the Create dialog displays empty fields for the layout grid height and width. These fields should be populated by default.</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1510
Originally created: Thu, 13 Aug 2015 16:17:00 -0700
Updated: Thu, 14 Jan 2016 17:01:16 -0800

**Comment by larkin** [comment]
Resolved.
