### ISSUE TITLE
[Timelines/Activities] Allow named URL links to objects

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#538]
<p>Allow the user to assign links (name + URL) to domain objects, particularly Activities. This may be useful for other object types as well. User must be able to edit in Properties view, and may also be able to at time of first creation in Create overlay.</p> <p><b>Charles (in response to below)</b><br/> Sound good. If the user is just adding name/value pairs, I’d do it like iTunes Smart Playlist editing where a + button adds a new name/value pair row of input fields. Hovering over existing ones affords a “-“ sign or trashcan that can be used to remove the row. I’ll add this as a sketch to the UI doc.</p> <p>Is this something that needs to manifest initially when the user is creating the Activity, or is it something that’s touched later? The answer here drives whether this interface also needs to be present in the Create dialog overlay that’s displayed every time the user adds an Activity. </p> <p>Also, what’s the expected behavior when the user clicks a link? Open new browser window per link feels Ok to me, but does that work in an opps context?</p> <p><b>From Jay, via email "Activity Links"</b><br/> This is a note/reminder that activities must be able to link to a URL or a file. This is not a requirement for the immediate release, it’s a nice to have, but not required. The current activities, in the desktop client, allow the user to add two links I think. We use those for activity descriptions and procedures.</p> <p>Here’s how it should work:</p> <p>Each activity should have a pre-defined space for links to the activity description, flight rules and procedures (meaning three links already there). From there the user should be able to add a link and name it, rather than being limited to two. A simple + sign with a dialog, or however Charles wants to do it is fine with me. Realistically we should be able to add up to five links, though that number is arbitrary.</p> <p>For now we can link to the documents in Google Drive. We will need to move off of Google Drive over time, perhaps to our own server as per our earlier discussions.</p> <p>Please put this on the list, as I said, it’s not a requirement for the end of year release.</p> <p>Thanks.</p> <p>Jay</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-361
Originally created: Tue, 9 Sep 2014 11:13:03 -0700
Updated: Thu, 7 Jan 2016 17:42:49 -0800

**Comment by charlesh88** [comment]
Functionality partially implemented with new Hyperlink domain object with #1652. Most important here is the inclusion of external links as an Activity property.
