### ISSUE TITLE
[Static Root Plugin] Plugin fails to load if key value in the tree is null

### ISSUE THREAD

**Issue by khalidadil** [nasa/openmct#5380]
#### Summary
The static root plugin recursively crawls down the tree to rewrite object identifiers so that they can be unique to the plugin. In the logic it looks like there's a spot where `null` values aren't handled properly, causing the parsing of the object tree to fail.

#### Steps to Reproduce
1. Export a JSON tree where one of the key values is null
2. Set up the static root plugin and use the exported JSON path to load the exported tree. You'll notice that the static root plugin fails to load the tree successfully

#### Impact Check List

- [X] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by unlikelyzero** [comment]
@khalidadil can you add test instructions to this dude

**Comment by khalidadil** [comment]
Testing instructions:
1. Locally get the latest viper-openmct release/2.0.5
2. Download the attached JSON file
3. Replace the file with the same name in the root of the viper-openmct root directory
4. Run `npm run clean` `npm install` and `npm run build:dist`
5. Start the app with `npm start` and make sure the Static Objects folder and children load without errors in devtools

**Comment by davetsay** [comment]
verified. can see the map tool object inside of static objects folder

**Comment by akhenry** [comment]
Verified fixed. I was able to successfully load the attached filed with no errors.
