### ISSUE TITLE
[Operator Status] RangeError: Invalid time value

### ISSUE THREAD

**Issue by khalidadil** [nasa/openmct#5385]
#### Summary
I'm seeing the following error on banner testathon:
![Screen Shot 2022-06-23 at 5 03 00 PM](https://user-images.githubusercontent.com/2343076/175423419-734ec0b4-c0de-429f-842e-67b57a6390d4.png)

#### Impact Check List
- [ ] Data loss or misrepresented data?
- [X] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Steps to Reproduce
1. Load the page and the error should be visible in the Chome devtools

#### Environment
* Open MCT Version: release/2.0.5 on 06/23/2022
* Deployment Type:  Viper Testathon
* OS: MacOS 11.6.6
* Browser: Chrome

**Comment by shefalijoshi** [comment]
I also noticed this on Open MCT load:
<img width="762" alt="image" src="https://user-images.githubusercontent.com/5247066/175429597-2fe0e45a-0acf-4b06-9504-13501b54ec34.png">

**Comment by akhenry** [comment]
Good catch, I'll take a look.

**Comment by unlikelyzero** [comment]
@khalidadil @akhenry can you add some test instructions?

**Comment by khalidadil** [comment]
Testing Instructions:

1. Load the OpenMCT page on the testing server.
2. Check the developer tools and make sure the errors above are no longer displayed (original errors were seen on load of any OpenMCT page).

**Comment by khalidadil** [comment]
I'm still seeing the error in the original issue:
![Screen Shot 2022-07-06 at 2 04 48 PM](https://user-images.githubusercontent.com/2343076/177624215-360dbf8d-3390-4a1f-b589-884b812a3e7c.png)

**Comment by ozyx** [comment]
Verified Testathon 7/8/22

No longer seeing this error in the console on load
