### ISSUE TITLE
Using New Search while editing yields unexpected results

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#5391]
#### Summary
1. While editing an object view, use the new search capability to find something. 
2. Click a search result, observe: the selected object view is navigated to in the main view, _replacing_ the view that was previously being edited. The application remains in Edit mode. One can do this multiple times, and whilst saving (impressively!) persists any changes to _all_ views that were navigated to in the course of this flow, this behavior is not what the user expects and could be highly distressing if a lot of edits to a view hadn't been previously saved.
 
#### Expected vs Current Behavior
Search (in the tree) while editing used to provide a way to find objects in order to add them to a composition. This issue is filed as a bug (rather than an enhancement) because this change is a regression from prior capability and there is real concern about users being very surprised by this behavior. 

There are a number of possible solutions, in order of preference (and decreasing scope?): 
1. The user should be able to drag a result from the new search window directly into a composition, the same as if they were interacting with a tree element. Clicking on a result is handled as described in the next solution.
2. Clicking on a result could display it in the Large View overlay in the same way that clicking a tree item does while editing. Drag-to-add-to-composition (as described above) could be added later.
6. Disable new search during Edit mode and reinstantiate the old tree-based search as a filter capability.
7. Just temporarily disable new search during Edit mode until we can implement a better solution as described above. This can be done as a pure CSS solution.

#### Steps to Reproduce

1. See summary.

#### Environment

* Open MCT Version:  release/2.0.5
* Deployment Type:  local
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information
![Screen Shot 2022-06-24 at 3 47 41 PM](https://user-images.githubusercontent.com/1056412/175744556-84b68967-f598-4ed0-9f72-9d8c5b64f8f7.png)
![Screen Shot 2022-06-24 at 3 47 49 PM](https://user-images.githubusercontent.com/1056412/175744625-817ff301-8d05-40f3-b2c9-c7bf63d9a686.png)

**Comment by khalidadil** [comment]
@scottbell what was the intended fix from the list of possible solutions? On testing it looks like fix #1 and 2 specified by Charles are working.

**Comment by scottbell** [comment]
Fixes #1 and #2 were preferred, so it sounds like we’re good!
