### ISSUE TITLE
Domain Object Properties are not applied at time of being set

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#5398]
#### Summary
Domain Object Properties are not applied at time of being set. This appears in many different forms, but the most recent example is with an issue filed here https://github.com/nasa/openmct/issues/5138

#### Expected vs Current Behavior
We expect that a domain object's representation is **immediately** updated after using the 'Edit Properties' Menu, however it takes a refresh or a navigation trigger.

#### Steps to Reproduce
It applies to all domain objects, but the example for a Display Layout:
1. Create or navigate to an already created Display Layout
2. Add an Example Imagery into the Display Layout and Save and exit
3. Edit Properties of Display Layout and grid dimensions (name does not apply to this case)
4. Click OK
Note: Grid Dimension changes do not take affect
5. Refresh or Navigate to-and-from the domain object again
Note: Grid Dimensions have taken affect

#### Environment
* Open MCT Version: 2.0.5

#### Impact Check List
- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by mpingleton** [comment]
I tried to replicate the error on my installation, but it seems the domain object is updated immediately upon editing properties.  Am I missing something?

**Comment by charlesh88** [comment]
> I tried to replicate the error on my installation, but it seems the domain object is updated immediately upon editing properties. Am I missing something?

Are you using the `release/2.0.5 branch`? This may be a regression and you may not see it in all cases in `master`.

**Comment by ozyx** [comment]
@mpingleton There's also the possibility that this is specific to CouchDB persistence and not localStorage. It isn't mentioned in the ticket, but this bug has so far (to my knowledge) only been observed while using the CouchDB plugin.

**Comment by ozyx** [comment]
Confirming that I am unable to reproduce this using `localStorage`. It seems to be an issue specific to the `CouchDB` plugin

**Comment by ozyx** [comment]
## Testing Notes

1. Create a domain object with more than 5 editable properties (such as Example Telemetry)
2. Edit a single property far down the list
3. Press 'Save'
4. Verify that the property is updated
5. Navigate away, navigate back
6. Verify that the property persists
