### ISSUE TITLE
Use Requirejs optimizer for production builds

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#54]
Currently the application uses requirejs to load modules without using the optimizer.  This results in a large number of requests made to load the app and slows down application load significantly.  Additionally, it causes us to use caching settings that are not ideal for production environments.  

Using the requirejs optimizier to generate a single javascript file which can be fingerprinted and cached as a whole would decrease load times substantially.

**Comment by larkin** [comment]
Note that when the server requires auth for all requests, the load time for OpenMCTWeb increases substantially because of the large number of files that must be individually requested.  The optimizer would be very useful in this case.

**Comment by VWoeltjen** [comment]
Addressed in the context of #642
