### ISSUE TITLE
[CouchDB] Status indicator erroneously shows 'connected' in some scenarios

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#5406]
#### Summary

If a response is received on initial connect to CouchDB with a status code that is not explicitly handled, the status indicator will erroneously show 'green' -- CouchDB is connected.

Example: If connecting to CouchDB in a stopped docker container, Docker will return a 503. Since this code isn't explicitly handled, the CouchDB indicator will show "connected" as this is the default state if any response is received.

#### Expected vs Current Behavior

The CouchDB indicator should show red/disconnected if a 5xx response code is received.

#### Steps to Reproduce

1. Run CouchDB in a docker container
2. Stop the CouchDB docker process
3. Start OpenMCT (configured to connect to the CouchDB instance)
4. Notice that the status is green 'connected'

#### Environment

Version: 2.0.5
Build Date: Mon Jun 27 2022 13:56:25 GMT-0700 (Pacific Daylight Time)
Revision: 00a5cbd2fd2a68de2c5ad7b385bafbe90c98903d
Branch: release/2.0.5

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by shefalijoshi** [comment]
Couch DB indicator does show OFFLINE when couch is taken down.
However, when couch comes back up, the indicator does not show 'green' till you interact with the Open MCT application.

**Comment by ozyx** [comment]
# Testing Instructions

1. Navigate to OpenMCT in our testing environment
2. Verify that CouchDB status indicator is green
3. Stop the CouchDB container on the server: `docker stop <container id>`
4. Verify that the CouchDB status indicator has become red
5. Start the CouchDB container on the server `docker start <container id>`
6. Wait at least 20 seconds (perform no actions or navigation) and verify that the CouchDB status indicator becomes green again
7. Click around a bit to smoke test that the CouchDB connection is alive again

**Comment by unlikelyzero** [comment]
It is good

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon 10/24/2022

**Comment by khalidadil** [comment]
Looks like "Clear site data" under the Chrome application tab is *not* the same thing as the "Empty cache and hard reload" option! I did the former and it looks like I didn't have the new code until I did the "empty cache and hard reload."

Verified Fixed in Testathon on 10/24/22
