### ISSUE TITLE
Search should indicate if the result is from a removed object

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#5407]
The object and tag search can bring up results from objects which have been removed. This is fine, but there is currently no visual indication of this. This can potentially lead to some confusing search results.

This is most apparent with tags:
![image](https://user-images.githubusercontent.com/9259993/176297385-20e54ba8-7899-4c93-9aa4-b7c51911a403.png)

...but can also be confusing with objects:
![image](https://user-images.githubusercontent.com/9259993/176298102-596ed0aa-787c-434c-9b18-846834106b9e.png)

Especially if they have the same name:
![image](https://user-images.githubusercontent.com/9259993/176299315-be76ae0b-e663-410c-96af-19f80468edd8.png)

**Comment by charlesh88** [comment]
This is a good candidate as we move forward on the search capability. By default, we should not include removed objects in the results, with a option in an Advanced search UI to enable searching for removed objects. Result items should also include a designator when an object has been removed.

**Comment by scottbell** [comment]
> This is a good candidate as we move forward on the search capability. By default, we should not include removed objects in the results, with an option in an Advanced search UI to enable searching for removed objects. Result items should also include a designator when an object has been removed. If we do this, removed objects should also be allowed to be restored via a UI gesture.
> 
> In the short-term, I'd argue we should not include removed objects at all in order to avoid confusion as noted, but I'm open to arguments to the contrary.

Agree regarding removed items in search, but we'll need a good way to designate them "deleted". We used to rely on them no longer being reachable in the network graph, but this doesn't work for annotations. One idea to do this:
Have objects that are deleted (like annotations) designated with a `deleted` boolean attribute. When `deleted` is present and `true`, don't index the item.

**Comment by scottbell** [comment]
@akhenry Thinking about this more, another idea is index all the regular domain objects first (i.e., non-annotations), and then index all the annotations. We could then only index annotations that have "reachable" targets, namely annotations that have an indexed domain object target.

**Comment by jvigliotta** [comment]
This is related, but possibly moot if we don't show the objects in search. Although, if you know the id, you could still navigate to it. #5603

**Comment by scottbell** [comment]
Orphaned objects should not be returned anymore in search

**Comment by khalidadil** [comment]
I'm still seeing objects that are missing in the tree. I think @jvigliotta did some digging on this. Testathon on 08/04/22

**Comment by khalidadil** [comment]
When I create an object and then delete it, it no longer shows up in the search. There may be some other search issues, but this seems to be fixed. Verified Fixed in Testathon on 08/04/22
