### ISSUE TITLE
[Notebook] Various visual issues with Notebook navigation

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#5413]
#### Summary

A few visual issues with naming sections or pages in any Notebook (including other notebook types).

#### Expected vs Current Behavior

1. 
**Current**: Section / Page names are truncated while renaming. This is more apparent with a reduced screen width.
**Expected**: Section / Page names should not be truncated while input is active.

https://user-images.githubusercontent.com/9259993/176560917-19162b48-6c00-4caf-ae0d-e4516df4d30e.mov

2. 
**Current**: Hitting 'enter' while renaming a section or page adds a newline instead of confirming entry. Note that the newline is added *before* the text and not after.
**Expected**: Hitting 'enter' should confirm the rename and *not* add a newline. **Question for @charlesh88**: Should newlines be able to be added to section/page names with another key combo such as Shift+Enter?

https://user-images.githubusercontent.com/9259993/176561153-32a1c86e-19ed-4dcd-873d-6bbb3d0db76b.mov

3. 
**Current**: If only one section or page exists in the Notebook, renaming that section or page results in a "blank" that cannot be renamed until context is switched or the section or page is deleted.
**Expected**: After removing the last remaining section or page, the Notebook must always add in a new section or page titled with the correct default value ('Unnamed Section/Page').

https://user-images.githubusercontent.com/9259993/176561364-d837886d-4b1d-4981-837b-5990758a28d8.mov

4. 
Clicking on a section or page to navigate to it immediately puts the name into edit mode, but doesn't assign the correct CSS class for the contenteditable span element. This makes using the nav pane to view pages a very bad experience, and adds a bunch of risk that a section or page may be accidentally renamed.

<img width="272" alt="image" src="https://user-images.githubusercontent.com/1056412/182681828-9ba29016-24b2-4a1d-999e-39e45d643c6a.png">

Instead, the user should only be able to edit a previously _selected_ section or page. So to rename a non-selected section or page, they must select it, then click it again. 

<img width="266" alt="image" src="https://user-images.githubusercontent.com/1056412/182683151-d51fa92d-a1ff-4a94-944f-8d72d7fc746c.png">

This mimics how file renaming works in many computer operating systems. This is how it used to work and how it should work now.

#### Steps to Reproduce

See videos above.

#### Environment

Version: 2.0.5
Build Date: Wed Jun 29 2022 12:58:29 GMT-0700 (Pacific Daylight Time)
Revision: e8df2bd437bc2eef193b7eff9c8120a455c0048e
Branch: release/2.0.5

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information
Problems may have been introduced with changes made in 9fbb695379cc695d2a76c23ea3f2566bcc54aa7c.

**Comment by charlesh88** [comment]
> **Current**: Hitting 'enter' while renaming a section or page adds a newline instead of confirming entry. Note that the newline is added _before_ the text and not after. **Expected**: Hitting 'enter' should confirm the rename and _not_ add a newline. **Question for @charlesh88**: Should newlines be able to be added to section/page names with another key combo such as Shift+Enter?

No, section/page names should not support line breaks in any form.

**Comment by charlesh88** [comment]
This behavior has a pretty significant impact on the usage of the Notebook, which is getting a lot of visibility. @akhenry We should fix this.

**Comment by unlikelyzero** [comment]
Will need to pick this up for testing in next release

**Comment by rukmini-bose** [comment]
Verified Testathon 9/12 

Issues 1-4 seem to have been fixed.

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon 9/12/22 all steps
