### ISSUE TITLE
Potential for memory leaks with Telemetry Collections

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#5419]
#### Summary
Telemetry Collections allow views to offload bounds checking to the telemetry API and focus on displaying telemetry data. Telemetry Collections will maintain historical telemetry for the duration of the currently configured time conductor bounds by design.

Although this is intended behavior, if telemetry collections are used for doing simple bounds checking in "instantaneous value" type displays, like [LAD Tables](https://github.com/nasa/openmct/blob/master/src/plugins/LADTable/components/LADRow.vue#L135) and Channel Tables, it can lead to a memory leak, albeit a bounded one. These types of displays are only ever interested in the latest telemetry values, but if a TelemetryCollection is used for this purpose it will hold onto a lot of historical values unnecessarily.

#### Expected vs Current Behavior
A potential solution is to have Telemetry Collections inspect the request options and honor the 'latest' strategy when present. In this case it would just not retain any history.

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [x] Does this have an impact on Performance?

**Comment by jvigliotta** [comment]
## Testing
- gooooood question

**Comment by akhenry** [comment]
Confirmed fixed with LAD Tables -
1. Created LAD table with 11 members in system with the fix
2. Exported to legacy system without the fix
3. Set time window to 15 minutes in both
4. Observed memory grow by several MB in just a few minutes in the legacy system. Memory stayed stable in the system with the fix.
