### ISSUE TITLE
Old stacked plot objects broken with console error

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#5420]
#### Summary
Seeing a console error when trying to view an old stacked plot object and the stacked plot does not render.
Probably related to #5198 

```
vue.js?7193:634 [Vue warn]: Error in mounted hook: "TypeError: Cannot read properties of undefined (reading 'find')"

found in

---> <StackedPlotItem> at src/plugins/plot/stackedPlot/StackedPlotItem.vue
       <StackedPlot> at src/plugins/plot/stackedPlot/StackedPlot.vue
         <Root>
warn @ vue.js?7193:634
vue.js?7193:1906 TypeError: Cannot read properties of undefined (reading 'find')
    at VueComponent.getPlotObject (StackedPlotItem.vue?76c1:227:1)
    at VueComponent.updateView (StackedPlotItem.vue?76c1:135:1)
    at VueComponent.mounted (StackedPlotItem.vue?76c1:99:1)
    at invokeWithErrorHandling (vue.js?7193:1872:1)
    at callHook (vue.js?7193:4236:1)
    at Object.insert (vue.js?7193:3165:1)
    at invokeInsertHook (vue.js?7193:6385:1)
    at VueComponent.patch [as __patch__] (vue.js?7193:6602:1)
    at Vue._update (vue.js?7193:3964:1)
    at VueComponent.updateComponent (vue.js?7193:4082:1)
```

#### Expected vs Current Behavior
Stacked plots should work regardless of when they were created

#### Steps to Reproduce
1. Navigate to a plot object created before #5198 was merged in
2.
3.
4.

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [x] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by shefalijoshi** [comment]
We need an interceptor for Stacked plots that don't have configuration.

**Comment by ozyx** [comment]
Not fixed. Testathon 7/8/22

Still seeing this when viewing an old stacked plot:

![image](https://user-images.githubusercontent.com/9259993/178050536-783660bc-c513-49e3-854c-caa946a52679.png)

**Comment by ozyx** [comment]
Verified Testathon 7/8/22:

After redeploy, not seeing errors anymore, just the 'Missing domain object' warning when viewing an older stacked plot

**Comment by davetsay** [comment]
verified locally
