### ISSUE TITLE
If no poll question has been set, operator status indicator shows "--"

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#5424]
#### Summary
A minor gripe, but it will affect how our users first experience operator status if we don't address it.

#### Expected vs Current Behavior
The operator status indicator shows the current operator's status, OR if one has not been set it displays the current polling question. If neither an operator status, nor a poll question has been set, it is showing "--". Ideally it would show a more informative message to indicate that no poll question has been set.

#### Steps to Reproduce
1. Restart Yamcs to clear the latest data table
2. Reload Open MCT
3. Observe that the operator status indicator shows the text "--"

#### Environment
* Open MCT Version: release/2.0.5
* Deployment Type: VIPER Test

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by unlikelyzero** [comment]
@akhenry this will need test instructions

**Comment by akhenry** [comment]
### Testing instructions
1. Follow the repro steps in the issue
2. Verify that the poll question text now reads "NO POLL QUESTION" by default

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 07/08/22 - The default text now reads "No Poll Question". 

This is unrelated, but I can still set a status without a question which doesn't make sense to me. We may want to clean that up at some point.

![Screen Shot 2022-07-08 at 3 01 33 PM](https://user-images.githubusercontent.com/2343076/178062481-9d14eb25-b36b-4592-9d46-beba16264f7f.png)
