### ISSUE TITLE
[Image Telemetry] Add thumbnail strip

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#543]
<p>Add thumbnail strip to view of image telemetry; see <a href="https://trunk.arc.nasa.gov/jira/browse/WTD-1170" title="Image telemetry implementation" class="issue-link" data-issue-key="WTD-1170"><del>WTD-1170</del></a></p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1275
Originally created: Mon, 15 Jun 2015 11:04:56 -0700
Updated: Thu, 14 Jan 2016 17:10:30 -0800

**Comment by charlesh88** [comment]
We did this with #1632! Closing.
