### ISSUE TITLE
Clicking on a search entry does not navigate to entry in tree

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#5439]
#### Summary
Clicking on a search entry displays the object, displays the correct inspector view(s), but does not highlight the object in the tree.

Fix should be in router, or search not using router properly.

#### Expected vs Current Behavior
The object should be selected in tree.

#### Steps to Reproduce
1. use search bar to search for an existing object
2. click on a valid search entry
3. observe that the object is displayed in the main view and the inspector view
4. click on the target icon `show selected item in tree`
5. observe object is not navigated to when it should

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by akhenry** [comment]
This may relate to https://github.com/nasa/openmct/issues/5469. Search results appear to have incorrect contextual paths.

**Comment by michaelrogers** [comment]
Fix verified in testathon 07/12/2022.

**Comment by shefalijoshi** [comment]
Not fixed - Click on the VIPER dictionary, then type 'analog' in the search box. Click on one of the search results. The telemetry endpoint is displayed, however it is not brought into view in the navigation tree until the target button is clicked.

**Comment by jvigliotta** [comment]
Verified Fixed: Testathon 7/12/22
