### ISSUE TITLE
[Plot] Y-axis labels do not vary in precision

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#544]
<p>In plot view, Y axis labels consistently truncate after three digits; this makes them useless in cases where the data has been automatically fit to a small range (such as when all points are close to zero)</p> <p>Desired behavior is to show enough precision to distinguish these values.</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1325
Originally created: Tue, 23 Jun 2015 08:50:08 -0700
Updated: Thu, 14 Jan 2016 16:37:08 -0800

**Comment by charlesh88** [comment]
Is this still an issue with #1557?

**Comment by larkin** [comment]
This is resolved by #1557.  Ticks resize and recalculate precision.
