### ISSUE TITLE
Unable to create a bar graph with endpoints with enum metadata

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#5442]
#### Summary
Dragging an Operator Status endpoint into a bar graph does not work and produces infinite recursion console error.

#### Expected vs Current Behavior
You should be able to drag an operator status endpoint into a bar graph and see it's status.

#### Steps to Reproduce
1. Create a bar graph
2. Drag an endpoint with only 1 metadata value (Operator Status endpoints on VIPER) into the bar graph
3. Observe 'infinite recursion' error in the console

#### Environment

* Open MCT Version: release/2.0.5
* Deployment Type: VIPER testathon
* OS: All
* Browser: All

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by unlikelyzero** [comment]
@scottbell this should be fine

**Comment by shefalijoshi** [comment]
Verified fixed
