### ISSUE TITLE
Add interface documentation

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#545]
<p>JSDoc3 supports @interface and @implements now (see <a href="http://usejsdoc.org/tags-interface.html" class="external-link" rel="nofollow">http://usejsdoc.org/tags-interface.html</a>)</p> <p>A number of interfaces in Open MCT Web are defined by usage - we should go through and add @interface definitions for the major types where they are used (e.g. document the Indicator interface in whatever the primary consumer of Indicators[] is)</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1227
Originally created: Tue, 2 Jun 2015 10:19:01 -0700
Updated: Thu, 14 Jan 2016 16:38:15 -0800

**Comment by larkin** [comment]
won't address this directly, instead plan to update docs as we go.
