### ISSUE TITLE
Bar Graph does not update when time conductor value changes

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#5456]
#### Summary
Changing time conductor in fixed or local clock mode does not update the graph with new data.

#### Expected vs Current Behavior
Bar Graph should be updated to show relevant data to the time conductor.

#### Steps to Reproduce
1. Drag the analog aggregate to a bar graph
2. Expect that some bars are displayed (this is currently not happening)
3. Change time conductor start/end
4. Expect that some bars are displayed with new data.

#### Environment

* Open MCT Version: release/2.0.5
* Deployment Type: VIPER testathon
* OS: all
* Browser: all

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by akhenry** [comment]
Note that https://github.com/yamcs/yamcs/issues/685 will interfere with verifying this with real data.

**Comment by akhenry** [comment]
Verified fixed
* Switched to fixed mode
* Changed time conductor bounds
* Verified in the network tab that historical requests were being issued with the correct bounds.

**Comment by ozyx** [comment]
Verified 7/12/22

Was able to add analog aggregate to the bargraph, and change bounds in fixed/local clock modes. No loss of data was observed. In local clock mode, bars updated correctly as new telemetry streamed in.
