### ISSUE TITLE
Adding a Telemetry Point to a display layout throws an error and shows no data

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#5460]
#### Summary
Dragging a telemetry point from the tree into a display layout throws an error and shows no data.

```
TelemetryAPI.js?7b82:64 Uncaught (in promise) TypeError: CustomStringFormatter.default is not a constructor
    at TelemetryAPI.customStringFormatter (TelemetryAPI.js?7b82:64:1)
    at a.setObject (TelemetryView.vue?2ac2:284:1)
```

#### Expected vs Current Behavior
The telemetry point should immediately begin displaying real-time data and there should be no errors in the JavaScript console.

#### Steps to Reproduce
1. Create a display layout
2. Drag a telemetry point into the display layout
3. Observe that no telemetry is shown, and the an error is displayed in the JavaScript console

#### Environment
* Open MCT Version: 2bd38dab9fad630d2211471eee35f92a37a1c040
* Deployment Type: Viper Testathon

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by jvigliotta** [comment]
## Testing
- instructions in "Steps to Reproduce" above

**Comment by akhenry** [comment]
Verified fixed

**Comment by davetsay** [comment]
verified
