### ISSUE TITLE
Legacy stacked plot interceptor should be renamed for clarity

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#5463]
#### Summary
see #5422 for relevant code to rename

**Comment by unlikelyzero** [comment]
Needs updated test instructions

**Comment by alizenguyen** [comment]
**To Test:** 

Navigate to a plot object created before https://github.com/nasa/openmct/pull/5198 was merged in. No console errors should appear when viewing.

**Comment by ozyx** [comment]
Verified 7/11/22 Testathon:

Navigated to very old 1.7.8 stacked plot and saw no console errors.

**Comment by unlikelyzero** [comment]
### e2e testing notes
- generally, we should add a testcase which Imports an object from a previous stable release to understand how we're handling object changes over time
