### ISSUE TITLE
Remove performance marks for build 6

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#5464]
#### Summary
Performance marks are creating memory leaks in Telemetry Collections and Tables. Let's remove them for now until we can configure a performance-specific build.

#### Expected vs Current Behavior
Remove all LOC that are calling `window.performance.mark(..)` from non-test code.

#### Steps to Reproduce

1. Navigate to a LAD Table
2. Open the Chrome Dev Tools
3. Go to the memory tab
4. Run the garbage collector
5. Take a heap snapshot
6. Let the LAD Table run for 5 minutes
7. Run the garbage collector
8. Take a heap snapshot
9. Compare the heap snapshots. Sort by memory delta
10. Observe that a large number of performance marks were allocated between heap snapshots
![Screen Shot 2022-07-08 at 10 30 26 AM](https://user-images.githubusercontent.com/4215777/178044425-4ae7c82a-9d25-4044-9462-46d26f27f503.png)

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [x] Does this have an impact on Performance?

**Comment by unlikelyzero** [comment]
Re-enabling in some form here https://github.com/nasa/openmct/issues/5466

**Comment by unlikelyzero** [comment]
### Testing Notes
- [ ] Load a LAD Table and verify that when diffing two heapsnapshots that the references to performance.marks are not remaining

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 07/08/22

<img width="1652" alt="Screen Shot 2022-07-08 at 2 12 51 PM" src="https://user-images.githubusercontent.com/2343076/178056059-4f11cc99-8240-4d2b-9ab3-6ba12a061155.png">
