### ISSUE TITLE
Various UI problems

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#5467]
#### Summary
There are a number of UI-centric front-end problems that should be fixed:
- [x] Operator status label and layout needs fixing on the left-most column.
- [x] "Graph (Bar or Line)" name is not consistent with rest of the application.
- [x] CSS classing of menu items for Export as JPG and PNG is incorrect.
- [x] Vertical alignment of icons in `c-object-label` is broken.
- [x] Layout of menus in Imagery local controls is broken.
- [x] Gauge ranges and limits form organization is confusing.

#### Environment

* Open MCT Version:  release/2.0.5
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by charlesh88** [comment]
### Testing Notes
1. See list of issues reported above, verify against examples provided below

- [ ] Verify that Gauge property form fields layout as shown below:
<img width="660" alt="Screen Shot 2022-07-08 at 12 00 09 PM" src="https://user-images.githubusercontent.com/1056412/178065013-572c1eea-c19d-420c-a05c-0387f1804388.png">

- [ ] Verify the Export * menu items are not displayed with blue text:
<img width="150" alt="Screen Shot 2022-07-08 at 12 01 07 PM" src="https://user-images.githubusercontent.com/1056412/178065017-b1e46b51-a0b2-4970-baa7-e9f565e2cf89.png">

- [ ] Verify that Graph is named and described as shown:
<img width="509" alt="Screen Shot 2022-07-08 at 12 01 21 PM" src="https://user-images.githubusercontent.com/1056412/178065018-3557e809-bb73-415d-901a-fe2d2320233d.png">

- [ ] Verify that Imagery local controls display as shown:
<img width="231" alt="Screen Shot 2022-07-08 at 12 01 46 PM" src="https://user-images.githubusercontent.com/1056412/178065019-f53e834d-9aa4-4eaf-9d07-2c6c48234f08.png">
<img width="235" alt="Screen Shot 2022-07-08 at 12 01 52 PM" src="https://user-images.githubusercontent.com/1056412/178065021-a7e40f8c-8346-4f0e-92c5-b47f90aad8f6.png">

- [ ] Verify that "Current poll" reads as such:
<img width="365" alt="Screen Shot 2022-07-08 at 12 02 08 PM" src="https://user-images.githubusercontent.com/1056412/178065022-551fdb73-e69f-4ab2-a2ce-a2b957f079c6.png">

**Comment by rukmini-bose** [comment]
Verified Testathon 7/11/2022

**Comment by akhenry** [comment]
Verified Fixed.
