### ISSUE TITLE
Search results sometimes show the wrong contextual path, or no path at all

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#5469]
#### Summary
When displaying a list of search results, the results sometimes have the wrong contextual path displayed below each result, or the path is completely absent. This may relate to https://github.com/nasa/openmct/issues/5439

#### Expected vs Current Behavior
Each search result should include the contextual path to the object.

#### Steps to Reproduce
1. Import [the attached JSON file](https://github.com/nasa/openmct/files/9087545/Folder.A.json.zip)
2. Search for "Timer"
3. Observe that Timer A and Timer B are shown as suggested search results, but both context paths shown are incorrect

#### Environment
* Open MCT Version: 0f0a3dc48f1822132a2e2239dfd6d2c66500a06b
* Deployment Type: VIPER Test, local dev

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by scottbell** [comment]
replicated - looking into it.

**Comment by unlikelyzero** [comment]
Steps to Reproduce
Use search to look for something that returns a number of results in a location that is clearly different from your current location.
Note that the paths displayed for results may be the path to your current view's location, not the location of the result item.

**Comment by jvigliotta** [comment]
Verified Fixed: Testathon 8/2/22

**Comment by rukmini-bose** [comment]
Verified Testathon 8/2/22 

Might be unrelated to this issue, but there are a whole bunch of objects that do not have any sort of path and don't appear in the tree as well. <img width="654" alt="Screen Shot 2022-08-02 at 3 22 51 PM" src="https://user-images.githubusercontent.com/48999852/182483679-a1fd0cff-1403-4303-abcb-23a7b66e7660.png">

**Comment by akhenry** [comment]
@rukmini-bose Suspect those objects were "deleted" and are unreachable from the root object. ie. they're orphaned objects. 

We will look at better handling for deleted objects in Build 7, however we _could_ just ignore any objects without an original path for now? @scottbell Thoughts?

**Comment by scottbell** [comment]
@akhenry @rukmini-bose Yeah, that should be pretty straightforward to do!

**Comment by unlikelyzero** [comment]
Will fix based on @rukmini-bose 's finding in #3823

**Comment by scottbell** [comment]
> @akhenry @rukmini-bose Yeah, that should be pretty straightforward to do!

I have a fix in:
https://github.com/nasa/openmct/pull/5599
to filter objects (and tags that point to objects) that don't have an `originalPath`

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon 8/4/22

Created an object. Searched, it was there. Deleted it. Searched, it was no longer there.

**Comment by ozyx** [comment]
Verified Testathon 8/9/22:

Created an object. Was able to find it in the search. Tried switching focused path a few times and searching again, it still shows the correct path. Focused folders which were outside of 'My Items' folder and tested again, still shows the correct path. Deleted the object, and it no longer was able to be found via search.

**Comment by rukmini-bose** [comment]
Verified Testathon 8/11/22
