### ISSUE TITLE
Achieve a stable, useful API for plugin developers

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#547]
<p>Incorporate feedback from plugin developers to refine Open MCT Web API's, sufficient for a 1.0.0 release (after which time API will need to remain backwards-compatible, and developer useability issues may be harder to overcome)</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1195
Originally created: Tue, 12 May 2015 14:37:58 -0700
Updated: Thu, 14 Jan 2016 16:30:55 -0800

**Comment by larkin** [comment]
Closing this as represented in other issues.
