### ISSUE TITLE
CouchDB document creation timestamp is updated on every change

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#5472]
#### Summary
The creation date of a couchdb document is updated everytime the document is changed.
This should not be the case - it should be set once and only once - during creation of the document.

#### Steps to Reproduce
1. Create a new object under MyItems
2. Note the created timestamp
3. edit that object and save it
4. Note that the created timestamp is updated again

#### Environment

* Open MCT Version: release/2.0.5
* Deployment Type: VIPER Testathon
* OS: All
* Browser: All

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by jvigliotta** [comment]
Not Verified (I believe): Testathon 7/11/22

When it's first created, the metadata for the object has created time:
![Screen Shot 2022-07-11 at 11 41 49 AM](https://user-images.githubusercontent.com/12013460/178335648-de564e1e-825b-4f74-ad34-2b4940789372.png)


Subsequent requests do not have any created time:
![Screen Shot 2022-07-11 at 11 42 24 AM](https://user-images.githubusercontent.com/12013460/178335686-809e7fa3-4b0c-4c4e-a8ac-4093160cd51e.png)

**Comment by unlikelyzero** [comment]
FIX: Trivial
SEVERITY: Trivial

**Comment by jvigliotta** [comment]
Closing this now as it's a little more in-depth. Created this issue that is related: https://github.com/nasa/openmct/issues/5801
