### ISSUE TITLE
[Tests] Upgrade to Jasmine 2.x

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#548]
<p>Currently, test suite runs on Jasmine 1.3, which is a bit behind the current version. Jasmine 2.0 introduced some breaking changes, so updating would require modifications to a significant portion of tests. Still, should do this at some point to avoid falling too far behind (and so that we can take advantage of new features/improvements as they are added.)</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1166
Originally created: Fri, 1 May 2015 16:08:13 -0700
Updated: Thu, 14 Jan 2016 17:19:27 -0800

**Comment by akhenry** [comment]
Note that the SaveAsActionSpec uses the `waitsFor` and `runs` 1.x constructs. See https://github.com/nasa/openmct/pull/1170#r79203537

**Comment by VWoeltjen** [comment]
Think it's about time to look at this. A lot of tests are likely to move or change with API changes and associated platform refactors; placing in Robinson for evaluation, think that will be around the right time

**Comment by larkin** [comment]
Still desired.
