### ISSUE TITLE
Display Layout toolbar should be consistent

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#5480]
#### Summary
The Display Toolbar for alphanumerics changes depending on number of elements selected:

**One**
<img width="299" alt="Screen Shot 2022-07-11 at 10 48 19 AM" src="https://user-images.githubusercontent.com/1056412/178326556-4d8cac1a-a747-4d55-a5e3-8fcb4bfb58ef.png">

**More than one**
<img width="301" alt="Screen Shot 2022-07-11 at 10 48 27 AM" src="https://user-images.githubusercontent.com/1056412/178326581-dd7180ff-e55a-4575-9c84-f782131aed5a.png">

#### Expected vs Current Behavior
The labeled "View type" button should be the same regardless of the number of items selected.

#### Environment

* Open MCT Version:  r/2.0.5
* Deployment Type:  local
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 11/14/22

**Comment by ozyx** [comment]
Verified -- Testathon 11/17/22

The "View Type" button is the same when selecting one or more alphanumerics in a display layout w/ edit mode activated.

Excellent!

**Comment by rukmini-bose** [comment]
Verified Testathon 11/17/22
