### ISSUE TITLE
Fault Management is throwing console errors

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#5481]
#### Summary
Fault Management is throwing console errors on load and when updating (acking or shelving) a fault.
![image](https://user-images.githubusercontent.com/1056412/178331975-f53f9dcb-b7fe-497e-ad09-a6ce5c4d7648.png)

#### Expected vs Current Behavior
No console errors.

#### Steps to Reproduce

1. Load the Fault Management view.
2. Shelve or acknowledge a Fault.

#### Environment

* Open MCT Version:  r/2.0.5
* Deployment Type:  /testathon
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by unlikelyzero** [comment]
Verified Fixed
