### ISSUE TITLE
Condition Sets in Telemetry Views do not show any telemetry

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#5485]
#### Summary
When using condition sets as telemetry in Display Layouts the telemetry view of the condition set is showing no telemetry

#### Expected vs Current Behavior
The telemetry view of condition sets should display the current output value of the telemetry view.

#### Steps to Reproduce
1. Create a simple condition set with a frequently updating telemetry point
2. Create a display layout
3. Drag the condition set into the display layout
4. Observe that the telemetry view is blank

#### Environment
* Open MCT Version: 2.0.6 1c8784fec5ac2bcfb821b539a38d904e3c1cc926
* Deployment Type: VIPER Testathon

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by akhenry** [comment]
### Testing Instructions
1. Follow the reproduction steps.
2. Verify that the value of the condition set in the display layout shows the current output value of the condition set.

**Comment by shefalijoshi** [comment]
Verified fixed

**Comment by jvigliotta** [comment]
Verified Fixed: Testathon 7/12/22

**Comment by ozyx** [comment]
Verified 07/12/22

Created a condition set with `deltaTime`. One condition to output a string if value is > 0.08. The default condition outputs another string if the first one fails.

Embedded this condition set in a display layout. Saw that the value updated accordingly as telemetry streamed in.

https://user-images.githubusercontent.com/9259993/178596622-149c2347-0f48-4d2d-9624-5dfdd9f09fdc.mov
