### ISSUE TITLE
Open MCT is swallowing some persistence errors

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#5488]
#### Summary
In the event of a persistence conflict an error is shown in the JavaScript console, but is not displayed in the UI to the user.

#### Expected vs Current Behavior
The user should be informed of any persistence errors as this may impact their workflows.

#### Steps to Reproduce
The only way that I've found of _consistently_ triggering a persistence conflict is by repeatedly renaming an object. They also happen sporadically in other cases. Note that this has highlighted [another regression](https://github.com/nasa/openmct/issues/5489).

1. Rename an object
2. Renamed it again
3. Open the JavaScript console and observe that a persistence conflict has occurred, but none has been displayed to the user.

#### Environment
* Open MCT Version: 1c8784fec5ac2bcfb821b539a38d904e3c1cc926
* Deployment Type: VIPER Testathon

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by khalidadil** [comment]
I saw a few forms of this during testathon on 07/12/22. I would edit the properties on a hyperlink or a web page object in a subfolder, and the display would reflect the properties for a few seconds, but would then revert to the old settings. @ozyx noticed multiple PUT calls being made, including a PUT call with the old properties.

Here are some examples:

https://user-images.githubusercontent.com/2343076/178785738-15154d6c-64a9-4d98-a6a4-ff6f37062518.mov


https://user-images.githubusercontent.com/2343076/178785946-e72847e6-53a7-46a2-92a1-f59b63feb76d.mov

**Comment by ozyx** [comment]
@khalidadil see also #5398 , I believe this is the same issue. And unless anyone has experienced this with `localStorage`, I also believe this bug is specific to CouchDB persistence?

**Comment by akhenry** [comment]
# Test Instructions
1. Execute the reproduction steps in the issue description
2. Verify that a notification now appears informing the user that a persistence error has occurred.

**Comment by akhenry** [comment]
Closed in favor of https://github.com/nasa/openmct/pull/5576
