### ISSUE TITLE
Object rename is unreliable

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#5489]
#### Summary
Renaming of objects works unreliably right now.

#### Expected vs Current Behavior
Renaming an object should work immediately or should inform the user of any errors.

#### Steps to Reproduce
1. Create a folder
2. Rename the folder by clicking on the folder's name in the browse bar
3. Observe that the folder's name reverts to the original name almost immediately
4. This issue is not always reproducible, but repeating steps 2 and 3 should eventually trigger it.

#### Environment
* Open MCT Version: 1c8784fec5ac2bcfb821b539a38d904e3c1cc926
* Deployment Type: VIPER testathon

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment]
Verified Testathon 8/2/22

Repeated the steps many times, could not replicate the issue

**Comment by akhenry** [comment]
Verified Fixed.

Unsure how it got fixed. GitHub is mis-attributing to #5488, but they are separate issues.

**Comment by michaelrogers** [comment]
I'm seeing the same result as Andrew, the folder name will revert when changing it from the browse bar.

**Comment by akhenry** [comment]
OK, after some investigation, here's what I think is going on -
1. Renaming the object via the browse bar triggers a mutation event, as it should. Outside of edit mode this should trigger persistence as well, BUT!
2. Before persistence is triggered, an observer in the tree reacts to the change and refreshes the object from persistence by re-evaluating its composition (for some reason).
3. Refreshing the object replaces the in-memory model with the stale model from the persistence store, so the rename is almost immediately reverted.

**Comment by rukmini-bose** [comment]
Verified Testathon 8/22/22-- Cannot reproduce this issue using the original testing instructions.

**Comment by ozyx** [comment]
## Testing Instructions

### Verify object rename is persistent

Do the following in a live testing environment using CouchDB persistence.

- Create any domain object, call it "zzzz" or something easily alphabetizable
- Rename the object to "aaaa" by editing its name via the [browse bar | properties window]
- Verify that the object is renamed and appears in the correct order in the tree
- Click away to another object and click back, verify that the object name is persistent
- Collapse the folder the object is nested in and expand it again, verify the order of objects is maintained

Repeat the steps above for both methods of renaming objects

### Verify tree sorting is correct

The following may be performed locally or in a live testing environment with either LocalStorage or CouchDB persistence plugins.

- Create a folder
- Create a clock outside of the new folder, call it "zzzz"
- Create a clock within the new folder, call it "bbbb"
- Drag the outside clock ("zzzz") into the new folder to create a link
- Rename "zzzz" -> "aaaa"
- Verify that both the link and the original object are ordered correctly in the tree

**Comment by charlesh88** [comment]
Verified fixed Testathon 8/23/22.

**Comment by scottbell** [comment]
At least with local storage, still seeing this issue:

https://github.com/nasa/openmct/assets/9853862/c6ea1b1a-ede3-4728-ae61-d497990039fb
