### ISSUE TITLE
[Timelines] New child Activities should use Start of parent

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#549]
<p>When creating a timeline with a start time some time (days) in the future, activities created within that timeline still start at time 0, and it is a lot of work to move them over into the timeline.</p> <p>When subactivities exist within an activity but start well before it, I can't move the parent activity earlier in time, as the subactivities can't have a negative start time.</p> <p>These kind of odd, unobvious behaviour may require an adjustment to creating subactivities always at start time 0 as the default. We should probably discuss.</p>

Migrated from: 
Originally created: Thu, 23 Apr 2015 15:50:23 -0700
Updated: Thu, 7 Jan 2016 17:07:51 -0800

**Comment by RCarvalhoNASA** [comment]
Primarily this comes from the default settings.  When creating a sub-activity, it is autofilled with a start time of 0.  I suggest that when creating an activity within something (timeline or activity), that the default start of that new activity be the start time of the parent.  This will significantly reduce these issues.
