### ISSUE TITLE
[Scrolling view] Allow scrolling view to be filtered

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#550]
<p>Allow the scrolling view to be filtered by column value. Filtering should be appropriate to the column type; for example:</p> <ul class="alternate" type="square"> <li>String contains filtering might be applied to a Name column</li> <li>&lt; &gt; = filtering might be available for a numeric value column.</li> <li>Events might be filtered via a dropdown list of string values applied to a "severity" column.</li> </ul>
            

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1308
Originally created: Thu, 18 Jun 2015 14:18:20 -0700
Updated: Thu, 7 Jan 2016 16:26:06 -0800

**Comment by charlesh88** [comment]
This feature is complete!
