### ISSUE TITLE
[Build Process] Intermittent error when using execSync to get git rev and branch info

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#5501]
#### Summary

Sometimes, when including Open MCT as a dependency, there are errors (see image at end of issue). This seems to be due to using `execSync` during the build process to get the git revision and git branch information. (an explanation can be found here: https://github.com/lerna/lerna/issues/763#issuecomment-301717255). 

#### Expected vs Current Behavior

Consistently build without errors, currently you cannot build if you encounter this error.

#### Steps to Reproduce

1. Not entirely sure. I think it has do do with uncommitted changes in a branch, but not positive.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information

![Screen Shot 2022-07-13 at 2 08 26 PM](https://user-images.githubusercontent.com/12013460/178837135-8a74ef2f-88f7-4ac4-be31-c6c0bbb3308a.png)

**Comment by jvigliotta** [comment]
closed by https://github.com/nasa/openmct/pull/5433

**Comment by unlikelyzero** [comment]
Difficult to reproduce. Closing. Should re-open
