### ISSUE TITLE
No Code Coverage for toggleClass utility function in src/utils/template/templateHelpers.js

### ISSUE THREAD

**Issue by Drew-Daniels** [nasa/openmct#5522]
#### Summary
There is currently not code coverage for the `toggleClass` function in `src/utils/template/templateHelpers.js`. I would like to add tests that validate this function works as expected.
### Testing Instructions
- Navigate to the new `src/utils/template/templateHelpersSpec.js` file
- Update line 32 to the following (prepending an f to describe)(this is to ensure no other test suites are run):
```javascript
fdescribe('toggleClass', () => {
```
- Run `npm test`
- See that all the new tests pass

**Comment by unlikelyzero** [comment]
@Drew-Daniels this sounds great! I'm curious, did you find this in our codecov.io report?

**Comment by Drew-Daniels** [comment]
@unlikelyzero I did! I'll probably submit a few more issues/PRs for additional testing opportunities I find in there as well. Really like openMCT so far by the way!

**Comment by Drew-Daniels** [comment]
Made the tests for this, but looks like I need to sign the CLA first!

**Comment by unlikelyzero** [comment]
@Drew-Daniels yes that's a standard part of the NASA Open Source project .

If you don't mind, could you open up the PR and we can start reviewing it as we wait for your CLA to be approved?

That would also allow you to start another PR if you would like to on another ticket!

**Comment by Drew-Daniels** [comment]
Sure thing! Just sent in my CLA and created a PR for this.
