### ISSUE TITLE
PRCop only checks for lower-case `x` checkboxes

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#5526]
#### Summary

Our PRCop is currently verifying that "Testing instructions included in associated issue OR is this a dependency/testcase change?" has been checked off, but it's only checking for lower-case `[x]` checkboxes. Upper-case `[X]` checkboxes are also valid, which can lead to a confusing PRCop failure. The regexp should be updated to include upper-case X checkboxes.

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 08/02/22
