### ISSUE TITLE
Multiple problems in Time List view

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#5534]
Report of incorrect timestamps moved to https://github.com/nasa/openmct/issues/5605

**These default settings are non-optimal and should be changed to show all future events by default. Past events as 'don't show' is Ok.**
<img width="311" alt="Screen Shot 2022-07-20 at 10 14 59 AM" src="https://user-images.githubusercontent.com/1056412/180042980-daeb5ffb-6f4a-42ff-8dc2-145484f3bca0.png">

In addition, the ability to upload a file to a Time List directly is confusing and unclear about how it works.
1. Given the user's ability to create a Plan view and upload a file to _that_, and then put the Plan in the Time List, they can accomplish the same goal. 
2. The user is allowed to upload a file _and_ drag a Plan into a Time List - but which one is in effect? 
3. This is further complicated by the fact that the user cannot remove an uploaded file attached to a Time List. 

The upload file button in Time Lists should be removed.

#### Environment

* Open MCT Version:  R 2.0.5
* Deployment Type:  /testathon
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by charlesh88** [comment]
Original design and documentation: https://trunk.arc.nasa.gov/confluence/display/VIPERMS/Time+Views+in+Open+MCT%3A+Timelist+View

**Comment by charlesh88** [comment]
### Testing Notes
1. If needed, prepare a Plan view by accessing that object type in the Create menu. You can use the plan JSON file attached to this issue with the dates 2022-08-16 00:00:00.000Z to 2022-08-18 00:00:00.000Z.
2. Create a new Time List view. 
3. Verify that a 'Upload plan' form section and button is not displayed in the Properties dialog. Click 'Ok' to continue.
4. While editing the Time List, verify that the Inspector's 'Timeframe' properties time options all default to 'Show all': 
<img width="269" alt="image" src="https://user-images.githubusercontent.com/1056412/185262757-2d0929ae-c56b-45e2-b052-057eb227c5ae.png">
5. Drag a Plan view into the Time List. Verify that rows appear in a more vertically compact style (3px top/bottom padding), like this:
<img width="611" alt="image" src="https://user-images.githubusercontent.com/1056412/185262990-162edf09-2498-421e-9874-1b8fa2bf7a7f.png">
and NOT like this (7px top/bottom padding):
<img width="604" alt="image" src="https://user-images.githubusercontent.com/1056412/185263007-09ee41cf-3921-45f4-8277-b9b3830c4050.png">

**Comment by ozyx** [comment]
Verified -- Testathon 8/22/22

**Comment by rukmini-bose** [comment]
Verified 8/22/22
