### ISSUE TITLE
Correlation Telemetry Object throws errors and does not emit any correlated values

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#5539]
#### Summary
* Creating a correlation telemetry point does not result in any correlated data being emitted
* Errors are shown in the JavaScript console
* The errors persist even after navigating away from the correlation telemetry object, suggesting the existence of a memory leak.

#### Steps to Reproduce
1. Create two sine wave generators
2. Create a new correlation telemetry point and select the previously created sine wave generators as the telemetry sources
3. Save the new correlation telemetry point
4. Observe that no data is displayed
5. Open the JavaScript console and observe errors similar to below:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'namespace')
    at Object.makeKeyString (object-utils.js?40a1:98:1)
    at ObjectAPI.makeKeyString (ObjectAPI.js?99d1:595:16)
    at ObjectAPI.get (ObjectAPI.js?99d1:193:1)
    at getTelemetryObject (plugin.js?6ac3:7:1)
    at Object.request (plugin.js?6ac3:80:1)
    at TelemetryAPI.request (TelemetryAPI.js?7b82:281:1)
```

#### Environment
* Open MCT Version: 2bfe632e7e1779a5e8c879ee9bb204ee266f33ea (release/2.0.5)
* Deployment Type: VIPER test

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by jvigliotta** [comment]
This was made in another repo, closing as it's been fixed.

**Comment by jvigliotta** [comment]
Verified Fixed: Testathon 8/2/22
