### ISSUE TITLE
The in-memory search indexer is observing mutation of the composition property.

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#5549]
https://github.com/nasa/openmct/blob/2fa053e80ca7013aeb7ff94b57ac81e47c6197d6/src/api/objects/InMemorySearchProvider.js#L315

This is an unreliable method of detecting composition changes as not all objects will use the composition property to define their composition.

Instead, the Composition API should be used. It provides observers for composition changes that are agnostic of the underlying data structure.

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by scottbell** [comment]
To test:

1. Add a folder object
2. Add a clock object
3. Ensure you can search for folder and clock
4. Refresh page
5. Ensure you can search for folder and clock

**Comment by scottbell** [comment]
On our test server, we're getting an error:
```
Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'MessagePort': function(e,t){let o=e,a=t;return o<a&&(o=t,a=e),o-a<.5} could not be cloned.
    at InMemorySearchProvider.index (webpack-internal:///5244:747:34)
    at InMemorySearchProvider.onCompositionAdded (webpack-internal:///5244:692:18)
    at eval (webpack-internal:///6243:324:19)
    at Array.forEach (<anonymous>)
    at CompositionCollection.emit (webpack-internal:///6243:320:31)
    at CompositionCollection.add (webpack-internal:///6243:206:18)
    at eval (webpack-internal:///6243:226:48)
    at Array.forEach (<anonymous>)
    at CompositionCollection.eval (webpack-internal:///6243:226:30)
    at async InMemorySearchProvider.index (webpack-internal:///5244:758:30)
```

This is probably because the object has dangling functions on it. We should turn this into a domain object that can be serialized properly by `structuredClone` so the post to the `InMemoryIndexer` will work.

**Comment by ozyx** [comment]
Verified Testathon 8/22/22:

Found an additional issue while testing, logged here: #5690
