### ISSUE TITLE
Containment bugs

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#555]
<p>Testathon 4/23/15. </p> <p>Testing <a href="WTD-962" title="Objects can be put within objects not allowed to contain them" class="issue-link" data-issue-key="WTD-962"><del>WTD-962</del></a>, and was able to </p> <ul class="alternate" type="square"> <li>Create Layout, Folder and Panel within a Packet.</li> <li>Create an Activity Mode within a Layout.</li> <li>Create an Activity within a Layout.<br/> Note that all actions accomplished via the Create overlay Save In dialog.</li> </ul>

Migrated from: WTD-1133
Originally created: Thu, 23 Apr 2015 15:54:15 -0700
Updated: Thu, 14 Jan 2016 17:14:21 -0800

**Comment by charlesh88** [comment]
Still a problem!
