### ISSUE TITLE
Menus in Snow theme have no border

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#5556]
#### Summary
In snow theme the menus - create, 3-dot, context - are missing some border and drop shadow styling

#### Expected vs Current Behavior
Border and drop shadow

#### Steps to Reproduce
1. open browser console
2. use `openmct.install(openmct.plugins.Snow())` and `openmct.install(openmct.plugins.Espresso())` to toggle themes
3. compare menus (create, context, 3-dot) in Snow and Espresso themes

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by charlesh88** [comment]
### Testing Notes
1. In the Espresso theme, make sure that the Create menu and More Options (3 dot) menus flyouts all look as expected:

<img width="1711" alt="Screen Shot 2022-07-25 at 3 10 40 PM" src="https://user-images.githubusercontent.com/1056412/180882411-28c722ef-16ac-4e05-9da5-ea9504b1405a.png">

2. Switch the Snow theme, make sure that a drop shadow appears beneath menus and hovering over a menu item shows both text and icon in a light color. The theme can be changed on-the-fly or remotely by entering this command in the browser console: 
`openmct.install(openmct.plugins.Snow())`

<img width="1711" alt="Screen Shot 2022-07-25 at 2 38 41 PM" src="https://user-images.githubusercontent.com/1056412/180878466-ad866959-7563-43ec-89a3-b1bf239ef6d1.png">

**Comment by michaelrogers** [comment]
This fix is verified during testathon 08/04/2022. Border and drop shadow styling is present for context menus in the MCT tree, three dot menu, and inspector time bounds overlays.
