### ISSUE TITLE
[Plot] Add step-forward control

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#556]
<p>Add a "step forward" control to the Plot view which allows stepping forward through pan/zoom history (similar to the behavior of the existing "step back" control.)</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1136
Originally created: Sun, 26 Apr 2015 10:57:05 -0700
Updated: Thu, 14 Jan 2016 16:32:38 -0800

**Comment by larkin** [comment]
I believe this is not necessary given that a user can simply recreate the previous zoom or pan action.  Closing as wontfix.
