### ISSUE TITLE
Remote changes to notebooks not being reflected in real-time

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#5562]
#### Summary
AKA "multi-user notebook doesn't work any more".

#### Expected vs Current Behavior
When multiple users are viewing a notebook, changes by one users should be automatically reflected in other user's views. For example, when one user adds a new entry, all users viewing that page should see that entry appear automatically. This used to work but it appears that [a recent code change](https://github.com/nasa/openmct/commit/3c70cf1767a35a6c72c939611e986d6b1f20db8f#diff-65eecdb132430c1ee14c1f6be3551e25a5e64cec0b7370c7d19b47472101d259L203) has introduced a regression here.

#### Steps to Reproduce
1. Using an instance of Open MCT with Couch DB as the persistence backend
2. Open a notebook in Firefox (or Safari)
3. Open the same notebook in Chrome. It's important to use two different browsers as the Couch synchronization uses a shared worker to reduce the number of server connections we are holding open.
4. Add a new entry in Firefox.
5. Observe that the new entry does not automatically appear in Chrome.

#### Environment
* Open MCT Version: c10e9ad14c1040746b7cf08ae9a9c6a9172c5e72
* Deployment Type: VIPER test and local dev with Couch DB enabled

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by akhenry** [comment]
# Test Instructions
1. Execute reproduction steps above and verify that remote changes to notebook entries are automatically reflect
2. Add and remove tags and verify that changes are automatically reflected for other users (using the same two browser method from step 1.

**Comment by jvigliotta** [comment]
Verified Fixed: Testathon 8/2/22

**Comment by ozyx** [comment]
Verified Testathon 8/2/22:

I was able to create entries on Chrome and Firefox instances and they appeared in the other, synchronized. Edits, and deletes were also reflected across browser instances.

**Comment by akhenry** [comment]
Reopening, this regression was again observed in recent demo of 2.0.7

**Comment by jvigliotta** [comment]
Was unable to replicate this issue again, needs retesting.

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon 9/12/22 (Without Tags, will update, with tags)
