### ISSUE TITLE
Borders in Layout overlapped

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#557]
<p>(Feedback from @slhale for testathon 6/25/2015)</p> <p>In layouts, sometimes borders which seem like they should be flush with each other overlap a little bit. </p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1378
Originally created: Thu, 25 Jun 2015 17:22:54 -0700
Updated: Thu, 7 Jan 2016 13:54:17 -0800

**Comment by charlesh88** [comment]
Dupe of #427, closing.
