### ISSUE TITLE
Search should indicate in-progress and no results states

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#5572]
"Grand search" should indicate to the user when a search in in progress, and when it hasn't found any results. This is important for use in upcoming sims which are getting access to this early.

**Searching for a non-findable string**
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/1056412/181609928-529c0bd9-edd5-42c1-8a19-57c96253a19b.png">

**Comment by rukmini-bose** [comment]
Proposed design for this issue: 
(1) Progress bar when search is in progress
![Loading Bar](https://user-images.githubusercontent.com/48999852/181611572-d14ba5e5-7794-42b4-bf47-54eecabc929e.png)

(2) Indication of no search results. 
![No Results](https://user-images.githubusercontent.com/48999852/181611902-6398a670-5f3d-4532-a884-2e80f90cd008.png)

**Comment by rukmini-bose** [comment]
Proposed design for the issue: 
(1) Progress bar when a search query is in progress: 
![Loading Bar](https://user-images.githubusercontent.com/48999852/181614739-c092ef22-2ba3-41fd-bb06-5ddbfcdfaddf.png)

(2) Message indicating no search results being found: 
![No Results](https://user-images.githubusercontent.com/48999852/181614799-d98bc102-1aaa-4f0a-83a6-85f761198dc4.png)

**Comment by scottbell** [comment]
@rukmini-bose regarding progress bar, we don’t know a priori how long or how much their to search necessarily. We can make a progress bar that creeps independently (e.g., 1-10s bar regardless of how long search will actually take). As an example, if the search actually takes 1s, and the bar is set to 10s, the bar will be a 10th of the way over when the search finishes.

**Comment by rukmini-bose** [comment]
@scottbell This is a great idea! Just a few clarifications: 

Would this mean that we would set a time limit to complete a search which depends on the type of search itself? In your example, it seems like 10 seconds would be the limit. But if a user were to search a keyword that is expected to display a large number of results, would the time limit be set to longer? 

And just to understand the flow, once the maximum time has been reached and no results were retrieved, would we expect to see the "No matching results" message? Please correct me if I am wrong.

**Comment by scottbell** [comment]
@rukmini-bose 
> Would this mean that we would set a time limit to complete a search which depends on the type of search itself? In your example, it seems like 10 seconds would be the limit. But if a user were to search a keyword that is expected to display a large number of results, would the time limit be set to longer?
No, the progress bar would reach 9/10ths and just sit there until the search finishes. As we don't know how long a search will take beforehand, the progress of the bar is independent of the search. It may better to use something similar to an "indeterminate progress bar" like they have in Material & iOS:
https://material.io/components/progress-indicators
https://developer.apple.com/design/human-interface-guidelines/components/status/progress-indicators/

> And just to understand the flow, once the maximum time has been reached and no results were retrieved, would we expect to see the "No matching results" message? Please correct me if I am wrong.
Yes, that would be correct.

**Comment by rukmini-bose** [comment]
> 

Ah, thank you for clarifying. I think that is the best way to go! Let's do that instead.

**Comment by scottbell** [comment]
@rukmini-bose need to add some tests, but here are some example interactions with fake lag:

https://user-images.githubusercontent.com/9853862/182591267-b86520eb-2fb7-447d-9d6a-8f22dae1f7c8.mov

**Comment by alizenguyen** [comment]
Verified Testathon 8/4/22

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon 8/4/22

**Comment by rukmini-bose** [comment]
Verified Testathon 8/4/22
