### ISSUE TITLE
[Build] Remove  maelstromTheme

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#5575]
#### Summary
We parameterized our visual tests to run in the espresso and snow theme. When asked about Maelstrom, @charlesh88 recommended that we just remove it.

This ticket captures the work necessary to remove it from our build

**Comment by vhenckel** [comment]
Hello. I don't understand if it's to remove it from the tests or remove the theme from the entire application.
Is this theme no longer used in the application?

**Comment by unlikelyzero** [comment]
@vhenckel hey! This is removing it from our css themes and the entire application. Are you currently using maelstrom theme?

**Comment by vhenckel** [comment]
https://github.com/nasa/openmct/pull/5600

**Comment by unlikelyzero** [comment]
### Testing Notes
Unable to see maelstrom in build

**Comment by shefalijoshi** [comment]
Verified Fixed.
