### ISSUE TITLE
[Plot] Add axis expansion button

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#559]
<p>Add button which can be used to expand axis boundaries to show out-of-bounds data in a plot, as shown in UI docs attached to <a href="https://trunk.arc.nasa.gov/jira/browse/WTD-868" title="UI for setting plot bounds in a plot view" class="issue-link" data-issue-key="WTD-868"><del>WTD-868</del></a>, p. 71.</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1142
Originally created: Sun, 26 Apr 2015 11:10:41 -0700
Updated: Thu, 14 Jan 2016 16:31:42 -0800

**Comment by charlesh88** [comment]
This would just reset the Y axis zoom to encompass all points to display, without affecting X axis zoom or pan. We should examine this requirement for desirability. Also, relates to #517, #971, #601.

**Comment by larkin** [comment]
Examining for desirability: by default the Y-axis will autoscale, users can enable/disable this as they please.  Do not believe a dedicated button is warranted.  

Closing.
