### ISSUE TITLE
[Object Tree] Handle targeting an orphaned object

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#5603]
#### Summary
Currently if you try to target an orphaned object in the object tree, it does nothing.

![Screen Shot 2022-08-03 at 1 12 32 PM](https://user-images.githubusercontent.com/12013460/182701250-58cd271a-da3c-4db3-a03c-dd1486bb5249.png)

#### Expected vs Current Behavior
If the item is orphaned, we need to not allow targeting, possibly dim the icon or remove it altogether?

#### Steps to Reproduce

1. Create an item
2. Remove the item
3. Search the removed (orphaned) item 
4. View it
5. Click the target button in the tree

#### Impact Check List

- [x] Data loss or misrepresented data? Kind of misrepresented data
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by scottbell** [comment]
As orphaned objects aren’t accessible via search anymore, this may be fixed?

**Comment by ozyx** [comment]
Verified fixed, Testathon 8/9/22

Created a clock and deleted it. Was not able to find it via search since it is now orphaned, thus cannot target it

**Comment by rukmini-bose** [comment]
Testathon Verified 8/9/22
