### ISSUE TITLE
Plans show incorrect start and end time in time list view

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#5605]
Originally reported in https://github.com/nasa/openmct/issues/5534

#### Summary
Day 1 Plan displays properly in this view
<img width="1005" alt="plan1" src="https://user-images.githubusercontent.com/4215777/182727059-649fd8d8-9491-4855-986f-7edb3a358d4a.png">

Day 1 Plan in Time List view: dates and to/froms are not displaying properly
<img width="1004" alt="plan2" src="https://user-images.githubusercontent.com/4215777/182727062-ad90087b-7fe7-4194-830a-b1368c5f84e0.png">

#### Steps to Reproduce

1. View a Plan with Time Conductor (TC) settings such that activities in the plan are in view. Confirm start dates and durations are correct or at least plausible.
2. Drag the plan into a Time List view with the same TC settings.
3. Observe that the starts and to/from values are not the same as in the Plan view.

#### Environment

* Open MCT Version: release/2.0.5
* Deployment Type: VIPER test

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by akhenry** [comment]
# Test instructions
1. Follow the reproduction steps in the original issue
2. Verify that the timestamps shown in the start and end columns are within the configure conductor range.

**Comment by unlikelyzero** [comment]
@charlesh88 to tackle

**Comment by charlesh88** [comment]
Verified fixed Testathon 8/22/22.
