### ISSUE TITLE
On new CouchDB install, "My Items" isn't being created

### ISSUE THREAD

**Issue by scottbell** [nasa/openmct#5606]
#### Summary
On a new CouchDB install, the first time OpenMCT connects to the CouchDB, it creates the `My Items` object to store new objects into. With the [recent CouchDB fixes for persistence errors](https://github.com/nasa/openmct/pull/5576), we're throwing an error before the plugin has a chance to load.

#### Expected vs Current Behavior
[Follow a new CouchDB install using the README](https://github.com/nasa/openmct/blob/master/src/plugins/persistence/couch/README.md), an administrator should be able to connect to a new CouchDB installation without issues.

#### Steps to Reproduce
1. [Following a new CouchDB install using the README](https://github.com/nasa/openmct/blob/master/src/plugins/persistence/couch/README.md) to create a new CouchDB installation.
2. Launch OpenMCT, ensure "My Items" is created and no errors are reported.

##### System:
 - OS: macOS 12.5
 - CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
 - Memory: 93.87 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
##### Binaries:
 - Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
 - npm: 6.14.17 - ~/.nvm/versions/node/v14.20.0/bin/npm
##### Browsers:
 - Chrome: 103.0.5060.134
 - Firefox: 103.0.1
 - Safari: 15.6

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information
This error:
```
GET http://localhost:5984/openmct/mine 404 (Object Not Found)
request @ CouchObjectProvider.js?9318:208
eval @ CouchObjectProvider.js?9318:336
Promise.then (async)
#deferBatchedGet @ CouchObjectProvider.js?9318:327
get @ CouchObjectProvider.js?9318:311
get @ ObjectAPI.js?99d1:219
migrate @ plugin.js?29a1:40
getMutable @ ObjectAPI.js?99d1:307
eval @ Browse.js?bb5e:118
pathToObjects @ Browse.js?bb5e:115
navigateToPath @ Browse.js?bb5e:67
eval @ Browse.js?bb5e:20
doPathChange @ ApplicationRouter.js?a65c:322
handleLocationChange @ ApplicationRouter.js?a65c:370
hashChaged @ ApplicationRouter.js?a65c:395
eval @ ApplicationRouter.js?a65c:230
eval @ location-bar.js?f420:213
any @ location-bar.js?f420:20
loadUrl @ location-bar.js?f420:211
start @ location-bar.js?f420:181
start @ ApplicationRouter.js?a65c:231
MCT.start @ MCT.js?b2c3:371
(anonymous) @ (index):202
```

occurs before the [myItemsInterceptor](https://github.com/nasa/openmct/blob/master/src/plugins/myItems/myItemsInterceptor.js#L39) has a chance to run:
```
invoke (myItemsInterceptor.js?7460:40)
(anonymous) (ObjectAPI.js?99d1:461)
applyGetInterceptors (ObjectAPI.js?99d1:460)
(anonymous) (ObjectAPI.js?99d1:222)
Promise.then (async)
get (ObjectAPI.js?99d1:219)
migrate (plugin.js?29a1:40)
getMutable (ObjectAPI.js?99d1:307)
eval (Browse.js?bb5e:118)
pathToObjects (Browse.js?bb5e:115)
navigateToPath (Browse.js?bb5e:67)
eval (Browse.js?bb5e:20)
doPathChange (ApplicationRouter.js?a65c:322)
handleLocationChange (ApplicationRouter.js?a65c:370)
hashChaged (ApplicationRouter.js?a65c:395)
eval (ApplicationRouter.js?a65c:230)
eval (location-bar.js?f420:213)
any (location-bar.js?f420:20)
loadUrl (location-bar.js?f420:211)
start (location-bar.js?f420:181)
start (ApplicationRouter.js?a65c:231)
MCT.start (MCT.js?b2c3:371)
(anonymous) ((index):202)
```

##### Workaround
Comment out the [throw in the CouchObjectProvider](https://github.com/nasa/openmct/blob/master/src/plugins/persistence/couch/CouchObjectProvider.js#L223).

**Comment by shefalijoshi** [comment]
This also results in the [MissingObjectInterceptor](https://github.com/nasa/openmct/blob/release/2.0.8/src/plugins/interceptors/missingObjectInterceptor.js) to not be called.

**Comment by unlikelyzero** [comment]
### Steps to Reproduce

1. [Following a new CouchDB install using the README](https://github.com/nasa/openmct/blob/master/src/plugins/persistence/couch/README.md) to create a new CouchDB installation.
2. Launch OpenMCT, ensure "My Items" is created and no errors are reported.

**Comment by khalidadil** [comment]
Verified on 08/22/22
