### ISSUE TITLE
notes field

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#561]
<p>activites and activity types both need notes fields once we have multiple users on the system. One example of the need is that if another user puts in a activity type for a certain subsystem at 80% duty cycle, that user will want me to know why the power numbers are lower than I might expect based on other knowledge of that subsystem.</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-461
Originally created: Thu, 2 Oct 2014 11:56:37 -0700
Updated: Thu, 7 Jan 2016 17:33:24 -0800

**Comment by charlesh88** [comment]
Covered by #1184 and #1194

**Comment by charlesh88** [comment]
Fixed, closing.
