### ISSUE TITLE
[Search] Plans don't show up in search results

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#5614]
#### Summary

Plan objects don't show up when searched for in the Grand Search

#### Expected vs Current Behavior

**Expected:** Plan objects should show up in the results when searched for in the grand search
**Current:** They don't

#### Steps to Reproduce

1. Go to an Open MCT instance with a Plan
2. Search for the plan name in the Grand Search
3. It doesn't show up in the search results

#### Environment

* Open MCT Version: 
```
Version: 2.0.7
Build Date: Thu Aug 04 2022 12:33:07 GMT-0700 (Pacific Daylight Time)
Revision: 15a0a872512556792cac6a8f8cd201a350222312
Branch: release/2.0.7
```
* Deployment Type:  Testathon
* OS: MacOS
* Browser: Chrome

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by scottbell** [comment]
@ozyx I'm having trouble replicating this locally with CouchDB

https://user-images.githubusercontent.com/9853862/183044407-7ab8d9e1-f045-4d54-96c9-6c144077bcc1.mov

**Comment by ozyx** [comment]
@scottbell 

This is actually a separate issue. The plan was not showing up in search on our test environment because the original object had been deleted. The plan I was searching for was actually a LINK to a deleted plan, which is non-removable (from the 'Plans') folder on our test env.

Closing.
