### ISSUE TITLE
'Save' on Edit Properties mutates objects multiple times for a single property change

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#5616]
#### Summary

Whenever the 'Save' (OK) button is clicked on the Edit Properties dialog, a separate mutation event is fired for each editable object property even if only for a single property change. This has performance and persistence implications when using an external persistence such as CouchDB. This also means that editing a single object property will cause multiple revisions of the object to register in CouchDB.

I believe this is ultimately leading to a lot of bugs related to editing properties (#5398, #5533 , partially #5138).

The behavior was modified in #4947, [here](https://github.com/nasa/openmct/pull/4947/files#diff-991629f1ca27c5648f9ed24ca4cd62675b30c5cc2e2e7c6776b548873f2b9189R70), to use multiple `mutate()` calls instead of a single `save()` so that observers could listen on specific property changes.

#### Expected vs Current Behavior

**Current:** On hitting 'Save' in the Edit Properties dialog, objects are mutated once for each editable property regardless of whether or not their values have changed.
**Expected:**
- If changes are made to one or more properties, a single mutation for the whole object should be performed.
- Mutation events for each of the modified properties should be fired off individually.

#### Steps to Reproduce

This is easiest to see while using CouchDB plugin.

1. Open an object's 'Edit Properties' dialog
2. Without changing anything, click 'OK' (Save)
3. In the Network tab, see that multiple unnecessary PUTs have been fired off.
4. Notice that with each PUT, the object in the request remains unchanged.

#### Environment

```
Version: 2.1.0-SNAPSHOT
Build Date: Thu Aug 04 2022 13:02:04 GMT-0700 (Pacific Daylight Time)
Revision: 36736eb8a041acd3893b3223cd8bc93a7d4299db
Branch: release/2.0.7
```

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [x] Does this have an impact on Performance?

**Comment by akhenry** [comment]
Good catch. There appear to be two issues here:
* The FormsAPI is reporting that every object property has changed, even when it hasn't.
    * I don't know what the root cause is here. Needs some investigation.
* Mutating each property separately is triggering a persistence event.
    * I think the correct way to handle this is to open a transaction before initiating the property updates.

**Comment by ozyx** [comment]
> * The FormsAPI is reporting that every object property has changed, even when it hasn't.

Edited this issue and split this one off into its own separate issue here: #5705

**Comment by khalidadil** [comment]
Tested by editing object properties and clicking "OK". I'm currently seeing only 1 PUT request on save. 

Verified Fixed in Testathon on 10/27/22
