### ISSUE TITLE
[Procedures] Fix column headers

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#562]
<p>Suggested by Scott, May 6 2015, would like to be able to see column headers remain fixed for procedures while viewing them. (Embedded procedures from Confluence have full tables which scroll, so by the time you're reasonably far along in the procedure, these headers are no longer visible.)</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1184
Originally created: Wed, 6 May 2015 11:07:57 -0700
Updated: Thu, 7 Jan 2016 17:17:32 -0800

**Comment by charlesh88** [comment]
This is really covered by #1481, closing as a dupe.
