### ISSUE TITLE
Default indicators should be re-sortable

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#5621]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when a default indicator cannot be sorted.

**Describe the solution you'd like**
Allow indicators I didn't install to be sorted.

**Describe alternatives you've considered**
Order my indicators around the existing priorities (but I still wouldn't be able to order multiple default indicators).

**Additional context**
Useful for JPL installations.

**Testing Instructions**
1. open console browser and load openmct
2. run this command in the console,`openmct.indicators.getIndicatorObjectsByPriority()`
3. expand the list of indicator objects
4. mentally choose an indicator to reorder and run this command, `openmct.indicators.setPriority('{INDICATOR-KEY}', {INDICATOR-PRIORITY})`, where `{INDICATOR-KEY}` is the key string for the indicator and `{INDICATOR-PRIORITY}` is a priority that differs from the current indicator priority
5. run this command in the console, `openmct.indicators.getIndicatorObjectsByPriority()`
6. observer that the indicator priority has changed (the indicators do not actually visually reorder, since they are rendered in priority order on component mount only)

**Comment by unlikelyzero** [comment]
@davetsay are we going to backport this to openmct/master?

**Comment by davetsay** [comment]
@unlikelyzero there are two separate PRs linked to this issue. One is targetting `master`. One is targetting a JPL release branch.

**Comment by unlikelyzero** [comment]
@davetsay I think we are going to back out the current implementation and make a new master implementation

**Comment by davetsay** [comment]
Need new implementation in general to alter configurations for plugins installed by default
