### ISSUE TITLE
[Condition Sets] Cannot add Condition to Condition Set

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#5625]
#### Summary
Attempting to add a Condition to a new or pre-existing Condition Set doesn't add the Condition in the editor, and throws this console error:

<img width="573" alt="image" src="https://user-images.githubusercontent.com/1056412/183316022-9ce4597b-b70a-4a87-ae10-0cc8b069091a.png">

Saving and refreshing _will_ display the added Condition, but the Condition Set will not evaluate values and render output. This effects a key component and also results in loss of data, so setting as a blocker.

#### Expected vs Current Behavior
The Condition should have been added without any console errors and breaking the Condition Set.

#### Steps to Reproduce

1. Create a new Condition Set.
2. Display dev tools.
3. Click the Add Condition button. No other action (such as adding a data source) needs to be done to cause the issue.
**Observe**: no Condition is added, and a console error as shown above occurs.

#### Environment

* Open MCT Version:  R2.0.7
* Deployment Type:  /stable
* OS: MacOS
* Browser: Chrome

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by charlesh88** [comment]
8-8-22 3:17 PM: This problem appears to be isolated to 2.0.7.
- I can replicate this easily on /stable and /testathon in the 2.0.7 build.
- I can replicate this easily locally by building the release/2.0.7 branch.
- This problem does NOT happen running latest master locally with 2.1.0.

**Comment by unlikelyzero** [comment]
Retesting on 2.0.8 after backmerge

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 8/22

No issues adding new conditions.
