### ISSUE TITLE
Time list views should support following remote clock, not just wall clock

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#5629]
#### Summary
The time list view shows a time-ordered list of plan activities, with an indication of _now_ in the form of a vertical line.

The time list view should be enhanced to be able to follow a remote clock in order to support systems that use simulated time. This will be essential for using the time list view in VIPER simulations.

We need to think about how to approach this from an API perspective. Some outstanding questions:
1. Open MCT supports multiple clocks -so which one do we follow?
2. Right now clocks only tick when started (typically by selecting it from the time conductor). This enhancement implies the presence of an always ticking global clock to replace global wall-clock time.

**Comment by michaelrogers** [comment]
### How to test
* Navigate to a timelist
* Select fixed time
* Observe that all available events are shown irrespective of past, present, or future (this behavior should be consistent with clicking on edit mode)

**Comment by ozyx** [comment]
Testathon 9/15/22:

I noticed that in fixed time mode, if you edit the properties and hit 'save', those settings seem to override.

It's also a bit confusing visually if you set them all to "Don't Show" and then change time conductor mode to fixed time and they all show up. Is this intended?

https://user-images.githubusercontent.com/9259993/190522920-3839fa8f-184e-4620-a901-6a765dc7f8d5.mov

**Comment by shefalijoshi** [comment]
Verified partially fixed.
1. Navigate to a timelist view in local clock mode
2. Switch to fixed timespan - verify that all activities are shown
3. Refresh the browser
4. Observe that the timelist is empty, but all activities should be displayed instead.

**Comment by shefalijoshi** [comment]
Reopening this as it did not follow the remote clock, only the local clock

**Comment by ozyx** [comment]
Testathon 12/29/2022:

Verified fixed on both 2.1.5 and 2.1.4-ERT.

**Comment by shefalijoshi** [comment]
Reopening as this wasn't working for remote clock on banner.

**Comment by akhenry** [comment]
This was incorrectly verified fixed. It appears that the verification steps provided were for another issue.

**Comment by shefalijoshi** [comment]
Testing instructions:
1. Set the clock to 'Remote clock'.
2. Create a Timelist from the create menu
3. Drag a plan into the timelist and save it
4. Observe the start and end times and the duration - Ensure that the start and end times are in ISO format (if applicable)
5. Ensure that the duration calculation is correct when you subtract the start time from the current time.
6. Ensure that any activities in the current time range are shown as such.
7. Switch from Remote Clock to Local Clock.
8. Observe the start and end times and the duration.
9. Ensure that the duration calculation is correct when you subtract the start time from the current time.

**Comment by charlesh88** [comment]
Verified fixed Testathon 2023-03-30.
