### ISSUE TITLE
[Remove] Add confirmation dialog

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#563]
<p>Add warning dialog when the remove action is performed</p> <p>See UI docs attached to <a href="https://trunk.arc.nasa.gov/jira/browse/WTD-846" title="[Timeline] First implementation of new timeline design" class="issue-link" data-issue-key="WTD-846"><del>WTD-846</del></a>, p. 99</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-935
Originally created: Wed, 25 Feb 2015 13:16:32 -0800
Updated: Thu, 14 Jan 2016 16:41:44 -0800

**Comment by VWoeltjen** [comment]
Observed during training 9/28/2016 that the absence of a warning here was disconcerting

**Comment by charlesh88** [comment]
Keep running into this and it's a problem we really should fix. Adding this as a Help Wanted task.

**Comment by tobiasbrown** [comment]
Are there any specific requirements for this dialog?  Size, message, icons?

**Comment by charlesh88** [comment]
This would use the standard dialog service. Text should be along the lines of "Warning! This action will permanently remove this object. Are you sure you want to continue?" with Ok and Cancel buttons.
