### ISSUE TITLE
Notebook entries should use Time API, not Date.now()

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#5630]
Currently notebook entries are timestamped with wall clock time. In simulation environments the "now" time may not necessarily correspond to the real-world time, in which case the notebook entries should be timestamped with the simulated time.

**Comment by akhenry** [comment]
Related - https://github.com/nasa/openmct/issues/5629.

API change is probably needed to support a global clock.

**Comment by akhenry** [comment]
Clock indicator should also use Time API global clock, and not Date.now()

**Comment by unlikelyzero** [comment]
@akhenry before someone gets started on this one, let's identify what the final behavior is supposed to be. All of our visual tests are relying on Date.now() manipulation and we'd just like to make sure we understand what the final behavior will be

**Comment by unlikelyzero** [comment]
The tests no longer manipulate the clock

**Comment by jvigliotta** [comment]
## Testing
- go into "fixed" mode in the time conductor
- create a new entry in a notebook
- note that the entry timestamp seems correct
- if possible, use ANOTHER clock that is noticeably different from wall time
- repeat these steps

**Comment by akhenry** [comment]
Verified fixed. Looks good!
