### ISSUE TITLE
Clicking image thumb in Time Strip doesn't display selected image

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#5632]
#### Summary
Clicking on an Imagery image in the Time Strip view should display that image in the resulting large view, but doesn't. 

**Click image in RT**
<img width="1548" alt="Screen Shot 2022-08-08 at 2 32 04 PM" src="https://user-images.githubusercontent.com/1056412/183518406-16dc4b71-9ef3-4e0e-b58f-aa0576f3bc62.png">
**Resulting large view in RT**
<img width="1548" alt="Screen Shot 2022-08-08 at 2 32 10 PM" src="https://user-images.githubusercontent.com/1056412/183518501-c169c055-606b-428a-8e90-8c910d9a8972.png">
**Click image in Fixed**
<img width="1548" alt="Screen Shot 2022-08-08 at 2 30 06 PM" src="https://user-images.githubusercontent.com/1056412/183518420-a56b1811-aeeb-4e35-8a70-904bdab9110c.png">
**Resulting large view in Fixed**
<img width="1548" alt="Screen Shot 2022-08-08 at 2 30 16 PM" src="https://user-images.githubusercontent.com/1056412/183518417-aebb4661-808c-47c0-b29a-7744866c21a4.png">

#### Steps to Reproduce

1. Put an actual data product image source or Example Imagery into a Time Strip view and save it.
2. Get the Time Conductor such that imagery is in view in the Time Strip.
3. Click an image thumbnail.
**Observe**: no image is selected and displayed in the resulting large view overlay.
**Expected**: the selected image is selected and displayed in the resulting large view overlay.

#### Environment

* Open MCT Version:  R 2.0.7
* Deployment Type:  /stable
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by michaelrogers** [comment]
### How To Test

1. Put an actual data product image source or Example Imagery into a Time Strip view and save it.
1. Get the Time Conductor such that imagery is in view in the Time Strip.
1. Click an image thumbnail
1. the selected image is selected and displayed in the resulting large view overlay.

**Comment by rukmini-bose** [comment]
Verified Testathon 8/22/22 
Clicking an image thumbnail in a Time Strip view opens the image in Large View.
