### ISSUE TITLE
Unify syntax for forms/toolbars

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#564]
<p>Revise syntax for structures given to the mct-toolbar directive and the mct-form directive, such that both accept identical structures.</p> <p>This may probably as simple as changing "rows" to "items" in mct-form.</p> <p>Should continue to support "rows" (maybe in both cases?) for backward compatibility, perhaps with a deprecation warning.</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1154
Originally created: Tue, 28 Apr 2015 11:03:13 -0700
Updated: Thu, 14 Jan 2016 17:20:41 -0800

**Comment by charlesh88** [comment]
Is this still relevant given our move away from Angular?
