### ISSUE TITLE
[Notebook] Many network calls generated when a single entry is added

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#5641]
#### Summary
I was noticing that my tag notebook edits were taking a long time to apply in a larger notebook while accessing a viper deployment on the VPN. I opened up the network tab and saw the following

After creating a Notebook with 15 entries, entering the 16th and 17th entries causes
107 network requests which take 4 seconds to resolve.

#### Steps to Reproduce
1. Create a notebook with 15 entries
2. Click the 'To start a new entry, click here or drag and drop any object' to add a new entry (16)
3. Enter an entry name (test 16)
4. Repeat steps 2 and 3.
5. Hit [enter] key

#### Environment
* Open MCT Version: 2.0.7
* Deployment Type: viper/testathon

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [x] Does this have an impact on Performance?

#### Additional Information
![Screen Shot 2022-08-10 at 9 45 41 AM](https://user-images.githubusercontent.com/12446869/183968145-19eaaba4-2f4e-41c3-8ffa-a6202ca904e5.png)

**Comment by shefalijoshi** [comment]
The number of _find calls is equal to the number of entries. Annotations are updated for each entry with each network call.

**Comment by scottbell** [comment]
We could optimize this and look into asking for all tags for a notebook instead of per entry?

**Comment by shefalijoshi** [comment]
Yes, but there's also another issue - when a notebook get synced by CouchDB, the domain object get updated, which triggers a computation for annotationQuery (in NotebookEntry.vue) even if there is no change to the entry or tags.
This computation change then triggers another query to get tags. This is the real optimization we need to do. If there is no change in the entry/tags, we should not re-request tags for that entry.

**Comment by scottbell** [comment]
In that case, we’ll need a way to know that tags haven’t changed.

**Comment by scottbell** [comment]
I've reduced this to 6 network calls/

**Comment by ozyx** [comment]
Closed by #5763

**Comment by ozyx** [comment]
Verified Testathon 09/30/22:

- Only 2 network requests each were generated when adding entry 16 and entry 17

**Comment by unlikelyzero** [comment]
Please retest with notebook tagging

**Comment by ozyx** [comment]
Need better verification instructions before we sign off on this. Testing notes:

Testathon 10/4/22:

Seeing 9 requests per tag. Seems to be the same number no matter how many entries or tags are present on the notebook page.

**Comment by akhenry** [comment]
@scottbell What would constitute verification of this fix? how many requests should we now expect?

**Comment by scottbell** [comment]
Per the e2e tests, 9-12 sounds about right:
https://github.com/nasa/openmct/blob/master/e2e/tests/functional/plugins/notebook/notebookWithCouchDB.e2e.spec.js#L83
the main thing to test is that it’s not increasing per entry as it once was.

**Comment by akhenry** [comment]
@ozyx

**Comment by ozyx** [comment]
Verified Testathon 10/6/22.

Adding entries and tags always makes the same number of requests. ~2 for adding/removing entries, and ~9 for adding tags, ~4 for removing tags.. The number of network requests does NOT increase as the number of entries / tags increase.
