### ISSUE TITLE
Cancel any outstanding requests for annotations when navigatating away from a Notebook

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#5646]
**Is your feature request related to a problem? Please describe.**
Notebooks can generate a lot of requests in order to discover annotations that might link to notebook entries. If these requests are still outstanding at the time that a user navigates away from a notebook they can block the application until the requests resolve.

**Describe the solution you'd like**
Navigating away from a notebook should cancel any outstanding annotation requests.

**Comment by ozyx** [comment]
# Testing Instructions

- Navigate to Open MCT (either locally and configured to use CouchDB, or on our shared testing environment)
- In DevTools, throttle the Network speed to 'Fast 3G'
- With the 'Network' DevTools tab open, navigate to a Plot of any kind
- Wait until you see a pending request to the `_find` endpoint for Couch, and then navigate away to a different domain object
- Verify that all `pending` requests for that endpoint have been aborted
- Repeat the same steps for a Notebook object with annotated entries, verifying that the pending requests cancel when navigating away to a different domain object.
