### ISSUE TITLE
Add user author attribution to objects

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#5656]
**Is your feature request related to a problem? Please describe.**
Current objects have a modified and a persisted time associated with them. We should also a user attribution to objects, as we now do with notebook entries.

**Describe the solution you'd like**
"createdBy" and "modifiedBy" fields could be added and automatically populated with the logged in user, if available.

**Comment by jvigliotta** [comment]
## Testing
- create an object (Folder, Notebook, Plot, etc) in an instance of Open MCT with a user provider and a logged in user
- select the object and look at the inspector to see if there are `createdBy` and `modifedBy` fields
- have another users edit the object in ANY way (name, properties, etc)
- verify that the `modifiedBy` field has been updated to the new user

**Comment by jvigliotta** [comment]
https://github.com/nasa/openmct/issues/5903 follow up for visual test

**Comment by michaelrogers** [comment]
Fix verified in testathon on 10/24/2022. If a object is modified, the change is correctly attributed to the user that last updated the domain object. When deleting the object, the user is properly navigated back to the parent.
