### ISSUE TITLE
[Plot] Add pin/unpin control

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#566]
<p>Add pin/unpin control to Plots, as shown in p 71 of UI docs attached to <a href="https://trunk.arc.nasa.gov/jira/browse/WTD-868" title="UI for setting plot bounds in a plot view" class="issue-link" data-issue-key="WTD-868"><del>WTD-868</del></a>, bullet 3. When pinned, a plot's domain axis should not change to fit incoming data.</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1138
Originally created: Sun, 26 Apr 2015 11:03:01 -0700
Updated: Thu, 14 Jan 2016 16:32:17 -0800

**Comment by larkin** [comment]
There are similar options available when the time conductor is running in real-time: a simple pan will lock, and then the history stack allows resuming.

Closing as wontfix, can review at later date as desired.
