### ISSUE TITLE
[Playwright] Visual Test Run Error

### ISSUE THREAD

**Issue by khalidadil** [nasa/openmct#5675]
#### Summary
When running some visual tests in playwright, I'm seeing the following error in the trace:
[.WebGL-0x14c00ef71500]GL Driver Message (OpenGL, Performance, GL_CLOSE_PATH_NV, High): GPU stall due to ReadPixels

#### Environment
* Open MCT Version: release/2.0.8

#### Impact Check List
- [ ] Data loss or misrepresented data?
- [X] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [x] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information
The trace can be downloaded here:
https://output.circle-artifacts.com/output/job/18ad2da8-3558-45f8-9c44-38312e1caa3b/artifacts/0/html-test-results/index.html#?testId=d279fc8d3f4cde14bba527479849ef64c4735aaf-b22c1c271bdc95da467866b0461194a12ec27867

**Comment by unlikelyzero** [comment]
[0f475ab4ed112be985a20681c5142a42f3b57906.zip](https://github.com/nasa/openmct/files/9374620/0f475ab4ed112be985a20681c5142a42f3b57906.zip)

**Comment by unlikelyzero** [comment]
Cannot reproduce
