### ISSUE TITLE
[Notebook] Delete Page PopUp Does Not Go Away

### ISSUE THREAD

**Issue by khalidadil** [nasa/openmct#5679]
#### Summary
This has been copied from VIPEROMCT-160:
When clicked on the Shift Log for 20220729, the Delete Page popup appeared. When I subsequently clicked elsewhere it remained. Performed the following to try to clear it, which all failed:

Making a shift log entry
Switching to different days and different shifts
Navigating away to a different screen/layout
Refreshing the browser did clear it. And could not get the popup to stick.

Note from Khalid:
I was unable to get the delete popup to display while clicking a notebook page, but I was able to reproduce this while clicking the dropdown next to a notebook page twice. In this case the popup persists as described and nothing can be done to close it other than refreshing the page.

#### Steps to Reproduce
1. Go to a notebook and create a section and a page if none exist.
2. Click on the dropdown arrow next to a notebook page. The "Delete Page" dropdown should open.
3. Click on the dropdown arrow next to the same notebook page again (avoiding clicking on the "Delete Page" dropdown).
4. The dropdown will now persist despite trying to click elsewhere and there should be an error in the log.

#### Environment
* Open MCT Version: release/2.0.8
* OS: MacOS
* Browser: Chrome

#### Impact Check List
- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [X] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information
https://user-images.githubusercontent.com/2343076/185431129-182fa463-6433-4d9d-9014-17fb9691ea0d.mov

**Comment by unlikelyzero** [comment]
Will need to address https://github.com/nasa/openmct/issues/5713 in a follow up

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon 9/12/22

**Comment by michaelrogers** [comment]
Fix verified during testathon 09/12/2022.

**Comment by rukmini-bose** [comment]
Verified Testathon 9/12/2022
