### ISSUE TITLE
[Persistence] Don't poll to update indicator

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#568]
<p>ElasticSearch persistence indicator currently polls to verify the availability of ElasticSearch. Would instead prefer to change status only when connections succeed or fail, something like:</p> <ul class="alternate" type="square"> <li>OK: A request has succeeded in the last N seconds</li> <li>Unavailable: A request has failed in the last N seconds</li> <li>Idle: No requests attempted in the last N seconds</li> </ul> <p>Need to consider the value for N carefully. Unavailable should take priority over OK (and maybe should stick around until the user acknowledges it?)</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1492
Originally created: Wed, 29 Jul 2015 14:02:46 -0700
Updated: Thu, 14 Jan 2016 17:07:05 -0800

**Comment by larkin** [comment]
Think this is okay as currently implemented.  wontfix for now.
