### ISSUE TITLE
Unhandled TypeError when creating an object within a Flexible Layout

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#5682]
#### Summary

Errors are thrown when creating an object within a Flexible Layout (but not when dragging and dropping the same object into the layout).

```
[Vue warn]: Error in beforeDestroy hook: "TypeError: Cannot read properties of undefined (reading 'isMutable')"

found in

---> <FrameComponent> at src/plugins/flexibleLayout/components/frame.vue
       <ContainerComponent> at src/plugins/flexibleLayout/components/container.vue
         <FlexibleLayoutComponent> at src/plugins/flexibleLayout/components/flexibleLayout.vue
           <Root>
```
```
vue.js?7193:1906 TypeError: Cannot read properties of undefined (reading 'isMutable')
    at VueComponent.beforeDestroy (frame.vue?5a0c:115:1)
    at invokeWithErrorHandling (vue.js?7193:1872:1)
    at callHook (vue.js?7193:4236:1)
    at Vue.$destroy (vue.js?7193:3994:1)
    at destroy (vue.js?7193:3185:1)
    at invokeDestroyHook (vue.js?7193:6153:61)
    at invokeDestroyHook (vue.js?7193:6158:1)
    at invokeDestroyHook (vue.js?7193:6158:1)
    at VueComponent.patch [as __patch__] (vue.js?7193:6504:32)
    at Vue.$destroy (vue.js?7193:4017:1)
```

#### Steps to Reproduce

1. Create a Flexible Layout
2. Save and Finish Editing (exit edit mode)
3. With the Flexible Layout still in focus, create any other embeddable object (Clock for example)
4. Observe TypeErrors in the console

#### Environment

```
Version: 2.0.8
Build Date: Thu Aug 18 2022 15:19:05 GMT-0700 (Pacific Daylight Time)
Revision: d162b5dbd878e72750d6275c799bb31094003dec
Branch: release/2.0.8
```

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [x] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment]
Related, possibly duplicate of this issue: https://github.com/nasa/openmct/issues/3660

**Comment by rukmini-bose** [comment]
Verified Testathon 9/15. Do not see any error messages in the console.

**Comment by ozyx** [comment]
Verified Testathon 9/15

Followed steps above, did not see any console errors.

**Comment by khalidadil** [comment]
LGTM! Verified Fixed in Testathon on 09/15/22
