### ISSUE TITLE
[Grand Search] Duplicate search results when using CouchDB

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#5690]
#### Summary

Seeing duplicate search results when using CouchDB as persistence store. Both duplicates navigate to the correct object.

#### Steps to Reproduce

1. Start a fresh Open MCT instance with CouchDB plugin as persistence store
2. Create a uniquely named object
3. Search for it in the Grand Search
4. Notice two duplicate search entries appear

#### Environment

Seen locally and in live test environment
```
Version: 2.0.8
Build Date: Mon Aug 22 2022 15:05:20 GMT-0700 (Pacific Daylight Time)
Revision: 06b321588ecef292730f671e5fb850b7b5e1e6ab
Branch: release/2.0.8
```

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information

![image](https://user-images.githubusercontent.com/9259993/186027954-d8fb0e37-b40b-4517-97c4-f5c1f584ed05.png)

**Comment by ozyx** [comment]
Regression of #4667

**Comment by shefalijoshi** [comment]
Initial investigation, root cause:
It appears that when searching,
1. The CouchObject provider AND the in-memory search provider support searching for 'OBJECTS'. See: https://github.com/nasa/openmct/blob/master/src/api/objects/ObjectAPI.js#L282
2. They both return results when searching for a given string
3. The results are then flattened and displayed as duplicate results

**Comment by ozyx** [comment]
## Testing Instructions

- Create an object. Name it uniquely using a [generated uuid](https://www.uuidgenerator.net/version4)
- Search for it in the grand search
- Verify that there is only a single search result

**Comment by jvigliotta** [comment]
Verified Fixed: Testathon 8/23

No more dupes

**Comment by unlikelyzero** [comment]
Verified
