### ISSUE TITLE
[Plot] Plot should pin during marquee zoom

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#570]
<p>Initiate a marquee zoom on a plot with live data (e.g. sine wave generator), but do not complete the zoom (click, drag, hold). Observe that the grayish selection box moves with the data.</p> <p>Desired behavior is that the selection box remains in the pixel positions that the user selected. But, desired behavior is also that the selection box remains at the value/time positions the user selected (the user positioned the drag based on the value/time that was there, not based on what was going to be there) - it is not useful to have data continue to flow "underneath" a selection rectangle.</p> <p>To achieve this, plot axis bounds should pin (instead of changing to accommodate new data) as soon as the user initiates the drag. Plot should presumably stay pinned once the zoom is completed (although there may need to be edge cases which deviate from this - should plot stay pinned if the new bounds include now?)</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-343
Originally created: Fri, 5 Sep 2014 10:15:19 -0700
Updated: Thu, 14 Jan 2016 17:14:08 -0800

**Comment by larkin** [comment]
I believe the current behavior is as desired: the coordinates of the marquee are fixed to the underlying data.  Given the uncertainty about the behaviors above, don't believe that immediate disconnect from time conductor on drag start is necessary.  Closing as wontfix.
