### ISSUE TITLE
Notebook should use the Menu API for context menus

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#5713]
The Notebook object has a number of context menus which look and feel like menus generated from the Menu API, but are really generated by a [PopupMenu component exclusive to the Notebook](https://github.com/nasa/openmct/blob/0f12aa1eaebe25bee0daed039ac45e083ce637f4/src/plugins/notebook/components/PopupMenu.vue), whose existence predates the Menu API.

The Notebook should be updated to use the Menu API to help ensure consistent context menu behavior across the application.

**Comment by unlikelyzero** [comment]
https://github.com/nasa/openmct/blob/0f12aa1eaebe25bee0daed039ac45e083ce637f4/src/api/menu/menu.js#L60

**Comment by khalidadil** [comment]
The delete section/page menus look and work as expected. Verified in Testathon on 07/21/23
