### ISSUE TITLE
[Flexible Layout][Import/Export] Embedded tab view lost when exporting flexible layout

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#5715]
#### Summary

A flexible layout with an embedded tab view was exported. After importing the flexible layout the embedded tabbed view entirely absent and showing as a missing object.

#### Expected vs Current Behavior
All items should be exported and imported correctly.

#### Steps to Reproduce

1. Create a flexible layout with some items (Notebook, etc) and a Tab View
2. Export the flexible layout.
3. Import the flexible layout to another folder.
4. Note tab view is gone.

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by jvigliotta** [comment]
Unable to replicate this, locally with local storage and on two different instances of Open MCT with couch.

## Testing
- Follow the steps to reproduce above

**Comment by ozyx** [comment]
Verified 9/12/22 Testathon

Was able to export / import flexible layout w/ multiple tabs views and other items embedded without issue
