### ISSUE TITLE
Add icon loader

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#572]
<p>Add an icon loader service which automatically populates the head with link rel="icon" for various permutations described in bundles. Should make it simple for different deployments to override icons added.</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-738
Originally created: Tue, 27 Jan 2015 14:36:49 -0800
Updated: Thu, 14 Jan 2016 17:24:44 -0800

**Comment by larkin** [comment]
Wontfix.  Deployment specific.
