### ISSUE TITLE
Synchronization for new tags on notebook entries

### ISSUE THREAD

**Issue by scottbell** [nasa/openmct#5734]
**Is your feature request related to a problem? Please describe.**
Currently we don't have a way to know that an annotation has been created for a particular domain object when using a persistence store like CouchDB. Because of this, users watching remote notebooks aren't notified when new tags are created.

**Describe the solution you'd like**
Per a discussion with @akhenry, create a new field called `annotationModified` for domain objects. UIs can observe this field, and when the field changes, they can initiate a search for the new annotation.

**Describe alternatives you've considered**

- add `include_docs` to include JSON of new items over the [CouchDB change feed](https://docs.couchdb.org/en/3.2.0/api/database/changes.html) - means more traffic per client
- add a new SharedWorker that opens a separate connection to CouchDB. It would use a [special _selector filter](https://docs.couchdb.org/en/3.2.0/api/database/changes.html#filtering) to reduce traffic from :point_up_2:. We’d need to use `feed=continuous` (or `longpoll`) though as SSEs can’t take a selector.

**Additional context**
Note the existing CouchDB change feed only gives a `keystring`, which means if we need to know a particular annotation has been created for a particular domain object, we’ll need to lookup each new object in the change feed in full - expensive!

**Comment by scottbell** [comment]
Testing instructions:

- Open two browser implementations (e.g., Firefox & Chrome)
- Point them both to the same OpenMCT instance running CouchDB as its persistence store
- Create a new notebook and navigate to this using both browsers
- Create an entry in Firefox, observe it appears in Chrome "live"
- Create a tag in Firefox for the entry, observe the tag appear in Chrome "live"
- Delete the tag in Firefox, then add all the tags in Firefox, observe the tags delete and reappear in Chrome "live"

**Comment by jvigliotta** [comment]
Tested with Rukmini and I was able to see tags populating live, but unable to test with FF due to cert issue.

**Comment by unlikelyzero** [comment]
@ozyx to finalize with safari 16

**Comment by ozyx** [comment]
Verified with Safari 16 / Chrome stable. Testathon 09/30/22

Was able to create entry on chrome and see it on safari and vice versa. Was able to add a tag to the entry on chrome and see it on safari and vice versa.
