### ISSUE TITLE
Notebook should not check edit state, should instead check if transaction is active

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#5747]
#### Summary
The notebook uses transactions in order to batch multiple mutations into a single persistence event. Currently [it uses a check to `openmct.editor.isEditing()`](https://github.com/nasa/openmct/blob/60f20c64d5250c9ea3915412b177861b11c7a2ed/src/plugins/notebook/components/Notebook.vue#L858) to determine whether a transaction is already active. Transactions and edit mode are related but separate concepts, and in this case we don't really care whether or not edit mode is active, we only care whether a transaction is active.

Since we are starting a transaction, we should instead check `openmct.objects.isTransactionActive()`. Currently this function contains a bug however and also [checks whether edit mode is active](https://github.com/nasa/openmct/blob/60f20c64d5250c9ea3915412b177861b11c7a2ed/src/api/objects/ObjectAPI.js#L639). If this code has not already been fixed by the time this issue is addressed then `isTransactionActive` should also be modified to remove the edit mode check.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [X] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by akhenry** [comment]
### Testing Instructions

This touches notebook persistence code, so some general regression testing should be performed there

Note that there is currently [a known issue with multi-user notebook conflict resolution](https://github.com/nasa/openmct/issues/5921).

Confirm that the following can be done without errors:

1. Creating a notebook entry
2. Editing a notebook entry
3. Deleting a notebook entry
4. Adding a new page
5. Renaming a page
6. Adding a new section
7. Renaming a section

**Comment by michaelrogers** [comment]
Fix verified during testathon on 10/15/2022.
