### ISSUE TITLE
[Framework] Newly instantiated objects should be able to be contextualized

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#575]
Currently, objects created via the InstantiationCapability are not able to be contextualized. This affects how they are handled by some capabilities such as `CompositionCapability` that contextualize objects.

Newly instantiated objects cannot be contextualized 'at birth' because they do not have a context. However, contextualization could take place prior to persistence when composition takes place. At this point, a context can be established. Indeed, the `CompositionCapability` does perform contextualization, but fails with nascent objects because it relies on an object lookup to the ObjectService, which fails. 

One possibility here is to add an ObjectProvider that keeps a pool of nascent objects. The problem with this is lifecycle. When would objects be removed from the pool? The provider could listen for persist events and remove at that point, but objects that are discarded and never persisted would linger around indefinitely. 

A solution might be to use the `EditableDomainObjectCache`, which is scoped to the lifetime of an edit session, however my feeling is that nascent objects should be considered the same as persisted objects by the application, without needing special handling via `EditableDomainObject`s

**Comment by VWoeltjen** [comment]
Addressed in the context of #1342. 

__For testing,__ this is a refactor testing should be for regressions instead of verifying new behavior. Look for console errors, or aberrant behavior around "context" (the objects which contain an object.) For example, linked/unlinked icons, the Remove action, and Move/Duplicate/Link all depend upon "context" in this sense.

**Comment by charlesh88** [comment]
Testathon 2017/04/20 No weird regressions observed.

**Comment by larkin** [comment]
Removing unverified based on testathon evidence that this works. (no one found other bugs)
