### ISSUE TITLE
Was able to drag parent folder into child folder

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#576]
<p>In today's testathon.</p> <p>Steps:</p> <p>Under the Testathon Folder, I highlighted folder 'C', which was a child of the folder "Pete".<br/> In the tree, I grabbed "Pete" and dragged and dropped it into 'C'</p> <p>I was allowed to do this, meaning I dragged a parent folder into its child folder, making the child the parent of its own parent. </p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1253
Originally created: Thu, 11 Jun 2015 15:59:01 -0700
Updated: Thu, 14 Jan 2016 16:01:31 -0800

**Comment by VWoeltjen** [comment]
Migrated comment, from @VWoeltjen:
<blockquote>
<p>We should solve this with a composition policy that prevents cycles. There may be valid use cases for cycles in the domain object hierarchy, but we don't know them, and we do know of several cases where cycles are confusing (to say the least)</p> <p>Addressing this with a composition policy specific to cycles will permit us to change this decision later at minimal cost</p>
</blockquote>

**Comment by charlesh88** [comment]
@VWoeltjen Is there actually a functional problem here? The action just creates a link to the parent. Unless this creates a paradox that will destroy the space-time continuum (or for-real create object persistence problems) I don't feel the need to fix this.

**Comment by larkin** [comment]
Feel that this is a wontfix, closing.
