### ISSUE TITLE
[Timelist] Follow up from 5629

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#5772]
#### Summary

    Navigate to a timelist view in local clock mode with the following filters in the inspector:
    
<img width="196" alt="image" src="https://user-images.githubusercontent.com/5247066/199108668-f41a6975-cbdc-4bb9-9f83-bf70ebcc6f0e.png">

    Switch to fixed timespan - verify that all activities are shown
    Refresh the browser
    Observe that the timelist is empty, expectation is that all activities should be displayed.

https://github.com/nasa/openmct/issues/5629#issuecomment-1248733293

#### Expected vs Current Behavior
Timelist is empty when in Fixed timespan mode, expectation is that all activities should be displayed.

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by michaelrogers** [comment]
@shefalijoshi - When testing locally against the latest master I am not seeing this behavior when following the reproduction steps above. Even with a hard refresh, the fixed time view still displays all activities.

**Comment by michaelrogers** [comment]
### How to test
1. Create a Timelist or naviagate to an existing one
2. Create a Plan and upload an appropriate JSON activities
3. Change Time Conductor to fixed time
4. Observe that the full list of activities being displayed (just like in edit mode)
5. Refresh the page
6. Observe that the list remains the same length

**Comment by michaelrogers** [comment]
Referencing from an [attached PR](https://github.com/nasa/openmct/pull/5957) to document the change in direction for how fixed time is handled. 

> @charlesh88 talking with @shefalijoshi 2023-01-30: Here's the new thinking about the solution, thanks to Shefali: given that the Time List View uses its own timeframe settings (show future, current, past events) and effectively ignores the Time Conductor's bounds, in Fixed Time mode we should temporarily use the Start datetime as "now" for the Time List view (TLV). This allows the TLV to have a meaningful view in Fixed Time mode, and honors the overall model of how the TC governs time, and how the TLV works. In the future when we separate out clock (local, remote) from time span handling (real-time, fixed time) the TLV can be augmented to use the remote clock's "now" instead of having to rely on the TC's Start datetime.
> 
> Implementation questions should be addressed to Shefali.

**Comment by michaelrogers** [comment]
## How to test
[plan.json.txt](https://github.com/nasa/openmct/files/11772785/plan.json.txt)

Setup
1. Create a Timelist view
2. Create a Plan and upload a plan.json (use attached .json by removing txt extension)
3. Return to the Timelist view and drag the newly created plan

Testing
1. Start in Local Clock mode
2. Switch to `Fixed Time` mode
3. Observe that only activities that fit within the Fixed Times time bounds are shown and not necessarily all activities
4. Adjust time bounds to include or exclude more activities
5. Observe these are now correctly visible in the Timelist view

Bonus: Regression test realtime mode (remote/local clock)

**Comment by akhenry** [comment]
In testing this is didn't work with real plans. Will send a video.

**Comment by shefalijoshi** [comment]
Looks ok. Current activities that start _before_ the current fixed time span start time do show up, I'm on the fence about this.
![image](https://github.com/nasa/openmct/assets/5247066/2cc88afa-a5e2-4b01-9c15-0e38c54c8710)

**Comment by charlesh88** [comment]
Testathon 2023-07-25 verified fixed.
