### ISSUE TITLE
Global clock

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#5773]
**Is your feature request related to a problem? Please describe.**
Open MCT should provide a clock that is always ticking, irrespective of time conductor mode, to provide a canonical time value for "now". Many plugins need to know what the current time is according to the configured time system and clock, even if the time conductor is in "fixed" mode.

eg. Displays such as the time list view which display a moving "now" line relative to scheduled activities in the past and future.

`Date.now()` cannot be used for this purpose because Open MCT must support simulated times in the past and future, as well as non-terrestrial time systems.

**Describe the solution you'd like**
#### Stage 1: Separate the selection of "mode" from the selection of the "clock"
1. Modify the time conductor UI to add a "mode" drop-down that selects between fixed and real-time modes. A drop-down for selecting the clock will be maintained, however the "fixed" option will be removed from it, as this is now selected via the "mode". 
2. Selecting "real-time" mode from the drop-down will set the active clock to the one that is currently selected in the "clock" drop-down. Selecting "fixed" mode will unset it. The conductor is already doing this, but with a single drop-down instead.

#### Stage 2: Add API support for a canonical Open MCT clock
1. Modify the Time API to add a `mode()` getter/setter to time contexts. Setting the `mode` to `real-time` will start the configured clock, and cause the conductor's time context to automatically follow that clock, automatically updating the bounds as it currently does when following a clock. Setting the `mode` to `fixed` ~will stop the currently configured clock~.
2. Modify the Time API so that when a clock is set via the `clock()` setter that clock is also immediately started. The time context will only follow the clock if the `mode` is set to "real-time".

#### Stage 4: Modify Notebook entry timestamps to use the Open MCT clock instead of the wall clock.

** Open Questions**

* What about object timestamps? I suspect we still want to use `Date.now()` for this. Although it might cause some user confusion, we need to know the wall-clock time that objects were created and modified for various API-internal reasons.

**Comment by shefalijoshi** [comment]
From initial discussions, and in the interest of maintaining backwards compatibility, we will retain (and deprecate) the existing time API methods - `clock(), timeSystem(), bounds(), clockOffsets(), stopClock()` as well as events like `bounds`, `clock`, `clockOffsets`, `timeSystem`.
A new set of getters and setters will be implemented to enhance the Time API as follows:
**Events**
`clockChanged` - emitted when ticking clock changes
`modeChanged` - fixed / realtime mode
`boundsChanged` - emitted once for fixed mode and for every tick in realtime mode
`clockOffsetsChanged` - emitted when the clock offsets change.
`tick` - always emitted with the current timestamp value

**Methods**
```
getClock
setClock

getBounds
setBounds

getTimeSystem
setTimeSystem

getClockOffsets
setClockOffsets
```

**Comment by jvigliotta** [comment]
I think we're going to also need an, `addClock` method that would let you add clocks but not set them UNLESS there is no already set clock.

**Comment by jvigliotta** [comment]
## Testing Clocks, Timers, Clock Indicator
- create clocks and timers
- verify they seem to be working correctly
- change the current clock to something noticeably different if possible (ex. future dates)
- see if the clocks and times are respecting these times
- check the clock indicator in the top of Open MCT and make sure it's working as expected

**Comment by rukmini-bose** [comment]
Issues found: https://github.com/nasa/openmct/issues/6811
