### ISSUE TITLE
Document one Open MCT API using TypeScript

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#5778]
#### Summary
Document one Open MCT API using TypeScript so that usage such as:
```
openmct.composition...
```
will result in detailed intellisense code completion in client code. The Composition API might be a good place to start because it is fairly simple, but also pretty useful.

The challenge, I suspect, will not be in annotating [the Composition API itself](https://github.com/nasa/openmct/blob/425e662d6e5c71e2b87dd4bf176f118ad281f6a4/src/api/composition/CompositionAPI.js) (which already has pretty good jsdocs) so much as annotating [MCT.js](https://github.com/nasa/openmct/blob/master/src/MCT.js) and [api.js](https://github.com/nasa/openmct/blob/master/src/api/api.js) such that calling `openmct.composition` works with intellisense.

You might look at what can be achieved through auto-generation from jsdocs - https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html

**Comment by 360macky** [comment]
> The challenge, I suspect, will not be in annotating [the Composition API itself](https://github.com/nasa/openmct/blob/425e662d6e5c71e2b87dd4bf176f118ad281f6a4/src/api/composition/CompositionAPI.js) (which already has pretty good jsdocs) so much as annotating [MCT.js](https://github.com/nasa/openmct/blob/master/src/MCT.js) and [api.js](https://github.com/nasa/openmct/blob/master/src/api/api.js) such that calling openmct.composition works with intellisense.

So is necessary to document with JSDocs all MTC.js to obtain intellisense for Composition API?

I am testing the type auto-generation command. It works pretty well with almost all files, and when it does the typing structure it returns properties with type `any`. I imagine that another challenge will be to create other types that fit those properties, for example:

```ts
export default class TelemetryCollection {
    /**
     * Creates a Telemetry Collection
     *
     * @param  {object} openmct - Openm MCT
     * @param  {object} domainObject - Domain Object to user for telemetry collection
     * @param  {object} options - Any options passed in for request/subscribe
     */
    constructor(openmct: object, domainObject: object, options: object);
    // ⬇️ Here...
    loaded: boolean;
    openmct: any;
    domainObject: any;
    boundedTelemetry: any[];
    futureBuffer: any[];
    parseTime: (datum: any) => any;
    metadata: any;
    unsubscribe: any;
    options: any;
    pageState: any;
    lastBounds: any;
    requestAbort: AbortController;
    isStrategyLatest: boolean;

```

I'm going to cite this #issue in a comment above my manual declaration of the types for the APIs I use in my Open MCT plugin.

**Comment by ozyx** [comment]
### Testing Instructions

1. Create a new project. `npm init`
2. Install openmct as a dependency: `npm i --save-dev nasa/openmct`
3. Create a `jsconfig.json` with this minimal configuration:

```json
{
  "compilerOptions": {
    "baseUrl": "./",
      "target": "es6",
      "checkJs": true,
      "moduleResolution": "node",
      "paths": {
        "openmct": ["node_modules/openmct/dist/openmct.d.ts"]
      }
  }
}
```

4. Create a new file, `app.js`
5. `import openmct from "openmct";` at the top of the file
6. Type in `openmct.` and verify that autocompletion hints show up with the entire first-level of public API suggested
7. Type in `openmct.composition.` and verify that the composition API is typed out sufficiently

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon 10/24/2022

Nice work!

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 10/24/22
