### ISSUE TITLE
Plans should show version if available

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#5782]
**Is your feature request related to a problem? Please describe.**
Plans should show version information in the inspector if it is available.
See VIPEROMCT-51

**Comment by unlikelyzero** [comment]
@shefalijoshi can you provide Plan Info testing notes

**Comment by charlesh88** [comment]
What the heck is this?! Cannot test in Testathon 10-04-22.

**Comment by shefalijoshi** [comment]
Testing instructions:
Expand the Viper Plans folder on banner
Click on any plan
Look for the Version property in the Open MCT Inspector properties

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon 10/27/2022

Plans with versions on the domain object (checked in network tab) will show them in the inspector when viewing.

**Comment by ozyx** [comment]
Fixed. Testathon 10/27/22

Plan version shows in the inspector
