### ISSUE TITLE
Elements pool should allow bucketing plot series into one of 3 Y Axes

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#5787]
**Is your feature request related to a problem? Please describe.**
All series of plots currently are assigned to only 1 y-axes. Enhance the elements pool to allow bucketing series into one of 3 y-axes.
Details of the design can be found here: https://trunk.arc.nasa.gov/confluence/display/VIPERMS/Multiple+Y-Axes+for+plots

**Describe the solution you'd like**
Ideally we should create a separate component for Plot related elements items in the elements pool so taht the generic treatment of elements in the pool is not affected.
Since the CompositionCollection.methods have no knowledge of the yAxis, consider saving the key of the series to the yAxisModel by listening for composition events within the Elements pool component.

Users should be allowed to choose which y-axes they want a series to be part of. 
Within a y-axis bucket, the user should be able to change the series that drives the y-axis.
https://github.com/nasa/openmct/blob/master/src/ui/inspector/ElementsPool.vue

**Default behavior:** The metadata value (yKey) that drives a given y-axis will be the first metadata value of the first series in the bucket.
**Customization:** The user can change the yKey to use for a given series as it does currently. 
https://github.com/nasa/openmct/blob/master/src/plugins/plot/axis/YAxis.vue#L38
If this is the series that is driving a given y-axis, then all the series in that y-axis bucket should update the yKey to the new metadata value chosen.

**Describe alternatives you've considered**
None

**Additional context**
This is the second step to getting multiple Y Axis into plots for Open MCT

**Comment by charlesh88** [comment]
Verified in Testathon 2023-08-22 for Open MCT 3.0.0
