### ISSUE TITLE
Visual treatment of multiple Y axes

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#5792]
**Is your feature request related to a problem? Please describe.**
Based on the design here: https://trunk.arc.nasa.gov/confluence/display/VIPERMS/Multiple+Y-Axes+for+plots
Allow showing/hiding Y axes, identifying Y axes on hover etc.

**Describe the solution you'd like**

- Layout changes to the yaxis to include color swatches and visibility toggle
- Show/Hide plots for a given y-axis

**Describe alternatives you've considered**
N/A

**Additional context**
This is step five of the Multiple Y axes implementation for Open MCT plots.

**Comment by unlikelyzero** [comment]
To Verify this:

1. Adding/Removing series to different Y axis buckets requires navigating away and back to the overlay plot.
2. Add a visibility toggle to the y-axis
3. Add color swatches to indicate which series are part of the y axis (no hover interaction is done for MVP)

**Comment by charlesh88** [comment]
Verified fixed Testathon 2023-01-31.
