### ISSUE TITLE
Condition Widget text alignment is broken

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#5799]
#### Summary
When a Condition Widget added to a layout 

![Screen Shot 2022-09-21 at 4 05 17 PM](https://user-images.githubusercontent.com/1056412/191625571-e89dbd4b-b2fc-4110-a38f-4d382b38a264.png)

is not of sufficient width to display it's label, the text is not wrapping as intended:

![Screen Shot 2022-09-21 at 4 05 26 PM](https://user-images.githubusercontent.com/1056412/191625601-614c1863-e103-4e3e-8947-e0ab872418e1.png)

#### Expected vs Current Behavior
Text should center align when wrapping with sufficient padding:

![Screen Shot 2022-09-21 at 4 06 49 PM](https://user-images.githubusercontent.com/1056412/191625637-d195e340-a11c-49f7-a28e-8a25a9a99069.png)

#### Steps to Reproduce

1. Make a Condition Widget with a label that can wrap.
2. Add the widget to a layout and resize such that the width will force the text to wrap.
3. Observe that the widget looks like the second example above.

#### Environment

* Open MCT Version: 2.0.7
* Deployment Type: stable
* OS: Any
* Browser: Any

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment]
Verified Fixed -- Testathon 10/14/22

**Comment by rukmini-bose** [comment]
Verified Testathon 10/24

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon 10/24/2022
