### ISSUE TITLE
Condition Widget using Condition Set output as label is blank

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#5805]
#### Summary
The setup:
1. A Condition Widget (CW) that uses a Condition Set (CS) for conditional styling.
2. The CS either has no telemetry in its composition, or has telemetry for which there is no data currently.
3. The CW has "Use Condition Set output as label" enabled.

The problem: in the setup above, even though the CS UI reports that the CS is outputting the Default condition's output, it isn't. 

Most importantly: the CW will be blank. 

This has a serious effect on real-world usage of Condition Widgets with conditional styling, and effectively makes using the CS output as a CW label useless, as the CW will be blank until there is telemetry available and flowing.

#### Expected vs Current Behavior
Given that the CS should only output in response to input (telemetry data) we need to find a solution that allows a CW to not be blank in the setup outlined above. 

**For the CW**, there are two options:
1. The CW uses the CS's Default condition "output" when the CS isn't actually outputting anything. I think this would be most inline with a user's expectations.
2. When a linked CS isn't outputting anything, the CW falls back onto its own static Label property. This is less desirable, and in usage makes the Default condition functionally equivalent to the "isDefined" criteria in a composed condition.

**For the CS** edit and browse UI, when the CS isn't outputting anything the "Current Output" display should be blank. We also should amend hint text and documentation to clarify the actual behavior here.

#### Steps to Reproduce

1. Create a Condition Set (CS) and set its Default condition to output some string.
6. Add a condition, and set that to output a string. Don't add any telemetry. Save and exit.
7. Observe: the CS UI reports that it is currently outputting the Default condition's string.
9. Create a Condition Widget and add the CS into it via the Conditional Styling UI. 
10. Enable "Use Condition Set output as label".
11. Observe that the widget's label will be blank:

#### Environment

* Open MCT Version:  2.1.1-SNAPSHOT, 2.0.7
* Deployment Type:  latest, stable
* OS: Any
* Browser: Any

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by unlikelyzero** [comment]
This has been fixed

**Comment by charlesh88** [comment]
Testathon 2024-02-27 verified fixed for steps to reproduce 1 - 6.
