### ISSUE TITLE
Notebook Embeds Should Include New Action Menu 

### ISSUE THREAD

**Issue by rukmini-bose** [nasa/openmct#5810]
**Is your feature request related to a problem? Please describe.**
Notebook embeds need to be enhanced so that users have a more clear action button. At the moment, it is very confusing for a user when interacting with an embed. Clicking parts of the embed may navigate a user away from a Notebook, or do actions that were not intended by a user. 

**Describe the solution you'd like**
We want to implement an enhanced action menu whose action options are more clear to a user. This action menu will be similar in design to our Create menu button, in which, on hover, a description of each option will be displayed to the right side of the menu. 

** Testing Instructions**

1. Create a notebook entry and drag an embed into it, or navigate to a Notebook object that already contains embeds. 
2. Observe that each embed now contains a 3-dot menu with the following actions: Quick View, Navigate to Item, Navigate to Item In Time, and Remove This Embed. 
3. Select each actions and verify that the following behaviors occur:
(a) Quick View: Opens a full screen overlay of the embed.
(b) Navigate to Item in Time: Navigates to item in its time frame when captured.
(c) Navigate to Item: Navigates to item with the current time settings.
(d) Remove This Embed: Removes embed from the notebook entry.
4. Add a snapshot to a notebook entry. Verify that the action menu has the same actions as described above, as well as an additional option called "View Snapshot". Verify that selecting this action will open up the snapshot overlay.
5. Create a notebook entry that has enough embeds that they cannot fit on one line. Verify that after the embeds are unable to fit on one line, a scrolling container appears to encapsulate all of the embeds. 

**Additional context** 
Closes https://github.com/nasa/openmct/pull/5809

**Comment by charlesh88** [comment]
Verified fixed Testathon 2023-01-24. Great work!

**Comment by davetsay** [comment]
verified. really cool.

i am seeing this though
![image](https://user-images.githubusercontent.com/3614296/214976705-407cf6bf-b86f-4f86-83d6-0637b27c9b16.png)

**Comment by unlikelyzero** [comment]
@davetsay filing as https://github.com/nasa/openmct/issues/6217
