### ISSUE TITLE
Tree Disappeared in Location Tab When Creating New Object 

### ISSUE THREAD

**Issue by rukmini-bose** [nasa/openmct#5819]
#### Steps to Reproduce

1. Create a new object. 
2. When trying to save in a specific folder, notice that the tree has disappeared. 
3. Notice that searching for a location in the tree does not return any results, and also gives network errors. 

NOTE: Right now, you can still save new in a specified location– however, you must navigate to the location in the tree manually before creating the object. 
#### Environment

* Open MCT Version: Version: 2.1.1 (bug found during 9/30 testathon)
* Deployment Type: Testathon
* OS: 
* Browser: Chrome

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by akhenry** [comment]
@rukmini-bose  I think the 500 error from Yamcs is key here. If the Yamcs dictionary fails to load, then the tree fails to load (even in the main tree).

We _should_ handle this case more gracefully, but I don't think this is a blocker on Open MCT, if Yamcs is not working then our VIPER users can't really do anything useful.

**Comment by akhenry** [comment]
I think that the fix here is to handle Yamcs errors while fetching the dictionary more gracefully so that the rest of the tree can still load.

**Comment by akhenry** [comment]
Have filed a followup issue which may resolve this - https://github.com/nasa/openmct/issues/5859.

**Comment by unlikelyzero** [comment]
Retest on 2.1.5

**Comment by rukmini-bose** [comment]
Verified Testathon 12/28/2022 

When and after creating a new object, I am not seeing any indications of the tree disappearing, search is working appropriately, and I see no network errors.

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 3/20/24

**Comment by charlesh88** [comment]
Testathon 2024-03-20 cannot repro, fixed.
