### ISSUE TITLE
Deleting a notebook entry without tags throws an error and the modal does not close

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#5823]
#### Summary

When deleting a notebook entry without a tag, an unhandled error is thrown in the console and the delete modal does not close as expected.

#### Expected vs Current Behavior

Expected: The entry should be deleted and the modal should close.
Current: The entry is deleted, but the modal does not close and an error can be seen in the console

#### Steps to Reproduce

1. Create a notebook
2. Add an entry
3. Add another entry and tag it
4. Delete the entry without tags
5. Observe an error in the console and the modal does not close
6. Delete the entry with tags
7. The entry deletes and modal closes as expected with no errors

#### Environment

```
Version: 2.1.1
Build Date: Fri Sep 30 2022 15:41:32 GMT-0700 (Pacific Daylight Time)
Revision: 1c00f1a731263cd7573f02e0a8f1591b634d2298
Branch: release/2.1.1
```

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information

![image](https://user-images.githubusercontent.com/9259993/193368080-70afcba1-1525-43fb-8845-742e3b621070.png)

**Comment by akhenry** [comment]
@jvigliotta to test

**Comment by jvigliotta** [comment]
Confirmed Fixed - Testathon 10/4

Was able to delete with and without tags with no errors or stuck modals.

**Comment by charlesh88** [comment]
Testathon 10-04-22 verified fixed. Same as @jvigliotta and also with embeds, for extra credit.

**Comment by rukmini-bose** [comment]
Verified Testathon 10/4
