### ISSUE TITLE
Uncaught promise rejection when cancelling out of the Create modal

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#5825]
#### Summary

Cancelling out of the Create modal throws an unhandled promise rejection error

#### Expected vs Current Behavior

Expected: No error
Current: Error

#### Steps to Reproduce

1. Click "Create+" and select any domain object to open the create modal
2. Click "Cancel"
3. Observe error in the console

#### Environment

```
Version: 2.1.1
Build Date: Fri Sep 30 2022 15:41:32 GMT-0700 (Pacific Daylight Time)
Revision: 1c00f1a731263cd7573f02e0a8f1591b634d2298
Branch: release/2.1.1
```

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information

![image](https://user-images.githubusercontent.com/9259993/193368357-3443723d-e87d-49f9-ba27-a87ba294f402.png)

**Comment by unlikelyzero** [comment]
Setting to medium severity

**Comment by ozyx** [comment]
No longer can reproduce-- closing this
