### ISSUE TITLE
[Webpack] Changes to *.scss files no longer being hot-reloaded in development mode

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#5832]
#### Summary

Initially reported by @rukmini-bose :

Changes to *.scss files while using webpack-dev-server in development mode are not being reflected (no hot reloading of *.scss files). In order to see the changes, one must trigger a `npm run build:dev` and reload the page manually.

Likely some side effect of #5797 

#### Expected vs Current Behavior

The changes should be reflected on the page immediately (hot-reloaded).

#### Steps to Reproduce

1. Create a Notebook
2. Create a notebook entry
3. Drag in an embed
4. Reduce the width of the notebook entry container (via browser or side-panes) until the scroll container shows
5. In `notebook.scss`, modify the `background` property of `.scrollContainer` to be a static color, (e.g.: red, blue).
6. Save
7. Notice that webpack reports "compilation successful" but the color change is not reflected on the page

#### Environment

```
Version: 2.1.1-SNAPSHOT
Build Date: Mon Oct 03 2022 15:48:08 GMT-0700 (Pacific Daylight Time)
Revision: 945f220727208d3c4ed9e4356083b919a0dcf307
Branch: nb-embed-enhance
```

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by scottbell** [comment]
Changing the `webpack-dev-server` config to this:
```
devServer: {
        devMiddleware: {
            writeToDisk: true
        },
        static: {
            directory: path.join(__dirname, '/dist/'),
            publicPath: '/dist',
        },
        client: {
            progress: true,
            overlay: true
        }
    }
```
Seems to work, but it breaks HMR as `dist` is constantly be updated. We can resolve this by changing the `static` route to:
```
static: {
            directory: path.join(__dirname, '/dist/'),
            publicPath: '/dist',
            watch: false
        },
```
but this removes live reloading on CSS changes. Maybe this is an acceptable compromise? The best would be HMR on `vue` & `js` changes, and live reloading on everything else.

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon 10/24/2022

Tested locally changing various css styles, the were reloaded in the UI.

**Comment by rukmini-bose** [comment]
Verified Fix Testathon 10/24/2022
