### ISSUE TITLE
[Elements Pool] Aliased items are not shown to be aliased

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#5833]
#### Summary

When we show aliased objects, we will display an arrow over the domainObject icon to show the user that this is an aliased item and not the original.

#### Expected vs Current Behavior

Aliased items should be show to be aliased in the elements pool.

#### Steps to Reproduce

1. Drag an aliased item into an object with composition (stacked plot, overlay plot, etc)
2. Note that the item does not show the usual aliased item styling.

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information

![Screen Shot 2022-10-03 at 4 31 50 PM](https://user-images.githubusercontent.com/12013460/193703939-4c64bbd5-0af9-488a-be4c-b00039245c26.png)

**Comment by jvigliotta** [comment]
## Testing
- follow the reproduction steps

**Comment by ozyx** [comment]
Verified fixed Testathon 10/4/22

![image](https://user-images.githubusercontent.com/9259993/193896001-b9baa9c9-f7f4-491b-b661-208bb76fea9c.png)

**Comment by rukmini-bose** [comment]
Verified 10/4 Testathon
