### ISSUE TITLE
Refine plot UX design

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#584]
<p>Testathon 1/29/15. Jay feels that the view control in plots that controls whether the plot is viewed in overlaid or stacked mode is not discoverable enough: currently the user must mouse over the plot area to display the control. This is however, a conscious design tradeoff to allow plots to display in small areas without being overwhelmed by their controls.</p> <p>The UX/UI for plots needs to be reviewed and discussed with the team, before further plot control dev is undertaken.</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-790
Originally created: Thu, 29 Jan 2015 15:45:33 -0800
Updated: Thu, 7 Jan 2016 17:26:09 -0800

**Comment by charlesh88** [comment]
Look at plots in VISTA as well for cases where user is hovering over multi-line plots and the new "snap to" data display can take up many lines of space.

**Comment by charlesh88** [comment]
Redefining this a bit to allow it widen scope to include the following:
* Overlay vs. stacked view controls as previously mentioned.
* Zoom/pan step back and reset controls.
* Value at a point display: #553.
* Legends display: #618 and #573.

**Comment by charlesh88** [comment]
Assessment/approach on elements:
##### Legends
* Overflow currently handled very badly. If current strategy of showing one line of legend items is to be continued, need to clearly indicate when there are more legend items that are being hidden.
* Want to allow viewing of legend while not obscuring plotted data for the plot of interest. Hover shows flyout element?
* Allow user to pin/unpin plot legend, even on layout frame elements.
* Dynamic sizing of plot area based on size of container, e.g. container is "small" show one line of legend items, "med" shows 2 lines, etc.
* Expanded legend does or doesn't show legend items inline, need to determine. Would result in bad space usage for short telem elements in a wide container.

**Comment by charlesh88** [comment]
Discuss in concert with sub-object selection.

**Comment by larkin** [comment]
Need to start addressing this in concert with plot work done by Pete.  Need to break down into sub issues.

**Comment by larkin** [comment]
Charles: Going to do a final design review, check with users on design ideas, and produce final? sketch doc.

As part of Sprint planning for Robinson we need to decompose this sketch doc into tasks which will be assigned to Charles & Pete.

**Comment by larkin** [comment]
@charlesh88 To set up/meet with Pete to decompose tasks.

**Comment by charlesh88** [comment]
[Updated UI is here](https://drive.google.com/open?id=0B0v27OM1JkSeR001RFJZMk43QVk) starting at pg. 84.

**Comment by charlesh88** [comment]
Same as #618: in progress, but not done documenting prior discussions on redesign strategy. Pulling into Tiptree.

**Comment by charlesh88** [comment]
[Updated UI is now here](https://drive.google.com/a/nasa.gov/file/d/0B0v27OM1JkSeeTAzZ09JUERGbkE/view?usp=sharing). @larkin Let's discuss when you get to this.

**Comment by charlesh88** [comment]
Design should consider and solve for these issues:
- [ ] #573
- [ ] #618
- [ ] #620
- [ ] #1022
- [ ] #1391
- [ ] #1392

**Comment by charlesh88** [comment]
Created #1590 to track styling implementation.
