### ISSUE TITLE
[Timer] Timers require Target datetime when editing, but should not

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#5843]
#### Summary
A Target datetime is required when editing, but isn't when creating. This forces a user to always create a running Timer when editing properties.

#### Expected vs Current Behavior
Instead, a Target datetime should always be optional. 

1. A "well-formed" validation _must_ be performed on the input as a whole. Any partial entry (like hours, but not minutes, or no date) should be treated as invalid. To whit, the current approach of defaulting 0 for the hours / mins / secs inputs must be fixed - those fields should be blank by default. If the user enters a date but not hours / mins / secs we could treat the input as valid, enable the OK button, and default 0's at time of storage.
2. If the user uses the UI to reset the Timer to an unset state, then editing Properties should show the Target datetime as completely none-defined, not with 0's in the hours / mins / secs inputs.

#### Steps to Reproduce

1. Create a new Timer. Note that it can be saved

<img width="585" alt="Screen Shot 2022-10-05 at 1 36 38 PM" src="https://user-images.githubusercontent.com/1056412/194159700-7746036e-06fe-4974-977b-46d6ea26a8cc.png">

and will result in a non-running Timer.

<img width="197" alt="image" src="https://user-images.githubusercontent.com/1056412/194159925-3edff174-0cb0-4d20-991a-031e91e34616.png">

4. Edit the timer, and blank out any of the hours / minutes / secs inputs, like this:
<img width="594" alt="Screen Shot 2022-10-05 at 1 37 03 PM" src="https://user-images.githubusercontent.com/1056412/194160674-05d3276a-13df-4663-98ea-745fc7470680.png">
Note that the Ok button is not enabled.

5. Restore hours / minutes / seconds so it looks like it did right before actions in step 2:

<img width="585" alt="Screen Shot 2022-10-05 at 1 37 13 PM" src="https://user-images.githubusercontent.com/1056412/194160504-a17d870a-e013-4763-b36e-2b01acf46a49.png">

Note that the Ok button is still not enabled. Only by entering a fully qualified date and time will the form validate.

#### Environment

* Open MCT Version:  2.0.5
* Deployment Type:  stable
* OS: Any
* Browser: Any

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by unlikelyzero** [comment]
Cannot reproduce 08/04/23
