### ISSUE TITLE
User edits can be lost if failures occur during save

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#5848]
Relates to https://github.com/nasa/openmct/issues/5802

#### Summary
When editing a display layout, user changes are not saved after an error has occurred unless the user makes an additional change to the layout before retrying the save.

The issue is because the previous failed save marked the object clean, so it is no longer queued to be saved. A workaround is to make another change to the object after the initial save failure. A subsequent save will then work as expected.

#### Steps to Reproduce
1. Edit a display layout
2. Open the network tab in Chrome dev tools
3. Make some changes to the display layout (you can just move something around)
4. In the "Throttle" dropdown in the network tab select "offline"
5. In the display layout, click "Save and Finish Editing"
6. Observe that an error is displayed.
7. In the "Throttle" dropdown in the network tab select "no throttling"
8. In the display layout, click "Save and Finish Editing" again.
9. Observe that the save appears successful, and that the application is no longer in edit mode.
10. Navigate away from the layout, and navigate back again
11. Observe that the changes were not saved.

#### Environment
* Open MCT Version: release/2.1.1 @ 9022d5d85989dbd5cdd6e508d7c382f12807cfef
* Deployment Type: VIPER Test

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by akhenry** [comment]
Assigning severity of critical because it's an edge case, and there is a workaround

**Comment by ozyx** [comment]
Not fixed. Testathon 10/27/22

I'm still able to reproduce the issue with the given steps

**Comment by davetsay** [comment]
Not fixed (even though I smoke tested it and it was fixed...).

**Comment by jvigliotta** [comment]
> Not fixed (even though I smoke tested it and it was fixed...).

Yep! Feel ya!

**Comment by ozyx** [comment]
Verified fixed Testathon 11/10/22

Following the provided instructions and changes were saved and persisted
