### ISSUE TITLE
Document markup style for common elements

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#585]
<p>Create documentation for best practices in markup for adding buttons, dropdowns, menus ,etc.</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-428
Originally created: Mon, 22 Sep 2014 11:24:02 -0700
Updated: Thu, 7 Jan 2016 17:30:45 -0800

**Comment by charlesh88** [comment]
Covered by #1230

**Comment by charlesh88** [comment]
Closing this as a dupe of #823
