### ISSUE TITLE
Show me where I am zoomed within an image

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#5851]
**Is your feature request related to a problem? Please describe.**
When zoomed in an image, it would be useful to know _where_ in the full image I am zoomed. This is particularly useful when locking zoom state and moving between images.

**Describe the solution you'd like**
When zoomed within an image, show a rectangle within a thumbnail of the full image indicating where I am zoomed. This could be overlaid on the existing image thumbnail, since we're already showing a thumbnail there.

**Example**
![Screen Shot 2022-10-06 at 2 52 41 PM](https://user-images.githubusercontent.com/4215777/194425684-40251f18-1478-4ca0-95a0-5ab498fb68b5.png)

**Comment by akhenry** [comment]
@charlesh88 Thoughts?

**Comment by LuciNyan** [comment]
I'd love to work on this issue! Could you please assign this to me if not been assigned to anybody yet? Thanks! <3

**Comment by ozyx** [comment]
Verified, Testathon 12/5/22:

Zoom indicator displays correctly when zoomed in and panned. It also applies to adjacent images if the zoom if locked. On window resize, the zoom area adjusts correctly. Awesome stuff.

**Comment by davetsay** [comment]
verified

**Comment by davetsay** [comment]
this is great @LuciNyan , thanks!
