### ISSUE TITLE
Allow domain objects to be tagged

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#586]
<p>Allow domain objects to have one or more user-defined textual tags to be applied to them. </p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-79
Originally created: Mon, 13 Jan 2014 13:09:29 -0800
Updated: Thu, 7 Jan 2016 12:59:52 -0800

**Comment by VWoeltjen** [comment]
Migrated comment, from @charlesh88:
<blockquote>
<p>Getting this in as a backlog item for parity with MCT. Not necessarily required at this point.</p>
</blockquote>

**Comment by charlesh88** [comment]
Possible Help Wanted candidate?

**Comment by charlesh88** [comment]
Corollary here: tags would need to be included as a Search field.

**Comment by charlesh88** [comment]
Notes from tagup 10/26/16
- Related to #132.
- Involved with annotations and the Notes field.
- Could be simple, but could be complex as well.
- Possible Future Help Wanted issue.

**Comment by larkin** [comment]
Happy to close as wontfix for the time being.
