### ISSUE TITLE
Refactor code to use composition API

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#5860]
#### Summary
There are [several](https://github.com/nasa/openmct/blob/cb8e09c9f9ec176884c8b8d193a9f8f01667077e/src/plugins/remove/RemoveAction.js#L89) [instances](https://github.com/nasa/openmct/blob/cb8e09c9f9ec176884c8b8d193a9f8f01667077e/src/plugins/charts/scatter/ScatterPlotView.vue#L119) [in](https://github.com/nasa/openmct/blob/cb8e09c9f9ec176884c8b8d193a9f8f01667077e/src/plugins/gauge/components/Gauge.vue#L605) [our](https://github.com/nasa/openmct/blob/cb8e09c9f9ec176884c8b8d193a9f8f01667077e/src/plugins/displayLayout/components/DisplayLayout.vue#L515) codebase where domain object composition is being changed by directly mutating the `composition` property of domain objects. This is problematic for two reasons:
1. It will not trigger composition listeners.
2. It will not work at all with anything other than the default composition provider.

We see a lot of bugs that are some version of "removing an object from X does not update Y". This issue may underlie a lot of these kinds of issues that keep coming up. There was legacy code that used to plaster over this issue by automatically detecting composition changes in object mutation in order to bridge the legacy and current APIs, but this code has been removed along with the legacy codebase.

#### Expected vs Current Behavior
Object composition operations should _always_ use the composition API.

**Comment by ozyx** [comment]
# Testing Notes

Test composition in general:
1. Add / Remove objects to / from composition-able objects
2. Verify the composition is correct after save by calling `this.openmct.composition.get(domainObject)` in console

**Comment by unlikelyzero** [comment]
Verified
