### ISSUE TITLE
[Layout] Can put a layout inside itself; weirdness ensues

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#587]
<p>Can put a Layout inside itself; it appears in a panel inside itself (with a hall-of-mirrors effect). Most interactions are still available, but cannot move the panel which contains the layout; some hover effects for panels in the layout-in-layout are applied but the cursor doesn't save.</p> <p>After hitting "Save" on the Layout when doing this, browser is frozen.</p> <p>Noted in testathon 10/9/2014</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-502
Originally created: Thu, 9 Oct 2014 16:31:21 -0700
Updated: Thu, 14 Jan 2016 17:14:30 -0800

**Comment by VWoeltjen** [comment]
Migrated comment, from @charlesh88:
<blockquote>
<p>This is still an issue.</p>
</blockquote>

**Comment by larkin** [comment]
Fixed, closing.
