### ISSUE TITLE
Time input selection in flexible layout causes plot requery

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#5874]
#### Summary
Selecting and highlighting the start or end input field of the time conductor can trigger an unwanted plot requery from within a flexible layout.

#### Expected vs Current Behavior
Plots should not be requeried unless the time range changes

#### Steps to Reproduce

1. Create a flexible layout
2. Add an overlay plot with telemetry
3. Add another plot with telemetry
4. Save flexible layout
5. Open browser dev tools and navigate to the network tab
6. Toggle independent time conductor in one of the plots
7. In the toggled independent time conductor, click and drag inside start or end bounds inputs to highlight time to change
8. Observe that plots requery even though time bounds have not yet changed

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [x] Does this have an impact on Performance?

**Comment by akhenry** [comment]
Not this again...This is a regression, so we need to make sure we define an e2e for it.

**Comment by akhenry** [comment]
Reclassifying as medium because it has no functional impact and really shouldn't happen that often. I do want to fix it quickly though, this is an annoying regression.

**Comment by davetsay** [comment]
Can't repro. Closing to retest.

Filing a somewhat related bughancement found during attempted repro. #6035
