### ISSUE TITLE
Create action does not respect namespace

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#5890]
#### Summary
Create Action is using just the key from the identifier to make the key string.

#### Expected vs Current Behavior
Objects containing a `namespace` should be created and saved successfully.

#### Steps to Reproduce
1.
2.
3.
4.

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by jvigliotta** [comment]
@davetsay how we test this son of a gun?

**Comment by davetsay** [comment]
Added local environment testing instructions

**Comment by michaelrogers** [comment]
This issue appears to be resolved after following the above testing instructions.

<img width="390" alt="Screen Shot 2022-10-27 at 5 01 28 PM" src="https://user-images.githubusercontent.com/7417521/198406611-5731410b-fc19-4b57-8011-aa982ee39584.png">
