### ISSUE TITLE
In Firefox, right click on tree shows browser menu (in addition to tree menu)

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#5910]
#### Summary
Right click on a tree item opens both the browser right-click menu as well as the tree menu under the browser menu.
This makes it difficult to perform tree-related actions.

#### Expected vs Current Behavior
Only the tree menu should show when right-clicking on a tree item.

#### Steps to Reproduce
1. Right click on the My Items folder (or any other item in the tree)
2. Observe the menus that pop up
3. If you click away from the menu, the browser menu closes and THEN you can access the tree menu under it.

#### Environment

* Open MCT Version: 2.1.1
* Deployment Type: banner/testathon and local
* OS: Mac
* Browser: Firefox

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information
<img width="477" alt="image" src="https://user-images.githubusercontent.com/5247066/197830766-b7978fbc-4e1a-480a-86a9-3d5e3c060dfe.png">

**Comment by akhenry** [comment]
Yeah this has started happening to me recently as well. I think it might be a Firefox bug because I'm seeing it in Office 365 as well.

**Comment by akhenry** [comment]
We can close this, turns out [it's a Firefox setting](https://www.reddit.com/r/firefox/comments/q1t31u/comment/hfgn7ce/?utm_source=reddit&utm_medium=web2x&context=3). For whatever reason it must have been enabled by default in our managed Firefox install.
