### ISSUE TITLE
Starting OpenMCT fresh causes persistent error message

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#5914]
#### Summary

When starting OpenMCT with a fresh instance (fresh DB, either local or CouchDB), a persistent error message is generated:

![image](https://user-images.githubusercontent.com/9259993/197903869-57ecc593-5028-460d-a8e9-6184e98f6239.png)

The persistence of the error message and the red color would serve to indicate that something has gone terribly wrong. And in some cases, this may be true. But in the case of a fresh DB, this is to be expected. Since the `mine` folder ('My Items', or otherwise named) does not yet exist, this will trigger an attempt to create the `mine` folder.

The existence of this error message impacts our visual tests as it now shows up in every snapshot we take (since the message needs to be manually dismissed).

#### Expected vs Current Behavior

We should handle this specific case gracefully somehow, and not generate an error unless the attempt to create the `mine` folder fails (after noticing it does not yet exist).

#### Steps to Reproduce

1. Clear browser cache
2. Start openMCT fresh
3. See a persistent error message "Failed to retrieve object mine"
4. Notice that error message does not go away unless manually dismissed

#### Environment

* Open MCT Version:  `2.1.2`
* Deployment Type:  local
* OS: MacOS
* Browser: Chrome

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [x] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by unlikelyzero** [comment]
Adding blocker as this is blocking the utility of the visual tests

**Comment by akhenry** [comment]
This is almost certainly due to https://github.com/nasa/openmct/issues/5488 which fixed an issue where persistence errors were being suppressed inappropriately. We clearly need to suppress some errors, but as high up the chain as possible so we are not losing important user feedback. Perhaps our object interceptor API could be modified to allow interceptors to suppress errors under certain circumstances.

**Comment by akhenry** [comment]
@ozyx does this have a functional impact? And is there a workaround?

**Comment by ozyx** [comment]
> @ozyx does this have a functional impact? And is there a workaround?

There is no functional impact as far as I'm aware. It's mainly impacting our visual and couchDB tests

**Comment by akhenry** [comment]
Actually, I think this is just an object interceptor order issue in this case. The `missingObjectInterceptor` is kicking in before the `myItemsInterceptor`. Maybe we just need to reverse that order.

**Comment by akhenry** [comment]
Non-functional issues should not block release, even if we need to get to it as a priority.

**Comment by ozyx** [comment]
> Actually, I think this is just an object interceptor order issue in this case. The `missingObjectInterceptor` is kicking in before the `myItemsInterceptor`. Maybe we just need to reverse that order.

Potential solution to implement prioritization for interceptors?: https://github.com/nasa/openmct/blob/4a9744e916d24122a81092f6b7950054048ba860/src/api/objects/InterceptorRegistry.js#L48

**Comment by ozyx** [comment]
Splitting the CouchDB 404 off of this ticket onto its own, since I think it should be handled on the e2e side.

**Comment by ozyx** [comment]
# Testing Notes

1. Clear localStorage in the browser completely
2. Start Open MCT with Local Storage plugin enabled
3. Navigate to Open MCT
4. Verify there is no error notification produced
5. Verify that the "My Items" folder has been created by inspecting localStorage

Repeat the same steps above with CouchDB plugin and a fresh CouchDB database and verify that the 
My Items" folder is created and no error notification is generated

**Comment by michaelrogers** [comment]
Fix verified during testathon on 10/14/2022.
