### ISSUE TITLE
Allow auto-layout feature while composing Layout

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#592]
<p>Allow user to quickly drag items from Library to Elements, then hit an Auto-layout button that algorithmically lays the objects out. </p> <p>Needs design/UX discussion. Testathon 1/29/15 from Jay.</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-787
Originally created: Thu, 29 Jan 2015 15:40:53 -0800
Updated: Thu, 7 Jan 2016 13:17:06 -0800

**Comment by larkin** [comment]
Closing, think this would be implemented as a separate layout type (e.g. responsive, etc).
