### ISSUE TITLE
Conflict resolution is not working in multi-user notebooks

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#5921]
#### Summary

When two users make conflicting changes to a notebook the notebook plugin will detect the conflict and attempt to merge the changes from the two users.

#### Expected vs Current Behavior
Adding two different entries at the same time should result in both entries appearing in the notebook with no errors shown to the user.

#### Steps to Reproduce
1. Open a notebook in Chrome
2. Open the same notebook in Firefox
3. In the Chrome network tab throttle the network connection down to slow 3d
4. Add an entry to the notebook in Chrome 
5. Quickly jump over the Firefox and add an entry there.

Observe that an error is displayed to the user, and the entry made in Firefox appears in Chrome.

#### Environment
* Open MCT Version: 2.1.2
* Deployment Type: VIPER Dev

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by michaelrogers** [comment]
Conflicts still appear when testing multi-user notebooks. @jvigliotta and myself tested this during testathon 10/17/2022.

 
![Screen Shot 2022-11-17 at 4 45 03 PM](https://user-images.githubusercontent.com/7417521/202576554-d282d3a3-aa23-4e48-9c31-9e2803b47323.png)

**Comment by unlikelyzero** [comment]
### Testing Notes
Test on 2.1.4.ERT and 2.1.5

**Comment by ozyx** [comment]
Verified on 2.1.5 and 2.1.4-ERT.

One thing I did notice is that the timestamp on the entry is the time the entry was initiated, but not when it was persisted. This can lead to some confusion, but sorting does put the entries in the correct order in terms of when they were persisted.
