### ISSUE TITLE
Condition Set LAD Table "view switch" isn't consistent with other view types

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#5924]
#### Summary
A number of objects (telemetry, imagery, more) in Open MCT allow view pivoting to the same data in different ways. Numeric telemetry for instance allows a pivot from a plot view to a table, and back. The app model is: view the same data, but in a different way. 

The Condition Set object also allows pivoting between its own native view as well as several different views - but those views are _not_ all of of the same data:

![Screen Shot 2022-10-28 at 5 18 55 PM](https://user-images.githubusercontent.com/1056412/198753056-33c82985-8967-4d6a-981e-b332d8c02755.png)

Native view
![Screen Shot 2022-10-26 at 4 09 33 PM](https://user-images.githubusercontent.com/1056412/198416864-e7f02254-3c12-486f-9ef4-77d45e9e3b47.png)

LAD Table view
![Screen Shot 2022-10-26 at 4 18 50 PM](https://user-images.githubusercontent.com/1056412/198416904-80bb6122-62b9-437c-9733-5a70b62c462f.png)

**Plot view and Telemetry Table views** both display a plot and a scrolling table of the CS's output value - not the constituents values - which is correct and desired. The native view shows the CS's current "output" based on whatever condition is currently matching, but the LAD Table view shows the current value(s) of the CS's constituents - these are not the same. This can especially be misleading when there's only one telemetry point in a Condition Set. One might argue that Imagery, which pivots between bitmaps and a scrolling table of URLs isn't obeying the model, but there's a one-to-one relationship between a given image and its corresponding URL, which is not the case with the CS pivot.

#### Proposed Solution
There are 2 fundamental solutions here:
1. **Don't allow this**. Remove "LAD Table" from the view options.
2. **Allow this**. Basically, set expectations for this view and allow it. I think this opens up options, and simply renaming "LAD Table" to "Child Values" or something similar in this instance might be enough.

#### Steps to Reproduce

1. In Browse mode, nav to a Condition Set and access its view switcher dropdown menu. 
1. Switch to the LAD Table view.

#### Environment

* Open MCT Version:  2.1.2
* Deployment Type:  all
* OS: any
* Browser: yes

#### Impact Check List

- [x] Data loss or **misrepresented** data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by akhenry** [comment]
This might be a side effect of making LAD tables the default view of aggregate telemetry. We could probably just suppress it for condition sets.

**Comment by scottbell** [comment]
After discussion with @akhenry & @charlesh88, it sounds like removing LAD tables for condition sets (i.e., option 1) is what we'd like.

**Comment by scottbell** [comment]
Testing instructions:

1. Make a Condition Set
2. Make 2 Sine Wave Generators
3. Add both to the Condition Set
4. Ensure "Lad Table" view option isn't visible.
5. Ensure "Conditions View", "Telemetry Table", and "Plot" are visible.

**Comment by ozyx** [comment]
Verified - Testathon 03-09-2023

**Comment by davetsay** [comment]
verified
