### ISSUE TITLE
[Import/Export] Support import and export of domain objects

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#593]
<p>Ability to export (save a local copy) of domain objects is necessary to provide users with a means of avoiding data loss, particularly while software matures. Actions to export and import domain objects (including composite domain objects, e.g. layouts and all the panels they contain) should be provided.</p> <p>Format for this export is TBD. Initial suggestion would be to export object models directly to JSON with some minimal header information. </p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-344
Originally created: Fri, 5 Sep 2014 10:25:31 -0700
Updated: Thu, 14 Jan 2016 17:12:20 -0800

**Comment by charlesh88** [comment]
I'm going to start leaving comments here every time I wish I had this. Comic Con 2017.

**Comment by larkin** [comment]
Was tracked 12/10/2015 in VISTA as a user request

**Comment by larkin** [comment]
Third party developer mentioned this feature as a way to share displays made in development environments with others.

**Comment by VWoeltjen** [comment]
Had another request for this from a third-party developer (this time to save/restore user-created "checklists," similar to the TODO tutorial.

Note that this could be implemented as a standalone feature/plugin by registering a few appropriate actions.
