### ISSUE TITLE
Aggregate LAD Table view doesn't work properly when children are aggregates

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#5939]
#### Summary
When an aggregate element in the tree is navigated to, it provides a LAD Table view of its children. This is great when the children are leaf telemetry nodes, but when the children are themselves aggregates, the LAD view tries to displays "values" for those elements:

![Screen Shot 2022-10-31 at 10 54 52 AM](https://user-images.githubusercontent.com/1056412/199077116-13c53fdb-0058-4858-9cd0-b1c86e382d10.png)

What's happening is that the first actual value within the nested aggregate is being lifted up as if it's the value of the aggregate, which is very misleading. 

#### Proposed Solution
Provide the LAD Table view, but only show values for actual telemetry end points. For nested child aggregate elements, include them in the list, but don't show a timestamp or value. Consider adding a "Type" column to this view in particular (_not_ all LAD Table views) that would clarify what type of object a given line item is. 

At the very least, if we can't fix the view as suggested above, we should suppress the table view when it's not capable of displaying the right data.

#### Steps to Reproduce

1. View an aggregate node that has an aggregate as a child.
2. Observe that the LAD Table view erroneously displays a value for the child aggregate.

#### Environment

* Open MCT Version:  2.1.2
* Deployment Type:  any
* OS: all
* Browser: any

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by akhenry** [comment]
What about if we used used the LAD Table Set functionality here? ie grouped the children by aggregate parent? We would have to figure out how to handle nesting - that might require a change to the LAD Table Set view (LAD Sets within LAD Sets)

**Comment by scottbell** [comment]
After discussion with @charlesh88 & @akhenry, we're going to show aggregates that have aggregates (i.e., not leaf telemetry nodes) as a special child, that clicking it will navigate you to.  The child will not have a timestamp or value, and may have a "Type" as a "Aggregate".

For extra credit, other children (i.e., leaf telemetry nodes) will also be clickable and navigable.

**Comment by charlesh88** [comment]
This issue is related to https://github.com/akhenry/openmct-yamcs/issues/281.

**Comment by scottbell** [comment]
@charlesh88 and/or @akhenry If the telemetry object is not an "Aggregate", how specific do we want to make the type? Is "Simple" or "Leaf" enough? Or do we want something more specific like "Numeric"?

**Comment by scottbell** [comment]
> @charlesh88 and/or @akhenry If the telemetry object is not an "Aggregate", how specific do we want to make the type? Is "Simple" or "Leaf" enough? Or do we want something more specific like "Numeric"?

@charlesh88 @akhenry
Here's what I've got so far:
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/9853862/223662652-800598f3-808d-476e-ad11-c1049662340f.png">

**Comment by ozyx** [comment]
Verified fixed -- Testathon 3/17/2023 🍀
