### ISSUE TITLE
[Timeline] Swimlanes refresh too often

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#595]
<p>In <a href="https://trunk.arc.nasa.gov/jira/browse/WTD-1075" title="When an Activity is present in a Timeline more than once, only the &quot;last&quot; will display as selected" class="issue-link" data-issue-key="WTD-1075"><del>WTD-1075</del></a>, traced the root cause to the manner in which selection state is preserved and restored when the set of visible swimlanes changes.</p> <p>While there was a bug in the logic used there, it is not immediately obvious why the swimlanes are being refreshed in some of the cases where that bug is observed. Filing this as a followup issue to investigate further, to see if the frequency of these refreshes can be reduced (treating as lower priority since performance consequences have not been observed yet.)</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1121
Originally created: Thu, 16 Apr 2015 15:30:34 -0700
Updated: Thu, 14 Jan 2016 16:34:03 -0800

**Comment by akhenry** [comment]
Situation may have been improved or resolved by #780

**Comment by larkin** [comment]
closing as wontfix or fixed (IIABDFI)
