### ISSUE TITLE
[Timeline] Add suppress-in-future option to dialog

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#596]
<p>Add checkbox to suppress showing warning dialog for timeline deletion</p> <p>See UI docs attached to <a href="https://trunk.arc.nasa.gov/jira/browse/WTD-846" title="[Timeline] First implementation of new timeline design" class="issue-link" data-issue-key="WTD-846"><del>WTD-846</del></a>, p. 99</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-936
Originally created: Wed, 25 Feb 2015 13:17:09 -0800
Updated: Thu, 14 Jan 2016 16:54:48 -0800

**Comment by charlesh88** [comment]
Closing as dupe of #520.
