### ISSUE TITLE
Tree sporadically doesn't update from composition changes

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#5975]
#### Summary
Seen mostly when multiple users creating objects in their own folders, within a common folder. Creating objects would often not cause updates to containing folders in the tree. The main view's Grid view did not exhibit this problem. Charles was able to _sporadically_ replicate this on his own as a singleton user on the server.

Circumstances:
- Users had their own named folders within a single folder in the tree.
- Users were creating multiple objects, like LAD Tables, Telem Tables, etc. in their own folders. 
- This was all happening concurrently during training.

#### Expected vs Current Behavior
Adding an object to a folder via create must immediately update that folder's view _for that user_ in the tree, in all circumstances.

#### Steps to Reproduce

1. Create a new folder within a sub-folder of Shared Items. Navigate to that folder.
2. Create a LAD Table, Telem Table, Overlay or Stacked Plot. Save to the new folder, which should have defaulted in the Save As dialog locator.
3. Scroll up in the tree to get to telemetry in a way that takes your new folder out of view. Note that this may be important to replicate the problem.
4. Add telemetry to your object view. Save and exit. 
5. Click the "nav up to parent" arrow button to the left of the main view's object label. Don't touch or scroll the tree.
6. Repeat steps 2 through 4 for the other suggested views in step 2. Do this 3 or 4 times. Again, don't scroll or touch the tree except to drag and drop into your composition.
7. At last, scroll back down the tree and expand your new folder, or look at your folder if already expanded: sporadically, the new objects won't be shown. Sometimes expanding and collapsing the folder in the tree will force a reload and bring the new objects into view, sometimes it won't. A browser refresh always seems to fix the problem.

#### Steps to Reproduce 2, Feb 6, 2023
1. Expand the tree to display any composable folder, like Shared Items. 
2. Make a folder inside that folder. You should now be navved you into that new folder. Do not touch the folder in the tree or do any other nav actions.
3. While the newly created step 2 folder is _collapsed_ in the tree, create a new object like a LAD Table.
4. In the dialog's locator, make sure you are saving into the folder created in step 2. Click Ok.
5. Save and exit, you don't need to do anything else such as add telemetry.
6. Expand the folder in the tree that was created in step 2. Note that the newly created object from step 3 is not visible. You can expand/collapse the folder multiple times and it will not refresh.
7. Use the main view's "nav to parent" button to go up to the containing step 2 folder. Note that the tree will do a get and now display your step 3 object. 

#### Environment

* Open MCT Version:  2.1.2
* Deployment Type:  
* OS: any
* Browser: Chrome for sure, not sure about others.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available? Refresh.
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment]
# Testing Instructions
See repro steps above. Confirm this cannot be reproduced.

**Comment by davetsay** [comment]
verified

**Comment by shefalijoshi** [comment]
Verified fixed

**Comment by unlikelyzero** [comment]
@davetsay to restest on the ERT release

**Comment by davetsay** [comment]
verified on ERT release

**Comment by charlesh88** [comment]
This problem has been seen recently in 2.1.6-SNAPSHOT, reopening.

![Screen Shot 2023-02-06 at 2 09 19 PM](https://user-images.githubusercontent.com/1056412/217098866-87b7fff6-2c3d-405a-ab4b-bd00378efa03.png)

**Comment by shefalijoshi** [comment]
Verified Fixed
