### ISSUE TITLE
Tree sporadically stops populating

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#5976]
#### Summary
Seen mostly when multiple users creating objects in their own folders, within a common folder. The tree would sporadically stop populating, and instead display a blank space beneath. Duplicate folders would also seem to manifest. Refreshing would _sometimes, but not always_ fix the problem.

![Screen Shot 2022-11-03 at 3 02 08 PM](https://user-images.githubusercontent.com/1056412/201243567-a257a942-74d5-412e-883a-8b5fcc6588ec.png)

Circumstances:
See same description in #5975.

#### Expected vs Current Behavior
Tree should always fully populate.

#### Steps to Reproduce

See circumstances as noted above. Could be due to number or concurrent users, create and edit workflow, etc.

#### Environment

* Open MCT Version:  2.1.2
* Deployment Type:  any
* OS: any
* Browser: Chrome for sure, not sure about others.

#### Impact Check List

- [X] Data loss or misrepresented data?
- [X] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment]
![image](https://user-images.githubusercontent.com/9259993/201783837-9a1c42ee-9e4e-46aa-b720-6b561ea605ff.png)

**Comment by unlikelyzero** [comment]
Note: Saw this in the modal tree. No reproduction steps

<img width="709" alt="Screen Shot 2022-11-14 at 3 22 28 PM" src="https://user-images.githubusercontent.com/12446869/201788593-f2f39abf-8fd1-4d88-a740-b42774d30810.png">

**Comment by ozyx** [comment]
> ![image](https://user-images.githubusercontent.com/9259993/201783837-9a1c42ee-9e4e-46aa-b720-6b561ea605ff.png)
> 
> 

It's also worth noting that I did not observe any couchDB errors in the process of reproducing this.

**Comment by ozyx** [comment]
# Reproduction Steps

Using `openmct-yamcs` and yamcs `quickstart`

1. Start `openmct-yamcs` with yamcs quickstart
2. View some telemetry point from YAMCS (such as Events, Commands, or other telemetry point)
3. Expand the tree enough to where there's a decent scrollable area
4. Refresh the page while viewing the telemetry, and while its refreshing, madly scroll downward on the tree
5. Observe that the tree breaks completely, and a single console error:

<img width="893" alt="image" src="https://user-images.githubusercontent.com/9259993/202050439-481f920d-c75f-4efc-bec3-32bc018de6a9.png">

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 11/17/2022

Tested using repro steps with and without throttling network. Looked good, no issue, no missing items.
