### ISSUE TITLE
[Plot] Refactor plots to reuse canvas resources

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#598]
<p>Refactor plots to reuse canvas resources, such that WebGL contexts do not run out so quickly and plots do not show up empty as often. </p> <p>This should also create a reusable charting component for resource graphs, etc., such that this resource-tracking is done in one place. (Root of this issue is Chrome's limit of 16 active WebGL canvases.)</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-545
Originally created: Mon, 27 Oct 2014 16:27:29 -0700
Updated: Thu, 14 Jan 2016 16:51:27 -0800

**Comment by larkin** [comment]
fixed in #1557
