### ISSUE TITLE
[Imagery] Mutation error on navigation

### ISSUE THREAD

**Issue by khalidadil** [nasa/openmct#5984]
#### Summary
When navigating between imagery objects, I'm seeing an error:
ImageryView.js?a055:49 Error: Attempted to mutate immutable object Navcam_left_image

#### Steps to Reproduce
1. Navigate to an imagery object (such as Navcam_left_image).
2. Navigate to a different object.
3. You should see an error in the console.

#### Environment
* Open MCT Version: 2.1.3-SNAPSHOT
* Deployment Type: Testathon

#### Impact Check List
- [ ] Data loss or misrepresented data?
- [X] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by unlikelyzero** [comment]
To be tested on:

- [ ] 2.1.4-ERT
- [ ] 2.1.5

**Comment by michaelrogers** [comment]
Fix verified, the error is no longer seen in the console when navigating between objects.
