### ISSUE TITLE
[Gauge] Editing any single config property causes all other config properties to become undefined

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#5985]
#### Summary

When editing config properties of a gauge, all other properties become undefined causing the Gauge to go into a bad state and break.

#### Expected vs Current Behavior

Configuration properties should not be lost, Gauge should not break on property edit

#### Steps to Reproduce

1. Create a Gauge, save it
2. Edit Properties of the Gauge
3. Change any configuration option (anything that's not name or notes, Gauge specific properties)
4. Click Save
5. Observe a ton of errors in the console due to things being undefined

#### Environment

* Open MCT Version:  2.1.4-SNAPSHOT
* Deployment Type:  local
* OS: MacOS
* Browser: Chrome/ any

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment]
# Testing Instructions

1. Create a Gauge with defaults
2. Save it to get out of edit mode
3. Click on the 3dot menu, click "Edit Properties"
4. Change a single Gauge-specific configuration option (anything that isnt name or notes)
5. Save it
6. Verify no console errors
7. Click edit properties again
8. Verify that the properties persisted and no config properties are blank

**Comment by jvigliotta** [comment]
Partially Fixed with a caveat: New issue, it now is in edit mode after you save.
