### ISSUE TITLE
Objects renamed when scrolled out of view don't update in the tree

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#5990]
#### Summary

If an object is scrolled out of view in the tree and is then renamed, the name change is not reflected in the tree and the tree is not sorted properly.

#### Expected vs Current Behavior

The tree should always be sorted properly and should always reflect the current state of objects

#### Steps to Reproduce

1. Create an object and focus it
2. Expand enough items in the tree so you can scroll the object out of view
3. Scroll the object out of view
4. Rename the object either through edit properties dialog, or by editing the name in the titlebar
5. Scroll back down.
6. Notice that the object has its old name and is (potentially) not sorted correctly

#### Environment

* Open MCT Version:  2.1.4-SNAPSHOT
* Deployment Type: local
* OS: MacOS
* Browser: Chrome

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [ ] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by 360macky** [comment]
Hi @ozyx!

Is this the correct flow to reproduce the bug? I can't reproduce it.

https://user-images.githubusercontent.com/47821093/202486626-f90efe05-cbc4-4a70-ba23-630c2bbbdd66.mp4

I also tried creating an object just before changing the name to see if it is not updated.

(Using the same environment)

**Comment by ozyx** [comment]
Hi @360macky!

Thanks for giving this a shot. In fact, I am also unable to reproduce this bug with the steps given here. I think when I logged this I was actually seeing a different issue related to object renames not propagating across different sessions. So for example, if you open two browsers to Open MCT, and rename an object on one browser, the other browser's tree will not update with the new name until you focus it. At that point the tree doesn't sort itself, so you end up with this (potentially) unsorted tree until you collapse/expand the tree or refresh the browser.

Let me try and find a good home for this bug. In the meantime, I'm going to close this one as "won't fix".

Thank you so much for looking into this! 🚀

**Comment by ozyx** [comment]
> So for example, if you open two browsers to Open MCT, and rename an object on one browser, the other browser's tree will not update with the new name until you focus it.

This likely falls under https://github.com/nasa/openmct/issues/4147

**Comment by 360macky** [comment]
> So for example, if you open two browsers to Open MCT, and rename an object on one browser, the other browser's tree will not update with the new name until you focus it.

Yes, that happens. Thanks for the clarification @ozyx!
Certainly the object is not sort in the object tree even when you focus on it:

![CleanShot 2022-11-17 at 12 11 02](https://user-images.githubusercontent.com/47821093/202512194-0399c645-cb3b-4864-acbb-521563d6d2f3.gif)

I'll review #4147.
