### ISSUE TITLE
[Plot] Plots for string

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#600]
<p>Attempting to plot a telemetry point which has string data results in a plot that stays empty. Plots should either be suppressed in this case, or display for string data (e.g. include the state in the left-hand axis)</p> <p>Noted during long duration test, Jan 28 2015</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-760
Originally created: Wed, 28 Jan 2015 17:09:03 -0800
Updated: Thu, 14 Jan 2016 17:17:41 -0800

**Comment by larkin** [comment]
closed as tracked by other issues (https://github.com/nasa/openmct/issues/1601)
