### ISSUE TITLE
[Plot] Add Reset Zoom drop down and options

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#601]
<p>Modify "reset zoom" control such that two additional options are available from a drop-down: "Reset Zoom X" and "Reset Zoom Y", which reset the X and Y axes to their original state.</p> <p>See UI docs attached to <a href="https://trunk.arc.nasa.gov/jira/browse/WTD-868" title="UI for setting plot bounds in a plot view" class="issue-link" data-issue-key="WTD-868"><del>WTD-868</del></a>, p 71</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1137
Originally created: Sun, 26 Apr 2015 10:59:06 -0700
Updated: Thu, 14 Jan 2016 16:32:09 -0800

**Comment by charlesh88** [comment]
Desire for this should be reconsidered; closing issue for now.
