### ISSUE TITLE
[Table] Hide Name column in telemetry tables for one object

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#602]
<p>Hide the Name column in the Scrolling list view when there is only one telemetry object being viewed.</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1175
Originally created: Mon, 4 May 2015 16:37:49 -0700
Updated: Thu, 14 Jan 2016 16:52:53 -0800

**Comment by larkin** [comment]
wontfix, related to #1099
