### ISSUE TITLE
Locator search results show deleted objects

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#6030]
#### Summary

When using the Locator search in the Create modal, deleted objects will show up in search results.

Hypothetically this could allow users to create objects within deleted folders or objects. But mostly would serve to muddy up the search results as object trees become more complex with use.

#### Expected vs Current Behavior

The search results should not include deleted objects.

#### Steps to Reproduce

1. Create an object
2. Delete it
3. Search for it in the Grand Search (it doesn't show up)
4. Click "Create"
5. Click any domain object to open the modal
6. Search for the deleted object (it shows up)

#### Environment

* Open MCT Version: 2.1.4-SNAPSHOT
* Deployment Type: local
* OS: MacOS
* Browser: Chrome 107

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information

Searching for deleted object:

https://user-images.githubusercontent.com/9259993/205165007-3729b1f5-7013-48b1-be39-caa6ad5f7aec.mov

Creating an object in a deleted folder:

https://user-images.githubusercontent.com/9259993/205165563-46a5b957-828c-47f0-830e-1334b4ec9dd4.mov

**Comment by unlikelyzero** [comment]
Verified fixed
