### ISSUE TITLE
Plot rescaling

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#605]
<p>When a plot auto-scales for a large value, and then the large value scrolls off the left, the plot does not re-scale back to a reasonable size for the new values.  This probably builds toward the whole discussion on how plots could have a manually adjusted zoom/scaling while still allowing the data to flow, but that's probably a larger feature.</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1519
Originally created: Thu, 20 Aug 2015 09:42:34 -0700
Updated: Thu, 21 Jan 2016 14:48:50 -0800

**Comment by charlesh88** [comment]
This needs user input.

**Comment by charlesh88** [comment]
Is this still an issue with #1557 on the way?

**Comment by VWoeltjen** [comment]
Closing as wontfix; #1557 has a more mature strategy for autoscaling so this feature request is obsolete
