### ISSUE TITLE
[Notebooks] Formatted entries v1

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#6059]
**Is your feature request related to a problem? Please describe.**
For links in notebook entries, we have had requests to turn them into an actual clickable link.

**Describe the solution you'd like**
When editing a Notebook entry, if you enter a link, ex: http://www.google.com, when the notebook entry is saved and viewed (not being edited) we'd like to wrap that in an HTML <a> link tag. This should have a `target="_blank"` blank attribute so the user isn't navigated away from Open MCT.

**Describe alternatives you've considered**
Markdown formatting.

**Additional context**
This is just a v1. v2 would include more robust formatting (bold, italic, lists, etc). That issue is here: #6060

**Comment by jvigliotta** [comment]
## Testing
- enter a valid link (http/https) while editing an entry
- view the entry, can you click the link? sweet... (if so)
- now, try to break it
- now, try to inject some nefarious items (script tags, alerts, etc) and make sure you can't

**Comment by charlesh88** [comment]
Verified fixed Testathon 2023-01-24, but why do we have to whitelist URLs?

**Comment by rukmini-bose** [comment]
Verified Testathon 1/24/2023

**Comment by davetsay** [comment]
verified but really urls that take up a lot of space make it really really hard to edit the entry.
<img width="471" alt="image" src="https://user-images.githubusercontent.com/3614296/214974747-b54b7804-8918-49ba-81e9-24cd50c096af.png">

**Comment by unlikelyzero** [comment]
Filed a follow up as https://github.com/nasa/openmct/issues/6218
