### ISSUE TITLE
Refactor duplicated test mocks

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#606]
<p>Currently, to test any one component, all of it's dependencies must be mocked.  We define new mocks for each dependency for each for each component we test, which duplicates a lot of code.  Furthermore, if these mocks become outdated (e.g. the service they are mocking changes and the mock is not updated), our tests will be rendered useless.</p>

<p>We should refactor all test mocks into shared mocks that are maintained alongside the implementation of the code they are mocking.  These mocks can simplify testing while simultaneously allowing us to detect integration-level bugs.</p>

<p>This task should be be broken down into smaller focused sections that can be spread out over multiple sprints.</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1260
Originally created: Fri, 12 Jun 2015 11:17:30 -0700
Updated: Thu, 21 Jan 2016 14:55:46 -0800

**Comment by larkin** [comment]
wontfix.
