### ISSUE TITLE
[Notebooks] Formatted entries v2

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#6060]
**Is your feature request related to a problem? Please describe.**
Robust formatting in Notebook entries. Using Markdown: https://www.npmjs.com/package/snarkdown is a lightweight viable option.

**Describe the solution you'd like**
When editing a notebook entry, if you were to use MarkDown, when viewing the notebook entry, it would be formatted accordingly using HTML.

**Additional context**
First version is #6059

**Comment by akhenry** [comment]
Note that users have requested support for tables, so we should ensure that whatever library we use supports tables.

**Comment by scottbell** [comment]
@jvigliotta Snarkdown looks cool/clean, but they unfortunately [don't support tables](https://github.com/markedjs/marked) (yet?). So maybe something like [Marked](https://github.com/markedjs/marked) instead? They appear to support tables (a la Github)

**Comment by jvigliotta** [comment]
@scottbell Yeah I think we went with Snarkdown because of the size and functionality needs at the time, if you think Marked is a better choice then I'm on board!

**Comment by scottbell** [comment]
Tables!

https://github.com/nasa/openmct/assets/9853862/f5af6d13-385a-4ee0-b647-13a0fb343052

It looks like we ignore `<em>` in our CSS though.

**Comment by scottbell** [comment]
To test, use this markdown sample file:

[sample.md](https://github.com/nasa/openmct/files/12725477/sample.md)

and ensure it renders properly. Try to add new some new elements too like tables, text, and whitelisted and non-whitelisted links.

**Comment by charlesh88** [comment]
### Testing Notes
1. Test markdown capabilities. We need to test as many different formatting capabilities as we can. In a Notebook entry, paste the contents of this text file:
[Notebook Markdown test 1.txt](https://github.com/nasa/openmct/files/12823235/Notebook.Markdown.test.1.txt)

2. Save the entry and verify it looks like this screenshot:
![image](https://github.com/nasa/openmct/assets/1056412/c46e0c5c-074c-4d1c-bb3b-10ef5657d6ba)

3. Try editing the entry, adding and removing line breaks. Verify that unexpected line breaks aren't added and that formatting works as expected.
4. Go freeform! Try your own markdown.

**Comment by ozyx** [comment]
Verified in Testathon 10/5/23

Great job! This rocks.

**Comment by khalidadil** [comment]
Verified in Testathon on 10/05/2023

**Comment by rukmini-bose** [comment]
Verified Testathon 10/5/2023

**Comment by charlesh88** [comment]
How do I quote lines? 

> Like this, right?

**Comment by scottbell** [comment]
@charlesh88 right! From the marked demo:
> The overriding design goal for Markdown's
> formatting syntax is to make it as readable
> as possible. The idea is that a
> Markdown-formatted document should be
> publishable as-is, as plain text, without
> looking like it's been marked up with tags
> or formatting instructions.

**Comment by charlesh88** [comment]
> @charlesh88 right! From the marked demo:
> 
> > The overriding design goal for Markdown's
> > formatting syntax is to make it as readable
> > as possible. The idea is that a
> > Markdown-formatted document should be
> > publishable as-is, as plain text, without
> > looking like it's been marked up with tags
> > or formatting instructions.

Lol, that was a test... Turns out I think sanitizing Notebook entries has broken block quotes, as 
`> block quote` gets encoded as `&gt; block quote`.

**Comment by charlesh88** [comment]
Verified fixed Testathon 2023-10-05. There are a few issues and I'll file a followup issue for future fixes.

**Comment by scottbell** [comment]
Agreed, that makes sense. Dang carats
