### ISSUE TITLE
[Plot] Update pan-zoom controls

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#607]
<p>Update pan-zoom controls as suggested on pp 73-74 of UI docs attached to <a href="https://trunk.arc.nasa.gov/jira/browse/WTD-868" title="UI for setting plot bounds in a plot view" class="issue-link" data-issue-key="WTD-868"><del>WTD-868</del></a>. Focus should be on behavior under the desktop, while also making changes reusable/useful for mobile cases.</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1144
Originally created: Sun, 26 Apr 2015 11:16:42 -0700
Updated: Thu, 21 Jan 2016 15:05:19 -0800

**Comment by VWoeltjen** [comment]
Migrated comment, from @VWoeltjen:
<blockquote>
<p>Note that there is still some ambiguity in the referenced UI docs around these gestures (both a click-drag based). One recommendation:</p>

<ul class="alternate" type="square">
	<li>Behave as marquee zoom with no modifier selected (current behavior)</li>
	<li>Behave as drag-style pan with a modifier key (e.g. control)</li>
	<li>Behave as plain zoom when scroll wheel is used</li>
</ul>


<p>These alternatives need to be reviewed with Charles for UX before implementing</p>
</blockquote>

**Comment by VWoeltjen** [comment]
Migrated comment, from @VWoeltjen:
<blockquote>
<p>Mark's suggestion from sprint-planning 4/27/2015:</p>

<ul class="alternate" type="square">
	<li>Instead of dragging in plot area for pan, drag axis labels
	<ul class="alternate" type="square">
		<li>Drag is constrained to axis where drag initiated, unless user exceeds some certain plateau, then it should be active on both axes</li>
	</ul>
	</li>
	<li>Scroll wheel for zoom in the plot area (both axes, centered on mouse hover)</li>
	<li>Scroll wheel for zoom per-axis when done over plot labels</li>
</ul>

</blockquote>

**Comment by larkin** [comment]
Zoom is supported.  Closing this.
