### ISSUE TITLE
Related telemetry for imagery not received in realtime mode

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#6074]
#### Summary

Originally described in VIPEROMCT-225 

Related telemetry for imagery is not being received in realtime mode due to changes made in [this PR](https://github.com/akhenry/openmct-yamcs/pull/217). This manifests as the Compass Rose not showing up for streaming imagery in realtime mode (either local clock or remote clock).

#### Expected vs Current Behavior

Related Telemetry for streaming imagery should be received correctly, the compass rose should show up if the appropriate Related Telemetry is present

#### Steps to Reproduce

1. Navigate to our testing environment
2. Switch to either local clock or remote clock mode
3. View streaming imagery from YAMCS
4. Wait for an image to stream in
5. Observe console errors
6. Observe there is no compass rose

#### Environment

* Open MCT Version:  2.1.5-SNAPSHOT
* Deployment Type:  openmct-yamcs
* OS: MacOS
* Browser: Chrome / any

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment]
# Testing Instructions

- Follow the above repro instructions.
- In realtime mode (local or remote clock) verify that compass rose appears in images as they stream in
- Also in realtime mode, verify that compass rose appears in previous thumbnails
- Verify that compass rose still appears in fixed time mode

**Comment by unlikelyzero** [comment]
To be tested on 2.1.4-ERT and 2.1.5

**Comment by michaelrogers** [comment]
Fix verified on 2.1.4 on the development and test environments. The compass rose appears for both the current image as well as historical images.
