### ISSUE TITLE
[Plot] long parameter names cut off in legend

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#609]
<p>the legend on the panel gets cut off when the parameter names are long.  See attachment</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1414
Originally created: Tue, 30 Jun 2015 09:49:01 -0700
Updated: Thu, 21 Jan 2016 14:51:20 -0800

**Comment by VWoeltjen** [comment]
Migrated comment, from @VWoeltjen:
<blockquote>
<p>Specifically applies to plots in layouts (or at least, that's the most realistic situation into which a user would run into this)</p>
</blockquote>

**Comment by VWoeltjen** [comment]
Migrated comment, from @charlesh88:
<blockquote>
<p>Keeping as user request; relates to <a href="https://trunk.arc.nasa.gov/jira/browse/WTD-1428" title="Design a good solution for plot legends" class="issue-link" data-issue-key="WTD-1428">WTD-1428</a>.</p>
</blockquote>

**Comment by charlesh88** [comment]
Relates to #584

**Comment by charlesh88** [comment]
[Updated UI is here](https://drive.google.com/open?id=0B0v27OM1JkSeR001RFJZMk43QVk) starting at pg. 84.

**Comment by charlesh88** [comment]
Closing this as covered by #584.
