### ISSUE TITLE
Dragging a series from the tree directly to the 2nd y axis throws errors

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#6096]
#### Summary
Dragging a series into a multiple-y-axis supporting overlay plot's 2nd y axis group does not work.

#### Expected vs Current Behavior
Expected: The series should be added to the top of the 2nd y axis bucket
Actual: Error is observed as follows:
```
[Vue warn]: Error in v-on handler: "TypeError: this.elementsCache[keyString] is undefined"

found in

---> <ElementItemGroup> at src/ui/inspector/ElementItemGroup.vue
       <PlotElementsPool> at src/ui/inspector/PlotElementsPool.vue
         <Pane> at src/ui/layout/pane.vue
           <Multipane> at src/ui/layout/multipane.vue
             <Inspector> at src/ui/inspector/Inspector.vue
               <Pane> at src/ui/layout/pane.vue
                 <Multipane> at src/ui/layout/multipane.vue
                   <Layout> at src/ui/layout/Layout.vue
                     <Root> [vue.js:634](webpack://openmct/node_modules/vue/dist/vue.js?7193)
TypeError: this.elementsCache[keyString] is undefined
    updateCacheAndMutate PlotElementsPool.vue:269
    moveTo PlotElementsPool.vue:257
    group PlotElementsPool.vue:35
    VueJS 4
    emitDrop ElementItemGroup.vue:91
    VueJS 39
    applySearch PlotElementsPool.vue:230
    applySearch PlotElementsPool.vue:229
    addElement PlotElementsPool.vue:217
    emit CompositionCollection.js:342
    #emit CompositionCollection.js:338
    add CompositionCollection.js:227
    load CompositionCollection.js:243
    load CompositionCollection.js:243
    showSelection PlotElementsPool.vue:152
    mounted PlotElementsPool.vue:118
    VueJS 19
    mounted BrowseBar.vue:248
    emit index.js:137
    edit Editor.js:44
    edit BrowseBar.vue:290
    click BrowseBar.vue:133
    VueJS
```
### Steps to Reproduce
1. Create a Sine Wave Generators and a State Generator
2. Create an overlay plot that supports multiple y axes
3. Drag one sine wave generator to the plot and save it
4. Edit the Overlay plot so that the elements pool is visible
5. Drag the State Generator directly on top of the 2nd y axis bucket/group
6. Observe the error above.

#### Environment

* Open MCT Version: Feature branch - multiple y axes
* Deployment Type: Local
* OS: All
* Browser: All

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by unlikelyzero** [comment]
@shefalijoshi @ozyx should this be on the feature branch Milestone?

**Comment by ozyx** [comment]
Good catch @shefalijoshi. Missed this one in the requirements.

**Comment by akhenry** [comment]
Verified fixed.
