### ISSUE TITLE
[Context Menu] Implement 'Unlink' action

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#610]
<p>Implement 'Unlink' action as described in attachment to <a href="https://trunk.arc.nasa.gov/jira/browse/WTD-965" title="[Object Model] Extend object model to distinguish moves/links" class="issue-link" data-issue-key="WTD-965"><del>WTD-965</del></a> and expose this in the Context Menu for domain objects in the Browse tree.</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-970
Originally created: Fri, 27 Feb 2015 15:42:15 -0800
Updated: Thu, 21 Jan 2016 15:08:41 -0800

**Comment by VWoeltjen** [comment]
Migrated comment, from @VWoeltjen:
<blockquote>
<p>Note that UI docs linked from <a href="https://trunk.arc.nasa.gov/jira/browse/WTD-1053" title="Move / Copy / Link user experience requirements and UI design" class="issue-link" data-issue-key="WTD-1053"><del>WTD-1053</del></a> should supersede the issue description above; decomposition of <a href="https://trunk.arc.nasa.gov/jira/browse/WTD-965" title="[Object Model] Extend object model to distinguish moves/links" class="issue-link" data-issue-key="WTD-965"><del>WTD-965</del></a> preceded completion of Move/Copy/Link design</p>
</blockquote>

**Comment by charlesh88** [comment]
Not sure what this issue wants to do, even after reviewing original Jira links. Is this something we still want / need?

**Comment by larkin** [comment]
This is the same as "remove," and is a wontfix.
