### ISSUE TITLE
[Elements Pool] Previewing a plot element shows empty plot and throws errors

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#6107]
#### Summary

In edit mode on a Stacked or Overlay plot, clicking on a Plot element in the Elements Pool to preview shows an empty plot and throws errors if using remote telemetry.

Seems that the `start` and `end` values for time are not passed along to the request so the request fails:
![image](https://user-images.githubusercontent.com/9259993/211410517-244f606f-5459-46af-afaa-340e7ffd50a3.png)

Viewing telemetry in table format, however, does succeed.

#### Expected vs Current Behavior

Plots should be displayed correctly when previewed from clicking on the element in the Elements Pool

#### Steps to Reproduce

1. Create an Overlay Plot or a Stacked Plot
2. Drag some telemetry into it (SWG or otherwise)
3. In Edit Mode, click on a series in the Elements Pool
4. Observe an empty plot is displayed
5. If using YAMCS telemetry, notice errors thrown in the console

#### Environment

* Open MCT Version:  `2.1.6-SNAPSHOT`
* Deployment Type:  local, openmct-yamcs
* OS: MacOS
* Browser: Chrome

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information

https://user-images.githubusercontent.com/9259993/211412133-6473d131-b0b9-4f27-bc60-831164d73da3.mov

**Comment by ozyx** [comment]
Verified fixed! Testathon 2-13-2023

Tested preview on Overlay Plots and Stacked Plots, and with multiple different telemetry types. Snapshots in preview also worked as expected.

**Comment by rukmini-bose** [comment]
Verified Fixed Testathon 3/20/2024
