### ISSUE TITLE
Use factories for mocking domainObjects and capabilities

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#611]
<p>Our unit tests contain a lot of repetitive boilerplate for mocking domain objects and over time many different mocking methods have been used.  A large amount of time is spent mocking domain objects which reduces the time available for testing code.  The inconsistency of object mocking also means that bugs may be hidden because the mock code is not up-to-date.</p>

<p>A DomainObjectFactory function would help create mock domain objects quickly.  Similarly, a CapabilityFactory function could be used to generate capabilities for domain objects in a lightweight fashion.</p>

<p>The entanglement bundle adds an initial version of DomainObjectFactory, this could be moved into a core bundle and built upon for future test suites.</p>

<p>Implementing these would increase the speed at which we can write and test new code and allow us to ensure our unit tests are implemented consistently across the code base.</p>

<p>The estimate for this issue depends on how much of our test code we would refactor in the first pass.  We have a few choices:</p>

<ul>
    <li>migrate all specs to use the new factory</li>
    <li>don't migrate any specs, use factory for all new specs.</li>
    <li>some mix of migrating specs and keeping others.</li>
</ul>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1259
Originally created: Fri, 12 Jun 2015 11:08:03 -0700
Updated: Thu, 21 Jan 2016 14:56:12 -0800

**Comment by larkin** [comment]
closing as wontfix.  we have other test priorities.
