### ISSUE TITLE
Labeled grid for Imagery

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#6114]
Imagery overlay layer art. PNG attached, will add SVG later.

![imagery grid 4x4](https://user-images.githubusercontent.com/1056412/211954226-af99f601-dc3f-4015-b572-6dfbd46def5e.png)

**Comment by charlesh88** [comment]
Here's a better SVG version, created at https://codepen.io/charlesh88/pen/MWBmQbW?editors=1010 using https://docs.google.com/spreadsheets/d/1B8aRNfwquDrcdPlakpTpGpVF6QAImNFUT61JvJhnk54/edit#gid=454873104

![imagery-grid-4x4-v3](https://user-images.githubusercontent.com/1056412/211966593-f4fa1188-d547-4897-b6eb-3745f10576c7.svg)

**Comment by charlesh88** [comment]
Also need to modify the layers CSS to set layer opacity at 0.7 or 0.8 instead of 0.5.

**Comment by akhenry** [comment]
Totally missed this, this is awesome, thanks!

**Comment by charlesh88** [comment]
### Testing Notes
![Screen Shot 2023-01-24 at 2 57 28 PM](https://user-images.githubusercontent.com/1056412/214439807-76b96d1a-22d6-41d0-ab35-b66cde7a7c25.png)

1. Nav to an Imagery view. 
2. Hover over the image, and click the Layers control (orange arrow) to show the image's layers menu. Select the grid option.
3. Verify that a 4 x 4 is laid over the image.
4. Verify that the grid scales proportionally as the image size is changed.
5. Verify that the grid stays in register with the image when zooming and panning.
6. Use the Layers control to hide the grid by clicking that option again; verify that the grid is hidden.

**Comment by akhenry** [comment]
Even at an opacity of 1 it has been determined that the grid is difficult to see on SLOG images. Some investigation is needed to determine the best way to differentiate the grid from the base image.

**Comment by ozyx** [comment]
Verified -- Testathon 03-09-2023

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 03/09/23
