### ISSUE TITLE
[Browse] Show bread-crumb in title bar

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#612]
<p>Show a bread-crumb description of a domain object's canonical location in the title bar in Browse mode. See attachment to <a href="https://trunk.arc.nasa.gov/jira/browse/WTD-965" title="[Object Model] Extend object model to distinguish moves/links" class="issue-link" data-issue-key="WTD-965"><del>WTD-965</del></a> for a summary of how this location is defined.</p>

<p>Clicking on a bread-crumb element should perform a navigate action.</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-975
Originally created: Fri, 27 Feb 2015 15:51:54 -0800
Updated: Thu, 21 Jan 2016 15:08:05 -0800

**Comment by VWoeltjen** [comment]
Migrated comment, from @VWoeltjen:
<blockquote>
<p>Note that UI docs linked from <a href="https://trunk.arc.nasa.gov/jira/browse/WTD-1053" title="Move / Copy / Link user experience requirements and UI design" class="issue-link" data-issue-key="WTD-1053"><del>WTD-1053</del></a> should supersede the issue description above; decomposition of <a href="https://trunk.arc.nasa.gov/jira/browse/WTD-965" title="[Object Model] Extend object model to distinguish moves/links" class="issue-link" data-issue-key="WTD-965"><del>WTD-965</del></a> preceded completion of Move/Copy/Link design</p>
</blockquote>

**Comment by VWoeltjen** [comment]
Migrated comment, from @VWoeltjen:
<blockquote>
<p>Need 'location' capability to drive this</p>
</blockquote>

**Comment by charlesh88** [comment]
Fixed with inclusion of breadcrumb in Inspector.
