### ISSUE TITLE
Moving a telemetry endpoint to a different y axes in an overlay plot requires navigating away from the view.

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#6128]
#### Summary
Move a series in an overlay plot from one y axis to another. Notice that the overlay plot view is not updated.

#### Expected vs Current Behavior
The y axes should update to show the series on the right y axis.

#### Steps to Reproduce
1. Create an overlay plot with 1 or more telemetry endpoints.
2. Edit the plot
3. In the elements pool move the telemetry endpoint to a different axis
4. Save the plot
5. Expect to see the telemetry endpoint on the correct y axis.
6. Observe that it continues to display on the old one
7. Navigate to a different object in the Open MCT tree and then navigate back to the overlay plot
8. The y axis change now shows correctly.

#### Environment

* Open MCT Version: feature/multiple-y-axes
* Deployment Type: VIPER testathon
* OS: Mac
* Browser: All

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by charlesh88** [comment]
Saw this problem during Testathon 2023-01-24.

**Comment by ozyx** [comment]
Verified fixed Testathon 1-31-23

**Comment by rukmini-bose** [comment]
Verified Testathon 1/31/23
