### ISSUE TITLE
Notifications Overlay Opens Automatically

### ISSUE THREAD

**Issue by rukmini-bose** [nasa/openmct#6130]
#### Summary

The notifications overlay is opening automatically and after it has opened one time before that. This can get pretty annoying for users who have opened the notifications to clear them, but are still working on the same .

#### Expected vs Current Behavior
The notifications overlay should only open when a user clicks on it from the status bar. However, I am observing that it opens up automatically when a user has opened it once in the past. 

#### Steps to Reproduce

1. Do an action that produces a notification. (For example, edit a new or current object, and then save). 
2. Click the notification in the status bar to open the overlay. 
3. Close the notification overlay. 
4. Do another action that produces a notification (Again, you can edit the same object, create a new one, or navigate to another object and edit that). 
5. When you press save, notice that the notifications overlay opens up automatically. 

#### Environment

* Open MCT Version: R 2.1.5
* Deployment Type:  Dev
* OS: 
* Browser: Chrome

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information

https://user-images.githubusercontent.com/48999852/213029796-3f79d67b-b32a-4311-a559-64d11e2b8a79.mov

**Comment by unlikelyzero** [comment]
### Testing Notes
Follow reproduction steps and video

**Comment by ozyx** [comment]
Verified fixed - Testathon 1/24/23
