### ISSUE TITLE
Operator Status Poll Option Indicator will not be available if Poll Question is set as Empty String

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#6136]
#### Summary
If a Poll Question is not set, the Poll Option Indicator will not be available to Operator Status users

#### Expected vs Current Behavior
A Open MCT Installation should be able to support a scenario with a Poll Question has not yet been asked or is set to empty.

#### Steps to Reproduce
1. Enable Operator Status Plugin
2. Set Question to ""
3. Have a user attempt to use Operator Status Indicator

#### Environment

* Open MCT Version: 2.1.5
* Deployment Type: reproducible in vanilla openmct 

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by scottbell** [comment]
An example of the bug in action

https://user-images.githubusercontent.com/9853862/213289242-d422886a-ef96-4dd5-9492-bc9d7ca2abf3.mov

**Comment by unlikelyzero** [comment]
Please wait until we've updated Yamcs to Build 7RC2

**Comment by unlikelyzero** [comment]
Verified and filed https://github.com/nasa/openmct/issues/6263
