### ISSUE TITLE
Use deferred library for mocking promises

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#614]
<p>Currently, most interfaces which return promises are mocked using synchronous promises.  This forces asynchronous execution and makes it difficult to reproduce race conditions in tests.</p>

<p>Mocks that return promises should utilize a deferred to allow for greater control of execution flow during tests.</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1258
Originally created: Fri, 12 Jun 2015 10:57:12 -0700
Updated: Thu, 21 Jan 2016 14:56:32 -0800

**Comment by larkin** [comment]
Closing as wontfix.
