### ISSUE TITLE
[Stacked Plots] Plots are not lining up properly with Multiple Y Axes in Stacked Plots

### ISSUE THREAD

**Issue by rukmini-bose** [nasa/openmct#6147]
#### Summary

When an overlay plot with multiple y-axes is added to a stacked plot, plots do not line up anymore. In addition, the y-axes names and ticks are overlapping with each other. 
<img width="933" alt="213769962-25675524-ceac-4ffd-819e-796870c92e18" src="https://user-images.githubusercontent.com/48999852/213775517-5f615e47-f3b8-4fc0-bf93-7d822071f670.png">

#### Expected vs Current Behavior

The x axes of plots within stacked plot objects should line up no matter the width of the y-axes. (AKA, if there exists a plot with multiple y-axes, ALL of the plots should adjust their widths to accommodate for this. 
<img width="1007" alt="Screen Shot 2023-01-20 at 10 21 05 AM" src="https://user-images.githubusercontent.com/48999852/213776949-ffa97e97-378b-4531-be4e-6fe8467c08c6.png">

#### Steps to Reproduce

1. Create a stacked plot. 
2. Add an overlay plot with one axis, and another overlay plot with multiple axes (specifically, one where two axes populate the left side of the plot)
3. Observe that the x axes for the plots do not line up anymore, since the y axis area for the plot with multiple y-axes  is greater in width than the plot with only one axis. 

#### Environment

* Open MCT Version: 
* Deployment Type:  
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information

Issue that came out of https://github.com/nasa/openmct/pull/6102

**Comment by charlesh88** [comment]
This is actually a serious problem and IMO should be considered as data loss, in that the axis becomes unreadable and time on the X axis in the stacked children doesn't line up and is misleading:
![Screen Shot 2023-01-24 at 2 23 01 PM](https://user-images.githubusercontent.com/1056412/214436141-0a48f7c3-429c-463d-96f3-2ea68995122c.png)

**Comment by shefalijoshi** [comment]
Testing instructions:
Add a telemetry endpoint plot to a stacked plot
Create an overlay plot with _one telemetry endpoint on yaxis 1, yaxis 2 and yaxis 3 each_.
Add the overlay plot to the stacked plot.
Create another overlay plot with one telemetry endpoint on _y axis 2 only_
Ensure that the canvases for all plots line up correctly on the left and right.

**Comment by unlikelyzero** [comment]
Verified fixed

**Comment by charlesh88** [comment]
Verified fixed Testathon 2023-02-02.
