### ISSUE TITLE
Moving the first series from a y axis bucket does not work

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#6148]
#### Summary
Moving the first of 2 or more series from one y Axis to another does not resize the remaining series in the original y axis to scale to the canvas and the ticks don't update.

#### Expected vs Current Behavior
Expect the remaining series in the original y axis to scale correctly to the canvas/ticks

#### Steps to Reproduce
1. Start with an overlay plot that has two or more series (with different y axis ranges in a given bucket.
2. Using the elements pool, move the *first* of the series to another y axis
3. Notice that the series that's left in the y axis bucket does not scale to it's y range and the ticks for that y axis don't update to reflect the change.

#### Environment

* Open MCT Version: feature/plots-multiple-y-axes
* Deployment Type: VIPER
* OS: Mac
* Browser: All

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment]
Cannot reproduce-- see attached recording:


https://user-images.githubusercontent.com/9259993/214719339-c7593a5b-f4cd-4089-8327-b5f8410fe4c8.mov

**Comment by akhenry** [comment]
Retest

**Comment by ozyx** [comment]
Verified Fixed Testathon 1-31-2023

**Comment by rukmini-bose** [comment]
Verified Testathon 1/31/2023

**Comment by charlesh88** [comment]
Testathon 2024-03-20 cannot reproduce, fixed.
