### ISSUE TITLE
[Context Menu] Implement 'delete' action

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#615]
<p>Implement a "delete" action, available in the Context Menu, which deletes (instead of just removing) a domain object.</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-971
Originally created: Fri, 27 Feb 2015 15:43:25 -0800
Updated: Thu, 21 Jan 2016 15:08:33 -0800

**Comment by charlesh88** [comment]
Clarification: Remove and Delete are meant to apply to different object types: "Delete" would apply to original objects, while "Remove" would be apply only to Links. Deleting an original object would ideally also delete all Links to that object so we don't end up with orphans.

**Comment by larkin** [comment]
as it stands, we can't implement delete as described because of potential object visibility problems.   could be re-addressed if we rethink our serverside strategy - i.e. if we provide a persistence service.
