### ISSUE TITLE
Navigating to an object from a Breadcrumb doesn't update the URL hash

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#6151]
#### Summary

When navigating to an object via a Location Breadcrumb such as those in the Grand Search's search results or in Recent Objects, the URL hash is not updated. This will block e2e tests in certain situations if we need to wait for a URL update to confirm navigation has completed. This will also cause the tree to fail to highlight the focused item as the current location does not change.

#### Expected vs Current Behavior

The URL hash should always reflect the currently focused object

#### Steps to Reproduce

1. Navigate to an object via the Location  Breadcrumb either in the GrandSearch results or in Recent Objects
2. Notice that the currently focused object changes in the object view
3. Notice that the URL hash doesn't change and no longer reflects the focused object

#### Environment

* Open MCT Version:  `2.1.6-SNAPSHOT`
* Deployment Type:  local
* OS: MacOS
* Browser: Chrome

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [x] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information

https://user-images.githubusercontent.com/9259993/213790951-fd2c4a2f-3297-4a2b-8923-ae1353794bcc.mov

**Comment by shefalijoshi** [comment]
Doesn't look like this is fixed - I still see the issue un testathon.

**Comment by ozyx** [comment]
> Doesn't look like this is fixed - I still see the issue un testathon.

Did you see this on Grand Search or in Recent Objects? There may be an edge case that;s not handled

**Comment by akhenry** [comment]
Verified fixed for me.

**Comment by shefalijoshi** [comment]
Verified Fixed!
