### ISSUE TITLE
Annotations on empty entries in notebook are lost

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#6156]
#### Summary
Entries do not get persisted until text is entered. If you create a blank entry, then add an annotation/tag to it, then navigate away, the blank entry is removed and there is a misleading indication that the tag is attached to something.

#### Expected vs Current Behavior
Either the tag is also removed from view, or blank entries can be persisted. @charlesh88 , what say you?

#### Steps to Reproduce
1. create and navigate to a notebook
2. click + to add an entry
3. click on the entry element
4. click on the annotations tab in inspector
5. add an annotation/tab
6. observe the blank entry is removed from view and the tag in inspector is still displayed

#### Environment

* Open MCT Version: master
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [] Regression? Did this used to work or has it always been broken?
- [] Is there a workaround available?
- [] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [] Does this block the execution of e2e tests?
- [] Does this have an impact on Performance?

**Comment by unlikelyzero** [comment]
@davetsay is this the same as #6411 ?

**Comment by scottbell** [comment]
> @davetsay is this the same as #6411 ?

@unlikelyzero I think these are slightly different issues. One is you have to select an entry when creating a new one. The second is if you've made an entry without text, tag it, and click away, we delete the entry underneath it (and the tags now point to nothing).

**Comment by ozyx** [comment]
Verified fixed -- Testathon 4-17-23

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 04/17/23

**Comment by rukmini-bose** [comment]
Verified Testathon 4/17/2023
