### ISSUE TITLE
[Plots] Overlay plots render slower in 2.1.6 than they did in 2.1.5 without determinism

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#6159]
#### Summary
Overlay plots are now _initially_ rendering slower in 2.1.6 and without the level of determinism available in 2.1.5.

#### Expected vs Current Behavior
Overlay plots should perform as well as -- or better than -- 2.1.5. 

#### Steps to Reproduce
1. Run the overlayplots e2e tests
Note: canvas does not appear

#### Environment

* Open MCT Version: d1c7d133fc718229717ae338b95cd96b8d78e133 was about the time the tests started changing

#### Impact Check List
- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [x] Does this block the execution of e2e tests?
- [x] Does this have an impact on Performance?

**Comment by scottbell** [comment]
@unlikelyzero I'll need some help replicating this. I think the canvas is rendering for me, and the tests appear to be passing:

https://user-images.githubusercontent.com/9853862/214331047-bf72bb4f-7728-4bcd-99bc-0bd478000357.mov

I didn't see an overlayplots e2e test in `release/2.1.5` to use, but the Sinewave Generator (without annotations) seem to render about the same speed as `master`.

**Comment by ozyx** [comment]
@unlikelyzero @scottbell 
This was actually failing because of an extra `1px` padding added to plot legend items in this commit:

https://github.com/nasa/openmct/pull/6108/files#diff-2dbf1e2d399ba036135dbc9d1c8e86d1cb7ae10cf340420eee0d60b66505d3f1R667

This causes the plot to squish by 2 additional pixels, thus snapshot test failure
