### ISSUE TITLE
Handle browser refresh/navigate well

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#616]
<p>With more folks now starting to use the application, we need to start handling browser refreshes and navigation actions better. Here are my initial thoughts as a starting point, with P1 - P3 as indications of priority.</p>

<p>Refresh during editing is my biggest concern. Ideally, the app can locally cache all changes so the user can refresh at will without any ill effects or warnings. Notes below proceed as if that's not a viable option for us, and instead warn the user prior to completing the refresh or nav action.</p>

<p><b>Browse mode, refresh browser while browsing an object:</b></p>

<ul class="alternate" type="square">
    <li>Current behavior: loses context of current object, loses expand/collapse state of tree, resets to default view.</li>
    <li>Desired behavior:
    <ul class="alternate" type="square">
        <li>Object in view when refresh initiated should be restored. <span class="error">&#91;P1&#93;</span>.</li>
        <li>View type (plot, fixed position, etc.) that was selected prior to refresh should be restored. <span class="error">&#91;P2&#93;</span>.</li>
        <li>Expand/collapse state of navigation tree should be restored. <span class="error">&#91;P2&#93;</span>.</li>
    </ul>
    </li>
</ul>

<p><b>Edit mode, refresh browser or navigate elsewhere while editing an object:</b></p>

<ul class="alternate" type="square">
    <li>Current behavior:  loses all changes and puts the app into an indeterminate state - we're in edit mode, but the context for the object being edited has been lost.</li>
    <li>Desired behavior, on refresh action:
    <ul class="alternate" type="square">
        <li>Intercept with warning dialog box "WARNING: this action will lose all unsaved changes. Are you sure you want to continue?" with Yes/No or Ok/Cancel. <span class="error">&#91;P1&#93;</span>
        <ul class="alternate" type="square">
            <li>If user selects "Yes", refresh the page, staying in Edit mode with the same object in view <span class="error">&#91;P2&#93;</span>. Ideally maintain other transient settings like the current View type. If needed, fall back to losing all changes and returning to browse view on the object that was being edited <span class="error">&#91;P2&#93;</span> or refreshing to the default state. The priority is to not put the app into Edit-mode limbo <span class="error">&#91;P1&#93;</span></li>
            <li>If user selects "No", cancel refresh and dismiss the dialog box. <span class="error">&#91;P1&#93;</span></li>
        </ul>
        </li>
    </ul>
    </li>
    <li>Desired behavior, on navigation action (user clicks a bookmark, or other action that loads a URL into the browser):
    <ul class="alternate" type="square">
        <li>Same intercept as noted for Refresh case above <span class="error">&#91;P1&#93;</span>
        <ul class="alternate" type="square">
            <li>If user selects "Yes", take them to desired URL. <span class="error">&#91;P1&#93;</span></li>
            <li>If user selects "No", same as noted for this case in Refresh case above.</li>
        </ul>
        </li>
    </ul>
    </li>
</ul>

<p><b>Refreshing or navigating while in a modal overlay:</b></p>

<ul class="alternate" type="square">
    <li>Current behavior: same as Browse case above.</li>
    <li>Desired behavior: same as Browse case above, don't worry about intercepting user.</li>
</ul>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1013
Originally created: Wed, 11 Mar 2015 12:27:24 -0700
Updated: Thu, 21 Jan 2016 15:07:37 -0800

**Comment by larkin** [comment]
* Edit mode shows warnings before browser refresh, allows user to skip refresh.
* Edit mode shows warnings before navigation.
* refreshing while in a modal overlay: not resolved, but considered low priority at this time.

closing.
