### ISSUE TITLE
[Placeholder Plots] Duplicate Plot Series

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#6164]
#### Summary

Through some series of actions which have not been identified yet, Plot Series will mysteriously duplicate in the inspector and also in the tree composition.

#### Steps to Reproduce

1. Create an overlay plot
2. Drag a bunch of series into it, place them on separate y-axes etc, and then Save, 
3. Edit the object again and using the object tree, click the "Move" action on one of the elements in the plot. 
4. Notice that 2 things may happen: 
(a) The overlay plot becomes duplicated in the object tree 
(b) The element you are trying to move becomes duplicated within the Overlay Plot. 
<img width="1284" alt="Screen Shot 2023-01-25 at 3 51 30 PM" src="https://user-images.githubusercontent.com/48999852/214726813-c77dd7c9-f69d-4398-b0f7-bd907fd190bf.png">
<img width="1007" alt="Screen Shot 2023-01-25 at 4 17 37 PM" src="https://user-images.githubusercontent.com/48999852/214726822-82da44a8-b0bd-46d6-b95e-56012410ef90.png">
<img width="601" alt="Screen Shot 2023-01-25 at 4 19 16 PM" src="https://user-images.githubusercontent.com/48999852/214726823-fd7210e8-942a-48e2-bcf6-52ac1a745803.png">

#### Environment

* Open MCT Version:  2.1.6-SNAPSHOT
* Deployment Type:  testathon
* OS: MacOS
* Browser: Chrome

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by shefalijoshi** [comment]
This should be fixed by #6206
