### ISSUE TITLE
[Plots] Placeholder for loading old plots

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#6165]
#### Summary
https://github.com/nasa/openmct/issues/2321#issuecomment-1402436667

#### Steps to Reproduce

1.
2.
3.
4.

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by shefalijoshi** [comment]
Fixed by #6170

**Comment by shefalijoshi** [comment]
Testing instructions:
Try to open a plot (simple, overlay) that was create before Release 2.1.5.
Ensure that there are no console errors.

**Comment by unlikelyzero** [comment]
Verified fixed. Need to generate a build 6 display
