### ISSUE TITLE
Integrate entanglement with core commonUI, deduplicate code

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#617]
<p>There is currently duplication of code between commonUI and the entanglement bundle.  Specifically, the entanglement bundle defines a LinkAction which duplicates functionality of commonUI.</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1257
Originally created: Fri, 12 Jun 2015 10:53:17 -0700
Updated: Thu, 21 Jan 2016 14:56:48 -0800

**Comment by charlesh88** [comment]
Is this still as issue / desired as we move away from Angular?

**Comment by charlesh88** [comment]
No longer relevant.
