### ISSUE TITLE
Some Overlay Plot color swatches are not updating while editing

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#6176]
#### Summary
![Screen Shot 2023-01-24 at 3 27 02 PM](https://user-images.githubusercontent.com/1056412/214444272-517e3a77-229d-4088-845e-460aec018f20.png)
While editing an Overlay Plot, trying to manually change the color of a plot series doesn't update the axis swatches (orange arrow) and the current color swatch indicator (green arrows) in the Inspector's picker. Note that the legend swatches (blue arrows) and plot traces _do_ get updated. Saving the plot and then editing will update the swatches that previously didn't.

#### Expected vs Current Behavior
All related color swatches should update while editing as the user makes changes.

#### Steps to Reproduce

1. Create a new Overlay Plot and add some telemetry elements to it.
2. In Plot Series, change the color of that series.
3. Observe the problem as noted above.

#### Environment

* Open MCT Version:  2.1.6-SNAPSHOT
* Deployment Type:  /testathon
* OS: Mac
* Browser: Chrome

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [x] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by rukmini-bose** [comment]
Verified Testathon 2/6/23. Plot swatches are being updated in real-time

**Comment by ozyx** [comment]
Testathon 02-06-2023

Mostly fixed. Blue and orange arrow swatches update in real time, green arrow (swatch in inspector) does not update.

We should close this and split off the inspector swatch into its own issue
