### ISSUE TITLE
[Stacked Plot] Removing a plot from the elements pool is removing the wrong one

### ISSUE THREAD

**Issue by rukmini-bose** [nasa/openmct#6178]
#### Summary

https://user-images.githubusercontent.com/48999852/214450768-101817dc-c8f7-4509-a5b6-ba8909a045b9.mov

When removing a plot from a stacked plot using the Elements Pool, the wrong one is being removed. 

In the video, I have added 2 plots to the Stacked Plot: (1) Overlay Plot with 4 elements (2) Sine Wave Generator. 
I am attempting to remove the Sine Wave Generator from the Stacked Plot. Upon clicking the delete confirmation button, notice that the Overlay Plot has disappeared from the canvas. Instead, the Sine Wave Generator still stands.

#### Expected vs Current Behavior

When there are multiple plots in a stacked plot and we want to remove one, we expect the plot we select to remove to successfully disappear. Instead, we are seeing another element from the stacked plot being removed. However, if we refresh the page, the changes are applied successfully– the correct element is removed from the Stacked Plot

#### Steps to Reproduce

1. Create a Stacked Plot and add 2 or more plots to it. 
2. Delete one of the plots from the Elements Pool (make a note of which one you are deleting). 
3. After hitting the delete confirmation button, notice that while the elements pool has removed the correct plot, the canvas has not.

#### Environment

* Open MCT Version:  2.1.6
* Deployment Type:  Testathon
* OS:
* Browser: Chrome

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by akhenry** [comment]
Yikes. Good catch.

**Comment by akhenry** [comment]
### Testing notes

1. Follow reproduction steps in original issue and confirm that the correct plot trace is being removed
2. Repeat reproduction steps for an overlay plot and confirm that the correct plot trace is being removed
3. Repeat reproduction steps for some non-plot objects, like tables, LAD tables, etc. and confirm that the correct child is being removed.

**Comment by ozyx** [comment]
Verified Testathon 1-31-2023

Removal from stacked plots, telemetry tables, overlay plots, and LAD tables were tested, all looks good

**Comment by michaelrogers** [comment]
Fix verified during testathon 01/31/2023.
