### ISSUE TITLE
[Search] Increase the debounce timeout on search

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#6179]
**Is your feature request related to a problem? Please describe.**
Search debounce is a little aggressive right now and results in multiple requests being fired off even when I am typing quite quickly. This results in a lot of unnecessary hits on back-end services, and slows down the UI.

eg.

Typing the word "notebook" into the search input results in a request for every single letter that I type in. Many of them are cancelled, however not all.

```
{selector: {model: {name: {$regex: "(?i)n"}}}}
{selector: {model: {name: {$regex: "(?i)no"}}}}
{selector: {model: {name: {$regex: "(?i)not"}}}}
{selector: {model: {name: {$regex: "(?i)note"}}}}
```
**Describe the solution you'd like**
We should debounce user input at a much slower rate than we currently are to reduce backend requests.

On this topic, I am curious about what happens when results arrive out of order (eg a search for `n` might take a lot longer to return than a search for `notebook`. Some investigation should be performed to ensure we are only ever showing the most recent search results.

**Comment by akhenry** [comment]
Classifying as critical due to performance implications and user confusion.

**Comment by scottbell** [comment]
To test:

1. Bring up network panel and wait for page to load.
2. Type quickly in search for an object you know exists
3. Ensure only one network request for `_find` goes to CouchDB (not including a preflight request)

**Comment by akhenry** [comment]
Verified fixed. Can confirm that joy was sparked.

**Comment by akhenry** [comment]
Found a separate issue with search and filed a followup - https://github.com/akhenry/openmct-yamcs/issues/288
