### ISSUE TITLE
Design a good solution for plot legends

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#618]
<p>Related to <a href="https://trunk.arc.nasa.gov/jira/browse/WTD-1386" title="Plot legends display poorly" class="issue-link" data-issue-key="WTD-1386"><del>WTD-1386</del></a></p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1428
Originally created: Wed, 1 Jul 2015 10:42:10 -0700
Updated: Thu, 21 Jan 2016 14:50:11 -0800

**Comment by VWoeltjen** [comment]
Migrated comment, from @charlesh88:
<blockquote>
<p>We need to come up with a better solution for plot legends that works when the plot is small in a layout, large in its own view, handles a varying number of legend items well, and doesn't potentially hide legend items that are in limit violation.</p>

<p>The current UI design is not be covering all relevant use cases. I'm specifically concerned about telem elements in a limit violation state that might be hidden if not in the initially visible area of the legend. On the suggestion in <a href="https://trunk.arc.nasa.gov/jira/browse/WTD-1386" title="Plot legends display poorly" class="issue-link" data-issue-key="WTD-1386"><del>WTD-1386</del></a> that all legend items should be visible with the plot filling the remaining area, this solution has a serious challenge in that the plot area would have to dynamically compress or expand its height depending on the number of legend items and how they are wrapping at any given time - we can't use the browser's layout engine for this. This will also really suck when the plot element is small in a layout.</p>

<p>Ideas may include only enumerating legend items when the plot element is of sufficient size - if legend items are hidden, the user can mouse over a plot line to display its legend. The legend area in this case may be collapsed, with a single line of small icons showing if limit violations are occurring. The user would be able to expand the legend area to then see all legend items.</p>

<p>Recommendation is to discuss desired behavior with user team members (Mark, Robert, etc.) to determine the best solution here. Will file a separate issue to address this.</p>
</blockquote>

**Comment by larkin** [comment]
Pete and Charles to meet remote Thursday, onsite Monday to discuss and move forward.

**Comment by charlesh88** [comment]
[Updated UI is here](https://drive.google.com/open?id=0B0v27OM1JkSeR001RFJZMk43QVk) starting at pg. 84.

**Comment by charlesh88** [comment]
Made progress on this during Stross, but am not yet finished documenting what we discussed. Will bring this over into Tiptree.
