### ISSUE TITLE
Visual tweaks to Recently Viewed items

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#6180]
**Is your feature request related to a problem? Please describe.**
The current design approach for Recents with the large icons, in the tree context, make them look too disparate from their counterparts in the rest of the tree. Additionally, when there is no pathway beneath the object name, the design is awkward and takes up useful space.

![Screen Shot 2023-01-24 at 4 53 20 PM](https://user-images.githubusercontent.com/1056412/214455440-4d147447-34d1-42b8-bbe4-d70ecd8f01db.png)

**Describe the solution you'd like**
Size the object icon down, and visually center the alignment with its label to make it look more like a tree item.

![Screen Shot 2023-01-24 at 4 52 06 PM](https://user-images.githubusercontent.com/1056412/214455273-cf6ab644-7c0a-4933-a2cd-75c7d0e6fa47.png)

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 01/31/2023

**Comment by charlesh88** [comment]
Verified fixed Testathon 2023-01-31.
