### ISSUE TITLE
Detect and respond to device abilities

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#619]
<p>Allow the system to respond to a given user's device type when they are engaging in or near high-performance activities or elements (like plots) on a device that may not be capable of adequately rendering the element. For example, a well equipped desktop machine may be capable of rendering 1000 plot lines at a fidelity of 10Hz, while this may choke a tablet's processor, resulting in poor rendering performance. The goal of this requirement is to ensure that the overall responsiveness of the application and the user's device is not compromised, and that the user is aware of the fidelity of what they are viewing.</p>

<p>This may take several forms: the simplest of which is to detect the user's device type and compare against a known set of types (iPhone, Android phone, tablet, etc.) and displaying a message that their device may not be capable of rendering an element or elements. A more advanced solution might see the system displaying a warning and rendering a plot at a fidelity below the defined acceptable minimum, or not rendering a plot at all.</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-30
Originally created: Wed, 20 Nov 2013 10:48:39 -0800
Updated: Thu, 21 Jan 2016 15:22:42 -0800

**Comment by VWoeltjen** [comment]
Migrated comment, from @charlesh88:
<blockquote>
<p>Jay: take low impact approach here of showing a notification per device type, instead of a more intense programmatic approach. </p>
</blockquote>

**Comment by larkin** [comment]
Closing as wontfix.  We can address this for specific issues as they are encountered.  We can revisit this when we start getting requirements for expected performance / usage on mobile devices.
