### ISSUE TITLE
Possible memory leak in Object API

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#6193]
#### Summary
The object API will temporarily create a mutable in order to refresh an object's model. This is to make sure all holders of that object get a fresh model and we are not maintaining multiple different versions of a model in memory.

Whenever a mutable is created however, it must be destroyed by the code that created it. It does not appear that this is happening currently, so this is a potential source of memory leaks that should be fixed.

We should also investigate why we have logic checking whether an object returned by a provider is a mutable. Objects returned by `.get()` should never be mutable, this is why we have a distinction between `.get()` and `.getMutable()`

* Open MCT Version: 2.1.6

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [x] Does this have an impact on Performance?

**Comment by akhenry** [comment]
Filing is critical because of the impact of memory leaks on performance.

**Comment by ozyx** [comment]
Code was originally introduced [here](https://github.com/nasa/openmct/commit/ea8c9c7cc8342f18d1691e897e9785b041ca5eed)
