### ISSUE TITLE
MoveAction fails to save transactions in some circumstances

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#6197]
#### Summary

There's a codepath where MoveAction can fail to save a transaction, causing the next transaction to fail to start.

#### Expected vs Current Behavior

MoveAction should clean up after itself.

#### Steps to Reproduce

1. Create a folder
2. Create another folder
3. Create a clock within one of the folders
4. With the empty folder focused, right click on the Clock in the tree and select "Move"
5. Move the clock to "My Items"
6. Right click the clock again
7. Move
8. Move the clock anywhere else
9. Notice console errors about failing to start another transaction

#### Environment

* Open MCT Version:  2.1.6-SNAPSHOT
* Deployment Type:  local
* OS: MacOS
* Browser: Chrome

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by unlikelyzero** [comment]
### Testing Notes
Follow reproduction steps

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon 1/31/23

Moved that thin allllll over the place. No issues.

**Comment by khalidadil** [comment]
@ozyx Should the clock in the example be removed from recent items?

**Comment by rukmini-bose** [comment]
Verified Fixed 1/31/2023. don't see any of those console errors that I ran into in the past

**Comment by ozyx** [comment]
> @ozyx Should the clock in the example be removed from recently viewed?

Yes, this is expected and a caveat of how the Move action is implemented. Recent Objects listens to composition remove events for objects within the recents list. Since the Move action is a composition remove/add, the clock gets removed from recent items. I don't know of a fix for this, but we should log it somehow so we can prioritize it
