### ISSUE TITLE
Vue warnings after Recent Objects target animation ends

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#6201]
#### Summary

Title says all

#### Expected vs Current Behavior

No vue warnings

#### Steps to Reproduce

1. Click on an object to populate the Recent Objects list
2. Click the target button for the object
3. See the object highlight and flash
4. Once the animation ends, notice vue warning(s) in the console:
![image](https://user-images.githubusercontent.com/9259993/214910687-b92ef4f9-eeac-4017-9748-e7c4f5cab080.png)

No functional impact.

#### Environment

* Open MCT Version:  2.1.6-SNAPSHOT
* Deployment Type:  local
* OS: MacOS
* Browser: Chrome

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment]
# Testing Instructions
1. Open console
2. In recent objects, use the "target" button to scroll to and highlight an object in the tree
3. Wait until animation ends and confirm no vue warnings pop up in the console

**Comment by michaelrogers** [comment]
Fix verified during testathon on 2022-02-02. No console errors were observed when the target button is triggered. Additionally, spamming the target button and interrupting and existing animation does not cause any problems and works as expected.
