### ISSUE TITLE
[Notebook] Links are sometimes not formatted

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#6202]
#### Summary

Sometimes when pasting in links you can get into a state where urls aren't formatted/purged of tags. Needs more investigation and a fix.

#### Expected vs Current Behavior

Should always work anytime an entry is edited in any way.

#### Steps to Reproduce

1. Copy and paste a whitelisted url (domain ending in nasa.gov) link in
2. To exit click rapidly in a blank area underneath the entries, notice the text is not formatted

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by jvigliotta** [comment]
Looks like the issue was that links were being saved in the configuration for entries unnoticed because they are always formatted in the view. The fix is to sanitize before saving AS well.

**Comment by jvigliotta** [comment]
## Testing
- follow the repro steps
- in the console, `console.log(await openmct.objects.get([notebookKeyString]))` 
- go to `configuration.entries.[randoUuid].[anotherRandoUuid]` and verify there are no tags in the entries

**Comment by shefalijoshi** [comment]
This doesn't appear to be working. This is what I see:
![image](https://user-images.githubusercontent.com/5247066/217110222-a4113d6f-8b0b-4b3c-b79b-2af2480d5cd6.png)

**Comment by akhenry** [comment]
@shefalijoshi URL highlighting only works for whitelisted URLs. In our test environment anything that ends in `.nasa.gov` should work.

**Comment by shefalijoshi** [comment]
A couple of things are happening here:

1. A new link that I add does highlight and i am able to click it just fine.
2. If I navigate away to a different object in the tree and return to my notebook, now the URL is not highlighted
3. If I select the URL entry and delete everything from that entry so that it is empty, then press enter or click away from the empty entry, the entry text/url comes back. :/

**Comment by akhenry** [comment]
Oh, dang, yeah, URLs do not get highlighted when you nav away and back.

**Comment by akhenry** [comment]
Not fixed for reasons above.

**Comment by khalidadil** [comment]
I'm seeing the same issues as @shefalijoshi here

**Comment by unlikelyzero** [comment]
Fix #2 ignore the rest (even if you're in there)

**Comment by rukmini-bose** [comment]
Testathon 2/13: 
Notebook links are not working in Shift Logs after the page has been committed. 
<img width="1109" alt="Screen Shot 2023-02-13 at 2 29 19 PM" src="https://user-images.githubusercontent.com/48999852/218589076-dff5e112-3988-41ee-938b-0008cab423e3.png">

**Comment by ozyx** [comment]
Verified fixed -- Testathon 2-15-2023

**Comment by rukmini-bose** [comment]
Verified 2/15/23 yay
