### ISSUE TITLE
[Plots, Annotations] Annotation gesture not working consistently

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#6207]
#### Summary
When in real-time mode, using option-shift drag to select plot points to annotate works inconsistently:
1. When the plot is not paused, option-shift drag does a zoom and pauses the plot, but doesn't select any points.
2. When the plot is paused, the gesture works as expected and selects points for annotation.

#### Expected vs Current Behavior
The gesture needs to work consistently when the plot if not paused. Solutions, in order of preference:
1. If the plot detects an option-shift drag gesture, immediately pause the plot (and show it paused with orange border, etc.) and allow the annotation gesture to proceed. Once a mouse-up event occurs, the plot stays paused until the user unpauses it, and user is able to add annotations. By far, this is a the preferred solution.
2. Do not allow the option-shift drag gesture unless the user pauses the plot first. This is much less desirable as a solution than bullet 1 above.

#### Environment

* Open MCT Version:  2.1.6-SNAPSHOT
* Deployment Type:  /testathon
* OS: Mac
* Browser: Chrome/any

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment]
Verified Fixed - Testathon 3/14/2023 🥧

maybe dupe of https://github.com/nasa/openmct/issues/6294 ?

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 03/14/23
