### ISSUE TITLE
[Plot] Unable to annotate the plot view of a Telemetry Point

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#6209]
#### Summary
When a user navigates directly to the plot view of a telemetry point (this is the default view of a telemetry point) and attempts to annotate it, the annotation is not created, and an error appears in the JavaScript console

#### Expected vs Current Behavior
The annotation should be created and shown in the plot. Although Telemetry Points are immutable annotating them is expressly supported by our data architecture.

The issues is almost certainly occurring when we attempt to update the `targetDomainObjectAnnotated` timestamp on the Telemetry Object itself. We need some guard code to not attempt this if the object is immutable.

#### Steps to Reproduce
1. Navigate to a an immutable Telemetry Object (SWG won't work for this purpose, they are mutable)
2. You should see a telemetry plot.
3. Pause the plot and select some points to annotate.
4. In the inspector, click on the Annotations tab
5. Select a tag to add to the plot
6. Note that the selected tag  does not get updated
7. Open the JavaScript console and observe the following error:
```
Object provider does not support saving
```

Should be reproducible with Open MCT-Yamcs

#### Environment

* Open MCT Version: 2.1.6
* Deployment Type: VIPER Test

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment]
Not fixed -- Testathon 02-02-2023

**Comment by scottbell** [comment]
> Not fixed -- Testathon 02-02-2023

This is a different issue, but manifesting as the same problem. I'm [assigning the namespace](https://github.com/nasa/openmct/blob/master/src/api/annotation/AnnotationAPI.js#L142) in `AnnotationsAPI` with the same value as the thing it's annotating. If using YAMCS, this is going to be `taxonomy`, which when saving, is going to throw an exception as the [object provider doesn't support saving](https://github.com/nasa/openmct/blob/master/src/api/objects/ObjectAPI.js#L360). I think we've got at least three options:

1. Walk through the providers in the `AnnotationsAPI` and find the first provider that supports saving. Use that provider's keyspace for newly created annotations.
2. Use the `MyItems` namespace.
3. Use `` as the namespace (which is what `MyItems` uses).
4. Have a configuration that tells OpenMCT which provider to use for persisting annotations.

I think I'm going to try for option 3 for the interim, but let let me know what you think @akhenry
