### ISSUE TITLE
[Annotations] Annotations can't be applied when data is pending

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#6210]
#### Summary
When trying to annotate in a view like a plot, if data is incoming and the plot is loading, the user is allowed to use the annotation selection gesture and Inspector UI to annotate the selected points, but the tag is never applied as it is being blocked by the incoming data.

#### Expected vs Current Behavior
Annotations should be able to be applied in a responsive and speedy manner. Applying an annotation and providing visual feedback that it has "stuck" should happen within 2 seconds at most; it seems most likely though that we need to augment the design to provide feedback of the pending state, using a spinner or some other "in progress" indicator to tell the user that something's happening. The concern here is that users will not understand the non-applied state of an annotation, and move on with their workflow - while in reality their annotation never ends up being applied.

#### Steps to Reproduce

1. Nav to a plot view that has telemetry in such that it takes some time to load. Ideally, the progress bar continues to display.
2. Pause the plot, then do an option-shift drag on some points to select them for annotation.
3. In the Inspector Annotation tab, select and apply a tag.
4. Note that while the progress bar is displayed, the tag menu will be displayed and the tag itself won't be applied.

#### Environment
 
* Open MCT Version:  2.1.6-SNAPSHOT
* Deployment Type:  /testathon
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information
Note that progress bar is not displaying, but needs to be.
![Screen Shot 2023-01-26 at 3 42 29 PM](https://user-images.githubusercontent.com/1056412/214981467-34e6b40a-eaf8-46d9-89f3-27c826f800d8.png)

**Comment by scottbell** [comment]
@charlesh88 I've tried replicating this locally with a slow YAMCS connection and am having trouble. May need to setup a meeting to see the bug in action.

https://user-images.githubusercontent.com/9853862/225309532-b19af9f0-20aa-4cda-bb29-3c77310348f7.mov


https://user-images.githubusercontent.com/9853862/225309545-10314c7a-52cf-4057-82d3-e1aea35ce4cd.mov

**Comment by charlesh88** [comment]
Tried to replicate this problem with Scott today on banner using browser "Slow 3G" throttling, but could not.
