### ISSUE TITLE
[Multiple Y-Axes] Multiple marquees when selecting with multiple series

### ISSUE THREAD

**Issue by khalidadil** [nasa/openmct#6213]
#### Summary
When making a selection for annotation or a selection for zoom in a plot with multiple series, the marquee seems to be duplicated for each y-axis. This creates a layering effect where the final selection box is very bright.

![Screen Shot 2023-01-26 at 5 45 56 PM](https://user-images.githubusercontent.com/2343076/214978944-dec4ab46-eac0-492e-8a0e-c88e054bb3ff.png)

Testing Instructions:
1. Create an overlay plot and drop in 2 telemetry sources.
2. Try drawing a marquee to zoom or to annotate the plot. The marquee should not be as dark as in the screenshot above.
3. Try moving the telemetry sources to various plot axes and annotate/zoom again to verify multiple marquees aren't being drawn.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [X] Is there a workaround available?
- [ ] Does this impact a critical component?
- [X] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment]
Verified fixed -- Testathon 4-17-23

**Comment by rukmini-bose** [comment]
Verified Testathon 4/17/2023
