### ISSUE TITLE
[Annotations] Tags in Inspector need layout/visual refinement

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#6215]
#### Summary
![Screen Shot 2023-01-26 at 3 33 12 PM](https://user-images.githubusercontent.com/1056412/214981665-d774af1d-f7b0-42ea-9299-d2b02916f144.png)

Layout and margin all should be addressed.

#### Environment

* Open MCT Version:  2.1.6-SNAPSHOT
* Deployment Type:  /testathon
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by charlesh88** [comment]
### Testing Notes
#### Reference
**Initial state**
![Screen Shot 2023-01-27 at 6 57 47 PM](https://user-images.githubusercontent.com/1056412/215238758-18e24955-de77-4c10-8572-348693f75c0b.png)
**Hover over add button**
![Screen Shot 2023-01-27 at 6 57 55 PM](https://user-images.githubusercontent.com/1056412/215238756-d867f4f8-c78a-48b2-9bdc-0c552b1abdbe.png)

#### Steps
1. Interact with tags by annotating a Notebook entry or telemetry points in a plot.
2. Verify that tags in the Inspector look like the reference image above. Note that the look of tags has been updated for consistency.
3. Verify there are no regressions as to how tags appear, like in a Notebook entry.

**Comment by ozyx** [comment]
Verified fixed --- Testathon 02-06-2023
