### ISSUE TITLE
[Notebook] Notebook URL Embedds with really long URLs make it difficult to edit entries

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#6218]
#### Summary
Noted here: https://github.com/nasa/openmct/issues/6059#issuecomment-1405818029

Really long URLs cause issues when editing entries. It's possible this applies to any long string

#### Steps to Reproduce

1.
2.
3.
4.

#### Environment
* Open MCT Version: 2.1.6

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information
<img width="471" alt="214974747-b54b7804-8918-49ba-81e9-24cd50c096af" src="https://user-images.githubusercontent.com/12446869/215159203-8e71eca9-eaa6-497d-94ec-444516238f48.png">

**Comment by depperm** [comment]
maybe related #6691

**Comment by depperm** [comment]
is this still a problem? how do you enter a hyperlink (https://www.nasa.gov/feature/day-of-remembrance-marks-20th-anniversary-of-columbia-crew-loss) in notebook that is different from text?

**Comment by scottbell** [comment]
Closing this as per #7084, we can create compact links now.

**Comment by scottbell** [comment]
BIG LINKS

https://github.com/nasa/openmct/assets/9853862/28558bd6-b939-44ed-9759-7a353b9f3356
