### ISSUE TITLE
Finalize plot control details

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#622]
<p>Discuss UX and other nuances of users interacting with data in plots via their controls. Pete has some thoughts here.</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1168
Originally created: Mon, 4 May 2015 11:03:39 -0700
Updated: Thu, 21 Jan 2016 14:59:10 -0800

**Comment by charlesh88** [comment]
Discussion had and ideas rolled into #584
