### ISSUE TITLE
Autocomplete input shows empty options list

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#6221]
#### Summary
When interacting with the autocomplete field, if the field is initially blank and if the user has typed a string that isn't matched, an empty version of the matching options list is displayed:
![Screen Shot 2023-01-27 at 6 41 13 PM](https://user-images.githubusercontent.com/1056412/215238142-90baf611-5892-4ca2-ad82-199d7ce58dc9.png)

#### Expected vs Current Behavior
The options list holder (`.c-input--autocomplete__options`) shouldn't be displayed at all unless there are one or more options to display. Maybe this could be fixed along with #6219?

#### Steps to Reproduce

1. Interact with autocomplete field in the annotations tag interface, or in the Clock object Properties dialog.
2. Blank out the input and/or type a non-matching string.
3. Observe the result as shown above which is the empty options list.

#### Environment

* Open MCT Version:  2.1.6.-SNAPSHOT
* Deployment Type:  local, all
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by rukmini-bose** [comment]
verified testathon 3/9/23

**Comment by akhenry** [comment]
Verified fixed
