### ISSUE TITLE
Timers need a stop button

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#623]
<p>Once I start a timer, there doesn't seem to be a way to ever stop it, only restart it.  Would be nice to be able to stop it when I don't need it anymore.</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1326
Originally created: Tue, 23 Jun 2015 10:15:50 -0700
Updated: Thu, 21 Jan 2016 14:51:53 -0800

**Comment by charlesh88** [comment]
We currently have a pause function; would the desired functionality be pause and set to 00:00:00

**Comment by VWoeltjen** [comment]
My expectation would be that it would go to "--:--:--" and show a Play button on hover; basically, return it to the same state it would have been in if it had just been created (with no target time specified)

Original issue was filed by @RCarvalhoNASA - any input here?

**Comment by charlesh88** [comment]
@VWoeltjen You're right, I forgot it had that state.

**Comment by RCarvalhoNASA** [comment]
Victor's expectation is also what I was looking for.

**Comment by DocJava** [comment]
For the new buttons, (Stop, Pause, Resume). What kind of implementation are we looking for? I currently have something ready but the new buttons only show in the menu. 

Do we also want them to be displayed in the hover section? If so should the hover section continue to push the clock to the right and out of view? Or is putting them with the timer text out of scope of this issue?

**Comment by charlesh88** [comment]
This is related to #438
