### ISSUE TITLE
[Overlay Plot] Turning on Log Mode and turning off Autoscale breaks the plot

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#6230]
#### Summary

Turning off autoscale and turning on log mode for a plot series, saving, and then navigating away and back again breaks the plot completely and throws a bunch of console errors.

#### Expected vs Current Behavior

Log mode should be set and autoscale should be set with sensible defaults

#### Steps to Reproduce

1. Create an Overlay Plot
2. Drag an SWG into it
3. Edit
4. Turn off autoscale
5. Observe sensible defaults populate the min and max fields
6. Turn on log mode
7. Observe the ticks change on the y axis
8. Save
9. Navigate away
10. Navigate back
11. See that the plot is completely broken, settings cannot be changed

#### Environment

* Open MCT Version: 2.1.6-SNAPSHOT
* Deployment Type:  local
* OS: MacOS
* Browser: Chrome

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information

![image](https://user-images.githubusercontent.com/9259993/215628106-14bd9622-791f-4d64-a7ed-d3a0f500fe8e.png)

https://user-images.githubusercontent.com/9259993/215628119-d3189f55-b22a-4eda-a225-71779417cd32.mov

**Comment by ozyx** [comment]
# Testing Notes
1. Create an Overlay Plot
2. Drag an SWG into it
3. Edit
4. Turn off autoscale
5. Observe fields are blank and an error is displayed. Leave them blank and ignore it.
6. Turn on log mode
7. Observe the ticks change on the y axis
8. Save
9. Navigate away
10. Navigate back
11. Verify that log mode is activated and the ticks reflect that
12. Verify that Autoscale has reverted to being activated
13. Turn off autoscale and set sensible min and max, notice the plot scale changes to reflect that.
14. Try a few different min and max values, do some bounds testing here
15. Save
16. Navigate away, navigate back
17. Confirm that plot series is still visible, plot scale is the same, log mode is still on

**Comment by michaelrogers** [comment]
FIx verified during testathon on 2023/02/09.

**Comment by rukmini-bose** [comment]
Verified Testathon 2/9/23.

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 02/09/23
