### ISSUE TITLE
[New Edit Mode] Warning messages about contextualization

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#624]
First seen in #305. Newly created objects are persisted and their location set to the composing object, but composing object has not been created yet. Ideally parent and child should be persisted together, but this is currently prevented by the inability to lookup nascent objects. Original issue below (taken from (https://github.com/nasa/openmctweb/issues/305#issuecomment-161146898)

>Partial fix on open305. Resolving this causes another problem to be tickled: The newly-created object references its parent as its location, but the actual parent does not contain it within its composition. When this gets contextualized (by the LocatingObjectDecorator) a warning is issued:

>Attempted to contextualize 18998ddb-440a-48c1-983b-0cbbb02ddab6 in 9ad4baa4-7764-4e66-8a48-84a08cd4dae3 but that object does not contain 18998ddb-440a-48c1-983b-0cbbb02ddab6 in its composition. Unexpected behavior may follow.
This is actually benign in this case. Some options:

> Check for this case from LocatingObjectDecorator, and just don't contextualize objects in this case. This should still behave correctly under nominal circumstances, but is funny logic.
Modify Edit mode such that objects created during Edit mode are not actually persisted until Edit mode completes. This means that "temporary" objects in Edit mode need to be retrievable somehow; can probably stuff this into the EditableLookupCapability.
Just live with the grumpy logging for now.
Option 1 sounds funny. Option 2 sounds most correct, but don't know how much effort to put into this with NEM on the horizon.

>Think Option 2 should be pursued, falling back to Option 3 if it is non-trivial.
@VWoeltjen 

Issue #575 should go some way to alleviating this by allowing creation and composition to happen at the same time without persisting the new object first.

**Comment by VWoeltjen** [comment]
### Note for Testing

Open Chrome's Developer Tools, switch tabs to Console. Create a Timeline, then Add some Activities to it before saving. Expect _not_ to see warning messages like:

    Attempted to contextualize 18998ddb-440a-48c1-983b-0cbbb02ddab6 in 9ad4baa4-7764-4e66-8a48-84a08cd4dae3 but that object does not contain 18998ddb-440a-48c1-983b-0cbbb02ddab6 in its composition. Unexpected behavior may follow.

**Comment by charlesh88** [comment]
Testathon 2016-07-18 Verified fixed using Victor's "Note for Testing" above.
