### ISSUE TITLE
Clear the Recent Objects list

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#6240]
It would be nice if there were a way to clear Recent Items other than clearing the localStorage cache manually. This could be a button, context action, or other, that can either partially or entirely clear the Recent Objects list.

**Comment by akhenry** [comment]
@ozyx  Can you add some testing notes please?

**Comment by ozyx** [comment]
# Testing Notes

- Go to Open MCT and navigate around a bit to populate the Recent Objects list
- Observe that there is a button in the top right corner with the same icon as "Clear Data" action
- Click it, verify that a confirmation dialog appears
- Click cancel, verify that Recent Objects is not cleared
- Click the clear button again
- Click OK
- Verify that the Recent Objects list is cleared
- Check in localStorage and verify that the recent objects key has a value of empty array
- Click around again, verify that Recent Objects populates as expected
- Click some objects in the recents list, verify that it still works as expected

**Comment by rukmini-bose** [comment]
Verified Testathon 4/17/2023

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 04/17/23
