### ISSUE TITLE
Creating multiple notifications at the same time causes duplicated keys error

### ISSUE THREAD

**Issue by 360macky** [nasa/openmct#6242]
#### Summary

If two or more notifications are created at the same time, the same timestamp is assigned to the identifiers of the notification. This will cause the error of "Duplicated keys" from Vue.

[src/plugins/notificationIndicator/components/NotificationsList.vue](https://github.com/nasa/openmct/blob/66d7c626e1e54540af6f124d6e50d941215dd5a3/src/plugins/notificationIndicator/components/NotificationsList.vue#L15)
```js
 <notification-message
  :key="notification.model.timestamp"
```

While I'm not aware of a current situation where two notifications are created at the same time, this is one possible behavior that could occur. It also **prevents creating two notifications** using OpenMCT API **without the tests failing**.

#### Expected vs Current Behavior

Creating multiple notifications with the same time should not cause a Vue error of 'Duplicated keys'.

#### Steps to Reproduce

You can also check the video of the 'Additional Information' section of this issue.

1. Try to create two notifications using the OpenMCT API
```js
openmct.notifications.error("Error message 1");
openmct.notifications.error("Error message 2");
```
2. Click on "2 Notifications" button
3. Check error in console.

#### Environment

* Open MCT Version: 2.1.6-SNAPSHOT
* Deployment Type:  Dev
* OS: Mac OS
* Browser: Google Chrome

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [x] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information

Reproduction of the error:

https://user-images.githubusercontent.com/47821093/215947258-079c5fef-1385-4fa2-b606-c953f49be8dd.mov

Error when trying to run tests creating multiple notifications:

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/47821093/215951676-a22a4147-e188-4145-9ea7-a41cda8c6c69.png">

**Comment by ozyx** [comment]
Verified Fixed - Testathon 3-14-2023 🥧

**Comment by michaelrogers** [comment]
Fix verified during testathon 03/14/2023.
