### ISSUE TITLE
Stacked Plots don't allow child selection while editing

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#6261]
#### Expected vs Current Behavior
Stacked Plots must allow child selection.

#### Steps to Reproduce

1. Edit a Stacked Plot, add at least one telemetry point.
2. While editing, click the child plot.
3. The child should select and hilite with a dashed border, but doesn't.

#### Environment

* Open MCT Version:  2.1.6-SNAPSHOT
* Deployment Type:  /testathon
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment]
Verified fixed -- Testathon 02-06-2023

**Comment by rukmini-bose** [comment]
Verified Testathon 2/6/23
