### ISSUE TITLE
Staleness doesn't work for overlay plots embedded in stacked plots

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#6265]
#### Summary

Staleness doesn't show on overlay plots embedded in stacked plots

#### Expected vs Current Behavior

Staleness indicator should show

#### Steps to Reproduce

1. Create an overlay plot
2. Create an SWG with staleness option ON
3. Drag SWG into the overlay plot
4. Create a stacked plot
5. Drag the original SWG and the overlay plot into the stacked plot
6. Watch it and observe that staleness border shows up for SWG but not the overlay plot

#### Environment

* Open MCT Version:  2.1.6-SNAPSHOT
* Deployment Type:  testathon
* OS: macos
* Browser: chrome

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information

![Pasted Graphic](https://user-images.githubusercontent.com/9259993/216435710-aa217a62-41a9-44e8-a8cd-7f220c49405d.png)

**Comment by jvigliotta** [comment]
## Testing
- follow the rerpro

**Comment by rukmini-bose** [comment]
Testathon 2/9/23. This issue has been verified, as well as well as https://github.com/nasa/openmct/issues/6109#issuecomment-1414231882
