### ISSUE TITLE
[New Edit Mode] Remove Edit mode workflow from Create action

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#628]
From #481:

> * Remove Edit mode workflow from Create action
  * Again, should be able to remove "edit" as a bundle and still be able to Create things.
  * Some approaches here - decoration, substitution (most/much creation-related code is already delegated to the CreationService, so an alternate Create action might be able to use that without redundant code). Solving #546 might open the door for a more cleanly-separated solution here.
  * Solution to #491 may be helpful here (or may do this already)

**Comment by akhenry** [comment]
> In the UI, we have an Edit button that either switches to Edit mode or shows an Edit Properties dialog. > IIRC these are two different edit actions with complementary policies. (With similar logic to this if.)

> Are there tweaks to those edit actions that would allow us to replace this if-else with a single perform('edit')? (e.g. if they both return promises for success or failure...)

@VWoeltjen from https://github.com/nasa/openmct/pull/838#discussion-diff-60992358

**Comment by akhenry** [comment]
> Again, should be able to remove "edit" as a bundle and still be able to Create things

I'm starting to think that the `CreateAction` should be part of the edit bundle. It's in browse right now, which doesn't make much sense. You can't create without editing (at the very least, you're editing the composition of the parent).

**Comment by akhenry** [comment]
### Note to Testers
This change is a refactoring of the Create action. Testing should be performed around the creation of new objects to verify that it is still functioning as intended.

**Comment by VWoeltjen** [comment]
Tested Create action for various object types during testathon 5/31/2016. Did encounter #979, but think that is not related to this issue
