### ISSUE TITLE
Plan is rendering incorrectly when in a Time Strip in a layout

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#6296]
#### Summary

In this example, the first event shown, "Panorama", has a start of 2023-12-21 20:04:18.949Z. When a Plan is in a Time Strip view within a Display or Flexible Layout it doesn't render properly: the Gantt area of the Plan when it's within a Time Strip doesn't appear to be responding to width of its container.

#### Closeup of Plan view in main view area rendering correctly
<img width="660" alt="Screen Shot 2023-02-07 at 10 56 54 AM" src="https://user-images.githubusercontent.com/1056412/217342040-7efcc240-79b3-43a6-8e4d-5f84e779c152.png">

#### Plan view in Time Strip in main view, bad render
<img width="643" alt="Time Strip in main view closeup 2 bad" src="https://user-images.githubusercontent.com/1056412/217343665-3548ffaf-5a95-4bf6-9b3f-f8b18d519e44.png">

#### Plan views and Time Strips in Flexible Layout columns layout; bad render in Time Strip Plan at bottom
<img width="1183" alt="Plans and Time Strips in Flex Layout bad" src="https://user-images.githubusercontent.com/1056412/217343568-b258c809-3679-41d3-b02a-5941e4c69ba0.png">

#### Plan views and Time Strips in Flexible Layout rows layout; bad render in all Time Strips
This is particularly visible when using a columns layout with multiple objects in a single row. Note the Plan view compressing events into the available vertical space, but the two Time Strips do not. 
<img width="1134" alt="Screen Shot 2023-02-07 at 11 31 53 AM" src="https://user-images.githubusercontent.com/1056412/217346743-b2852eda-2231-4977-9962-77e4b9d85629.png">

#### Time Strip and Plan in Display Layout; bad render in Time Strip
<img width="589" alt="Screen Shot 2023-02-07 at 11 44 08 AM" src="https://user-images.githubusercontent.com/1056412/217349625-52ef5ddb-7ae9-4706-a644-2b5d0b1a7391.png">

#### Expected vs Current Behavior
Time Strip should always display plans correctly and scale all elements visually to fit available space. We may need to institute a min width after which horizontal scrollbars would appear.

#### Steps to Reproduce

1. Add one or more Plan views to a Time Strip view. 
2. Add the Plan and the Time Strip to a Flexible Layout in columns mode. Add columns to the Flexible Layout and note that the UTC ticks and activities in Plan scale correctly, but activities in the Time Strip do not.
3. Do step 2 with a Display Layout and note same problem.

#### Environment

* Open MCT Version:  2.1.4 MMOC; 2.1.6-SNAPSHOT 
* Deployment Type:  VIPER; /testathon
* OS: Linux, Mac
* Browser: Chrome

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by akhenry** [comment]
@charlesh88 What happens if you reload? Just wondering whether it is not responding to _changes_ in the width of its container? Or it's not respecting the width of its container at all?

**Comment by unlikelyzero** [comment]
retest

**Comment by shefalijoshi** [comment]
Closing this to retest.

**Comment by ozyx** [comment]
This is still an issue. In the below screenshot, the Time Strip is rendering the Plan incorrectly (activities do not render in the correct locations). The same Plan can be seen above, which renders correctly when placed in the layout.

![image](https://user-images.githubusercontent.com/9259993/232838959-2a06f874-4f66-45b5-8cad-f64669464c13.png)

**Comment by ozyx** [comment]
Verified Fixed Testathon 7/31/23. Embedded multiple plans in a Flexible layout, everything looks great. Even set the different plans to other times using the ITCs and it worked well.

**Comment by rukmini-bose** [comment]
Verified Fixed Testathon 7/31/2023!

**Comment by charlesh88** [comment]
Testathon 2023-07-31: Verified _mostly_ fixed, but still seeing Activity overlap issues when horizontal space is compressed: activities should be forced down vertically to avoid collision but aren't in some cases:

![Screen Shot 2023-07-31 at 3 00 04 PM](https://github.com/nasa/openmct/assets/1056412/abd60bca-b42b-4b18-94d5-3ad2c9fefc14)

**Comment by ozyx** [comment]
@charlesh88 
file as a separate issue?
