### ISSUE TITLE
View Large from Elements Pool doesn't display time-based data properly

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#6299]
#### Summary
View Large from the Elements Pool doesn't display time-based data using the Time Conductor settings. This occurs for both real-time modes as well as fixed time.

#### Expected vs Current Behavior
View Large should show the same thing, no matter where it's invoked. It appears that the View Large from the Elements Pool is not the same code as used elsewhere. While this could _technically_ be considered data loss, not characterizing as such as it only happens during Edit mode in a non-critical capacity.

#### Steps to Reproduce

1. Create or edit a view that uses the Elements Pool, like a plot, Time Strip, etc.
2. Add time-based data like a numeric or Plan that displays data within the current Time Conductor bounds.
3. Click an item in the Elements pool, observe: the view will not display the data and the Y axis ticks may be seen to move around.
4. Click the same object from step 3 in the tree at left: observe that View Large modal will display the data properly.

#### Environment

* Open MCT Version:  2.1.4, 2.1.6
* Deployment Type: MMOC, /testathon
* OS: Linux, Mac
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment]
I think this might be a dupe of https://github.com/nasa/openmct/issues/6107 ?

**Comment by khalidadil** [comment]
> I think this might be a dupe of #6107 ?

Sounds like it

**Comment by charlesh88** [comment]
Closing as dupe of #6107
