### ISSUE TITLE
[New Edit Mode] Simplify SaveAction

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#630]
From #481:

> * Simplify SaveAction
  * The number of dependencies and the number of LOC here both indicate that this action has many responsibilities. Its responsibility should be simple - "persist any changes made during editing" - and any workflow-related behavior should be separated into other classes. (_Or_, say that the "Save" action is narrowly responsible defines this specific workflow, and have it act as a manager for other classes which implement the various parts of that workflow.)

**Comment by VWoeltjen** [comment]
Per #500, also want to look at & reconcile any commonality b/w AddAction and CreateAction in the context of this issue.

**Comment by VWoeltjen** [comment]
One thing I see (looking at this in the context of #656) is that there is a very early [branch](https://github.com/nasa/openmctweb/blob/5daf2f54cda893587038dece051d93722a4d2a87/platform/commonUI/edit/src/actions/SaveAction.js#L130) in how Save gets performed, depending on whether or not the object has been previously persisted. Think this could instead be split into two Save actions (perhaps with a common parent class) with complementary `appliesTo` constraints; then, each only needs to contain the logic and reference the dependencies needed for that specific Save workflow.

**Comment by larkin** [comment]
In the context of #656, the two save actions could be "Save" and "SaveAs".

**Comment by VWoeltjen** [comment]
> In the context of #656, the two save actions could be "Save" and "SaveAs".

:+1:!

**Comment by akhenry** [comment]
Addressed by #829
