### ISSUE TITLE
Imagery causes unintended scrolling of overflowed views on hover

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#6300]
#### Summary
Display Layouts with overflow (scrollbars showing) will scroll unintentionally as the user just moves their mouse cursor around and hovers over Imagery view objects. This occurs wherever the containing Display Layout occurs: main view, or itself as a frame within another layout (both types). This is making some existing ops layouts very hard to use and could represent data loss if an image is unexpectently hidden. Wondering if this was a consequence of changes effected for #5961.

#### Expected vs Current Behavior
The view should only be scrolled on direct intent from the user, via standard scrolling gestures.

#### Steps to Reproduce

1. Create or edit a Display Layout to include two more or more Imagery objects in it. Make them large, such that the layout can't fit in the available main view area. Save the layout. Put on image frame vertically below or horizontally beside the other such that both images are not fully in view without the main view overflowing and displaying its scrollbar.
2. View the layout, and size the browser window such that the layout's scrollbar appears. One image should be in view, with the other partially in view.
4. Move the cursor over the the partial image, and observe that the main view will scroll itself to bring that image into view.

#### Environment

* Open MCT Version:  2.1.4, 2.1.6
* Deployment Type:  MMOC, /testathon
* OS: Linux, MacOS
* Browser: Chrome, Firefox

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by shefalijoshi** [comment]
Possibly fixed by #6318 Please retest.

**Comment by akhenry** [comment]
@shefalijoshi  to test

**Comment by shefalijoshi** [comment]
Not fixed. :(

**Comment by michaelrogers** [comment]
## How to Test
1. Create a display layout
2. Drag two imagery objects to the display layout
3. Oversize them to the view screen (for more detail see Charles' above repro steps)
4. Save and exit edit mode
5. Move mouse between the two imagery items
6. Observe that the viewscreen has not focused/autoscrolled to the hovered image

**Comment by ozyx** [comment]
Verified fixed -- Testathon 3-14-2023 🥧
