### ISSUE TITLE
Prevent tabbing into entry inputs in Notebook

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#6312]
#### Summary
In the Notebook, for entries without any embeds, tabbing out of a new entry automatically puts the cursor into the next entry in the list, with the field in "edit" mode. This is HIGHLY undesirable; the user could very easily add extra characters or delete an entry thinking they were doing something else. _Nobody_ wants to tab between Notebook entries sequentially to edit them - in fact, they want the complete opposite.

If an entry has embeds, tabbing moves the focus between embed elements. Unclear what the utility of this is: those elements do not have a Enter key gesture that uses them.

@unlikelyzero Any accessibility or automated test considerations with this change?

#### Expected vs Current Behavior
The gesture to edit a Notebook entry must be very deliberate, the user should have to deliberately click on the text area of an entry to make it editable.

#### Solution Notes
Notebook entries are currently being set to use `tabindex="0"` - this should be changed to "-1" to actively prevent tabbing in to the input. A nice-to-have future feature would be to allow tabbing the selected entry, with a full _selection_ occurring and that entry driving the Inspector information.

#### Steps to Reproduce

1. See Summary above.

#### Environment

* Open MCT Version:  2.1.4
* Deployment Type:   MMOC
* OS:
* Browser: Chrome

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by charlesh88** [comment]
### Testing Notes
1. Populate a Notebook page with a number of entries.
2. Sort the view by Newest First.
3. Create a new entry and type some characters into it.
4. Press the Tab key. Verify that the next entry's input field does not come into focus in its active "edit" style.
5. Click into an existing entry that is followed in the list by at least one more entry. Perform step 4 again.

**Comment by davetsay** [comment]
verified

**Comment by rukmini-bose** [comment]
Verified testathon 3/9/2023
