### ISSUE TITLE
[Notebook] Double snapshot indicators

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#6316]
#### Summary

Thar be 2 of em.

#### Expected vs Current Behavior

Should just be the one.

#### Steps to Reproduce

1. Look at the snapshot indicators
2. There's 2

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information

![Screen Shot 2023-02-09 at 3 42 02 PM](https://user-images.githubusercontent.com/12013460/217964135-1c0a8800-2fb0-4975-92f9-0e856006268f.png)

**Comment by jvigliotta** [comment]
## Testing
- just, uh... make sure there's only one

**Comment by akhenry** [comment]
@michaelrogers  to test

**Comment by michaelrogers** [comment]
Fix verified on testathon on 02/13/2023. Only a single icon is shown.
