### ISSUE TITLE
[Time Conductor] Refactor ConductorRepresenter to be less sensitive to specific details of DOM

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#632]
From #481:

> * Refactor ConductorRepresenter to be less sensitive to specific details of DOM
  * This was really an existing flaw of that representer. Think this should be easier after the API Refactor, particularly once we have a better set of interfaces for dealing with UI components

**Comment by VWoeltjen** [comment]
Assigning to @akhenry; we expect this issue to become obsolete after refactoring related to real-time/historical integration with time conductor

**Comment by larkin** [comment]
Closed with new TC integration.
