### ISSUE TITLE
LAD Tables should disable user-select

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#6321]
#### Summary
The LAD Table elements support a context-click and Actions menu to support various operations. Users can also select the text of more than one row - but context-clicking still invokes the Actions menu, as if the available actions can apply to all the selected rows, which is not correct.

#### Expected vs Current Behavior
User-select should be set to `none` for the rows of this view.

#### Environment

* Open MCT Version:  2.1.4, 2.1.6
* Deployment Type:  MMOC, local
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by charlesh88** [comment]
### Testing Notes
1. Create or edit a LAD Table with more than one row of elements in it.
2. Hover over the table, verify that a text-selection cursor is NOT displayed, and the row highlights.
3. Attempt to click and select the text of the table: verify this is not allowed.
4. Context-click a row in the table and verify that the Action menu displays and functions as expected.

**Comment by michaelrogers** [comment]
Fix verified during testathon on 03/30/23. All the above test cases for LAD tables work as described.
