### ISSUE TITLE
Clicking "Add Tag" and then removing an existing tag causes the "Add Tag" button to disappear

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#6330]
#### Summary

Clicking the "Add Tag" button then removing a tag causes the "Add Tag" button and dropdown to disappear completely until you navigate away and back again.

#### Expected vs Current Behavior

The "Add Tag" button and/or dropdown should not disappear.

#### Steps to Reproduce

1. Create a Notebook
2. Create an Entry in the Notebook
3. Click on the Entry
4. Click on "Annotations" tab in the Inspector
5. Click "Add Tag" and add a tag
6. Click "Add Tag" again, but don't add a tag
7. With the "Add Tag" dropdown visible, delete a tag
8. Observe that the Add Tag button and dropdown both disappear and you're unable to add any further tags.

#### Environment

* Open MCT Version:  2.1.6-SNAPSHOT
* Deployment Type:  local
* OS: any
* Browser: Chrome

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information

![openmct-issue1](https://user-images.githubusercontent.com/9259993/218334066-eb7789c8-caa1-4525-80f8-febe08ca7cb0.gif)

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 04/09/23

**Comment by michaelrogers** [comment]
Fix verified during testathon.

**Comment by rukmini-bose** [comment]
Verified testathon 3/9/23
