### ISSUE TITLE
Limit lines disappear when changing the y axis for series (navigating away and back solves the issue)

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#6338]
#### Summary
If you view an overlay plot with limit lines enabled, then change the y axis the series belongs to, the limit lines disappear.

#### Steps to Reproduce
1. Create an overlay plot with a telemetry endpoint that has limits defined.
2. Edit the plot to enable limit lines, ensure that the lines show up and save it.
3. Edit the overlay plot and move the telemetry endpoint to a different y axis (elements pool)
4. Save the change - observe that the limit lines have disappeared
5. WORKAROUND - navigate away and back to see the limit lines.

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment]
# Testing Notes

- Create an overlay plot
- Add telemetry that has limits defined (SWG should work too)
- Go into edit mode, activate limit lines for the given plot series
- Save
- Navigate away and back again
- Verify that the limit lines still show
- Go back into edit
- Go to the "Elements" tab and move the telemetry to another Y Axis
- Verify that the limit lines still show
- Navigate away and back again
- Verify that the limit lines still show

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 04/09/2023

**Comment by akhenry** [comment]
Retest with real telemetry (not SWG)

**Comment by akhenry** [comment]
Verified fixed.
