### ISSUE TITLE
[Staleness] Switching between clock modes incorrectly persists the current staleness state

### ISSUE THREAD

**Issue by michaelrogers** [nasa/openmct#6339]
Relates to #6109 

#### Summary

When staleness is currently visible in a component and the user switches clock modes, the staleness state is not cleared and persisted until new telemetry streams in.

#### Expected vs Current Behavior

Currently the staleness state is persisted between clock modes. Expected behavior is to clear the staleness state.

#### Steps to Reproduce

1. Setup a display layout containing SWG with staleness enabled
2. Wait until staleness is triggered ~10 seconds
3. Switch clock modes from Local to Remote
4. Observe the staleness styling is still present

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by michaelrogers** [comment]
https://user-images.githubusercontent.com/7417521/218593648-f72945d8-98e4-4886-bc0a-c2f1ec5f0089.mov

**Comment by unlikelyzero** [comment]
Only a blocker if occurs between remote and fixed time

**Comment by khalidadil** [comment]
@shefalijoshi I'll have to work with you to figure out why this isn't working properly in remote clock - reopening

**Comment by khalidadil** [comment]
Note: Please use telemetry that has staleness when testing this (not an SWG).

**Comment by ozyx** [comment]
MOSTLY Verified. When switching while the components are stale, the staleness correctly clears on the objects but not on the parent:

![image](https://github.com/nasa/openmct/assets/9259993/f4bb69f3-3164-4f4c-8337-510377c81397)

**Comment by ozyx** [comment]
Verified fixed -- 10/6/23

Steps:
1. Navigate to Flexible Layout full of telemetry which will go stale (timelyParameter) in local clock mode
2. Wait until staleness state is active
3. Navigate to the `timelyParameter` telemetry itself
4. Toggle to Remote Clock
5. The staleness state is cleared

The issue was that staleness styling was not being cleared on telemetry plot views
