### ISSUE TITLE
[New Edit Mode] Remove Edit-related concerns from mct-representation

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#634]
From #481:

> * Remove Edit-related concerns from mct-representation
  * Should actually be low priority, may want to remove mct-representation during API refactor

**Comment by akhenry** [comment]
Note to testers: #824 and #634 affect edit mode generally, so general testing around edit mode is necessary. Track issues on either of these tickets.
* Triggering edit mode - does it still work as expected? (edit mode button, and drag-drop)
* Once in edit mode, do actions still work as expected?
* Make sure no changes are being persisted that shouldn't be (eg. after a cancel)
* Likewise, make sure that changes are persisted when they should be
* Especially test around timelines where edit mode issues have surfaced in the past.

**Comment by VWoeltjen** [comment]
Conducted various behaviors above during testathon 2016/05/31, noted no issues here
