### ISSUE TITLE
Searching a Notebook with whitelisted links for '.' exposes some html

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#6347]
#### Summary

Searching a Notebook with whitelisted links for '.' displays some html and looks weird:

![Unnamed Section  Unnamed Page](https://user-images.githubusercontent.com/9259993/219225853-879ed3e4-aeef-4001-9d18-17f039fb0c15.png)

![Search Results (1)](https://user-images.githubusercontent.com/9259993/219225865-f2382095-ee3b-4d7b-aef6-a4551b508e66.png)

#### Expected vs Current Behavior

HTML shouldn't be exposed

#### Steps to Reproduce

1. Configure the Notebook plugin for some whitelisted links
2. Create a Notebook, add an entry with a whitelisted url
3. Search the notebook for '.'
4. See weirdness

#### Environment

* Open MCT Version:  2.1.6-SNAPSHOT
* Deployment Type:  testathon
* OS: MacOS
* Browser: Chrome

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment]
# Testing Instructions

1. Follow reproduction steps and verify that no html is exposed anymore
2. Perform regular searches and verify that search still works as expected

**Comment by rukmini-bose** [comment]
Verified Testathon 3/30/2023

**Comment by michaelrogers** [comment]
Fix verified during testathon 03/30/2023. Hyperlinks are returned instead of stringified HTML.

**Comment by shefalijoshi** [comment]
Verified fixed
