### ISSUE TITLE
[Telemetry Tables] Potential Bug: Investigate out of order telemetry in Telemetry Tables

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#6350]
#### Summary

TelemetryCollections were recently enhanced to emit a sort index when new telemetry is received. This was to address an issue in the Imagery view where out of order telemetry would cause images to appear out of order in the view. Although the TelemetryCollection maintains sort internally, it was not previously exposing this to consumers so that they themselves could maintain the correct sort order.

Telemetry Tables also use Telemetry Collections so may be susceptible to the same issue. Although, in the case of Telemetry Tables a second layer of sorting is applies in addition to the internal sort maintained by telemetry collections (because tables can be sorted by any column).

#### Steps to Reproduce
1. In real-time mode, load a relatively low frequency (like 1Hz) telemetry source in a table
2. Scroll down the table and verify that all values are in the expected order. The issue, if present, will manifest as the most recent value appearing out of order.

#### Environment
* Open MCT Version: 2.1.6
* Deployment Type: All

#### Impact Check List
- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by unlikelyzero** [comment]
Still critical

**Comment by unlikelyzero** [comment]
@jvigliotta please keep this in mind when working on pagination in tables

**Comment by akhenry** [comment]
@unlikelyzero We should close this for retest?

**Comment by shefalijoshi** [comment]
This needs to be retested after this is fixed: VIPEROMCT-428

**Comment by rukmini-bose** [comment]
Verified Testathon 4/4/2024. Don't see any telemetry values being out of order in tables.

**Comment by ozyx** [comment]
Verified Testathon 4/4/24-- Cannot reproduce

**Comment by charlesh88** [comment]
Testathon 4/4/2024 cannot repro.

**Comment by davetsay** [comment]
verified
