### ISSUE TITLE
Allow Enter key in Notebook entry to add new lines by default

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#6354]
**Is your feature request related to a problem? Please describe.**
Line breaks by default from the Enter key was the initial design approach, but that was changed after some user requests at that time. However, after an extended period of Notebook usage by multiple constituents, it's become clear that there is a strong desire to allow line breaks in Notebook entries as the default action. This will become even more important when we go after entry formatting, that allows bulleted lists and tables. 

From VIPER user requests 225.

**Describe alternatives you've considered**
To support this but try to retain some of the Enter key's streamlining, we should do the following:
- Remap the Enter back to its original usage of adding lines in entries.
- Allow a key modifier like Cmd+Enter (or Windows key+Enter) to close an entry.
- Keep the "tab out" function which currently closes the entry.
- Add commit and (ideally) cancel buttons to the edit mode of the entry. It's not clear we need a "cancel" button, which could be significantly more effort - the expectation would be to revert all changes to the entry.

**Additional context**

**Comment by charlesh88** [comment]
### Testing Notes
1. Create or edit a Notebook Shift Log or Notebook. The Shift Log is preferred to test for regressions on locked pages.
2. Go to a page with several entries; add new entries if needed.
3. Hover over an entry other than the current one, verify that it "lights up" a little bit to indicate clickability.
4. Click directly into the text of a currently unselected entry, verify that it does NOT immediately put the text field into "edit" mode, but does select the entry.
5. Click again into the text field of the selected entry, verify that the input is now editable by adding or modifying the text. 
6. Press the Enter key while editing. Verify that a line return is added to the text and the entry remains in edit mode.
7. Press the Tab key while editing, and verify that edit more is exited and any changes were saved. 
8. While editing, click anywhere outside the entry and verify that behavior is the same as step 7.
9. Repeat step 5, and while editing observe that a button with a checkmark appears at the lower right of the text field. Click that button and verify that the input is no longer in edit mode and that any changes were saved.
10. Nav away and back from the Notebook; verify that any edits were persisted.
11. If testing a Shift Log, commit a page or go to an already committed page. Verify that entries cannot be edited as expected.
12.

**Comment by davetsay** [comment]
filed this as a follow up bug, #6411

**Comment by rukmini-bose** [comment]
This all looks good. Verified Testathon 3/14/2023

**Comment by akhenry** [comment]
Verified fixed

**Comment by davetsay** [comment]
i appreciate all the verifieds but....

i think something is seriously borked here.
you can get into weird states where the new entry doesn't get focused, and then clicking on the input to focus it makes the entry go away.

separate issue is that if you try to delete a new entry, you get an error since the new entry isn't yet persisted

**Comment by ozyx** [comment]
Verified fixed-- Testathon 3/17/2023 🍀
