### ISSUE TITLE
Sub-object editing of Display Layouts isn't working

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#6359]
#### Summary
See title.

#### Expected vs Current Behavior
THIS IS A SERIOUS REGRESSION. Display Layouts within Display Layouts must allow editing of their elements.

#### Steps to Reproduce

1. Put a Display Layout within another Display Layout.
2. Try to click any element within the nested layout to edit it.
3. Observe: you can move items like alphanumerics, but the resize and move handles are not displayed.

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [X] Regression? Did this used to work or has it always been broken?
- [X] Is there a workaround available?
- [X] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information
<img width="810" alt="Screen Shot 2023-02-17 at 12 23 56 PM" src="https://user-images.githubusercontent.com/1056412/219786333-0082aa23-13a5-4634-a06b-267d2d7f9db7.png">
<img width="772" alt="Screen Shot 2023-02-17 at 12 24 03 PM" src="https://user-images.githubusercontent.com/1056412/219786330-11d95f09-1f11-4834-b37c-5edd1e3c2a9a.png">
<img width="759" alt="Screen Shot 2023-02-17 at 12 24 17 PM" src="https://user-images.githubusercontent.com/1056412/219786318-d1e9e0e3-50c8-4499-bdfd-80ed6421f43b.png">

**Comment by charlesh88** [comment]
We need to re-up on this one, it keeps coming up as an issue for users in the MMOC.

**Comment by unlikelyzero** [comment]
@charlesh88  to take a quick look at css as a source of the issue

**Comment by scottbell** [comment]
@charlesh88 I'm having trouble reproducing this, though I may be missing something:

https://github.com/nasa/openmct/assets/9853862/082764b8-ec37-4978-aa62-7bbadfe07ea7

**Comment by scottbell** [comment]
Verified this was broken in 1.8.4:

https://github.com/nasa/openmct/assets/9853862/1c3e8ea0-29cd-404f-ad5a-f074bcca8409

As it appears fixed now, closing this for further testing.

**Comment by rukmini-bose** [comment]
Verified Testathon 10/23/2023

**Comment by khalidadil** [comment]
Verified that child items of a nested display layout can be repositioned as expected. Verified in Testathon on 10/23/23

**Comment by charlesh88** [comment]
Testathon 2024-03-20 cannot reproduce, sub-object editing is gloriously back!
