### ISSUE TITLE
[New Edit Mode] Remove Edit-related concerns from DropGesture

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#636]
From #481:

> * Remove Edit-related concerns from DropGesture
  * Triggering of related workflow behavior (e.g. starting editing, creating virtual panels) should be a responsibility of components in the Edit bundle

**Comment by akhenry** [comment]
Note to testers: This change specifically affects the "drag-drop" gesture used to trigger edit mode, so testing of this functionality is necessary.

Try dragging objects into layouts, panels, etc. and ensure that composition occurs as expected, and that edit mode is triggered. Also test that drag-dropping into folders does NOT trigger edit mode.

**Comment by VWoeltjen** [comment]
Did various drag-drop gestures in and out of Edit mode during testathon 2016/05/31, no regressions observed that would appear to be a result of this. Considering this verified.
