### ISSUE TITLE
Layout hidden frame controls prevent usage of visible layout frame controls

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#6379]
#### Summary

When layouts include a nested layout with its frame hidden, the popup controls for the hidden layout's frame can prevent usage of visible "more options" controls for nested elements. This is particularly problematic with Flexible Layouts where nested element's frames can easily occupy the same space. Seen during SIM-2 today.

#### Expected vs Current Behavior
When a _layout_ is nested _and_ its frame has been hidden, then completely hide its popup "more options" buttons.
 
#### Steps to Reproduce

1. Make a new Flexible Layout. Drag a plot, table or imagery view(s) into it. Save it.
2. Make a new Flexible Layout, and drag the first layout into it. Use columns layout and place that element in the right hand column. Save it.
3. In browse mode, mouse over the 3 dot menu for the layout from step 2. Note that the more options menu for the hidden frame appears (blue background in Espresso theme), covering the button options for view in the upper right.
4. Click "View Large" on the hidden frame options holder, note that the hidden frame is shown in large view, not the individual view the user expected.

#### Environment

* Open MCT Version:  2.1.4
* Deployment Type: 
* OS: all
* Browser: all

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information

Nested Flex Layout with hidden frame, note structure in tree at left.
<img width="1629" alt="Screen Shot 2023-02-28 at 12 45 18 PM" src="https://user-images.githubusercontent.com/1056412/221975585-6205a88e-3f85-405d-84d9-ff84bc74dc11.png">

Nested more options menu appearing
<img width="1629" alt="Screen Shot 2023-02-28 at 12 45 14 PM" src="https://user-images.githubusercontent.com/1056412/221975591-32cc2cf0-1c5b-419b-be83-636e8da1b16f.png">

**Comment by charlesh88** [comment]
### Testing Notes
[Test 6379.json.zip](https://github.com/nasa/openmct/files/11033530/Test.6379.json.zip)

1. Import the attached Display Layout; this will give you a Display Layout that holds a Flexible Layout, which in turn holds an Example Imagery.
2. Nav to the imported layout named "Display Layout holds Flex Layout". You should see something similar to the reference below.
![Screen Shot 2023-03-21 at 1 47 35 PM](https://user-images.githubusercontent.com/1056412/226738716-7c34ad2c-415c-4364-9ad5-1121df462681.png)

3. Edit the layout: first set the Example Imagery to hide its frame. Exit edit and confirm that hovering over the imagery displays its frame header controls (blue buttons in upper right).
![Screen Shot 2023-03-21 at 1 48 33 PM](https://user-images.githubusercontent.com/1056412/226738900-a33b60a0-5aab-4cf5-8cae-f6dd599cc3ee.png)

4. Edit the layout again: now set the "Flexible Layout holds Imagery" element to hide its frame. Exit edit and confirm that hovering over the imagery displays its frame header controls as before, and that clicking the View Large button in the hover controls displays a large view of the Imagery, NOT the Flexible Layout.
![Screen Shot 2023-03-21 at 1 49 38 PM](https://user-images.githubusercontent.com/1056412/226739245-56821c46-bb5e-4b59-acb3-e6a1493d9905.png)

**Comment by ozyx** [comment]
Verified fixed -- Testathon 4-17-23

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 04/17/23
