### ISSUE TITLE
Allow view customization of LAD table columns

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#6385]
**Is your feature request related to a problem? Please describe.**
Users would like to be able to suppress columns in the same way they can in Telemetry Tables. In particular, allow the ability to suppress the timestamp column.

**Describe the solution you'd like**
Add an inspector view for edit mode on lad tables allowing you to hide "timestamp" and "unit" columns.

**Describe alternatives you've considered**
A mishmash of alphanumerics in display layouts.

**Additional context**
This would be the start of adding more configurability to LAD Tables and LAD Table Sets.

**Comment by jvigliotta** [comment]
## Testing
- Create a LAD Table and add some telemetry objects (some with units, ex SWGs and some without, ex State Generator)
- Edit the LAD Table, note there is now an Inspector View for it
- Hide/Show columns, save and reload, make sure it's working as expected
- If you remove/add an endpoint with units, make sure the "units" checkbox disappears/appears as expected
- Do the same as above, but with LAD Table Sets, adding and removing LAD Tables

**Comment by akhenry** [comment]
Works great! Verified!

**Comment by unlikelyzero** [comment]
https://github.com/nasa/openmct/issues/6430
