### ISSUE TITLE
Composition is not-re-evaluated when node is expanded in the tree

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#6391]
#### Summary
When a child is added to a parent object in another tab (or by another user) it does not appear in the tree even after collapsing and expanding the parent node. It appears that the composition is cached in the tree and is not re-evaluated every time the parent node is expanded.

#### Expected vs Current Behavior
The new child should appear after collapsing and expanding the parent node.

#### Steps to Reproduce
1. Navigate to the same folder in two different Open MCT tabs, and expand it in both
2. In the first tab, add a child object to the folder
3. In the second tab, collapse the parent folder and then expand it again
4. Observe that the new child does not appear even after expanding and collapsing the parent

#### Environment
* Open MCT Version: 2.1.6

#### Impact Check List
- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment]
Should be fixed by #6306

**Comment by ozyx** [comment]
# Testing Instructions

- Follow reproduction steps and verify that the child object shows up on the second tab
- Repeat above steps with localStorage and CouchDB plugin

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon 3/16 on couch, next up... local storage

**Comment by davetsay** [comment]
this is still an issue with grandparents
