### ISSUE TITLE
Cannot add annotations on newly create notebook entry

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#6411]
#### Summary
When a notebook entry is created, it is focused for editing, but it is not selected by the SelectionAPI. Annotations can only be applied to selections, so you cannot annotate the new notebook entry until it is re-selected.

#### Expected vs Current Behavior
You should not have to re-select the new notebook entry to add annotations.

You have to click the text input area of the notebook entry before adding tags.

#### Steps to Reproduce
1. Create a new notebook
2. Click the annotations tab in the inspector
3. Click the + drop area in the notebook to create a new notebook entry
4. Observe that the Add Tags button is not visible in the annotations tab in the inspector when it should be

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment]
Verified fixed -- Testathon 4-17-23

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 04/17/23

**Comment by rukmini-bose** [comment]
Verified Testathon 4/17/2023
