### ISSUE TITLE
InspectorView priority is ignored

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#6413]
#### Summary

InspectorViews show up in the same order regardless of priority.

#### Expected vs Current Behavior

InspectorViews should be able to be reordered by priority.

#### Steps to Reproduce

1. Change the priority on an InspectorView to something else
2. Load the inspector, notice the order doesn't change

#### Environment

* Open MCT Version:  2.2.0-SNAPSHOT
* Deployment Type:  local
* OS: MacOS
* Browser: Chrome

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment]
# Testing Notes

Test Locally.

- Modify an InspectorViewProvider's priority to an overwhelmingly positive or negative integer value and ensure that the new order is reflected in the view

**Comment by khalidadil** [comment]
Verified in Testathon on 03/16/23
