### ISSUE TITLE
Image view should support showing more images than the conductor bounds

### ISSUE THREAD

**Issue by scottbell** [nasa/openmct#6434]
**Is your feature request related to a problem? Please describe.**
Users would prefer if Imagery in the thumb strip persisted and was not removed by the Time Conductor bounds, while using a designated "now" context (local clock, remote clock). This supports the usage scenario of wanting to globally see plotted data for around 15 minutes, but imagery for much longer.

**Describe the solution you'd like**
1. A toggle switch for Imagery views, per view and enabled by default, that makes that view ignore the TC real-time bounds. "Now" would still be defined by the TC.
Discuss if Fixed Timespan mode would or would not pay attention to this setting.
1. Independent Time Conductor is another possibility, but that UX is more cumbersome to deal with for this use case; option 1 above would be preferred.

**Additional context**
For images it's good enough to just enable the independent time conductor for now.

**Comment by scottbell** [comment]
> This will potentially be very problematic if we're requesting hundreds of images of 5.5 MB, unbounded

@unlikelyzero I think the idea here (at least at first) is to slap an independent time conductor on here instead. I know at one point we were linking at automatic thumbnailing/caching through a proxy (e.g., Apache), but not sure where that ended.

**Comment by unlikelyzero** [comment]
@scottbell let me know when you have a WIP PR. I have a Driver displaylayout with 12 Images formatted for the MMOC Monitors. I want to show you how the independent time conductor would affect the screen real estate

**Comment by scottbell** [comment]
@unlikelyzero the screen real estate isn't much, about 22 pixels:
<img width="858" alt="Screenshot 2023-03-22 at 11 32 44 AM" src="https://user-images.githubusercontent.com/9853862/226876663-7bc8a037-07d6-481b-8647-6df40aed0380.png">

**Comment by unlikelyzero** [comment]
When you're ready, let me deploy it and we can look at it inside of a driver display

**Comment by ozyx** [comment]
> This will potentially be very problematic if we're requesting hundreds of images of 5.5 MB, unbounded

Worth noting that the Imagery View can support thumbnail size images in the image strip now.

**Comment by scottbell** [comment]
To test:

1. Bring up Example Imagery View
2. Flip the button near the top of the view to turn on independent time
3. Ensure Real Time and Fixed Time both work, and that the images generated match what the time conductor is asking for


https://user-images.githubusercontent.com/9853862/227140510-6271094e-bb09-44b8-8b3e-342b404863db.mov

**Comment by scottbell** [comment]
I "think" this is still waiting on some independent time conductor UI changes, is that correct @jvigliotta / @akhenry?

**Comment by rukmini-bose** [comment]
Verified Testathon 6/24/2023. All different ITC time settings seem to generate the write type of images.

**Comment by ozyx** [comment]
Verified Testathon 7/24/23. Setting the ITC to greater bounds than the global conductor displays the correct number of images in the Imagery view
