### ISSUE TITLE
Allow export of a Notebook as Text

### ISSUE THREAD

**Issue by scottbell** [nasa/openmct#6435]
**Is your feature request related to a problem? Please describe.**
Users want to be able to export a Notebook as text.

**Describe the solution you'd like**
Dumping a notebook to a text file than can be saved to disk should suffice.

**Additional context**
One question for the future is how to handle Snapshots? Large size in the scope of each entry, as linked images within the document?

**Comment by scottbell** [comment]
To test:

1. Create a Notebook with several sections, pages, entries, and tags. Try to vary the content up.
2. Right click on the Notebook object, and select "Export Notebook as Text"
3. Use the default options (no metadata or tags)
4. Look at resultant text file. Ensure it includes all your sections, pages, and entries exist.
5. Change the options (with metadata and tags) and ensure your tags show up with appropriate metadata.

**Comment by rukmini-bose** [comment]
Verified Testathon 3/30/2023

**Comment by charlesh88** [comment]
Verified fixed Testathon 2023-03-30.
