### ISSUE TITLE
Clicking a plot annotation should pause the plot

### ISSUE THREAD

**Issue by scottbell** [nasa/openmct#6443]
#### Summary
When clicking on a plot annotation in real time mode, you can't see it as the plot isn't paused.

#### Expected vs Current Behavior
As you're intentionally clicking a plot annotation, we should pause the plot for you to display it to you.

#### Steps to Reproduce
1. Create a plot annotation by tagging some points (option + shift + drag)
2. Enter real time mode if you're not already
3. Search for the tag you made
4. Notice the annotation isn't visible as the plot isn't paused

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment]
Verified fixed -- Testathon 3/17/2023 🍀
