### ISSUE TITLE
Conditional styling leaves the last selected style applied

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#6444]
#### Summary
When applying conditional styling to an object in a display layout, the user is able to select the conditional styles in order to preview them. Selecting a conditional style immediately applies it to the element being styled.

The issue right now is that upon saving changes, the applied styling remains active. Instead it should revert to a default state.

#### Steps to Reproduce
1. Define a condition set with a telemetry point that has no telemetry (this is important, new telemetry will clear the applied style)
2. Define at least two conditions
3. Drag the condition set into a display layout
4. Use the condition set to apply some conditional styling to the condition set telemetry in the display layout
5. Observe that selecting condition styles applies them immediately as expected
6. Save the display layout
7. Observe that the last selected style is still applied.

#### Workarounds
Navigate away from the display layout and back again.

#### Environment
* Open MCT Version: 2.0.0
* Deployment Type: dev

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by shefalijoshi** [comment]
Another scenario here is:
1. Apply conditional styles to a display layout item.
2. Ensure that you're in fixed timespan mode and there is no data to determine the condition set output. It should be `---`
3. Notice that they first condition style is applied to the display layout item by default.

**Comment by akhenry** [comment]
Characterizing as blocker for now because if this edge-case is triggered an operator may be given the wrong impression about system status based on incorrect application of conditional styles.

**Comment by shefalijoshi** [comment]
Root cause - if the condition set was previously working, we set the `selectedConditionId` and save it on the domainObject being styled.
At a later time when the view is loaded again, we recall that selectedConditionId here: https://github.com/nasa/openmct/blob/master/src/plugins/condition/StyleRuleManager.js#L67
and use it's styling even if that's not the currently matched one.

**Comment by shefalijoshi** [comment]
Test instructions:
1. Make sure that there is no data flowing (maybe by setting the clock to Local clock and using telemetry that doesn't produce any data for local time)
2. Create a condition set with at least one condition
3. Create a display layout and add a layout item or telemetry view and style it with the condition set created in Step 2.
4. Ensure that no styling is applied if no condition set output has been calculated.

**Comment by ozyx** [comment]
> Test instructions:
> 
> 1. Make sure that there is no data flowing (maybe by setting the clock to Local clock and using telemetry that doesn't produce any data for local time)
> 2. Create a condition set with at least one condition
> 3. Create a display layout and add a layout item or telemetry view and style it with the condition set created in Step 2.
> 4. Ensure that no styling is applied if no condition set output has been calculated.
> 5. Ensure that when the view is in edit mode, clicking on a condition style in the inspector view applies that style in the main view. Once done editing, the selection should reflect an computed styles only.

Verified the above repro steps, all looks good!


Sidenote:

After completing the above steps and finishing in a state where my condition was true (telemetry value > X), I switched to local clock mode (which has no telemetry). The styling on the layout item did not clear. Upon refresh, the styling of the layout item was still that of `condition === true`. This persisted until I cleared cache and reloaded. It seems that whatever the last datum was before switching clocks (and receiving no further data) is cached.
