### ISSUE TITLE
Creating an object while viewing a VIPER Plan kills Open MCT

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#6455]
#### Summary

Having a VIPER Plan open and then opening the Create modal (to create any object) causes Open MCT to run out of memory and crash.

#### Expected vs Current Behavior

Open MCT should not die

#### Steps to Reproduce

1. Have a VIPER Plan selected
2. Try to create any object
3. Open MCT dies

#### Environment

* Open MCT Version:  2.2.0-SNAPSHOT
* Deployment Type:  Testathon
* OS: MacOS
* Browser: Chrome

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [x] Does this have an impact on Performance?

**Comment by ozyx** [comment]
# Testing Instructions

- On Testathon, navigate to a VIPER plan
- Click the create modal
- Create any object
- Verify that Open MCT does not freeze

**Comment by michaelrogers** [comment]
Fix verified on testathon 03/17/2023. I was able to create an object via the create modal while a VIPER plan was focused.
