### ISSUE TITLE
Tags disappear after resizing then dismissing the "Add Tag" select

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#6457]
#### Summary

Tags magically disappear from the view if you resize the inspector pane with the "Add Tag" select activated, then click off

#### Expected vs Current Behavior

Tags shouldn't disappear

#### Steps to Reproduce

1. Create a Notebook
2. Create an Entry
3. Click the entry
4. Go into the "Annotations" tab
5. Add a few tags
6. Click "Add Tag"
7. Resize the pane. "Add Tag" disappears
8. Click anywhere else, the most recently added tag disappears
9. Lather, Rinse, Repeat

#### Environment

* Open MCT Version:  2.2.0-SNAPSHOT
* Deployment Type:  Testathon
* OS: MacOS
* Browser: Chrome

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [ ] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information

https://user-images.githubusercontent.com/9259993/225759864-fc4caaa1-2941-43f1-b4a4-5b4952c48e15.mov

**Comment by rukmini-bose** [comment]
Verified Testathon 3/30/2023. 

I dont see anything funky with tags anymore!

**Comment by michaelrogers** [comment]
Fix verified during testathon 03/23/2023. Tags and add tag button remain visible through resizing events.
