### ISSUE TITLE
Jumping to a plot annotation from search sometimes does not show the annotation highlighted 

### ISSUE THREAD

**Issue by khalidadil** [nasa/openmct#6458]
#### Summary
I'm seeing an issue when searching for an annotation tag and jumping to a plot where that annotation can be found. Sometimes clicking on the search result only shows the plot itself and doesn't bring up the annotation highlighted in the plot. I would expect to always jump to a paused plot, zoomed into the annotation location.

When clicking on the search result again, it correctly shows the annotation. This is an intermittent issue.

**Comment by michaelrogers** [comment]
Fix verified on testathon 03/17/2023. After tagging an annotation, I was able to search for the tag and the plot was paused and highlighted the annotation.
