### ISSUE TITLE
Array type values are not shown correctly in tables

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#6466]
#### Summary
When telemetry has values of type Array, telemetry tables should display them correctly as such.

#### Expected vs Current Behavior
Currently, the values don't show up

#### Steps to Reproduce
1. View a telemetry endpoint that has array type values
2. Change the option to view it as a telemetry table
Expect to see telemetry values for the metadata that is an array.
Actual: You see no values

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by unlikelyzero** [comment]
Verified fixed

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon 3/17/23
