### ISSUE TITLE
LAD Tables are constantly auto-resizing

### ISSUE THREAD

**Issue by michaelrogers** [nasa/openmct#6471]
Relates to VIPEROMCT-298

#### Summary

When telemetry values have a large character count to them (like those with stringified arrays), the column width will jump around making it difficult to track telemetry.

#### Expected vs Current Behavior

LAD tables should have stable column widths like telemetry tables.

#### Steps to Reproduce

1. Navigate to a LAD table
2. Add a telemetry endpoint that returns an array value
3. Observe the width of the column changes as the array does

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [X] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [X] Does this have an impact on Performance?

**Comment by michaelrogers** [comment]
## How To Test

1. Navigate to LAD table
1. Observe that the columns dont jump around with long values
1. Toggle the resize button
1. Observe the previous layout mode is preserved and now a user can horizontally scroll

**Comment by ozyx** [comment]
Verified fixed! Testathon 3/17/2023 🍀
