### ISSUE TITLE
Clicking on a telemetry point and panning a plot with an annotation on it duplicates the marquee

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#6475]
#### Expected vs Current Behavior

There should only be a single marquee around the annotations

#### Steps to Reproduce

1. Create an Overlay Plot
2. Drag telemetry into it
3. Annotate it (shift + option + click'n'drag)
4. Click on a telemetry point (the point itself) and pan the plot
5. A marquee is stacked on the existing marquee every time you pan

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information

https://user-images.githubusercontent.com/9259993/226071899-2b835992-bfce-43db-9efa-30bcec538c62.mov

**Comment by unlikelyzero** [comment]
Loss of data -- critical

**Comment by akhenry** [comment]
Cannot repro in master on banner. Closing to re-test

**Comment by ozyx** [comment]
Verified fixed-- Testathon 1/17/24
