### ISSUE TITLE
Imagery controls appear on top of the Grand Search dropdown

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#6481]
#### Summary

The Imagery controls appear on top of the Grand Search results dropdown

#### Expected vs Current Behavior

The search dropdown should appear above the image controls

#### Steps to Reproduce

1. Open the Imagery View
2. Type something into the Grand Search to get the dropdown to appear
3. Hover over the image so that the image controls appear
4. The image controls appear on top of the Search Dropdown

#### Environment

* Open MCT Version:  2.2.0-SNAPSHOT
* Deployment Type:  local
* OS: MacOS
* Browser: Chrome

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information

![image](https://user-images.githubusercontent.com/9259993/226678924-227f87b7-072c-47c6-a19d-d78e85661053.png)

**Comment by charlesh88** [comment]
### Testing Notes
1. Perform Steps to Reproduce.
2. Verify that problem does NOT occur as described.

**Comment by ozyx** [comment]
Verified fixed -- Testathon 3/30/23
