### ISSUE TITLE
Collapsing a tree item can accidentally remove sibling items under certain conditions

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#6488]
#### Summary

VIPER issue: VIPEROMCT-285

When we collapse a treeItem, we check against the `navigationPath` of all other tree items to see if the `navigationPath` of the item being collapsed is a substring of the given path. If it is, we assume this is a child and remove it from the available treeItems (effectively "collapsing" it).

For example, if we are collapsing path:
`/browse/mine/abcd`

It is assumed that a path such as `/browse/mine/abcd/1234` is a child, and should be filtered out.

This works with the assumption that each identifier in the path is unique and no siblings contain any part of the parent path. However, with custom dictionaries, this may not be true (as identifiers are not necessarily uuids). For example, collapsing an item with path:

`/browse/Science`

will also inadvertently collapse:

`/browse/ScienceSomethingElse`

Collapsing and expanding a shared parent of the two siblings brings them back (as a workaround).

#### Expected vs Current Behavior

Collapsing a tree item should only remove that tree items children

#### Steps to Reproduce

1. On Testathon, load the VIPER dictionary
2. Find folder 'Science'
3. Expand/Collapse it
4. Notice that 'ScienceSimData' disappears

#### Environment

* Open MCT Version:  2.2.0-SNAPSHOT
* Deployment Type:  VIPER -- testathon
* OS: MacOS
* Browser: Chrome

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment]
# Testing Notes
1. Do above repro steps and verify that `ScienceSimData` folder no longer disappears
2. Expand/collapse other folders in/outside of Shared Items.
3. Verify that child objects appear and disappear correctly

**Comment by akhenry** [comment]
Verified fixed. Nice!
