### ISSUE TITLE
Proposed fix to remove the warnings "4 high severity vulnerabilities" after performing "npm install"

### ISSUE THREAD

**Issue by m-marbukh01** [nasa/openmct#6492]
#### Summary

After performing an `npm install` the output states there are four vulnerabilities.  

#### Expected vs Current Behavior

Expected behavior should be no errors are displayed.
#### Steps to Reproduce

1. Performing `npm install` gives the following error
```
4 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force
```
2. After performing  `npm audit fix --force` eight warnings apear.  The first one is show below.

`  WARNING in ./src/plugins/imagery/components/ImageryTimeView.vue?vue&type=script&lang=js& (./node_modules/vue-loader/lib/index.js??vue-loader-options!./src/plugins/imagery/components/ImageryTimeView.vue?vue&type=script&lang=js&)   
`

4. To fix the warnings involved making changes to two files (ImageryTimeView.vue and Plan.vue).

The lines commented out of ImageryTimeView.vue include lines 37, 221, and 226.
import * as d3Scale from 'd3-scale';
this.xScale = d3Scale.scaleUtc();
this.xScale = d3Scale.scaleLinear();

The lines commented out of Plan.vue include lines 60, 332, and 337.
import * as d3Scale from 'd3-scale';
this.xScale = d3Scale.scaleUtc();
this.xScale = d3Scale.scaleLinear();

NOTE: I am not sure how the code changes will effect the rest of the code

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS: Any
* Browser: Any

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment]
Hi @m-marbukh01 ! Thanks for opening this issue.

Instead of commenting those lines out, it seems we may need to change the way we're importing those packages. According to [the release notes for d3-scale v4](https://github.com/d3/d3-scale/releases/tag/v4.0.0) and [the linked FAQ](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c), it can no longer be required directly due to it being a pure ESM package now.

I think we might need to bundle them somehow using Webpack.

**Comment by m-marbukh02** [comment]
@ozyx Thank you
