### ISSUE TITLE
[Build] Restructure source hierarchies and handle assets

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#650]
Restructure source hierarchies from:

```
+ platform
|
+-+ foo
  |
  +-+ src
  | |
  | +-+ Foo.js
  |
  +-+ res
  | |
  | +-+ foo.html
  | |
  | +-+ foo.scss
  |
  +-+ test
    |
    +-+ FooSpec.js
```

to 

```
+ src
|
+-+ foo
  |
  +-+ Foo.js
  |
  +-+ FooSpec.js
  |
  +-+ foo.html
  |
  +-+ foo.scss
```

Note that there is no longer a need for a `platform` directory post #460 

In the context of this issue, will likely need to address the changed paths to various assets (HTML & CSS files) which will have occurred as a consequence.

**Comment by VWoeltjen** [comment]
This is in progress; new code is being authored in the `src` hierarchy and asset-handling is at least partially handled (templates in that hierarchy are included via the `text` plugin.)

A `setAssetPath` is available on the `openmct` object to facilitate asset-handling.

Remaining work here:

- [ ] Move the `platform` hierarchy into the `src` hierarchy
- [ ] Add SCSS->CSS build steps for the `src` hierarchy

**Comment by larkin** [comment]
Don't think we directly tackle this, think we choose to address this at a later date.
