### ISSUE TITLE
[Recently Viewed Items] Disable button if no items

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#6503]
**Is your feature request related to a problem? Please describe.**
No, no issue. It would just be nice to have the button to clear recently viewed objects be disabled until there are recently viewed objects to clear.

**Describe the solution you'd like**
Add the disabled attributed to the button if there are no recently viewed items.

**Additional context**
With items... good to go!
![Screen Shot 2023-03-24 at 12 59 30 PM](https://user-images.githubusercontent.com/12013460/227627743-dac1f655-5f27-40d3-89bf-1dc406d6ddf7.png)

With no items, still active.
![Screen Shot 2023-03-24 at 12 59 42 PM](https://user-images.githubusercontent.com/12013460/227627739-7343df1d-1755-44f3-bd39-2933be87e819.png)

Would like it to be disabled.
![Screen Shot 2023-03-24 at 1 00 01 PM](https://user-images.githubusercontent.com/12013460/227627736-dbc502c9-25fd-4640-bccd-605d9d5efb25.png)

**Comment by ozyx** [comment]
# Testing Instructions

- Navigate to an object in Open MCT
- Observe that the Recent Items list is populated, and the "Clear" button is enabled
- Click the "Clear" button
- Observe that the Recent Items list is empty, and the "Clear" button is disabled
- Navigate to a different object in Open MCT
- Observe that the Recent Items list is populated, and the "Clear" button is enabled again

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 04/17/23

**Comment by rukmini-bose** [comment]
Verified Testathon 4/13/2023
