### ISSUE TITLE
[Condition Widget] Condition widgets with links do not keep styling

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#6514]
#### Summary

When a condition widget is setup to use a URL and it is styled, it will not keep its styles on load. The reason for this is, condition widgets will be a `SPAN` tag by default but will switch to an `A` tag if after it is mounted and checks if a URL is present. During this time, the Object View will pull the `SPAN` every time as the object to be styled. It is never updated after the widget is changed to an `A` tag. Also, the `target="_BLANK"` attribute is not set, so any clicks will take you away from Open MCT.

#### Expected vs Current Behavior

Condition Widgets as links with styles should persist their styles. Also, the links should open in a new tab.

#### Steps to Reproduce

1. Create a condition widget
2. Edit it's properties to add a URL
3. Style the condition widget in the inspector view "style" tab in edit mode and save
4. notice the styles have disappeared

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by jvigliotta** [comment]
## Testing
- Reproduction steps
- Additional condition widget styling tests (with conditional/static styling and with/without URLS)

**Comment by ozyx** [comment]
Verified fixed -- Testathon 4-17-23

**Comment by rukmini-bose** [comment]
Verified Testathon 4/17/2023

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 04/17/23
