### ISSUE TITLE
Progress Bar does not show progress percentage

### ISSUE THREAD

**Issue by dmkorten** [nasa/openmct#6516]
#### Summary
When including a progress percentage in the progress bar, only an empty grey bar is displayed. 

#### Expected vs Current Behavior
The progress bar should be filled in to the progress percentage, currently it is all black.

#### Steps to Reproduce

1. Add `<progress-bar :model=" {progressPerc: 74}" />` to a Vue provider
2. Run the code
3. Progress bar will be black

#### Environment

* Open MCT Version: 2.1.5
* Deployment Type:  npm dev
* OS: MacOS 11.7.4
* Browser: Chrome 111.0.5563.110

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [X] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by dmkorten** [comment]
Screenshot did not show up in the bug report
<img width="1164" alt="Screen Shot 2023-03-27 at 4 35 33 PM" src="https://user-images.githubusercontent.com/69947321/228073087-9a829269-71b3-4b7a-a42d-59a895068cef.png">

**Comment by ozyx** [comment]
# Testing Instructions
- Follow steps to reproduce and verify that a Progress Bar is rendered with the correct percentage of the bar filled in

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 08/22/23

**Comment by charlesh88** [comment]
Verified fixed Testathon 2023-08-22.

**Comment by ozyx** [comment]
Verified! 2023-08-22.

Thanks again!
