### ISSUE TITLE
Need relative links for legacy code pulling openmct in as a dependency

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#6517]
#### Summary
webpack aliased links are breaking code

#### Expected vs Current Behavior
npm should build

#### Testing Instructions
1. see testing instructions and perform for ONLY telemetry table component here, #6109

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by unlikelyzero** [comment]
@davetsay can you provide some more context? We can make additional changes to prevent this relative import in the future, but have been using relative imports for years

**Comment by unlikelyzero** [comment]
Verified as fixed and a follow up is here: #6610
