### ISSUE TITLE
npm install npm WARN deprecated 

### ISSUE THREAD

**Issue by shaynababe** [nasa/openmct#6519]
![Screenshot_2023-03-29_11-49-16](https://user-images.githubusercontent.com/120763310/228638534-b5536973-3a3c-418b-9020-780555309173.png)

(base) z@spin7:~/tools/openmct$ npm install
npm WARN deprecated argv@0.0.2: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated codecov@3.8.3: https://about.codecov.io/blog/codecov-uploader-deprecation-plan/

> openmct@2.2.1-SNAPSHOT prepare
> npm run build:prod && npx tsc

> openmct@2.2.1-SNAPSHOT build:prod
> webpack --config ./.webpack/webpack.prod.js

webpack compiled successfully

added 786 packages, and audited 787 packages in 1m

92 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
(base) z@spin7:~/tools/openmct$

#### Steps to Reproduce

Google Chrome | 111.0.5563.64 (Official Build) (64-bit)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Linux
JavaScript | V8 11.1.277.13
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Command Line | /usr/bin/google-chrome --flag-switches-begin --flag-switches-end --desktop-startup-id=xfce4-panel/exo-open/1287-0-spin7_TIME50060
Executable Path | /opt/google/chrome/google-chrome
Profile Path | /home/z/.config/google-chrome/Default

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:
* PRETTY_NAME="Debian GNU/Linux bookworm/sid"
NAME="Debian GNU/Linux"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

update code 
3 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force
d3 fails
ompiled with problems:X

WARNING in ./src/plugins/imagery/components/ImageryTimeView.vue?vue&type=script&lang=js& (./node_modules/vue-loader/lib/index.js??vue-loader-options!./src/plugins/imagery/components/ImageryTimeView.vue?vue&type=script&lang=js&) 221:30-46

export 'scaleUtc' (imported as 'd3Scale') was not found in 'd3-scale' (module has no exports)

WARNING in ./src/plugins/imagery/components/ImageryTimeView.vue?vue&type=script&lang=js& (./node_modules/vue-loader/lib/index.js??vue-loader-options!./src/plugins/imagery/components/ImageryTimeView.vue?vue&type=script&lang=js&) 226:30-49

export 'scaleLinear' (imported as 'd3Scale') was not found in 'd3-scale' (module has no exports)

WARNING in ./src/plugins/plan/components/Plan.vue?vue&type=script&lang=js& (./node_modules/vue-loader/lib/index.js??vue-loader-options!./src/plugins/plan/components/Plan.vue?vue&type=script&lang=js&) 332:30-46

export 'scaleUtc' (imported as 'd3Scale') was not found in 'd3-scale' (module has no exports)

WARNING in ./src/plugins/plan/components/Plan.vue?vue&type=script&lang=js& (./node_modules/vue-loader/lib/index.js??vue-loader-options!./src/plugins/plan/components/Plan.vue?vue&type=script&lang=js&) 337:30-49

export 'scaleLinear' (imported as 'd3Scale') was not found in 'd3-scale' (module has no exports)

WARNING in ./src/plugins/timeConductor/ConductorAxis.vue?vue&type=script&lang=js& (./node_modules/vue-loader/lib/index.js??vue-loader-options!./src/plugins/timeConductor/ConductorAxis.vue?vue&type=script&lang=js&) 145:30-46

export 'scaleUtc' (imported as 'd3Scale') was not found in 'd3-scale' (module has no exports)

WARNING in ./src/plugins/timeConductor/ConductorAxis.vue?vue&type=script&lang=js& (./node_modules/vue-loader/lib/index.js??vue-loader-options!./src/plugins/timeConductor/ConductorAxis.vue?vue&type=script&lang=js&) 147:30-49

export 'scaleLinear' (imported as 'd3Scale') was not found in 'd3-scale' (module has no exports)

WARNING in ./src/ui/components/TimeSystemAxis.vue?vue&type=script&lang=js& (./node_modules/vue-loader/lib/index.js??vue-loader-options!./src/ui/components/TimeSystemAxis.vue?vue&type=script&lang=js&) 143:30-46

export 'scaleUtc' (imported as 'd3Scale') was not found in 'd3-scale' (module has no exports)

WARNING in ./src/ui/components/TimeSystemAxis.vue?vue&type=script&lang=js& (./node_modules/vue-loader/lib/index.js??vue-loader-options!./src/ui/components/TimeSystemAxis.vue?vue&type=script&lang=js&) 148:30-49

export 'scaleLinear' (imported as 'd3Scale') was not found in 'd3-scale' (module has no exports)

#### Additional Information

![Screenshot_2023-03-29_11-38-28](https://user-images.githubusercontent.com/120763310/228636024-b9f6ffa4-96fd-4d8f-9ace-8bd02ca6e1d3.png)
![Screenshot_2023-03-29_11-46-39](https://user-images.githubusercontent.com/120763310/228637913-b00ace03-30cd-4c54-a01a-cf47911b919e.png)

**Comment by ozyx** [comment]
Hi @shaynababe . Thanks for opening this issue.
Please see [this comment](https://github.com/nasa/openmct/issues/6492#issuecomment-1481532370) for some context on why d3 breaks after upgrading to >=4.0.0.

**Comment by shaynababe** [comment]
yes is this it did not look yet
Hi @m-marbukh01 ! Thanks for opening this issue.
Most java code has there warning but update normal to Fix this only show error i put the current E3 github package install still the same warning Maybe a patch is needed
scaleUtc' 
'scaleLinear

Very few libraries actually supported it officially, but since Node.js v12.20.0 (2020-11-24) and v14.13.0 (2020-09-29) the latest and finally stable version of package.exports is available, and since support for Node.js v10.x is dropped, everything should be fine and supporting ESM shouldn't be that hard.

a pure ESM package now.

Instead of commenting those lines out, it seems we may need to change the way we're importing those packages. According to [the release notes for d3-scale v4](https://github.com/d3/d3-scale/releases/tag/v4.0.0) and [the linked FAQ](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c), it can no longer be required directly due to it being a pure ESM package now.

I think we might need to bundle them somehow using Webpack.

**Comment by unlikelyzero** [comment]
Thank you for finding and filing this issue!

The Open MCT team has identified this issue as a duplicate of an existing issue. To follow along with that development (or contribute!), please subscribe to the following: https://github.com/nasa/openmct/issues/6592
