### ISSUE TITLE
table rows should be able to provide context menus for the row objects

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#6523]
#### Summary
Regression introduced from #3770

#### Expected vs Current Behavior
You should be able to use context actions that are specific to the row's domain object, like historical lookup for just that row's domain object.

#### Steps to Reproduce
1. create telemetry table
2. add two telemetry endpoints
3. save table
4. context-click a row and select "view historical data"
5. observe that the data is for the row only, and not for the other telemetry in the table

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by michaelrogers** [comment]
Fix verified during testathon on 03/30/2023. Context menu selection on `View Historical Data` shows only the relevant data point.
