### ISSUE TITLE
[ExportNotebookAsText] Action is not available for Restricted Notebooks

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#6534]
#### Summary

The "Export Notebook as Text" action is unavailable for Restricted Notebooks ("Notebook Shift Log").

#### Expected vs Current Behavior

"Export Notebook as Text" should apply to all Notebook types.

#### Steps to Reproduce

1. Install the "RestrictedNotebook" plugin with defaults
2. Create a "Notebook Shift Log"
3. Add some entries
4. Right click on the tree item, or click the 3dots menu
5. Notice that "Export Notebook as Text" option does not show up

#### Environment

* Open MCT Version:  `2.2.1-SNAPSHOT`
* Deployment Type:  Testathon
* OS: MacOS
* Browser: Chrome

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon 4/19/22
