### ISSUE TITLE
[ExportNotebookAsText] Entries export with no value for "Created by" if user is unknown

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#6535]
#### Summary

If user is unknown, Notebook entries export to text with no value for Created by.

Likely due to [initializing username to empty string](https://github.com/nasa/openmct/blob/1d4cf1ff06573487f3762cbfe34ca0162d080ef0/src/plugins/notebook/utils/notebook-entries.js#L5).
#### Expected vs Current Behavior

Current:
```md
### Unnamed Page

Created on 2023-03-15 16:36:04 UTC by user 

Updated on 2023-03-23 21:36:04 UTC by user Unknown

asdfasdfasdf
```
Expected:
```md
### Unnamed Page

Created on 2023-03-15 16:36:04 UTC by user Unknown

Updated on 2023-03-23 21:36:04 UTC by user Unknown

asdfasdfasdf
```

#### Steps to Reproduce

1. Run Open MCT locally
2. Create a Notebook
3. Create some entries
4. Export to text
5. Notice that "Created by" has no username or UNKNOWN after it

#### Environment

* Open MCT Version: 2.2.1-SNAPSHOT
* Deployment Type:  local
* OS: MacOS
* Browser: Chrome

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by khalidadil** [comment]
I'm seeing the following:

```
# Menu Test Notebook

Created on 2023-07-21 17:35:44 UTC by user [username]

Updated on 2023-07-21 17:39:38 UTC by user [username]

## Unnamed Section

### Unnamed Page

Created on 2023-07-21 17:35:46 UTC by user [username]: Viewer

Updated on 2023-07-21 17:35:55 UTC by user [username]: Viewer

Test Entry
```

I removed my username for security. Is that what's expected?

**Comment by ozyx** [comment]
Verified Testathon 7/24/23
