### ISSUE TITLE
Time List not scrolling to keep view centered on "now"

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#6536]
#### Summary
The Time List view is automatically scrolling its view to the latest possible activity in the view.
![Screen Shot 2023-03-30 at 3 40 10 PM](https://user-images.githubusercontent.com/1056412/228979506-27832e92-c309-4ad0-827e-c5f946108648.png)

#### Expected vs Current Behavior
The Time List view is supposed to scroll to keep activities that are close to "now" centered in the available view. This is key to making this view useful in a real-time ops context.
![Screen Shot 2023-03-30 at 3 39 45 PM](https://user-images.githubusercontent.com/1056412/228979451-8483ee08-c867-467c-bcdd-afbe2a2521b0.png)

#### Steps to Reproduce

1. Set the Time Conductor to a real-time mode.
2. View a Time List that includes a plan with activities in the past and the future based on settings from step 1.
3. Size the view such that the container displays a scroll bar. If needed, add the view to a layout.
4. Observe that the Time List scrolls to the list's extent and doesn't center the view.

#### Environment

* Open MCT Version:  2.2.1
* Deployment Type:  /testathon
* OS: Mac
* Browser: Chrome

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by rukmini-bose** [comment]
Verified Testathon 6/20/23: 

Upon taking an example plan into a Time List view, and adding it to a display layout and setting the time settings to real-time mode, I notice that upon loading the layout, the Time List view automatically scrolls the current event to the top of the the view.

**Comment by unlikelyzero** [comment]
@shefalijoshi can you update this to include testing instructions we can perform on banner with a plan?

**Comment by shefalijoshi** [comment]
Testing instructions:
Create a Timelist and add a plan to it so that it shows activities.
When there are some current activities, the timelist should scroll them into view (near the center).

**Comment by charlesh88** [comment]
Testathon 2023-07-25 verified fixed.
