### ISSUE TITLE
Telemetry API should support requesting a subscription provider

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#6546]
#### Summary
The function `findSubscriptionProvider` was public but was made private by #5887. It should still be public, like `findRequestProvider` is, even though it isn't being called externally in Open MCT.

#### Expected vs Current Behavior
I should be able to use this to find a subscription provider outside of subscribing explicitly to something.

#### Steps to Reproduce
1. subscribe to data in a jpl deployment and see that it works

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by akhenry** [comment]
Can we add some brief notes for regression testing in open?
