### ISSUE TITLE
Create no longer defaults to where my Browse position is

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#655]
Testathon 20160209.

Previous to New Edit Mode, the starting point for the Save In dialog was the location I was currently in when creating a new object. So if I was in a nested folder like My Items > CHacskaylo > Layouts and invoked the Create menu to create a new Layout, the Save In dialog would default to Layouts.

The current behavior seems to always default to an uppermost valid directory like "My Items"; instead, the system should behave as it did and remember where the user was when creating new objects. This should also apply to new objects created via drag-and-drop.

**Comment by VWoeltjen** [comment]
Can't reproduce as of https://github.com/nasa/openmct/commit/70acef6905c817a43326c68d19f8bd7ecb66532e, marking unverified so we can check this next testathon

**Comment by charlesh88** [comment]
Testathon 041816
Functionality now as expected. Verified fixed.

**Comment by VWoeltjen** [comment]
Verified testathon 20160418
