### ISSUE TITLE
[Operator Status] Where multiple roles match, user should be asked to select a role.

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#6555]
**Is your feature request related to a problem? Please describe.**
The Operator Status functionality uses the Open MCT User API to detect a user's role(s) (filtered to the roles that support operator status). In some edge cases, users may perform more than one operator role, depending on shift. We need a way of knowing which role to use for the active session.

**Describe the solution you'd like**
In the case where the user has multiple operator status roles defined, we should provide UI for them to select the role to use for this session. We could use session storage to store the result so that they don't need to select it again in each new tab/window that they open.

A couple of options here:
1. A modal that blocks them from using Open MCT at all until they select a role. Although very intrusive, it would completely prevent misattribution in notebook entries etc.
2. We allow them into Open MCT using a previously selected role (or the first  role returned as it does now), but show a prominent warning in the UI telling them to select a role before they can use it again. Perhaps we block certain functionality until they select a role (eg. operator status, notebook entries, annotations). Although less intrusive and arguably a better approach doing this properly is a lot more complicated than option 1.

**Describe alternatives you've considered**
Automatically selecting the correct role based on shift schedule. This has been determined to be infeasible.

**Comment by rukmini-bose** [comment]
@charlesh88 and @rukmini-bose to discuss design

**Comment by charlesh88** [comment]
As discussed 4/11/23 with @michaelrogers:

- When a user first starts up Open MCT _and_ they have more than one role, we will intercept them with a modal dialog box asking them to select a role. 
  - A role should be preselected, and there should be no null default option. 
  - There is only an Ok button; there is no Cancel button.
  - Here's a very rough mockup:
  
![Screen Shot 2023-04-11 at 2 59 49 PM](https://user-images.githubusercontent.com/1056412/231535191-3eac125d-ecf6-4927-8612-4fe85f1ae955.png)

- The logged in user Indicator should be augmented to include the current role for the user; this should be the case even if the user doesn't have more than one role. 
  - A button to support changing the current role should be included. Clicking this button would display the dialog as described above, with the only difference being the inclusion of a Cancel button.
  - Here's a mockup of the indicator element:

![image](https://user-images.githubusercontent.com/1056412/231536921-5d0f6869-0492-4f13-862d-4760ba68bbf9.png)

**Comment by akhenry** [comment]
I think we need to make some changes to the User API  - https://github.com/nasa/openmct/issues/6664

**Comment by akhenry** [comment]
Discussed some changes to the User API to support this:

We should add an additional function to the user API for retrieving the active role
```
const role = await openmct.user.getActiveRole()
```

We should refactor the status API to make use of this function. The existing function `openmct.user.status.getStatusRoleForCurrentUser()` should be removed. Anywhere that it is used we should instead make a call to `openmct.user.getActiveRole()`. We should then call `openmct.user.status.canProvideStatusForRole()` and pass in the returned role.

The reason for the distinction here is that users may have multiple roles, and not all of them are applicable for operator status (not every user is always polled).

**Comment by michaelrogers** [comment]
### How To Test

General
1. Navigate to any page on OpenMCT
2. Observe that the user is prompted to select a role before continuing
3. Select a role
4. Observe that the selected role is updated in the User Indicator

Change Role
1. Click Change Role button in User Indicator
2. Observe the current selected role is reflected as the first choice in the drop down
3. Select a different role
4. Observe that the role has been updated in the User Indicator

Across Tabs
1. Have 2+ tabs open for OpenMCT
2. Change the role on one of the tabs
6. Observe the role is updated across all tabs

**Comment by rukmini-bose** [comment]
Verified Testathon 7/25/2023

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 07/25/23
