### ISSUE TITLE
[Annotations] Image tagging prototype

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#6557]
The v1 prototype should include:

1. Marquee select ala Plots
2. Tag selector in the inspector to add and remove tags to the given area
3. Show indication of tagged area on image load.

Prototype can be rough and ready, placeholder markup and styling is perfect. Does not need to be integrated with search for the prototype.

**Comment by scottbell** [comment]
https://user-images.githubusercontent.com/9853862/232490092-a97895ad-9234-4e08-a9d0-bc360a3e29fc.mov

Rudimentary image tagging.

**Comment by scottbell** [comment]
@akhenry I think we're close to done on this ticket:

https://user-images.githubusercontent.com/9853862/234034701-141230e1-5e72-4e82-9c0e-539170a3a456.mov

The last thing to add is the indicator on the timeline if an image has annotations, but I think I can knock that out pretty quickly.

**Comment by scottbell** [comment]
Annotation indicators on image timeline:
https://user-images.githubusercontent.com/9853862/234268413-a0f6554e-9395-41b6-af5c-e7e4a9f04c54.mov

**Comment by scottbell** [comment]
To test:

1. Use Alt+Shift drag (while not zoomed) to create a tag a marquee on an image
2. Create a tag with the annotation
3. Create several overlapping tags. Ensure clicking on them works
4. Ensure the thumbnail timeline shows an indicator that tags exists on the image
5. Ensure tags appear in search (though they do not jump to the appropriate image yet)

**Comment by akhenry** [comment]
This is really cool! A couple of small notes on the implementation inline. There are also two things I think we need to fix before we can merge this:

* Clicking on overlapping marquees doesn't after I navigate away and back. I can only select the first marquee. See video.
* We need a way to delete the annotation marquee after it's created. I can select an area of an image and never add a tag, and it just lives there in perpetuity. i can also remove all the tags for an image marquee and the same thing happens.

**Comment by unlikelyzero** [comment]
Testathon Feedback:

1. When using an image embedded in a display layout, annotations do not load until the layout is selected.
2. After deleting an annotation, the image still displays a reference to the annotation
<img width="128" alt="Screenshot 2023-06-20 at 11 52 56 AM" src="https://github.com/nasa/openmct/assets/12446869/65b7d4fb-da38-476e-b705-88f24d0f7624">

**Comment by rukmini-bose** [comment]
Verified Testathon 6/20/23

**Comment by unlikelyzero** [comment]
@ozyx which issue did you find?
