### ISSUE TITLE
[New Edit Mode] Creating a timeline naming process not clear

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#657]
From @RCarvalhoNASA:

> Creating a timeline naming process not clear:  I create a new timeline, and immediately I'm in the edit mode on Unnamed Timeline, without any chance to name it.  I double-click on the name, and it won't let me change it.  Apparently, I have to pull the little thing next to the name and then edit properties in order to give this timeline a name, which used to be the first thing to do.  I'm not sure why this detail was hidden like this.  Naming dialog then comes up again when I go to save the timeline.  Apparently this is true for all items, not just timeline.  Seems odd.

**Comment by akhenry** [comment]
It's a fair comment. It is actually by design, and is a deliberate feature of New Edit Mode.

I do wonder whether this will cause confusion to new users, or whether it's a case of existing users just being used to the old behavior?

**Comment by VWoeltjen** [comment]
> I do wonder whether this will cause confusion to new users, or whether it's a case of existing users just being used to the old behavior?

Hard to say, but a good point to raise. I think the analogous behavior is creating a New file, which various editors handle differently. (For example, Adobe Brackets doesn't prompt for a name until you Save, like we do, whereas WebStorm prompts for a name before the new file is created, like we used to do.) So I don't think there's a single standard expectation here.

Based on the report, the intuitive thing was to try double-clicking on the title to edit the name. If the title bar supported this behavior for objects being edited, I think that would resolve the issue.

In any case, think this is a design task first (NEM is behaving as-specified here)

**Comment by akhenry** [comment]
Agreed, editing the title directly would be awesome.

**Comment by charlesh88** [comment]
@akhenry And only a year and a half later, we deliver! #1679
