### ISSUE TITLE
[New Edit Mode] Dragging a pre-existing object into a container should not initiate edit mode

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#661]
Similar to how objects of the wrong type cannot be dropped to initiate edit mode on a given object, dropping an object that already exists in a current composition should not initiate edit mode. For example:
- Panel A
  - Telem 0
  - Telem 1

In browse mode, dragging Telem 1 onto Panel A should not initiate edit mode. Ideally, we'd also display a non-persistent message banner in the status area to the effect of "Object cannot be added more than once" or similar.

If we get to a world where the same object can be added more than once in a given container, than this action should be allowed when appropriate.

**Comment by VWoeltjen** [comment]
Are we sure this is undesired? 

I'm thinking of the use case where someone is editing a Layout that contains Panel A and Panel B. They drag Panel B from the tree into the view of the Layout. Possible consequences:

* Another copy of Panel B appears in the Layout, and Edit mode is initiated. (Think this is _most_ desirable behavior, insofar as it most accurately reflects user's probable intent.)
* Existing copy of Panel B is moved to the new location in the Layout, and Edit mode is initiated. (This this is current behavior; think this is _best approximation_ of user's probable intent until we allow multiple instances of same object in a Layout.)
* No change is made in the Layout and Edit mode is not initiated. (Think this does not reflect user's intent.)

If the drag was indeed errant, user can exit Edit mode and discard those changes.

Perhaps this is only undesired behavior for certain views (e.g. Plot) but is desired for others (e.g. Layout)?

**Comment by charlesh88** [comment]
Closing, this is not an important issue.
