### ISSUE TITLE
removing vulnerabilities caused by d3-scale version in the package json file

### ISSUE THREAD

**Issue by m-marbukh03** [nasa/openmct#6629]
Current version of d3-scale in the package json file causes vulnerabilities.  Updating d3-scale to version 4.0.2 removes the vulnerabilities.

#### Expected vs Current Behavior

Updating d3-scale to version 4.0.2 removes the vulnerabilities below.
```
MacBook-Pro:openmct$ npm i
npm WARN deprecated argv@0.0.2: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated codecov@3.8.3: https://about.codecov.io/blog/codecov-uploader-deprecation-plan/

> openmct@2.2.3-SNAPSHOT prepare
> npm run build:prod && npx tsc


> openmct@2.2.3-SNAPSHOT build:prod
> webpack --config ./.webpack/webpack.prod.js

webpack compiled successfully

added 832 packages, and audited 833 packages in 3m

96 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
MacBook-Pro:openmct$ 
```

#### Steps to Reproduce

1. CLONE THE SOURCE CODE: git clone https://github.com/nasa/openmct.git
2. INSTALL DEVELOPMENT DEPENDENCIES: npm install
3. RUN A LOCAL DEVELOPMENT SERVER: npm start

#### Environment

* Open MCT Version: Up to date OpenMCT version
* Deployment Type: 
* OS: Mac OS
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by unlikelyzero** [comment]
@m-marbukh03 thank you for filing this! We are going to tackle this is a package bump.

**Comment by unlikelyzero** [comment]
Thank you for finding and filing this issue!

The Open MCT team has identified this issue as a duplicate of an existing issue. To follow along with that development (or contribute!), please subscribe to the following: #6592
