### ISSUE TITLE
[New Edit Mode] Elements pool filtering behaving weirdly

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#663]
When filtering the Elements pool during editing, the behavior when having entered a single character is unexpected:
* Entering a single character does some filtering, but the results don't make sense: items whose name doesn't contain the single character still display along with those that do. See screenshot filtering 2.png.
* Entering two or more characters seems to work as expected. See filtering 3.png.

![testathon 20160209 elements filtering 1](https://cloud.githubusercontent.com/assets/1056412/12933350/70d7c7ac-cf3c-11e5-9e4c-7f83d15dcee5.png)
![testathon 20160209 elements filtering 2](https://cloud.githubusercontent.com/assets/1056412/12933351/70d8e966-cf3c-11e5-9956-6eefeb5608ce.png)
![testathon 20160209 elements filtering 3](https://cloud.githubusercontent.com/assets/1056412/12933349/70d67974-cf3c-11e5-8019-7d381aaeed64.png)

**Comment by VWoeltjen** [comment]
Verified fixed, testathon 20160509

**Comment by akhenry** [comment]
Verified fixed, testathon 20160509
