### ISSUE TITLE
[LAD Tables] Configuration not changed/persisted when toggling "Autosize" for columns

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#6636]
#### Summary
There are some cases where you can't autosize the columns. This is sometimes avoided if there are hidden columns or if you were to hide/show columns and then autosize.

#### Expected vs Current Behavior
When clicking on the 'Autosize' LAD Table button, we should expect it to do _something_. Either equal width columns or autosized columns.

#### Steps to Reproduce

1. View LAD Table and copy it's id from the url
2. in the console, `await openmct.objects.get('[thatIdThatWeJustTalkedAbout]')`
3. right click the JSON and store as a global variable
4. `openmct.objects.mutate(temp1, 'configuration', {})` 
5. refresh the view, try to autosize the columns
6. make sure you can still hide/show columns as expected

_I'm not sure how we got into this state before, but this is a solid way to see if a fix for it works._

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available? if you show or hide columns then autosize, it works
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by charlesh88** [comment]
Testathon 2023-05-08 verified fixed.
