### ISSUE TITLE
[Edit Mode] Canceling edit mode with unsaved changes should show confirmation dialog to user

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#664]
From #660 

> Ideally, clicking the cancel edit "X" button should have the same result as if the user tried to navigate elsewhere while editing: the unsaved changes dialog is displayed and clicking Cancel in that dialog should keep the user in edit mode.

**Comment by akhenry** [comment]
Verified testathon 2016/06/16

**Comment by VWoeltjen** [comment]
Verified testathon 2016-06-16

**Comment by charlesh88** [comment]
Testathon 2016-06-16
Verified fixed.
