### ISSUE TITLE
Move and Link dialog's Locator is way too small

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#6654]
#### Summary
The Move and Link dialogs are using a different form builder configuration that doesn't size the Locator properly; it should be the same as the one used in Save and Duplicate.

Move/Duplicate
<img width="1046" alt="image" src="https://github.com/nasa/openmct/assets/1056412/ba5fea47-66f2-4762-a6b4-08bb7f5f32b4">

Save/Save As...
<img width="1044" alt="image" src="https://github.com/nasa/openmct/assets/1056412/85d71e88-7538-44ab-a09c-2bcfdb956a2a">

#### Steps to Reproduce

1. Use the Move or Duplicate action on an object.
2. Observe the resulting dialog's Locator element.

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by charlesh88** [comment]
### Testing Notes
1. See steps to reproduce above.

**Comment by charlesh88** [comment]
Testathon 2023-05-30 verified fixed.

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 05/30/23

**Comment by rukmini-bose** [comment]
Testathon Verified 5/30/2023 :)
