### ISSUE TITLE
Timelist To/From incorrect for 'current' activities

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#6657]
#### Summary
When an activity is 'current' (current timestamp is between the activity's start and end times) in a Timelist view, the To/From column should be displaying the `time to the end timestamp` of the activity.

#### Expected vs Current Behavior
Currently it shows the `time passed since the start timestamp`.

#### Steps to Reproduce
1. Create a timelist and drag a plan into it with at least 1 activity displaying as 'Current'.
2. Note the To/From column duration is incorrect.

#### Environment

* Open MCT Version: 2.2.2
* Deployment Type: All
* OS: All
* Browser: All

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by michaelrogers** [comment]
Fix verified on testathon. The Time/To From calculation is based on the End Time value rather than start time.
<img width="1017" alt="Screenshot 2023-06-20 at 2 21 49 PM" src="https://github.com/nasa/openmct/assets/7417521/0a31ea78-9d35-4f37-ad77-70079b048645">
