### ISSUE TITLE
Add role attribution to notebook entries

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#6664]
**Is your feature request related to a problem? Please describe.**
Notebook entries include the user who created the entry. Users may have more than one role, so it would be useful to also include the user's active role at the time they created the notebook entry

**Comment by jvigliotta** [comment]
May need to update export as well: https://github.com/nasa/openmct/blob/master/src/plugins/notebook/actions/ExportNotebookAsTextAction.js

**Comment by michaelrogers** [comment]
### How To Test

#### With user provider
1. Navigate to / create a notebook
2. Add a new entry
3. Observe that the new entry contains `username: role`
4. Change role and create a separate entry
5. Observe that changed role is captured on entry

Note: any existing entries prior to this feature will not have the role saved

### Without user provider
General smoke testing around notebook entries

### Notebook text export
1. Navigate to / create a notebook
2. Add sufficient number of entries (both created/modified by different users/roles)
3. `Export Notebook as Text`
4. Observe that the Created at and Modified lines include the user's active role when possible

**Comment by ozyx** [comment]
Testathon 7/18/23:

Verified! Adding an entry shows the username and current role. Switching roles and adding an entry shows the new role. Export as JSON / Export as Text preserves username and role.

Caveats (general):

- Viewer role still shows "CHANGE ROLE" button but does nothing
- The entries always show the role of the person that created the entry, but no info about who last modified the entry. More of an open question for @charlesh88

**Comment by unlikelyzero** [comment]
@ozyx please file those as two issues an remove the unverified label
