### ISSUE TITLE
Entries being lost in notebooks

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#6675]
#### Summary
Multiple users have reported losing notebook entries. The notebook entries appear to be added but upon navigating away and back the entries are gone. These issues have been observed even in notebooks that only have a single concurrent user, open in a single tab, suggesting that this is not a persistence conflict.

The persistence call to save a notebook entry could be getting backed up behind other pending requests and is never successfully persisted. Aside from reducing the number of requests overall, this could be improved by providing better user feedback, like an activity indicator that shows when an entry is saving. We should also prevent a user from adding additional entries when a persistence operation is taking place, this will highlight to the user sooner that a problem has occurred and reduce the amount of work lost.

There may also be some as-yet unknown issue with persisting notebook entries.

#### Steps to Reproduce
Exact steps are unknown at this point. Try adding entries to a single-user notebook with heavy network throttling in place.

#### Environment
* Open MCT Version: 2.2.0
* Deployment Type: MMOC

#### Impact Check List
- [X] Data loss or misrepresented data?
- [X] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [X] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by unlikelyzero** [comment]
Might be possible with a restart to Apache if you already have a notebook open.

**Comment by ozyx** [comment]
I’m able to reproduce by doing the following:

With two instances of chrome open (one chrome, one chromium):
1. Throttle chrome to slow 3g
2. Navigate both browsers to the display layout containing the notebook
3. On the throttled chrome, create a new page, name it, and then create an entry
4. While those are saving (progress bar is going), edit an existing entry on another page on the non-throttled browser
5. The new entry added on the throttled browser disappears after a “conflict detected” warning

**Comment by akhenry** [comment]
I've found the issue, it's related to transactions. I don't know exactly _how_ users are getting the application into this state (although I have found one reliable reproduction path), but once they do it's difficult to recover.

Here's how I reproduced it. It's probably _not_ how users are doing it in production, but hopefully enough for us to fix it.

1. Open a notebook
2. In dev tools, open the network tab and set throttling to "Slow 3G"
4. Add a new notebook entry and then very quickly navigate away to another object.
5. Navigate back to the notebook. Observe that the new entry section at the top is disabled. If it's not repeat steps 4 and 5 until it is.
6. Navigate away and back again
7. Observe that the new entry section is now enabled again.
8. In dev tools, clear network tab
9. Add several new entries and observe that no network traffic is created, the entries are not persisted.
10. Refresh the notebook and observe that any entries added after step 8 are gone.

**Comment by akhenry** [comment]
Although I can reproduce this issue using the above steps in version 2.2.0 of Open MCT in our VIPER MMOC environment, I cannot reproduce it in 3.0.0 snapshot. Closing to retest.

**Comment by akhenry** [comment]
# Testing Instructions
Follow reproduction steps in https://github.com/nasa/openmct/issues/6675#issuecomment-1659385547 and verify that the issue cannot be reproduced.

**Comment by khalidadil** [comment]
I'm not able to reproduce step #4 where the entry section at the top is disabled.

**Comment by ozyx** [comment]
Cannot reproduce. Fixed(?)

**Comment by davetsay** [comment]
throttled network and tried to stress the network by opening several instances of the map tool. could not reproduce loss of entries.
