### ISSUE TITLE
Time List view should not show milliseconds in times

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#6677]
#### Summary
The current implementation of Time List includes milliseconds in timestamps and durations. This is not inline with the original design; this uses up needed space and makes times harder to parse.

#### Expected vs Current Behavior
Times should be shown without milliseconds.

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by shefalijoshi** [comment]
Testing instructions:
Ensure that when you look at the timelist, activity start, end and duration don't show milliseconds.

**Comment by rukmini-bose** [comment]
Verified Testathon 6/22/23

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 06/22/23

**Comment by michaelrogers** [comment]
Fix verified during testathon 06/22/2023.
