### ISSUE TITLE
Create a quickstart Docker compose file which contains couchdb and yamcs/quickstart

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#6679]
We should create a flightlike docker compose setup with the following:

- flight.js with many of the available plugins 
- apache configured as a reverse proxy with a /yamcs/ and /couchdb/ route
- (bonus) apache configured with basic auth
- quickstart's `make all` and default networks used for apache's docker networks. `docker networks external: true`
- openmct's existing couchdb docker config used
- apache build with docker layer caching

**Comment by scottbell** [comment]
@unlikelyzero When you have a chance, could you please post the link to your example Docker Compose from the performance branch? Thank you!

**Comment by scottbell** [comment]
@unlikelyzero This is ready for review:
https://github.com/scottbell/openmct-quickstart

<img width="1564" alt="Screenshot 2023-06-28 at 11 39 57 PM" src="https://github.com/nasa/openmct/assets/9853862/93b090ef-e72b-4fbb-b3de-e5355b1a7882">

<img width="1524" alt="Screenshot 2023-06-28 at 11 39 52 PM" src="https://github.com/nasa/openmct/assets/9853862/be7eebcf-60fc-41c9-8719-3d2731a2bbd0">

@akhenry Did we ever hear back on a more official repository?

**Comment by scottbell** [comment]
@unlikelyzero let me know if we can close this.

**Comment by scottbell** [comment]
> @unlikelyzero let me know if we can close this.

@unlikelyzero Going to close for the interim. We can reopen if we need.

**Comment by unlikelyzero** [comment]
This was implemented as https://github.com/scottbell/openmct-quickstart
