### ISSUE TITLE
Increasing number of redundant requests made to search provider on tag added to an immutable object annotation

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#6689]
#### Summary

On adding a tag to an annotation of an immutable object such as a YAMCS telemetry plot, I'm seeing an increasing number of redundant requests made to the provider.

#### Expected vs Current Behavior

Expected:
- at most 2 - 4 requests made to providers (CouchDB) upon adding a tag to an annotation
Current:
- an increasing number of requests made depending on how many annotations you've looked at so far

#### Steps to Reproduce

1. Start Open MCT with YAMCS quickstart
2. Navigate to yamcs telemetry, make a few annotations on the plot and add some tags
3. Refresh the page and open the network tab in devtools. Set it to filter Fetch/XHR only
4. Click on an existing annotation and add a tag. Observe there are only 2 `_find` requests being made
5. Click on a bunch of the other existing annotations
6. Create a new annotation and add a tag
7. Observe an increased number of `_find` requests being made in the inspector

#### Environment

* Open MCT Version:  2.2.3
* Deployment Type:  openmct-yamcs quickstart
* OS: MacOS
* Browser: Chrome (any)

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [x] Does this have an impact on Performance?

#### Additional Information

https://github.com/nasa/openmct/assets/9259993/9904777a-48f8-4e23-955a-336ceea10c43

**Comment by scottbell** [comment]
yikes! nice catch @ozyx

**Comment by shefalijoshi** [comment]
Verified Fixed. When you navigate away from an object with annotations, subsequent views do not trigger annotation queries for tags on that object.
