### ISSUE TITLE
[Notebook] copy pasting long sentences into entries pushes trash and save buttons way right

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#6691]
#### Summary
Copy/paste a long sentence and see that the buttons are pushed outside of the entry body. click in the long sentence and type and observe the buttons get pushed even further

#### Expected vs Current Behavior
text should wrap and button should remain in the body of the notebook

#### Steps to Reproduce

1. copy a long sentence into clipboard
2. navigate to a notebook
3. edit or create a new notebook entry
4. paste the long text
5. observe buttons pushed right
6. click into long text and type
7. observe buttons push further right

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by unlikelyzero** [comment]
@davetsay  do you have an image

**Comment by scottbell** [comment]
This was also fixed via #7084 

https://github.com/nasa/openmct/assets/9853862/6c74f199-09b0-47de-9f7d-25660db4a710
