### ISSUE TITLE
[Data table] Create new Data Table type and view

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#670]
Create a new type and a new view to support scrolling lists of telemetry data that supports
composition by multiple telemetry points, 
* Sorting of columns, 
* Filtering of rows, 
* Selection of visible columns
* Display of historical or realtime telemetry
* Highlights rows in alarm state

**Comment by shobart** [comment]
It now exports, but the format is not user-friendly.  See Mark Shirley's comments in  #751 
Also, it seems to automatically download to the Download directory.  Would be good to give the user the option to select the location of where they want to download it.

**Comment by akhenry** [comment]
Addressed by #708
