### ISSUE TITLE
[Imagery] toggling an overlay layer by clicking label toggles for first imagery

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#6709]
#### Summary
If you have multiple imagery, and if you toggle an overlay layer by clicking the label, not the checkbox, then the layer toggles for the first image view, not the one you are toggling.

#### Expected vs Current Behavior
You should toggle the layer for the image the controls are in.

#### Steps to Reproduce
1. Create a display layout
2. Add multiple imagery views to the layout
3. hover over second image and click the layers dropdown
4. in the layers menu, click the label, not the checkbox, for a layer
5. observe that the layer appears over the first image, not the second one

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by rukmini-bose** [comment]
Verified Testathon 6/20/23
