### ISSUE TITLE
[Build] Configure jshint

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#671]
[Configure jshint](https://github.com/nasa/openmctweb/pull/642#issuecomment-180516276) to trigger build failures on possible defects identified via static analysis. Pull request for this issue should serve as venue for discussing which rules we actually want to enforce and why.

:information_source: __Note for testing__: This includes code style changes throughout the application. Search and persistence need particular attention when testing for regressions.

**Comment by charlesh88** [comment]
Testathon 20160512
Search itself seems like it's functioning as 'normally' as it ever did. One thing: dragging from search results into an item being edited doesn't give me a  gray 'drag and drop' proxy box while dragging. On drop, the item is added to the workspace view. Dragging from the browsing tree does display the proxy box.
Reopening for evaluation. If the drag behavior is a separate issue, let's file as such.

**Comment by VWoeltjen** [comment]
Could you define "proxy box" and "workspace view"? I'd like to see if I can reproduce this under the stable build (to determine if it's a regression or not)

In either case, would be easiest to handle that as a separate issue

**Comment by charlesh88** [comment]
By proxy box, I mean the grayed out rectangle that stands in for an object when you're dragging it. By "workspace view" I meant the view area of an object being edited; sorry about the poor choice of words.

I just tried this in live_demo as well as master, and I'm seeing the same behavior. I'll close this and file a separate issue.

**Comment by VWoeltjen** [comment]
Thanks, I understand now (that's actually what I thought you'd meant, but couldn't reproduce; I think that "gray box" is OS-specific, on Mac I get a translucent version of the tree node while dragging)

**Comment by charlesh88** [comment]
@VWoeltjen Would you mind quickly trying a drag from Search results and tell me if you see anything being dragged?

**Comment by VWoeltjen** [comment]
Yep, see the same thing whether I'm dragging from search results or from the tree

**Comment by charlesh88** [comment]
Chrome? What version? I see the same as you in Firefox, but not my Chrome.

**Comment by VWoeltjen** [comment]
Google Chrome	49.0.2623.112 (Official Build) (64-bit)

**Comment by charlesh88** [comment]
Filed #926 to cover this.
