### ISSUE TITLE
Support embedding images in notebook entries

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#6737]
Users have requested the ability to embed screenshots in Notebook entries. Notebooks already support embedding snapshots captured in Open MCT, and the same mechanism can be used for persisting screenshots captured by the OS. All that's really needed is to support dragging and dropping an external image into a notebook entry.

**Comment by scottbell** [comment]
@charlesh88 per @shefalijoshi you may have some thoughts on design for this. My thinking was the operator would drop an image onto the "Add Snapshots" area and it would embed the image in the same manner we embed screenshots.

**Comment by scottbell** [comment]
@akhenry @charlesh88 I’ve made some good progress (in that you can drop images onto entries!), but have some architectural questions. In particular, the way snapshots work currently, we create a separate object to hold the full resolution image. Do we want to do this for external images too? Do we want to use the snapshot workflow to do this, or just do it under the hood? Or alternatively, do we want to do the old method (judging from the code) of embedding the full resolution image in the entry itself? Thanks for the help!

**Comment by scottbell** [comment]
Per @akhenry, we're going to store the fullsize image as a separate object, the same as the snapshot works.

**Comment by scottbell** [comment]
https://github.com/nasa/openmct/assets/9853862/950b1b3c-f019-483c-b2e9-3a3d87aa54de

Basic functionality 👆

I'm going to write some basic tests and put a PR in for this.

**Comment by scottbell** [comment]
To test:

- Create a notebook.
- Drop an image onto the notebook
- Drop an image onto an existing entry
- Ensure image embeds persist across page reloads
- Annotate image
- Ensure annotations persist across page reloads
- Delete image
- Ensure deletion persists across page reloads

**Comment by unlikelyzero** [comment]
@scottbell this meets the definition of a feature and we need to schedule some feature testing time for this

**Comment by unlikelyzero** [comment]
Note: @scottbell to add a ticket for improving the error handling in the case that we're uploading the wrong file format

**Comment by scottbell** [comment]
> Note: @scottbell to add a ticket for improving the error handling in the case that we're uploading the wrong file format

@unlikelyzero added here #7097

**Comment by michaelrogers** [comment]
Issue verified during testathon 10/03/2023. I noticed that the thumbnail images were exported via JSON as base64, should there be a full size image that is exported to JSON or is the thumbnail sufficient? @charlesh88 or @scottbell?

**Comment by shefalijoshi** [comment]
Verified fixed (within the same domain). Note that dragging from Imagery views does not work unless you open the thumbnail image in a different browser window and then drag it into the notebook.

**Comment by scottbell** [comment]
@rukmini-bose I had some difficulty with replication the annotation issue:

https://github.com/nasa/openmct/assets/9853862/2e067c7b-f00f-440e-aa39-afc43cee6fd1

Is this roughly what you did?

**Comment by rukmini-bose** [comment]
@scottbell Yep– that's what I did. I also tried to replicate the problem, but I couldn't anymore (really weird). However, I'm seeing the same issue in which annotations do not persist upon a save, but I think it may have to do with the following error I am getting about the image I chose being too large: 
<img width="464" alt="Screen Shot 2023-10-04 at 9 59 53 AM" src="https://github.com/nasa/openmct/assets/48999852/5c29c8d8-641c-4517-8949-a0c0d4615001">

Is this a problem? I also have a full video showing what I did, so ping me if you want it– I wont upload it on here due to some VIPER links being exposed in the console.

**Comment by scottbell** [comment]
@rukmini-bose Yeah, the document too large this is coming from CouchDB, which we can catch to tell the user. Should we add it to this ticket #7097?

**Comment by rukmini-bose** [comment]
@scottbell Definitely. I'll add a couple comments to the issue

**Comment by scottbell** [comment]
Closing per @akhenry. We'll fix it on #7097
