### ISSUE TITLE
Imagery annotations don't appear on mount

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#6749]
#### Summary

When navigating to an imagery view (mutable or immutable, either on its own or embedded in a layout), existing annotations on the current image will not show until either the image canvas is clicked (focused), or the image thumbnail is toggled (to another image and back again).

#### Expected vs Current Behavior

The existing annotations for the current image should show on mount.

#### Steps to Reproduce

1. Create an Example Imagery
2. Add an annotation to it (shift + option + click and drag, add the tag in the inspector "Annotations" tag)
3. Quickly nav away and back so that the current image is still the one you annotated
4. Observe that no annotations appear
5. Click the image canvas
6. Observe that the annotations appear

#### Environment

* Open MCT Version:  2.1.5-SNAPSHOT
* Deployment Type:  local, testathon
* OS: MacOS
* Browser: Chrome

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information

https://github.com/nasa/openmct/assets/9259993/1ae58793-bf0b-4a7b-a0c8-c3aacf343102

**Comment by scottbell** [comment]
Testing instructions included in description.
