### ISSUE TITLE
[MCTTree] We've lost abort on closing of folders, could lead to bad performance

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#6753]
#### Summary
The tree has undergone some changes recently with converting the domainObjects to MutableDomainObjects. In the mix, we've lost the ability to cancel requests when a folder is closed. We should be able to set this back up relatively easily.

If we just grab the signal here:
https://github.com/nasa/openmct/blob/d8ac209a96dbd295ff3987b4ffff82178231efc7/src/ui/layout/mct-tree.vue#LL330C28-L330C28

Then pass it in here:
https://github.com/nasa/openmct/blob/master/src/ui/layout/mct-tree.vue#L332

The rest of the functionality seems to be in place. We should probably add a test for this as well.

#### Steps to Reproduce

1. Open network tab
2. Open/Close repeatedly an item in the tree (with couch persistence)
3. Should see canceled requests

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [x] Does this have an impact on Performance?

**Comment by jvigliotta** [comment]
## Testing
- open the network tab
- throttle the network
- open a tree item then close it quickly before the child items have resolved
- note cancelled requests in network tab

**Comment by ozyx** [comment]
Verified Fixed -- 07/19/23
