### ISSUE TITLE
[Timelines] Dragging a sub-activity to its parent creates a link

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#679]
1. Edit (or create) a timeline
2. Create a sub activity underneath an activity at the top level
3. Drag sub-activity to the timeline at the top level
4. Activity will be moved, but is now a link

**Comment by larkin** [comment]
There's another bug that will materialize here if we fix #678(which is marked critical) without fixing this issue (because of the solution for #656).  

It would be best if we fix this issue and #678 them at the same time.

**Comment by charlesh88** [comment]
Testathon 031516
While editing a Timeline with Activities, observed that dragging an Activity down the empty area of the upper left pane (tabular) area will create a  new Link whilst leaving the original Activity in place. User would expect that this would be a move operation, functionally equivalent to dragging the Activity onto the Timeline's first row.

**Comment by VWoeltjen** [comment]
> There's another bug that will materialize here if we fix #678(which is marked critical) without fixing this issue (because of the solution for #656).

Yep! (At least, if we're thinking of the same thing.)

Using branch from #773 and the scratchpad plugin (different space in the identifier, like Packets), and I:

1. Select Scratchpad
2. Create Timeline T
3. Add Activity A
4. Select Activity A
5. Add Activity B to Activity A
6. Drag Activity B to Timeline T (observe - a link, as described in this issue)
7. Save
8. Choose My Items in dialog
9. Hit OK

...everything is saved as expected, but Activity B still belongs to the `scratch` persistence space (which, in the case of Packets, would cause a plain persistence failure.)

At minimum, need to update the location of domain objects when moving them like this. However, want to take care that this does not cause unexpected behavior when dragging from the tree into the Timeline (I _think_ that in those cases we do just want the Activity to be a link - @charlesh88, is that correct?)

**Comment by charlesh88** [comment]
Testathon 032416
Verified fixed.

**Comment by RCarvalhoNASA** [comment]
20160324 Testathon, While I see that this works for dragging an activity into another activity, it seems like the drag to reorder within the same level of the timeline seems to be failing, I'll ping Charles on this and it may be another bug that is separate.

**Comment by akhenry** [comment]
This has been resolved by #790. The resolution is that sub-activities cannot be dragged into their immediate parent, dragging into higher parent will move and not link.

**Comment by akhenry** [comment]
Verified fixed, testathon 20160509
