### ISSUE TITLE
Console error when clicking on couchDBSearchFolder item

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#6794]
#### Summary
Notice that the following error is logged in the console when viewing clocky reports:
`classList of undefined` in the viewLargeAction `appliesTo` method

#### Expected vs Current Behavior
No console error is observed

#### Steps to Reproduce

1. On banner, expand the Clocky reports folder
2. Click on any report under that folder
3. Notice that the following error is logged in the console:

`classList of undefined`

#### Environment

* Open MCT Version: 2.2.6-SNAPSHOT
* Deployment Type: VIPER dev
* OS: All
* Browser: All

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment]
Verified fixed -- Testathon 7/19/23

**Comment by khalidadil** [comment]
@shefalijoshi I don't see any errors on testathon when viewing items under the "Clocky reports" folder, but the Example TTT report and the other TTT report don't load anything for me on testathon.
