### ISSUE TITLE
Time list view should use the global clock in fixed time mode

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#6797]
**Is your feature request related to a problem? Please describe.**
An [upcoming API change](https://github.com/nasa/openmct/issues/5773) introduces a global clock that is always available, irrespective of mode (fixed or real-time). This should be used to determine "now" in the time list view, rather than using the fixed mode start bounds [as we currently do](https://github.com/nasa/openmct/pull/6497/files#diff-3709092281067f6cef64e3e6af93a6f734d09503b5ae2821a6142bb74f23f623R208).

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shefalijoshi** [comment]
Testing Instructions:
1. Create and Timelist object and add a plan to it.
2. View the activity times are ticking along (up or down) with the currently active clock.
3. Change the active clock
4. Ensure that the times displayed in the Timelist now reflect deltas from the new clock timestamps

**Comment by ozyx** [comment]
Verified -- Testathon 7-28-23

**Comment by rukmini-bose** [comment]
Verified TEstathon 7/28/2023

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon 7/28/2023
