### ISSUE TITLE
Suppress role selection if no roles available

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#6801]
#### Summary
The openmct-yamcs adapter is currently prompting the user to select a role, even when no roles are available for the user (eg. they are the guest user). We should not prompt the user to select a role when there are no roles to select.

#### Steps to Reproduce
1. Pull down openmct-yamcs master
3. `npm run build:example:master`
4. `npm run test:e2e:quickstart`

#### Environment
* Open MCT Version: e386036dbfd1340907da46c84bf22e5f58e5305f
* Deployment Type: openmct-yamcs

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [x] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by akhenry** [comment]
# Test instructions
Follow the reproduction steps above and verify that the e2e tests pass.

**Comment by ozyx** [comment]
Testathon 7/24/23:
Still seeing this when my only role is "Viewer" (default). Clicking on the button does nothing.

**Comment by charlesh88** [comment]
Testathon 2023-07-26: verified fixed, with caveat that I still see the role selection button in the user Indicator although I only have one role: 
![image](https://github.com/nasa/openmct/assets/1056412/7f86f54c-ecaa-4ca7-8b36-2d3f6ced7fac)

**Comment by ozyx** [comment]
Looks good! I only have one role and it suppressed the `change role` button.

Verified fixed Testathon 7/26/23

**Comment by rukmini-bose** [comment]
Verified Testathon 7/26/2023
