### ISSUE TITLE
Issues with ctrl+hover gesture in plot legends 

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#6810]
#### Summary
The `ctrl+hover` gesture to get the full path has various issues.

1. When hovering over telemetry in legend, it does retrieve the full path, but  404s are in console and error notifications UI, and the hover displays `Missing: [The name of the object being hovered over]`

EDIT: This is only happening with telemetry added from the VIPER dictionary.

2. If an aggregate is dragged into a plot, `ctrl+hover` does nothing when hovering over in the plot legend.

3. When the telemetry, not overlay or other plot type, is selected in tree, The `ctrl+hover` gesture is not displaying full path.

#### Expected vs Current Behavior
No console errors. The full path is displayed without a missing object label just like hovering over the the object name in other display locations.

#### Steps to Reproduce
1. Create an overlay plot
2. Drag and drop telemetry from the VIPER dictionary into the overlay plot
3. Drag and drop an aggregate telemetry from the VIPER dictionary into the overlay plot.
4. Create a sine wave generator in the overlay plot

Issue 1
1. `Ctrl+Hover` over the VIPER telemetry from setup step 2 in the plot legend
2. Observe error notification, console error, and `missing:` prefix in hover tooltip

Issue 2
1. `Ctrl+Hover` over the aggregate telemetry from setup step 3 in the plot legend
2. Observe the tooltip does not show

Issue 3
1. `Ctrl+Hover` over the Sine Wave Generator from setup step 4 in the plot legend
2. Observe the tooltip works as expected
3. Select the Sine Wave Generator in the navigation tree
4. `Ctrl+Hover` over the Sine Wave Generator from setup step 4 in the plot legend
5. Observe the tooltip does not show 

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment]
Verified fixed -- Testathon 8/23/23. Verified the scenarios listed in the issue body work properly now

**Comment by charlesh88** [comment]
Verified fixed Testathon 2023-08-23.
