### ISSUE TITLE
Plots in Time Strip are not aligning properly with Plans

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#6812]
#### Summary
In Testathon 7/19/23, when a plot view is in a Time Strip with a Plan, it's not aligning properly with the Plan in time due to the plot's Y axis: 

![Screen Shot 2023-07-19 at 11 02 58 AM](https://github.com/nasa/openmct/assets/1056412/6ab391ef-0279-4253-9b34-5661c07d18e8)

#### Expected Behavior
The Time Strip is supposed to include any included plot's Y axes width into its offset calculation:

![image](https://github.com/nasa/openmct/assets/1056412/5aaef29c-73bb-4ed1-b344-eb95fc4723eb)

#### Environment

* Open MCT Version:  3.0.0 SNAPSHOT
* Deployment Type:  /latest, /testathon
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by charlesh88** [comment]
@akhenry to look for older duplicate issue.

**Comment by charlesh88** [comment]
One possible approach to a fix here is: instead of putting the plot axis into the left column in the DOM, first calc the space needed for the widest Y axis space for all plots included in the view, then use that value to offset the left edge of all other views (plans, imagery, etc.) so that everything lines up.

**Comment by unlikelyzero** [comment]
still critical

**Comment by charlesh88** [comment]
Testathon 2024-05-09: still not fixed. Purple and yellow dashed lines show elements that should be aligned.

![Screenshot 2024-05-09 at 2 31 37 PM](https://github.com/nasa/openmct/assets/1056412/04a830f8-a342-4f81-8314-d23f018f64bc)

**Comment by shefalijoshi** [comment]
Testing Instructions:
Create a Time Strip with different types of plots, stacked plots, overlay plots with multiple axes and a plan.
For example:

<img width="1412" alt="image" src="https://github.com/nasa/openmct/assets/5247066/5d6682fa-648d-43a1-8a92-2fd0341f8899">

**Comment by akhenry** [comment]
Looks good to me! Verified fixed.
