### ISSUE TITLE
[e2e] Add npm script for watch mode playwright execution

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#6816]
#### Summary
Playwright added a watch mode to watch tests as they execute in bulk. They also allow full test result summaries in line to provide faster failure triage.

**Comment by unlikelyzero** [comment]
### Testing Notes
1. Start openmct in another terminal with `npm run start:coverage`
2. Run the new npm script for e2e watch mode
3. Run a single test
4. Filter the available tests and run by filtered names
5. Run an entire suite (not all suites)

**Comment by khalidadil** [comment]
Verified in Testathon on 08/22/23 . I was able to start e2e tests in UI mode with `npm run test:e2e:watch`
