### ISSUE TITLE
Recent Objects do not update when object names are changed

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#6818]
#### Summary
Changes to a domain object name are not picked up by recent objects.

#### Expected vs Current Behavior
The recent object name should be updated at the same time the tree object name is updated.

#### Steps to Reproduce

1. Navigate to an editable object in the tree
2. Observe the object is listed at the top of recent objects
3. context click object and edit the name property
4. On save, observe the object name changes in tree but not in recent objects.

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by scottbell** [comment]
I've noticed the above behavior, where only the recent objects item fails to update, but also noticed that sometimes the item in the tree doesn't update either:

https://github.com/nasa/openmct/assets/9853862/1aaaaf4c-f872-41cc-ab61-bcd1c05ca1fd

Refreshing causes everything to update properly.

**Comment by scottbell** [comment]
I think [this issue](https://github.com/nasa/openmct/issues/5489) may have cropped up again

**Comment by scottbell** [comment]
By the time we get [to here in the tree](https://github.com/nasa/openmct/blob/master/src/ui/layout/mct-tree.vue#L717), the name is correct. For some reason it's not reactive down to the ObjectLabel though in either the tree or Recently Viewed.

**Comment by scottbell** [comment]
I think the issue here is the `key` we're using for the `v-for` isn't taking into account the `name`. Something like this:
```
:key="`${treeItem.navigationPath}-${index}-${treeItem.object.name}`"
```
appears to fix the issue.
