### ISSUE TITLE
Independent Time Conductor stops working after saving settings

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#6826]
#### Summary
Two problems:
1. Make any changes to the ITC and save, you cannot view the popup again upon a second click; you have to refresh to see it again. Console errors are thrown (see below) on clicking the popup's check button. 
2. Enabling the ITC and changing settings, then navving to another view (such as an Overlay Plot) sporadically causes the "Imagery View" view switcher to remain visible, even for an object type that doesn't use it. As of 7/21/23, @charlesh88 was not able to reproduce this.

<img width="1086" alt="Screen Shot 2023-07-19 at 11 20 32 AM" src="https://github.com/nasa/openmct/assets/48999852/5e2d78e2-7fbe-46be-8a2d-8d1de8c5b762">

4. Disabling the independent Time Conductor while the settings popup is visible causes the ITC to toggle closed but appear to still be active. When subsequently re-enabling, the settings popup will not be shown on click. 

<img width="391" alt="Screen Shot 2023-07-20 at 10 30 08 AM" src="https://github.com/nasa/openmct/assets/48999852/2369dce7-6f0b-4d31-bd21-5b49ec287706"> 

<img width="511" alt="Screen Shot 2023-07-20 at 10 33 00 AM" src="https://github.com/nasa/openmct/assets/48999852/b9fa93ca-0b44-4761-b161-5f426282f18c">

#### Environment

* Open MCT Version:  3.0.0 SNAPSHOT
* Deployment Type:  /testathon
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information
![image](https://github.com/nasa/openmct/assets/1056412/5e83749a-0c33-4b2b-9c5f-31ed91112f48)

**Comment by ozyx** [comment]
# Testing Instructions

- Follow repro steps above and verify the ITC is functioning nominally and there are no console errors

**Comment by ozyx** [comment]
The ITC functions, but still seeing some errors in the console when changing time bounds on the ITC in realtime mode:

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'setAttribute')
    at Proxy.eval (timePopupRealtime.vue:251:27)
    ```

**Comment by khalidadil** [comment]
I'm seeing the same thing Jesse is seeing, and also: when you open the settings popup for the ITC and then navigate to another object, the settings popup remains visible.

**Comment by shefalijoshi** [comment]
Created a new issue to track Issue 2 here: 6842
