### ISSUE TITLE
Remote clock periodically freezes

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#6828]
#### Summary
The Remote clock in the Time Conductor periodically freezes ticking, then starts again - frequently.

#### Environment

* Open MCT Version:  3.0.0
* Deployment Type:  /testathon
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by shefalijoshi** [comment]
Unable to reproduce - let's retest.

**Comment by jvigliotta** [comment]
Testathon - 7/24/23

Unable to reproduce, BUT there does seem to be an issue with the endpoint producing the serverTime and I believe that's what's causing the issue to manifest in the front end.

**Comment by ozyx** [comment]
Closing as a YAMCS issue.
