### ISSUE TITLE
Plots show incorrect data (realtime) independent time conductor is turned off

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#6831]
#### Summary
When you switch from the global time conductor to using the independent time conductor and then turn off the independent time conductor, the plots continue to show data for the independent time conductor bounds. (flickering)

#### Expected vs Current Behavior
Plots should show data only for either the global bounds or the independent time conductor bounds.

#### Steps to Reproduce
1. Ensure Open MCT has at least 2 clocks installed (Local clock and one other)
2. Create an overlay plot and add an endpoint (SWG works) to it and Save it.
3. Ensure the global time conductor is in Realtime mode with whichever clock results in plot data being drawn.
4. Enable the independent time conductor and change it's clock to the OTHER clock.
5. Note that the plot no longers displays data. (This is fine and expected)
6. Disable the independent time conductor.
7. Observe that the plot now flickers and the data being drawn is incorrect.
**WORKAROUND**: Refreshing the page shows the right data.

#### Environment

* Open MCT Version: 3.0.0
* Deployment Type: testathon
* OS: All
* Browser: All

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by rukmini-bose** [comment]
Testathon 7/26/2023 Verified
