### ISSUE TITLE
Timelist events don't tick down

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#6832]
Filed as VIPEROMCT-360

#### Summary

When using a Timelist with a Plan in it, in realtime mode the time does not count down.

#### Expected vs Current Behavior

The to/from times should count down as expected

#### Steps to Reproduce

1. Create a Timelist
2. Drag a Plan into it
3. Save and exit
4. Observe that the to/from counter doesn't count down

#### Environment

* Open MCT Version: ~~`3.0.0-SNAPSHOT`~~ `3.1.0-next`
* Deployment Type: local/testathon
* OS: MacOS
* Browser: Chrome

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by unlikelyzero** [comment]
Filed as VIPEROMCT-360

**Comment by ozyx** [comment]
# Testing Instructions
- Create a Timelist object
- Drag a Plan into it
- Switch to RealTime mode
- Verify that the 'Time To/From' field values continually update as time ticks

**Comment by rukmini-bose** [comment]
Verified Testathon 7/25/2023

**Comment by charlesh88** [comment]
Testathon 2023-07-25 verified fixed.

**Comment by ozyx** [comment]
Guess who's back... back again...

Reopening!
