### ISSUE TITLE
Show selected item in tree action doesn't work

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#6839]
#### Summary
Pressing the show selected item in tree doesn't focus on the item in the navigation tree and a continuous spinner is shown.

#### Expected vs Current Behavior
The item should come into focus in the tree and be highlighted.

#### Steps to Reproduce
1. Click on a folder in the tree (while it's collapsed)
2. Select a child item from the main view
3. Once the item is displayed in the main view, click on the show selected item in tree (button that looks like a target)
4. Observe a continuous spinner

#### Environment

* Open MCT Version: 3.0.0
* Deployment Type: viper/testathon
* OS: All
* Browser: All

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment]
Fixed by https://github.com/nasa/openmct/commit/ee3a1cca39c03fac7402ce01fcce72827e0cc3d2

# Testing Instructions

Follow repro instructions and verify that tree items load correctly and don't get stuck on continuous spinnner

**Comment by rukmini-bose** [comment]
Verified Testathon 7/26/2023

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 07/26/23
