### ISSUE TITLE
Independent time conductor popup is not dismissed on navigating to a different object

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#6842]
#### Summary
Enabling the ITC and changing settings, then navving to another view (such as an Overlay Plot) without closing the itc popup does not dismiss it.

#### Expected vs Current Behavior
The ITC popup should get dismissed if you navigate away from the currently viewed object

#### Steps to Reproduce
1. Enable the ITC in a view
2. Click on the ITC settings to bring up the popup
3. Navigate to a different item by choosing it in the tree
4. Observe that the ITC popup remains open

#### Environment

* Open MCT Version: 3.0.0
* Deployment Type: viper/testathon
* OS: All
* Browser: All

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by charlesh88** [comment]
Verified fixed Testathon 2023-08-22. Woot!

**Comment by rukmini-bose** [comment]
Verified Testathon 8/22/23

**Comment by charlesh88** [comment]
Why is this back for Testathon 2023-09-12?
