### ISSUE TITLE
[Display Layout] Multi-select marquee doesn't update on select

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#6843]
#### Summary

When selecting multiple items in a layout, the marquee doesn't update itself until one object is moved slightly.

#### Expected vs Current Behavior

The marquee should update to encompass all selected objects right away, on select.
It does not.

#### Steps to Reproduce

1. Create a Display Layout
2. Add two shapes
3. Save
4. Edit
5. Shift + Click both shape
6. Note in the inspector "2 objects selected" but the marquee only encompasses one
7. Move one object slightly
8. Note that the marquee updates to encompass all objects selected and works as expected

#### Environment

* Open MCT Version:  `3.0.0-SNAPSHOT`
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information

https://github.com/nasa/openmct/assets/9259993/cfb5c23b-714c-48ff-b861-df5f5e5e9036

**Comment by ozyx** [comment]
Fixed by https://github.com/nasa/openmct/commit/c1ed7b47023620a43d6b9eb688727ced00e2994b

# Testing Instructions

- Create a Display Layout
- Add two shapes
- Save
- Edit
- Shift + Click both shapes
- Verify the Edit Marquee encompasses both and you can move / resize correctly
- Add more shapes and verify it works for 3+ objects

**Comment by rukmini-bose** [comment]
Verified Testathon 7/27/2023

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 07/27/23
