### ISSUE TITLE
[Display Layout] Lines can be edited when not in edit mode. 

### ISSUE THREAD

**Issue by rukmini-bose** [nasa/openmct#6846]
#### Summary

In Display Layouts, you can currently edit a line's shape and size when NOT in edit mode. This should not be possible– if you aren't in edit mode, no draw objects should be able to be changed. This is potentially a big issue since it could allow users to accidentally drag lines when viewing, and potentially mess up complex displays. In addition, the change persists so upon refresh so there's no way to go back to the previous settings of the layout. 

https://github.com/nasa/openmct/assets/48999852/4b187161-3c7f-4fae-bcc4-74bf9226ddcc

#### Expected vs Current Behavior

Lines should not be able to be adjusted when not in edit mode.

#### Steps to Reproduce

1. Create a/navigate to a Display Layout
2. In edit mode, add a line object to the layout. 
3. Save the settings.
4. Click the line, and you can see that you can drag the line, adjust its length and orientation. 

#### Environment
 
* Open MCT Version:   Version: 3.0.0-SNAPSHOT
* Deployment Type:  /testathon
* OS:
* Browser: Chrome

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by shefalijoshi** [comment]
It appears that this has been the behavior for a while:
https://github.com/nasa/openmct/blob/master/src/plugins/displayLayout/components/DisplayLayout.vue#L199

**Comment by rukmini-bose** [comment]
Verified Testathon 7/31/2023

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 07/31/23

**Comment by ozyx** [comment]
Verified Fixed Testathon 07/31/23

**Comment by charlesh88** [comment]
Testathon 2023-07-31: verified fixed.
