### ISSUE TITLE
Console error when navigating away from a LADTableSet

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#6854]
#### Summary

On nav away from a LADTableSet, console errors are thrown while unregistering composition listeners.

#### Expected vs Current Behavior

No console errors should happen

#### Steps to Reproduce

1. Create a couple LAD tables
2. Create a LAD Table Set and add the LAD tables to it
3. Navigate to it
4. Navigate away, observe console errors

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information

![image](https://github.com/nasa/openmct/assets/9259993/a4d5fbcb-e300-49b2-bcae-df058a52a831)

**Comment by ozyx** [comment]
# Testing Instructions
1. Follow reproduction steps above and verify that no console errors are thrown on nav away

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 07/31/23

**Comment by charlesh88** [comment]
Testathon 2023-07-31: verified fixed.
