### ISSUE TITLE
Plan view showing duplicate scrollbars

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#6864]
#### Summary
For Plan views that aren't using clipped Activity names, in some cases the view will display multiple scroll bars and get into a repetitive "joggling" animation. This results from a second scrollbar being activated, which causes the area width to change and Activities to reflow, which then removes the second scrollbar and causes _another_ reflow, which then starts the cycle anew.

#### Main view
![Plan scroll boogie](https://github.com/nasa/openmct/assets/1056412/91e4cd79-509e-4f38-b52b-430a126d04c9)

#### In a Display Layout
![Plan scroll boogie in Display Layout](https://github.com/nasa/openmct/assets/1056412/2905438a-66dd-42a6-ae58-8b4fd0e5d07d)

#### Expected vs Current Behavior
The second scrollbar should not be displayed. Removing `overflow-y: auto` on `c-plan c-timeline-holder` fixes the problem, but make sure this doesn't mess things up in other views: 
![image](https://github.com/nasa/openmct/assets/1056412/8ede9e8a-61bd-4b8e-a36c-264e229c9c42)

#### Steps to Reproduce

1. Use a Plan view that doesn't use clipped Activity names.
1. Size the view area of a Plan view such that a number of activities are hidden beneath the scroll.
2. Slowly tweak the width of the view area until a second scrollbar appears and the view starts to joggle. While _increasing_ the area width, look for the moment when an Activity is allowed to flow horizontally after another but _just_ fits. Then, shrink the area width slowly until joggling occurs.

![Plan scroll boogie pane width drag](https://github.com/nasa/openmct/assets/1056412/663f662a-de5a-4306-a1d5-62431e575f22)

#### Environment

* Open MCT Version:  3.0.0
* Deployment Type:  
* OS: any
* Browser: all

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by charlesh88** [comment]
### Testing Notes
Follow replication steps above and ensure you can't replicate the problem.

**Comment by charlesh88** [comment]
Verified fixed Testathon 2023-08-22.

**Comment by rukmini-bose** [comment]
verified testathon 8/22/23
