### ISSUE TITLE
Toggling certain Plot Series options throws errors and doesn't work

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#6867]
#### Summary

Toggling Alarm Markers, Markers, or changing the value of the Marker style dropdown will throw errors. As a result, these options do not work.

#### Expected vs Current Behavior

There should be no errors thrown and markers / alarm markers should be able to be toggled and the marker style should be able to change. The settings should persist on save.

#### Steps to Reproduce

1. Create an Overlay Plot
2. Drag some telemetry into it (or SWG)
3. Edit
4. In the plot series options, toggle markers, alarm markers, change marker style dropdown
5. Notice errors and the alarm markers / markers / marker styles are not updated

#### Environment

* Open MCT Version:  `3.0.0-SNAPSHOT`
* Deployment Type:  testathon / local
* OS: MacOS
* Browser: Chrome

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information

![image](https://github.com/nasa/openmct/assets/9259993/da5ff509-cd3b-4ce8-be9e-07d6119c05af)

**Comment by ozyx** [comment]
# Testing Instructions

1. Create an Overlay Plot
2. Add some telemetry with limits to it (or SWG, preferably test both)
3. Edit
4. In the Plot Series options, activate and deactivate limits for different series
5. Verify they turn on and off
6. Save, navigate away, navigate back
7. Verify the setting persists
8. Activate and deactivate Alarm Markers
9. Verify they turn on and off
10. Save, navigate away, navigate back
11. Verify the setting persists
12. Change the marker style
13. Save, hover over the plot and verify it has changed
14. Toggling Markers on and off doesn't actually do anything due to [this issue](https://github.com/nasa/openmct/issues/6869), but toggle them and make sure no errors are thrown.

**Comment by akhenry** [comment]
Verified fixed.

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 08/01/23

**Comment by rukmini-bose** [comment]
Verified Fixed Testathon 8/1/2023
