### ISSUE TITLE
Remove large series models from reactive data in Plots

### ISSUE THREAD

**Issue by scottbell** [nasa/openmct#6879]
#### Summary

Plot configurations, highlights, and annotations have series models in them, and are reactive all the way down. We should instead being passing around series IDs instead of the full series model, and then have the individual components look up the series models internally. The trick here is they’ll need to then follow updates to add/removals of both series, and in the case of stacked plots, adding/removal of telemetry from the composition. I think this logic would be common to Legend components, MctPlot, and MctChart, and could exist in a separate helper class. The helper class could also return a series given an ID, which is what all these components want in the first place.

**Comment by scottbell** [comment]
With legends, was able to get a 4x speedup by removing series from `highlights` object. Before:

<img width="1232" alt="Screenshot 2023-08-07 at 3 30 42 PM" src="https://github.com/nasa/openmct/assets/9853862/64060d31-e6a9-498a-98af-619a6fd2c1e5">

After:
<img width="594" alt="Screenshot 2023-08-07 at 3 29 52 PM" src="https://github.com/nasa/openmct/assets/9853862/37784226-e74a-45c4-9fa3-9457988b92d0">

**Comment by akhenry** [comment]
This must have been an issue pre Vue3 as well, no? Does it improve steady state rendering of plots as well?

**Comment by scottbell** [comment]
> This must have been an issue pre Vue3 as well, no? Does it improve steady state rendering of plots as well?

Steady state looks about the same (surprisingly to me). It's anything interactive (zoom/rectangles/highlighting points) that drags the performance down with traversals of the big reactive objects.

**Comment by akhenry** [comment]
Got it, thanks, this helps me to prioritize the fix.

**Comment by scottbell** [comment]
To test:

- Create a high rate Sine Wave Generator (3Hz)
- Move mouse around and look at legend, should be much faster than previous incarnations.
- Create some annotations in real time mode and move mouse around. Should feel a lot faster.

**Comment by scottbell** [comment]
Before (note long mouseover time and annotation draw):
<img width="793" alt="before" src="https://github.com/nasa/openmct/assets/9853862/78609f3c-060d-4c78-8878-c1e62322c7cd">

After:
<img width="563" alt="after" src="https://github.com/nasa/openmct/assets/9853862/89789e2a-bf44-4993-85a0-9174db748771">

**Comment by ozyx** [comment]
Verified Testathon 9/12/23 -- Plots are much more responsive, with or without annotations

**Comment by rukmini-bose** [comment]
Verified Testathon 9/12/2023
