### ISSUE TITLE
Changes in timer state are not observed by other users

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#6880]
#### Summary
[A recent change](https://github.com/nasa/openmct/pull/6841) removed refresh calls from Timers which are necessary to ensure timer state is kept consistent between multiple users. This polling strategy was always sub-optimal, but worked for simple cases where remote change detection was not supported.

#### Expected vs Current Behavior
When one user changes the state of a timer (eg. pauses, plays, resets) all users observing that timer should also see the change.

#### Steps to Reproduce
1. Create a timer
2. Open that timer in two windows
3. Press play on the timer in one window
4. Expected behavior is that the timer starts playing in the other window as well.

#### Environment
* Open MCT Version: release/3.0.0
* Deployment Type: dev

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by jvigliotta** [comment]
## Testing 
- follow reproduction steps in issue description

**Comment by akhenry** [comment]
Verified
