### ISSUE TITLE
[CouchDB] init script is missing the create_users_db() step and creating lots of errors

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#6914]
#### Summary
init script is missing the create_users_db() step and creating lots of errors

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by unlikelyzero** [comment]
Testing instructions

1. Use the documentation to clear the couchdb instance
2. Start the container with the readme
3. Check that no errors appeared in logs with `docker logs couchdb1`
4. Remove the instance with provided documentation

**Comment by ozyx** [comment]
Will test

**Comment by ozyx** [comment]
Verified Testathon 10/5/23

Logs are clear of errors
