### ISSUE TITLE
Condition sets should send their time context with telemetry requests

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#6928]
**Is your feature request related to a problem? Please describe.**
Some telemetry providers (like yamcs) need to know if requests are being made in real time or fixed time span mode.
Condition sets should provide this information.

**Describe the solution you'd like**
Send in the time context to telemetry requests so that providers can use them as needed.

**Additional context**
Yamcs batches requests with size limit of 1 in real time mode.

**Comment by shefalijoshi** [comment]
Testing instructions:
1. Create a condition set with multiple telemetry endpoints.
2. Open the Network tab in chrome dev tools.
3. Create a condition widget and style it based on the condition set created in step 1. Save it.
4. Check that network requests are batched when possible. (like with yamcs)

**Comment by ozyx** [comment]
Verified fixed -- Testathon 8/23/23

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 08/24/23. I'm seeing a parameters:batchGet in the network requests
