### ISSUE TITLE
[TOOLING]: Add nvmrc file

### ISSUE THREAD

**Issue by evenstensberg** [nasa/openmct#6956]
#### Summary
Nvm is good for ensuring that the team is using the same node version.

Repo: https://github.com/nvm-sh/nvm

**Comment by unlikelyzero** [comment]
### Testing Notes
1. run nvm use on openmct

**Comment by davetsay** [comment]
verified `nvm use 18` uses node 18

**Comment by ozyx** [comment]
Testathon 8/22/23:
Verified! `nvm use` sets npm to latest lts version. Great stuff, thanks!
