### ISSUE TITLE
[INFRA]: Improve package.json fields more

### ISSUE THREAD

**Issue by evenstensberg** [nasa/openmct#6974]
#### Summary
Make package.json more informative and complete.

**Comment by unlikelyzero** [comment]
### Testing notes
Check that this change makes sense

**Comment by evenstensberg** [comment]
@unlikelyzero If this repo is published on npm, these changes will be visible in npm UI

**Comment by ozyx** [comment]
Verified -- Testathon 8/22/23

**Comment by davetsay** [comment]
verified changes look good
