### ISSUE TITLE
Messaging in role selection overlay is incorrect

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#6978]
#### Summary
The role selection overlay text reads as if role selection is solely for operator status. While true, it's for more than that. 

![image](https://github.com/nasa/openmct/assets/1056412/3c229b5c-932c-4a65-985c-8d49f7a68344)

#### Expected vs Current Behavior
The title says enough ("Select Role") and the hint text "Please select..." should be removed.

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by evenstensberg** [comment]
@charlesh88 can I fix this?

**Comment by ozyx** [comment]
# Testing Instructions

- Open the role selection dialogue for Operator Status
- Verify that the "Please select..." text does not appear

**Comment by charlesh88** [comment]
Verified fixed Testathon 2023-09-12.

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 09/12/23
