### ISSUE TITLE
Extraneous and invalid url params when using Open in New Tab action from certain objects

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#6982]
#### Summary

This was introduced by [this PR](https://github.com/nasa/openmct/pull/6025) back in 2.1.4.

Using the "Open in New Tab" action from certain objects, such as Plots and Notebooks, generates bad url params with function bodies:

```http://my-url-that-openmct-is-hosted-at.com/#/browse/mine/ad025953-ef7a-4e9a-a179-01171ca9f97f?tc.mode=local&tc.startDelta=900000&tc.endDelta=15000&tc.timeSystem=utc&view=plot-single&show=%28e%2Ct%2Cn%29%3D%3E%7Bo.parentElement%3De.parentElement%2Cr%28e%2Ct%2Cn%29%7D&getViewContext=%28%29%3D%3Es%3Fs.%24refs.plotComponent.getViewContext%28%29%3A%7B%7D&destroy=function%28%29%7Br&r%28%29%7D=&getComponent=%28%29%3D%3Es&key=plot-single&parentElement=%5Bobject+HTMLDivElement%5D```

#### Expected vs Current Behavior

URL params should NOT have stringified objects in them

#### Steps to Reproduce

1. Navigate to a plot (Sine Wave Generator works for this)
2. In the 3 dot menu, click "Open in New Tab"
3. See borked url params

#### Environment

* Open MCT Version:  2.1.4 and beyond
* Deployment Type:  any
* OS: any
* Browser: Chrome

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by unlikelyzero** [comment]
Putting this back to medium since the telemetry or object is discoverable through other means (search and direct linking)

**Comment by ozyx** [comment]
# Testing Instructions

- Navigate to a plot (Sine Wave Generator works for this)
- In the 3 dot menu, click "Open in New Tab"
- Verify that the url params look sane (there should be no deserialized view objects in the params)
- Repeat the same for some other objects / objects embedded in layouts

**Comment by rukmini-bose** [comment]
Verified Testathon 3/14/2024. Tested this on various objects, and it looks gucci!
