### ISSUE TITLE
[Imagery, Annotations] Do not show local controls when annotation gesture is active

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#6994]
**Is your feature request related to a problem? Please describe.**
Imagery and plots now allow the user to drag and mark areas in their views when holding down a key combo, in order to apply annotation tags to part of an image or selected data points in a plot. However, local controls get in the way when doing so.
![Screen Shot 2023-08-25 at 11 05 16 AM](https://github.com/nasa/openmct/assets/1056412/79dc2ed0-305d-47c3-bf57-b0e3422c7537)

**Describe the solution you'd like**
Only show local controls in an annotatable view if the user is _not_ pressing down the keyboard combo that triggers drawing an annotation selection area.

**Describe alternatives you've considered**

**Additional context**

**Comment by scottbell** [comment]
To test:

- Create some Example Imagery
- Click Option+Shift drag on the image to create an annotation
- Ensure while dragging image controls are hidden
- Ensure post drag image controls are visible again

**Comment by charlesh88** [comment]
Tracking in VOMCT repo as 413.

**Comment by rukmini-bose** [comment]
Verified Testathon 10/3/2023

**Comment by shefalijoshi** [comment]
This sort of worked for me. After adding the annotation, if it's behind imagery controls, selecting the annotation was a bit annoying.

**Comment by ozyx** [comment]
Verified fixed Testathon 10/3/2023
