### ISSUE TITLE
Timers don't count down or up to target date properly

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#7016]
#### Summary

When creating or editing a Timer, users can set a target date for the timer to count down or up to. This is broken, and on pressing play the timer always just resets to 0 and counts up from there.

#### Expected vs Current Behavior

The timer should count down or up to the specified target date

#### Steps to Reproduce

1. Create a Timer
2. Specify a target date
3. Press play
4. Note that the timer does not start counting until you reset from 0

#### Environment

* Open MCT Version:  3.0.1
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by msf-caesar** [comment]
Try with resetting the timer to the specified target date before pressing play. This way, the timer should start counting down or up from the desired target date instead of resetting to 0.

**Comment by ozyx** [comment]
# Testing Instructions

- Create a new Timer with defaults
- Verify that start, stop, pause, restart at 0 all function as expected
- Create a new Timer with a target date in the future
- Verify that the Timer counts down appropriately and all actions work as expected
- Create a new Timer with a target date in the past
- Verify that the Timer counts up appropriately and all actions work as expected
