### ISSUE TITLE
`hideTree` and `hideInspector` url param no longer hides the tree and inspector

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#7019]
#### Summary

URLs with `hideTree=true`and/or `hideInspector=true` in them used to hide the left pane tree or inspector. 

@unlikelyzero edit: This has been broken for quite some time.

#### Expected vs Current Behavior

It should hide and inspector the tree on load.

#### Steps to Reproduce

1. Add `hideTree=true` as a url param to any openmct url and navigate to it
2. Notice that the tree is still expanded

#### Environment

* Open MCT Version:  >=3.0.0
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by msf-caesar** [comment]
Try with the following solution: Instead of using the `hideTree=true` URL parameter, try manually collapsing the left pane tree by clicking on the collapse arrow next to the tree. This should hide the tree on load without requiring any code changes.

**Comment by ozyx** [comment]
# Testing Instructions

1. Add `hideTree=true` to the url params and navigate
2. Verify that the left pane is collapsed on nav
3. Add `hideInspector=true` to the url params and navigate
4. Verify that the right pane is collapsed on nav
5. Add both to the url params and navigate
6. Verify that both panes are collapsed on nav

**Comment by charlesh88** [comment]
Verified fixed Testathon 2023-09-12.

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 09/12/23
