### ISSUE TITLE
Notifications have ProgressBar artifacts in them

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#7022]
#### Summary

Notifications now have tiny ProgressBar artifacts next to the message body. This regression seems to be caused by some change introduced here: #6953 

#### Steps to Reproduce

1. Create a notification via the Open MCT API
2. Notice a ProgressBar artifact next to the notification message contents

#### Environment

* Open MCT Version:  3.1.0-next
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information

<img width="1791" alt="image" src="https://github.com/nasa/openmct/assets/9259993/a746c489-55e3-47ed-9dfe-786628e3bf9b">

**Comment by msf-caesar** [comment]
Try with removing or reverting the change introduced in commit #6953 that caused the regression. This should help eliminate the ProgressBar artifacts in the notifications. Additionally, ensure that thorough testing is done before deploying any changes to prevent similar visual bugs from occurring in the future.

**Comment by ozyx** [comment]
Verified Fixed -- Testathon 3/5/24
