### ISSUE TITLE
Display Layout editing tools overlaps inspector

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#7036]
#### Summary
display layout editing tools are overlapping the inspector area

#### Expected vs Current Behavior
display layout editing tools should not overlap the inspector area

#### Steps to Reproduce

1. create a display layout
2. click + and add any layout object to the layout
3. select the object if necessary and verify you see the editing tools in the toolbar
4. make the inspector and tools in the main view overlap (zoom the window, reduce the size of the window, drag the inspector left)
5. observe tools and inspector text overlaps

#### Environment

* Open MCT Version: latest
* Deployment Type: 
* OS:
* Browser: chrome

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information
<img width="1216" alt="image" src="https://github.com/nasa/openmct/assets/3614296/aa2d3938-0c78-4b7e-a95f-f8ecd22329c5">

**Comment by charlesh88** [comment]
### Testing Notes
Follow steps to reproduce as above and verify that the toolbar is clipped when panes are resized as shown below.

![Screen Shot 2023-09-05 at 4 44 18 PM](https://github.com/nasa/openmct/assets/1056412/5def2668-410f-4ef4-9c02-2b37d59f01de)
