### ISSUE TITLE
Data Visualization Inspector Tab

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#7041]
**Describe the solution you'd like**
View plots and images in the inspector, as it relates to a selection

**Additional context**

**Testing Instructions**
See related VIPER implementation ticket

**Comment by akhenry** [comment]
> Testing Instructions
>  See related VIPER implementation ticket

Which VIPER ticket?

**Comment by unlikelyzero** [comment]
Testing as a part of the viper ticket
