### ISSUE TITLE
Double clicking on an image in a layout should embiggen it but does not.

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#7055]
#### Summary
When an image is embedded in a display layout a user should be able to double click on the image to show a larger version of that image.

#### Workaround
1. Use the "Large View" button
2. Double click on the gray background around the image itself.

#### Steps to Reproduce
1. Create a layout
2. Drop an image into the layout
3. Save and Finish Editing
4. Double click on the image
5. Observe that nothing happens.
6. Double click on the gray area around the image
7. Observe that the image is enlarged as expected.

#### Environment
* Open MCT Version: 3.0.1+
* Deployment Type: MMOC, Dev
* Browser: Chrome 116.0.5845.187

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment]
# Testing Instructions
1. Create Example Imagery
2. Navigate to it
3. Double click on the image, confirm that it embiggens
4. Close
5. Double click on the grey border around the image, confirm it does not embiggen

**Comment by rukmini-bose** [comment]
Verified Testathon locally on 1/18/2024
