### ISSUE TITLE
Have annotations work with domain objects that have dots

### ISSUE THREAD

**Issue by scottbell** [nasa/openmct#7063]
#### Summary
Annotations that have periods in their domain object IDs (like YAMCS aggregated telemetry) aren't retrievable  with CouchDB. Periods are a special character in JSON. Namely the targets of the annotations look like this:
```
"targets": {
      "taxonomy:~myproject~Gyro.x": {
        "minX": 1694597219934.105,
        "minY": 13.14969686405388,
        "maxX": 1694597312669.8083,
        "maxY": 29.724520818440027
      },
      "taxonomy:~myproject~Gyro.y": {
        "minX": 1694597219934.105,
        "minY": 13.14969686405388,
        "maxX": 1694597312669.8083,
        "maxY": 29.724520818440027
      },
      "taxonomy:~myproject~Gyro.z": {
        "minX": 1694597219934.105,
        "minY": 13.14969686405388,
        "maxX": 1694597312669.8083,
        "maxY": 29.724520818440027
      }
    }
```

The `taxonomy:~myproject~Gyro.y` is causing the CouchDB query fits because it's interpreting y (and x and z) as sub-properties of the target instead as part of the domain ID.

Unfortunately Couch doesn't allow regex on the field name during search, so we can't just escape the dot in the query. The solution we're going to pursue is refactoring the annotation to look like this:
```
"targets": [
    {
        "keyString": "taxonomy:~myproject~Gyro.x"
        "minX": 1694597219934.105,
        "minY": 13.14969686405388,
        "maxX": 1694597312669.8083,
        "maxY": 29.724520818440027
      }
    ]
```

Namely, make the target an array (instead of an object).

#### Expected vs Current Behavior
Annotations should be able to work on aggregated telemetry in YAMCS.

#### Steps to Reproduce
1. Find an aggregate piece of telemetry (like `Gyro` in YAMCS Quickstart).
2. Drop a piece of the aggregated telemetry onto a Overlay Plot (e.g., `Gyro.x`)
3. Attempt to tag some data
4. Note that the tag never takes, though the tagged area is searchable by GrandSearch, the points never show up

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by scottbell** [comment]
I think with the restructured annotations, we've got a solution:

https://github.com/nasa/openmct/assets/9853862/4eccbea2-d1ef-4662-845e-6fe286377b05

**Comment by scottbell** [comment]
@scottbell TODO: add some data about adding a ton of objects and how the index works.

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 09/22/23. I was able to add annotations to telemetry with a dot in the name as well as search and pivot back to the annotated points.

**Comment by rukmini-bose** [comment]
Verified Testathon 9/23/2023, looks good!

**Comment by ozyx** [comment]
- Verified the annotation removal script works on testathon

- Verified that plot annotations work with aggregate members
- Verified that map annotations work with the new format
- Verified that image annotations work with the new format (bug found)
- Verified that notebook annotations work with the new format
