### ISSUE TITLE
[Table] Add realtime scrolling data display

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#707]
Currently the new Table component only supports the display of historical data. Update this to support realtime.

**Comment by VWoeltjen** [comment]
A _nice-to-have_ in the context of this issue would be some auto-scroll behavior that ensures RT values are displayed. There may be design concerns/nuances with this (or implementation may be non-trivial); if so, should spin off into a separate issue. In particular, there may be exceptions to when you want to auto-scroll (e.g. if the user has explicitly scrolled to the middle)

This auto-scroll behavior will be important for real-time monitoring of event messages (particularly as part of a larger display.) Desired sort order in this case will be for new messages to appear at the bottom (so event messages can be read top-to-bottom in the order they occur.) However, in the absence of auto-scroll, user would need to manually scroll down to see the latest messages, which in turn may be coming in very frequently (1Hz or faster); without auto-scroll, a user would need to devote significant attention to just keeping the latest data in view.

**Comment by akhenry** [comment]
This was implemented by #733

**Comment by akhenry** [comment]
@VWoeltjen There is support (albeit limited) for autoscrolling in #733. Event messages (assessed by testing if telemetry type is "string") will automatically auto-scroll. That is, scrolling will stay at the bottom of the table as new telemetry comes in.
Some notes on the implementation:
* Auto-scroll can be disengaged by scrolling away from from the bottom of the table. Doing so will mean that user it not snapped back to the bottom of the table if they have explicitly scrolled away.
* Auto-scroll can be enabled on any telemetry table by scrolling to the bottom of the table. It can likewise be disabled by scrolling away from the bottom of the table.

**Comment by charlesh88** [comment]
Testathon 031516
Verified working, but with issues - no column for datetime. Andrew has filed a bug for this.
