### ISSUE TITLE
"WebGL context lost" when loading plots

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#7081]
#### Summary

When re-rendering multiple plots (but fewer than 16), the warning can be seen in the console:
`WARNING: Too many active WebGL contexts. Oldest context will be lost.` 

Plots fall back to canvas2D and WebGL contexts don't seem to become immediately available, so this warning is seen multiple times.

#### Expected vs Current Behavior

If there are < 16 known active WebGL contexts on the page, we should not see this warning. Plots should not fall back to 2D.

#### Steps to Reproduce

1. Create a Flexible Layout with 4 SWGs
2. Clone it
3. Flip back and forth between the two flexible layouts with your console open
4. Navigate to some SWGs directly 
5. Notice the warning in the console and plots fall back to 2D

#### Environment

* Open MCT Version:  3.1.0-next
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [x] Does this have an impact on Performance?

#### Additional Information

https://github.com/nasa/openmct/assets/9259993/a723a63f-5356-4d79-b6b2-69f18e3a49d6

**Comment by ozyx** [comment]
# Testing steps

- Follow steps to reproduce and verify that you no longer see the "Lost WebGL context" warning in the console

**Comment by rukmini-bose** [comment]
Looks good, verified testathon 10/3/2023
