### ISSUE TITLE
It is possible to create image annotations that cannot be selected

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#7083]
#### Summary

It is possible to create unselectable (and thus unremovable) image annotations.

#### Expected vs Current Behavior

Image annotations should always be selectable.

#### Steps to Reproduce

Reproduction steps semi-unknown at this point.

1. Use CouchDB persistence or test in our testing environment
2. Navigate to a display layout with real imagery
3. Hold option+shift and click and drag from the BOTTOM RIGHT to the TOP LEFT to create the annotation box
4. Tag it
5. The annotation is unselectable and unremovable.

#### Environment

* Open MCT Version:  3.1.0-next
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information

https://github.com/nasa/openmct/assets/9259993/a9805e3a-979c-4471-b4f9-845ced7e0930

**Comment by ozyx** [comment]
Saw this again in Testathon 10/3/2023 while creating the first annotation for non-mutable imagery. It's possible that the next image came in while I was annotating this one. Is that an edge case that could cause problems? @scottbell

**Comment by scottbell** [comment]
> Saw this again in Testathon 10/3/2023 while creating the first annotation for non-mutable imagery. It's possible that the next image came in while I was annotating this one. Is that an edge case that could cause problems? @scottbell

@ozyx If it's coming up regularly, I think it's something we'll want to address.

**Comment by scottbell** [comment]
Going to try to replicate this and figure out what's going on.

**Comment by scottbell** [comment]
@ozyx I'm having a devil of a time trying to reproduce this. If we've got the bad annotation still up, would it be possible for us to take a look together?

**Comment by scottbell** [comment]
The issue is creating the annotation by clicking and then dragging back and to the left, which creates a negative height and width. This needs to be findable in the the annotation index.

**Comment by scottbell** [comment]
To test:

- Bring up example imagery
- Alt+shift drag to create some tags
  - Create tag by clicking and dragging up and to the left
  - Create tag by clicking and dragging up and to the right
  - Create tag by clicking and dragging down and to the left
  - Create tag by clicking and dragging down and to the right
- Ensure all rectangles that you created and selectable/editable/deletable

**Comment by michaelrogers** [comment]
Fix verified during testathon on 10/23/2023, when following the testing steps all rectangles were selectable/editable/deletable.

**Comment by rukmini-bose** [comment]
Verified Testathon 10/23/2023

**Comment by davetsay** [comment]
verified

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 10/23/23
