### ISSUE TITLE
[New Edit Mode] Animate transition into/out of NEM

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#709]
Switching into and out of NEM can be slightly jarring, as the top edge of the view of the object being edited needs to jump slightly to accommodate the tool bar area. Animation could be used to make this transition feel more seamless.

(Certainly low priority, proposing since it may be easy to implement.)

**Comment by charlesh88** [comment]
Actually, I do (or did) have an animation on this. May have gone missing due to a merge, and there are some other things going on at the same time. I'll take a look.

**Comment by charlesh88** [comment]
See notes in the PR #987; I can't apply a transition on exiting Edit mode at this time. Leaving this open and reassigning to discuss what's needed to allow a transition out. Basically, transitional animations have to be allowed to execute before the DOM is manipulated to remove elements.

Checkout the remove function in https://jsfiddle.net/MadLittleMods/EM4xL/

**Comment by VWoeltjen** [comment]
Verified in testathon, 6/16/2016
