### ISSUE TITLE
Plans are not updating automatically - browser refresh required

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#7098]
#### Summary
When viewing a plan, if changes occur to the plan in the persistence storage, the changes don't reflect in the plan view without a browser refresh.

#### Expected vs Current Behavior
Browser refresh should not be required for plan updates

#### Steps to Reproduce
1. View an existing plan (on VIPER, in the the VIPER plans directory)
2. Keep the view up and make changes to the plan JSON remotely (via the couch db fauxton interface?)
3. Expected: The changes should be reflected in the plan view immediately
4. Actual: The plan doesn't update unless a browser refresh is done.

#### Environment

* Open MCT Version: 3.0.2 / 3.0.1
* Deployment Type: VIPER
* OS: All
* Browser: All

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by akhenry** [comment]
Upgrading to 3.1.0 release blocker. With a green card not a SIM blocker

**Comment by ozyx** [comment]
Verified fixed Testathon 10/3/2023

**Comment by charlesh88** [comment]
Testathon 2024-03-20 cannot repro, fixed.
