### ISSUE TITLE
[Notebook] Notebook entry hover isn't triggering properly

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#7105]
#### Summary
Selecting and then hovering over the text content of a Notebook entry should darken the area of the text, indicating it is editable. 
<img width="619" alt="image" src="https://github.com/nasa/openmct/assets/1056412/7971ddb0-2d7a-40ed-ba58-e79cf8aabce4">

This works if the entry is selected by clicking outside the text area, but it doesn't work if the user selects the entry by clicking in the text content area itself - hovering when having selected that way doesn't do anything on hover.

#### Expected vs Current Behavior
No matter how an entry is selected, hovering over the content area should visually indicate the edit affordance.

#### Steps to Reproduce

1. In a Notebook, select an unselected entry by clicking at the very top of it in the datetime stamp area.
2. Hover over the entry's text area, note that the background under the text changes visually.
3. Select another entry by clicking directly on its text.
2. Hover over the entry's text area, note that the background under the text does not change visually.

#### Environment

* Open MCT Version:  3.1.0-next
* Deployment Type:  local
* OS: Mac
* Browser: Chrome

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by charlesh88** [comment]
### Test Notes
Perform 'Steps to Reproduce' as above and ensure that step 4 does not occur as described, but instead occurs as described  in step 2.

**Comment by ozyx** [comment]
Verified fixed Testathon 1/17/24

https://github.com/nasa/openmct/assets/9259993/f43faf91-a3c8-4648-bde0-6c4a463917fd

**Comment by davetsay** [comment]
verified

**Comment by rukmini-bose** [comment]
Verified Testathon 1/17/2024
