### ISSUE TITLE
Suppress log statements from `cspell`

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#7109]
#### Summary

`cspell` produces a lot of log bloat in CI. We should use the `--quiet` option to only show spelling errors in order to reduce bloat.

**Comment by ozyx** [comment]
# Testing

1. Run `npm run lint:spelling`
2. Verify that output is quiet and only misspellings are output

**Comment by michaelrogers** [comment]
Fix verified during testathon on 10/23/2023. The --quiet flag is properly applied to cspell.

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 10/23/23
