### ISSUE TITLE
[Time List view] Time List view ignores Current Events "Don't show" setting

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#7113]
#### Summary
Time List view allows filtration of its view based on an event's Start and End datetimes. Setting Current Events to "Don't show" doesn't work, but should.

![Screen Shot 2023-10-04 at 4 13 40 PM](https://github.com/nasa/openmct/assets/1056412/b9666a35-0d74-4a94-8a56-87fdd2b7b298)

#### Expected vs Current Behavior
Setting Current Events to "Don't show" should suppress the display of any event that has a Start datetime after "now" in the current clock.

#### Steps to Reproduce

1. Identify a Plan file that has a collection of events that have Start datetimes earlier ("current events") and later ("future events") from "now" (in either local or remote clock), all of which have End datetimes after now.
2. Add the Plan to a Time List view. Set the view as shown in this screencap: 

![image](https://github.com/nasa/openmct/assets/1056412/c20c1997-7119-4c7e-bd79-52b73e858ebc)

3. Save and exit edit mode. 
5. Observe: you will see "current" events in the view as above. One can use the browser's Inspector to confirm that the view thinks these are current events as well:

![image](https://github.com/nasa/openmct/assets/1056412/7d7617fd-d89e-4e40-b32b-b7f33fa40182)

#### Environment

* Open MCT Version:  3.0.1
* Deployment Type:  MMOC
* OS: all
* Browser: all

#### Impact Check List

- [X] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [X] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by shefalijoshi** [comment]
As per conversation on 10/19/20203, We will:
1. Enable independent time conductor for the timelist view. (This will handle showing past or future activities)
2. Remove the `Timeframe` section from the inspector
3. Add a single checkbox to show/hide current activities.
4. Filtering should use more metadata (TBD)

**Comment by charlesh88** [comment]
### Testing Notes
#### Setup
Start with a Time List view and add a Plan to it that has events in the past, current and future. This [Open MCT export](https://github.com/nasa/openmct/files/13126090/Time.List.test.7161.json.zip) includes all needed Time List views plus a Plan with events from 10-23-23 to 11-10-23.

- **Create a Current events Time List**: Edit the Time List view to show all current events, and set its Independent Time Conductor (ITC) to 1 second into the past and 1 second into the future. 
- **Create a Past events Time List**: Duplicate the above Time List, and edit it to set Current Events to "Don't show". Set its Independent Time Conductor (ITC) to 4 hours into the past and 0 time into the future. 
- **Create a Future events Time List**: Duplicate the Past events Time List, and set its Independent Time Conductor (ITC) to 0 time into the past and 4 hours into the future. 

#### Testing
1. View the Time Lists and alter the ITC settings on all. Verify that events are brought in and out of view as expected.
2. Compare the Time List views to the included reference image and verify that the colors are consistent for the type of events (past, current and future).

**Time List views in Espresso**
![Screen Shot 2023-10-24 at 11 55 54 AM](https://github.com/nasa/openmct/assets/1056412/1d261e41-52d8-4ede-a7fd-0b28a452aad4)

**Time List views in Snow**
![Screen Shot 2023-10-24 at 11 48 05 AM](https://github.com/nasa/openmct/assets/1056412/e7abfbcc-1b82-4e60-b65a-3df96e49fa8f)

**Comment by ozyx** [comment]
Verified Fixed Testathon 11/13/23

**Comment by rukmini-bose** [comment]
Verified Testathon Fixed 11/13/2023
