### ISSUE TITLE
[Notebook] Fixes for Markdown in Notebook entries

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#7119]
#### Summary
There are a number of issues with markdown in Notebook entries that should be fixed:
1. Block quotes are not being tokenized as such, but are instead being HTML-encoded: `> block quote` gets encoded as `&gt; block quote`. Instead, block quotes should work as documented for vanilla markdown.
2. Space before headings (H1, H2, etc.) is missing: 

**Desired output**
![image](https://github.com/nasa/openmct/assets/1056412/0c9aecfb-4428-48d5-8382-494b466b675b)

**Rendered output**
![image](https://github.com/nasa/openmct/assets/1056412/c80e1974-666b-4239-8247-1b2cbf20b031)

CSS currently adds vertical space under the headings, but doesn't add it above. This was done to avoid adding unnecessary vertical space before headings when they're the first line in an entry. However, CSS can be properly written to avoid this and should be implemented here.

#### Steps to Reproduce

1. In a Notebook entry, reproduce the identified issues above as noted.

#### Environment

* Open MCT Version:  3.1.0
* Deployment Type:  /testathon
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by scottbell** [comment]
@charlesh88

>Block quotes are not being tokenized as such, but are instead being HTML-encoded: > block quote gets encoded as &gt; block quote. Instead, block quotes should work as documented for vanilla markdown.

I've got a fix for this in this [PR](https://github.com/nasa/openmct/pull/7115).

>Space before headings (H1, H2, etc.) is missing
This appears to be a Markdown thing, so I'm not sure we can change this. E.g., on both the [Marked demo](https://marked.js.org/demo/?text=%23%20%20%20%20%20%20%20no%20spaces%20preserved%0A%23%23%20%20%20%20on%20any%20size%0A&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%0A%7D&version=9.1.0) and the here on Github's markdown editor, this:
```markdown
#       no spaces preserved
##    on any size
```

renders as:
#       no spaces preserved
##    on any size

**Comment by scottbell** [comment]
To test:
1. Create a blockquote in a notebook entry using markdown (using `>` characters)
2. Ensure it appears indented in the code, and creates a `<blockquote>` in the HTML

**Comment by shefalijoshi** [comment]
Verified fixed
