### ISSUE TITLE
Fix remaining `vue-compat` warnings

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#7124]
#### Summary

In order to finish migrating to Vue 3 proper, we will need to fix all of the remaining warnings generated from `vue-compat`.

**Comment by khalidadil** [comment]
Are there any specific areas we should be testing for this @ozyx? The PR looks huge!

**Comment by khalidadil** [comment]
I clicked around a bunch of existing objects I had, and I didn't see any console warnings other than ones we generate. I'll wait to mark this verified until @ozyx responds with any specific areas to test.

**Comment by ozyx** [comment]
@khalidadil ah! sorry about that. Yeah, the PR is massive! Verification for this is really just verifying that the `vue/compat` package has been removed and e2e + unit tests continue to pass. The fact that it was merged is a verification enough, I guess??
