### ISSUE TITLE
[Time List view] Better format for To/From "Days Hours" timestamp

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#7130]
**Is your feature request related to a problem? Please describe.**
The Time List view uses a confusing and non-standard time format using a colon delimiter between the days and hours values:
> -01:10:53:23

This is hard to read, and it's easy to confuse the days portion as hours. Additionally, durations of less than 24 hours use a "00" for days; in most cases in operations, users won't use this view outside a window of a few hours - always including a day value portion adds unnecessary noise. Finally, this is inconsistent with how we display this kind of value in our Timer views.

**Describe the solution you'd like**
1. Change the display to make the different values more clear, and also more consistent with how the same information is displayed in Open MCT Timers:
> -1D 10:53:23

The days number should not be zero padded, and use as many digits as it needs.
2. Only include the days portion when the value is greater than 24 hours:
> -10:53:23

**Comment by shefalijoshi** [comment]
Testing instructions:
Use a large time range (days) in the past and future and view time list activities.
Ensure that days are represented with a +/- D
If there is no day value, then only hours, minutes and seconds should be displayed.

**Comment by ozyx** [comment]
Verified Testathon 1/17/24

**Comment by rukmini-bose** [comment]
Verified Testathon 1/17/2024
