### ISSUE TITLE
Defer rendering for inactive tabs in Open MCT Tabbed View

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#7132]
**Is your feature request related to a problem? Please describe.**
The Open MCT Tabbed View allows users to create displays with multiple complex embedded displays within them. Chrome and other browsers have an optimization that throttles callbacks to `requestAnimationFrame` for inactive _browser_ tabs and we should implement something similar for inactive tabs in an Open MCT Tabbed View.

**Describe the solution you'd like**
An API function that wraps `requestAnimationFrame` and replaces it wherever we are using it in our views. This function would be aware of the visibility of the calling component and only actually call the wrapped RAF callback if the component is in an active tab.

Potential means of detecting visibility include:
1. The tabbed view emitting an event on active tab change that is observed by all child views
OR
2. Doing something snazzy with [Intersection Observers ](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) to determine whether the component is visible and not obscured by another tab. The benefit of this approach is that it potentially handles the case where a component is scrolled outside of the viewport. While this case shouldn't typically happen during mission usage (displays should be sized to the operator's workstation) it would still be a nice feature to have.

Let's also use tab visibility awareness to release Web GL contexts from inactive tabs.

Do some experimentation, propose an API, and then let's review the proposal.

**Comment by scottbell** [comment]
I've been fiddling with Intersection Observers, and I think that's the best route. We can use the `el` in the `ViewProviders`, and then only fire requestAnimationFrame if the visibility is true (namely, [isIntersecting](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserverEntry/isIntersecting) set to `true`).

https://github.com/nasa/openmct/assets/9853862/2d43c583-6a38-41df-bcdc-2f05aee4555a

I'll come up with an API next.

**Comment by scottbell** [comment]
@akhenry I've got a proposed API in this draft PR: #7149

**Comment by scottbell** [comment]
@akhenry Here's performance before. Note the CPU remains pretty heavy regardless of tab chosen:

https://github.com/nasa/openmct/assets/9853862/b8356342-c928-42ed-8369-0aaee731334f

And here's after. Note tabbing to the notebook causes the CPU to plunge and remain low:

https://github.com/nasa/openmct/assets/9853862/81b6714a-ea90-4608-ae23-40d93de07d96

**Comment by unlikelyzero** [comment]
@akhenry @scottbell let's sync on how we're going to test this

**Comment by unlikelyzero** [comment]
Complex "Real" Display Test
- TBD
- 

4 Tab display
- Create a Display Layout with the following Plot, LAD Table, Telemetry Table, Gauge, and Alphanumeric with 4 tabs referencing 2 telemetry endpoints.
- Click between tabs and determine if there's any slowness
- Click between tabs and determine how historical telemetry network requests with eager load and without eager load

**Comment by scottbell** [comment]
@akhenry note i split off the webgl stuff into [this branch](https://github.com/nasa/openmct/tree/7132-defer-rendering-for-inactive-tabs-in-open-mct-tabbed-view-webgl). Should we create another ticket too?

**Comment by scottbell** [comment]
To test:

1. Create a tabbed layout
2. Drop some high frequency data into one tab as stacked plots
3. Drop a large LAD table with high frequency data into another tab
4. Drop a notebook into another
5. Bring up the [performance monitor](https://developer.chrome.com/blog/new-in-devtools-64/) in Chrome.
6. Bring up the large LAD table and look at the performance monitor. Note the high CPU usage.
7. Bring up the plot and notice the high CPU usage.
8. Bring up the notebook, the CPU usage should decrease

**Comment by scottbell** [comment]
> @akhenry note i split off the webgl stuff into [this branch](https://github.com/nasa/openmct/tree/7132-defer-rendering-for-inactive-tabs-in-open-mct-tabbed-view-webgl). Should we create another ticket too?

@akhenry created a ticket here #7202

**Comment by khalidadil** [comment]
The data I was looking at didn't have a super high data rate, but I did notice a small CPU usage difference when I switched between tabs.

Verified Fixed in Testathon on 11/13/23
