### ISSUE TITLE
Telemetry Tables Configuration tab should be renamed to Config to match other tabs

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#7135]
**Describe the solution you'd like**
Change telemetry table configuration tab to `Config` to save inspector horizontal space and to match that of other configuration tabs. Plots and other objects with configuration have a tab called `Config`. The telemetry table is the only object which has a similar in function tab called `Configuration`. Some other objects also have this naming scheme which should be changed for consistency.

**Comment by khalidadil** [comment]
Verified in Testathon on 10/23/23. I'm seeing the "config" tab for Bar Graphs, Plots, and Telemetry Tables.

**Comment by rukmini-bose** [comment]
Testathon Verified Fixed 10/23/23
