### ISSUE TITLE
[Plots] Very large values cause entire plot to disappear

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#7137]
#### Summary

When there is a very large telemetry value (in this case -7.5e+177) within the time range, the VISTA plot is blank, even though there are data points in the range. This example is for a short time range, but if you expand the time boundaries (e.g. over a week or more), you will see that the whole plot is blank. This makes it seem like data is missing, but it’s a plotting bug.

Follow up for test: https://github.com/nasa/openmct/issues/7139

#### Expected vs Current Behavior

At the very least the rest of the plot should still be plotted.

#### Steps to Reproduce

1. View a plot with values that would break a Float32Array (we have an option for this in the sine wave generator)
2. Once a value that exceeds Float32Array capabilities (Above 3.4+38, Below -3.4+38) appears in the plot, the whole thing disappears 

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available? (viewing in log mode, which is basically useless at these ranges)
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by jvigliotta** [comment]
## Testing
- follow the reproduction steps
- with the fix, you should see gaps in the plot and if you hove over them, you should see the values that are missing

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 10/26/23

**Comment by ozyx** [comment]
Verified Testathon 11/13/23, plots don't disappear, only small gaps
