### ISSUE TITLE
Telemetry Table menu actions not available in Preview mode

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#7158]
#### Summary

Actions like "Export Marked Rows" on the TelemetryTable 3dot menu aren't available in Preview mode, but it feels like they should be?

@charlesh88 Is this a defect?

#### Expected vs Current Behavior

TelemetryTable specific menu actions (such as "Export Marked Rows") should be available in the 3dot menu when I'm:
1. ✅ Viewing a TelemetryTable object
  
![Screenshot 2023-10-20 at 1 36 25 PM](https://github.com/nasa/openmct/assets/9259993/4d1b5958-79a0-4f2b-957b-f21a63031c23)

2. ✅ Viewing a TelemetryTable object in "Large View" mode (clicking on "Large View" button from the object embedded in a layout)
  

https://github.com/nasa/openmct/assets/9259993/617ca081-8861-4ef8-aa8e-c13110a892b6

3. ❌ Viewing a TelemetryTable object in Preview mode (clicking on a TelemetryTable object or Telemetry w/ Table view in the tree while editing another object).

  https://github.com/nasa/openmct/assets/9259993/e3e24be9-deb0-41e7-aa1f-578abf736b38

#### Steps to Reproduce

1. Create a Sine Wave Generator
2. Create a Display Layout and leave it in edit mode
3. Click on the Sine Wave Generator in the tree to preview it
4. Click the 3dot menu and notice that actions like "Export Marked Rows" are not available

#### Environment

* Open MCT Version: 3.2.0-next
* Deployment Type: any
* OS: any
* Browser: any

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by charlesh88** [comment]
This is most definitely a bug. The Telemetry Table view should have the same capabilities regardless of how it was invoked.

#### Additional Notes About Reproduction


1. Create or go to a view that uses the telemetry table view, like a numeric data source.
2. In the main view, note the controls available and the contents of the More Options menu (3 dot menu) in the upper right.
3. Nav away from the object, then find it in the tree. Context-click it there and select "View" from the context menu.
4. Observe that available controls, and the contents of the More Options menu are different and very limited.

**Full, desired table capabilities from the main view:**
![Screen Shot 2023-10-23 at 2 29 25 PM](https://github.com/nasa/openmct/assets/1056412/bba1a3cb-197b-4ff6-a171-d63a58e322ba)

**Invoking "View" from the tree:**
![Screen Shot 2023-10-23 at 2 37 28 PM](https://github.com/nasa/openmct/assets/1056412/147982a5-06dd-40df-9bf7-8bc10a3c347d)

**The 2nd, limited table view in the Large View overlay:**
![Screen Shot 2023-10-23 at 2 29 39 PM](https://github.com/nasa/openmct/assets/1056412/714da65a-e537-4e69-8299-1e50d0ce64a6)

**The correct table view _is_ available from a Display Layout's "Large View":**
![Screen Shot 2023-10-23 at 2 32 12 PM](https://github.com/nasa/openmct/assets/1056412/6f189c75-5e68-4c37-b4c0-46bd3243df10)

**Comment by michaelrogers** [comment]
## How to test

_From Jesse's original steps:_
**Steps to Reproduce**

1. Create a Sine Wave Generator
2. Create a Display Layout and leave it in edit mode
3. Click on the Sine Wave Generator in the tree to preview it
4. Click the 3dot menu and notice that actions like "Export Marked Rows" are not available

**Comment by scottbell** [comment]
Note this issue appears more widespread. E.g., the Timer object has the same issues:

https://github.com/nasa/openmct/assets/9853862/c79c315a-db0d-4784-9b52-d76ecedfe3ef

Note the controls all function, but they're not updating their display appropriately to state changes. The original action bar (i.e., the one in the Display Layout) is receiving the state changes, but the action bar in the PreviewContainer is not.

**Comment by scottbell** [comment]
The issue is `getActionsCollection` isn't returning the cached `ActionsCollection`, and is instead creating a new one for the Preview. This new `ActionsCollection` doesn't receive the updates from the View object, and so doesn't respond appropriately to changes.

**Comment by scottbell** [comment]
To test:
1. Create a SWG
2. Create a Telemetry Table, and add the SWG
3. While viewing the Telemetry Table, click the More Options menu (3 dot menu) in the upper right.
4. Ensure you can see actions like "Export Marked Rows".
5. Create a DisplayLayout, and put it in edit mode
6. Click the Telemetry Table in the tree to a get a Preview
7. Click the More Options menu (3 dot menu) in the upper right of the Telemetry Table preview
8. Verify you can see "Export Marked Rows", be sure it's disabled
9. Verify you can see "Pause"
10. Close the Preview
11. Drag the Telemetry Table to the Display Layout and save
12. Click the More Options menu (3 dot menu) in the upper right of the Telemetry Table in the Display Layout
13. Ensure you can see actions like "Export Marked Rows"
14. Click the "View Large" action
15. Click the More Options menu (3 dot menu) in the upper right of the Telemetry Table in the preview
12. Verify you can see "Export Marked Rows", be sure it's disabled
13. Verify you can see "Pause"
14. Click the "Pause"
15. The table should now be paused, with the play button visible
16. Click the More Options menu (3 dot menu) in the upper right of the Telemetry Table in the preview
17. Verify you can see "Play"

Do the same for Timer object in a Display Layout. The Actions should be similarly reactive.
