### ISSUE TITLE
Inconsistent behavior with multiple annotations in imagery

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#7170]
#### Summary
Lots of unexpected whackiness when adding and removing multiple annotations
Some observed behaviors
* when you add multiple annotations, each subsequent annotation adds its own opacity filter so the selected annotation continues to get lighter and lighter
* when you have multiple annotations and delete 1 or more, the selected annotation appears to become unselected, even though it technically still is and you can continue to add or remove annotations from it (noticed for right most annotation but not neccessarily for other annotations)
* different combinations of adding/removing/clicking on annotation can make the tags temporarily dissapear except for latest addition, which come back after selecting the annotation again

#### Steps to Reproduce
Create and navigate to an example imagery
Hold Alt+shift and drag over imagery to create an annotation
When selecting an existing annotation, use the inspector to add tags

Multiple annotations changes selected annotation color
1. add an annotation
2. add a tag and observe the annotation becomes selected (turns purple if not already from yellow)
3. add more tags and observe the selected annotation becomes lighter on

Annotation appears deselected
1. add an annotation
2. add two tags
3. delete the right-most tag and observe the annotation appears to become deselected (turns yellow from purple)

Tags appear to disappear but are still there
1. add an annotation
2. add a tag
3. re-select the annotation
4. add another tag and observe original tag dissapears
5. re-select the annotation and observe all the annotations reappear
6. rinse and repeat with variations to see all kinds of fun behavior

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by scottbell** [comment]
@davetsay what version did you see this on? We fixed a bunch of image annotation stuff in the last month or so. I think the opacity stuff is still there, but unsure about the other stuff.

**Comment by scottbell** [comment]
This looks like a regression from previous behavior (aside from the opacity thing, which has always existed). I'll investigate more.

**Comment by ozyx** [comment]
@davetsay woops i missed that haha

**Comment by rukmini-bose** [comment]
Tested Locally and Verified 1/18/2024. Tried all sorts of different funky scenarios with annotations, and everything looks all good now!

**Comment by ozyx** [comment]
Verified -- Testathon 01/25/24
