### ISSUE TITLE
Selection of object in layout should only show marquee for that object

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#7179]
#### Summary
When selecting an object in a layout, multiple objects have the resize marquee displayed.
Also found grid is incorrectly not displaying on selection for nested objects

#### Expected vs Current Behavior
Expect only the selected object to have the marquee
Expect the parent layout to display a grid for the selected object

#### Testing Instructions (see attached pics)
1. Create a display layout A with layout object(s) inside (Click + in layout toolbar to add layout objects)
2. Create a display layout B with optionally layout objects(s) inside
3. Create a display layout C and then drag layout A and layout B into layout C
4. Edit display layout C
5. Observe layout C has a background grid displayed
6. Observe other layouts and layout objects do not have a grid displayed
7. Click layout A
8. Observe layout A has a marquee displayed, is surrounded by a resizing box with grab points in the corners
9. Observe layout B, and all layout objects, do not have a marquee displayed
10. Observe layout C and only layout C has a background grid displayed
11. Click a layout object in layout A
12. Observe the layout object and only the layout object has a marquee displayed
13. Observe layout A and only layout A has a background grid displayed

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information
Correct behavior with only the selection displaying a marquee
<img width="1031" alt="single marquee" src="https://github.com/nasa/openmct/assets/3614296/117c9a25-1fa7-44aa-a44c-e4a592ef4ad9">

Incorrect behavior with multiple items displaying a marquee
<img width="851" alt="multiple marquees" src="https://github.com/nasa/openmct/assets/3614296/cd0be1fb-67fb-42f3-9b25-4527efb03db7">

Correct grid behavior with parent layout selected
<img width="663" alt="parent display selected" src="https://github.com/nasa/openmct/assets/3614296/c6587fcf-ace2-4a92-bddd-06112e6b4b27">

Correct grid behavior with child layout selected
<img width="663" alt="child display selected" src="https://github.com/nasa/openmct/assets/3614296/3ff6e0aa-11cb-45c0-9a72-c0802516d327">

Correct grid behavior with layout object inside of child layout selected
<img width="664" alt="object in child display selected" src="https://github.com/nasa/openmct/assets/3614296/56feb4d9-4d6b-4e1f-bd19-d8a19b63047a">

**Comment by rukmini-bose** [comment]
Verified Testathon 11/16/2023
