### ISSUE TITLE
TelemetryTable filters are broken

### ISSUE THREAD

**Issue by scottbell** [nasa/openmct#7181]
#### Summary

When using a TelemetryTable, the column filters for both regular text search & regex aren't filtering properly:

https://github.com/nasa/openmct/assets/9853862/3f3e1a27-dcd6-4d3e-b4ea-87ff0988c8b7

Instead an exception is thrown:
```js
Uncaught TypeError: Cannot read properties of undefined (reading 'trim')
    at TableRowCollection.setColumnFilter (TableRowCollection.js:279:1)
    at Proxy.filterChanged (TableComponent.vue:680:30)
    at invokeFunc (lodash.js:10401:1)
    at trailingEdge (lodash.js:10450:1)
    at timerExpired (lodash.js:10438:1)
```

#### Expected vs Current Behavior

In 3.0.2, this works as expected:

https://github.com/nasa/openmct/assets/9853862/cdac288e-1488-4660-934b-70e48c854ea3

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by scottbell** [comment]
It looks to be a side effect from [removing our Vue2 compatibility layer](https://github.com/nasa/openmct/pull/7133/files#).

**Comment by ozyx** [comment]
Verified fixed Testathon 11/13/23 

The filtering works but filter input is kinda laggy and rubber-bands a lot. Will create a separate issue for this.


https://github.com/nasa/openmct/assets/9259993/cb03b2f6-0a28-424a-8985-299bcd384356

**Comment by khalidadil** [comment]
I'm seeing the same as @ozyx with respect to filtering working, but input values are disappearing while typing. @ozyx mentioned that he'll create a separate issue for the input issues.

Verified Fixed in Testathon on 11/13/23

**Comment by ozyx** [comment]
> This error is related to that issue:
<img alt="Screenshot 2023-11-13 at 5 01 06 PM" width="526" src="https://user-images.githubusercontent.com/2343076/282615141-d70d48d2-8e27-4cc0-9f4e-92b44d72c546.png">

[Related issue](https://github.com/nasa/openmct/issues/6083)
