### ISSUE TITLE
tabs should default to not load eagerly

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#7198]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by scottbell** [comment]
To test:

1. Create a tabs object. The resultant form should have the eager tabs toggle switched off: 
<img width="1684" alt="after-default-false" src="https://github.com/nasa/openmct/assets/9853862/462446f4-a53b-48eb-9f08-15681f46457d">

2. Change the `index.html` to install the plugin using the option to enable eager loading to default to true:
```js
openmct.install(openmct.plugins.Tabs({ eagerLoad: true }));
```

3. Create a tabs object. The resultant form should have the eager tabs toggle switched on: 
<img width="1684" alt="after-default-true" src="https://github.com/nasa/openmct/assets/9853862/5f1383c7-cad2-494f-afbc-b59bf14cd9c7">

4. Generally test tab eager loading by creating two SWGs to drop onto the tabs object. When eager loading is turned on, on page load, both tabs object should have their component HTML loaded: 
<img width="1684" alt="Eager-tabs-on" src="https://github.com/nasa/openmct/assets/9853862/1b73124d-d9cd-42b4-ae27-32f3d1306ba3">

When eager loading is turned off, only the selected tab on page load should have its component HTML loaded:
<img width="1684" alt="Eager-tabs-off" src="https://github.com/nasa/openmct/assets/9853862/658b8611-0121-443e-b6f3-8642eaf45d1f">

**Comment by ozyx** [comment]
Verified Testathon 2/5/24
