### ISSUE TITLE
Have WebGL contexts eagerly lose context when not visible

### ISSUE THREAD

**Issue by scottbell** [nasa/openmct#7202]
**Is your feature request related to a problem? Please describe.**
When a WebGL context isn't visible, we should try to lose it. When it becomes visible again, we should reclaim it.

**Describe the solution you'd like**
The WebGL context loss/gain is [a bit involved](https://www.khronos.org/webgl/wiki/HandlingContextLost), and also somewhat browser dependent. Some browsers use it for testing of a synthetic context lost for testing (e.g., [Webkit](https://opensource.apple.com/source/WebCore/WebCore-7602.1.50.0.6/html/canvas/WebGLRenderingContextBase.cpp.auto.html) and sometimes [Chrome](https://www.khronos.org/webgl/public-mailing-list/public_webgl/1611/msg00013.php)), and some use it to initiate context loss (e.g., [Firefox](https://www.khronos.org/webgl/public-mailing-list/public_webgl/1611/msg00023.php)).

Ideally, when the [Intersection Observer](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) detects we're no longer visible, we should tell WebGL to destroy our context. When the Intersection Observer tells us we're visible again, we should rebuild it. In #7149, we were able to use Intersection Observers to delay calls to the `requestAnimationFrame`, this is a furtherance of that work.

**Comment by scottbell** [comment]
Note, for this ticket we're going to destroy the canvas when we've detected we've lost visibility via the intersection observer, then rebuild when we're visible again.

**Comment by scottbell** [comment]
To test:

- Create a tabbed layout
- Drop a clock onto one tab
- Drop a plot on another tab
- Click on plot tab and ensure plot renders
- Inspect DOM and ensure there are two canvas elements
- Click on the clock tab
- Inspect DOM and ensure there are no canvas elements
- Click back and forth repeatedly an ensure there are no errors thrown

**Comment by akhenry** [comment]
Verified
