### ISSUE TITLE
[Fault Management] Cannot acknowledge or shelve faults with bulk actions

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#7215]
#### Summary
Users are currently unable to acknowledge or shelve faults in the fault management view with the bulk actions.

#### Expected vs Current Behavior
When selecting one or many faults in the fault management screen, the user should be able to shelve or acknowledge a fault. Today they do not 

#### Steps to Reproduce
1. Create an alarm or two
2. Navigate to the Fault Management View
3. Select the checkbox for all alarms
4. Note: the shelve and acknowledge buttons do not highlight

#### Environment
* Open MCT Version: 3.2.0
* Deployment Type: openmct-yamcs and viper

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [x] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by unlikelyzero** [comment]
Critical

**Comment by ozyx** [comment]
# Testing Instructions

## In our Test Environment:
- Navigate to Fault Management static object in the tree
- Create a fault
- Confirm it appears in the view

## Acknowledge a single fault
- Check a single fault
- Verify that the "Acknowledge" and "Shelve" buttons become enabled
- Click "Acknowledge" and leave a comment. Confirm the dialog.
- Verify the single Fault has a checkmark on it and is slightly grayed
- Click the dropdown in the top right to filter only to "Acknowledged" and verify the single fault appears.
- Set the filter back to default

## Acknowledge multiple faults
- Check multiple un-acked faults
- Click Acknowledge
- Repeat the steps above and verify that both are acknowledged

## Acknowledge a single fault with the context menu
- Check multiple faults
- Click on the context menu of one unacked fault and select "Acknowledge"
- Verify that the dialog states it is acknowledging only the fault for which the context menu was selected
- Confirm the dialog
- Verify that the single fault was acknowledged and all previously checked faults are unchecked

## Shelving faults
- Repeat the steps above but for Shelving faults, verifying that faults disappear from the view once shelved.
- Change the filter to "Shelved" and verify they appear again in the view.

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon 3/14/24
No issues observed all working as expected.
