### ISSUE TITLE
Independent time conductor shows local clock time when remote clock selected

### ISSUE THREAD

**Issue by michaelrogers** [nasa/openmct#7223]
I found a scenario in which the independent time conductor for a plot can show the local clock time in the conductor itself, even though the plot is ticking on the correct time.
 
Relates to VIPER-398

#### Steps to Reproduce
1. Navigate to an overlay plot 
2. Observe that the independent time conductor is configured to use remote-clock, while the global time conductor is following local clock.
3. Observe that the independent time conductor shows wall-clock, even though the plot shows real-time data in remote-time.

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by michaelrogers** [comment]
How to Test

1. Navigate to an overlay plot
2. Observe the mode of the global and independent time conductor
3. Set them so they are different (i.e. global local clock and ITC remote clock)
4. Observe that the time conductors display an appropriate time value and the ITC matches the plot mode

**Comment by khalidadil** [comment]
@michaelrogers Does this work with sine wave generators?
