### ISSUE TITLE
[e2e test] in notebook.e2e.spec.js

### ISSUE THREAD

**Issue by saram7619** [nasa/openmct#7226]
#### Summary

Using playwright, I completed the 

`test.fixme('Can create a Notebook Object') //Create domain object and Newly created notebook should have one section and one page`

**Comment by ozyx** [comment]
Awesome! Please go ahead and open a pull request once you're ready for it to be reviewed.

**Comment by saram7619** [comment]
Do I need to do a draft pr or just a pr?

**Comment by ozyx** [comment]
> Do I need to do a draft pr or just a pr?

Just a regular PR
