### ISSUE TITLE
[Transactions] General issue with transactions in OpenMCT

### ISSUE THREAD

**Issue by khalidadil** [nasa/openmct#7233]
#### Summary
Shefali and I noticed issues with OpenMCT and transactions. This manifests while trying to add items to any object and then trying to cancel saving. I'm also seeing this while styling items in a layout and then trying to discard changes and exit editing.

#### Impact Check List
- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by unlikelyzero** [comment]
@khalidadil can you reframe this in terms of user impact

**Comment by khalidadil** [comment]
From memory, I think canceling editing while modifying the styles of an object persists the styles anyway. This issue could show up in lots of other ways throughout the app (which should be investigated).

**Comment by khalidadil** [comment]
@unlikelyzero This still seems to be an issue. If you style a flexible layout and then cancel editing, the styling will persist until the page is reloaded. If a child is styled, the child styling will correctly revert after canceling editing.

**Comment by scottbell** [comment]
We able to reproduce:

https://github.com/nasa/openmct/assets/9853862/1198650c-6db2-41f2-8f38-3a99cb85fbee

Note navigating away and back also fixes it.

**Comment by scottbell** [comment]
To test:
1. Create a Flexible Layout & drop a few SWGs on it.
2. Click edit on the Flexible Layout, and change its border to green. Do not click Save
3. Cancel the edit
4. Observe the Flexible Layout incorrectly still has a green border.

See the above video for the issue in action.

**Comment by ozyx** [comment]
Verified Testathon 2/27/2024
