### ISSUE TITLE
[Flex Layout] Remove Frame button doesn't work anymore

### ISSUE THREAD

**Issue by rukmini-bose** [nasa/openmct#7234]
#### Summary

The "Remove Frame" button in Flexible Layouts does not work anymore. This can get slightly problematic if a user adds a frame to a layout, then decides they don't want it anymore. There's no way to remove the frame at this point. There's a workaround to removing an object in the layout (using the Elements Pool). 

#### Expected vs Current Behavior

When a user clicks on a frame or object in a Flexible Container and clicks the "Remove Frame" button, the selected object/frame should be removed. This however, does not happen. 
#### Steps to Reproduce

1. Create/Navigate to a Flexible Layout
2. Add an object to the layout. 
3. Try to remove the object from the layout using the "Remove Frame" button in the toolbar. Observe that after pressing "ok" on the confirmation dialog, the object does not get removed.
4. Press the "Add Container" button. Repeat step 3 and observe the same thing happening.

#### Environment

* Open MCT Version:   3.2.0-next
* Deployment Type:  Testathon
* OS:
* Browser: Chrome

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by davetsay** [comment]
Re-opening because remove frame still does not work. Remove container was fixed.

**Comment by khalidadil** [comment]
Verified in Testathon on 12/04/23. I'm seeing the same thing as Charles, with the "remove frame" button showing even if there's a single frame in the container.
