### ISSUE TITLE
Laggy input and rubber-banding in Telemetry Table filter inputs

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#7239]
#### Summary

Filter input is kinda laggy and rubber-bands a lot.

#### Expected vs Current Behavior

Filter changes should be responsive immediately (<200ms), input should not rubber-band

#### Steps to Reproduce

1. Make a Telemetry Table
2. Add a SWG
3. Switch to Realtime mode
4. Type in the filters inputs and notice the lagginess and rubber-banding

#### Environment

* Open MCT Version:  3.3.0-next
* Deployment Type:  any
* OS: any
* Browser: any

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information

https://github.com/nasa/openmct/assets/9259993/cb03b2f6-0a28-424a-8985-299bcd384356

_Originally posted by @ozyx in https://github.com/nasa/openmct/issues/7181#issuecomment-1809256231_

**Comment by rukmini-bose** [comment]
Verified Testathon 12/4/2023. Don't see any more rubberbanding in the input, or any lag when filtering

**Comment by michaelrogers** [comment]
Fix verified on 12/4/2023. Filter changes were very responsive and not laggy.

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 12/04/2023. Still seeing this bug: https://github.com/nasa/openmct/issues/6083, but it wasn't addressed under this PR.
