### ISSUE TITLE
Table view is default view for a plot

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#726]
The table is now the default view for plot objects.  Need some way of assigning view priority for a given object.  If we simply change the order of view registration the problem would be switched-- tables would then display as plots.

View as object is a bit confusing here.  @VWoeltjen have any ideas for a simple short term solution?

**Comment by VWoeltjen** [comment]
`viewService` could be decorated to sort the returned list of views for Table objects (and pass-through for other objects.) Simple and unlikely to cause problems elsewhere.

**Comment by larkin** [comment]
Hrm, I think this becomes more problematic the more views we have.  

Right now it's just plots and tables, but other options will exit-- realtime tables, historical tables, combined plots, overlay plots, stacked plots.  Not to mention unknown other view types we haven't implemented yet-- rollup indicators, etc.

Maybe a change to view registration to allow a one to one mapping of object types to "primary view" with all other views still being options for the user?

**Comment by VWoeltjen** [comment]
Slightly-more-complicated, maybe-more-future-proof solution would be to have a `defaultView` property of domain objects. (We actually had such a property implied by earlier designs for the Create menu, but it was never fully implemented.)

When browsing to an object, this property (if present) could be used to initialize view selection. Plot/Table/etc could have this property in their initial model. If this property is unassigned, obey priority order.

More generally, if we attach such a property per-object (as opposed to per-type or per-view) then our data model is compatible with a broader design space.

(Tangential: I've been thinking of the "view as object" concept and keep coming back to the nouns-versus-verbs question. A Plot or a Table is noun-like when your task is display-building; "View as Plot" and "View as Table" are verb-like when you are browsing. As such, maybe we want "view as object" to be confined to Layout editing; "Add > Plot" and "Add > Table" could be shorthands available when editing a Layout for "Create a Telemetry Group with `defaultView=plot`".)

**Comment by akhenry** [comment]
@VWoeltjen I like this suggestion. It also opens up the possibility of user-definable default views.

**Comment by charlesh88** [comment]
@larkin Is this fixed with #1557?

**Comment by larkin** [comment]
Fixed with #1557.
