### ISSUE TITLE
Speed up search with CouchDB

### ISSUE THREAD

**Issue by scottbell** [nasa/openmct#7264]
**Is your feature request related to a problem? Please describe.**
Search is taking a long time to return with CouchDB.

**Describe the solution you'd like**
A quicker search, possibly making the search algorithm more asynchronous.

**Comment by ozyx** [comment]
@scottbell 

Testathon 12/04/2023

Seeing some weird behavior in our testing environment.

When I search outright for something with multiple hits, I see the same behavior as before (everything comes in at once). Then I hit backspace and remove the last letter, and I see the behavior described in the PR (matching results without paths remain, the search progress bar appears, and then the rest load). Is that correct?

**Comment by shefalijoshi** [comment]
Seems to be working. Sometimes the paths come in right away and update quickly, other times the search in progress bar appears and the search results update eventually.

**Comment by charlesh88** [comment]
Testathon 2023-12-04: Verified MUCH BETTER. Searches for strings like 'enabledFlag', 'switchStatuses' and 'disabledFlag' (all of which have dozens if not hundreds of dictionary entries) came back quite quickly. Matching domain objects are added afterwards. Very nice!

**Comment by unlikelyzero** [comment]
@scottbell to meet with @michaelrogers and @khalidadil  to determine if this feedback from @ozyx is ok

**Comment by ozyx** [comment]
> @scottbell to meet with @michaelrogers and @khalidadil  to determine if this feedback from @ozyx is ok

This is verified. I was seeing expected behavior, problem was that I wasn't searching for a query that matched both an object name and an annotation tag. So I was misunderstanding what the expected behavior should be.
