### ISSUE TITLE
Plots sometimes do not render on load

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#7277]
#### Summary
Ocassionally plots will not load when embedded in a tabbed display. This appears to be a race condition related to the intersection observer that dynamically allocates and deallocates webgl contexts to plots.

#### Steps to Reproduce
1. Load openmct-yamcs quickstart
2. Start the Yamcs Quickstart server and Python Simulator
3. Import [the attached display](https://github.com/nasa/openmct/files/13562597/Unnamed.Tabs.View.json)
4. Navigate to the imported display
5. In Chrome dev tools, add a breakpoint to [this line of code](https://github.com/nasa/openmct/blob/2d9c0414f72c583e2894d81cc80ab1bad09e06c6/src/plugins/plot/chart/MctChart.vue#L284).
6. Refresh the display
7. Hit continue every time the break point is triggered
8. Observe that the plots are empty

https://github.com/nasa/openmct/assets/4215777/0a418bae-22eb-46c0-8009-a00c0727d573

#### Environment
* Open MCT Version: 3.3.0
* Deployment Type: openmct-yamcs / yamcs quickstart

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by scottbell** [comment]
Was able to replicate:

Uploading Screen Recording 2023-12-05 at 5.34.36 PM.mov…

will get to work fixing it.

**Comment by davetsay** [comment]
verified using a complex display with plots in a tab view

**Comment by akhenry** [comment]
Verified fixed following the testing instructions with Yamcs quickstart.
