### ISSUE TITLE
User is sometimes unable to switch operator roles

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#7280]
#### Summary
If operator has role selection cached in Local Storage that is no longer in the list of user's assigned roles Open MCT will default to the cached role and prevent them from selecting a different role.

#### Expected vs Current Behavior
If the cached role is not one of the user's assigned roles Open MCT should behave as though there is no cached role at all.

Workaround is to clear cached role from local storage

#### Environment
* Open MCT Version: 3.3.0
* Deployment Type: VIPER MMOC

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by scottbell** [comment]
@akhenry Hmm, having some trouble reproducing this:

https://github.com/nasa/openmct/assets/9853862/bbe96807-78d6-40bc-a2cb-570c58a503ab

I'll keep investigating

**Comment by unlikelyzero** [comment]
@akhenry to update the reproduction steps for scott

**Comment by akhenry** [comment]
@scott In this scenario it should not log the user in as Msolo Ops, since they don't have that role, it should either:

a) Trigger the role selection dialog automatically if the user has multiple roles to select from
OR
b) Auto-select the role if they only have one role assigned.

It's already doing this logic if the user has no role persisted, so a simple solution is to check if the persisted role is one of their currently assigned roles, and if not delete the persisted role and then execute the "user has no persisted role" logic.

**Comment by scottbell** [comment]
To test:

1. Log in as a user that has multiple roles in YAMCS
2. Note active role
3. Delete active role from YAMCS' admin page
4. Refresh page and note that user is still logged in with deleted role

See video in https://github.com/nasa/openmct/issues/7280#issuecomment-1854390624 on how to reproduce.

**Comment by akhenry** [comment]
Verified fixed! Nice work.
