### ISSUE TITLE
Data inspector visualization missing `renderWhenVisible`

### ISSUE THREAD

**Issue by scottbell** [nasa/openmct#7283]
#### Summary
When clicking on an object that is supported by the data inspector visualization, a stack trace is thrown stating `renderWhenVisible` is undefined.

#### Expected vs Current Behavior
No errors should be thrown and the data should be visualized.

#### Steps to Reproduce
* Install two plugins:
  * openmct.install(openmct.plugins.example.ExampleDataVisualizationSourcePlugin());
  * openmct.plugins.InspectorDataVisualization({ type: 'exampleDataVisualizationSource' })
* Create a Sine Wave Generator and drop it on on the previously created object
* Create an "Example Data Visualization Source"
* Open the "Data Visualization" inspector tab on the right
* Click on the Sine Wave Generator in the "Example Data Visualization Source" table
* Ensure the Sine Wave Generator plot is visible and working on the right

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment]
needs #7282 to be merged before we can manually test this

**Comment by davetsay** [comment]
This works but I see an error when trying to open the telemetry in a new tab
<img width="639" alt="image" src="https://github.com/nasa/openmct/assets/3614296/b6e25f4b-2985-4118-a921-4b2613a5946b">

**Comment by davetsay** [comment]
@scottbell , FYI i modified your install instructions on the second plugin to be 
`openmct.install(openmct.plugins.InspectorDataVisualization({ type: 'exampleDataVisualizationSource' })));`
rather than 
`openmct.plugins.InspectorDataVisualization({ type: 'exampleDataVisualizationSource' }));`

**Comment by akhenry** [comment]
Verified fixed.

@davetsay Feels like a new bug?

**Comment by davetsay** [comment]
Agreed. Verified and Filed #7382
