### ISSUE TITLE
API documentation indicates that renderWhenVisible is required, it should be optional

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#7284]
#### Summary
Our API documentation [indicates that the `renderWhenVisible` function is required](https://github.com/nasa/openmct/pull/7262/files#diff-b161966f7254af9c9c5382e859495c69622843e4602a6bb4208e08134e660121R1318). This capability should be opt-in in the interests of backwards-compatibility.

#### Expected vs Current Behavior
`renderWhenVisible` should be opt-in. Hoping that it already is and that just the documentation needs updating.

**Comment by scottbell** [comment]
You're correct, the function is optional to use, but will always be available. I'll reword.
