### ISSUE TITLE
Build Open MCT with Terser plugin to reduce library size.

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#7286]
**Is your feature request related to a problem? Please describe.**
Experimentation has shown that the Terser plugin may significantly reduce the size of our built library.

We should also consider using Terser in some of our other projects (viper-openmct, openmct-yamcs, openmct-mmgis).

**Comment by ozyx** [comment]
So as it turns out, Webpack is [already using TerserPlugin](https://webpack.js.org/guides/production/#minification) and applying sensible defaults (that net us the lowest bundle size without doing crazy things).

**Comment by ozyx** [comment]
# Testing Instructions

- Clone a fresh copy of openmct
- git checkout master
- npm i; npm pack
- Move the generated *.tgz archive to another folder (outside of openmct repo)
- Repeat the same but on this branch
- compare packed / unpacked space
- Manual smoke test of basic usage

**Comment by davetsay** [comment]
verified. packed goes from `9747535` to `9260085`.
