### ISSUE TITLE
Tabular front-end styling

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#729]
As needed. Relates to #670.

**Comment by charlesh88** [comment]
@akhenry Andrew, given that code freeze is end of this week, I'd like to get this under the limbo bar. Items I see are:

* New glyphs for RT Table and Historical Table.
* CSS / markup on the Inspector config section.
* Any needed CSS tweaks to the table layout itself
* Make column sort indicator more visible, particularly in the Snow theme
* Sticky headers?

Are you at a good point where I can start wading in? If so, what branch can I fork?

**Comment by akhenry** [comment]
Sounds like a plan.

There is a branch, open670, which has historical tables, but I'll try and get realtime into a state where I can push a branch today that has both historical and realtime for you to play with.

**Comment by larkin** [comment]
Historical tables should be merged into master at this point; not in 670.  Can you apply styles there?

**Comment by akhenry** [comment]
@charlesh88 At the risk of confusing things here, there is now a branch, open707, that contains both realtime and historical tables. There are some problems in realtime at the moment that I am working through, but it's functional at least. You can use realtime tables with the sine wave and event generators. Historical you can use by enabling the REMS integration module (examples/msl). I would strongly advise against using the sine wave generator with historical tables. It will work, but it will produce massive amounts of data, and take a few seconds to process it.

**Comment by charlesh88** [comment]
@akhenry I should be able to do the styling I need to do against master, I'll start with that.

**Comment by akhenry** [comment]
@charlesh88 So, open707 is approaching stability, and is basically feature complete. tbh I wouldn't mind a second pair of eyes on it to make sure it's consistent with requirements as you understand them.

The major outstanding issue at the moment is that tables for event messages lack column names (they're all 'Column 1', 'Column 2', etc.) but that shouldn't impede styling changes.

**Comment by akhenry** [comment]
@charlesh88 You'll also notice a weird row appearing occasionally with a bunch of W's in it :) That's also a known issue. Any other issues though, do let me know.

**Comment by charlesh88** [comment]
PR filed with #735
