### ISSUE TITLE
[WebGL] 2D fallback logic fails due to null ref

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#7294]
#### Summary

When creating too many WebGL contexts, we have logic to fall back to 2D rendering. However it currently fails due to a null reference exception.

#### Expected vs Current Behavior

The canvas drawing should successfully fall back to a 2D context

#### Steps to Reproduce

1. Create a display layout with at least 6 plots
2. Navigate to it
3. Duplicate the browser tab 5 - 8 times and navigate between them
4. Observe the "Aw Snap" error on plots

#### Environment

* Open MCT Version:  release/3.2.0
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by rukmini-bose** [comment]
Verified Testathon 3/20/2024. Seeing no issues!

**Comment by charlesh88** [comment]
Testathon 2024-03-20 verified fixed.
