### ISSUE TITLE
`package.json` should define the `main` entry point for CJS

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#7297]
Currently, if consumers want to import and use `openmct`, they must specify the specific path to `openmct.js` i.e:

```js
const openmct = require('./node_modules/openmct/dist/openmct.js');
```

OR specify a webpack alias for `openmct`.

Either way is not ideal! We can simply include an entry for `main` in our `package.json` which informs the entry point of the framework. This enables consumers to:

```js
const openmct = require('openmct');
```

out of the box which is what consumers would expect, I'd think.

**Comment by ozyx** [comment]
# Testing Instructions

1. Create a new node project: `npm init`
2. Ensure there is a `start` script in `package.json`: `"start": "node index.js"`
3. Install openmct `npm i --save-dev nasa/openmct`
4. In index.js, add this code:

```js
const openmct = require('openmct');
console.log(openmct);
```

Run `npm start` and ensure that the console prints out the Open MCT API object.

**Comment by jvigliotta** [comment]
I'm getting this error:
![Screenshot 2024-03-05 at 3 42 02 PM](https://github.com/nasa/openmct/assets/12013460/777956cb-958c-43a2-834f-290946685e1a)

**Comment by ozyx** [comment]
Will rewrite instructions as these don't make sense

**Comment by davetsay** [comment]
not ready for test in today's testathon

**Comment by unlikelyzero** [comment]
@ozyx to file a new issue

**Comment by ozyx** [comment]
see: https://github.com/nasa/openmct/issues/7602
