### ISSUE TITLE
[Telemetry] TelemetrySubscription does not handle composition changes correctly

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#730]
From https://github.com/nasa/openmctweb/blob/master/platform/telemetry/src/TelemetrySubscription.js#L199

``` javascript
function idsMatch(ids) {
    return ids.length === self.telemetryObjects.length &&
        ids.every(function (id, index) {
            return self.telemetryObjects[index].getId() === id;
        });
}

function modelChange(model) {
    if (!idsMatch((model || {}).composition || [])) {
        // Reinitialize if composition has changed
        self.unsubscribeAll().then(initialize);
    }
}
```

The logic here seems incorrect. For one, it doesn't seem to account for the case where the parent object itself is a telemetry object, as it only considers the object's composition. It seems to assume that the object in question is a container for other telemetry objects. 

In `idsMatch`, it assumes that all composed objects will be telemetry objects. This assumption may actually be a safe one to make, I'm not sure, but if it's ever incorrect it will cause cause this function to return false every time, causing new subscriptions on every model mutation.

Finally, it assumes that the composition and telemetryObjects arrays are ordered in exactly the same way. Again, this might be a safe enough assumption for now, but it's not very future proof. In the past when I have had to make a similar comparison I have used sorted arrays of object ids.

I've actually wondered before whether we should have a composition change event. I think that it's a sufficiently common case, and it involves writing a bunch of error prone boilerplate like this each time. Could be a listener on the composition capability, rather than being a mutation event.

I'm going to suggest deferring any changes here until after the telemetry API has been reconsidered.

**Comment by larkin** [comment]
TelemetrySubscription will be depreciated.
