### ISSUE TITLE
URL not updating when navigating to object from Grand Search

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#7303]
#### Summary
The object navigated to from search is viewed, but the url doesn't change. This means the view of the navigated from object is retained for the navigated to object. Also, the url cannot be shared to other users.

NOTE: this seems to only be an issue with dictionary objects but needs verification

#### Expected vs Current Behavior
The url should be updated

#### Steps to Reproduce
1. Navigate to an object (dictionary, not created, object)
2. search for another object (dictionary, not created, object)
3. navigate to the searched object
4. Observe url doesn't change from navigated from object to the navigated to object
5. For extra credit try to navigate to an object that does not have the view type of the first object, and observe the view is still of the first object even though the second object does not have that view

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by scottbell** [comment]
Been investigating this a bit, and the issue crops when the objects are supported by the same view object. Namely, if you click on something that defaults to a plot, it won't change the URL. If you click on two user created objects sequentially of the same type (e.g., a telemetry table), it won't change the URL.

**Comment by unlikelyzero** [comment]
I'm classifying this as trivial until someone can convince me otherwise

**Comment by scottbell** [comment]
Here's the issue in action:

https://github.com/nasa/openmct/assets/9853862/5ff804ec-f72c-42ae-abc5-be903ae1cdcb

The reason dictionary items are often having the problem, is they're typically viewed with the same view key, namely the plot. You can see the same behavior in user generated items if they're viewed with the same View type.

**Comment by davetsay** [comment]
> I'm classifying this as trivial until someone can convince me otherwise

It's trivial for numeric telemetry that is all plottable. It's not trivial when telemtry is split 50/50 between numerical (plot) and event message (table). It is also not trivial when sharing urls is a regular process for situational awareness.

**Comment by ozyx** [comment]
Verified fixed -- Testathon 2/27/2024

Navigating between dictionary objects via search now changes the URL correctly. It also applies the view type correctly if switching between them

**Comment by charlesh88** [comment]
Testathon 2024-02-27 verified fixed.
