### ISSUE TITLE
[e2e] Update eslint guidelines to disallow page.locator in favor of web-first locators like page.getByRole

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#7307]
#### Summary
This will be a fairly large undertaking, but the playwright eslint plugin can help us find all examples of page.locator and replace with  page.getByRole()

- [x] Upgrade to eslint-playwright >1.6.0
- [x] Set playwright eslint rule for `no-nth-methods` and `no-raw-locators` to required
- [x] Skip for the performance/contract tests

**Comment by unlikelyzero** [comment]
Notable violations:
- Create Menu injects icon `getByRole('menuitem', { name: ' Display Layout' })`

**Comment by akhenry** [comment]
Needs test instructions

**Comment by shefalijoshi** [comment]
When I zoom into an image and pan down to view the compass, I don't see it.
