### ISSUE TITLE
[e2e] Update playwright configuration to support already exposed webserver in the ci config

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#7311]
#### Summary
Launching the web service automatically in the playwright config is great but is slow for most debugging. Let's update the config

**Comment by unlikelyzero** [comment]
This was merged

**Comment by unlikelyzero** [comment]
### Testing Notes

- Open two terminals: one for the local dev server and one for playwright
- Start openmct in terminal one with `npm run start`
- Start tests in terminal two with `npm run test:e2e:stable` and make sure they start. Don't wait for all tests to finish

**Comment by ozyx** [comment]
Verified -- Testathon 2/5/2024
