### ISSUE TITLE
Autoscale creates weird plots if the min and max are very close

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#7321]
#### Summary

Certain aggregate members which always emit a constant value are losing precision right before they are plotted, which leads to weird plots.

![Screenshot 2023-12-20 at 1 48 11 PM](https://github.com/nasa/openmct/assets/9259993/890995aa-aef9-4495-95c3-c3e0e2d8e1cc)

![Screenshot 2023-12-20 at 1 47 59 PM](https://github.com/nasa/openmct/assets/9259993/a9bf8db3-a21b-40a4-bd60-f5963b807c57)

Notice that the same telemetry point on yamcs graph does NOT display incorrectly, so this is something Open MCT is doing.

![Screenshot 2023-12-20 at 5 04 28 PM](https://github.com/nasa/openmct/assets/9259993/2924346e-7985-4bdc-837d-f220d823808b)

#### Expected vs Current Behavior

The value coming in should be the value plotted. I.e:
If we receive the value 3.1456, we should plot that value at the same precision it was received.

#### Steps to Reproduce

1. 
2.
3.
4.

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by unlikelyzero** [comment]
Setting as blocker given the context in which this was found

**Comment by scottbell** [comment]
FWIW, if I override the websocket callback and add:
```js
if (this.isTelemetryMessage(message)) {
                    let values = message.data.values || [];
                    let parentName = subscriptionDetails.domainObject.name;

                    values.forEach(parameter => {
                        let datum = {
                            id: qualifiedNameToId(subscriptionDetails.name),
                            timestamp: parameter[METADATA_TIME_KEY]
                        };
                        let value = getValue(parameter, parentName);
                        if (parameter?.engValue?.type === 'FLOAT') {
                            value = 3.31456;
                        }
...
```

it seems to display properly:

https://github.com/nasa/openmct/assets/9853862/45444909-b074-4222-9c71-576c03cde409

**Comment by ozyx** [comment]
Yeah, I went on a whole wild goose chase yesterday afternoon. I think the issue is that telemetry from yamcs sent over websocket/json has lower precision than historical data fetched from the API

**Comment by ozyx** [comment]
I'm leaning towards this being a yamcs bug now? @unlikelyzero lets sync today when you have a minute

**Comment by ozyx** [comment]
According to Mark R, these two values are identical and thus it's up to the client to display them in a non-confusing way. I'm inclined to agree, which would make this an Open MCT / plotting / autoscale issue

**Comment by akhenry** [comment]
> According to Mark R, these two values are identical and thus it's up to the client to display them in a non-confusing way. 

@ozyx  @merose 3.1456 _might_ be 3.31455984 rounded, but it might also be 3.31455983. They're not necessarily the same number, and I can guarantee that treating all values within a certain precision as the same number will break functionality for other users. So I'm not convinced that changing how auto-scaling works is the right way to fix inconsistent precision from Yamcs.

I think if Yamcs is inconsistent with its precision when reporting real-time vs historical values, and they don't want to change that behavior, then we should just force all telemetry values to the lowest level of precision in the adapter, so in this case we round to 3.31456. We will have to confirm what strategy Yamcs uses for rounding to make sure we're consistent.

**Comment by ozyx** [comment]
@akhenry its worth mentioning that using protobufs doesn't have this issue, it's just the yamcs json that sends telemetry with different precision

**Comment by unlikelyzero** [comment]
1. Move this to openmct-yamcs
2. Make a GDS Ticket to be tracked

**Comment by unlikelyzero** [comment]
Closing to be tracked in https://github.com/akhenry/openmct-yamcs/issues/406
