### ISSUE TITLE
[e2e] Improve and document e2e watch mode

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#7323]
#### Summary
Playwright introduced a watch mode and we do not explicitly call it out in our documentation as the preferred way of updating or triaging tests.

- [ ] Update playwright watch config so that the dev server can hotreload
- [ ] Update documentation to match the new config and usecases for working with playwright

**Comment by unlikelyzero** [comment]
### Testing Notes
- start the tests with `npm run test:e2e:watch`

**Comment by akhenry** [comment]
Verified fixed:
1. Reviewed the documentation, looks good.
2. Ran `npm run test:e2e:watch`
3. Enabled watch mode in the Playwright UI
4. Modified a test spec file.
5. Verified that the modified test ran automatically upon save.
