### ISSUE TITLE
Time Conductor Snow theme may need some love

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#7327]
Time conductor in Snow theme looks very close to time conductor in Espresso.

<img width="1113" alt="image" src="https://github.com/nasa/openmct/assets/3614296/f1c4d502-d986-451e-b3db-5410f1c6ce96">

<img width="1097" alt="image" src="https://github.com/nasa/openmct/assets/3614296/2fcbe4ae-256c-4397-a9e0-48a948bda5b8">

**Comment by charlesh88** [comment]
In general, this is looking as intended. That said, there are a few elements (like the TC icon) that are too low contrast and should be addressed. I'll have a look today.

**Comment by charlesh88** [comment]
This was fixed.
