### ISSUE TITLE
[Styling] Persisted styles don't get applied to Stacked Plot Items

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#7338]
#### Summary

See title. If you apply and save styles on a StackedPlotItem (such as a Plot), then reload (or navigate away and back), the styles don't get applied.

#### Expected vs Current Behavior

The persisted styles should apply to the stacked plot items.

#### Steps to Reproduce

1. Create a Stacked Plot
2. Create a Sine Wave Generator
3. Drag the Sine Wave Generator into the Stacked Plot
4. Click on the Sine Wave Generator Stacked Plot Item to select it
5. In Edit mode, click on the "Styles" tab in the right-hand inspector.
6. Style the item with a custom color, border, font style and font size
7. Save and Finish Editing
8. Reload the page
9. No styles :(

#### Environment

* Open MCT Version:  https://github.com/nasa/openmct/commit/70de7363d8193528141481411a93939cf47b3760
* Deployment Type:  local
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information

Uploading Screen Recording 2024-01-03 at 5.07.34 PM.mov…

**Comment by ozyx** [comment]
# Testing Instructions

- Follow steps to reproduce and verify that persisted styles apply correctly on mount

**Comment by rukmini-bose** [comment]
Verified Testathon 1/17/2024.
