### ISSUE TITLE
New action to reload an individual view and all of its children

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#7343]
**Is your feature request related to a problem? Please describe.**
There are situations where it is useful to be able to reload the telemetry in an individual view either because it's embedded within a complex layout, or simply to avoid incurring the cost of a browser refresh. An example of this case is when telemetry throttling results in telemetry being dropped. It may be possible to recover the dropped telemetry by re-requesting historical data.

**Describe the solution you'd like**
A new action in a view's menu that triggers an individual view to be reloaded. 

Ideally we would more selectively reload just the telemetry such that we do not lose any ephemeral configuration that the user has defined. This is significantly more work though, and requires new API, modifications to all existing screens, and imposes a new requirement on developers to support it.

**Comment by scottbell** [comment]
To test:
1. Create two Sinewave generators
2. Create a Display Layout
3. Drop both Sinewave generators onto the layout
4. Click the Action toolbar (hamburger menu) and select "Reload" on the Display Layout
5. Ensure both Sinewave generators reload
6. Do the same for the individual sinewave generators
7. Test a smattering of other object views too (e.g., Gauges)

**Comment by khalidadil** [comment]
Verified in Testathon on 01/25/23 (testing using SWG alphanumerics, a notebook, a telemetry table, and a gauge)

**Comment by rukmini-bose** [comment]
Verified Testathon 1/25/24
