### ISSUE TITLE
[Mobile Support] Global Search is missing and needs redesign for mobile

### ISSUE THREAD

**Issue by rukmini-bose** [nasa/openmct#7349]
#### Summary

The Global Search capability is missing from Open MCT on mobile. This is because of a larger issue where we made a decision in the past to remove the status area from mobile, which is where Global Search is located. 

However, upon further discussion, we have plans to bring _a modified version_ of the Status Area back into mobile. (This larger issue is tracked at https://github.com/nasa/openmct/issues/7348). 

Along with bringing Global Search into mobile, we need redesign the way global search will look on mobile. Areas of redesign include where the search is located, and how the displayed search results will look. (Design mockups to come). 

#### Steps to Reproduce

1. TBA

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by rukmini-bose** [comment]
Testing Instructions: 
1. Set up a mobile environment (you can use the Chrome emulator) and choose a mobile device like an iPhone or Android. Make sure to refresh after selecting a device. 

**PORTRAIT MODE (DO THESE IN ORDER):**
1. Verify that in Portrait mode, the search feature, located in the status area, constitutes of only the search icon. 
2. Click on the search icon and verify that a search bar expands and that you are prompted to type. 

3. Start typing in the search bar and verify that the results take up the entire width and height of the device. Also verify that if there are overflow results, that a scroll bar appears. 
4. Verify that clicking on a search result closes the overlay and takes you to the selected result. Note that if the Tree was open before you started your search, that the you have to manually close the tree by clicking the hamburger menu to view the object. This is an issue that will fix in the future. 
5. Verify that the search results popup has a close button on the top right, and that clicking it closes the overlay. 
6. You should now be in a state where the search bar still has your previous keywords in it, but you are not being prompted to type. Verify that the "clear search" button is visible, regardless of whether or not you have clicked on the search bar. Click the button and verify that your search keywords have been cleared. 

**LANDSCAPE MODE (DO THESE IN ORDER):** 
1. Verify that in Landscape mode, the search feature constitutes of the search icon AND the search bar. 
2. Repeat steps 3-6 from above.

**Comment by charlesh88** [comment]
Testathon 2024-03-20 verified fixed.
