### ISSUE TITLE
Support more than one Couch database for a single Couch Server

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#7359]
**Is your feature request related to a problem? Please describe.**
Open MCT should be able to support more than one couch database on the same server.

**Describe the solution you'd like**
A developer should be able to install the couch plugin and optionally pass in multiple database names (eg. `openmct-sandbox`, `openmct-cm`) and have Open MCT populate the tree with a separate root object and namespace for each database.

The Couch plugin already supports [multiple namespaces](https://github.com/nasa/openmct/blob/master/src/plugins/persistence/couch/plugin.js#L45), so this should be a relatively trivial change. I think the solution is to implement a new instance of the CouchObjectProvider per namespace.

Also see https://github.com/nasa/openmct/issues/7360 where we implement support for "read-only" databases.

**Comment by scottbell** [comment]
@akhenry I think there's a few more gotchas here than I expected:

1. Right now, we only support [one URL per CouchObjectProvider](https://github.com/nasa/openmct/blob/master/src/plugins/persistence/couch/CouchObjectProvider.js#L40). We'll need to be able to map the new URLs to the new DBs
2. This also means that the CouchChangeFeed worker would need to [subscribe to the new servers](https://github.com/nasa/openmct/blob/master/src/plugins/persistence/couch/CouchChangesFeed.js#L84). We'll need to start one worker per server as the workers only receive updates from the database they've registered with.

I'm working through these issues, but wanted to check in with an update.

**Comment by scottbell** [comment]
@akhenry Some questions:
1. It looks like we're going to be installing multiple CouchChangeFeed workers per db, as [change feeds are per db](https://docs.couchdb.org/en/stable/api/database/changes.html).
2. Do new installations still need the `` and `mct` namespaces?
3. If the above is true, I was going to specify `default` database configuration flag that uses those two namespaces. If one isn't specified, will OpenMCT still function?
4. I think the above is the only case where [a separate search provider](https://github.com/nasa/openmct/issues/4667) is required and configured with a generated namespace. Otherwise we can just instantiate it normally with an CouchObjectProvider.
5. I'm adding an optional flag on whether the connection to a db requires an indicator.

**Comment by scottbell** [comment]
Some progress! I think I've got everything working except old configurations:

https://github.com/nasa/openmct/assets/9853862/26701c90-b6e5-4418-b6b7-10537cd783cf

**Comment by ozyx** [comment]
Verified Testathon 2/7/2024

Changes work as expected. Set up two separate CouchDB databases following the instructions in the ticket. Edit is disabled for the readonly folder as expected. Multiple indicators also work if specified. Awesome

**Comment by shefalijoshi** [comment]
Unable to verify this. I followed the steps to create two databases and update index.html to use them.
I get this error:
```
Error: No Provider Matched for keyString "mine"
    get ObjectAPI.js:241
    migrate plugin.js:39
    childObjects CompositionCollection.js:213
    load CompositionCollection.js:213
    #navigateToFirstChildOfRoot Browse.js:140
    doPathChange ApplicationRouter.js:318
    handleLocationChange ApplicationRouter.js:370
    hashChanged ApplicationRouter.js:393
    start ApplicationRouter.js:228
    loadUrl location-bar.js:213
    any location-bar.js:20
    loadUrl location-bar.js:211
    start location-bar.js:181
    start ApplicationRouter.js:229
    start MCT.js:344
    promise callback*nextTick runtime-core.esm-bundler.js:275
    start MCT.js:339
    <anonymous> (index):266
    EventListener.handleEvent* (index):265
[Browse.js:147](webpack://openmct/src/ui/router/Browse.js?5a6b)
```

**Comment by shefalijoshi** [comment]
Verified Fixed
