### ISSUE TITLE
Support "read-only" Couch databases

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#7360]
**Is your feature request related to a problem? Please describe.**
The Open MCT Couch plugin should support a flag that designates a specified database as "read-only". Couch DB does not natively support the concept of read-only databases, but they can be implemented [using design documents](https://github.com/pouchdb-community/pouchdb-authentication/blob/master/docs/recipes.md#everybody-can-read-only-some-can-write-everything ).

**Describe the solution you'd like**
A flag specifying that a database is read-only when the Couch plugin is installed. I think we will need a new optional `isReadOnly` function on object providers, since it currently feature detects create and update functions, and we need more control that this since we are using the CouchObjectProvider for both mutable and read-only databases.

Note that it probably makes sense to implement https://github.com/nasa/openmct/issues/7359 before implementing this change.

**Comment by scottbell** [comment]
Testing notes for this ticket [are here](https://github.com/nasa/openmct/issues/7359#issuecomment-1909750435).
