### ISSUE TITLE
[Mobile Support] Time Conductor is being cut off and unusable for certain device sizes

### ISSUE THREAD

**Issue by rukmini-bose** [nasa/openmct#7366]
#### Summary

When on a small mobile device, some features of Open MCT are being cut off the screen, and thus unusable. 

One example of this is the Time Conductor popup. Note in this image example, I am using an iPhone 12 Pro, and a user _cannot_ scroll horizontally to see the full popup. Therefore, the checkmark and cancel buttons, which save or cancel the Time Conductor settings, is blocked and users cannot change the settings of the Time Conductor. 
<img width="392" alt="Screenshot 2024-01-09 at 10 26 55 AM" src="https://github.com/nasa/openmct/assets/48999852/728d4c77-bb80-43b2-b56a-ef40f3c5c44b">

#### Expected vs Current Behavior

For the Time Conductor, users should be able to view the entire element. This could be possible with either enabling horizontal scrolling, or resizing the Time Conductor popup. 

#### Steps to Reproduce

1. Go to Open MCT on mobile–– either using the devtools, or on your mobile device. If you are using devtools, be sure to empty cache and hard reload. Make sure to select some sort of mobile device, preferable a phone with a smaller resolution (iPhone 12 Pro works).
2. Go to the Time Conductor and click on it to enable the popup to appear.
3. Attempt to change and save the Time Conductor settings.
4. Observe that the save button is cut off the screen, and that horizontal scrolling is disabled so we cannot access the save button at all. 

#### Environment

* Open MCT Version:  3.3.0
* Deployment Type:  testathon
* OS:
* Browser: Chrome

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by rukmini-bose** [comment]
Testing Notes: 
1. Go into the emulator and switch to a mobile device in PORTRAIT mode.
2. Click on the Time Conductor. Verify that the TC popup looks like this, where popup is not being cut off, that there are two rows, and that the buttons to save the TC settings are visible and clickable: 
<img width="365" alt="Screenshot 2024-03-13 at 2 10 13 PM" src="https://github.com/nasa/openmct/assets/48999852/cb797aa7-ef52-4d87-995f-7e7985eba50d">
3. Switch to Fixed Timespan mode and verify the same thing. 
4. Now in your mobile device, switch to landscape mode (if using the Chrome emulator, there's a button that looks like this at the top of your screen.
<img width="47" alt="Screenshot 2024-03-13 at 2 12 24 PM" src="https://github.com/nasa/openmct/assets/48999852/bf8edf55-b1d9-4e92-83f9-903f6cafcecf">
5. Verify that the TC popup looks like the one you see in desktop, like this: 
<img width="479" alt="Screenshot 2024-03-13 at 2 13 12 PM" src="https://github.com/nasa/openmct/assets/48999852/70171c77-dfc9-4ba2-9ca7-36a6d73faf38">
6. Verify that you can click the buttons.

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon 3/13/24

Found another popup gettin cut off, but does not seem overly important::
![Uploading Screenshot 2024-03-13 at 2.34.12 PM.png…]()
