### ISSUE TITLE
Export as JSON needs an activity modal

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#7367]
**Is your feature request related to a problem? Please describe.**
The "Export As JSON" action can take a long time to execute. Currently users are given no feedback that an export is taking place, so with large exports it can appear that the export has silently failed.

**Describe the solution you'd like**
A progress or activity overlay informing the user that an export is happening.

**Comment by scottbell** [comment]
To test:
1. Use OpenMCT with CouchDB
2. Load or create a lot of objects
3. Right click on "My Items" and click "Export as JSON"
4. Note the nifty progress bar


https://github.com/nasa/openmct/assets/9853862/460fb315-6619-4e3a-8f5d-5fa6af18c3b6

**Comment by akhenry** [comment]
Verified fixed. Progress dialog is a thing of beauty.

**Comment by shefalijoshi** [comment]
Verified on 01/25
