### ISSUE TITLE
Allow setting states for activities in a plan (gantt chart and time list views)

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#7369]
**Is your feature request related to a problem? Please describe.**
For situational awareness there is a need to set the execution status of activities within a plan.

**Describe the solution you'd like**
Allow changing the execution state of activities. These should be persisted and reflected to other users.

**Describe alternatives you've considered**
N/A

**Additional context**
See VIPEROMCT-460

**Comment by shefalijoshi** [comment]
Testing instructions:

Create a timelist with a plan (ensure that the plan has id per activity). Sample here: https://github.com/nasa/openmct/files/14059001/Synth.plan.2024-01-25.json
Set the time conductor range so that you have a few activities in view.
Click on any activity/row of the timelist
An Activity properties tab should now be available in the inspector
Ensure that the activities tab shows time properties, any details if available (like a description maybe) and an the activity status section.
Open the exact same timelist and click on the same activity in a different browser window or tab.
Change the status of an activity in one window. The status should update in realtime in other windows for that activity.

**Comment by rukmini-bose** [comment]
Verified Testathon 1/31/2024. Looks good

**Comment by ozyx** [comment]
Verified! Testathon 3/12/24

Looks great, changes reflected across tabs
