### ISSUE TITLE
Deduplicate requirejs.config

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#737]
RequireJS configuration is currently duplicated between `main.js` and `test-main.js` (the latter adds some additional configuration properties.) This should be separated out into a single configuration file used by both scripts.

**Comment by VWoeltjen** [comment]
See [Open MCT WARP adapter](https://github.com/larkin/openmct-warp-adapter) for a minimal example

**Comment by llvieira** [comment]
Hi @VWoeltjen, the link for a minimal example no longer works, could you please update the link? I think I can help with a solution for this issue.

**Comment by LeoDog896** [comment]
[(OpenMCT doesn't use RequireJS anymore)](https://github.com/nasa/openmct/commit/0d53898af9797ed8e725619ecf06f88f72d31dcf)

**Comment by ozyx** [comment]
@LeoDog896 thanks! closing this
