### ISSUE TITLE
Allow compact view for time list for Situational Awareness dashboards

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#7377]
**Describe the solution you'd like**
As part of the situational awareness work, we need a compact view of the time list view so it can be included in a dashboard.
This compact view will have minimum needed information and widgets for easier visualization of activities.

The design for compact view can be found on confluence page "Situational Awareness Needs and Design"

**Comment by shefalijoshi** [comment]
Testing Instructions:
Create a timelist and add a plan to it, save the timelist.
Adjust the time conductor start and end times so that some activities are in view.
(Optional: Note which activities are in view)
Edit the timelist and click on the View Properties tab in the inspector and change the Display style to 'Expanded'.
Save the change.
The view should now have switched to the expanded view.
Make sure that you can see the same activities that you saw in the compact view.
Find the `Situational Awareness Needs and Design` design on confluence and check that the design elements match including:
1. Name
2. Duration, start time, end time, count up/ count down and count up/down labels
3. Progress pie graphics
4. Activity state graphics

Select an activity in the expanded view
Click on the Activity Properties tab in the inspector
You should see Activity time properties, details and status
Changing activity status should be reflected in the expanded view (including graphics changes)

**Comment by rukmini-bose** [comment]
Testathon 2/27/2024: waiting on https://github.com/nasa/openmct/pull/7485

**Comment by shefalijoshi** [comment]
#7485 Is now fixed.

**Comment by rukmini-bose** [comment]
Verified Testathon 3/13/2024. Looks gucci!

**Comment by akhenry** [comment]
I noticed in testing that changing the status of one activity sometimes affected other activities. I don't know if this is by design and simply due to some logic that I am just not aware of? It didn't happen with every activity. See video below - 


https://github.com/nasa/openmct/assets/4215777/c0949919-a95d-4eb3-8431-9a62f60270c9

**Comment by shefalijoshi** [comment]
> I noticed in testing that changing the status of one activity sometimes affected other activities. I don't know if this is by design and simply due to some logic that I am just not aware of? It didn't happen with every activity. See video below -
> Screen.Recording.2024-03-14.at.5.07.42.PM.mov

This is a bug in the planning tool. Activities that were copied appear to have the same uuid in the plan. I will raise this with the planning tools team.

**Comment by akhenry** [comment]
In that case, verified.

**Comment by charlesh88** [comment]
Testathon 2024-03-19: all test instructions run through, verified fixed.
