### ISSUE TITLE
NASA moved the Example Imagery files

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#7380]
#### Summary

Example Imagery loads its images from NASA's image archives. These images now 404, likely due to NASA's recent work on web consolidation and migration to WordPress. These URLs likely just need to be updated.

#### Expected vs Current Behavior

The image urls should not 404

#### Steps to Reproduce

1. Load example imagery
2. Images no loady

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [x] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information
We reference images hosted by nasa hq like 'https://www.hq.nasa.gov/alsj/a16/AS16-117-18748.jpg' in our example imagery plugin. This changed to 'https://www.nasa.gov/wp-content/uploads/static/history/alsj/a16/AS16-117-18731.jpg'

**Comment by unlikelyzero** [comment]
Candidate for backport since this is technically a blocker for a default plugin

**Comment by rukmini-bose** [comment]
Testathon Verified locally on 1/18/2024
