### ISSUE TITLE
LAD Table Sets failing to initialize telemetry

### ISSUE THREAD

**Issue by scottbell** [nasa/openmct#7383]
#### Summary

LAD Table Sets are failing to initialize telemetry on load:
```js
Uncaught (in promise) TypeError: this.renderWhenVisible is not a function
    at Proxy.updateView (LadRow.vue:244:34)
    at Proxy.setLatestValues (LadRow.vue:267:12)
    at TelemetryCollection.emit (index.js:116:1)
    at TelemetryCollection._processNewTelemetry (TelemetryCollection.js:270:1)
    at TelemetryCollection._requestHistoricalTelemetry (TelemetryCollection.js:172:1)
```

<img width="1650" alt="Screenshot 2024-01-18 at 10 54 18 AM" src="https://github.com/nasa/openmct/assets/9853862/160e9e59-d6b8-4d6f-a883-017a378292c0">

#### Expected vs Current Behavior

LAD Tables are working as expected. LAD Table Sets should also load telemetry properly.

#### Steps to Reproduce
1. Create two SWGs
2. Create two LAD tables with above SWGs
3. Create a LAD Table Set with above LAD tables
4. Notice telemetry is always blank and exception is printed to console.

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by davetsay** [comment]
verified
(but seeing two other issues)

**Comment by khalidadil** [comment]
Verified in Testathon on 01/23/24

**Comment by charlesh88** [comment]
Verified Testathon 01/25/24
