### ISSUE TITLE
Allow filtering of time list activities by metadata

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#7389]
**Is your feature request related to a problem? Please describe.**
In addition to the name, filtering on other metadata of an activity is beneficial

**Describe the solution you'd like**
Allow filtering activities on metadata in addition to just the 'name'.
Allow users to specify which specific properties they would like searched for an activity. In the absence of these specified properties, by default, search for values in `properties`.
```
activity: {
    name: "First",
    properties: {
           location: "Grand Hall"
    }
}
```

**Comment by shefalijoshi** [comment]
Testing instructions:
Create a timelist by adding a plan to it.
Ensure that you can see some activities in the plan
Edit the timelist and click on the timelist properties tab to view filtering options.

Use comma separated values to filter the list and check expected results - try just the name, then just the metadata and both.
Use invalid filters and check that you see an error
In case of erroneous filter, the valid portion of the filter is applied and the rest is discarded

**Comment by unlikelyzero** [comment]
Putting Feature on here to capture the design work comparison

**Comment by rukmini-bose** [comment]
Verified Testathon 1/31/2024

**Comment by davetsay** [comment]
metadata filtering does not appear to be working. i clicked on an activity with a property with a string value. nothing displays when filtering on that metadata. Activity Names seems to work properly

**Comment by rukmini-bose** [comment]
If searchable meta-data values include numbers, this may be an issue. A lot of the numeric meta-data include decimals, which are considered an "invalid" input and will throw an error.

**Comment by shefalijoshi** [comment]
Reopening - filtering on viper with sourceMaps has a bug.

**Comment by charlesh88** [comment]
Testathon 2024-01-31: verified NOT working. 
1. Tried various values from existing metadata values (like "rails") and filtering didn't function. 
2. We can't filter on values with "." in them - why not? If the user is trying to filter on a decimal number, they won't be able to.
3. The error messaging for the input is very poor and provides no concrete feedback of the what the problem is or how to address it. This needs to be addressed from a text and layout standpoint.

![image](https://github.com/nasa/openmct/assets/1056412/aadd15f8-a6ab-4546-8c26-7b3e112fdf71)

**Comment by shefalijoshi** [comment]
Testing instructions:
Create a new timelist.
Add a plan to this timelist. For example: https://github.com/nasa/openmct/files/14059001/Synth.plan.2024-01-25.json
Ensure you are seeing several activities in the timelist by adjusting the time conductor - (2024-01-25 00:00:00 to 2024-02-25 00:00:00)
Edit the timelist and click on the View Properties inspector tab
In the metadata filtering text input, type `sa` or `cm`

You should see some results.

**Comment by rukmini-bose** [comment]
Verified Testathon 2/8/2024: works well with strings and various numbers.

**Comment by ozyx** [comment]
Verified Testathon 2/27/24
