### ISSUE TITLE
Provide support for worker-based WebSocket management

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#7390]
**Is your feature request related to a problem? Please describe.**

The best practice for WebSocket management [according to the Chrome development team is to do it from within a worker](https://bugs.chromium.org/p/chromium/issues/detail?id=456476#c30). This prevents the UI being blocked on WebSocket operations, and also means that a slow UI does not induce unnecessary back-pressure on servers, which can affect overall server performance.

Aditionally, In testing it has been found that batching telemetry into arrays and passing them back to views periodically provides superior performance to invoking a subscription callback for individual telemetry values.

**Describe the solution you'd like**

API support for worker-based WebSocket subscriptions with optional batching. The API should handle basic state and lifecycle management of WebSocket connections, including telemetry queuing and automatic re-connection on error. These features are assumed to be necessary for most WebSocket based connections. The details of message parsing should be left to individual telemetry providers.

Note that issue https://github.com/akhenry/openmct-yamcs/issues/213 exists to implement worker-based WebSocket handling in the openmct-yamcs adapter.

**Comment by akhenry** [comment]
@akhenry To add testing notes.

**Comment by davetsay** [comment]
still needs testing instructions @akhenry

**Comment by akhenry** [comment]
Testing notes on https://github.com/akhenry/openmct-yamcs/issues/424 which fixes a bug in the original implementation.
