### ISSUE TITLE
Incorporate IndicatorAPI into the Vue reactivity system

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#7394]
**Is your feature request related to a problem? Please describe.**
In our IndicatorAPI we expect an HTMLElement in order to ["go around" the Vue system](https://github.com/nasa/openmct/blob/43ae3cf655feb3b202fa57f85275d274b4079bcd/src/ui/layout/status-bar/StatusIndicators.vue#L37) and:
1. Mount HTMLElements dynamically (using `this.$el.appendChild`)
2. Maintain the framework-agnostic nature of the Open MCT API

This approach works, but can lose reactivity if we're not careful. Additionally, we can't conditionally render/un-render certain indicators based on API-wide settings such as User Role. This approach also has performance implications, [since we create an Anonymous Vue component and mount an additional Vue app for each indicator](https://github.com/nasa/openmct/blob/43ae3cf655feb3b202fa57f85275d274b4079bcd/src/plugins/clock/plugin.js#L98).

**Describe the solution you'd like**
![image](https://github.com/nasa/openmct/assets/9259993/ab3d8ab0-d220-496f-965b-cc09a30966a8)

We should avoid using `mount()` and creating a whole new Vue app for each indicator.

With Vue 3, there are better ways to wrap HTMLElements as Vue components (using [render functions](https://vuejs.org/guide/extras/render-function)) so we can maintain Open MCT's framework-agnostic nature, while also keeping the indicators within the same main Vue app. Additionally, we can support rendering Vue components directly via a new, optional property on indicators.

**Comment by akhenry** [comment]
![image](https://github.com/nasa/openmct/assets/4215777/add6274d-6e93-4040-9a77-3e54a0807423)

**Comment by ozyx** [comment]
Hah! I realized this _after_ I made the meme so I let it slide :)

WHAT IF I TOLD YOU

WE CAN (eventually) HAVE ONLY ONE VUE APP

I guess would be the correct text

**Comment by ozyx** [comment]
# Testing Instructions

1. Load Open MCT locally in its default configuration
2. Verify that all default Indicators appear and are functional (snapshot, clock, clearData, notifications)
3. Load Open MCT VIPER
4. Verify that all indicators appear and are functional (indicators listed above, plus Couch DB status, etc.)
5. Open the console and install the Performance Indicator by using the command: `this.openmct.install(this.openmct.plugins.PerformanceIndicator())`
6. Verify it appears in the status bar immediately and dynamically updates

**Comment by davetsay** [comment]
verified
