### ISSUE TITLE
Actions menu on Display Layout alphanumeric doesn't work

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#7400]
#### Summary
Initially reported by Matt Machlis.
Context-clicking on an alphanumeric in a Display Layout  doesn't work and throws a console error. This problem was initially seen in the deployment for the VIPER mission (Version: 3.3.0-next) but also was verified in current master, which is the same version. Given that this is a critical feature that _is_ used and is a type of data loss, filing as a blocker.

#### Expected vs Current Behavior
This gesture should display an actions menu allowing the user to copy the current value and view historic data for that end point.

#### Steps to Reproduce

1. Context-click (right-click) an alphanumeric within a Display Layout.
2. Observe: no action menu is displayed, and a console error is thrown:
![Screenshot 2024-01-22 at 2 26 22 PM](https://github.com/nasa/openmct/assets/1056412/1dfb6173-f691-4cb7-a753-8b0633084610)

#### Environment

* Open MCT Version:  3.3.0-next
* Deployment Type:  VIPER dev, open
* OS: all
* Browser: all

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment]
Something to do with `renderAsVisible` making its way into the context menu actions @scottbell 

![image](https://github.com/nasa/openmct/assets/9259993/2a7e1c5c-106c-47d7-988e-817ac9244eb0)


Either way, a simple null check will fix this

**Comment by jvigliotta** [comment]
_kinda_ fixed. The menu shows, but there's still an error thrown:
![Screenshot 2024-01-25 at 1 15 15 PM](https://github.com/nasa/openmct/assets/12013460/4c1b346c-fbb5-43b2-b60e-ef1e54d3e548)

**Comment by scottbell** [comment]
> _kinda_ fixed. The menu shows, but there's still an error thrown

@jvigliotta it looks like it's missing the object on the CouchDB server? Unclear how the object rendered in the first place!

**Comment by ozyx** [comment]
Verified Fixed -- Testathon 1/31/24

> _kinda_ fixed. The menu shows, but there's still an error thrown: ![Screenshot 2024-01-25 at 1 15 15 PM](https://private-user-images.githubusercontent.com/12013460/299809498-4c1b346c-fbb5-43b2-b60e-ef1e54d3e548.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NDAyNTMsIm5iZiI6MTcwNjczOTk1MywicGF0aCI6Ii8xMjAxMzQ2MC8yOTk4MDk0OTgtNGMxYjM0NmMtZmJiNS00M2IyLWI2MGUtZWYxZTU0ZDNlNTQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDIyMjU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwZTgyYTZjZDcxZDJkNzlhODNiN2U0N2JkYjEzMTJiODA5N2M2OWVhNWU0NjI0MjlhYTQxNGNhN2U4YjY0NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SC2nZuih-tWhgUG_ucZfQi29K7IGCpZwfQRD1LneR8g) Note: Action items still work correctly as well as show.

^ found this bug though #7446
