### ISSUE TITLE
[Plot Legends] Legends not expanding when requested 

### ISSUE THREAD

**Issue by rukmini-bose** [nasa/openmct#7403]
#### Summary

This issue is seen in both Stacked Plots and Overlay Plots. However, the behaviors amongst the two are _slightly_ different, but caused by the same issue. 

***_**OVERLAY PLOT ISSUE (Occurs with both Real Telemetry or Sine Wave Generators)**_ ***
When, in an Overlay Plot that is populated either with _real telemetry,_ or _Sine Wave Generators,_ a user selects the "expand by default" option for the legend and saves, the class that enables the legend to be expanded is being applied, but the legend is not actually expanding. Instead, we're getting into a weird state that looks like the image below. Notice that the triangle icon is indeed the one that we use for expanding an item (the triangle is pointing down), but the legend itself is not expanding. For a user to see the expanded legend, they have to manually click the icon to first collapse it, then click it again to expand it. 
<img width="530" alt="Screenshot 2024-01-23 at 1 59 18 PM" src="https://github.com/nasa/openmct/assets/48999852/4bcf450d-2aac-4414-8e05-f84aa2067b67">

Additionally, the inspector settings are not updating once out of edit mode or even refreshed. This image below shows that even after I saved the plot settings with the legend "expanded by default" enabled, then _refreshed_, the inspector still shows the setting as disabled. However, note that if I do go into edit mode and look at the setting, it shows that it is enabled. 
<img width="1228" alt="Screenshot 2024-01-23 at 2 00 58 PM" src="https://github.com/nasa/openmct/assets/48999852/54441a43-5b17-4d79-a556-00fd836c0ff2">

***_**STACKED PLOT ISSUE (Sine Wave Generators and Real Telemetry present different behaviors)**_ ***
(A) When, in a Stacked Plot that is populated with **Sine Wave Generators**, the following incorrect behavior happens when you enable the "expand by default" setting for legends: 
While the inspector shows that the setting is enabled, the legends in the plot are not being expanded on default. Unlike the Overlay Plot issue from above, the "expanded" class is not being added in the code, and thus is not even being shown visually with the triangle icons.  
<img width="944" alt="Screenshot 2024-01-23 at 2 15 37 PM" src="https://github.com/nasa/openmct/assets/48999852/d765db36-350b-4624-99b9-6c09f5abe439">

(B) When, in a Stacked Plot that is populated with **Real Telemetry**, the following incorrect behavior happens when you enable the "expand by default" setting for legends, save the object, and refresh: 
The same behavior as Overlay Plots occurs, where the Inspector still shows the setting as _disabled_, while the legend icon appears to be expanded, while the legend table itself is collapsed. 
<img width="947" alt="Screenshot 2024-01-23 at 2 28 50 PM" src="https://github.com/nasa/openmct/assets/48999852/fcea9e60-e35f-4218-98fa-3db6110436fa">

#### Expected vs Current Behavior

When the setting for legends, "expand by default" is enabled on a Overlay Plot or Stacked Plot, the legend should be expanded when you first navigate to the object. You should not have to manually expand the legend.

#### Steps to Reproduce

**OVERLAY PLOT ISSUE & STACKED PLOT ISSUE (USING REAL TELEMETRY)_ **
1. Navigate to an Overlay Plot and go into Edit Mode. For Stacked Plots, make sure the plot is populated with REAL telemetry, not Sine Wave Generators.
2. Under the Config tab in the Inspector, enable the "expand by default" option for legends, then Save. 
3. Observe that in the Inspector, under the Config tab, the "expand by default" setting is still set to "No."
4. Also observe that the legend's triangle icon is pointing down (showing the legend is expanded), but the legend table does not appear until you press the triangle icon to collapse, then press again to expand the legend.

**_STACKED PLOT ISSUE (USING SWGs)_ **
1. Navigate to a Stacked Plot that is populated with SWGs. 
2. Under the Config tab in the Inspector, enable the "expand by default" option for legends, then Save. 
3. Observe that while the inspector is showing the "expand by default" setting set to "Yes", the legend in the plot is completely collapsed.

#### Environment

* Open MCT Version:  3.3.0
* Deployment Type:  testathon
* OS:
* Browser: Chrome

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by rukmini-bose** [comment]
TESTING INSTRUCTIONS 

**OVERLAY PLOT ISSUE**
1. Navigate to an Overlay Plot and go into Edit Mode. 
2. Under the Config tab in the Inspector, enable the "expand by default" option for legends, then Save.
3. Verify that in the Inspector, under the Config tab, the "expand by default" setting is still set to "Yes."
4. Also Verify that the legend is automatically expanded. You can double check by navigating away and back and seeing the legend is expanded on default. 

**STACKED PLOT ISSUE (with REAL telemetry)** 
1. Navigate to a Stacked Plot. Make sure the plot is populated with REAL telemetry, not Sine Wave Generators.
2. Repeat steps 2-4 from above. 
 
**STACKED PLOT ISSUE (USING SWGs) **
1. Navigate to a Stacked Plot that is populated with SWGs.
2. Under the Config tab in the Inspector, enable the "expand by default" option for legends, then Save.
3. Verify that the inspector shows the "expand by default" set to YES, AND that the legend in the plot is automatically expanded as well.

**Comment by ozyx** [comment]
Verified Fixed - Testathon 3/5/24

**Comment by charlesh88** [comment]
Testathon 2024-03-05 verified fixed.
