### ISSUE TITLE
Change Imagery positional freshness from 'POS' to 'ROV'

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#7404]
**Is your feature request related to a problem? Please describe.**
To avoid confusion with the concept of 'pose', change the Imagery view's positional freshness indicator label from 'POS' to 'ROV'. Ideally, we'd make this a per-deployment configuration item, but in the short-term this issue seeks to just change it in open.

@akhenry Thoughts?

**Comment by charlesh88** [comment]
### Testing Notes
1. With the Time Conductor in Real-time mode, view a Imagery end point that's capable of displaying positional freshness.
3. Wait for a new image to come in.
4. Repeat step 2 zero to 10,000 times.
5. Observe: the positional freshness indicator beneath the image should read 'ROV'.

![Screenshot 2024-01-23 at 5 00 58 PM](https://github.com/nasa/openmct/assets/1056412/229d15c3-a523-40bd-8862-339059a9852c)

**Comment by ozyx** [comment]
Need to retest when we have imagery telemetry in our testing environment

**Comment by unlikelyzero** [comment]
Verified on hulk

**Comment by charlesh88** [comment]
Testathon 2024-02-27 verified fixed.
