### ISSUE TITLE
Canvas sometimes dies on refresh

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#7405]
#### Summary

One of our e2e tests caught this. Sometimes when viewing an Overlay Plot with a SWG in it, if you reload the page, Open MCT goes into a state where nothing gets drawn on any canvas. It seems that the canvas are disconnected somehow.

https://github.com/nasa/openmct/assets/9259993/0a7ab651-47e3-4558-9478-e013f3d7af82

@scottbell I think it has something to do with the IntersectionObserver destroying the canvas on load

#### Expected vs Current Behavior

The plot should render

#### Steps to Reproduce

1. Create an SWG
2. Create an Overlay Plot
3. SWG -> Overlay Plot
4. Navigate to the Overlay Plot
5. Set a breakpoint[ here](https://github.com/nasa/openmct/blob/master/src/plugins/plot/chart/MctChart.vue#L284)
6. Reload the page while moving your mouse around where the canvas WOULD be
7. Breakpoint gets hit (keep trying if it doesnt work the first time)
8. continue, notice no canvas gets drawn on

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by scottbell** [comment]
Here's my current explanation of what's going on:

If the page load is slow-ish, [the splashscreen](https://github.com/nasa/openmct/blob/master/index.html#L72) covers the ObjectView as it mounts, causing the visibility observer to detect that we're hidden. This can cause a [race condition here](https://github.com/nasa/openmct/blob/master/src/plugins/plot/chart/MctChart.vue#L688) if `scheduleDraw` as `renderWhenVisible` needs to fire once for the canvas to load. Further, there's a disconnect between the component loads and `renderWhenVisible` as the ObjectView only constructs the [VisibilityObserver once](https://github.com/nasa/openmct/blob/master/src/ui/components/ObjectView.vue#L134). Instead, I think we should be rebuilding this guy every time the object view changes.

The current branch I hope addresses this, but I'd like to sync with you @ozyx to test if you please.

**Comment by ozyx** [comment]
Verified fixed Testathon 1/31/24

Unable to reproduce both locally and in our testing environment. Nice!
