### ISSUE TITLE
Event colors don't provide enough contrast

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#7410]
As reported by VIPER, there are issues with colors used for text in the Events table, particularly for Errors which use a red color. These colors are defined in SCSS files in the open repo, hence this issue. This is a problem for mission-critical information, so this is a blocker. 

Colors should be adjusted in all themes and smoke tested for a11y conformance.

**Comment by charlesh88** [comment]
### Testing Notes
Reference images show examples of all the different event color levels (yellow, red, purple, orange) in Espresso and Snow themes. 
1. View Events data in a way that allows you to see all the available levels of events in your deployment.
2. Verify that the table's view corresponds with the matching theme reference image below.
3. If you have the Wave accessibility plugin installed, enable that and verify that there are no Contrast violations in the table's view area. **IMPORTANT**: this issue depends on certain key theme colors (like the page body background color) having been updated via https://github.com/nasa/openmct/pull/7315. If those changes aren't merged, then this step won't pass verification.
4. Switch themes using the devtools Console command `openmct.install(openmct.plugins.Snow())` or `openmct.install(openmct.plugins.Espresso())`.
5. Repeat steps 2 and 3.

#### Espresso theme example 
![Screenshot 2024-01-24 at 3 15 50 PM](https://github.com/nasa/openmct/assets/1056412/4eab7e5d-b6f7-4e1f-8240-92da53409c75)
#### Snow theme example 
![Screenshot 2024-01-24 at 3 17 01 PM](https://github.com/nasa/openmct/assets/1056412/3bf2085b-a5e3-4e28-b17c-f855e55b0712)

**Comment by rukmini-bose** [comment]
Verified Testathon 2/5/2024. Looks gucci

**Comment by ozyx** [comment]
Verified Testathon 2/5/2024
