### ISSUE TITLE
Add Mission Status user indicator control panel

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#7420]
**Is your feature request related to a problem? Please describe.**
Issue to put work against the Open repo for the mission status user indicator component.

**Comment by charlesh88** [comment]
Covered by https://github.com/nasa/openmct/pull/7418

**Comment by charlesh88** [comment]
Testathon 2024-03-05: deployment yaml file is not mapping permissions properly, so Camera, Command, etc. statuses can't be set currently. But, missionStatus1 - 6 can be set, update values as expected in Yamcs, and properly reconstitute their values in the control panel itself. 

With that: verified fixed.

![image](https://github.com/nasa/openmct/assets/1056412/77c4f476-cf29-4a5a-bf73-6d926f029cb1)

![image](https://github.com/nasa/openmct/assets/1056412/038ef12f-580a-427b-8d38-3b03ea2d98e7)

**Comment by davetsay** [comment]
verified...
but got an error when switching from realtime to fixed time in time conductor. I think the error only occurs for endpoints that have not had GO/NO GO statuses set.
