### ISSUE TITLE
[Condition Sets] "Apply Test Data" doesn't work anymore

### ISSUE THREAD

**Issue by rukmini-bose** [nasa/openmct#7424]
#### Summary

The "Apply Test Data" feature allows us to test Condition Sets that are being used by manually inputting data values. This does not work anymore. This is problematic for users that are creating objects in Open MCT with Condition Sets. If data is not flowing, there's no way for them to test what they have created. 

After inputting a valid value in the input (see blue rectangle in picture), the "Apply Test Data" toggle (see red rectangle in picture) should be enabled for us to click. It is not. 
<img width="1183" alt="Screenshot 2024-01-29 at 11 54 31 AM" src="https://github.com/nasa/openmct/assets/48999852/ab996b33-2a80-4e5a-a702-3545a12bddfc">

#### Expected vs Current Behavior

After inputting valid data in the "Apply Test Data" area, we should be able to click the button to test our Condition Set. 

#### Steps to Reproduce

1. Create or Navigate to a Condition Set that is populated with a couple of conditions.
2. Under "Test Data", add some test data values in by selecting a telemetry point, selecting "value", and typing in a valid value. (If you're using real data, you may need to double check what are valid values for that specific telemetry point). 
3. Observe that the "Apply Test Data" toggle never turns on for us to click, making this feature useless. 

#### Environment

* Open MCT Version:  3.3.0 
* Deployment Type:  Hulk and Testathon 
* OS:
* Browser: Chrome

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by unlikelyzero** [comment]
This is a blocker for GDS Testing

**Comment by rukmini-bose** [comment]
Verified Testathon 3/5/2024 yay this works again!

**Comment by ozyx** [comment]
Verified Fixed - Testathon 3/5/24
