### ISSUE TITLE
Large View for Telemetry doesn't show any plot

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#7446]
#### Summary

Seen in Testathon. Large view for telemetry doesn't seem to show anything on the plot.

#### Expected vs Current Behavior

Plot should show the same data as in non-large view

https://github.com/nasa/openmct/assets/9259993/1c6407a0-3de7-487e-87d5-64afda66a0c2

#### Steps to Reproduce

1. Try to view large view of any telemetry (right click, "View" on tree item, action menu item, or subcomponent right-click menu
2. See nada

#### Environment

* Open MCT Version:  18e4b9da6561038f658e5c46bb2823cd84982535
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment]
Testathon 2/27/24

Verified fixed-- view large in all different scenarios works as expected.
Tested:
- subcomponent right click
- Large View button
- Edit / Preview
- Right click action menu item

**Comment by rukmini-bose** [comment]
Verified Testathon 3/5/2024.
