### ISSUE TITLE
Selecting activities in Gantt Chart view throws errors

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#7447]
#### Summary

Selecting activities in the Gantt Chart view throws errors:

![image](https://github.com/nasa/openmct/assets/9259993/e660aba2-7e60-4d26-932b-e3b1e43f5f0f)

#### Expected vs Current Behavior

Selecting an activity should have the same behavior as in a Plan, but user should also be able to set activity status.

#### Steps to Reproduce

1. Create a Gantt Chart
2. Drag in a Plan (used the single Plan on testathon)
3. Click activities
4. Notice errors in console

#### Environment

* Open MCT Version:  
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment]
Testathon 2/27/24
Verified fixed -- no more errors when selecting

**Comment by rukmini-bose** [comment]
Verified Testathon 2/27/2024
