### ISSUE TITLE
Time List auto-centering is problematic and should be removed

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#7449]
This is closely tied to and may be a dupe of #7167.

#### Summary
Automatically scrolling to  "auto-center" current Activities in the Time List view (per https://github.com/nasa/openmct/issues/7167) is still not fixed. The centering feature doesn't work as requested, and the view still "fights" manual scrolling: when trying to manually scroll the view, the auto-centering will attempt to wrest the control away from the user.

#### Desired: Note current Activity at top in view:
![Screenshot 2024-01-31 at 2 49 08 PM](https://github.com/nasa/openmct/assets/1056412/81a3d532-8804-4cd5-a42b-f3d08e9b8274)

#### Not desired: When auto-scrolled, top current Activity is now hidden:
![Screenshot 2024-01-31 at 2 49 15 PM](https://github.com/nasa/openmct/assets/1056412/cde7016c-38d9-4ee2-88da-1d2f19074aaf)

#### Expected vs Current Behavior
Given the recently added ability to apply the independent Time Conductor to this view, which allows the user to have better control over what's in view, the need for auto-centering is much less or nonexistent. Additionally, users now need to be able to easily manually scroll and select Activities to set status on them. 

Given the above, I strongly recommend we entirely remove the auto-centering functionality, keep the current sorting methods and relying on the Time Conductor to control what's in view at a given time.

#### Steps to Reproduce

1. View the Time List with plan data that has past, current and future activities and events.
2. For auto-centering: size the view such that the vertical scroll bar appears. You may have to try different sizes, with the scrollbar _almost_ disappearing if all activities can be brought into view (see image above).
3. For scroll control "fighting": size the view so that 50% of activities are hidden beneath the scroll, then manually scroll the view. Observe that it will be sporadically hard to scroll, or after scrolling and attempting to select an Activity, the desired activity will be automatically scrolled out of view. 

#### Environment

* Open MCT Version:  3.3.0-next
* Deployment Type:  /testathon
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by akhenry** [comment]
Recategorizing as blocker, it's potential loss of situational awareness.

**Comment by ozyx** [comment]
Verified-- Testathon 2/27/24

No more auto scrolling in non edit, edit, compact, and expanded modes

**Comment by rukmini-bose** [comment]
Verified Testathon 3/5/2024
