### ISSUE TITLE
Time List compact view "Time To/From" always shows with "+"

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#7450]
#### Summary
![Screenshot 2024-01-31 at 3 31 37 PM](https://github.com/nasa/openmct/assets/1056412/ab56a90e-7400-4393-bc70-aaa043039634)

In the Time List compact view, all Activities regardless of time frame (past/current/future) are displaying with "+" in their "Time To/From" values. Given that this dangerously mis-represents the character of available time in an essential view, this is a blocker. This is not a problem in the expanded Time List view. 

#### Expected vs Current Behavior
Current and future Activities (blue and orange arrows above) will always be counting down, and should have a "-" instead.

#### Steps to Reproduce

1. View the Time List with plan data that has past, current and future activities and events.

#### Environment

* Open MCT Version:   3.3.0-next
* Deployment Type:  testathon
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by scottbell** [comment]
Pretty simple fix I think. Will add a test too:

<img width="1195" alt="Screenshot 2024-02-01 at 2 07 52 PM" src="https://github.com/nasa/openmct/assets/9853862/309085ff-e3df-4ae0-bb36-64384e330e84">

**Comment by ozyx** [comment]
Verified Testathon 2-5-2024

Tested locally and on testathon and looks great

**Comment by rukmini-bose** [comment]
Verified Testathon 2/5/2024

**Comment by charlesh88** [comment]
Testathon 2024-02-05: verified fixed.
