### ISSUE TITLE
[Overlay Plots] Cannot Remove Elements from a Plot

### ISSUE THREAD

**Issue by rukmini-bose** [nasa/openmct#7456]
#### Summary

We currently cannot remove elements from an Overlay Plot if the plot is in view. If we attempt to remove it from the Element Pool or through the Object Tree, this error is thrown: 
<img width="986" alt="Screenshot 2024-02-02 at 9 54 52 AM" src="https://github.com/nasa/openmct/assets/48999852/d4b03f47-5328-4199-872b-7f9e51d802fa">

The only workaround is to navigate _away_ from the object, and remove the elements through the Object Tree. 
#### Expected vs Current Behavior

We should be able to remove elements from a plot. 
#### Steps to Reproduce

1. Create or Navigate to an Overlay Plot with multiple elements in it. Open your console. 
2. Go to Edit Mode, and in the Elements Pool, right click one of the elements and press "remove". 
3. Observe that there is an error thrown in the console, similar to the image above. 
4. Save the object and refresh. Observe that the element you tried to remove, has indeed, NOT been removed. 
5. Now, go to the object tree and try to remove an element from the Overlay Plot from there. 
6. Repeat 3 and 4. 

#### Environment

* Open MCT Version:  3.3.0
* Deployment Type:  /testathon, commit hash 5e3b051bf150a98eebf2cf4ed39bd9caf4b8c017
* OS:
* Browser: Chrome

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment]
Also verify that removing the element from the object tree action menu works properly and throws no errors

**Comment by rukmini-bose** [comment]
Verified Testathon 2/27/2024, looks gucci
