### ISSUE TITLE
HTMLElement indicators are not justified with Vue indicators in the status bar

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#7457]
#### Summary

Vue component indicators and HTMLElement indicators (which are wrapped in Vue components) are not in line with eachother in the status bar.

#### Expected vs Current Behavior

Current:
<img width="649" alt="image" src="https://github.com/nasa/openmct/assets/9259993/77e70e72-12b7-42d5-911e-f36eac7ae77f">

Expected:
<img width="649" alt="image" src="https://github.com/nasa/openmct/assets/9259993/f33f7f59-9736-4ab7-9671-60ce2d508243">

#### Steps to Reproduce

1. Start Open MCT
2. In the console, do: `this.openmct.install(this.openmct.plugins.PerformanceIndicator())`
3. Notice the indicators are not lined up
4.

#### Environment

* Open MCT Version: 4.0.0-next
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment]
Testing Instructions:

Follow steps to reproduce and verify that all indicators are justified with eachother

**Comment by charlesh88** [comment]
Testathon 2024-02-27 verified fixed.
