### ISSUE TITLE
Erroneous "Telemetry metadata does not match the active time system" notifications

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#7476]
#### Summary
Open MCT shows the above error incorrectly when an object is missing. This notification is intended to inform the user when a misconfiguration has occurred.

An attempt was made to fix this issue previously but it had either regressed or the issue was never completely solved - https://github.com/nasa/openmct/issues/6349#issuecomment-1462649780

#### Expected vs Current Behavior
The Telemetry Metadata error should only be shown for _extant_ objects, and not missing objects.

#### Steps to Reproduce

1. Navigate to the "TAB - DRIVING RAILS" display in the VIPER Open MCT test environment
2. Observe a notification that states "Telemetry metadata does not match the active time system"

#### Environment

* Open MCT Version: 4.0.x 0aceb4b590be32d0abfc172b972b82b8c2bbcbfd
* Deployment Type: VIPER Test

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by jvigliotta** [comment]
## Testing
- follow repro steps and makes sure there are no warnings in console or error notifications for telemetry metadata

**Comment by ozyx** [comment]
Verified Fixed -- testathon 3/28/24
