### ISSUE TITLE
Flicker along right-hand side of screen when starting WARP

### ISSUE THREAD

**Issue by shobart** [nasa/openmct#748]
This happens only on the PC (not Mac of Linux).

1) start WARP
2) Observe the initial splash screen, and very shortly after, a flicker of a line along the right-hand side.

The flicker goes away quickly.  Charles/Andrew/Pete speculate this is a scroll bar showing briefly.

Notes:  On Chrome, this happens only on start-up; refresh does not make it re-occur.
On Firefox, browser refresh causes this to re-occur.

**Comment by RCarvalhoNASA** [comment]
20160317 testathon this seems to be resolved now

**Comment by charlesh88** [comment]
Testathon 031716
Verified fixed
