### ISSUE TITLE
Add progress indicator to expanded Time List view

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#7483]
**Is your feature request related to a problem? Please describe.**
The design for Activities in the new expanded Time List view includes a progress indicator that shows how much time is left to complete an Activity. This indicator was not able to be included in the first round deliverable. The lack of this indicator makes it very hard to see that an Activity has been set to "In Progress" due to it being currently selected.

**Describe the solution you'd like**
Add a progress indicator back into the element.

**Describe alternatives you've considered**
A graphic element (like the checkmark used for Completed activities) that indicates the work status.

**Comment by unlikelyzero** [comment]
Will test the implementation in https://github.com/nasa/openmct/issues/7377
