### ISSUE TITLE
Overlay Plot swatches do not handle compressed vertical space well

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#7490]
#### Summary
When an Overlay Plot is in a tightly compressed vertical space, the axis swatches overrun their space and can get superimposed over an expanded legend in a way that makes view very difficult to read.

#### Legend collapsed
![Screenshot 2024-02-08 at 10 07 44 AM](https://github.com/nasa/openmct/assets/1056412/30ddfc6b-c062-4092-a447-1eda02ac1ff0)

#### Legend expanded
![Screenshot 2024-02-08 at 10 07 58 AM](https://github.com/nasa/openmct/assets/1056412/a7639192-9e9d-4884-83b7-d98a7abe2dee)

#### Expected vs Current Behavior
We should clip the axis labels area within the plot axis and display area by adding an `overflow: hidden` style:

![Screenshot 2024-02-08 at 10 27 19 AM](https://github.com/nasa/openmct/assets/1056412/3c0caa66-6356-4466-b16e-e9cec4dcd9e0)

#### Steps to Reproduce

1. Make an Overlay Plot with a number of items in it.
2. Make it really short, then expand the legend.
3. Note that is resembles the reference images above.

#### Environment

* Open MCT Version:  3.3.0-next
* Deployment Type:  all
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by akhenry** [comment]
[Test instructions](https://github.com/nasa/openmct/pull/7493#issuecomment-1997866650)

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon 3/14/24

looks... _quite_ nice
