### ISSUE TITLE
[Recent Objects] Add a collapse button to Recents

### ISSUE THREAD

**Issue by rukmini-bose** [nasa/openmct#7491]
#### Summary

Recent Objects needs a horizontal collapse bar, similar to what we have for the Object Tree and Inspector. This will give us the ability to collapse and hide Recent Objects if it is not needed by a a user. Additionally, a collapse button will help with our mobile user experience improvements. That mobile issue can be found here: https://github.com/nasa/openmct/issues/7318

Currently, the only capability we have is the ability to drag to resize Recents on Desktop. What we want is the ability for a "minimize" button next to the Recent Objects header. Clicking this will automatically drop the vertical height of the pane. This is a quick example of what we want:
<img width="387" alt="Screenshot 2024-02-08 at 4 49 58 PM" src="https://github.com/nasa/openmct/assets/48999852/e878c5e5-ae3e-48be-a108-451e37874c68"> <img width="336" alt="Screenshot 2024-02-08 at 4 50 09 PM" src="https://github.com/nasa/openmct/assets/48999852/11f693bb-8943-4dcc-8da5-ef6e9b4f7d98">

For more information on design and behavior, talk to @rukmini-bose. 
#### Steps to Reproduce

1.
2.
3.
4.

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by unlikelyzero** [comment]
@rukmini-bose when implementing this, you'll need to make this title and aria-label distinct from the other collapse buttons for inspector and tree

**Comment by rukmini-bose** [comment]
Testing Instructions: 

1. Open the Object Tree and verify that Recent Objects is open by default. 
2. Check that a new collapse button has been added to the Recent Objects. The button looks the same as the collapse pane buttons that are used for the Object Tree and Inspector
3. Click the button and verfiy that the Recent Objects pane collapses down vertically to become a very small pane, in which only " + Recently Viewed" is visible. 
4. Click the collapsed pane, and verify that the Recent Objects pane expands upwards again. 
5. Resize the Recent Objects pane vertically, and then repeat steps 3 and 4 and make sure that the pane retains the same height as before.

**Comment by ozyx** [comment]
Verified -- Testathon 3/5/24

Fantastic work.
