### ISSUE TITLE
Operator status indicator should check for role when receiving status

### ISSUE THREAD

**Issue by scottbell** [nasa/openmct#7508]
#### Summary

When the operator status indicator receives status updates, [it's not checking](https://github.com/nasa/openmct/blob/master/src/plugins/operatorStatus/operatorStatus/OperatorStatus.vue#L144) to see if the role matches the user's current role.

#### Expected vs Current Behavior

It should only change the status indicator based on the user's current role.

#### Steps to Reproduce

1. Ensure multiple roles are available on the system
2. Login with one of the roles
3. Change the operator status using the indicator
4. Reload the page
5. Note the indicator will correctly show the status at first, but then change it to the wrong status as new telemetry arrives (and the role isn't checked)

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information

https://github.com/nasa/openmct/assets/9853862/11ba4004-b5ca-4b90-8344-e5fb6425ae60

**Comment by ozyx** [comment]
Verified Testathon 3/20/24
