### ISSUE TITLE
Open in new tab has stopped working.

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#7524]
#### Summary
The "open in new tab" action from the context menu in display layouts has stopped working for some reason. It shows an error in the JavaScript console

#### Steps to Reproduce
1. Open (or create) a display layout containing a LAD table
2. Click on the context menu (three-dot menu) in the LAD table and select "Open In New Tab"
3. Observe that nothing happens and there is an error in the console

#### Environment
* Open MCT Version: 5f8d6899d229ffd8b466d8fca02c00bf67cbad3c
* Deployment Type: testathon

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information

```
Uncaught TypeError: Cannot convert object to primitive value
    at paramsToArray (url.js:51:29)
    at objectPathToUrl (url.js:72:1)
    at OpenInNewTab.invoke (openInNewTabAction.js:35:30)
    at action.onItemClicked (MenuAPI.js:81:1)
    at callWithErrorHandling (runtime-core.esm-bundler.js:192:1)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:199:1)
    at HTMLLIElement.invoker (runtime-dom.esm-bundler.js:681:31)
    ```

**Comment by ozyx** [comment]
# Testing Instructions

## Scenario 1
- Open (or create) a display layout containing a LAD table
- Click on the context menu (three-dot menu) in the LAD table and select "Open In New Tab"
- Verify that the new tab opens to the LAD table and the url params look sane

## Scenario 2
- Create a display layout containing an Overlay Plot with some live telemetry in it
- Save it
- Click on the context menu (three-dot menu) in the Overlay Plot and select "Open In New Tab"
- Verify that the new tab opens to the Overlay Plot object and the url params look sane
- Navigate back to the display layout containing the plot
- Activate the Independent Time Conductor on the Overlay Plot
- Set it to "Fixed time" and change the time bounds to something else
- Click on the context menu and open it in a new tab
- Verify that the Overlay Plot in the new tab has the ITC activated with the same mode and bounds
- Verify that the global time conductor has the same mode and bounds as the previous page
- Repeat the same steps for realtime mode

**Comment by jvigliotta** [comment]
Verified Fixed - Testathhon 3/13/24

**Comment by rukmini-bose** [comment]
Verified Testathon 3/13/2024
