### ISSUE TITLE
[Overlay Plots] Removing 1 Object from the Elements Pool Removes 2 from the Legend

### ISSUE THREAD

**Issue by rukmini-bose** [nasa/openmct#7527]
#### Summary

In an Overlay Plot, removing an object from the elements pool is removing two objects from the legend. The two are being removed are the selected object and another random one. Sometimes, refreshing can bring the legend back to the correct state. 

Look at this image which was taken after removing an element. There are 7 elements in the legend, while there are 8 in the elements pool.
<img width="1223" alt="Screenshot 2024-02-27 at 2 42 18 PM" src="https://github.com/nasa/openmct/assets/48999852/af29f656-08a8-4530-8461-372fb5366e8f">

#### Expected vs Current Behavior

When you remove an object from the Elements Pool, we should see **only** that object being removed from the plot and the legend. 
#### Steps to Reproduce

1. Navigate to an Overlay Plot that is populated with multiple data points.
2. Count the number of elements in the plot. 
3. Go to Edit, and remove an object from the Elements Pool. 
4. Now go to the legend, and count the number of elements that are in it. 
5. Observe that there are 2 less elements in there, instead of 1. 

#### Environment

* Open MCT Version:   4.0.0-next
* Deployment Type:  testathon
* OS:
* Browser: Chrome

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment]
introduced in #7453

**Comment by ozyx** [comment]
# Testing Instructions
- Follow steps to reproduce
- Verify that removing 1 plot element from the tree context menu removes 1 legend item
- Verify that removing 1 plot element from the elements pool context menu removes 1 legend item

**Comment by rukmini-bose** [comment]
Verified Testathon 3/5/2024 YIPPEE

**Comment by jvigliotta** [comment]
Verified Testathon 3/5/2024 BOOM
