### ISSUE TITLE
[Overlay Plot] Deleting an element via Remove Action breaks the Legend

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#7530]
#### Summary

When removing an element in an Overlay Plot via the remove action and saving, errors are continually thrown when hovering over the plot (until refresh or nav away/back)

#### Expected vs Current Behavior

There should be no errors. The element should be removed from the plot and the legend should reflect that accurately. Highlights should still work.

#### Steps to Reproduce

1. Create an Overlay Plot with multiple SWGs in it
2. Save
3. Edit
4. Click on "Elements" tab to access the Elements Pool
5. Right click on an element, "Remove"
6. Save
7. Hover over the plot
8. Notice many errors in the console

#### Environment

* Open MCT Version:  4.0.0-next
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment]
# Testing Instructions
- Follow steps to reproduce
- Verify no errors in the console and the plot continues to function

**Comment by rukmini-bose** [comment]
Verified Testathon 3/5/2024, removing elements works beautifully again

**Comment by jvigliotta** [comment]
Verified Testathon 3/5/2024, nice!

**Comment by charlesh88** [comment]
Testathon 2024-03-05 verified fixed.
