### ISSUE TITLE
Large view from flexible layout panel leads to blurry charts and nonworking buttons

### ISSUE THREAD

**Issue by inad9300** [nasa/openmct#7535]
#### Summary
When going into "Large View" mode in a chart, particularly from a panel within a flexible layout, the plotted graph lacks sharpness, as well as the ability to interact with it by hovering over individual points, zooming in with the mouse or the buttons, panning, etc. When trying to perform these actions, the graph stays frozen in its blurry state, it never gets redrawn from its original form.

#### Steps to Reproduce
1. Create a new flexible layout
2. Assign telemetry to the two panels presented by default
3. Maximize either of them by clicking "Large View"
4. Observe the blurriness in the chart
5. Rub your eyes to make sure it isn't an artifact of your vision system :upside_down_face: 

#### Environment
* Open MCT Version: 3.2.0, Feb 23 2024 (4c2b59d4a1c47f6d018e2f6499154b9479d506f0)
* Deployment Type: `npm run build:prod`
* OS: Ubuntu 22.04
* Browser: Chrome

#### Impact Check List
- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information

An example:

![blurry-open-mct-chart](https://github.com/nasa/openmct/assets/3440331/24ac0ed2-8c56-4238-9181-6c63d397e0b1)

**Comment by ozyx** [comment]
@inad9300 Thanks for reporting this. I was able to reproduce the issue on v3.2.1, but not on 86e636cbcecbd56d8c93c0d09546379feb0e2e5b, so this will be fixed in the next release (which should be released by the end of this month). Once I identify the commit that fixed the issue, I'll follow up in this thread so you can build your own from source for the meantime,  if needed.

**Comment by ozyx** [comment]
Verified fixed -- Testathon 3/5/24

Looks good!
