### ISSUE TITLE
Annotating image notebook snapshots is broken

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#7552]
#### Summary

Opening an image snapshot and annotating it causes Open MCT to crash.

#### Expected vs Current Behavior

Should be able to annotate image snapshots without failure

#### Steps to Reproduce

1. Create Example Imagery
2. Open an Image
3. Select Snapshot > Create a Notebook Snapshot
4. Open the Snapshots menu from the Snapshot indicator
5. Click the Image
6. In the context menu, click "annotate"
7. No image, errors in console

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment]
# Testing Instructions

- Try taking snapshots of various objects and annotating them
- Verify no errors in console and that annotating works, persists correctly, exports, etc

**Comment by rukmini-bose** [comment]
Testathon 3/14/2024, Cannot test with Example Imagery due to CORS issue

**Comment by rukmini-bose** [comment]
Testathon 3/19/2024– annotations _work_ but there's a separate issue of where Snapshots are not capturing certain objects properly. I'll file and link a new issue for this.
