### ISSUE TITLE
[CSS] Inspector can no longer be scrolled vertically if contents overflow

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#7566]
#### Summary

If the contents of the inspector pane overflow, no scrollbar appears.

#### Expected vs Current Behavior

There should be a scrollbar and users should be able to scroll the inspector contents vertically.

This regression appeared as a result of the changes in [this PR](https://github.com/nasa/openmct/pull/7037), particularly [this line](https://github.com/nasa/openmct/pull/7037/files#diff-ca6747d028b62f8be91ca939d106868ac53eca6f66f2d449e45e287650d1d5d0R96).

#### Steps to Reproduce

1. Open inspector
2. Shrink window vertically until it inspector contents overflow
3. No scrollbar
4. No scrolling :(

#### Environment

* Open MCT Version: 4.0.0-next
* Deployment Type: local
* OS: MacOS
* Browser: Chrome

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available? (yes, depending on how tall your monitor is, I suppose?)
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by davetsay** [comment]
Testing instructions
1. Navigate to an object
2. Make sure there is content in the inspector
3. Click the properties tab if no or limited content in inspector
4. Shrink the window vertically so that the inspector content overflows
5. Scroll the content vertically and it see that the content scrolls

**Comment by rukmini-bose** [comment]
Verified Testathon 3/14/2024. Contents are vertically scrolling in the inspector~
