### ISSUE TITLE
[Tables] No maximum table size currently enforced

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#757]
Table sizes will only be limited by Number.MAX_SIZE, which allows for very large tables. In realtime tables integer overflow will result in undefined behaviour.

**Comment by akhenry** [comment]
@larkin What's a sensible maximum size for VISTA? The table is optimized for a large number of rows, so we need not limit ourselves unnecessarily here. 

I'll do some testing with various limits and see where performance starts to become an issue.

**Comment by larkin** [comment]
I think 10k or 100k rows for a realtime table is good enough. Even better... Expose as a option on the view.

**Comment by akhenry** [comment]
And historical tables? Wasn't intending to limit them differently.

**Comment by larkin** [comment]
no limit for historical tables: their limit is bounded by the query.  They don't have the capability to expand without limit, which is the only reason the rt table needs a limit.  (At limit, it must discard the oldest row, which will require a method for removing a row at a specific index).

**Comment by akhenry** [comment]
@larkin re: RT, yep, that's how I've implemented it. 

re: historical, they can't grow without limit, but they can be arbitrarily large. With realtime, performance will become an issue before integer overflow does. Likewise, historical tables will run into performance limitations with very large arrays. That said, handling arbitrarily large arrays has implications beyond just tables, although there could be performance constraints unique to tables such as sorting, filtering etc. Think we should leave this until we see performance issues in the wild though.

**Comment by larkin** [comment]
@akhenry I agree, I don't imagine we'll see any issues in the wild but we'll have to see.
