### ISSUE TITLE
Plan names not updating automatically when the plan is updated in Couch

### ISSUE THREAD

**Issue by scottbell** [nasa/openmct#7586]
#### Summary

When an update was pushed to an existing plan that changes the plan's name, the name did not automatically updated in Open MCT.

#### Expected vs Current Behavior

The plan name should update in Open MCT when changed in Couch.

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by scottbell** [comment]
@akhenry I'm having difficulty reproducing this locally:

https://github.com/nasa/openmct/assets/9853862/281d04a4-5b21-49e1-a2aa-1bfb15e3477d

Do you have more details on the issue here? I've changed both the title of the plan, and activity names, and they both appear in the plan post page refresh. Or was the idea to add notebook-like hooks into the couchdb change stream?

**Comment by scottbell** [comment]
Per @shefalijoshi this should be using couch SSE to get streamed feeds. Will investigate.

**Comment by scottbell** [comment]
Closing for the time being as won't fix.

**Comment by akhenry** [comment]
This is part of a wider issue with remote object synchronization which is not supported yet. The need for the specific use case captured here is no longer relevant.
