### ISSUE TITLE
Resizing the window causes Plan activities to stay fixed

### ISSUE THREAD

**Issue by scottbell** [nasa/openmct#7587]
#### Summary

Resizing the window causes Plan activities to stay fixed by the vertical NOW line to resize.

#### Expected vs Current Behavior

UTC Time and vertical NOW lines should stay properly aligned on resize.

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by scottbell** [comment]
To test:
1. Create a PlanView with a plan (e.g., using the [plan generator](https://github.com/ozyx/openmct-plan-generator))
2. Resize the browser
3. Ensure Time Axis expands/contracts properly like so:

https://github.com/nasa/openmct/assets/9853862/e2f99fb6-2fb9-4e62-b52f-3cd8081348fc

**Comment by shefalijoshi** [comment]
Verified Fixed
