### ISSUE TITLE
Time Conductor calendar popup appears cut off

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#7594]
#### Summary
The time conductor calendar appears to be rendering too far to the left of the conductor itself, causing it to appear truncated. See screenshot
![Screenshot 2024-03-15 at 8 23 02 AM](https://github.com/nasa/openmct/assets/4215777/ce8ff95b-94a0-4ebb-920b-a1d2d8b000b8)

#### Steps to Reproduce
1. Put time conductor in fix time mode
2. Click on the calendar icon next to the start bounds input
3. Observe that the calendar popup appears offset to the left of the screen

#### Environment
* Open MCT Version: 4.0.0-next
* Deployment Type: Testathon, mini-sim

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by rukmini-bose** [comment]
Testing Instructions: 
1. Navigate to Open MCT and resize your window pane so it's pretty small. 
2. Change the TC to Fixed Time and click on the calendar that changes the start time. 
3. Verify that the Calendar opens to the right and is NOT being cut off. 
4. Click on the calendar that changes the end time. 
5. Verify that the Calendar opens up to the left and is NOT being cut off. 
6. Now navigate to an Open MCT object that has an Independent Time Conductor (Plot, Time List, etc).
7. Repeat steps 2 and 3 and verify that the calendar opens downwards and left/right in a way that the calendar is not being cut off.

**Comment by akhenry** [comment]
Verified fixed, nice work
