### ISSUE TITLE
Require/import of `openmct` doesn't work as expected

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#7602]
#### Summary

see https://github.com/nasa/openmct/pull/7590 for details

**Comment by unlikelyzero** [comment]
ReferenceError: window is not defined
    at /Users/jchill9/new-npm-project/node_modules/openmct/dist/openmct.js:2:3035939
    at /Users/jchill9/new-npm-project/node_modules/openmct/dist/openmct.js:2:4410073
    at /Users/jchill9/new-npm-project/node_modules/openmct/dist/openmct.js:2:4410087
    at /Users/jchill9/new-npm-project/node_modules/openmct/dist/openmct.js:2:81
    at Object.<anonymous> (/Users/jchill9/new-npm-project/node_modules/openmct/dist/openmct.js:2:195)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)

Node.js v20.12.2

**Comment by ozyx** [comment]
> ReferenceError: window is not defined at /Users/jchill9/new-npm-project/node_modules/openmct/dist/openmct.js:2:3035939 at /Users/jchill9/new-npm-project/node_modules/openmct/dist/openmct.js:2:4410073 at /Users/jchill9/new-npm-project/node_modules/openmct/dist/openmct.js:2:4410087 at /Users/jchill9/new-npm-project/node_modules/openmct/dist/openmct.js:2:81 at Object. (/Users/jchill9/new-npm-project/node_modules/openmct/dist/openmct.js:2:195) at Module._compile (node:internal/modules/cjs/loader:1369:14) at Module._extensions..js (node:internal/modules/cjs/loader:1427:10) at Module.load (node:internal/modules/cjs/loader:1206:32) at Module._load (node:internal/modules/cjs/loader:1022:12) at Module.require (node:internal/modules/cjs/loader:1231:19)
> 
> Node.js v20.12.2

i think my testing instructions are bad or misinformed. at present i think this is correct-- openmct cannot be run in a purely node context as it relies on the `window`.

**Comment by unlikelyzero** [comment]
I think this is verified by virtue of nirvss and diy working
