### ISSUE TITLE
Import from JSON is extremely slow with large imports

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#7612]
#### Summary
Importing very large JSON files (on the order of megabytes) is extremely slow. This would be less of an issue if Open MCT gave the user some feedback that it was doing something, but it doesn't.

#### Expected vs Current Behavior
Import from JSON has some inefficiencies which could be improved to speed up the import process. The user should be informed that an import is in progress.

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [x] Does this have an impact on Performance?

**Comment by akhenry** [comment]
Assigning severity of critical. This issue significantly impairs the usage of this functionality, and functionally blocks it for large imports.

**Comment by scottbell** [comment]
To test:
1. Use the attached [Big Test Folder (2).json.zip](https://github.com/nasa/openmct/files/14805898/Big.Test.Folder.2.json.zip) to initiate an import.
2. Ensure the import finishes in a timely manner and the progress bar appears
3. Create your own folder, with nested objects and folders. Export it.
4. Ensure that import works properly too.

**Comment by davetsay** [comment]
verified

**Comment by ozyx** [comment]
Verified
