### ISSUE TITLE
Import from JSON action does not work in anything other than the default namespace

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#7617]
#### Summary
Marking as blocker as it blocks an important downstream workflow for viper ops, with no workaround.

#### Steps to Reproduce
1. Configure Open MCT for multiple couch databases, [per the instructions on this ticket](https://github.com/nasa/openmct/issues/7359#issuecomment-1909750435)
2. Export a folder from the default namespace to JSON
3. Import the resulting file into the second database
4. Observe that a missing object appears in the second database
5. Refresh the browser, and observe that the objects initially appear in the second database
6. Click on one of the objects in the second database
7. Observe that Open MCT reports the object as missing.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by scottbell** [comment]
Just a note as a workaround, there is this script in this PR too:
https://github.com/nasa/openmct/pull/7501

**Comment by scottbell** [comment]
I'm having trouble replicating this using the instruction provided:

https://github.com/nasa/openmct/assets/9853862/bf0e41c2-53fd-466b-ba43-22fd300d2f87

Perhaps the JSON exported had a default namespace? I'll give that a go and see if I see the issue.

**Comment by scottbell** [comment]
I do get an error if I:
1. Export a folder from a default namespace
2. Import that folder where the default namespace does not exist

Here's the error:
```
ImportFromJSONAction.js:212 Uncaught (in promise) Object provider does not support saving
_importObjectTree @ ImportFromJSONAction.js:212
await in _importObjectTree (async)
onSave @ ImportFromJSONAction.js:77
eval @ ImportFromJSONAction.js:274
Promise.then (async)
_showForm @ ImportFromJSONAction.js:272
invoke @ ImportFromJSONAction.js:64
action.onItemClicked @ MenuAPI.js:81
callWithErrorHandling @ runtime-core.esm-bundler.js:192
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:199
invoker @ runtime-dom.esm-bundler.js:681
```

The `ImportFromJSONAction` should be using the namespace it's been asked to import to, not the default. I'll see about fixing this.

**Comment by scottbell** [comment]
To test:
2. Setup OpenMCT to use the [default empty string namespace setup for CouchDB](https://github.com/nasa/openmct/blob/master/src/plugins/persistence/couch/README.md#manual-configuration-1).
3. Inside of a folder, make a bunch of objects and subfolders
4. Dump this folder to JSON using the Export JSON action.
5. Configure Open MCT for [multiple couch databases](https://github.com/nasa/openmct/issues/7359#issuecomment-1909750435)
6. Use the Import JSON action to import
7. Ensure objects load, there are no errors, and everything looks good.

**Comment by akhenry** [comment]
verified fixed.
