### ISSUE TITLE
Create automated test for import from JSON into non-default database.

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#7621]
#### Summary

We need an automated test to catch regressions in the recent change to the ImportFromJSONAction to make sure we can catch regressions in this action.

Although the original bug manifested while testing multiple Couch databases, a test that operates on a single database with a non-default namespace and imports data from a different namespace would be a sufficient test.

**Comment by shefalijoshi** [comment]
This needs some testing notes. @scottbell

**Comment by scottbell** [comment]
@shefalijoshi this ticket is just to add a test. I'm not sure what manual testing would be done here...
