### ISSUE TITLE
Time Conductor Axis does not resize correctly in certain scenario

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#7623]
This is fixed for the plan and gantt chart views.
However, there is some issue with the time conductor axis. If you load Open MCT with a small window size and switch to Fixed timespan mode, then made the window bigger (horizontally), the times in the axis don't update properly:
<img width="1123" alt="image" src="https://github.com/nasa/openmct/assets/5247066/384d61b0-5a1c-4d95-878d-0f426a2a082c">

_Originally posted by @shefalijoshi in https://github.com/nasa/openmct/issues/7587#issuecomment-2008187543_

**Comment by rukmini-bose** [comment]
Verified Fixed 3/27/2024

**Comment by ozyx** [comment]
# Testing Notes

1. Start Open MCT (or navigate to testing environment)
2. Switch to realtime clock if not already realtime
3. Make the window small and refresh
4. Switch to fixed mode
5. Make the window wider
6. Ensure that the timeconductor resizes appropriately

**Comment by davetsay** [comment]
not verified. i see this when expanding
Screenshot 2024-03-27 at 2.40.28 PM

**Comment by rukmini-bose** [comment]
Verified Fixed 3/27/2024
