### ISSUE TITLE
[Telemetry Tables] Telemetry mode changes break on objects that are unable to be persisted

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#7625]
#### Summary

When an object is unable to be persisted, changing telemetry modes (limited, unlimited) will break. 

#### Steps to Reproduce

1. view an object that is unable to be persisted, in a table
2. try to switch telemetry modes
3. notice a mutation error in the console and the mode does not switch

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment]
# Testing Instructions

- view an object that is unable to be persisted, in a table (events or commands)
- try to switch telemetry modes (unlimited / limited)
- verify no mutation error in the console and the mode switches

**Comment by ozyx** [comment]
Testathon 4/4/24 - Verif👁️'d fixed. Switching telemetry modes on the "Events" immutable object works perfectly and produces no errors. Navving away and back resets the telemetry mode on the table to the default. 👍

**Comment by charlesh88** [comment]
Testathon 2024-04-04 verified fixed.
