### ISSUE TITLE
Getting ConditionSet historical telemetry fails

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#7631]
#### Summary

```
TelemetryCollection.js:548 Uncaught (in promise) Error: TypeError: Promise.all(...).forEach is not a function
    at af._error (TelemetryCollection.js:548:11)
    at af._requestHistoricalTelemetry (TelemetryCollection.js:161:14)
 ```

#### Expected vs Current Behavior

Historical telemetry for Conditions should be received but its not.

#### Steps to Reproduce

1. Ensure realtime mode
2. Create a Condition Set
3. Add some telemetry to it
4. Add some conditions
5. Save
6. Create a display layout
7. Drag the condition set into it
8. errors in the console
9. No historical data shows for condition set
10. Let it run for a bit to build up realtime data then reload the browser
11. notice no historical data

#### Environment

* Open MCT Version:  e305b46d88854b604ad44ec8e8b69b5102c89265
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment]
# Testing Instructions

1. Create a Condition Set
2. Add some telemetry to it
3. Add some conditions
4. Save
5. Create a display layout
6. Drag the condition set into it
7. Save, verify no errors in console
8. Reload the page
9. Verify condition set value shows correctly
10. Edit the layout, change the type of view for the condition set to a plot
11. Verify the plot gets historical and realtime data
12. Repeat step 8,9,11
13. Repeat step 10 but change type to a table
14. Verify table gets historical and realtime data
15. Repeat step 8,9,14

**Comment by davetsay** [comment]
@ozyx, i don't think condition sets work historically in this context yet. You can look at what a condition evaluates to at a point in history, but that evaluation may be different depending on the amount of telemetry inputted, ie. time frame before the condition evaluation takes place. The way they work now is they look at the latest data available and re-calculate on each incoming datum.

**Comment by davetsay** [comment]
but. this is fixed in that condition sets can now be inside of plots and tables and not break.

fix is verified.
