### ISSUE TITLE
Nested Flexible Layouts don't display properly

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#7635]
#### Summary
A Flexible Layout (FL) that uses a column layout displays its elements like this:
![Screenshot 2024-03-21 at 11 53 29 AM](https://github.com/nasa/openmct/assets/1056412/d03b4bda-2e69-41ff-9d81-2d39943dae85)

but, when placed in a FL that uses a rows layout displays incorrectly:
![Screenshot 2024-03-21 at 11 54 24 AM](https://github.com/nasa/openmct/assets/1056412/d0d43c6a-b463-4079-884c-330ecf8b26e1)

The problem is that outer FL's `flex-direction` is affecting the inner's, but shouldn't.

#### Steps to Reproduce

1. Create a Flexible Layout (FL) using a columns layout. Put two objects inside the same column, and note which object is above the other. Save and exit editing.
2. Create another FL using a rows layout. Drag the DL from step 1 into a row of this layout.
3. Observe: the objects in the step 1 layout will now be side-by-side, but should be above and below each other.

#### Environment

* Open MCT Version:  4.0.0-next
* Deployment Type:  any
* OS: all
* Browser: legion

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by charlesh88** [comment]
### Testing Notes
Import the attached folder with included Flexible Layouts and resources: [Issue 7635 debugging cols rows cols.json](https://github.com/nasa/openmct/files/14711877/Issue.7635.debugging.cols.rows.cols.json)

1. View the included Flexible Layout (FL) named "FL 3 Columns". Verify that it looks like this ref image:
![Screenshot 2024-03-21 at 3 17 07 PM](https://github.com/nasa/openmct/assets/1056412/5ff0e5c0-568b-4bbc-806f-3b40b12e2297)
1. Edit FL 3 Columns, and hover the layout direction in the toolbar (first button). Verify that it is displaying the "rows" icon, and a tooltip that reads "Switch to rows layout":
![image](https://github.com/nasa/openmct/assets/1056412/d4e9dbab-ab79-4289-ab1b-ce58505e3c9f)
1. Click the layout direction button to switch to rows layout. Verify that the FL is now in "rows" layout direction with the green "Empty DL" in the first row.
2. Save and exit edit mode.
3. Verify that the FL 3 now looks like this ref image, and especially:
  - That the layouts of FL 4 and FL 5 have not changed their layout direction: the green "Empty DL" should be at the bottom of DL 4, and to the right in FL 5. They will change width and height due to the change to FL3; this is expected and is correct.
  - The Gauge should always be above the SWG in FL 5.
![Screenshot 2024-03-21 at 3 18 22 PM](https://github.com/nasa/openmct/assets/1056412/08fcfa2e-d602-4c11-85bf-398f99ae94b5)
4. View FL 4 and FL 5 and verify that they retain their respective layout directions in the main view.

For bonus points: 
- Switch layout direction in FL 4 and FL 5 and verify that when viewing either in a containing context (FL 3 and FL 4 respectively) that their layout directions are as expected.

**Comment by rukmini-bose** [comment]
Verified Testathon 4/25/2024 yippeeeee

**Comment by charlesh88** [comment]
Testathon 2024-04-25 verified fixed.
