### ISSUE TITLE
Telemetry tables are not requesting the correct sort order for limited mode

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#7636]
#### Summary
In descending mode limited the x rows, the earliest x rows are being returned from the historical request.

#### Expected vs Current Behavior
When sorted descending and limiting to x rows, I would expect the x rows requested to be the latest. Instead I am getting the earliest in the time range.

#### Workaround
1. Use unlimited mode

#### Steps to Reproduce

1. Navigate to a telemetry table that has telemetry
3. Ensure it is in limited mode (toggle at bottom right of telemetry table)
4. Set time conductor to a large range (1 hr or more)
5. Hover mouse over pause button
6. Refresh the browser
7. Pause as soon as telemetry request is finished (pretty much when pause button becomes visible)
8. Observe the timestamps for the data is from the beginning of the time range, not the end

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by jvigliotta** [comment]
## Testing
- Follow the repro steps, make sure that the results that come in do not have a large gap
- make sure the request that goes out has `order=desc` url param

**Comment by rukmini-bose** [comment]
Verified Testathon 4/2/2024
