### ISSUE TITLE
Reloading View in Preview breakes View Large in Display Layouts

### ISSUE THREAD

**Issue by scottbell** [nasa/openmct#7638]
#### Summary

A reloading of an enlarged View in Display Layouts causes the element to be invalidated, and prevents a second Preview. Reloading the View again in a Display Layout resolves the issue, and is a workaround.

Here's the error:
```js
runtime-core.esm-bundler.js:254 Uncaught Error: ViewLargeAction: missing element
    at ViewLargeAction.invoke (viewLargeAction.js:48:1)
    at action.onItemClicked (MenuAPI.js:81:1)
    at callWithErrorHandling (runtime-core.esm-bundler.js:192:1)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:199:1)
    at HTMLButtonElement.invoker (runtime-dom.esm-bundler.js:681:31)
```

#### Expected vs Current Behavior

It shouldn't throw an error and instead should run "View Large" as normal.

#### Steps to Reproduce

https://github.com/nasa/openmct/assets/9853862/fcacbc9d-fbe7-4aa0-807e-2d676bb3c63c

1. Create a display layout with a sine wave generator in graph form
2. Use the View Large action to embiggen it
3. Reload the View in Preview mode
4. Close Preview
5. Return to Display Layout, and attempt to run View Large again, note the error
6. Note also a subsequent Reload allows View Large again.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by scottbell** [comment]
To test:
1. Create a display layout with a sine wave generator in graph form
2. Use the View Large action to embiggen it
3. Ensure Reload action is missing.

**Comment by rukmini-bose** [comment]
Testathon 3/27/2024 NOT verified. The action menu under the "View Large" still has the "reload" option in it.
<img width="1637" alt="Screenshot 2024-03-27 at 2 34 25 PM" src="https://github.com/nasa/openmct/assets/48999852/a54ec96f-ba81-432e-b66c-9813a18d19b9">

**Comment by davetsay** [comment]
not verified. 3-dot menu of view large still has reload. upon reloading and closing, view large throws error

**Comment by scottbell** [comment]
FWIW, I just tested this again locally on `master` and it worked for me:

https://github.com/nasa/openmct/assets/9853862/c8c84b71-2704-44ff-aa05-1611c8441126

**Comment by unlikelyzero** [comment]
@scottbell  we had a bad merge on testathon. Will retest. Go to sleep 💤

**Comment by rukmini-bose** [comment]
Verified Testathon 3.27/2024 locally and testathon. We're good scott :) 💤 😴
