### ISSUE TITLE
Timelines fail to save

### ISSUE THREAD

**Issue by RCarvalhoNASA** [nasa/openmct#764]
Created a timeline, put an activity in it from the tree, then went to edit the timeline.  Created more activities, hit save, and only the tree activity was there.  Went to edit the timeline again, and created 2 activities, one persisted, the other did not.

**Comment by RCarvalhoNASA** [comment]
Testathon 20160317

**Comment by VWoeltjen** [comment]
Duplicated by #770 (which is addressed, pending verification)
