### ISSUE TITLE
Couch persistence plugin should use Object API `model.created` standard rather than `metadata.created`

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#7655]
#### Summary

* Object API already has `created` attribute
* `metadata.created` was never used for anything meaningful
* `metadata.created` is ephemeral and gets removed on any non-creation update

**Comment by davetsay** [comment]
Testing Instructions: see VIPEROMCT-513

**Comment by akhenry** [comment]
Verified Fixed!
