### ISSUE TITLE
Code coverage for e2e tests is busted

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#7657]
#### Summary

We had a 6% drop in codecoverage since the ESM/import/require fixes. This is caused by the splitting off of the openmct-e2e framework into its own workspace, since the path in which `.nyc_output` is generated has changed and no longer matches up with our generated sourcemaps

**Comment by ozyx** [comment]
# Testing Instructions

Go to codecov and look at the latest commit on master (this can be reached by clicking on the "codecov" banner on the readme page). verify that the `e2e`, `e2e-stable`, etc. flags have coverage data uploaded.

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon 4/16/2024
e2e-full, e2e-stable and unit all have coverage, which is what we are looking for
