### ISSUE TITLE
Telemetry Tables scroll sort should mirror that of order sort

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#7669]
#### Summary
On first navigation to a telemetry table sorted descending, before any manual scrolling, the table should scroll to the last of the data set (top of the table).

Observations
* on navigation to a table view this doesn't seem to work at all
* on refresh, not navigation, of a persistable table object this seems to work. 
* (i suspect) if any realtime data comes in before the historical request is fully received and handled, the scroll goes to the latest of the historical request (somewhere in the middle of the table)

#### Expected vs Current Behavior
If I am navigating to a table view that is sorting, say timestamps, descending, then I expect the scroll to start at the latest timestamp (top of table). This isn't consistent.

#### Steps to Reproduce

Testing a telemetry view for a non-persistable object
1. navigate to a telemetry object
2. switch to table view if not already (which should automatically be sorted by timestamp descending)
3. observe scroll goes to earlier telemetry row when it should go to latest
4. refresh the page
5. observe scroll goes to earlier telemetry row when it should go to latest

Testing a telemetry view for a persistable object
1. create a table object, drag the original telemetry from the previous test, and save
2. repeat steps from previous test but observing scroll sort seems to work after a page refresh

Testing high-frequency data in table views
1. navigate to a table view for a telemetry object with high frequency (which should automatically be sorted by timestamp descending)
2. observe a few rows populate the top of the table (presumably realtime data), then a bunch more fill the table (presumably historical request) and then the table scrolls to near the top but not quite the top of the table

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by jvigliotta** [comment]
## Testing
- follow the repro steps on this issue

**Comment by charlesh88** [comment]
Testathon 2024-05-09 verified fixed.
