### ISSUE TITLE
Staleness indication inconsistency misapplied to layouts based on navigation.

### ISSUE THREAD

**Issue by jtrack3d** [nasa/openmct#7670]
#### Summary
The display gets confused when to show / not show staleness indicator after visiting stale providing object in navigation.

I theorize that pub/sub isn't un-subbing somewhere.

#### Expected vs Current Behavior
If you are on a Display layout where one object/component goes stale, only that component indicates staleness.  What I'd expect.

But, if you visit that object directly on the browse navigation (outside a display layout), there after, the staleness affect not only appears on the object/component but the whole display layout whether the object/component is part of the display layout or not.  If it is part of the layout, the layout is stale and the subcomponent is stale as well.  This seems incorrect. 

#### Steps to Reproduce
1. Create a Sine Wave Generator (Example) and enable Staleness Updates.
2. Create a "Display Layout", you can leave it empty.
3. Click Sine Wave Generator from Navigation - Notice the Staleness indicator occurs occasionally.
4. Visit the empty "Display Layout", notice it indicates staleness occasionally, though Sinewave isn't on the display.
5. To compare, visit the display layout, from the browser navigation, drag the sign-wave onto the blank display.
6. Now you have a display that both the object and the display are showing staleness.
7. Save the layout, reload the page... visit only the display layout, notice only the sinewave goes stale.
8. Visit the sine wave generator that is not part of the display, revisit the display and now both display and component go stale.

#### Environment

* Open MCT Version: 3.2.1 (Feb Build)
* Deployment Type: I think it's prod build.
* OS: Windows 10
* Browser: Latest Chrome 123, Latest Firefox 115.

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by unlikelyzero** [comment]
Needs investigation in VIPER

**Comment by unlikelyzero** [comment]
Assigning to @jvigliotta

**Comment by jtrack3d** [comment]
Thank you! :)  I figured it was an unsubscribe issue.
