### ISSUE TITLE
Exported JSON files do not work with StaticRootPlugin

### ISSUE THREAD

**Issue by jllamas** [nasa/openmct#7678]
#### Summary

After setting up some layouts in the My Items section. We then export them as JSON files. Adding those JSON files to a URL and pointing the StaticRootPlugin at them, I get "Missing [Object, Object]" error.

#### Expected vs Current Behavior

I would have expected to see TLM values displayed the same was as they do in the My Items folder.

#### Steps to Reproduce

1. Setup a graph or table in My Items and export it as JSON.
2. I put the JSON file in the OpenMCT directory in new subfolder called JSON
3. Add the StaticRootPlugin with the following config:
```
openmct.install(openmct.plugins.StaticRootPlugin({ namespace: 'LTB', exportUrl: 'JSON/SCLKs.json' }));
```

#### Environment

* Open MCT Version:  2.2.1 3c60b0416f004f213bf5c1642c76b02a35408460
* Deployment Type: NPM Dev and Apache
* OS: Linux 5.14.0-362.24.1.el9_3.x86_64 - Red Hat Enterprise Linux release 9.3
* Browser: Chrome, Safari, Brave, Firefox

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information

Here is whats in my particular JSON export if it helps.
```
{
  "openmct":{
    "596d0e39-5eb8-4ecd-b2e9-146269400295":{
      "identifier":{
        "key":"596d0e39-5eb8-4ecd-b2e9-146269400295","namespace":""
        },
        "name":"SCLKs",
        "type":"telemetry.plot.overlay",
        "composition":[
          {"namespace":"ait-ns","key":"TLM_TLM.AGG_RT_1_TIME_SCLK_S"},
          {"namespace":"ait-ns","key":"TLM_TLM.AGG_RT_LO_TLCM_SCLK_SECONDS"},
          {"namespace":"ait-ns","key":"TLM_TLM.AGG_SM_RT_2_TIME_SCLK_S"},
          {"namespace":"ait-ns","key":"TLM_TLM.TLCM_SCLK_SECONDS"},
          {"namespace":"ait-ns","key":"TLM_TLM.TIME_SCLK_S"}
        ],
        "configuration":{
          "series":[
            {"identifier":{"namespace":"ait-ns","key":"TLM_TLM.AGG_RT_1_TIME_SCLK_S"}},
            {"identifier":{"namespace":"ait-ns","key":"TLM_TLM.AGG_RT_LO_TLCM_SCLK_SECONDS"}},
            {"identifier":{"namespace":"ait-ns","key":"TLM_TLM.AGG_SM_RT_2_TIME_SCLK_S"}},
            {"identifier":{"namespace":"ait-ns","key":"TLM_TLM.TLCM_SCLK_SECONDS"}},
            {"identifier":{"namespace":"ait-ns","key":"TLM_TLM.TIME_SCLK_S"}}
          ]
        },
        "modified":1697574355560,
        "location":"mine",
        "created":1697574355555,
        "persisted":1697574355561
      }
    },
    "rootId":"596d0e39-5eb8-4ecd-b2e9-146269400295"
  }
```

Shows TLM working from the My Items folder
<img width="1404" alt="Screenshot 2024-04-02 at 4 10 27 PM" src="https://github.com/nasa/openmct/assets/38157/ce1175c1-7b0b-4296-8983-af487e26c148">

Shows the error I get trying to use the JSON file from the StaticRootPlugin
<img width="1404" alt="Screenshot 2024-04-02 at 4 14 01 PM" src="https://github.com/nasa/openmct/assets/38157/d4c71dcd-247a-4351-8c78-d7abfed1c5d8">

**Comment by ozyx** [comment]
Hi there! Thank you for reporting this. I believe [this bug was fixed in 2.2.2](https://github.com/nasa/openmct/issues/6584). If you're able to upgrade, could you please give [2.2.2](https://github.com/nasa/openmct/releases/tag/v2.2.2) a shot and let us know if it fixes your issue?

Also, we're interested to know if there's anything blocking you from upgrading to the latest stable release ([3.2.1](https://github.com/nasa/openmct/releases/tag/v3.2.1))?

**Comment by jllamas** [comment]
Awesome! Thanks for the quick response. The only thing holding us back is time, testing , integration. We've spent a lot of time setting up the dashboards in 2.x, are they compatible with 3.x? If so I'll upgrade to 3.x otherwise we'll probably be stuck on 2.x

**Comment by jllamas** [comment]
I've tried upgrading to 3.x and I get an empty page and a pile of errors.

Running 2.2.3 solves my problem.

Thank you!

**Comment by ozyx** [comment]
> I've tried upgrading to 3.x and I get an empty page and a pile of errors.
> 
> Running 2.2.3 solves my problem.
> 
> Thank you!

OK, great!

3.x introduced some big changes re: dependencies and build tooling. Right now we're working on making openmct easier to consume in the next major version. We will also provide migration documentation, so keep an eye out for that.

Cheers,
Jesse
