### ISSUE TITLE
Timeline activity handle mouse icon oddity

### ISSUE THREAD

**Issue by RCarvalhoNASA** [nasa/openmct#768]
Testathon 20160317 While editing a timeline, once I click on an activity, the mouse icon I get while over the middle of the bar in the gantt chart is a 4 way arrow icon, which implies that I can grab the bar and move it up and down as well as sideways.  I can't.  I can move the names of the activities in the table part up and down, but not the bars.  I believe the mouse icon over the bar used to just be a two way arrow (<-->).  I suggest either returning to that or enabling up and down movement.

**Comment by VWoeltjen** [comment]
Verified fixed testathon 2016/05/31; I now see a ↔️-style cursor on hover in this area

**Comment by charlesh88** [comment]
Testathon 20160531
Verified fixed.
