### ISSUE TITLE
Paste frequently does not work in notebook entries

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#7686]
#### Summary
Core Open MCT ticket for VIPEROMCT-474.
Bug introduced by #7115

#### Expected vs Current Behavior
Pasting text should paste the text, not paste it and then immediately remove it.

#### Steps to Reproduce

1. Open a notebook entry
2. Paste from clipboard
3. Repeat paste a couple times
4. Observe if all pastes work or not

#### Environment

* Open MCT Version: 
* Deployment Type: with `couchDB` persistence provider
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available? Repeat paste quickly until your text remains
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by rukmini-bose** [comment]
Verified Testathon 4.16.2024
Tested on Notebooks and Shift Logs and see no problems
