### ISSUE TITLE
Remove all usage of deprecated Time API methods

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#7687]
#### Summary

In #6768 , many methods in the Time API were deprecated and produce warnings when used. However, Open MCT core still uses the deprecated methods. Let's not be hypocrites!

**Comment by ozyx** [comment]
@unlikelyzero I think we should also get this in before we publish 4.0.0

**Comment by ozyx** [comment]
# Testing Notes

- Smoke test:
  - Global Time Conductor in Fixed / Realtime mode
  - Independent Time Conductors in Fixed / Realtime modes
  - Pan/zoom and other time bounds related features

Verify that no warnings appear in the console about deprecated methods and everything works.

**Comment by unlikelyzero** [comment]
'heading' telemetry view
switch to fixed timespan
Synchronize Time conductor

**Comment by rukmini-bose** [comment]
Verified Testathon 4/25/2024. Nada console errors!
