### ISSUE TITLE
[Tables] Sorting in Real-time tables shows incorrect ordering

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#769]
20161703 Testathon

This possibly just affects columns that contain a mix of alpha and numeric values, as purely alpha and purely numeric columns order as expected.

To reproduce
1. Create a new real-time table
2. Drag in bmsio_brief_dat/bmsio_brief_dat.state_of_charge and epsio_bit/epsio_bit.wireless
3. Order by 'value' column
4. Column order will show text and numeric values out of order

**Comment by akhenry** [comment]
``` javascript
> typeof NaN
"number"
```
God dammit Javascript.

**Comment by charlesh88** [comment]
Testathon 041816
Per Andrew, this hasn't been fixed yet. Removing "unverified" label.

**Comment by akhenry** [comment]
Resolved by #822

**Comment by VWoeltjen** [comment]
Verified fixed in testathon 20160509
