### ISSUE TITLE
Condition Sets don't allow removal from their composition

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#7710]
#### Summary
Telemetry end points or Sine Wave Generators added into the composition of a Condition Set as datasources can't be removed: removing the reference via object's Elements pool or via the tree's action menu initially appears to work, but after the remove action, navving away and back or collapsing the containing Condition Set in the tree and re-expanding it will reveal that the item is still there. 

- This occurs with Open MCT from a remote server as well as running locally.
- This only happens when the Condition Set is in the main view. Navving away from the CS and removing via the tree works as expected.
- The Condition Set MUST have at least one condition defined in it - if there's only a default condition, the problem will not manifest.
- No console errors are thrown. 
- At this time, this is not a sporadic problem but appears to be constant. 
- Clearing cache and refreshing does not solve the problem.

Due to the need for users to be able to remove a telemetry parameter mistakenly added to a Condition Set, setting to critical. Without a workaround, this would be a blocker.

**RUKMINI'S COMMENTS:** 
Example of the original issue. This occured on Banner. Note that I am navigated on the Condition Set when trying to remove the element when this issue happened. 
https://github.com/nasa/openmct/assets/48999852/40c387d1-5adc-4503-804e-6dd5bcf87461

Additionally, for one instance, while I was able to successfully remove an element from the Condition Set (there were two elements in the CS, I removed one element), the tree was not updated even upon refreshing.
Look at this image– there's two elements in the Condition Set in the tree, while there is one in the Elements Pool. 

<img width="1572" alt="Screenshot 2024-05-06 at 12 02 39 PM" src="https://github.com/nasa/openmct/assets/48999852/9eb63a21-4cbd-4b9c-a183-2389f3a41f9d">

#### Expected vs Current Behavior
Removing an object from a Condition Set's composition should work the same as it does for other objects with composition: 
- if removing via the tree, remove the object immediately and persist the change. 
- If editing the Condition Set, persist the change on Edit > Save. Removing the object and then cancelling out of edit would not remove the object.

#### Steps to Reproduce

1. Add a telemetry end point or Sine Wave Generator to a Condition Set. Create at least one condition that evaluates values in the included parameters. Save and exit edit mode.
2. Via the tree, expand the Condition Set. Context-click the telemetry end point - choose "Remove" from the action menu. 
4. Observe that the end point appears to be removed. Collapse the Condition Set, then re-expand it. Note that the end point reappears.
5. Edit the Condition Set, go to the Elements tab, and context-click the telemetry end point. Choose "Remove" from the action menu. Save and exit edit mode.
6. Nav away from the Condition Set, then back. Repeat step 4 and note that the telemetry end point is back.

#### Environment

* Open MCT Version:  4.0.0-next
* Deployment Type:  banner, local
* OS: all
* Browser: Chrome

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [x] Does this have an impact on Performance?

**Comment by charlesh88** [comment]
Update, workaround available: nav away such that the Condition Set is not in the main view, then Remove from via the tree.

**Comment by ozyx** [comment]
I can't reproduce this @charlesh88

**Comment by davetsay** [comment]
could not repro in viper rc4

**Comment by rukmini-bose** [comment]
Example of this issue on banner 
https://github.com/nasa/openmct/assets/48999852/fcf78c0b-9f99-4509-9f90-a0540b015938


Additionally, for one instance, while I was able to successfully remove an element from the Condition Set (there were two elements in the CS, I removed one element), the tree was not updated even upon refreshing.
Look at this image– there's two elements in the Condition Set in the tree, while there is one in the Elements Pool. 

<img width="1572" alt="Screenshot 2024-05-06 at 12 02 39 PM" src="https://github.com/nasa/openmct/assets/48999852/9eb63a21-4cbd-4b9c-a183-2389f3a41f9d">

**Comment by rukmini-bose** [comment]
Example of this issue on banner 
https://github.com/nasa/openmct/assets/48999852/b11c8b7b-980a-45bb-b836-b55c83d4e4d7


Additionally, for one instance, while I was able to successfully remove an element from the Condition Set (there were two elements in the CS, I removed one element), the tree was not updated even upon refreshing.
Look at this image– there's two elements in the Condition Set in the tree, while there is one in the Elements Pool. 

<img width="1572" alt="Screenshot 2024-05-06 at 12 02 39 PM" src="https://github.com/nasa/openmct/assets/48999852/9eb63a21-4cbd-4b9c-a183-2389f3a41f9d">

**Comment by charlesh88** [comment]
@unlikelyzero Test of your user id

**Comment by charlesh88** [comment]
Verified fixed Testathon 2024-05-09.

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon 5/9/2024
