### ISSUE TITLE
[Conditional Styling] Visibility option on Conditional Styling is broken

### ISSUE THREAD

**Issue by rukmini-bose** [nasa/openmct#7718]
#### Summary

When you conditionally style widgets or images  in a Display Layout, the option to toggle the visibility is broken. 

https://github.com/nasa/openmct/assets/48999852/7848fd86-2090-4206-ab60-aefa26ba2b27

#### Expected vs Current Behavior

The eye toggle in Conditional Styles allows for images to appear or disappear based on the condition. 

#### Steps to Reproduce

1. Download this JSON file that includes an example of the bug. [DL .json](https://github.com/nasa/openmct/files/15242291/DL.json)
2. This JSON has the following: a Display Layout that shows a Condition Set output, the telemetry's current value, and an image that uses the Condition Set. This image has the conditional styling logic such that when the Condition Set outputs the string "invisible", the image disappears. When the Condition Set outputs the string "visible", the image appears.
3. Observe that when the Condition Set outputs "Invisible", the NASA logo does not disappear as it should. 

#### Environment

* Open MCT Version:  4.0.0 next
* Deployment Type:  All 
* OS:
* Browser: Chrome

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by charlesh88** [comment]
If this breaks any existing mission operations displays, then I'll argue strenuously that this is a blocker.

**Comment by ozyx** [comment]
> If this breaks any existing mission operations displays, then I'll argue strenuously that this is a blocker.

Important caveat I discovered in my testing. This seems to only apply to images. And I've only tested with png format so far.

**Comment by ozyx** [comment]
#7782 Related

**Comment by jvigliotta** [comment]
Verified Fixed - Testathong 10/2/24
