### ISSUE TITLE
[Table] Timestamps don't show milliseconds

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#776]
Time stamps in a Table view don't show milliseconds. For faster than 1Hz data, this creates ambiguity.

(Issue is likely not with Table itself but with the default telemetry format - expect that amending this to include milliseconds will resolve the issue.)

**Comment by VWoeltjen** [comment]
Treating this as critical, since this may be regarded as loss of data

**Comment by RCarvalhoNASA** [comment]
20160324 Testathon this is working in plots and table view
