### ISSUE TITLE
[e2e] Update all references to our custom clock api to use the native one provided by playwright

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#7763]
#### Summary

Playwright added the clock api in 1.45 which replaces our custom clock intercept in baseFixtures https://github.com/nasa/openmct/blob/393da7dc62966ebc9173b30740df347073f008e4/e2e/baseFixtures.js#L96

- [ ] Bump to 1.45.0 in all repos
- [ ] Investigate the new package.clock() API as a literal replacement
- [ ] Replace all custom API calls with page.clock()
- [ ] Remove all dependencies which were added specifically for our sinon implementation (at least the sinon package and types)

**Comment by akhenry** [comment]
Needs test instructions

**Comment by ozyx** [comment]
# Testing Instructions

See https://github.com/nasa/openmct/issues/7797#issuecomment-2389693813
