### ISSUE TITLE
Implement 'vue/component-name-in-template-casing': ['error', 'PascalCase']

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#7769]
#### Summary
Implement `'vue/component-name-in-template-casing': ['error', 'PascalCase']` for consistency in our component names

**Comment by ozyx** [comment]
# Testing Instructions

1. Create Example Imagery
2. Verify that all toolbar buttons function properly
    - Zoom in
    - Zoom out
    - Zoom lock
    - Reset 
3. Drag it into a display layout
4. Verify that the toolbar buttons still function properly
5. Drag it into a timelist
6. Verify that the toolbar buttons still function properly

**Comment by shefalijoshi** [comment]
Verified fixed.
