### ISSUE TITLE
Properties of stacked plot series that aren't mutable don't get applied

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#7771]
#### Summary
Changing the properties/config of a stacked plot series that is not mutable gets saved correctly, but does not get applied when loaded.
Workaround is to first include the series in an overlay plot, save the config and then include the overlay plot inside the stacked plot.

ALSO SEE: VIPERGC-535

#### Steps to Reproduce
1. Create a stacked plot
2. Add a series (telemetry) to the stacked plot that cannot be saved to couchdb (like a Sine wave generator)
3. Edit the stacked plot, select the series and change it's config - for example, the marker size
4. Save the change
5. Observe that the change is not applied.

#### Environment

* Open MCT Version: 4.0.x
* Deployment Type: all
* OS: all
* Browser: all

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by jvigliotta** [comment]
Partially Fixed/New Issue - Testathon 10/2/24

The first item in a stacked plot in edit mode is unable to be selected. If it's the only one, it still cannot be selected.
When editing a dictionary endpoint in the stacked plot (when it was the second item) it's properties DID persist.
