### ISSUE TITLE
[Table] Low precision in displayed values

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#778]
Values displayed in a real-time table are truncated to three digits; this is effectively loss of data. As with #776, this is almost certainly an issue with the telemetry formatter and not with Table.

Solving this with formats may solve #544 as well.

**Comment by VWoeltjen** [comment]
Trying to solve #544 along with this is impractical - simply showing the full data values (as one would want to in a table) causes Y axis labels to overflow. In the case of axis labels, the consequences are less serious, the values being truncated are not telemetry values

(Really, this should be a user preference, but in the absence of that the defaults we provide should work reasonably well.)

**Comment by larkin** [comment]
Would deal with #544 in the context of plots (e.g. ticks should be normalized and then have consistent intervals defined e.g. 0.75, 1.5, 2.25, 3.0), and deal with #778 in the context of tables (e.g. display raw data value, don't format).

To auto-improve formatting, we need a) more metadata on which to base decisions about formatting, and b) more per-view control of data formats.  The natural progression here is to c) refactor out shared formatting libraries, so long as we can strike the right balance.  It's interesting to look at https://github.com/d3/d3-format which is a very powerful library focused entirely on formatting numbers for human consumption.  It's generic and useful enough that it should be easy to decouple from concerns of individual views.

**Comment by RCarvalhoNASA** [comment]
20160324 testathon, this is verified as working
