### ISSUE TITLE
Alphanumerics cannot be conditionally hidden

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#7782]
#### Summary

Condition visibility does not work with alpha-numeric display elements.

#### Expected vs Current Behavior
Display builders should be able to hide or show alphanumeric elements based on the output of a condition set.

#### Steps to Reproduce
1. Import [the attached display layout]([Alphanumeric visibility.json](https://github.com/user-attachments/files/16241562/Alphanumeric.visibility.json)).
2. Switch to real-time mode.
3. Observe that the SWG alpha-numeric element is always visible
4. Click on the SWG alpha-numeric and observe that it has conditional styling applied that should render it invisible when the value of the SWG drops below 0.

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon 10/2
