### ISSUE TITLE
[Time Conductor] In fixed time mode, dismissing bounds changes actually submits them

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#7791]
#### Summary

When making changes to time conductor bounds in fixed mode, dismissing the changes via the 'X' button will submit them anyway. 

Discovered due to [failing tests in openmct-yamcs](https://github.com/akhenry/openmct-yamcs/actions/runs/10080695502/job/27871032510?pr=465#step:13:219) 

#### Expected vs Current Behavior

Clicking 'Dismiss' should not submit any changes

#### Steps to Reproduce

1. Switch to fixed time mode in the global time conductor
2. Change the start year to something else (e.g. 2024 -> 2023)
3. Dismiss the changes by clicking the 'X'
4. Check the time conductor and see that the change has actually been submitted

#### Environment

* Open MCT Version:  4.0.0-next
* Deployment Type:  local, openmct-yamcs
* OS: any
* Browser: chrome

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information

https://github.com/user-attachments/assets/b5541ff3-3a5c-47eb-bac1-6f0a1f48de50

**Comment by ozyx** [comment]
# Testing Instructions
- Follow steps to reproduce and verify that the time conductor does not change bounds if changes are dismissed

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon 10/2/24
