### ISSUE TITLE
[e2e] Finalize playwright-eslint work

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#7797]
#### Summary

- Remove `force: true` from click actions in e2e to the greatest extent possible
  - Document wherever it's not possible, and why
- baseFixtures and appActions
  - Review code in appActions and try to update the locators to be modern as best as we can
- **No more test changes**

**Comment by akhenry** [comment]
Needs test instructions

**Comment by ozyx** [comment]
The main functional code this touches is removing a `nextTick()` before we resize the compass component on an image view.

# Testing Instructions

1. Create an example imagery view
2. Navigate to it
3. Ensure the compass appears correctly
4. Resize the window. Ensure the compass behaves properly
5. Create a display layout
6. Drag the imagery view into the layout
7. Resize it in the layout and verify that it resizes properly
8. Create a timelist
9. Drag the example imagery into the timelist
10. Verify that the compass appears (or doesn't appear) where it should be

**Comment by unlikelyzero** [comment]
Followed TO THE BEST OF MY ability reading these GARAGIO instructions
