### ISSUE TITLE
[Telemetry TABLES!] Changing performance mode changes sort order of request unexpectedly

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#7809]
#### Summary

Changing the performance mode on Telemetry Tables will incorrectly swap the sort order of the outgoing request.

#### Expected vs Current Behavior

Should keep the current order or default to descending.

#### Steps to Reproduce

1. Change the performance mode on a telemetry table while viewing the network tab for the request
2. Note the order in the request url, then change the mode again and note the order has changed

#### Impact Check List

- [x] Data loss or misrepresented data? (with duplicate timestamps, the order can be different)
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information

Related to VIPERGC-424

**Comment by davetsay** [comment]
not fixed. changing sort order is not re-requesting so when you toggle from `desc` to `asc`, and then clock the performance mode toggle, the request will still query in `desc`.

**Comment by charlesh88** [comment]
10/4/24: Still not fixed. Toggling from unlimited to limited should requery but doesn't; this is fixed by https://github.com/nasa/openmct/pull/7863. BUT: changing sort order from desc to asc then toggling performance always uses desc as the sort argument.

**Comment by akhenry** [comment]
Note that #7863 fixes stable insertion into tables, but DOES NOT fix the issue where tables in limited mode are not re-querying when sort order is changed.

**Comment by jvigliotta** [comment]
## Testing
- open the network tab
- view an immutable object in a table (can be a dictionary endpoint)
- note the request order param (default is order=desc)
- change the sort order of a column, then change the mode of the telemetry table to trigger another request
- note the request order param and make sure it has changed (desc to asc or asc to desc)
- next, view the table in "Limited" mode
- now change the sort order of a column
- make sure a new request is sent out
- now change the table to unlimited mode
- change the sort order
- make sure no new request was made

**Comment by akhenry** [comment]
@charlesh88 to test

**Comment by charlesh88** [comment]
Testathon 2024-10-10: verified not fixed. Toggling the sort method on the Timestamp column now properly preserves that sort method when toggling limited/unlimited, but sorting on another column (like Value) and toggling performance reverts sorting to the Timestamp column.

**Comment by akhenry** [comment]
ok, so in the current implementation, Yamcs only sorts by timestamp (it's a time-series database). This behavior is probably not unusual in time-series databases.

Limited mode (aka performance mode) relies on the back-end being able to return us a sorted, limited, subset of results. In this case it literally can't, so we can't support sorting by anything other than timestamp in limited mode right now.
