### ISSUE TITLE
Gauge type Needle Dial not working

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#7820]
#### Summary
Selecting "Needle Dial" as the visualization type in a Gauge doesn't display the needle.

Gauge using Filled Dial: works as expected
<img width="849" alt="Screenshot 2024-08-27 at 3 36 42 PM" src="https://github.com/user-attachments/assets/82525b45-c84a-443f-ae1b-e08e2460c340">

Gauge using Needle Dial: does not work
<img width="849" alt="Screenshot 2024-08-27 at 3 34 26 PM" src="https://github.com/user-attachments/assets/e7c7c6ac-8d5f-4cf6-884a-16e1be6d5367">

#### Steps to Reproduce

1.  Make or edit a Gauge.
2. Choose "Filled Dial" in the Gauge Type in the object's Properties dialog.
3. Add a data source and set the Gauge's min and max values such that current values will fall within the Gauge's display range.
4. Verify that you can see the Gauge filled similar to as shown above.
5. Edit properties on the Gauge and select  "Needle Dial" in the Gauge Type in the object's Properties dialog. Save, nav away and back to the Gauge.
6. Verify that you cannot see the needle visualization in the Gauge.

#### Environment

* Open MCT Version:  9.0.0-rc10
* Deployment Type:  dev server
* OS: Linux, Macos
* Browser: Chrome

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by charlesh88** [comment]
Here's the problem - the needle path fill color is set to rgba 0 opacity:
![image](https://github.com/user-attachments/assets/d3371697-5616-4a39-a61d-373f82aea041)

**Comment by charlesh88** [comment]
### Testing Notes
1. Follow Steps to Reproduce 1 - 5 above. 
2. Now, verify that the needle is _not_ hidden and is visible.
3. Use the console to load the Snow, Darkmatter and Maelstrom themes, and verify step 2 in these notes.

**Comment by ozyx** [comment]
Verified ! LGTM

10/02/2024 - Testathon
