### ISSUE TITLE
[Imagery] Some images not being bounded properly

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#7825]
#### Summary
Thumbnail strip in imagery view is organized chronologically, ascending left to right, with most recent image telemetry on the right. If, paused, on resume, the paused image (and other older images) can get stuck to the right side of the thumbnail strip, if the strip was paused for too long. My guess is too long refers to when the images were to scroll off screen.

Upon further investigation, the root cause is images are not being removed if multiple images are to be removed in the same event. Pausing was the only way I could reliably reproduce this (although I'm not 100% sure why that plays a role).

VIPERGC-577

#### Expected vs Current Behavior
Expect on resume, all thumbnails are present and in order, and focus goes to the most recent, right most, image.

#### Steps to Reproduce

1. Navigate to an example imagery object, with the time conductor in realtime mode
2. Pause telemetry by clicking on an image, or clicking the pause button located above the thumbnail strip
3. Wait for a while... (My guess is until when the images were to scroll off screen)
4. Resume telemetry
5. Observe that when new telemetry comes in, the paused images are stuck to the right of the incoming telemetry (timestamp and staleness indicator will indicate)

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available? Refresh or change time conductor bounds to force a reload
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by davetsay** [comment]
Testing Instructions: see steps to reproduce for failing case

**Comment by ozyx** [comment]
Verified -- Testathon 2024-10-03
