### ISSUE TITLE
[Tables] Table options do not appear in edit mode

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#784]
Actual issue is that table options do not appear when editing telemetry objects in real-time or historical table view. Options do appear when editing table type objects. In the world of "views as objects" this may not be a problem, but it could be confusing to the user if they can sometimes edit visible columns, but not at other times?

Note that this issue was originally described slightly differently as a regression. Not a regression, behavior is as-designed. Author was tired :smile:

**Comment by charlesh88** [comment]
Closing: implementation is as designed currently.
