### ISSUE TITLE
Condition Manager is using older telemetry API and conditional styling can use a performance upgrade

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#7840]
#### Summary

This came about when debugging VIPERGC-550, in which a conditionally styled alphanumeric in a display layout was showing the wrong styles being applied. Testing showed there are situations where conditional styling could be applied incorrectly. This lead to performance enhancements to how the styles are applied and discovering a mismatch in how telemetry is requested in ConditionManager. 

#### Expected vs Current Behavior

Applying styles can happen quickly and change often, it should be performant. ConditionManager should use the newer TelemetryCollections in the telemetry API to request telemetry.

#### Steps to Reproduce

1. Create a condition on a moderately fast changing endpoint
2. Use that endpoint to style an alphanumeric in a display layout
3. Note that styles can be applied incorrectly

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [x] Does this have an impact on Performance?

#### Additional Information

In the below video, the item should only be red, when the value is above 100 (that is not happening consistently).
https://github.com/user-attachments/assets/4fa2f7cf-c821-461d-9a30-d1430764900d

**Comment by akhenry** [comment]
Verified Fixed.

In the video below the fixed code is in the left window, the pre-fix code is on the right. At about the 12 second mark the pre-fix code condition set shows > 100 even though the underlying value is 65. The  Note that the data are being fed from different data sources, so the data are expected to be different.

https://github.com/user-attachments/assets/9f1abbe1-3166-4e41-8205-fa5004726feb
