### ISSUE TITLE
[Fault Management] Providers should be able to specify shelve durations

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#7853]
**Is your feature request related to a problem? Please describe.**
Currently, shelve durations are hard-coded and only provide a few different options.

**Describe the solution you'd like**
Fault providers should be able to define their own shelve durations. An optional API method such as `getShelveDurations` can be defined by the fault provider and return a list of options with label and duration (in ms):

```js
[
  {
    name: '1 minute',
    duration: 60 * 60 * 1000
  },
  {
    name: '5 minutes',
    duration: 5 * 60 * 60 * 1000
  }
]
```

**Comment by ozyx** [comment]
# Testing Instructions

## openmct core

- modify `index.html` to install the example fault source plugin:
```js
openmct.install(openmct.plugins.example.ExampleFaultSource());
```
1. Modify the `getShelveDurations()` method in `exampleFaultSource.js`. Give it some kind of duration and label.
2. `npm start`
3. Goto Fault Management
4. Shelve a fault
5. Verify that the specified durations appear in the drop down
6. Remove the `getShelveDurations()` method completely
7. Repeat steps to shelve a fault
8. Verify that the default shelve durations appear in the dropdown

## openmct-yamcs

1. Modify that yamcs fault provider's `getShelveDurations()` to add some custom durations (a short duration would be helpful to test the unshelving)
3. Start `openmct-yamcs` with YAMCS quickstart running
4. Add an `mdb-override` to a parameter to get it to trigger a fault. Here's an example using Latitude:

```sh
curl -X PATCH "http://localhost:8090/api/mdb-overrides/myproject/realtime/parameters/myproject/Latitude" \
-H "Content-Type: application/json" \
-d '{
  "action": "SET_DEFAULT_ALARMS",
  "defaultAlarm": {
    "staticAlarmRange": [
      {
        "level": "WATCH",
        "minInclusive": 808,
        "maxInclusive": 810
      },
      {
        "level": "WARNING",
        "minInclusive": 810.01,
        "maxInclusive": 812
      },
      {
        "level": "DISTRESS",
        "minInclusive": 812.01,
        "maxInclusive": 814
      },
      {
        "level": "CRITICAL",
        "minInclusive": 814.01,
        "maxInclusive": 820
      },
      {
        "level": "SEVERE",
        "minInclusive": 820.01,
        "maxInclusive": 824
      }
    ]
  }
}'
```
5. Goto fault management and verify fault(s) has/have been triggered
6. Shelve a fault and verify your custom durations show in the dropdown
7. Shelve a fault for a short amount of time and verify that it unshelves when its time is up
8. Shelve a fault selecting "indefinite" as the option for duration. Verify that it never unshelves (waiting 5+ min is probably enough here?)

**Comment by jvigliotta** [comment]
Partially Fixed - Testathon 10/3/24

Getting an error when removing the `getShelveDurations()` from the provider.

**Comment by shefalijoshi** [comment]
Testing with core Open MCT:
1. Setting to a custom duration - Verified
2. Remove `getShelveDurations()` completely - failed with console error:
`Uncaught (in promise) TypeError: this.provider.getShelveDurations is not a function
    getShelveDurations FaultManagementAPI.js:142
    created FaultManagementView.vue:143`
3. Set getShelveDuration() to return `[]`. On Clicking the `shelve` button- failed with console error:
`Uncaught (in promise) TypeError: this.shelveDurations[0] is undefined
    toggleShelveSelected FaultManagementView.vue:313
    callWithErrorHandling runtime-core.esm-bundler.js:195`

**Comment by shefalijoshi** [comment]
I still see an error if the return value for getShelveDuration() is set to [].
<img width="1674" alt="image" src="https://github.com/user-attachments/assets/37009162-4ddc-4a81-b815-913b0c783363">

**Comment by charlesh88** [comment]
Testathon 2024-10-17: verified fixed.

**Comment by ozyx** [comment]
> I still see an error if the return value for getShelveDuration() is set to []. <img alt="image" width="1674" src="https://private-user-images.githubusercontent.com/5247066/377255294-37009162-4ddc-4a81-b815-913b0c783363.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNzI1ODIsIm5iZiI6MTcyOTI3MjI4MiwicGF0aCI6Ii81MjQ3MDY2LzM3NzI1NTI5NC0zNzAwOTE2Mi00ZGRjLTRhODEtYjgxNS05MTNiMGM3ODMzNjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMThUMTcyNDQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDdjOWUxMWZjOTMyYTc5NDU5ZTZkZDlhMjgyY2JkODhkYzk1ZjNjOTVjMTc2OTk4YmQ5NmI2MmU5MjA0N2EyNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.aJ87-adaxwxZIUcYLkX8IthvdffyZxxo1XfTcezgfNg">

Good catch on an edge case-- let's file it separately

**Comment by jvigliotta** [comment]
Open MCT Core Testing steps - Verified Fixed - 10/18/24
YAMCS Testing steps - TBD
