### ISSUE TITLE
Tabbed displays trigger persistence when navigating away

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#7871]
#### Summary
Tabbed displays trigger a persistence call on navigation away. This is a problem in shared displays because:
1. It is incompatible with immutable displays of the type needed for flight environments
2. It causes regular persistence conflicts in shared displays.

#### Expected vs Current Behavior
Object persistence should not ever occur during normal display browsing, unless the user has taken some deliberate action to modify object attributes.

#### Steps to Reproduce
1. Navigate to any tabbed display in our test environment
2. Open dev tools network tab
3. Navigate away from the display without changing anything
4. Note in the network tab there is a PUT to the tabbed display object. There shouldn't be.

#### Environment
* Open MCT Version: 4.1.0-next#55c023d1eb06e487fa7689ec7b86fc5ada576587
* Deployment Type: testathon
* OS: MacOS 14.7
* Browser: Chrome

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by akhenry** [comment]
An acceptable short term solution here is to just check whether the display is unlocked and persistable before attempting to mutate it.

**Comment by shefalijoshi** [comment]
Testing instructions:

1. Navigate to a tabs view with multiple tabs
2. Lock the object by clicking on the lock icon next to the 3-dot menu
3. Change to view a different tab than the currently selected one
4. Navigate away from the tabs view by clicking on another object in the navigation tree
5. Navigate back to the tabs view.
6. Verify that the tab selected in step 3 is not the default tab displayed.
7. Unlock the view and repeat steps 3-5.
8. Verify that the tab selected in step 3 is the default tab displayed.
Ideally we would repeat the steps for a tabbed view that CANNOT be mutated (but I'm not sure we have a way to test that currently)

**Comment by charlesh88** [comment]
Testathon 2024-10-16 verified fixed.
