### ISSUE TITLE
Support locking objects en-masse to prevent ad-hoc changes in restricted environments.

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#7877]
**Is your feature request related to a problem? Please describe.**

Certain of our operational environments require a subset of domain objects to be immutable to regular users. For example, displays that users are trained on should only be modified following a change-management process, and should not be modifiable ad-hoc during live operations.

**Describe the solution you'd like**
Open MCT already supports object locking. This capability could be leveraged as a mechanism for preventing changes in operational environments by enforcing object locking on the server-side (ie. in Couch DB), and disallowing users from unlocking them.

Implementation is in a single PR, but I've split this task into multiple GitHub issues to allow us to split up testing more effectively.

* [ ] #7880
* [ ] #7878
* [ ] #7879

In all cases the existing user-locking functionality should be retained.

**Describe alternatives you've considered**
A second read-only couch database. This requires more widespread changes to Open MCT and the attendant risk associated with large-scale changes to our persistence API.

**Comment by akhenry** [comment]
## Testing Notes
Test instructions are provided in the issues linked above. They should be executed in the order listed above.

**Comment by charlesh88** [comment]
Front-end changes pushed and testing notes in https://github.com/nasa/openmct/issues/7878 updated.
