### ISSUE TITLE
Object Locking UI Improvements

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#7879]
**Is your feature request related to a problem? Please describe.**
See #7877 for a description of the overall problem being addressed here

**Describe the solution you'd like**
* [x] If an object cannot be unlocked (because it is prevented in Couch DB) disable the unlock action in the UI, and provide a hint on hover explaining that it cannot be unlocked.
* [x] When an object is locked by a user or a script give attribution in the UI
* [x] Extend the lock icon to all object types (eg. folders) that are not user-lockable.

**Comment by akhenry** [comment]
## Testing Notes

### Script locking

1. Identify a large and complex folder of objects to lock. eg. "Discipline Displays"
2. Follow the instructions in <BLAH> to lock the target object tree
3. Click on various objects in the tree and confirm that for every object, the `lock` icon appears in the bar at the top of the object view:
![Screenshot 2024-10-09 at 3 30 43 PM](https://github.com/user-attachments/assets/75b04e41-9d9d-47b4-9735-ee0b14a874c1)
4. TBC...

User locking (regression testing)

**Comment by akhenry** [comment]
@unlikelyzero to test

**Comment by charlesh88** [comment]
Also @johnhill2: Testathon 2024-10-10: duplicating an object within a script-locked folder into a non-locked location results in the object being script-locked; this is not expected or desired.

**Comment by unlikelyzero** [comment]
Looks good
