### ISSUE TITLE
lts/* in .nvmrc causes sudden change without testing

### ISSUE THREAD

**Issue by wilsonmar** [nasa/openmct#7889]
The .nvmrc file is supposed to specify the version of node the app need.
It currently now contains:
```
lts/*
```
This approach is convenient because whatever is the latest LTS is downloaded.
However, the problem is that Node can change suddenly without testing.
How about specifying a specific version, such as:
```
v20
```
Or, according to the list https://nodejs.org/en/about/previous-releases
```
lts/iron
```

NOTE: https://refine.dev/blog/install-nvm-mac-and-windows/#advanced-nvm-usage
The workaround to this is:
```
nvm use v20
```
The response:
```
Now using node v20.18.0 (npm v10.8.2)
```

I came upon that approach after "its/*" errored for me.
When I installed the latest, I received this error:
```
npm error notsup Required: {"node":">=18.14.2 <22"}
```
The "<22" led me to believe that v21 would work.
But there is no "brew install node@21".

https://github.com/nodejs/node/tags

**Comment by ozyx** [comment]
@unlikelyzero should we change this to `lts/iron` ? I don't think it has changed since we've implemented it

**Comment by unlikelyzero** [comment]
@wilsonmar thank you for opening the issue. 

1. We use the `nvmrc` to declare support for the **project** for build engineers _at the instant they need to build openmct_
2. We use the package.json `engine` target to declare the range of **tested** node versions. There are times when the Y and Z releases in X.Y.Z versions of node are incompatible.

I would make sure that you do a `nvm install` and `nvm use`. If you'd like to try node21, you can use `nvm install v21`
