### ISSUE TITLE
[Timeline] Can no longer re-order peer Activities in a Timeline view

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#789]
Testathon 032416, found by Robert (who gets the finder's fee).
Re-ordering peer elements (either Timelines or Activities) in a Timeline no longer works, although inserting between existing elements does work properly when promoting an element. Possibly a regression from #767. 

This isn't technically a blocker, but is very important functionality to Robert.

1. Create a Timeline with Activities A, B, and C. All Activities should be peers.
1. In edit mode, Drag C between A and B such that the lower border of A highlights indicating a valid drop.
1. Note: releasing B does not move it between A and C; instead, the lower border of A will remain erroneously highlighted and C will not have moved. 

Screenshot of result of trying to re-order:
![testathon 032416 - timeline reorder peers bug](https://cloud.githubusercontent.com/assets/1056412/14033503/16dc443a-f1d8-11e5-9f16-136c4c687e54.png)

**Comment by charlesh88** [comment]
May be relate to #790

**Comment by VWoeltjen** [comment]
When this occurs, see console error: "/platform/entanglement/src/services/MoveService.js:86 Uncaught Error: Tried to move objects without validating first."

**Comment by VWoeltjen** [comment]
Verified testathon 20160401
