### ISSUE TITLE
Marcus Bains "now" line broken in Plan and Gantt views

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#7892]
#### Summary
The Marcus Bains (aka "now") line is not positioning itself properly in Time Strip, Plan and Gantt views. Note the Time Conductor settings, - 7 / +7 hours which should place the line in the middle of the Gantt area:
![Screenshot 2024-10-15 at 2 26 50 PM](https://github.com/user-attachments/assets/97fbe67a-8c7d-4a0c-8085-eca3c1a923f0)

If a Time Strip just has a Plan in it, it won't work as noted. But if the Time Strip has telemetry in it, it will work properly:
![Screenshot 2024-10-15 at 2 27 44 PM](https://github.com/user-attachments/assets/d42c9195-f255-412a-91e1-c069051bf2a2)

IMO this should be a blocker as it's severely misleading for situational awareness.

#### Steps to Reproduce

1. Put the Time Conductor into Real-time mode. Set the Start and End roughly the same interval.
2. View a Plan. 
3. Observe the MB line at the very start of the Gantt area.
4. Add a Plan view to a Gantt view. Repeat step 3.

#### Environment

* Open MCT Version: 4.1.0-next 47f0b66c7e52b29f559c3479591aa2be539d72cd
* Deployment Type:  
* OS: MacOS
* Browser: Chrome

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by shefalijoshi** [comment]
Testing instructions:
View a plan in either a regular plan view or a gantt chart view.
Change the time conductor to use Real Time.
Make sure that the `now` line shows up in the right place by changing the before and after offsets for the real-time window.
