### ISSUE TITLE
Gauges do not handle missing objects

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#7908]
#### Summary
A missing object in a Gauge will throw a JavaScript error in the console. The issue appears to be in this line of code, which assumes at least one range is returned -
https://github.com/nasa/openmct/blob/057a5f997c8592cf5c9f404b75edaea64e14866f/src/plugins/gauge/components/GaugeComponent.vue#L656

#### Expected vs Current Behavior
There should not be any unhandled errors in the JavaScript console

**Comment by jvigliotta** [comment]
## Testing Instructions
- View a gauge with a missing object
- Verify now errors in the console
- Verify if you modify the start/end bounds/offsets that they are updated correctly
