### ISSUE TITLE
Inappropriate context actions available for Packet items

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#792]
Testathon 032416. Context menu actions were available for Packets and their items that shouldn't be. Observed while editing, and browsing. Context menu included:
* Open in New Tab
* Move
* Duplicate
* Create Link

Of the four actions, only the first and last were appropriate for these object types. @akhenry believes that a forthcoming PR - #783 - will fix this problem.

**Comment by charlesh88** [comment]
Victor: #783 probably won't cover this, as it extends beyond editing. Could be related to tree re-coding. Policy-based solution is the way to go.

**Comment by VWoeltjen** [comment]
w.r.t. policies, moving should be disallowed in this situation because it would modify Packets (users shouldn't be able to modify this), and duplicating should be disallowed because it would create new Packet objects (users shouldn't be able to instantiate these)

**Comment by VWoeltjen** [comment]
Verified testathon 20160401
