### ISSUE TITLE
[Real-time tables] Clicking on telemetry objects when selected view is "rt-table" sometimes results in blank screen

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#793]
~~This issue is really intermittent and difficult to recreate~~. Suggests a race condition of some kind. The steps below will need to be followed repeatedly until the issue manifests -

1. Open a panel under RP15 Tlm Panels
2. Select the 'rt-table' view
3. Now go through the other panels under RP15 Tlm Panels randomly selecting them.

**Comment by akhenry** [comment]
This can actually be consistently reproduced by reloading the browser while on a panel in rt-table view.

**Comment by charlesh88** [comment]
Post-testathon triage: marking as blocker, this results in data loss. Also a very important feature for VISTA.

**Comment by larkin** [comment]
On review, not sure it's a blocker: there's a very simple work around: navigate to a different object and then back.

**Comment by akhenry** [comment]
@larkin agree that there's a simple workaround. Not clear on the exact criteria for a blocker? Fairly confident that this issue existed in the previous testathon and we just didn't notice it. Should also exist in VISTA, and we haven't noticed it there. 

In any case, I think I have a fix for it, just need to do a little testing. This being the final sprint in the release, I'd prefer to delay the release by a few days to fix this fairly major issue.

**Comment by akhenry** [comment]
@larkin having trouble recreating this locally. Think it might be due to with the way that the data dictionary is used to create the telemetry metadata in WARP, which has no analogue in Open. Would be interested to know if this issue is reproducible in VISTA?

**Comment by larkin** [comment]
Similar issues are reproducible. Try using example/taxonomy but put a timeout somewhere in the model service. 

Might have something to do with fast promises- the expectation is that something will be asynchronous but fast promises are not. That could cause unpredictable behavior.

**Comment by akhenry** [comment]
@larkin hrm, when I do the above I see a brief pause before the columns appear (similar to what happens with plot axis labels), but they always eventually appear. Can't reproduce what I was seeing in WARP (columns do not appear at all).

Are you seeing this behavior in VISTA?

**Comment by akhenry** [comment]
Addressed by #796

**Comment by VWoeltjen** [comment]
Verified testathon 20160401
