### ISSUE TITLE
[Tables] Column widths should be resized as new data is added to the table. 

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#798]
Tables calculate column widths based on the rows initially set in the table. In the case of historical tables this does not matter as all row data is available up front. For real time tables it's a problem if subsequent rows are much longer than the first row as they may see truncation of values.

**Comment by akhenry** [comment]
Resolved by #822

**Comment by akhenry** [comment]
**Testing Notes**
This affects real-time tables. The issue was that as new values were added to a real-time table the columns were not resizing to accommodate the new values. This lead to truncation of values. This may be difficult to reproduce in WARP, suggest combining values of different types, eg. Temperature, location, pose, drive state that have fairly heterogeneous data values.

**Comment by VWoeltjen** [comment]
Verified fixed in testathon 20160509
