### ISSUE TITLE
[Fixed Position] Drag-and-drop results in two copies

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#804]
Steps to reproduce:

1. Create a new Telemetry Panel
2. While still in Edit mode, switch to Fixed Position view
3. Drag-and-drop a telemetry object (e.g. Sine Wave Generator) into the Fixed Position View

Observe: Two instances of the Sine Wave Generator appear (one at the drop location, one slightly above)

**Comment by akhenry** [comment]
Would like to fix for live demo, but might be easiest to disable fixed poz.

**Comment by VWoeltjen** [comment]
Verified fixed during testathon 2016/05/31
