### ISSUE TITLE
[Fixed Position] Drag-drop into Fixed Position shows incorrect dialog

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#805]
Steps to reproduce:
1. Create a Telemetry Panel
2. Save the Telemetry Panel.
3. Switch to a Fixed Position view of the Telemetry Panel
4. Drag and drop a Sine Wave Generator into the Fixed Position view

Observe: A dialog appears warning about unsaved changes. Whether OK or Cancel is chosen, we proceed directly into Edit mode (and additionally see #804)

**Comment by akhenry** [comment]
Would like to see this fixed for live demo. Possibly just disable fix pos. for live demo?

**Comment by charlesh88** [comment]
Closing, Telem Panels should not have further enhancement.
