### ISSUE TITLE
[Tables] Cleanup of mct-table component

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#806]
Currently the interaction between historical/real-time tables and the mct-table directive is fairly idiosyncratic, and prevents mct-table being used as a generic component. Improvements should be made to 
a) Document the mct-table directive interface #801 
b) Remove idiosyncrasies such as the relationship between setting and adding rows, which currently presents potential concurrency issues.
c) Address code review issues from #796 
d) TableConfiguration.prototype.saveColumnConfiguration is marked as a private method and is called externally.  Fix.

**Comment by akhenry** [comment]
**Testing notes**
Test behavior of real-time and historical tables for general robustness, stability.

**Comment by VWoeltjen** [comment]
Did signficiant testing around tables during testathon 20160509; filed issues #910 and #912. Removing unverified label here
