### ISSUE TITLE
[Firefox] Table headers grow unexpectedly

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#809]
Testathon 2016-04-01 In firefox, As the height of a realtime table expands, the height of the table's headers also expand.  Have not yet tested with historical tables.

![screen shot 2016-04-01 at 12 07 36 pm](https://cloud.githubusercontent.com/assets/226503/14217370/6610a444-f802-11e5-90e3-49f0a62d2659.png)

![screen shot 2016-04-01 at 12 07 51 pm](https://cloud.githubusercontent.com/assets/226503/14217371/67fede60-f802-11e5-9914-e13cdec79c19.png)

**Comment by akhenry** [comment]
Would like to see this fixed for SpaceOps

**Comment by VWoeltjen** [comment]
Treating as blocker for purposes of live demo

**Comment by akhenry** [comment]
Testathon 20160509 verified fixed

**Comment by VWoeltjen** [comment]
Testathon 20160509 verified fixed
