### ISSUE TITLE
[API] Telemetry API

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#811]
Propose changes to telemetry API; suggest supporting with minimal prototypes to illustrate usage from views.

Focus here should be on improving usability of Telemetry API, which occurs on two fronts:

* Using Telemetry API from views. ("Dead simple" case should be a table view.)
* Implementing telemetry adapters.

Infrastructure between these two points may be left undecided, although there should be sufficient analysis of what this might look like to identify any performance or implementation concerns which might be implied by these APIs.

Some specific concerns to consider:

* Historical telemetry
* Real-time telemetry
* Canceling historical requests
* Time conductor integration (to the extent this might influence APIs)
* Units
* Formatting telemetry for display as text
* Parsing values for display in plots
* Limits
* Enumerations (specifically, sets of possible values)
* Semantically distinguishing timestamps (or similar) from non-timestampy properties
* Various telemetry types
  * Numeric telemetry
  * String telemetry
  * Enumerated telemetry (strings with a well defined ordering)
  * Image telemetry
  * Spectral telemetry (maybe)
  * Streaming data products (maybier)
* Update types
  * Simple request-response
  * Appending of telemetry (for plot performance, esp.)
* Request variations
  * Strategy (e.g. minmax)
  * Start/end-bounded requests (including property used to bound)
  * Requests for single latest datum (e.g. fixed position)
  * Different sources

**Comment by larkin** [comment]
Telemetry API needs additional testing in new API and this is a good place for that.  Reconciliation of realtime and historical depend on this API being stable.

**Comment by larkin** [comment]
We have a merged and deployed candidate of Telemetry API, will close this and open new issues for followups and improvements.
