### ISSUE TITLE
[Website] Open MCT Website markup/CSS/graphics creation

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#814]
From the Open MCT Website design, create static HTML and CSS markup

**Comment by charlesh88** [comment]
Started work on this yesterday 4/18.

**Comment by charlesh88** [comment]
@akhenry Markup/CSS for home page and body page templates available at https://github.com/charlesh88/openmct-site-2016.

Still to-do:
* Body page hero graphics
* Stack diagram

**Comment by charlesh88** [comment]
* download and install lektor
* git clone the openmct-lektor repo
* run 'lektor server' in that directory

**Comment by larkin** [comment]
Basic design complete, opened #1227 for follow-up task of mobile styling.
