### ISSUE TITLE
[Website] Create Open MCT site in Lektor

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#815]
Taking the markup from #814, create the static site in Lektor to allow editing of content.

**Comment by VWoeltjen** [comment]
Is the intent here to include developer documentation (such as API docs and documentation currently under `docs/src`)? If so, I believe this would satisfy #225 as well

**Comment by VWoeltjen** [comment]
@akhenry - noticed this issue is unassigned but in the current sprint; should this be assigned to you?

**Comment by charlesh88** [comment]
@akhenry Markup/CSS/imagery available via #814 and at https://github.com/charlesh88/openmct-site-2016.

**Comment by VWoeltjen** [comment]
Notes from tag-up 5/3/2016:

* Slight preference to keep dev docs in this repo (to stay in sync with code)
* Prefer to keep web site generator in a separate repository
  * Avoid introducing extra code/dependencies to this repo
  * Sit outside the repo to allow generation of version-specific docs without weird repo introspection
* Separate repository would need to be public to be accessible to CI
