### ISSUE TITLE
[Build] Remove Open MCT Web references

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#816]
Remove Open MCT Web references, most specifically as the `name` in `package.json` (may address other usages in the context of this issue as appropriate)

Will also likely need to file corollary changes in repositories which use Open MCT to reflect this change as well.

**Comment by VWoeltjen** [comment]
:information_source: __For testing__: Want to see if there are any "Open MCT Web" references (as opposed to "Open MCT") still lurking around in the About dialog, etc. One specific exception is copyright and/or licensing notices; these have intentionally retained the terminology agreed-upon during the open source release process.

**Comment by charlesh88** [comment]
Testathon 20160512
NOT FIXED, see screenshots:

About overlay, see orange hilited "OpenMCT Web":
<img width="806" alt="screen shot 2016-05-12 at 1 31 09 pm" src="https://cloud.githubusercontent.com/assets/1056412/15229403/c55f44e2-1845-11e6-9f5e-494f883d63d6.png">

Licensing main page. Does this need to stay as is in the header here?
<img width="673" alt="screen shot 2016-05-12 at 1 31 58 pm" src="https://cloud.githubusercontent.com/assets/1056412/15229443/f1ab64d6-1845-11e6-987a-63236d5d015b.png">

**Comment by VWoeltjen** [comment]
Remaining reference accounted for by https://developer.nasa.gov/ResourceProspector/warp/issues/164, closing this issue
