### ISSUE TITLE
Timeline display align with start of timeline

### ISSUE THREAD

**Issue by RCarvalhoNASA** [nasa/openmct#817]
For purposes of building up individual timelines into a greater timeline (e.g. building a multi-day timeline each for lander cruise, lander descent, and lander surface, then building a lander mega-timeline), I'm assigning non-zero start times to a timeline.  It would be nice, while working within/looking at those individual timelines, to have the default display start at the start of the timeline, rather than at day 0 00:00:00.

**Comment by RCarvalhoNASA** [comment]
Related to this, if I have a timeline starting on day 5, I can't even scroll all the way over to it unless I zoom way out.  Then I can't see any of the detail of it because I can't zoom in on the part of interest.
![timeline display bug](https://cloud.githubusercontent.com/assets/5769437/14264329/4e6fb0f4-fa74-11e5-89fe-20c6db82aa8f.jpg)

**Comment by VWoeltjen** [comment]
Self-assigning, as this is addressed in #936

**Comment by VWoeltjen** [comment]
Addressed by #955

**Comment by charlesh88** [comment]
Testathon 20160531
Verified fixed, BUT there is a new problem: if a Timeline set to start at 2 days holds an Activity that is set to start at 1 day, I get the following: neither element displays, and the zoom factor seems to be way off, as I have to scroll quite a bit to see anything in the Gantt area.
<img width="1179" alt="screen shot 2016-05-31 at 2 07 50 pm" src="https://cloud.githubusercontent.com/assets/1056412/15690609/31962e62-2739-11e6-98d4-22b7e5ed41d9.png">

Once scrolled, this is what I see. Note that the container Timeline is a 2px wide bar at upper right.
<img width="1187" alt="screen shot 2016-05-31 at 2 06 16 pm" src="https://cloud.githubusercontent.com/assets/1056412/15690622/408f4f2a-2739-11e6-9937-cd61d9fa7344.png">

When the Activity starts after the beginning of the Timeline, all is working as expected:
<img width="1180" alt="screen shot 2016-05-31 at 2 04 29 pm" src="https://cloud.githubusercontent.com/assets/1056412/15690653/6a369432-2739-11e6-9be4-e9b4524aa641.png">

My take is this: let's mark this issue verified, and open a new issue for the behavior I'm seeing. Unfortunately, I think our approach to Timeline containership is wrong: a Timeline extends to encompass its children when those children start after its own start, but the Timeline cannot flex to encompass the situation when any of its children start before it. I'd argue that perhaps Timelines shouldn't have start values, but instead encompass their children no matter what. This would create a more useful differentiation and purpose for a Timeline vs. an Activity - the Timeline becomes a grouping mechanism for Activities, and Activities do all the heavy lifting with regard to Start datetimes. @RCarvalhoNASA Thoughts?

**Comment by RCarvalhoNASA** [comment]
I think a more consistent approach across timelines and activities would be more helpful.  Given a (timeline/activity) with a set start time, when I'm creating sub-activities, it should pre-fill the start time of the children with that of the parent.  Users are allowed to move it wherever they want, but at least that prevents the default behaviour of starting a child at time 0 when the parent starts at 3 days, 4:32:45.

**Comment by charlesh88** [comment]
In that case, I think our approach to the default zoom should change then: the default zoom should encompass the earliest start datetime of any element, not just the outer Timeline.

**Comment by VWoeltjen** [comment]
This was working, but regressed (I believe with #982). Initial position is now sometimes before or after timeline start (except when timeline starts at 0 00:00:00). Workaround is to use the "zoom to fit" button.

Think this is an ordering issue; scroll position may be getting determined before width, which would cause the calculated scroll position to be invalid. Will see if there's an easy fix that can make it into today's testathon.

**Comment by VWoeltjen** [comment]
Ah, it is an ordering thing. Issue is something like:

* Timeline DOM elements have initial width determined by default zoom factor, timeline end, and physical width of display area. Let's say scrollable width=1000 with visible width=800
* Timeline determines its initial zoom level, and sets the scroll position based on that. Let's say that scroll x=300 at this point, with a new scrollable width=20000
* __Problem:__ The scroll position appears to be getting applied to the DOM before the new scrollable width. (This is mediated by Angular, and multiple components are involved, so it's hard to observe directly.) So physical width=1000, visible width=800, and scroll x gets set to 300. This is past the max scroll position (300 scrolled pixels + 800 visible pixels > 1000 pixel scrollable area) so the browser changes it to some lower number. After that, the width gets updated.

The easy fix is to ensure that there's always a little extra physical space to begin with. This does mean that if you zoom out far enough, you can scroll farther to the right than you need to, but this seems innocuous (doesn't result in #981, since you need to be zoomed _in_ to have that issue)

**Comment by VWoeltjen** [comment]
Nope, "easy fix" doesn't work in all cases. In particular, when start time is high relative to duration (e.g. a 6-hour timeline that starts at 3d) then doubling the initial width is still insufficient.

**Comment by charlesh88** [comment]
Testathon 2016-06-02
What are we testing in this testathon? Has this been fixed?

**Comment by VWoeltjen** [comment]
The behavior to test is as described in the original issue; this was fixed with #936 but regressed after fixing #981.

Haven't looked at the case where a timeline has an activity that starts before it (think we should have a separate issue for that to disambiguate)

**Comment by charlesh88** [comment]
Testathon 2016-06-16
Doesn't appear to be fixed. Here's what I did:

1. Had an existing Timeline that started at 0 days, 0, 0 etc.
![screen shot 2016-06-16 at 2 35 44 pm](https://cloud.githubusercontent.com/assets/1056412/16133991/a792fe7c-33cf-11e6-82c0-658609fa6a1f.png)

2. Via the tree, context-clicked the top-most Timeline and set Start to be 1 days, 0, 0 etc. On exiting edit, this is what I saw. This is also what displays when refreshing the browser.
![screen shot 2016-06-16 at 2 35 16 pm](https://cloud.githubusercontent.com/assets/1056412/16133997/b30b5cd6-33cf-11e6-99f4-63cd2619acf5.png)

3. What I expected to see is what happens after I click the "Zoom to fit" button:
![screen shot 2016-06-16 at 2 33 59 pm](https://cloud.githubusercontent.com/assets/1056412/16134007/bd5234b2-33cf-11e6-82ee-56f7e0c2eedf.png)

**Comment by VWoeltjen** [comment]
Are you seeing issues for any well-formed timelines? Want to get a sense of practical impact for triage; if we only see this for timelines with constraint violations, I'd move this to backlog

**Comment by VWoeltjen** [comment]
Hm, seeing this for well-formed timelines on page load (e.g. if I reload while the timeline is being viewed.) I'm _fairly_ certain I wasn't seeing this locally, so there may be some sensitivity to latency in these.

Not seeing any issues with well-formed timelines when exiting edit mode.

**Comment by charlesh88** [comment]
Nope, if I edit a Timeline such that it's well formed it does behave as expected. Don't disagree on moving this to backlog, but it might be worth getting @RCarvalhoNASA's input here: it's very easy to create this situation.

**Comment by charlesh88** [comment]
@VWoeltjen Is this still an issue?

**Comment by VWoeltjen** [comment]
Still an issue (in the cases described in previous comments)
