### ISSUE TITLE
[Edit] Remove EditableDomainObject

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#824]
Replace with transactional service for editor.

* Decorate persistence service to implement edit mode sandboxing (wiring should be minimal, as this part of the approach is likely to change later.)
* If not in transaction, persist immediately.
* Editor:
  * Start transaction
  * Track all persists
  * Either commit or rollback
* Persist automatically in browse
* Persist only when triggered in edit

**Comment by VWoeltjen** [comment]
Allocating to sprint Heinlein; prioritize among NEM refactoring where it would simplify subsequent refactoring tasks

**Comment by akhenry** [comment]
Note to testers: this change affects the transition from browse to edit mode, so general testing around edit mode is necessary. 
* Triggering edit mode - does it still work as expected? (edit mode button, and drag-drop)
* Once in edit mode, do actions still work as expected?
* Make sure no changes are being persisted that shouldn't be (eg. after a cancel)
* Likewise, make sure that changes are persisted when they should be
* Especially test around timelines where edit mode issues have surfaced in the past.

**Comment by VWoeltjen** [comment]
Encountered #979 during testathon 2016/05/31, which I believe may be related to these changes. Otherwise, did various testing around Edit mode and did not observe problems; since #979 is accounted for separately, think we can remove Unverified label here
