### ISSUE TITLE
[Persistence] Phase out requirement to call persist after mutate

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#825]
Phase out persistence calls (after implementing persistence service)

* Start phasing out persist calls
* Listen on mutate/handle changes alternatively.
* Maybe occasionally we still need persistence, we can discuss.

End Goal: mutate mutates, persist persists, you don’t have to call persist manually, that’s part of edit/browse/whatever.  

__Note for testing__: This is a refactor of object persistence code so no behavioral changes should be observable. Do want to test around editing, saving, cancelling, etc. to check for regressions.

**Comment by VWoeltjen** [comment]
May break this down into sub-issues or handle as a single task

**Comment by VWoeltjen** [comment]
Minimal work-in-progress on branch `persist-on-mutation-825`; since goal here is "phase out", may leave some loose ends here (e.g. not remove every unnecessary `persist` usage) and instead add a check to the `persist` call itself to avoid redundant calls to the underlying `persistenceService` (which is a sensible little optimization anyway)

**Comment by akhenry** [comment]
@VWoeltjen Closed issue as #874 seems to address it. Please feel free to reopen if there is additional remaining work here.

**Comment by larkin** [comment]
Testathon 2016-10-21: Don't see any obvious issues with this, though I wonder if it may contribute to #1277 or #1278 or #1281.  I'm okay to remove the unverified label.
