### ISSUE TITLE
[Timelines] Drag-drop to initiate edit mode not working when drop is over swimlane

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#826]
Believe that this is due to the TimelineSwimlandDropHandler [suppressing drop event](https://github.com/nasa/openmct/blob/master/platform/features/timeline/src/directives/MCTSwimlaneDrop.js#L93) by design. Logic needs to be tweaked here.

Workaround is to drop into timeline, but outside of swimlanes.

**Comment by akhenry** [comment]
Would like to see this fixed for SpaceOps

**Comment by charlesh88** [comment]
Just tested this: still an issue. Drop should be allowed anywhere; placement of dropped item can be below existing elements. Note that we may need to scroll the view to bring the dropped item into view if a large number of items.
