### ISSUE TITLE
Windows 10 building issue

### ISSUE THREAD

**Issue by isacikgoz** [nasa/openmct#827]
![snap](https://cloud.githubusercontent.com/assets/2153367/14462734/194ca9a0-00d1-11e6-908b-19f506238e89.png)

I had issues with SSL connection and solved it via configuring npmrc file. Anyways, I still get an error while I try to build OpenMCT in Win10 x64 OS

Did anyone faced with this issue?

**Comment by akhenry** [comment]
Could be a path issue while trying to invoke bower and gulp -  http://stackoverflow.com/questions/18060673/dot-slash-not-recognized-in-command-prompt-trying-to-install-python-module

**Comment by VWoeltjen** [comment]
Thanks for reporting this - it turns out there are a couple of places where our build is incompatible with Windows (due to path separators and script execution conventions.) I've opened a pull request (#828) to address these problems.
