### ISSUE TITLE
[Examples] Don't include example plugins by default

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#835]
Currently, example plugins are included by default in the built Open MCT. Other projects must explicitly disable these. As a consequence, these projects often end up with things like Sine Wave Generator or Example Imagery available in the Create menu, even though these things are not useful

It would be better to move the installation of these out of `main.js` (e.g. to `index.html` or `bundles.json`) such that dependent projects would have a "blank slate" to start out with.

Observed during testathon 20160418

**Comment by VWoeltjen** [comment]
__Note for testing__: Expect not to see "Sine Wave Generator" or any "Example" types in the Create menu

**Comment by akhenry** [comment]
Testathon 20160509 verified fixed
