### ISSUE TITLE
[Layout] Layout frame title context arrow not displaying on hover

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#836]
While editing a Layout, the menu arrow to the right of a panel title does not appear. This should appear and should expose context menu actions when clicked.

First observed in https://github.com/nasa/openmct/issues/635#issuecomment-210693301

Workaround: Leave Edit mode, those actions become available again.

**Comment by VWoeltjen** [comment]
Initially assigning to @charlesh88 to see if this is simply markup-related (e.g. something is blocking the hover from causing the arrow to show in the first place)

**Comment by charlesh88** [comment]
This is a z-index problem. Make this fix:
![screen shot 2016-04-21 at 3 58 31 pm](https://cloud.githubusercontent.com/assets/1056412/14726841/2162185e-07da-11e6-897f-b696dafea144.png)

**Comment by akhenry** [comment]
Testathon 20160509 verified fixed

**Comment by VWoeltjen** [comment]
Testathon 20160509 verified fixed
