### ISSUE TITLE
[Examples] Clean up and reorganize example plugins

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#841]
There are a number of example plugins in the codebase that in the interests of simplicity should be removed. Below are the plugins that are proposed to be removed:
- `example/builtins` 
- `example/composite`
- `example/extensions`
- `example/persistence`
- `example/worker`

A number of existing plugins under `example` are in fact developer tools, and should be moved to a separate `developer` or `tools` directory.
- `developer/mobile`: Moved from example/mobile
- `developer/plotOptions`: Moved from `example/plotOptions`
- `developer/profiling`: Moved from `example/profiling`

The telemetry examples could be moved under a single `telemetry` directory in order to group these related examples together.
Under `example/telemetry`:
- `example/telemetry/generator`
- `example/telemetry/eventGenerator`
- `example/telemetry/imagery`

**Comment by VWoeltjen** [comment]
With the new API coming in #1124, some new/relevant examples are:

* Basic plugin example
* Composition (using, adding new providers)
* Custom view
* Custom view using React (common request)
* Object provider example

Having these as standalone HTML files seems useful. Some examples of this are on the work-in-progress branch for #1124, at 09c73ef5f820a37e26b4425be87999a077d25032, although these reference work-in-progress APIs.

**Comment by larkin** [comment]
merge to #846
