### ISSUE TITLE
[Examples] Create new examples for object definition and telemetry API, and refactor the telemetry examples

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#845]
Suggest this does not happen until 1.0 API is available.
- example/telemetry -- contains all our generators, but does not expose objects that users create.  I think it is important to decouple the object from the provider.
- example/object -- example of how to define a domain object which can be created, and show how to configure properties of it.
- example/telemetryview -- a really simple telemetry view that demonstrates how to use the telemetry API.

**Comment by larkin** [comment]
merge to #846
