### ISSUE TITLE
[Design] Reconcile real-time and historical

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#847]
Design for the reconciliation of real-time and historical telemetry displays. In particular, need to specify behavior of time conductor (or around time conductor) such that it is intuitive and appropriate for both real-time monitoring and historical analysis use cases.

**Comment by charlesh88** [comment]
Related to https://github.jpl.nasa.gov/MissionControl/vista/issues/69

**Comment by charlesh88** [comment]
Starting work on this.

**Comment by charlesh88** [comment]
### Real-time Mode
A console operator wants to monitor health data is it's available in real-time. 
* Time Conductor allows user to connect to RT data of choice (e.g. in VISTA topics/sessions)
* TC in this mode uses a "follow time" behavior in which the latest receipt of RT data is indicated via a marker in the TC slider and ticks areas. The TC would automatically advance to keep the latest RT data marker in view, with values in the date inputs automatically updating to maintain a consistent time duration window. This window is defined by the user as an offset from the end datetime. For example, if the window is set to one hour, the TC automatically adjusts start and end datetimes to set the end datetime to the timestamp of the latest received RT data; the start is set to the end minus one hour.
* All time-aware components would stay in sync with the conductor just as if the user were manually manipulating the start and end datetime values.
* The TC and all time-aware components would visually indicate when they are operating in RT "follow-time" mode.

### Historical Mode

#### Staleness
* The TC and all time-aware components should indicate when they are in a stale state. Staleness would be defined by all of the following being true: 
 * The user expects to be receiving RT data. This state is actively signified to the system by the user connecting to a RT source.
 * The latest received data is past a time threshold TBD. 
* Each component should articulate staleness independently. Components A and B may include a telemetry element that was updated 1 second ago, while component C's telemetry elem hasn't gotten any new data for the last hour. The TC, A and B would all show as fresh, while C would indicate stale.

**Comment by charlesh88** [comment]
Time Conductor sketches reviewed with team and incorporated into [UI sketches v2.1.7](https://drive.google.com/a/nasa.gov/file/d/0B0v27OM1JkSeR001RFJZMk43QVk/view?usp=sharing) starting on page 48.

Still needed:
- Sketching around user gestures in components and views.

**Comment by charlesh88** [comment]
Closing as this has been decomposed into child issues.
