### ISSUE TITLE
[Website] Improve diagram in Open MCT website content

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#853]
Diagram should be flipped, and prettified. Remove plugins from the Open MCT box.

**Comment by charlesh88** [comment]
Final diagram. @akhenry Please have a look.

![diagram-architecture-1 1](https://cloud.githubusercontent.com/assets/1056412/14895046/8a5b10c6-0d2b-11e6-848d-78d40c2828bc.png)

**Comment by akhenry** [comment]
@charlesh88 Looks great, thanks.
