### ISSUE TITLE
[tables] Tables do not resize with container

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#861]
When tables are within a layout, they do not resize automatically when their container is resized. Is necessary to save layout and reload to see table resized. Consider this important for the live demo.

**Comment by akhenry** [comment]
@larkin @VWoeltjen This is going to look ugly if we don't fix it for the live demo.

**Comment by VWoeltjen** [comment]
Would be nice to have for live demo but not a blocker; should address if time allows

**Comment by charlesh88** [comment]
Testathon 2016-06-16
Verified fixed.

**Comment by akhenry** [comment]
Verified testathon 2016/06/16

**Comment by VWoeltjen** [comment]
Verified testathon 2016-06-16 as well
