### ISSUE TITLE
[Search] "More Results" button shows after filtering by object type

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#862]
Do a search that finds a large number of results such that the "More Results" button is displayed. Now, filter by object type such the result set is quite small. Observe: the "More Results" button still displays, but it shouldn't.

**Comment by larkin** [comment]
This is reported elsewhere, probably needs to be deduped. Solution is filtering by object type inside of the search provider instead of at the aggregator level.

**Comment by charlesh88** [comment]
I did a search for "More Results" and couldn't find anything. If you know of the issue, let me know.

**Comment by charlesh88** [comment]
Nevermind, got it. Closing this as a dupe of #501.
