### ISSUE TITLE
Actions missing in search results

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#868]
Telemetry objects retrieved via search results are missing actions such as "create link".

I can reproduce against https://openmctweb-staging-un.herokuapp.com

1. search for "voltage"
2. right click on one of the results

expected: you should have link action
actual: you do not have link action.

![screen shot 2016-04-28 at 9 41 57 am](https://cloud.githubusercontent.com/assets/226503/14894057/a2c0b13e-0d26-11e6-983d-095ffc0d2b17.png)

![screen shot 2016-04-28 at 9 43 51 am](https://cloud.githubusercontent.com/assets/226503/14894059/a53e641a-0d26-11e6-8346-d14fd5606cff.png)

**Comment by VWoeltjen** [comment]
I see "Create Link" in both those screenshots?

**Comment by larkin** [comment]
Erm, I think I screenshotted the wrong thing here... hrm.  I was able to reproduce this in VISTA with those telemetry points.

**Comment by charlesh88** [comment]
Notes from tagup 10/26/16:
This is not actually a bug, working by design. Links should not be in search results.
