### ISSUE TITLE
Open MCT Site to-dos

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#870]
#### Bugs?
- [x] Some layouts display Time Conductor (Mars Weather Display Layout), and some don't (Edit Display Layout Example). All layouts should display the TC.
- [x] Many objects in the tree don't have a view, like "Mars Science Laboratory" and "rems". These manifest as generic objects, but should be folders or something that displays a view. Am guessing that this was done to prevent users from editing, but I feel pretty strongly that the lack of view for these objects is very confusing.

#### Production

- [x] Produce final body page headers. Need to sync with Andrew on final content.
- [ ] Build process (how will the site be built?)
- [x] Integrate existing docs
- [x] Images and css for content pages (about, contribute, etc).

#### Tour-related

- [x] Latest live_demo has replaced Examples folder with My Items, but Hopscotch tour refers to Examples. Reconcile.
- [x] Tour refers to 'Real-time telemetry', 'Composites', and 'Thermal Panel', but the last two items don't exist.
- [x] Change "Edit" bubble to use placement "up" instead of "left". Remove text suggesting that Inspector can be hidden in previous step.
- [x] Move "Positioning and Resizing" bubble to the left so that it points at the open spot but doesn't cover it so much.

#### General

- [x] Fix bullets in date picker #869 

#### Content
- [x] Links to "Find out more" for How is NASA using.. and How Can You use.. should go to anchors. @charlesh88 
- [x] Change "Start using Open MCT" to “Developers, Start Using Open MCT”. @charlesh88 
- [x] Make "NASA Ames Research Center, in Silicon Valley" more visible. @charlesh88 
- [x] Change wording of "NASA’s next gen framework" @charlesh88 
- [x] Clarify usage of VISTA at JPL @akhenry
- [x] Tweak steps text on front page. Images are too ambiguous, use brief succinct text. Tell people to use  `npm start` instead of `gulp develop` @charlesh88 
- [x] Change play button on live demo link to text @charlesh88 
- [x] Remove tutorials (for now) @akhenry
- [x] Add Contact link in footer, goes to arc-dl-openmct@mail.nasa.gov @charlesh88

**Comment by charlesh88** [comment]
@akhenry FYI, am using this issue as a consolidated tracker for remaining site to-dos.

**Comment by akhenry** [comment]
> Change "Edit" bubble to use placement "up" instead of "left".

I actually changed this from "bottom". The problem was that if the inspector was collapsed (as is suggested in one of the previous steps" then the bubble gets partly obscured because half of it hangs off the edge of the screen.

**Comment by charlesh88** [comment]
Hmm, good point. I think I'll remove the collapsing suggestion, it's not that important. I'd rather have the bubble do a better job pointing at the button.

**Comment by akhenry** [comment]
@charlesh88 Sounds fair enough

**Comment by akhenry** [comment]
> Some layouts display Time Conductor (Mars Weather Display Layout), and some don't (Edit Display Layout Example). All layouts should display the TC.

Should they?

**Comment by charlesh88** [comment]
@akhenry For the "next gen" issue in the home hero, I suggest this: "NASA's Open MCT is a next generation mission control framework..."

**Comment by charlesh88** [comment]
@akhenry I've implemented many fixes, see new PR at https://github.com/nasa/openmct-website/pull/1. Highlights:
- Lost on "Silicon Valley". Jay very adamant he wanted that and Ames Research Center to be prominent. Solution arrived at in the hero was least of other suggested evils...
- "Next-generation" language has been addressed across the site.

**Comment by charlesh88** [comment]
@akhenry @larkin 
So, in Pete's comments: 

> tell people to use  `npm start` instead of `gulp develop`.

Are you saying they don’t need Gulp, so that text should be omitted from the About page?

**Comment by charlesh88** [comment]
We're done for now with this, we should file new issues as needed.
