### ISSUE TITLE
[Live Demo] Live Demo spawns from website with tree and Inspector hidden

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#883]
Live Demo testathon 05052016
Clicking the "Try it Live" link from my version of the site running on localhost:5000 opens the live demo in a new tab, but with both the tree and the Inspector collapsed as if I had invoked "Open in New Tab" from the app itself. Expectation (and needs of the tour) require those elements to be initially visible.

**Comment by akhenry** [comment]
Good catch.

**Comment by akhenry** [comment]
This is happening because the link uses `target="_blank"` to open in a new tab. This is a known bug, and there is a workaround. On the other hand, @larkin made the point that it should be left up to the user whether then open in a new tab or not, and we should just remove `target="_blank"`. I'm tending toward the latter.

**Comment by charlesh88** [comment]
Pete is wrong here. Anytime you click something in a nav element that takes you away from that nav, it should be done in the context of a new tab. Nobody ever thinks "Gee, I should right click this link and choose 'Open in New Tab'" when they're interacting with a site.

This is a real problem. What's the workaround? The app shouldn't use a blanket eval of "I'm in a new tab" as its logic to determine whether or not to hide the left and right panes.

**Comment by VWoeltjen** [comment]
A probably-quick solution would be to use a query string parameter (e.g. "collapsed=true"), supplied by Open in New Tab and checked wherever this existing "I'm in a new tab" check is

**Comment by larkin** [comment]
I don't like overriding people's browser functionality-- who knows what they might already have in place.  Would rather give users the choice of opening in new tab instead of forcing things always to open in new tab.

**Comment by larkin** [comment]
I do agree that the app should be smarter about it's open in new tab functionality-- separate discussions.

**Comment by charlesh88** [comment]
I am strongly adamant that nav elements that disappear the nav on me when I click a link that looks like all the other nav links totally suck, and that there is a special level in Hell reserved for people that build crap that works like that.

That said, I like Victor's suggestion a lot.

**Comment by akhenry** [comment]
The workaround mentioned above should fix it for the live demo without a code change in master

**Comment by charlesh88** [comment]
Awesome! Do you take this one Andrew?

**Comment by larkin** [comment]
> I am strongly adamant that nav elements when clicked that make the nav itself disappear totally suck, and that there is a special level in Hell reserved for people that build crap that works like that.

I see your point of disappearing nav.  This button is not like the rest.

**Comment by akhenry** [comment]
Fixed in website repo
