### ISSUE TITLE
[Live Demo] Live demo tweaks

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#884]
Live Demo testathon 05052016

### General

* #887 Make left pane wider by default

### Tour Content

1. "Select Object to Edit": add " Then click 'Next' when you're ready'.
1. "Edit Button": change "...or click..." to "...then click..."
1. "Adding an Object": change "...Real-time Plots..." to "...Real-time Telemetry, expand 
Rover Subsystems, and drag Wheel RL Temp..." to 
1. "Positioning and Resizing": move to left to free up space over empty area.

**Comment by charlesh88** [comment]
@akhenry One of my tour content changes (3) is realigning a ref in the tour with modified taxonomy. Is the taxonomy stable at this point?

**Comment by akhenry** [comment]
Taxonomy is stable (so long as there are no complaints)
