### ISSUE TITLE
[Live Demo] Version information is missing

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#885]
In the live demo, click on the Open MCT logo in the bottom-right, then scroll down to the "Version Information" section. This contains placeholders where one would expect to see version information injected during the build:

> * Version @@ version
> * Revision @@ revision
> * Branch @@ branch
> * Built @@ timestamp

**Comment by VWoeltjen** [comment]
Appears to be because the app is being run in-place; you can see the fully-built version at `/dist`, but the guided tour is not correctly-styled.

**Comment by VWoeltjen** [comment]
Possible workaround - add an option to app.js to have it serve static files from `dist` instead of (or in addition to) `.`

Want to require a command line flag to enable this to avoid interfering with usage in a dev env

**Comment by larkin** [comment]
Command line flag is great-- then we can use a Procfile to change the command line from `npm start` to `node app.js --special-flag-here` without having to make any other changes.
