### ISSUE TITLE
[safari] [tree] tree edit mode icon is strangely positioned

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#886]
Experienced this bug in Safari 9.1, do not see the bug in Latest Chrome.

![screen shot 2016-05-05 at 3 46 08 pm](https://cloud.githubusercontent.com/assets/226503/15059720/6f038c78-12d9-11e6-87d5-9830f1337bd3.png)

**Comment by charlesh88** [comment]
Closing, fixed.
