### ISSUE TITLE
[platform] clicking create doesn't hide create menu

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#888]
the tour instructs users to open the create menu by clicking.  It's odd that you can't close the create menu by clicking the create button a second time-- that's how start menu, mac menus, and other menus work.  You can close it by clicking elsewhere but it seems weird that it won't close just by clicking "create" a second time.

**Comment by larkin** [comment]
Similar: search type filter downarrow won't disappear by clicking the icon a second time.  As I follow the demo steps I find this weird.

**Comment by charlesh88** [comment]
Agree on both. Do you find this disconcerting enough that we should try to fix for the demo? My hope is it's not that distracting; when you click 'Next' both elements are dismissed.

**Comment by larkin** [comment]
If it's simple I'd say fix it, if it's a PITA don't fix it.  Considering the handler is `ng-click="toggle.toggle()"` you would think it would toggle, otherwise it's a badly named method.

(I imagine this is a 1 line fix for both instances).

**Comment by VWoeltjen** [comment]
Not positive, but think what's happening is the `click` on document is being detected, collapsing the menu, followed by `toggle.toggle()` getting evaluated, expanding the menu.

**Comment by larkin** [comment]
*yoink*

**Comment by akhenry** [comment]
Testathon 20160509 verified fixed

**Comment by VWoeltjen** [comment]
Testathon 20160509 verified fixed

**Comment by VWoeltjen** [comment]
Reopening per [comment](https://github.com/nasa/openmct/issues/1065#issuecomment-233478358); need to solve and verify this does not cause regression on #1065

**Comment by VWoeltjen** [comment]
Reopening, placing in Le Guin until triaged

**Comment by akhenry** [comment]
## Note for testers:
As well as verifying that the search menu works as expected, important to test for regressions to popup menu behavior generally.

### Search menu
1. Click the dropdown arrow next to the search field once. 
__Expected behavior__: Shows the search menu. 

2. Click the dropdown arrow a second time. 
__Expected Behavior__: Hides the search menu

3. While search menu visible, select some search options.
__Expected Behavior__: Search menu remains visible

### General Menu Behavior
* Menus generally should appear when button is clicked once, and disappear on a second click. 
* While menu is visible, clicking outside the menu should dismiss the menu
* While menu is visible, selecting a menu option should also dismiss the menu
* Examples of menus to test include the view selector (eg. changing between plot, fixed, and table views in panels), plot mode selector, the various toolbar options in fixed displays, and any other menus you can think of

**Comment by VWoeltjen** [comment]
Verified in testathon 20160808

**Comment by larkin** [comment]
verified fixed testathon 2016-08-08 in multiple locations.  Very happy!
