### ISSUE TITLE
[Time Conductor] Time conductor labels overflow edges

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#889]
Labels for the two handles of the time conductor overflow into the surrounding panes. Depending on contents of the tree and/or inspection area this may interfere with readability, and at minimum it's a little aesthetically funny. Desired behavior would be for these to be fit in the available space (either by making the text smaller, or leaving more space by making the bounds control bar a little narrower)

![screen shot 2016-05-05 at 4 07 29 pm](https://cloud.githubusercontent.com/assets/1685764/15059986/ad780e78-12db-11e6-884a-8a339b919c5f.png)

**Comment by charlesh88** [comment]
Related to https://github.jpl.nasa.gov/MissionControl/vista/issues/198

**Comment by VWoeltjen** [comment]
Verified in testathon 6/16/2016

**Comment by charlesh88** [comment]
Testathon 2016-06-16
Verified fixed.
