### ISSUE TITLE
[Live Demo] Consider removing 'unsupported browser' message from live demo

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#892]
It looks bad if someone hits the site in a modern browser, and our "next generation" web based mission control system tells them they're using an unsupported browser. It's a bit "Best viewed in Internet Explorer". Might also dissuade people from reporting issues.  Support for Firefox and Safari are pretty solid now in Open MCT. Edge is another matter - if anyone has a windows machine they can use to give it the once-over, that would be great.

Suggest we remove the warning and let people report issues that they find. Will be a useful exercise in crowd-sourcing our browser testing.

**Comment by larkin** [comment]
:+1: for removal. Didn't seem to prevent people from using other browsers in the first place and we have done a good job of fixing it.

**Comment by VWoeltjen** [comment]
I concur and have gone ahead and merged this (we can easily revert if we change our minds). 

While I definitely think this is the right thing for the live demo, I have some lingering doubts about this in WARP/VISTA. Is it worse at this point for those users to _possibly_ see Firefox-specific bugs without a warning, or to _certainly_ see an unsupported browser warning (with all that it connotes)? I'm not really sure.

@charlesh88 - what are your thoughts?

**Comment by akhenry** [comment]
My thinking is that with no warning, people *might* experience issues, but if they do, we want to be made aware of them. I believe people will be more likely to report issues without a browser warning. Otherwise they might think "I'm using an unsupported browser, so I won't report this issue".

**Comment by shobart** [comment]
Brought it up with Firefox, and I do not see the message.  Believe this to be verified now.
