### ISSUE TITLE
Can not build openmct with npm install

### ISSUE THREAD

**Issue by pacozaa** [nasa/openmct#895]
I got this error after run command 
`npm install`
![openmct](https://cloud.githubusercontent.com/assets/3154089/15064701/950cdf7a-1381-11e6-8c1b-ffbbaaec2b8c.PNG)

**Comment by VWoeltjen** [comment]
Looking at that log, I see that there was an error attempting to acquire FileSaver.js from GitHub. I've double-checked that the repo still exists, and that I can build openmct from a clean checkout.

Have you seen this error consistently? If not, this was probably a transient issue, and I'd recommend giving `npm install` another try.

**Comment by pacozaa** [comment]
@VWoeltjen  It works now. Thank you. 

One question
If I want to run the app just use `node app.js` right?

**Comment by pacozaa** [comment]
Just search around with full sleep and found this link
https://github.com/nasa/openmct/blob/master/docs/src/tutorials/index.md

Should it be guided on the [readme.md] (https://github.com/nasa/openmct/blob/master/README.md) by adding some link or mention a little bit?

Can I pull some request for this?
