### ISSUE TITLE
In the Live Demo, Time Conductor appears randomly

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#897]
Some objects display the Time Conductor (Mars Weather Display Layout), and some don't (Edit Display Layout Example). Is there a rationale here? All time-aware objects should display the TC.

**Comment by akhenry** [comment]
By design. Time conductor will only be visible in a layout that contains historical telemetry. The presence of the time conductor will actually prevent any real-time plots from working.

**Comment by akhenry** [comment]
@charlesh88 Can I close this issue?
