### ISSUE TITLE
[Timeline] Modifying child activity only marks immediate predecessor dirty

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#905]
eg.
Timeline
    |--- Activity 1
        |--- Sub Activity 1
        |--- Sub Activity 2

1. Edit Timeline
2. Drag-drop Sub Activity 2 above Sub Activity 1 to reorder them. 
3. Click on another object
4. Navigation will immediately change to the new object without user prompt about unsaved changes. This is because dirty checking does not check other children within the edit context.

**Comment by VWoeltjen** [comment]
Are there circumstances where this causes changes to be lost on a Save?

**Comment by akhenry** [comment]
@VWoeltjen Actually on closer inspection, this only affects #838

**Comment by VWoeltjen** [comment]
From sprint planning 5/16/2016, this is fixed in branch #838 now.

**Comment by akhenry** [comment]
Addressed by PR #838

**Comment by akhenry** [comment]
Note to testers:
* Modifying nested activities was not marking the parent timeline dirty, so test modifications to nested activities by reordering them etc.
* See original comment for basic test procedure

**Comment by charlesh88** [comment]
Testathon 2016-06-02
Verified fixed.
