### ISSUE TITLE
Resource Graphing of timeline not persisting state

### ISSUE THREAD

**Issue by RCarvalhoNASA** [nasa/openmct#908]
I'm working on a timeline in the stable version of WARP (Nobile May 2016).  I'm in edit mode, I select the timeline row in the table, click the button to have that shown in the resource graph.  It appears correctly while I remain in edit mode, but when I click save, it does not show in the view mode.

**Comment by larkin** [comment]
From Tagup 2016-05-10: Problem is that resource graph toggle state isn't persisted when changes are made in edit mode.  You can re-enable the resource graph while viewing a timeline, but the changes don't persist.

These changes should persist.

However, not considering a blocker for Herbert, moving to Huxley.

**Comment by RCarvalhoNASA** [comment]
20160531 Testathon verified as fixed
