### ISSUE TITLE
[Real-time Table] Sort order not applied immediately

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#910]
Steps to reproduce:

1. Create a Real-time Telemetry Table
2. Drag in a telemetry point known to update at 1Hz or less
  * Initially encountered this following steps to reproduce from #769
3. Allow a few rows of data to fill in.
  * But not enough to cause the table to scroll vertically. Once enough data has accumulated to cause a vertical scroll, issue cannot be reproduced.
4. Click the "Value" header to change sort order
  * It is easiest to see the issue if this click is timed just _after_ the last telemetry point displayed.
5. __Observe:__ Sort order does not immediately change.
6. Wait a moment for a new telemetry datum to arrive.
7. __Observe:__ _Now_ the sort order updates.

Expected behavior would be for this to have updated at Step 5, immediately after clicking the header.

Observed during testathon 20160509

**Comment by akhenry** [comment]
*interesting*. Good catch!

**Comment by VWoeltjen** [comment]
From tagup: May actually be failing to trigger a digest cycle generally; it's possible that the clock (and not the 1Hz data) is what's triggering the refresh. @larkin mentions having seen this fail to update to show the latest real-time datum in VISTA (which has no clock.)

**Comment by VWoeltjen** [comment]
Labeling as blocker since we suspect this may cause some data to fail to display (if there is a digest issue on real-time updates.) If, on investigation, we're confident this won't occur, we can remove the "blocker" label.

**Comment by VWoeltjen** [comment]
Verified testathon 20160512

**Comment by charlesh88** [comment]
Testathon 20160512
Verified fixed.

**Comment by akhenry** [comment]
👍
