### ISSUE TITLE
[Real-time Table] Redundant values appear

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#912]
Steps to reproduce:
1. Create a real-time table.
2. Drag and drop in a telemetry point that updates "quickly" (1Hz or so)
3. Drag and drop in a telemetry point that updates "slowly" (less than 1Hz, e.g. image telemetry)
4. Wait as a few updates arrive.
5. **Observe:** Whenever a new data point for the "fast" telemetry point arrives (every 1s or so), a row is added for that telemetry point (expected behavior), but a row is _also_ added for the "slow" telemetry point (showing the same timestamp/value as another row)
   - Over time, this results in _many_ redundant rows for the "slow" telemetry point

Expected behavior is that each distinct datum that arrives should immediately appear in exactly one row.

Observed during testathon 20160509

**Comment by VWoeltjen** [comment]
From tagup 5/10/2016: Resolving this would change the way we're using current telemetry API from tables. Since no incorrect data is displayed, want to defer work on this until telemetry APIs are revised (#811)

**Comment by larkin** [comment]
This is resolved with new table updates.
