### ISSUE TITLE
Timeline scroll bar location

### ISSUE THREAD

**Issue by RCarvalhoNASA** [nasa/openmct#913]
I'm working a rather large timeline in the stable production warp, and as I'm editing at the bottom of the available working space, and the horizontal scroll bar in the tabular pane is partially obscuring values that I'm trying to read.  See attached image
![badscroll](https://cloud.githubusercontent.com/assets/5769437/15130367/b5f03098-15fc-11e6-98f9-bdbc6dfe74e1.jpg)

**Comment by VWoeltjen** [comment]
From tagup 5/10/2016: Want to add some space here at the bottom such that scroll bars can go down far enough to display all data.

**Comment by charlesh88** [comment]
Testathon 20160531
Verified fixed.

**Comment by RCarvalhoNASA** [comment]
Now I see that the scrollbar has blank space to the left of it, obscuring the entire row rather than the partial row it was obscuring before.  However, there still is some blank vertical space between the scrollbar and the horizontal pane separator (from the Resource Graph Legend pane).  Could that be reduced?

**Comment by charlesh88** [comment]
It's not obscuring a row: now the bottoms of the all the containers are now aligned. I can reduce the space beneath the horizontal scroll element a little bit: that's actually used by the horizontal splitter bar as a grabable area so that you don't have to be precisely on the line to grab it.

**Comment by charlesh88** [comment]
And I just noticed that  with my latest fix the problem happens in reverse when you expand the tabular left pane far enough that the scrollbar goes away. Sigh.

**Comment by charlesh88** [comment]
Work in progress in branch timeline-913a.

**Comment by charlesh88** [comment]
This should address Robert's comments from the last round. PR filed with #995.

* Scrollbar now always visible in Timeline tabular right area
* Splitters tightened up to take up less space

**Comment by charlesh88** [comment]
Testathon 2016-06-16
Verified fixed.
