### ISSUE TITLE
[Usability] Allow user to view an item from the left pane while editing

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#928]
When editing, a very common observation is users single-clicking an object in the left pane (both browse tree and search) and being taken out of Edit mode, or being warned with the "Unsaved changes" dialog. What they want is to be able to see an object before adding it to a thing they're currently editing. 

Proposed solution: 
- Single-clicking in the left pane during Edit mode displays the clicked object in an overlay without taking the user out of Edit mode. 
- All normal "view" functionality (like plot pan/zoom) would be available. 
- There should be a "Add This Item" button available in the overlay as well that would add the item being viewed to the object being edited, then closes the overlay.

**Comment by larkin** [comment]
:+1:

**Comment by larkin** [comment]
Can we prototype this in Huxley and get some hands on feedback with it before committing to it?  Might be more valuable that way.

**Comment by charlesh88** [comment]
I've uploaded a [sketch for this](https://drive.google.com/a/nasa.gov/file/d/0B0v27OM1JkSeR001RFJZMk43QVk/view?usp=sharing): checkout page 9.

There are some points of discussion. As always, poking at as many cases as possible; we can very probably pick an initial set of stuff to support to sidestep some of these issues. 
* All view manipulation functionality (pan/zoom in plots, filter in tables, etc.) should be available. 
* Actions that would result in editing should not be available - this may mean blanket suppression of context menus when an object is viewed in this manner.  
* We may want to support navigation, mostly to allow a user to click on a folder. 
 * Navigation should be supported here with the same restrictions imposed on the tree while editing an object. There _shouldn't_ be a way that the user could navigate to the object they are currently editing, but we should ensure this is the case. Otherwise, we will have to filter clicks on type in the tree, which will cause confusion to the user. 
 * If the user is allowed to navigate within the overlay, then the Add functionality would need to support adding the current object in view, not just the one that the user started with.

**Comment by akhenry** [comment]
Another option to consider here is removing the restriction on viewing and even editing other objects while in edit mode. Make the save button application-wide rather than associated with a particular object. User can edit whichever objects they like, navigate to other objects, edit them, etc. Dirty objects will be visually marked as dirty in the UI. When they're done, they hit save, and all dirty objects are persisted. No need to build new user interactions, can keep using the existing ones.

The main problem I see is edit collisions. The longer we allow people to have unsaved changes the higher the likelihood of collisions - which is an argument for doing away with edit mode altogether and making every change a live change (with the addition of undo) ala Google Docs (everyone can see everyone else's edits in real-time).

**Comment by charlesh88** [comment]
I like a lot of the comments here. "Always edit" could be very attractive from the standpoint of making the interface much more organically usable - users just do what they need to do and the interface supports that. The biggest problems that I see with this have been the following:

- People mistakenly change things they didn't intend to, and can get fearful about interacting with objects. To counter this:
 - The ability to lock objects, probably coupled with permissions. 
 - Really good undo. This is essential.
 - File revisions (ala Google Docs).
 - As has been said, collision prevention.
- We have a limited number of gestures when interacting with a given object. In some cases, like manipulating plots while browsing, keyboard modifiers will very probably play a role. Including editing at the same time potentially adds more gesture overhead we'd have to deal with. Solution here would be to take a deeper look at a good use case (like telemetry) and map out the gesture space.

**Comment by charlesh88** [comment]
Sketch done in UI sketches v2.1.7, needs to be published.

**Comment by larkin** [comment]
If anyone looking to contribute to this help-wanted issue has questions, please mention @charlesh88

**Comment by larkin** [comment]
@charlesh88 To attach screenshot and unassign.

**Comment by charlesh88** [comment]
Screen cap of UI sketch: 
![screen shot 2016-10-25 at 11 23 16 am](https://cloud.githubusercontent.com/assets/1056412/19698779/814b4ec6-9aa5-11e6-97db-ad686a307a26.png)

**Comment by larkin** [comment]
jay re-requested while reviewing demo site.

**Comment by charlesh88** [comment]
This is related to #1838 and would help a lot with that issue.

**Comment by charlesh88** [comment]
This has been implemented as part of @dtailor90's work on the Notebook re. #1947.

### Testing notes:

1. Right-click on a tree item and select "Preview" from the context menu, or
1. Edit an object that has an editing UI, like a layout or plot view. Left click any object in the tree (other than one that is locked as currently being edited).
1. In both cases above, you should see the selected object in a "large view" overlay. Clicking the Done button dismisses that view.

**Comment by psarram** [comment]
Verified in Testathon 3/30/18.
