### ISSUE TITLE
[Table] Allow CSV export of table contents

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#934]
It should be possible to export the realtime data from a realtime table. Currently, the export as CSV uses a historical query to export data instead of exporting the realtime data it has received.

More generally, there should be a user gesture to allow export of all data contained in a Table view (Historical or Real-time). Design pending (discuss with @charlesh88)

**Comment by charlesh88** [comment]
I believe we currently support a context action on the object that allows export. This would be available in the label context menu in the title of the object (in the main view area and as a framed element in a layout), and from the tree. 

If possible, we could increase discoverability by including an Export button in the view area when the table is selected, perhaps in a similar format and next to the Edit button. This button would appear in both Browse and Edit modes.

**Comment by VWoeltjen** [comment]
There's an "export the data I'm currently looking at" use case which I think is different from the "export all data for this object within the time conductor bounds" use case that we currently support with the Export Data action.

From the perspective of the first use case, the shortcomings of the current action are:

* Real-time data is not reflected (esp. when no history is available)
* Table sort order, column selection, and filters are not reflected

My expectation would be that there would be a separate action (initiated from the table) to satisfy this use case. Are you instead saying that the existing Export Data should behave differently?

**Comment by charlesh88** [comment]
Ah hah, wasn't aware of the difference. Ideally we would do this:
* Export from a tree object would be in the context of the current Time Conductor bounds.
* Export from a view would utilize that view's time bounds, plus filtering, sorting, etc. and include all data (historic, RT or a mixture) that matches the view's filter criteria. Whether the view is synced with the Time Conductor at the time of export doesn't matter to the export. 

I would call the actions two different things: the first could be "Export Data" and the second could be "Export This View's Data" or something to that effect. On the second action, do we ever have a pagination case where there is more data than can be displayed given current filter settings? If so, my expectation would be that all data matching the current filter settings would be exported, regardless of client-side display limitations on our part.

**Comment by larkin** [comment]
> My expectation would be that there would be a separate action (initiated from the table) to satisfy this use case.

This is my expectation too.  I think a really basic implementation would be a good starting point-- just exporting whatever is currently visible in the table (based on filters/etc).  Handling the pagination and other problems is going to require additional work (some of which is already slated for telemetry API) and probably out of scope at this time.

**Comment by charlesh88** [comment]
Testathon 2016-06-16
Verified fixed.

**Comment by VWoeltjen** [comment]
Verified testathon 2016/06/16
