### ISSUE TITLE
[Layout] Items in a layout cannot be dragged by the top part of the frame.

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#935]
Possibly related to fixes for #836.

When attempting to drag an object within a layout to reposition it, the natural tendency is to click and drag on the top part of the frame. Currently the object label prevents this from happening because it does not appear to be responding to the drag gesture. 

To reproduce:
1. Open or create a layout with at least one object in it
2. In edit mode, click and drag to move the object around the layout. Dragging at the top of the frame is unresponsive, but the rest of the frame works ok.

**Comment by charlesh88** [comment]
Testathon 20160531
Verified fixed.

**Comment by VWoeltjen** [comment]
Verified fixed testathon 20160531
