### ISSUE TITLE
[Table] Support URL telemetry type

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#947]
Support URL telemetry types from Real-time and Historical tables. When this type is present, a Download button should be displayed in the relevant column.

This is an approach to supporting Data Products in a manner which can later be unified with our existing Image support. (Images are really a specific type of data product.)

**Comment by larkin** [comment]
@VWoeltjen I am concerned about generalizing support for data products at this time.  Straight-to-open-source doesn't give us an opportunity to prototype or get user feedback in a reasonable timeline.  Would rather we do a minimal implementation and get it in front of users ASAP to validate our ideas before we spend too much time on them.  Also-- we don't have the metadata we need to support this approach right now.  (There's no dictionary that defines what data products are available).

**Comment by VWoeltjen** [comment]
Good point; moved this out to the next sprint, we'll see if this still looks like the right approach after implementing more basic support and getting some user feedback.

**Comment by larkin** [comment]
Calling wontfix for now, can reconsider later.
