### ISSUE TITLE
[Code Style] Allow variable shadowing

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#953]
@larkin [comments](https://github.com/nasa/openmct/pull/927#commitcomment-17581568):

> I think disabling shadowing is a little restrictive with minimal benefits-- in the rare cases it occurs you would have to invent some interesting variable names or break other style rules (e.g. abbreviating). And I haven't seen any code break due to it. I also think that some of the risky edge cases of shadowing shouldn't exist as other parts of our style guide should prevent them from occurring.

w.r.t. the "risky edge cases", there are jshint options for [maxstatements](http://jshint.com/docs/options/#maxstatements) and [maxdepth](http://jshint.com/docs/options/#maxdepth) that would cover at least some of these (cases where context is lost due to function length and it becomes unclear that a variable has been shadowed)

(Filing as a new issue since #927 has been merged.)

**Comment by akhenry** [comment]
> restrictive with minimal benefits
I dunno, I feel like a lot of linting rules fall into this category if considered in isolation :) But collectively they make the code more robust and comprehensible. Variable shadowing immediately introduces ambiguity into code and contributes unnecessarily to the cognitive load on developers trying to parse it.

**Comment by larkin** [comment]
Ok, As it stands, let's leave this as configured.  It's hard to envision a case where you really want variable shadowing.  Should we start to see real downsides to this rule we can re-evaluate then.  For now I will close this.
