### ISSUE TITLE
Time conductor not visible

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#957]
Reproducible in master:

1. edit main.js and add './platform/features/conductor/bundle' to the bundle list
2. load openmct
3. navigate to a telemetry object that should show time conductor
4. observe that time conductor is not visible any more.

I'm wondering if this is due to changes in the order that representers are instantiated / refreshed?

Sending to @VWoeltjen or @akhenry for research.

**Comment by VWoeltjen** [comment]
This was introduced in #942 

Think simplest thing will be to revert 20ecf168f238b9a4b2341508650f4b573bfd4f0b, and find another solution to #908

**Comment by larkin** [comment]
@VWoeltjen Sounds good.
