### ISSUE TITLE
Fix minimum width in Timeline Gantt bars

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#965]
There is currently a minimum width issue with Timeline and Activity elements: they can't get small enough. This may be a CSS problem. Elements should be able to be scaled to a minimum width of 1 or 2 px. We may need to disallow click/drag actions unless an element has sufficient width TBD.

**Comment by charlesh88** [comment]
PR filed, closing with unverified.

**Comment by charlesh88** [comment]
Testathon 20160531
Verifiied fixed.

**Comment by VWoeltjen** [comment]
Verified fixed testathon 20160531
