### ISSUE TITLE
App crashes into restart on mobile with very large object trees

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#969]
Seen in VISTA at https:///mcws/clients/vista/

Go to any pre-existing object and select it in the tree, even a folder. Wait about 30 seconds, then observe: the app will crash, and reload to the Start screen. This will continue in an ongoing cycle. @larkin thinks is due to an out-of-memory error possibly due to search continuing to index. 

Note that this is happening in .../mcws/clients/vista/ where there are a great number of objects in the tree; this can't be duplicated in .../mcws/clients/vista-msl/ for example. Have not tried to recreate this in openmct.

Although this results in loss of data, not filing as a blocker due to mobile-only nature of the problem.

**Comment by akhenry** [comment]
Doing some cleanup. Am going to close this issue, as we have an entirely new code-base since this was filed. We can reopen if we find this issue in future testing.
