### ISSUE TITLE
Nav-to-parent arrow is showing while in Edit mode

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#970]
<img width="484" alt="934 nav-to-parent visible" src="https://cloud.githubusercontent.com/assets/1056412/15587617/f5a60358-233e-11e6-977e-06d33af43842.png">

Nav-to-parent should be hidden while in Edit mode.

**Comment by charlesh88** [comment]
Testathon 20160531
Verifiied fixed.

**Comment by VWoeltjen** [comment]
Verified fixed testathon 20160531
