### ISSUE TITLE
[Timeline] Zoom with scroll wheel

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#971]
From #936. Allow user to change zoom level in a timeline using the scroll wheel. This would need to be in conjunction with a modifier key, such that normal scroll bar behavior continues to work as expected.

**Comment by larkin** [comment]
Hrrrrm... I would say "no."  And then I'd look at priorities and say "figure it out months/years down the road".

**Comment by TypicalFooBar** [comment]
I have written a directive that can handle zooming for the Timeline with the mouse wheel.

```
define(
    [],
    function() {
        function MCTZoom() {
            function link(scope, element, attrs) {
                // Bind to the mouse wheel scroll event
                element.bind("DOMMouseScroll mousewheel onmousewheel", function(event) {
                    // Do not propagate this event further
                    event.stopPropagation();

                    // If the shift key is clicked
                    if (event.shiftKey) {
                        // Determine the direction the mouse wheel was turned
                        var zoomDirection = event.wheelDelta > 0 ? -1 : 1;

                        // Call the zoom callback in order to perform the zoom in the controller
                        scope.zoomCallback({arg1: zoomDirection});
                    }
                });
            }

            return {
                // Applies to attributes
                restrict: "A",
                // Add the zoom callback to the scope
                scope: { zoomCallback: '&mctZoomCallback' },
                // Link using above function
                link: link
            };
        }

        return MCTZoom;
    }
);
```

At first I used this directive on the entire top-right pane, but when the shift key is clicked and the mouse wheel is turned it will sometimes move the entire webpage left or right. I can get a video of this to show you if you'd like.

If I use this directive on _just_ the tick-mark portion of the timeline (not the part with the swimlanes), then it works just fine with the shift key. It works exactly the same as if you had pressed the **+** or **-** buttons. I could also _not_ do the check for the shift key and then you'd be able to scroll-zoom at any time just by hovering over the tick-mark portion of the timeline - it felt quite nice, actually.

Using this directive is a quick and easy way to get the scroll wheel working on the timeline for zooming in and out. That said, it would be so much nicer if the timeline were zoomable just like the Timeline portion of the Chrome dev tools - zooming to mouse in the Chrome dev tools is so intuitive and functional and I think it would be ideal for this timeline as well. Click-and-drag to move the timeline left and right is also very helpful in the Chrome dev tools timeline. I'm guessing it would be quite a bit of work to get the nice zoom to cursor working correctly and I don't know if that's wanted for this issue.

So, my ultimate question is - would using this simple directive on the tick-mark portion of the timeline (not the swimlanes), either in conjunction with the shift key or not, to make zooming in or out possible with the scroll wheel just as if you had clicked the **+** or **-** buttons resolve this issue? If so, I'll make a pull request for it. Alternatively, the scope of this issue could expand to include a more robust zooming system on the timeline (but maybe that's partially what issue #936 is about).

Let me know what you think.

**Comment by VWoeltjen** [comment]
Thanks for looking at this; I think that using the directive described is the right approach. I'm curious to know what the root cause of that whole page moving is.

@charlesh88 - what are your thoughts on the various options above, from a UX perspective?

**Comment by charlesh88** [comment]
Hi, really sorry it's taken me a while to get to this. We'd really like to have mouse zooming and drag panning in the Timeline, here's my thoughts on the UX:
- Zooming: an unmodified mouse wheel gesture is used to scroll in window ports with scrollable elements. Alt-mouse wheel make sense to me, and we should center the zoom on the cursor position. 
- Panning: we use alt-click and drag in plots to enable panning. If we could re-use that same gesture in Timelines that would be best.

Thanks so much for the time and attention to this feature.

**Comment by charlesh88** [comment]
Refers to old deprecated feature (Timeline) so closing.
