### ISSUE TITLE
[Export] Style tabular Export button

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#973]
Based on work done in #934 that now displays an Export button, style it so it lays out well in a variety of contexts:
* Main view: Force the top of the table down, and add a toolbar row above the table header and put the button there.
* In a frame in a layout: hide the button until the user mouses over, then float it above the table with a glow/dropshadow to offset it, similar to the reset button in plots.

**Comment by charlesh88** [comment]
To verify: 

1. Make a Real-time or Historic Table. Note that there is an Export button with icon in the upper left of the view.
1. Save your table, then add it to a Layout. Save the layout, and exit edit mode. Nav to the layout and observe that when hovering over the table in the Layout that the table animates down a little bit and displays a small Export button.

**Comment by charlesh88** [comment]
Testathon 2016-06-16
Verified fixed.

**Comment by akhenry** [comment]
@charlesh88 Assume that the absence of the button when layout is in edit mode is intentional? If so, verified fixed.

**Comment by VWoeltjen** [comment]
Verified in testathon 2016/06/16
