### ISSUE TITLE
[Navigation] Move orphan navigation handling to SaveAction

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#975]
As described in comments on #951, move orphan navigation handling from a general-purpose handler to the SaveAction specifically.

This is contingent on #408, as persistence failures need to bubble up sufficient for SaveAction to detect this situation and address it. Additionally, persistence queue will need to reject persistence-related promises when a user chooses Discard.

**Comment by larkin** [comment]
Closing this as I think this is not-an-issue long term.  We won't have orphan navigation after we fix persistence error handling.
