### ISSUE TITLE
[Timeline] Tick marks disappear at high zoom levels

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#996]
Steps to reproduce:
- Create a timeline starting on day 3, with at least another day of duration.
- Zoom in until tick labels are 1 or 2 seconds apart
- Scroll all the way to the right
- **Observe**: Tick marks end unexpectedly. At highest zoom levels, these end before timeline begins.

Expect to see tick marks continue to both extremes of the scrollable area, and to be able to reach any point in the timeline by scrolling.

![timeline-tick-bug](https://cloud.githubusercontent.com/assets/1685764/15787908/acdddc22-2979-11e6-8b29-cd84d0b3ae8c.png)

**Comment by VWoeltjen** [comment]
Doubt we would see this interfere with actual use; do not know of any use cases where these zoom levels would be needed, particularly for a timeline of this duration.

Observed using testathon build for 20160603

**Comment by charlesh88** [comment]
Not just the ticks, but the labels as well. Could this be due to some right-side "padding" that you introduced to allow the extents zoom?

**Comment by charlesh88** [comment]
My Timeline and its Activity (both starting at day 3) aren't visible at that zoom; in fact, I just can't scroll far enough to the right to bring them into view. Ticks end at 001:22:36:09. Zooming out just one level brings everything back.

**Comment by VWoeltjen** [comment]
Think that we're bumping into a browser limitation here; the `width` property being set here is being specified as `4.074e+07px`, but the computed pixel width is `33554400` (2<sup>25</sup> - 2<sup>5</sup>). This looks like the [browser's maximum](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwijq4nYwIzNAhXG1CYKHb5nDxUQFggdMAA&url=http%3A%2F%2Fstackoverflow.com%2Fquestions%2F16637530%2Fwhats-the-maximum-pixel-value-of-css-width-and-height-properties&usg=AFQjCNEvca9dNTL--EJP7YG04GpfNcc6JQ).

I see two approaches to address this:

1. Limit the maximum zoom based on predicted pixel width. This could get tricky, as timeline duration can change during editing (if someone Adds an Activity far to the right, a previously "safe" zoom level could exhibit this issue.)
2. Do some "infinite scroll" kind of thing where the physical width of those elements never exceeds some maximum. (This has the effect of changing the way the scroll bar behaves, which has a usability impact.)

Particularly in the absence of a straightforward fix, I'm still inclined to say we shouldn't worry about this unless we see it interfering with actual use cases.

**Comment by charlesh88** [comment]
This has been fixed.
