### ISSUE TITLE
[Timeline] See flashes during zoom

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#997]
Timeline tends to "flash" briefly during zoom, showing some other region of the timeline before recentering.

Believe this is due to adjustment of scroll position on a timeout from #994. Simple fix would probably be to set the scroll during _and before_ the timeout (would still see flashing in cases where scroll position gets undesirably clamped, but only in those cases)

**Comment by VWoeltjen** [comment]
This issue is primarily aesthetic, but is a little annoying. Think the fix should be trivial so placing in Kress, will want to move out if this is non-trivial

**Comment by VWoeltjen** [comment]
Observed using testathon build, 20160603

**Comment by charlesh88** [comment]
How about we set `t-swimlanes-holder l-swimlanes-holder` and `l-graphs-holder` to opacity: 0 while we're doing the pan and zoom, then remove that when we're done? I can create a class for this; we have .hidden but that uses display: none which would probably have undesirable effects.

**Comment by charlesh88** [comment]
Also seen during Testathon 2016-06-03

**Comment by charlesh88** [comment]
Testathon 2016-06-16
Verified fixed, looks great!

**Comment by VWoeltjen** [comment]
Verified in testathon 2016-06-16
